### ISSUE TITLE
Macro recording not work as intended

### ISSUE THREAD

**Issue by jinkazama82it** [Ryochan7/DS4Windows#1000]
Yesterday I tried to record macro for a single and multi action button but key on keyboard are recognized with wrong value, for example the left alt is recognized like system (?!) button and this makes it impossible to create the shortcut you need.
I don't know if other key are wrongly recognized but probably yes.

**Comment by mika-n** [comment]
Jep. There is something weird how WinOS reports the left ALT key up/down events to DS4Win app. Maybe localized keyboard layout has something to do with it? I have Finnish/Swedish keyboard layout and it is a bit different than US layout.

Anyway. When I press "left ctrl + left alt" keys then DS4Win recognizes LeftAlt key up/down events (plus left ctrl). Then I can simply remove those extra LeftCtrl key events from the recorded macro sequence and leave just LeftAlt events there. This is one workaround to this issue Does this trick work with your keyboard layout? What kind of layout you have?

All other keys seem to be recognized just fine here.

**Comment by jinkazama82it** [comment]
Italian layout, but before v 2.03 no issue with macro recording so probably something goes wrong during the move to the new version.
I'm not sure if the the issue is present even on v 2.00 or later but in latest version before 2.00 i haven't noticed any issue related macro recording.

**Comment by Ryochan7** [comment]
WPF handles Alt as a special case. Reports on StackOverflow show that correcting this error should be a one line fix.

**Comment by mika-n** [comment]
I just fixed this. Was about to create a pull request.
