### ISSUE TITLE
DS4Windows v.2.0.3 doesn't minimize to tray

### ISSUE THREAD

**Issue by LEAMMO** [Ryochan7/DS4Windows#1008]
Since I updated to the latest version the program doesn't seen to be able to minimize itself to tray. Even with Start Minimized + Minimize to Taskbar + Close Minimizes it stays in the taskbar.

I've:
Restarted PC
Redownloaded
Switched between Run as Admin and normal
Switched betwen Task and Program (although since redownload it doesn't let me switch to Task)

Help appreciated :)

**Comment by S-trace** [comment]
Could you please tell more about your OS?
I'm using W10v1909b18363.535 (AMD64), and DS4Windows 2.0.3 minimizes to tray without any problems.

**Comment by LEAMMO** [comment]
> Could you please tell more about your OS?
> I'm using W10v1909b18363.535 (AMD64), and DS4Windows 2.0.3 minimizes to tray without any problems.

Hey, I'm using: 18362.535
http://prntscr.com/qjnbj0

**Comment by Tiberiusmoon** [comment]
You have to untick the minimise to taskbar and tick Start minimised

**Comment by LEAMMO** [comment]
> You have to untick the minimise to taskbar and tick Start minimised

It solved the problem, but still it's weird that having both options ticked it would default to NOT go to tray.

Correct it?

**Comment by Ryochan7** [comment]
Personally I would find it weird if it did minimize to the tray in that case; the behavior was wrong in some previous versions before it was corrected. They are related options but they cover to different aspects of behavior. "Start Minimized" just tells DS4Windows whether to minimize the app or show the main window at launch. "Minimize to Taskbar" tells the app where it should be minimized.
