### ISSUE TITLE
Button did not work

### ISSUE THREAD

**Issue by PizzaRules668** [Ryochan7/DS4Windows#1010]
When I set the the down button to Ctrl it did not work when I when I set it to a different PS4 button it did not work.

**Comment by mika-n** [comment]
Now I must admit I didn't quite follow what you described. 
What down button? LS/RS stick down or beyboard arrow down key or dpad down button in DS4 gamepad?
How you set it? Re-mapped as keyboard key or another DS4 button?

Please see Troubleshooting doc page for more info what information to provide at minimum (DS4Windows app version, WinOS, gamepad type, Logs logfile content if errors, profile file if issues with profile setup etc)
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting

**Comment by PizzaRules668** [comment]
Now both joystick are out saying they are being aimed to the left, and makes it very hard to play KSP.
Is they a way to reset them?

**Comment by mika-n** [comment]
Do you mean that LS and/or RS stick are constantly drifting to left even when you are not touching the stick? 

That is "normal behavior" of some gamepads and the solution is to set big enough deadzone option to LS or RS stick. See the following doc page.
https://github.com/Ryochan7/DS4Windows/wiki/Settings#deadzone

The "normal" means that LS/RS stick (and gyro axis) is never completely stable in a hardware level and sometimes it doesn't return to exactly the same center position when you release it. If LS/RS axis configuration has zero deadzone value then this "not returning to the same center position" or "woppling" of a stick is seen by a constant drifting to some direction. This issue may become worse over time when springs in the LS/RS stick wear out or dust gets in. This is not DS4Windows app issue, but a hardware level issue. The solution is to set a small deadzone to LS or RS stick to make sure that when stick stays inside of certain radius from center position then it is interpreted as "center resting position" and not as stick movement.
