### ISSUE TITLE
(v2.0.3) opens... then closes.

### ISSUE THREAD

**Issue by nr1995** [Ryochan7/DS4Windows#1012]
Since updating to v2.0.3 (from v2.0.2 and v2.0.1),
DS4Windows just opens... waits a second... then closes.
It didn't do this in v2.0.2.
And I haven't touched my RTSS since before DS4Windows was even v2.0.0.
I haven't even opened RTSS for a few months.  I saw someone else mentioned it.
Could it be something to do with Steam?

**Comment by Tiberiusmoon** [comment]
Try closing steam then reopen DS4 and see if it still happens. (or try closing one app at a time and see which one prevents DS4 from opening)
Reply back with the results. :)

**Comment by nr1995** [comment]
It had nothing to do with Steam,
it was because the controller was plugged in but not turned on.
Unplugged and bluetooth-connected, everything is fine.
Unplug, connect bluetooth, replug, open DS4, same problem again.

**Comment by mika-n** [comment]
What do you see in "%APPDATA%\DS4Windows\Log" logfiles when you re-cycled the gamepad connection? What kind of gamepad you have? Official Sony DS4? 

Here DS4 gamepad works just fine even when I at first connect it over BT and the "hot re-connect" it using USB cable. DS4Windows app recognizes that it is still the same physical gamepad.

There is a logic in DS4Windows app to recognize when the same physical gamepad is "hot re-connected" using USB cable while it was already connected over BT. This identification is based on the ID address of gamepad device (xx:xx:xx:xx:xx:xx value). Some 3rd party gamepads don't support real ID/MAC addresses, so the ID is runtime generated based on the connection port. This ID may be different for the same gamepad if it is connected over USB or BT (or even connected to different USB ports). Maybe your isssue has something to do with this? When you connect the gamepad using USB (without first using BT) then is the ID same as when you connect the gamepad over BT (without using usb)?

**Comment by whitestar127** [comment]
Hi, I'm getting the same error. It opens up, then just closes a few seconds later and the light on my DS4 starts to blink red.
It seems to be something to do with MSI Afterburner and/or RTSS. When I close Afterburner everything works fine. No errors while using Steam.

**Comment by mika-n** [comment]
I just made a note of this problem in Troubleshooting wiki page:
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting

Seems like other apps and users are having the same issue with MSIAfterburner/RTSS with D3D/WPF applications. Don't know if the latest version of thos apps fixes the issue. At this point it seems that the bug is in MSIAfterburner side and not in DS4Windows app side.
https://forums.guru3d.com/threads/afterburner-rtss-is-crashing-occt-on-some-setups.428644/


If there are any config tweaks/overlays features in MSIAfterburner/RTSS then try closing those options one by one if there is some specific feature causing the issue (d3d injection is like walking on thin ice).

**Comment by whitestar127** [comment]
Thanks for your work on this, mika-n.
I'll test the reset RTSS cache solution when I get home.

**Comment by whitestar127** [comment]
It works!
Well, at least for me it worked. Here's what I did:

1. Exit DS4Windows
2. Open RTSS window
3. Click **[Setup](https://i.imgur.com/awLJ0On.png)** and go down to the bottom of the **General** tab
4. Click **[Reset cache](https://i.imgur.com/T7qCQsv.png)**
5. Start DS4Windows again

Good luck! :-)
