### ISSUE TITLE
Forza Horizon 4 issue with the right stick

### ISSUE THREAD

**Issue by bd2k9** [Ryochan7/DS4Windows#1014]
I'm having a problem with Forza Horizon 4. The right stick (which controls the camera), tilts to the left. I've opened the new version of the software and I noticed that both sticks are a lot more unstable than they used to be.

Is there a way to change the sensitivity of both?

**Comment by mika-n** [comment]
See the following post about LS/RS deadzone setting. Check the LS/RS deadzone in a profile settings.
https://github.com/Ryochan7/DS4Windows/issues/1010#issuecomment-571215900

**Comment by Ryochan7** [comment]
Old profiles from the Jays2Kings build have slightly different behavior with this build. The old implict deadzone for the sticks is gone. Anything beyond absolute center will send output when using a 0.0 deadzone.

Newly created profiles set an explicit deadzone and also anti-deadzone for use in games using XInput. Make sure to set a deadzone on LS and RS around 0.08 to start. You can then adjust based on personal preference.

**Comment by bd2k9** [comment]
Weirdly enough, after I set up the dead zone to 0.35 (the calibration was terrible), the controller calibrated by himself. Both of them are a lot beter right now. Not at 100% stable but very close. Thanks.
