### ISSUE TITLE
Cemu 1.16.1 issue playing Zelda:BotW

### ISSUE THREAD

**Issue by GrammerPro33** [Ryochan7/DS4Windows#1015]
JayKings version used to work fine on Cemu 1.16.1 and the game but obviously without gyro support. Upon update to the forked version provided here, the controller works but ingame the left and right sticks on my DS4 v1 controller seem to be moving on their own very slowly which basically makes the game unplayable. Any suggestions why this could be happening? Padtest doesn't show any gyro issues with  the controller itself.

**Comment by Tiberiusmoon** [comment]
Have you tried playing with the dead zones of the joysticks?

**Comment by GrammerPro33** [comment]
fixed by deleting default profile and relaunching ds4windows. Old ds4windows default profile seemed to mess with the settings
