### ISSUE TITLE
[Feature Request] Move Hide DS4 to Profiles

### ISSUE THREAD

**Issue by SiTWulf** [Ryochan7/DS4Windows#102]
One idea, you can please move the Hide DS4 option to profiles, for example for make a Xbox 360 Profile and a DS4 Real Profile, and change profiles with Auto Profiles.

Thanks!

**Comment by Ryochan7** [comment]
This has somewhat been discussed before but nothing has come of it. Disabling exclusive mode for a controller should probably be implemented at some point along with being able to retry grabbing exclusive mode access. It would probably help for the few games that support the DS4 natively.

The closest functionality that is in DS4Windows currently is the "Turn off DS4Windows Temporarily" option in Auto Profiles. That way, you can use the native real DirectInput DS4 controller as opposed to using a virtual Xbox 360 controller for the few games that support the DS4 natively. There is nothing in place to emulate devices other than the Xbox 360 controller and KB+M so remapping could not be done when using a DS4 Real Profile.

**Comment by SiTWulf** [comment]
@Ryochan7 
I check your indications and Works like a Charm!...
Now i can define what games use a Native DS4 or Xbox360...

Thanks!
