### ISSUE TITLE
Auto profile: "Turn off DS4 temporarily" does not work as it should.

### ISSUE THREAD

**Issue by Tiberiusmoon** [Ryochan7/DS4Windows#1020]
[export.txt](https://github.com/Ryochan7/DS4Windows/files/4032156/export.txt)

So by the looks of things the app would turn off when x program is not detected.
Then when you click the x program to turn DS4 back on it would use the default profile rather than the profile it was set out to detect.

In my case on line 2 of the export.txt i clicked the OW program to trigger the profile to use.
After loading the profile accordingly the DS4 restarts but then loads a default profile instead.

If i understand the "turn off DS4 temporarily" function right, it should not do this it should run the profile it was intended to use from auto profiler originally.

Having the app use the last used profile universally could work as a solution or section of code to specify saving the last used profile for auto profiles only.

(Now i know why i was having trouble with auto profiles earlier x.x)

**Comment by mika-n** [comment]
Okey. I will test this scenario, but could be that after re-starting DS4Win app through auto-profiler it might accidentally revert back to default profile. I will test this but sounds like a bug in auto-profiler.

**Comment by mika-n** [comment]
Just committed a change to fix this "temporarily turn off" auto-profiler bug. Now a new profile is correctly loaded and activated when system is waking up from tempOff state and the service is not accidentally turned on when auto-profiler detects an unknown process (if the new "Revert to default profile on unknown process" option is not enabled)..
