### ISSUE TITLE
Suggestion: Special DS4 hotkey

### ISSUE THREAD

**Issue by Tiberiusmoon** [Ryochan7/DS4Windows#1022]
What if the PS button was able to turn DS4 on or off?
A option to turn on DS4 in the settings by pressing the PS button for X amount of seconds.
A second option located in the special actions menu of the profile to turn off DS4 for X amount of seconds.

The latter seems doable but i dont know if DS4 can detect certain inputs while in a stopped state.

**Comment by mika-n** [comment]
Yes, would be technically possible. In theory DS4Windows app could open a shared connection to the physical gamepad while the app is in stopped state but there is a macro set to wake up the app on key presses. But I think that "almost" the same thing can be done by using a profile with "Use DInput Only" option enabled. This option skips the creation of virtual output driver and opens the physical gamepad interface in shared mode.  Macros and keyboard/mouse re-maps are available in "Use DInput only" mode (ds4 gamepad key re-mapping is not available), so there could be a LoadProfile macro to load another profile without UseDInputOnly option when the DS4Windows app should wakeup and do its magic again.

But as mentioned earlier anything relating "dynamically" stopping and starting DS4 gamepad works only in USB and SonyWA connections. BT connections have the "dead BT hid device" problem and the dead device comes back alive only after disconnect/re-connecting the BT connected gamepad.

By the way. Now when you are testing and experimenting how to "dynamically" stop and start DS4Windows app then have you seen the cmdline interface? It is possible to stop and start DS4Widnows app programmatically from a 3rd party app or cmdline script. Although I have to admit that I haven't got around to test this cmdline interface in V2.x version, yet.
https://github.com/Ryochan7/DS4Windows/wiki/Command-line-options

**Comment by Tiberiusmoon** [comment]
I didnt know it had a CMDline interface or how to bring it up.
Maybe using the controllers status as a check for such connections could help with handling this?

I don't have wireless functionality on my razer raiju so i don't have much experience with wireless interactions on DS4.

**Comment by mika-n** [comment]
Closed because there is now a new "DS4WindowsCmd.exe" tool and new cmdline options available to query the status of a gamepad and profiles and the app. Using these cmdline options a custom batch file can do pretty much "everything" (query status/stop/start/change profiles/etc).
https://github.com/Ryochan7/DS4Windows/wiki/Command-line-options
