### ISSUE TITLE
[BUG] Macro record error

### ISSUE THREAD

**Issue by zus0** [Ryochan7/DS4Windows#1024]
So, when I try to press LAlt on my keyboard (164), program records 0 and macros don't work

**Comment by mika-n** [comment]
#1000  see the linked issue. This problem with LeftAlt (and with few other special keys) has been fixed in the current development version, so just keep eye on the next official release. 
https://github.com/Ryochan7/DS4Windows/releases

**Comment by Ryochan7** [comment]
This issue has already been fixed in the code but I have not gotten around to making a new DS4Windows release yet. WPF handles some key inputs differently and the macro recorder did not take any key that was registered as a system key into account.
