### ISSUE TITLE
Multitouch doing mouse right click than default

### ISSUE THREAD

**Issue by flingrocks** [Ryochan7/DS4Windows#1025]
~~One issue, I can't get touchpad uppertouch click action to perform.~~
But first, the default action for multitouch click of touchpad is said to be mouse middle-click. However, it seems to be doing a mouse right-click instead.

![touchpad multitouch](https://user-images.githubusercontent.com/29521315/72048090-02ad2a00-328a-11ea-9425-211d307ed0a5.gif)

**Comment by Ryochan7** [comment]
Looks like some indexes are probably flipped. The mapping routine is correct though. Multi-touch defaults to right click and Upper Touch defaults to middle click. Hopefully this will be a quick fix.

**Comment by flingrocks** [comment]
Ah, I did suspect uppertouch to also have this problem.
Strike the comment about uppertouch action not working. Found out from reading that I needed to push higher up, the top edge rather.
