### ISSUE TITLE
error CiceroUIWndFrame

### ISSUE THREAD

**Issue by Qumojo** [Ryochan7/DS4Windows#1027]
Hi, from v2.0.3, every time I try to edit any button (that the window to select functions has to come up) ds4w throws an error saying CiceroUIWndFrame: DS4Windows.exe -Application Error - The exception unknown software exception (0xe0434352) occurred in the application at location 0x00007FFEE866A839. 
Previous versions work just fine. Tried updating .NET Frame, already in 4.7, tried to uninstall office as internet said it could be that, still error. Got an ViGEmClient.dmp file created on desktop every time the error occurs and I can send it over if needed. Otherwise the app works perfectly. No issues other than this one. I can use previous versions to edit my profiles and this to run meanwhile :D Thanks you for your hard work.

**Comment by mika-n** [comment]
VigemClient.dmp dump? Hmmm..... 

Make sure you have the latest version of ViGem driver installed (at the moment "ViGEmBus_Setup_1.16.116.exe" package in Vigem download pages).
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#link-list

Did you use auto-updater to update the previous version of DS4Windows? There has been bugs in some of the older versions of auto-updater and it failed to install all required files. Try downloading the latest version directly from DS4Windows releases page and install it (ie. extrac the zip file);
https://github.com/Ryochan7/DS4Windows/releases

**Comment by Qumojo** [comment]
Ok, I think I've nailed down why that error comes up as this only happens when trying to edit only one specific profile saved! Took me time to see it, sorry about that. Can you check what's wrong with  this culprit profile for me? Otherwise I will recreate it from scratch, thanks so much for taking the time, much appreciate
`<?xml version="1.0" encoding="utf-8"?>


<DS4Windows>
  <flushHIDQueue>True</flushHIDQueue>
  <touchToggle>False</touchToggle>
  <idleDisconnectTimeout>1200</idleDisconnectTimeout>
  <Color>225,225,225</Color>
  <RumbleBoost>100</RumbleBoost>
  <ledAsBatteryIndicator>False</ledAsBatteryIndicator>
  <FlashType>1</FlashType>
  <flashBatteryAt>10</flashBatteryAt>
  <touchSensitivity>50</touchSensitivity>
  <LowColor>0,0,0</LowColor>
  <ChargingColor>0,0,0</ChargingColor>
  <FlashColor>255,0,0</FlashColor>
  <touchpadJitterCompensation>False</touchpadJitterCompensation>
  <lowerRCOn>False</lowerRCOn>
  <tapSensitivity>30</tapSensitivity>
  <doubleTap>True</doubleTap>
  <scrollSensitivity>0</scrollSensitivity>
  <LeftTriggerMiddle>51</LeftTriggerMiddle>
  <RightTriggerMiddle>51</RightTriggerMiddle>
  <TouchpadInvert>0</TouchpadInvert>
  <L2AntiDeadZone>0</L2AntiDeadZone>
  <R2AntiDeadZone>0</R2AntiDeadZone>
  <L2MaxZone>100</L2MaxZone>
  <R2MaxZone>100</R2MaxZone>
  <ButtonMouseSensitivity>25</ButtonMouseSensitivity>
  <Rainbow>0</Rainbow>
  <MaxSatRainbow>100</MaxSatRainbow>
  <LSDeadZone>25</LSDeadZone>
  <RSDeadZone>25</RSDeadZone>
  <LSAntiDeadZone>0</LSAntiDeadZone>
  <RSAntiDeadZone>0</RSAntiDeadZone>
  <LSMaxZone>100</LSMaxZone>
  <RSMaxZone>100</RSMaxZone>
  <LSRotation>0</LSRotation>
  <RSRotation>0</RSRotation>
  <SXDeadZone>0.25</SXDeadZone>
  <SZDeadZone>0.25</SZDeadZone>
  <SXMaxZone>100</SXMaxZone>
  <SZMaxZone>100</SZMaxZone>
  <SXAntiDeadZone>0</SXAntiDeadZone>
  <SZAntiDeadZone>0</SZAntiDeadZone>
  <Sensitivity>1|1|1|1|1|1</Sensitivity>
  <ChargingType>0</ChargingType>
  <MouseAcceleration>False</MouseAcceleration>
  <LaunchProgram>
  </LaunchProgram>
  <DinputOnly>False</DinputOnly>
  <StartTouchpadOff>False</StartTouchpadOff>
  <UseTPforControls>False</UseTPforControls>
  <UseSAforMouse>False</UseSAforMouse>
  <SATriggers>-1</SATriggers>
  <SATriggerCond>and</SATriggerCond>
  <SASteeringWheelEmulationAxis>None</SASteeringWheelEmulationAxis>
  <SASteeringWheelEmulationRange>360</SASteeringWheelEmulationRange>
  <TouchDisInvTriggers>-1</TouchDisInvTriggers>
  <GyroSensitivity>100</GyroSensitivity>
  <GyroSensVerticalScale>100</GyroSensVerticalScale>
  <GyroInvert>0</GyroInvert>
  <GyroTriggerTurns>True</GyroTriggerTurns>
  <GyroSmoothingWeight>50</GyroSmoothingWeight>
  <GyroSmoothing>False</GyroSmoothing>
  <GyroMouseHAxis>0</GyroMouseHAxis>
  <GyroMouseDeadZone>10</GyroMouseDeadZone>
  <GyroMouseToggle>False</GyroMouseToggle>
  <GyroOutputMode>Controls</GyroOutputMode>
  <GyroMouseStickTriggers>
  </GyroMouseStickTriggers>
  <GyroMouseStickTriggerCond>and</GyroMouseStickTriggerCond>
  <GyroMouseStickTriggerTurns>True</GyroMouseStickTriggerTurns>
  <GyroMouseStickHAxis>0</GyroMouseStickHAxis>
  <GyroMouseStickDeadZone>30</GyroMouseStickDeadZone>
  <GyroMouseStickMaxZone>830</GyroMouseStickMaxZone>
  <GyroMouseStickAntiDeadX>0.4</GyroMouseStickAntiDeadX>
  <GyroMouseStickAntiDeadY>0.4</GyroMouseStickAntiDeadY>
  <GyroMouseStickInvert>0</GyroMouseStickInvert>
  <GyroMouseStickToggle>False</GyroMouseStickToggle>
  <GyroMouseStickVerticalScale>100</GyroMouseStickVerticalScale>
  <GyroMouseStickSmoothing>False</GyroMouseStickSmoothing>
  <GyroMouseStickSmoothingWeight>50</GyroMouseStickSmoothingWeight>
  <LSCurve>0</LSCurve>
  <RSCurve>0</RSCurve>
  <ProfileActions>
  </ProfileActions>
  <BTPollRate>4</BTPollRate>
  <LSOutputCurveMode>linear</LSOutputCurveMode>
  <LSOutputCurveCustom>
  </LSOutputCurveCustom>
  <RSOutputCurveMode>linear</RSOutputCurveMode>
  <RSOutputCurveCustom>
  </RSOutputCurveCustom>
  <LSSquareStick>False</LSSquareStick>
  <RSSquareStick>False</RSSquareStick>
  <SquareStickRoundness>5</SquareStickRoundness>
  <SquareRStickRoundness>5</SquareRStickRoundness>
  <L2OutputCurveMode>linear</L2OutputCurveMode>
  <L2OutputCurveCustom>
  </L2OutputCurveCustom>
  <R2OutputCurveMode>linear</R2OutputCurveMode>
  <R2OutputCurveCustom>
  </R2OutputCurveCustom>
  <SXOutputCurveMode>linear</SXOutputCurveMode>
  <SXOutputCurveCustom>
  </SXOutputCurveCustom>
  <SZOutputCurveMode>linear</SZOutputCurveMode>
  <SZOutputCurveCustom>
  </SZOutputCurveCustom>
  <TrackballMode>False</TrackballMode>
  <TrackballFriction>30</TrackballFriction>
  <OutputContDevice>X360</OutputContDevice>
  <Control>
    <Button>
      <RXNeg>Mouse Left</RXNeg>
      <RXPos>Mouse Right</RXPos>
      <RYNeg>Mouse Up</RYNeg>
      <RYPos>Mouse Down</RYPos>
      <L3>Left Mouse Button</L3>
      <R3>Right Mouse Button</R3>
      <TouchMulti>Left Mouse Button</TouchMulti>
    </Button>
    <Macro>
      <TouchRight>164/461/160/501/57/413/57/546/160/502/164</TouchRight>
    </Macro>
    <Key>
      <LXNeg>37</LXNeg>
      <LXPos>39</LXPos>
      <LYNeg>38</LYNeg>
      <LYPos>40</LYPos>
      <DpadUp>78</DpadUp>
      <DpadRight>114</DpadRight>
      <DpadDown>77</DpadDown>
      <DpadLeft>113</DpadLeft>
      <TouchLeft>13</TouchLeft>
      <TouchUpper>121</TouchUpper>
    </Key>
    <KeyType>
      <TouchRight>Macro</TouchRight>
    </KeyType>
  </Control>
  <ShiftControl>
    <Button>
      <RYNeg Trigger="14">WUP</RYNeg>
      <RYPos Trigger="14">WDOWN</RYPos>
      <L3 Trigger="15">LS</L3>
      <R3 Trigger="15">RS</R3>
      <Circle Trigger="16">Start</Circle>
    </Button>
    <Macro>
      <LXNeg Trigger="5">160/437/164/612/56/434/56/389/164/390/160</LXNeg>
      <LXPos Trigger="5">160/437/164/521/54/412/54/592/164/480/160</LXPos>
      <LYNeg Trigger="5">160/447/164/484/53/435/53/659/164/479/160</LYNeg>
      <LYPos Trigger="5">160/437/164/522/55/434/55/637/164/503/160</LYPos>
      <RXNeg Trigger="6">160/392/164/544/52/502/52/592/164/457/160</RXNeg>
      <RXPos Trigger="6">160/460/164/477/51/479/51/659/164/457/160</RXPos>
      <L2 Trigger="17">164/610/71/502/71/704/164</L2>
      <Triangle Trigger="6">164/475/160/682/50/569/50/659/160/682/164</Triangle>
      <TouchLeft Trigger="5">164/431/160/524/48/367/48/502/160/592/164</TouchLeft>
      <Options Trigger="6">160/483/164/588/49/479/49/547/164/569/160</Options>
    </Macro>
    <Key>
      <L1 Trigger="17">117</L1>
      <R1 Trigger="17">118</R1>
      <Square Trigger="6">164</Square>
      <Cross Trigger="6">9</Cross>
      <DpadUp Trigger="15">115</DpadUp>
      <DpadRight Trigger="15">116</DpadRight>
      <DpadDown Trigger="15">86</DpadDown>
      <DpadLeft Trigger="15">112</DpadLeft>
      <TouchUpper Trigger="14">51</TouchUpper>
      <TouchRight Trigger="6">119</TouchRight>
      <Share Trigger="15">13</Share>
    </Key>
    <KeyType>
      <LXNeg>Macro</LXNeg>
      <LXPos>Macro</LXPos>
      <LYNeg>Macro</LYNeg>
      <LYPos>Macro</LYPos>
      <RXNeg>Macro</RXNeg>
      <RXPos>Macro</RXPos>
      <L2>Macro</L2>
      <Triangle>Macro</Triangle>
      <TouchLeft>Macro</TouchLeft>
      <Options>Macro</Options>
    </KeyType>
  </ShiftControl>
</DS4Windows>`

**Comment by mika-n** [comment]
Please share the actual profile file (zipped).

**Comment by mika-n** [comment]
The profile seems to use Shift modifiers in some of the button re-map rules. There was a bug in shift modifiers and it is fixed already in devel version. Just tested to edit this profile in the devel version and it worked, but if the same profile file is edited in the latest official release then it crashes.
#1023

**Comment by Qumojo** [comment]
Oh, fantastic then, will wait for new update, you're awesome, thanks again!!! :) 👍
