### ISSUE TITLE
Features Request

### ISSUE THREAD

**Issue by Qumojo** [Ryochan7/DS4Windows#1034]
Hi, as my issue got solved (editing button that had shift modifier) got solved pretty quickly. I wonder if there was any plan on adding shift modifiers to the setup. It is really nice to have one shift modifier, one button can do two function, but it would be even greater if there could be 2 or more shift modifiers. Not a priority of course, just wonder if there are plans further down the line of improvements. And again, thanks a lot for your amazing work so far.

**Comment by mika-n** [comment]
Shift modifier supports (at the moment) two functions per key, but other way to change button re-maps is to change a whole profile on the fly. You can use SpecialAction "LoadProfile" and bind it to a trigger key to load a specific profile. The "next profile" can use the same bind key and load a third profile and so on. You can link any number of profiles until the "last" profile loads the first profile again.
https://github.com/Ryochan7/DS4Windows/wiki/Settings#how-to-change-a-profile-on-the-fly-via-a-certain-gamepad-button-using-a-special-action

Or you can set a trigger key to unload the new profile (=revert back to previous profile) when a trigger key is released.

Maybe you can work out something you need through that specAct functionality.

**Comment by Qumojo** [comment]
That's right, I see. Not the best option for me and the game I am playing as it has already a really bad support for gamepads in general and doesn't deal well with profile switching as if it looses buttons (not sure yet why) it gets crazy and refuses to get back normal buttons presses any more and I have literally to restart my computer to make the game see my gamepad again. I know it is the game as it happens with other controllers (xbox orginal and 3rd parties too) lot of people complains about it. Devs say they won't fix it as everybody plays with mouse and keyboard. If unplugged or anything weird happens to controller while playing, forced to restart whole pc! That's why I wonder if a second shift would be implemented at some point. But I see there wouldn't be much sense as you've already have a good way to deal with that those extra needs. Thanks anyway for answering my question, much appreciate :)

**Comment by mika-n** [comment]
If the previous and the next profile use the same output controller type (both xbox360 or dualshock4 profiles) then DS4Windows app itself doesn't do any disconnect/connect tricks with the gamepad object (re-map rules are just changed under the hood). However, if those profiles use different output types then there will be disconnect and connect events because those are technically "different gamepads" if the controller type is changed on the fly. But I doubt there is ever need to switch between different type of controller profiles within the same game but DS4Windows app allow it.

**Comment by Ryochan7** [comment]
That sounds like an extremely shoddy game that I probably wouldn't bother playing. Anyway, if the game has such a big problem with gamepads then maybe you should just use KB+M bindings in a profile for that game. Make sure to also check the "Use DInput only" option for that profile as well. That will unplug any currently connected virtual Xbox 360 or DS4 controller. Of course, you will have to make sure Exclusive Mode is working in DS4Windows so the game does not see the real DS4.

As for the request, I am not so sure about multiple Shift Modifiers. I would prefer getting Action Set support implemented in some form so the bindings for the whole gamepad will change while a button is activated. That type of feature will probably never be implemented in DS4Windows. The ideal plan would to be to create a new mapper program that implements a completely different mapping API that would be much more flexible than DS4Windows. It has not been worked on in a long time.

https://github.com/Ryochan7/mappingtest
