### ISSUE TITLE
Suggestion: Stop service/kill process before enabling "Hide DS4"

### ISSUE THREAD

**Issue by Nucleoprotein** [Ryochan7/DS4Windows#1038]
Hello,

My suggestion is to add possibility to create list of service/program to stop before enabling "Hide DS4" then start it again after grabbing exclusive input.

I personally need to stop every time NvContainerLocalSystem service to allow "Hide DS4" to grab exclusive access.

**Comment by mika-n** [comment]
It would be never ending and changing list, so it is probably not useful to try to maintain this list on a application source code level. There is Wiki doc page where certain widely used problematic (for exclusive access) have been listed. The list is community maintained, so feel free to suggest new apps to be listed there.
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

But I think you were suggesting some kind of automation to shutdown certain apps/services automagically when DS4Windows app is started (or a controller) is attached?  Have you seen the "cmdline" options Wiki page? You could create your down BAT/CMD batch file to launch DS4Windows app and this custom batch file could shutdown any apps/services you want before launching DS4Windows app, wait few secs until the gamepad is connected and DS4Windows acquired an exclusive access and then re-launching those apps/services if needed.
https://github.com/Ryochan7/DS4Windows/wiki/Command-line-options

**Comment by Nucleoprotein** [comment]
My suggestion to build a editable by user list, something like profile list, with two buttons: Add service/Add Process, then user click button - display small windows with all running services/process, user select service/process - it's added to list. Then when start is done DS4Windows will check the list and disable/kill all service/processes, grab exclusive access and restart the service/process.

**Comment by Ryochan7** [comment]
Exclusive mode is such a big problem with no absolute solution right now. The old "Hide DS4 Controller" workaround has been considered deprecated for a long time as more software is found that interferes with it. The use of HidGuardian is the alternative approach for forcing exclusive access to a device but I do not like the vanilla 1.14.3.0 release. Also the HidGuardian project is in limbo for the most part. I am not sure what kind of support will be available in the future.

I personally find this proposal too invasive. The process would have to be done per hotplug event so it would potentially have to be run many times in a session. Also, that approach won't be guaranteed to work in all cases anyway (automatic services).

**Comment by xperia64** [comment]
After a few updates of I have no idea what, my DS4 controller no longer worked in exclusive mode. I went to check what was using it, and it was dwm.exe itself apparently. Yep.

Carefully going through the song and dance of temporarily killing/resuming it did indeed allow exclusive mode to work again, but I would say that's a good reason to not kill/stop things automatically.
