### ISSUE TITLE
"Link Profile/ID" keeps coming unchecked

### ISSUE THREAD

**Issue by eggw** [Ryochan7/DS4Windows#1039]
Using DS4W v2.0.4 set to run as administrator, up to date Windows 10.

Every time DS4Windows is launched, one of my profiles (always the same one) is selected by default and "Link Profile/ID" is unchecked. Changing the profile has no effect until this checkbox is ticked, so I basically have to tick it (and select my desired profile instead of it defaulting to my last selected profile) every time I launch.

This started happening after I reinstalled Windows 10. I carried over the "Profiles" folder from my previous installation.

**Comment by RosesAreDan** [comment]
Same issue for me, also all of my settings are reverted to default after a restart.

**Comment by mika-n** [comment]
There is a bug in V2.x version. It fails to read this config option properly, so the app uses the default option (ie. unchecked linkProfile). The V2.x code "forgot" to call LoadLinkedProfiles method, so the linking is never used at runtime.

**Comment by Ryochan7** [comment]
It did work at one point during development but I must have changed something that broke it. Confirmed that it does not work now.

**Comment by Ryochan7** [comment]
> Same issue for me, also all of my settings are reverted to default after a restart.

Not sure if it applies here but the config does not save when logging out or rebooting your system. That does kill automated background usage. I have found the proper hook to correct the issue. I did not do play testing yet so it has not been added yet.

**Comment by Ryochan7** [comment]
This problem should be fixed in version 2.0.5.
