### ISSUE TITLE
Desktop profile and set auto profile action

### ISSUE THREAD

**Issue by unknowwiiplayer** [Ryochan7/DS4Windows#1040]
Just like with steam's desktop controls, I'd like to control my pc with my DS4 when on bed but I have to manually switch to a profile with mouse controls using an action.

Having a desktop profile is really easy, but it can be quite annoying to have, because you have to manually switch profiles whenever going to the desktop or into a game, and I know auto profiles can help with this, setting a desktop profile as default and an auto profile for your games but you have to manually add it in the auto profile list.

I think this can be done by an action that sets the auto profile for the current game.

Auto profiles can be set automatically uppon first launch using something like discord's game database and then, if the game is not found on the database, or if it was recognized as a game while it's not, set it manually using an action like;
"L2+PS+Square -> Action: Set auto profile for this program -> PS layout games"
"L2+PS+Cross -> Action: Set auto profile for this program -> Xbox layout games"
"L2+PS+Circle -> Action: Set auto profile for this program -> None"

And yes, I know this may be lazyness but I'd like DS4Windows to remember which profile to use with a certain game without having to manually set it on the autoprofiles.

I hope you like my idea so it gets implemented, it would make the experience of using a DS4 on PC even more comfortable!
Thanks in advance!!

**Comment by unknowwiiplayer** [comment]
I see, but this will default the apps in the path to a profile, I'd set it to Xbox due to compatibility with games, but there are some games, like rocket league, that do support DS4 and have playstation buttons layout, so, I'd have to set those manually to use the PS layout games profile, as I prefer PS layout over Xbox layout due to some inner conflicts with nintendo's layout.

Another exception when using a path to default every *.exe to use a profile are those games that have launchers. Those would require to use desktop controls and then, when in game, a gaming profile.

Those exceptions can be easily work arounded by using an action to switch profiles or by manually setting an auto-profile for those exceptions, but having it to remember which profile to use without manually setting an auto-profile would be really neat.

Also, when you have multiple drives and folders you'd have to create multiple auto profile rules, or can you use commas to put multiple paths on an auto-profile rule?

**Comment by porterballs** [comment]
> Just like with steam's desktop controls, I'd like to control my pc with my DS4 when on bed but I have to manually switch to a profile with mouse controls using an action.
> 
> Having a desktop profile is really easy, but it can be quite annoying to have, because you have to manually switch profiles whenever going to the desktop or into a game, and I know auto profiles can help with this, setting a desktop profile as default and an auto profile for your games but you have to manually add it in the auto profile list.
> 
> I think this can be done by an action that sets the auto profile for the current game.
> 
> Auto profiles can be set automatically uppon first launch using something like discord's game database and then, if the game is not found on the database, or if it was recognized as a game while it's not, set it manually using an action like;
> "L2+PS+Square -> Action: Set auto profile for this program -> PS layout games"
> "L2+PS+Cross -> Action: Set auto profile for this program -> Xbox layout games"
> "L2+PS+Circle -> Action: Set auto profile for this program -> None"
> 
> And yes, I know this may be lazyness but I'd like DS4Windows to remember which profile to use with a certain game without having to manually set it on the autoprofiles.
> 
> I hope you like my idea so it gets implemented, it would make the experience of using a DS4 on PC even more comfortable!
> Thanks in advance!!

Check out controller companion on steam! been using it for a long time now to use controller on desktop in bed.

**Comment by mika-n** [comment]
> Those exceptions can be easily work arounded by using an action to switch profiles or by manually setting an auto-profile for those exceptions, but having it to remember which profile to use without manually setting an auto-profile would be really neat.

Yes., it would be nice-to-have a special action to add the current process+windowTitle name combination as an auto-profile entry (if not exist already) and set it to use the currently active profile. 

 
> Also, when you have multiple drives and folders you'd have to create multiple auto profile rules, or can you use commas to put multiple paths on an auto-profile rule?

One entry in auto-profile list can have just one path and wndTitle entry. But if you use "*\" as a search keyword in PATH then it would pretty much match with every process because probably all processes have a path separator char. This would be sort of "catch all" rule if none of the rules above it didn't match with the current process/wndTitle keywords.
