### ISSUE TITLE
I will off myself. (DS4Windows not working AT ALL)

### ISSUE THREAD

**Issue by efadfa3** [Ryochan7/DS4Windows#1042]
I installed DS4Windows the old version and it worked well ('well', it worked after I shamaned my way through millions of driver restarts and such) for The Crew2. It used to work well for Life Is Strange 2, too. Something went wrong this night in LiS2 and started yeeting my camera in different directions. So I started Googling. Apparently this version is the one that gets updates. So I downloaded this version and enabled """"exclusivity"""". It was even worse. So today when I woke up I got back into it. Checking if other programs use my DS4 - no, they don't, funny, I launched LiS 2 - doesn't detect ANYTHING now. intalling HIDGuardian (what does it even do? I just install the tester, reboot and it should miraculously stop other processes? The guide *did* say to stop reading after that so I did.) Well, I rebooted my PC, launched first DS4Windows as administrator, launched Steam, launched LiS 2 and... nothing. Still doesn't detect the controller. I have no idea what to do next. It went from "working" to "working really badly" to "not working at all" the more I tried to fix it. I don't know what else I can do. At this point it doesn't even detect 2 controllers in control panel, only one.

Oh, and. I don't have some options that are supposed to be somewhere. For example, I don't have the "Write HID Guardian Device List" option.

**Comment by mika-n** [comment]
See this page for explanation of exclusive mode (=Hide DS4 Controller option in DS4Windows app).
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

HidGuardian tool is ALTERNATIVE solution if you really cannot get the exclusive mode to work in your environment. Exclusive mode is sometimes difficult to get working and unfortunately those reasons are not DS4Windows app related (or DS4Windows app can't do much about it unless you find which apps are preventing the use of exclusive mode).

Anyway. HidGuardian tools is a system driver level solution which can hide the original physical controller from games to avoid double input problems and other weird bugs in game side. HidG tool hides the physical DS4 game controller before any other app can "steal it" and leaves it visible only for DS4Windows app. There is no need to use both exclusive mode and HidG tools both at the same time, so if you now have HidG tool installed then untick "Hide DS4 Controller" option.

Also, Do you have official Sony DS4 revision1 or revision2 gamepad? 
Do you use xbox360 or dualshock4 DS4 output controller type in a profile?

There is one issue with DS4 rev1 gamepads and HidGuardian tool if you use dualshock4 type of DS4Windows profile and not xbox360 profile. HidG may hide both the virtual and physical DS4 rev1 gamepads. The solution is to use DS4 rev2 gamepad and tweak AffectedDevices sysreg entry of HidG tool.  But if you use xbox360 profiles then you don't have to worry about this.
https://github.com/Ryochan7/DS4Windows/issues/669#issuecomment-487302990

Please read general Troubleshooting page also. Please provide logfile and app version and WinOS version information. It is difficult to help without detailed information.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting

What do you see in JOY.CPL controlPanel applet (run JOY.CPL command) when you connect a gamepad? What do you see there after you start DS4Windows app?


And constantly spinning camera issue in some games may be result of "double inputs" from the physcial gamepad and virtual ViGem gamepad. Hiding the original physical controller from a game is the solution there (exclusive OR hidG tool solution).

Or it could be missing deadzone in LS/RS sticks in case those sticks are not completely stable in your gamepad (well, usually those are never completely stable in hardware level). Setting a deadzone to LS/RS or gyro axies in DS4Windows profile settings solves this.
https://github.com/Ryochan7/DS4Windows/wiki/Settings#deadzone

**Comment by efadfa3** [comment]
Apparently the only issue (and I've done and checked all the things you mentioned except this one) is that I had ds4 set as an output. I have rev2 DS4, but Steam (and it seems to be a Steam-only issue) is a dick and as soon as I use DS4 output it pretends there's no controller whatsoever. Only when I use xbox 360 as an output, does Steam actually see it.
Thank you for your quick response and help.

**Comment by Ryochan7** [comment]
Luckily mika-n helped you out because I won't be so nice. Life is Strange 2 is not a game but pure leftist propaganda garbage. If you find that entertaining then I have no reason to help you. May Christ-chan set you on the path to righteousness.

![christchan](https://user-images.githubusercontent.com/581968/72482825-9ddf5b80-37c4-11ea-886f-ade31c81f86d.png)
