### ISSUE TITLE
problem with vigem bus driver

### ISSUE THREAD

**Issue by asp0909** [Ryochan7/DS4Windows#1043]
Since the last update of DS4, the current bus driver program asks to update in all the reboots of the PC ... and it has already been updated but the update window is still coming out ... and tried to eliminate all the ds4 but it keeps coming out ... .the whole problem started since the last update of ds4

**Comment by asp0909** [comment]
![Captura](https://user-images.githubusercontent.com/29218473/72479624-01688980-37c3-11ea-9bae-eaf59ce88371.PNG)

**Comment by PowerSpot** [comment]
Does VIGEm Bus Driver give you an error when you try to install it? When it happened to me, it said it tried to delete a folder but couldn't and had to reboot...

**Comment by asp0909** [comment]
everything is done correctly ... but it comes out whenever I start the pc

**Comment by PowerSpot** [comment]
It showed up often for me too, I had to install vigembus manually (on github, guy named nefarius makes it (v.1.16.116)). Rebooted my PC, and then the DS4 2 steps screen opened (step 1 - install vigem, step 2 - install 360 driver...). Closed that, tried to connect my DS4, it was connected to the PC but not DS4Windows. Opened DS4Windows, click start stop and DS4 connected correctly. It hasn't asked to update VIGEm bus yet, but my system hasn't been up long enough to see if it will work long term.

**Comment by Ryochan7** [comment]
This is not related to DS4Windows directly so the update would not affect anything. The ViGEm installer creates a scheduled task that runs once a day to look for a new version of the ViGEm installer. A new version of the installer was published in the past couple of days so that window is appearing. I ran the update and it worked fine for me. The task will be removed when you run the ViGEm uninstaller program.

Now that the latest installer has been tested on my machine, the next version of DS4Windows will link to that version.

**Comment by asp0909** [comment]
> It showed up often for me too, I had to install vigembus manually (on github, guy named nefarius makes it (v.1.16.116)). Rebooted my PC, and then the DS4 2 steps screen opened (step 1 - install vigem, step 2 - install 360 driver...). Closed that, tried to connect my DS4, it was connected to the PC but not DS4Windows. Opened DS4Windows, click start stop and DS4 connected correctly. It hasn't asked to update VIGEm bus yet, but my system hasn't been up long enough to see if it will work long term.

is what is happening to me ... but come back and appear

**Comment by mika-n** [comment]
If the automatic updater doesn't work or keeps popping up (either DS4Windows or Vigem updater) then try to manually download the latest version and install it. There has been cases where auto-updater had some bugs.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#link-list

Anyway. VigEm case is just like Ryochan7 described above. Either disable the vigem scheduled update job or download the latest Vigem driver manually or wait for new version of DS4Windows which should include the newer version of vigem driver installer.

**Comment by Asinin3** [comment]
I Had the same issue, updated from 2.0.3 which was working fine. And then it kept saying that vigem is uninstalled when it's not. I uninstalled it manually and installed through the link above and it started to work again normally.

I wrote in a discord server about it and someone else had the exact same issue, so I'm guessing it's fairly wide-spread.

**Comment by Ryochan7** [comment]
Version 2.0.5 now uses the latest version of the ViGEm installer.

**Comment by asp0909** [comment]
Thanks......
