### ISSUE TITLE
Controller Input Analog & Gyro Jittering 

### ISSUE THREAD

**Issue by LegendaryJay24** [Ryochan7/DS4Windows#1046]
So idk what's going on here but for some reason I see weird jittering looking stuff happening on the controller readings window. I've tried dead zone, etc settings but I don't know how to fix this. Before in some games when using ds4windows, my character would move to the left slowly, stop, then move barely an inch and repeats, it gets annoying when you're doing something that  requires you to be completely still. I think this happens with the camera too iirc, but I'll have to check again. When using steam I've never had this problem. I've reinstalled ds4windows, cleared my appdata, etc. Thank you in advance for your help (I'm using a wired connection fyi idk if it says it  or not)
![2020-01-16-15-02-00](https://user-images.githubusercontent.com/45545914/72558764-5c58ba00-3871-11ea-8e29-fd80ff9123d5.gif)
^This is what it looks like (if it works to show enough idk)

![Capture](https://user-images.githubusercontent.com/45545914/72559222-4e576900-3872-11ea-9e60-8ba4fdf679ec.PNG)
^and this is my settings for it

**Comment by Ryusennin** [comment]
First of all, you need a dead zone for your sticks and triggers. 0.05 would be the strict minimum.

Secondly, you can't rule out that your DS4 is experiencing analog drift. It unfortunately happens to a lot of controllers, especially v2. I've returned three faulty pads to Amazon in the last six months. They were supposedly new and genuine, sold by Sony and shipped by Amazon. In my experience, the situation is worst than with Nintendo.

**Comment by mika-n** [comment]
https://github.com/Ryochan7/DS4Windows/wiki/Settings#deadzone
