### ISSUE TITLE
After installing DS4 Windows my controller no longer works without it.

### ISSUE THREAD

**Issue by Cappyy2** [Ryochan7/DS4Windows#1051]
I can't describe how much this irritates me. After one update I couldn't use my controller without it. I tried uninstalling all files, virtual bus driver, restarting my controller to factory settings, uninstalling every single driver for it. Nothing works. I can't even play anything with my controller anymore cause of this. How do I completely remove this from my PC and what is causing my controller to not work without DS4Windows?

**Comment by Ryusennin** [comment]
You don't explain what doesn't work. Is the controller visible in your Windows devices? If it doesn't appear, maybe you have installed HidGuardian (which job is to hide the physical controller) and you need to uninstall it as well.

**Comment by Cappyy2** [comment]
It is visible in Windows devices. I also had and uninstalled HidGuardian.

**Comment by mika-n** [comment]
Make sure DeviceManager doesn't show any of the HumanInterface (HID) devices in disabled state. If there are disabled hid devices then try to enable it.

If you have something laying around from HidGuardian then open regedit and search for "AffectedDevices" sysreg entry (it is under hidGuardian settings). Clear this sysreg entry because then HidGuardian doesn't do anything even if you would still have it running in the background.

**Comment by Cappyy2** [comment]
No HID device is in disabled state.
I also removed all ds4windows and hidguardian entries in regedit. Still my controller just flashes yellow light like its charging and it's not working.

**Comment by mika-n** [comment]
Does it do the same when you connect a gamepad both in USB or BT mode?

**Comment by Cappyy2** [comment]
I always connect it in USB because I can't connect it with bluetooth (never knew how to) .
Can you tell me how to completely remove both HidGuardian and Ds4Windows (and their leftover settings) from my PC?

**Comment by mika-n** [comment]
- DS4Windows app uninstallation is simply removing the folder where you have the DS4Windows.exe file. However, this app does nothing if it is not running.
- ViGem driver uninstallation via DeviceManager. System Devices/Virtual Gamepad Emulation Bus and "Uninstall driver" menu command. Tick "Remove driver files" option to completely remove the driver. Or there via "Add or Remove programs". There should be entry for Vigem Gamepad app.

That's it for those.

HidGuardian is not "officially" part of DS4Windows, but DS4Windows app is compatible with it. This driver can be uninstalled in the same way as Vigem driver via DeviceManager. System Devices/HidGuardian Virtual Device -driver.

**Comment by Cappyy2** [comment]
I uninstalled them through device manager like you said. I reset my controller twice already and nothing happened.

**Comment by Ryochan7** [comment]
> This driver can be uninstalled in the same way as Vigem driver via DeviceManager. System Devices/HidGuardian Virtual Device -driver

I would advise against trying to unistall HidGuardian via the Device Manager. If you choose the option to actually remove the driver from the Driver Store, that still does nothing to the UpperFilters entry left in the registry. There is a good chance of losing keyboard and mouse support when Windows fails to find the HidGuardian driver after a reboot. If you only remove the HidGuardian Virtual Device then the driver would still be installed and continue to hide HID devices.

Using either the devcon method or the test installer are my recommended uninstall methods.

**Comment by Ryochan7** [comment]
I guess I would also advise that you check out the program DriverStore Explorer. Maybe some old driver files were left behind after an uninstall.

https://github.com/lostindark/DriverStoreExplorer/releases/tag/v0.10.58

**Comment by mika-n** [comment]
If there is a suspect that HidGuardian driver is incompletely uninstalled then please see the following notes from HidGuardian Readme file:
https://github.com/ViGEm/HidGuardian/blob/master/sys/README.md

Or try to use TestInstaller app to re-install and un-install it.
https://github.com/Ryochan7/DS4Windows/wiki/DS4Windows-and-HIDGuardian-Install-and-Setup-Guide#hidguardian-test-installer

**Comment by Cappyy2** [comment]
Okay, so I found out a temporary fix (maybe even a permanent one). All I had to do was change the setting in DS4Windows to recognise it as a PS4 controller, not a Xbox controller, and then change the polling rate to max. Thank you all for your help!

**Comment by mika-n** [comment]
Hmm... That's weird. Do you mean that after those changes in DS4Windows app the gamepad is now recognized by WindowsOS when ds4windows is uninstalled?  Don't understand how and why it fixed the issue because those shouldn't have anything to do when the gamepad is connected without DS4Windows app running. Well, the important thing is that the gamepad works again.

**Comment by Cappyy2** [comment]
Seems like after uninstalling everything, then installing just Ds4Windows it works without it now.
In the screenshot I showed you what did I change to fix my issue.
Thank you very much for your effort to try and help me.
![Screenshot_1](https://user-images.githubusercontent.com/60042995/72764490-a252ac80-3be8-11ea-8ee5-ac96040d9df3.png)
