### ISSUE TITLE
Problems with Battery %

### ISSUE THREAD

**Issue by willbclos** [Ryochan7/DS4Windows#1052]
EDIT: I apologize for the improperly formatted post, as I'm new to GitHub and just found out about the troubleshooting guide. I have since edited this to contain the proper info.

Hello. Love the app but I'm having an issue displaying the proper amount of battery the controller still has. It either shows 0% or 100%, never an accurate amount that represents how much battery I actually have left, with the controller sometimes turning off out of the blue while playing, since I can't tell if the batteries are close to dying or not. I use it via BT, but plugging it via USB cable also shows the wrong %, although it is capable of detecting it's charging.

Any ideas as to why this is happening? Attached are my current settings and a log (via USB). Thanks in advance.

[Info]
App Version: 2.0.4
Windows Version: Windows 10 Pro 10.0.18363 Build 18363
Gamepad Version: Official DS4
Bluetooth Connection (BT 4.0 Dongle), but issue persists via USB

[DS4WINDOWSLOGUSB.txt](https://github.com/Ryochan7/DS4Windows/files/4082852/DS4WINDOWSLOGUSB.txt)

![DS4WINDOWSSETTINGS](https://user-images.githubusercontent.com/38492484/72683819-a7650e00-3ab9-11ea-845b-081b2bbbe662.png)

**Comment by mika-n** [comment]
Have you checked if checking "Quick charge" option make any difference? The battery reading value DS4 gamepad sends is not very accurate, but there certainly is more "steps" than 0% and 100% values.
The value comes from a gamepad and DS4Windows app just reports what it receives. Have you tried to reset the gamepad? There is a small hole on the back of the gamepad you can press with a sharp pen.

**Comment by willbclos** [comment]
Hi. So, I did try all that. Initially, resetting the controller while it was connected via BT fixed the issue, but now it's stuck at 100% again.

**Comment by mika-n** [comment]
This sounds like a hardware issue. Or is PS4 console showing the correct battery level all the time?
