### ISSUE TITLE
Only 1 Controller working with Bluetooth

### ISSUE THREAD

**Issue by Bogo36** [Ryochan7/DS4Windows#1056]
Hello, i updated to the Ryochan Fork and now only 1 DS4 Controller is working with Bluetooth.
I have 2 Controllers and is doesnt matter with which one i connect first, the second one will not be Recognized by DS4 Windows. I can connect it with the PC and it only has a solid white light. I tried everything. Uninstall and reinstall all Bluetooth and Controller Devices, Reinstalled Drivers.
I even rolled back to Jays DS4 Windows, but its also not working anymore.

System:
Win 10
Ryzen 3700X
Gigabyte X570 Aorus Ultra (Bluetooth 5.0)
Palit GeForce GTX 1080 Ti JetStream

**Comment by Ryochan7** [comment]
Looks like the Jays2Kings version probably permanently disabled the one controller. Please check in the Device Manager and re-enable the device if necessary.

https://github.com/Ryochan7/DS4Windows/blob/jay/README.md#device-detection-issue

**Comment by Bogo36** [comment]
Nope, Everything enabled.

**Comment by JarnoVgr** [comment]
Sounds like a similar problem I have from time to time. Resetting the controllers and pairing it again using Bluetooth usually fixes it. Make sure to pick the Bluetooth option and not "Everything else" from the "Add Bluetooth or other device" screen..

**Comment by mika-n** [comment]
Are those two bluetooth connected DS4 gamepads shown with different MAC identifier (xx:xx:xx:xx:xx:xx) values in Controllers list when you connect those one by one? In theory if two gamepads share the same MAC address then DS4Win might be confused to think that the second gamepad is "already connected".

**Comment by Bogo36** [comment]
@JarnoVgr 
Always doing this.

@mika-n
The MAC addresses are different.

**Comment by Bogo36** [comment]
So nothing?

**Comment by mika-n** [comment]
Please run the debug version to generate a detailed logfile from a gamepad connection events.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

**Comment by Ryochan7** [comment]
Can't fix an unknown problem. Need more info
