### ISSUE TITLE
2.0.4 wont work

### ISSUE THREAD

**Issue by eclipsaa** [Ryochan7/DS4Windows#1058]
tried updating to 2.0.4 using the auto updater and tried a fresh install using the 2.0.4 download and neither would work.   Program wouldent launch and controller wouldent connect to anything.   Had to Downgrade back to the 1.7 version.

not sure whats wrong

**Comment by Ryochan7** [comment]
The auto updater not working was due to old problems with the updater. A fresh install should work just fine though. Did you check the Logs folder to see what is in the latest log file?

**Comment by kmcgurty** [comment]
I made a [video](https://www.youtube.com/watch?v=j7wu_ddoPug) of the same issue I believe you are/were having? I was able to fix it by restarting my computer.

**Comment by Ryochan7** [comment]
Need log file with the crash report

**Comment by kmcgurty** [comment]
I'd be happy to give it to you, but I wasn't able to find it earlier. Is there a crash report that saves in a file?

**Comment by Ryochan7** [comment]
There should be a Logs folder in your main configuration folder. That location depends on whether you are using the Program Folder or AppData option. Look for ds4windows_log.txt as that is the most recent file. There might be a few archive files in that folder as well.

Also, maybe a related page depending on whether something like MSI Afterburner might be interfering.

https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#nothing-works-and-ds4windows-app-and-vigem-driver-connection-silently-doesnt-do-anything

**Comment by wfairless** [comment]
I've had a similar issue with versions 2.0.4 and 2.0.5. Version 2.0.3 does not exhibit the issue and works properly. I found log files in %USER%/AppData/Roaming/DS4Windows/Logs but all of the files indicate version 2.0.3 (which I have downloaded alongside version 2.0.5). So it seems that the executable is crashing even before making a log file.

**Comment by wfairless** [comment]
Downloading a fresh copy of the latest release fixed the issue for me. So perhaps there is an issue upgrading from 1.7.x to 2.0.x

**Comment by T3rm1** [comment]
Updated to 2.0.8. Program doesn't even launch and crashes instantly. No log file is written.

**Comment by mika-n** [comment]
Strange. Did you use auto-updated in DS4Windows app to update to the latest version or did you download it from releases page?
https://github.com/Ryochan7/DS4Windows/releases

If you used auto-updated then please test if you download the latest version from releases page and use the exe.config file from there. Maybe the auto-updater fails to update the config file? It would be important piece of information because it would be a serious bug in auto-updater.

**Comment by T3rm1** [comment]
If I copy the exe.config file from the latest release manually to the folder I get the same crash on startup. It only starts if I delete the file.

**Comment by mika-n** [comment]
Try updating the .NET framework to the latest version. Maybe one of the libraries is out of date/too old and the config file tries to find a "too new" library version.
https://dotnet.microsoft.com/download/dotnet-framework

**Comment by T3rm1** [comment]
I have 4.8.03761 installed. That should be one of the latest.
