### ISSUE TITLE
DS4 over bluetooth

### ISSUE THREAD

**Issue by jokerr601** [Ryochan7/DS4Windows#1059]
Im not sure if i'm doing  something wrong but using the ds4 with this version of ds4windows doesnt work correctly for me.  I only use my ds4 through bluetooth so i pair it with windows and when i try to use it with ds4 windows none of my inputs are registered in game even though ds4 windows detects my controller using exclusive mode and regular shared mode. If i go look at my control bindings, it shows cross is cross, square is square, triangle is triangle, etc. Is that how its supposed to be? When I click a button on the controller layout it just wants me to bind a keyboard key to a button press but obviously that's not what i want to do. Am i missing something? remember i only use my controller wirelessly through bluetooth.

**Comment by mika-n** [comment]
Please see general troubleshooting tips:
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting

Post more details here like content of log file or Logs tab page, app version, gamepad type (official Sony or 3rd party), using xbox360 or dualshock4 profile option? Please attach a profile file you use here as TXT file attachment.
Try using a new default profile without any custom modifications to make sure the mistake is not in a custom profile you use.

**Comment by jokerr601** [comment]
mika-n you were right it was my profile that was my issue, completely user error! Dont know why i didnt think of just setting a default to see what that would do. Thank you
