### ISSUE TITLE
DS4Windows does not run at startup

### ISSUE THREAD

**Issue by Cavonzio** [Ryochan7/DS4Windows#106]
I tried in both run as task and program mode and it doesnt work, i think it has something to to with the old Jays2Kings version i was using because when i check ds4windows in the list of autostart programs it points to the old one instead of Ryochan7's fork

**Comment by TristanYoung** [comment]
I wasn't having much luck with the built-in 'Start with Windows' feature, so keep that unselected and use the Scheduled Task method.

I pretty much overwrote the Jays2Kings version with Ryochan7's version.

1.  Jays2Kings version was extracted from the archive and copied to c:\program files\DS4Windows\
2.  Downloaded the Ryochan7 version, opened the zip file, selected ALL and COPY to clipboard.
3.  Navigated to c:\program files\DS4Windows\ and PASTED Ryochan7's files over top of Jayz2Kings files.

I run DS4Windows as a scheduled task upon login, with highest privileges, to not terminate after any amount of time.  Works like a charm.  Tested with Windows 10 creator's update, and the last 4 insider preview releases (fast ring).

In the Task Scheduler, I created a new task, with the action:
- Start a program
- Action: "C:\Program Files\DS4Windows\DS4Windows.exe"
- Arguments: -m
- Start in: "C:\Program Files\DS4Windows"

I would love to see DS4Windows have the ability to create and manage its own scheduled task.  I know it can be done as another program I use did it earlier today (Let's Encrypt's free SSL certificate updater).

Try again, and let me know if any of that helped.

**Comment by shinra358** [comment]
Works here... I use the task scheduler option.

**Comment by Ryochan7** [comment]
Unchecking and then rechecking the "Run at Startup" option should be enough to create a new autostart link with the location of the current executable; there is supposed to be code that actually checks the link at program startup and refresh it if needed but I guess it doesn't work anymore. As for the Task option, the way it is set up is to make sure that the task is only active while in the process of starting DS4Windows. The task is no longer active once DS4Windows has been launched.

**Comment by Ryochan7** [comment]
Just tried out each version of this and it works fine on my system. Also, the shortcut location is properly checked upon program startup and will overwrite an old shortcut if the executable location has changed. From what I have seen, there has been no regression.
