### ISSUE TITLE
conflicting log info vs update notes

### ISSUE THREAD

**Issue by Tiberiusmoon** [Ryochan7/DS4Windows#1060]
isnt the driver suppose to be the version of 1.16.116?
https://i.imgur.com/krGYMRH.jpg

**Comment by Tiberiusmoon** [comment]
i tried reinstalling the driver through DS4 but got the same result

**Comment by Ryochan7** [comment]
No. That is just the installer version. The changelog states that it installs ViGEmBus 1.16.112.

**Comment by Tiberiusmoon** [comment]
ahh okay
