### ISSUE TITLE
Touchpad as Pentablet and limit screen area (for those who use multiple screen).

### ISSUE THREAD

**Issue by Pedrogon18** [Ryochan7/DS4Windows#1062]
Hello. I use my pentable to edit Super Mario Maker on CEMU and works greats. So I thought, If it is possible to implement this in DS4, it will be great.

**Comment by mika-n** [comment]
I have to confess I didn't quite understand what kind of feature you were hoping to see. Pentable and ilmit screen area? You mean somehow to define boundaries where "touchpad as mouse" can move the mouse cursor?

**Comment by Pedrogon18** [comment]
> I have to confess I didn't quite understand what kind of feature you were hoping to see. Pentable and ilmit screen area? You mean somehow to define boundaries where "touchpad as mouse" can move the mouse cursor?

Basically, yes. 
On a pentablet, you can define which monitor and which area it will cover. This helps to improve accuracy on multiple monitors.
 Eg: On the pentablet, if I click on the upper right corner, the cursor will go to the upper right corner of the screen.
 On the DS4 touchpad, in mouse mode, I have to drag the cursor to the corner of the screen.

It would be nice, if possible, when I click on the upper right corner of the DS4 touchpad, the cursor will go to the corner that I click on.

**Comment by mika-n** [comment]
Aaah. Right. Now I got it. Indeed I can see few scenarios where something like this would be handy.
However, the DS4 touchpad area is physically quite small and touches are not very "pixel" accurate and when this smaller precision is "upscaled" (or scale re-mapped, don't know correct term) to better screen precision and area then isn't this quite raw accuracy?

**Comment by Pedrogon18** [comment]
Yeah. I highly doubt it gonna be precise due size and so on. But still, it can be useful. Another example, Super Mario 3D World (i' give game exemples, because is where I use it more), you can hold enemies by clicking on them, if they are in the middle of the screen, just simply click in the middle of the touchpad, instead of dragging the cursor to the middle.
