### ISSUE TITLE
Random (and non random) temporary system lockups

### ISSUE THREAD

**Issue by Lombra** [Ryochan7/DS4Windows#1064]
(I've seen your post regarding Windows 7 support)

I've finally pinpointed a very peculiar issue I've been having. A few months ago I started experiencing lockups, where all input as well as video (but not audio) would freeze completely for around a minute. Random at first, and not very often. I first noticed it while watching videos on YouTube. I came to the incorrect conclusion of it being related to Windows updates, as it seemed to consistently work better after doing a system restore. At this time I was using DS4Windows 2.0.0.

It was only a few days ago I was able to consistently reproduce the issue using the Windows snipping tool. Every time I start it, the system will freeze in almost exactly the same manner. 15 seconds of freezing, followed by a split second where I can see the result of any keyboard or mouse input I've performed during the freeze, followed by either 30 or 45 seconds of freeze, followed by the snipping tool actually launching and the system resuming normal operation. I can't see anything in Windows event viewer or the DS4Windows log during this.

Shutting down or stopping DS4Windows, or unplugging the controller fixes the issue, and it continues to work even if I then restart it. Updating to 2.0.5 made no difference. This is on Windows 7 with the 64 bit DS4Windows.

**Edit:** I suspected exclusive access was causing it, which would explain why it would work after restarting DS4Windows, since I seem to have something preventing exclusive access after the initial startup. Disabling "Hide DS4 Controller" seems to work around the issue.

**Comment by mika-n** [comment]
"Hide DS4 Windows" (=exclusive access) mode has one nasty "feature". The original gamepad is technically visible for other apps but they cannot use it because the device handle is exclusively locked by DS4Windows app. Some apps may try to open such a device and wait for a timeout until continuing normal operation. HidGuardian is an alternative solution to hide the original physical controller and it doesn't this kind of problem because the hidden device is not visible for other apps at all.

**Comment by Lombra** [comment]
Alright, I see now that Geforce Experience seems to be what's trying to open the device. Not sure why it appeared to work after doing system restores, though. DS4Windows just happening to be slower to start after a system restore?

Anyway, I've looked into this HidGuardian before, but I seem to recall being confused by it. Is there a downside to using it, or why is the same method not employed by DS4Windows?

**Comment by Ryochan7** [comment]
That topic could get lengthy so I will just post a short version. Using HidGuardian and related utilities (HidCerberus) introduce unwanted input latency on my system. HidGuardHelper.exe is bundled with DS4Windows to work around my issues with HidCerberus but there are inherit limitations with the current stable HidGuardian driver. Also, the HidGuardian project is in limbo last I heard so I don't know what type of support will be available for the driver.

I end up having to use a custom version of the driver and run Windows in Test Mode when I use HidGuardian. A few final tweaks are needed to get rid of the latency issue and get input performance comparable to using the native HID device handle without the filter.

https://github.com/Ryochan7/HidGuardian/tree/gottagofast

**Comment by mika-n** [comment]
closed as "probably game specific exclusive access" issue. HidGuardian probably solves the issue if exclusive access (=Hide DS4 Controller) option confuses some apps.
