### ISSUE TITLE
VIGem Bus driver setup wizard ended prematurely

### ISSUE THREAD

**Issue by Sephiroth713** [Ryochan7/DS4Windows#1065]
Hello. Greetings everyone. I'm trying to use DS4Windows in order to use my PS4 controller for gyro acceleration in Cemu, but, everytime I try to install it, it just shows this message:

![imagen](https://user-images.githubusercontent.com/40272934/72856696-f5783e00-3c80-11ea-891e-5581a8c241f0.png)
Don't know what errror it is. 

I'm using Windows 10. 

What other options do I have for me to install this program?

**Comment by mika-n** [comment]
Try downloading the latest ViGem installer directly from Vigem web site and run the installer using "run as administrator" option.
https://github.com/ViGEm/ViGEmBus/releases/tag/setup-v1.16.116

**Comment by Ryochan7** [comment]
All DS4Windows does is launch the installer and check if the driver installed after the installer closes. You can try downloading the ViGEm installer and running it directly. If problems persist then you might have to post an issue to the ViGEm project.

**Comment by Sephiroth713** [comment]
Thanks for the replies. Well, my computer was acting up, so I format it. Installed DS4Windows, and it didn't end prematurely. Thanks :D
