### ISSUE TITLE
windows update connect issue (?)

### ISSUE THREAD

**Issue by VanLaser** [Ryochan7/DS4Windows#1068]
Probably not a DS4Windows issue, but I'm asking here just to see if it happens to other people, since then it *could* be relevant. For some time, and on a different machine too (where I never installed DS4Windows), I can't connect an already paired Dualshock v4 over BT pressing the 'playstation' logo button. Every time I start Windows, I have to open Bluetooth settings, remove the paired device, and add it again (re-pairing it, so to speak). Does this happen to anybody else? 

What's worse is that the other machine is a virtualized one (Linux KVM with VGA passthrough) and for some reason I can't use the USB connection (I can't pass the controller, I have to pass an entire USB root hub, it's complicated etc.) Long story short, for now I'm able to  only use Bluetooth to connect. Am I doing something wrong? 

Thanks for reading this and of course feel free to close this 'issue' if not relevant or misplaced.

**Comment by mika-n** [comment]
the issue in pairing is something outside of DS4Windows app control
