### ISSUE TITLE
touchpad binding conflicts with stick

### ISSUE THREAD

**Issue by zxhzxhz** [Ryochan7/DS4Windows#1069]
while touchpad has been set to "use for controls" and bind any swipe action to stick(left or right) actions, stick actions will not response to other actions which also bind to them.

**Comment by Ryochan7** [comment]
I can see the issue in HTML5 Gamepad Tester. Another issue is that only one direction ever works when Swipe Left and Swipe Right are mapped to LX; it looks like the later binding takes priority. I never use swipe controls in my profiles so this issue does not affect me. I will double check with the old Jays2Kings build to see the behavior with that version.

**Comment by Ryochan7** [comment]
Checked it and that type of binding works in version 1.4.52. I will take a look into trying to fix that binding.

**Comment by Ryochan7** [comment]
Found the issue. The old improper midpoint value (127.5) was being used when converting swipes to axis values. Updated those portions to use the current standard (128) and now swipe controls work as expected. They also no longer conflict with normal stick mapping.

**Comment by Ryochan7** [comment]
This issue has been fixed in version 2.0.7.
