### ISSUE TITLE
Can't use DS4 controller after auto-shutoff due to idle timeout.

### ISSUE THREAD

**Issue by TristanYoung** [Ryochan7/DS4Windows#107]
If the DS4 controller shuts off due to idle timeout, and it is turned back on, the controller is non-functional.  The controller still appears in the DS4Windows controller tab.

Had to STOP DS4Windows, then START it back up to regain controller functionality.

Will continue testing to see if it happens both in-game (usually), and outside of game.

**Comment by shinra358** [comment]
Sounds like the old version. Doesn't happen to me on this new one. Some games do not have hotplugging or afterplugging support (see, told ya'll this is most important lol). that would be your problem.

**Comment by TristanYoung** [comment]
I'm running the latest version, v1.4.87.

I'm currently playing ESO, and many times having the joystick auto-disconnect is fine, and I've been manually disconnecting and switching controllers, so I don't think it's the game.  It's just once in a while DS4Windows doesn't seem to process the auto-disconnect properly, thus it shows the controller as still being connected when it's actually disconnected.  Re-connecting the same controller that auto-disconnected doesn't resolve the problem.  I have to press STOP and then START in DS4Windows to do it.

I've increased the idle timeout in DS4Windows, which will help reduce this effect, however it is still present.

I do plan to test without running a game, to help isolate the issue more.

**Comment by shinra358** [comment]
turn the game on first then activate the controller. if the controller doesn't work, that means the game lacks hotplugging support. It also says partial controller support on steam.

Also, try other games. If this doesn't happen in other games, it's this game. Games infamous for not having complete controller support on pc are older titled square enix games and Koei games, and some online only games.

Also, are you on win10?

**Comment by TristanYoung** [comment]
The game supports hotplugging.  Moments ago I ran the game first, and once it was running and could move around, I then turned on the controller and the controller began working.  I've done this many times before in the past as I forgot to turn on the controller before reaching the game's world.

The problem is sometimes (not all times), the controller shuts off due to the idle timeout.  At that point, the controller is still listed in the controller tab of DS4Windows.  It is as if the controller is turned off, but DS4Windows doesn't recognize that has happened.  It also doesn't recognize when the same controller is turned back on, so I can't just turn the controller back on, and then reload the game.  I have to open DS4Windows, and click STOP, which clears out the list of controllers, then START - and then things work fine again.

I can turn off the controller manually through a special action mapped to the long-press of the PS button.  I do this all the time as the battery runs down and I switch to another controller.


Yes, I'm running Windows 10, insider preview edition (fast ring).

From everything mentioned above, I'm lead to believe there's an issue with respect to the idle timeout shutting of the controller, and DS4Windows recognizing the controller has indeed shut off - and can drop the controller from the list of controllers.

**Comment by shinra358** [comment]
if you're playing the game, it shouldn't shut off anyway. a decent idle time would be 10 minutes. Also, windows 10 has problems with alot of things. That's why I have W7ultimate still xD
Doesn't do this in W7. Also, you haven't mentioned any other games that you've tested.

**Comment by TristanYoung** [comment]
The problem is sometimes I need to leave the computer to take care of something. You probably need to as well, unless you figured out how to pee without leaving your computer (gaming laptop in the bathroom, catheter, or a pee bottle? That's just wrong!).  Things happen sometimes, and I end up being a bit longer than 5 minutes (son needs help in his game).  Yes, I've upped it to 10 minutes, but the reason for the shorter shut-off time was to save power.  The original PS4 controllers have incredibly short life before needing recharge - and I have two of them plus a newer model.  Even with a 10 minute idle time, I'm still going to hit it the odd time.

In any case, Windows 10 has for the most part been working very well for me.  I'm not returning to Windows 7; it was a good OS, but it's old.  Have to move forward.

I'm playing Elder Scrolls Online.  I don't have other games installed right now.  I've been trying to get this issue to occur again by purposely using a short idle time (0.1 minutes), but it's not re-occurring.  It seems to happen when I actually leave the computer.  I will continue testing.  I have some other diagnostic stuff I'm going to look at.

**Comment by shinra358** [comment]
lol, it knows when you leave huh xD

**Comment by Ryochan7** [comment]
Unfortunately, this problem does not happen on my system. It seems like the disconnect routines are not running as intended so DS4Windows still has the old HID device handle reference. With that old reference, the hotplug routine in DS4Windows will see the controller as already connected and ignore it. You said that it does not happen all the time. Can you find a way to force the controller idle timeout routine to always fail?

**Comment by Ryochan7** [comment]
The main disconnect and idle disconnect routines seem to work as intended. However, the thread timeout routine for attempting to disconnect BT controllers that have lost their connection with a BT dongle would occasionally fail. The timeout interval that was being used previously was not long enough. Despite the controller actually being disconnected from the BT dongle, Windows would still take the output packet being sent rather than making the file routine in the input thread fail. Extending the timeout interval used for that purpose has worked without fail so far. Hopefully that change would help fix your problem.

**Comment by TristanYoung** [comment]
Sounds good.  I'm going to test it over the next few days, purposely set a lower idle disconnect time.  I had it happen a bunch more over the last few days, each time when I wasn't at the computer.  Didn't seem to be a pattern, sometimes I would have to shut down the game, and other times it would re-connect just fine.

Thanks for taking a look into that, and also changing the priorities.

I'm going to send you an email with a question about priorities.

**Comment by TristanYoung** [comment]
I guess I don't have your email address.  Odd, could have thought I emailed you once.

Anyways, I noticed with my own task I created in task scheduler to call DS4Windows would start very slow, and it had low priority.  I edited the task (export, then edit xml, then imported), and that seemed to make it fast again.  If I switch over to using your Start with Windows function, will that priority be normal again?

**Comment by TristanYoung** [comment]
Seems there is still a problem.

So in ESO, I can manually shut off a controller (hold PS for 2 seconds), and wake up the same, or a new controller over and over again and resume playing the same session reliably.

However, auto shut off is still causing the occasional headache.  I can't reproduce it reliably.  Every so often when the controller shuts off and I turn the same controller back on, I cannot resume playing the same session.  I haven't tried it yet by turning on a different controller before retrying the original controller.

It's very odd.

**Comment by TristanYoung** [comment]
I don't know if this is related, but earlier today, my controller auto-shut off.  I was able to re-connect it and continue playing ESO.

I shut off the controller, put it on my charging stand which uses the lower connector on the controller, not the USB connector, so not connected to the computer at all.  Came back 8 hours later, turned on the controller, and the status LED was blinking red, which I have set when below 10% charge.  I turned off the controller, and picked up the other 3 I have and tried them in succession - same thing - red flashing bar.

I shut down DS4Windows, did an update, and started the new version of DS4Windows.  Voila, now I get the blue bar as I was expecting with all my controllers.

**Comment by Ryochan7** [comment]
That is a good news but I don't know what change could have resolved your problem. The last few releases have been minimal code changes that mainly aimed at improving general application performance. The code behind the idle timeout routine has not really been changed. Hopefully this issue remains resolved but please post if the problem returns.

**Comment by TristanYoung** [comment]
Since my last post, I haven't had any further disconnect issues.  Continuing to monitor.

**Comment by czukowski** [comment]
I have a similar issue, not sure if it's the same as OP has, but could be at least related and I can't seem to reproduce it reliably. Maybe if enough observations from different users is collected, the problem could be resolved. So, for what its worth, here are mine:

I rarely disconnect the controller manually because the PS button must be held for like 10s. What I noticed is that if the controller disconnects on idle timeout and is turned on "soon enough" (usually some minutes, but also up to an hour or maybe even longer), it reconnects well. If left disconnected for _much_ longer, ie until next day, especially if the computer is put to sleep in between, chances are, it would not reconnect, but not always. If it is not reconnecting, the light bar would flash for a few seconds and then is stuck with white light or with no light.

To fix the connection, sometimes it suffices to just change Xinput port number, other times to stop and restart DS4Windows using its UI button, sometimes I have to physically unplug the Bluetooth adapter and plug it back in. Working solution seems to be random, I usually start with easier-to-reach method and move further if it doesn't help. Sometimes DS4Windows UI became unresponsive and even killing the process and restarting it wouldn't help (although I don't remember it occurring recently, could have been fixed after some update).

Last seen with v1.4.099, just upgraded to .100...

Will continue monitoring, but this line I've read above sounds like trouble that would not be easy to solve, if at all possible:

> Windows would still take the output packet being sent rather than making the file routine in the input thread fail.

**Comment by TristanYoung** [comment]
Good news about the PS 10 second disconnect thing.... you can define the PS button in DS4Windows to shut off the controller after a few seconds.  I have mine set for 2 seconds.

You can configure this under the Special Actions tab.

10 seconds - well, that's the intrinsic shut-off of the controller.

**Comment by czukowski** [comment]
@TristanYoung, 10 seconds was default, I guess and I've never changed it. I figured there is a possibility to reduce it from reading your earlier comment, and will give it a try, but the preferred way to shut off would still be on idle timeout. Why holding a button even for 2 seconds if it can turn off all by itself after lying still for a while (assuming it will reconnect without issues afterwards)? :)

**Comment by TristanYoung** [comment]
10 second isn't a default.  It's programmed into the controller's firmware.  You can't change that one.  You can only add a software-based disconnect that's less than 10 seconds.

A good case for setting a shorter disconnect time is one I encounter daily:    I'm playing ESO, involved in a WB, dungeon or trial, and all of a sudden my controller reports the battery is low.  I have defined a 2-second disconnect, so I can quickly swap-out controllers mid-battle.   

The idle disconnect thing would still be a nice thing to have work reliably, but I've learned to live without it for now.  It's easier for me to 2-second PS disconnect the controller, that way I know for sure when I return, I won't have to terminate-and-reload the game.
