### ISSUE TITLE
Custom Steam Folder not sticking

### ISSUE THREAD

**Issue by Servinjesus1** [Ryochan7/DS4Windows#1072]
I can't put a custom Steam Folder into settings. When I check the box, the box becomes editable, so I paste my location `D:\Games\Steam\steamapps\common` but the box blanks itself out as soon as it loses focus. What gives?

Windows 10, DS4Windows Version 2.0.5

**Comment by Ryochan7** [comment]
The short version is that the binding was actually saving the previous empty string rather than the new value. I also changed a couple of other related bits with the recent commit.
