### ISSUE TITLE
Duplicate is bugged

### ISSUE THREAD

**Issue by reyaz006** [Ryochan7/DS4Windows#1073]
When I duplicate some profile, it's all ok. When I duplicate something second time, I get 2 new profiles under same new name. Then 3, 4, 5... and so on.

Have to click each one of those dupes and click Delete, since Shift and Del keys don't work.

**Comment by Ryochan7** [comment]
Checked it and duplicate entries show up in the list. Only single files are generated though. The actual file creation portion is working as intended.
