### ISSUE TITLE
Max Zone doesn't work for L2 and R2 if Dead Zone is zero

### ISSUE THREAD

**Issue by keatsandyeats** [Ryochan7/DS4Windows#1075]
I would expect that setting Max Zone to 0.30 means that if I pull a trigger 30% down, it reads as pulled 100% down. However this appears not to be true. Here you can see it with a new default profile: 

![ds4windows max zone](https://user-images.githubusercontent.com/8346964/73149231-437caf80-408e-11ea-8569-64883bcf0aeb.png)

From my testing and limited understanding of the code, it seems that Max Zone doesn't do anything for L2/R2 if Dead Zone is zero. If that's intended, maybe someone could update the wiki to explain why.

DS4 revision 1 connected over USB
Windows 10
DS4Windows v2.0.6 (and earlier)

**Comment by Ryochan7** [comment]
Confirmed. That modifier will only apply if there is a dead zone set on the triggers. Need to change the if clause used for applying some modifiers.

**Comment by Ryusennin** [comment]
Side question: what is the difference between max zone (outer dead zone) and max output?

**Comment by Ryochan7** [comment]
I was wanting to record some video describing the changes in version 2.0.6 but I keep getting side tracked. Anyway, max output works as an axis value cap to keep the output axis value below a certain value. That modifier was made as a replacement to the old negative dead zone functionality that was in the old Jays2Kings build.

Max zone sets the point where output should be considered maxed out. That feature is mostly meant to work around worn out analog sticks that no longer reach the maximum range. It can be useful for other uses.

Both modifiers can be combined although there probably won't be any real reason to do that.

**Comment by Ryochan7** [comment]
This version has been fixed in version 2.0.7.
