### ISSUE TITLE
I cannot map numpad period to any button.

### ISSUE THREAD

**Issue by Starbuck7410** [Ryochan7/DS4Windows#1076]
I am making a profile to use with Blender and wanted to map the R3 button to numpad period.

So to map it, i click the button to map R3, and then click on the numpad period key, but nothing happens.
Edit: Mapping it to any other key works. only the numpad period key doesn't do anything.
Edit 2: After playing a bit more around i also found out numpad 0 has the same issue.

![image](https://user-images.githubusercontent.com/25639793/73212203-65416980-4156-11ea-8d6c-139d4f08f1a0.png)

I'm using the latest 2.0.6 build.

**Comment by mika-n** [comment]
Yes, There seems to be bug in re-map screen. Numpad symbols "0" and "." does nothing. You could temporarily workaround this problem by modifying the profile file in Notepad and adding re-map rule to those key codes there. If you create mapping rules to other numpad keys and then take a look at the profile file in Notepad then I'm sure you see the syntax used there.

**Comment by Ryochan7** [comment]
This issue has been fixed in version 2.0.7.
