### ISSUE TITLE
Saving Profiles is Broken

### ISSUE THREAD

**Issue by Firewall999** [Ryochan7/DS4Windows#1077]
This issue has been reported before in different ways.  See "When I modify profile options and press "Save profile" button in DS4Windows app then settings are lost the next time I open the profile editor."  (I couldn't figure out how to reply to that post.)

I noticed a problem with the naming of profiles. The program does not recognize all the characters, such as underscore ( _ ), and spaces in the name.  (This may be why starting a new profile sometimes works.  The user coincidentally changes the name to "Test" or something that the program can read.)  The program should clearly tell the user any required naming conventions, or just recognize all legitimate windows filenames.

Another symptom on this issue is that when the user right-clicks on the DS4Windows icon in the systray, and selects "Controller 1," there is no check mark next to the user's profile name, although the name is there in the list.  Selecting the profile name does nothing - no check mark is set.

I hope this helps.

BTW, the workaround is to not use profiles.  Just configure the default.  That always works.

**Comment by Ryochan7** [comment]
Not sure about a problem with underscore but I know profiles with spaces work fine. My most recent playthrough was of Dark Messiah of Might and Magic using a DS4Windows profile named "Dark Messiah". 

The lack of check marks in the tray menu was a small oversight. It is not a big deal to me but it should not be too hard to get that feature back.

**Comment by Ryochan7** [comment]
Underscores work fine for me as well. Something other problem must be happening with your configuration. Are you using the "Program Folder" or "AppData" method to save the DS4Windows configuration? Which directory is the configuration being stored?

**Comment by Firewall999** [comment]
My profiles are being stored in appdata/roaming.  

Still no problems using the default.

My installation was not using that vegxxx driver, if that helps.  Does it???  And that installation would not reload except during a reboot or logoff/on.  So I just installed that driver using your supplied dialog (nice touch!).  

The quitting/reload problem is still there.

I will retest the profile naming soon.

Thanks for your response!

John








 On Thursday, January 30, 2020, 3:51:36 PM UTC, Travis Nickles <notifications@github.com> wrote:







Underscores work fine for me as well. Something other problem must be happening with your configuration. Are you using the "Program Folder" or "AppData" method to save the DS4Windows configuration? Which directory is the configuration being stored?

**Comment by Firewall999** [comment]
TEST RESULTS / REV 2.08 (after installing that driver beginning with the letter v)

Spaces are being accepted.  Underscores are being ignored/dropped.  File saves correctly now, and check mark is there with rev. 2.08.

NEW PROBLEM

However, that quitting/reload problem is still there.  Try quitting, then reload.  The symptom is "DS4Windows has stopped working."  The workaround is to logoff then on.

QUESTION

What is the difference between running DS4W as a task compared to running it as a program?
(I am running it as a task, BTW.)  Is there someplace where this is explained?  I can't find it.

Thank you for your kind attention!

John








 On Thursday, January 30, 2020, 3:51:36 PM UTC, Travis Nickles <notifications@github.com> wrote:







Underscores work fine for me as well. Something other problem must be happening with your configuration. Are you using the "Program Folder" or "AppData" method to save the DS4Windows configuration? Which directory is the configuration being stored?
