### ISSUE TITLE
Issue with disabling touchpad inversion by button.

### ISSUE THREAD

**Issue by vvilkommen** [Ryochan7/DS4Windows#108]
I can select any button but PS it seems (that's the one I want to use most, too!) Whenever I choose "PS" from the list, "None" remains displayed in the Disable Invert box. If I leave PS checked and select another button, the second selected button will disable inversion without requiring the previously selected PS be held, it's kinda ignored.

Thanks for adding this feature, though! Really, thanks for everything... this program is amazing now.

**Comment by Ryochan7** [comment]
Sorry about that. The proper bounds were not being used so the last context menu strip item (PS option) was ignored. That has been corrected and now the PS button has been tested to work properly.

https://github.com/Ryochan7/DS4Windows/releases/download/v1.4.89/DS4Windows_1.4.89_x64.zip

**Comment by vvilkommen** [comment]
You are absolutely amazing.
