### ISSUE TITLE
DS4Windows doesn't see the controller

### ISSUE THREAD

**Issue by AlienX97** [Ryochan7/DS4Windows#1080]
It worked fine but it stopped to see the controllers, before it worked fine, i got everything installed properly, vigembus driver etc.

**Comment by mika-n** [comment]
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting

make sure there are no HID devices (especially gamepad hid devices) in disabled state in DeviceManager.

Do you see the DS4 gamepad in JOY.CPL controlPanel applet when DS4Windows app is not running?

**Comment by Ryochan7** [comment]
I have a strict policy about "The thing don't work" style posts.
