### ISSUE TITLE
DS4Windows as a program

### ISSUE THREAD

**Issue by ghost** [Ryochan7/DS4Windows#1084]
Hi, i have install the app in AppData for the settings but i would delete the folder for start the only icon program. 
Do I do this by moving the program folder to not have it in view and create a shortcut on the desktop?

**Comment by mika-n** [comment]
You can remove Start-menu icons in a normal way and create a shortcut to DS4Windows.exe app anywhere you want (desktop or inside a folder on the desktop etc...). DS4Windows app doesn't really care where the shortcut is located if you launch DS4Windows.exe manually from an app link/shortcut.

**Comment by Emanuele-1998** [comment]
> You can remove Start-menu icons in a normal way and create a shortcut to DS4Windows.exe app anywhere you want (desktop or inside a folder on the desktop etc...). DS4Windows app doesn't really care where the shortcut is located if you launch DS4Windows.exe manually from an app link/shortcut.

Yes but the folder can’t remove while He don’t work

**Comment by mika-n** [comment]
Hmm.... I don't quite follow what you mean.

**Comment by Emanuele-1998** [comment]
> Hmm.... I don't quite follow what you mean.

If remove the folder don’t work the app .exe

**Comment by mika-n** [comment]
Still don't understand. How about if you try to take a screenshots of those steps you are doing? 

What folder you are removing?
app .exe? You mean DS4Windows.exe executable file? How it doesn't work? Error messages? Doesn't launch or launches but connected gamepad is not recognized?
