### ISSUE TITLE
Gyro Mouse moving upwards by itself

### ISSUE THREAD

**Issue by Zero199** [Ryochan7/DS4Windows#109]
Hi,
Whenever I enable gyro to control the mouse, the mouse will move upwards by itself when the x-axis is in the yaw position.  If I change the x-axis to roll, then the mouse moves by itself towards the right top corner.  Anyone else experiencing this and have a solution?  Thanks.

**Comment by Ryochan7** [comment]
It sounds like the bias of the gyroscope is slightly out of bounds of the assigned dead zone. As it is, there is no calibration being performed so the raw values from the gyroscope are being used. There is a fork of DS4Windows that has calibration support but I find it slow enough to not want to use it. Even if calibration support were included at some point, having a hard coded dead zone might still be a problem depending on the controller.

The only way around this problem currently is to not use the **Always On** option when using Gyro Mouse. You would have to set up a button as a trigger and then make sure the Trigger Behavior - Turns Gyro option is enabled. That way, the mouse will only move while you have a button held down on your controller.

**Comment by Zero199** [comment]
Thanks for the response.  I will use it like that then.  Hopefully it could be fixed in the future.  
: )

**Comment by Ryochan7** [comment]
My new DS4 v2 controller has a larger inherit bias than my DS4 version 1. There was subtle up movement when the cursor was not locked. It was still playable and better than I have experienced with Steam's Gyro Mouse for the DS4. I think I finally have managed to make a calibration routine work at an acceptable level that gyro calibration support might actually get integrated into the next release.

**Comment by Ryochan7** [comment]
Gyro calibration support has been added to version 1.4.97. Even with the decreased gyro mouse dead zone, control is a bit tighter now than it was with previous versions. It seems to work pretty well. Currently, I am playing through Turok 2 using Gyro Mouse so having this functionality working is important.
