### ISSUE TITLE
DS4 back button attachment?

### ISSUE THREAD

**Issue by eclipsaa** [Ryochan7/DS4Windows#1091]
Was wondering if this will work (most likely)  But the big question is will DS4 windows be able to re map the back buttons to be independent of the normal face buttons?

**Comment by mika-n** [comment]
back buttons? face buttons? I have to raise my hand and ask a teacher to explain what are those buttons.

**Comment by TVsIan** [comment]
https://www.playstation.com/en-us/explore/ps4/accessories/dualshock-4-back-button-attachment/

I don't think they'll be able to be detected as extra buttons, I think they'll just map to duplicates of whatever you set them to.

**Comment by eclipsaa** [comment]
Yeah just wondering if anyone tried it.  That would be my guess that it cant be done.  But unless someone tries its just a guess.

**Comment by Ryochan7** [comment]
I doubt that it can be done. I bet the input report is changed before it is sent to your PC. I doubt the input report would change to reflect the two additional buttons that the attachment uses.
