### ISSUE TITLE
2.0.8: DS4Windows preventing Windows 10 mouse cursor from animating

### ISSUE THREAD

**Issue by CaptainStarPaw** [Ryochan7/DS4Windows#1097]
I'm seeing odd behaviour with the mouse cursor since the 2.0.8 update, whereby the mouse cursor animation frames are "frozen" whilst DS4Windows is running in the background.

If I quit the program, the mouse cursor behaviour returns to normal.

I have attached my DS4Log and DxDiag.

[DS4Log.txt](https://github.com/Ryochan7/DS4Windows/files/4174827/DS4Log.txt)
[DxDiag.txt](https://github.com/Ryochan7/DS4Windows/files/4174836/DxDiag.txt)

Let me know if I can provide anything else to help.

**Comment by mika-n** [comment]
Do you mean, for example, "spinning waiting for something" mouse icon animation? Do you have a profile where touchpad is mapped as a mouse? Any difference if you set "touch as control" option (ie. not mapped as mouse) and unbind mouse clicks from touchpad regions?

How about if you create a new default profile? The same effect?
Any differences if you connect the gamepad over USB or BT?
Can you revert back to older versions one by one to verify if it really affects only V208 version? 
https://github.com/Ryochan7/DS4Windows/releases

**Comment by CaptainStarPaw** [comment]
> Do you mean, for example, "spinning waiting for something" mouse icon animation? Do you have a profile where touchpad is mapped as a mouse? Any difference if you set "touch as control" option (ie. not mapped as mouse) and unbind mouse clicks from touchpad regions?
> 
> How about if you create a new default profile? The same effect?
> Any differences if you connect the gamepad over USB or BT?
> Can you revert back to older versions one by one to verify if it really affects only V208 version?
> https://github.com/Ryochan7/DS4Windows/releases

Thx for the reply, and the awesomely detailed list of things to try. Thankfully it resolved itself when I updated to 2.0.9, and I cannot seem to replicate now. If it occurs again though, I will be sure to go through this list and troubleshoot as much as possible.

**Comment by Ryochan7** [comment]
The only thing this could sound like is a UAC permission issue. If you attempt to play a game that requires admin privileges (Mass Effect 1) while running DS4Windows as a normal user, simulated mouse events will not be seen by the game so the cursor will be stuck. You would have to run DS4Windows as admin in order to get mouse movement to work.

**Comment by CaptainStarPaw** [comment]
> The only thing this could sound like is a UAC permission issue. If you attempt to play a game that requires admin privileges (Mass Effect 1) while running DS4Windows as a normal user, simulated mouse events will not be seen by the game so the cursor will be stuck. You would have to run DS4Windows as admin in order to get mouse movement to work.

Oh it is not the literal movement that I am referring to, but the cursor animation e.g. when Windows is performing an operation, the cursor graphic will change to a spinning wheel, and that spinning wheel graphic itself should "animate". Thankfully this is not an issue anymore. Would you say that it is generally advisable to run DS4Windows as an administrator? I have been running it as a normal user process the entire time.
