### ISSUE TITLE
ds3 support

### ISSUE THREAD

**Issue by lodesmets** [Ryochan7/DS4Windows#110]
I know this program is called ds4 windows, but the development of scp toolkit is dead. And there isn't really an alternative. And I have a ds4 controller, but my friends have a ds3 . 
So is it possible to also add ds3 support?

**Comment by lodesmets** [comment]
sorry I didn't look in the closed issues and there the issue was already asked. And from what I understood of the question there was no

**Comment by Ryochan7** [comment]
That's okay. Having a more universal mapping program would be really useful for people that prefer a controller other than a DualShock 4. I use several different controllers depending on the game and whether I feel like tinkering. Besides the DS4, I use a Steam Controller for any game that works better with a KB+M (FPS, Strategy, etc.), I still use an Xbox 360 but that has mainly been for testing, and I even play some games with a Wiimote in IR and MotionPlus mode.

As it is, there has been enough work making DS4Windows work well with just the DS4 that trying to cram in support for other devices would not work out well. DS4Windows is serving more as a testing platform for seeing just how well ScpVBus can emulate an Xbox 360 controller. ViGEm will have to be tested at some point.
