### ISSUE TITLE
i have issues with Shift Modifier fonction

### ISSUE THREAD

**Issue by KILL3R77** [Ryochan7/DS4Windows#1101]
hello
i have issues
i want use my right Stick has B but i want when i use R1 Shift Modifier the right stick has right stick and not B but it does work with DS4

the bug is if i use the real key in the shift modifier DS4 do not make shift modifier and onli use  the regular bind 

```
exemple:
Controller:                               Games see Key:
Push Right Stick                      B

Hold R1                                   Hold R1
Push Right Stick                      Push Right Stick
release R1                               release R1 

Push Right Stick                      B
```

i wish you understand what's i say i'm sorry for the bad english i'm french i do not speak very well

**Comment by Ryochan7** [comment]
Not sure why this type of shift modifier does not work. I'll take a look at the mapping routine.

**Comment by Ryochan7** [comment]
It was a minor omission when writing out shift bindings. Default bindings need to be explicitly bound when assigning to a shift modifier. The actual mapping routine did not need to be changed.

**Comment by Ryochan7** [comment]
While testing the old version 1.4.52 build for another issue, I tested this type of mapping out there and it did not work correctly in that version. So I unintentionally fixed that type of binding just to break it again with version 2.0.
