### ISSUE TITLE
Double-tap drag

### ISSUE THREAD

**Issue by gaibo** [Ryochan7/DS4Windows#1102]
Hi there, thanks for maintaining this project btw!
I'd been using Jay2Kings's latest version (1.4.52) until I discovered this repo today. However, I've immediately noticed that I can't get 2.0.8 to activate double-tap drag on the touchpad.
To be exact, on 1.4.52 I am able to lightly tap the touchpad twice on the border of a window and then drag my finger to move the window, as if I am using a touchpad mouse. I've attached a screenshot of my configurations in 1.4.52 - the same checkboxes on 2.0.8 do not allow for dragging.

![DS4 Windows 1 4 52 Double-Tap Drag Configurations](https://user-images.githubusercontent.com/9064408/74111271-18e42980-4b59-11ea-8eca-d4adeecb77d4.PNG)

**Comment by Ryochan7** [comment]
It looks like the initial Mouse Left Button down action occurs but it does not stay held while the touchpad is still touched.

**Comment by gaibo** [comment]
That sounds like exactly it! Will check on new update and report back.

**Comment by Ryochan7** [comment]
The next release will likely come out Friday night in my region. I am still testing a few tweaks.
