### ISSUE TITLE
RL RIGHT STARTS RUMBLE

### ISSUE THREAD

**Issue by dukkiedodo** [Ryochan7/DS4Windows#1104]
when i use rl right my controller starts rumbling first when i recorded a macro it stopped but it won't stop now.

**Comment by mika-n** [comment]
RL Right? You mean right stick?

Is the issue only with macro? Please share the profile file and macro definition here for further investigation. 

Version? Log file?
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting

**Comment by dukkiedodo** [comment]
no sorry i mean the left stick to the right im not sure with macro or not.



my version is: 1.4.52

sorry but github doesnt support that file maybe you can send me a good profile or something.

**Comment by Ryusennin** [comment]
You're using a very old version by Jay2Kings. Latest version by Ryochan (this site) is 2.0.10.

**Comment by dukkiedodo** [comment]
so? still doesn't work

**Comment by dukkiedodo** [comment]
nvm it worked thank you 😀

**Comment by mika-n** [comment]
This github site is not about the Jay2Kings 1.4.x versions. That is veeeeery (many years) old version not supported anymore. 

This github site is about 2.x Ryochan7 fork of the DS4Windows app. However, please note that this newer version no longer use ScpVBus driver but newer ViGem driver. The best practice is to uninstall ScpVBus driver before installing the newer ViGem driver.
https://github.com/Ryochan7/DS4Windows/releases
https://github.com/Ryochan7/DS4Windows/issues/1105#issuecomment-585112395

You can zip profile files and attach here small zip or txt files.
