### ISSUE TITLE
recognize: DS4 as wired / Xbox as bluetooth

### ISSUE THREAD

**Issue by MoHaX87** [Ryochan7/DS4Windows#1105]
Hello guys, today i fond this, when playing Star Wars jedi fallen.
When i use controler with bluetooth, game  recognize controller as XBOX. In game controls are (X,A,Y,B) etc, and rgb light all the time.
But when i play with usb cable, game recognize as shout be DS4 controller. And controls in game are  (▲, O , X) and rgb light blinks when controller rumble.
It this is normal ? or a strange bug with bluetooth ?

**P.S - Sorry my mistake i used Jays2Kings version. Now i see this is another mod of program. Will test later today**

**Comment by mika-n** [comment]
Jays2Kings original version never supported anything else but xbox360 output virtual controller. So, in this scenario I'm sure the game used the original physical controller device over USB cable and not the virtual output controller created by Jays2Kings+ScpVBus driver. Something like this could happen if the original physical controller is not hidden. 

Nowadays WinOS supports DS4 gamepad over USB connection. Over BT connections WinOS supports only "xbox compatible feature set" of DS4 gamepad (ie. no touchpad/gyro/rumble/lightbar). DS4Windows app is required to utilize touchpad/gyro/rumble/lightbar over bluetooth in WinOS and of course if you want to utilize macros and button re-map features.

This Ryochan7 fork of DS4Windows app is an improved beast and supports loooots of new features and newer ViGem driver. Through this driver DS4Windows app supports both xbox360 and dualshock4 output virtual controller types.
https://github.com/Ryochan7/DS4Windows/wiki/Settings

And here a link to explain a bit more about when and why you may want to sometimes hide the original physical controller.
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

**Comment by MoHaX87** [comment]
Thanks for the reply.
Today i tested this version of the softwere, but again game recognize controller as Xbox. It is not huge deal, i can play like that.
I dont know, maybe thats way  shoud be working ,but will be nice somehow to cheat the system. 

Or it is possible to have some virtual driver from other rearelease and cause a problem ?  
I just clean AppData folder and install Ryochan7 version with ViGEm, but i did not uninstall anything else from old app.

**Comment by mika-n** [comment]
You should be able to set the type of virtual output controller in DS4Windows profile settings (in this Ryochan7 version). See the Settings link I provided. DS4Windows logile should also list whether a profile is in xbox or dualshock4 mode. Make sure you see those entries in a logfile.

The ancient ds4windows version used Scpvbus driver and it may cause problems with BT connections and ViGem driver.  Mr Google shows links to Scpvbus uninstallation tool.

There has been causes where some veeeeery old profile and config files have caused problems. Cleaning up everything in %APPDATA%\ds4windows older should take care of that (ds4win app re-creates default files).

**Comment by Ryochan7** [comment]
Here is a current URL to the ScpVBus installer/uninstaller:

https://github.com/Ryochan7/DS4Windows/raw/jay/extras/Virtual%20Bus%20Driver.zip

**Comment by MoHaX87** [comment]
Good morning , it is working :) i unistall the drivers , mark in options  dualshock4, and it work like a charm. Thank you.
![ps4](https://user-images.githubusercontent.com/60914631/74408335-cf3b5d80-4e3c-11ea-8d20-f5076e21d325.jpg)

**Comment by portals999** [comment]
After years of DS4 working well it stopped tonight, not sure why, anyway this fixed it for me as above so try:
1. delete the folder: %APPDATA%\ds4windows
2. use the removal tool https://github.com/Ryochan7/DS4Windows/raw/jay/extras/Virtual%20Bus%20Driver.zip
3. install latest version from github
4. reboot and test.

Thanks for the wiki, appreciate your efforts on this project!
