### ISSUE TITLE
Lightbar constantly flashing red even when 'disabled'

### ISSUE THREAD

**Issue by JustOneCarb** [Ryochan7/DS4Windows#1107]
After a little while of using the program, the light bar turns red and starts flashing. It's annoying because I don't want the lightbar on at all, because I use my controller to study in class and it's really conspicuous when the red light keeps flashing. The RGB is turned totally down, Color by Battery %, flashing when latency is high, all that stuff is disabled. If the red light comes on, it stays on (flickering) even if I change the profile, stop/start, turn the controller off and on, disable and re-enable bluetooth, reset the program, etc. Any insights?

**Comment by mika-n** [comment]
Is the logfile of DS4Windows showing "high input latency" warning messages at the same time?

**Comment by JustOneCarb** [comment]
I've seen that in the log before once or twice, but it also happens without that showing up at all.  Thanks for the input.  It's possible that my bluetooth is just weak.  My computer only cost 300 dollars lol.  I've definitely considered that tape idea.  I live in a developing country so stuff like that tape is hard to come across, but it's certainly a possibility.  I'll see what I can find. :).  Thanks Mika.

**Comment by Ryochan7** [comment]
Tested this out and the setting works as intended for me. One thing to note is that the setting only takes affect after a latency state change has taken place. If you disable it while the latency is over the threshold then the lightbar will continue to flash red until you disconnect the controller or restart DS4Windows.

**Comment by JustOneCarb** [comment]
Still doesn’t work for me sadly.  But eventually I just put some tape over the light at.  Doesn’t really bother me.  Thanks for your efforts Ryo, this small issue aside your releases have been greatly useful for me.
