### ISSUE TITLE
Is it possible to make wireless ds4 appear as wired?

### ISSUE THREAD

**Issue by Muhlawor** [Ryochan7/DS4Windows#1109]
Some games utilize native support for ps4 but only while it is wired when connected wirelessly games don't detect the controller. 
So it is possible to make the wireless controller appear as wired?

**Comment by mika-n** [comment]
duplicate question. #1105

**Comment by Ryochan7** [comment]
You need to make sure that you are using DualShock 4 as the output controller in a profile and that Exclusive mode is working in DS4Windows. ViGEmBus emulates a wired DS4 v.1 controller. Exclusive mode is needed so that the game does not unintentionally detect the real DS4 controller.

**Comment by Muhlawor** [comment]
I see that, but for example, in a game Blue Estate there is a mode for native ds4 support which is achieved by holding the ps button for few seconds, and when connected wired motion controls are working but using ds4windows no input is registered at all not even buttons.

**Comment by Ryochan7** [comment]
Gyro and Touchpad support don't work when using ViGEmBus. That is a known limitation of the ViGEmBus driver. If you are playing a game that depends on those controls and you are using a wired connection, you will have to disable DS4Windows while playing the game.

**Comment by pokemontotalwar** [comment]
I'm having this issue, for example in Apex Legends -- it supports wired DS4, but gets no output from DS4Windows if I have it set to output as a DS4, Exclusive mode or not. It works if I have it set to emulate a X360 controller, which is fine for playing, but slightly annoying having it display the wrong buttons.

**Comment by mika-n** [comment]
ApexLegends indeed does something weird with DS4 gamepad inputs. It does recognize DS4 gamepad type when DS4Windows is used to do all sort of ds4 button remaps, but the game never sees any input events. With or without exclusive mode, with or without HidGuardian, renamed executable. USB or BT connected ds4 gamepad. Nothing seems to solve that issue. I could not get virtual VigEm DS4 gamepad to work with ApexLegends no matter what I tried.  Weird.

Don't know if this is an issue in ViGem driver orin ApexLegends or in DS4Windows app. Probably in ViGem driver. If someone has an old DS4Windows 1.4x + ScpvBus version still available then does ApexLegends recognize the virtual gamepad over the ScpvBus driver?  I dont have that old version and driver laying around anymore.

**Comment by Ryochan7** [comment]
Archived 1.4.52 build
https://github.com/Jays2Kings/DS4Windows/releases/download/v1.4.52/DS4Windows.zip

Old ScpVBus installer:
https://github.com/Ryochan7/DS4Windows/raw/jay/extras/Virtual%20Bus%20Driver.zip
