### ISSUE TITLE
Using the AutoUpdater, Reassigning Profiles and Some Options Mandatory

### ISSUE THREAD

**Issue by shinra358** [Ryochan7/DS4Windows#111]
When using the autoupdater to update, I have to reassign profiles and have to recheck options under the settings tab when I launch again. When I update manually, all settings stay saved.

**Comment by Ryochan7** [comment]
No matter whether you are storing settings in the program folder or in AppData, no settings files should be touched in the process so all settings should carry over to the new version. I have never run into that kind of problem while testing the Autoupdater.

**Comment by shinra358** [comment]
I have to do it every time. That is why I try not to use the feature. Maybe it is a special character problem or a character exceed problem. One of my folder names has a space in it. I store my things in program's folder.

**Comment by shinra358** [comment]
seems fixed now
