### ISSUE TITLE
sticks don't work when starting fortnite

### ISSUE THREAD

**Issue by gambl3rkk** [Ryochan7/DS4Windows#1110]
Hi, whenever I run fortnite the sticks don't work (other buttons work, even L3, R3,only sticks don't work) . I have to start/stop ds4 several times to make them work. I have tried running ds4 before launching the game, hide ds4 windows, and run ds4 after fortnite but the problem persists.

**Comment by Ryochan7** [comment]
Is Exclusive access actually active for the controller (check mark in the controller listing)?

There have been too many issues posted about Fortnite and other Epic Games Store exclusive games. I guess I will have to perform an act of high cuckery and finally create an Epic Games Store account to test some problems people have brought up in the past.

**Comment by gambl3rkk** [comment]
Where do I find exclusive access? I have checked but did not find it

**Comment by Ryochan7** [comment]
You have to check the **Hide DS4 Controller** option in the Settings tab first. That does not necessarily mean that DS4Windows will succeed in getting exclusive access to the controller though. A warning message will appear in the Log tab and an X will appear in the Ex column if DS4Windows cannot get exclusive access to the controller.

Exclusive access:
![ds4win_exclusive](https://user-images.githubusercontent.com/581968/74506219-cb501f80-4ebe-11ea-980c-721d39f45659.png)

Shared access:
![ds4win_shared](https://user-images.githubusercontent.com/581968/74506233-d014d380-4ebe-11ea-9a90-24519fd845f6.png)

**Comment by Ryochan7** [comment]
For more information:
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

**Comment by Ryochan7** [comment]
I have tested Fortnite and DS4 support works fine for me. At least now I know that the game reads from the HID device rather than using the DInput interface since Fortnite can change the lightbar. I could not find the answer to that question online previously.

**Comment by gambl3rkk** [comment]
I already have that setting on. 
This happens only if I select “DualShock 4” in ds4 settings. When I had “360 controller” it all worked

**Comment by gambl3rkk** [comment]
everytime I run ds4, it says "couldn't open ds4 exclusively". I only have nvidia share and nvidia container among the processes.  I think i am going to start/stop it unless it works :)

**Comment by Ryochan7** [comment]
The Nvidia software that you are using is likely the reason that DS4Windows cannot obtain exclusive access to the DS4 controller. You can possibly try to use HidGuardian to attempt to hide the controller but maybe it would be better just to temporarily disable DS4Windows while playing Fortnite. Luckily that is an option when using a wired connection.
