### ISSUE TITLE
Controller has stopped to be recognized in just one usb port.

### ISSUE THREAD

**Issue by AlienX97** [Ryochan7/DS4Windows#1111]
As in the title, when i connect controller to another usb port it works. But i want to connect it to the one it stopped to recognize it. Any suggestions?

**Comment by mika-n** [comment]
Is the gamepad recognized by WinOS in the problematic usb port when DS4Windows is NOT running? What do you see in JOY.CPL controlPanel applet? Is the ds4 gamepad listed there as "Wireless Controller"?  (yes, ds4 pad is listed with WirelessController name even when it is connected over usb).

 If the gamepad is not reconized by WinOS then there is not much DS4Windows app can do. Check the there are no disabled USB host devices in DeviceManager, try another cable, are other usb devices recognized in the same port?

**Comment by AlienX97** [comment]
I don't know what caused that but gamepad has been recoginised again in this port i don't know what i've done, i just turned it off for some hours and plug it in again and it works again, but i have aprehension that i will happen again. If it will, i just post an message here, and yes gamepad is recognised in game controllers section as a Xbox 360 Controller.

**Comment by AlienX97** [comment]
I have some news, i mean that the same happened to my mouse i just restarted pc and it worked fine, its rather nothing related to DS4Windows.
