### ISSUE TITLE
Updater reopens DS4Windows as Adminstrator

### ISSUE THREAD

**Issue by aureq** [Ryochan7/DS4Windows#1113]
Hi,

In 2.0.10 and earlier versions, the updater requires `Administrator` privileges if DS4Windows installed system wide (ie: `%ProgramW6432%\DS4Windows`). This is necessary for the upgrade to be successful .

Upon the update completion, the updater reopens DS4Windows but not as the current logged-in user but as the `Administrator` user that was used to perform the upgrade.

The consequence to this is my `Administrator` user doesn't have any profile installed and so, after the upgrade I need to close and reopen DS4Windows.

Applications like Firefox and VSCode reopen their applications as the logged-in user. It would be nice if this could be addressed.

Thank you.

**Comment by Ryochan7** [comment]
It looks like there is only one real way to run a command un-elevated from an elevated process. That is to make a call to explorer and tell it to run the program.

**Comment by deadair3210** [comment]
Don't know how much this will help, but apparently you can spawn unelevated processes from elevated ones, it just takes some work

https://devblogs.microsoft.com/oldnewthing/20190425-00/?p=102443

**Comment by Ryochan7** [comment]
I opted to use the Explorer version as that is the only option from Managed code. The other version is a bit more indirect in case someone happens to be using a custom shell rather than Windows Explorer. I finally updated the DS4Updater to take an extra command line argument into account so it can use the Windows Explorer shell workaround when launching DS4Windows.

Unfortunately, that means that you will not see that change until after updating to DS4Windows 2.0.14. There is no planned date for its release as of yet.

**Comment by aureq** [comment]
Hey @Ryochan7 thank you so much for the update on this issue, and also for sharing the technical details. I'll give you feedback on your changes as soon as 2.0.14 is out.

**Comment by aureq** [comment]
Hi,

I just upgraded from 2.0.13 to 2.0.14 and when DS4Windows reopened, the processed ran as "admin" instead of my currently logged in user.

![Task Manager](https://user-images.githubusercontent.com/1161681/77719734-23d81800-703a-11ea-9c5c-7ab801a50d50.png)

That's the task manager screen capture to show that. Was there something I should have done when I upgraded to 2.0.13 maybe ?

**Comment by Ryochan7** [comment]
As long as DS4Updater 1.4.1 is now installed, the next update should launch DS4Windows again as a normal user. Both the updated updater and updated DS4Windows version is needed. You won't see the change in behavior until the update to DS4Windows 2.0.15 whenever that comes out.

**Comment by Ryochan7** [comment]
Version 2.0.15 is now out and it looks like the routine is working as intended.
