### ISSUE TITLE
Controller not being recognized

### ISSUE THREAD

**Issue by sebkuip** [Ryochan7/DS4Windows#1118]
Hello there,
I have been using DS4Windows with great success in DCS world. But recently it randomly stopped working. When I try to connect the controller I just get "Windows does not recognize this USB device". Important info:
> I use a true sony DS4 controller that came with my PS4
> The PS4 is turned off
> I run windows 10 up to date
> I run DS4Windows up to date
> My desktop does not support Bluetooth so I use a USB cable

I have already verified that the controller works with my PS4. I also changed out the USB cable and changed the USB port on my PC.
![image](https://user-images.githubusercontent.com/61157793/74672205-08f9c480-51ad-11ea-836c-8af535e14ddd.png)

EDIT: I also tried a fresh new download of all the bus drives and DS4Windows, to no avail. Restarting PC also did not work.
EDIT 2: I now notice that it often connects and then instantly disconnects. The longest I could get it to stay was like 5 seconds, but most of the time it's in the milliseconds. I am getting a slight feeling the mico-USB port on the controller is broken.
EDIT 3: Well I cannot deny not verify if the USB port on the controller is broken as it charges just fine, but when connecting to the PC it sometimes connects when I hold in in a certain angle. Could this mean broken data pins on the USB port?

**Comment by mika-n** [comment]
Sounds like a hardware issue. The usb port in ds4 gamepad is quite easy to replace because the usb port is in a separate board and not soldered directly on the main board within DS4 gamepad.

**Comment by sebkuip** [comment]
Thanks for the reply. I have tried with a third cable (this one is slightly shorter so it's not the best), which has a rubber end that's a bit thicker. This apparently is enough to make it work again. Still thanks for helping.
