### ISSUE TITLE
Installing VigEm

### ISSUE THREAD

**Issue by mccorkled** [Ryochan7/DS4Windows#1119]
I am having a problem installing VigEm through my own installer. I know VigEm is not your project, but perhaps you could assist me. When I run the installer through my own program, it seems to install fine and I can see it in windows uninstall programs list. I have DS4Windows setup to run on Windows start, and it does, but then I get the initial installer window popping up stating VigEm is not installed.

**Comment by Ryochan7** [comment]
To answer the initial question, I have never played with Advanced Installer so no. I had written a ViGEmBus installer a while ago using the Nefarius Managed Devcon library. The current unofficial HidGuardian installer is a slightly modified version of the same code.

Old unofficial ViGEmBus installer:
https://github.com/Ryochan7/ViGEmBusInstaller

Unofficial HidGuardian installer:
https://github.com/Ryochan7/HidGuardianInstaller

**Comment by mccorkled** [comment]
Thanks for the help. I should have just left the thread I guess. I actually got VigEm installing through my own installer and I set DS4Windows to run when the PC starts. Everything seems to have installed fine and I can see VigEm in the program manager but when I restart the PC and DS4 starts, I get an error saying VigEm is not installed and the initial DS4Windows installer window opens.

**Comment by mika-n** [comment]
DS4Windows app asks WinOS to enumerate all device classes and tries to find VigEm with an identifier {96E42B22-F5E9-42F8-B043-ED0F932F014F}  (SetupDiEnumDeviceInfo  winAPI call).

Are you sure your installer installs the VigEm driver with the same ID and registers it with WinOS kernel in the same way as official VigEm installe?

**Comment by mccorkled** [comment]
I'm certain that it does because I am using the actual Vig build. I just set it as a pre req in my installer. My installer runs the Vig installer and you have to go through all of the normal menus.

**Comment by mccorkled** [comment]
It seems to have started working now. I am quite puzzled. I would still like to be able to install it without using the official Vig installer. If you could help me, that would be great!

**Comment by Ryochan7** [comment]
Is the Virtual Gamepad Emulation Bus device (under System Devices) listed in the Windows Device Manager? Also, I cannot remember what happens when reversing the order but any custom installer code needs to create the bus device first before installing the actual driver.
