### ISSUE TITLE
Autoupdater, Close Program Then Overwrite

### ISSUE THREAD

**Issue by shinra358** [Ryochan7/DS4Windows#112]
Currently, the program runs into an issue and tells you to unpack manually if DS4windows is on when trying to overwrite to the new version.

**Comment by Ryochan7** [comment]
Do you have DS4Windows installed under the Program Files folder somewhere? I have my copy installed under a subfolder in Downloads and the Autoupdater brings up a prompt that will terminate DS4Windows, if it is running, so the update can finish successfully.

**Comment by shinra358** [comment]
No. For me, if I try to terminate, it just tells me i have to do it manually. works fine if I stop the program first. Maybe it should stop itself before trying to close itself.

**Comment by shinra358** [comment]
seems fixed now
