### ISSUE TITLE
8 way movement stick / diagonal

### ISSUE THREAD

**Issue by eclipsaa** [Ryochan7/DS4Windows#1120]
Trying to map a game that requires 8 way movement (ie upper left,  upper right, ect)  But i can only see a way to map up, down, left and right on the left and right stick.  Is there a way to set up diagonal movements?

**Comment by Ryochan7** [comment]
DS4Windows is not flexible enough to allow rogue-like 8 way controls for the sticks. The major focus of this project is getting the XInput conversion process done as quickly as possible.

I hope to make a different mapper backend at some point that will be capable of more but I think I have managed to add a lot to the current code base. If you have ever heard of the software antimicro then you can see that I have made a system that was capable of that functionality before. Stick to mouse emulation is now better in DS4Windows though.
