### ISSUE TITLE
Deadzone and senstivity| Fortnite

### ISSUE THREAD

**Issue by tarikgaming** [Ryochan7/DS4Windows#1121]
Hey! I recently downloaded the ds4 windows 2.0 and instantly got 1 Ms delay only! Im happy with that but the sentivity and deadzone is way to high. In fortnite i already have the setting where i can adjust everyrthing from sensitivty to deadzone. Is it a way to disable those settings on Ds4?

**Comment by mika-n** [comment]
https://github.com/Ryochan7/DS4Windows/wiki/Settings

Just tweak the deadzone/antideadzone/outputCurve/sensitivity settings in a profile. By default there may be a small deadzone in a new profile, but you can set it to zero. However, sensitivity should be 1.0 already and output curve linear (ie. standard ds4 sensitivity and input-to-output-curve mapping).

**Comment by tarikgaming** [comment]
Hey again! I tried to tweak in many ways without sucesss. I even tried to put most of the settings to 0 and let the sensetivity and deadzone on default settings, and when i do that i cant even move on fortnite.

**Comment by mika-n** [comment]
if the game doesnt react to any of the gamepad stick movements and button presses then it may be the problem of "not hiding the original gamepad from the game" issue. See the following page which explains why some games require that the original physical controller device is hidden and this way forcing the game to use just the virtual output controller created by DS4Windows app. 
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

Are you using bluetooth connection with DS4 gamepad and the gamepad is an official Sony gamepad? If you are using BT then the game is probably accidentally trying to use the original physical BT gamepad device handle but it is in dead state. This is a WinOS level problem with DS4 bt connected gamepads when the DS4 gamepad is used in native ds4 mode over BT. USB connected  DS4 doesn't suffer from the same issue, but you still want to hide the original physical controller (as explained in the above linked doc page).

**Comment by Ryochan7** [comment]
Works for me (TM)
