### ISSUE TITLE
Milestone Version 2.1

### ISSUE THREAD

**Issue by Ryochan7** [Ryochan7/DS4Windows#1126]
The WPF code base has really improved since version 2.0 was released a couple of months ago. The initial launch was pretty rocky but things have stabilized for the most part. At some point, an incremented minor version number should be used to establish that differences that have been made to the project since version 2.0. Unlike previous DS4Windows minor releases, there will probably be no defining feature that marks the milestone.

**Comment by Ryochan7** [comment]
The changes **mika-n** has written to offer better third party controller support will be the defining feature in version 2.1.

**Comment by mika-n** [comment]
A quick check list issue for the next release about HidGuardHelper tool. 

I was having problems with HidGuardian and DS4Windows. For some reason HidGuardHelper.exe tool didn't want to add the Whitelist process ID value to a sysreg with the latest DS4Win version. After going back to 2.0.16 release HidGuardHelper tool worked again.

It looks like that some shared .NET library version is now newer version in the latest head branch of DS4Windows (when re-compiled from sources) and the old "not re-compiled" HidGuardHelper.exe tool fails to work with newer shared libraries. I suppose the HidGuardHelper tool should be re-compiled before packing it into a new release.

**Comment by Ryochan7** [comment]
HidGuardHelper.exe works fine on my dev setup and with version 2.0.16. Did you make sure to copy over the UtilLibrary.dll file in your build output folder as well? HidGuardHelper.exe will not run without it and that library has the routines used to interact with the registry. That library is built off of a C++/CLI project. With more recent .NET discoveries, HidGuardHelper.exe could probably be changed to use the standard .NET libraries rather than needing custom code. This was another case of doing weird things to get better performance.
