### ISSUE TITLE
No color picker for "Full" battery percentage

### ISSUE THREAD

**Issue by Serosis** [Ryochan7/DS4Windows#1128]
As the title says. Should there not also be a color picker for the "Full" battery percentage when choosing `Color by Battery %` ?

![image](https://user-images.githubusercontent.com/4404965/75392090-2e1ebf00-58a0-11ea-9ed3-0b0b545c8cfc.png)

**Comment by Ryochan7** [comment]
It already exists. Click the lightbar segment of the controller display to bring up the color picker for the full color.

![ds4win_lightbar_color_picker](https://user-images.githubusercontent.com/581968/75496837-0440c780-5988-11ea-8564-25d9558df5dc.png)

**Comment by Serosis** [comment]
Well how about that, I didn't even think to click anywhere in that area.

Shows how much I was paying attention.

Thanks for pointing that out!
