### ISSUE TITLE
Problems in Bluetooth Connection.

### ISSUE THREAD

**Issue by AhilKhan** [Ryochan7/DS4Windows#1129]
I am using DS4WINDOWS with a third party dualshock 4 controller for almost 3 months over USB and there's no problem. 

But, when i use bluetooth connection. there's no input from the controller(Emulated Xbox Controller) at first i thought it was my controller's fault so i sent it for a repair where they verified that the controller is perfectly fine.  Also, the gamepad test in control panel show two controllers connected (one named wireless controller and other named controller XBOX 360 for windows) i believe wireless controller is the main controller while the other one is emulated by ds4.

so when i checked both of them one by one i found that wireless controller responds to every button and joystick input. while. the other one doesn't respond at all.

I tried hide ds4 option and the wireless controller disappeared from controller list but the other controller(now the only one) still doesn't respond.

i also tried reinstalling dotnet framework. vigeM drivers and even the xbox 360 drivers.

when i map the controller on steam it works fine but with a bit of lag and i can't use gyro in steam(coz it's triggered by gyro button or something i don't know) I kind of like the gyro for racing games.

can anybody help me.

**Comment by AhilKhan** [comment]
here's the log

02/27/2020 16:12:05: DS4Windows version 2.0.10
02/27/2020 16:12:06: Starting...
02/27/2020 16:12:06: Connection to ViGEmBus 1.16.112.0 established
02/27/2020 16:12:06: Searching for controllers...
02/27/2020 16:12:06: Using Shared Mode
02/27/2020 16:12:06: Found Controller: D0:27:98:FA:46:4C (BT) (DS4 v.2)
02/27/2020 16:12:06: Plugging in X360 Controller for input #1
02/27/2020 16:12:06: Controller 1 is using Profile "Default"

**Comment by AhilKhan** [comment]
Another log from debug version

02/27/2020 16:12:05: DS4Windows version 2.0.10
02/27/2020 16:12:06: Starting...
02/27/2020 16:12:06: Connection to ViGEmBus 1.16.112.0 established
02/27/2020 16:12:06: Searching for controllers...
02/27/2020 16:12:06: Using Shared Mode
02/27/2020 16:12:06: Found Controller: D0:27:98:FA:46:4C (BT) (DS4 v.2)
02/27/2020 16:12:06: Plugging in X360 Controller for input #1
02/27/2020 16:12:06: Controller 1 is using Profile "Default"

**Comment by AhilKhan** [comment]
A log from debug version

02/27/2020 16:14:56: DS4Windows version 2.0.10
02/27/2020 16:14:56: Starting...
02/27/2020 16:14:56: Connection to ViGEmBus 1.16.112.0 established
02/27/2020 16:14:56: Searching for controllers...
02/27/2020 16:14:56: Using Shared Mode
02/27/2020 16:14:56: DEBUG: EnumerateDS4. HID#1 Path=\\?\hid#vid_4e53&pid_5407&mi_01&col02#7&162ceb66&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant consumer control device  VID=0x4E53  PID=0x5407  Usage=0x1  Version=0x100
02/27/2020 16:14:56: DEBUG: EnumerateDS4. HID#2 Path=\\?\hid#vid_0e6a&pid_02c0&mi_00#7&3b8dccc4&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd  Description=HID Keyboard Device  VID=0x0000  PID=0x0000  Usage=0x0  Version=0x0
02/27/2020 16:14:56: DEBUG: EnumerateDS4. HID#3 Path=\\?\hid#vid_4e53&pid_5407&mi_01&col03#7&162ceb66&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant system controller  VID=0x4E53  PID=0x5407  Usage=0x80  Version=0x100
02/27/2020 16:14:56: DEBUG: EnumerateDS4. HID#4 Path=\\?\hid#vid_4e53&pid_5407&mi_01&col04#7&162ceb66&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant vendor-defined device  VID=0x4E53  PID=0x5407  Usage=0x1  Version=0x100
02/27/2020 16:14:56: DEBUG: EnumerateDS4. HID#5 Path=\\?\hid#vid_4e53&pid_5407&mi_01&col05#7&162ceb66&0&0004#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant vendor-defined device  VID=0x4E53  PID=0x5407  Usage=0x1  Version=0x100
02/27/2020 16:14:56: DEBUG: EnumerateDS4. HID#6 Path=\\?\hid#vid_0e6a&pid_02c0&mi_01&col01#7&17b68f02&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant consumer control device  VID=0x0E6A  PID=0x02C0  Usage=0x1  Version=0x321
02/27/2020 16:14:56: DEBUG: EnumerateDS4. HID#7 Path=\\?\hid#vid_0e6a&pid_02c0&mi_01&col02#7&17b68f02&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant system controller  VID=0x0E6A  PID=0x02C0  Usage=0x80  Version=0x321
02/27/2020 16:14:56: DEBUG: EnumerateDS4. HID#8 Path=\\?\hid#vid_0e6a&pid_02c0&mi_01&col05#7&17b68f02&0&0004#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd  Description=HID Keyboard Device  VID=0x0000  PID=0x0000  Usage=0x0  Version=0x0
02/27/2020 16:14:56: DEBUG: EnumerateDS4. HID#9 Path=\\?\hid#vid_0e6a&pid_02c0&mi_01&col03#7&17b68f02&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant vendor-defined device  VID=0x0E6A  PID=0x02C0  Usage=0x1  Version=0x321
02/27/2020 16:14:56: DEBUG: EnumerateDS4. HID#10 Path=\\?\hid#vid_4e53&pid_5407&mi_00#7&3a042928&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant mouse  VID=0x0000  PID=0x0000  Usage=0x0  Version=0x0
02/27/2020 16:14:56: DEBUG: EnumerateDS4. HID#11 Path=\\?\hid#vid_0e6a&pid_02c0&mi_01&col06#7&17b68f02&0&0005#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd  Description=HID Keyboard Device  VID=0x0000  PID=0x0000  Usage=0x0  Version=0x0
02/27/2020 16:14:56: DEBUG: EnumerateDS4. HID#12 Path=\\?\hid#vid_4e53&pid_5407&mi_01&col01#7&162ceb66&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd  Description=HID Keyboard Device  VID=0x0000  PID=0x0000  Usage=0x0  Version=0x0
02/27/2020 16:14:56: DEBUG: EnumerateDS4. HID#13 Path=\\?\hid#vid_0e6a&pid_02c0&mi_01&col04#7&17b68f02&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd  Description=HID Keyboard Device  VID=0x0000  PID=0x0000  Usage=0x0  Version=0x0
02/27/2020 16:14:56: DEBUG: findControllers. Found 0 possible devices
02/27/2020 16:15:04: DEBUG: EnumerateDS4. HID#1 Path=\\?\hid#vid_4e53&pid_5407&mi_01&col02#7&162ceb66&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant consumer control device  VID=0x4E53  PID=0x5407  Usage=0x1  Version=0x100
02/27/2020 16:15:04: DEBUG: EnumerateDS4. HID#2 Path=\\?\hid#vid_0e6a&pid_02c0&mi_00#7&3b8dccc4&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd  Description=HID Keyboard Device  VID=0x0000  PID=0x0000  Usage=0x0  Version=0x0
02/27/2020 16:15:04: DEBUG: EnumerateDS4. HID#3 Path=\\?\hid#vid_4e53&pid_5407&mi_01&col03#7&162ceb66&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant system controller  VID=0x4E53  PID=0x5407  Usage=0x80  Version=0x100
02/27/2020 16:15:04: DEBUG: EnumerateDS4. HID#4 Path=\\?\hid#vid_4e53&pid_5407&mi_01&col04#7&162ceb66&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant vendor-defined device  VID=0x4E53  PID=0x5407  Usage=0x1  Version=0x100
02/27/2020 16:15:04: DEBUG: EnumerateDS4. HID#5 Path=\\?\hid#vid_4e53&pid_5407&mi_01&col05#7&162ceb66&0&0004#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant vendor-defined device  VID=0x4E53  PID=0x5407  Usage=0x1  Version=0x100
02/27/2020 16:15:04: DEBUG: EnumerateDS4. HID#6 Path=\\?\hid#vid_0e6a&pid_02c0&mi_01&col01#7&17b68f02&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant consumer control device  VID=0x0E6A  PID=0x02C0  Usage=0x1  Version=0x321
02/27/2020 16:15:04: DEBUG: EnumerateDS4. HID#7 Path=\\?\hid#vid_0e6a&pid_02c0&mi_01&col02#7&17b68f02&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant system controller  VID=0x0E6A  PID=0x02C0  Usage=0x80  Version=0x321
02/27/2020 16:15:04: DEBUG: EnumerateDS4. HID#8 Path=\\?\hid#vid_0e6a&pid_02c0&mi_01&col05#7&17b68f02&0&0004#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd  Description=HID Keyboard Device  VID=0x0000  PID=0x0000  Usage=0x0  Version=0x0
02/27/2020 16:15:04: DEBUG: EnumerateDS4. HID#9 Path=\\?\hid#vid_0e6a&pid_02c0&mi_01&col03#7&17b68f02&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant vendor-defined device  VID=0x0E6A  PID=0x02C0  Usage=0x1  Version=0x321
02/27/2020 16:15:04: DEBUG: EnumerateDS4. HID#10 Path=\\?\hid#vid_4e53&pid_5407&mi_00#7&3a042928&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant mouse  VID=0x0000  PID=0x0000  Usage=0x0  Version=0x0
02/27/2020 16:15:04: DEBUG: EnumerateDS4. HID#11 Path=\\?\hid#vid_0e6a&pid_02c0&mi_01&col06#7&17b68f02&0&0005#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd  Description=HID Keyboard Device  VID=0x0000  PID=0x0000  Usage=0x0  Version=0x0
02/27/2020 16:15:04: DEBUG: EnumerateDS4. HID#12 Path=\\?\hid#vid_4e53&pid_5407&mi_01&col01#7&162ceb66&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd  Description=HID Keyboard Device  VID=0x0000  PID=0x0000  Usage=0x0  Version=0x0
02/27/2020 16:15:04: DEBUG: EnumerateDS4. HID#13 Path=\\?\hid#vid_0e6a&pid_02c0&mi_01&col04#7&17b68f02&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd  Description=HID Keyboard Device  VID=0x0000  PID=0x0000  Usage=0x0  Version=0x0
02/27/2020 16:15:04: DEBUG: EnumerateDS4. HID#14 Path=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&0002054c_pid&09cc#8&33030c4f&1&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant game controller  VID=0x054C  PID=0x09CC  Usage=0x5  Version=0x0
02/27/2020 16:15:04: DEBUG: EnumerateDS4. HID#14 detected as DS4 compatible gamepad device
02/27/2020 16:15:04: DEBUG: IsRealDS4. IsRealDS4=True  hDevicePath=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&0002054c_pid&09cc#8&33030c4f&1&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  deviceInstanceID=hid\{00001124-0000-1000-8000-00805f9b34fb}_vid&0002054c_pid&09cc\8&33030c4f&1&0000  Device_UINumber=
02/27/2020 16:15:04: DEBUG: findControllers. Found 1 possible device
02/27/2020 16:15:04: DEBUG: findControllers. Idx=0 Potential DS4 gamepad. Description=HID-compliant game controller  Path=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&0002054c_pid&09cc#8&33030c4f&1&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
02/27/2020 16:15:04: DEBUG: findControllers. idx=0 Opening device VID=0x054C  PID=0x09CC  isExclusiveMode=False
02/27/2020 16:15:04: DEBUG: findControllers. idx=0 IsOpen=True
02/27/2020 16:15:04: DEBUG: readSerial. Trying to read serial# from VendorID=0x054C, ProductID=0x09CC, Version=0, DevicePath=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&0002054c_pid&09cc#8&33030c4f&1&0000#{4d1e55b2-f16f-11cf-88cb-001111000030} InputReportLen=547
02/27/2020 16:15:04: DEBUG: readSerial. OK. HidD_GetSerialNumberString. Serial#=D0:27:98:FA:46:4C
02/27/2020 16:15:04: DEBUG: findControllers. idx=0 IsValidSerial=True  Serial=D0:27:98:FA:46:4C
02/27/2020 16:15:04: DEBUG: findControllers. idx=0 Using device \\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&0002054c_pid&09cc#8&33030c4f&1&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  metainfo.name=DS4 v.2  metainfo.featureSet=DefaultDS4
02/27/2020 16:15:04: DEBUG: DS4Device. DS4 v.2 conType=BT  MAC=D0:27:98:FA:46:4C
02/27/2020 16:15:04: DEBUG: DS4Device. Raw InputReportLen=547  OutputReportLen=547
02/27/2020 16:15:04: DEBUG: DS4Device. Current debug options: debug_HidDSetNumInputBuffers=2  debug_GyroCalibration=True  debug_GyroCalibrationType=0
02/27/2020 16:15:04: DEBUG: DS4Device. Current debug options: debug_SendRumbleLightbarData=True  debug_SendRumbleLightbarDataType=0  debug_SendRumbleLightbarDataAPI=0
02/27/2020 16:15:04: DEBUG: DS4Device. Current debug options: debug_ReadTouchpadData =True  debug_ReadGyroData=True  debug_ReadBatteryData=True
02/27/2020 16:15:04: DEBUG: DS4Device. Current debug options: debug_ForceConnectionType=0  debug_PrintoutInputDataBuffer=False
02/27/2020 16:15:04: DEBUG: DS4Device. DS4 v.2 conType=BT UsedInputReportBufLen=545 UsedOutputReportBufLen=78 synced=True runCalib=True
02/27/2020 16:15:04: DEBUG: DS4SixAxis. gyroMultiplierYaw=1  gyroMultiplierRoll=1  gyroMultiplierPitch=1
02/27/2020 16:15:04: DEBUG: RefreshCalibration. getCalibrationData and DS4ModeSwitch. conType=BT  calibDataType=5
02/27/2020 16:15:04: DEBUG: RefreshCalibration. ERROR. readFeatureData failed. conType=BT dataType=5 LastErrorCode=0
02/27/2020 16:15:04: DEBUG: RefreshCalibration. ERROR. readFeatureData failed. conType=BT dataType=5 LastErrorCode=0
02/27/2020 16:15:04: DEBUG: RefreshCalibration. ERROR. readFeatureData failed. conType=BT dataType=5 LastErrorCode=0
02/27/2020 16:15:04: DEBUG: RefreshCalibration. ERROR. readFeatureData failed. conType=BT dataType=5 LastErrorCode=0
02/27/2020 16:15:04: DEBUG: RefreshCalibration. ERROR. readFeatureData failed. conType=BT dataType=5 LastErrorCode=0
02/27/2020 16:15:04: DEBUG: RefreshCalibration. calibration found=False
02/27/2020 16:15:04: DEBUG: setCalibrationData. calibrationDone=False  FromUsb=False
02/27/2020 16:15:04: DEBUG: setCalibrationData. calibrationData[0] bias=0  sensNumer=0  sensDenom=0
02/27/2020 16:15:04: DEBUG: setCalibrationData. calibrationData[1] bias=0  sensNumer=0  sensDenom=0
02/27/2020 16:15:04: DEBUG: setCalibrationData. calibrationData[2] bias=0  sensNumer=0  sensDenom=0
02/27/2020 16:15:04: DEBUG: setCalibrationData. calibrationData[3] bias=0  sensNumer=16384  sensDenom=0
02/27/2020 16:15:04: DEBUG: setCalibrationData. calibrationData[4] bias=0  sensNumer=16384  sensDenom=0
02/27/2020 16:15:04: DEBUG: setCalibrationData. calibrationData[5] bias=0  sensNumer=16384  sensDenom=0
02/27/2020 16:15:04: DEBUG: setCalibrationData. gyroSpeed2x=0 gyroSpeedPlus+gyroSpeedMinus=(0 + 0)  yaw=0 yawPlus-yawMinus=(0 - 0)
02/27/2020 16:15:04: DEBUG: DS4Device. DS4 v.2 conType=BT IsFileStreamOpen=True
02/27/2020 16:15:04: DEBUG: findControllers. idx=0 OK. DS4Win uses the device as input source
02/27/2020 16:15:04: Found Controller: D0:27:98:FA:46:4C (BT) (DS4 v.2)
02/27/2020 16:15:04: Plugging in X360 Controller for input #1
02/27/2020 16:15:04: Controller 1 is using Profile "Default"
02/27/2020 16:15:04: DEBUG: performDs4Input. WARNING. D0:27:98:FA:46:4C crc32 check of BT input packet failed. btInputReport type0=1  type2=128
02/27/2020 16:15:04: DEBUG: performDs4Input. WARNING. D0:27:98:FA:46:4C crc32 check of BT input packet failed. btInputReport type0=1  type2=128
02/27/2020 16:15:04: DEBUG: performDs4Input. WARNING. D0:27:98:FA:46:4C crc32 check of BT input packet failed. btInputReport type0=1  type2=128
02/27/2020 16:15:04: DEBUG: performDs4Input. WARNING. D0:27:98:FA:46:4C crc32 check of BT input packet failed. btInputReport type0=1  type2=128
02/27/2020 16:15:04: DEBUG: performDs4Input. WARNING. D0:27:98:FA:46:4C crc32 check of BT input packet failed. btInputReport type0=1  type2=128
02/27/2020 16:15:04: DEBUG: performDs4Input. WARNING. D0:27:98:FA:46:4C ignoring repeating crc32 check failure. Continuing to accept input packets. btInputReport type0=1  type2=128
02/27/2020 16:15:04: DEBUG: performDs4Input. WARNING. D0:27:98:FA:46:4C unexpected BT packet type. Ignoring. btInputReport type0=1  type2=128
02/27/2020 16:15:04: DEBUG: performDs4Input. WARNING. D0:27:98:FA:46:4C unexpected BT packet type. Ignoring. btInputReport type0=1  type2=128
02/27/2020 16:15:04: DEBUG: performDs4Input. WARNING. D0:27:98:FA:46:4C unexpected BT packet type. Ignoring. btInputReport type0=1  type2=128
02/27/2020 16:15:04: DEBUG: performDs4Input. WARNING. D0:27:98:FA:46:4C unexpected BT packet type. Continuing to accept PC-friendly packets from BT connection. btInputReport type0=1  type2=128
02/27/2020 16:15:06: DEBUG: EnumerateDS4. HID#1 Path=\\?\hid#vid_4e53&pid_5407&mi_01&col02#7&162ceb66&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant consumer control device  VID=0x4E53  PID=0x5407  Usage=0x1  Version=0x100
02/27/2020 16:15:06: DEBUG: EnumerateDS4. HID#2 Path=\\?\hid#vid_0e6a&pid_02c0&mi_00#7&3b8dccc4&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd  Description=HID Keyboard Device  VID=0x0000  PID=0x0000  Usage=0x0  Version=0x0
02/27/2020 16:15:06: DEBUG: EnumerateDS4. HID#3 Path=\\?\hid#vid_4e53&pid_5407&mi_01&col03#7&162ceb66&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant system controller  VID=0x4E53  PID=0x5407  Usage=0x80  Version=0x100
02/27/2020 16:15:06: DEBUG: EnumerateDS4. HID#4 Path=\\?\hid#vid_4e53&pid_5407&mi_01&col04#7&162ceb66&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant vendor-defined device  VID=0x4E53  PID=0x5407  Usage=0x1  Version=0x100
02/27/2020 16:15:06: DEBUG: EnumerateDS4. HID#5 Path=\\?\hid#vid_4e53&pid_5407&mi_01&col05#7&162ceb66&0&0004#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant vendor-defined device  VID=0x4E53  PID=0x5407  Usage=0x1  Version=0x100
02/27/2020 16:15:06: DEBUG: EnumerateDS4. HID#6 Path=\\?\hid#vid_0e6a&pid_02c0&mi_01&col01#7&17b68f02&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant consumer control device  VID=0x0E6A  PID=0x02C0  Usage=0x1  Version=0x321
02/27/2020 16:15:06: DEBUG: EnumerateDS4. HID#7 Path=\\?\hid#vid_0e6a&pid_02c0&mi_01&col02#7&17b68f02&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant system controller  VID=0x0E6A  PID=0x02C0  Usage=0x80  Version=0x321
02/27/2020 16:15:06: DEBUG: EnumerateDS4. HID#8 Path=\\?\hid#vid_0e6a&pid_02c0&mi_01&col05#7&17b68f02&0&0004#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd  Description=HID Keyboard Device  VID=0x0000  PID=0x0000  Usage=0x0  Version=0x0
02/27/2020 16:15:06: DEBUG: EnumerateDS4. HID#9 Path=\\?\hid#vid_0e6a&pid_02c0&mi_01&col03#7&17b68f02&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant vendor-defined device  VID=0x0E6A  PID=0x02C0  Usage=0x1  Version=0x321
02/27/2020 16:15:06: DEBUG: EnumerateDS4. HID#10 Path=\\?\hid#vid_4e53&pid_5407&mi_00#7&3a042928&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant mouse  VID=0x0000  PID=0x0000  Usage=0x0  Version=0x0
02/27/2020 16:15:06: DEBUG: EnumerateDS4. HID#11 Path=\\?\hid#vid_045e&pid_028e&ig_00#3&b8a95ad&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant game controller  VID=0x045E  PID=0x028E  Usage=0x5  Version=0x0
02/27/2020 16:15:06: DEBUG: EnumerateDS4. HID#12 Path=\\?\hid#vid_0e6a&pid_02c0&mi_01&col06#7&17b68f02&0&0005#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd  Description=HID Keyboard Device  VID=0x0000  PID=0x0000  Usage=0x0  Version=0x0
02/27/2020 16:15:06: DEBUG: EnumerateDS4. HID#13 Path=\\?\hid#vid_4e53&pid_5407&mi_01&col01#7&162ceb66&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd  Description=HID Keyboard Device  VID=0x0000  PID=0x0000  Usage=0x0  Version=0x0
02/27/2020 16:15:06: DEBUG: EnumerateDS4. HID#14 Path=\\?\hid#vid_0e6a&pid_02c0&mi_01&col04#7&17b68f02&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd  Description=HID Keyboard Device  VID=0x0000  PID=0x0000  Usage=0x0  Version=0x0
02/27/2020 16:15:06: DEBUG: EnumerateDS4. HID#15 Path=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&0002054c_pid&09cc#8&33030c4f&1&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant game controller  VID=0x054C  PID=0x09CC  Usage=0x5  Version=0x0
02/27/2020 16:15:06: DEBUG: EnumerateDS4. HID#15 detected as DS4 compatible gamepad device
02/27/2020 16:15:06: DEBUG: IsRealDS4. IsRealDS4=True  hDevicePath=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&0002054c_pid&09cc#8&33030c4f&1&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  deviceInstanceID=hid\{00001124-0000-1000-8000-00805f9b34fb}_vid&0002054c_pid&09cc\8&33030c4f&1&0000  Device_UINumber=
02/27/2020 16:15:06: DEBUG: findControllers. Found 1 possible device
02/27/2020 16:15:06: DEBUG: findControllers. Idx=0 Potential DS4 gamepad. Description=HID-compliant game controller  Path=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&0002054c_pid&09cc#8&33030c4f&1&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}

**Comment by mika-n** [comment]
Hmm... Interesting. In the first post you mentioned that you have 3rd party DS4 gamepad (ie. not the official Sony model). The interesting part is that the debug logfile shows VID/PID hardware identifier as it was an official Sony revision 2 ds4 gamepad device. Veeery suspicious. 

Does the gamepad work with the debug version of DS4Windows app? The log file shows number of warnings but the debug version tries to recover from those automatically. Are button and stick activity shown in JOY.CPL controlPanel applet or in ControllerReadings tab page of DS4Windows (debug) app?

How about lightbar and rumble? Are those working with debug version? You can test these in DS4Windows profile editor.

However, you could try following option in DS4WindowsDebug.exe.config configuration file (edit in Notepad while DS4Win app is closed). This instructs the debug version to try alternative way to calibrate gyro in BT connection mode. If this doesn't fix gyro calibration warnings then you can ignore those messages (it is not fatal error. Some 3rd party ds4 compatible gamepads don't support gyro calibration).
`Debug_GyroCalibrationType=1`

What is the model and type code on the back of the gamepad? Do you have a link to some webstore page where you purchased the gamepad? It is quite uncommon to have an after market ds4 gamepad with the same VID/PID hardware type code as official Sony gamepads. Usually after market gamepads have their own VID/PID code.

**Comment by AhilKhan** [comment]
Currently its working with the debug version. But I can't use gyro and rumble. 

My controller does have Gyro coz i do use gyro over USB connection. I can't undertsand why that can't work over bluetooth but that's fine.

By the way my Controller is a Cosmic Byte Stratos Xenon

https://www.thecosmicbyte.com/cosmic-byte-stratos-xenon-ps4-wireless-gamepad-with-turbo-function-and-programmable-buttons-black?gclid=Cj0KCQiAkePyBRCEARIsAMy5ScsYG9199GfWkTCnKPRTn4Fe2x1Atxo9_i2pwwqhZiPSnq7fR2KG31MaAj_4EALw_wcB

**Comment by mika-n** [comment]
Nice looking gamepad with a bit different RS-stick placement and built-in four back buttons. What kind of operations you can program to those 4 back buttons? 

There is one thing you could try while connecting over BT. Please try following DS4WindowsDebug.exe.config option:
```
Debug_GyroCalibration=true
Debug_GyroCalibrationType=1
Debug_SendRumbleLightbarDataType=1
Debug_SendRumbleLightbarDataAPI=1
```

If those two options still not work then add this option:
`Debug_ForceConnectionType=1`

Remember to close DS4WindowsDebug.exe app when modifying the xxx.exe.config file.

If this doesn't work then it may be a bit too difficult to debug this without an actual hardware, so I guess you have to continue to use the usb connection or try to debug it yourself (if you are familiar with .NET and HID input device programming).

**Comment by AhilKhan** [comment]
On those back buttons one can program any button from the controller (except the turbo and maybe the PS button)

By the way do I have to replace any lines with these ones or just enter them at the end of doc? 
I'm not at all familiar to HID programming

**Comment by mika-n** [comment]
Just replace the value of existing options, dont add any new lines.

**Comment by rushtothesun** [comment]
This may not be related but I had a similar issue with regards to Final Fantasy 13 not accepting any input from my DS4 controller while it was connected by Bluetooth. I fixed this by going to game controllers in the control panel, clicking advanced, and then selecting the controller that works in the box under preferred device.

**Comment by mika-n** [comment]
@rushtothesun  Do you mean that that "preferred controller" option in JOY.CPL controlPanel applet worked without using exclusive mode? Hmmm.... Intresting....
