### ISSUE TITLE
Autoupdater, Have the Zip Folders Named Appropriately

### ISSUE THREAD

**Issue by shinra358** [Ryochan7/DS4Windows#113]
When updating, the zip folder says update.zip which doesn't tell us which version this is and they one would end up going to the website anyway to download one with the version writen as the .zip name. I would like for the zip name to be the same as it is when downloading from this site.

**Comment by Ryochan7** [comment]
I am not sure if there is a need for this. Although the output file name is generic, the file is only used temporarily and should be deleted after the update process is finished. Update.zip would then just imply newest. Anyone wanting to keep an archive of the zip file or grab a specific version of DS4Windows should download it from GitHub. The old standard that was in place for the updater seemed to work fine. There didn't seem to be need to change the updater beyond replacing urls and taking an extra newline in the version.txt file into account. It probably wouldn't take much work to change this functionality though.

**Comment by shinra358** [comment]
the file does not autodelete. also, it is good practice to keep installer zips along with the program in case something happens. Yes that is the whole point to not have to go to a website to keep up with versions. To keep up with versions just in case something goes wrong, if just going to the website is the solution, then there is no point for the autoupdate feature.

**Comment by jtcmedia** [comment]
Alternatively, you could use chocolatey for auto-updating https://chocolatey.org/packages/ds4windows/

**Comment by Ryochan7** [comment]
Finally got around to working on this. The updater will download the zip file with the original file name. Also, the updater will not delete the archive after the update is complete. However, any applicable archive will be deleted upon the next run of DS4Updater.exe

**Comment by shinra358** [comment]
Should leave zip alone if there is no update to be found. Currently it deletes zip nomatter what. I went to revert aftr new version's xinput isnt working and now I cant because the program deleted my backup zip.

I think a better option would be to ask if you want the new version to be backed up and if yes is chosen, it gets put in a backup folder and left alone. And if no is pressed, zip gets deleted after update is complete.

**Comment by Ryochan7** [comment]
Finally got around to updating the DS4Updater again. The default behavior with the latest updater is to download the DS4Windows archive to your Downloads folder and extract the contents in the DS4Windows application folder. The updater will not delete the archive at any point if it is stored in the Downloads folder. That type of routine is good enough for FileZilla so that should work fine for DS4Windows.

**Comment by shinra358** [comment]
cool

**Comment by shinra358** [comment]
i see an 'update files' folder with ds4 windows exe in there but there is no zip and it is not named so I don't know what version it is. Do we make the 'download' folder ourselves or is the app supposed to create it?

**Comment by Ryochan7** [comment]
The updater now uses your Windows user's Downloads folder. The location can be determined by checking the output of %USERPROFILE%\Downloads from the command prompt (C:\Users\ryoch\Downloads on my system). You can also type the location with the environmental variable in the Explorer location bar and it will go to your user's Downloads folder.

**Comment by shinra358** [comment]
Thats not good because it takes away from from the portability it was
intended with. Just like with the config files, they only go in the windows
folders if the program is in the windows program files. If its in a non
windows folder, its supposed to stay in its own folder. Thats one thing
that makes this miles better than inputmapper. If we are testing, its gnna
be tedious to navigate all the way there as well. I was expecting the
downloads folder would be made in ds4s own folder.

**Comment by shinra358** [comment]
I also never install on my system drive. Because if i have to reinstall to
fix a problem, itll only be an hour instead of 8 to get my system back up
and running. Ive even made programs to put pc game saves in their own
folder when not in use to keep my pc clean and fresh if krossx's save
relocator doesnt wrk for a game. Us gamers and enthusiasts dnt like hour
files for one program spread out all over the hdd thats all. Its just more
convenient and hassle free that way.

**Comment by Ryochan7** [comment]
Besides using FileZilla as an example, the main reason for using that folder instead of creating one is that it should be available for all Windows user's. Personally, I have found the "portable" aspect of DS4Windows to be more of a problem than an asset. There is plenty of behavior that really disqualifies DS4Windows as a truly portable application; needing admin privileges for some necessary features and the installation of the ScpVBus driver (and later HidGuardian) makes it so that DS4Windows can never truly be portable. Having profiles and settings contained within the DS4Windows folder is helpful though. I didn't want to add non-application files under the DS4Windows folder. Having an archives folder stored there did not seem to be a good idea at the time.

**Comment by shinra358** [comment]
Launchbox or gedosato are good examples of how what was originally asked is
done. Scp is a driver so it is expected that it installs its things where
it does. This is one of the reasons why everyone hates standalone bsnes.
Because Byuu expects ppl to put your roms in the appdata folder. Navigating
to windows download folder takes the same amount of time of just going to
download. Yes, youll have trouble with things bcuz of uac if you have ds4
in a windows folder which is why i have all my programs installed to a user
made program files folder that isnt controlled by the system, therefore no
uac troubles. This is why the original author made an if/else statement
saying if its not on a system controlled space, put in its own folder and
if it is, put it in the windows system folder. You probably had trouble
with this because you have ds4windows in the location that triggers the
uacs, on the system drive.

**Comment by Ryochan7** [comment]
I should mention that the latest version of the updater now places zip archives in its own subfolder within the DS4Windows folder; the folder is named Updates. Archives are not deleted by the application so that folder requires manual maintenance if you do not need access to older archives.

**Comment by shinra358** [comment]
Thanks
