### ISSUE TITLE
Macro type suggestion

### ISSUE THREAD

**Issue by joshuafrank77** [Ryochan7/DS4Windows#1131]
I was looking at macros and Iven't seen any macro that does the following:

Once the macro trigger is tap it will repeat the macro until the macro trigger is pressed again with a delay between each iteration, for example the macro trigger will do a jump and it will keep jumping every 1000 ms while jumping i can move the sticks L and R while still jumping every 1000 ms it will keep jumping until i tap again the macro trigger

**Comment by mika-n** [comment]
The current macro system doesn't support this kind of "repeated" execution, but I can see how this might be useful in some scenarios in Fortnite to gain unfair advantage :-)

**Comment by Ryochan7** [comment]
I have never liked the way the macro system is designed. It is mainly left in for compatibility with older profiles.
