### ISSUE TITLE
Toggle mouse click doesn't work

### ISSUE THREAD

**Issue by arifinmnur** [Ryochan7/DS4Windows#1132]
Toggle mouse click(LMB/RMB) doesn't work. It is bug? run fine if toggle of keyboard keys, just mouse click won't toggle

Example : 
when I click R3 buton on joystick, it will trigger for hold/toggle Right Mouse Click. 
but it doesn't work for holding mouse click
![Capture](https://user-images.githubusercontent.com/31398297/75775651-fd012b80-5d84-11ea-90c7-f55124bc8fe9.PNG)

**Comment by Ryochan7** [comment]
Did mouse button toggle work in older versions of DS4Windows? AFAIK, that option only applied to keyboard keys and I know that mapping works as I have used it in a profile recently. I'll take a look at the old behavior.

**Comment by Ryochan7** [comment]
Double checked. That option was only usable when mapping keyboard keys. The behavior has not changed with the WPF releases.
