### ISSUE TITLE
DS4 Windows Fifa 20 frame drop

### ISSUE THREAD

**Issue by Vitocorl** [Ryochan7/DS4Windows#1133]
I am using Version 2.0.11 to connect a Sony Dual-shock 4 V2 controller. Whenever i start DS4 Windows and then play Fifa 20 i get a 15 to 20 frame drop and the game is unplayable. If i stop DS4 Windows from running, the game plays fine and everything works flawlessly....
Are there any optimizations i should do, in order to avoid this problem? I have tried to hide the DS4 controller, but i guess this setting has nothing to do with the actual frame drop.

**Comment by Ryochan7** [comment]
The only advice that I have would be to make sure DS4Windows has Exclusive Access to the DS4 controller. It is pretty much mandatory with the FIFA games.

**Comment by Vitocorl** [comment]
You mean to hide DS4 controller from the settings, or use HIDGuardian (or both)?

**Comment by Ryusennin** [comment]
The problem with FIFA games (and many others) is that they listen to both the physical and virtual controllers, which means double inputs and possibly performance drops.

If the built-in hide option (which is a old hack) doesn't work for you, you should try installing HidGuardian (which is much more reliable). Disable the hide option in that case, as they're mutually exclusive.

**Comment by mika-n** [comment]
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

**Comment by Ryochan7** [comment]
I just tried the FIFA 20 Demo and it worked on my system fine while using DS4Windows.

**Comment by Vitocorl** [comment]
The controller is working in exclusive mode, DS4 Windows Log is showing that. I do not have a problem with double inputs, DS4 controller is working perfectly in game, however, every time i start the program i have a frame drop. I am using now x360ce and Dualshock 4 is working without frame drops in Fifa 20. Maybe the drops when i am using DS4 Windows are due to my PC being old and not being able to handle such a game....

**Comment by Ryochan7** [comment]
One other piece of advice that I can give is for you to adjust the BT Poll Rate set in a profile. Especially if you are playing with a wireless connection and using the Max poll rate (~1 ms), it will naturally cause DS4Windows to use a good amount of CPU time and take resources from other programs. A wired USB connection has a poll rate around 4 ms so maybe you can try running DS4Windows with a wired DS4 and see if the situation improves.

My PC barely meets the minimum requirements for FIFA 20 and it runs well with DS4Windows running. It feels like I am getting a consistent 60 FPS but I would need to run Fraps or some other frame rate counter to confirm. I should also mention that I was using the Sony Wireless Adapter during my testing and that has a fixed poll rate of 8 ms. I will test it with a BT connection in a bit.

**Comment by Ryochan7** [comment]
Tested it out. Even when using the Max BT Poll Rate with a BT connection, FIFA 20 runs fine on my system. Load times seem to be a bit longer when using Max Poll Rate rather than 4 ms but that is not unexpected.
