### ISSUE TITLE
cant run ds4

### ISSUE THREAD

**Issue by NessaCrona** [Ryochan7/DS4Windows#1135]
there is no application to run its just a bunch of png's even the readme isnt a readable file

**Comment by mika-n** [comment]
We are not psychics with a x-ray vision, so it is hard to tell what you have downloaded and from where. 
 See the "Link list" on the Troubleshooting page and make sure you have downloaded the correct app packages. 
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting

**Comment by NessaCrona** [comment]
I downloaded version 2.0.11 from github with the latest version of HIDGuardian and followed the install guide until the point where it told me to run the program, which i cant, because none of the files are runnable programs/executables.
even the readme isnt even a readable file.

I owuld have thought all of this would have been incredibly obvious

**Comment by NessaCrona** [comment]
ok so I was running an old version before and the new one is working

sorry for being retarded and stuff

**Comment by Ryochan7** [comment]
> sorry for being retarded and stuff

LOL

![zoomer_tide](https://user-images.githubusercontent.com/581968/76144316-91e57c80-6044-11ea-8ec7-90c535968bc5.gif)

**Comment by Ryochan7** [comment]
Opened a can of worms when I dissed DSP apparently. The whale chairs that watch his streams.
