### ISSUE TITLE
Wireless Network crash on Bluetooth connection

### ISSUE THREAD

**Issue by Kaytsey** [Ryochan7/DS4Windows#1137]
This is a really weird one. As of version 2.0.11 my router shuts down completely, every time I connect my DS4 via Bluetooth.

**Comment by Ryochan7** [comment]
There is something wrong outside the control of DS4Windows. Hopefully you find what the problem is with your router.

**Comment by mika-n** [comment]
I don't see how DS4Windows app or DS4 gamepad could do something like that even in a theoretical level. Only thing DS4Windows app does with network is to check an updated version. You can disable this setting in DS4Windows option but dont see how it could crash a router.

**Comment by chandrachur-mallick-693** [comment]
I am also facing the same issue. My wireless network crashes whenever I am using the ps5 controller via bluetooth
