### ISSUE TITLE
Macros affecting multiple controllers

### ISSUE THREAD

**Issue by magmadragoon** [Ryochan7/DS4Windows#114]
Hi!

When I connect 2 DS4 controllers and use a macro command on any one of them, the recorded action will be performed by both controllers. In other words, when P1 uses a macro in a game, P2 will do the same button combination even though he didn't press anything.

Macros can't be deleted from specific profiles, when added or deleted it works globally.
They can be unticked on specific controllers but it doesn't help. Unticking the macro on P2 doesn't allow the P2 to use it, but P1 using it will still trigger the same action from P2.

Can this be fixed?

**Comment by magmadragoon** [comment]
Tried deleting the macro from pad 2 profile pad under the <ProfileActions>, didn't help.
Any advice on what else I could try to fix this?

**Comment by Ryochan7** [comment]
Macros only work for generating keyboard and mouse events; it seems there is supposed to be controller button support but it has never worked. There is no separate device distinction when generating keyboard and mouse events. There is nothing in the code that seems to indicate that a macro will be executed for all controllers; it does seem that it should only be for the controller that executes the macro.

The macro system in DS4Windows is not very good and I don't even bother using it. Making anything useful would probably require completely breaking existing macro support and rewriting the whole system.

**Comment by magmadragoon** [comment]
I'm really sorry to hear that. I thought the macro system is actually really good when using just one controller. The macro recording feature is impressive, easy to edit and reads gamepad inputs well. In comparison, InputMapper has very limited macros.

If only macros didn't affect all connected controlers. That's really weird, since the built in command for disconnecting controllers from bluetooth (PS+options) works fine and disconnects the controller that actually pressed the buttons.

I wonder if this bug only happens with recoreded gamepad macros. I wish I could test it with some keyboard combinations but can't really think of a situation where the same keyboard button would affect 2 players in a game...

**Comment by Ryochan7** [comment]
I only recently got a second controller (DS4 v2) so I can test this out now. Special action macros are working as expected for me when using the same profile with different controllers.
