### ISSUE TITLE
Controller detected, but no status or battery level

### ISSUE THREAD

**Issue by NoaLou** [Ryochan7/DS4Windows#1140]
I just downloaded this newer version since the Jay version doesn't work anymore. I installed the ViGEmBus driver and it "detects" my DS4 controller, yet it doesn't show a battery level, the light of the controller doesn't work and the controller doesn't work in-game. Have I done something wrong? I tried rebooting, unplugging the controller, this doesn't work of course. I'm a noob so please use simple language in your answer. Thanks in advance!
![DS4NotWorking](https://user-images.githubusercontent.com/61940908/76164866-81232c80-6152-11ea-874d-a95e254eb349.png)

**Comment by mika-n** [comment]
What kind of gamepad you have? Official Sony DS4 gamepad or some DS4 compatible model?

Please post the logile or content of the Log tab page (you can press Export button there to save the Log tabpage content as text file).

Anyway. There has been in the past few similar reports even with official Sony DS4 gamepads. Those cases have turned out to be broken/incomplete usb cable issues (or even usb port in the gamepad broken). Try different usb cable. I have several mobile phone usb cables which can charge the DS4 gamepad but doesn't actually work (ie. the cable supplies only charging signals but not all required data lines).

**Comment by Ryochan7** [comment]
I really need to add a name column in the next update. We would need to know exactly which type of DualShock 4 controller you are attempting to use. I can only directly support first party Sony DS4 controllers.

**Comment by NoaLou** [comment]
Thank you for replying already! I reinstalled everything to make sure, but the problem persists. To answer your questions: I use an official Sony DS4 Gamepad with a working USB Cable. I can confirm both the gamepad and the usb cable work, because Rocket League on pc is one of those few games that you can play with a DS4 without needing any kind of software (not even the steam ds4 controller support, which doesn't work by the way for me). The log won't tell you much I'm afraid, here it is anyway. I can try the bluetooth connection method, but doesn't that mean I'll lose my connection with my actual Playstation 4? Just checking before I possibly ruin something.

I also want to add that my pc actually acknowledges that an "Xbox 360 Virtual Controller" is ready to use, just like in the DS4Windows I used from Jay. The only difference is of course that there isn't any light working on my controller, DS4 Windows isn't showing a battery level and the controller itself doesn't work in a game where it used to work before Jays version stopped working. Hope this information helps.
[log1.txt](https://github.com/Ryochan7/DS4Windows/files/4303910/log1.txt)

**Comment by mika-n** [comment]
If you bluetooth pair the controller with PC then the gamepad does work with PS4 also, but you have to re-pair it with PS console (ie. connect it via usb cable and PS4 will automagically pair it. After that it works again in PS4 console over BT).

When you connect the gamepad over USB cable and DS4Windows application is NOT running then what do you see in JOY.CPL controlPanel applet in WindowsOS? Run JOY.CPL command. Does it list "Wireless Controller"? Does it register all button presses normally?

If you have used JayKings version then maybe there are still left overs from the old ScpVBus driver laying around in the PC? VigEm driver has problems if ScpVBus is still there. Here are couple links to tools and instructions to uninstall the old ScpVBus driver. The first link and tool there is the easiest way to uninstall ScpvBus.
https://github.com/Ryochan7/DS4Windows/issues/1105#issuecomment-585112395
https://forums.vigem.org/topic/250/scptoolkit-removal-guide

**Comment by NoaLou** [comment]
Sorry, nothing works. 

1. I cannot pair my controller via Bluetooth, dunno why. I follow the correct steps, the white light starts flashing on the controller, yet the controller does not appear in the "add" screen of my Pc's bluetooth.

2. If I run the joy.cpl command, it lists "Wireless Controller" and all buttons register normally.

3. I also followed the steps to remove the scpdriver, there was only a little piece left.

The same problem persists. Is there no other way to make this work? Even a different program if I'm the special case where DS4Windows just isn't the solution somehow? 

I also tried steam's controller support, even that doesn't work. It recognises my controller, but I cannot change any settings, there is never any light burning, I can't use the controller in steam itself and in a game, nothing happens when I try using my controller.

The controller itself works fine though, because I can still use it in Rocket League and on my ps4.

**Comment by mika-n** [comment]
You could download the special DS4WindowsDeviceDetect debug version and provide the logfile it generates. It shows a lot more detailed messages about gamepad connection issues.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

The gamepad itself has also a reset button on the back of the pad (small hole you can press with a paperclip). It resets the gamepad and forgets all existing BT pairing information in case it causes conflicts when trying to pair the pad. When you try to pair the pad in PC then did you press "Add bluetooth device" button and then selected the "Bluetooth" device type option?

**Comment by NoaLou** [comment]
Sorry but I'm giving up, there isn't anything wrong with my gamepad, it worked fine on the previous DS4Windows. In my case it's the program that isn't working for me personally. I'm just gonna start gaming with my Xbox360 controller again. Thanks anyway for trying to help and good luck with the project

**Comment by mika-n** [comment]
Did you try to run the DS4WindowsDeviceDetect debug version I linked in the previous post? It might tell us more info about what's going on between the gamepad and PC.
