### ISSUE TITLE
Vibration works for half a second then stops.

### ISSUE THREAD

**Issue by AkrumQassem** [Ryochan7/DS4Windows#1142]
So I just had a windows update (10th March 2020), and coincidentally a Rocket League update on the same day. And now there's a problem with vibration.
Supposedly when you hold boost the controller keeps vibrating lightly, but now after the updates it vibrates for like half a second then stops completely.

Things I've tried:
- stop and start DS4windows
- change profile
- restart pc
- reinstall  ViGEmBus drivers
- make sure the Rumble setting is set to 100% and 0 seconds (tried to make it 8 seconds, nothing  changed)
- re-plug controller

Any ideas?

**Comment by mika-n** [comment]
Have you experienced the same in other games? When you press "Test Rumble" in DS4Windows then does it keep rumbling until you press Stop key (if rumble timeout is set to zero)?
Exclusive mode (=Hide DS4 Controller option in DS4Windows) or HidGuardian in use? Sure that it works? (ie. the original physical controller hidden rom Rocket League)

Anyway. This sounds like a game specific issue.

**Comment by AkrumQassem** [comment]
Yep, I'm a moron, just checked the patch notes of the latest update to Rocket League and found this.
My bad, I should've checked before posting.

![image](https://user-images.githubusercontent.com/47395272/76430130-03b12380-63c1-11ea-9cfd-03777dff8db5.png)
