### ISSUE TITLE
Invert mouse scroll on 2.0.12

### ISSUE THREAD

**Issue by fefo-dev** [Ryochan7/DS4Windows#1145]
Unless I am very mistaken there's no option to invert scrolling direction on the touchpad, and I faintly remember it existing in the past (Jays maybe). The "Invert" box doesn't seem to affect either scrolling or pointer direction, should it do so.

Bug or feature, would you mind giving it a look?

Thanks as per usual.

**Comment by Ryochan7** [comment]
The invert mouse options were more meant for Slide rather than Scroll. I will look into but I just discovered a related program crash as well.

**Comment by Ryochan7** [comment]
The backend code does not take invert into account for the Mouse Scroll function. Also, the old Jays2Kings build did not have the invert option for the Touchpad at all.

**Comment by fefo-dev** [comment]
Sorry for the late response, spotty internet lately.

Thanks for correcting me, I'll be waiting for this on a future release then.
