### ISSUE TITLE
Controller readings tab work for the first Controller only

### ISSUE THREAD

**Issue by LDami** [Ryochan7/DS4Windows#1149]
Hello,

In the "Controller readings" tab in the profile edition menu, we can only see the sensors from the first controller who has been connected.

This tab should appears for each controller (or by double-click on the controller we want to check ?).

Thanks for this amazing tool,

Regards,
Damien

**Comment by Ryochan7** [comment]
That is the intended behavior. When you select "New Profile" or "Edit" from the Controllers tab, the Profile Editor will read from the controller slot that was highlighted before the editor was opened. If you select a profile from the Profiles tab then DS4Windows will read from the first controller.
