### ISSUE TITLE
DS4 shutdown dont work as expected (bluetooth)

### ISSUE THREAD

**Issue by farebord** [Ryochan7/DS4Windows#115]
So, I got everything working just fine except ds4 shutdown. When I press my combo for disconnect, it doesnt power off the device. 

Sorry for my poor english.

**Comment by Ryochan7** [comment]
Which version of DS4Windows are you running? Is there any message in the Log tab after attempting to disconnect? The Disconnect BT special action works fine on my system using version 1.4.94.

**Comment by farebord** [comment]
DS4 1.4.92. The first time I pair with the DS it work just fine, after I reboot my machine and pair it, the combo didnt work anymore.
