### ISSUE TITLE
Black Desert Online strange behaviour wasd

### ISSUE THREAD

**Issue by Qumojo** [Ryochan7/DS4Windows#1156]
Not sure why this is happening in this game, but when I assign wasd to analogue stick, ingame is reflected as if I am jumping (double tapping w,a,s or d) when moving from one direction to the other. I know the game isn't controller friendly as it only works well with xbox controllers as stated by devs and only recently was updated to work with them correctly. 
Is there any way to set up ds4windows to account for 8 directions only when wasd is mapped to analogue sticks? Like, from -22,5" to 22.5" degrees only "W" would be pushed, 22.6" to 67,5" both "W" and "D" are pushed, and so on? Would that be even possible? Thanks a lot for your hard work, much appreciate.

**Comment by mika-n** [comment]
LS/RS re-mapping from analog behaviour to digital dpad (or keyboard) mapping is not that clever (at least not yet). I'm not sure if you can minimize the issue by playing around with LS/RS square stick and output curve options.
