### ISSUE TITLE
display issue with the french translation

### ISSUE THREAD

**Issue by aurelbdx** [Ryochan7/DS4Windows#116]
Hi,

I have these display issues when I use the french translation
https://www.dropbox.com/s/wqq8bpc0wrt6pcr/DS4windows.JPG?dl=0

thanks

**Comment by Ryochan7** [comment]
I cannot fix problems with the translation files. The GUI is fairly rigid so I am not surprised that longer strings of text would break the control layout. There is likely a way to make the interface more fluid to correct situations like this but I have not looked into it.

**Comment by aurelbdx** [comment]
Thanks for your answer
