### ISSUE TITLE
Feature request: Multiple Shift Modifiers

### ISSUE THREAD

**Issue by nr1995** [Ryochan7/DS4Windows#1160]
I was just thinking,
shouldn't there be multiple shift modifiers possible for a single button?
Just like how you can choose multiple triggers for your gyro?
An example:
I'm trying to set up **_RE2 Remake_** the same as good ol' **_Resident Evil 4_**.
That means I need X (PS4) to be A (360).  No problem.
But I also need X to be [Attack] when I'm holding down R2.  Still fine.
But I _also_ need X to be [Attack] when I'm holding L1 for the knife.
And at the moment, unless I'm missing something, that doesn't seem possible.
Possible feature addition in the future?

**Comment by TheSpiced** [comment]
I just hit this same roadblock in a different game.  The game doesn't allow the use of combo button presses for it's hotkeys, so I have to get creative with shift modifiers within the controller, only allowed 1 shift per button really limits what the user can do while customizing profiles.

**Comment by nr1995** [comment]
I know, right?
You don't even think of it until you want to do it,
then you can hardly believe it doesn't exist.

**Comment by mika-n** [comment]
Multiple shift-modifiers have been suggested before and maybe some day. 

Anyway, maybe you could play around and try to be creative with different profiles and "load a profile" special action macro key?  For example "Mode 3" (see the link below) is a sort of like "shift modifier for the whole profile". You could have slightly different profile bind in R2 and L1 keys.
https://github.com/Ryochan7/DS4Windows/wiki/Settings#how-to-change-a-profile-on-the-fly-via-a-certain-gamepad-button-using-a-special-action

**Comment by Ryochan7** [comment]
For my use case, getting XInput emulation working better was much more important than adding more mapping options. Also, the backend code and structure is not that flexible so I am a bit leary when it comes to changing the mapping routine.

I would like to make a different mapper at some point that would hopefully be more flexible. My vidya goal for 2020 is to make a mapper capable of the control scheme I want to play Elder Scrolls: Oblivion with a controller. I was able to do it with my old project so it is definitely doable. Mouse emulation is now better in DS4Windows so it would be easier to navigate the game if advanced functions like Holds and Action Sets were possible.

This is my minimal progress playing around with mapper ideas. Probably going to have to start from scratch again.

https://github.com/Ryochan7/mappingtest

**Comment by TheSpiced** [comment]
For me personally, I'm not freaking out demanding this  be added right now. I'm a dev myself and I know different routes need to be taken for the end goal of the project to be reached. I just wanted to voice my opinion on a feature that I would 100% use as i got more comfortable with the program, and to add a little more to the voice behind the request.  Love the program for what it does already, if this gets added in the future, it would be even greater, at least for me.
