### ISSUE TITLE
UI not showing

### ISSUE THREAD

**Issue by Hetsumani** [Ryochan7/DS4Windows#1162]
Hi, 
I'm not sure what happened, the UI stopped showing, but the app functions normally otherwise. 
I redownloaded it just to make sure, but it didn't fix it.

UPDATE: I deleted the AppData folder and that fixed it.  I'm attaching the files that cause the problem, maybe they can help solve the bug. 
[DS4Windows.zip](https://github.com/Ryochan7/DS4Windows/files/4364536/DS4Windows.zip)

**Comment by mika-n** [comment]
The problematic settings are probably the following entries in Profiles.xml file:

```
  <formLocationX>2531</formLocationX>
  <formLocationY>1300</formLocationY>
```

Do you have multiple monitors or extended virtual desktop? Anyway. Don't know how these values end up in your proiles.xml file, but the window probably ended up to non-visible part of the desktop. DS4Windows tries to remember the last position of the main window.
