### ISSUE TITLE
Headphone jack issue

### ISSUE THREAD

**Issue by Wheezbeck** [Ryochan7/DS4Windows#1164]
Been using ds4windows since November and it has worked on every game with no issues and when the battery dies in my controller I plug it in with no interruptions. Today for some reason I plugged it in when the battery was dieing and my audio output and input on the ds4 just completely disappeared. Also COD warzone won't recognize the controller over Bluetooth. Any help is appreciated.

**Comment by Ryochan7** [comment]
Sounds like a conflict as the BT connection and USB connection are seen as two separate devices in Windows. Pretty sure the audio would get muted when the BT controller first vibrates or the lightbar color changes. Having the controller plugged in via USB at the same time as using a BT connection is not a reliable way to have audio working for a BT connection.

If you want audio then you have to disconnect from BT and only use a wired USB connection.

**Comment by Wheezbeck** [comment]
Yep Bluetooth is long gone at this point. I have a dongle. No built in BT. Been trying to troubleshoot with no luck. I think I'm just going to uninstall and reinstall at this point.
