### ISSUE TITLE
Default profile values different than suggested?

### ISSUE THREAD

**Issue by KMixa** [Ryochan7/DS4Windows#1165]
One quick question from me. In a setting post found here: https://github.com/Ryochan7/DS4Windows/wiki/Settings

It says that recommended values for DeadZone should be:

LS: 0.09
RS: 0.09
L2: 0.30
R2: 0.30

But in latest version of DS4Windows, those values are:

LS: 0.08
RS: 0.08
L2: 0.00
R2: 0.00

So, should we adjust L2 and R2 values or default profile is more accurate than the suggested settings in that link I posted? What should be more accurate, those values from that link, or values in default profile in program?

**Comment by mika-n** [comment]
Well, just like in almost all freeware apps this app is not an exception. Documentation is something which will be done/updated/improved when "there is a better time". I guess you know when that time comes? So, just trust the code even if "the official" document seems to say something else.

**Comment by KMixa** [comment]
Ok, thanks for clarification this. Then default profile will be used. Cheers!
