### ISSUE TITLE
PS Now support

### ISSUE THREAD

**Issue by Voltgit** [Ryochan7/DS4Windows#1167]
Is it possible to implement support for gyro and touchpad for ps now?

**Comment by deadair3210** [comment]
pretty sure ps now uses it's own driver to talk directly to the controller, so I don't think this could do much to change that. could be wrong though

**Comment by mika-n** [comment]
Not possible via DS4Windows+ViGem created virtual controllers because the current version of ViGem driver doesn't support virtual touchpad and gyro events.

**Comment by Ryochan7** [comment]
That is a limitation of the ViGEmBus driver. Until gyro and touchpad data mapping is available in the driver, there is no way to get that functionality in PS Now while DS4Windows is running. Stop DS4Windows, unplug and replug the DS4 controller to your Windows PC in order to use PS Now.

**Comment by Voltgit** [comment]
Is it difficult to implement gyro/touch events support in the ViGEmBus driver, or just nobody tried?
I don't understand anything in these issues, sorry)

**Comment by Ryochan7** [comment]
I don't know how difficult it would be to expose that information to a virtual device. I have done very little work with the actual ViGEmBus code. The last time was when I was helping fix force feedback support early in the DS4Windows 1.7 releases.

Unless someone else looks into it, it is pretty much up to Nefarius to try to figure that problem out. I have no use for the feature so it will likely not be me. Nefarius has mentioned that it is on the ViGEmBus TODO list.
