### ISSUE TITLE
PS4 Controller not connecting

### ISSUE THREAD

**Issue by ninjqhunter** [Ryochan7/DS4Windows#1169]
I have the drivers installed, my controller is charged, when plugged in with USB it doesn't connect to DS4Windows
(https://cdn.discordapp.com/attachments/461933745193222144/692562368680689786/unknown.png)

**Comment by mika-n** [comment]
See general troubleshooting tips:
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting

What do you see in Windows JOY.CPL controlPanel applet when you connect the gamepad over USB without DS4Windows app running? Run joy.cpl command to open the WinOS gamepad config screen.

And run a special debug version to generate detailed logfile from a gamepad connection issues and attach the logfile to this discussion thread.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

**Comment by Ryochan7** [comment]
Going to assume that you are probably using a charging only USB cable. The general advice is to not use a USB cable that came bundled with a phone. You need a proper USB data cable to connect the DS4 to your PC.
