### ISSUE TITLE
found a typo, not a huge deal but figured you would want to correct it!

### ISSUE THREAD

**Issue by recoi1er** [Ryochan7/DS4Windows#1170]
![image](https://user-images.githubusercontent.com/19810634/77609677-da72b600-6edd-11ea-9512-d9197eb167fb.png)

**Comment by Ryochan7** [comment]
That is definitely the old Jays2Kings build. Also, that string is correct in the current version (2.0.13).

**Comment by recoi1er** [comment]
Oh it is? My bad! I’ll update right away then
