### ISSUE TITLE
Some About links broken

### ISSUE THREAD

**Issue by Ryochan7** [Ryochan7/DS4Windows#1171]
Need to find a better workaround for launching an un-elevated browser instance with a URL. The links in the About window that contain a query string in the URL no longer work. Will likely have to make some sort of bat script to act as a wrapper.

**Comment by mika-n** [comment]
Maybe something like I had to do to open browser instance with URL parameters. See ProfileSettingsViewModel.cs::LaunchCurveEditor method. It looks up the default browser settings from a system settings and uses that browser executable to open an URL with query string parameters.

**Comment by Ryochan7** [comment]
That uses Process.Start to launch the browser so the browser would be launched as elevated when running DS4Windows as admin.

**Comment by Ryochan7** [comment]
Made a minor wrapper script. It does the job but it does open a cmd window for a brief second. Can't find a way around that.

**Comment by Ryochan7** [comment]
Version 2.0.15 is now out with the updated routine. It is confirm to work for opening the Google Doc DS4Windows Changelog.
