### ISSUE TITLE
Original DS4 or fake?

### ISSUE THREAD

**Issue by KMixa** [Ryochan7/DS4Windows#1177]
Maybe it is a stupid question, but I wanted to know if DS4Windows can recognize original and fake controllers? If it says V2 in game-pad name, is it enough to think that it is a original DS4 gamepad?

**Comment by mika-n** [comment]
Can't be 100% sure, but 97.5% sure. but that's all DS4Windows app can do to identify the gamepad. "DS4 V2" type name is shown if the hardware ID matches the DS4 V2 VID/PID hardware id. Some copies re-use the same HW ID value on purpose, but other copies may look like DS4 gamepad but the HW ID is different. DS4Windows app would then show the gamepad with another name.

**Comment by Ryochan7** [comment]
Identification is done based on the exposed VID and PID of the device. I would assume some third party controllers probably re-use the official Sony identifiers so those devices would show up in DS4Windows as DS4 v.2 even if they are not.
