### ISSUE TITLE
Dualshock 4 not work when use DS4W for Fifaonline 4

### ISSUE THREAD

**Issue by NautHnim** [Ryochan7/DS4Windows#1178]
I connect dualshock 4 with your software via bluetooth and it work perfectly until i login to Fifa online 4.
I can not control player.
After that, i click hide ds4window, close ds4window and restart controller. It's work like a charm but touchpad not work, the light turn from custom color to white.
Any ideal?
Sorry for my bad english.

**Comment by mika-n** [comment]
Do you enable "Hide DS4 Windows" option when the game is already running? That probably doesn't work. You have to enable the HideDS4Controller option and connect the gamepad before you launch the game. This way there are better chances that exclusive (=hide ds4 controller) option works.
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues
