### ISSUE TITLE
adding controller

### ISSUE THREAD

**Issue by KhvLeDx** [Ryochan7/DS4Windows#1180]
Hello! Could you please add support for the controller with VID 0001 and 0000 PID?
Could you do it fast i need it to play tournements please ):

**Comment by mika-n** [comment]
Hmmm.. VID/PID 0001/0000 doesn't sound like a valid code. In theory it could be valid, but I doubt that.

You could run a DeviceDetect debug version of DS4Windows to generate more detailed logfile for further analyzing.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

**Comment by KhvLeDx** [comment]
Look at this pictures:
https://prnt.sc/rowmpx
https://prnt.sc/rownih

**Comment by mika-n** [comment]
Download the debug version and run it. Connect the gamepad and post the logfile here.

**Comment by Ryochan7** [comment]
So you got suckered into buying a knock off controller? That is not how any known DS4 controller is identified in Windows. Also,

> Could you do it fast

![veruca_salt](https://user-images.githubusercontent.com/581968/77859545-ba8a0d80-71cf-11ea-9a9d-31989d85195e.gif)
