### ISSUE TITLE
Virtual DualShock 4 isn't recognized by Steam or any other game

### ISSUE THREAD

**Issue by highlyaddicted** [Ryochan7/DS4Windows#1181]
Hey.

I just reformatted my PC and updated DS4Windows to latest version, and haven't really changed any software I use, so I can only assume this is some driver issue or DS4Windows's.

I had my DS4Windows set to BT Poll Rate 1ms, Controller DualShock 4 and that's all I had different from standard profile. In settings I had "Hide DS4 Controller" checked, Run at Startup as Task.

![DS4Windows_SgNsxB9a92](https://user-images.githubusercontent.com/6403765/77861986-dd8cdf80-7218-11ea-894d-f15286a8c3cb.png)
![DS4Windows_BGpyTxCntJ](https://user-images.githubusercontent.com/6403765/77861988-e087d000-7218-11ea-8766-1776461e353d.png)
![DS4Windows_kEdZW0e3nt](https://user-images.githubusercontent.com/6403765/77861991-e1b8fd00-7218-11ea-9789-29db1f29cf31.png)
![DS4Windows_3fwAfAjPWA](https://user-images.githubusercontent.com/6403765/77861992-e2ea2a00-7218-11ea-8b74-4685891618f4.png)

This prevented from having X360 button prompts on most games and use DualShock 4's prompts and this is how it behaved before I reformatted. It was working just fine two days ago, I was playing Crash Insane Trilogy on Steam with DS4Windows running, set exactly as that and had DS4 prompts. It was perfect! Unfortunately now, Steam doesn't recognize my controller as Dualshock. The only way to get it to recognize the controller through DS4Windows is to set my gamepad as Xbox 360 Controller: 

![DS4Windows_WAqsIkMNAT](https://user-images.githubusercontent.com/6403765/77862015-0e6d1480-7219-11ea-8406-8b7efc91979b.png)

But on the other hand, if I don't have DS4Windows running, Steam recognizes it absolutely fine and says like so.

![steam_uwKCxwkU4E](https://user-images.githubusercontent.com/6403765/77862038-2f356a00-7219-11ea-82e3-fba72b9592ef.png)

I've always had all of these checkboxes unchecked, this is my past and current settings.

I am not sure what to even troubleshoot anymore. This is a fresh system, latest DS4Windows and it was working just fine few days ago. Reverting to an older version of DS4Windows didn't do the trick.

**Comment by Ryochan7** [comment]
Sounds like you probably had not updated Steam in some time. For a long time now, Steam actually checks if DS4Windows is running and implicitly disables PlayStation Configuration Support when DS4Windows is detected. The easiest way to check whether that is the issue is to rename the DS4Windows.exe file and run DS4Windows again.

If that is the culprit then that it is not a bug but a feature (according to Valve).

**Comment by highlyaddicted** [comment]
Frankly, I just finished setting up my fresh OS and grabbed the latest Steam release, but I did doublecheck and indeed I was up to date. To go beyond I tried to update it to Beta version too, but that didn't help the issue.

I just renamed the executable to something random, ran it again and Steam actually recognized the DS4 now! How come when I ran it as "DS4Windows" instead of literally anything else, it didn't check whether I was running it or not?

**Comment by Ryochan7** [comment]
Not sure why you didn't encounter problems beforehand. Not going to dig around for the link but Valve developers confirmed this "feature" on the Steam forums a while ago (maybe mid 2019). The Steam client also performs the same type of executable check for InputMapper as well.

**Comment by highlyaddicted** [comment]
Alrighty, thanks for letting me know, I'll look around for that. Thank you again, it works now!
