### ISSUE TITLE
DS4windows acts as 2 players

### ISSUE THREAD

**Issue by ZoTaG** [Ryochan7/DS4Windows#1182]
this has been happening since even you where the main dev for the app every game see's it as 2 players. can we please have a fix i know people also having this issue

**Comment by Ryochan7** [comment]
Sounds like Exclusive mode is failing. Not sure which version of DS4Windows you are using. Microsoft breaking the old API call for version 1.4.52 is what made me create this fork in the first place. The updated routine works for me a majority of the time but it is inherently not reliable depending on your system configuration.

If the "Hide DS4 Controller" option is not working, you might want to try launching DS4Windows as the admin. If you still cannot get Exclusive access to the DS4, some other program is likely interfering. Some major culprits are GeForce Experience, GeForce In-Game overlay, and Microsoft Edge. Using HidGuardian is an option but it is not very straight forward and requires some manual configuration even when using my test installer.

https://github.com/Ryochan7/DS4Windows/wiki/DS4Windows-and-HIDGuardian-Install-and-Setup-Guide#hidguardian-test-installer

https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues
