### ISSUE TITLE
crashes when BT set to 1ms

### ISSUE THREAD

**Issue by ZoTaG** [Ryochan7/DS4Windows#1184]

**Comment by Ryochan7** [comment]
Do you have the log file handy? It is in your config folder under Logs. ds4windows_log.txt is your most recent log file and there might be a few archived files present as well. Especially with the update in 2.0.14, more background errors should show up in the log file even if the error occurs outside of the main GUI thread.

Another place to check is the Windows Event Viewer (System and Security > Administrative Tools > Event Viewer). Look for an error with Level **Error** and Source **.NET Runtime**.

Example:
![ds4windows_error_in_event_viewer](https://user-images.githubusercontent.com/581968/77869177-33568d00-7203-11ea-9a31-95f818a8d319.png)
.

**Comment by Ryochan7** [comment]
Filing this under "The thing don't work"
