### ISSUE TITLE
Easy run button for arcade games

### ISSUE THREAD

**Issue by reyaz006** [Ryochan7/DS4Windows#1185]
Some arcade games (e.g. Streets of Rage styled) require double-tapping left or right button to make the character run or dash. It's troublesome especially when I prefer using LS instead of D-pad.

Some newer games offer a separate Run button which you have to tap while walking in order to switch to running. So you just press a button while walking and the next moment you are running. I'd like to be able to do something like that for games that don't support it. For example, the run button I want is R1. Then, I need it to work like this:
- While Left is held, if R1 is pressed or tapped: release Left, double-tap Left and keep it pressed as long as Left is pressed.
- While Right is held, if R1 is pressed or tapped: release Left, double-tap Right and keep it pressed as long as Right is pressed.

Of course, it would cause a pause between switching from walking to running, but since such games don't support any other way I think it should work pretty good, as long as implemented and configured properly.

I've tried to do something like this with a macro, but it failed. I've never used macros before so I'm pretty sure I'm missing something. Also, it seems to me that macro should support some kind of conditions in order to do what I want.

This exact usage scenario also seems a fairly obvious thing to want to have, at least for classic arcade games experience.

**Comment by Ryochan7** [comment]
I don't know of any type of gamepad mapper that can execute an action like that. I cannot think of a generic way to configure some type of action like that which would not interfere with normal stick movement. DS4Windows is still lacking mapping options when it comes to some of the more basic use cases.

In short, I don't see that kind of action ever being possible in DS4Windows.

**Comment by Ryusennin** [comment]
You could try JoyToKey, but the kind of convoluted macro you're looking for might require a more complex macro editor, like the CronusMax SDK.
