### ISSUE TITLE
Can support be added for the HORI Wireless Controller Light?

### ISSUE THREAD

**Issue by kenechoko** [Ryochan7/DS4Windows#1188]
Where before I thought I was looking for the HORI MiniPad 0F0D:00EE, I didn't realize form my internet search that was referring to a wired-only version. I am now wondering if support can be added for the wireless edition called  HORI Wireless Controller Light.

0F0D:0123

Thank you!

**Comment by mika-n** [comment]
You might wanna try the debug version. The debug version tries to use unknown device types also, but it might not work. Anyway, there has been attempts to support HoriMiniPad 0F0D:00EE device, but back then it didn't work out. Try the debug version and provide the logfile.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems
