### ISSUE TITLE
Is there a language translation update?

### ISSUE THREAD

**Issue by jose350** [Ryochan7/DS4Windows#119]
Hello guys, some know where I can find the languages of DS4Windows that is not on the page DS4Windows as they are not updated, I say that I update the Spanish language 8 months ago and shared but never saw that was updated, is somewhere? Here I leave the route where you update the language, I hope you can help me.
Thanks

https://docs.google.com/spreadsheets/d/1ZyHta7h1Zuirq6X84fp8_eFszGFsxNlICjnG_CfuKMc/edit#gid=202017801

**Comment by Ryochan7** [comment]
Related to issue #124
