### ISSUE TITLE
Macros Inconsistent

### ISSUE THREAD

**Issue by KenJyn76** [Ryochan7/DS4Windows#1190]
Apologies if the title is somewhat vague, I'm not quite sure what's causing this issue. I'm currently trying to set up macros to match look sensitivities between games. The idea is, if I can record a macro to do a full 360 degree turn, then I can use that macro to match my sensitivity between different programs by tweaking the program's settings until that macro produces a 360 turn again. Similar concept to Kovaak's Sensitivity Matcher. I'm running into an inconsistency, though. 

It seems that either the macro entering "RS Right" isn't inputting the same analog value every time, or the program isn't waiting the appropriate delay every time.

I say this because, if I run the same macro repeatedly, I'll repeatedly get different results. One run will wind up with a near perfect 360, slightly undershooting the mark. Then, I'll run the same macro again, and it will vastly overshoot the mark. If the exact same values were being input every time, I'd expect identical results. 

I'm not sure if this is user error somehow, or if it's a bug in the program. 

I have my deadzone and anti-deadzone reduced to 0.00 in the Profile in question, since my deadzone is set in-game, and having the default values made small adjustments seem clunky.

`  </Action>
  <Action Name="Sensitivity Matcher (Horizontal)">
    <Trigger>Swipe Right</Trigger>
    <Type>Macro</Type>
    <Details>282/1062/282</Details> 
  </Action> `

**Comment by Corgano** [comment]
This type of macro will always have some order of inconsistency.  The rate that the controller reports to the program, the program pulls the controller, and the program updates is never going to be completely consistent. You can try making the rotation slower, which should improve consistency, but it'll really be hit and miss.
