### ISSUE TITLE
Suggestion Feature - Mass alter input delays.

### ISSUE THREAD

**Issue by KBD20** [Ryochan7/DS4Windows#1191]
Would it be possible for the existing macro engine to either allow either editing many/all macro delays at once or somehow have a way to trick "record input delay" to always see the same delay (as an option).

I've made a macro for a game with controller support but keyboard only save naming - and had to manually set everything to 90ms to speed up the typing process (accessibility reasons).

**Comment by mika-n** [comment]
Possible yes. But for know you could "mass edit" macros via Notepad in profiles folder. Take a look at existing macro definition there. Delay is something like 300+delay, value 350 is actually 50ms delay. Or something like that, not 100% sure was the base number 300. Well, I'm sure you can figure it out when you created a simple test macro with just one key down, delay, key up events.

**Comment by Ryusennin** [comment]
300 is indead the base value (this is **not** 300 ms).

**Comment by KBD20** [comment]
Thanks to these comments I've made the connection, I guess 0-299 are different keys/buttons and 300+ is delay by the looks of it (my 90ms delays all show as 390).

That should help in the future.

**Comment by Ryochan7** [comment]
I don't use the macro system myself. It has a lot of limitations that probably cannot be rectified without a complete rewrite and a different file format spec. The macro system is really only left in for backward compatibility. Other problems have been more important for me to solve.

300 is the base offset that is used to specify a wait time in a macro string. The delay would be written as 300+(time) with the time being specified in milliseconds.
