### ISSUE TITLE
Touchpad/multitouch and ps button not working on ps4 remote play

### ISSUE THREAD

**Issue by Janer1** [Ryochan7/DS4Windows#1195]
I've been playing a game that requires the multitouch/touchpad thing., and when i try yo press it nothing happens. It works as mouse mode but not on the ps4 remote play. The PS button dosent work as well if I wanna go home.

**Comment by mika-n** [comment]
The current version of ViGem virtual gamepad driver doesn't support touchpad and gyro events, yet. ViGem supports only "touchpad click" event. So, it is not possible to send touchpad events via virtual dualshock4 controller. Sorry. You might wanna ask the question in ViGem forums or in ViGem discord channel if touchpad support is on a drawing board.
