### ISSUE TITLE
[Notice] Read this before posting a new Discussion or Issue ticket requesting help (Troubleshooting tips)

### ISSUE THREAD

**Issue by mika-n** [Ryochan7/DS4Windows#1196]
**WARNING. If you request help, but you have failed to follow instructions here then be prepared to see your new post being closed without comments. So, if you want help then you have to be ready to help us to help you**
 
- Please read typical troubleshooting instructions and tips before posting a new issue ticket. https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting
- Try to use search by keyword -functionality to find existing duplicate tickets.

- Since the V3.0.11 version **rumbling is disabled on purpose when a profile uses dualshock4 output** controller type (there are few nasty bugs which need to be resolved until this feature can be re-enabled). But, rumbling does work when the profile uses xbox360 controller mode. 

- In 99.99999% cases these days you need to use the 64 bit version of DS4Windows application, ViGem bus device driver and .NET 5.x for desktop runtime libraries. Make sure you installed **x64 (=64bit) versions** of these and NOT the x86 32bit version (most people can forget those x86 32bit applications nowadays if there is x64 64bit alternative also available).

- Don't reply in this issue ticket. Create a new general discussion in "Discussions" page or a specific "Issue" ticket. But, DO NOT create a new issue ticket unless you are ready to collect all the information listed here. **All issue tickets with limited information will be ignored or closed without comments (after all, if you are not ready to help us to help you then why should we bother).**
- Provide this minimum information in Dicussions or Issue ticket posts:
  - The latest DS4Windows log file (see *%APPDATA%\DS4Windows\Logs* folder and the latest file there). Rename the logfile as TXT extension and attach the file (drag-n-drop) into a comment box in Discussion or Issue post.
  - Windows OS operating system version (Win7/8/10/11 and is it x64 64bit or x86 32bit version). See MyComputer/SystemInformation.
  - If the issue is about re-mapping rules then provide the profile file you are using. See *%APPDATA%\DS4Windows\Profiles* folder.
  - DS4Windows application versions you have tried. If something doesn't work in the latest version then test older versions one by one to see if the feature did work in some older version and provide this information. You can install old versions of DS4Windows application to a new separate folder, so no need to uninstall the latest version. See https://github.com/Ryochan7/DS4Windows/releases
  - ViGemBus driver version you have installed. See the [link list](https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#link-list)
  - .NET 5.x for **desktop applications** runtime library version you have installed if the application complains that .NET libraries are missing. See the [link list](https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#link-list)

- Provide **information about the gamepad** you have (genuine Sony DS4 or compatible?). Back of the gamepad should have a label tag. Or take a look at DeviceManager / specific HID gamepad entry / Properties / HardwareID identifier property value. **DS4Windows "Settings / Device Options" page has "Enable verbose log" option. Enable this option and then re-connect the gamepad to see more log file details about the gamepad**.

- **Please provide a logfile as text file attachment** with the new ticket (drag-and-drop the text file into a comment field, don't just copy-paste the logfile content as text because sometimes logfiles are quite long. You may have to rename the log file as TXT file before drag-and-dropping the file to a comment field). 
- See "_%APPDATA%\DS4Windows\Logs_" folder for the latest logfile or use Logs tabpage in DS4Windows app to export the log content.
- Re-start DS4Windows app while testing different things to generate a new logfile per test run (easier to interpret logfiles when there are events from just one test scenario).

- **If you are having "double input" type of problems** (ie. a game sees two simultaneous button or axis movement events, in-game camera is spinning wildly, analog axis mapped as a digital button generates random events or two gamepads even when you have physically just one) then take a look at the following explanations
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues
https://github.com/Ryochan7/DS4Windows/wiki/Settings#axis-zone-mapping

- **If you are having gamepad connection problems** (DS4Windows app doesn't see the gamepad or random disconnections) then disconnect the gamepad, tick "Enable verbose log" option in DS4Windows Settings/Device Options options screen and re-connect the gamepad. Then take a look at the logfile and provide the logfile with your message.

- If you have previously used Jays2Kings version of DS4Windows and then upgraded to this Ryochan7 version of DS4Windows and **are having drifting issues with LS/RS stick then check the deadzone** value in a gamepad profile. The old profile file created by Jays2Kings version may have zero deadzone value, but it worked in Jays2Kings version because that old app had built-in deadzone (ie. zero deadzone value in a profile was not really zero in Jays2Kings version). This Ryochan7 version supports true zero deadzone because in some scenarios it is useful (if a game has its own deadzone tweak settings). The solution to drifting LS/RS stick is to set an explicit deadzone value in LS/RS axis settings in Ryochan7/DS4Windows profile settings (try 0.08 or 0.10 for a start and check ControllerReadings tab page and the red circle if the deadzone is big enough for the gamepad). You may want to tweak the anti-deadzone value also (set it to zero if you don't want to use anti-deadzone). See Wiki/Settings doc page for more info.

- This site is for Ryochan7/DS4Windows (version 2.x/3.x) application support. Some people may still use Jays2Kings (version 1.4.x) version of DS4Windows application. The Jays2Kings version is not supported here even when the app has the same name and the same origin. Jays2Kings version haven't been actively maintained, developed or supported in years.

**Comment by Ryusennin** [comment]
It should be mandatory for people to first indicate **what kind of controller** they're actually using -- a genuine DualShock 4 or a clone (Razer, Nacon, no name, etc). Too many "strange" issues are related to unsupported hardware.

**Comment by ThePapaw** [comment]
There was an option to turn controller off after a certain amount of time, say 5 minutes. Has that been removed? If so, any chance it can return? I sure am missing it not turning off controller not being used

**Comment by mika-n** [comment]
@ThePapaw Please open a new specific issue ticket and don't spam this because the ticket title has nothing to do with the issue.

**Comment by ThePapaw** [comment]
> @ThePapaw Please open a new specific issue ticket and don't spam this because the ticket title has nothing to do with the issue.

@mika-n. Apoligize, it's not a spam, it was a mistake by posting in wrong place.

**Comment by Mister-Curious** [comment]
_Try to use search by keyword -functionality to find existing duplicate tickets._

Curious to know if the closed topics are supposed to be included in the search feature? Presently it appears they are not, and if this is the case then users are going to get minimal input into their queries considering there is no way to comb through old threads other than to manually type each one at: 

https://github.com/Ryochan7/DS4Windows/issues/xxxx (where XXXX is put query number)

**Comment by mika-n** [comment]
@Mister-Curious For sure search can find both open and closed issue tickets. Maybe you tested the search by specifying "is:open is:issue" search attribute tags to limit the scope of the search? But, if you just use a keyword then the search engine goes through all issue posts, wiki docs and even code commits.

![github_SearchKeywordForIssues](https://user-images.githubusercontent.com/35538525/113259990-6e881200-92d6-11eb-810a-29a992838415.png)

**Comment by Mister-Curious** [comment]
Thanks for this.. VERY helpul! I was using the search bar at the **top of the site page** instead of the search bar in the one at https://github.com/Ryochan7/DS4Windows/issues. I kindly suggest to include this link in the second line of your original post above as I may not be the only person who made this mistake. 

Thank you!

**Comment by mika-n** [comment]
The search field on the top left corner does "full search" over this repository or even over several repositories.
![github_SearchField](https://user-images.githubusercontent.com/35538525/113339687-88a40d80-9333-11eb-9082-9ca7309b93e2.png)

**Comment by mika-n** [comment]
re-opening this ticket after providing a warning message here that all new Discussion or Issue posts requesting help with limited information will be ignored or closed without comments.
