### ISSUE TITLE
[Crash] Special Actions options trows unhandled exception - Fixed

### ISSUE THREAD

**Issue by pralima87** [Ryochan7/DS4Windows#12]
Just found out about this fork of DS4W!
Thanks for all the work!!

~~But trying to access the Special Actions tab crashes the app with a **unhandled exception** error!
Both on old and new profiles.~~

~~I notice I can only access the tab just after creating a new profile.~~
~~Closing the app and loading the same profile Special Actions or any other profile will crash.~~

~~Work-around before accessing special actions tab just create a new profile~~

**Comment by pralima87** [comment]
Just a follow up.

I deleted several special actions and now this error does not happen.
Maybe some of the actions were currupted.

**Comment by Ryochan7** [comment]
I am running into a similar problem. It seems like that section only works when at most 1 special action is defined. Usually the Disconnect Controller default special action is the only action that I have defined. Something doesn't get defined correctly and that will need to be checked.

**Comment by Ryochan7** [comment]
This issue has been resolved with the latest commit. Also, I found that the Battery Check action was not working and fixed that action in the process. Now tilting the controller up to check the battery status via lightbar works.
