### ISSUE TITLE
Stops working with Steam once unplugged

### ISSUE THREAD

**Issue by Lombra** [Ryochan7/DS4Windows#120]
Had this issue for a while now, and decided to finally get to the bottom of it. I use DInput only on my default profile, in case that will be important. I do not hide DS4 Controller.

So, the issue is, that when I unplug (henceforth with an implied "and plug it back in") my controller while DS4Windows is running, it seems to stop working in Steam. The PS button seemingly works, as I can still bring up Steam and start big picture mode using it, but I cannot navigate big picture, nor does any game seem to recognise the controller. It's as though the Steam DS4 support stops working? Why I thought my use of DInput might be relevant.

Simply restarting Steam does not fix it.
Stopping DS4Windows does not fix it.
Combining any of the above with unplugging the controller again does not fix it.

Terminating DS4Windows and then unplugging the controller _does_ fix it, and once it's fixed, I can start DS4Windows and resume using it.

Steam running or no the moment the controller is unplugged does not seem to matter.

I just updated from 1.4.92 to 1.4.95 and experienced the same issue. Pretty sure I've had it with older versions, too.

**Comment by Ryochan7** [comment]
Thank you for the break down of the problem. I can replicate it on my system with the current release and the last Jays2Kings version (1.4.52). Oddly, the Windows Game Controller settings window still shows the original controller and events from the controller. Also, the fact that Steam can detect the PS button press and nothing else doesn't make much sense. The only game that I have in my library that supports the DS4 natively is Rocket League but I don't have it installed now so I have no game to test; I will have to re-install it.

**Comment by Lombra** [comment]
Just tried Rocket League and it worked. I have specifically disabled the Steam DS4 hook for that though, so I get the DS4 prompts. I tried enabling it, which made it stop working.

**Comment by Ryochan7** [comment]
It looks like the problem occurs once the first output report is sent to the controller. Once the type of input report changes afterwards, the DS4 is not really usable in DInput mode. Similar behavior occurs when Steam's PS4 controller support is enabled in Big Picture mode. It looks like this behavior cannot be avoided without losing access to the gyro, accelerometer, and touchpad data.

**Comment by Lombra** [comment]
That is unfortunate. I personally would not mind as I don't use either of those features, though... ¯\_(ツ)_/¯

**Comment by Ryochan7** [comment]
I have been using gyro and accelerometer quite a bit lately but I don't use the touchpad much. Besides those features, rumble and custom lightbar color would not be possible either.

**Comment by Lombra** [comment]
Ow. Ok, that's not good. So no real solution at this time? I don't suppose it would be possible to make it so that I can disable DS4Windows instead of shutting it down while replugging the controller?

**Comment by Ryochan7** [comment]
You can stop DS4Windows from reading controllers temporarily and start again without closing the program. There is an also an option for auto profiles to have DS4Windows do that automatically. Besides that, I guess the only real workaround is to make sure that you start a program before DS4Windows so it has a chance to obtain a handle before DS4Windows does its job.

**Comment by Lombra** [comment]
Hm, no but "stopping" DS4Windows is not enough. If I do so and replug the controller, it's still "dead".

The way I have set things up now is I'm using DS4Windows auto profiles which enables XInput for the few games I have outside of Steam that requires it. For the rest I use DInput and leave it to Steam.

If it's possible to avoid the problem by suspending DS4Windows, then it would be cool to somehow have the ability to suspend it until one of my auto profiles are loaded.

**Comment by Ryochan7** [comment]
I guess stopping the DS4Windows process is not good enough. Disconnecting and reconnecting the controller whether using BT or USB is required to use the native DInput device properly.
