### ISSUE TITLE
Question: Key-Press API

### ISSUE THREAD

**Issue by DoganM95** [Ryochan7/DS4Windows#1201]
Hi! first of all, awesome software!!

Is there any way to press the controller buttons/move the sticks virtually, like e.g. an API? 
Would love to write an anti-recoil code by accessing the buttons virtually.

I still have to read what that UDP-Server is for tough.

Thanks in advance.

**Comment by mika-n** [comment]
Not through DS4Windows app. It doesn't have any API to receive programmatic gamepad events and then feeding those to the virtual output gamepad. Theoretically it would be possible to implement such API, but it is not the intention of this app. There are other apps to do something like that (or you could write a completely new custom app from scratch to do it). Take a look at AutoHotKey app. It has an API. Well, of course you would then loose everything what DS4Windows does.

**Comment by DoganM95** [comment]
Could you implement that api to get/send key events? This would open new possibilities like macros, automated keypresses etc. for external programs.

I know every feature-request is work to do, so a no is totally acceptable.

**Comment by mika-n** [comment]
Well.. I do understand and see some potential use cases for such a functionality, but don't see that it would be implemented in the near future (at least by me). Anyway, Ryochan7 has the final call what goes into this fork and I'm sure he is busy enough with other things already. So, don't hold your breath.

**Comment by mika-n** [comment]
closed as "the requested feature is not the original role of this DS4Windows app". The feature is probably not going to make it through in near future, especially when AHK probably supports the feature already.
