### ISSUE TITLE
Error after latest update (2.0.15)

### ISSUE THREAD

**Issue by fedamerd** [Ryochan7/DS4Windows#1204]
After updating to the latest version using _Check For Update Now_ from the settings menu inside the program I got the following message upon relaunching:

![error](https://user-images.githubusercontent.com/60607011/78549832-4a990a00-7803-11ea-9110-24b0de713244.png)

Solved by downloading the latest version from the repo and replacing all the files in the DS4Windows directory.

**Comment by Ryochan7** [comment]
Related to issue #1113. Need to devise a different way of dealing with copying the updater I guess. People really shouldn't be using DS4Windows from the Program Files directory.

**Comment by Ryusennin** [comment]
On Win10 I install most of my programs in a custom "Program Files (Users)" folder because many apps like DS4Windows won't run from "Program Files" or won't allow to read/write config files from there. Yet another umpteenth reason why Win7 is vastly superior.

**Comment by fedamerd** [comment]
Haven't had any errors after updating before, so I figured it could be due to a change or bug in the latest release. I will move DS4Windows to my user folder from now on. Thanks for all the hard work you (and everyone else) put into this project!
