### ISSUE TITLE
DS4 Windows suddenly stopped working, now shows 2 controllers in device manager which makes games unplayable and Hide DS4 doesn't work.

### ISSUE THREAD

**Issue by RealRaptoReX** [Ryochan7/DS4Windows#1206]
Pretty much title:
![ds4](https://user-images.githubusercontent.com/29068336/78628721-43224100-7895-11ea-8f6d-5ab9e4bd80ed.png)

As you can see in the picture, the program now puts 2 controllers into device manager. Even if you remove one, it gets readded when reconnecting the controller. MY hardware didn't change, I just updated to Windows-Insider a few weeks ago and even then it worked for a couple of versions, now it doesn't. This is frustrating as hell and makes games unplayable, since pressing one button activates 2 commands.

**Comment by mika-n** [comment]
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting

Logfiles? Take a look at the pinned "Read this before posting a new ticket" comment also for more info. 

Anyway. The red warning text on the bottom of the DS4Windows app pretty much sums it. Some app has hijacked the DS4 controller and this way prevents the "Hide DS4 Controller" option to acquire an exclusive lock on the gamepad device. See the above linked "exclusive mode" explanation for more details.

**Comment by RealRaptoReX** [comment]
[ds4windows_log_20200407.12.txt](https://github.com/Ryochan7/DS4Windows/files/4445213/ds4windows_log_20200407.12.txt)
Here is my log file. I have read that and tried for hours to close applications and all the other stuff, but I wasn't able to get anything working.

**Comment by mika-n** [comment]
Couple notes about the logfile. Do you use HidGuardian tool to hide the original physical gamepad device? At least the logfile tells that you have HidG. But, at the same time you have enabled "Hide DS4 Controller" (=exclusive mode) option in DS4Windows settings.

HidG and exclusiveMode are alterative solutions (as explained in the webpage I linked) to hide the physical gamepad and usually there is no need to use both of these at the same time.

Try unticking "Hide DS4 Controller" option if you use HidG tool. And you mentioned that you have installed some WinOS updates. Sometimes some major WinOS update may break the HidG driver registration and it no longer hide the physical gamepad device even when it is installed. The solution is to simply re-installing HidGuardian driver, so please try that. The easiest way to install HidG is to use "HidG Test Installer" (yes, weird name for an installer app).
https://github.com/Ryochan7/DS4Windows/wiki/DS4Windows-and-HIDGuardian-Install-and-Setup-Guide#hidguardian-test-installer

If you don't use HidG tool then you should tick the "Hide DS4 Controller" exclusive mode option AND to figure out which app is locking the device (Edge browser background app? Windows Store app? Steam client? UPlay client? Any other web browser supporting gamepad controls?). HidG is usually the most bullet proof way to hide the physical controller, but some users don't want to use it. Then "Hide DS4 Controller" is the only other option but you have to try to figure out which app is holding an open connection the gamepad.

```
HidGuardian in use. Launching HidGuardHelper.
Using Exclusive Mode
Warning: Could not open DS4 A4:53:85:75:C1:52 exclusively. You must quit other applications like UWP apps (Netflix), Steam, Uplay, NVIDIA IN-GAME before activating the 'Hide DS4 Controller' option. For more info check https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues
```

**Comment by RealRaptoReX** [comment]
Thanks for your reply! I solved the issue by reinstalling HidG. 

I don't understand why tough, I never changed it and it was never neccesary before to reinstall it. 

And i still don't get why Hide DS4 never works, I don't even use Edge and even if i turn all other programs off, it doesn't change anything. The Hide DS4 function NEVER worked properly for me.

**Comment by mika-n** [comment]
Good to hear it works again. HidG registration may break even when you don't change anything. Sometime MS WinOS updates may break the HidG filter driver chain. That's why it is good idea to keep the HidG TestInstaller available in case some other WinOS update breaks it again.

Exclusive mode is sometimes a nasty thing to get working because some very unexpected apps may open a gamepad connection even when you don't really use gamepad in that app. WinStore background app may lock the gamepad even when you don't use WinStore app, the same thing with Edge background service (it may be running even when you don't use Edge browser). And zillions of other apps.
