### ISSUE TITLE
Invisible Rectangle

### ISSUE THREAD

**Issue by volitank** [Ryochan7/DS4Windows#1210]
Hello. I have this issue where DS4Windows opens this invisible little rectangle on my desktop. I can't really interact with it. It happens about 50% of the time I open DS4Windows, and 100% of the time I connect my PS4 controller. Any Idea what is going on?

![Capture](https://user-images.githubusercontent.com/23148438/78826918-5249e180-79b0-11ea-8b50-5c8c0382055a.JPG)

**Comment by volitank** [comment]
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/4452521/ds4windows_log.txt)

**Comment by Ryochan7** [comment]
What version of Windows are you using? I don't know if there is much I can do about your problem. Windows at least acknowledges that a window should be rendering. Have you tried running any other WPF or maybe UWP application (if you are using Windows 10)? Like the wallpaper btw.

Easiest thing to try is try running DS4Updater.exe on its own. That has been a WPF application since the start.

**Comment by deadair3210** [comment]
It almost looks like the same effect windows applies when you use Aero Peak

**Comment by mika-n** [comment]
How do you startup the DS4Windows app? Do you use "Run at Startup / Program or Task" option? How about if you try to dsable this auto-startup and launch DS4Windows app "manually"?

**Comment by volitank** [comment]
@Ryochan7 I'm using Windows 10 LTSC. The program works fine. The window renders, It just also makes this. It's not a huge deal or anything, the program works great. Just figured if anyone would know what's going on you would. And thanks. I've had Mitsuha as my wallpaper for quite some times. Love the colors.

@mika-n I tried all of those. Running at startup makes the rectangle go away until I plug in the controller. If the controller is plugged in on boot with it running at startup then it still makes the rectangle, doesn't matter if program or task. If I run it manually then I get the rectangle about 50% of the time it starts. 100% of the time I plug in a DS4 controller.

**Comment by volitank** [comment]
Also worth noting that while starting DS4Windows causes this, closing DS4Windows does not make it go away.

**Comment by Ryusennin** [comment]
Maybe related to Xbox Game Bar or whatever it's called?

**Comment by volitank** [comment]
@Ryusennin Doesn't appear to be. I double checked, but I have all that disabled.

**Comment by volitank** [comment]
Actually appears to be some kind of interaction between DS4Windows and Steam. If I close steam through task manager the rectangle goes away. Much be some kind of steam popup when it detects a controller? I'll have to do more testing.

**Comment by volitank** [comment]
Closed both DS4Windows and Steam. Then started DS4 Windows, Started Steam, plugged in my controller I get this. Same exact position as the invisible rectangle. Looks to be some kind of issue with steam rather than DS4Windows. 

![Steam window](https://user-images.githubusercontent.com/23148438/79000814-547c7f00-7b1b-11ea-88a1-ee69c18bc7a2.JPG)

**Comment by Ryusennin** [comment]
Try disabling all Steam > Settings > Controller options.
