### ISSUE TITLE
orange light bar

### ISSUE THREAD

**Issue by arsooamgad** [Ryochan7/DS4Windows#1211]
when i connect the controller it flashes slowly on orange and all the buttons is working even in games but after 10 minutes orange light disappears and d-pad disconnects from working .. no light appears since i connect the controller except orange only !!

**Comment by mika-n** [comment]
See the pinned "Read this before posting a new issue ticket" post for instructions what information to provide (app version, logfiles, gamepad type, winos etc).

The troubleshooting documentation page has also a link to a special debug version which prints out more detailed messages about gamepad connections.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems
