### ISSUE TITLE
Driver prevents renaming bluetooth devices

### ISSUE THREAD

**Issue by Corgano** [Ryochan7/DS4Windows#1212]
I've discovered an issue recently with renaming controllers in windows not working when the driver DS4Windows uses is installed. Uninstalling the driver / stopping DS4Windows and changing the name of a bluetooth device through windows "printer and devices" menu works, and the name is maintained after i reinstall DS4Windows / driver, but trying to change any controller names while the driver is installed is cleared the next time the controller is turned off and back on.

**Comment by mika-n** [comment]
This must be some WinOS magic. While some app uses the driver/gamepad is probably understandable that it prevents renaming, but still it must be a WinOS thing. Or using "exclusive mode" (=Hide DS4 Controller) option in DS4Windows app may cause extra exclusive locks to the device handle, but this app doesn't try to actively stop renaming of devices.

**Comment by Ryochan7** [comment]
Not something I would bother with. I consider this a non-issue for the most part.

I am going to assume that using Exclusive access is what would prevent a device rename from persisting.

**Comment by Corgano** [comment]
The only problem is when you have a lot of controllers paired and you want to tell them apart. I repair controllers and i ds4 windows to help diagnose them, and often have over 50 controllers paired. When one forgets the pc because its battery was unplugged (jdm-011s mostly) and windows won't let you put it into pair mode and re-pair it without first removing it, i often have to go through half my list unpairing them one by one and trying to re pair it. If i could rename them the first time i pair it i could simply remove only the one I'm working on at the time.

It remembers names fine without ds4 windows, so it must be ds4 windows doing it
