### ISSUE TITLE
Opening DS4windows does nothing.

### ISSUE THREAD

**Issue by DesolatePsyche** [Ryochan7/DS4Windows#1215]
Title.

Basically I double click ds4windows to open it. It shows loading cursor for split second and that's it. It doesn't open or anything.

**Comment by mika-n** [comment]
See the pinned "Read this before posting a new issue ticket". Please provide more info as explained in the pinned post (versions, logfiles, check Windows EventViewer for potential error messages, update to the latest MS .NET drivers, make sure required MS VisualStudio and VigEm drivers are installed as explained in installation docs).

**Comment by DesolatePsyche** [comment]
1. No logs were generated in DS4 folder
2. Have latest ms .net and studio + vigem
3. no label on controller
[e1.txt](https://github.com/Ryochan7/DS4Windows/files/4464599/e1.txt)
[e2.txt](https://github.com/Ryochan7/DS4Windows/files/4464600/e2.txt)
[e3.txt](https://github.com/Ryochan7/DS4Windows/files/4464601/e3.txt)

**Comment by mika-n** [comment]
```
Exception Info: System.IO.FileNotFoundException
   at DS4WinWPF.App.Application_Startup(System.Object, System.Windows.StartupEventArgs)
   at System.Windows.Application.OnStartup(System.Windows.StartupEventArgs)
```

Hmm... FileNotFound error, but what file? One thing OnStartup initialization does is to read (and if missing then creating) configuration files. Maybe there are some permission issues.

When you downloaded and run the DS4Windows app for the first time then it asks where you want to install config files. Did you get this prompt dialog? Or you get this error on the very first run?

Sometimes there are permission issues if the app is installed in C/ProgramFiles folder structure. Try unzipping the DS4Windows.zip file into C:/Apps/DSWindows folder (or any other than programFiles) and see if it helps.
https://github.com/Ryochan7/DS4Windows/releases

**Comment by DesolatePsyche** [comment]
> 
> 
> ```
> Exception Info: System.IO.FileNotFoundException
>    at DS4WinWPF.App.Application_Startup(System.Object, System.Windows.StartupEventArgs)
>    at System.Windows.Application.OnStartup(System.Windows.StartupEventArgs)
> ```
> 
> Hmm... FileNotFound error, but what file? One thing OnStartup initialization does is to read (and if missing then creating) configuration files. Maybe there are some permission issues.
> 
> When you downloaded and run the DS4Windows app for the first time then it asks where you want to install config files. Did you get this prompt dialog? Or you get this error on the very first run?
> 
> Sometimes there are permission issues if the app is installed in C/ProgramFiles folder structure. Try unzipping the DS4Windows.zip file into C:/Apps/DSWindows folder (or any other than programFiles) and see if it helps.
> https://github.com/Ryochan7/DS4Windows/releases
It's not in program files. Not even on Windows drive. And no, it didn't ask anything first time I booted it.

**Comment by DesolatePsyche** [comment]
> 
> 
> > ```
> > Exception Info: System.IO.FileNotFoundException
> >    at DS4WinWPF.App.Application_Startup(System.Object, System.Windows.StartupEventArgs)
> >    at System.Windows.Application.OnStartup(System.Windows.StartupEventArgs)
> > ```
> > 
> > 
> > Hmm... FileNotFound error, but what file? One thing OnStartup initialization does is to read (and if missing then creating) configuration files. Maybe there are some permission issues.
> > When you downloaded and run the DS4Windows app for the first time then it asks where you want to install config files. Did you get this prompt dialog? Or you get this error on the very first run?
> > Sometimes there are permission issues if the app is installed in C/ProgramFiles folder structure. Try unzipping the DS4Windows.zip file into C:/Apps/DSWindows folder (or any other than programFiles) and see if it helps.
> > https://github.com/Ryochan7/DS4Windows/releases
> > It's not in program files. Not even on Windows drive. And no, it didn't ask anything first time I booted it.

Okay.... I seem to have solved it.

I downloaded .zip before instead of .rar 

.zip had only 2 exes. .rar had tons of other files.. that seemed to fix it.

**Comment by mika-n** [comment]
RAR archive? Releases download list doesn't have RAR archive, but zip and 7zip archive.
https://github.com/Ryochan7/DS4Windows/releases

Just verified the zip file and it does have all required library files, so I wonder what did you downloaded originally and from where.

**Comment by DesolatePsyche** [comment]
> 
> 
> RAR archive? Releases download list doesn't have RAR archive, but zip and 7zip archive.
> https://github.com/Ryochan7/DS4Windows/releases
> 
> Just verified the zip file and it does have all required library files, so I wonder what did you downloaded originally and from where.

my bad. Mean I grabbed before 7z , then zip. 7z had for me only 2 files. (2 exes)

**Comment by mika-n** [comment]
Okey. Just verified the 7z archive to make sure that it contains all required files and it seems to be OK and the 7z extracted app worked just fine. So, something must have gone bad while unzipping the 7z package. I used the V20.00 Alpha 64bit EXE version from 7-zip.org web site.  Anyway, good that everything is now OK.
