### ISSUE TITLE
I cant connect my ds4 with ds4windows

### ISSUE THREAD

**Issue by JeaNSneaL** [Ryochan7/DS4Windows#1216]
Hello everybody, after a few tries to find out the problem for myself, i must ask you for help. The problem is, after using my ds4 on the ds4windows app its all fine, but after i used my ds4 on the ps4 and then on the pc the ds4 is not recogniced by the ds4windows program. I tried a lot and i downloaded an older version of ds4 and i worked fine after i used again my ds4  on the ps4 and back to the pc i doesnt recognice it on the ds4windows on my PC. Its a strugle for me because like any gamer knows how hard it is to play games like NFS on the keyboard ;) I hope somebody can help me in my problem :)

**Comment by mika-n** [comment]
Please see the pinned "Read this before posting a new issue ticket". App versions? Logfiles? Running a debug version to diagnose connection issues? USB or BT connection? WinOS?
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems
