### ISSUE TITLE
[Minor] Gyro/Accel are backwards

### ISSUE THREAD

**Issue by bluechipps** [Ryochan7/DS4Windows#1220]
On the Controller Readings tab, the readings labeled Gyro are actually the readings of the accelerometer and vice versa. 

I'm using a DS4 CUH-ZCT2U, It was correct in the last version I used (about a month prior) so I'm pretty sure it's a bug and not just me.

PS. I would very much love the ability to map the accelerometer axis in DS4Windows to things ;)

**Comment by cthom055** [comment]
Yep getting same here on the same model

**Comment by Ryochan7** [comment]
I will have to test this with my version 2 controller. The readings are correct with my version 1 controller connected to the Sony Wireless Adapter.

**Comment by Ryochan7** [comment]
Version 2 readings when connected via BT are correct. I have a suspicion though. If you are comparing the current build to the old Jays2Kings build, you should know that it was actually wrong and mapped the data backwards.

Also, the Tilt controls are what is used to map actions to the accelerometer.

**Comment by michcio1234** [comment]
I am facing the same issue with DS4 CUH-ZCT1E. Acceleration shows position and vice versa. It makes my game unplayable. How can I change it?
