### ISSUE TITLE
Controller Latency over USB??

### ISSUE THREAD

**Issue by Alphxx101** [Ryochan7/DS4Windows#1222]
Hi,

I'm having problems with DS4 because I am getting really bad controller latency over both WiFi and bluetooth. PC is on ultimate performance mode and no power saving on the bluetooth or the USB hub is enabled. Can any help and tell me why i am getting latency over USB connection.

I have tried the cable plugging into the port on the motherboard and on the front I/O but it is the same result. Any help appreciated.
[log.txt](https://github.com/Ryochan7/DS4Windows/files/4472423/log.txt)

**Comment by Alphxx101** [comment]
UPDATE: I have had my controller plugged in to the USB passthrough on my keyboard and for some reason I am not getting any latency variations so far. Very weird, maybe I have too many USBs plugged in to my motherboard.

**Comment by mika-n** [comment]
Weird. Never heard of latency issues in USB connected DS4 gamepads. It is more like an issue in some BT setups. PC or usb drivers are not up to the task or too many devices in the same usb host causing busy signals.

**Comment by Ryochan7** [comment]
Maybe too many active devices are on a USB hub. I ran into a similar issue with USB bandwidth issues. It was not with a DS4 but it happened with my webcam on OBS. I got odd frame drops for no good reason. Changed the USB device layout and I have not had problems with my webcam since.

**Comment by Alphxx101** [comment]
What do you mean changed the USB hub layout. The current USB devices I have are:
HyperX Alloy Elite (2 USBs)
Glorious Model O (1 USB)
They are all plugged into the mobo
Also TP-Link Bluetooth adapter.
The Micro USB cable that I use for charging the controller I now need to plug in the passthrough on the keyboard.

**Comment by Ryochan7** [comment]
Odd way of saying changed which USB ports I plugged devices into

**Comment by manafoo** [comment]
check the bt poll rate , put it on 1000hz if possible , chances are you were connected to bt even when you were plugged in
