### ISSUE TITLE
DS4 can't recognize my controller 

### ISSUE THREAD

**Issue by arnav-k** [Ryochan7/DS4Windows#1223]
So I am having this issue where my controller has suddenly stopped showing up on DS4 windows. I was using the older versions of DS4 windows(1.4.x) for the past couple of days and everything was going well when I was playing FIFA 20. But then suddenly, the controller stopped working in 'exclusive mode' and did random stuff in-game so I installed HIDGuardian to fix the issue. But after installing it, my controller stopped showing up altogether on the DS4 application. So I removed HIDGuardian from 'System devices' under device manager and replaced the old version with the latest one(2.0.16) posted here thinking it would solve the problem. But even after doing that, it still doesn't show up.

I tried reinstalling the HID-compliant game drivers, the USB Root Hub drivers, enabling and disabling them several times and also switching USB ports but to no avail. The controller doesn't even show up when I run joy.cpl and I get the error of 'No gamepad detected' on HTML5 Gamepad Tester. 

I have the original Sony PS4 rev1 controller and I use a wired USB connection. Has the HIDGuardian caused some issues, because I read in one of your responses here that it isn't compatible with the older model? I have attached the detailed log file below after running the debugging version of DS4Windows. 

[log_file.txt](https://github.com/Ryochan7/DS4Windows/files/4475697/log_file.txt)

**Comment by Ryusennin** [comment]
DS4W 1.4 and 2.0 are different programs developed by different persons. Version 2.0 is not a "drop-in" replacement, you should start from a fresh profile.

If your controller disappears after you install HidGuardian, that's a good sign. It just means you misconfigured the AffectedDevices registry key. Consult post #1196 for troubleshooting.

**Comment by arnav-k** [comment]
What exactly does starting with a 'fresh profile' mean? I wasn't able to locate DS4W under 'Uninstall a Program' in Control Panel so I just deleted the previous one and downloaded the latest one and installed the drivers provided.

Also, my controller disappears, as in it doesn't light up as DS4 controllers are supposed to do when they are active and it's not displayed under the 'Controllers' tab of the DS4W application. I still get a 'No controllers connected' message. Another error I get is that the HID-compliant game controller shows 'Device not migrated' in the Events tab.

I will try reconfiguring the AffectedDevices registry key but is there any way to get rid of HIDGuardian completely if I prefer running it in Exclusive Mode by disabling all the background applications? 

Appreciate the help, thanks!

**Comment by mika-n** [comment]
To test things without HidGuardian doing it's magic then you could edit AffectedDevices sysreg entry by commenting out all hardware identifier strings (just append # char at the beginning of a line). Or use Hider app to manipulate the AffectedDevices entries.
https://github.com/Ryochan7/DS4Windows/issues/1219

The logfile you provided had "Exclusive mode" enabled (=Hide DS4 Controller -option in DS4Windows). HidGuardian 3rd party tool and ExclusiveMode in DS4Windows app are alternative solutions as explained in the below linked doc page. You don't need both at the same time.
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

Also. If you have both exclusiveMode or HidG in use and a profile has "Use DInput Only" option enabled then you would end up being without a controller. Check DS4Windows profiles and untick "Use DInput Only" option.

Make sure there are no HID input/gamepad devices in DeviceManager in disabled state.

**Comment by arnav-k** [comment]
Thank you so much! My controller is back up and running. I deleted the existing config files as you had instructed and commented out the entries in AffectedDevices. I'm using it in exclusive mode and it's working like a charm now. Hope it doesn't go missing again.
Thank you once again! A saviour during this quarantine lockdown.
