### ISSUE TITLE
Tray icon always visible

### ISSUE THREAD

**Issue by pajwoj** [Ryochan7/DS4Windows#1225]
Would it be possible to add an option hide the tray icon (sort of like SCPToolkit worked)?

**Comment by mika-n** [comment]
Here the tray icon (Win10) is not always visible unless I set "always show" option in Win10 settings. Normally the DS4Windows tray icon is "hidden" behind the small /\ icon.

**Comment by pajwoj** [comment]
Sorry for my bad wording, I meant to ask if it's possible to hide it completely (even from the ^ icon)

**Comment by mika-n** [comment]
well, everything would be possible but don't see this as a major issue when optionally the icon is "hidden" behind the /\ group icon. What is the use case scenario for not having an icon there at all?

**Comment by pajwoj** [comment]
just preference honestly, switching from DS3 drivers that didn't have an icon I'd just rather not have one at all

very insignificant thing but I can't see myself being the only person so if it's not a hard thing to implement why not do it
