### ISSUE TITLE
Ds4Windows input delay unstable. "oscilating"

### ISSUE THREAD

**Issue by Cypery** [Ryochan7/DS4Windows#1226]
The input delay is unstable it oscilates to a high number for no reason. 
It stays between 2 and 3 ms, but it changes on a level higher than 10 ms out of nowhere.
I don't know if can be a problem on BT Dongle or on the Drivers.
The adaptor that I use is (Usb Bluetooth 5.0 Csr Dongle).
There are no other bluetooth devices close enough to interfire on the signal however the wifi is near.
I already uninstalled and installed The Vigem Bus Driver.

**Comment by apoklyps3** [comment]
try to connect the usb dongle via a extension cable. there is alot of interference with the internal components whe connected directly via usb

**Comment by Ryochan7** [comment]
It could be interference. Disable your WiFi adapter temporarily and see if input performance improves. Maybe you could also play around with the BT Poll Rate that is used in the active profile.

Although, it is expected that there can be up to 16 ms of time spent between output reports. DS4Windows calculates an average of the last 20 reports when displaying the Input Delay.

**Comment by Cypery** [comment]
> try to connect the usb dongle via a extension cable. there is alot of interference with the internal components whe connected directly via usb

I can't do this right now because I don't have an extension cable, but I'll try when I can.



> It could be interference. Disable your WiFi adapter temporarily and see if input performance improves. Maybe you could also play around with the BT Poll Rate that is used in the active profile.
> 
> Although, it is expected that there can be up to 16 ms of time spent between output reports. DS4Windows calculates an average of the last 20 reports when displaying the Input Delay.


I did what you suggest, but issue persisted. 

Thank you so much for your help. Maybe everything is ok and this is just a normal thing that happens.

**Comment by apoklyps3** [comment]
another thing that could work as an extension is a plain external usb hub.
anything that keeps the dongle as far away for your I/O shield.

**Comment by mika-n** [comment]
closed as "infamous weird BT radio frequency" issue which is outside of DS4Windows app control
