### ISSUE TITLE
Battery doesn't display over "50%"

### ISSUE THREAD

**Issue by Ilike2hackstuff** [Ryochan7/DS4Windows#1227]
I just got my brand new DS4 in the mail today so I fired up DS4Windows and installed the drivers, everything was fine until I wanted to charge it. When I plugged it in it started to increase as normal at a reasonable rate but then stopped at "50%+" I thought it might take some time but after waiting quite a white it would not budge. I unplugged it, tried Bluetooth and a fresh config, nothing worked. 

![image](https://user-images.githubusercontent.com/30152545/79531491-63859480-8027-11ea-9ebf-70a60b6774d2.png)

**Comment by Ryochan7** [comment]
You are using the old Jays2Kings version 1.4.52 build. Please download the latest release (2.0.16).

https://github.com/Ryochan7/DS4Windows/releases/tag/v2.0.16
