### ISSUE TITLE
BT latency increases when multiple controllers are connected

### ISSUE THREAD

**Issue by Ryochan7** [Ryochan7/DS4Windows#123]
It has been mentioned before that the input delay for controllers increases as more controllers are connected to one Bluetooth adapter. This is a problem in the Jays2Kings build as well. With a 4 ms poll rate set, the input delay is around 6.5 ms when two controllers are connected to one Bluetooth dongle. Multiple controllers can be used with no increase in input delay if multiple connection types (BT, Sony dongle and USB) are used or if controllers are only connected via USB. The problem only occurs when more than one controller is connected to one Bluetooth adapter.

I have tried many different options to see if anything can be done in software to get rid of this behavior but nothing has helped. I am not sure if it is entirely a hardware issue or if it is an issue with the Windows Bluetooth stack. This problem will have to be looked into further and this issue will serve as a reminder.

**Comment by Ryochan7** [comment]
After testing the controllers on Linux using the BlueZ Bluetooth stack, it does seem like the problem is hardware related. I have an older Bluetooth adapter so I might have to buy a Bluetooth 4.0 adapter and see if that helps.

**Comment by TristanYoung** [comment]
DS4 controllers are Blutooth 2.1 + EDR.  If your current adapter is the same, I can't imagine you'd get much different performance. That being said, certain chipset brands may have better results.  Maybe certain optimizations have been made progressively where a BT4.0 dongle will work better.

Microsoft fixed the SCR Bluetooth radio support in their lastest couple of builds of W10 Insider Preview.  There's SCR (Qualcomm) and Broadcomm I believe.  Would be interesting to know if chipset brand has any impact.  I know SCR hasn't been highly regarded for use with DS4Windows, but I used one for a long time without any issue.  I'm now using a Broadcomm based radio from iogear which also works well.  I keep my SCP around for testing/backup.

**Comment by Ryochan7** [comment]
Looking at the old official page for my dongle, it seems the adapter is Bluetooth 2.0 with EDR support. I have the Rocketfish RF-FLBTAD.

https://www.rocketfishproducts.com/pdp/RF-FLBTAD/8819282

After testing various poll rate settings, it seems like poll rates stabilize if both controllers are set around 8 ms. Also, I have already ordered a new dongle for testing.

**Comment by TristanYoung** [comment]
BT v2.0 vs. v2.1 - the radio you have now simply misses a few things.
- No EIR (extended inquiry response)
- Lower power consumption
- Faster pairing

Nothing in there to make it go faster, sadly.  I would think any speed gains would have to be through optimizations of the hardware,.

I notice the original PS4's only support Bluetooth 2.1, where-as the PS4 Slims support Bluetooth 4.0.  Until Sony starts shipping Bluetooth 4.0 controllers, there may not be any way to reduce latency further.

Curious...  How bad would the latency be with multiple DS4's bluetoothing with the PS4 simultaneously?  Think it's higher than what PC users experience?

**Comment by Ryochan7** [comment]
Unfortunately, I have no way to test that. I do not own a PS4 and I don't have any friends that own a PS4. It might be the case that this problem might exist to an extent on the PS4 hardware. I would assume that the PS4 probably uses a slower poll rate for the controllers than the actual DS4 hardware is capable of anyway.

**Comment by Ryochan7** [comment]
I just got a chance to test my new Bluetooth adapter. Connection speed is far better with the new adapter than with my old Rocketfish. The input delay varies a bit but the average is probably around 4.5 ms now when two controllers are connected. I have not done a play test yet.

Just to put it out there, my new Bluetooth adapter is a Rosewill RNX-BT401.

https://www.newegg.com/Product/Product.aspx?Item=N82E16833166126

**Comment by Ryochan7** [comment]
Play tests have shown that the new adapter works perfectly fine while both controllers are connected.
