### ISSUE TITLE
Controller random inputs every second reconnection

### ISSUE THREAD

**Issue by pajwoj** [Ryochan7/DS4Windows#1230]
I use a DS4 V2.
The first connection, wired or wireless works good. After disconnecting the controller once and connecting it again, it starts acting weird - wired it seems to be pressing left constantly and sometimes up, and wireless it's either holding up constantly or pressing up when I press down.
After disconnecting and reconnecting again everything works as intended (until you disconnect again)
So every second, fourth, sixth and so on connection sends weird inputs.

**Comment by Ryochan7** [comment]
Need a comparison with the DirectInput interface. It might just be the controller with a combination of no dead zone in your selected profile.

**Comment by pajwoj** [comment]
How do I test and show everything needed?
I figured it might be the deadzone being wrong but then why does it only freak out after disconnecting and reconnecting once?
