### ISSUE TITLE
Update wants to download backend error

### ISSUE THREAD

**Issue by laurinius** [Ryochan7/DS4Windows#1235]
During the short GitHub outage today the following update message was shown:
![DS4Windows Update](https://user-images.githubusercontent.com/50016928/79889821-da8fa400-83fe-11ea-87b8-929a58cf8041.PNG)
Probably should validate server response.

**Comment by mika-n** [comment]
good catch. "Luckily" you were trying to update during the Github problem to discover this kind of "silent bug".
