### ISSUE TITLE
Problem disconnecting

### ISSUE THREAD

**Issue by Com3Carne** [Ryochan7/DS4Windows#1236]
I activated the option that turns off the control if it leaves it stopped for 5 minutes. Only sometimes when he reconnects it, he changes the door. DS4Windows keeps saying it is control 1, but the game/emulator says it is control 2. Does anyone know how to solve this problem/bug?

**Comment by mika-n** [comment]
It is a bug or feature in VigEm driver and in xinput WinOS driver level.
https://github.com/Ryochan7/DS4Windows/issues/1163

There has been discussions on to create a concept of "persistent virtual output controller cache" in DS4Windows app and that would probably solve that issue. This feature would hold a pool of x360 output controller devices in active state even when a physical DS4 gamepad is disconnected. When a ds4 gamepad is re-connected it would re-use an existing x360 output controller devices from this connection pool. This way WinOS and games would not see gamepad disconnect/re-connect events and create new xinput slots.

**Comment by Com3Carne** [comment]
> É um bug ou recurso no driver VigEm e no nível do driver xinput WinOS.
> [# 1163](https://github.com/Ryochan7/DS4Windows/issues/1163)
> 
> Houve discussões sobre a criação de um conceito de "cache persistente do controlador de saída virtual" no aplicativo DS4Windows e isso provavelmente resolveria esse problema. Esse recurso manteria um conjunto de dispositivos controladores de saída x360 em estado ativo, mesmo quando um gamepad DS4 físico for desconectado. Quando um gamepad ds4 é reconectado, ele reutiliza os dispositivos controladores de saída x360 existentes desse pool de conexões. Dessa forma, o WinOS e os jogos não veriam os eventos de desconexão / religação do gamepad e criariam novos slots xinput.

Is there any way around this problem without having to log out and back into Windows?

**Comment by Com3Carne** [comment]
> It is a bug or feature in VigEm driver and in xinput WinOS driver level.
> #1163
> 
> There has been discussions on to create a concept of "persistent virtual output controller cache" in DS4Windows app and that would probably solve that issue. This feature would hold a pool of x360 output controller devices in active state even when a physical DS4 gamepad is disconnected. When a ds4 gamepad is re-connected it would re-use an existing x360 output controller devices from this connection pool. This way WinOS and games would not see gamepad disconnect/re-connect events and create new xinput slots.

Is there any way around this problem without having to log out and back into Windows?

**Comment by mika-n** [comment]
the latest release has "persistent controller slot" feature which probably helps to fight with this issue in WinOS/xinput/ViGem slot ordering thing.
