### ISSUE TITLE
Suggestion: Feature to go back to a selectable previous version

### ISSUE THREAD

**Issue by Eiion** [Ryochan7/DS4Windows#1239]
I'd like to suggest an option in the settings, that allows us to go back to a previous version which - ideally - can be picked from a drop down menu.
In cases were a new version doesn't run well for us - for whatever reason, we'd have an easy solution to go back 1, 2, 3 or more versions before the current one.

**Comment by mika-n** [comment]
It is quite easy to "manually" run an older version of DS4Windows in case the new version doesn't work. Just download a different version from Releases web page and unzip the package to a different folder and run DS4Windows.exe from there. It will re-use all existing configuration files automagically.
https://github.com/Ryochan7/DS4Windows/releases

**Comment by Ryochan7** [comment]
Counting this as out of scope. You can easily download an older release and revert back to an older version. Uncheck **Check for DS4Windows Updates at Startup** from the Settings menu. The archived log files will show you which version of DS4Windows you were running before the update. Also, a Changelog is being added to the Updater window so people can get a better idea if there is a desired feature update worth updating DS4Windows to get.

For my personal use, I would obviously recommend running the latest version when possible. DS4Windows is mainly made for my own use so, almost always, each new version should be better than previous versions.

**Comment by Eiion** [comment]
Ok.
