### ISSUE TITLE
Spanish language updated

### ISSUE THREAD

**Issue by jose350** [Ryochan7/DS4Windows#124]
Hello I leave a copy of the source code, just modify the translation files to Spanish, update them as the old translation lacked meaning and spelling errors. I would appreciate you to add them to the last update

Thanks

[DS4Windows Update Spanish.zip](https://github.com/Ryochan7/DS4Windows/files/1348780/DS4Windows.Update.Spanish.zip)

**Comment by Ryochan7** [comment]
Localization support has not been a priority since I would not be able to maintain the files. I only remember a little Spanish and I have an elementary understanding of Japanese. Also, I need to look if the translation files can be bundled differently as I do not like the default behavior.

**Comment by jose350** [comment]
You are right I edit the Spanish language correctly, create my own version with the source code and it does not fit as there are some very long phrases and removes the aesthetics to DS4Windows the same I will work to adjust it in a better way and I share it again so that no You have to make adjustments, greetings

**Comment by Ryochan7** [comment]
Thank you for providing the updated Spanish translation files. I ended up finding a way to bundle the translation files differently than the standard .NET way and now all translation files will be bundled with the application. The only problem is that I think some of the culture specific translation files might not be set up properly.
