### ISSUE TITLE
rumble doesn't work

### ISSUE THREAD

**Issue by manafoo** [Ryochan7/DS4Windows#1243]
i play rocket league and rumble "vibrations " is not working , its enabled in the game and ds4settings ,does anyone else have this issue, my controller is a ps4 pro controller

**Comment by mika-n** [comment]
The same issue? The linked issue turned out to be a bug in Rocket League app.
#1142

**Comment by manafoo** [comment]
it doesn't work at all in the game that is , when i do test rumble in ds4windows it works,i will test hisgaurdian

**Comment by Ryochan7** [comment]
Rocket League does not support rumble for DirectInput which is how the game uses the DS4. You need to set the output controller to an Xbox 360 controller in order for rumble to work in game. It has nothing to do with the behavior of DS4Windows.

**Comment by manafoo** [comment]
it worked when i set it xbox 360 instead of ps4
