### ISSUE TITLE
(feature request) perm disable audio?

### ISSUE THREAD

**Issue by eldrickb** [Ryochan7/DS4Windows#1245]
every time I plug in my controller my audio auto switches to the controller. disabling the device doesn't persist through restarts for some reason. can we get a toggle in settings to disable controller audio permanently?

**Comment by mika-n** [comment]
The new upcoming version has couple code changes which makes this easier to do per profile. There is noways, for example, profile setting to disable rumble/ligthbar message writing to gamepad (ie. PC sends actively data to the gamepad). The same code base makes it easy to disable audio feature also if needed per profile (and per gamepad type in a code level). Let's put this to the TODO list.

**Comment by Ryochan7** [comment]
This is a Windows issue.
