### ISSUE TITLE
Controller not working with Battlefield 4. (2.0.16)

### ISSUE THREAD

**Issue by Norbi095** [Ryochan7/DS4Windows#1249]
Even with the latest version, Battlefield 4 does not work at all using the controller in wired mode.

**Comment by mika-n** [comment]
Read the "Read this before posting a new issue ticket" pinned message for more info what information to provide. 
When you say in "doesn't work in wired mode" then do you mean that "but works in wireless mode"? 
Is ds4windows profile using Xbox360 or Dualshock4 output mode?
Does the gamepad and the same profile work in other games and in JOY.CPL winOS controlPanel applet?
Using exlusiveMode (=Hide DS4 Controller option) or HidGuardian to hide the original (duplicate) gamepad device from games?

**Comment by Norbi095** [comment]
It works fine in wireless mode, but because of the headphone jack, I like playing in wired mode more.
Its is working fine in any other games, tried with "Hide DS4 Controller" option as well, did not work.
What i discovered though is that if I unplug the controller from a USB port and plug in to another then I suddenly starts working in-game. Before that, the game itself actually changes the UI to the controlller's layout, but does not respond to any input at all. Strange.
