### ISSUE TITLE
Minecraft issues

### ISSUE THREAD

**Issue by shade1333** [Ryochan7/DS4Windows#1250]
So, I'm trying to use this for minecraft cause I don't have a mouse, and none of the keyboard buttons work. I can look around, place blocks, punch, scroll through inventory, but I can't move, open inventory, or jump. And when I use the controller outside of minecraft, it does do the inputs so I know it's working. Sorry if you already talked about this issue, I couldn't find anything.

**Comment by Yohoki** [comment]
Try this profile. This is the one I use.
[Minecraft.zip](https://github.com/Ryochan7/DS4Windows/files/4555390/Minecraft.zip)
