### ISSUE TITLE
[TODO] Update Nefarius.ViGEm.Client.dll library so the newer API is used

### ISSUE THREAD

**Issue by Ryochan7** [Ryochan7/DS4Windows#1253]
Someone had mentioned issues with trying to use the ViGEmClient library with the DS4Windows source code. The person grabbed the NuGet version of the package and conflicts popped up. The big discovery from that issue was that it seems the refine API had been pushed out in a public release.

I had made a patch file before that converted DS4Windows to use the newer API but it was lost a while ago. I thought I had to add some custom bits to get it working the way I wanted at that time. A newer implementation will have to be written.

Also, there are some custom bits in the current version of the Nefarius.ViGEm.Client.dll file that DS4Windows uses. I believe some of those changes have made it upstream. Some testing will have to be done to make sure rumble functionality will still work as intended when using the newer API.

**Comment by mika-n** [comment]
I have kept eye on ViGem development. The new stock version of ViGemClient/ViGem.NET library no longer expose the "_nativeReport" record directly (the current version of DS4Windows app uses that record directly to set button states). Instead all button/axis/slider state values should be set one by one via an interface method calls and then command the .NET client to submit the nativeReport.

**Comment by Ryochan7** [comment]
Working on testing the refine API with the switchpromappertest project. The changes to the ViGEmClient API are not that huge so only some minor changes were required to get mapping support working again. However, the vanilla NuGet package seems to be a lot slower so using the vanilla package does not seem feasible.

I guess I had forked the upstream repo a while ago and made some custom modifications to an older version of the refine API. The next line of testing will be to figure out what I had attempted before since I have no idea how the changes performed..

https://github.com/Ryochan7/ViGEm.NET/commit/3ad3ca21f6384139041974abfb29d44efbf0711e

**Comment by Ryochan7** [comment]
Experiments have shown that pretty much all those changes will still be needed to get performance in line with what I want. With the most recent changes, it seems like I am getting slightly better performance than with the currently used library. I will have to delete my current fork of ViGEm.NET and fork the current repo code base.

It looks like these changes would affect at least three projects that I am working on.

**Comment by Ryochan7** [comment]
Got the most recent ViGEm.NET changes uploaded. This task can now be counted as finished.

https://github.com/Ryochan7/ViGEm.NET/tree/ryochan_api_changes
