### ISSUE TITLE
Not working on Mahou Arms

### ISSUE THREAD

**Issue by SubZero0** [Ryochan7/DS4Windows#1254]
It works fine for most games but not Mahou Arms specifically (no input).
It's a genuine Sony ps4 controller (CUH-ZCT2U).
Tried wired and wireless, hiding and not.

Might be worth to say my controller works fine in this game if I use Jays2Kings version (1.4.52)

Logs: 
[ds4windows_log_20200429.1.txt](https://github.com/Ryochan7/DS4Windows/files/4555737/ds4windows_log_20200429.1.txt)
[ds4windows_log_20200429.2.txt](https://github.com/Ryochan7/DS4Windows/files/4555738/ds4windows_log_20200429.2.txt)
[ds4windows_log_20200429.3.txt](https://github.com/Ryochan7/DS4Windows/files/4555739/ds4windows_log_20200429.3.txt)
[ds4windows_log_20200429.4.txt](https://github.com/Ryochan7/DS4Windows/files/4555740/ds4windows_log_20200429.4.txt)
[ds4windows_log_20200429.5.txt](https://github.com/Ryochan7/DS4Windows/files/4555741/ds4windows_log_20200429.5.txt)

**Comment by Ryochan7** [comment]
Are you using the "Use DInput only" option in the profile? No virtual Xbox 360 controller is ever plugged in according to the logs. Having that option enabled in a profile would be the main reason why no virtual controller would attempt to get connected.

**Comment by SubZero0** [comment]
Tried enabling "Use DInput only" wired/wireless (.6 log), still nothing.
Disabled hide (but kept the dinput only) wired (.7 log) also didn't work.
Can only move my mouse with the touchpad (in all cases), but no other input works.

[ds4windows_log_20200429.7.txt](https://github.com/Ryochan7/DS4Windows/files/4555804/ds4windows_log_20200429.7.txt)

[ds4windows_log_20200429.6.txt](https://github.com/Ryochan7/DS4Windows/files/4555803/ds4windows_log_20200429.6.txt)

**Comment by SubZero0** [comment]
I think I misunderstood you, the first logs were all with it disabled.
Enabled it for the only two above.

**Comment by Ryochan7** [comment]
Can you share the profile you are trying to use?

**Comment by SubZero0** [comment]
Sure, here it is
[Default.txt](https://github.com/Ryochan7/DS4Windows/files/4555957/Default.txt)

**Comment by Ryochan7** [comment]
I should have seen it before. There is no entry on PCGamingWiki for Mahou Arms but I doubt there is any form of DualShock 4 support in that game. The game likely only supports reading XInput controllers (Xbox 360 and Xbox One). Please make sure to use Xbox 360 for the Controller output mode in the profile. That way a virtual Xbox 360 controller will be connected when the profile is loaded.

**Comment by SubZero0** [comment]
It's an early access game so they are still working a lot on it. The Dev said it's a standard UE4 game, so they didn't add anything related to DS4, just that some people used ps4 controllers (with Jays2Kings DS4Windows and x360ce). Would you know what would they need to add to make it work so I can suggest it?

**Comment by SubZero0** [comment]
Think I found it, the Controller option, swapped it to X360. Tried hiding, not hiding, using only input and not. Still nothing sadly.
[ds4windows_log_20200430.0.txt](https://github.com/Ryochan7/DS4Windows/files/4558511/ds4windows_log_20200430.0.txt)
