### ISSUE TITLE
Is possible add a controller?

### ISSUE THREAD

**Issue by jinkazama82it** [Ryochan7/DS4Windows#1255]
Hi, today I write for a question: Is possible add different controller to DS4Windows?
More specifically it would be interesting to add the Thrustmaster T.Flight Hotas 4 (is the recent version for ps4) to the compatibile controller list but not because the controller isn't compatible with the PC but because some game simply don't recognize it (too old for recognize it) and map it like a xbox controller can be very useful.

**Comment by mika-n** [comment]
The first thing would be to run the DeviceDetect debug version while trying to connect the gamepad. Then provide the logfile generated by this debug app (add here as an attachment to a post).
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

**Comment by jinkazama82it** [comment]
Ok this is the log, the device in this long list is the first with the vid-pid: VID_044F&PID_B67C


[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/4559844/ds4windows_log.txt)

**Comment by mika-n** [comment]
The controller doesn't seem to be fully DS4 compatible. For example the HID usage flag is 0x4 instead of 0x5 (ds4 gamepads have this usage 0x5 attribute).

Anyway. You can try how it works when you force the debug version to accept devices with another usage flag value. Modify DS4WindowsDebug.exe.config file in a Notepad and set following option (it is in the end of the config file).
`  <add key="Debug_CustomHIDUsageFlag"          value="4" />
`

**Comment by jinkazama82it** [comment]
Yes the pc don't see it like a DS4 because is specifically made for be used in both hardware so probably the PS4 see it like a compatible controller and on PC it have dedicated Driver.
tonight i try to edit the line and see if it work.

**Comment by jinkazama82it** [comment]
this us the new log, and the controller don't appear controller label.

[ds4windows_log-1.txt](https://github.com/Ryochan7/DS4Windows/files/4561473/ds4windows_log-1.txt)

**Comment by mika-n** [comment]
Sorry. Based on the debug log there seems to be too many differences in how the gamepad acts (compared to DS4 gamepad protocol). Without having an actual hardware it is a bit too difficult to add support to it and it would require lots of changes to the existing "DS4 communication" protocol layer.

**Comment by jinkazama82it** [comment]
eh, I imagined, if you tell me how to do it I could try to do it ... always admitted no special programming knowledge is needed (I have some knowledge of programming in various languages, but never studied much).

**Comment by mika-n** [comment]
You should try to find out what kind of input (and optionally output) reports the gamepad HID device uses and what kind of HID API is required to read it (or write it). DS4Windows app has two different APIs to talk to a gamepad device. One of those low-level APIs might work with the gamepad you have (see Debug_ForceConnectionType debug option).

Then study is the gamepad "natively" in Windows xinput or dinput device. There are differences in WinAPI how to talk to those devices.

Finally you should study the input/output report structure sent by the gampad.

https://docs.microsoft.com/fi-fi//windows-hardware/drivers/hid/
