### ISSUE TITLE
Hold Button while moving?

### ISSUE THREAD

**Issue by Flo082002** [Ryochan7/DS4Windows#1256]
Hello,
I would like to use my PS4 controller for my CAD program. I want to use the Left Stick or the left up right down buttons to change the view. Normally I have to hold down SHIFT+ middle mouse button and then move the mouse to change the view.
Is that possible?

Many greetings
Flo S

**Comment by Ryochan7** [comment]
I guess it would technically be possible to add some virtual outer ring style button for the sticks. Although, it would still be limited to only being able to output one virtual action so your use case would still not be doable. The functionality would be pretty much limited to allowing Run or Walk functionality for games when mapping output to KB+M.

**Comment by Ryochan7** [comment]
Done in 3.0.11. Also, related issue #1508
