### ISSUE TITLE
Lightbar stays on after PC shuts down (wired)

### ISSUE THREAD

**Issue by admiralzeech** [Ryochan7/DS4Windows#1258]
Hi, I'm using an official DS4 on Windows 10, plugged in via USB cable.

Using the latest version of DS4 Windows.

Everything is working fine, except when I shut down my PC, the light bar stays on (solid blue colour).

In my DS4Windows settings, I have the bar colour set to black.  It's black/off while the controller is connected to DS4Windows, as expected.

This problem does not occur if I close DS4Windows before shutting down, or if I unplug and then replug the controller after the PC is off.

Is this some sort of setting somewhere? Or a bug?

**Comment by mika-n** [comment]
Is PC feeding power to the usb port even when the PC is shutdown? Try other USB port which doesn't feed power when PC is shutdown and this way forces the usb connected DS4 gamepad to shutdown itself also.

Or try to play with "ligthbar passthrough vs normal" setting. Anyway. Here DS4 ligthbar is not lit when PC is shutdown, so maybe this is something to do how the usb power behaves after shutdown.

**Comment by admiralzeech** [comment]
Yes, I believe the PC is feeding power to the USB ports, I'm not sure if I actually have any ports that don't do this.

However, why does it behave as expected when I close DS4Windows manually and then shutting down, as opposed to shutting down the PC with DS4Windows open?

I assume when you shut down windows, it closes all open programs anyways?  Or is this maybe just a timing thing?

**Comment by admiralzeech** [comment]
Oh, I should mention, even though the PC is feeding power to the USB ports (I had a gaming mouse whose LEDs would also stay on), the DS4 isnt actually getting charged - the battery goes flat if I leave it like this overnight.
