### ISSUE TITLE
Can we play psnow with DS4 controller from your software ?

### ISSUE THREAD

**Issue by Lacertaenova** [Ryochan7/DS4Windows#1262]
All is in the title ^^
The ps button and touchpad of the DS4 controller (version 1) doesn't work to play psnow (ps4) games ? Have you a solution to fix this or is it impossible ?

It is impossible to bind the touchapd and ps button ?
Thanks for your answer and sorry for my poor english.
Sincerely,

**Comment by deadair3210** [comment]
ps now uses it's own driver which takes over the controller

**Comment by Ryochan7** [comment]
The PS button should work. There is currently no support for the touchpad nor the gyro in ViGEmBus so mapping that data is not possible now. Someone has gotten touchpad integration working in a test build of ViGEmBus so maybe touchpad integration for an emulated DS4 will be possible in the future.

If you are using a proper Sony branded DS4 controller, it would be best to just not run DS4Windows before starting Remote Play. You will be forced to play wired.
