### ISSUE TITLE
Profile Cycling with hotkey cycles only 1 profile until window is opened.

### ISSUE THREAD

**Issue by Spairus** [Ryochan7/DS4Windows#1263]
I think I remember 2.0.5 fixing this, but a few versions later (not sure which) I found it happening again. 2.1.0 still has this problem:

When running DS4Windows with "start minimized" enabled, it seems like profiles don't actually load in until you click the taskbar icon to open the UI. The result is, swiping with two fingers cycles only your last used profile (you can tell from the pop-up notification repeating the same message every time). 

Exiting ds4windows and running it again can reproduce the problem, so it doesn't require a reboot.

**Comment by mika-n** [comment]
profile switching seems to be working here through a special action key trigger or "swipe touchpad to switch profiles" options.
