### ISSUE TITLE
How to use modifier key (control) with hotkey?

### ISSUE THREAD

**Issue by vanclute** [Ryochan7/DS4Windows#1264]
I'm using my DS4 not for gaming, but for a specific application.  I want to be able to assign a bunch of hotkeys that all use the control key as modifier (Control-1, Control-2, etc.).  But in DS4Windows every time I try to assign a keystroke, the instant any one key is pressed the windows closes.  It seems impossible to create a hotkey that uses a modifier key, is this so?

I even tried making a macro that did Control, then keystroke, then release keystroke and release control.  It did absolutely nothing at all.  I'm stumped on how to get this to work for me.  Any suggestions?

**Comment by Ryochan7** [comment]
The macro approach would be the way to go. You would probably have to add a pause between the Control key down and 1 key down actions. Some games require a pause between a modifier key press and a secondary key press. The only old example that I can think of is The Witcher 1; it might have been to initiate looting but I cannot remember for sure. Normal actions can only be bound to one output. I can get a screenshot with an example in a couple of minutes.

**Comment by Ryochan7** [comment]
Ctrl+1 example. Need to enable Record Delays to add the Wait steps and you have to double click the Wait steps to edit the time duration.

![ds4windows_macro_example](https://user-images.githubusercontent.com/581968/81223345-7a2a6600-8fab-11ea-82ec-486acbb59fd2.png)

**Comment by vanclute** [comment]
Hmmmm ok, this isn't for a game though and the execution speed is critical, so I'm not sure this is going to work for me after all.  I'll experiment with it... thanks!

**Comment by vanclute** [comment]
I stand corrected, just a single 1ms delay on only the first step (between the Ctrl key and my chosen keypress) has done the job.  Anything after that is irrelevant.  Thanks!
