### ISSUE TITLE
my controller disconnects after 5 minutes when I'm not using it (bluetooth)

### ISSUE THREAD

**Issue by nizeyanal** [Ryochan7/DS4Windows#1265]
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/4579742/ds4windows_log.txt)
in the log file it says "disconnecting due to idle disconnect". How can i disable this so the controller will not disconnet by him self?
Its an original sony dualshok 4 controller.
I captured the disconnect time with DS4Windows turned off and the controller is disconnecting after 15 minutes. If DS4Windows is on then the controller is disconnecting after 5 minutes. How to fix?

**Comment by mika-n** [comment]
DS4Windows profile settings have (Other tab page) Idle Disconnect setting. If this is enabled and a time set then DS4Windows will force disconnect the gamepad if there are no button activity within the set time period. So, try unticking this option.
