### ISSUE TITLE
MPC - DS4W don't work in this window

### ISSUE THREAD

**Issue by onolox** [Ryochan7/DS4Windows#1266]
Hi, first, great work!
I have this problem, whenever I bring the window of Media Player Classic x64 to active state the controller simply stop working altogether, if I change the active window the controller start working normal again.
No auto profiles used.
Can you test and see if works for you?

Other players work normal.
Nothing different in the logs.

**Comment by Ryochan7** [comment]
It is likely a UAC permission issue; MPC is likely running as an elevated process. The main way around that problem would be to run DS4Windows as the Administrator. That is a limitation of using the SendInput API for generating virtual KB+M events.

**Comment by onolox** [comment]
Oh, it worked, thanks!
