### ISSUE TITLE
DS4Windows permanently broke my Dualshock 4 connection with my PC

### ISSUE THREAD

**Issue by stargoonman** [Ryochan7/DS4Windows#127]
So this used to happen when DS4Windows didn't turn off the controller properly for those connected with Sony's adapter. It has been "fixed" since then.

When this happened, I had to change the USB port of my Sony adapter, or else the controller would be stuck in solid white light. It's somehow connected to the computer as some things are recognized (like in sound device), but it will never get recognized by games or DS4Windows.

DS4Windows reports:
Found controller: 00:00:00:00:00:00 (SONYWA)
Controller 1 is using Profile "Me"

but in the list of controllers it says "No Controllers Connected (Max 4)".

**Now here is the important part.** Recently, it shut off my controller improperly somehow and now it's stuck in permanent solid white.

I can't use this controller at all.

**Comment by Ryusennin** [comment]
But it's not really "broken", is it? You can simply reset your DS4 with a paper clip.

http://ccm.net/faq/36785-how-to-reset-your-playstation-4-controller

**Comment by stargoonman** [comment]
I'm aware of the little hole and I tried resetting it. It doesn't work.
It did break the connection.

**Comment by OptimalJew** [comment]
@stargoonman This part: "When this happened, I had to change the USB port of my Sony adapter, or else the controller would be stuck in solid white light." sounds a lot like an issue I ran into multiple times with InputMapper before I switched. Can you open Device Manager and check the Human Interface Devices tab to see if anything is disabled, and if it is, right click > enable?

**Comment by Ryochan7** [comment]
I would normally say that exclusive mode might have permanently disabled your controller and that you might need to re-enable it in the Device Manager. However, the lightbar being stuck at solid white does not fit that problem. Are you sure you do not have PS4 controller support enabled in Steam BPM? You cannot use Steam's DS4 remapping support and DS4Windows at the same time.

**Comment by pralima87** [comment]
This happens to me every now and them.
Just enable the "HID controller" in the Device Manager.

The solid white bar means the controller is connected to the PC but the PC can't detect it.

**Comment by SeemsFishy** [comment]
I can confirm that issue. Sometimes after fresh boot or sleep mode my SONYWA is not recognized properly. I fix that manualy through the Device Manager menu. I am not sure this is DS2Windows problem, could be just  another "Windows 10 new update problem".

**Comment by Ryochan7** [comment]
There is the rare occasion that I still run into the DS4 being permanently disabled by DS4Windows. It happens far less often than with the older versions of DS4Windows though and more fixes have been made to fix odd edge cases. In the end, the problem stems from how exclusive mode is being obtained. Disabling and then re-enabling a device quickly does not seem to work gracefully.

**Comment by Ryochan7** [comment]
Unfortunately, one edge case was toggling the Hide DS4 Controller option.

**Comment by SeemsFishy** [comment]
The new version .97 works better so far.

**Comment by pralima87** [comment]
A workaround would be nice to refresh the "HID-compliant game controller" on startup.
Manually enabling it on every startup is kind of annoying.

**Comment by stargoonman** [comment]
Still doesn't work on the latest version 1.4.99.

If I refresh "HID-compliant game controller", the controller lights green, but it never shows up on DS4Windows.

I get

Found controller: ~~~~ (SONYWA)
Found X360 Controller #1
Plugging in X360 Controller #1
X360 Controller #1 failed. Using DInput only mode.
could not open DS4 ~~~~~ exclusively. You must quit other applications blabla
Note: I quit every single applications I can from task manager just to test it and it doesn't work.

I can't use my DS4 even without this program anymore. It's been over a month and this issue is still not fixed. Thanks for breaking it.

**Comment by Ryochan7** [comment]
If nothing else, it works fine on my system and that is what matters most. At some point, not having to rely on the disconnect and re-connect method to attempt to force getting exclusive access would hopefully get rid of problems like this.
