### ISSUE TITLE
Controller keeps intermittently disconnecting

### ISSUE THREAD

**Issue by BamHam99** [Ryochan7/DS4Windows#1273]
I have my DS4 connected to my PC over a USB BT dongle. The only other device that's also paired with the dongle is a wireless speaker. Normally everything works flawlessly but starting today the controller keeps randomly disconnecting itself around an average frequency of every 10 minutes. I don't think it's a problem with the dongle since the wireless speaker continues to be paired and outputs audio just fine. Everytime the controller disconnects I see the following in the logs: "Gamepad data write connection is lost. Disconnecting the gamepad. LastErrorCode=1167" Any help with this would be appreciated thanks.

**Comment by mika-n** [comment]
Please provide more details (logfiles, app versions). Run a special debug version to generate more detailed logfiles.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

Try running without any other BT devices and even while WLAN is disabled. Sometimes even WLAN can cause issues with BT hosts (both share partially the same radio frequencies).

**Comment by Ryochan7** [comment]
The error code 1167 corresponds to Windows Error **ERROR_DEVICE_NOT_CONNECTED**. It looks like the DS4 device is getting disconnected from Windows for some reason. Not sure if the upcoming output report changes would help with this problem or not; BT connections seem better on my system with code changes for the upcoming release (version 2.1.1). I hope to get version 2.1.1 released sometime soon.

https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--1000-1299-

**Comment by Ryochan7** [comment]
Also, make sure you do not have Idle Disconnect enabled in your DS4Windows profile; it is enabled by default.
