### ISSUE TITLE
Controller readings tab greyed out

### ISSUE THREAD

**Issue by dankjan** [Ryochan7/DS4Windows#1280]
I am using the latest version of DS4Windows, but, whenever I try to open the profile settings and go to controller readings, it is unclickable (greyed out). If I try to use an older version of DS4Windows, like 1.7.17, the tab opens. Any idea on why I can't see the readings on newer versions? Thank you.

**Comment by mika-n** [comment]
Press "Edit" profile button in Controllers tab page (ie. where it lists all connected gamepads). This way the Readings tab is bind to that specific controller

**Comment by dankjan** [comment]
Yeah, I can see the readings this way, but in profiles it still is greyed out. Nevertheless, it's enough for viewing the readings I guess. Thank you, and have a good day.
