### ISSUE TITLE
cant play as ps4

### ISSUE THREAD

**Issue by dukkiedodo** [Ryochan7/DS4Windows#1281]
when i change my controller to ps4 nothing works in a game and when i change it to xbox it does work

**Comment by Rogus** [comment]
Does the game supports direct input like Ni No Kuni II Revenant Kingdom supports? I have the game and it supports dualshock prompts and the dualshock controller also. There are little developers that makes ps4 controller support for these games that has ports in steam and gog and origin and that epic games store. I've noticed a problem with ds4windows and steam as soon as you opens ds4windows steam closes down the controller support. Try disabling steam run at startup and enabling this one for DS4Windows. And reboot, see if that changes.

**Comment by mika-n** [comment]
Please see the "Read this before posting a new ticket" and Troubeshooting tips. The issue about Steam client and DS4 virtual output controllers is mentioned there.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#steam-doesnt-see-the-virtual-output-controller-if-a-profile-uses-the-dualshock4-output-type-steam-sees-the-ds4-controller-only-if-ds4windows-uses-xbox360-output-controller-type

Another possibility to cause something like this is HidGuardian tool and DS4v1 revision1 gamepad type. HidGuardian may accidentally hide both physical DS4v1 and virtual DS4v1 devices. The following post explains this and gives few ideas what to do (if you have physical DS4v2 gamepad then tweak HidGuardian AffectedDevices sysreg config entry).
https://github.com/Ryochan7/DS4Windows/issues/720#issuecomment-499097172

**Comment by dukkiedodo** [comment]
i did everything but i still dont understand can someone help me?

**Comment by mika-n** [comment]
Please read the "Read this before posting" message. There are instructions what minimum information to provide. We can't do much without logfiles, app version information, the profile file you have created. Zip those and place here as an attachment (drag and drop the zip file to a comment field).

**Comment by Ryochan7** [comment]
Filing this under "The Thing Don't Work" and possibly "Using the Application Wrong". The game being played, whatever it is, likely does not support DualShock 4 controllers in the first place. Xbox 360 emulation is likely required which is the reason to use DS4Windows in the first place.
