### ISSUE TITLE
Bind TrackPad Press

### ISSUE THREAD

**Issue by niklas2233** [Ryochan7/DS4Windows#1282]
Hey as you know alot of games uses the select button to open maps or scoreboard from COD and other games but now the select button has dissapeared and been replaced with a share button. Is there a way to map the pressing the trackpad on a DS4 v2 controller to the share buttton when making a custom profile?

**Comment by mika-n** [comment]
You can map three different regions of the touchpad to any gamepad or keyboard or mouse key. If you need to map the "whole touchpad click" to one event then you can map all three regions to the same output key.

**Comment by niklas2233** [comment]
I want to map the share button as trackpad click but I can't find a way to do it

**Comment by mika-n** [comment]
Oh, the other way around. Hmm... Indeed, it is not possible to do it that way in DS4Windows (ie. map Share button as TouchPad click button). Technically there is nothing preventing the mapping that way, but DS4Windows "forgot" to offer such an option. Originally DS4Windows did not even have Dualshock4 output controller type, so the touchpad click as a target event was not even possible. Laster on DS4 output type was added into DS4Windows app, but the keypad mapping routines were never updated to support touchpad click as a target. It can be only source event.

**Comment by Ryochan7** [comment]
There is no way to do that currently. I did not see a need to offer support for assigning Touchpad Click when adding output DualShock support. The assumption was that people would just click the DS4 Touchpad when needed so the Touchpad Click button state is just transferred to the virtual DS4. Maybe it would be useful for third party DS4 controllers with no Touchpad; I would think that those controllers would provide a button to output Touchpad Click like the Hori Mini seems to offer.

**Comment by mika-n** [comment]
One scenario where I see some benefit of re-mapping other keys to "touchpad click" event is when touchpad is used as a mouse (move and click mouse buttons), but still some game needs to receive "touch click" event. Then for example Share button could be used to send out the "touch click" event.

**Comment by adrianodennanni** [comment]
Sorry for ressurecting this old issue, but I am not able to map Touchpad Click -> Touchpad Click for every kind of click (left, right, upper or multi). I am just able to map touchpad clicks to other buttons/keyboard.
The Death Stranding game, a previously PS4 title, uses the touchpad licks natively for actions in game, and I can't find anyway to use them via DS4Windows.

**Comment by Ryochan7** [comment]
The way it is set up currently, clicking any region of the Touchpad will transmit the Touchpad Click action to the virtual DS4. Although I don't see myself using it, I have a commit pending that allows other DS4 buttons to be bound to output Touchpad Click.

**Comment by Ryochan7** [comment]
This is now an option in version 2.1.8.
