### ISSUE TITLE
[Feature] Verbose Logging

### ISSUE THREAD

**Issue by joseashb** [Ryochan7/DS4Windows#1283]
Hello mate,

was wondering if you could add verbose logging to the log panel, to disable things such as if hidguardian was able to hook to the controllers, keys being pressed and so on, as it become way easier for troubleshooting issues

Thanks

**Comment by mika-n** [comment]
The app doesn't have such verbose logging option at the moment, but maybe some day. However, I personally don't see this as high priority issue.

**Comment by Ryochan7** [comment]
Right now, there are only two levels used for logging: INFO and WARN. For the most part, I don't see a need to further categorize message types to limit which messages appear in the log; I guess the Auto Profile debug info does not need to appear in the output log text file. Also, the HidGuardian messages would likely always be tagged as INFO. That info is more useful to me when looking at someone else's posted log files.

**Comment by Ryochan7** [comment]
I finally got around to fixing the problem with auto profile debug messages being written to the log file.
