### ISSUE TITLE
Difference between LoadProfile and LoadTempProfile

### ISSUE THREAD

**Issue by cubatilles** [Ryochan7/DS4Windows#1285]
Hi,

I'm testing some CLI options (described on the wiki). And found these two options about loading profiles from CLI:
DS4Windows.exe -command LoadProfile.<controller#>.<profile name>
DS4Windows.exe -command LoadTempProfile.<controller#>.<profile name>

But could not find any explanation of both, and why should be better to use one or the other. Based on my experience, LoadProfile is the same as changing profile manually from the GUI, while LoadTempProfile acts silently changing the profile like the Auto-Profiling system (the change is not reported on the GUI).
I also found that changing the profile with LoadTempProfile and then changing it again with LoadProfile does not seem to take effect, the profile loaded with LoadTempProfile is always active  until you change it again with LoadTempProfile.

Could any dev explain why these two options exist, the difference between both and why should I choose one over the other?

Thank you so much.

**Comment by mika-n** [comment]
Yes, right. The Documentation. It is always left as "will be done when nothing better to do".

Anyway. The difference between LoadProfile and LoadTempProfile is
- LoadProfile = The same as changing the profile via GUI in "Controllers" list. This becomes the new default profile for the controller. The controller loads the default profile after disconnect/re-connection.

- LoadTempProfile = Temporary profile does not change the default profile of that controller. Temp profiles in DS4Windows are usually part of special actions (LoadProfile action type). This is a bit like "Mode 1" spec action as described in the following web page. The temp profile needs to be unloaded (ie. reset back to default profile) before new profile can be loaded. This explains why LoadTempProfile doesn't allow LoadProfile to do anything. Well, cmdline doesn't have unload trigger, so it is a bit weird logic in cmdline interface.
https://github.com/Ryochan7/DS4Windows/wiki/Settings#how-to-change-a-profile-on-the-fly-via-a-certain-gamepad-button-using-a-special-action

The temp profile concept is legacy code derived from the original Jay2Kings version. The cmdline interface was added in this Ryochan7 version, but the concept of profile loading was never refreshed. 

But, which one should you use? LoadProfile or LoadTempProfile?  It depends whether you want to change the default profile setting also. If/When profiles are re-saved then the controller remembers the last default profile after re-connection.

**Comment by cubatilles** [comment]
Oh,
Thanks for the fast and perfect explanation @mika-n . Indeed, LoadTempProfile is what I want.
Btw, regarding your method about hiding the physical DS4v2 while whitelisting the emulated DS4v1 which you explain here:
https://github.com/Ryochan7/DS4Windows/issues/669#issuecomment-487302990
There is an error on the regedit content. Your code:

```
HID\VID_054C&PID_09CC&REV_0100&MI_03
HID\VID_054C&PID_0BA0&MI_03
HID{00001124-0000-1000-8000-00805f9b34fb}_VID&0002054c_PID&05c4
HID{00001124-0000-1000-8000-00805f9b34fb}_VID&0002054c_PID&09cc
```

lacks the antislash (\) after the "HID" string on the last two lines. The correct code is:
```
HID\VID_054C&PID_09CC&REV_0100&MI_03
HID\VID_054C&PID_0BA0&MI_03
HID\{00001124-0000-1000-8000-00805f9b34fb}_VID&0002054c_PID&05c4
HID\{00001124-0000-1000-8000-00805f9b34fb}_VID&0002054c_PID&09cc
```

With your method the emulated DS4v1 is still blacklisted. Once corrected with the missing backslashes, the code works as expected. I use it to play PSNow where XInput controllers don't support gyro neither touchpad functions, which some games require. With your trick and an autoprofile for PSNow it works like a charm. I suggest you to update the closed issue (which is referenced through the Wiki to accomplish the desired functionality) so that other users don't have problems setting it up on the future.

DS4Windows is the ultimate gaming controller software for Windows. Thanks to you and @Ryochan7 for the great work, and keep it up guys!

Greetings.

**Comment by mika-n** [comment]
Thx for noticing the backslash error in BT device strings. The backslash actually was there, but github decided to remove it because of the curly bracket (I guess github treated the backslash as special escape char). I modified to comment to use "CODE" editor block to make sure github won't try to do special tricks with chars.
