### ISSUE TITLE
Motion/sixaxis gyro drift to the left.

### ISSUE THREAD

**Issue by gitlava** [Ryochan7/DS4Windows#1286]
Hi,  I have two brand new controllers.  One doesn't do this as bad, but the other drifts to the left.  Using the most recent ryochan7 fork version of DS4Windows.  I notice this in Cemu and splatoon the worst.  That game has no calibration options internally that I can find.  I have been told that steam has a fix for this sort of thing, but I don't want to use steam.  I looked for motion calibration in ds4windows, but came up short, I tries playing with sixaxis deadzones but no luck.

Anyone have any suggestions?

Thanks

**Comment by Chase-Lebo** [comment]
I'm having the same issue now too. I tried on two controllers with similar results. I don't remember this happening until a few days ago.

**Comment by gitlava** [comment]
Yeah, I'm at a loss.

**Comment by Chase-Lebo** [comment]
Hey so i was able to fix it by deleting all my profiles and then delete omg the entire ds4windows folder and uninstalling the driver. Then I reinstalled everything and now it seems to be working fine

**Comment by gitlava** [comment]
Sadly, not for me.

**Comment by mika-n** [comment]
Closed as "hardware issue" (LS/RS stick is never completely stable in hardware level, so small deadzone is usually required with all gamepads and LS/RS analog sticks). Deadzone can be set either in DS4Windows profile settings or via a game specific options.
https://github.com/Ryochan7/DS4Windows/wiki/Settings#axis-zone-mapping

However, users of CEMU are in a bit different group than those users who use DS4Windows directly. Deadzone/output linearity settings are not applied to UDP server used by CEMU emulator, so CEMU users have to hope that CEMU or game supports axis tweaks. Or maybe sometimes in the future the re-mapping logic of DS4Windows would be applied to CEMU UDP server also.
