### ISSUE TITLE
Cohabitation between PS4 controller and Joystic Thrustmaster T.16000M

### ISSUE THREAD

**Issue by A-312** [Ryochan7/DS4Windows#1287]
Hi,

I also have a [joystick T.16000M](http://www.thrustmaster.com/products/t16000m) but if I use/launch in same time DS4 windows, this broke my driver of T16000M and my joystick doestn't work anymore with [TARGET](http://ts.thrustmaster.com/download/accessories/pc/hotas/software/TARGET/TARGET_User_Manual_ENG.pdf). I need to uninstall/remove my T.16000M and reboot my computer to be able to play again with my joystick.

Is there a way to blacklist some driver ?

**Comment by mika-n** [comment]
Hmmm...... DS4Windows should not do anything with a device it doesn't recognize as DS4 or compatible. Anything in DS4Windows logfiles? %APPDATA%\DS4Windows\Logs

Or maybe you should run the debug version of DS4Windows to generate more detailed logfile
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

Do you use HidGuardian tool or the built-in "Hide DS4 Controller" option in DS4Windows?

**Comment by A-312** [comment]
I use the default settings, I will retry
