### ISSUE TITLE
Opening steam overlay using PS button.

### ISSUE THREAD

**Issue by yaz981** [Ryochan7/DS4Windows#1288]
Hello, DS4WINDOWS works fine with every game I ran from steam big picture, the only problem I am facing is when I press PS button( middle button) while in-game it doesn’t open steam big picture overlay.

Is there way to enable it?

**Comment by raff-run** [comment]
Pretty sure it still works with Steam, as I had to go configure steam to stop doing it. Are you sure you didn't disable it through steam? Try checking Steam(big picture mode) -> settings -> Controller settings and seeing if your controller is checked, then check Steam(big picture mode) -> settings -> base controller settings -> desktop configuration. You can also check if the overlay is enabled.

Also, windows itself seems to use that button for its Game Bar, so there might be interference from there, too.

**Comment by shinra358** [comment]
you can open anything you want by using the map program to a button feature in ds4windows
