### ISSUE TITLE
Compensate the gyro drifting

### ISSUE THREAD

**Issue by cubatilles** [Ryochan7/DS4Windows#1289]
Hi,

DS4Windows is an awesome piece of software. I do make us of the gyro capabilities to simulate mouse movement and play lightgun games on several emulatores, which is a pleasant control scheme.

There is something which makes the experience not perfect, though. 

The gyro hardware built on DS4v2 (I've read somewhere this did not happen on DS4v1, but who knows) has some type of drifting on the gyro sensors, that's why DS4Windows has an option to setup deadzone on the gyro, which defaults to "5" or "10", which is enough to compensate the drifting when using the default 100% gyro sensitivity.

The problem comes when using the gyro on large sessions. The deadzone does its work when the gyro is not being used (so that the mouse will not move because of the deadzone even though it has some permanent drifting), but if you are playing a lightgun game, for example, where you have your DS4's gyro permanently moving, the deadzone makes no effect (which is of course the correct behaviour according to the deadzone concept), so that if you have a drifting  where your gyro permanently drifts to down, this effect will keep moving your pointer down at the same speed if your movement exceeds the deadzone setting, so every minute or so (depending on the amount of drifting you have on your DS4 gyro) you have to reposition your DS4 on  your hands every so.

I hope I have explained myself well enough, english is not my natural language.

I guess this could be solved by implementing a "constant deviation correction" button or something like that, which allows you to calibrate your gyro so that DS4Windows knows exactly the drifting  amount and it applies this difference while calculating the movement  when you do use the gyro. I mean, if I have a drifting to down which causes permanent drifting of "5" (I use here the deadzone values, I don't know if it means 5% or 5 pixels per second or whatever) to down, it would be enough to compensate (with an equitative oposite value) when DS4Windows reads any gyro movement and apply the result to the mouse output movement.

Can something like this be implemented? It would make my lightgun games experience much better.

Thank you so much guys.

**Comment by AstralStorm** [comment]
Actually, the better fix would be to keep deadzone around current gyro value, rather than 0. Gyro is not a relative control.

**Comment by Ryochan7** [comment]
I have played longer game session, spanning several hours, using Gyro controls. Fortunately for me, I have not really come across an issue with drift when using the DS4 gyro. Testing out adding a Kalman filter might be worth doing in the future.

Gyro drift has been a major problem for me in the past with the Wiimote Motion Plus gyro. The fact that the Wiimote gyro takes a long time to stabilize and it can deviate greatly depending on usage made me stop playing games with the Wiimote Gyro + Nunchuk control scheme. The routine I used at that time took a certain number of measurements upon startup, while the controller was resting on a surface, and would average out a drift compensation value from that.

This video is probably one of the better examples of my experiments with the Wiimote Gyro. Granted, this footage was recorded after having the gyro warm up for about 30 minutes.

Wiimote MotionPlus - Borderlands: TPS:
https://www.youtube.com/watch?v=bnzdi4plCAE

**Comment by val3nt33n** [comment]
With DS4windows, I have huge drift on my DS4v1 that immediately pushes the mouse into the top left corner and makes gyro unusable. Even with deadzone set to 100, once I start moving the controller the mouse starts drifting a lot.
I've been playing with JoyShockMapper, which has a gyro calibration feature and that works perfectly. There is no drift at all after calibration. If you are curious, the code is here: https://github.com/JibbSmart/JoyShockLibrary/blob/master/JoyShockLibrary/JoyShock.cpp

**Comment by firodj** [comment]
My controller's gyro also have a drift. I try to using CEmu Zelda with [Cemuhook](https://cemuhook.sshnuke.net/padudpserver.html) to use motion when targeting the enemies with  bow, but it is become hard because the view is always moving. Thanks @val3nt33n for referencing the idea how to create the gyro calibration, here is a PR if want to add that feature: https://github.com/Ryochan7/DS4Windows/pull/1776 @Ryochan7 

For testing: https://files.sshnuke.net/PadTest_1011.zip

**Comment by Ryochan7** [comment]
This feature was added in version 2.2.3.
