### ISSUE TITLE
PC hang for a few seconds when turning off controller

### ISSUE THREAD

**Issue by gimli520** [Ryochan7/DS4Windows#1291]
Hi there. First let me say thank you very much for making DS4Windows.

I just have a small problem. When I turn off my PS4 controller, my pc will hang for a second or 2. Meaning it will kind of soft freeze, my mouse won't respond or anything. This hang up only lasts a few seconds but I was wondering if there is a way to fix it.

I have DS4Windows fully up to date.

TYVM

**Comment by mika-n** [comment]
Are you running DS4Windows on system boot? Does it behave the same if you launch DS4Windows "manually" (ie. not automatically as a task or system boot app) using "Run as administrator" option in FileExplorer?

**Comment by gimli520** [comment]
> 
> 
> Are you running DS4Windows on system boot? Does it behave the same if you launch DS4Windows "manually" (ie. not automatically as a task or system boot app) using "Run as administrator" option in FileExplorer?

Thank you very much for replying!

I honestly did not know I could run it at boot, but to answer your question I do not, I only turn it on just before I start a game.

I have not tried running the program as Admin, but when I get home later I can try it and post back with my results.

**Comment by gimli520** [comment]
> 
> 
> Are you running DS4Windows on system boot? Does it behave the same if you launch DS4Windows "manually" (ie. not automatically as a task or system boot app) using "Run as administrator" option in FileExplorer?

Hi there again, seems using it through Admin seems so far to solve the problem. If it happens again, will post again. 

Thank you!

**Comment by catscarlet** [comment]
> 
> 
> > Are you running DS4Windows on system boot? Does it behave the same if you launch DS4Windows "manually" (ie. not automatically as a task or system boot app) using "Run as administrator" option in FileExplorer?
> 
> Hi there again, using it through Admin seems so far to solve the problem. If it happens again, will post again.
> 
> Thank you!

Can you test it like this?
1. Open DS4Windows with DS4 connected, Exclusive Mode(Check Hide DS4 Controller in the Settings panel). Check if Exclusive Mode is working(See in the Log Panel)
2. Open [HTML5 Gamepad Tester](https://html5gamepad.com/) with Firefox or Chrome
3. See if computer got freezed/hanged with 12 seconds or more(Mouse or keyboard with absolutely no response)?

Please test and it will help me a lot. Thank you.
