### ISSUE TITLE
Controller inputs only work after program restart

### ISSUE THREAD

**Issue by raff-run** [Ryochan7/DS4Windows#1293]
I have DS4Windows running on boot as a Task, and for some days now (started noticing it 05/18), and when I first connect the controller, none of the inputs work, save for the trackpad/clicks. Then when I try to stop the service and start it up again to redetect the controller, the program "hangs" on "closing vigembus connection" forever (but remains responsive), and I have to close DS4Windows. Then when it starts up again, things work as normal.

Here are the logs:
[ds4log.txt - before restarting, first run after pc boot](https://github.com/Ryochan7/DS4Windows/files/4665773/ds4log.txt)
[ds4log reboot.txt - after restarting](https://github.com/Ryochan7/DS4Windows/files/4665777/ds4log.reboot.txt)

**Comment by shinra358** [comment]
same here. had to revert back to the one i had 2.0.13

**Comment by mika-n** [comment]
Does it do the same if you start the latest version of DS4Windows without "start on boot option"? Ie using FileExplorer to to run DS4Windows.exe?

**Comment by shinra358** [comment]
will check now. funny thing is, everything functions as if it is working correctly but nothing happens when youre in a game. brb.

**Comment by shinra358** [comment]
restarted with the new version just to double check and make sure. I notice when on the new version and I go to the joy.cpl, only one of my controllers is turned on, yet there are 3 instances of the controller active in the .cpl. Official pc games, the controller works. Emulators, the controller does not work. 

Restarting pc again with start on boot option off. brb

**Comment by shinra358** [comment]
ok, back. unfortunately there is no change. I ran the program as admin manually from windows and I still had to restart ds4windows in order to get the controllers to work. All the lights and connection sounds worked as they were supposed to. just that on first run, nothing happened in emulators when you pressed things. Only on official pc games. 2 instances of xbox controllers were in the joy.cpl without any controller turned on before I turned them on.

**Comment by Ryusennin** [comment]
I haven't noticed that behaviour on Win7 nor Win10.

The two controllers appearing in the game control panel seem to point to an exclusivity issue. I'm using HidGuardian, so my physical device is hidden. Some apps/games will be confused if they have to pick between the physical and virtual device.

**Comment by shinra358** [comment]
this issue has happened throughout the history of this program's development when updated. i've been here since the beginning. If it is an exclusivity issue, it is in this version of the program for it is not in version 2.0.13. I haven't tested the versions in between 2.013 and 2.1.1.

**Comment by mika-n** [comment]
The first logfile has "data write connection is lost" error message. DS4Windows app uses data writing sequence (BT) to check if the gamepad is still conneted or disconnected/battery dead/force shutdown via PS button. If rumble and lightbar data writing (ie. PC and DS4Windows app sends data to DS4 gamepad) fails then the app assumes DS4 was unexpectedly disconnected.

`05/21/2020 20:49:58: Gamepad data write connection is lost. Disconnecting the gamepad. LastErrorCode=1167
`

The latest version of DS4Windows has a new profile option "Enable Output data to DS4" option in profile/Other tab page. If you disable this then does it work better at boot time? Unticking this option does mean that lightbar and rumble doesn't work, but this is just to test this theory. Maybe the "data write connection is lost" logic is too aggressive and it should wait a bit longer before it decides that "hey, the connection really is gone" (sometimes BT connection may have some temporary "radio wave" related hiccups).

**Comment by mika-n** [comment]
And a side note from another issue. Interesting finding about "WinOS fast restart" feature in case it is enabled. 
https://github.com/Ryochan7/DS4Windows/issues/1163#issuecomment-633664971

**Comment by shinra358** [comment]
I have windows installed to an ssd with programs installed on hdds. So my
hibernation mode is turned off to not wear down ssd.

**Comment by mika-n** [comment]
This "Fast Startup" is not exactly the same as hibernation mode. I have nothing but SSDs disk and hibernation disabled, but this "Fast Startup" is still an additional option behind the "Choose what power buttons do" ControlPanel configuration options.
https://www.windowscentral.com/how-disable-windows-10-fast-startup

**Comment by shinra358** [comment]
I do have that and it is on. But it was always on and andi shouldnt have to
toggle a system option for a version of a program for it to work when a
precious version works w it. I can toggle to test but i cant keep it there
for i know startup will be slow af after shutting it off 😂

**Comment by mika-n** [comment]
Well, i cannot tell a difference in startup times with or without that option. I guess SSDs are nowadays so fast that that option is a historical HDD tweak. Anyway, please read the earlier comment about trying with a profile "Enable Output data to DS4" option unticked also.

**Comment by shinra358** [comment]
I turned that option off. Nothing is shown in joy.cpl with it off. But there's no change in the controller working. Still have to restart ds4 once for proper functionality. also with it off, Lightbar not showing correct color.

**Comment by deadair3210** [comment]
Fast startup is basically hybrid hibernation, it saves the kernels memory and any states that can be preserved between sessions, and discards the rest of memory. It tends to cause issues with driver's especially kernel ones that have to interact with another program or a attached device

It's recommended to leave it off by most people as it only helps if you have a slow boot drive or low ram

**Comment by shinra358** [comment]
Just read that fast startup is on win8 and above. Win7 doesn't have fast startup. We have quickboot and that's only accessible via system bios and I don't believe it's the same thing.

**Comment by deadair3210** [comment]
Yeah it was added with 8, quick startup or fast startup in most old bios versions before 8 came out refers to a setting where the bulk of the POST can be skipped after the first full success, which speeds up how long the comp spends in the bios before checking and loading the os

**Comment by raff-run** [comment]
Just updating that I haven't been able to reproduce the issue anymore for a few days now(just tried it), despite having it for a while. Thing is, I don't think I have changed anything at all. Maybe it really was a case of a "failed handshake" over bluetooth like @mika-n said?

**Comment by raff-run** [comment]
Reading the log more carefully now, I think this bug will only happen if your controller has a low battery and tries to connect. I don't know if being at startup is at all relevant in this case actually, because this line is different from the usual "Controller 1 was removed or lost connection." entry:

05/21/2020 20:49:58: Controller 1 was removed or lost connection. Charge the battery

I assume then that when the program flow falls onto this condition, the removal of the controller from some dictionary is not done, which leads to this when you try to connect again:

05/21/2020 23:15:32: An item with the same key has already been added.

And since the exception is not handled properly, the controller stays connected.

**Comment by shinra358** [comment]
My controllers were around 80% since ive been chatting with you guys.

**Comment by raff-run** [comment]
I see. I looked at the code now and it really doens't seem the case anymore. The condition that makes the log display "charge the battery" does just that, and apparently doesn't influence anything.

`if (device.getBattery() <= 20 &&
                        device.getConnectionType() == ConnectionType.BT && !device.isCharging())
                    {
                        removed += ". " + DS4WinWPF.Properties.Resources.ChargeController;
                    }`

**Comment by shinra358** [comment]
I'd like to add that 2.1.0 works properly if that narrows something down.

**Comment by teeedubb** [comment]
Hi,

I have begun noticing the same - that input doesnt work in games and sometimes it works if I restart the game, other times I need to restart my PC. Digging deeper it seems a 'ghost' controller is created upon startup. I just rebooted my pc and this is what happens:
1. After logging in, I head the windows chime and get a notification that a controller was lost or disconnected - no controller has been turned on at this point.
2. joy.cpl shows a xbox360 controller connected, though no DS4 or other controllers are connected.
3. After turning on the DS4 a second controller shows in joy.cpl.
4. When I stop DS4 windows both controllers disappear from joy.cpl.
5. After starting DS4windows (without turning off the 1x DS4) only 1 controller shows in joy.cpl.

Some notes:
*Battery was at 100% when I did this test.
*I have seen it happen when connected via USB, though I mainly use it via BT
*I am using HID guardian and for completeness sake I reinstalled it the other day.
*DS4windows is running as admin at startup
*I always shutdown my PC when finished with it

Something's I will try:
*Using v 2.1.0
*https://github.com/Ryochan7/DS4Windows/issues/1293#issuecomment-633677788
*See if turning off the controller before shut down helps.

![New Bitmap Image](https://user-images.githubusercontent.com/3460068/83351048-1ca7f000-a384-11ea-95da-7ec17b1b139f.jpg)
[ds4windows.txt](https://github.com/Ryochan7/DS4Windows/files/4707560/ds4windows.txt)

**Comment by raff-run** [comment]
Something like that just happened to me: I played Witcher 3 and turned off my computer without disconnecting the controller first. When I booted it up today, I found a similar log:
[boot without connecting a controller.txt](https://github.com/Ryochan7/DS4Windows/files/4708007/boot.without.connecting.a.controller.txt)

It detected the controller despite it not being connected yet, and started the xbox controller simulation 
![image](https://user-images.githubusercontent.com/44688128/83357675-290c5880-a344-11ea-8179-72d623cb88f1.png)

I'll try to reproduce it as well.

**Comment by mika-n** [comment]
@raff-run  Have you disabled the Windows "fast startup/fast boot" option in power plan options? If not then can you try how it goes when this fast startup is disabled.
https://www.asus.com/us/support/FAQ/1031533/

In practice fast startup is useless option in todays SSD PCs. If PC has an ancient HDD disk then fastStartup may be able to improve Windows boot up times by caching various information between boots. The theory is that this fast startup may cache virtual controllers created by ViGem driver and this way screws up the next boot up.

**Comment by raff-run** [comment]
Hey! Sorry for the delay. I tried reproducing it today, still with fast startup on, and it seems the last update actually fixed this. When the computer boots, DS4Windows detects and connects the ghost controller, then disconnects it. I guess it doesn't need to keep the virtual controller alive in case of reconnection anymore since we can specify permanent controllers, which is nice.

Here's the end of log when attempting this now:
![image](https://user-images.githubusercontent.com/44688128/83701976-b91afe00-a5e1-11ea-82f0-ff3a453116c5.png)

@shinra358, try the new update, if it also works for you this issue is pretty much solved.

**Comment by shinra358** [comment]
Yes it works correctly. Was actually talking about the new version's
features in some other threads

**Comment by raff-run** [comment]
Neat, I'll close it then. Thanks everyone!
