### ISSUE TITLE
[Sony Dongle] Disconnect actions

### ISSUE THREAD

**Issue by pralima87** [Ryochan7/DS4Windows#13]
Not sure if is possible but is there any chance the app options to disconnect the controller could work trough the dongle?

**Comment by Ryochan7** [comment]
Currently, there is no way in the stable build to disconnect a controller connected to the Sony Dongle. I just recently got one and I have been editing DS4Windows to treat a controller connected to the dongle differently. The current source does allow for disconnecting a controller from the Controllers tab but no progress has been made regarding getting the Disconnect BT special action working with the dongle.

The problem when adapting the Disconnect BT action is that the virtual controller created by the dongle will then repeat the last known state of the previously connected wireless controller. Having the virtual controller continue to spam the PS button can cause some major problems with some applications like Steam.

**Comment by pralima87** [comment]
Yeah being looking all around and so far there is really no propoer way to send disconnect commands trough the dongle.
Only the holding the PS button since is hardcoded in the controller.

Thanks for the detailed answer! ;)

**Comment by pralima87** [comment]
Idle disconnect for sony dongle works! Cheers!

But there is a problem were the controller will stop working when reconnecting.
The app needs to be restarted to register the controller again.

**Comment by Ryochan7** [comment]
I managed to work around the problem and idle disconnect works in the new version.

**Comment by pralima87** [comment]
Yep is working fine ;)!
