### ISSUE TITLE
thanks for your works, dev. i need help!

### ISSUE THREAD

**Issue by idioteque914** [Ryochan7/DS4Windows#130]
first, i really appreciate to your works.
what a nice program that i want!
but, i got a problem from ds4windows.
when i playing fifa18, if i press direction button, then it work twice.(also left analog stick too)
and other command button(circle, square, cross, triangle) are not work correctly.
anyway, i'm using latest version of this on win10(1703).
what happened to me? have any others issues like this?

**Comment by OptimalJew** [comment]
Have you tried the 'Hide DS4 Controller' setting?

**Comment by idioteque914** [comment]
yes, i tried that setting. but still have problems.
if i check 'hide ds4 controller', all buttons going to normal.
but, right analog stick have no signal.

**Comment by idioteque914** [comment]
please help me.. i need solutions..

**Comment by OptimalJew** [comment]
Have you tried disabling DS4Windows, connecting your DS4 via USB, and playing FIFA18 via directinput?

**Comment by idioteque914** [comment]
yes, i tried. using usb cable without ds4windows.
it was same situation that i checked 'hide ds4 controller'.
no input from right analog stick.

**Comment by OptimalJew** [comment]
Sounds like a problem with the game itself. Googling 'FIFA 18 right stick' gives me pages of people with that problem, with a variety of proposed fixes.

**Comment by idioteque914** [comment]
oh, thanks! i'll find that way.

**Comment by Ryochan7** [comment]
Looks like you have already gone through the main troubleshooting steps. I have never played a FIFA game so I don't know about any possible issues with the game itself. If the game sees the XInput controller rather than the DirectInput DS4 controller then I would hope that everything would just work. It looks like there is a demo available from Origin so I will check it out on my system and see if I run into the same problem.

**Comment by Ryochan7** [comment]
XInput emulation works fine in FIFA 18 on my system. I can perform style moves and switch players with the right analog stick.

**Comment by idioteque914** [comment]
thanks you so much. i solved my problems!
how kind you are!

**Comment by Ryochan7** [comment]
Sarcasm noted
