### ISSUE TITLE
DS4Windows not linking profile correctly on startup

### ISSUE THREAD

**Issue by t824601** [Ryochan7/DS4Windows#1300]
Version : DS4Windows 2.1.1

Hardware : 
3 DSU controllers
3 Sony Bluetooth receiver

When configuring each controller on a different profile the software keeps rotating each time it restarts regardless if the  link profile is selected.

This causes issues when playing games when the controllers keep changing which one is number 1 2 3 or 4. Even when adding the game/emulators quick profile the controller still follows the DS4Window order even if the controllers are not connected.

Any fix would be appreciated :)

Below are some images illustrating the controller order. In this case only one controller was connected via the wireless adapter and it was still identified as controller 4. This was the one with the DS1 profile that was originally confifured as controller 1. Had to reconfigure the emulator as it was this time recognizing it as controller 4.

Thank you!!

<img width="591" alt="2020-05-27 18_05_18-DS4Windows" src="https://user-images.githubusercontent.com/66043081/83084318-d41bca00-a045-11ea-8e70-b4dfbd56f04c.png">
<img width="1920" alt="2020-05-27 18_08_03-Greenshot" src="https://user-images.githubusercontent.com/66043081/83084322-d5e58d80-a045-11ea-8335-9637f5b0a287.png">

**Comment by Ryochan7** [comment]
The dongle presents itself to Windows as a controller even when no DS4 is synced to it. Disconnect the unused dongles.

**Comment by t824601** [comment]
Yes, that would work, except this is installed on an arcade machine.I fixed the issues by going 100% Bluetooth so I don't have to deal with these issues.Thank you for the quick response! RobertOn May 27, 2020 6:46 PM, Travis Nickles <notifications@github.com> wrote:
The dongle presents itself to Windows as a controller even when no DS4 is synced to it. Disconnect the unused dongles.
