### ISSUE TITLE
DE Language not shown

### ISSUE THREAD

**Issue by Flo082002** [Ryochan7/DS4Windows#1302]
Hello,
five weeks ago I added the German language and Ryochan7 merged my commits. https://github.com/Ryochan7/DS4Windows/pull/1229
Unfortunately, German is not shown in the latest version from two weeks ago.
Anybody have any idea what the problem that might be?
Many greetings
Florian S

**Comment by Huseriato** [comment]
Thank you for adding german language. It's not shown to me, too. I'd like to push this a little bit, because I think it should not be a big issue to solve this.

**Comment by dondrakon** [comment]
German language added to project and I can switch language to German when I build project from the code. Looks like @Ryochan7 forget to add German translation to a release script. 

@Ryochan7 could you check your release script?

**Comment by Flo082002** [comment]
It works
