### ISSUE TITLE
I can't get any of the gamepad buttons to behave as a toggle

### ISSUE THREAD

**Issue by taoliu12** [Ryochan7/DS4Windows#1309]
I can't get any of the gamepad buttons to behave as a toggle, even with toggle checked in the key mapper window. Therefore, I cannot toggle keyboard keys, mouse buttons, or other controller buttons.

**Comment by Ryochan7** [comment]
The mapper only uses that option for keyboard key bindings. It isn't set up to work for emulated gamepad buttons.

**Comment by raff-run** [comment]
Would be nice if we could map key combinations to other gamepad buttons. I recently had to do some serious remapping on Witcher 3, and had to map a key combination, R2 + Circle, for example, to Q (the keyboard equivalent of R2), but then the game briefly thinks I'm trying to play with the keyboard, so it swaps all UI to match keyboard keys. This problem would be alleviated if I could just map R2 + Circle to R2 instead.
