### ISSUE TITLE
Feature request: update without prompt

### ISSUE THREAD

**Issue by 3thanfox** [Ryochan7/DS4Windows#1311]
Can't find a way to set this up, if there isn't one, request feature to enable DS4Windows to auto download/install updates in background (without prompt) upon launch.  Just makes it more streamlined when installed on a multipurpose/family HTPC/game system.  Thanks!

**Comment by mika-n** [comment]
Disable auto-update check in DS4Windows settings and setup a separate TaskScheduled job to run "DS4Updater.exe" app. If there is a new version available then running this updater app directly will download and install it. Well, there is one issue when DS4Updater.exe is run manually. The app remains open until user clicks "close" button, but a clever task script could force shutdown the process after a while.

**Comment by Ryochan7** [comment]
I am usually against the idea of software auto-updating itself. Using Windows 10 and issues with its update process have re-enforced that stance. I would suggest that you uncheck **Check for DS4Windows Updates at Startup** for the time being. There is a link in the Settings tab to have DS4Windows check for an update at any time so you can use that when desired.

On a somewhat related note, a possible update in the future would be to tell DS4Windows to stop update prompts from appearing until another new version has been released.
