### ISSUE TITLE
Permanent controller does not reset the state upon disconnect

### ISSUE THREAD

**Issue by Uiasdnmb** [Ryochan7/DS4Windows#1313]
I tried using permanent controller and it was nice at first but then my applications (especially UWP) were behaving oddly.

I noticed that after disconnecting (wireless) ds4, virtual controller is not wiping out button states. It keeps whatever buttons were down as down until ds4 is replugged, and in case of using (default) PS button + options to disconnect it just makes pause trigger everywhere.

**Comment by shinra358** [comment]
I guess this is same issue I was just having
