### ISSUE TITLE
Keyboard binds not working on tilt/ swipe/ touch in game

### ISSUE THREAD

**Issue by Venithien** [Ryochan7/DS4Windows#1317]
Hello. I have read many posts on here looking for a solution to my problem.
The problem is inconsistent and sometimes, after restarting DS4Windows several times, it works, however after many attempts, I have not been able to get it to work.

I use DS4Windows for PSO2. I have the touchpad and gyro set up to use the keys 1 through 0.
However, sometimes, this does not work. It's working in notepad, it's working in Discord, but not in game.

Based on similar issues I've seen on here, reddit, and various forums, I've tried many different solutions, but none seem to work; so far, repeatedly restarting the program and testing each time has been the only effective method, and it's not a permanent solution, as after restarting my PC, it breaks again. Additionally, I've restarted at least twelve times today and it isn't working, and I'm kind of at a loss.

When launching the application, I always right-click and run in administrator mode.
"Hide DS4 Controller" is enabled and there does not seem to be a problem with it.
I've tried enabling and disabling "Scan Code" for the key inputs, but it makes no difference.
I've attempted to use HidGuardian instead of "Hide DS4 Controller" on the off chance exclusive mode wasn't properly functioning, but there wasn't any change.
I've made sure no other controller using applications are running, including nvidia geforce experience and the nvidia overlay.
Any help would be greatly appreciated. I haven't had a use for github up until today so I'm sorry if this post ends up terribly formatted.

**Comment by Venithien** [comment]
Sorry, only just saw the "Read before posting" notice. I am using a regular Sony DS4 controller. The back label has long since fallen off. Uploading log files from previous attempts. DS4Windows is registering my controller and shows exclusive mode as functioning properly. I have tried both this version and the old J2K version and both have the same issue.

[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/4729013/ds4windows_log.txt)
[ds4windows_log_20200604.10.txt](https://github.com/Ryochan7/DS4Windows/files/4729014/ds4windows_log_20200604.10.txt)
[ds4windows_log_20200604.11.txt](https://github.com/Ryochan7/DS4Windows/files/4729015/ds4windows_log_20200604.11.txt)
[ds4windows_log_20200604.12.txt](https://github.com/Ryochan7/DS4Windows/files/4729016/ds4windows_log_20200604.12.txt)
[ds4windows_log_20200604.13.txt](https://github.com/Ryochan7/DS4Windows/files/4729017/ds4windows_log_20200604.13.txt)

**Comment by mika-n** [comment]
Do you mean that DS4Windows re-map rules are working OK while you test it in Notepad, but at the same time the same re-map rules don't work in PSO2 game (whatever that is)?

Sorry, but this sounds like a game specific issue if exclusive mode or HidGuardian is doing its magic (ie. the game doesn't accidentally pickup the physical gamepad instead of the re-mapped virtual gamepad). DS4Windows profile should behave the same and it doesn't even know which app is using the virtual output controller.

What do you see in JOY.CPL controlPanel applet when DS4Windows is running? Do you see only one gamepad there (x360 if ds4windows profile uses xbox360 output mode)?

There has been cases where those simulated keyboard and mouse events sent by DS4Windows app are ignored by certain apps. Some apps handle kbd and mouse in "low level" instead of doing it via traditional IO message queue. In those cases the game never handle simulated kbd/mouse events even when it probably receives those events.

Or do you mean that sometimes DS4Windows doesn't work at all in any app?

Maybe you should attach the profile file here (as zip or TXT file) in case there is something weird.

**Comment by Ryochan7** [comment]
Haven't gotten around to re-installing PSO2 since I re-installed Windows. The game uses GameGuard for anti-cheat protection but SendInput events do work in game. I am going to assume that the game probably runs with admin privileges so DS4Windows probably has to be run as the Administrator in order for virtual KB+M events to work in game.

I will get PSO2 installed again and test my hypothesis later today,

**Comment by Ryochan7** [comment]
Running Windows on the main Admin account is not enough. You have to choose the **Run as Administrator** option from Windows Explorer. There is also a way to set it permanently in Properties > Compatibility.

![ds4win_run_as_admin](https://user-images.githubusercontent.com/581968/83790391-bcec6600-a65d-11ea-81a5-a9f861534b24.png)

**Comment by Venithien** [comment]
I have it set to run as administrator under compatibility settings, yes. I can also right-click to run as administrator and have tried that as well many times, in case the compatibility settings weren't working properly for whatever reason, but the keybinds still don't work in game.
Images attached just to confirm that it's in administrator mode, and also that the application is running properly in exclusive mode according to the check next to the ID and status.
![admin](https://user-images.githubusercontent.com/66413173/83792870-4e110c00-a661-11ea-8842-00ebd4c7bf05.png)
![hide ds4](https://user-images.githubusercontent.com/66413173/83792884-55381a00-a661-11ea-8cb6-fd451cd0fc02.png)

**Comment by Venithien** [comment]
I'm at a loss. I've tried wiping all of my profiles and just about every solution I can think of, but the problem still persists. I even reinstalled the game itself. I don't have an indicator of what the issue actually is so it's really hard to fix. I've tried reinstalling device drivers and even the game itself to no avail. Is there anything else I could do to help identify what's going wrong?

**Comment by mika-n** [comment]
Sorry. I have also run out of ideas. The profile you sent looks OK. One thing to check is if you have any other 3rd party "bling bling AsusRog keyboard LED bling bläng hotkey" app running. Try without those services/apps in case those cause some conflicts.

**Comment by Cameron-Naidoo** [comment]
Try recording a macro instead of just using the key press. Tick the record delays checkbox and press the key for a realistic amount of time. The delay between press and release might allow the game to poll the key without missing it.

**Comment by Ryochan7** [comment]
The log shows that you are definitely running DS4Windows as the admin. Have you made any progress figuring out this problem? KB+M bindings worked fine for me the few times I have tried in PSO2. I have only played through the initial tutorial sequence. I will try the profile you have posted in a bit.

**Comment by Ryochan7** [comment]
Swipe action to use Monomate works fine for me

**Comment by bridgewaterrobbie** [comment]
I can confirm I am also seeing similar behavior as I try to play PSO2 (Phantasy Star Online 2)

I can attach logs and such tomorrow, but I have tried running DS4Tool in administrator mode with no luck.

I am specifically trying to map trackpad events to keyboard presses, though I also tried some gamepad buttons as a test.

I would note that the NA release of PSO2 is a weird mix of UWP and non UWP app- it's an 8 year old game that finally came to the US, and it's launcher is a UWP app (This has caused many issues for the game in general- not sure if it might be mucking up DS4Windows compatibility)

**Comment by bridgewaterrobbie** [comment]
Sorry for the double comment, but I want to get to the bottom of this (For my own sake at least)


Ryochan7, are you playing the JP version of the game or the new NA version? I wonder if we are comparing apples to apples here. If you are playing the NA game, which method did you launch it with? I have been using the popular "PSO2 Tweaker" which resolves some of the other issues that the official launcher off of the Windows store has.

**Comment by Venithien** [comment]
I've tried many things and still no progress. I am playing the NA version through the tweaker like bridgewaterrobbie is if that does make any difference. Every time I load up the game I try different things for 30 or so minutes, but so far no dice. I tried using a macro but it also didn't work.

**Comment by bridgewaterrobbie** [comment]
Just noting, I tried the Windows on-screen keyboard, which DID work in PSO2 where DS4 can not. Not sure if that helps.

**Comment by bridgewaterrobbie** [comment]
Sorry for another double post, but I just half-solved the problem.

If you close DS4 tool, start PSO2 and THEN open DS4Tool, keypresses will work as expected. 

This does not require DS4 tool to be opened in admin mode. It also does not require the press be of "Scan code" type.

**Comment by Ryochan7** [comment]
> Ryochan7, are you playing the JP version of the game or the new NA version? I wonder if we are comparing apples to apples here. If you are playing the NA game, which method did you launch it with? I have been using the popular "PSO2 Tweaker" which resolves some of the other issues that the official launcher off of the Windows store has

I am running the new NA version downloaded from the Microsoft Store. I am just using the official launcher to start the game.

I am not sure why the virtual events would work fine if DS4Windows is launched  after the game is loaded but not before. That does not happen on my system.
