### ISSUE TITLE
Computer won't go to sleep, monitors/displays do not turn off

### ISSUE THREAD

**Issue by rcdailey** [Ryochan7/DS4Windows#1318]
DS4Windows 2.1.1 keeps my PC from sleeping. It also keeps the monitors from turning off after the designated idle time. Note during this time I do leave my DualShock PS4 controller plugged into USB. I dug around settings but didn't see an option for "Prevent sleep" or similar option.

**Comment by Ryochan7** [comment]
I am going to assume that some virtual KB+M events are being sent from DS4Windows so Sleep mode will not activate. Either that, or maybe there is some jitter with the analog sticks that would be counted as active input; not sure if Windows takes controller input into account regarding stopping Sleep mode from activating.

Either way, you very like need to add a dead zone for both LS and RS. I will give this a try later.

**Comment by rcdailey** [comment]
On the "Controller Readings" page, I do see the RY (I) value jumping back and forth between 130 and 131. So that must be it.

Also is there a way to disable the SixAxis/Gyro? I don't need it and it might also be creating unnecessary movement keeping PC awake.

**Comment by shinra358** [comment]
Firstly he should get 2.1.2

**Comment by rcdailey** [comment]
I'm already running that, but I don't see how that is relevant to my issue.

**Comment by shinra358** [comment]
Because you said 2.1.1 and latest version is needed to see if issue still there...

**Comment by rcdailey** [comment]
Same behavior on 2.1.2. I neglected to mention that this has been an issue since the 1.x days before the fork.

**Comment by rcdailey** [comment]
Closing this as I was able to work around this issue by setting error to 0.10 on X and Y

**Comment by McNippleson** [comment]
Hi guys after changing hardware (but importing old profile) my monitors stopped going to sleep, however it happens even with DS4windows stopped, plugged controller is enough to cause this.

In controller readings I see X(I) and Z(I) jumping around a bit which is gyro reading. Can they be the culprit? Any way to disable gyro?
