### ISSUE TITLE
Nacon Revolution Pro 1

### ISSUE THREAD

**Issue by UnitedFN** [Ryochan7/DS4Windows#1320]
I bought a Nacon Revolution Pro 1 2-3 years ago and it worked perfectly when I reprogrammed the buttons on my laptop and when used on my PS4.
I recently bought a PC and I want to use it to play fortnite, but it’s not recognized by the latest version of Ryochan7 DS4 Windows even though I have disabled it from device manager since it was identifying as an audio device. I have the latest version of DS4 and the latest drivers. Please help soon
Thanks

**Comment by mika-n** [comment]
We can't do anything without logfile. Please take a look at the pinned post for instructions how to find logfiles. And try running a special debug version to generate more detailed logfile.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems
