### ISSUE TITLE
Fifa 20 Random Inputs and Double Controller Bug

### ISSUE THREAD

**Issue by Ins3rt3Z** [Ryochan7/DS4Windows#1321]
I have tried starting Fifa through steam and ive tried using Hide DS4 Controller in exclusive mode but nothing has worked.

**Comment by Ryusennin** [comment]
Old exclusive mode doesn't work in FIFA. You need HidGuardian to hide the physical controller.

**Comment by Ryochan7** [comment]
You are pretty much forced to use HidGuardian when playing the FIFA games. If it weren't for the Microsoft driver signature paywall then I would probably remove the old "Hide DS4 Controller" option entirely at this point. Although I don't use vanilla HidGuardian, here is a small installer for it.

https://github.com/Ryochan7/DS4Windows/wiki/DS4Windows-and-HIDGuardian-Install-and-Setup-Guide#hidguardian-test-installer
