### ISSUE TITLE
[Suggestion] Make DS4Updater preserve name of (renamed) DS4Windows executable

### ISSUE THREAD

**Issue by Robyer** [Ryochan7/DS4Windows#1322]
I had problems with Steam or Steam games not supporting virtual DualShock4 controller (instead of Xbox 360). I read here that it is because Steam checks if DS4Windows.exe process is in memory and if it is then it just ignores DualShock4 controllers in system and solution is to rename DS4Windows executable (and manifest) to something else. This indeed works, but after each update, new DS4Windows.exe is created and started by updater, so I had to manually exit app, delete my (old) renamed files, rename (new) files again to different name and start app again.

If updater could get current filename of my executable (either by running DS4Windows app providing it as argument, or just by searching for executables in program folder) and then preserve this name after update (i.e. delete old exe/manifest, extract new exe/manifest, rename new exe/manifest to old name), that would be great.

What do you think?

**Comment by mika-n** [comment]
Or disable the automatic update option in DS4Windows and create a batch file to run ds4pudater.exe app once a week and if the updater downloads a new version of DS4Windows.exe then the batch file would automatically rename it to a custom name.

**Comment by Robyer** [comment]
That's a possible workaround, but wouldn't be better to solve the situation for all users of DS4Windows who want to have working DualShock emulation with Steam rather than forcing all these users to come up with own workarounds?

Also I'm now sure how easily this workaround could be done (I see few complications with that) and it would probably require much more work than integrating it directly into DS4Updater code.

**Comment by Ryusennin** [comment]
Renaming the executable is already a nasty workaround in itself (which you don't need to use if you simply disable Steam Input).

**Comment by Ryochan7** [comment]
My stance is that you should not attempt to use DS4Windows and Steam Input at the same time. Other controller types, besides the DS4, should still be usable within Steam Input while DS4Windows is running. The only time where any issue with compatibility might pop up would be games that take advantage of the SCAPI. A game would likely fallback to XInput (Xbox 360) support if SCAPI is not used.

**Comment by Robyer** [comment]
@Ryochan7 Wait what does it mean "not attempt to use DS4Windows and Steam Input at the same time"? When I open Controller settings in Steam I have everything unchecked there. Problem is that I don't even see there the (emulated) DualShock controller there when DS4Windows executable is not renamed. Btw I have enabled "Hide DS4 Controller" option.

My idea was to always use emulation of DS4 controller in order to get in-game icons for DS4 buttons instead of Xbox 360 buttons when the particular game supports it. Right now I play mainly Last Year game, which doesn't support DS4 icons yet, but otherwise controls works (when DS4Windows executable is renamed). When DS4Windows wasn't renamed and I wanted to emulate DS4, game wasn't getting any input from controller. I don't understand what exactly is going on or what magic Steam does or why it ignores the DS4 controller when it finds DS4Windows executable running?

**Comment by mika-n** [comment]
This behavior is a stupid decision by Valve and it is not only DS4Windows related issue. Some other apps (InputMapper, x360ce etc) suffer from the same issue (ie. Steam actively ignores DS4 gamepad type). I guess they fear that people are confused and may keep asking Valve why DS4 gamepad behaves the way it does in Steam.

https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#steam-doesnt-see-the-virtual-output-controller-if-a-profile-uses-the-dualshock4-output-type-steam-sees-the-ds4-controller-only-if-ds4windows-uses-xbox360-output-controller-type

**Comment by mika-n** [comment]
the latest version has some tweaks in how "custom DS4Windows app name" can be used via Task.bat batch file.
