### ISSUE TITLE
Auto-profile + Watch Dogs 2

### ISSUE THREAD

**Issue by Flea-2B** [Ryochan7/DS4Windows#1327]
I use the auto-profile to change to the DS4 profile for games that support it natively, until now I didn't had had any problem with it, but with Watch Dogs 2 in particular it just doesn't seem to trigger the change, I've tried all the executables of the game folder and it still doesn't works, I've used the task manager to pinpoint that specific executable and still, no dice

Anyway, not a big problem by any means, I created some special actions to change profiles by swiping the touchpad, just thought I'd report this glitch

These are some of the debugging msgs during the game launch

`06/08/2020 02:26:23: DEBUG: Auto-Profile. PID=4144  Path=d:\jogos\ubisoft game launcher\games\watch_dogs2\bin\splashscreen.exe | WND=1511034  Title=

06/08/2020 02:26:35: DEBUG: Auto-Profile. PID=4868  Path=d:\jogos\ubisoft game launcher\upc.exe | WND=2034360  Title=uplay

06/08/2020 02:26:40: DEBUG: Auto-Profile. PID=4144  Path=d:\jogos\ubisoft game launcher\games\watch_dogs2\bin\splashscreen.exe | WND=1511034  Title=

06/08/2020 02:27:02: DEBUG: Auto-Profile. PID=6900  Path=c:\windows\explorer.exe | WND=1839158  Title=watch_dogs2

06/08/2020 02:27:24: DEBUG: Auto-Profile. PID=10592  Path=?atch_dogs2 | WND=1576570  Title=watch_dogs 2

06/08/2020 02:28:29: DEBUG: Auto-Profile. PID=6900  Path=c:\windows\explorer.exe | WND=2558648  Title=bin

06/08/2020 02:28:33: DEBUG: Auto-Profile. PID=10592  Path=?in | WND=1576570  Title=watch_dogs 2

06/08/2020 02:28:36: DEBUG: Auto-Profile. PID=6900  Path=c:\windows\explorer.exe | WND=65734  Title=

06/08/2020 02:28:37: DEBUG: Auto-Profile. PID=6900  Path=c:\windows\explorer.exe | WND=11075930  Title=start menu

06/08/2020 02:28:39: DEBUG: Auto-Profile. PID=6900  Path=c:\windows\explorer.exe | WND=65752  Title=

06/08/2020 02:28:40: DEBUG: Auto-Profile. PID=6884  Path=e:\rafael\ds4w\ds4windows\ds4windows.exe | WND=131094  Title=ds4windows

06/08/2020 02:29:30: DEBUG: Auto-Profile. PID=10592  Path=?s4windows | WND=1576570  Title=watch_dogs 2

06/08/2020 02:29:38: DEBUG: Auto-Profile. PID=6900  Path=c:\windows\explorer.exe | WND=65734  Title=

06/08/2020 02:29:39: DEBUG: Auto-Profile. PID=6900  Path=c:\windows\explorer.exe | WND=11207002  Title=start menu

06/08/2020 02:29:41: DEBUG: Auto-Profile. PID=6884  Path=e:\rafael\ds4w\ds4windows\ds4windows.exe | WND=131094  Title=ds4windows

06/08/2020 02:30:19: DEBUG: Auto-Profile. PID=10592  Path=?s4windows | WND=1576570  Title=watch_dogs 2`

**Comment by mika-n** [comment]
What kind of auto-profile rules you have tried (process and wndTitle search keywords)?

Have you noticed that rule keywords support wildchars? And if the actual game process isn't recognized, but a loading splash screen is recognized then try setting a auto-profile rule to the splash screen process/wndTitle and UNTICK the option "Revert to default profile on unknown process". This way the WD2 splash screen triggers the profile change and leaves it active even if the main process might not trigger any foreground or wndTitle rules (why? don't know).
https://github.com/Ryochan7/DS4Windows/wiki/Profile-selection-using-auto-profile-rules

**Comment by Flea-2B** [comment]
my dumbass had no idea the other line was for the window title lol

that was my bad, thanks @mika-n !
