### ISSUE TITLE
Ds4 Windows Keeps Crashing

### ISSUE THREAD

**Issue by JoelLindsey** [Ryochan7/DS4Windows#1329]
Everytime i try and open ds4 windows it crashes right away. I've tried to reinstall didnt work.

**Comment by mika-n** [comment]
Please read the pinned "Read this before posting a new issue ticket". Your post don't have much information to comment on.

**Comment by Ryochan7** [comment]
This issue does not help diagnose the problem at all. Need logs.

**Comment by vyrelis** [comment]
Having the exact same problem. Where are logs saved to? Application crashes immediately so log cannot be opened and exported, the program is frozen. Using 2.1.1 for now

**Comment by Ryochan7** [comment]
The issue posted in that log file was fixed in version 2.1.3. Since this issue is dead, it is probably safe to close it.
