### ISSUE TITLE
Controller randomly goes off during game

### ISSUE THREAD

**Issue by T33JAY** [Ryochan7/DS4Windows#1332]
I've been having this issue since I started using ds4windows 2 years ago and I've decided to finally speak up. I play a lot of online FIFA and 3 out 10 times my controller just randomly goes off or stops working in game. And if I alt + tab I lose the game. With the newest updates I can now see the log of what happened and it always says this

Gamepad data write connection is lost. Disconnecting the gamepad. LastErrorCode = 1167

I get this so many times it's unbelievable. Any help on how to never see this again?

**Comment by T33JAY** [comment]
I've repaired the game a couple of times and I figured the problem wasn't FIFA. I don't see the HidGuardian option in settings. What does that do?

**Comment by mika-n** [comment]
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

https://github.com/Ryochan7/DS4Windows/wiki/DS4Windows-and-HIDGuardian-Install-and-Setup-Guide#hidguardian-test-installer

HidGuardian is not an option in DS4Windows, but an additional piece of software (not part of DS4Windows, but DS4Windows supports it). If the built-in "Hide DS4 Controller" option doesn't work in some PC setups then HidGuardian driver solution is alternative solution to hide the original physical controller and to workaround "double input" type of problem.
