### ISSUE TITLE
Not really an issue more of a request

### ISSUE THREAD

**Issue by MikinhaGodv2** [Ryochan7/DS4Windows#1335]
Hi i recently switched from reWASD to this new version of ds4windows,and i used a custom deadzone there,but when i tried to copy them into ds4 it didnt work, so  i was wondering if you could show me how these deadzone settings would be on ds4

[deadzone.txt](https://github.com/Ryochan7/DS4Windows/files/4762633/deadzone.txt)

**Comment by mika-n** [comment]
The config file is from reWASD app? Sorry, but you have try to explain what and how deadzone is setup in that config file and what you want to do and what doesn't work. No one probably wants to go through the reWASD config file line by line trying to understand what is there.

https://github.com/Ryochan7/DS4Windows/wiki/Settings#axis-zone-mapping

**Comment by Ryochan7** [comment]
I have barely used reWASD so I am not too familiar with how its mapping system works.

**Comment by MikinhaGodv2** [comment]
Sorry, i want to know how these deadzone numbers "  sensitivity: "x": 29394  "y": 28844 "x": 11599.
Would transfer to the 4 numbers on ds4 custom deadzone like what values the numbers i put here would be on ds4

**Comment by mika-n** [comment]
closed as "non DS4Windows app issue".
