### ISSUE TITLE
Black DS4 icon?

### ISSUE THREAD

**Issue by BoukObelisk** [Ryochan7/DS4Windows#1336]
hi Ryochan7, thank you for your incredible work! It's really, really appreciated. 

I was wondering if  you could allow us to use a Black DS4 icon for the program? I remember the old versions having a black icon until it was changed to a more colorful one. Would you mind giving us an option to switch to a black icon just like there currently is the option for a white one? Thanks a lot!

**Comment by Ryochan7** [comment]
The change of icon color was done mainly due to Windows 10. The default taskbar color is black so the tray icon would blend in. Right now, the icon choice is represented as a boolean so only two choices are allowed. Some migration would be needed to convert the current value to allow more choices.

**Comment by BoukObelisk** [comment]
Thanks - do you think you can simply replace the White option with the black one? I don't know, I just like it more even though the black icon clashes with the W10 taskbar. I understand if it's too much hassle. Thanks again.

**Comment by Ryochan7** [comment]
That image is compiled as a resource so changing the image would require compiling the application. The big hold over before was coming up with some sort of config migration issue. A migration system has been made for profiles but I might not even bother with it for this case. I'll just check for a newer tag and look for the current WhiteIcon tag as a fallback. I can get that ready for the next release.

**Comment by Ryochan7** [comment]
Version 2.1.10 is now out and a Black icon is an option.

https://github.com/Ryochan7/DS4Windows/releases/tag/v2.1.10
