### ISSUE TITLE
ds4 not recognized after being plugged in

### ISSUE THREAD

**Issue by budafuko** [Ryochan7/DS4Windows#1338]
hello, when i had my ds4 set up as an emulated xbox remote i had no issues but i was having a problem with the x key cause its in a different place on both nintendo and playstation and the b button cause of nintendo as well and kept pressing the wrong keys so i changed it to DS4 instead of Xbox remote as i am playing the witcher 3 and it has the option for the ds4 input prompt. and the controller will connect fine via bluetooth and if it disconnects i can reconnect it but after i have it plugged in to charge and disconnect it i have to disconnect the pad from my computers bluetooth and reconnect it in order for it to be recognized again by ds4windows or my pc. i cant see how the mac address would be getting changed in between and this is the only reason behind the problem i could think of. if anyone could help me solve my problem that would be great

**Comment by mika-n** [comment]
Log files?

And if you have connected the game over BT and want to charge it then try doing it over wall plug and not via PC. Some PCs and gamepads really don't want to behave nicely when the pad connected over BT and then USB cable is "hot plugged".

Or use a usb cable whch doesn't carry over USB data, but can charge the DS4 gamepad. I have several mobile phone cables here which can charge the DS4 but don't carry over data signals.
