### ISSUE TITLE
[Feature] Add Action For Start/Stop

### ISSUE THREAD

**Issue by WolfieeifloW** [Ryochan7/DS4Windows#1339]
It would be really great to be able to "Start" and "Stop" DS4Windows using a button on keyboard.

I am currently using the controller only for a certain part in a level that I need to keep running over and over. This means every ~45 seconds I need to reach over and push the USB in then a few seconds later reach over and unplug it again.

If, instead, I could add an action (for example F12, or F11 & F12 if they need to be separate actions) to "Start"/"Stop" DS4Windows then I could just leave my controller plugged in and use the keyboard buttons to start/stop DS4Windows.

Just to be clear I'm talking about this button, in the bottom-right corner of DS4Windows:
![image](https://user-images.githubusercontent.com/40577712/84446129-dddf2900-ac12-11ea-878e-c3e17eb2f112.png)

**Comment by mika-n** [comment]
You can do it over command line interface. Your custom app or script or hot key can run a cmdline to start/stop DS4Windows app or load a certain profile.

https://github.com/Ryochan7/DS4Windows/wiki/Command-line-options

**Comment by WolfieeifloW** [comment]
This seems like something that should be built into the program though, no?
Having to create a separate file just to do this function seems overly complicated.

**Comment by mika-n** [comment]
DS4Windows app was never intended to be a general purpose keyboard hotkey manager app. In fact the app supports gamepad -> kbd re-mapping, but doesn't actually actively monitor "physical" keyboard events so other way around is not possible. Everything is possible, but even when it may sound trivial to listen kbd events then it is not actually that easy to do as a background application Usually normal kbd events go to a foreground app, not to a background app. It requires few tricks to listen kbd events as a background app. HotKey listener apps do it, but DS4Windows is not meant to be kbd hotkey app.

**Comment by Ryochan7** [comment]
This would only make sense if DS4Windows would hook into global keyboard events so it can react to key presses even when the program is not in focus. I really don't want to add the extra overhead to allow such a feature to be possible.
