### ISSUE TITLE
DS4Windows doesn't inherit the system custom themes.

### ISSUE THREAD

**Issue by Uka-Uka** [Ryochan7/DS4Windows#1340]
Hi, I just want to report this minor aesthetic issue, simply when you replace the os default theme with a custom one, the app doesn't inherit the styling elements of that theme.

![Capture](https://user-images.githubusercontent.com/63985430/84520324-adab8f00-acd3-11ea-883d-6ad2c76aac37.PNG)

**Comment by mika-n** [comment]
there has been experiments with dark theme
