### ISSUE TITLE
DS4windows connects and disconnects continuously mainly with bluetooth

### ISSUE THREAD

**Issue by tjsolid** [Ryochan7/DS4Windows#1341]
My DS4 pad does not work with bluetooth it connects and then disconnects continuously but it works well with cable(Ver 2.1.0 and below). but since version 2.1.1 and above
[ds4windows_log_20200612.16.txt](https://github.com/Ryochan7/DS4Windows/files/4771784/ds4windows_log_20200612.16.txt)
[ds4windows_log_20200612.13.txt](https://github.com/Ryochan7/DS4Windows/files/4771815/ds4windows_log_20200612.13.txt)
, it disconnects continuously with both bluetooth and cable. i have tried all possible means to make it work with usb cable.
my pad model is CUH-ZCT2E

**Comment by Howarddj** [comment]
Also having this issue, have just discovered my controller with issues is a fake.

Version 2.1.0 works perfectly over usb, will pair once and work over bluetooth, but does not send light bar colour change over bluetooth. Will not reconnect after switching off over bluetooth.

Everything above version 2.1.0 puts the controller in a disconnect/ reconnect loop over usb, behaves the same as previously over bluetooth. 

I have tested a genuine ds4 v2 controller on all programs and it works perfectly, so ds4windows and hidguardian are working as they should.

**Comment by tjsolid** [comment]
Thanks for the response, will try and get another pad and test it. but this pad works perfectly with a PS4 system so was convinced it was ds4windows. Anyway thanks again
