### ISSUE TITLE
2.1.2 crashes immediately on launch

### ISSUE THREAD

**Issue by transam617** [Ryochan7/DS4Windows#1342]
[ds4windows_log_20200612.7.txt](https://github.com/Ryochan7/DS4Windows/files/4772821/ds4windows_log_20200612.7.txt)

Upgraded to 2.1.2 when it launched, then today began crashing.  Reinstalled with same result, revert to 2.1.1 works.

**Comment by BloodyMummer** [comment]
Same issue.  Started after the windows update

**Comment by dondrakon** [comment]
Could you provide crash messages? You can find it in Windows Event Viewer.

**Comment by Ryochan7** [comment]
Hopefully this issue has already been fixed. Not sure how but people have run across incomplete OutputSlots.xml files but the reader has been changed to take that scenario into account.
