### ISSUE TITLE
Lightbar has constant red hue

### ISSUE THREAD

**Issue by kingcailan** [Ryochan7/DS4Windows#1347]
I'm on v2.1.2, and when attempting to set my lightbar to any color, it has a constant red hue, I'm estimating around ~180 red after playing with settings. For exaple, trying to set the color to pure blue comes out as a light lavender. Here's an album of a few examples: https://imgur.com/a/bwmhUDj

**Comment by mika-n** [comment]
Have you enabled the "Battery level %" lightbar option? Try disabling it. By default DS4Windows app "blends in" a ligthbar "warning color" when battery is running low if this option is enabled.
