### ISSUE TITLE
[Notice] Likely HidGuardian Problems After Windows 10 2004 Update. Reinstall

### ISSUE THREAD

**Issue by Ryochan7** [Ryochan7/DS4Windows#1348]
If you were using HidGuardian prior to updating to the latest Windows 10 update, you will likely have to re-install HidGuardian in order to re-enable controller blocking. One common problem with the HidGuardian driver is that Windows 10 updates can remove the UpperFilters registry listing that Windows uses to establish filter drivers. Despite the HidGuardian driver being installed and the virtual device being listed in the Device Manager, the UpperFilters portion is what Windows depends on to use HidGuardian with HID devices.

Fortunately for me, I am using a custom version of HidGuardian that takes the UpperFilters registry value into account in the main INF file. That way Windows knows about it and will write the entry back in when Windows is done installing updates.

**Comment by Ryochan7** [comment]
If it is possible, I think I will make a test installer for my custom version of HidGuardian. The main stipulation is that Windows will have to be run in Test Mode with Driver Signature verification disabled. An installer will have to check for that before allowing an install to commence.

**Comment by Ryochan7** [comment]
It looks like this should be possible although inconvenient. I have a working version of the HidGuardian test installer that can install a custom built version of HidGuardian and detect whether Windows is running in Test Mode. It is confirmed to work in Windows 10 and Windows 7.

I cannot recall any titles but I believe that some online games would not be playable if a computer is running in Test Mode. I don't really play online games so it does not bother me much. PSO2 does not check if Windows is running in Test Mode. I just need to spend some time to actually play it and build up a character.

If I would consider making a public release, I need to re-implement skipping virtual devices in HidGuardian. That patch was lost a long time ago but it was only a few extra lines of code IIRC.

**Comment by Ryochan7** [comment]
Figured it out again and made a new commit to the gottagofast branch. I have tested it and the updated driver does ignore virtual devices created by ViGEmBus.

https://github.com/Ryochan7/HidGuardian/commit/cb0d63ebc574ce98a73dbabe8639d2c93b0b899d

**Comment by Ryochan7** [comment]
Another likely mistake but here we go. Here an updated HidGuardian test installer that includes some of my own changes to the driver. It seems like it can install on Windows installations beyond my current Windows 10 install. As mentioned before, you will have to run Windows in Test Mode with Test Signing turned on. The easiest way to enable that mode is to run a Command Prompt as Admin, enter the following command and reboot.

```
bcdedit -set TESTSIGNING ON
```

HidGuardianInstaller_20200615.7z:
https://drive.google.com/file/d/1XSIdgh6P-WCLs3JR0yVWYnWr_FNT5jfZ/view?usp=sharing

![hidguardiantestinstall_20200615](https://user-images.githubusercontent.com/581968/84736196-ec0eab80-af6a-11ea-937e-d7a2e6e2b30d.png)

**Comment by mika-n** [comment]
The same thing. WinOS is notorious on how it may break the filter driver linking after major WinOS updates (affects HidGuardian and other drivers using kernel filter layer). Easiest solution is to re-install HidGuardian to re-setup the filter driver linking. I'm sure there would be some other registry trick to fix it, but re-installation is easy as it can be so it is easy route to take when hidg no longer work.

**Comment by Ryochan7** [comment]
I grumbled about it on the Twitter cesspool a few days ago but MS threw a major curve ball with a recent Microsoft Edge browser update. For some reason, the Edge browser update nuked my HidGuardian Affected Devices list in the registry so I was forced to start from scratch. :wheelchair: 

I don't know if there is a point keeping this issue open anymore so I am going to close it for now.
