### ISSUE TITLE
32 Bit Version

### ISSUE THREAD

**Issue by wild9** [Ryochan7/DS4Windows#135]
Is there any way of getting a 32 bit version of the current builds? Unfortunately my Linx tablet is 32 bit only.

**Comment by Ryochan7** [comment]
I could compile a 32 bit version. The main reason for explicit architecture builds is due to one library change in more recent updates to Windows 10 that broke exclusive mode. Running a 32 bit version on a 32 bit installation of Windows would work fine.

**Comment by Ryochan7** [comment]
Here is a 32 bit compiled version that includes changes since version 1.4.97.

https://drive.google.com/open?id=0B6yGHDx0CFzDZ21lLTJPZVpJVTA

**Comment by wild9** [comment]
Thanks, I really appreciate the help and your effort in continuing the development!

**Comment by Ryochan7** [comment]
Thank you for confirming that the 32 bit version works on your system. I had tested it in its own directory but it is good to know that it does work on other systems. Unless there is any major hurdle that happens in the future, new releases of DS4Windows will have a 32 bit build as well as a 64 bit build.
