### ISSUE TITLE
360 Steering Wheel mode and Calibration only works when editing Default profile

### ISSUE THREAD

**Issue by Ryochan7** [Ryochan7/DS4Windows#1355]
I was wanting to test a minor fuzz implementation for 360 Steering Wheel mode for the Gyro and I came across this problem. Not sure why it works for the Default profile and not others. I tested back to version 2.0.13 and the problem persists. It has been a long time since I have been able to use 360 Steering Wheel mode so I have not tested it in some time; turning the controller still feels a bit odd now but it is doable.

I used custom profiles for Euro Truck Simulator and American Truck Simulator in the past. This bug destroys my use of the feature. This should be considered a high priority issue.

**Comment by Ryochan7** [comment]
Found the reason why this problem occurs. The remapping routine was not getting invoked for the newer profile as no custom bindings were added and the Disconnect BT special action was not checked even though it should have been. Once either variable was changed then the calibration routine would activate when requested.

Not sure why Disconnect BT is not getting checked by default so that should be fixed first. That would not solve the problem completely though.

**Comment by mika-n** [comment]
Hmm.... have to take a look at this also because this is a major issue and might explain why some people reported problems with 360 steering wheel emulation mode even when I didnt find any problems in my tests.
