### ISSUE TITLE
DS4W 2.1.3 Permanent Mode Controllers Get Wrong Profile

### ISSUE THREAD

**Issue by shinra358** [Ryochan7/DS4Windows#1356]
If you turn both controllers on, then turn them back off. Then turn them back on, p1 controller will control p2 in game. And p2 will control p1. How do I know? P1 profile is configured to use blue color and P2 profile is configured to use red color.

Issue born from this thread:
https://github.com/Ryochan7/DS4Windows/issues/1312

Seems to work as intended for emulators but not for real pc games. Real PC games, the above happens. Emulators, this doesn't happen at all and everything is fine.

EDIT: Did more testing and it seems like it is isolated to one game. That game is fighting ex layer on steam.

Also, when playing vanilla Street fighter iv, I turned both controllers on. And testing by turning  one controller off and on slowly. Eventually the controller I kept toggling's light turned white and didn't connect to a profile. I had to hold the ps button down for 10 secs to turn controller off. But when I turned it back on, it connected to the profile it was supposed to. Then I tried with no game. out of 6 times it didn't happen. But a few times, the light turned off and stalled before turning white and then to the desired color.

**Comment by mika-n** [comment]
the latest release has fixes in how the profile is chosen. The issue should be gone now
