### ISSUE TITLE
DS4 2.1.3 [Stop]/[Start] Breaks Virtual Pads

### ISSUE THREAD

**Issue by shinra358** [Ryochan7/DS4Windows#1358]
When controllers are on and you are using [permanent] virtual controllers, if you press [Stop] and then press [Start], Virtual Gamepads would be broken and unusable. Rendering the controller's light to white. Then only way to then fix this issue would be to force close the ds4windows process.

Desired: Pressing [Stop] would first turn controllers off [equivalent to doing so via hotkey] then deinitialize the virtual pad [Equivalent to how virtual pads work correctly on permanent if whole ds4windows is turned on/off].

**Comment by mika-n** [comment]
there has been some tweaks in permantent device feature and hopefully those tweaks fix the issue
