### ISSUE TITLE
Reconnected but no input in games until a reboot.

### ISSUE THREAD

**Issue by jtran2795** [Ryochan7/DS4Windows#1359]
This issue has been occurring to me a lot recently. Usually when leaving a game running hand having my controller disconnect through a set timeout in DS4Windows, when I reconnect my controller DS4Windows recognizes it, Windows recognizes it (through the Control Panel controller setup), but all of my games fail to receive any input. Only rebooting my entire PC will let me use my controller again. Nothing seems to be logged on the application log nor any System Events. Currently using the most recent version of DS4Windows, Windows 10 Pro ver 2004 (has been happening prior to this version), using HID Guardian.

Some things I've attempted but failed to resolve the issue:
- Ending Steam/Nvidia Overlay Processes
- Disabling and Re-enabling Bluetooth and Gamepad Device in Device Manager
- Updating and Reinstalling ViGEmBus Drivers

**Comment by mika-n** [comment]
Maybe you are suffering from the "ghost xinput slot number / changing xinput slot #" issue? It is a problem in WinOS and VigemBus driver level.
https://github.com/Ryochan7/DS4Windows/issues/1163

The latest version has a new "persistent / dynamic" option which is meant to help to tackle that issue. Persistent option keeps the virtual output controller "connected" even when the physical DS4 gamepad is disconnected. This way games won't see the disconnect event and this way causing the WinOS level xinput slot# rotation issue.  The next time you re-connect the physical controller it re-uses the persistent virtual output controller and starts to feed key events again.

**Comment by jtran2795** [comment]
That could make sense, I remember limiting the slot to only use 1. I'll try using that persistent feature and report back in a few days.

**Comment by jtran2795** [comment]
Confirmed to be the solution. No hitches in the past few days, thank you!

**Comment by Erquint** [comment]
Weird how no one mentions BSODs aside from me and Ryochan acknowledging them being a symptom on restarts. Gonna try the persistent version myself now. Should help.
