### ISSUE TITLE
“Apply” button thanks!

### ISSUE THREAD

**Issue by nr1995** [Ryochan7/DS4Windows#1361]
I didn't know this was a problem with DS4Windows until it got fixed in v2.1.3
**_Dark Souls Remastered_** wouldn't recognise the controller!
No matter what I did.  Any combination of Steam and DS4Windows.  Nothing.  Zero.
Then v2.1.3 comes along with an “Apply” button,
and I quickly realise all it takes is one click of that and **_Dark Souls_** is working again!
Maybe this information is useful in relation to how the “Save” button works or something, I don't know.
But either way, thanks!

**Comment by mika-n** [comment]
Do you mean that the virtual output gamepad doesn't work in DarkSouls until you press "Apply" button in profile editor (even when you did't change any settings)?

**Comment by nr1995** [comment]
In previous versions of DS4Windows I would just press “Save” after setup
and that would be enough for every game to recognise the controller and work properly.
But for **_Dark Souls Remastered_** everything would look to be in order in DS4W, as usual,
but in the game itself there would be absolutely zero recognition of the gamepad.
Hitting the “Apply” button fixed everything and makes it work as expected,
and I'm not sure but it doesn't appear to matter when it's pressed.
Although I think restarting the game will require another press of the “Apply” button,
I'll have to do some more playing around with it.
It's a little difficult to pin down now that it's working properly.
