### ISSUE TITLE
Is it possible to create a dual stage trigger function?

### ISSUE THREAD

**Issue by austinsky9110** [Ryochan7/DS4Windows#1363]
Similar to the one the Steam Controller Configuration provides. In the image below, I have an example of what Id liked to be able to do but in DS4Windows. Simply put, the triggers analog output stays the same (right trigger) however, when the trigger is completely pressed down it activates the B button. So, how is this feature useful? I'm using it in the game Rocket League, a competitive, fast paced sports game. Like many driving games, the right trigger allows you to drive forward, the B button in RL is used to activate the boost to go faster. In order to get faster reaction time, I combined the drive and boost into one trigger. This way I didn't have to constantly worry about hitting two different buttons. 

![ScreenShot_20200618184316](https://user-images.githubusercontent.com/48164594/85080000-1e502100-b196-11ea-9b02-417883961ac9.png)

**Comment by Ryusennin** [comment]
As of yet, DS4Windows has no such complex remapping features. JoyToKey should do the trick.

**Comment by Ryochan7** [comment]
It might be possible to change the current code base to add dual stage triggers. I doubt I will ever get around to trying to implement it. I never used that feature with my Steam Controller. I almost always just mapped an action to soft pull.

**Comment by Ryochan7** [comment]
It is now possible with version 2.2.3.
