### ISSUE TITLE
Persistent controllers - error when switching controller type

### ISSUE THREAD

**Issue by TVsIan** [Ryochan7/DS4Windows#1365]
[ControllerTypeError.txt](https://github.com/Ryochan7/DS4Windows/files/4842702/ControllerTypeError.txt)

I've had to roll back to an older version due to this particular error.

If you switch from an X360 to a DS4 profile, or vice versa, manually or via auto profiles, it will lock out a controller slot, even when set to dynamic. After a few changes, all the controllers are unusable, and I get a "No available output slots" message.

I usually use the X360 profile, but for games that support DS4 button icons, I'll switch the profile. So after playing one or two things like that, it's locked out until DS4Windows is exited and relaunched.

[Edit] I installed it on a second computer to test, and I was able to reproduce the issue. The controller slots stay locked after a profile change to the other controller type and will fill up. I've attached the log.

If it would be possible to set a total of 8 slots, with 4 permanent X360s and 4 DS4s, disable the slots entirely, or release the slot instantly on controller type change, those might fix the issue.

**Comment by Flea-2B** [comment]
Having the same issue, I use swipe right to go back and forth between DS4 and X360 and am getting constant output slot errors

**Comment by mika-n** [comment]
the recent version has some tweaks in persistent controllers feature. hopefully the issue is now gone.
