### ISSUE TITLE
Desintalar DS4Windows en PC (Forma correcta)

### ISSUE THREAD

**Issue by Ykoalcon** [Ryochan7/DS4Windows#1369]
Hola, amigos. Quiero eliminar y desintalar DS4Windows (Ryochan7) en un computador que ya no ocupo para después instalarlo en el nuevo. ¿Cuál es la forma correcta de hacerlo?

Muchas gracias, saludos cordiales
Yerko

**Comment by Masamune3210** [comment]
Lo siento si esto no tiene sentido, no hablo español bien, así que estoy usando un traductor. En el futuro, si es posible, use inglés para problemas

Hasta donde sé, la mejor manera de eliminar DS4Windows es desinstalar los controladores que vienen con él y luego eliminar la carpeta en la que se encuentra el ejecutable. No creo que haya una ruta de instalación específica, por lo que debería estar donde la colocó.
