### ISSUE TITLE
Shift to switch Left and Right Analog Sticks?

### ISSUE THREAD

**Issue by Thypari** [Ryochan7/DS4Windows#1370]
So I was trying to make L1 a shift button that would on hold make the left analog stick be the right one.

Unfortunately you can only change single buttons but not the whole analog stick. 
Can this be implemented somehow?

**Comment by mika-n** [comment]
It should work. You can map LS-stick to behave like RS-stick when L1 shift modifier is pressed. I actually just tested the scenario and it worked great. Just remember that you can (and in this case you should) map all LS X/Y axis movements. DS4Windows supports separate mapping rules not only per X and Y axis, but also in - and + directions per single axis. So, if you want then you could re-map L1 shift modifier to re-map only LS x axis to RS x axis and to leave the Y axis as it is.

![DS4Win_LSShiftModifier](https://user-images.githubusercontent.com/35538525/85374291-3250a580-b53d-11ea-933e-353edf571413.png)

**Comment by Thypari** [comment]
thanks I will try it
