### ISSUE TITLE
Doesn't work with Sekiro: Shadows Die Twice

### ISSUE THREAD

**Issue by NuclleaR** [Ryochan7/DS4Windows#1372]
I donno what the problem but in this game controller doesn't work. I tested in other games and seems like everything ok but something strange with this game

**Comment by Ryusennin** [comment]
Sekiro has already been discussed.

#622

**Comment by Ryochan7** [comment]
The short version is that you have to use HidGuardian to hide to original DS4 device from the game.

https://github.com/Ryochan7/DS4Windows/wiki/DS4Windows-and-HIDGuardian-Install-and-Setup-Guide#hidguardian-test-installer
