### ISSUE TITLE
The DS4 can be detected, but the buttons do not respond

### ISSUE THREAD

**Issue by popyoung** [Ryochan7/DS4Windows#1376]
Here is the log.

2020/6/26 0:25:27: DS4Windows version 2.1.3
2020/6/26 0:25:27: OS Version: Microsoft Windows NT 6.2.9200.0
2020/6/26 0:25:27: OS Product Name: Windows 10 Pro
2020/6/26 0:25:27: OS Release ID: 1909
2020/6/26 0:25:27: System Architecture: x64
2020/6/26 0:25:27: Running as User
2020/6/26 0:25:28: Starting...
2020/6/26 0:25:28: Connection to ViGEmBus 1.16.112.0 established
2020/6/26 0:25:28: Searching for controllers...
2020/6/26 0:25:28: Using Exclusive Mode
2020/6/26 0:25:28: DEBUG: EnumerateDS4. HID#1 Path=\\?\hid#vid_09da&pid_0260&mi_00#9&120cfe0a&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd  Description=HID Keyboard Device  VID=0x09DA  PID=0x0260  Usage=0x6  Version=0x250
2020/6/26 0:25:28: DEBUG: EnumerateDS4. HID#2 Path=\\?\hid#vid_1532&pid_001c#7&df26292&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant mouse  VID=0x1532  PID=0x001C  Usage=0x2  Version=0x100
2020/6/26 0:25:28: DEBUG: EnumerateDS4. HID#3 Path=\\?\hid#vid_09da&pid_0260&mi_01&col01#9&35e43bcc&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=���� HID ��׼��ϵͳ������  VID=0x09DA  PID=0x0260  Usage=0x80  Version=0x250
2020/6/26 0:25:28: DEBUG: EnumerateDS4. HID#4 Path=\\?\hid#vid_09da&pid_0260&mi_01&col02#9&35e43bcc&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=���� HID ��׼���û������豸  VID=0x09DA  PID=0x0260  Usage=0x1  Version=0x250
2020/6/26 0:25:28: DEBUG: findControllers. Found 0 possible devices
2020/6/26 0:25:45: DEBUG: EnumerateDS4. HID#1 Path=\\?\hid#vid_09da&pid_0260&mi_00#9&120cfe0a&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd  Description=HID Keyboard Device  VID=0x09DA  PID=0x0260  Usage=0x6  Version=0x250
2020/6/26 0:25:45: DEBUG: EnumerateDS4. HID#2 Path=\\?\hid#vid_054c&pid_05c4#8&209b476b&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant game controller  VID=0x054C  PID=0x05C4  Usage=0x5  Version=0x100
2020/6/26 0:25:45: DEBUG: EnumerateDS4. HID#2 detected as DS4 compatible gamepad device
2020/6/26 0:25:45: DEBUG: EnumerateDS4. HID#3 Path=\\?\hid#vid_1532&pid_001c#7&df26292&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant mouse  VID=0x1532  PID=0x001C  Usage=0x2  Version=0x100
2020/6/26 0:25:45: DEBUG: EnumerateDS4. HID#4 Path=\\?\hid#vid_09da&pid_0260&mi_01&col01#9&35e43bcc&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=���� HID ��׼��ϵͳ������  VID=0x09DA  PID=0x0260  Usage=0x80  Version=0x250
2020/6/26 0:25:45: DEBUG: EnumerateDS4. HID#5 Path=\\?\hid#vid_09da&pid_0260&mi_01&col02#9&35e43bcc&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=���� HID ��׼���û������豸  VID=0x09DA  PID=0x0260  Usage=0x1  Version=0x250
2020/6/26 0:25:45: DEBUG: IsRealDS4. IsRealDS4=True  hDevicePath=\\?\hid#vid_054c&pid_05c4#8&209b476b&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  deviceInstanceID=hid\vid_054c&pid_05c4\8&209b476b&0&0000  Device_UINumber=
2020/6/26 0:25:45: DEBUG: findControllers. Found 1 possible device
2020/6/26 0:25:45: DEBUG: findControllers. Idx=0 Potential DS4 gamepad. Description=HID-compliant game controller  Path=\\?\hid#vid_054c&pid_05c4#8&209b476b&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
2020/6/26 0:25:45: DEBUG: findControllers. idx=0 Opening device VID=0x054C  PID=0x05C4  isExclusiveMode=True
2020/6/26 0:25:45: DEBUG: findControllers. idx=0 IsOpen=True
2020/6/26 0:25:45: DEBUG: readSerial. Trying to read serial# from VendorID=0x054C, ProductID=0x05C4, Version=256, DevicePath=\\?\hid#vid_054c&pid_05c4#8&209b476b&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030} InputReportLen=64
2020/6/26 0:25:45: DEBUG: readSerial. OK. readFeatureData. Serial#=D0:27:88:5B:55:78
2020/6/26 0:25:45: DEBUG: findControllers. idx=0 IsValidSerial=True  Serial=D0:27:88:5B:55:78
2020/6/26 0:25:45: DEBUG: findControllers. idx=0 Using device \\?\hid#vid_054c&pid_05c4#8&209b476b&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  metainfo.name=DS4 v.1  metainfo.featureSet=DefaultDS4
2020/6/26 0:25:45: DEBUG: DS4Device. DS4 v.1 conType=USB  MAC=D0:27:88:5B:55:78
2020/6/26 0:25:45: DEBUG: DS4Device. Raw InputReportLen=64  OutputReportLen=32
2020/6/26 0:25:45: DEBUG: DS4Device. Current debug options: debug_HidDSetNumInputBuffers=2  debug_GyroCalibration=True  debug_GyroCalibrationType=0
2020/6/26 0:25:45: DEBUG: DS4Device. Current debug options: debug_SendRumbleLightbarData=True  debug_SendRumbleLightbarDataType=0  debug_SendRumbleLightbarDataAPI=0
2020/6/26 0:25:45: DEBUG: DS4Device. Current debug options: debug_ReadTouchpadData =True  debug_ReadGyroData=True  debug_ReadBatteryData=True
2020/6/26 0:25:45: DEBUG: DS4Device. Current debug options: debug_ForceConnectionType=0  debug_PrintoutInputDataBuffer=False
2020/6/26 0:25:45: DEBUG: DS4Device. DS4 v.1 conType=USB UsedInputReportBufLen=64 UsedOutputReportBufLen=32 synced=True runCalib=True
2020/6/26 0:25:45: DEBUG: DS4SixAxis. gyroMultiplierYaw=1  gyroMultiplierRoll=1  gyroMultiplierPitch=1
2020/6/26 0:25:45: DEBUG: RefreshCalibration. getCalibrationData. conType=USB  calibDataType=2
2020/6/26 0:25:45: DEBUG: setCalibrationData. calibrationDone=True  FromUsb=True
2020/6/26 0:25:45: DEBUG: setCalibrationData. calibrationData[0] bias=0  sensNumer=17280  sensDenom=17723
2020/6/26 0:25:45: DEBUG: setCalibrationData. calibrationData[1] bias=-1  sensNumer=17280  sensDenom=17615
2020/6/26 0:25:45: DEBUG: setCalibrationData. calibrationData[2] bias=1  sensNumer=17280  sensDenom=17632
2020/6/26 0:25:45: DEBUG: setCalibrationData. calibrationData[3] bias=64  sensNumer=16384  sensDenom=16039
2020/6/26 0:25:45: DEBUG: setCalibrationData. calibrationData[4] bias=176  sensNumer=16384  sensDenom=16076
2020/6/26 0:25:45: DEBUG: setCalibrationData. calibrationData[5] bias=234  sensNumer=16384  sensDenom=16056
2020/6/26 0:25:45: DEBUG: setCalibrationData. gyroSpeed2x=1080 gyroSpeedPlus+gyroSpeedMinus=(540 + 540)  yaw=17615 yawPlus-yawMinus=(8807 - -8808)
2020/6/26 0:25:45: DEBUG: DS4Device. DS4 v.1 conType=USB IsFileStreamOpen=True
2020/6/26 0:25:45: DEBUG: findControllers. idx=0 OK. DS4Win uses the device as input source
2020/6/26 0:25:45: Found Controller: D0:27:88:5B:55:78 (USB) (DS4 v.1)
2020/6/26 0:25:45: Plugging in virtual X360 Controller
2020/6/26 0:25:45: Associate X360 Controller for input DS4 #1
2020/6/26 0:25:45: Controller 1 is using Profile "Default"
2020/6/26 0:25:47: DEBUG: EnumerateDS4. HID#1 Path=\\?\hid#vid_045e&pid_028e&ig_00#3&69dc547&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant game controller  VID=0x045E  PID=0x028E  Usage=0x5  Version=0x0
2020/6/26 0:25:47: DEBUG: EnumerateDS4. HID#2 Path=\\?\hid#vid_09da&pid_0260&mi_00#9&120cfe0a&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd  Description=HID Keyboard Device  VID=0x09DA  PID=0x0260  Usage=0x6  Version=0x250
2020/6/26 0:25:47: DEBUG: EnumerateDS4. HID#3 Path=\\?\hid#vid_054c&pid_05c4#8&209b476b&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant game controller  VID=0x0000  PID=0x0000  Usage=0x0  Version=0x0
2020/6/26 0:25:47: DEBUG: EnumerateDS4. HID#4 Path=\\?\hid#vid_1532&pid_001c#7&df26292&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant mouse  VID=0x1532  PID=0x001C  Usage=0x2  Version=0x100
2020/6/26 0:25:47: DEBUG: EnumerateDS4. HID#5 Path=\\?\hid#vid_09da&pid_0260&mi_01&col01#9&35e43bcc&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=���� HID ��׼��ϵͳ������  VID=0x09DA  PID=0x0260  Usage=0x80  Version=0x250
2020/6/26 0:25:47: DEBUG: EnumerateDS4. HID#6 Path=\\?\hid#vid_09da&pid_0260&mi_01&col02#9&35e43bcc&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=���� HID ��׼���û������豸  VID=0x09DA  PID=0x0260  Usage=0x1  Version=0x250
2020/6/26 0:25:47: DEBUG: findControllers. Found 0 possible devices
2020/6/26 0:25:48: DEBUG: EnumerateDS4. HID#1 Path=\\?\hid#vid_045e&pid_028e&ig_00#3&69dc547&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant game controller  VID=0x045E  PID=0x028E  Usage=0x5  Version=0x0
2020/6/26 0:25:48: DEBUG: EnumerateDS4. HID#2 Path=\\?\hid#vid_09da&pid_0260&mi_00#9&120cfe0a&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd  Description=HID Keyboard Device  VID=0x09DA  PID=0x0260  Usage=0x6  Version=0x250
2020/6/26 0:25:48: DEBUG: EnumerateDS4. HID#3 Path=\\?\hid#vid_054c&pid_05c4#8&209b476b&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant game controller  VID=0x0000  PID=0x0000  Usage=0x0  Version=0x0
2020/6/26 0:25:48: DEBUG: EnumerateDS4. HID#4 Path=\\?\hid#vid_1532&pid_001c#7&df26292&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant mouse  VID=0x1532  PID=0x001C  Usage=0x2  Version=0x100
2020/6/26 0:25:48: DEBUG: EnumerateDS4. HID#5 Path=\\?\hid#vid_09da&pid_0260&mi_01&col01#9&35e43bcc&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=���� HID ��׼��ϵͳ������  VID=0x09DA  PID=0x0260  Usage=0x80  Version=0x250
2020/6/26 0:25:48: DEBUG: EnumerateDS4. HID#6 Path=\\?\hid#vid_09da&pid_0260&mi_01&col02#9&35e43bcc&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=���� HID ��׼���û������豸  VID=0x09DA  PID=0x0260  Usage=0x1  Version=0x250
2020/6/26 0:25:48: DEBUG: findControllers. Found 0 possible devices
2020/6/26 0:25:50: DEBUG: EnumerateDS4. HID#1 Path=\\?\hid#vid_045e&pid_028e&ig_00#3&69dc547&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant game controller  VID=0x045E  PID=0x028E  Usage=0x5  Version=0x0
2020/6/26 0:25:50: DEBUG: EnumerateDS4. HID#2 Path=\\?\hid#vid_09da&pid_0260&mi_00#9&120cfe0a&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd  Description=HID Keyboard Device  VID=0x09DA  PID=0x0260  Usage=0x6  Version=0x250
2020/6/26 0:25:50: DEBUG: EnumerateDS4. HID#3 Path=\\?\hid#vid_054c&pid_05c4#8&209b476b&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant game controller  VID=0x0000  PID=0x0000  Usage=0x0  Version=0x0
2020/6/26 0:25:50: DEBUG: EnumerateDS4. HID#4 Path=\\?\hid#vid_1532&pid_001c#7&df26292&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant mouse  VID=0x1532  PID=0x001C  Usage=0x2  Version=0x100
2020/6/26 0:25:50: DEBUG: EnumerateDS4. HID#5 Path=\\?\hid#vid_09da&pid_0260&mi_01&col01#9&35e43bcc&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=���� HID ��׼��ϵͳ������  VID=0x09DA  PID=0x0260  Usage=0x80  Version=0x250
2020/6/26 0:25:50: DEBUG: EnumerateDS4. HID#6 Path=\\?\hid#vid_09da&pid_0260&mi_01&col02#9&35e43bcc&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=���� HID ��׼���û������豸  VID=0x09DA  PID=0x0260  Usage=0x1  Version=0x250
2020/6/26 0:25:50: DEBUG: findControllers. Found 0 possible devices

**Comment by popyoung** [comment]
more detail: "Stop" button never succeeds. it stops at "Closing connection to ViGEmBus" every time. And if I exit without pressing the stop button, the program will freeze and I have to kill the process

**Comment by mika-n** [comment]
What do you see in JOY.CPL controlPanel applet or in html5gamepad.com web page with and without DS4Windows app? Do you see any gamepad btn/axis/gyro activity in DS4Windows "Controller Readings" tab page? Or if you press "Test rumble" then does it work? And what about lightbar?

The logfile doesn't show any problems.

**Comment by Ryochan7** [comment]
> more detail: "Stop" button never succeeds. it stops at "Closing connection to ViGEmBus" every time. And if I exit without pressing the stop button, the program will freeze and I have to kill the process

That problem has been fixed in the code already. I have not put out a new release with the fix included though. Hopefully I will get around to that soon.

https://github.com/Ryochan7/DS4Windows/issues/1358

**Comment by popyoung** [comment]
I can see an X360 controller in JOY.CPL controlPanel. But “No gamepad detected” is displayed on the webpage (html5gamepad.com).
There is no response to the operation of the Controller in DS4Windows "Controller Readings" tab page. Same in the test panel of JOY.CPL.
And if I connect the DS4 whitout running DS4Windows first, I can't enter exclusive mode. When I check device in ProcessExplorer, I found it is occupied by dwm.exe. I don't know if it is abnormal.

**Comment by popyoung** [comment]
> 
> 
> > more detail: "Stop" button never succeeds. it stops at "Closing connection to ViGEmBus" every time. And if I exit without pressing the stop button, the program will freeze and I have to kill the process
> 
> That problem has been fixed in the code already. I have not put out a new release with the fix included though. Hopefully I will get around to that soon.
> 
> #1358

Thx. Good to know

**Comment by popyoung** [comment]
I tried various methods, and even compiled a version myself to debug. Finally, I suddenly found a problem, my DS4 is connected to a usbhub on the keyboard. So I tried to plug it into the hub on the front panel of the chassis, and everything was good...
