### ISSUE TITLE
Roundness Limitation

### ISSUE THREAD

**Issue by AIIisia** [Ryochan7/DS4Windows#1378]
Hello.

The current version of DS4Windows limits the roundness values of the squaring function to a maximum of 5. Using a linear squaring function leads to inherent inaccuracy in games sensitive to input, like Rocket League, since the acceleration of input isn't consistent across the entire stick.

If the roundness value were hypothetically infinite, then at maximum analog input, the output would instantaneously be maximized. This allows for the benefits of squared input in games that don't clamp the input values (like Rocket League) whilst not creating the issues with acceleration of input.

I tested a custom version of DS4Windows, edited by a friend, that removed the limit on the roundness values and allowed for this sort of use case, which is very useful and effective. As DS4Windows has been further updated, the libraries used in that version have also been updated and the custom version no longer works. 

**Would this unique use case be a good justification for potentially removing the limit on the roundness value, or potentially adding a separate function that does this?**

To reclarify, in case the function was misunderstood:
At maximum input from the controller, the output is maximized, allowing for 100% of the stick to be used with linearly and consistently accelerated input, but also allowing values of [(1,1),(1,-1),(-1,1),(-1,-1)] to be used.

The Bezier curves cannot be configured to do this, and I haven't found any software that can do this besides assigning a keyboard macro triggered by maximized analog input, which causes directional problems.

Thank you for all your hard work and understanding.

**Comment by mika-n** [comment]
Didn't quite follow the logic you were hoping to see vs what DS4Windows already have (or doesn't have).
- If you want to max out the X/Y axis output in a virtual gamepad without ruining the precision of initial movements of LS/RS stick then bezier curve output allows you to set "almost linear" output in the beginning of axis input but then rapidly max out the output at the end of the curve.

**Comment by Ryochan7** [comment]
I would not be against bumping up the maximum allowed setting for Roundness. Although, I don't really get what functionality you are really aiming for that cannot already be done in DS4Windows. The post is not very clear.

Based on the original page documenting the technique and my own experience, the setting of 5.0 seemed like a good balance between keeping the roundness of most of the input range while still allowing maximum output to the diagonals. The only game I have actively used the Square Stick function has been Star Wars: Shadows of the Empire (PC port from GOG). It definitely improved the experience for that game.

**Comment by AIIisia** [comment]
@Ryochan7 Squaring algorithms lead to inherent inaccuracies, which are especially noticeable for games requiring very fine control, like Rocket League. 

The inherent inaccuracy:

When moving the analog stick from the centre (https://i.imgur.com/ynHSDyD.png) to the left or right (https://i.imgur.com/1yoii6n.png) then the values on the Y-axis remain the same whilst the X-axis value changes.

When using a squaring algorithm, this doesn't work the same (https://i.imgur.com/bGgIbes.png), and instead there's values added to the Y-axis to accommodate the difference in dimensions of a square and circle. In game, this change in value translates to a change in movement on axes that are unwanted.

Using higher roundness values makes this unwanted value appear more suddenly, which generally makes it feel more controlled around the centre of input. Lots of people attribute the difficulty of using unrounded squared input to how "sensitive" it feels, whereas in reality it's because the input is less consistent across the stick.

The game this causes me a major issue in is Rocket League. Rocket League doesn't clamp raw input, and there are distinct benefits to playing with squared input. Unfortunately, using a squaring algorithm, even at 5 roundness, leads to so much inaccuracy due to the problem mentioned above. Having a hypothetically infinite roundness value allows for consistent input almost across the entire stick, but then maximum squared values can be achieved when wanted.

Squared vs non-squared input has been a point of contention in the competitive scene there, because many players understand there's an objective advantage to having it, but it leads to so much inaccuracy that it's not used competitively. Competitively, players typically use an in-game sensitivity of around 1.30 to 1.50, but this applies to an output in the game, and not the input. The input and output in the game are used separately in different calculations, which is why squared input still gives an advantage. If squared input simply wasn't used because it's too sensitive, then players wouldn't be able to use sensitivities higher than 1.30 in-game, comfortably. After a lot of testing and trying to figure this out for myself, I was able to find that the inaccuracy that comes with the input is as I described above, instead. 

A workaround I've found for this, that achieves squared input whilst maintaining consistency, is increasing the sensitivity of the stick to roughly 1.30 to 1.42, or decreasing the max zone to somewhere around 0.70-0.78. Unfortunately, when doing this, there's objectively a lot less of the stick that's able to be used, since the input maxes out on the cardinals far before the analog stick actually reaches its physical limit. Unfortunately, no software I've found is able to offer the functionality I'm looking for besides assigning keyboard macros, which introduce problems by themselves. 

Despite what @mika-n said, it's not possible to do the Bezier curve function in DS4Windows, either.
A) This is about the best curve that can be achieved: https://i.imgur.com/e7rcw2o.png
B) Manipulating the numbers and forcing the values above the limits the GUI imposes doesn't solve this either. The curve seems to max out at some undefined point.
C) Even if there were a Bezier curve that could be created to achieve what I'm looking for, the Bezier curve, from my testing, behaves weirdly when extreme values are applied to it, and it often doesn't achieve a full range of input, still.

**Comment by Ryochan7** [comment]
Checking the output now. With such high values for Roundness, the output values snap to the diagonal pretty much as soon as the input has exceeded the inner circle. That is especially true when using the new max value of 1000.0 as opposed to even 100.0 which was a potential max. I guess that choosing 1000.0 was the better choice.

**Comment by Ryochan7** [comment]
In a practical test for myself, I tried some different values in Shadows of the Empire. I find that using a Roundness setting of 20.0 feels pretty good. It does feel like an improvement over using a value of 5.0.

**Comment by AIIisia** [comment]
Thank you for providing feedback. It means a lot, @Ryochan7. Is there anywhere I can donate to you?
