### ISSUE TITLE
Bluetooth wont work

### ISSUE THREAD

**Issue by prtmrj** [Ryochan7/DS4Windows#1379]
I thought it would be supported, the search suggestion had already been made and did not solve my problem. anyway i will wait for updates.

**Comment by mika-n** [comment]
Read the pinned "Read this before posting a new ticket" post. You should provide more info (versions, logfiles, gamepad type, etc).
Also, using the search feature with "bluetooth connection problem" keywords may lead to topics with the same issue.
https://github.com/Ryochan7/DS4Windows/search?q=bluetooth+connection&unscoped_q=bluetooth+connection+problem
