### ISSUE TITLE
Witcher 3 Light bar passthrough not working as expected

### ISSUE THREAD

**Issue by artzox** [Ryochan7/DS4Windows#1380]
Hi,

It's great that this new option was added.

I tried enabling it via a custom profile and also tested setting the controller type to DS4 in the profile.

Regardless if set to xbox or ds4 controller the lightbar glows white if passthrough is enabled.

The only way I have managed to get the actual in-game glow to work properly was stopping DS4Windows, connecting the controller wired and starting the game. It starts with blue color then and changes accordingly  throughout the play session.

Any suggestion on how to get this working properly if possible?

Thanks,
Arztox

**Comment by Ryochan7** [comment]
The feature was disabled a while ago; I cannot remember the exact version when it was disabled. People had mentioned running into infinite rumble problems although I could not reproduce the problem on my end.

I have opted to add the functionality back in to the code with commit https://github.com/Ryochan7/DS4Windows/commit/cf9183ac57241d4084114f81c74c5ea1d477bd87. As stated in the commit message, hopefully I won't regret it.

**Comment by artzox** [comment]
Thanks for adding it back Ryochan.
Just tested and for now it works fine with ps4 profile and lightbar passthrough.
Will post again if there are any issues down the line.
I assume that there is no way of lowering the intensity if using passthrough?
Thanks,
Artzox

**Comment by Ryochan7** [comment]
Looks like this feature is going to get disabled again. Something is likely happening in the ViGEmBus driver but I do not have the time to look into it. I cannot find a way to work around various feedback report issues in client code.
