### ISSUE TITLE
Virtual 360 controller created in slots above the first

### ISSUE THREAD

**Issue by rcostanza** [Ryochan7/DS4Windows#1381]
Occasionally, the virtual 360 controller is created on slots 2/3. Some (most?) games can't deal with that, and so inputs won't work. The controller still works fine in some games and the online tester, and through `XInput-Python` I can see it's on a slot above the first.

No other controllers are connected, and I don't see more than one virtual controller at a time on device manager.

I can't seem to reproduce this, but what I do know is that it doesn't happen after a fresh reboot. Also, it never "goes down" a slot; once it starts going above 1 it'll only fix itself after rebooting.

I tried debugging this, but I'm at version 2.0.13 (latest), I couldn't get my controller to be recognized in the debug version at all.

I'm on Win10 2004, had HidGuardian before but uninstalled since the bundled HidNinja does the job.

**Comment by mika-n** [comment]
Take a look at the "xinput and ghost controller" search keywords.
https://github.com/Ryochan7/DS4Windows/issues/1163

Anyway. The latest version of Ryochan7/DS4Windows has a new "dynamics vs persistent" slot settings per gamepad. This is meant to tackle the issue of "ghost xinput device locking xinput slots in WinOS level". The idea of this persistent slot feature is to leave the virtual x360 output controller "alive" even when the phystical source ds4 gamepad is offline. This way games and WinOS still thinks the xbox360 gamepad is connected and won't try to roll xinput slots.

**Comment by Ryusennin** [comment]
"Had HidGuardian before but uninstalled since the bundled HidNinja does the job."

You're mistaken. HidNinja alone does nothing, it's essentially a GUI for HidGuardian.

**Comment by Ryochan7** [comment]
I have had this same problem happen while working on my Switch Pro and JoyCon experiments. Sometimes I have had the virtual Xbox 360 controller get associated with XInput slot 2 despite it being the only XInput device seen by the system. With some games, it does not matter but Deus Ex: Human Revolution will not work correctly if the virtual Xbox 360 controller is not plugged into XInput slot 1.

The test Switch Pro and JoyCon programs are extremely simple so I am pretty sure I am not doing anything wrong on my end. It just seems like ViGEmBus does not close virtual devices cleanly sometimes so slot numbers can get skipped.

**Comment by rcostanza** [comment]
The odd thing is that the slot can still be filled by another controller.

When this issue happens, I can connect another xinput controller (like my SN30Pro+ in xinput mode), it'll go to the first slot and work normally. Disconnecting this controller won't "give the slot back", though.

-- 

About using a persistent output slot, I've had the same issue with it and seems to be related to hibernating;/sleeping the computer. It'll "disconnect" the virtual device before shutting down, and on resume it's sometimes recreated on a higher slot. I know it's fairly specific scenario since sleep/hibernate isn't that much used since SSDs, just figured I could mention.

**Comment by mika-n** [comment]
closed as "some of those slot issues are related to VigEm driver and unfortunately nothing DS4Windows app do about it". The new presistent slot in DS4Windows helps to fight the issue, but there may still be some corner cases which slip through the persistent slot feature.
