### ISSUE TITLE
Battery Level Problem

### ISSUE THREAD

**Issue by abdulwahab1996** [Ryochan7/DS4Windows#1382]
I brought a cheap ps4 controller works fine but when I move right analog stick up, battery level drops by 13% and increase by 12% when moved down and always shows 87% when full charged.

**Comment by mika-n** [comment]
Interesting. Sounds like that DS4 copy wanna-be gamepad sends slightly different HID/USB input reports and the field where the official/fully compatible DS4 gamepads report the "semi-true" battery level the gamepad you have reports some other activity. But DS4Windows app has no way of knowing that the gamepad has a buggy input report, so it simply reports those bogus values as battery level. Maybe. This was just a theory how something like this could happen. If everything else works then maybe you should just ignore the battery reading level with that gamepad.

**Comment by abdulwahab1996** [comment]
The battery last only for four hours where as on my original Ps4 controller it goes around 8. Just need to increase the battery life.

**Comment by mika-n** [comment]
How long the battery lasts when you connect the fake DS4 gamepad to PS4 console? If it works there the same 4 hours then there is not much DS4Windows app can do.

However, one way to limit the traffic to DS4 gamepad and this way to increase battery level is to disable rumble and lightbar support. If you untick "Data output To DS4" option in a profile then DS4windows app won't send periodic rumble and ligthbar commands to DS4 gamepad.

**Comment by abdulwahab1996** [comment]
Thanks for the help
