### ISSUE TITLE
Lightbar related usability suggestions

### ISSUE THREAD

**Issue by reyaz006** [Ryochan7/DS4Windows#1384]
My thoughts about DS4 after using it for more than a year:
- The lightbar is useless, annoying and I want it off to increase the battery life.
- Current lightbar settings are mostly useless. The only one that is actually useful is flashing on low battery.

I thought about ways lightbar could be slightly more useful. Note, I'm a wireless user, and it's all about wireless mode.

1. Immediately after I connect the gamepad with a PS button, I may want to know the battery status to ensure that enough is left and I wouldn't need to pause the session for recharging or connecting to USB. I thought the lightbar would be perfect for this. E.g. right after the DS4 is connected via Bluetooth, flash the lightbar a few times with a color that would indicate a rough percentage of the remaining energy.

2. It might be used as a feedback for certain events that are triggered by DS4Windows. However I came up with the only one trigger function that could benefit me, and it's not implemented yet. It's about Idle Disconnect. Basically, it's a partial workaround for the another issue I've made about [Persistent device](https://github.com/Ryochan7/DS4Windows/issues/874). Here is how I think it may work:
- While playing a game, you get distracted or need to pause for an unknown period of time. You don't want to pause the game.
- You press the PS button twice.
- DS4Windows reads that and disables Idle Disconnect. The lightbar flashes twice to confirm that Idle Disconnect is disabled.
- You go without worrying that DS4 disconnects.
- Maybe at this point it's also okay to flash the lightbar periodically to indicate active mode.
- After you are done with your business and ready to get back to playing, you press the PS button twice.
- Same as before, DS4Windows reads that and enables Idle Disconnect back. The lightbar flashes twice with a different color to confirm this change. If it was flashing, it doesn't anymore.

**Comment by Ryusennin** [comment]
That sounds awfully complicated for a feature that most people will never use nor understand (how many times do you need to double-click that PS button, and what happens if you forget about double-double-clicking, seriously).

Personally, I gave up on the lightbar about telling me how much juice is left, as in my case the percentage has never been reliable (and I only connect the pad via USB). I use the lightbar instead to informe me on the status of specific profiles -- green for XInput, blue for PS4/DInput, cyan for auto-profile.

**Comment by reyaz006** [comment]
It doesn't have to be double press.

>and what happens if you forget about double-double-clicking

Nothing serious would happen. In my scenario, Idle Disconnect would remain disabled, and lightbar would blink indicating that.

**Comment by mika-n** [comment]
the latest version shows the battery level at gamepad connection time (popup message on bottom right corner).
There is also a special action "Check battery life" and you can bind this action to some gamepad key combination. The specAction can show the battery level as a popup message or via ligthbar color.
