### ISSUE TITLE
Possibly implement 1€ Filter for 360 Gyro Steering Wheel Mode

### ISSUE THREAD

**Issue by Ryochan7** [Ryochan7/DS4Windows#1385]
I have been testing using the 1€ Filter with 360 Steering Wheel mode and it can greatly improve wheel stability. Using 1€ gets the performance pretty much inline with how Gyro Steering operates in Steam Input with the Steam Controller. The DS4Windows version would still be more snappy even with the currently tested variables to the filter.

**Comment by mika-n** [comment]
This sounds really interesting and promising. I'm using the "360 steering wheel emulation" with the DIY rig and it makes the "steering wheel" and gyro sensor readings very stable and predicable, but if someone uses the feature in "free hands in the mid air" then I can see how something like this would improve the (or lower the gyro noise) gyro steering.

**Comment by Ryochan7** [comment]
I think I am pretty close to finishing testing and tweaking the default values that will be used. Profile settings have to be made and the GUI will have to be updated to expose the values used by the OneEuroFilter instances. I still need to get around to reading the full white paper documenting the 1€ Filter before I commit code that actively uses it; I have only read a small portion of the white paper.

**Comment by mika-n** [comment]
included in the latest release
