### ISSUE TITLE
[Suggeston] Accepting KB+M Input

### ISSUE THREAD

**Issue by ImportTaste** [Ryochan7/DS4Windows#1388]
My apologies if this has been covered before, I did do a search in the issues but nothing stuck out. I've always been interested in the use of analog stick + mouse controls, particularly with the supported PS Move Navigation Controller. 

_**EDIT**: I didn't think about it until just now, but this also has uses with console-to-PC ports that might not accept mouse input at all and/or have really wonky keyboard input issues._

Most games these days will completely switch your control scheme the moment it detects keystrokes/clicks or controller activity, making it very impractical to use both in tandem without having one emulate the other. While it's easy enough to configure it to output keystrokes for the 8 cardinal/intercardinal directions, I would much rather have the option to retain full analog movement.

Now that HidNinja is fully integrated and capable of limiting what output devices a game can perceive, what I would like to see is a way for DS4Windows to recognize keystrokes/clicks and mouse movement and be able to translate it to button presses and analog stick movements.

**Comment by mika-n** [comment]
This has been discussed before. Everything is possible, but reading KB+Mouse as an INPUT device was never the original intention of this app.And adding that to the existing code and re-map logic would be quite big change (the base code goes back several years and has some limitations).

There are other apps which support KB+M as an input and re-maps those as VJoy or ViGem gamepad events (autohotkey, rewasd etc).

**Comment by ImportTaste** [comment]
> This has been discussed before. Everything is possible, but reading KB+Mouse as an INPUT device was never the original intention of this app.And adding that to the existing code and re-map logic would be quite big change (the base code goes back several years and has some limitations).
> 
> There are other apps which support KB+M as an input and re-maps those as VJoy or ViGem gamepad events (autohotkey, rewasd etc).

As far as I know, none of them can turn mouse movement into full radial analog sick movement.

**Comment by stealth-alex** [comment]
> As far as I know, none of them can turn mouse movement into full radial analog sick movement.

reWASD has such feature

**Comment by Ryochan7** [comment]
This is beyond the scope of DS4Windows. That use case would likely warrant the development of a completely different program. I am not really convinced that such a control scheme is really worth attempting for the most part.

> reWASD has such feature

If I remember correctly, it did not even take into account the full range of the DS4 analog sticks. I will have to give reWASD another try sometime but I was very disappointed with the program when I tried it.

**Comment by Ryochan7** [comment]
Trying out reWASD KB+M mapper right now. Kind of limited and laggy. There doesn't seem to be many options to tweak the responsiveness of the virtual RS. It is an interesting idea but I couldn't see myself using that type of config in its current state. Going with the filter driver route would be the way to go to block the original KB input.

Also, reWASD does actually take the full stick axis range into account. However, the clamping that is done is a bit over aggressive at trying to enforce a perfect circle (around 32767 value) on the output. For the controller mapper, anything less than an absolute direction, even when the max value is still active for the input controller, nerfs the max value for the output coordinate.

I have experienced something similar myself while testing possible changes for my own programs. To allow some wiggle room around the cardinal directions, the clamping value should probably be slightly higher (maybe around 34000 value) instead.

**Comment by ImportTaste** [comment]
Yeah, I tried it out myself and I'm pretty disappointed with it.
