### ISSUE TITLE
[Request] Dinput only mode on Bluetooth

### ISSUE THREAD

**Issue by adrianodennanni** [Ryochan7/DS4Windows#139]
Is there a reason for Dinput not work with bluetooth? Steam is able to recognize the DS4 even on Bluetooth mode.
Older games (such as Guitar Hero III) also detect the DS4 as a generic dinput controller.
I really would like to play supported games in Dinput mode instead of Xinput, without losing all the features DS4Windows offers.

I could help developing this feature too, if feasible.

**Comment by Ryochan7** [comment]
The DS4 is seen by Windows as an HID gamepad. Steam has support for the DInput DS4 device thanks to an SDL mapping. The better comparison is between using DS4Windows and the PS4 controller remapping support built into Steam. When using the extra support for the DS4 in Steam to remap controls and use the gyro and touchpad, the behavior will be similar as the mode of the DS4 changes once an output report is sent. 

As it is, using the DInput version of the Xbox 360 virtual controller is all that can be used for playing older DInput only games. Using something like ViGEm might make it possible to have the system see the DS4 as an emulated DS4 with access to remapping controls and using the various extra features of the controller. The driver does not seem ready though and the bus device is not visible on my system after installing the driver. Either way, that is good enough for my use case.
