### ISSUE TITLE
DS4 not working with Remote Play

### ISSUE THREAD

**Issue by ZortecYT** [Ryochan7/DS4Windows#1392]
I used DS4 mode on DS4Windows but it won't let me use it on Remote Play. pleaseee help!!!
![asdasd](https://user-images.githubusercontent.com/68050253/87008963-131d6d80-c1f7-11ea-9ff0-0c366f032d34.JPG)
![wqeqwe](https://user-images.githubusercontent.com/68050253/87008970-17498b00-c1f7-11ea-8124-c15df63b0810.JPG)

**Comment by Masamune3210** [comment]
remote play requires it's own driver to talk directly to the controller

**Comment by ZortecYT** [comment]
> remote play requires it's own driver to talk directly to the controller

where can i find it??? how come before i was able to do it without it before by just using XInput to ViGEm sample application with DS4 windows

**Comment by mika-n** [comment]
I have used DS4Windows + ds4 v2 gamepad + Bluetooth + Win10 + PSRemotePlay app + PS4 console and it works just fine. Just tested it with the latest DS4Windows V2.1.4 and works great.

I use DS4Windows with HidGuardian tool to hide the original physical gamepad, so only the virtual ds4 gamepad (ds4windows profile is set to use dualshock4 output controller type) is visible for PS4RemotePlay app on PC.

Have you tested both usb and BT connections in PC? Have you enabled "Hide DS4 Controller" option or are you using the alternative solution HidGuardian driver to hide the original physical controller?

By the way, if you don't need to re-map ds4 gamepad keys then you don't need DS4Windows app if you use USB connection. However, I use the "360 steering wheel emulation" mode of DS4Windows to map gyro as LS x-axis stick in racing games. Works great.

**Comment by Ryochan7** [comment]
This was discussed in Discord. He had HidGuardian blocking the virtual DS4 controller from Remote Play.
