### ISSUE TITLE
Audio Problem with Revolution Unlimited Pro Controller

### ISSUE THREAD

**Issue by DarkGigi2217** [Ryochan7/DS4Windows#1393]
When i connect my headphones jack to the controller, the computer recognize an audio device called Revolution unlimited Pro Controller, and i can hear sounds through headphones; but as soon as i open DS4Windows it doesn't work anymore. it seems like the volumes continuously resets to 0, because if i rise it up i can hear sounds for a few seconds. Please Help!!!
![sound example](https://user-images.githubusercontent.com/68064955/87042343-d69c4280-c1f3-11ea-9444-9254d7eb5d55.png)
Image Text is in Italian, but the last device on the list is the controller one.

**Comment by Ryochan7** [comment]
That is a consequence of sending output reports when DS4Windows cannot detect a DS4 audio device. The headphone volume is a part of the output report used to transmit rumble data, lightbar data, along with other data. If DS4Windows cannot find the associated audio device for that DS4 then the headphone volume will get set to 0. DS4Windows can find the audio device for a DS4 v.2 and the Sony Wireless Adapter.

The current routine used to scan for DS4 audio devices is not great and mainly uses string identifiers. That limitation would probably not work well for people not using English as the primary language in Windows. Also, there is no way that I have found to associate a specific DS4 audio device to a specific DS4 HID gamepad device.

**Comment by KillerVan** [comment]
I had the same issue with that controller; i dont get why is there need to set the volume to 0. Is there a way to make this audio reset a bool that the user can change?

**Comment by DrDedmon** [comment]
Having the same issue. Any workaround for it?

**Comment by Ryochan7** [comment]
> I had the same issue with that controller; i dont get why is there need to set the volume to 0. Is there a way to make this audio reset a bool that the user can change?

I should just stop trying to explain technical issues to people.
