### ISSUE TITLE
Controller not detected by Retroarch when using DS4Windows.

### ISSUE THREAD

**Issue by Newtype14** [Ryochan7/DS4Windows#1396]
Controller: DS4 (via USB).
DS4Windows version: 2.1.4
Retroarch version: 1.8.9

I've been trying to fix this for hours. I'm familiar with DS4Windows' settings and Retroarch, but this has got me completely puzzled. When I'm not using DS4Windows, my controller is detected and I can control Retroarch's menu with it. When I'm using DS4Windows, nothing works, it's like I have no controller plugged in. This only happens with Retroarch.

In DS4Windows, "Hide DS4 Controller" is enabled.
In Retroarch, the controller driver is set to "xinput".
In Input => Port 1 Controls, Device Index is set to "Disabled" and I cannot change it to anything else.

I know that Device Index should be set to "XInput Controller" for it to work, but that's not even possible for me to do.

**EDIT**: Out of curiosity, I just tried it with Jays2Kings' DS4Windows and everything worked. Device Index was set to XInput Controller, I was able to control the menu and games were working as well, with vibration and everything. What could be causing the problem with this DS4Windows?

**EDIT 2**: I tested older versions of DS4Windows and found that version 1.6.14 is the oldest working version.

**EDIT 3**: Solved. Read further below for the solution.

**Comment by mika-n** [comment]
https://github.com/Ryochan7/DS4Windows/issues/435

- Make sure exclusive mode is working or replace it with HidGuardian tool.
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

- Is Steam set to start at system boot? In that cause you may have to replace the built-in " Hide DS4 Controller" option with HidGuardian solution.

**Comment by Newtype14** [comment]
Exclusive mode is working and I also tried HidGuardian. It didn't work.
Steam is not running.

I tried to find the oldest working version of DS4Windows and it's version 1.6.14.

**Comment by Ryusennin** [comment]
DS4Windows 2.1.4 does work with RetroArch. I've just used it a couple days ago. I'll have to check my configuration (away from my desktop right now) but I don't remember setting anything special. HidGuardian is installed.

**Comment by Newtype14** [comment]
> You need to set this option to "EasySMX". Use the keyboard arrows (left or right) to select it.

Are you using a DualShock 4 controller? I didn't know what EasySMX was so I googled it and it's a company that makes gaming controllers and other stuff. "Disabled" is the only option for me (using keyboard arrows gives no other choice). This is probably because Retroarch doesn't detect my controller when I launch it. I don't get any message in the bottom left corner when I launch the program.

**Comment by Ryusennin** [comment]
Yes, I use genuine Sony DS4 controllers (v1 and v2). For some unknown reason, the XInput/X360 option in RetroArch has been recently re-labelled EasySMX, which is maybe a bug or maybe a marketing stunt with the manufacturer of the same name. I have no clue but it works for me.

A quick search on Reddit showed many people with the same issue, except their X360 controller is not working at all. It could be related to your problem and that would rule out DS4Windows.

https://www.reddit.com/r/RetroArch/comments/haf9q5/wired_360_controller_xinput_now_loading_as_easysmx/

**Comment by Newtype14** [comment]
**I have just solved my problem**. I tried to find why it was working with version 1.6.14, but not the others after. Looking at the changelog for version 1.7.0, it says: "ViGEmBus support has been added. ScpVBus support has been removed."

I looked at my log window in DS4Windows and it said this: "Connection to ViGEmBus 1.14.3.0 established".
I took a chance and reinstalled ViGEmBus, then relaunched DS4Windows.
Now my log window says this: "Connection to ViGEmBus 1.16.112.0 established".

It updated it! I had assumed that when you update DS4Windows, it also updates ViGEmBus. The main page says that DS4Windows installs it for you.

I now launched Retroarch and it detected my controller immediately. Device Index also says "XInput Controller (User 1)".

**Comment by mika-n** [comment]
@Newtype14  Good it works now. DS4Windows installer does install VigEm driver also if it is missing because without it DS4Windows 2.x version would not work at all. However, the auto updater of DS4Windows does not update VigEm driver, so maybe you had an old version of ViGem driver originally?

**Comment by Newtype14** [comment]
@mika-n I've been using DS4Windows for a long time, so that was probably why.

**Comment by Ryochan7** [comment]
ViGEm installer 1.16.112.0 and later sets up a scheduled task to check for ViGEmBus updates. DS4Windows checks if a version of the ViGEmBus is installed and will allow the option to download the ViGEm installer if the driver is not found. DS4Windows should still work with ViGEmBus 1.14.3.0 even with the updated ViGEm.NET library but I have had no reason to test it.

A few 2.x builds with ScpVBus support have been made in the past. The last version packaged was for version 2.1.2. It is mainly for testing as I would not normally recommend people use it. 

DS4Windows_ScpVBus_20200607.7z:
https://drive.google.com/file/d/1yhaEhlZWV9pGgJjQuJJR7yOKtpnRx9Om/view?usp=sharing
