### ISSUE TITLE
make gyro passthrough for emulated ds4 controller

### ISSUE THREAD

**Issue by TheHacker24680** [Ryochan7/DS4Windows#1399]
so i have geforce experience installed so i needed to download hid guardian and it worked but now when i play a game that accept native gyro control it doesn't work with ds4windows cuz it doesn't have gyro passthrough so i tried turning off ds4windows but cuz of hidguardian the controller doesn't show up so that means every time i try to play a game (like paladins) with native gyro support i have to remove my controller id from the registry and restart the pc ( i have ds4 v.2)

**Comment by mika-n** [comment]
You can use the HidNinja tool to "comment out" device vid/pid identifier in HidGuardian AffectedDevices sysreg entry (or use exported REG file to import a specific enabled/disable HID reg file). Then all you need to do is to disconnect and re-plug a gamepad to make it work with or without HidGuardian tricks. There should not be need to restart PC.

Unfortunately the current version of ViGem doen't support yet gyro and touchpad output interfaces. VigEm team has experimented with touchpad output interface, but it is not released yet as an official signed HidG driver. Not sure if anyone has experimented with gyro output support.

**Comment by TheHacker24680** [comment]
first off thanks for replying 
so where can i download this tool?

**Comment by mika-n** [comment]
The latest V2.1.4 DS4Windows zip package has new "Tools" folder. HidNinja tool is there.

**Comment by TheHacker24680** [comment]
thanks so much for the reply HIDNinja tool worked but sadly the game wouldn't recognize the controller as it is DS4 V.2
would hope that ViGEm driver support native gyro output in the near future
