### ISSUE TITLE
[Sony Dongle] USB priority

### ISSUE THREAD

**Issue by pralima87** [Ryochan7/DS4Windows#14]
Another issue with the Sony dongle.
Even after disconnecting the controller with the dongle and them connecting with the USB cable causes the controller to become the second controller.

Like the dongle is a controller by itself.
But the "dongle" controller does not work or respond.

Any chance the USB could take priority?

**Comment by Ryochan7** [comment]
The dongle is a controller by itself. That is the way the hardware is designed. As long as the dongle is connected to your computer, it exposes a controller to Windows.  There isn't anything that can be done in DS4Windows to work around that design.
