### ISSUE TITLE
Swipe change lightbar color

### ISSUE THREAD

**Issue by efremzero7** [Ryochan7/DS4Windows#1400]
Can i possibly make a swipe down change the color of the current profile to black, so turning it off, and then swipe up to turn back to what it was set in the profile?
Thanks

**Comment by mika-n** [comment]
Yes and No. You cannot directly bind "change color" to swipe down event, but Settings tab page has "swype to change profile" option. You could use swype to change profiles and each profile could have the same setup except with a different color.

**Comment by mika-n** [comment]
See #1224    

This feature is now possible with a special action macro. The macro recorder can record both normal button events and custom lightbar events. Now if the macro set a custom ligthbar color then the color is left active if the macro has "Keep key state" option set and the macro execution is completed. This ligthbar behavior is now consistent how keepKeyState option works with normal button events.
