### ISSUE TITLE
Gyro issue

### ISSUE THREAD

**Issue by Anycker** [Ryochan7/DS4Windows#1401]
when I check invert x in output mode = mouse joystick , what inverted is not the x axis, but the y axis. But work well in mouse output mode. Please fix this problem

**Comment by mika-n** [comment]
Please provide the profile file you use (zip it or rename as .TXT file and attach here).

**Comment by Ryochan7** [comment]
Invert X accidentally inverts the Y axis coordinate instead. Invert Y does nothing.

**Comment by Ryochan7** [comment]
Looked back and that feature has been broken since the release of version 2.0. The last commit fixes the problems with the invert options.
