### ISSUE TITLE
R2 Fire time *question*

### ISSUE THREAD

**Issue by OuroborosVX** [Ryochan7/DS4Windows#1402]
Is there a way to make R2 go through instantly instead of "charging up" by that I mean instead of being in a car speeding up with R2, the r2 goes through instantly either slightly or at full force doesn't matter to me.

**Comment by mika-n** [comment]
Tweak the output curve of L2 axis. You can set it to "custom" and then use bezierCurve to "max out the output curve" even when the L2 is pressed just slightly.

Or you could tweak sensitivity or anti-deadzone values also to max out the output almost instantly when the L2 is pressed downl. 
 
Tweak those settings and use "Controller Readings" tab page to verify when the output is what you want (input vs output value of L2 axis).

**Comment by Ryochan7** [comment]
mika-n has already answered the question. There are a few options for making R2 behave more like a digital button than an analog trigger.
