### ISSUE TITLE
Can't set steering wheel on ETS2

### ISSUE THREAD

**Issue by joaogrande10** [Ryochan7/DS4Windows#1407]
Hello, I can't properly set the steering wheel function of DS4windows on ETS2. I got vJoy installed and the vJoy dll correctly into the folder that contained DS4windows.exe file and I could calibrate and create the vJoy device. But I can't make this function properly inside the game. ETS2 recognizes the vJoy device, although it doesn't respond to my controller movements. I'm sorry if I couldn't make myself clear, I'm a noob here :)

**Comment by mika-n** [comment]
I use DS4Windows + 360 steering wheel emulation mode  + vJoy output axis with ETS2. Works great with "DIY rig" (the "steering wheel" immersion is surprisingly good). Much better than trying do steer the truck with mouse or keyboard.
https://github.com/Ryochan7/DS4Windows/pull/491#issuecomment-439821245

https://github.com/Ryochan7/DS4Windows/wiki/Settings#steering-wheel

Step 1 is to make sure the 360-steering wheel mode works and the gyro output is redirected to vJoy axis. When DS4Windows is running then what do you see in JOY.CPL controlPanel applet? Run this command or click "Controller Settings" link in DS4Windows Other option tab page. When you choose vJoy joystick device in JOY.CPL and turn around the gamepad then do you see any activity in vJoy axis?

If you don't see any vJoy activity then please attach the DS4Windows logfile here (the latest file in %APPDATA%\DS4Windows\Log folder. Rename it as TXT file and attach the file here).



Step 2 is to configure controllers in ETS2 game. Make sure the vJoy joystick axis is chosen as a steering axis.

Also, if you re-map any of the "normal" DS4 gamepad keys then ETS2 requires exclusive mode or HidGuardian tool to avoid double input problem.
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

**Comment by joaogrande10** [comment]
Thanks for the reply, mika-n. I ran joy.cpl and when I moved my controller, the axis haven't moved at all. It stayed in the center of the square. The log and joy.cpl window are attached below.
![joycpl](https://user-images.githubusercontent.com/55845765/87933083-fb4db100-ca62-11ea-8b88-70e28f513fdd.png)

[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/4947338/ds4windows_log.txt)

**Comment by mika-n** [comment]
Does the 360-steering wheel mode work if you map is as LS or RS x-axis?  This would tell us if the issue is in vJoy side or something wrong with the 360 mode in DS4Windows setup in your PC.

**Comment by joaogrande10** [comment]
No, it doesn't work either, not responding to any of my commands.

**Comment by mika-n** [comment]
Hmm.... Maybe you should send the profile file here for testing? Rename the profile file as .TXT or zip it.
When you tilt the gamepad do you see any gyro activity in "Controller Readings" tab page?

Or have you enabled the "Use DInput only" option? Try disabling that option because at some point there was a bug where 360-steering wheel mode didn't work if this option was set and there were no special actions defined either (ie. all custom re-map rules were disabled and ignored and this way 360-steering wheel custom mapping rule was never executed).

**Comment by joaogrande10** [comment]
I'm sorry for replying late, but I had some busy day yesterday. Here is my profile configs. Again, thanks for your patience and will to help.
[ETS.zip](https://github.com/Ryochan7/DS4Windows/files/4956023/ETS.zip)

**Comment by Ryochan7** [comment]
This looks like a profile reader problem. The SXDeadZone and SZDeadZone are not interpreted correctly so the SX and SZ dead zones are maxed out. Lower those dead zones allows 360 Steering Wheel mode to work as intended.

**Comment by Ryochan7** [comment]
Nothing is wrong with the profile reader nor the writer. Looking at that profile, I am going to assume that you edited the profile manually and did not respect the proper data range. SXDeadZone and SZDeadZone have always been interpreted as a double in the range of 0.0 - 1.0; that is true in the old Jays2Kings build as well. The value of 25 should not be present in the profile when the file is written out by the program. That value would be represented as 0.25 for 25%.
