### ISSUE TITLE
Controller Readings break with Square Stick enabled

### ISSUE THREAD

**Issue by Flybel** [Ryochan7/DS4Windows#1409]
Using Windows 10 Pro 1909 and a newer DualShock 4 via Bluetooth to a USB Bluetooth dongle.
I am editing a profile and have the Controller Readings tab opened. 

When I enable "Square Stick" for the left analogue stick and then move that stick beyond (seemingly) the deadzone, the readings freeze completely. When I close the profile editor and reopen it, the readings are then empty. The only way to exit DS4Windows in that case is to press Stop and then close the application (the BT connection remains, but only then will the DS4Windows process end and the emulated controller disconnect), doing either one without the other will not work.

This issue does not occur when the Controller Readings tab is not opened or Square Stick is disabled. The corresponding value for this option does not seem to matter.

DS4Windows logs don't show any information beyond perfectly normal connecting and shutdown.

**Comment by Ryochan7** [comment]
It is working fine for me using version 2.1.4. I doubt it but maybe this issue can be attributed to a division by zero issue fixed in #1410. That change has not been pulled or committed to the code yet.

**Comment by Flybel** [comment]
I am on the latest version (2.1.4, using the built in updater) also and this (still) happens with both the left and the right stick while square stick is enabled for the respective side. I will report back when there is an update, I also plan on reinstalling Windows soon-ish.

**Comment by Flybel** [comment]
The issue persists in version 2.1.5.

**Comment by Ryochan7** [comment]
Still works for me even with that profile
