### ISSUE TITLE
Can we have separe deadzones for X/Y axis in both Right and Left stick?

### ISSUE THREAD

**Issue by DarkRoku12** [Ryochan7/DS4Windows#1412]
The title says all. 

Can we have separe deadzones for X/Y axis in both Right and Left stick?

**Comment by Ryochan7** [comment]
Different dead zone options for LS and RS have been discussed before. I have never gotten around to trying to implement something. I have never needed anything more than the radial dead zone option that is currently used.

**Comment by Ryochan7** [comment]
Hoping to work on this for version 2.1.12; 2.1.11 will likely be a small hotfix release.

**Comment by Ryochan7** [comment]
Finally got this implemented in version 2.2.11

https://github.com/Ryochan7/DS4Windows/releases/tag/v2.2.11
