### ISSUE TITLE
Gyro analog control + gyro actions?

### ISSUE THREAD

**Issue by alpharou** [Ryochan7/DS4Windows#1413]
So, I created this simple special action where you tilt the controller up to check the battery with the lightbar, really cool that you can do that. But I also frequently use gyro as a mouse input, which for some reason completely negates the tilt actions.

Is there a way tilt actions can be triggered alongside mouse gyro control? It sounds strange, but for the sake of consistency I think it should behave that way.

**Comment by Ryochan7** [comment]
This conflates two different systems. The special actions system is separate from the main mapping system so a special action bound to a Tilt direction will work no matter which Gyro output mode is used. Even though Steam Input allows binding to Gyro Lean controls when binding Gyro Mouse, that is not possible in DS4Windows.

The current mapping system would not accommodate that type of binding option. Also, I have never needed an option like that even when using Steam Input. That feature will likely never be implemented.
