### ISSUE TITLE
The process DS4Windows.exe was terminated due to an unhanded exception

### ISSUE THREAD

**Issue by mitalis83** [Ryochan7/DS4Windows#1416]
I recently upgraded from DS4Windows 1.7.2 to 2.1.4 as I guess some recent windows 10 update broke something as I could not get the application to recognize my controller plugged in bluetooth despite Windows 10 seeing it. So I opted to upgrade. Now if I double click on the DS4Windows app... Nothing happens.. I was reading the forums and somebody pointed out checking the Event Viewer and sure enough I'm seeing errors.  This is what I'm getting when I try opening the DS4Windows 2.1.4:

EventData Application error:

DS4Windows.exe
Log Name:      Application
Source:        Application Error
Date:          7/25/2020 8:38:00 AM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      n/a
Description:
Faulting application name: DS4Windows.exe, version: 2.1.4.0, time stamp: 0x80cc936b
Faulting module name: KERNELBASE.dll, version: 10.0.18362.959, time stamp: 0x7b90c1b5
Exception code: 0xe0434352
Fault offset: 0x000000000003a799
Faulting process id: 0x2840
Faulting application start time: 0x01d6629993fd5700
Faulting application path: C:\Users\name\Desktop\DS4Windows\DS4Windows.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: ac8f064a-be53-4aa0-acea-c1ed879ea3a5
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-07-25T15:38:00.832290500Z" />
    <EventRecordID>14138</EventRecordID>
    <Channel>Application</Channel>
    <Computer>name</Computer>
    <Security />
  </System>
  <EventData>
    <Data>DS4Windows.exe</Data>
    <Data>2.1.4.0</Data>
    <Data>80cc936b</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.18362.959</Data>
    <Data>7b90c1b5</Data>
    <Data>e0434352</Data>
    <Data>000000000003a799</Data>
    <Data>2840</Data>
    <Data>01d6629993fd5700</Data>
    <Data>C:\Users\Mitalis\Desktop\DS4Windows\DS4Windows.exe</Data>
    <Data>C:\Windows\System32\KERNELBASE.dll</Data>
    <Data>ac8f064a-be53-4aa0-acea-c1ed879ea3a5</Data>

.NET Runtime error:
Application: DS4Windows.exe Framework Version: v4.0.30319 Description: The  process was terminated due to an unhandled exception. Exception Info:  System.IO.FileNotFoundException at  DS4WinWPF.App.<CreateControlService>b__24_0() at  System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext,  System.Threading.ContextCallback, System.Object, Boolean) at  System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext,  System.Threading.ContextCallback, System.Object, Boolean) at  System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext,  System.Threading.ContextCallback, System.Object) at  System.Threading.ThreadHelper.ThreadStart()

Any ideas?

**Comment by mika-n** [comment]
Anything in the latest "%APPDATA%\ds4windows\log" logfile?

Meanwhile make sure you have the latest runtime requirements;
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#link-list

**Comment by mitalis83** [comment]
Latest runtime requirements I guess was the problem. Updates .net framework. Seems weird given .net updates normally happen through the windows updates.
