### ISSUE TITLE
Gyro -> Mouse Joystick -> "Invert X" inverts Y and "Invert Y" does nothing.

### ISSUE THREAD

**Issue by guiq83** [Ryochan7/DS4Windows#1421]
"Gyro" -> "Mouse Joystick" -> "Invert X" inverts Y and "Invert Y" does nothing.
Tested on version 2.1.4 and 2.1.3 both x64 from the .zip files.

**Comment by mika-n** [comment]
#1401 

Fixed but waiting to be released: https://github.com/Ryochan7/DS4Windows/commit/95dc849fafab4a7290ffc545a4cd612a954372f9
