### ISSUE TITLE
Multiple inputs mapped to one control 

### ISSUE THREAD

**Issue by aemiguel** [Ryochan7/DS4Windows#1423]
Some games would benefit greatly from the ability to assign multiple controls to one input.

An example of this is Far Cry 5 where, if the general controls are mapped to Xbox 360 but the gyro is mapped to mouse aim the game flips constantly between mouse and controller hints on screen and this results in severe stutter when aiming.

Others have solved this problem when using steam controllers by having the touch input on the pad also send a keyboard press to force the hints to show as keyboard, but this isn’t possible with DS4Windows thus there are no really suitable configurations for controller plus gyro aim on FC5.

This could be implemented in the same way as the alternate input, where, when configuring a button you can select the radio button and assign a different output if, for example, a trigger is pressed.

A third radio button could allow you to specify a second output when a controller key is pressed, meaning that pulling the L2 trigger would input L2 to the game, but also e.g. right shift to force the hints to remain on keyboard and not flip between that and controller hints.

This is just one example but there are other potential cases where this could be beneficial to jointly send inputs with one button and free up buttons on the controller.

**Comment by Ryochan7** [comment]
Never heard of sending both KB and XInput controls being a possible workaround to the issue in some games. The typical workaround for games that have problems with Mixed input mode is to map the Gyro to Mouse Joystick. I don't see multiple actions for one control ever being implemented in DS4Windows though. I tend to avoid making massive changes that could lead to breakage and changing the mapping system to allow for multiple outputs for one input would break several assumptions put into the mapping system.

**Comment by Ryochan7** [comment]
Apart from the mapping system, a change like this would very likely require a profile migration system at this point. The syntax of the XML files would have to change to accommodate for multiple actions bound to one input.

**Comment by aemiguel** [comment]
I wasn't aware of Mouse Joystick and it works great in my big example case (FC5) so thanks for that!  

To be honest that was by far the most compelling case, I can't think of anything else that isn't just theoretical and it sounds like the degree of effort required would require much more justification than that.

**Comment by Ryochan7** [comment]
On a somewhat related note, profile migration support is in the works for DS4Windows 2.1.6. Adding support for the 1 Euro filter for other Gyro modes has made me finally get around to making some form of migration system. Basic support for binding multiple outputs to one input might be more feasible in the future. Some backend classes would have to be changed to take away the one bound output assumption. I would mainly use it just to allow for something like binding Shift + Tab to bring up the Steam Overlay. Although, the macro system can take care of that use case already.
