### ISSUE TITLE
latency over 10ms

### ISSUE THREAD

**Issue by belhiumr** [Ryochan7/DS4Windows#1424]
im using a usb bluetooth dongle with an original ps4 controller, but i get high latency and sometimes disconnect.
i tried alot of solutions(power mode/usb power)but nothing worked.
the controller works fine with a cable and with my laptop.[
[log.txt](https://github.com/Ryochan7/DS4Windows/files/5012445/log.txt)
](url)

**Comment by Ryochan7** [comment]
:shrug:

**Comment by dougshell** [comment]
belhiumr, what Bluetooth dongle are you using? Some are trash and some are amazing. If you have a good dongle, try plugging it into a male to female cable extension and backing away from your laptop a bit as it may be an interference issue. 


Here is the dongle I use. 
https://www.amazon.com/Bluetooth-Receiver-Keyboards-Controllers-USB-BT400/dp/B00DJ83070

**Comment by mika-n** [comment]
try setting the "flash lightbar at high latency" issue to higher value if your PC/BT dongle/BT chipset is not up to the task to handle both read+write BT operations fast enough (DS4Windows app both reads from DS4 pad AND writes data to DS4 pad over BT communication line and this happens several times per second).  Even if some sportwatches and devices like that work over BT those often don't read/write in such a fast pace as gamepads and DS4Windows app.

Also, you might get better result with non-100% compatbile BT dongles/chipsets if you untick "Enable Output data to DS4" option. You loose lightbar and rumble support, but by unticking this option means DS4 gamepad data is only read (not written to), so it makes the life of BT a bit easier.
