### ISSUE TITLE
Crash when i try to edit profile

### ISSUE THREAD

**Issue by marcelgompact** [Ryochan7/DS4Windows#1425]
crash when i click on the edit button to open profile editor it does it with any profile and i even try deleting ViGEmBus driver but still crashes. 

Here is my log
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/5013627/ds4windows_log.txt)

**Comment by mika-n** [comment]
There has been few similar reports before. Those turn out to be issues in 
- .NET Framework installations (old or corrupted .NET library setup). Try updating WinOS and the latest .NET library version.
- file permission issues (some PCs don't like it if a ZIP file is extracted into c:\programfiles folder). Try running the app in for example c:\apps\ds4windows\ folder.

https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#link-list

**Comment by mika-n** [comment]
closed as inactive
