### ISSUE TITLE
[Feature request] Flick stick , like JoyShockMapper?

### ISSUE THREAD

**Issue by Darthagnon** [Ryochan7/DS4Windows#1426]
Greetings.

I was wondering if it would be possible to implement a flickstick control toggle, similar to [JoyShockMapper](https://github.com/JibbSmart/JoyShockMapper)? Or maybe implement JoyShockMapper under-the-hood, to deal with gyro and flick stick stuff?

**Comment by Ryochan7** [comment]
I have had that idea recently. I am on the JSM Gyro Gaming Discord and I have been testing JSM often over the past few weeks. I have played with Flick Stick a bit and that feature seems like even more of a game changer than the way JSM handles Gyro mouse. Especially now that Steam has its own implementation of Flick Stick for the beta version of Steam Input, it is probably a good idea to try to attempt to make an implementation for DS4Windows.

**Comment by Darthagnon** [comment]
Thank you so much for considering this! I saw some Halo gameplay with JSM, and it confirmed what I'd suspected from experiments using DS4Windows' gyro implementation for shooters - makes it significantly more accurate than pure joystick, and comparable with mouse imo

**Comment by jdawgzim** [comment]
I'm trying to get into Flick Stick but JSM isn't easy to setup if you're constantly trying new games with it.  I'd love to see it in DS4Windows and it'll also help send a message to Microsoft and Sony that Gyros can be useful.

**Comment by Ryochan7** [comment]
At least, in theory, it is possible. Other than being able to pull off a quick 180 degree turn, I am not sure I would use it.

The following diff shows that it does not require much extra work to allow some basic support.

https://gist.github.com/Ryochan7/8fbbf5d43f7e687b0ffb04a26fd4fa59

**Comment by Darthagnon** [comment]
Thank you so much for sharing that!

Is it likely to be implemented in a future release, or would I do better installing the dependencies and building from source with that edit?

**Comment by Ryochan7** [comment]
The hope is to implement the feature in a future version of DS4Windows. A couple of minor tweaks have been made since the first test diff that addresses a couple of issues; particularly the fuzz issue that is brought up on GyroWiki when some positions of the stick cause oscillation between coordinates. I would say the current diff works about as well as Steam's implementation of Flick Stick.

Another related problem that must be solved first is to allow different output modes for LS and RS. I am working on the MapCustom routine to attempt to allow different modes other than Controls mode.

**Comment by Ryochan7** [comment]
I think I will end up tweaking the schema used to store the settings in a profile. Other than that, I think the feature is pretty much done. The code is currently available in the flickstick branch. I want to hold off on merging the code to jay for at least a couple of days.

https://github.com/Ryochan7/DS4Windows/tree/flickstick

**Comment by Ryochan7** [comment]
Short demo video of Flick Stick in action. Playing a small section of Jedi Academy. Probably should have chosen a different game; footage is fairly dark.

https://www.youtube.com/watch?v=PMxA4GksH0c

**Comment by jedinjapan** [comment]
Performs excellent when tested in Bioshock Remaster.

Circle strafing produces a bit of a "stutter" effect and is a bit less smooth than analog camera, but I believe that is just part of this type of control.

**Comment by Ryochan7** [comment]
You might want to try playing with the **Min Angle Threshold** setting. Some positions of the DS4 thumbsticks can produce some minor jitter which would be more apparent when using Flick Stick. This type of problem is mentioned in GyroWiki. I think JoyshockMapper works around the problem by throttling smaller output changes.
