### ISSUE TITLE
Steam not detecting ds4 controller (can't navigate in big picture) when exclusive mode is enabled with HIDGuardian

### ISSUE THREAD

**Issue by dhanjit** [Ryochan7/DS4Windows#1427]
Is this normal behaviour? Shouldn't steam pick up the controller through DS4Windows?

**Comment by Ryusennin** [comment]
HIDGuardian works fine in Big Picture. Make sure to uncheck all configurations in Steam Controller Settings.

https://i.imgur.com/ZFMf9UH.png

**Comment by dhanjit** [comment]
It worked after changing the mode from DualShock4 to Xbox 360 in profile of controller. Thanks,.
