### ISSUE TITLE
Mapping special action (eg. PS+R2) to a macro passes the R2 to the game as well.

### ISSUE THREAD

**Issue by dhanjit** [Ryochan7/DS4Windows#1428]
Basically I mapped PS+R2 to a macro Ctrl+Alt+Home (a custom screenshot task through sharex). However, while the screenshot gets taken, the R2 still passes on to the game. Can this be avoided?
Using latest DS4windows, Hidguardian from the wiki installer. Game I am trying on is cemu/Zelda BotW.
P.S Is there a better way to take screenshots through the controller?

**Comment by dhanjit** [comment]
Have tried the scan code method as well, still passes on R2 to the game. Also tried Keep key state option, doesn't work either.

**Comment by Corgano** [comment]
Duplicate with https://github.com/Ryochan7/DS4Windows/issues/1430. There's more comments about this issue there

**Comment by Ryochan7** [comment]
Version 2.1.7 implements a simple workaround to the problem that should be good enough for most cases. Now triggers for Special Actions will deactivate the state fields before running through the actual mapping routine. The R2 mapping would not take effect until the PS button is released.
