### ISSUE TITLE
Controller In Charge Mode Indefinitely

### ISSUE THREAD

**Issue by shinra358** [Ryochan7/DS4Windows#1429]
when the controller is plugged in for charging, it stays at 90+ percent when it gets there and stays in charge mode. When you remove the cord and plug it back in, ds4 windows shows 100% and then charge mode is off. This should be automatic without having to unplug and replug.

**Comment by Ryochan7** [comment]
The events should be transmitting as intended. I have not run into this type of problem while charging my controllers. The only way, that I can think of, to diagnose this issue would be to add a view to the Controller Readings section that would allow inspecting the data in the current DS4State instance. That way, you would be able to see if DS4Windows is reading 100% battery from the controller when the GUI is only reporting a 90%+ in the controller listing.

**Comment by shinra358** [comment]
Happened to me when the program was on for an extended period of time

**Comment by shinra358** [comment]
But that sounds good for diagnoses

**Comment by shinra358** [comment]
Yeah, just tried the new version, left it plugged in over night. When I woke up, still in rainbow charging mode until I unplugged and replugged.

win7u

**Comment by Ryochan7** [comment]
I started implementing my original idea and decided it was not worth the trouble. I just added the Battery Level to the current Controller Readings panel. It will display the current value in the DS4State object. That will probably be good enough anyway.

![contreading_batterylvl](https://user-images.githubusercontent.com/581968/91206783-50698c00-e6cd-11ea-8224-504784093211.png)
