### ISSUE TITLE
[Feature Request] Automatically Stop NvContainerLocalSystem service when clicking Hide DS4, then run the service after it hiding

### ISSUE THREAD

**Issue by bigorados** [Ryochan7/DS4Windows#1431]
It is known at least for me that Hide DS4 doesn't work when this service is running, so aside from just showing a suggestion warning, i would like for the program to do all the work for the user =V

**Comment by Ryochan7** [comment]
It is too invasive of a procedure. Also, it is a moving target as more software keeps interfering with the old Hide DS4 functionality. For the most part, it is a dead feature and HidGuardian would be considered a part of a standard DS4Windows install if the vanilla version worked the way I wanted it too. I have made an installer for my custom version but it obviously requires running Windows with TESTSIGNING turned on. Some online games don't like that; Valorant is one example.

HidGuardianInstaller_20200615.7z:
https://drive.google.com/file/d/1XSIdgh6P-WCLs3JR0yVWYnWr_FNT5jfZ/view?usp=sharing

**Comment by bigorados** [comment]
That interests me very much, thank you for the reply, will definetely try that.
I hope that you can revamp the Hide DS4 with HidGuardian for more casual users

**Comment by Ryochan7** [comment]
Unfortunately, Microsoft has placed that type of ease of integration behind a paywall (~$200 USD). Can't really distribute Windows drivers without getting them verified and digitally signed with a valid certificate. Using a test certificate has some flaws as noted before and places a bigger burden on the end user to allow the driver to work at all.

**Comment by mika-n** [comment]
@bigorados   If you want to force shutdown some apps or services when launching DS4Windows app then you can do it via a custom batch (CMD/BAT) script. The script could shutdown services or apps you want, launch DS4Windows app and then re-enabling services or apps.

Here a link to "DS4Windows command line" documentation page for more info about how to start/stop/shutdown DS4Windows app via Windows batch script command line calls. You could do those calls within your own batch script.
https://github.com/Ryochan7/DS4Windows/wiki/Command-line-options
