### ISSUE TITLE
[Feature Request] Support PS4 dongle for guitar hero live

### ISSUE THREAD

**Issue by dougshell** [Ryochan7/DS4Windows#1432]
The hardware is the same on Wii, Xbox, and PS4 but the PS4 dongle doesn't work.

It pairs, but doesn't map properly.

**Comment by Ryochan7** [comment]
I don't have the hardware so I can't do anything about adding support for it. Nonetheless, I am going to mark this issue as invalid. I would recommend that you check out Rocksmith 2014 instead and learn how to play a real guitar.

https://rocksmith.ubisoft.com/rocksmith/en-us/home/
https://store.steampowered.com/app/221680/Rocksmith_2014_Edition__Remastered/

**Comment by dougshell** [comment]
I know how to play a real guitar. 

Where are you located, I could send you one of mine if you think you would be able to figure it out. 

Everything maps perfectly, the issue is that the strum bar moves the up/down on the x/y but when a button is pushed, it negates any strum action. 

If you are in the states I would ship both ways if you thought you had a decent chance of fixing
