### ISSUE TITLE
DS4 Control Disconnect / reconnect loop - wired doesnt work either

### ISSUE THREAD

**Issue by jbrook93** [Ryochan7/DS4Windows#1434]
**Describe the bug**
Old DS4 control developed an analog stick fault, bought a new V2 controller. Synced with bluetooth and all you see is the the device appear on the controllers list and then disappear every 1-2 seconds.

You also hear the windows connecting and disconnecting sounds

**To Reproduce**
1. Connect new DS4 control (solid white light)
2. Click on ds4 windows, Clicking start starts the above mentioned loop.
3. Click stop because cant bear it, sound goes away. 

**Expected behavior**
The device to connect so I can play Fifa

**Screenshots**
none

**Desktop:**
 - OS: Windows 10 1909
 - DS4Windows Version 2.1.5

**Additional context**
Older DS4 control works ok and connects without above issues. (Only analog stick is broken so I have to use new) 
- Have uninstalled HID compliant game from device manager

[log.txt](https://github.com/Ryochan7/DS4Windows/files/5046135/log.txt)

**Comment by Ryochan7** [comment]
The log shows that it is a fake DS4 controller. I do not support the use of fake controllers.

**Comment by jbrook93** [comment]
Im not understanding what indicates it is a fake controller by looking at the log?
