### ISSUE TITLE
[Suggestion] Add option to emulate dualshock 4 v1(old controller) connected via wire instead of xbox 360 controller emulation

### ISSUE THREAD

**Issue by luckydaemon** [Ryochan7/DS4Windows#1435]
Some games have dualshock 4 support without using any external software, but problem is that they specifically want dualshock4 to be connected via wire or seeks for old version of controller, otherwise they dont recognize controller at all or recoginze it as 360 controller with wrong mapping. So I thought it would be nice feature to emulate ds4 v1 with wired connection, so people who want to use their controller wirelessly or have only new version can get native support in games.

**Comment by mika-n** [comment]
Hmm..... This Ryochan7 version of DS4Window app already supports dualshock4 as an output controller type, so I'm missing something in the question or are you using some veeeeeery old version with ds4 support?

See "Read this before posting a new issue ticket" pinned post for more info about what information to provide (logfiles, app versions).
https://github.com/Ryochan7/DS4Windows/issues/1196

https://github.com/Ryochan7/DS4Windows/wiki/Settings

**Comment by Ryochan7** [comment]
The option already exists

**Comment by Ryochan7** [comment]
A video discussing the feature

DS4 Emulation in DS4Windows
https://www.youtube.com/watch?v=RdQAuboYYKo

**Comment by luckydaemon** [comment]
Somehow I missed this option myself, and wherever I asked about it no one told me that it exist. Sorry for opening issue.
