### ISSUE TITLE
Wireless won't connect

### ISSUE THREAD

**Issue by tiggman** [Ryochan7/DS4Windows#1436]
Unsure if the issue is within the program itself ort somewhere else, I am just beginning with it. I followed all the steps, I have the controller connected to my pc via the bluetooth dongle, I have connected the controller via the micro usb cable and installed the drivers, followed every step the guide gave me, every video I could find...  if I unplug the controller from the wire the light flashes and it never connects.

hoping someone can provide some advice. 

Thanks

**Comment by mika-n** [comment]
Please read the pinned "Read this before posting a new issue ticket" post. Your message doesn't have much information. While you are reading the instructions about how to post a detailed error report then you might wanna try the debug version because it show a lot more detailed log messages.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

**Comment by jekyllgrim** [comment]
Hi, I'm having the same problem. DS4 connects fine, but nothing aside from Windows detects it (neither DS4Windows, nor Steam Big Picture). This only occurs with bluetooth; wired works fine. (Naturally, it works fine with my PS4 as well). Attaching logs for wired and wireless attempts. I'm not sure what I could modify in debug config, though, so there are only 2 files.

[ds4windows_log_20200820.5 - wireless.txt](https://github.com/Ryochan7/DS4Windows/files/5104925/ds4windows_log_20200820.5.-.wireless.txt)
[ds4windows_log_20200820.4 - wired.txt](https://github.com/Ryochan7/DS4Windows/files/5104926/ds4windows_log_20200820.4.-.wired.txt)

**Comment by mika-n** [comment]
@jekyllgrim  I guess you accidentally named those logfiles vice-versa (wireless vs wired). Anyway, looks like you haven't properly paired the DS4 bluetooth with the PC because the PC does not list the BT device at all (if WinOS doesn't use the BT device then DS4Windows app cannot use it).

Do you see the "Wireless Controller" in WinOS bluetooth devices? When DS4Windows app is NOT running then what do you see in JOY.CPL controlPanel gamepad applet? (you can run JOY.CPL cmd to quickly open the gamepad controlPanel applet).

If you have paired the DS4 BT with PC then another potential issue could be HidGuardian. Have you installed HidGuardian device driver tool, but for some reason DS4Windows app is not whitelisted there and therefore DS4Windows app cannot see the gamepad)?

**Comment by jekyllgrim** [comment]
@mika-n I might've messed up the renaming, whoops.

Anyway, yes, Windows can see the device. I performed the pairing as per instructions, and a Wireless Controller is listed under Bluetooth & other devices and is marked as Connected. Light bar emits a stable blue light. Also, according to the comments from the buyers, that specific dongle I bought should be compatible with DS4 without issues.

I've not installed HidGuardian.

Two things I've noticed. When I turn on DS4, no "game controllers" appear in the Device Manager's HID section. I'm not sure it's supposed to be this way.
Another thing is, no matter how many times I hit install VigEmBus, DS4Windows keeps telling me it's not installed. I checked the list of apps in my system, and it actually is. Not sure if these are related to my bluetooth issue.

**Comment by viproq8** [comment]
@mika-n I have the same problem as @jekyllgrim but I see Wireless Controller in devices and when I test on the webpage it is working.
the gamepad is a 3rd party DS4 V2 called Pictek controller
it is recognized by windows but the DS4Windows is connecting and disconnecting the device and in device manager, I can see the controller is being installed as Xbox 360 controller 4 times as a 4 different controllers.

sometimes I can see the controller in DS4Windows as 2 devices but there is no input or any response.

while the USB connection is working perfectly.
the first log is Bluetooth
second one is USB

[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/5133570/ds4windows_log.txt)
[ds4windows_log_20200826.0.txt](https://github.com/Ryochan7/DS4Windows/files/5133571/ds4windows_log_20200826.0.txt)

**Comment by mika-n** [comment]
@viproq8   Looks like the 3rd party DS4 gamepad is not fully 100% compatible with genuine DS4 bluetooth communication protocol. The gamepad fails already in gyro calibration routine and it is usual symptom in fake/wanna-be DS4 gamepads over BT. Those often work in PC just fine over USB, but BT is problematic.

```
2020-08-26 21:55:09.7874|INFO|DEBUG: RefreshCalibration. getCalibrationData and DS4odeSwitch. conType=BT  calibDataType=5
2020-08-26 21:55:09.8188|INFO|DEBUG: RefreshCalibration. ERROR. readFeatureData failed. conType=BT dataType=5 LastErrorCode=0
2020-08-26 21:55:09.9283|INFO|DEBUG: performDs4Input. WARNING. D0:27:98:25:37:5F crc32 check of BT input packet failed. btInputReport type0=1  type2=128
```

Could be that it is possible to make those copies to work over BT, but someone with an actual hardware should debug the gamepad and see what is different in BT protocol compared to original DS4 gamepads.

The debug version has DS4WindowsDebug.exe.config configuration file. You could try to tweak there one by one few options:
```
  <!-- Debug_GyroCalibrationType 0=default, 1=feature0x02, 2=feature0x05 -->
  <add key="Debug_GyroCalibrationType"         value="0" />

  <!-- Debug_SendRumbleLightbarDataType 0=default type, 1=Type1_0x05,   2=Type2_0x11 -->
  <!-- Debug_SendRumbleLightbarDataAPI  0=default API,  1=ViaInterrupt, 2=ViaControl -->
  <add key="Debug_SendRumbleLightbarDataType"  value="0" />
  <add key="Debug_SendRumbleLightbarDataAPI"   value="0" />
```

**Comment by viproq8** [comment]
@mika-n any suggestions of what to tweak and what to change?

**Comment by mika-n** [comment]
@viproq8 see the following post: https://github.com/Ryochan7/DS4Windows/issues/1194#issuecomment-682421550
