### ISSUE TITLE
invalid custom bezier curve

### ISSUE THREAD

**Issue by mrcrecker** [Ryochan7/DS4Windows#1442]
**Describe the bug**
Pasted  number from the calculator into the app are not in the valid format, does not recognize the "."

Thank you

**Screenshots**
![2020-08-14_172330](https://user-images.githubusercontent.com/20745761/90266457-50a79300-de54-11ea-9533-667392f0bf2a.jpg)

**Desktop (please complete the following information):**
 - OS: window10 italian
 - DS4Windows Version [ 2.1.5]

**Comment by mika-n** [comment]
Interesting. Just tested this and seems to work here just fine in DS4Windows 2.1.5 version. 

You seem to Italian (maybe) WinOS and regional settings. I have Finnish regional settings here and copy-pasting the custom bezier curve values from the web app back into DS4Windows "custom bezier editbox" fields work fine. I used string 0.72, 0.14, 0.82, 0.12  (ie. period as decimal separator and comma as list separator even when officially Finland uses comma as decimal separator char. The code in DS4Windows expects to see "Americano" decimal format).

What was the string you tried to copy-paste? Make sure there are no hidden special chars in the beginning or at the end of the value. 

What regional setting you have in WinOS? Does it use comma or period as decimal separator char?

**Comment by mrcrecker** [comment]
thank you for your reply, my windows is set to italian region, if i type directly into the app for example 0.7, 0.8, 1.0, 1.0 the app responds with the invalid custom bezier curve and sees the numbers as 7, 8, 10, 10

In italy the decimal separator is the comma, the period is used to group numbers. 

this is my windows settings:
![2020-08-14_182050](https://user-images.githubusercontent.com/20745761/90270776-0d045780-de5b-11ea-96e1-c9d9fbb0c353.jpg)

hope this helps, thank you, ciao!

**Comment by mika-n** [comment]
I did a small fix to how different localization settings are used in custom bezier string value. The fix is not yet in the official release, but you can test it by downloading an updated debug version. This would tell us if the fix really work in your setup also. You can download the debug zip file and extract it into the same folder with DS4Windows app. The debug version re-uses all existing config and profile files.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

**Comment by mrcrecker** [comment]
Thank you very much, i think it is fixed now, no error in the registry log. 

[log.txt](https://github.com/Ryochan7/DS4Windows/files/5077597/log.txt)

have a nice day.

**Comment by mika-n** [comment]
fixed. the next official release should have the fix.
