### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by kalken** [Ryochan7/DS4Windows#145]
Hello! I just wanted to say THANK YOU so much for this awesome program. I´ve had problems to get my ds4 controller working propperly in windows and you really saved the day!

keep up the great work, and know that there are some people out there that really appreciate your work!

/K

**Comment by Ryochan7** [comment]
Thank you for the kind words. I just tried to build upon the work of others like Jays2Kings that have put lot  of work into the source code for this project. I am glad that other people have found these changes useful. For me, this project has been more useful than the alternatives available.

**Comment by QaleQ** [comment]
Hi!
Hope you don't mind me hi-jacking this thread with some questions that I wasn't sure warranted opening a new issue:
1. The reported input delay I get with your release always stays at 4ms no matter what polling rate I pick. (I'm saving profile and even restarting the application after making changes to it) But the official version gives me delay of 1,4-2ms.
2. Exclusive mode only works for me whenever I connect the controller wirelessly. I have the same problem with the official version, but not with InputMapper. (However, InputMapper gives an error message saying exclusive mode is not working, yet it still does.) I've tried rebooting and restarting the application all variants of having the setting on/off and controller connect/disconnected. Just does not seem to want to work.
3. Is the information message you get when hovering over "Quick Charge" in settings misspelled? "Auto-Disable BT when 'conencting' to USB"? Was gonna make an issue about this until I saw https://github.com/Jays2Kings/DS4Windows/blob/jay/DS4Windows/Properties/Resources.Designer.cs#L1431 , where the same appearent typo appears again. But the phrasing of that sentence makes it seem like it's not copy/pasted, making me hesitatant.

If you'd like me to make separate issues for any of these things, and/or provide you with more info about my system etc., let me know.

And ofcourse, thank you for keeping this tool alive!

**Comment by Supa-Troopa** [comment]
Heya. Dunno about 2 or 3, but for question №1 — go to your chosen profile, and find option BT Poll Rate, on Controls tab. Set it to Max, or 1000 MHz, and you'll get your lesser input delay back.

**Comment by Ryochan7** [comment]
1. The setting should take affect after saving a profile if you are using a Bluetooth connection. That setting only affects controllers connected via Bluetooth. USB controllers should always have an input delay around 4 ms and Sony dongle connections should give around an 8 ms input delay.

2. The current exclusive mode hack has always been a problem. The only decent solution at this point is to use HidGuardian. You have to install HidGuardian and manage the AffectedDevices list yourself. The necessary whitelist file needed by HidGuardian is written by DS4Windows if you run it as the admin so HidGuardian will give access to hidden devices.

3. I have never edited those strings. As long as no major problem occurs when editing that resource then that typo should be corrected; I can never be too sure what minor changes might end up causing input lag problems.

**Comment by QaleQ** [comment]
Thanks for the response.

1. Seems counter intuitive that you should have less input delay while wireless as opposed to wired :p However the BT poll rate setting just does not have any effect for me (no matter if I set it higher or lower than the default 250Hz), and my input delay on the official release of DS4Windows is always lower than what I get using your release.

2. I actually found a decent fix for this. With DS4Windows running as admin (haven't verified that this is necessary. Just a meassure I always take); Go to Device Manager > Human Interface Devices and disable/re-enable the first "HID-compliant game controller" related to your controller. The seemed to permanently fix it at first.

But I found that there's one instance that breaks it. This is if your controller is connected via BT, and then you connect your USB cable without disconnecting your BT connection first. Device Manager shows your controller as 3 separate HID devices at this point, and exclusive mode breaks until you disconnect your controller from either it's BT connection, or its USB connection, and then stop/start DS4Windows.

Using "Disconnect from BT when Stopping" option, in conjuction with always stopping DS4Windows before connecting your USB cable when your controller needs charging, seems to be the best option provided. Maybe it's possible to trigger a disconnect of the controllers BT connection when it's connected to USB?

3. Well, it's a minor typo in a relatively obscure place. Really not a major issue :)

**Comment by Ryochan7** [comment]
The Jays2Kings builds specify in the output report to have the DS4 use the fastest poll rate the hardware is capable of; that speed would fluctuate around 1.25 ms. Later on, I stumbled upon the portion of the output report that allowed the poll rate to be changed. After play tests, it seemed like overall XInput performance was better when using a more conservative poll rate like 4 ms. That is why 4 ms is the default poll rate in my builds. I should test that assumption again at some point.

Plugging in a controller via USB while using a Bluetooth connection should lead to two devices being seen by Windows. DS4Windows attempts to hide the USB HID device and keep a reference to it. The Quick Charge setting can be used if you want the program to disconnect the Bluetooth device and use the USB HID device instead.

The typo has been corrected.

**Comment by Ryochan7** [comment]
I tried out the poll rate setting last night and my original findings still hold up. XInput performance is worse when the poll rate is set to max compared to 4 ms. However, performance when using a pure KB+M mapping with no virtual XInput controller plugged in is much better when the max poll rate setting is used compared to using a 4 ms setting. There does seem to be an issue with ScpVBus rather than DS4Windows.

**Comment by QaleQ** [comment]
Oh, right. Must've been so focused on the typo in "Quick Charge"'s description that I didn't register what it actually did, haha. Works like a charm now. Can change connectivity any way I want, and exclusive mode always works. Thanks!

I see, so I don't need to care about the fact that I can't get it lower than 4 ms. That's interesting!
