### ISSUE TITLE
DS4 and Nacon controller

### ISSUE THREAD

**Issue by LockDw** [Ryochan7/DS4Windows#1452]
I bought the ps4 controller from nacon, the one with the cable, but DS4 does not detect the connection, so I wanted to ask: DS4 does not support the nacon controller?

**Comment by mika-n** [comment]
See this
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

And this
https://github.com/Ryochan7/DS4Windows/issues/1196

**Comment by mika-n** [comment]
closed because of inactivity of the original poster/lack of information.
