### ISSUE TITLE
I always get an error when re-opening DS4Windows via a shortcut (since 2.0.0)

### ISSUE THREAD

**Issue by CarissaIsWierd** [Ryochan7/DS4Windows#1462]
Similar to [Issue #417](https://github.com/Ryochan7/DS4Windows/issues/417) that was fixed two years ago, I'm trying to re-open DS4Windows with a shortcut or even the .exe file itself, but it gives an error every time. I can close the popup and everything's fine, but it's a bit annoying. Re-opening by double clicking the system tray icon doesn't give an error. (I'm way late in reporting this, hoping it'd get noticed eventually!)

> Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	DS4Windows.exe
  Problem Signature 02:	2.1.5.0
  Problem Signature 03:	85f60c0f
  Problem Signature 04:	DS4Windows
  Problem Signature 05:	2.1.5.0
  Problem Signature 06:	85f60c0f
  Problem Signature 07:	5a2
  Problem Signature 08:	8
  Problem Signature 09:	System.NullReferenceException
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	4e05
  Additional Information 2:	4e0524138763bdde474bded732409b2f
  Additional Information 3:	eecf
  Additional Information 4:	eecf6e61ec2c5b6faef9056efdc7e736

(I'm on Windows 7 x64, by the way.)

**Comment by mika-n** [comment]
See the "Read this before posting a new issue ticket" pinned thread. Please provide the information listed there (logfile mainly in this case).

**Comment by CarissaIsWierd** [comment]
> 08/25/2020 11:16:56: DS4Windows version 2.1.5
08/25/2020 11:16:56: OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
08/25/2020 11:16:56: OS Product Name: Windows 7 Professional
08/25/2020 11:16:56: OS Release ID: 
08/25/2020 11:16:56: System Architecture: x64
08/25/2020 11:16:56: Running as Admin
08/25/2020 11:16:56: Starting...
08/25/2020 11:16:56: Connection to ViGEmBus 1.14.3.0 established
08/25/2020 11:16:56: Searching for controllers...
08/25/2020 11:16:56: Using Exclusive Mode
08/25/2020 11:16:56: Found Controller: 1C:96:5A:05:72:07 (USB) (DS4 v.1)
08/25/2020 11:16:56: Plugging in virtual X360 Controller
08/25/2020 11:16:56: Associate X360 Controller for input DS4 #1
08/25/2020 11:16:56: Controller 1 is using Profile "Default"

**Comment by mika-n** [comment]
Hmm.... Nothing weird in the logfile. It means that the exception was to relayed to DS4Windows .NET code layer. And this means that some WinOS level service or API method threw the exception.

Anyway. Here shortcut to DS4Windows app seems to be working fine. The shortcut launches the app if it is not yet running in background. If the app is already in background (hidden in toolbar) then clicking the shortcut brings up the DS4Windows app window just fine.

Must be some Win7 issue or PC setup specific thing. At least the ViGem driver you have seems to be ancient 1.14.3.0 (please note that the auto-update of DS4Windows does not update ViGem device driver). Try updating to the latest .NET framework and ViGem driver versions. 
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#link-list

**Comment by Ryochan7** [comment]
I'm pretty sure this issue has been fixed with commit 5b4546968bd4e2318e7bf553227e09ed9a11ba5a. There was no log holder when launching a second instance. The application shutdown of the second instance would crash when it tried to access that object. The log file would correspond to the first instance as no log is made for the temporary second instance.

**Comment by Ryochan7** [comment]
I would hope to get a new release out sometime soon.

**Comment by Ryochan7** [comment]
Version 2.1.6 is now out.

https://github.com/Ryochan7/DS4Windows/releases/tag/v2.1.6
