### ISSUE TITLE
Rotation for SixAxis

### ISSUE THREAD

**Issue by Casqade** [Ryochan7/DS4Windows#1463]
Both sticks have a 'Rotation' setting which compensate thumb shifting. 
Is it possible to implement similar setting for SixAxis? 

One of the use cases for this feature would be using gyro as a flight stick without weird hands positioning. Since zero axis values expect the controller to be facing upwards with USB port pointed forward - it is not possible to hold gamepad as a racing wheel and use Z axis simultaneously. 
But rotating the axis by 45-90 degrees would allow that. 

P.S.: it depends on how accurately DS4 gyro reads upwards-pointed transition. I think with 45-degree axis rotation and proper Max Zone setting adjusted the readings should remain stable.

**Comment by isaakfawkes** [comment]
I reaally like this idea.

**Comment by Ryochan7** [comment]
When you hold the controller with the USB port pointing at the ceiling, once you rotate the controller around the X axis then the Z axis value will change as well. Changing the neutral Z axis value is not going to work around that problem. It is a fundamental limitation of the accelerometer. Trying to use the Y axis value doesn't fair too well either depending on the current position of the controller.

People have mentioned this idea before but it does not seem feasible with using the accelerometer nor the gyro.
