### ISSUE TITLE
buttons switching between xbox and ps

### ISSUE THREAD

**Issue by andersonbruno02** [Ryochan7/DS4Windows#1466]
while I'm playing playing falling guys on steam, the game shows ps buttons like triangle, ball, square x.
but keep switching for xbox buttons like A B X Y.
what im missing?

**Comment by Masamune3210** [comment]
Seems Fall Guys has native support for the DS4, so it's seeing both sets of inputs. Either stop DS4Windows and use the native support, or Hide the DS4 and use DS4Windows

**Comment by mika-n** [comment]
https://github.com/Ryochan7/DS4Windows/issues/1196

https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues
