### ISSUE TITLE
Issue: An Item has already been added with the same key. 

### ISSUE THREAD

**Issue by Itsfurqan1337** [Ryochan7/DS4Windows#1467]
**Describe the bug**
The bug is caused whenever i connect my Controller (USB Connection and i dont know about BT Connection) 
This causes the ingame controls to be all over the place and jumbled. 

**To Reproduce**
Just connecting the controller to the DS4 Will give this error in a red.

**Expected behavior**
It will cause my ingame controls to be jumbled and shuffled.

**Screenshots**
Sorry, I couldn't take Screenshots as I had already rolled back to the previous version of DS4Windows.

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: Windows 10 Pro Ver 2004
 - DS4Windows Version 2.1.6

**Additional context**
By installing the Version 2.1.5 which i initially had, it fixed.

**Comment by mika-n** [comment]
"ingame controls"? Or button placement in DS4Windows button mapping screen in DS4Windows profile editor?
And do you mean that a game shows "an item has already been added with the same key" message?

If you mean that some game is showing this msg then I believe you are having "double controller" issue.
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

**Comment by mika-n** [comment]
closed as inactive
