### ISSUE TITLE
crash after update to version 2.1.6

### ISSUE THREAD

**Issue by wergio** [Ryochan7/DS4Windows#1468]
after update to version 2.1.6 DS4Windows is always crashing when connectig after pressing PS button. I tryed updating HidGuardian and ViGEmBus to latest, but nothing changed 

in log I see this error:
Thread App Crashed with message Index (zero based) must be greater than or equal to zero and less than the size of the argument list.

full log:
[ds4windows_log_20200829.3.txt](https://github.com/Ryochan7/DS4Windows/files/5145100/ds4windows_log_20200829.3.txt)

**Comment by mika-n** [comment]
Yes. Seems to be problem in the new "show battery at connection time" change WHEN the default profile is not found for some reason at connection time.

Localized reasource string "NotUsingProfile" has `"Controller {0} is not using a profile. Battery level is {2}%"` value, but the code supplies only two input parameters: 
`string prolog = string.Format(DS4WinWPF.Properties.Resources.NotUsingProfile, (ind + 1).ToString(), $"{device.Battery}");
`
The "Battery level is {2}" should be "Battery level is {1}" in this NotUsingProfile resource string.

However, what I don't understand is why default profile file (xml file in settings folder) is not found there?
What do you see in "%APPDATA%\DS4Windows\Profiles.xml" file and in Controller1/Controller2/Controller3/Controlle4 options?
There should be a name of the default profile and a XML file like that should be found from Profiles subfolder.

**Comment by wergio** [comment]
i solved deleting "%APPDATA%\DS4Windows" and letting the program recreate conf file. thanks

**Comment by Ryochan7** [comment]
Version 2.1.7 fixes the initial problem.
