### ISSUE TITLE
SnakeByte GamePad 4S not recognized by DS4Windows

### ISSUE THREAD

**Issue by boct1584** [Ryochan7/DS4Windows#1471]
This one: https://www.amazon.com/Snakebyte-Gamepad-PlayStation-Controller-Nostalgic/dp/B01MCRTVCT

It had a firmware update to the controller for compatibility with PS4 firmware 6.20 but DS4Windows still does not recognize after this update.

**Comment by mika-n** [comment]
Please read the pinned "Please read this before posting a new ticket" post first and provide necessary information.
And take a look at the debug version tip explained in the pinned post.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

**Comment by boct1584** [comment]
My bad, I'll provide the info tonight. Gotta go to work for now.

**Comment by boct1584** [comment]
The debug build detected the controller immediately! Here's the debug log: https://www.dropbox.com/s/a1i2ury6kt9q60h/DS4Windows%20Debug%20Log%20Snakebyte%204S.txt?dl=0

Would you rather I dump the full text in a comment? No problem if so, just don't want to spam.

**Comment by mika-n** [comment]
Added support to SnakeByte Game:Pad 4S (wired) gamepad. Based on the logfile it looks like the pad doesn't have gyro or lightbar and it always reports 0% battery value (well, wired pad doesn't need a battery). Therefore DS4Windows app won't try to calibrate gyro and uses a dummy 99% battery value (to avoid "low battery" warnings).
The next official release should have the support, so keep eye on releases web page.

If you encounter some issues with the existing debug version then please report those findings here. This ticket will be closed in few days if things seem to work fine there. Test touchpad (map touchpad to mouse in DS4Windows app), test both rumble motors and all buttons and sticks. Are rumble and touchpad working fine?

**Comment by boct1584** [comment]
Touchpad works well, rumble seems fine too!

Also worth noting that, as I mentioned, out-of-the-box mine needed a firmware update for PS4 firmware 6.20. I did that before attempting to make it work with DS4Windows.

**Comment by mika-n** [comment]
closed as "the next release includes the pad suppport"
