### ISSUE TITLE
Upgrade to Win10 2004 broke startup

### ISSUE THREAD

**Issue by testunde** [Ryochan7/DS4Windows#1475]
Hey all,
I just updated my Windows 10 to the 2004 build and DS4WIndows just does not start up. The process is there (also an empty taskbar icon) and ends shortly after. Yes, I reinstalled HIDGuardian (#1348) already but without success.
I used the 2.1.7 Version before on the 1909 build without any problems. Also, I have no MSI Afterburner installed. I had the "run at startup" mark activated (it also still tries to run an instance on Win boot).
The DS4Windows installation folder is on a random folder on a different drive. Had no problems with this configurations so far.
Its basically the same error as #993, however my TaskScheduler service is running. I couldn't get anything working out of the named issue. Am I overseeing something?

**What I tried**
- clean installation including an empty %appdata%/DS4Windows folder
- reinstalling ViGem and HIDGuarding drivers plus VisualC++
- run DS4Windows as administrator
- WMI, WMS and TaskScheduler services are running

**To Reproduce**
1. Update Win 10 from 1909 to 2004
2. Start DS4Windows (auto-startup on boot or manually)
3. Process shortly opens up but ends shortly after

**Expected behavior**
DS4Windows starting up (window or task bar icon)

**Desktop**
 - OS: Windows 10 Home x64 Build 2004
 - DS4Windows Version: 2.1.7
 - .NET Version: 4.8.04084

**Logs**
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/5155845/ds4windows_log.txt)

**Comment by mika-n** [comment]
Hmmm... The exception is coming from WinOS API layer and COM engine and not from DS4Windows app code itself.   Well, DS4Windows app could have an exception handler there to trap the exception and then decide what to do when DS4Windows task was not found or COM engine threw an excepton.

How about if you try to download and update (or re-install it) to the latest .NET Framework libraries now when you have updated WinOS?
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#link-list

**Comment by Ryochan7** [comment]
The exception is thrown by the TaskSchulder code and not from anything done by the DS4Windows code itself. Not sure why the FindTask routine would be failing like this unless maybe you would have the Task Scheduler service disabled. I tend to avoid adding exception handling unless it is deemed absolutely necessary.

**Comment by testunde** [comment]
> How about if you try to download and update (or re-install it) to the latest .NET Framework libraries now when you have updated WinOS?

Well I already have the newest .NET version (4.8) installed, so there is no update option and since it is integrated into the OS itself there is no way to uninstall/reinstall it. The installer does not do anything by saying "already up to date, done". I ended up unchecking and then rechecking the .NET 4.8 tickbox in *programs and features*, but no luck.


> The exception is thrown by the TaskSchulder code and not from anything done by the DS4Windows code itself. Not sure why the FindTask routine would be failing like this unless maybe you would have the Task Scheduler service disabled.

TaskScheduler service is running. I can't even start/restart/stop this service (probably due to missing permissions).


Well, would be good if a major Windows update would run smoothly 😂 :(

**Comment by mika-n** [comment]
Try to run the updated debug version (updated few mins ago). It has an additional "eat all exceptions and just report it in logfile" addition in the code part using TaskService (=WinOS TaskScheduler) API objects. It means that RunAsTask feature doesn't work if this TaskService error msg is shown in a logfile but at least you should be able to start the app and use it without taskServices.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

Please let me know how this test run goes and if it works then maybe this "one liner" workaround should be added to the official version in case other people run in to the same issue (well, in the past few people has run into the issue and usually it has been TaskSchduler corruption or permission issue).

**Comment by testunde** [comment]
Yea now it starts. Log is below. I even can run the task if I change the filename accordingly in *task.bat* (which then works also on Win boot). So once the Task is registered in the TaskScheduler the *RunAsTask* feature does work in the end, but you can't (de)activate it, right?
```
2020-09-01 16:47:15.9754|INFO|DS4Windows version 2.1.7
2020-09-01 16:47:15.9854|INFO|DS4Windows exe file: DS4WindowsDebug.exe
2020-09-01 16:47:15.9854|INFO|OS Version: Microsoft Windows NT 10.0.19041.0
2020-09-01 16:47:15.9854|INFO|OS Product Name: Windows 10 Home
2020-09-01 16:47:15.9854|INFO|OS Release ID: 2004
2020-09-01 16:47:15.9854|INFO|System Architecture: x64
2020-09-01 16:47:15.9854|INFO|Logger created
2020-09-01 16:47:18.1914|WARN|Error in TaskService. RunAsTask feature doesn't work. Check WinOS TaskScheduler service functionality. An internal error occurred. (Exception from HRESULT: 0x8007054F)
2020-09-01 16:47:18.2364|WARN|Error in TaskService. RunAsTask feature doesn't work. Check WinOS TaskScheduler service functionality. An internal error occurred. (Exception from HRESULT: 0x8007054F)
2020-09-01 16:47:19.2883|INFO|Running as User
2020-09-01 16:47:19.3003|INFO|HidGuardian in use. Launching HidGuardHelper.
2020-09-01 16:47:22.3920|INFO|Starting...
2020-09-01 16:47:22.3920|INFO|Connection to ViGEmBus 1.16.112.0 established
2020-09-01 16:47:22.3920|INFO|Searching for controllers...
2020-09-01 16:47:22.3920|INFO|Using Shared Mode
2020-09-01 16:47:22.4320|INFO|DEBUG: EnumerateDS4. HID#1 Path=\\?\hid#saitekkeyboard#2&2bfc56e6&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd  Description=HID Keyboard Device  VID=0x06A3  PID=0x5041  Usage=0x6  Version=0x1
...
2020-09-01 16:47:22.4320|INFO|DEBUG: EnumerateDS4. HID#20 Path=\\?\hid#saitekhotkeys#2&3437057c&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant consumer control device  VID=0x06A3  PID=0x5081  Usage=0x1  Version=0x1
2020-09-01 16:47:22.4320|INFO|DEBUG: findControllers. Found 0 possible devices
```

**Comment by mika-n** [comment]
Submitted a workaround to the official release, so keep eye on the new releases. Meanwhile continue to use the debug version (unless the bug was gone when you managed to create the task or untick "RunAsTask" option).

If the TAskService doesn't work in your WinOS setup then you cannot activate/deactivate runAsTask functionality (or the status of the GUI does not show the true status because you can always create those taskScheduler jobs manually outside of DS4Widnows app or using other name than DS4Windows).

**Comment by testunde** [comment]
Alright, thank you for your time!

Should I come across a solution to the WinOS TaskScheduler (because it seems somewhat corrupted and I didn't find any general fix yet, other than probably reinstalling Windows itself), I will post it here.

**Comment by testunde** [comment]
Okay, so I managed to fix the TaskScheduler issue. For those who continue reading: **DO NOT EDIT YOUR REGISTRY IF YOU DO NOT KNOW WHAT YOU ARE DOING**. You are on your own when doing these edits on your system and I do not take any credits on any damage which could occur. You have been warned.

So I found [this blog post](https://thegeekpage.com/fix-error-task-scheduler-service-is-not-available-in-windows-10-solved/). The problem was fixed by doing part 3 "fix the registry". What I did **effectively**: I made a backup of the Tree-folder (export the registry keys); delete each Key-folder in the Tree folder (as I could not simply rename it); started Task Scheduler; re-imported these keys; restarted Task Scheduler. Now once its window opens I got an Error for each Task which was "not found anymore". I deleted these tasks manually from the registry (they were not listed in the Task folder anymore anyway), and opened all these Programs which were associated with it so I can re-register the Tasks. Now everything is like before and I can open The Task Scheduler without errors. And most importantly, DS4Windows' *RunAsTask* feature works like intended. I suspect that the Win 1909 to 2004 failed to translate these Task in some way.

Still, thanks @mika-n for looking in it :)

**Comment by pleasejustgo** [comment]
If I do a fresh install of windows 10 2004, should everything run fine?

**Comment by mika-n** [comment]
> If I do a fresh install of windows 10 2004, should everything run fine?

Is this a trick question? The answer is "definitely maybe".

**Comment by pleasejustgo** [comment]
How is that a trick question?? The author wrote that upgrading to 2004 caused issues. But what if you already have 2004 straight away. It's a reasonable question.

**Comment by mika-n** [comment]
Win updates can always break something no matter how it works in some other PC setups. If you are preparing to play in The International finals then don't update WinOS just before the finals, otherwise feel free to update and hope nothing breaks. Just like in the case of the original poster, DS4Windows app works with the latest WinOS update but something in WinOS level may be broken and you have to prepare to fix it (things not directly related to DS4Windows app itself).
