### ISSUE TITLE
Power off Controller

### ISSUE THREAD

**Issue by ThePapaw** [Ryochan7/DS4Windows#1478]
There was an option to turn controller off after a certain amount of time, say 5 minutes. Has that been removed? If so, any chance it can return? I sure am missing it not turning off controller not being used

**Comment by mika-n** [comment]
Profile editor has "Idle timeout for BT connected gamepad" option (edit a profile for editing and take a look at Other tab page).

**Comment by ThePapaw** [comment]
Thank so much, found it
