### ISSUE TITLE
Binding Left Stick axises onto D-Pad buttons no longer seems to work

### ISSUE THREAD

**Issue by TheKins** [Ryochan7/DS4Windows#148]
...or at least, is very very weird about whether it wants to work or not.

I use several older emulators like WinVICE that are very insistent on using the Left Stick for movement, where I'd prefer to use the D-Pad, so I use a config that binds the Left Stick actions to the D-Pad. This worked all well and good until relatively recently (I don't recall an exact date or version, sorry) where it no longer seems to do anything. I suspect I'm missing some new option that has me define how far the "stick" is pushed when I use the D-Pad or something, but I haven't found anything. It might actually be a bug, though, I dunno.

Any ideas?

**Comment by Ryochan7** [comment]
I just tried mapping left stick axes to the d-pad and it worked fine for me.

**Comment by TheKins** [comment]
Weird. I just created a new profile that did it, and using the Windows Controller properties window to test, only the left and right buttons worked, and only briefly in a flickery manner before just flat out giving up.

**Comment by Ryochan7** [comment]
I was using HTML5 Gamepad Tester before. Testing in Windows Controller properties is no different though. It is working as expected. Which version of DS4Windows are you using?

**Comment by TheKins** [comment]
Version 1.4.99.

I think I was able to find a solution though - it turns out the real left stick's input was "overriding" the d-pad's left stick inputs, and I needed to apply a deadzone to the left stick to fix this.

Weird, but all's well that ends well...

**Comment by Ryochan7** [comment]
That would explain it. I almost always use a deadzone on both sticks set at 9%.
