### ISSUE TITLE
DS4 not recognizing Nacon ps4 controller

### ISSUE THREAD

**Issue by otDan** [Ryochan7/DS4Windows#1483]
DS4 seems to not recognize the Nacon ps4 controller. Every other ps4 controller I have gets recognized, it's just this one that doesn't. This is the model: PS4OFCPADRED

**Comment by mika-n** [comment]
Take a look at the "Read this before posting a new issue ticket" pinned thread. You provided hardly any information needed to speculate the question.

the "Read this before" has a link to troubleshooting page and there is a special section about not-recognized gamepads.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

**Comment by mika-n** [comment]
@otDan Did you test the debug version? There is not much we can do if you don't do your part of the debugging.

**Comment by mika-n** [comment]
closed as "inactive ticket / not enough information / original poster failed to follow the instructions in ReadThisFirst post"
