### ISSUE TITLE
Lightbar flashing, stop working

### ISSUE THREAD

**Issue by Santt0** [Ryochan7/DS4Windows#1485]
The option flash lightbar at high latency is desactivated, and there is no lag(4ms), but when i change pages in the windows explorer or i open the internet browser, etc the lightbar stop working for a few seconds but the joystick is still working fine. The version of the ds4 is v1.0, is conected via BT, the problem still happening when i connect the joystick via usb.
There is a fix to this bug? I tried other versions but stills the same.
In my other joystick(ds4 V2.0) i dont have this issue.
I am in the latest version of windows and ds4, with vigem reinstalled.
![DS4Windows 9_8_2020 10_58_55 PM](https://user-images.githubusercontent.com/54033546/92545642-f4ebe200-f226-11ea-8d93-ab9d48f626e0.png)
![DS4Windows 9_8_2020 10_59_12 PM](https://user-images.githubusercontent.com/54033546/92545649-f61d0f00-f226-11ea-8d76-d01d8fea0193.png)

**Comment by mika-n** [comment]
what do you mean by "lightbar stops working"?  It goes to a black color or game is unable to change the color? Technically there are no lightbar on/off switch in DS4 gamepad, the color can be set black but the lightbar is still "on" even when it shows a black color.

Logfiles have anything strange?

Anyway. Sounds like a DS4 pad issue. Thesedays there are zillions of fake Chinese copies of DS4 gamepad which look like genuine DS4 pad, but are actually fake copies. The clear sign of this is a pad with DS4v1 revision1 hardware ID (DS4windows logfile shows this) with gamepads purchased in recent years. Sony itself haven't manufactured ds4v1 gamepads in 4-5 years.

Those fake DS4 pads often have problems in BT communication, but may work just fine over USB. But your mileage may vary...

**Comment by Santt0** [comment]
The ds4 gamepad is old and original, but could be averiated or a windows problem. Because when i connect the joystick without the program it works but the lightbar dont emmit light. Time ago the lightbar work just fine, but i dont remember when it start to fail.
Now I dont think that the problem its provenient from the program

**Comment by mika-n** [comment]
Indeed sounds like a DS4 hardware issue (assuming DS4Windows options in Ligthbar tab page are set correctly). Closed as "hardware issue".
