### ISSUE TITLE
[Bug] Gyro Toggle function incostistent

### ISSUE THREAD

**Issue by alpharou** [Ryochan7/DS4Windows#1486]
I have my profiles configured so that I can toggle between xInput and Mouse control.

The Gyro Mouse Control setup like so:

Gyro turns off temporarily when pressing the selected button (In my case X button)
Toggle ticked off

Everything works correctly at boot, first time a controller is connected.

When you disconnect and reconnect the controller while in Gyro Mouse Control Profile, so that said profile gets loaded first, the selected button acts as a toggle until you switch to another profile and back to Mouse Control.

Closing and Reopening DS4 reestablishes the issue, first conection no problem, any more and the toggle acts until reload of the Profile.

**Comment by Ryochan7** [comment]
No info. Even the info requested in the issue template would have been of some use. There is nothing to work with.

**Comment by alpharou** [comment]
Updated the bug report.
