### ISSUE TITLE
[Bug] Special actions "load profile" causes wrong profile to load upon reconnect

### ISSUE THREAD

**Issue by alpharou** [Ryochan7/DS4Windows#1488]
**Describe the bug**
Gyro setting "Toggle" always applies next time controller connects, if the profile has previously been loaded by an special action.

**To Reproduce**
1. Create two profiles, one with Gyro control, one without it:
![Captura de pantalla 2020-09-11 224935](https://user-images.githubusercontent.com/8113318/92972409-7f7c4d80-f482-11ea-939d-bd4b153edfa7.png)

In this case, Default has Gyro on ( Set a button trigger, Toggle ticked off), ControllerInput has Gyro off.
![Captura de pantalla 2020-09-11 224916](https://user-images.githubusercontent.com/8113318/92972458-9884fe80-f482-11ea-9a5f-803b298255f3.png)

2. Create a special action that loads "Default" (Gyro profile) from the other one.
![Captura de pantalla 2020-09-11 225322](https://user-images.githubusercontent.com/8113318/92972654-df72f400-f482-11ea-85f9-4f733f2bc56b.png)
![Captura de pantalla 2020-09-11 225218](https://user-images.githubusercontent.com/8113318/92972636-d3873200-f482-11ea-9569-37336aeb20d2.png)

3. Load the non-Gyro profile.
![Captura de pantalla 2020-09-11 225420](https://user-images.githubusercontent.com/8113318/92972741-0af5de80-f483-11ea-97b6-6e6bd3454662.png)

Then trigger the special action to switch to the gyro (everything works as intended for now).
![Captura de pantalla 2020-09-11 225439](https://user-images.githubusercontent.com/8113318/92972966-7dff5500-f483-11ea-8ebd-b813db2380f1.png)

4. Disconnect the controller while the newly loaded Gyro profile is active.
![Captura de pantalla 2020-09-11 225456](https://user-images.githubusercontent.com/8113318/92972996-8bb4da80-f483-11ea-9c60-53eea616015a.png)

5. (Issue) Reconnect the controller.
![Captura de pantalla 2020-09-11 225521](https://user-images.githubusercontent.com/8113318/92973198-efd79e80-f483-11ea-8bcf-570519408aaf.png)
Take a look at the name of the profile (It should say Default, but instead shows ControllerInput, while in fact the controller acts as configured on Default. Even the light shows up correctly).
At this moment, everything but the Gyro Toggle works as configured in profile "Default".

6. Switching profile again, manually or by special action loads every profile parameter correctly, until you once again disconnect and reconnect the controller.

**Expected behavior**
Switching profiles by special actions should update GUI correctly.
Switched profiles should load every parameter correctly next time controller reconnects.

**Desktop:**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2E)
 - OS: Windows HOME NT 10.0.18363.0 Release 1909 x64
 - DS4Windows Version 2.1.9
 - ViGEmBus Version 1.16.112.0
 - Running as Admin

**Comment by Ryochan7** [comment]
I have been trying to reproduce this problem but the Toggle option works fine on my end under those conditions.

**Comment by alpharou** [comment]
I have three machines and two v2 controllers, and can recreate the issue just by turning off and back on every controller, on any machine. 2/3 times the toggle function gets turned on for no apparent reason.

So, given that you cannot recreate it, I'll try to pinpoint any other clue by creating new installations of DS4, new profiles and settings, and will update this post.

Do you have any other advice on how to hopefully find the problem?

**Comment by alpharou** [comment]
Updated the issue.

**Comment by Ryochan7** [comment]
That is a completely separate issue. The Load Profile Special action uses the temp profile association like Auto Profiles do. However, it looks like that association is not properly removed on device disconnect. When a device reconnects, it will actually re-load the last loaded temp profile rather than the main profile selected in the controller listing.

**Comment by Ryochan7** [comment]
Also, the temp profile association is meant to not update the selected profile in the controller listing. Not sure about the original justification for that behavior.

**Comment by alpharou** [comment]
So, if you manually set profile "Default"active, then make use of two special actions to switch to another profile and back to "Default", the issue still persists because the profile that gets loaded is a temp profile of the "Default" one, right?

So the solution you propose, to load the initially selected profile upon reconnect, might as well solve this issue. But I still have to know why in the process of switching between temp and solid profiles the toggle feature does not get ignored, but when loading the temp back in it is ignored and defaults to 1.

Maybe the load profile action does not actually carry the toggle parameter, but it does not overwrite the value of the profile it got loaded from, so it works until loading it from scratch.
