### ISSUE TITLE
Option/Start Button not working

### ISSUE THREAD

**Issue by Itsfurqan1337** [Ryochan7/DS4Windows#1489]
The Start/Option Button doesnt work on 2.1.6 to 2.1.10 version of DS4Windows whenever I press the corresponding button on DS4.
The Start Button works correctly in Version 2.1.5 of the DS4Windows.

**Comment by mika-n** [comment]
"Options" button in DS4 gamepad seems to work just fine here with the latest 2.1.10 version.  Maybe you have something conflicting in a profile settings? Try creating a new empty profile and see if all buttons work with default mappings.

**Comment by Ryochan7** [comment]
This is false. The problem has to be your profile.

**Comment by mika-n** [comment]
closed as in-active ticket (no comments from the original poster) and here things seem to work just fine. maybe a local profile setup issue.
