### ISSUE TITLE
[2.1.10] Touchpad settings are reset to "Use as mouse"

### ISSUE THREAD

**Issue by Ryusennin** [Ryochan7/DS4Windows#1490]
In version 2.1.10, the Touchpad settings (Profiles > Controls tab) are reset to "Use as mouse", and previous bindings/macros defined in "Use as controls" are deleted. For example Right Touch (which I had previously remapped to Start) is defaulted to Left Mouse Button.

Thankfully I regularly make a backup of my custom profiles, but I consider this a serious bug.

**Comment by Ryochan7** [comment]
With no reference profile to work with, there is nothing I can do. I don't experience this type of problem on my end.

**Comment by Ryusennin** [comment]
[XInput [X360].zip](https://github.com/Ryochan7/DS4Windows/files/5214988/XInput.X360.zip)

This is my primary profile, which works in 2.1.9. When upgrading to 2.1.10, the touchpad settings are switched from "use as controls" to "use as mouse" and all bindings (TouchLeft, TouchRight) are reset to mouse buttons.

**Comment by Ryochan7** [comment]
The profile works fine on my end.

**Comment by Ryochan7** [comment]
People really need to start abiding by the issue template. I had to guess my way around the problem. At least it is confirmed now. The test profile index must be wrong.

Key Point: The issue only comes up when bringing up the Profile Editor from the Profiles tab. Hitting Edit from the Controllers list loads the profile just fine.

**Comment by Ryochan7** [comment]
Version 2.1.11 has been released. It includes a fix to this problem.

https://github.com/Ryochan7/DS4Windows/releases/tag/v2.1.11

**Comment by Ryusennin** [comment]
I mentioned I was using the profile editor, but I'll use the issue template next time.

Thanks for the quick fix.

**Comment by Ryusennin** [comment]
[Erratum]

Just tested 2.1.12 and unfortunately the problem (via the **profile editor**) doesn't seem to be fixed. It's not just "Use as mouse" but the whole profile settings which are reset to default values.

(As a side note, I had to dig through the github repo to find that "issue template", which isn't referenced anywhere.)

------------

**Describe the bug:** in 2.1.10 and later, custom profile settings are not loaded when using the profile editor.

**Steps to reproduce the behavior:**

Grab this custom profile: [XInput [X360].zip](https://github.com/Ryochan7/DS4Windows/files/5214988/XInput.X360.zip).
Go to Profiles tab.
Double-click on the custom profile.
All custom values are reset to default.

**Expected behaviour:** Custom values (dead zones, "Use as controls" bindings, etc) should be loaded.

**Screenshots:**

Version 2.1.9 (expected)
![V2 1 09](https://user-images.githubusercontent.com/9519544/93087357-b461ed80-f698-11ea-8bf4-547d0bb2a9dd.png)

Version 2.1.10~2.1.12 (unexpected)
![V2 1 12](https://user-images.githubusercontent.com/9519544/93087370-bb88fb80-f698-11ea-8956-7c61f1a42612.png)

Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
OS: Windows 10 Pro Build 2004
DS4Windows Version: 2.1.12

**Comment by Ryochan7** [comment]
So much for pushing out the 8 controller version at all. I checked for parity with the rejected pull request before pushing out the final version. So many checks missed in both versions. I didn't even care for 8 controller support in the first place.

**Comment by Ryusennin** [comment]
2.1.13 seems to be a-ok. I checked all my custom profiles through the profile editor and at first glance the different settings are correctly loaded in each tab. I tested a few games without any apparent issue.

Thanks again!
