### ISSUE TITLE
latency over 10ms via bluetooth after 20 min gaming

### ISSUE THREAD

**Issue by VovaShtoyka** [Ryochan7/DS4Windows#1491]
Hello guys, my latency first 20 min gaming 3-4ms, but then up to 30-40ms.  My doongle https://www.amazon.com/Bluetooth-Receiver-Keyboards-Controllers-USB-BT400/dp/B00DJ83070/ref=sr_1_9?crid=1AN3QGKR4D5VH&dchild=1&keywords=bluetooth+adapter+for+pc&qid=1600009323&sprefix=Bluetooth+a%2Caps%2C247&sr=8-9

**Comment by mika-n** [comment]
See comments here.
https://github.com/Ryochan7/DS4Windows/issues/1470#issuecomment-691471025
