### ISSUE TITLE
Virus alert in version 2.1.10

### ISSUE THREAD

**Issue by terkloki2332** [Ryochan7/DS4Windows#1492]
Virus alert in version 2.1.10
-
When I tried to update to version 2.1.10 Windows Defender gave me this message.
And when I try to download version 2.1.10 from the repository it automatically deletes the .rar file.
![Ds4windowserror](https://user-images.githubusercontent.com/71241144/93036558-99e73000-f616-11ea-8fdb-8691b5f73a61.png)

**Comment by TunTunaTu** [comment]
Yeah I downloaded the update minutes ago and got this too.

**Comment by pbanj** [comment]
false positive, virustotal shows nothing

**Comment by mika-n** [comment]
Must be a false positive. 
Did you get the warning already from the archive file itself or after you had extracted all files? If you downloaded the RAR archive then how about if you try to download the ZIP archive? Maybe some unfortunate binary signature in the RAR is causing this false alarm.

**Comment by terkloki2332** [comment]
Yeah, I know it was a false positive I thought it was worth to report it since no one reported.
I got the warning before extracting the files, but now I tried downloading again and didn't receive any warning, who knows maybe Windows Defender updated and no longer recognize as a threat.

**Comment by Dave247** [comment]
Seems to be happening again in 2.1.13 which I mentioned in ticket #1494

**Comment by mika-n** [comment]
#1494  duplicated topic. closing this one with a title to older app version.
