### ISSUE TITLE
Not really a bug, but some space saving by not bundling .net files ?!

### ISSUE THREAD

**Issue by escape75** [Ryochan7/DS4Windows#1493]
I have adjusted the DS4Windows.exe.config in the following way, and removed the libs folder and the app runs just fine:

```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6.2" />
  </startup>
</configuration>
```

**Comment by Ryochan7** [comment]
The download progress section of the Welcome Dialog will not run correctly without those extra DLL bindings in place. IIRC, no other portion of the program currently uses the HttpProgress library that requires the extra DLL files.

**Comment by escape75** [comment]
I see, interesting ... not sure if this is connected to that but 'Settings' and 'Changelog' funtion was crashing  as well ...
To fix it I added "Markdown.Xaml.dll" in the main DS4Windows.exe folder and now it works, without the libs folder.

**Comment by escape75** [comment]
I am confirming that without the libs folder, but with Markdown.Xaml.dll in the main folder the download
of ViGEmBus still works, gives progress and then proceeds to the setup stage ... Here's the files I have:

```
01/01/2010  01:00 AM         3,517,952 DS4Windows.exe
01/01/2010  01:00 AM               177 DS4Windows.exe.config
01/01/2010  01:00 AM            45,056 Hardcodet.Wpf.TaskbarNotification.dll
01/01/2010  01:00 AM            13,824 HttpProgress.dll
01/01/2010  01:00 AM            33,280 Markdown.Xaml.dll
01/01/2010  01:00 AM           327,680 Microsoft.Win32.TaskScheduler.dll
01/01/2010  01:00 AM           606,208 Nefarius.ViGEm.Client.dll
01/01/2010  01:00 AM           700,336 Newtonsoft.Json.dll
01/01/2010  01:00 AM               451 NLog.config
01/01/2010  01:00 AM           838,144 NLog.dll
01/01/2010  01:00 AM           101,888 Ookii.Dialogs.Wpf.dll
01/01/2010  01:00 AM            86,016 UtilLibrary.dll
01/01/2010  01:00 AM            80,384 WPFLocalizeExtension.dll
01/01/2010  01:00 AM            31,232 XAMLMarkupExtensions.dll
01/01/2010  01:00 AM         1,162,240 Xceed.Wpf.Toolkit.dll

```

Markdown DLL file was found here in lib folder:
https://www.nuget.org/packages/Markdown.Xaml/
