### ISSUE TITLE
2.1.13 Blocked in Windows Defender 

### ISSUE THREAD

**Issue by Dave247** [Ryochan7/DS4Windows#1494]
Something in the version seems to have triggered something that Windows defender doesn't like. Not a big issue but still wanted to report it. Seems to also be the same detection type as in #1477
_Edit: for reference the definition version at the time was 1.323.1165.0_
![ApplicationFrameHost_2020-09-15_16-31-46](https://user-images.githubusercontent.com/10183015/93174547-813f5d00-f771-11ea-99cb-1e25fa2689fe.png)

**Comment by Dave247** [comment]
Well it looks like I spoke too soon, I get even more warnings when trying to active exclusive mode. Seems like it _really_ doesn't like this version.
![consent_2020-09-15_16-44-48](https://user-images.githubusercontent.com/10183015/93175513-13943080-f773-11ea-9495-0566067e9f5d.png)
![ApplicationFrameHost_2020-09-15_16-45-10](https://user-images.githubusercontent.com/10183015/93175517-15f68a80-f773-11ea-96db-cde4169711f1.png)

**Comment by Dave247** [comment]
I thought to check for a new definition version and turns out the version that just came out (1.323.1194.0) sort of fixed it, it still complains on launch but can be allowed without any further observed issues.
![ApplicationFrameHost_2020-09-15_17-18-39](https://user-images.githubusercontent.com/10183015/93178880-3aa13100-f778-11ea-9413-69a5734f0edd.png)

**Comment by pascalliedtke** [comment]
For me the defender even automatically deletes DS4Windows.exe immediately. Since my Defender settings are company managed, I cannot even change anything about it. 
Meaning that I cannot use DS4Windows at all anymore :(

**Comment by alexthecamel** [comment]
Similar behaviour here, different name for the detected file is concerning. Has been fine up until today's update.
![image](https://user-images.githubusercontent.com/13772499/93190218-ff344180-f73a-11ea-80ea-11cd67041b33.png)

**Comment by TheSOSOGE** [comment]
> Similar behaviour here, different name for the detected file is concerning. Has been fine up until today's update.
> ![image](https://user-images.githubusercontent.com/13772499/93190218-ff344180-f73a-11ea-80ea-11cd67041b33.png)

P much got the same detection

**Comment by raghav-clumio** [comment]
Yeah, got the same detection. Could it be true?

**Comment by Raghav-intrigue** [comment]
Yeah, got the same detection. Could it be true?

**Comment by Raghav-intrigue** [comment]
This looks concerning.

**Comment by Raghav-intrigue** [comment]
Although

**Comment by Ryusennin** [comment]
Windows Defender has become increasingly aggressive over the months, especially against established injectors like Reshade or dgVoodoo. Updates for those applications are systematically flagged as dangerous by Microsoft and Google before getting whitelisted a few hours later.

**Comment by pascalliedtke** [comment]
I could work around the issue by adding the full DS4Windows as an exclusion folder in the Windows Defender. Seems like this is still allowed in my case. 
Open Windows Security -> Virus & Thread Protection -> Virus & Thread Protection Settings -> Manage Settings -> Exclusion -> Add or Remove Exclusions. 
Finally add the folder DS4Windows folder there.

**Comment by RedDevilus** [comment]
![image](https://user-images.githubusercontent.com/24227051/93215722-1852e780-f767-11ea-8812-6306821bd37b.png)
Not sure why it's having a false-positive.

**Comment by Dave247** [comment]
Seems to have gone away today as I'm not seeing anything show up in today's definition version (1.323.1306.0). Not sure if it fixed itself or if MS have approved the submission that I assume Ryochan7 would of uploaded.

I wonder if there's a way to have it so it doesn't keep flagging almost every new version, I don't know if having a digital signature would help but it's probably not worth it for how expensive it is. Another possible thing would be to have it so as little changes are made to the main executable file as possible between updates as that's what seems to always be getting flagged, though I don;t know if that could even be done and even if it could would likely take a lot of time and work restructuring the program that again probably isn't worth it.

**Comment by Masamune3210** [comment]
Code signing is expensive in most cases unfortunately and isn't even guaranteed to help in all cases, and attempting to abstain from changing the exe isnt worth it and would be borderline impossible. Even if you were to keep from changing the exe, and instead use dll's or something of the like, the issue would just likely move to the new files instead. Heuristic antivirus engines are useful but one of the major downsides is there is no good way to deal with the issue of brand new files

**Comment by Ryochan7** [comment]
I have been testing the archives with various tools and they keep coming up clean for me; tests have been run on all my local archives and some downloaded from GitHub servers. Tools used to scan include Windows Defender, ClamAV, Malwarebytes, and VirusTotal. All virus definitions are up to date for all locally installed utilities. I have also tried ClamAV and uploading to VirusTotal on my Fedora system to eliminate the Windows factor and the tests show no infected files.

**Comment by Dave247** [comment]
Marking as closed as the the issue has been resolved as no more detections have been reported. Hopefully it can be used in the future when encountering the same detection type and/or when trying to narrow down the exact cause of the flag.

**Comment by Ryochan7** [comment]
Tested the archives with BitDefender and Kaspersky and those tools found nothing. Kaspersky does not seem too bad and I plan to keep it installed. I didn't know about VirusTotal before but I will make sure to use it for future archives. It would be nice to know why Windows Defender had a problem with the files in the first time though.
