### ISSUE TITLE
Auto Profile editing isn't working anymore

### ISSUE THREAD

**Issue by CarissaIsWierd** [Ryochan7/DS4Windows#1499]
All the controller dropdowns under the Auto Profiles tab appear as empty. Picking a profile from any dropdown shows it as selected for all of them, and saving one doesn't actually change anything. Auto Profiles.xml is still filled with all my previous edits and working, though.

I'm on Windows 10 Pro x64 using the newest DS4Windows. It was fine in v2.1.9.

**Comment by Ryusennin** [comment]
Confirmed, probably related to #1490.

**Comment by anphetamina** [comment]
I'm not able too

> 
> 
> All the controller dropdowns under the Auto Profiles tab appear as empty. Picking a profile from any dropdown shows it as selected for all of them, and saving one doesn't actually change anything. Auto Profiles.xml is still filled with all my previous edits and working, though.
> 
> I'm on Windows 10 Pro x64 using the newest DS4Windows. It was fine in v2.1.9.

I'm not able too

**Comment by Ryochan7** [comment]
Confirmed. Controller slots are set to (none) in Auto Profiles.xml not matter what is selected.

**Comment by Ryochan7** [comment]
Got it working again. A re-factor for populating the ComboBox controls resulted in data bindings breaking in that side panel for most controls. The initial change was a departure from the 8 Controller pull request as I did not like the way that version populated the ComboBox controls. I still have a local copy of that version and it looks like the data binding would have been fine with the other version.

This breakage was 100% my fault.

**Comment by hdd1013** [comment]
> Got it working again.

Cool. ETA for the update release?

**Comment by Ryochan7** [comment]
Probably sometime tomorrow (Saturday)

**Comment by Ryochan7** [comment]
Version 2.1.14 is now out.

https://github.com/Ryochan7/DS4Windows/releases/tag/v2.1.14
