### ISSUE TITLE
AUTO Xinput Port Setting

### ISSUE THREAD

**Issue by shinra358** [Ryochan7/DS4Windows#15]
On my machine (have no idea why) one day, a set of clear xinput ports may be 1-4. The next day, working xinput ports may be 4-7, etc. I would have to constantly keep changing to the ports that work correctly every week or so. I would like to request an Auto setting so that it will find the best xinput ports by itself without user interaction.

**Comment by Ryochan7** [comment]
Do you have any real XInput device or wireless receiver connected to your computer when this happens? If not then I don't know why the port numbers would need to be changed to make XInput emulation work. It would be nice to have the port range be handled automatically so native XInput devices and emulated XInput devices could work together more seamlessly.

**Comment by shinra358** [comment]
May be something that deals with different things being plugged in to the usb but I only have the ds4 allocated to this program and sometimes the wii mote. But I have different usb extensions and hubs and what not. But no real xinput devices. 

This has been a problem from the start and is 50% of some of the problems ppl have on the pcsx2 forums. I don't know why there is a manual config for the ports but I've always wished for it to do it automatically.

" It would be nice to have the port range be handled automatically so real XInput devices and emulated XInput devices could work together more seamlessly."
This too ;)

**Comment by shinra358** [comment]
since the xinput connection things are fixed, I guess that there is no more need for this anymore probably. But what we could use is an indicator that tells us if the ports are overlapping already occupied ports. And ports that are occupied just wont be shown in the arrow list.

**Comment by Ryochan7** [comment]
I haven't actually messed with this so it is a bit weird that other changes have fixed the problem. I guess it is all good. Testing this out with my old Xbox 360 controller seems to work as the XInput driver is able to assign ports between virtual Xbox 360 and real Xbox 360 controllers as needed despite the XInput port number range used in Scp Virtual Bus; ScpVBus port number 2 can lead to XInput port 3 being used for the virtual Xbox 360 controller. Maybe that port range only really matters regarding other software connecting to the Scp VIrtual Bus to create virtual Xbox 360 controllers.

**Comment by shinra358** [comment]
"I haven't actually messed with this so it is a bit weird that other changes have fixed the problem"
The problem was probably related to the xinput connectivity fixes.

Wow youre right, pretty much all ports connect with no problem now xD
Youre a real miracle worker

Guess this can be closed!
