### ISSUE TITLE
How can I disable "PS + Touch = Touchpad movement is on/off" hotkey?

### ISSUE THREAD

**Issue by vpontin** [Ryochan7/DS4Windows#150]
Hi!
I'm trying to use DS4Windows to map some keys to Dolphin, but this hotkey is very unconfortable.
How can i disable this? I want to, depending of the profile select, have the touch always ON or always OFF.

Thanks in advance!

**Comment by Ryochan7** [comment]
First, you want to disable the **Enable Touchpad Toggle** option in the profile that you are using; it is listed in the Other group. To have the touchpad always disabled, you can have the Touchpad mapping set to **Use for Controls** and have nothing mapped for the swipes.

**Comment by vpontin** [comment]
Thanks a lot!
