### ISSUE TITLE
R2 & L2 Trigger Seem Unresponsive + Request?

### ISSUE THREAD

**Issue by LithiumPB** [Ryochan7/DS4Windows#1501]
Triggers seem unresponsive while playing a game.
Bluetooth connection has this issue, although corded connection works but with random moments of unresponsiveness. 
When playing without DS4 the game and controller seemed to work fine.

Reproducing:
Connect controller as normal. Turn on controller, hit start on DS4. Play game.

Expected behavior:
R2 and L2 to work.

Desktop Info:
 - Controller Make and Model: TOONEV Wireless Controller
 - OS: Windows 10 Home 19041.508
 - DS4Windows Version: 2.1.13

Additional context:
None, but a request if that's alright: Separate Vertical and Horizontal Sensitivities for joysticks?
I apologize if it's just me having the issue.

**Comment by mika-n** [comment]
What do you see in "%APPDATA%\DS4Windows\log" logfiles? Any warnings about gamepad latency?

About separate X and Y axis sensitivity settings. This and other similar features (separate deadzone per axis/separate output curve per axis etc) have been mentioned here few times. Those would be handy, but some of the legacy code in DS4Windows doesn't make it that easy to do. However, now when Ryochan7 has done some re-writing it would be easier to do than in V1.7.x version branch. Those would be definitely handy features, but the landing ETA is still unknown....
