### ISSUE TITLE
will the audio jack ever work over bluetooth?

### ISSUE THREAD

**Issue by TheHacker24680** [Ryochan7/DS4Windows#1502]
so i bought ds4 controller a year ago thinking that ds4windows or input mapper could make this work and it promised that they will work on it so is there any progress or it is not on the to-do list?

**Comment by Ryochan7** [comment]
I don't remember ever promising to get Bluetooth audio working. I have done some experiments with the information that is out there. Audio technically works but the end result was very choppy and I did not find a way to provide a solid audio stream with the information available. That is about the extent to what work has been done. There isn't much hope getting it working fully. Also, issue #1268

DS4 Bluetooth Audio Testing on Linux
https://www.youtube.com/watch?v=Ru6TYGhNMWE
