### ISSUE TITLE
Lightbar passthrough for aurora

### ISSUE THREAD

**Issue by pinospin** [Ryochan7/DS4Windows#1503]
I've tried to enable passthrough lightbar option on DS4Windows but the program trying to overlap the RGB lightbar option from Aurora. If the color is alternating or changing color, it's fine. But when the color idle or solid, the controller's lightbar revert to the color indicated in DS4Windows
So, how can I use Aurora RGB lightbar without turn off DS4Windows? I want to play many game that feature RGB lighting from Aurora like GTA V or Rise of the Tomb Raider

**Comment by Ryochan7** [comment]
It is not possible right now. The feature was disabled again some versions back mainly due to the data from the force feedback routine in the ViGEmClient library being highly inconsistent.

**Comment by mika-n** [comment]
DS4Windows debug version has re-enabled the rumble and ligthbar feature of dualshock4 output controller type.
The logic in the following commit is as follows:
- Rumble sent by a game is passed on to a physical ds4 gamepad if rumble 0..100% amplifier value in a profile is >0% (ie. 0% value can be used to disable rumble). Also, the watchdog timer is reset only if the new rumble value is different than the prev one (the watchdog timer works not better with games using a rumble in a "weird" way).
- Lightbar sent by a game is passed on to a physical ds4 gamepad if ligthbar mode is Passthru in a profile (if the ligthbar mode is "normal" then DS4Windows app controls how the ligthbar looks like).

https://github.com/mika-n/DS4Windows/commit/3c735ec3e26d559bc3138431217560158519d6ce

I think this works pretty good even with "weird" games discussed earlier and the feature was temporarily disabled. With this logic at least user can control per profile how ligthbar and rumble are handled by the physical gamepad and DS4Windows app. If some game really doesn't work then it is possible to disable ligthbar or rumble feedback messages or both per profile.

**Comment by pinospin** [comment]
> DS4Windows debug version has re-enabled the rumble and ligthbar feature of dualshock4 output controller type.
> The logic in the following commit is as follows:
> 
> * Rumble sent by a game is passed on to a physical ds4 gamepad if rumble 0..100% amplifier value in a profile is >0% (ie. 0% value can be used to disable rumble). Also, the watchdog timer is reset only if the new rumble value is different than the prev one (the watchdog timer works now better with games using a rumble in a "weird" way).
> * Lightbar sent by a game is passed on to a physical ds4 gamepad if ligthbar mode is Passthru in a profile (if the ligthbar mode is "normal" then DS4Windows app controls how the ligthbar looks like).
> 
> [mika-n@3c735ec](https://github.com/mika-n/DS4Windows/commit/3c735ec3e26d559bc3138431217560158519d6ce)
> 
> I think this works pretty good even with "weird" games discussed earlier and the feature was temporarily disabled. With this logic at least user can control per profile how ligthbar and rumble are handled by the physical gamepad and DS4Windows app. If some game really doesn't work then it is possible to disable ligthbar or rumble feedback messages or both per profile.

So, can I have the debug version please?

**Comment by pinospin** [comment]
I think the debug version use completely different profiles
It's like all of existing profiles are link to each other
Is it intentional or unintentional?

**Comment by mika-n** [comment]
closed because pull-request #1583 re-enables rumble/lightbar in ds4 output mode. Once that PR is merged and released then Passthru lightbar mode can be used to let games control the lightbar.
