### ISSUE TITLE
Controller gets connected as Controller #2

### ISSUE THREAD

**Issue by lucasblack29** [Ryochan7/DS4Windows#1504]
As the title says, my controller is detected an hidden from Windows 10, however it gets connected to slot 2 even though slot 1 is still empty. Sometimes it goes as far as slot 3 as shown in the image

DS4Windows: 2.1.13
Windows: 2004 (build 19041.508)
ViGEM: 1.16.116

![Controllers](https://user-images.githubusercontent.com/43682420/94343426-53e09200-0042-11eb-9183-abf7311c2f49.png)
![XInput](https://user-images.githubusercontent.com/43682420/94343429-55aa5580-0042-11eb-9575-0901739ccf3b.png)
[Controller Info.txt](https://github.com/Ryochan7/DS4Windows/files/5286834/Controller.Info.txt)
[Log Debug.txt](https://github.com/Ryochan7/DS4Windows/files/5286835/Log.Debug.txt)
[Log.txt](https://github.com/Ryochan7/DS4Windows/files/5286836/Log.txt)
![Joy cpl](https://user-images.githubusercontent.com/43682420/94343430-580caf80-0042-11eb-9876-443881bdb0c3.png)

Note: The debug DS4 Windows detects a non-existant DualShock 4 as a Bluetooth controller yet doesn't report any battery info.

**Comment by Ryusennin** [comment]
#1163

**Comment by lucasblack29** [comment]
Thank you

**Comment by Ryochan7** [comment]
This is the main reason that the XInputChecker app exists. ViGEmBus can sometimes not fully remove XInput devices from the XInputBus so a slot is still used. Controller support might not work in some games if it only supports reading gamepads from XInput slot 1. I have encountered similar slot skipping with some of my smaller experimental programs as well. I believe this is an acknowledged problem on the ViGEmBus GitHub so hopefully some solution will be made.

I doubt I would be able to reproduce the issue on demand and possibly help diagnose the driver issue.

**Comment by lucasblack29** [comment]
I see. Is there anyway to force VigEmBus to restart without shutting down the whole computer?

**Comment by lucasblack29** [comment]
I see, thank you then, I will close this issue now
