### ISSUE TITLE
DS4Windows resets settings and asks saving location at startup

### ISSUE THREAD

**Issue by qwinci** [Ryochan7/DS4Windows#1506]
DS4Windows asks saving location (app directory or appdata) and resets settings every time i reopen it.

1. Close ds4windows
2. Open ds4windows

**Expected behavior**
DS4Windows remembers my settings and doesn't ask for saving folder every time.

 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2E)
 - OS: Windows 10 Home Build 2004
 - DS4Windows Version 2.1.14

**Comment by Ryusennin** [comment]
Where have you installed/copied DS4Windows? "Program Files" is system-reserved and will usually prevent config files from being written there. You could try using a custom directory (C:\MyPrograms for example).

**Comment by Ryochan7** [comment]
I am betting that is exactly what is happening. Going to have to implement a check to prevent this.

**Comment by qwinci** [comment]
I have it copied to my documents and selected save configuration to appdata. It is still happening. I also checked that ds4windows directory in appdata is not read only.
