### ISSUE TITLE
DS4W stop to work

### ISSUE THREAD

**Issue by jinkazama82it** [Ryochan7/DS4Windows#1507]
After moving from 2.1.13 to 2.1.14 the emulated xbox controller stop to appear on device, only the native ds4 is available when i remove the check from hide device.
I tried to reinstall vigem bus but nothing are changed, actually I reverted to DS4W 2.1.13

 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: Windows 10 Pro Build 2004
 - DS4Windows Version 2.1.14

**Additional context**

**Comment by Ryochan7** [comment]
Looking at the commit log now. There is no change in version 2.1.14 that would cause this problem. It has to be some configuration issue on your end.

**Comment by jinkazama82it** [comment]
I've simply updated from 2.1.13 to 2.1.14 what happened i don't know, i know only that if i use the old one all work well with the latest version the emulated device isn't available... simply disappear, restart the PC disconnect the ds4 any type of action don't work.

**Comment by Ryochan7** [comment]
Oh No. I am betting you downloaded the ScpVBus alt build. That build is only for regression testing.

**Comment by jinkazama82it** [comment]
no no I haven't downloaded the ScpVBus of you see on pic only x64 version are available.
![IMG_20200927_173508](https://user-images.githubusercontent.com/28483698/94370432-dcfdd480-00e7-11eb-8087-fcf9436286d0.jpg)

**Comment by mika-n** [comment]
please attach the latest "%APPDATA%\ds4windows\log" logfile here as TXT file (rename the latest logfile as .txt extension).
And do you use HidGuardian tool? It may stop working after major WinOS updates. Simple solution is to re-install  HidGuardia.

**Comment by Ryochan7** [comment]
Continued lack of information. Closing
