### ISSUE TITLE
[Feature Request] Outer Ring Style Binding for Sticks

### ISSUE THREAD

**Issue by MadMax4Q2** [Ryochan7/DS4Windows#1508]
Is it possible to set analogue sticks sensitivity input mapping so for example a game which uses W key to run forward & shift key + W key to walk forward could both be assigned to the same sticks sensitivity mapping when engaging lightly or fully moving the stick?  🤔

> 
> 
> I think you need a program like JoyToKey for that.

will that work along side ds4windows?

**Comment by Ryusennin** [comment]
I think you need a program like JoyToKey for that.

**Comment by MadMax4Q2** [comment]
will JoyToKey work alongside ds4windows to produce that effect?

**Comment by Ryusennin** [comment]
Yes, they are compatible. I use them both for a couple of complicated game profiles.

In the button editor of JoyToKey, section Keyboard (Multi), you have an option named "Switch depending on analog input level".

**Comment by MadMax4Q2** [comment]
Thanks 😏👌

**Comment by Ryochan7** [comment]
I would like to try to change the main mapping routine within a few releases. The main mapping loop will have to be broken up a bit to allow more than one output type for LS and RS (if Flick Stick would ever get implemented). Another reason would be to possibly add at least some kind of outer ring style binding for LS and RS in Controls mode. There are a few uses where that would come in handy but trying to fit something like that in the existing infrastructure has been a challenge.

**Comment by Ryochan7** [comment]
Done in 3.0.11. Just ended up calling it Outer Button rather than Outer Ring. Still only half of what I would want though. Need to get Absolute Mouse bindings implemented eventually. With that last change, Torchlight 2 would pretty much be accessible again. Been wanting to play a bit of that game again.
