### ISSUE TITLE
[Feature Request] Independent sensitivity for x and y axes of analogue sticks

### ISSUE THREAD

**Issue by YuJin44** [Ryochan7/DS4Windows#1509]
Please add another sensitivity slider for each analogue sticks, so that I can set up different sensitivities on both axes (x and y) of the e.g. right stick. Also unlock sensitivity lower than 0.5 (make e.g. 0.1 possible)
![sensitivity](https://user-images.githubusercontent.com/62327163/94465127-b6ab6800-01bf-11eb-90e5-79aa6e0109e3.png)

**Comment by Ryochan7** [comment]
This would be easy enough to do. People have requested a similar feature before but I still don't see the real use for it myself.

**Comment by YuJin44** [comment]
All I can say is try to play genshin impact on windows using a controller (or even amouse):
https://forums.mihoyo.com/genshin/article/17020

**Comment by muizzsiddique** [comment]
If anyone plays with a high right-stick sensitivity and the game itself doesn't support separated X and Y axis control then when playing the game you will very easily look right down at the floor or the sky. So I'm waiting for this, too.

**Comment by Ryochan7** [comment]
This is now available in version 2.2.11. Dead zone, Max Zone, Anti-dead zone, and Max Output can be set per axis in Axial mode.

https://github.com/Ryochan7/DS4Windows/releases/tag/v2.2.11

**Comment by Atyne** [comment]
I don't know if I'm missing something but there is no sensitivity option in axial mode.

**Comment by jctrulz1** [comment]
I'm having the same problem. There's no option to change sensitivity if Axial is selected as Dead Zone Type.
