### ISSUE TITLE
[Bug] Controller keeps disconnecting/reconnecting till ''Latest USB device not recognized'' error

### ISSUE THREAD

**Issue by dogancana** [Ryochan7/DS4Windows#1510]
**Describe the bug**
I used DS4Windows with FIFA21 successfully for 20 minutes. After that it suddenly disconnected and reconnected couple of times. After this time, FIFA was showing 3 controllers at some point.
In 1-2 minutes, windows gave the 'Latest USB device not recognized' error. I thought it was a hardware issue and tried with 3 different cables on different USB ports. Updated all the drivers and windows. Restarted the computer. Disabled/Enabled related devices from device manager. No luck after these tries and now I'm looking for ways to debug it. 
I also provide log file from my latest trial. This log file was obtained without reconnecting/disconnecting the device, all software issues, Please make sure to check timestamps and see how fast it's happening.

**To Reproduce**
I believe it's not applicable as it's probably related to my system.

**Expected behavior**
To work stable.

**Screenshots**
Not necessary

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: Windows 10, version 1909
 - DS4Windows Version [e.g. 2.1.14]

**Additional context**
I'm also a developer myself. I don't have any driver related experience, But if you give me ways to debug it, I can follow them through.
Not sure if it's related but, whenever controller is connected for the first time again, it starts to load proper profile, shows up in the app etc. 
And I can provide screen recording if requested.
[log.txt](https://github.com/Ryochan7/DS4Windows/files/5314358/log.txt)

**Comment by mika-n** [comment]
See this https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

**Comment by dogancana** [comment]
Thank you @mika-n 

I used debugger one and got logs. In the mean time I also reset my windows to clear all the stuff I did in device manager. Now windows just don't recognize the controller and DS4Windows only got the controller once after I reset the pc. 
I know it's an issue with windows and my controller, not DS4Windows but maybe these logs ring a bell to you?

[ds4_not_finding_hid.txt](https://github.com/Ryochan7/DS4Windows/files/5322991/ds4_not_finding_hid.txt)
[unknown_device_error.txt](https://github.com/Ryochan7/DS4Windows/files/5322994/unknown_device_error.txt)

**Comment by mika-n** [comment]
If windows doesn't recognize the DS4 gamepad HID devices then some driver missing or conflict in PC. There is nothing DS4Windows app can do about it, so try to sort out the ds4 gamepad driver issue. One way to make sure all required things are installed is to install Sony PS RemotePlay app on PC.
