### ISSUE TITLE
Original ds4 controller not working while app is open (unsure if feature or bug)

### ISSUE THREAD

**Issue by Nato390** [Ryochan7/DS4Windows#1516]
Basically just the standard controller is no longer recognized by anything while I have the app open, wasn't sure if this was intended. If yes it's meant to do that, feature request!

Make an option where we can enable the original controller so we can have 2 controllers to pick from game-by-game in apps such as Steam Big Picture (ex. CEMU uses ds4windows xinput, everything else including big picture menu just uses the standard ds4 controller), sort of like an opposite feature to the "Hide ds4 Controller" option

If this is NOT a feature and both devices should be separate and working, here's some info
Windows 10 Home
DS4Windows 2.1.14
Sony DS4 v.2 (CUH-ZCT2U)
Regular ds4 does not work regardless of whether "hide ds4 controller" is enabled or not

Apologies if this is a simple fix or a feature.

**Comment by mika-n** [comment]
Are you using BT connection? It is a limitation in WinOS that once DS4Windows switches the DS4 to the native DS4 mode (from PC-friendly default mode) then DS4 no longer work over BT in WinOS. USB connection doesn't have this problem.

**Comment by Ryochan7** [comment]
Mika already explained it but I will add an extra note that the same behavior occurs with other mappers as well (Steam Input, InputMapper).
