### ISSUE TITLE
The ViGemBus install prompt closes if you click on the "Install ViGemBus driver" button more than once

### ISSUE THREAD

**Issue by zacchi4k** [Ryochan7/DS4Windows#1517]
**Describe the bug**
The ViGemBus install prompt closes if you click on the "Install ViGemBus driver" button more than once

**To Reproduce**
1. Open DS4Windows on a machine without the ViGemBus driver
2. Click the "Install ViGemBus driver" button at least twice
3. The window closes without installing the driver

**Expected behavior**
The windows should not close (or the button should be disabled)

**Video**
https://streamable.com/ht8z2t

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro Build 2004 x64
 - DS4Windows Version 2.1.14

**Comment by Ryochan7** [comment]
This is more of the case of why would you do this.

**Comment by zacchi4k** [comment]
No reason, just stumbled upon it. But its definitely an unintended effect anyway

**Comment by Ryochan7** [comment]
This issue has been addressed with version 2.1.15.
