### ISSUE TITLE
Input from Wirelessly Connected DS4 Is Not Detected While a Certain Program Is Running

### ISSUE THREAD

**Issue by jsway06** [Ryochan7/DS4Windows#1518]
DS4Windows Version: 2.1.14
ViGEmBus Version: 1.16.112.0
Gamepad Version: v.1
Windows OS Version: 10.0.19041.0

Hello. In addition to DS4Windows, I am a user of gamepad mapper reWASD. There was a time when I could use both programs in conjunction without any issue. For quite some time, I have been aware of an issue where DS4Windows will not detect the input of a wirelessly connected DS4 when the reWASD service is running. However, recently I have found that when the gamepad is connected via micro USB, all input—including gyro/accel—is detected. I have tested with joy.cpl and can confirm that input is always detected, wired and wirelessly. This issue can be reproduced on my other PC as well.

I cannot say exactly when this issue was introduced. I believe reWASD once used the ViGEmBus Driver for employing virtual devices, but now uses its own proprietary driver, hidgamemap. I have wondered if the onset of this change is when the issue arose, which had led me to believe reWASD may be at fault—this was compounded by the fact that when the reWASD service is disabled, DS4Windows works as intended. However, I recently chatted with a developer on the reWASD forum, and he suggested that this may be an issue with DS4Windows.

There are a few things that may be worth mentioning. First, both the physical gamepad and reWASD's virtual gamepad are recognized in DS4Windows. When connected wirelessly, neither has detectable input. When wired, only the physical gamepad's input is detectable. Second, reWASD has a setting, much like the DS4Windows _Hide DS4 Controller_ setting, to hide the physical gamepad; oddly, when this setting is enabled, the virtual gamepad's input—excluding gyro/accel because emulation is not yet implemented—is detected. Finally, running the DS4Windows debug version generates a log with warning message _check of BT input packet failed_.

Honestly, I am not sure if this would be considered a bug, or just expected behavior given that both programs are generally serving the same purpose, which is perhaps causing conflict. But, as mentioned above, everything had worked well together in the past, and presently only when the DS4 gamepad is wired. If anyone could chime in, I would greatly appreciate any insight. I have attached debug log files for reference—one generated with Bluetooth connection and the other with USB connection, respectively.
[logBT.txt](https://github.com/Ryochan7/DS4Windows/files/5324640/logBT.txt)
[logUSB.txt](https://github.com/Ryochan7/DS4Windows/files/5324641/logUSB.txt)

 Thank you.

**Comment by mika-n** [comment]
Difficult to say and debug this issue without reWASD.  Could be that reWASD hides the physical controller from other processes or reWASD has already switched the BT connected gamepad into native DS4 mode and when DS4Windows app tries to do the same then something goes wrong.

When DS4 gamepad is connected over USB then there is no need to do "pc-friendly mode switch over to native ds4 mode" type of thing with the physical gamepad. It may explain why it works over usb.

But, difficult to say for sure without actually seeing and testing what happens with reWASD and with its own custom version of ViGem driver (I believe they have forked the Nefarious ViGem driver and didn't create everything from scratch).

**Comment by mika-n** [comment]
Difficult to say and debug this issue without reWASD.  Could be that reWASD hides the physical controller from other processes or reWASD has already switched the BT connected gamepad into native DS4 mode and when DS4Windows app tries to do the same then something goes wrong.

When DS4 gamepad is connected over USB then there is no need to do "pc-friendly mode switch over to native ds4 mode" type of thing with the physical gamepad. It may explain why it works over usb.

But, difficult to say for sure without actually seeing and testing what happens with reWASD and with its own custom version of ViGem driver (I believe they have forked the Nefarious ViGem driver and didn't create everything from scratch).

**Comment by mika-n** [comment]
.

**Comment by jsway06** [comment]
Interesting! That makes sense. Reading through some of the other issues, I had seen you mention the whole default PC-friendly mode to native DS4 mode concept. I also saw your merged pull request regarding non-standard DS4 support—a good read. Thank you for the informative post, much appreciated.
