### ISSUE TITLE
..

### ISSUE THREAD

**Issue by WiggleButt17** [Ryochan7/DS4Windows#1519]

**Comment by Masamune3210** [comment]
if the issue persists even through a OS install, it's a issue with your hardware

**Comment by WiggleButt17** [comment]
Doubtful. I worked perfectly until I downloaded that. Also tried them on my laptop and it worked perfect.

I finally, got the PC to somehow recognize the PS4 controller again after about 5 hours, but it still wont let me connect via Bluetooth.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by Masamune3210** [comment]
...I mean you can doubt all you want, but the Hide DS4 option doesn't do anything to the controller, it just tells windows to ignore your controller, which would be wiped out if you actually reinstalled windows

If you actually did reinstall windows, make sure your Bluetooth has its drivers installed, if not windows won't be able to use it

**Comment by WiggleButt17** [comment]
If I actually did?? Ok.

I mean you can doubt it all you want but it happened.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Ryochan7** [comment]
:man_shrugging: Closing and locking
