### ISSUE TITLE
Locale: Not all words are fully shown due to bigger sized words

### ISSUE THREAD

**Issue by RedDevilus** [Ryochan7/DS4Windows#1521]
DS4Windows seems to clamp some of it words with a fixed size but in  some parts of the other languages you get:

German;
Edit 
![image](https://user-images.githubusercontent.com/24227051/95279700-a6485c80-0853-11eb-9ee3-daab67c83597.png)
Dutch;
Edit 
![image](https://user-images.githubusercontent.com/24227051/95279827-f0c9d900-0853-11eb-8a95-fb5022e5b142.png)
Profile, Other:
![image](https://user-images.githubusercontent.com/24227051/95279879-0ccd7a80-0854-11eb-95b4-8eda877f24c2.png)

Examples where its correct;
French;
Edit
![image](https://user-images.githubusercontent.com/24227051/95280076-7483c580-0854-11eb-8b70-58218aac9f22.png)

**Comment by Ryochan7** [comment]
Looks like there are more controls that need to use MinWidth rather than a fixed Width property.
