### ISSUE TITLE
Wont autoupdate

### ISSUE THREAD

**Issue by thegamerx1** [Ryochan7/DS4Windows#1522]
**Describe the bug**
It downloads the zip file to the `Updates` folder but then just closes no error

**To Reproduce**
say yes to update dialog
click yes on close to continue
crash

**Expected behavior**
update

**Desktop (please complete the following information):**
 - Controller Make and Model: not important
 - OS: Windows 10 Pro Build 2004
 - DS4Windows Version 2.1.14

**Additional context**
[crashdump.zip](https://github.com/Ryochan7/DS4Windows/files/5341918/crashdump.zip)

ended up manually extracting the `DS4Windows_2.1.15_x64.zip` file

**Comment by mika-n** [comment]
probably some permission issue because the update procedure for sure works in numerous other workstations.
