### ISSUE TITLE
After years of working without issues my DS4Windows went crazy yesterday

### ISSUE THREAD

**Issue by McNippleson** [Ryochan7/DS4Windows#1523]
Pretty much suddenly my controller stopped being recognized in some games yesterday so I've wasted 2.5 hours trying to fix it but couldn't find a proper fix.

I tried a lot of random things out of frustration and had these scenarios

1 - With controller added to hidninja's list - When disguised as X360 controller I see it here https://gamepad-tester.com/ But when I switch to the same profile but emulating DS4 it says I have no controller connected and I can't play 
2 - somehow I always had 054c-05c4-Wireless Controller connected and then I either had an X360 or PS4 controller connected a a second one depending on profile used in DS4Windows. So all my input was duplicated.
3 - removing everything from hidninja so running in non exclusive mode is the only thing working currently. Switching between X360 and DS4 works @ https://gamepad-tester.com/ . The only problem is that lightbar is not lighting up at all for some reason.

**Comment by Ryusennin** [comment]
If you have a genuine DS4 v1 gamepad, HidGuardian does _not_ support "Emulated DS4" mode on v1 controllers.

**Comment by McNippleson** [comment]
> If you have a genuine DS4 v1 gamepad, HidGuardian does _not_ support "Emulated DS4" mode on v1 controllers.

I guess it explains why I don't get native button icons in Rocket League I guess? (Though I do get them in RDR2).

But I don't think it explains why it stopped properly working at all.

**Comment by mika-n** [comment]
Some windows update broke HidGuardian installation? It can happen. Easiest solution is to re-install HidGuardian to re-register its filter driver.
