### ISSUE TITLE
you cant use XBOX 360 in fortnite and some outher games

### ISSUE THREAD

**Issue by lilnemo** [Ryochan7/DS4Windows#1524]
First of all i would like to thank the person\ persons who are programing this ds4 program 
second of all i think you should revert this update cuz we cant use the xbox 360 controller option in fortnite everything was good before this update

**Comment by Ryusennin** [comment]
According to PC Gaming Wiki, Fortnite is fully XInput compatible.

"Some other games" -- please give a list of specific examples.

**Comment by lilnemo** [comment]
i can show you that it dont work in fortnite

**Comment by lilnemo** [comment]
or i can show you my settings in ds4

**Comment by Ryochan7** [comment]
It has worked for me perfectly fine in the past. As I believe the game can support the DS4 natively, you will have to make sure that DS4Windows has exclusive access to the DS4 so Fortnite does not detect it.

**Comment by Ryochan7** [comment]
Not a problem with DS4Windows so this issue can be closed.
