### ISSUE TITLE
First try connection via Bluetooth is succesful but after restarting controller I get a solid white light and nothing works.

### ISSUE THREAD

**Issue by matthqs** [Ryochan7/DS4Windows#1526]
First try connection via Bluetooth is succesful but after restarting controller I get a solid white light and nothing works. I tried removing and reinstalling everything but still no luck. It works and detects fine with USB but I can't get it to work via bluetooth

**Comment by mika-n** [comment]
please read the pinned "Read this before posting a new issue ticket". Your post lacks all basic information we need to diagnose and discuss the issue.

**Comment by mika-n** [comment]
closed as inactivity
