### ISSUE TITLE
Task only starts when computer is connected to mains power

### ISSUE THREAD

**Issue by ds22x** [Ryochan7/DS4Windows#1529]
Whenever you enable DS4Windows to run as a task on Windows 10, it will make a profile with a condition to only run when the computer is connected to mains power.
Disabling this condition in the task scheduler only disables this until the next time DS4Windows is run, after which the condition is re-enabled.

**Comment by Ryochan7** [comment]
I guess that is a default option at least for tasks created with the Task Scheduler package. I'll have to find what property to change to not force that power option when creating a Task entry.

**Comment by mika-n** [comment]
"Allow task startup if running on battery power " change is already released in the latest version
