### ISSUE TITLE
Some texts of HIDNinja is garbled when win10 system language is Chinese (Traditional, Taiwan)

### ISSUE THREAD

**Issue by SyaoranChang** [Ryochan7/DS4Windows#1530]
Hi,

I find a issue about some texts of HIDNinja is garbled when win10 system language is Chinese (Traditional, Taiwan)

![Some texts of HIDNinja is garbled](https://user-images.githubusercontent.com/18550228/96030566-baf9a580-0e8e-11eb-8919-7e27f4f5dfeb.png)

**Comment by Ryochan7** [comment]
The string encoding process is still off. I am not sure why. Will have to look into this again.

**Comment by Ryochan7** [comment]
Needed to change the system call used to get a proper Unicode string. International text is confirmed to work now; tested changes against a Japanese locale. An app update should be bundled with the next release of DS4Windows.
