### ISSUE TITLE
Error 1167

### ISSUE THREAD

**Issue by gustavobfernandes** [Ryochan7/DS4Windows#1531]
Hi guys,

my PS4 controller disconnects randomly via bluetooth conection. In the log, the error says "Gamepad data write connection is lost. Disconnecting the gamepad. LastErrorCode=1167". I'm using a generic dongle CSR 4.0. Someone can help me?

**Comment by Masamune3210** [comment]
are you sure your controller is a legit 1st party? maybe your Bluetooth dongle isn't good enough?

**Comment by gustavobfernandes** [comment]
Do you mean an original controller? Yes, it is. I am thinking that the dongle isn't good enough, but now i am playing for over a hour and the controller didn't disconnect.

**Comment by Masamune3210** [comment]
If the dongle or connection is bad, issues can be caused by something as simple as having something in between the dongle and the controller like your table or a phone nearby

**Comment by mika-n** [comment]
Here are few tips you could try to experiment if BT connection isn't stable
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#gamepad-connection-over-bluetooth-bt
