### ISSUE TITLE
Strange Behavior after a few days running.

### ISSUE THREAD

**Issue by Abbygales** [Ryochan7/DS4Windows#1534]
**Describe the bug**
After about 3 days when DS4Windows is running it prevents every exe file from running. Only fix is to close DS4Windows.

**To Reproduce**
Let it run for a long time without restarting the pc.

**Expected behavior**
It does not block any programs from loading.

**Desktop (please complete the following information):**

 - Controller Make and Model: Sony DS4 v.1 (CUH-ZCT1E)
 - OS: Windows 10 Pro 2004
 - DS4Windows Version 2.1.15

**Comment by mika-n** [comment]
anything in the DS4Windows logfiles when those strange things started to happen? Or in Windows Events (EventViewer)?

If nothing else happens then you could try to setup a scheduled job to restart DS4Windows app once a day in the middle of the night when computer is idling (ie. a scheduled job to run during non-busy hours AND when the PC is in idling state). A simple batch script can do shutdown-restart thing
https://github.com/Ryochan7/DS4Windows/wiki/Command-line-options
```
DS4Windows.exe -command shutdown
timeout /nobreak /t 60
DS4Windows.exe
```

**Comment by Abbygales** [comment]
The logfile does not show anything. Only shows what happens when its loading and when I shut it down. Nothing in between when it acts up.
[ds4windows_log_20201017.0.txt](https://github.com/Ryochan7/DS4Windows/files/5400604/ds4windows_log_20201017.0.txt)

**Comment by Ryochan7** [comment]
How much memory is DS4Windows using when this happens? I cannot think of a reason why DS4Windows would interfere with other processes unless it just gobbled up all your system's memory. There is a garbage collection loop routine that should free memory frequently. On my system, .NET does free extra memory used by the .NET Runtime when needed and I have seen DS4Windows use less than 10 MB of memory when playing games.

**Comment by mika-n** [comment]
closed as inactive ticket

**Comment by Abbygales** [comment]
Found the problem seems to be related to some Power state issue. When I try to restart after it happened it causes a power state blue screen.
