### ISSUE TITLE
Unable to use keyboard after installing HIDGuardian

### ISSUE THREAD

**Issue by jamezsan** [Ryochan7/DS4Windows#1535]
Encountering the exclusive mode error constantly, I decided to install HIDGuardian to make it easier for myself. After installing manually, following the steps, I rebooted. Now I cannot use the keyboard in any windows application (Settings, File Explorer etc), and some services that are meant to run at startup aren't running at startup. 

If you need any info from me, just ask. I am running the latest version of DS4 and downloaded the latest version of HIDGuardian.

**Comment by jamezsan** [comment]
Tried removing the HIDGuardian in registry editor, after reboot nothing is fixed

**Comment by jamezsan** [comment]
Further info in case this matters: I was not using the latest version of DS4 when i installed the HIDGuardian, I have since updated but nothing has changed.

**Comment by mika-n** [comment]
See #1525 how to recover the usb kbd/mouse. You must have somehow messed up the driver installation and filter driver registry settings.

You probably should have used the "one click" installer (HidTestInstaller) to install HidGuardian instead of trying to do it via command line manual commands.
https://github.com/Ryochan7/DS4Windows/wiki/DS4Windows-and-HIDGuardian-Install-and-Setup-Guide#hidguardian-test-installer

**Comment by jamezsan** [comment]
I found that issue but it didnt fix my issue, mostly because the thing you say to alter the value of didn't exist in the hive.  I also ran the installation as admin to install it.

**Comment by jamezsan** [comment]
I did the one click installer like you said, and the only change now is that I can press space during the login screen to enter my password, where as before I needed to click before entering my information.

**Comment by jamezsan** [comment]
So I'm presuming I just format my PC, because nothing I've tried seems to work. Unless there's something anyone here can recommend?

**Comment by mika-n** [comment]
or if you have a restore point prior messing up something.

Anyway. usually the manual registry tweaks explained in the linked post usually helps if usb kbd/mouse are lost,  but I find it a bit strange that there would be some behavior difference between 3rd party apps and WinStore apps. So something unique in your incident. Sorry, I don't have any more new ideas what to do except restore point or "re-install windows10 from a bootable usb stick".

**Comment by Ryochan7** [comment]
Generally, I do not recommend that people use the command line method for installing HidGuardian. It is too easy to get the order wrong or forget a step (especially when uninstalling) and have a bad time. I use my own utilities to install and uninstall HidGuardian.

Test installer for last stable HidGuardian:
https://drive.google.com/file/d/1PNL3uv_4KektN00S9fm61djypSQ-3HED/view?usp=sharing

Custom experimental update (requires running Windows in Test Mode):
https://drive.google.com/file/d/1XSIdgh6P-WCLs3JR0yVWYnWr_FNT5jfZ/view?usp=sharing

![youre-gonna-have-a-bad-time](https://user-images.githubusercontent.com/581968/97337026-bbf6e380-184d-11eb-97a2-4da9ad23c78f.jpg)
