### ISSUE TITLE
Xbox Stat Remover Option

### ISSUE THREAD

**Issue by shinra358** [Ryochan7/DS4Windows#1536]
Can you add an option to remove the xbox stat pop up when ps button is pressed that happens when installing the xbox360 drivers. That way, it would be all in one place and one wouldnt have to search the net to find the script.

**Comment by Masamune3210** [comment]
Just turn it off in Windows Settings, its under the gamebar options

**Comment by Masamune3210** [comment]
The app just passes the button through to the system, so its doing the correct thing

**Comment by shinra358** [comment]
It creates an unneeded popup everytime it is pressed that is useless.
XboxStatRemover was what the script was called. The only thing being
altered is the visibility of the popup.

**Comment by shinra358** [comment]
There is no gamebar in win7

**Comment by Masamune3210** [comment]
What stat thing are you talking about then, I'm confused

**Comment by Masamune3210** [comment]
If you go to this issue in a web browser you can upload a pic

**Comment by shinra358** [comment]
That was answered in my first response to you. The script was called
xboxstat remover. What it did was turn off that circular popup that came up
every time the home button is pressed.

That's all im asking is for ds4w to be able to do it.

**Comment by Masamune3210** [comment]
Pretty sure you an just unbind the ps button if you arent using it, can you not?

**Comment by shinra358** [comment]
I can't find that actual bat script anymore but here is a page that says how to do it manually.
Disabling the ps button is not what is desired.

http://www.volnapc.com/all-posts/xbox-controller-users-get-rid-of-xboxstatexe

**Comment by Masamune3210** [comment]
Aah, seems a bit out of scope for this, but that's for the actual devs to decide. I'm just a lurker

**Comment by Ryusennin** [comment]
On Win7 you can disable Xbox Accessories via Autoruns, that's what I did years ago. No need to uninstall it.

**Comment by shinra358** [comment]
Yes but that's a 2nd program. Or rather an outside disguised bat script.
Ive just done it via bat in the past. But since ds4 can handle installation
of the driver, it would also be nice for it to handle the nuisance w the
driver. When testing ds4w's updates, there comes times when we have to
reinstall the 360 drivers. So it would be more convenient that an option
for for the pop up removal be added to ds4w bcuz it handles everything else
controller related.

It can simply be a link on the same tab as the driver install that calls a
bat within the ds4w folder to remove it or it can simply be added after the
drivers are installed from ds4w to automatically remove the popup.

Ooooor, it could check the location that windows see it to run to see if it
needs to be removed on startup of ds4w. If it's on, ds4 turns it off. If
it's already off nothing happens.

The bat was pretty small so i dnt see this being difficult.

**Comment by shinra358** [comment]
Found the bat for this just in case there's interest in adding this option to the program:

`echo Start
echo #
echo ######################## Default dirctory for x86 x64 ########################
echo #
echo this command is default system32 directory for x86 OS or x64 OS
cd %windir% & cd system32
reg delete "HKCU\Software\Microsoft\Windows\CurrentVersion\Run" /v "XboxStat" /f
reg delete "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Run" /v "XboxStat" /f
echo #
echo ######################## Change the dirctory for x64 ########################
echo #
echo this command is x86 application's registry for x64 OS
cd %windir% & cd syswow64
reg delete "HKCU\Software\Microsoft\Windows\CurrentVersion\Run" /v "XboxStat" /f
reg delete "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Run" /v "XboxStat" /f
echo End `
