### ISSUE TITLE
Battle.Net/Blizzard App and other programs wouldn't launch until I close DS4Windows

### ISSUE THREAD

**Issue by devinkamar** [Ryochan7/DS4Windows#1537]
Title says it all. Couldn't get Battle.net to open no matter what I did. Most of my problems end up being DS4Windows, so I force closed it in Task Manager (it wouldn't close normally) and Battle.Net instantly popped up out of the aether. 

Had the same problem with Steam the other day.

**Comment by Ryusennin** [comment]
Which DS4Windows version are you using?

When you run your game launcher and it seems to freeze, try unplugging/replugging your controller. Does that do anything?

**Comment by mika-n** [comment]
Are you using "Hide DS4 Controller" or "HidGuardian" option to hide the original gamepad device?
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

If you use HideDS4Controller (=exclusive access) option then any difference when this option is unchecked? Naturally this may have other side effects in games when both the original and the virtual gamepads are visible to games, but some app are badly programmed and freeze when those try to open an exclusively locked device handle. Then HidGuardian may be your only alternative option available at the moment.

**Comment by devinkamar** [comment]
I'm using the latest version the auto-update gives me, so 2.1.15. I'm using the HideDS4Controller setting, I don't use HIDGuardian. I've also noticed that, uh, DS4Windows is using up ~30% of my CPU now and barely responsive, so that's not ideal. This is a new problem, unlike the restart thing I'll detail in a minute. 

I tested it once and found that it dropped instantly to 15% if I went to the output slots menu and unplugged one of the slots it seems to have plugged in (I'll need to check and see if it starts that high or is something that happens when I restart DS4Windows). Reopened it (still haven't restarted) and it's at 30% and clicking unplug doesn't make anything happen. The log just says "Unplugging virtual etc etc" but nothing changes and I can click unplug over and over with no change. 

I'll test a bit to see what other details I can suss out, but it's a bit of a pain because testing DS4Windows stops functioning pretty much after being closed or the controller being disconnected. 

Elaborating on that last bit, I think it's all probably tied up with another long-standing problem I've had for as long as I can remember and seen discussed here, where after disconnecting the controller or closing DS4Windows, its impossible to ever connect the controller to DS4Windows and use it in a game again before a restart. Even if I do manage to get the controller synced back with DS4Windows, which is maybe 50/50, it doesn't work in any games or on the HTML5 test site. 

I also find that if DS4Windows has been open at any point then my computer will not be able to successfully restart without me manually powering the system off, even if I kill the program completely via task manager first; it'll just sit at the "Restarting" screen forever.

**Comment by devinkamar** [comment]
On a fresh restart, controller syncs instantly with DS4Windows when it connects to the Bluetooth, CPU usage is less than 1%. 

Battle.Net opens fine in the fresh state, too. So it seems like all of the problems are just manifestations of whatever's going sideways if I restart the program for any reason.

**Comment by devinkamar** [comment]
Ah, and the output slots only show one controller with "Unplug" as an option. It was sitting at three but none of them active after a few restarts.

**Comment by mika-n** [comment]
Do you use BT connection? And is the auto-disconnect BT gamepad after X minutes idling option enabled?  If YES then maybe some app is hijacking the gamepad after the gamepad is re-connected after auto-disconnection and this way prevents the exclusive mode (HideDS4Controller) option to do its magic? 

By default the output slots uses dynamic option which means that when the physical gamepad connection is lost then the virtual output controller is dynamically also disconnected. Some games may be confused by this or they hijack the physical gamepad and prevents exclusive mode to work until you reboot the PC or close the game and re-connect the gamepad.

Try setting output slot to "persistent" option. If there is some temporary disconnection issue or auto-disconnection then the virtual output controller is still left in "connected" state even when it won't receive any button events until you re-connect the physical gamepad. Anyway, this persistent virtual controller helps to solve issues with those games having problems if a gamepad is disconnected while the game is running.

**Comment by devinkamar** [comment]
So, I tried using the Permanent option for the controller, not sure it made any difference for my particular problem. 

When I tried to launch Steam, it didn't open, but the program was in my task manager. When I clicked 'Stop' in DS4Windows Steam instantly popped up. I clicked Start and my controller light turned green meaning it was reconnected to DS4Windows again. 

A bit later Steam asks to restart, and restarts without issue. This surprised me a bit, so I immediately went to DS4Windows and launched the HTML5 site to test the gamepad. No controller detected. So if I click stop and start in DS4Windows the controller connects to the profile but no longer works for anything, same as if I closed DS4Windows or disconnected and reconnected to BT.

If it follows the usual pattern, it won't work again through DS4Windows until I restart my computer entirely. I'll attach the log in a second, but it doesn't look very illuminating.

**Comment by devinkamar** [comment]
[notworking.txt](https://github.com/Ryochan7/DS4Windows/files/5438512/notworking.txt)

**Comment by Ryochan7** [comment]
This unfortunately is an issue with ViGEmBus. When unplugging a virtual controller, sometimes it leaves the virtual controller stagnant and I believe the Force Feedback loop never exits. Not trying to use the virtual controller will not impact system performance. However, once a mapper or a game tries to interface with the stagnant controller, it will cause ViGEmBus to consume one CPU core for that stagnant controller. You can test that by switching to a dedicated KB+M profile that has the **Use DInput Only** option enabled. Not much that can be done about this issue on the DS4Windows side. The only recourse is to reboot your computer.

I believe there is supposed to be an upcoming update for ViGEmBus fairly soon. Hopefully it will get released by the end of the current year.
