### ISSUE TITLE
Issue with profile option Emulated controller

### ISSUE THREAD

**Issue by Ashuraman666** [Ryochan7/DS4Windows#1538]
**Describe the bug**
When choosing Dualshock 4 on the emulated controller option in the Other tab of the profile, the controller stops working completely

**To Reproduce**
1. Go to profile edit screen
2. Click on other tab
3. Select Dualshock 4 on Emulated Controller
4. Controller completely stops working in game

**Desktop (please complete the following information):**
 - Controller Make and Model: Honestly not sure, it's one of the first ever Dualshock 4
 - OS: Windows 10
 - DS4Windows Version: Latest

**Comment by Ryusennin** [comment]
DualShock 4 version 1 is not compatible with the DS4 emulated controller option. A v2 is required (the culprit is not DS4Windows but the VigEm driver used by DS4Windows).

**Comment by Ashuraman666** [comment]
> DualShock 4 version 1 is not compatible with the DS4 emulated controller option. A v2 is required (the culprit is not DS4Windows but the VigEm driver used by DS4Windows).

Interesting. Because i actually got it to work with one single game. Just one

**Comment by mika-n** [comment]
If you use HidGuardian driver to hide the physical controller then it doesn't work with DS4 revision1 gamepads IF THE PROFILE USES dualshock4 output mode. HidG does work with ds4 output mode if you have DS4 revision2 gamepads, but it requires you to tweak the AffectedDevices settings of HidGuardian driver.

This thing is explained here. And a little helper tool HidNinja can be used to tweak the registry setting or you can do it directly via WinOS registry editor.
https://github.com/Ryochan7/DS4Windows/issues/669#issuecomment-487302990
https://github.com/Ryochan7/DS4Windows/issues/1219

If you don't use HidGuardian then something else is causing the issue. Are you using the "Hide DS4 Controller" option to hide the physical gamepad? Are you sure it works?
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

**Comment by Ashuraman666** [comment]
> If you use HidGuardian driver to hide the physical controller then it doesn't work with DS4 revision1 gamepads IF THE PROFILE USES dualshock4 output mode. HidG does work with ds4 output mode if you have DS4 revision2 gamepads, but it requires you to tweak the AffectedDevices settings of HidGuardian driver.
> 
> This thing is explained here. And a little helper tool HidNinja can be used to tweak the registry setting or you can do it directly via WinOS registry editor.
> [#669 (comment)](https://github.com/Ryochan7/DS4Windows/issues/669#issuecomment-487302990)
> #1219
> 
> If you don't use HidGuardian then something else is causing the issue. Are you using the "Hide DS4 Controller" option to hide the physical gamepad? Are you sure it works?
> https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

Yes i have the "Hide DS4 Controller" option selected, always have had it selected since the start. And yes i'm 100% sure it works but only one a single game, that being Marvel's Avengers. On any other game i've tried the controller stopped working but for Marvel's avengers it worked fine and even had the Ps4 icons in game. Also i've tried unselecting the "Hide DS4 controller" option and it still wouldn't work(except for the game i mentioned)

**Comment by mika-n** [comment]
Make sure you have the latest version of ViGem driver installed. Updating DS4Windows app won't update the ViGem driver.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#link-list

**Comment by Ashuraman666** [comment]
> Make sure you have the latest version of ViGem driver installed. Updating DS4Windows app won't update the ViGem driver.
> https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#link-list

Even after updating the issue persists. Guess it's just my controller not being compatible with that function. No big deal really

**Comment by mika-n** [comment]
Are you using Steam games? Please take a look at this page:
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#steam-doesnt-see-the-virtual-output-controller-if-a-profile-uses-the-dualshock4-output-type-steam-sees-the-ds4-controller-only-if-ds4windows-uses-xbox360-output-controller-type

**Comment by Ashuraman666** [comment]
> Are you using Steam games? Please take a look at this page:
> https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#steam-doesnt-see-the-virtual-output-controller-if-a-profile-uses-the-dualshock4-output-type-steam-sees-the-ds4-controller-only-if-ds4windows-uses-xbox360-output-controller-type

It happens with both steam and non steam games so i doubt that's the issue but i'll give that solution a shot, see if it works
