### ISSUE TITLE
WRC 9 FIA World Rally Championship (emulated dualshock)

### ISSUE THREAD

**Issue by IceLancerSR** [Ryochan7/DS4Windows#1540]
Epic Store
Start game without Ds4windows, game recognizes dualshock 4 perfectly it even adds appropriate button icons (playstation)
using dualshock V2 (tested both wired and wireless)
Problem happens when u start game with DS4win app and turn on dualshock emulation in options
game no longer recognizes dualshock but thinks its random generic gamepad? Not even xbox. 
My guess is..? that ds4win emulates my V2 as V1? and game doesn't support V1??

Emulating as V1 has its advantages on some games, where V2 isnt supported like Batman games, but seems to be obstacle here?
game developers are really making things weirder and weirder each day

https://i.imgur.com/8AKCDnK.jpg

**Comment by Ryusennin** [comment]
Maybe your AffectedDevices registry key is not properly configured. "Emulated DS4" requires a V2 with a specific reg key.

https://github.com/Ryochan7/DS4Windows/issues/669#issuecomment-487302990

**Comment by IceLancerSR** [comment]
> 
> 
> Maybe your (HidGuardian) AffectedDevices registry key is not properly configured. "Emulated DS4" requires a V2 with a specific reg key.
> 
> [#669 (comment)](https://github.com/Ryochan7/DS4Windows/issues/669#issuecomment-487302990)

I was using emulate ds4 before. Batman which only works with V1 , tomb raider last 2 games, dualshock is recognized when emulated so i dont think i am affected by this

**Comment by Ryochan7** [comment]
PC Gaming Wiki only mentions support for the DS4 v.2. It might be possible that the DS4 v.1 might not be supported. If that is the case then support would not work as ViGEmBus only supports creating a virtual DS4 v.1.

https://www.pcgamingwiki.com/wiki/WRC_9:_FIA_World_Rally_Championship

**Comment by IceLancerSR** [comment]
> 
> 
> PC Gaming Wiki only mentions support for the DS4 v.2. It might be possible that the DS4 v.1 might not be supported. If that is the case then support would not work as ViGEmBus only supports creating a virtual DS4 v.1.
> 
> https://www.pcgamingwiki.com/wiki/WRC_9:_FIA_World_Rally_Championship

ah , that is the info i didn't knew. So no V2 emulation ? that sucks. This game developers..there was only one game where i saw that devs did it really professionally. They didnt bother with what controller u have, they simply gave u option to choose button promts in config. Ys - Memories of Celceta

I would like if someone with V1 gamepad can confirm that V1 indeed is not supported

**Comment by zsohu** [comment]
I have a V1 controller and exclusive mode and ds4 emulation both working. I don't have WRC 9 but it was okay with MK11 and Death Stranding. The only thing what didn't work was the touch input (swipe for some action) in Detroit.

**Comment by IceLancerSR** [comment]
> 
> 
> I have a V1 controller and exclusive mode and ds4 emulation both working. I don't have WRC 9 but it was okay with MK11 and Death Stranding. The only thing what didn't work was the touch input (swipe for some action) in Detroit.

alright, but that's not the issue. But if u do managed to get WRC 9 do please test with ur V1 gamepad

**Comment by IceLancerSR** [comment]
i guess i should close this as its nothing that can be done due to vigembus support
