### ISSUE TITLE
Inputs are doubled when PS4 controller is plugged in. 

### ISSUE THREAD

**Issue by shoeles** [Ryochan7/DS4Windows#1542]
**Describe the bug**
Controller inputs are being recognized twice as many times as they should be. 

**To Reproduce**
1. Open DS4
2. Connect PS4 controller to PC via USB to Micro USB cable
3. Run any game

**Screenshots**

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: [e.g. Windows 10 Pro Build 2004]
 - DS4Windows Version 2.1.15

**Additional context**
On Minecraft Dungeons, the game recognized the controller as Player 2 and didn't try to switch Player 1 to the controller.

**Comment by Ryusennin** [comment]
Your games detect both the physical Dualshock and the emulated Xbox pad.

You need to install [HidGuardian](https://github.com/Ryochan7/DS4Windows/wiki/DS4Windows-and-HIDGuardian-Install-and-Setup-Guide) (use the HidGuardian Test Installer) to hide the physical DualShock. You can also try the old "Hide DS4 Controller" option in the Settings tab, but it's deprecated and won't work in many recent games.

**Comment by mika-n** [comment]
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues
