### ISSUE TITLE
Minimize to Taskbar option is inverted.

### ISSUE THREAD

**Issue by SubsonicBeatz154** [Ryochan7/DS4Windows#1543]
**Describe the bug**
The "Minimize to Taskbar" option's values in the UI are inverted, meaning off is on, and on is off. This had me scratching my head as to why I suddenly couldn't minimize the app to the taskbar anymore...

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: Windows 10 Home Build 2004
 - DS4Windows Version 2.1.15

**Additional context**
This was not an issue in the previous version, so something must have broke in 2.1.15.

**Comment by Ryochan7** [comment]
It is working as expected for me with version 2.1.15.

**Comment by mika-n** [comment]
can't replicate the issue even in Win10 20H2 version.
