### ISSUE TITLE
Special Action: Ignore Trigger if a user specified button is currently being held

### ISSUE THREAD

**Issue by vvilkommen** [Ryochan7/DS4Windows#1548]
Hello again!

I have an odd feature request, I think. I have made a special action trigger in ds4w that is quite comfortable to the hands, feels natural, and is very muscle memorized. My problem is that the trigger is quite similar to one handled outside ds4w that would be frustrating to change. I know this is probably an extreme edge case, but I would like to ask for something like this:

(This trigger combination is simplified for illustrative purposes)
Example: A Special Action Trigger in ds4w is Triangle Circle, but Game has another, unrelated combination: L2 Triangle Circle. 

If I press only Triangle Circle in the game, I get the expected special action from ds4w, say... double jump. But if I press the external to ds4w Combination of L2 Triangle Circle, not only does the game's action go off, the ds4's action does as well due to the overlap. This is certainly expected! But, does it have to be? dun dun DUN.... what if ds4w allowed me to specify, in this case, L2 as an ignore special action button (like, a new option "[ ] Ignore if this button is being held: [Clicky Box to specify the button]" could be added under "[ ] Unload on trigger release") in the Special Actions "Edit" area. Then, when I press L2 Triangle Circle, the game does its thing, but ds4w holds itself back, seeing that the no-no button, L2 in this instance, is also being held.

**Comment by mika-n** [comment]
something like this has been proposed few times in the past. I can certainly see benefits of that, but the bad news is that the whole macro engine in the code base is a bit of a mess (legacy derived code). It is not easy to tweak it without breaking something else.

However, maybe you could do this other way around:
- Don't use special action. Instead bind a macro to the triangle button (via the mapping screen where you can see the keyboard and ds4 button layout)
- Then define a shift modifier to the triangle button and set L2 as the modifier btn. Don't bind the macro to this shift-modified version of triangle (leave it as "triangle" event).

Not sure if this works in this case, but feel free to try it

**Comment by Ryochan7** [comment]
Don't really like the idea and I don't see myself getting around to implementing this. Dead in the water
