### ISSUE TITLE
DS4Windows not starting.

### ISSUE THREAD

**Issue by bobogaEX** [Ryochan7/DS4Windows#1552]
Been having a problem with DS4 windows 2.1.15.

since i downloaded, it would not start up at all, nor is it shown in my task manager. i checked logs and it tells me 

"2020-11-07 01:50:06.7310|INFO|LinkedProfiles.xml can't be found." i tried deleting the path that lead to the profiles and tried re-installing normally, but still wouldnt start up.

is there any insight to this?

**Comment by Ryusennin** [comment]
Maybe you tried to install it in a restricted folder (like Program Files). Try another location.

**Comment by Toka-mk** [comment]
I was having the same problem and I solved it by downloading the 64 bit version manually. I updated from an old 1.5 version on my computer and the auto-updater defaults to x86 version I think.

So if your system is x64, make sure you're downloading the x64 version from the release page.

**Comment by mika-n** [comment]
please provide the whole logfile as TXT attachment here (rename the logfile to TXT file and attach here).

**Comment by mika-n** [comment]
closed as inactive ticket
