### ISSUE TITLE
vibration dont work

### ISSUE THREAD

**Issue by AndrijReally** [Ryochan7/DS4Windows#1553]
vibration dont work when emulated controller is dualshock 4
![image](https://user-images.githubusercontent.com/34485522/98440824-b7f77b00-2103-11eb-9acc-1578ed33b61d.png)

**Comment by Dark360** [comment]
I am having the same issue. However I dont know if the issues is present prior to 2.1.16 as I just found this option.

**Comment by mika-n** [comment]
Rumble support is disabled in dualshock4 mode at the moment. The debug version does support it, but the code change is not yet in the official release. DS4 and rumble used to work but some games had weird problems with rumble and ligthbar, so the support was disabled and no option for user to enable it it. The new code change re-enables that (or a profile can choose to use rumble and/or ligthbar or ignore it).

**Comment by AndrijReally** [comment]
> Rumble support is disabled in dualshock4 mode at the moment. The debug version does support it, but the code change is not yet in the official release. DS4 and rumble used to work but some games had weird problems with rumble and ligthbar, so the support was disabled and no option for user to enable it it. The new code change re-enables that (or a profile can choose to use rumble and/or ligthbar or ignore it).

where i can download debug version?

**Comment by Ryusennin** [comment]
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting

**Comment by AndrijReally** [comment]
on debug version vibration still don't work.

**Comment by mika-n** [comment]
Here the rumble works in dualshock4 mode when using the debug version:
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

Try downloading the latest debug version and provide the latest logfile here if it still doesn't work (rename the latest logfile as TXT file and attach to a comment field).

**Comment by AndrijReally** [comment]
> Here the rumble works in dualshock4 mode when using the debug version:
> https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems
> 
> Try downloading the latest debug version and provide the latest logfile here if it still doesn't work (rename the latest logfile as TXT file and attach to a comment field).

[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/5591237/ds4windows_log.txt)

> What happens when you press "Test rumble" buttons in DS4Windows profile editor?

gamepad is vibrating, but not in game

**Comment by mika-n** [comment]
How about what happens when DS4Windows is running and you navigate to https://gamepad-tester.com/ web site and press a button on the controller and then "Vibrate" text link on the web page? Does the controller rumble?  If it does then the problem must be in the game you are using.

**Comment by TheMasterDingo** [comment]
i have the same problem , vibration works when testing with ds4 app , it does not work on the emulated controller (in game and in the website test)

**Comment by mika-n** [comment]
@TheMasterDingo Do you have a DS4Windows profile in xbox360 or dualshock4 output mode? 
The ds4 virtual output mode doesn't support vibrations at the moment (xbox360 mode does support). The code change is already submitted and the next official release should support vibrations in DS4 output mode also.

**Comment by AndrijReally** [comment]
> How about what happens when DS4Windows is running and you navigate to https://gamepad-tester.com/ web site and press a button on the controller and then "Vibrate" text link on the web page? Does the controller rumble? If it does then the problem must be in the game you are using.

vibrate button works only on one of two controllers. I will test vibration in GTAV

**Comment by AndrijReally** [comment]
in GTAV vibration don't works too

**Comment by TheMasterDingo** [comment]
> @TheMasterDingo Do you have a DS4Windows profile in xbox360 or dualshock4 output mode?
> The ds4 virtual output mode doesn't support vibrations at the moment (xbox360 mode does support). The code change is already submitted and the next official release should support vibrations in DS4 output mode also.

In xbox output works fine, in ds4 output does not work, i mostly use the app for bt ds4 emulation

**Comment by mika-n** [comment]
The vibration doesn't work yet in DS4 output mode, but the next official release should have that support re-enabled.
At the moment you might wanna try the debug version which already have this DS4 rumble support.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems
