### ISSUE TITLE
Step 2 sey me :"Please , go in the fucking ass"

### ISSUE THREAD

**Issue by nova5223** [Ryochan7/DS4Windows#1554]
**Describe the bug**

**To Reproduce**
1. Go to DS4Windows.'
2. Click on 'Step 2 '
3. See error and program does not respond 
My system - Windows 7

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: [e.g. Windows 10 Pro Build 2004]
 - DS4Windows Version [e.g. 2.1.5]

**Additional context**

**Comment by nova5223** [comment]
https://user-images.githubusercontent.com/74104100/98443373-ed0fc780-211b-11eb-9555-8c0611ac946a.png

**Comment by rocketbucket10** [comment]
So DS4Windows crashes when you try to install the 360 drivers?
I got some questions:
Are you on x86 or x64?
Have you tried using an older version of DS4Windows?
Are you using rev 1 or rev 2?
Have you tried installing Xbox 360 drivers from another source?

(funny title by the way, made me laugh)

**Comment by mika-n** [comment]
closed because of inactivity from the orginal poster
