### ISSUE TITLE
Very high latency every 2-3 seconds, lightbar flashing red

### ISSUE THREAD

**Issue by axonll** [Ryochan7/DS4Windows#1556]
**Describe the bug**
Very high latency that occurs every 2-3 seconds, can tell due to the lightbar flashing red whenever it happens

**To Reproduce**
1. Open DS4Windows
2. Connect controller via Bluetooth

**Expected behavior**
Latency that isn't as high as it is at the moment

**Screenshots**

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2E)
 - OS: Windows 10 Pro Version 1909
 - DS4Windows Version 2.1.14

**Comment by mika-n** [comment]
BT connection maybe and not USB? Try to see if any tip in the following web page helps. If those tips don't help then you may be out of luck.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#gamepad-connection-over-bluetooth-bt

**Comment by mika-n** [comment]
closed because of inactivity
