### ISSUE TITLE
Hexadecimal value 00x0, is an invalid character.Line 1, position 1.

### ISSUE THREAD

**Issue by maphole** [Ryochan7/DS4Windows#1558]
**Describe the bug**
After a force restart of the pc due to it freezing i got this error. The controller is being recognized but it doesn't work at all.

**Screenshots**
![image](https://user-images.githubusercontent.com/74244891/98671214-32b6d500-2354-11eb-99bf-abd1919ffc1d.png)

**Desktop (please complete the following information):**
 - Controller Make and Model: Nacon Revolution Pro v1
 - OS: Windows 10 Build 1909
 - DS4Windows Version 2.1.16

**Comment by Ryochan7** [comment]
That error would seem to imply some config file got corrupted. The next line in the Log should probably be regarding the virtual controller being plugged in. Can you check your OutputSlots.xml config file?

**Comment by maphole** [comment]
Sorry but I can't find the .xml file you mentioned

**Comment by Ryochan7** [comment]
Are you using the Program Folder option for storing config files or AppData?

**Comment by maphole** [comment]
Found it:
<?xml version="1.0" encoding="utf-8"?>


<OutputSlots app_version="2.1.16" />

**Comment by maphole** [comment]
![image](https://user-images.githubusercontent.com/74244891/98676270-aad4c900-235b-11eb-95ea-d2d1e3588ea9.png)

**Comment by Ryochan7** [comment]
Okay. That looks normal so it has to be something else.
