### ISSUE TITLE
After uninstalling DS4Windows Xbox controller not working

### ISSUE THREAD

**Issue by kaniamac** [Ryochan7/DS4Windows#1559]
Hi guys, 

I had DS4Windows installed and used it with my DS4 controller on my PC. However my DS4 controller broke recently and I bought an xbox one wireless controller. I have uninstalled DS4Windows, the Vigem bus driver and even used the SCP toolkit to uninstall all drivers. The issue is that my xbox one wireless controller works flawlessly when connected via usb, but when it's connected through bluetooth it works on websites like gamepad-tester.com but doesn't work in any games. I assume it's because of some DS4 drivers still left behind that emulate the controller. Please can someone give me some tips on how to completely wipe all DS4 stuff and fix this?

Thanks

**Comment by mika-n** [comment]
Highly doubt that any DS4Windows left over could cause something like that. 

HidGuardian could do something, but then again HidGuardian with DS4Windows never tried to hide xbox controllers. And HidGuardian was an additional component and not required to run DS4Windows.

SCPToolkit is notorious to hijack the whole BT device if you have linked the SCPToolike to a specific BT interface.  However, DS4Windows haven't used SCPToolkit/ScpVBus driver in ages. But of course you could have left overs of SCPToolkit/ScpVBus from an ancient versions.
https://forums.vigem.org/topic/250/scptoolkit-removal-guide

**Comment by kaniamac** [comment]
Thanks a lot for your help. 

I used the DriverStore Explorer tool from your link to delete some old drivers and now it's all working.
