### ISSUE TITLE
What are notifications?

### ISSUE THREAD

**Issue by lifehome** [Ryochan7/DS4Windows#156]
I am seeing the word "notification" everywhere, profiles and settings. But none of which indicates where exactly the "notification" shows???

I suggest re-implementing the feature as Windows 10 native notification, such as it prompts when controller is under 20% of battery level, or the BT signal is too weak that the input delay is large enough to create bad gaming experience.

**Comment by Ryochan7** [comment]
Notifications appear as native Windows notification alert messages. Notifications will appear when DS4Windows is not in focus and certain events occur like a controller connecting or disconnecting, if input latency goes higher than the set time frame (20 ms) or exclusive access to a controller cannot be obtained. Enabling Warnings Only for the Show Notifications setting would mean that DS4Windows will not display a notification message for certain events like controller connects and disconnects.

**Comment by lifehome** [comment]
As the fact that I am raising this issue, is because of DS4Windows is not showing any form of notifications.

I have tried to configure my "Share" key as a check of remaining battery status, both "notification" and "lightbar" has been checked. The lightbar works as it should, but not the "notification". That I can only check the real time value through hovering on the DS4Window tray icon...

Soooo, is that a bug?

**Comment by Ryochan7** [comment]
Notifications pop up on my system for the Check Battery special action.

**Comment by lifehome** [comment]
Closing issue until problem can be reproduced properly.
