### ISSUE TITLE
buttons work but vibration doesn't work

### ISSUE THREAD

**Issue by kakashidinho** [Ryochan7/DS4Windows#1561]
**Describe the bug**
I'm using my DS4 controller with DS4Windows. It is detected and the buttons are mapped to X360 buttons without any issue. However the vibration doesn't work, using test heavy and test light button result in nothing vibrate. Vibration also doesn't work in games (except Witcher 3 which supports DS4 natively). It's strange because when connecting my DS4 to PS4, it can vibrate fine.

**To Reproduce**
1. Connect DS4 to Windows.
2. Run DS4Windows.
3. Click Rumble's "Test Heavy"/"Test Light" button.

**Expected behavior**
The controller should rumble.

**Screenshots**

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 (CUH-ZCT1U)
 - OS: Latest Windows
 - DS4Windows Version 2.1.16

**Additional context**

**Comment by kakashidinho** [comment]
it is also worth noting that the light bar control also doesn't work.

**Comment by kakashidinho** [comment]
More note: Using gamepad tester website https://gamepad-tester.com/, vibration works for "Wireless Controller" but doesn't work for emulated "X360 controller"

**Comment by w1lddog2** [comment]
Same here rumble was working just fine till today. Same issues kakashidinho as "wireless controller" works just fine but  doens't work as an emulated 360 controller.

**Comment by mika-n** [comment]
if the "Test Rumble" btn or "Lightbar" doesn't work and the gamepad is not a genuine DS4 gamepad then it may be that the 3rd party controller is not 100% compatible. This is often the case with many copy-cats over BT connection. The same gamepad may work just fine over USB.

But, the OP poster seem to have the real thing, so the case is a bit more interesting. The same result over BT and USB with the TestRumble button?

When DS4Windows app is NOT running then does rumble work in https://gamepad-tester.com/ gamepad test app?

**Comment by w1lddog2** [comment]
It seems my ds4windows profile was bugged, because i deleted the profile, made a new one and it's working again.

**Comment by kakashidinho** [comment]
> if the "Test Rumble" btn or "Lightbar" doesn't work and the gamepad is not a genuine DS4 gamepad then it may be that the 3rd party controller is not 100% compatible. This is often the case with many copy-cats over BT connection. The same gamepad may work just fine over USB.
> 
> But, the OP poster seem to have the real thing, so the case is a bit more interesting. The same result over BT and USB with the TestRumble button?
> 
> When DS4Windows app is NOT running then does rumble work in https://gamepad-tester.com/ gamepad test app?

When DS4Windows is not running, ps4 controller's vibration still works on the gamepad tester website. When DS4Windows is running, there will be two gamepads detected on that website:
- the 1st one is the emulated xbox controller (vibration doesn't work)
- the 2nd one is the original DS4 controller (vibration works).

FYI I was using USB connection the whole time, not BT. Vibration also works if connecting to PS4 itself. Which means the method DS4Windows is using to send vibration data to the controller DOES NOT work for my controller (but PS4 and Chrome some how do it correctly).

I took a look at Chromium source code to see how it sends vibration data to DS4 controller, this is their source code: https://github.com/chromium/chromium/blob/1d6b29cd85c1c3cba093b8b69b2727cc26eaac97/device/gamepad/dualshock4_controller.cc#L235

The only thing different between chromium code and DS4Windows code is that Chromium only sends 2nd byte = 0x1 (only vibration) while DS4Windows set this byte to 0xf7.

I follow Chromium code and made a change to DS4Windows on my fork here, and the vibration as well as lightbar are now working for my controller:
https://github.com/kakashidinho/DS4Windows/blob/c95c671e3d380d3510fc5cfc8d67c6e1488a3b86/DS4Windows/DS4Library/DS4Device.cs#L1381

**Comment by mika-n** [comment]
Hmm.. Veeery interesting. You seem to have the DS4 revision1 gamepad and the output report bitflag for rumble and lightbar has been the same for years.  Maybe there are a bit different DS4 rev1 firmware versions. Do you remember when you purchased the DS4 gamepad? Did it came with the first set of PS4 consoles or have you purchased it recently (except that Sony haven't manufactured official DS4 rev1 gamepads for years, only some copy-cats these days use the rev1 hardware id)?
 
Few months ago there were slight changes in these output report data values, but not in that bitfield.

**Comment by kakashidinho** [comment]
You might be right. I have my original PS4 controller that came with the console, it works properly with DS4Windows, though its square button has been broken. I bought this new replacement controller from a retail shop (it was indeed cheaper than official ones, but they said it is a promotion discount). You might be right, this could be a copy cat.
However it works fine with my PS4, so it would be quite difficult to prove that it is a fake to request a refund.

**Comment by mika-n** [comment]
Often those DS4 copy-cats struggle to work over BT. Communication is unreliable, lag (and this way DS4Windows app shows a warning log message and flashes lightbar because of "too big" latency). The same gamepad may work just fine over USB.

**Comment by kakashidinho** [comment]
I think mine is indeed copycat. I just noticed that its joystick data is square instead of circle like the official ones. This has some issues in games expecting circle joystick data such as Divinity Original Sin.
Not sure it is a valid reason to refund
