### ISSUE TITLE
internal bug with the game call of duty: cold war

### ISSUE THREAD

**Issue by KIDZZJC** [Ryochan7/DS4Windows#1564]
so u get the program running before u load up the game rigth? its suppossed to see that ds4 controller as an xbox one but when u go inside call of duty: cold war, whenever u click in any button in the controller it changes back to a ps4 one, and if u click in any button again its changes to xbox, and so for it.

**To Reproduce**
1. get the program running before the game starts (cold war)~
2. load up the game
3. click in any button of the controller to spot bug which cosntally changing beetween and xbox controller to a ps4 one.

**Expected behavior**
well i expect to not keep chaging all the time whenever i click in any button  of my controller, i expect to be a considered xbox controller all the time in my gaming exprience.

screenshots:
cant show proper screenshots but u can go try for yourself, load the program first then jump in call of duty cold war and see what happens.

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: [e.g. Windows 10 Pro Build 2004]
 - DS4Windows Version [e.g. 2.1.5]

**Additional context**

**Comment by mika-n** [comment]
Double controller problem?
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

**Comment by spxx33** [comment]
Currently having this issue aswell. For some reason Exclusive mode does not seem to fix the issue unlike others games.

**Comment by Ryusennin** [comment]
Use HidGuardian.
