### ISSUE TITLE
DS4Windows periodically causes Voicemeeter Banana to process audio incorrectly

### ISSUE THREAD

**Issue by nike4613** [Ryochan7/DS4Windows#1565]
**Describe the bug**
Periodically, but only while a DS4 controller is connected through DS4Windows, Voicemeeter Banana (which handles all of my system audio) stops processing audio fast enough to have clean throughput. It becomes extremely static-y, suggesting that its processing is out of sync with its buffer. I *suspect* that it has something to do with the audio output on the controller, though I can't really tell.

**To Reproduce**
I cannot get reliable steps to reproduce, but when it happens, it happens extremely frequently.

The best I can describe is to install Voicemeeter, send all of your system audio through it, then connect a controller and fiddle around with settings in DS4Windows or some game until your audio breaks.

**Expected behavior**
Clean audio regardless of whether or not a controller is connected.

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: Windows 10 Pro 1607 (yes I know its over 4 years old; I would update if I could)
 - DS4Windows Version: 2.1.16
 - Voicemeeter Banana Version: 2.0.5.0

**Comment by Ryusennin** [comment]
Try disabling the wireless controller audio output in Windows sound device manager.

**Comment by mika-n** [comment]
closed as inactive ticket
