### ISSUE TITLE
DS4Windows + v.1 DS4 + Strikepack  on  Call of Duty

### ISSUE THREAD

**Issue by MRog40** [Ryochan7/DS4Windows#1566]
Using DS4Windows + v.1 DS4 + Strikepack on Call of Duty: Warzone. I'm trying to get my controller to show up as a normal DS4.

I looked at [#882](https://github.com/Ryochan7/DS4Windows/issues/882) and trying to follow Chris Ayala's final comment, but it was lacking some of the details I think I'm missing.

In DS4 windows, my DS4+Strikepack shows up like this:
![image](https://user-images.githubusercontent.com/47461109/99142759-c53dc980-261d-11eb-9ccd-c3713f478636.png)

Controller light stays off, and no controller is recognized in game. Note the 0% battery.

The HID devices show up as:
![image](https://user-images.githubusercontent.com/47461109/99143102-9f65f400-2620-11eb-83d2-f98aa4d7131a.png)

Controller readings here do nothing:
![image](https://user-images.githubusercontent.com/47461109/99143114-aee53d00-2620-11eb-9526-f333eddd72e7.png)

But in the Control Panel -> Game Controllers menu, it shows up as 
![image](https://user-images.githubusercontent.com/47461109/99143153-e358f900-2620-11eb-803f-d38bc4d4fd83.png)
And works fine. Even the paddles register correctly as the buttons they were programmed to be.

Here are my settings in Profiles -> Other to try and make it show up as a DS4 in game: 
![image](https://user-images.githubusercontent.com/47461109/99143230-77c35b80-2621-11eb-8eba-25dd04718054.png)

And here is my log: 
![image](https://user-images.githubusercontent.com/47461109/99143395-98d87c00-2622-11eb-928f-6508e336a815.png)

**Comment by Ryusennin** [comment]
I'm not familiar enough with the Strikepack, but DS4Windows (more precisely the underlying ViGEm driver) doesn't support v1 controllers set as emulated DS4. You need a v2.

**Comment by MRog40** [comment]
Are you sure about that? As it reads [in this comment](https://github.com/Ryochan7/DS4Windows/issues/882#issuecomment-550402914), v1 is not an issue for @chris-ayala. I also can plug in my ds4 v1 directly and DS4Windows allows me to set DS4 output mode and it shows up in game, although I'm not sure if that is just the controller by itself.

**Comment by MRog40** [comment]
After trying about everything and reading through debug logs I finally found a comment of a guy on youtube saying he "used the VR port of his motherboard to make the strikepack work". I thought to myself that there is no way this works but then unplugged my Oculus port and plugged in my controller and it immediately worked.
