### ISSUE TITLE
"Minimize to taskbar" flag bug

### ISSUE THREAD

**Issue by sergentum** [Ryochan7/DS4Windows#1567]
I'm using ds4windows 2.1.16 version. 
"Minimize to taskbar" logic is actually inverted.
When the flag isn't set than it minimizes to taskbar.
When the flag is set than it minimizes to task panel.

**Comment by mika-n** [comment]
Here the latest V2.1.16 works as expected:
-"Minimize to taskbar" option set and the app is minimized to the taskbar, not to the notification area (the bottom right corner).
-"Minimize to taskbar" option NOT set and the app is minimized to the notification area (those small icons on the bottom right corner).

**Comment by sergentum** [comment]
Here I recorded my screen:
https://www.youtube.com/watch?v=6dShqf-4o5c&feature=youtu.be

**Comment by FlyingWolFox** [comment]
Mine was doing this too, after an update. Reinstalling solved it

**Comment by sergentum** [comment]
I didn't updated app, I just bought ps4 controller and that's my first installation of ds4win

**Comment by mika-n** [comment]
closed as "cannot re-produce the problem, works here"
