### ISSUE TITLE
Buggy "minimize" issue

### ISSUE THREAD

**Issue by lifehome** [Ryochan7/DS4Windows#157]
- [x] Build 1.4.100

Once ticked the "Start" and "Close" minimize feature, reopening DS4windows may occur in opening a blank and zero-content window, you can see the border, but just nothing in it.

**Comment by javsp** [comment]
Exactly. I was gonna post just that issue.

1.4.99 works fine so it only happens with the last version.

**Comment by Ryochan7** [comment]
I will have to look into this. The commits for that version don't seem to
show any change that would cause a problem.

**Comment by javsp** [comment]
> 

BTW, if I close the program, delete profile.xml and re-open it everything works again (the file creates itself again). So I guess this version writes something in that file that is causing this issue.

**Comment by SeemsFishy** [comment]
Right-click on tray icon and then "Open", now just double-clicking. That should work as a workaround for now, give it a try

**Comment by Ryochan7** [comment]
The issue was due to the introduction of form location saving. When the form is minimized, the X and Y values are negative which will cause problems when DS4Windows is opened again.
