### ISSUE TITLE
'.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.

### ISSUE THREAD

**Issue by zus0** [Ryochan7/DS4Windows#1572]
**Describe the bug**
After updating to 2.1.16 got `'.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.`

**To Reproduce**
1. Launch the app
2. See the error.

**Expected behavior**
Nothing.

**Screenshots**
![Screenshot](https://i.ibb.co/SKXR76x/Screenshot-2020-11-16-132745.png)

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony wireless adapter (CUH-ZWA1E)
 - OS: Windows 10 Pro 20H2 (19042.610)
 - DS4Windows Version: 2.1.16

**Additional context**
I think, that something is wrong with the config, I can provide it to you if required.

**Comment by mika-n** [comment]
Probably something wrong in one of the configuration or profile XML files. Maybe localization issue with comma vs period as decimal pointer.

Try creating a new default profile and set it as default for the controller. If it works then the old "Games" profile has something wrong. If the new default profile works then try comparing the new and old one to see which option causes this issue. I suspect some localization issue.

If the same error with a new default profile then some of the general config files have something weird.

%APPDATA%\DS4Windows\ should have all config and profile files.

**Comment by zus0** [comment]
Ok. I've found the problem. For some reason, one of my profiles became a binary file full of zeros. Idk how did that happen, but thanks for quick response!
