### ISSUE TITLE
Very high latency every 2-3 seconds, lightbar flashing red

### ISSUE THREAD

**Issue by axonll** [Ryochan7/DS4Windows#1573]
**Describe the bug**
Very high latency that occurs every 2-3 seconds, can tell due to the lightbar flashing red whenever it happens

**To Reproduce**
1. Open DS4Windows
2. Connect controller via Bluetooth

**Expected behavior**
Latency that isn't as high as it is

**Screenshots**

**Desktop (please complete the following information):**
- Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2E)
- OS: Windows 10 Pro Version 1909
- DS4Windows Version 2.1.16

**Additional context**
I already posted this a week ago but I wasn't available to reply, also I tried https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#gamepad-connection-over-bluetooth-bt but nothing worked

**Comment by consandstuff** [comment]
I had this same problem with my living room PC. Turns out my bluetooth dongle was connected to a front USB port of a metal PC Case that was not properly grounded I guess because the metal in the case was giving signal issues.

I solved it by pluging the dongle in another plastic USB dongle and now the controller has minimum latency even on the other side of the room.

So basically I plugged a USB extension to one of the back USB ports of the PC and then the bluetooth dongle on the USB extension.

**Comment by axonll** [comment]
> I had this same problem with my living room PC. Turns out my bluetooth dongle was connected to a front USB port of a metal PC Case that was not properly grounded I guess because the metal in the case was giving signal issues.
> 
> I solved it by pluging the dongle in another plastic USB dongle and now the controller has minimum latency even on the other side of the room.
> 
> So basically I plugged a USB extension to one of the back USB ports of the PC and then the bluetooth dongle on the USB extension.

Oh. Do you think this is the problem I'm having? I don't wanna buy a USB extension cord just to find out it won't fix the issue :/

**Comment by 12354** [comment]
If you have any issues with high latency(especially using a CSR bluetooth adapter) you can try disabling "Enable output data to DS4".


You can do this by editing your controller settings like this:
Edit => Other(tab on the right) => Disable "Enable output data to ds4"
Afterwards click 'save' and restart DS4Windows to apply the changes.

**Comment by axonll** [comment]
Ok found the problem. It's most likely the distance between me and the dongle. If I'm only 20-25 inches away, there's no noticable input latency. If I move just a tiny bit (10 inches maybe,) the input latency reaches 30..

**Comment by mika-n** [comment]
Try using usb extension cable to move the BT dongle further away from the PC metal chassis and from a radio storm caused by WLAN/PSU in the PC.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#gamepad-connection-over-bluetooth-bt
