### ISSUE TITLE
Vibration don't work properly in some games

### ISSUE THREAD

**Issue by michele-grifa** [Ryochan7/DS4Windows#1575]
**Describe the bug**
The vibration is weak or not working at all with some games i'm playing, specifically:

- SnowRunner: the vibration is weak but working
- Euro Truck Simulator 2: the vibration don't work at all

The profile emulation is set to Xbox Controller and the vibration is on 100%, and i'm connected with BT.

**Expected behavior**
The vibration should work.

**Screenshots**

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.1
 - OS: Windows 10 Pro v1909
 - DS4Windows Version: 2.1.16

**Comment by Ryusennin** [comment]
Vibration works in SCS truck sims if you choose XInput controller instead of X360 (in the game settings).

**Comment by michele-grifa** [comment]
> 
> 
> Vibration works in SCS truck sims if you choose XInput controller instead of X360 (in the game settings).

Choosing XInput instead of X360 worked. In SnowRunner is always weak or not working at all in some cases.

**Comment by Mxater** [comment]
In exclusive mode, vibration work fine in Steam. But must be set Force Steam Input in steam.

Without Steam Input and without exclusive mode, vibration work bad too.

**Comment by mika-n** [comment]
If vibration is weak then check rumble amplifier percentage in profile settings. You can set the rumble percentage value to 0% (=disables rumble) or even >100% to amplify it from the level game tried to send to a gamepad.

Also, at the moment the official release doesn't support rumble in dualshock4 output mode (supported only in xbox360 output mode). However, ds4 rumble will be hopefully re-enabled soon in upcoming versions.
