### ISSUE TITLE
RR and RL channels of DualSense disabled when using DS4Windows

### ISSUE THREAD

**Issue by Freak2121** [Ryochan7/DS4Windows#1578]
I had set up my DualSense via EqualizerAPO so that its RL and RR channels would receive an equalized (only bass frequencies) copy of the L and R audio channels. I'm assuming this functionality was disabled so that XInput vibration could take its place, but is it possible to have a toggle? I rather liked being able to "feel" sounds such as gunshots or horse footsteps through my controller, much more so than the vibration that's there right now.

**Comment by charliekyoot** [comment]
yeah that would be the best, tho there is a ~300 ms delay offset  from onboard audio and controller.

**Comment by Xurca86** [comment]
A toggle would be nice to have. I have a similar setup with Equalizer APO for my DualSense. 

@Freak2121 if you want audio haptic back on you have to disable the set main motors in the coding by changing "outputReport[1] = 0x03" to "0x00". Enabling haptic, but disabling rumble.

**Comment by Freak2121** [comment]
Thanks for the tip, working perfectly now. 👍

**Comment by Freak2121** [comment]
> 
> 
> A toggle would be nice to have. I have a similar setup with Equalizer APO for my DualSense.
> 
> @Freak2121 if you want audio haptic back on you have to disable the set main motors in the coding by changing "outputReport[1] = 0x03" to "0x00". Enabling haptic, but disabling rumble.
