### ISSUE TITLE
Support for Gamepad Switch clone from china

### ISSUE THREAD

**Issue by ivanlakersss2016** [Ryochan7/DS4Windows#1580]
Hello I would like to know if it is possible to make compatible through your application of a Nintendo Switch Clone gamepad purchased in China, I leave the link address so that you can examine it better, it is a fairly cheap and good quality gamepad to be able to use it on PC through bluetooch, thank you.

https://es.aliexpress.com/item/1005001692634162.html?spm=a2g0o.productlist.0.0.14bbe458Vl4BCa&algo_pvid=b666f546-6d4b-4d73-a0d1-2f6afdb4122f&algo_expid=b666f546-6d4b-4d73-a0d1-2f6afdb4122f-1&btsid=2100bdd516058750056098528e0eaf&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_

**Comment by rocketbucket10** [comment]
It's not gonna work with DS4Windows, but you could try x360ce or other Xinput emulators.
Most likely it will show up as a generic Xinput or Dinput device.
