### ISSUE TITLE
Forza Horizon 4 Issue

### ISSUE THREAD

**Issue by TheIrishCanuck** [Ryochan7/DS4Windows#1581]
Using the DualSense 5 controller, it doesn't seem to be working in game. Same issue with before when you needed to use the "Hide DS4 Controller" workaround. Is there a way to get it to work with the new controller and software?

**Comment by stashymane** [comment]
https://github.com/Ryochan7/DS4Windows/wiki/DS4Windows-and-HIDGuardian-Install-and-Setup-Guide
If the issue is FH4 constantly switching between keyboard/controller, setting up HIDGuardian resolved everything for me. The hiding function on DS4W did not work for me.

**Comment by skanderbegv2** [comment]
It works fine for me over Bluetooth; USB causes the keyboard/controller switching every time you press and release a button.

**Comment by Ryochan7** [comment]
Definitely need Exclusive Access working to avoid input conflicts with Forza.
