### ISSUE TITLE
controller vibration does not go in DualShock4 controller emulation mode

### ISSUE THREAD

**Issue by nicolapanzarino** [Ryochan7/DS4Windows#1584]
**Describe the bug**

controller vibration does not go in DualShock4 controller emulation mode, but only in XBOX 360 mode, could you fix it? However, the Dualsense will arrive tomorrow, I am available for testing

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS5 v.1 CFI-ZCT1W
 - OS: [Windows 10 Pro Build 2004]
 - DS4Windows Version [2.1.17]

**Comment by Masamune3210** [comment]
Pretty sure DS4 mode vibration and passthrough was just submitted as a pull request, so it might be coming soon. Don't hold me on that though

**Comment by TheMasterDingo** [comment]
are you trying with the ds4 or the ds? i tried the ds4v2 in emulation ds4 and vibration does not work

**Comment by nicolapanzarino** [comment]
I tried both with DS4 V1, first absolute version, and with DualSense

**Comment by nicolapanzarino** [comment]
it doesn't work either way

**Comment by TheMasterDingo** [comment]
> it doesn't work either way

It is the app, try vers 2.1.4, until that version it works

**Comment by nicolapanzarino** [comment]
okok thanks you, but dualsense is supported?

**Comment by TheMasterDingo** [comment]
> okok thanks you, but dualsense is supported?

Dualsense works only in the latest version of the app

**Comment by mika-n** [comment]
The debug version has the virtual DS4 rumble support (the debug version is based on the latest official release, but there are few additional debug messages and new upcoming features like DS4 rumble support).
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

**Comment by TheMasterDingo** [comment]
> The debug version has the virtual DS4 rumble support (the debug version is based on the latest official release, but there are few additional debug messages/checks/verifications when a gamepad is connected and new upcoming features like DS4 rumble support).
> https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

I tried to add the two debug files in the ds4 windows folder . The app shows the log of the controller but the controller does not show in windows

**Comment by mika-n** [comment]
sorry. I forgot that the latest code changes with dualsense DS5 support is in a separate dualSense branch of the app and the debug version is based on the "official" branch.  So, my bad. The debug version doesn't help you there, it would only help those people using DS4 gamepad and dualshock4 virtual output mode until the next official release is out.

**Comment by nicolapanzarino** [comment]
@mika-n Is it possible to merge the code for DS5 support with version 2.1.4?

**Comment by nicolapanzarino** [comment]
even before the next official version, because otherwise the only way to use the ds5 with rumble is xbox virtual controller

**Comment by TheMasterDingo** [comment]
> sorry. I forgot that the latest code changes with dualsense DS5 support is in a separate dualSense branch of the app and the debug version is based on the "official" branch. So, my bad. The debug version doesn't help you there, it would only help those people using DS4 gamepad and dualshock4 virtual output mode until the next official release is out.

No i tried the debug version with ds4 controller, it shows the log but no controller in the main page

**Comment by nicolapanzarino** [comment]
okok
