### ISSUE TITLE
DS4 v2, charging status constantly changing when bt-connected, and charging not via computer

### ISSUE THREAD

**Issue by pieterjoanUvA** [Ryochan7/DS4Windows#1585]
I just noticed that when charging the DS4 v2 controller via another usb-charger, so not via computer connected usb, and connected via BlueTooth, that the charge level hops. [application version 2.1.17] Windows 10 20h2[nov 2020 update]

eg. 63%, 72%, 87%, 100%, all with the + sign. 
However, the + sign is not always there, and the order of appearing percentages also differs.

So there is something a bit off.

Just letting you know, since the controller works just fine with this cosmetic issue.

Since the more simple 'driver' for supporting the connection-emulation with xbox360,
in my recent windows, the operation is more stable.

Keep up your efforts, those are greatly appreciated by me.

With kind regards,

Pieter Joan

**Comment by mika-n** [comment]
See this explanation.
https://github.com/Ryochan7/DS4Windows/issues/1539#issuecomment-732123472

It is what it is and DS4Windows app doesn't try to level out the fluctuation of battery level value coming from DS4 gamepad. Yes, it might be better to use some kind of "filter" or taking an average or weighted average value from a certain period of time (60 or 120 secs or something) to level out the battery value to eliminate those random highs and lows in the battery value sent by DS4 pad. Who knows what kind of voltage metering the DS4 pad uses internally, so the battery level is probably not an exact math in the hardware level either and those measurements have some fluctuation.
