### ISSUE TITLE
The latest ds4 exe file wont open!

### ISSUE THREAD

**Issue by shanks12345** [Ryochan7/DS4Windows#1586]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: [e.g. Windows 10 Pro Build 2004]
 - DS4Windows Version [e.g. 2.1.5]

**Additional context**

**Comment by mika-n** [comment]
please read the pinned "Read this before posting a new issue ticket" message because now your post really didn't have any relevant information. You simply copy-pasted the template message, so if you are not ready to take the time to help us to help you then why should we take the time to help you?
