### ISSUE TITLE
Half detection of Chinese clone of Switch Pro Controller Diswoe ET16801

### ISSUE THREAD

**Issue by Genosystem** [Ryochan7/DS4Windows#1588]
**Describe the bug**
Chinese clone of Switch Pro Controller(Diswoe ET16801) don't work and don't show under Controller section until the controller power off (by timeout), but if I power on again the "Controller Readings" section don't receive data
With PS5 Dualsense works like a charm.

**Desktop (please complete the following information):**
 - Controller Make and Model: Diswoe ET16801
https://www.amazon.co.uk/Diswoe-Wireless-Controller-Bluetooth-Rechargeable/dp/B07ZTCDY6R
 - OS: [e.g. Windows 10 Pro Build 1909]
 - DS4Windows Version [e.g. 2.1.17]

**Additional context**
DS4 LOG:
11/25/2020 01:32:15: DS4Windows version 2.1.17
11/25/2020 01:32:15: OS Version: Microsoft Windows NT 10.0.18363.0
11/25/2020 01:32:15: OS Product Name: Windows 10 Pro
11/25/2020 01:32:15: OS Release ID: 1909
11/25/2020 01:32:15: System Architecture: x64
11/25/2020 01:32:15: Running as User
11/25/2020 01:32:17: Starting...
11/25/2020 01:32:17: Connection to ViGEmBus 1.16.112.0 established
11/25/2020 01:32:17: Searching for controllers...
11/25/2020 01:32:17: Using Shared Mode
11/25/2020 01:32:17: Found Controller: 22:04:01:02:63:25 (BT) (Switch Pro)
11/25/2020 01:32:17: Plugging in virtual X360 Controller
11/25/2020 01:32:17: Associate X360 Controller for input DS4 #1

**Comment by Genosystem** [comment]
I've attached the debug log of DS4WindowsDebug
[ds4log.txt](https://github.com/Ryochan7/DS4Windows/files/5604958/ds4log.txt)

With this debug version, the controller don't show on timeout of the controller.

**Comment by Ryochan7** [comment]
I can only assume that the routine is getting stuck on the initial handshake somewhere.

**Comment by Genosystem** [comment]
So I am going to do an RMA, the doubt was in case I had an easy solution. 
Thank you!
