### ISSUE TITLE
Dualsense rumble not working in wired DS4 emulation

### ISSUE THREAD

**Issue by TheMasterDingo** [Ryochan7/DS4Windows#1589]
Dualsense rumble not working in wired DS4 emulation, with xbox controller emulation the rumble works, all this in wired not wireless.

EDIT: The problem is present even with ds4 controller when used in exclusive mode.

EDIT 2: the problem is related to the virtual ds4 controller

EDIT 4: Did some testing, it breaks at version 2.1.5, works fine until 2.1.4.

Or is it disabled on purpose?

**Comment by Ryusennin** [comment]
Vibration in emulated DS4 mode has been disabled some time ago because of conflicts between rumble and lightbar.

It will be reactivated in a future version.

**Comment by TheMasterDingo** [comment]
> Vibration in emulated DS4 mode has been disabled some time ago because of conflicts between rumble and lightbar.
> 
> It will be reactivated in a future version.

thanks!

**Comment by nicolapanzarino** [comment]
> Vibration in emulated DS4 mode has been disabled some time ago because of conflicts between rumble and lightbar.
> 
> It will be reactivated in a future version.

I think the rumble vibration is more important than the led, I hope you can have the same idea as me,

**Comment by nicolapanzarino** [comment]
please consider releasing a new version for that alone

**Comment by Genosystem** [comment]
The https://github.com/Ryochan7/DS4Windows/commit/cc8e8189baad204d9c5009e2f783b87f5029ee0f comit reenable the rumble.
