### ISSUE TITLE
Can you fix layout on russian language

### ISSUE THREAD

**Issue by Igorb16** [Ryochan7/DS4Windows#159]
Hello, Ryochan7. 
Can you fix layout on russian language - some elements overlap each other, and i can't set my controller properly. Look at the screenshots.
https://i.imgur.com/sxYSYe5.png
https://i.imgur.com/MsfyKvK.png
Thank you

**Comment by Ryochan7** [comment]
The layout settings of some controls are fairly rigid. I have only looked
at how to make more fluid layouts in Windows forms recently. I will see
what I can do.

**Comment by Ryochan7** [comment]
The layout issues that you mentioned should be fixed now. A new version with the latest changes will hopefully be released in a few days.
