### ISSUE TITLE
[Feature Request] Support for Dualsense Haptics

### ISSUE THREAD

**Issue by jedinjapan** [Ryochan7/DS4Windows#1590]
Currently, when running DS4 Windows, passing through audio to the controller to produce haptics is not possible at the same time, possibly because the haptic motor is being controlled by DS4 Exclusively?

If there is a method to allow DS4Windows to forward older "simple" rumble data to the controller, and somehow blend that with other sound data forwarded from something like Voicemeter, that would be ideal. This would for example allow strong rumble feedback in titles like DOOM or Bioshock, for grenades, while also having a subtle haptic feedback from SFX and music. 

Obviously, having a native audio "forwarding" within DS4Windows would be superb to keep everything controller related in one application, but I believe would be a significantly larger request.

**Comment by Xurca86** [comment]
Reason haptic is not working is because the "set main motors" are enabled for rumble emulation, which disables haptics.

If you want audio haptic back on, you have to disable the set main motors in the coding by changing "outputReport[1] = 0x03" to "0x00". Enabling haptic, but disabling rumble.

**Comment by Ryochan7** [comment]
I have never tried to play audio through the haptics. Maybe the motor flags can be changed to only enable rumble emulation when a rumble effect is requested. I doubt there would be a decent way to try to blend a fake rumble effect with audio being directed to the haptics.

**Comment by jedinjapan** [comment]
You can test the haptics using software in windows to feed a Rear Left and Rear Right surround sound signal to the controller's audio device over USB if you have a Dualsense.

My speculation was this: what if DS4Windows could have two static audio files that produce an approximately similar vibration as the "soft" and "strong" rumble effect signals that are traditionally sent. Thus giving an audio equivalent of "strong" and "weak" rumbles. Then DS4Windows could handle all rumble events on Dualsense via audio interface by sending these sound files to the VCA motors. This would have DS4Windows effectively acting as an emulation layer to convert the motor rumbles to a haptic equivalent. But would open up the haptics for use at all times.

Ideally these "audio" rumbles could be blended with other sounds eventually either via a DS4Windows (ideally) or 3rd party software that feeds sound to the Dualsense as well. It is a considerably large enhancement to consider, but it at least seems possible in theory.

**Comment by Ryochan7** [comment]
For future reference, it looks like one output report with the mode change has to be sent to the controller before rumble behavior changes take effect. Sending two output reports for every rumble effect start would be required if the motor flag change would occur.

**Comment by izlom777** [comment]
Can you add checkbox that will switch between rumble emulation or haptics? Thank you.

**Comment by token0** [comment]
And maybe the third option to consider in the future: mix rumble (convert effects to soundwave) and sound haptics, to output them both.

**Comment by maestrini** [comment]
Such a checkbox, to disable rumble and leave the haptics opened, would be amazing, so that (until DS4Windows supports haptic feedback, if ever [btw. if you need a programmer to do that, i am willing]) we could use third party tools to achieve similar outcomes WHILE using DS4Windows. Currently it is either rumble with DS4Windows or Haptic Feedback in combination with x360ce or games that support the DS5 out of the box.
Generally I would like to use the moment of my first comment on your git repo to thank you for your great work @Ryochan7

**Comment by Ryochan7** [comment]
There has been an option for the past few releases of DS4WIndows to either use rumble emulation or disable rumble emulation. It is available under Settings > Device Options and the option can be changed per DualSense controller. Rumble emulation is enabled by default.

That is about as much that can be done. I have tried using audio haptics through Voiceemeter a few times and I didn't really like it. At least that option is open for people know might want to use it.
