### ISSUE TITLE
Auto Profiles not working for Network Drives

### ISSUE THREAD

**Issue by DoganM95** [Ryochan7/DS4Windows#1593]
Auto Profiles works fine for programs on e.g. C:/ drive.

But When starting programs from a Network Drive, e.g. \\\\NAS mapped to Drive N:/
(under Windows go to This PC -> Computer -> Map Network Drive)
DS4W does not change profiles when opening the program specified from N:/

**Comment by Ryochan7** [comment]
I can only assume Windows is choosing a different mount point sometimes when the drive is connected. The full drive path is stored in the config file so the mount point is not allowed to change for a Network Drive. I don't think Windows would report data any differently, in this circumstance, for an executable launched from a Network Drive.

**Comment by mika-n** [comment]
Enable the "Show auto-profile debug messages"  and then take a look at the logfile to see if you can see why the app is not always automatically identified (different path and/or window title?)

If the path or wnd title is not always the same then you can use whildchar logic to identify the process path or windows title. There are "begins with / ends with / contains" type of search tags.
https://github.com/Ryochan7/DS4Windows/wiki/Profile-selection-using-auto-profile-rules

**Comment by mika-n** [comment]
closed because of inactivity
