### ISSUE TITLE
DualSense Mic LED Always on, no current way to disable, Issue with mic, feedback audible with button presses meaning others can hear stick flicks, bumper presses etc.

### ISSUE THREAD

**Issue by Diolusion** [Ryochan7/DS4Windows#1594]
**Describe the bug**
When the mic is enabled as the default mic, it is amazingly clear and sounds great, the main issues with it are, the mic button on the controller does not mute/unmute the mic therefore it is rendered useless atm, the mic itself picks up the presses of buttons, flicking of the sticks and bumpers, the actual LED light itself says illuminated when it is connected via USB C. 

**To Reproduce**
Plug the controller in and set your defualt device for audio input to wireless controller mic.

**Expected behavior**
A clear and audible voice from the user without background feedback, this is an issue im sure to do with pc not being able to benefit easily from Sony's Active noise cancelling without their own software, this would be amazing if it is something you can implement yourself later down the lines. The LED would be alot nicer if it was able to be turned off (By LED i mean the orange mic button). Also having the mic mute functionality would be amazing.

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DualSense (CFI-ZCT1W)
 - OS: Windows 10 Pro Build 2004
 - DS4Windows Version [2.1.17]

**Additional context**
Thanks for the support on the controller so far, im very much enjoying it and am super appreciative of the software you have made, i only write this ticket to try and help you identify areas to improve further.

**Comment by Genosystem** [comment]
In the commit [9d181c5](https://github.com/Ryochan7/DS4Windows/commit/9d181c554ca34029946c6d5fa02e2f8799189c44) the led has been disabled. Wait for the next release.

**Comment by Ryochan7** [comment]
Declaring this out of scope
