### ISSUE TITLE
Use smoothing udp server settings

### ISSUE THREAD

**Issue by Vladimir-Str** [Ryochan7/DS4Windows#1595]
If I deactivate the use smoothing setting some gyro vibration is transmitted to the Cemu app, if use it, all is ok, but I can't find some info what settings I need to setup for optimaly work.
Sometimes "Use smoothing" field values reset to 0 after I uncheck and check again  checkbox "Enable server" or "Use smothing"

**Comment by Ryochan7** [comment]
Doesn't happen on my end. All those related options can be toggled as intended and the smoothing Beta and MinCutoff values stick.
