### ISSUE TITLE
Critical Bug - Cannot Play Steam Games - Dualsense

### ISSUE THREAD

**Issue by AlexRux** [Ryochan7/DS4Windows#1603]
**Describe the bug**
DualSense popup as Xbox360 Controller and Wireless Controller Too. 
e.g. in Rocket League and The Binding Of Isaac, I can't play because it is seen as two separate controllers. 

**Screenshots**
![image](https://user-images.githubusercontent.com/45176956/100515390-20260380-317c-11eb-8e40-c493d4e28522.png)
![image](https://user-images.githubusercontent.com/45176956/100515437-86128b00-317c-11eb-9335-fe232eaf7bfc.png)

**I have a single controller connected to the pc**
![image](https://user-images.githubusercontent.com/45176956/100515456-aa6e6780-317c-11eb-9b9d-8feccbdd810e.png)

Controller Make and Model: Sony DualSense
OS: Windows 10 Pro
DS4Windows Version 2.1.17

**Comment by Ryochan7** [comment]
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

**Comment by AlexRux** [comment]
> https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

Thanks. I can say that the problem was "Gif Your Game" This must be closed or exclusive mode will not work. You can add in the info.
