### ISSUE TITLE
Translation feature seems broken in Version 2.1.18

### ISSUE THREAD

**Issue by SyaoranChang** [Ryochan7/DS4Windows#1604]
Hi,

Translation feature seems broken in Version 2.1.18

![Snipaste_2020-11-29_03-29-09](https://user-images.githubusercontent.com/18550228/100524431-25726500-31f3-11eb-8037-0a2df215c10d.png)

**Comment by rocketbucket10** [comment]
Did you restart DS4Windows after selecting the language?

**Comment by Ryochan7** [comment]
Borked it from feeling like I had to rush a release after trying to get my PC to boot for several hours. The issue is caused by commit b42bca0e564647c5bb69098ba69d524d2e8c7db2. The assembly binding was commented out for the Lang folder as well as the libs folder. The one directive was still needed.

**Comment by Ryochan7** [comment]
Version 2.1.19 fixes this problem.

https://github.com/Ryochan7/DS4Windows/releases/tag/v2.1.19
