### ISSUE TITLE
[Req] More text strings for translation

### ISSUE THREAD

**Issue by shikulja** [Ryochan7/DS4Windows#1606]
Can translation files be generated automatically?
The current files are missing a lot of strings, and some of them are very much mixed up.

Some of them, because everything is very difficult to find:

![image](https://user-images.githubusercontent.com/3386359/100550609-37541680-328c-11eb-9b5d-fcb2ee0f24cf.png)

![image](https://user-images.githubusercontent.com/3386359/100550627-5783d580-328c-11eb-82ca-e1a3ba9ec477.png)

![image](https://user-images.githubusercontent.com/3386359/100550668-9580f980-328c-11eb-9294-cb86f32cfe66.png)

![image](https://user-images.githubusercontent.com/3386359/100550734-f4df0980-328c-11eb-8372-951c25b3cd9b.png)

**Comment by shikulja** [comment]
![image](https://user-images.githubusercontent.com/3386359/100550922-826f2900-328e-11eb-8511-369d9e24a769.png)

![image](https://user-images.githubusercontent.com/3386359/100550924-92870880-328e-11eb-8a2f-2f162f2ca431.png)

![image](https://user-images.githubusercontent.com/3386359/100550931-a29ee800-328e-11eb-955b-d4378b852d8c.png)

![image](https://user-images.githubusercontent.com/3386359/100550947-b5192180-328e-11eb-92bc-23f9b6ce2c96.png)

![image](https://user-images.githubusercontent.com/3386359/100550954-bcd8c600-328e-11eb-95e8-92fef2a89b41.png)

**Comment by mika-n** [comment]
Yes. Feel free to add more translated strings. Translations are left to community. Most texts are translatable, but someone should make those english->somethingElse translations. Maybe you can do it for your language?

**Comment by shikulja** [comment]
I have already added all missing lines from Strings.cs.resx for Strings.ru.resx, and made a pull request
https://github.com/Ryochan7/DS4Windows/pull/1610

!!But those text strings in the screenshots above are still not in the standard language (english) for Strings.cs.resx

**Comment by mika-n** [comment]
True. When this new WPF GUI was introduced then some of the gui labels were accidentally dropped from the translation string table. Those have been added back one by one, but there is still a lot to do in that case. I guess most developers use the GUI either in English or Finnish, so re-adding those missing strings back to localization table is "will be done when motivation/time/memory cells have enough capacity to do it"

**Comment by shikulja** [comment]
Yes, I understand, just hinting that we need to do this.
Because the interface looks terrible, because the interface is in two languages ​​at the same time. This can be seen from the images.

It's strange that can't generate a translation file automatically, excluding unnecessary terms (like "%" symbols)

**Comment by Ryochan7** [comment]
I was hoping for more community involvement in this task. Pretty much have to wait for when/if I feel like getting to it.

**Comment by mika-n** [comment]
> @mika-n
> Yes, I understand, just hinting that **we** need to do this.

This is probably on low priority in the TODO list of various developers. More help is more than welcome to polish the GUI and to add those missing translatable string resources (ie hardcoded strings in the code moved to Strings resource file).

**Comment by RedDevilus** [comment]
I've added the current translatable strings (the ones which Ryochan himself added to the main english template) as a placeholder for now but i haven't added the other ones due to being busy on other projects.

**Comment by shikulja** [comment]
Will have to wait even longer as I saw a request to add new rows over a year ago)
