### ISSUE TITLE
DualSense USB Polling Rate

### ISSUE THREAD

**Issue by RyuMakkuro** [Ryochan7/DS4Windows#1608]
I haven't seen any information on the interwebs clearly stating what's the USB polling rate for the DualSense. Checking in the DS4Windows it seems by default it opts to 285Hz (3.5ms). I'm wondering if it's possible to get it to 1000Hz or is it once more blocked by the hardware as with DS4v1?

I've also seen some conflicting reports where people stated the DS4v2 had 250Hz polling rate through USB, but then others claiming on PS4 with some low latency USB the wired is much better than BT which would indicate it's more of an issue where the hardware needs to inform it's 1000Hz compatible (if that's even a thing).

I know this is only 2.5ms increase in delay at worst, but considering the bluetooth on my end is super unreliable (I orientate the gamepad in a specific way, suddenly 20ms+ delay) I would really appreciate some work done to try and get this supported. In games like Tekken, it can really help big time in making sure the input isn't ghosted/dropped which naturally means you can actually perform combos, punish correctly, block etc.

Love the work done so far btw.

**Comment by dogtopus** [comment]
The "suggested" polling rate is 6ms in the descriptor. From the packet capture from DS5 to PS5 it seems that the interval was about 4.2-4.5ms.

Also adaptive polling rate is only for DS3 IIRC. DS4 is 250 over USB and ~800 over Bluetooth.

**Comment by TheMasterDingo** [comment]
on bluetooth the controller readings say 1ms and in usb 3-3.5ms for the dualsense in ds4windows

**Comment by RyuMakkuro** [comment]
> The "suggested" polling interval is 6ms in the descriptor. From the packet capture from DS5 to PS5 it seems that the interval was about 4.2-4.5ms.
> 
> Also adaptive polling rate is only for DS3 IIRC. DS4 is 250 over USB and ~800 over Bluetooth.

I'd like to point out I did not ask what is the polling rate for DS4 or DualSense on their respective platforms. Furthermore DS4 easily does 1000Hz over Bluetooth, even on my shoddy dongle when using DS4Windows.

What I'm asking is if it is possible to achieve 1000Hz polling rate for DualSense through DS4Windows. And I'm asking for that since it doesn't run on the same polling rate through USB as DS4 does, which is 4ms delay (250Hz), but instead 3.5ms (285Hz). I also have no reason to doubt the readings in DS4Windows considering all other data lines up perfectly, aka 1ms through BT and 4ms through USB for DS4.

Clearly there's been an improvement to the USB connection on DualSense compared to DualShock 4.

> on bluetooth the controller readings say 1ms and in usb 3-3.5ms for the dualsense in ds4windows

Thank you for providing extra data. Now it's clear it's not just my DualSense that shows unusual latency value.

> (The ones who say Bluetooth sucks are likely just Bluetooth haters or they got polluted 2.4GHz environment since the polling rate is objectively higher when using Bluetooth)

That is definitely a possibility. However I managed to find this video: https://www.youtube.com/watch?v=x0wcJM4FtXQ

Apparently you can overclock the DS4v2 to run at 1000Hz and it will perform much better. I will try that method with DualSense cause I don't exactly have anything to lose.

**Comment by TheMasterDingo** [comment]
I dont have my pc at hand now but the setting in ds4 for the polling rate is only bt?

Also i have the same readings in my ds4v2, 1 ms on bt 3-4 in usb

**Comment by RyuMakkuro** [comment]
> I dont have my pc at hand now but the setting in ds4 for the polling rate is only bt?

Yes.

I tried "overclocking" the polling rate of DualSense using the method in that video I linked above, got DualSense to  run at 1000Hz polling rate and DS4Windows reports a rock solid, no deviation at all, 0ms latency :D
Works as a temporary solution for now at least.
