### ISSUE TITLE
Random stick drift every so often ONLY on DS4Windows

### ISSUE THREAD

**Issue by SurfingCats** [Ryochan7/DS4Windows#1611]
I'm currently experiencing random stick drift every few mins **only** on DS4Windows.

Its not the controller. Its happens when connected through bluetooth **and** usb. Latency doesn't jump when this occurs.

Windows 10, This is happening while playing Call of Duty Cold War.

**Comment by Ryochan7** [comment]
Add LS and RS Dead Zone

**Comment by SurfingCats** [comment]
I was using default stick settings. Which was 0.08 on both sticks. What should I change it to? Just up it by 0.1 value?

**Comment by SurfingCats** [comment]
I fixed this by setting dead zone and anti dead zone to 0. I've not noticed a downside doing this
