### ISSUE TITLE
Command line `DS4Windows.exe -command shutdown` not working

### ISSUE THREAD

**Issue by Technik-J** [Ryochan7/DS4Windows#1612]
Command line `DS4Windows.exe -command shutdown` not working. It asks the conformation to close and even if you say 'Yes' it still not closes.

First bug is that command line option should not ask conformation.
Second bug is that it not closing even if the user chooses 'Yes'.

**Comment by mika-n** [comment]
Indeed. doesn't seem to work anymore. I'll look into it....

**Comment by mika-n** [comment]
fixed. the next release should have the fix.
