### ISSUE TITLE
DS4Windows will no longer open

### ISSUE THREAD

**Issue by kcyrowolf** [Ryochan7/DS4Windows#1616]
After noticing my DS4 controller was not connecting today, I have found DS4Windows will no longer open (running Windows 10).

Attempts so far, with no success:

-Run As Administator
-Multiple Restarts
-Uninstalling (including wiping AppData)
-Reinstalling (plus rolling back to versions 2.1.19 and 2.1.18)
-Updating through DS4Update (which still functions)

**Comment by mika-n** [comment]
Logfile content?
Windows EventLog has any error messages? Maybe errors about WMI WinOS services?

https://github.com/Ryochan7/DS4Windows/issues/1196

**Comment by kcyrowolf** [comment]
Apologies, and thank you for that.

I ran the Windows Event Viewer and it appeared to be a .NET relate error. Updated my .NET Framework and now DS4Windows runs as normal.
