### ISSUE TITLE
lib folder empty in versions 2.1.18 and 2.1.19

### ISSUE THREAD

**Issue by BPDMF** [Ryochan7/DS4Windows#1618]
The lib folders are empty in those releases. When auto updating the folder stays filled with the things from the previous versions, but when downloading from git the lib folders are empty. Intended? Or was it and oversight?

**Comment by Ryochan7** [comment]
The update to targeting .NET Framework 4.8 eliminated the need for the redirect DLL files. DS4Updater has no way to handle file differences between versions of DS4Windows except to overwrite existing files. The simplest way around the issue would be to have the updater delete the old files and place the new files in that folder.
