### ISSUE TITLE
how to enable experimental rumble for DS4 emulation?

### ISSUE THREAD

**Issue by AndrijReally** [Ryochan7/DS4Windows#1619]
i can't found experimental rumble option in DS4 emulation mode. Where i can enable it?

**Comment by mika-n** [comment]
the latest version already have it enabled by default (unless you have set rumble-% to zero value or unticked "Send output data to DS4" option).
https://github.com/Ryochan7/DS4Windows/releases

You test this via https://gamepad-tester.com/ web page, but if a game still doesn't send rumble then could be that the game doesn't support it via dinput DS4 interface, but only via xinput xbox360 interface.
