### ISSUE TITLE
[ENCHANCEMENT] Check for Updates Now

### ISSUE THREAD

**Issue by shinra358** [Ryochan7/DS4Windows#1620]
I'd like to ask for a check for updates now button. In the task bar menu and/or in the settings menu. Currently there's no option for it but only for an at startup and after hours.

**Comment by Ryochan7** [comment]
Been there since Jays2Kings

![ds4win_check_updates_now](https://user-images.githubusercontent.com/581968/100780675-a1290900-33cf-11eb-9e35-ef0a8d23bc2b.png)

**Comment by shinra358** [comment]
Didnt see it. My ds4 window was small so it only showed 4 items there.
There isnt a scrollbar. I enlarged the window and then i saw more options.
Id like to ask for a scrollbar there then 😂

**Comment by shinra358** [comment]
When the window obscures the other options
