### ISSUE TITLE
Work on Controller Registration Window

### ISSUE THREAD

**Issue by Ryochan7** [Ryochan7/DS4Windows#1621]
**Describe the bug**
Now that many controller types can be supported, it might be a good idea to limit which controllers are actually opened by DS4Windows. There are times when people might want to use other tools to support certain controllers (BetterJoy with the Switch Pro). It would probably help to give the user an option to tell DS4Windows to ignore a controller type temporarily. 

**Expected behavior**
Ignore certain controller types when probing for new devices. Allow other programs to take control of a device

**Additional context**
I have not had a use for this feature but I figured it might be useful. Not sure if a DS4 and DualSense option need to be given. This would be more for Switch Pro and JoyCon controller support

**Comment by 7MXek** [comment]
Have you considered rebranding from DS4Windows to something more generic considering the program now supports more than just DS4 controllers? Most people might assume this project is only for DS4 controllers and ignore it all together.

**Comment by mrtostados** [comment]
> Have you considered rebranding from DS4Windows to something more generic considering the program now supports more than just DS4 controllers?

That's a pretty good point. Especially now that even Sony has evolved beyond DualShock 4. Maybe just DSWindows? Either way, this feature sounds like it could be helpful in certain use cases.

**Comment by Ryochan7** [comment]
The long term plan is to move away from this code base entirely. Eventually, I hope to finally get around to working more on a different mapper that will work around several issues that cannot easily be fixed with the DS4Windows mapper code base. The DS4Windows code base has allowed for a lot of experimenting with C#/.NET that have been useful in other projects though.

This is the current work in progress. API changes are still happening. Mapping is all done in the code still since the API is still being worked on. I don't know when some type of profile loading will be possible although I know that the files will be formatted in JSON.

https://gitlab.com/ryochan7/switchpromappertest/-/tree/action_ideas

**Comment by Ryochan7** [comment]
I can't be bothered to worry about this anymore. A very basic version has been committed and that is as good as it is going to get. Wouldn't be surprised if my GitHub account gets banned soon.
