### ISSUE TITLE
Battery Level Always 0% With Sony DS4 Adapter

### ISSUE THREAD

**Issue by FroggMaster** [Ryochan7/DS4Windows#1624]
**Describe the bug**
- When the DS4 controller is connected VIA the Sony DS4 Adapter the battery level displays as 0% no matter what the actual battery level of the controller is. 

**To Reproduce**
1. Connect Sony DS4 Adapater
2. Launch DS4 Windows in Administrator Mode
3. Connect the PS4 Controller
4. See battery level

**Expected behavior**
A accurate or at least estimated battery level rather than always showing 0%

**Screenshots**

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: Windows 10 Pro Version 2004 Build 19041.630
 - DS4Windows Version: 2.1.19
![image](https://user-images.githubusercontent.com/12762784/100859958-c0ae4900-3444-11eb-8a49-0a81877595c1.png)

**Comment by mika-n** [comment]
@Ryochan7 I believe you have Sony WA adapter also? Do you have the same issue with SonyWA dongle?

**Comment by Ryochan7** [comment]
Hiding a core piece of info I want from the screenshot (serial number). I am going to assume that the DS4 is just not paired to the dongle so the serial is all 0's.

Anyway, works for me.
