### ISSUE TITLE
[Feature Request] Add support Brook Mars controller (only add PID & VID)

### ISSUE THREAD

**Issue by r57zone** [Ryochan7/DS4Windows#1625]
Hi, could you please add to your cool project support for the Brook Mars Controller universal gamepad, it supports DualShock 4 mode and USB packet DualShock 4 is fully compatible, but it has a different PID & VID due to licenses.

BROOK DS4 VENDOR: `0x0C12`
BROOK DS4 PRODUCT ID USB: `0x0E20`

Thanks a lot.

**Comment by mika-n** [comment]
Please try the debug version and provide the debug logfile here as TXT attachment (rename the latest logfile in %APPDATA%\ds4windows\logs\folder as .TXT file and attach it here as an attachment).
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

The debug version tries to use all gamepad devices even when those are not set as "DS4 compatible".

**Comment by mika-n** [comment]
@r57zone Does this Brook gamepad has touchpad, lightbar, rumble and/or gyro support? Do you have links to any webstore or to the manufacturer's site with more details? Anyway, please test the gamepad and post here results from those special DS4 features because if those are not supported then it is possible to tweak the gamepad registration info and this way instruct DS4Windows app to ignore the use of those features. The debug logfile would tell a bit more about the gamepad.

**Comment by r57zone** [comment]
Supported: lightbar, gyroscope, vibration and touchpad. The touchpad works in emulation mode (press + right stick, swipes). The gyroscope works, I have not yet managed to fully configure the mouse emulation (weak mouse sensitivity emulated by a gyroscope), but in the "Racing" mode (emulation of the left stick by a gyroscope for racing) everything is fine.

Official page - https://www.brookaccessory.com/detail/51117579/

**Comment by mika-n** [comment]
Thx. Looks like pretty good 3rd party DS4 gamepad. Often those "compatible" gamepads lack gyro. And the touchpad emulation mode with "click + RS stick movement" is an interesting way to do it. 

The current version of ViGem virtual gamepad device doesn't support touchpad movement events, it supports only touchpad click btn (this is why DS4Windows uses touchpad only as a mouse or re-mapping source, but not as re-map target), but the true touchpad support is coming to the ViGem driver in the future (ViGem developers already have something in their lab). Many compatible and cheaper gamepads don't have true touchpad at all, but the way how Mars Controller emulates it is something which could be applied to all gamepads via DS4Windows app in the future. This touchpad emulation logic needs to be remembered when the official version of ViGem receives the true touchpad support.
