### ISSUE TITLE
DualSense Button Mapping remapping randomly

### ISSUE THREAD

**Issue by flok** [Ryochan7/DS4Windows#1626]
**Describe the bug**
Hey guys, enjoying the DualSense implementation so far. But i have one really annoying problem. Somehow the buttons get remapped randomly. In the main menu in Trackmania cross is select and then in the next menu cross is back somehow.

**To Reproduce**
1. Download Trackmania (free from uplay)
2. in the main menu you can select thinks like Track of the Day with cross
3. in the next menu cross turns to cancel somehow

**Expected behavior**
Button mapping should be the same

**Screenshots**

**Desktop (please complete the following information):**
 - Controller Make and Model: DualSense (idk Firmware)
 - OS: [e.g. Windows 10 Pro Build 2004]
 - DS4Windows Version: 2.1.9

**Comment by mika-n** [comment]
Are you using exclusive mode or HidGuardian to hide the physical controller from the game? If not then maybe the game randomly sees the the physical gamepad and the virtual gamepad device every now and then (ie. double controller issue)?
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

Or are you using auto-profile rules to automatically switch DS4Windows profiles? If you are then check those auto-profile rules to make sure that the profile remains the same over different game screens.

**Comment by flok** [comment]
Seems like the first one. I tried the Hid Guardian but doesnt seem to work. Which exact thing should i add with the HidHideTest programm?
i have these at the moment. But it seems like the button are double mapped somehow ? first i can select with the cross then when i press square 2 actions happened together ? like square is triggering square and cross
![image](https://user-images.githubusercontent.com/37000563/101207236-a0fb6880-3670-11eb-8e49-94cf050a27dc.png)

**Comment by mika-n** [comment]
Actually, none of those values in the HidNinja/HidHide tool are for DS5 DualSense controller. Those default values are for DS4 gamepads. You can dig out the DualSense HID hardware identifier from WinOS DeviceManager or by running the following debug version of DS4Windows app.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

**Comment by flok** [comment]
You sure? i wrote a python library to access and read from the DS5 controller and use the VID 054c and PID 0ce6? So i thoughts thats the DS5 controller

This is the output from the debug version

`12/04/2020 21:32:45: DS4Windows version 2.1.19
12/04/2020 21:32:45: OS Version: Microsoft Windows NT 10.0.19041.0
12/04/2020 21:32:45: OS Product Name: Windows 10 Pro
12/04/2020 21:32:45: OS Release ID: 2004
12/04/2020 21:32:45: System Architecture: x64
12/04/2020 21:32:45: Running as User
12/04/2020 21:32:45: HidGuardian in use. Launching HidGuardHelper.
12/04/2020 21:32:46: Starting...
12/04/2020 21:32:46: Connection to ViGEmBus 1.16.112.0 established
12/04/2020 21:32:46: Searching for controllers...
12/04/2020 21:32:46: Using Shared Mode
12/04/2020 21:32:46: DEBUG: EnumerateDS4. HID#1 Path=\\?\hid#vid_1b1c&pid_1b3d&mi_00&col01#8&38892959&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd  Description=HID Keyboard Device  VID=0x1B1C  PID=0x1B3D  Usage=0x6  Version=0x3006
12/04/2020 21:32:46: DEBUG: EnumerateDS4. HID#2 Path=\\?\hid#vid_1e7d&pid_2e22&mi_01#7&7ac2d76&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd  Description=HID Keyboard Device  VID=0x1E7D  PID=0x2E22  Usage=0x6  Version=0x101
12/04/2020 21:32:46: DEBUG: EnumerateDS4. HID#3 Path=\\?\hid#vid_1e7d&pid_2e22&mi_00&col01#7&32535837&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant mouse  VID=0x1E7D  PID=0x2E22  Usage=0x2  Version=0x101
12/04/2020 21:32:46: DEBUG: EnumerateDS4. HID#4 Path=\\?\hid#vid_1e7d&pid_2e22&mi_00&col02#7&32535837&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant consumer control device  VID=0x1E7D  PID=0x2E22  Usage=0x1  Version=0x101
12/04/2020 21:32:46: DEBUG: EnumerateDS4. HID#5 Path=\\?\hid#vid_1e7d&pid_2e22&mi_00&col03#7&32535837&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant device  VID=0x1E7D  PID=0x2E22  Usage=0x0  Version=0x101
12/04/2020 21:32:46: DEBUG: EnumerateDS4. HID#6 Path=\\?\hid#vid_1e7d&pid_2e22&mi_00&col04#7&32535837&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant device  VID=0x1E7D  PID=0x2E22  Usage=0x0  Version=0x101
12/04/2020 21:32:46: DEBUG: EnumerateDS4. HID#7 Path=\\?\hid#vid_046d&pid_c231#2&229a2ea&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant mouse  VID=0x046D  PID=0xC231  Usage=0x2  Version=0x1
12/04/2020 21:32:46: DEBUG: EnumerateDS4. HID#8 Path=\\?\hid#vid_046d&pid_0a5b&mi_03&col01#7&13e2a184&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant consumer control device  VID=0x046D  PID=0x0A5B  Usage=0x1  Version=0x101
12/04/2020 21:32:46: DEBUG: EnumerateDS4. HID#9 Path=\\?\hid#vid_046d&pid_c232#2&132d72ab&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd  Description=HID Keyboard Device  VID=0x046D  PID=0xC232  Usage=0x6  Version=0x1
12/04/2020 21:32:46: DEBUG: EnumerateDS4. HID#10 Path=\\?\hid#vid_1b1c&pid_1b3d&mi_01#8&1765c54&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant vendor-defined device  VID=0x1B1C  PID=0x1B3D  Usage=0x4  Version=0x3006
12/04/2020 21:32:46: DEBUG: EnumerateDS4. HID#11 Path=\\?\hid#vid_046d&pid_0a5b&mi_03&col02#7&13e2a184&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant phone  VID=0x046D  PID=0x0A5B  Usage=0x1  Version=0x101
12/04/2020 21:32:46: DEBUG: EnumerateDS4. HID#12 Path=\\?\hid#vid_046d&pid_0a5b&mi_03&col03#7&13e2a184&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant vendor-defined device  VID=0x046D  PID=0x0A5B  Usage=0x202  Version=0x101
12/04/2020 21:32:46: DEBUG: EnumerateDS4. HID#13 Path=\\?\hid#vid_046d&pid_0a5b&mi_03&col04#7&13e2a184&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant vendor-defined device  VID=0x046D  PID=0x0A5B  Usage=0x1  Version=0x101
12/04/2020 21:32:46: DEBUG: EnumerateDS4. HID#14 Path=\\?\hid#vid_1b1c&pid_1b3d&mi_00&col02#8&38892959&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant consumer control device  VID=0x1B1C  PID=0x1B3D  Usage=0x1  Version=0x3006
12/04/2020 21:32:46: DEBUG: EnumerateDS4. HID#15 Path=\\?\hid#vid_1b1c&pid_1b3d&mi_00&col03#8&38892959&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant vendor-defined device  VID=0x1B1C  PID=0x1B3D  Usage=0x2  Version=0x3006
12/04/2020 21:32:46: DEBUG: EnumerateDS4. HID#16 Path=\\?\hid#vid_1b1c&pid_1b3d&mi_00&col04#8&38892959&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant vendor-defined device  VID=0x1B1C  PID=0x1B3D  Usage=0x3  Version=0x3006
12/04/2020 21:32:46: DEBUG: findControllers. Found 0 possible devices
12/04/2020 21:32:53: DEBUG: EnumerateDS4. HID#1 Path=\\?\hid#vid_1b1c&pid_1b3d&mi_00&col01#8&38892959&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd  Description=HID Keyboard Device  VID=0x1B1C  PID=0x1B3D  Usage=0x6  Version=0x3006
12/04/2020 21:32:53: DEBUG: EnumerateDS4. HID#2 Path=\\?\hid#vid_1e7d&pid_2e22&mi_01#7&7ac2d76&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd  Description=HID Keyboard Device  VID=0x1E7D  PID=0x2E22  Usage=0x6  Version=0x101
12/04/2020 21:32:53: DEBUG: EnumerateDS4. HID#3 Path=\\?\hid#vid_1e7d&pid_2e22&mi_00&col01#7&32535837&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant mouse  VID=0x1E7D  PID=0x2E22  Usage=0x2  Version=0x101
12/04/2020 21:32:53: DEBUG: EnumerateDS4. HID#4 Path=\\?\hid#vid_1e7d&pid_2e22&mi_00&col02#7&32535837&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant consumer control device  VID=0x1E7D  PID=0x2E22  Usage=0x1  Version=0x101
12/04/2020 21:32:53: DEBUG: EnumerateDS4. HID#5 Path=\\?\hid#vid_1e7d&pid_2e22&mi_00&col03#7&32535837&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant device  VID=0x1E7D  PID=0x2E22  Usage=0x0  Version=0x101
12/04/2020 21:32:53: DEBUG: EnumerateDS4. HID#6 Path=\\?\hid#vid_1e7d&pid_2e22&mi_00&col04#7&32535837&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant device  VID=0x1E7D  PID=0x2E22  Usage=0x0  Version=0x101
12/04/2020 21:32:53: DEBUG: EnumerateDS4. HID#7 Path=\\?\hid#vid_046d&pid_c231#2&229a2ea&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant mouse  VID=0x046D  PID=0xC231  Usage=0x2  Version=0x1
12/04/2020 21:32:53: DEBUG: EnumerateDS4. HID#8 Path=\\?\hid#vid_054c&pid_0ce6&mi_03#8&2895ed97&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant game controller  VID=0x054C  PID=0x0CE6  Usage=0x5  Version=0x100
12/04/2020 21:32:53: DEBUG: EnumerateDS4. HID#8 detected as DS4 compatible gamepad device
12/04/2020 21:32:53: DEBUG: EnumerateDS4. HID#9 Path=\\?\hid#vid_046d&pid_0a5b&mi_03&col01#7&13e2a184&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant consumer control device  VID=0x046D  PID=0x0A5B  Usage=0x1  Version=0x101
12/04/2020 21:32:53: DEBUG: EnumerateDS4. HID#10 Path=\\?\hid#vid_046d&pid_c232#2&132d72ab&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd  Description=HID Keyboard Device  VID=0x046D  PID=0xC232  Usage=0x6  Version=0x1
12/04/2020 21:32:53: DEBUG: EnumerateDS4. HID#11 Path=\\?\hid#vid_1b1c&pid_1b3d&mi_01#8&1765c54&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant vendor-defined device  VID=0x1B1C  PID=0x1B3D  Usage=0x4  Version=0x3006
12/04/2020 21:32:53: DEBUG: EnumerateDS4. HID#12 Path=\\?\hid#vid_046d&pid_0a5b&mi_03&col02#7&13e2a184&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant phone  VID=0x046D  PID=0x0A5B  Usage=0x1  Version=0x101
12/04/2020 21:32:53: DEBUG: EnumerateDS4. HID#13 Path=\\?\hid#vid_046d&pid_0a5b&mi_03&col03#7&13e2a184&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant vendor-defined device  VID=0x046D  PID=0x0A5B  Usage=0x202  Version=0x101
12/04/2020 21:32:53: DEBUG: EnumerateDS4. HID#14 Path=\\?\hid#vid_046d&pid_0a5b&mi_03&col04#7&13e2a184&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant vendor-defined device  VID=0x046D  PID=0x0A5B  Usage=0x1  Version=0x101
12/04/2020 21:32:53: DEBUG: EnumerateDS4. HID#15 Path=\\?\hid#vid_1b1c&pid_1b3d&mi_00&col02#8&38892959&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant consumer control device  VID=0x1B1C  PID=0x1B3D  Usage=0x1  Version=0x3006
12/04/2020 21:32:53: DEBUG: EnumerateDS4. HID#16 Path=\\?\hid#vid_1b1c&pid_1b3d&mi_00&col03#8&38892959&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant vendor-defined device  VID=0x1B1C  PID=0x1B3D  Usage=0x2  Version=0x3006
12/04/2020 21:32:53: DEBUG: EnumerateDS4. HID#17 Path=\\?\hid#vid_1b1c&pid_1b3d&mi_00&col04#8&38892959&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant vendor-defined device  VID=0x1B1C  PID=0x1B3D  Usage=0x3  Version=0x3006
12/04/2020 21:32:53: DEBUG: findControllers. Found 1 possible device
12/04/2020 21:32:53: DEBUG: findControllers. Idx=0 Potential DS4 gamepad. Description=HID-compliant game controller  Path=\\?\hid#vid_054c&pid_0ce6&mi_03#8&2895ed97&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
12/04/2020 21:32:53: DEBUG: findControllers. idx=0 Opening device VID=0x054C  PID=0x0CE6  isExclusiveMode=False
12/04/2020 21:32:53: DEBUG: findControllers. idx=0 IsOpen=True
12/04/2020 21:32:53: DEBUG: readSerial. Trying to read serial# from VendorID=0x054C, ProductID=0x0CE6, Version=256, DevicePath=\\?\hid#vid_054c&pid_0ce6&mi_03#8&2895ed97&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030} InputReportLen=64
12/04/2020 21:32:53: DEBUG: readSerial. OK. readFeatureData. Serial#=A0:AB:51:99:26:31
12/04/2020 21:32:53: DEBUG: findControllers. idx=0 IsValidSerial=True  Serial=A0:AB:51:99:26:31
12/04/2020 21:32:53: DEBUG: findControllers. idx=0 Using device \\?\hid#vid_054c&pid_0ce6&mi_03#8&2895ed97&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  metainfo.name=DualSense  metainfo.featureSet=DefaultDS4
12/04/2020 21:32:53: DEBUG: DS4SixAxis. gyroMultiplierYaw=1  gyroMultiplierRoll=1  gyroMultiplierPitch=1
12/04/2020 21:32:53: DEBUG: DS4Device. DualSense conType=USB  MAC=A0:AB:51:99:26:31
12/04/2020 21:32:53: DEBUG: DS4Device. Raw InputReportLen=64  OutputReportLen=48
12/04/2020 21:32:53: DEBUG: DS4Device. Current debug options: debug_HidDSetNumInputBuffers=2  debug_GyroCalibration=True  debug_GyroCalibrationType=0
12/04/2020 21:32:53: DEBUG: DS4Device. Current debug options: debug_SendRumbleLightbarData=True  debug_SendRumbleLightbarDataType=0  debug_SendRumbleLightbarDataAPI=0
12/04/2020 21:32:53: DEBUG: DS4Device. Current debug options: debug_ReadTouchpadData =True  debug_ReadGyroData=True  debug_ReadBatteryData=True
12/04/2020 21:32:53: DEBUG: DS4Device. Current debug options: debug_ForceConnectionType=0  debug_PrintoutInputDataBuffer=False
12/04/2020 21:32:53: DEBUG: setCalibrationData. calibrationDone=True
12/04/2020 21:32:53: DEBUG: setCalibrationData. calibrationData[0] bias=-2  sensNumer=17280  sensDenom=17730
12/04/2020 21:32:53: DEBUG: setCalibrationData. calibrationData[1] bias=-10  sensNumer=17280  sensDenom=17780
12/04/2020 21:32:53: DEBUG: setCalibrationData. calibrationData[2] bias=0  sensNumer=17280  sensDenom=17789
12/04/2020 21:32:53: DEBUG: setCalibrationData. calibrationData[3] bias=18  sensNumer=16384  sensDenom=16394
12/04/2020 21:32:53: DEBUG: setCalibrationData. calibrationData[4] bias=-98  sensNumer=16384  sensDenom=16368
12/04/2020 21:32:53: DEBUG: setCalibrationData. calibrationData[5] bias=-15  sensNumer=16384  sensDenom=16405
12/04/2020 21:32:53: DEBUG: setCalibrationData. gyroSpeed2x=1080 gyroSpeedPlus+gyroSpeedMinus=(540 + 540)  yaw=17780 yawPlus-yawMinus=(8883 - -8897)
12/04/2020 21:32:53: DEBUG: findControllers. idx=0 OK. DS4Win uses the device as input source
12/04/2020 21:32:53: Found Controller: A0:AB:51:99:26:31 (USB) (DualSense)
12/04/2020 21:32:53: Plugging in virtual X360 Controller
12/04/2020 21:32:53: Associate X360 Controller for input DS4 #1
12/04/2020 21:32:53: Controller 1 is using Profile "Default". Battery level is 100%
12/04/2020 21:32:55: DEBUG: EnumerateDS4. HID#1 Path=\\?\hid#vid_1b1c&pid_1b3d&mi_00&col01#8&38892959&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd  Description=HID Keyboard Device  VID=0x1B1C  PID=0x1B3D  Usage=0x6  Version=0x3006
12/04/2020 21:32:55: DEBUG: EnumerateDS4. HID#2 Path=\\?\hid#vid_1e7d&pid_2e22&mi_01#7&7ac2d76&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd  Description=HID Keyboard Device  VID=0x1E7D  PID=0x2E22  Usage=0x6  Version=0x101
12/04/2020 21:32:55: DEBUG: EnumerateDS4. HID#3 Path=\\?\hid#vid_1e7d&pid_2e22&mi_00&col01#7&32535837&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant mouse  VID=0x1E7D  PID=0x2E22  Usage=0x2  Version=0x101
12/04/2020 21:32:55: DEBUG: EnumerateDS4. HID#4 Path=\\?\hid#vid_1e7d&pid_2e22&mi_00&col02#7&32535837&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant consumer control device  VID=0x1E7D  PID=0x2E22  Usage=0x1  Version=0x101
12/04/2020 21:32:55: DEBUG: EnumerateDS4. HID#5 Path=\\?\hid#vid_1e7d&pid_2e22&mi_00&col03#7&32535837&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant device  VID=0x1E7D  PID=0x2E22  Usage=0x0  Version=0x101
12/04/2020 21:32:55: DEBUG: EnumerateDS4. HID#6 Path=\\?\hid#vid_1e7d&pid_2e22&mi_00&col04#7&32535837&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant device  VID=0x1E7D  PID=0x2E22  Usage=0x0  Version=0x101
12/04/2020 21:32:55: DEBUG: EnumerateDS4. HID#7 Path=\\?\hid#vid_046d&pid_c231#2&229a2ea&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant mouse  VID=0x046D  PID=0xC231  Usage=0x2  Version=0x1
12/04/2020 21:32:55: DEBUG: EnumerateDS4. HID#8 Path=\\?\hid#vid_054c&pid_0ce6&mi_03#8&2895ed97&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant game controller  VID=0x054C  PID=0x0CE6  Usage=0x5  Version=0x100
12/04/2020 21:32:55: DEBUG: EnumerateDS4. HID#8 detected as DS4 compatible gamepad device
12/04/2020 21:32:55: DEBUG: EnumerateDS4. HID#9 Path=\\?\hid#vid_046d&pid_0a5b&mi_03&col01#7&13e2a184&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant consumer control device  VID=0x046D  PID=0x0A5B  Usage=0x1  Version=0x101
12/04/2020 21:32:55: DEBUG: EnumerateDS4. HID#10 Path=\\?\hid#vid_046d&pid_c232#2&132d72ab&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd  Description=HID Keyboard Device  VID=0x046D  PID=0xC232  Usage=0x6  Version=0x1
12/04/2020 21:32:55: DEBUG: EnumerateDS4. HID#11 Path=\\?\hid#vid_1b1c&pid_1b3d&mi_01#8&1765c54&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant vendor-defined device  VID=0x1B1C  PID=0x1B3D  Usage=0x4  Version=0x3006
12/04/2020 21:32:55: DEBUG: EnumerateDS4. HID#12 Path=\\?\hid#vid_046d&pid_0a5b&mi_03&col02#7&13e2a184&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant phone  VID=0x046D  PID=0x0A5B  Usage=0x1  Version=0x101
12/04/2020 21:32:55: DEBUG: EnumerateDS4. HID#13 Path=\\?\hid#vid_046d&pid_0a5b&mi_03&col03#7&13e2a184&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant vendor-defined device  VID=0x046D  PID=0x0A5B  Usage=0x202  Version=0x101
12/04/2020 21:32:55: DEBUG: EnumerateDS4. HID#14 Path=\\?\hid#vid_046d&pid_0a5b&mi_03&col04#7&13e2a184&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant vendor-defined device  VID=0x046D  PID=0x0A5B  Usage=0x1  Version=0x101
12/04/2020 21:32:55: DEBUG: EnumerateDS4. HID#15 Path=\\?\hid#vid_045e&pid_028e&ig_00#3&1efb2488&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant game controller  VID=0x045E  PID=0x028E  Usage=0x5  Version=0x0
12/04/2020 21:32:55: DEBUG: EnumerateDS4. HID#16 Path=\\?\hid#vid_1b1c&pid_1b3d&mi_00&col02#8&38892959&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant consumer control device  VID=0x1B1C  PID=0x1B3D  Usage=0x1  Version=0x3006
12/04/2020 21:32:55: DEBUG: EnumerateDS4. HID#17 Path=\\?\hid#vid_1b1c&pid_1b3d&mi_00&col03#8&38892959&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant vendor-defined device  VID=0x1B1C  PID=0x1B3D  Usage=0x2  Version=0x3006
12/04/2020 21:32:55: DEBUG: EnumerateDS4. HID#18 Path=\\?\hid#vid_1b1c&pid_1b3d&mi_00&col04#8&38892959&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant vendor-defined device  VID=0x1B1C  PID=0x1B3D  Usage=0x3  Version=0x3006
12/04/2020 21:32:55: DEBUG: findControllers. Found 1 possible device
12/04/2020 21:32:55: DEBUG: findControllers. Idx=0 Potential DS4 gamepad. Description=HID-compliant game controller  Path=\\?\hid#vid_054c&pid_0ce6&mi_03#8&2895ed97&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
`

**Comment by mika-n** [comment]
sorry, my bad. Didn't look carefully enough and didn't see the 0CE6 hid identifier there (Ds5 pad).

And it is better to attach logfiles as .TXT renamed files here as an attachment and not as copy-paste text because sometimes Github comment field removes certain special chars.  But, I was still able to see the HID path in the logfile and you seem to have it.

When you launch DS4Windows app and then connect the DS5 gamepad then what do you see in the "Processes" tab page in HidHideTest app? There should be "DS4Windows : <processID>" line on the right side of the screen and the processID should match the current process ID of dS4Windows app (you can verify this via TaskManager).,

And what do you see in JOY.CPL controlPanel applet? Just run this JOY.CPL command or press "Control Panel" link in DS4Windows/Settings tab page. How many gamepads and what names? If there is just one xbox360 gamepad then HidGuardian has done its magic and the original physical gamepad is hidden. If you see both the xbox360 and the original DS5 gamepad there then HidG failed to hide the gamepad.

**Comment by flok** [comment]
Thanks for the follow up. The process ID match.

In the joy.cpl panel i only see the "Controller (xbox 360 for windows)" controller. Seems like it worked now !

Thanks for the help
