### ISSUE TITLE
dualsense left trigger

### ISSUE THREAD

**Issue by dog7431** [Ryochan7/DS4Windows#1628]
Hi! I found that the left trigger of my Dualsense doesn't work in game. XinputChecker shows 0 when the trigger is pressed

![xinput](https://user-images.githubusercontent.com/49536566/101145061-e80e3d00-3621-11eb-8e6f-05ef2650286f.JPG)

 - Controller Make and Model: Sony DualSense  (CFI-ZCT1W)
 - OS: Windows 10 Home Build 2004
 - DS4Windows Version 2.1.19

upd; 
![weird](https://user-images.githubusercontent.com/49536566/101178103-3e46a480-3651-11eb-898c-9607b15f6ff5.JPG)
I checked the trigger status in the profile settings, the "l" parameter was 255, but the second parameter "0" was zero. After I pressed all the buttons on the joystick, this parameter suddenly jumped. In the game, the trigger worked.

**Comment by Ryochan7** [comment]
Going to assume it is a mapping problem
