### ISSUE TITLE
Having troubles binding gamepad button to function as toggle.

### ISSUE THREAD

**Issue by Supa-Troopa** [Ryochan7/DS4Windows#163]
Hello! I'm having a hard time, trying to bind r1 to function as right trigger toggle. Pretty sure it's me, but I can't figure out what am I doing wrong. I go to the profile, double click R1, check "toggle" checkbox, and click on "RB" image, then save the profile, and make sure that's one enabled in game. Pressing R1 still function as a single press, though :(

Help?
The game is Bayonetta, if it's relevant, and I'm trying to set up target lock as a toggle.

p.s. — I doubled that message from Jays2Kings branch, but I installed Ryochan7 version before posting it here. Also, if I'm binding keyboard lock-on key, as a toggle (alt, in this case) — it works, but screws the interface, because all button icons will constantly change between keyboard/xbox360 ones.

**Comment by Ryochan7** [comment]
I believe the toggle option is only set up to work with keyboard bindings. The mapping methods used in DS4Windows are not very flexible and there is no easy way to tack on that functionality. For my usage, just getting the DS4 to operate as a basic XInput controller is good enough. That has been enough of a challenge.

**Comment by Supa-Troopa** [comment]
I see. Well, it is what it is. Thanks for clarifying!
