### ISSUE TITLE
How to have rainbow in lightbar while not charging too

### ISSUE THREAD

**Issue by nihaalnz** [Ryochan7/DS4Windows#1630]
I saw an option to have lightbar to rainbow when charging but wanted to know if there was a way to keep it doing this while not charging too. There should be an option right? Plus im using ps5 controller, and so far it works fine, though waiting for you guys to start development of ds5windows xp. Anywas, Great app!

**Comment by AndrijReally** [comment]
your profile > lightbar > ![image](https://user-images.githubusercontent.com/34485522/101241666-ebc4c100-3700-11eb-8eca-1cf8ece64893.png)

**Comment by nihaalnz** [comment]
@AndrijReally  I dont have such a button there. Which version are you using.

**Comment by mika-n** [comment]
Yes you have it. It is the "palette icon" on the left of "10 secs/cycle" option. Press the palette icon and it sets the lightbar mode to "always rainbow mode".  The "always rainbow mode" text shown in the screenshot made by AndrijReally is not a button, but tooltip text shown when you take the mouse on top of this palette icon.

**Comment by nihaalnz** [comment]
@mika-n  Thanks mate, found it out!!
