### ISSUE TITLE
Genshin Impact doesn't detect DualSense Controller that is connected via Virtual DualShock 4

### ISSUE THREAD

**Issue by Animus120** [Ryochan7/DS4Windows#1632]
Describe the bug
I'm trying to play Genshin Impact using my DualSense that is emulating a Virtual DualShock 4 so I can get the PlayStation prompt instead of the Xbox in-game. This does not work. Genshin will detect DualSense IF it is running on HIDGuardian using Virtual 360. I have attached a logfile to help detecting what is up and how to fix this.
[Genshin DualSense.txt](https://github.com/Ryochan7/DS4Windows/files/5647235/Genshin.DualSense.txt)

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DualSense (CFI-ZCT1W)
 - OS: Windows 10 LTSC Build 1809
 - DS4Windows Version [e.g. 2.1.19_x64]

**Additional context**
Genshin can detect DualSense as DualShock 4 without the need of DS4Windows, but I really like that we can customize the CREATE button on the DualSense as a shortcut for my application to take screenshot in-game. Also, I can use custom lightbar colors during gameplay, which reduce the battery drain of DualSense.

**Comment by mika-n** [comment]
Are you using Steam? Maybe the issue described below? At some point the simple solution was to rename DS4Windows.exe as for example DPadApp.exe (and DPadApp.exe.config), but these days there are more and more games where event this doesn't work. Some games deliberately ignore virtual output devices (I guess as part of multiplayer "cheat checks" to fight against some players using macro engine to do super fast Fortnite building).
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#steam-doesnt-see-the-virtual-output-controller-if-a-profile-uses-the-dualshock4-output-type-steam-sees-the-ds4-controller-only-if-ds4windows-uses-xbox360-output-controller-type

**Comment by Animus120** [comment]
> 
> 
> Are you using Steam? Maybe the issue described below? At some point the simple solution was to rename DS4Windows.exe as for example DPadApp.exe (and DPadApp.exe.config), but these days there are more and more games where event this doesn't work. Some games deliberately ignore virtual output devices (I guess as part of multiplayer "cheat checks" to fight against some players using macro engine to do super fast Fortnite building).
> https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#steam-doesnt-see-the-virtual-output-controller-if-a-profile-uses-the-dualshock4-output-type-steam-sees-the-ds4-controller-only-if-ds4windows-uses-xbox360-output-controller-type

Yes, I am running Steam when I launch Genshin, but I don't use the Steam build-in Controller Support. Upon seeing the link you linked, I'll give that a shot once I return from work and report back if this does solves it.

**Comment by Ryochan7** [comment]
I'm not entirely sure it is true but PCGamingWiki claims that Genshin Impact supports the DS4 v.2 (USB and BT) with no mention of DS4 v.1 support. ViGEmBus emulates a USB connected DS4 v.1 in DualShock 4 emulation mode.

https://www.pcgamingwiki.com/wiki/Genshin_Impact

**Comment by Animus120** [comment]
> 
> 
> I'm not entirely sure it is true but PCGamingWiki claims that Genshin Impact supports the DS4 v.2 (USB and BT) with no mention of DS4 v.1 support. ViGEmBus emulates a USB connected DS4 v.1 in DualShock 4 emulation mode.
> 
> https://www.pcgamingwiki.com/wiki/Genshin_Impact

Interesting. I finally managed to get DS4Windows to run while playing Genshin, but now lies a weird problem: it seems that whatever custom command I use on DS4W under DS4 emulation, it just doesn't work.
Further clarification: I tried to use the CREATE button on my DualSense to take screenshot with NVIDIA Experience, the macro is Alt+F1 for me. The macro doesn't work on Genshin, yet it works on any other game.
What could possibly cause this?

**Comment by Serfrost** [comment]
I have the same controller model as you, DualSense set to emulate DS4 within DS4Window; it works in Genshin just fine.  Please make sure you don't have Hide DS4 enabled in DS4Windows settings.  Secondly, ensure you've updated your Vidgembus installation.

**Comment by Animus120** [comment]
> 
> 
> I have the same controller model as you, DualSense set to emulate DS4 within DS4Windows; it works in Genshin just fine. Please make sure you don't have Hide DS4 enabled in DS4Windows settings. Secondly, ensure you've updated DS4Windows in addition to your Vidgembus installation.

Ah, it works now, I just have to update my DS4W. But it seems that the vibration is not working?

**Comment by Serfrost** [comment]
> @Animus120 Ah, it works now, I just have to update my DS4W. But it seems that the vibration is not working?

Are you aware of when the game is normally supposed to vibrate?  

Contrary to that, within your current DS4Windows Controller Profile that you go to the [Other] tab, make sure [Enable output data to DS4] is enabled.  If it was disabled, enable it.  You must then save the profile, then disconnect and reconnect your controller.

You can also check within DS4Window's Settings tab, within the [Device Settings] option, ensure DualSense Rumble Emulation is enabled and decide what Rumble Strength you want.

Vibration works fine on my end; including the [Test Heavy] and [Test Light] settings at the top of [Other]

**Comment by Serfrost** [comment]
Considering the nature of this post, I'd recommend closing this issue since it seems you already got it resolved.

**Comment by Animus120** [comment]
> 
> 
> > @Animus120 Ah, it works now, I just have to update my DS4W. But it seems that the vibration is not working?
> 
> Are you aware of when the game is normally supposed to vibrate?
> 
> Regardless - within your current DS4Windows Controller Profile, go to the [Other] tab, make sure [Enable output data to DS4] is enabled. If it was disabled, enable it. You must then save the profile, then disconnect and reconnect your controller.
> 
> You can also check within DS4Window's Settings tab, within the [Device Settings] option, ensure DualSense Rumble Emulation is enabled and decide what Rumble Strength you want.
> 
> Vibration works fine on my end; including the [Test Heavy] and [Test Light] settings at the top of [Other]

Yes, I am aware of when it's supposed to vibrate because I used a X1 controller to play Genshin prior to getting my DualSense. I checked the setting you mentioned and it's all on. I'm currently at work right now so I'll test it out when I got back home to see if playing Genshin via DS4 Emulation will vibrate in-game. But yes, I'll close the issue now because it's playable now. Thanks!

**Comment by Serfrost** [comment]
I don't think I tested rumble with DS4 Emulation, actually. I did have rumble working with X360 Emulation though. If you test this and it results in only X360 working, that's when I would open up a new issue. Take care.

**Comment by Animus120** [comment]
> 
> 
> I don't think I tested rumble with DS4 Emulation, actually. I did have rumble working with X360 Emulation though. If you test this and it results in only X360 working, that's when I would open up a new issue. Take care.

That's exactly what happens. The rumble will work while playing Genshin on my DualSense if it's running via X360 emulation. I'll check it out later tonight to see if playing Genshin with my DualSense via DS4 emulation will rumble or not, but if it doesn't, then I'll open up a new issue.

**Comment by mika-n** [comment]
are you sure the game supports rumble with a native physical DS4 gamepad? Someone with Genshin and DS4 gamepad probably should test it (without DS4Windows app) and verify that the game supports rumble over dinput interface.

**Comment by Serfrost** [comment]
@mika-n Good call, I can confirm that the Dinput usage of the DS4 doesn't support rumble on Genshin.  It seems rumble only works if you use DS4Windows and set it to X360 emulation, which I guess can be expected at this point. @Animus120 I think it's safe to say this isn't a DS4Windows issue, rather, it's just how the game behaves with Dinput devices.

**Comment by Animus120** [comment]
Thank you for clarification! I can safely put this issue to a close now.

**Comment by kin-patsu** [comment]
I'm not sure of what got changed with latest two updates (or even if it's an issue with Genshin), but now my DualSense stopped working as it should with the game. I haven't changed anything, profile-wise, yet Genshin detects my controller as an Xbox controller (normally it'd show PS Button Prompts). The game also registers the right stick always pointing up, moving the camera and making it virtually impossible to play, and additionally, L2 seems to be bound to d-pad down and while also lowering the camera.

**Comment by Serfrost** [comment]
@kin-patsu 

1. Set your DualSense to run as an emulated DS4 in DS4Windows instead of Xbox 360. It's at the bottom of one of the tabs for your current Controller Profile. Save and close your profile.

2. At the settings tab of DS4 Windows, enable the Hide DS4 option.

3. Afterwards, open a Windows Run prompt and run Joy.cpl

4. Make sure Genshin isn't running. Stop DS4Windows. Unplug your controller.

5. Check Joy.cpl, make sure no controllers are showing up. If a controller is shown, get it to be removed. You might have to restart your computer if you can't get it to go away.

6. Start DS4Windows and then plug in your DualSense again. Joy.cpl should only show one controller. This means Hide DS4 is working.

7. Now you can run Genshin and it should show the PS Buttons. Make sure not to disconnect your controller while Genshin is on or Genshin will  hijack the controller before DS4Windows can hook to it in exclusive mode.

The problem appears to be having two controller instances in Joy.cpl and Genshin trying to use both of them. As long as only one instance is shown, it should work fine. I had the same problem yesterday.

**Comment by kin-patsu** [comment]
@Serfrost 
That worked flawlessly, thanks a lot. I got somewhat stuck at point 6 while doing it, as something was interfering with DS4W Exclusive Mode, but ultimately I managed to get it to work

**Comment by mika-n** [comment]
> That worked flawlessly, thanks a lot. I got somewhat stuck at point 6 while doing it, as something was interfering with DS4W Exclusive Mode, but ultimately I managed to get it to work

Other apps can easily interfere with exclusive mode (=Hide DS4 Controller option in DS4Windows app). Reasons are beyond the app and if tips in the following page would not help then there is nothing DS4Windows app can do about it. HidGuardian would be the next option.
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

**Comment by Serfrost** [comment]
@kin-patsu as @mika-n stated, HIDGuardian is your best bet here so you never have to worry about this again unless you update Windows. I just got it set up using the Test Installer in mika-n's link and it's working perfectly. You will need the HidHideTest helper application in that section to hide your DualSense, as the DualSense isn't hidden by default unlike a DS4.  It should be relatively easy to figure out the HidHideTest helper application.

For me I selected the [Wireless Controller] entry, then selected the [HID\VID_054C&PID_0CE6&MI_03] entry, then clicked [Add].  Afterwards I started DS4Windows and it was shown immediately that DS4Windows has exclusive access to the controller with HIDGuardian, and that the regular "Wireless Controller" instance within Joy.cpl is no longer shown at all.

This should prevent all future problems for you, and will probably be the way to prevent this issue in the future.

**Comment by Animus120** [comment]
Thanks for the nice writeup @Serfrost , been trying to setup HIDGuardian but it always fails for my DualSense (thus why I defer to Hide DS4 option since it's simpler). Will try that later for a more permanent solution.

**Comment by kin-patsu** [comment]
@Serfrost I just tried what you wrote, the key icon does show in DS4Windows so the controller definitely is in exclusive mode, however Genshin will detect it only as a 360 controller (even though it's setup to emulate a DS4) and will refuse most inputs unless I change my profile to emulate a 360 controller

**Comment by mika-n** [comment]
When DS4Windows profile is set to output events via a virtual DS4 gamepad then ViGem driver creates that devices as DS4 revision1 (DS4v1). Now, if HidGuardian AffectedDevices list has a DS4v1 hardware type ID then HidGuardian will hide both the physical DualSence gamepad AND the virtual output DS4v1 gamepad. This is why it didn't work because by default HidGuardian/TestInstaller lists both DS4v1 and DS4v2 hardware type IDs. 

If you have a physical DS4v2 gamepad or DualSense gamepad then by removing DS4v1 from HidGuardian affectedDevices registry setting makes the virtual ds4v1 gamepad visible for games.

**Comment by Serfrost** [comment]
>@kin-patsu So I gave a better look at HIDHideTest, which by default comes with a few pre-included entries for what I think is the DS4. Removing those [...] makes everything work perfectly

Peculiar, I didn't have to do this on my end from what I remember, but that's good information to have.  mika-n's explanation addresses why this will occur though and explains why you had the problem.

In either case, I'm glad you got it working.  Enjoy.
