### ISSUE TITLE
Multiple triggers for gyro?

### ISSUE THREAD

**Issue by teeedubb** [Ryochan7/DS4Windows#1633]
Hi all,

I'm configuring my ds4 for use with doom eternal which has no dedicated button mapping for aiming and also has a button for toggling an alternate fire mode (which must be held down to use). I have thought to map an unused button and the button that activates alternate fire mode to each enable gyro which would solve the issue, but it seems as I need to held both buttons down to activate gyro.

Is there any way to have a OR option in the gryo triggers? eg L1 or L2 to activate gyro

Thanks

**Comment by mika-n** [comment]
By "to activate gyro" or by "L1 or L2" to activate gyro" statements above you mean the Gyro/Mouse Joystick/Trigger toggle definition or something else (or Gyro/Mouse/Trigger)?

Those triggers don't support multiple key bindings. However, you may be able to do something like this by using "Load Profile" special action macro. You can bind LoadProfile specAction to different buttons and each of these can load a different or the same profile. This way you could have a specAction in L1 to load a profile where gyroMouse or gyroMouseJoystick is enabled and where as the default profile has this disabled (or the default profile uses L2 as a gyro trigger),

DS4Windows+ViGem cannot emulate gyro output through the virtual gamepad controller (ViGem doesn't support virtual touchpad and gyro movement output feeding). DS4Windows can only read physical gyro events from the physical gamepad and re-map these events to do something else through the virtual output controller (LS/RS stick movement? vJoy axis movement? Mouse movement? etc)
