### ISSUE TITLE
Controller (DualSense) detected as two controllers ?

### ISSUE THREAD

**Issue by 5hidiwen** [Ryochan7/DS4Windows#1634]
**Describe the bug**
While checking on https://gamepad-tester.com/, my dualsense is actually detected two times 
-Wireless Controller (STANDARD GAMEPAD Vendor: 054c Product: 0ce6)
-Xbox 360 Controller (XInput STANDARD GAMEPAD)

The fact is, when i launch Rocket League for ex, it launch the game for 2 players.
On Haven, it launch game in coop, and dont even accept triggers.

**To Reproduce**
1. Go to https://gamepad-tester.com/
2. Hit any key to detect control
3. Two controllers are showing up

**Expected behavior**
One control detected

**Screenshots**

![image](https://user-images.githubusercontent.com/74630936/101273952-b4d1c800-375f-11eb-8776-ab33361aa548.png)

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS5 USB
 - OS: Windows 10 Pro Build 2004
 - DS4Windows Version 2.1.19

**Additional context**
I'm not sure if this is normal, but if there is a way to avoid this problem thanks in advance

**Comment by Ofigelov** [comment]
Yeah, I have the same issue

**Comment by mika-n** [comment]
The double controller issue. Either try to use "Hide DS4 Controller" option (doesn't matter even when it says DS4). But make sure you check the logfile to see if this really works.
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

If the "Hide DS4 Controller" (=exclusive mode) doesn't work then you have to use HidGuardian tool and add the DS5 hardware ID to HidG registry settings.
https://github.com/Ryochan7/DS4Windows/issues/1626

**Comment by 5hidiwen** [comment]
> The double controller issue. Either try to use "Hide DS4 Controller" option (doesn't matter even when it says DS4). But make sure you check the logfile to see if this really works.
> https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues
> 
> If the "Hide DS4 Controller" (=exclusive mode) doesn't work then you have to use HidGuardian tool and add the DS5 hardware ID to HidG registry settings.
> #1626

Awesome! That HidGuardian tool totally worked !
![image](https://user-images.githubusercontent.com/74630936/101291653-1a5d9d00-37d0-11eb-91be-d347396bfab8.png)
![image](https://user-images.githubusercontent.com/74630936/101291658-25183200-37d0-11eb-9538-df9211592415.png)

Thanks Mika !
