### ISSUE TITLE
Dual Sense not working in call of duty modern warfare or call of duty cold war

### ISSUE THREAD

**Issue by Mhinzy** [Ryochan7/DS4Windows#1636]
The controller is connected in DS4Windoes but not useable in the game. I am using a Dual Sense or DS5

**Comment by 5hidiwen** [comment]
Mhh actually its totally working for me on Warzone, but i dont have coldwar. 
Is it working on Warzone? For this game i put my DS5 detected as a DS4, not a microsoft controller, and its actually working 👍

**Comment by Mhinzy** [comment]
Nope that is also not working for me dunno what the problem is

**Comment by mrtostados** [comment]
Are you sure you downloaded the most recent release and not the old Jays2Kings one? That one won't support DualSense at all. The current build of DS4Windows works just fine with my DualSense. It can get a bit finicky if you're over Bluetooth; but I'm sure you've already tried a wired connection. Does it work with other games?

**Comment by Mhinzy** [comment]
I think the problems were done by steam automatic start because i removed steam en removed the settings files and started over now its good👌🏼👌🏼
