### ISSUE TITLE
Lightbar Not Working

### ISSUE THREAD

**Issue by RexxLifeVari** [Ryochan7/DS4Windows#1637]
When my controller is connected the lightbar doesn't work majority of the time. Sometimes (randomly) it will work and I have the rainbow effect turned on. Anyone know how to keep this feature on or manually turn the lightbar on? Not a serious issue just was wondering if anyone had a fix for that. It's a cool feature, especially for controller cam.

**Comment by mika-n** [comment]
not much information in the post. Gamepad model and version? DS4Windows app version? What kind of profile you have? Lightbar mode in Default or Passthrough? Logfile?

See the pinned "Read this before posting a new issue ticket" post.

**Comment by Ryochan7** [comment]
?
