### ISSUE TITLE
High Latency for DS5?

### ISSUE THREAD

**Issue by ensinator** [Ryochan7/DS4Windows#1639]
Hey Folks, is it possible for some reasons (maybe the lack of drivers for now) that the DualSense Controller has a high latency?

As you can see in the screenshot, mine is working good, but every now and then the latency is higher than 10ms (what you notice ingame, e.g. CoD)

Or is there maybe something wrong with my setup? Using USB for now to connect.

Thanks!

![image](https://user-images.githubusercontent.com/75678541/101488107-74d93380-395f-11eb-8972-93ddda36f912.png)

 - Controller Sony DualSense
 - OS: Windows 10
DS4Windows Version 2.1.19

**Comment by mika-n** [comment]
You mean high latency over USB connection? It is very uncommon situation, usually the latency is over BT.

Try using different USB port because some PCs may share the same usb bus with other devices (BT, WLAN,etc).

**Comment by mrtostados** [comment]
I rarely have high latency over BT and virtually never over USB. I virtually never get those red messages. I'd say there might be something up with whatever bus it's trying to send data through. As I am just now seeing,

> Try using different USB port because some PCs may share the same usb bus with other devices (BT, WLAN,etc),

what would have been my suggestion, has already been suggested. Best of luck, though!

**Comment by ensinator** [comment]
Edit: I now tried a different cable and a different usb port (at the back of the pc instead of one port on the front, i think still usb 2.0) and it seems to solve the problem. played a game for 10 mins now without any high latency.

I hope it works now :) Thanks for your quick help!
