### ISSUE TITLE
How many Scp Virtual Bus Drivers are supposed to be there?

### ISSUE THREAD

**Issue by czukowski** [Ryochan7/DS4Windows#164]
Sometimes I'm getting problems as described in #107 or #147. The other day DS4Windows became unresponsive and I went to the Device Manager to try and disable/enable Scp Virtual Bus Driver to see if that would help and I've found **three** devices with that name. Is that normal? Two of those have been "restarted" that way, but for one of those Windows has shown a message saying about changes to configuration have been done and I needed to restart the computer anyway.

I tried to find a screenshot of someone else's Device Manager in the issues here or another reference, but I was not successful.

**Comment by Ryochan7** [comment]
There should only be one Scp Virtual Bus Driver device listed in the Device Manager. Having multiple versions of the Scp Virtual Bus Driver installed on your system would probably cause some big problems. There are several programs that use the Scp Virtual Bus Driver and I would assume many of those use installers that install the Scp Virtual Bus Driver by default. Other programs that I use on my system that also utilize the Scp Virtual Bus Driver are InputMapper and Touchmote. I think that both programs default to installing a copy of the Scp Virtual Bus Driver but I am not sure; I am pretty sure Touchmote installs it by default but the installer gives you the option to omit installing the Scp Virtual Bus Driver.

**Comment by czukowski** [comment]
Thank you for the reply. I also have InputMapper installed, although not using it now, and the third one is possibly a leftover from who knows what. Will try to uninstall it and see if it has also removed any of the devices.

Just out of curiosity, do the applications "know", which of Scp Virtual Bus Driver is "their" or do they try to use the one available?

**Comment by czukowski** [comment]
I've removed all Scp Virtual Bus Driver devices and reinstalled one from Virtual Bus Driver subfolder. Will continue testing to see if it has resolved any of my issues. Feel free to close the issue as I got the answer to my original question.

One note of observation though: I had to run the driver installer manually as admin because when opened from DS4Windows, even though it had started as Task, the installer was failing and leaving an Unknown device (without an exclamation icon) in the Device Manager each time it's run like that. Obviously not DS4Windows' fault though.

```
SCP Driver Installer 1.2.2.175 [30.11.2017 19:08:01]

Detected - Windows 10 Pro (6.2.9200.0 AMD64)
Selected DEFAULT configuration.

SUCCESS - Virtual Bus Created
INFO    - ENTER:  DriverPackageInstallW
ERROR   - Could not open file C:\WINDOWS\system32\System\ScpVBus.inf.
INFO    - RETURN: DriverPackageInstallW  (0x3)

Install Succeeded.

-- Install Summary --
Bus Device
```

**Comment by Ryochan7** [comment]
I would think that any application launched from DS4Windows in that manner would launch with admin privileges. That problem should not occur if DS4Windows is being launched at startup using the Task method. I will take a look into that.

**Comment by Ryochan7** [comment]
I'm sorry but I just got around to testing the run as startup Task functionality. I set up DS4Windows to run at startup as a Task and uninstalled the Scp Virtual Bus Driver before rebooting. Upon booting Windows again, the Welcome Dialog came up as expected and I was able to install the Scp Virtual Bus Driver. It looks like administrative privileges do carry over to processes started using runas when DS4Windows is run as a task.

**Comment by czukowski** [comment]
@Ryochan7 no problem. There could be something wrong in my system. I'll close this issue since the original question has been answered. I'll try driver installation some more when I get a chance and then I may add a reply if I find out anything useful.

**Comment by Ryochan7** [comment]
This might be somewhat unrelated but I noticed that InputMapper will still run the Scp Virtual Bus Driver installation process if the Scp Virtual Bus Driver device is disabled. I have mainly been using ViGEm lately and I have the Scp Virtual Bus Driver device disabled. When I tested InputMapper recently, it caused a second Scp Virtual Bus Driver device to get installed. It looks like InputMapper runs the installation process if it cannot connect to the bus device while DS4Windows looks for a device with the name "Scp Virtual Bus Driver". Even while the device is disabled, DS4Windows is able to find it so the installation process is not run.

**Comment by Ryochan7** [comment]
As pointed out in another issue, there was a case when DS4Windows could fail to find the Scp Virtual Bus Driver device after installation and install a second device. The problem was due to a caching issue inherit with the routine that was being used. The check has been changed to use a different routine so that kind of problem should not occur again.
