### ISSUE TITLE
Exclusive Mode Not Working

### ISSUE THREAD

**Issue by Adore33** [Ryochan7/DS4Windows#1646]
**Describe the bug**
I was using version "DS4Windows_2.1.19_x64" which Exclusive mode was working.
I updated to version "DS4Windows_2.1.20_x64" and Exclusive mode doesn't work.
I rolled back to "DS4Windows_2.1.19_x64" and Exclusive mode is working again.

**To Reproduce**
Use current version "DS4Windows_2.1.20_x64"
Current version is displaying an X in Controllers Tab under Ex.

**Expected behavior**
Expected Exclusive Mode to still work.
To show a Check Mark like normal In Controllers Tab under Ex..

**Screenshots**

**Desktop (please complete the following information):**
 - Sony DS4 v.2 (CUH-ZCT2U)
 - OS: [e.g. Windows 10 - 10.0.19042 Build 19042]
 - DS4Windows Version  - 2.1.20 

**Additional context**
Reverting to previous version as stated fixes the issue.  I do appreciate from the developer that the previous versions are stored in DS4s install directory.  Made it easy for me to revert back until it is resolved.

**Comment by Ryochan7** [comment]
Display fixed in version 2.1.21

**Comment by Adore33** [comment]
@Ryochan7  Just updated to 2.1.21 and CheckMark is back.  Thank you for your response even though I closed the post.  I saw afterward you had posted "[Notice] "Hide DS4 Controller" option Removed".  Thank you for DS4Windows and the frequent updates.
