### ISSUE TITLE
Cannot create new profile. Profile name field disabled on New Profile window

### ISSUE THREAD

**Issue by Lunahria** [Ryochan7/DS4Windows#1647]
I just deleted the default profile and it seems like I can't make a new one because the Profile Name field is grayed out.
Am I missing something?

**Comment by marcValdz** [comment]
I'm having the same issue :<

**Comment by Lunahria** [comment]
> 
> 
> I'm having the same issue :<

I figured you can delete the appdata DS4Windows folder and relaunch the app, which will ask you where to put the app settings again and will re-generate new default profile.

**Comment by marcValdz** [comment]
I just downgraded to a previous version (%installdir%/DS4Windows/Updates), generated a new default profile, then reupdated back to the latest version with the greyed out text box.

**Comment by Ryochan7** [comment]
Not sure how this one happened. Creating a new profile is straight up busted now. The Profile field in the Profile Editor is always disabled so no name can ever be given to a profile. No new profile can be saved. This bug needs to be fixed ASAP.

**Comment by Ryochan7** [comment]
Found the offending commit. The problem is due to commit 72c0f37c5418225c2f357f58b8a52430e3b9fe0c. Must have been testing the theme and didn't revert a change back.

**Comment by Lunahria** [comment]
> 
> 
> Found the offending commit. The problem is due to commit [72c0f37](https://github.com/Ryochan7/DS4Windows/commit/72c0f37c5418225c2f357f58b8a52430e3b9fe0c). Must have been testing the theme and didn't revert a change back.

That was pretty fast, thank you.
I updated and gave creating new profile a try, seems to be working!
Another thing, is it possible to rename profiles after they have been saved?
