### ISSUE TITLE
[Question] What are the SCPvBus builds?

### ISSUE THREAD

**Issue by Darthagnon** [Ryochan7/DS4Windows#1648]
I've noticed the last couple of builds mentioning SCPvBus, and am confused. What are they? Isn't SCPvBus that old DS3/DS4 driver that Nefarius keeps recommending people remove?

**Comment by Ryusennin** [comment]
"updated ScpVBus build for regression testing"

ScpVbus was used before ViGEm. Chances are you don't need it.

**Comment by Ryochan7** [comment]
Some people have requested updated builds. I don't use it outside of regression testing and general curiosity.

**Comment by Darthagnon** [comment]
Thank you for the info!
