### ISSUE TITLE
Crash when trying to edit profile

### ISSUE THREAD

**Issue by Maccaferri** [Ryochan7/DS4Windows#1649]
A of the last two updates, the program crashes whenever I try to edit the profile

**Comment by axonll** [comment]
Same, hope someone posts a fix for this soon

**Comment by Ryochan7** [comment]
Two posts with The thing don't work. People must expect me to be clairvoyant. Ignored the Pinned posts and the issue template. It works on my end and there is nothing else to work with. Either way, I am locking this issue.

**[Notice] Read this before posting a new issue ticket (Troubleshooting tips)**
https://github.com/Ryochan7/DS4Windows/issues/1196
