### ISSUE TITLE
DS4Windows crashes whenever I try to edit profile

### ISSUE THREAD

**Issue by axonll** [Ryochan7/DS4Windows#1651]
**Describe the bug**
Any time I click "Edit" DS4Windows stops working

**To Reproduce**
1. Open DS4Windows
2. Connect controller
3. Press "Edit"
4. DS4Windows crashes

**Expected behavior**
For DS4Windows not to crash

**Screenshots**

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2e)
 - OS: [e.g. Windows 10 Pro Build 20H2
 - DS4Windows Version ((any version I try to use, tried latest all the way to 2.1.16))

**Additional context**

**Comment by mika-n** [comment]
#1650
