### ISSUE TITLE
Emulating Touch screen for windows 10?

### ISSUE THREAD

**Issue by KateHanami** [Ryochan7/DS4Windows#1652]
Disclaimer: I have not idea how to use github, not sure is this is the right way to do it

so, windows 10 have some native features for touch support, and while you could use the touchpad with absolute output, it would be more.... practical(?) to take advantage of these features, similar to how it's already implemented with Cemu hook

**Comment by Ryochan7** [comment]
I don't see a use case for trying to implement something like that. I am not sure that SendInput even allows creating fake Touch events that the system can recognize. VMulti might be needed to create a fake Touch cursor of some kind.

**Comment by KateHanami** [comment]
there's some kind some android app that let's you use your touch touchscreen in windows, but that doesn't really matter
if you looking for practical uses, here: https://store.steampowered.com/curator/6857883-Touch-friendly-games/
besides the gimmeck-y feel to it, there's no real reason
