### ISSUE TITLE
Dark Mode Crashes App

### ISSUE THREAD

**Issue by shinra358** [Ryochan7/DS4Windows#1655]
Navigating tabs in the app works fine. But when I put it on dark mode, it still has black text so you can't see the options. Also, if you navigate to another tab during this time, the app will crash. If you restart it, a blank icon will appear in the taskbar but app will never relaunch. Starting debug mode and then exiting will allow you to start the original app exe again. app = ds4windows.

**Comment by mika-n** [comment]
Dark mode works here. How about posting the latest logfile as TXT attachment (ie. rename the .log file as .txt and drag-n-drop the file here, not copy-paste the text. It is easier to browser though the logfile as file attachment).

**Comment by Ryochan7** [comment]
I can confirm that this issue occurs on my Windows 7 VM.

**Comment by Ryochan7** [comment]
Got the Log file pulled. It looks like an assembly file might be missing for Windows 7.

[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/5689987/ds4windows_log.txt)

**Comment by Ryochan7** [comment]
Tested it out and the last commit fixes Dark mode in DS4Windows when run in Windows 7
