### ISSUE TITLE
DualShock 4 Emulation lagging?

### ISSUE THREAD

**Issue by BlackAzrael128** [Ryochan7/DS4Windows#1664]
I just recently decided to try switching over to DS4Windows from the old Input Mapper 1.6.

I like the features and settings, especially the DS4 Emulation, however I'm having a strange lagging issue.

In bluetooth, when it's set to DualShock 4 in emulated controller (Other tab for settings), it says the Input delay is about 1ms but I definitely feel a delay in the inputs. Same problem in wired but it says around 3-3.5ms input delay in controller readings.

Yet when I set it to Xbox 360 as emulated controller, everything is just fine.

What's even more strange is that when I plug the DS4 wired without DS4Windows running, it works just fine (in a game that natively supports DS4 controller)

Any ideas on how to fix this if it's even possible?

EDIT: Sorry, forgot to include logs.
[ds4windows_log_20201216.1.txt](https://github.com/Ryochan7/DS4Windows/files/5705153/ds4windows_log_20201216.1.txt)
[ds4windows_log_20201216.2.txt](https://github.com/Ryochan7/DS4Windows/files/5705154/ds4windows_log_20201216.2.txt)
[ds4windows_log_20201216.3.txt](https://github.com/Ryochan7/DS4Windows/files/5705155/ds4windows_log_20201216.3.txt)
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/5705156/ds4windows_log.txt)
[ds4windows_log_20201216.0.txt](https://github.com/Ryochan7/DS4Windows/files/5705157/ds4windows_log_20201216.0.txt)

**Comment by mika-n** [comment]
The delay value in the "Controller Inputs" tab page is not scientifically accurate down to fraction of milliseconds, the value is just giving some indication between "good vs bad" delay but I wouldn't take it too seriously as comparing 3ms vs 3.5ms delays.

When you say "you definitely feel a delay" then where you feel this delay? In a game? The game itself may have something to do with this if it supports both xbox (xinput) and ds4 (dinput) gamepads. Maybe the game does something differently with xinput and dinput HID interfaces?

The logfile didn't show any DS4Windows warning messages about lag, so as long you don't see these warning messages then I would not worry too much about it (as far DS4Windows app is considered). What a game does or doesn't do with certain gamepads is another story, but it is out of DS4Windows scope.

**Comment by BlackAzrael128** [comment]
I tried in 3 games: Cyberpunk 2077, Witcher 3, and Shadow of the Tomb Raider.

I compared between just the normal 360 emulation and DS4, I notice a slight delay with DS4 emulation.

It's more noticeable with the analogs and maybe d-pad than anything else. It doesn't feel as responsive with DS4 emulation, when moving the camera with the analog in game especially. Sorry, I'm not sure how else I can explain it.

**Comment by Ryochan7** [comment]
For the most part, responsiveness should have been about equivalent. It can depend on the game though. I believe Rocket League is more responsive with a virtual Xbox 360 controller than a virtual DS4. Virtual DS4 support is a bit more snappy on my system than just using the game's native support without DS4Windows running. It has worked well enough so far.

My usually use case for DS4 output is when I play older PC games that only support DirectInput. DS4 output seems more snappy for that use case than outputting to a virtual Xbox 360 controller.

I see that you are using the latest ViGEmBus 1.17.333.0 driver. There is a branch that is being worked on to support the newer API for virtual DS4 output. It seems to be more responsive than the routine using the old API; some changes might occur with the old API interface as well. The new routine seems more snappy even with the extra data (Touchpad and Gyro) mapped to the virtual DS4 controller. Maybe a future DS4Windows update will help improve the experience for you.

**Comment by BlackAzrael128** [comment]
For me, there was only a handful of games that were working just fine with the DS4 emulation. It's good to know about the newer API though. Hopefully it fixes it for me in the next branch. Thank you very much, in the meantime I'll just stick with the default Xbox 360 emulation!
