### ISSUE TITLE
Download Speed is very slow in Malaysia

### ISSUE THREAD

**Issue by ooJetLeeoo** [Ryochan7/DS4Windows#1665]
Sorry for my English. I cant download ViGEmBus it runs at 0KB/s, is it because of region?

![image](https://user-images.githubusercontent.com/76165346/102492113-238e1a00-40ac-11eb-8332-1da04b88b389.png)

![image](https://user-images.githubusercontent.com/76165346/102492198-50dac800-40ac-11eb-8a5b-825e4a37d043.png)

**Comment by mika-n** [comment]
Well, the server side for sure won't cap the download speed to Malaysia so maybe just a client side issue or a temporary network issue. After all the download url points to AWS cloud machine, so I would not blame it at first for being slow.

**Comment by ooJetLeeoo** [comment]
alright, thank you very much👍👍
