### ISSUE TITLE
New Fortnite update not working with DS4Windows

### ISSUE THREAD

**Issue by iamkruse** [Ryochan7/DS4Windows#1666]
**Describe the bug**
I am not sure if Fortnite released an update or what happened but it is no longer working properly with Fortnite. I can't access settings, the map, inventory and the sensitivity is so high; it is like I am using keyboard and mouse settings for my PS5 controller.  I also am unable to switch weapons properly as it goes from slots 1, 3 and 5 rather than 1, 2, 3, 4 and 5. None of my settings have been changed in the game or anything like that so I have narrowed it down to either a new Fortnite update not supporting DS4Windows? Or DS4Windows not supporting a new Fortnite update? Both are updated to the latest version and I had the same exact problems when I tried a PS4 controller

**Expected behavior**
The controller to continue to be compatible for Fortnite

**Desktop (please complete the following information):**
 - Controller Make and Model: DualSense PS5 Controller (model CFI-ZCT1W)
 - OS: Windows 10 Home 19041.685 (v 2004)
 - DS4Windows Version 2.1.22

**Comment by mika-n** [comment]
Sounds like "double controller" issue.

https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#double-input-problem-in-games-game-does-all-sort-of-weird-things-when-i-press-a-button-second-player-drops-in-cannot-navigate-in-menus-because-focus-moves-two-lines-when-i-press-a-key-just-once-etc

https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

**Comment by iamkruse** [comment]
This worked. Thank you! Sent from Mail for Windows 10 From: mika-nSent: Thursday, December 17, 2020 4:59 PMTo: Ryochan7/DS4WindowsCc: iamkruse; AuthorSubject: Re: [Ryochan7/DS4Windows] New Fortnite update not working with DS4Windows (#1666) Sounds like "double controller" issue.https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#double-input-problem-in-games-game-does-all-sort-of-weird-things-when-i-press-a-button-second-player-drops-in-cannot-navigate-in-menus-because-focus-moves-two-lines-when-i-press-a-key-just-once-etchttps://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
