### ISSUE TITLE
Crashing when setting Emulated Controller to Dualshock 4

### ISSUE THREAD

**Issue by MadAd360** [Ryochan7/DS4Windows#1667]
**Describe the bug**
DS4Windows crashes consistently when setting Emulated Controller to Dualshock 4. First noticed this when trying the DualSense and reverted to DualShock to confirm the issue. Was unable to run the debug mode, but attached what I could gather.

[ds4windows_log_20201217.31.txt](https://github.com/Ryochan7/DS4Windows/files/5712687/ds4windows_log_20201217.31.txt)

**Expected behavior**
DS4Windows to continue to run and output as DS4

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DualSense and Sony DS4
 - OS: Windows 10 Pro 10.0.19042
 - DS4Windows Version: 2.1.22

**Comment by sebzukowski** [comment]
I am having the same issue. when using dualsense. When selecting profile other than default the app crashes.

**Comment by MadAd360** [comment]
This might be a non-issue, had to redownload and picked x86 instead of x64, works after I moved to x64.

**Comment by Ryochan7** [comment]
I am not sure why this would happen. Running the x86 build of DS4Windows and using virtual DS4 output works fine for me. As far as I know, the main drawback to running the x86 build on a 64 bit Windows install is that there is no chance for the **Hide DS4 Controller** option to work.
