### ISSUE TITLE
check battery life no longer working properly

### ISSUE THREAD

**Issue by rdtoi1** [Ryochan7/DS4Windows#1668]
Ever since I've used ds4windows I've used the check battery life special action, set to 'hold for 0 secs'
As of ~2 updates ago it was working normally(colouring the lightbar the whole time the button is held)
Now when I press the button, it stays that colour for 3 seconds after letting go of the button

Sony DS4 v.2 (CUH-ZCT2U)
Windows 10 Pro Build 2004
DS4Windows 2.1.22

**Comment by mika-n** [comment]
Strange. Here the latest 2.1.22 and "check battery" and "hold for 0 secs" seems to work (ie. the battery value is indicated right away when the btn is held down and remains so until the button is released. The indication via lightbar color is restored immediately when the trigger key is released).

Maybe something strange in your profile file?

**Comment by rdtoi1** [comment]
Okay, I did some further testing for you with a fresh download.

This only seems to occur if the default lightbar colour is set to 0,0,0

**Comment by mika-n** [comment]
Probably related to #1663 case. The fix to 1663 is already in the code waiting for to be officially released. However, the debug version already has the code change, so you might wanna try it to test if it solves the issue there (at least here it seems to be working)
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems
