### ISSUE TITLE
System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by Farid566** [Ryochan7/DS4Windows#167]
I connected two gamepads. After clicking Edit (Edit Profiles in tab Controllers) button issue below was appeared:

 I found that error is going from my profile even gamepads is turned off.

>Подробная информация об использовании оперативной 
(JIT) отладки вместо данного диалогового 
окна содержится в конце этого сообщения.

>************** Текст исключения **************
System.ArgumentOutOfRangeException: Значение '-1' недопустимо для 'Value'. 'Value' должно лежать в диапазоне от 'Minimum' до 'Maximum'.
Имя параметра: Value
   в System.Windows.Forms.NumericUpDown.set_Value(Decimal value)
   в DS4Windows.Options.Reload(Int32 deviceNum, String name)
   в DS4Windows.DS4Form.ShowOptions(Int32 devID, String profile)
   в System.Windows.Forms.Control.OnClick(EventArgs e)
   в System.Windows.Forms.Button.OnClick(EventArgs e)
   в System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   в System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   в System.Windows.Forms.Control.WndProc(Message& m)
   в System.Windows.Forms.ButtonBase.WndProc(Message& m)
   в System.Windows.Forms.Button.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

>************** Загруженные сборки **************
mscorlib
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.2600.0 built by: NET471REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
>DS4Windows
    Версия сборки: 1.4.103.0
    Версия Win32: 1.4.103
    CodeBase: file:///C:/Users/Wingear/Desktop/DS4Windows/DS4Windows.exe
----------------------------------------
>Microsoft.Win32.TaskScheduler
    Версия сборки: 2.5.28.0
    Версия Win32: 2.5.28.0
    CodeBase: file:///C:/Users/Wingear/Desktop/DS4Windows/Microsoft.Win32.TaskScheduler.DLL
----------------------------------------
>System.Windows.Forms
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
>System
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
>System.Drawing
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
>mscorlib.resources
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
>System.Xml
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
>System.Configuration
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
>System.Core
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.2600.0 built by: NET471REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
>System.Management
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
>System.Windows.Forms.resources
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

>************** Оперативная отладка (JIT) **************
Для подключения оперативной (JIT) отладки файл .config данного
приложения или компьютера (machine.config) должен иметь
значение jitDebugging, установленное в секции system.windows.forms.
Приложение также должно быть скомпилировано с включенной
отладкой.

>Например:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

>При включенной отладке JIT любое необрабатываемое исключение
пересылается отладчику JIT, зарегистрированному на данном компьютере,
вместо того чтобы обрабатываться данным диалоговым окном.`

**Comment by Ryochan7** [comment]
I just tried this with version 1.4.103 and it works fine for me with no controllers and multiple controllers connected. Looking at the error, some number is out of bounds but the error does not specify which control is being edited when the error occurs. Maybe you should check the profile you are trying to edit and see if a -1 is stored somewhere.

**Comment by Ryochan7** [comment]
With no new information, there is nothing that I can do.
