### ISSUE TITLE
Auto profile doesn't add "EXE" files, only "exe" 

### ISSUE THREAD

**Issue by Vandal101** [Ryochan7/DS4Windows#1670]
Some older games that have all caps "EXE" files are not added to auto profiles

1. Go to 'Auto Profiles'
2. Click on 'Add Programs'
3. Click on 'Browse for Other Programs'
4. Select a game with a .EXE file 
5. Game isn't added to the list

Expected behavior:
The game should be correctly added to the list like any other exe file

Desktop:
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: Windows 10 Home 1909
 - DS4Windows 2.1.22

**Comment by mika-n** [comment]
Confirmed. The good news is that the bug is now fixed and the next official release should have this fix.
