### ISSUE TITLE
15ms Input delay with Switch Pro Controller

### ISSUE THREAD

**Issue by digitaldelboy** [Ryochan7/DS4Windows#1673]
I noticed the input delay was 15ms over bluetooth compared to 3ms with the dualsense.

Is it supposed to be that high and if not is there any way to lower it or is that a DS4 issue. I tried using SPC wired but DS4 only shows it as charging and no inputs work so I dont think wired is supported yet.

**Comment by Ryochan7** [comment]
That is a hardware limit.
