### ISSUE TITLE
Sekiro doesn't detect DS4 pad anymore

### ISSUE THREAD

**Issue by magmadragoon** [Ryochan7/DS4Windows#1676]
Using Dualshock 4 v1 and Windows 7 

About a year ago I finished the the game. I never uninstalled/reinstalled the game or DS4Windows. As far as I can tell, the only thing that's changed is autoupdates to DS4W. Oh, and the game is bootleg, so it's not an update.

I've tested XInput with the included tools, I've played other XInput games. Everything works except for Sekiro. It doesn't detect the gamepad at all, other than the touchpad emulated mouse click.

**Comment by Ryusennin** [comment]
Sekiro requires exclusive mode. The old "Hide DS4" option doesn't cut it. You need to install HidGuardian.

https://github.com/Ryochan7/DS4Windows/wiki/DS4Windows-and-HIDGuardian-Install-and-Setup-Guide#hidguardian-test-installer

**Comment by magmadragoon** [comment]
Great, thx.

This is new, I presume? Any chance of implementing it (back) into DS4W?

**Comment by Ryusennin** [comment]
"Hide DS4" is still present in DS4W, but it won't work for many recent games. HidGuardian is usually the most reliable solution to enable exclusive mode.

https://github.com/Ryochan7/DS4Windows/issues?q=sekiro
