### ISSUE TITLE
Gamepad data write connection is lost. LastErrorCode=1784

### ISSUE THREAD

**Issue by luis0henrique** [Ryochan7/DS4Windows#1677]
So, a couple of days ago, I was using the app normally. When I tried to play today, I noticed some strange behaviors.

First, on the Controller tab, it showed 2 controllers connected, one with 0% battery and another with 100% battery, which is mine. And at the bottom there is a message saying:
_"Gamepad data write connection is lost. Disconnecting the gamepad. LastErrorCode=1784"_

I disconnected and tried again, now it shows only my controller, but the message is still there and on the Log tab it shows multiple times/lines. My controller seems to work fine, despite those messages and the fact that I can't change the lightbar, it's stuck on the blue light.

I tried the debug version, but I don't understand what is happening, so I attached the two Log files:

[log debug.txt](https://github.com/Ryochan7/DS4Windows/files/5721428/log.debug.txt)
[log.txt](https://github.com/Ryochan7/DS4Windows/files/5721429/log.txt)

Edit: Using version 2.1.18 seems to solve this issue

DS4Windows 2.1.22
Sony DS4 v.1
Windows 7 Home Premium

**Comment by mika-n** [comment]
Win7 support is becoming more and more problematic after each release. I suggest you finally upgrade to Win10 OS version 👍 

Anyway. Try toggling WinOS bluetooth on and off to cleanup BT stack.

**Comment by ExpatUK** [comment]
Can confirm this issue on Windows 7 x64. 2.1.18 is the last fully functional version.

**Comment by luis0henrique** [comment]
I want to upgrade to W10, but not until I get a SSD or upgrade my entire PC. I have a dual boot with Ubuntu 20.04 and use W7 mainly for gaming.

Anyway, I understand that support for it is becoming more difficult with time, so I'll stick with 2.1.18 and testing new releases when they come out to see if those issues are gone

**Comment by Ryusennin** [comment]
The only major change in 2.1.19 was apparently a fix for broken translations. How can it affect Win7?

**Comment by shinra358** [comment]
Still exists after new update today.

**Comment by Ryochan7** [comment]
Confirmed that sending output reports via the Interrupt endpoint is not possible in Windows 7 using the Microsoft BT stack. Made a change in commit b0f5c4c2bd1f1e73f44f2ab724480730b7645d99 to check the OS version and revert to using the Control endpoint on Windows 7. This change will only affect DS4 devices.

I will have to double check the DualSense class but it seems like force feedback and other output data will not work on a Windows 7 install for the DS. Based on my initial testing on Windows 10, the DualSense will only accept data via the Interrrupt endpoint.

**Comment by Ryochan7** [comment]
Okay. I have also found out that Steam Input suffers the same limitation on Windows 7 regarding the DualSense connected via Bluetooth. I did some minor hacking of the DualSenseDevice class and still didn't get any response from the controller. It is pretty safe to say that it is just not doable on Windows 7 when using BT.

**Comment by mika-n** [comment]
Good findings @Ryochan7    And I guess it is pretty safe to say that Win7 really is coming to the end of its life time. If more and more weird bugs like this popup then Win7 users may face the hard decision soon.

**Comment by Ryusennin** [comment]
The final nail in the coffin could be ViGEm 1.17 which requires Win10.

**Comment by luis0henrique** [comment]
Yep, Windows 7 is definitely showing its age.

**Comment by ExpatUK** [comment]
Still, it's the preferable operating system in an offline arcade/emulation system just for reliability, and compatibility with all the older bells and whistles of PC gaming. Would be nice if the last working version could be archived and made available for such purposes rather than forgotten.

**Comment by mika-n** [comment]
For sure the GitHub releases page of this app contains all versions, so all current and historical versions remain there to be downloaded. Well, as certain as anything can be with Interweb and online archives and cloud services.

**Comment by Ryusennin** [comment]
Version 2.2.1 is still operational on Win7 via USB (didn't try BT though, but it should be fixed).

**Comment by Ryochan7** [comment]
Version 2.2.1 is the last planned release that will incorporate workarounds for Windows 7. Several changes were made to account for differences in behavior on Windows 7 with the initial version 2.2 release. Especially with ViGEmBus 1.17.333.0 only working in Windows 10 and finding out that DualSense BT output support is not possible on Windows 7, people are probably going to have to migrate to Windows 10 eventually.

**Comment by shinra358** [comment]
Yeah, gravy now. Same with BT.
and......

aaaaaaaaaaAAAAAAAAAAAAAAAAAaaaaaaaaaaaaaaaaaHHHHHHHHHHHHHHHHHHHHHHHHHHHHH!

**Comment by MediaMaquina** [comment]
So can't the program detect if it's windows 7 and not display that message ?
It renders the log hard to read.

**Comment by Ryochan7** [comment]
The original problem has been fixed. Although, this whole issue shows how Windows 7 is just not capable of providing some desired functionality. Also, ViGEmBus using newer tech in the version 1.17.333.0 release is the final nail in the coffin when it comes to Windows 7 support.

**Comment by MediaMaquina** [comment]
Cool, i wish win10 wasn't a giant bloated spyware disguised as an OS.
Not a problem i'll take my error.

**Comment by luis0henrique** [comment]
Version 2.2.1 is working great here, thank you guys!
