### ISSUE TITLE
no vibration on fortnite when using ds4 for ps5 controller

### ISSUE THREAD

**Issue by bruhmoment6932f** [Ryochan7/DS4Windows#1678]
it could be on my end but when I use ds4 for my ps5 controller now on fortnite it doesnt take ds4's input and won't use it as the main one. so im left with no vibration for my controller like i used to get with ds4. if there is any solutions pls lmk.

**Comment by Ryochan7** [comment]
The game does not support it. Fortnite reads the DS4 as a DirectInput controller.
