### ISSUE TITLE
audio volume "curve" changes when using my controller with ds4windows compared to the native drivers?

### ISSUE THREAD

**Issue by Ghostlyboo** [Ryochan7/DS4Windows#168]
ill try to explain it the best i could, but excuse me since english isn't my first language,
when i connect my headphones to my controller while NOT using any programs, the audio "curve"([this one](https://imgur.com/a/zfOAr)) stays the same as connecting my headphones directly to the motherboard, in which 10-20% is my preferred audio level
but when using ds4windows, the "curve" changes, 20% becomes waaay too quiet and my preferred level becomes something around 50%, also 100% feels a _tad_ fake, almost like it was artificially increased

i don't know much about audio but the first thing i thought about was that, without ds4windows the audio was just passing through my controller, but while ds4windows is on it was using the dac inside the controller? 
im pretty sure its incorrect but it's the first thing that came to my mind

**Comment by Ryochan7** [comment]
The audio volume does seem different once DS4Windows starts sending output reports but I have not gotten around to trying to see if the issue can be corrected.

**Comment by Ghostlyboo** [comment]
it's not really a big problem, i was just wondering
thanks for the reply man

**Comment by Ryochan7** [comment]
A different range and an cubic easing out curve is used for the audio volume level now. The resulting output volume at various settings seems to be close enough to the level experienced before launching DS4Windows.
