### ISSUE TITLE
Hello, Any version above 2.1.17 and any attempt to update, start with ..."DS4Windows has stopped working"...any idea why? 10x

### ISSUE THREAD

**Issue by Whatsup12345** [Ryochan7/DS4Windows#1680]

**Comment by Whatsup12345** [comment]
Windows 7, x64...

**Comment by mika-n** [comment]
Log files?
Windows eventlog?

**Comment by Whatsup12345** [comment]
Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	DS4Windows.exe
  Problem Signature 02:	2.1.22.0
  Problem Signature 03:	dfc65f21
  Problem Signature 04:	mscorlib
  Problem Signature 05:	4.7.2053.0
  Problem Signature 06:	58fa6bc1
  Problem Signature 07:	3a93
  Problem Signature 08:	79
  Problem Signature 09:	System.IO.FileNotFoundException
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	f6aa
  Additional Information 2:	f6aab5c4175c549889bd8ab3207f5d4c
  Additional Information 3:	4f04
  Additional Information 4:	4f04dc2dd425ad64e32dc82b820e5d48

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt


This one?

**Comment by Whatsup12345** [comment]
So, no idea why I can only open 2.1.17 version?..:(

**Comment by mika-n** [comment]
Scenario 1: You probably have outdated Microsoft .NET framework libraries. Update to the latest MS .NET library version: https://dotnet.microsoft.com/download/dotnet-framework

Scenario 2: Something strange with language localization files. Try starting from scratch with the latest version of DS4Windows app (ie. remove everything from %APPDATA%\DS4Windows\ folder and extract the latest version of DS4Windows to a new folder like c:\games\DS4WinApp\  to make sure some left over files from an old version is not causing issues.

**Comment by Whatsup12345** [comment]
.NET Framework 4.8 solved my problem.....10x!!! :+1:
