### ISSUE TITLE
Compatibility issues with Mayflash NS-Magic (BT USB dongle that works with a lot of consoles / PC)

### ISSUE THREAD

**Issue by BakonBlitz** [Ryochan7/DS4Windows#1684]
**Describe the bug**
I am currently using a Mayflash NS-Magic Bluetooth Dongle to have my PS4 controller work with my PC. I have tried other BT dongles before and they could never recognize the PS4 controller or any of my other controllers. The Mayflash is the only thing that worked so far and is also recognized with Steam. The problem with Steam is that for some reason I cannot adjust the Triggers variable movement. If I press on L2 or R2 it's either going 100% or 0%, there is no in between. So I am trying to use DS4Windows but the adapter seems to not be recognized by DS4Windows.

**To Reproduce**
1. Get a Mayflash NS-Magic USB dongle. (It's pretty useful if you have other consoles, especially a Nintendo Switch)
2. Pair a PS4 Controller to it in DINPUT mode by plugging the controller in the USB dongle itself. Yes, there is a second plug inside that dongle.
3. Open DS4Windows and nothing is shown.

**Expected behavior**
Expected the controller to get recognized by DS4Windows.

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: Windows 10 Pro Build 18363.1256
 - DS4Windows Version 2.1.22

**Comment by mika-n** [comment]
DS4Windows app itself has nothing to do with BT/USB dongles and pairing. You have to do it in WinOS level already before doing anything in DS4Windows app. If WinOS cannot pair the gamepad then DS4Windows app cannot see it either. Or is the gamepad supposed to be seen by WinOS and games as "usb connected DS4" even when it is BT connected to that special dongle?

What do you see in JOY.CPL controlPanel applet when you have connected the gamepad to that dongle AND DS4Windows app is NOT running yet? Run "JOY.CPL" command to open the controlPanel applet. Do you see "Wireless Controller" dinput ds4 gamepad there and does it react to button presses in Properties screen?

And now when you launch DS4Windows app then what do you see then in JOY.CPL screen?

How about if you run the debug version of DS4Windows app? What do you see in the latest logfile? %APPDATA%\DS4Windows\Logs folder.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

**Comment by mika-n** [comment]
closed as inactive
