### ISSUE TITLE
razer raiju ultimate controller

### ISSUE THREAD

**Issue by pyromancer5** [Ryochan7/DS4Windows#1685]
after the update it wont discover my  razer raiju ultimate controller :( can you fix it like befor

**Comment by mika-n** [comment]
Try running the debug version and provide the logfile.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

However, probably the same issues as in #1659   The fix is already in the repository, but the new version is not yet released. However, the debug version already has this fix, so give it a test run.

**Comment by pyromancer5** [comment]
ty :D it worked with this debug thing...sry am not good at this but after putting it in the same folder now raiju conect with bluetooth again ^^ hope it will be fixed next version

**Comment by pyromancer5** [comment]
i skiped the update btw stoped at 1,19 or somthing like that now when the new version come how can i make it tell me about new update again? and about section doesnt tell me wich version is am using...ty so much for ur awsome softwere without i would never be able to play alot of games via bluetooth

**Comment by mika-n** [comment]
The "Logs" tab page of DS4Windows shows a detailed version information.
And to re-enable automagic updates you can set an option in "Settings" tab page in DS4Windows.

**Comment by pyromancer5** [comment]
log verion found it BUT re-enable automagic updates not there in Settings its just check for update every day or hour...and when i check manually its say my Version 2.1.19 is up to date help plz i want it to get back to tell me about updates after i get Version 2.1.23 since am using raiju and ps5 now i need this...ty for the help in advance

**Comment by FJRMaverick** [comment]
2.1.23 just arrived here and my Razer Raiju TE works with that version again.
