### ISSUE TITLE
Gamepad data write connection is lost. Disconnecting the gamepad. LastErrorCode=1784

### ISSUE THREAD

**Issue by shinra358** [Ryochan7/DS4Windows#1686]
[issues.txt](https://github.com/Ryochan7/DS4Windows/files/5732126/issues.txt)

Light not working correctly. System info in file. Error log spam. Newest version as of today's date. Controller still seems to function correctly though as far as controlling the game.

**Comment by mika-n** [comment]
Duplicate with #1677. Closed this one. Anyway, Win7 support is nowadays problematic and I'm not sure if any developer has a Win7 workstation anymore to test and debug those issues. If things work over USB then I guess it is time to move on to Win10 or stick with Win7+usb connection.

**Comment by shinra358** [comment]
ryochan has win7 vm
