### ISSUE TITLE
Dualsense rumble too strong?, gyro unusable at default settings when rumble is in use

### ISSUE THREAD

**Issue by leronoa** [Ryochan7/DS4Windows#1687]
**Describe the bug**
With the default settings on a Dualsense, when the rumble is in use the gyro is affected, shaking the pointer as a mouse and going left or right as mouse as joystick. You need to either reduce rumble to 5% and increase the deadzone to around 150 or disable rumble altogether to make it usable on mouse as joystick, if not it will start moving the camera right or left when firing automatic weapons. You can see it well in the 'Controller Readings' and 'Xinput Checker' on DS4Windows.  Is this normal behaviour for this controller?

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony Dualsense (CFI-ZCT1W)
 - OS: Windows 10 Pro 20H2
 - DS4Windows Version [2.1.22]

**Comment by frubo** [comment]
I recently mapped gyro down to L3 and noticed the same thing.

**Comment by Ryochan7** [comment]
Using normal rumble and Gyro at the same time? Seriously? Either disable rumble in game or lower the Rumble intensity in the profile. This is not a bug.
