### ISSUE TITLE
Extremely High Input Delay on DS5 and DS4

### ISSUE THREAD

**Issue by KirbyFrost** [Ryochan7/DS4Windows#1688]
Every time I connect my DS5 or DS4 v.2 to DS4Windows Version 2.1.22 (any version) on Windows 10, the input delay is extremely high and makes the controllers unusable. I tried uninstalling and reinstalling DS4Windows and ViGEmBus multiple times but it didn't work.

Edit:
Over BT on the DS5 the input delay is extremely high. Here is the log: 
[BT Extremely High Input Delay Log.txt](https://github.com/Ryochan7/DS4Windows/files/5739979/BT.Extremely.High.Input.Delay.Log.txt)

Over USB on the DS5 the input delay hovers around 3.5 ms. This is higher than it used to be. Here is the log: [USB Medium Input Delay Log.txt](https://github.com/Ryochan7/DS4Windows/files/5739982/USB.Medium.Input.Delay.Log.txt)

DS4's results are similar.

**Comment by Ryusennin** [comment]
USB? BT? Log?

**Comment by KirbyFrost** [comment]
Added an edit to the post

**Comment by frubo** [comment]
Check device manager (might need to enable the hidden devices options) for an unknown device under bluetooth and uninstall it; go to 'windows settings -> devices -> bluetooth & other devices' check if there's a paired unknown device and unpair it.

**Comment by KirbyFrost** [comment]
There isn't an unknown device. It's showing up as 'Wireless Controller' in both the device manager and Bluetooth settings. Any other ideas?

**Comment by mika-n** [comment]
Try these tips if you use BT connection. If you have BT dongle then try to use usb extension cable to move the BT usb dongle further away from the PC chassis and take it closer to desk level where the gamepad is.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#gamepad-connection-over-bluetooth-bt

Try running the debug version to generate a lot more detailed debug logfile.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

**Comment by mika-n** [comment]
closed because if the tips shown in the wiki docs won't help then there is not much to do on software side. Could be BT hardware incompatibility/incapability issue to deal with the high frequency/high volume DS4 gamepad data. The same BT may work just fine with mobile phone or sports watch or printer, but those usually don't send and receive data in such a high frequency as gamepads want to do.
