### ISSUE TITLE
dualsense official driver released for linux

### ISSUE THREAD

**Issue by TheMasterDingo** [Ryochan7/DS4Windows#1692]
https://www.phoronix.com/scan.php?page=news_item&px=Sony-HID-PlayStation-PS5

just wanted to share, please delete if is the wrong place

**Comment by Qarasique** [comment]
Good news

**Comment by Ryochan7** [comment]
Maybe for Linux users. Doesn't really do much right now for people on other OSes. There are no new capabilities that are exposed with the driver that haven't already been deciphered.

**Comment by TheMasterDingo** [comment]
> Maybe for Linux users. Doesn't really do much right now for people on other OSes. There are no new capabilities that are exposed with the driver that haven't already been deciphered.

Okay, just thought it might help :P

**Comment by Lunahria** [comment]
> 
> 
> Maybe for Linux users. Doesn't really do much right now for people on other OSes. There are no new capabilities that are exposed with the driver that haven't already been deciphered.

On the Steam Beta branch, Steam Input got an update that now supports the player slot LED, I wonder if that was also exposed?
Unfortunately, unlike DS4, despite turning off the PlayStation configuration support in Big Picture, Steam still applies control over DualSense and it messes up with DS4Windows now, making the controller act up and plug in as a 2nd controller from what I can see, with the 2 LEDs being turned on and the lightbar color changing to red while Steam is running.

**Comment by Ryochan7** [comment]
The byte that controls the player LEDs has been known for weeks.

**Comment by Ryochan7** [comment]
There really isn't much more to bring up at this time. Maybe some changes will get added that will expose more about the controller in the future.
