### ISSUE TITLE
DualSense shows up as xbox360 controller

### ISSUE THREAD

**Issue by JurnyJudasz** [Ryochan7/DS4Windows#1697]
**Describe the bug**
Dualsense loads all the times and in all games as xbox360 controller.

**Expected behavior**
Showing playstation icons in game and behaviour.

**Screenshots**
![logs](https://user-images.githubusercontent.com/64033761/103157605-04cb0a00-47b5-11eb-8339-3b06c934db0f.png)

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DualSense(CFI-ZCT1W)
 - OS: Windows 10 Pro
 - DS4Windows Version 2.1.23.0

**Additional context**
This occurs in every games that I own in GeforceNow

**Comment by Ryochan7** [comment]
Literally the main reason this program exists. From the README.

> DS4Windows is an extract anywhere program that allows you to get the best DualShock 4 experience on your PC. By emulating a **Xbox 360 controller**, many more games are accessible.

Maybe I should just outright remove the DS4 emulation option. People don't understand the point. Hardly any PC games natively support the DS4 nor the DualSense.
