### ISSUE TITLE
Old playstation controllers like six axis works with DS4Windows software?

### ISSUE THREAD

**Issue by Shadoware** [Ryochan7/DS4Windows#1698]
I would like to know if this software works with older playstation controllers but I didn't find this information!

**Comment by mika-n** [comment]
You mean PS3 gamepads? This app doesn't support those. In theory it would be possible via BthPS3 (https://forums.vigem.org/topic/362/playstation-r-3-peripherals-unofficial-bluetooth-drivers-bthps3) driver, but this app doesn't read PS3 gamepads.
