### ISSUE TITLE
How to contribute with a new translation?

### ISSUE THREAD

**Issue by avsha114** [Ryochan7/DS4Windows#1699]
Hi!
I would like to help with a Hebrew translation. but I didn't find the way to do so.
How can I do this?

**Comment by Ryochan7** [comment]
There are a couple of different ways to do it. Probably the easier way would be to add the translation via Transifex. The strings can be translated there and it can output a file that you can import into the DS4Windows project.

https://www.transifex.com/ds4windows/public/

You can also copy the main Strings.resx file (located in DS4Windows\Translations), rename it for the appropriate locale (Strings.he.resx in this case) and then use Visual Studio to edit the resource file with the appropriate strings. And then you can post a pull request with the updated translation file.

**Comment by Emertels** [comment]
Thank you, Ryonchan!

I've already joined the translation project, I'm just waiting to be accepted.

I noticed that most translations stopped at 37.6%. Is there any reason for this percentage?

**Comment by avsha114** [comment]
> There are a couple of different ways to do it. Probably the easier way would be to add the translation via Transifex. The strings can be translated there and it can output a file that you can import into the DS4Windows project.
> 
> https://www.transifex.com/ds4windows/public/
> 
> You can also copy the main Strings.resx file (located in DS4Windows\Translations), rename it for the appropriate locale (Strings.he.resx in this case) and then use Visual Studio to edit the resource file with the appropriate strings. And then you can post a pull request with the updated translation file.

Thanks.
In Transifex I see that Hebrew has already been requested so if you could approve it it'll be great.
In the meantime I'll start translating the locale file.
Happy to contribute to such a great project :)

**Comment by Emertels** [comment]
Just do not understand why the translations are at 37.6%?! I've been in the Project for days, but I haven't been accepted yet.

**Comment by avsha114** [comment]
never mind. I just edited the Strings file.

**Comment by Emertels** [comment]
> never mind. I just edited the Strings file.

How did you edit, can you give me details? I'm a layman at it.

**Comment by Emertels** [comment]
Lamentável!
