### ISSUE TITLE
Exclusive mode win 10.

### ISSUE THREAD

**Issue by puckle** [Ryochan7/DS4Windows#17]
Hi, not really an issue, more of a request that may help a few people. 

Is it possible to have DS4Windows automatically disable the controllers in device manager on Windows shutdown and then enable them after windows has loaded?

I've found that disabling the controllers in device manager before I shut down, and then manually enabling them after windows has loaded gets over the exclusive mode issue.

If I try disabling and re-enabling them without the shut down in between, exclusive mode can't be achieved.

Many thanks for your work.
Puckle.

**Comment by pralima87** [comment]
exclusive mode works fine for me on win10.
Might be a problem on your end.

**Comment by Ryochan7** [comment]
That shouldn't be necessary with recent versions of DS4Windows. Version 1.4.53 and later should not need that kind of workaround in order for exclusive mode to work on Windows 10. One thing that you could also try is to check on the processes that you have enabled on Windows startup. If you have something like Steam or Origin set to launch on Windows startup then that might interfere with exclusive mode working.

**Comment by puckle** [comment]
Thanks for the responses. I ended up disabling everything at startup and re-enabled a few things at a time. (I'd already disabled Steam, Origin and Uplay after some previous efforts to get it working)
Turns out it was fanaLEDs ( a program that controls the LEDs on my G29 steering wheel) causing the issue.
All seems good now :)
Hopefully the information may prove useful to someone.
Thanks again.
