### ISSUE TITLE
Plugging the controller via cable bugs Retroarch

### ISSUE THREAD

**Issue by vpontin** [Ryochan7/DS4Windows#170]
Hi! I was using 1.4.105 and during gameplay i need to plug the controller to a USB cable to recharge. Since my phone was using the charger i plug the controller direct to PC. When i reopen retroarch after connecting the controller i cant control the interface and the games, even when ds4windows recognizing the controller and even applying the color of the default profile. In fact only the shitty default driver "Wireless Controller" is listed on controllers menu of retroarch, even with xinput selected as the joypad driver.

After updating to 106 and checking the logs i got this:

`X360 Controller # 1 failed. Using DInput only mode`

What i need to to?

**Comment by Ryochan7** [comment]
I use RetroArch often and I have not run into this kind of problem. Hopefully some of the recent changes to DS4Windows have fixed this problem for you. There were a couple of real problems regarding device hotplugging that got resolved with the last release (1.4.109).
