### ISSUE TITLE
latency over 10ms via bluetooth after 5 to 10 min gaming and ghost input on LR which goes up

### ISSUE THREAD

**Issue by yoyz** [Ryochan7/DS4Windows#1700]
DualShock controller geniune which has one month buy from a trusted big store which does not sell chinese fake controller.
PC on win10 with a 8 core 1680v2 processor overclock at 4GHz all core and RTX2080 running Wolfenstein 2 new collosus ( steam version ) in 1080p ultra with vsync 60Hz.
Game run at 60 fps constant in game no issue and processor not bottleneck by this game.

After few minutes of gaming could be 5 to 15 min, I get ghost input on the right analog stick which goes up, not much but when it begin, you see that it will do that for 5s, then suddenly it behave normal for 30s or more but this ghost input will appear again.
Looking at the logs of the DS4, I see that I get "latency messages over 10ms", and those message appear only while gaming if I look at the timestamp :
-  it does not happen after multiple minute on desktop ( with the game in background ) and I see that controller always update info on screen, and the LR does not do something specially weird, like going up.
- this problem only appear in game, but some game show this more than other
If I "alt tab" so the game is still running but in background, I look at the latency from DS4, latency is okay at the 3ms range.
If I put the polling at 500Hz I see that the dongle is able to sustain the pooling rate.
But in game, it seem that the latency increase and at some moment there is spike of latency. 
The spike is not really a problem to be honnest, if it's just few spike every 2 minutes, but the "ghost touch" is really annoying doing fps.

I have put the dongle as close as possible to me ( around 20 to 50cm ) and I still get those latency spike in DS4windows. 
So I don't think it's bluetooth noise related.
Putting my phone at 5m does not solve the issue either.

I have used the lastest version of DS4 from 25 december. 
The dongle is a "cheap" amazon one which has been used with a DS3 controller running scptoolkit.
I got similar result using the DS4 controller on scptoolkit, no ghost touch, but latency issue.
scptoolkit does not have this issue using a DS3 controller for an unknown reason using this dongle.

I have put the profile of windows from balanced to high perf.
Put ds4windows in "realtime scheduling" instead of "high".
No result.

I trust that the DS4 controller is okay, and this is not dead zone stuff here.
My own belief here, is when load increase I have this issue.

**Comment by yoyz** [comment]
Look like in some position when I am lying down in the sofa, I can see 250ms under windows : so not in game.
And I'm able to reproduce that 250ms every time I want.
I won''t use this position when I game, but for now, until I discover why some position can have so much latency effect, forget this bug.

**Comment by mika-n** [comment]
If you have BT dongle in a PC try using it at the end of USB extension cable. This will take the BT dongle further away from the radio storm caused by PC chassis and closer to your gamepad (dongle no longer hidden under a desk)

**Comment by yoyz** [comment]
Hi Mika ! Thanks for your word.
I have just done that this evening. Putting a 5m usb extension cable so I had the DS4 with the bluetooth together in the sofa.
And I have finally understood where the issue is.
My DS4 controller works fine without much noise in the DS4Windows interface. But after 5 to 10 minute of gaming, the RS goes up. So at that moment I switch back to the windows desktop, and I try to "mimic" exactly what I was doing in game so pulling exactly the same trigger and doing the same kind of movement on RS and LS. Not just trying to do circle or other things, exactly mimic, what I was doing in game for one minute. And at this moment, I see that there is some ghost move to "the up" on the RS.
So it's a controller defect here, not a software bug. 
But if you don't touch the controller, then there is no spike of those movement to the up. Or doing circle or similar don't show the issue at all, worst, it seem to show controller is completely healthy.
I have try to use clean the controller the most possible with my vaccum ( without opening it, to not void guarantee ), but, issue is still there, so I will exchange the controller, here the problem is just me and an insidious issue on this controller !
Anyway, i'm happy to have finally find the root cause !

**Comment by yoyz** [comment]
And putting this 5m cable so controller was on the bluetooth dongle show that the latency problem goes away, so this "TP Link" bluetooth works fine, but sometime in this building there is "electrical noise".
Will buy a better dongle and replace the controller.
You can close this issue ! Thanks a lot !

**Comment by mika-n** [comment]
Believe it or not but microwave ovens may cause issues with BT radio frequencies.

Have you tried to reset the gamepad? There is a hold in the back of the gamepad you can press with paper clip. After this you need to re-pair the gamepad. Well, usually this doesn't help but it won't hurt to try.

When you see those weird movements then do you see warning messages in DS4Windows log file (or Logs tab page)?

**Comment by yoyz** [comment]
I believe you !
Yes, I have try to reset the gamepad at some point, and I have switch between scptoolkit, the old DS4Windows and the Ryochan7 version. I had multiple different issue that I now think, it's this DS4 game controller which had issue.

Today, I have replaced this gamepad by a new one, and the new one had no LED backlight, but no other issue, so I replaced it again ( was brand new ), and last one allow me to play 5 hours without any issue at all in bluetooth.
Sooo. There is DS4 v2 brand new which are broken.
Thanks a lot Mika-n, you can close this case.
