### ISSUE TITLE
No longer needing to whitelist games with HID after recent update (IDK if good thing)

### ISSUE THREAD

**Issue by SurfingCats** [Ryochan7/DS4Windows#1704]
After the recent DS4 windows update I no longer need to whitelist apps in HID to get my DS4 to work on them. I don't know if this is a good thing or a bad thing.

**Comment by Ryochan7** [comment]
That makes it sound like a Windows update might have deleted the AffectedDevices list in the registry. That is known to happen with vanilla HidGuardian. You might want to double check that HidGuardian is hiding the input DS4 device.

**Comment by SurfingCats** [comment]
You're probably right cause I did update Windows.
