### ISSUE TITLE
Gamepad data write connection is lost. Disconnecting the gamepad. LastErrorCode=1784

### ISSUE THREAD

**Issue by MediaMaquina** [Ryochan7/DS4Windows#1706]
I understand this is the new normal in Windows 7.
However this line repeats every 4 seconds indefinitely. When the log is millions of lines long, the program and pc get really slow.
Is there a way to pause logging? **Specially since the gamepad seem to work perfectly fine despite of that message.**

![spam](https://user-images.githubusercontent.com/8179611/103241811-a3da3800-4954-11eb-9e22-c413684879fb.png)

**Comment by Ryusennin** [comment]
No need to open a new ticket.

Duplicate of #1677

**Comment by Ryochan7** [comment]
Fixed in latest release
