### ISSUE TITLE
Hide DS4 Controller was removed

### ISSUE THREAD

**Issue by rhett565** [Ryochan7/DS4Windows#1707]
When playing rocket league you need to have Hide DS4 controller turned on. When hitting start to access menu it adds a split screen everytime which is extremely annoying. I could downgrade versions again but i dont believe the older versions support PS5 controller that i just switched to. not unplayable I just wish there was a way around this.

**Comment by Dave247** [comment]
You'll likely want to update to the Steam client beta version that just came out today which seems to speically mention this issue as being fixed.

> Fixed a crash when DS4Windows hides a PS5 controller that Steam has opened
https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/2919986982635497327

**Comment by Yohoki** [comment]
You might also want to upgrade DS4Win. The option to hide controllers was added back in as a legacy option.

**Comment by Lunahria** [comment]
I'm using the Steam Beta Client and Rocket League natively supports DualSense, with Steam Input disabled.
Unless you really hate the PlayStation symbols or you dislike the absence of rumble, I suggest that you enable Steam Input per-game for Rocket League and then go to Controller Configuration for the game and select "Gamepad" from the Templates menu, apply that, launch your game and now Steam would have hid your DualSense and will only let Rocket League use XInput.
