### ISSUE TITLE
PS5 Haptic Feedback only works when DS4Windows is not running?

### ISSUE THREAD

**Issue by QuestionAsker165** [Ryochan7/DS4Windows#1710]
When I turn on the Speaker Fill in Windows 10 the haptic feedback works perfectly with everything. 
But whenever I turn on the DS4Windows application it just immediately stops working. Is there any option to still use haptic feedback while using the program?

**Comment by Ryochan7** [comment]
DS4Windows uses the rumble emulation provided by the DualSense hardware rather than using fake audio haptic feedback. As a consequence, fake audio haptic feedback is disabled by the hardware when rumble emulation is active.

**Comment by Ryochan7** [comment]
I think I mentioned it in the DS5 support thread but I will mention it here. From what I have experienced with Streets of Rage 4 when using Steam Input, there is no granularity with the fake audio rumble support that Steam Input provides. Changing the vibration strength in game does nothing. It effectively becomes either Rumble on or Rumble off. This type of issue does not happen when using rumble emulation in DS4Windows.

**Comment by ArStah** [comment]
What about adding an option to disable rumble emulation? That would be great

**Comment by Ryochan7** [comment]
Now there is an option to disable rumble emulation. Settings > Device Options > DualSense > Enable Rumble Emulation

It might be changed later to allow the option to be set per device as opposed to per device type.
