### ISSUE TITLE
"Object synchronization method was called from an unsynchronized block of code."

### ISSUE THREAD

**Issue by JonTheVGNerd** [Ryochan7/DS4Windows#1711]
Apparently, the new DS4Windows update no long recognizes my PS4 controller and the error pops up. Tried removing device and reconnect it, no dice. Cannot Uninstall Driver either because it is greyed out with no way for me to resolve the issue. Is there any way to roll back the update? It seems updating a newer version did more harm than good. I'm on update 2.2.0.

**Comment by Ryochan7** [comment]
Hotfix is already out. Make sure to update to version 2.2.1
