### ISSUE TITLE
Launch .bat from special actions

### ISSUE THREAD

**Issue by TheMasterDingo** [Ryochan7/DS4Windows#1714]
I would like to be able to launch a bat script with the special actions menu, currently it accepts only .exe.

(great job with the latest update)

**Comment by Ryochan7** [comment]
That should be easy enough to add.

**Comment by TheMasterDingo** [comment]
Thank you!

**Comment by mika-n** [comment]
the feature is implemented and will be part of the next official release. See the link for more info:
https://github.com/Ryochan7/DS4Windows/pull/1728
