### ISSUE TITLE
Cannot Unhide Controller

### ISSUE THREAD

**Issue by hifihedgehog** [Ryochan7/DS4Windows#1716]
Long story short, I removed DS4Windows because I need to use my DS4 as just a regular DInput controller. Now, I was sure to uncheck the "Hide DS4 controller" option before uninstalling. But now, however, the input is not working when using it as a plain jane DirectInput/DInput controller. Sure, the DS4 shows up as a "Wireless controller" in the gamepad controller settings in Windows. But... no inputs are detected at all when I move my DS4's joysticks or press its buttons. What in the world is going on here and how can I get my DS4's DirectInput to work again?

**Comment by Ryusennin** [comment]
Maybe you installed HidGuardian and forgot to remove the AffectedDevices registry key?
