### ISSUE TITLE
[TODO] Make HID Report Listener clone

### ISSUE THREAD

**Issue by Ryochan7** [Ryochan7/DS4Windows#1717]
At some point, it might be a good idea to make a replacement for the HID Report Listener application. Although the current application was useful for inspecting the input reports from the DualSense and it helped get support in DS4Windows more quickly, I have encountered crashes while using the app in the past. Also, Wobbles has been MIA for several months and HID Report Listener has not been updated in over a year.

There is also the fundamental issue of relying on proprietary software to get work done. Having an open source version would be better.

**Comment by flok** [comment]
Would Like to look into this. Do you already have a plan of some sort? Do you wanna replicate the HID Report Listener first and then add needed extra features ?

**Comment by Ryochan7** [comment]
The plan is to make a functional clone with no planned new features. The only possible feature I could see implementing is the option to skip reading feature reports from HID devices. That would be useful for some devices to not enforce a mode switch and debug the input report from the "PC mode" (DirectInput interface) of a device.

As for the software stack, I will use the same stack I have been using on many apps lately. Written in C# using WPF for the GUI. The current HidLibrary used in DS4Windows will be the main library used to interface with HID devices. One major departure is that I would like to have the app target .NET 5.0 rather than the older .NET Framework. It would be a good idea to attempt to experiment with the future of .NET as .NET Framework has been deprecated.

I am going to give myself a week to get a version working. Hopefully it will only take a weekend to make a functional prototype. If I can't get something made in that time frame then the project will likely be scrapped.

**Comment by Ryochan7** [comment]
Current progress. Got a display working. It seems pretty snappy so far. Obviously proper names need to be grabbed for VID and PID info.

![hidreport_progress_2_20210104](https://user-images.githubusercontent.com/581968/103566683-0917b700-4e88-11eb-8f22-29f2a78e2a93.png)

**Comment by flok** [comment]
Nice do you plan to make the repo public in the near future? Will probably abandon my implementation and would love to work on yours

**Comment by Ryochan7** [comment]
Maybe I will try to get a repo set up later tonight. The source code is still a bit rough.

**Comment by mika-n** [comment]
This tool is for sure handy when trying to work out issues with those problematic DS4 copy-cats. 
Is it possible to change the input/output report byte viewer to show optionally hex or decimal number format? Sometimes it may be more useful to see the hex value in case the value is a half byte bit field or when looking at some input report specs written using hex values.

**Comment by Ryochan7** [comment]
That is an option on a per byte basis in the Input Report section in HID Report Listener. The popup that appears when you click the Tools icon has a combobox that sets the output display type used. Decimal is the default but Hexadecimal and Binary display options are available. That feature has already been duplicated.

In its current state, the app should serve as a mostly functional clone. There is still some testing to be done especially to make sure the Feature Report section displays properly; been having random issues with garbage data popping up and I am not sure that issue is entirely fixed. Also, I have not added a Feature Report section to the exported files. I am not sure if I will use it so that portion has been skipped for now. I am not sure the other version encodes the feature report data properly to base64 anyway; decoding the string to a byte array in Python has led to incorrect results.

GitHub repo for the source code

https://github.com/Ryochan7/HidReportInspector

![hidreport_progress_20210105](https://user-images.githubusercontent.com/581968/103692037-cffd4680-4f5c-11eb-8e7c-ab3273d77bd1.png)

**Comment by Ryochan7** [comment]
Never mind about the Feature Report encoding issue. It was being encoded properly in HID Report Listener. Mixed up device reports (DualSense and DS4) during comparison.

**Comment by Ryochan7** [comment]
Feature Report data is now exported to the JSON file

**Comment by Ryochan7** [comment]
Got a built version released. I am not sure if I will actively maintain this app though.

https://github.com/Ryochan7/HidReportInspector/releases/tag/v0.0.1
