### ISSUE TITLE
Dualsense kinda working but not in a good way

### ISSUE THREAD

**Issue by DoubleKimp** [Ryochan7/DS4Windows#1718]
**Describe the bug**
Dualsense inputs are oly registerd once when pressed.

**Expected behavior**
Fast switching between the controller and/or keyboard and mous inputs.

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS5
 - OS: Windows 10
 - DS4Windows Version

**Additional context**
It makes it that you can't steer(or walk) and in my case throttle is only apllying to about 75%

**Comment by Ryochan7** [comment]
What?

**Comment by Ryusennin** [comment]
Never file a bug report when you're drunk on New Eve.
