### ISSUE TITLE
rumble non stop

### ISSUE THREAD

**Issue by pyromancer5** [Ryochan7/DS4Windows#1720]
after updating to Version 2.2.1 while playing dolphin emulator with rumble on ds5 ds4 and raiju ultimate all of them start rumble no stop rerolled to 1.1.23 and its working perfact

**Comment by mika-n** [comment]
did you update the ViGem driver also? Those latest goodies need a new ViGem 1.17.333 driver version also. DS4Windows app doesn't automagically update the ViGem driver.
https://github.com/ViGEm/ViGEmBus/releases

**Comment by pyromancer5** [comment]
My man ty so much it worked like a charmed ^^ you the best sry if i bothered you
