### ISSUE TITLE
Lifting the shift modifier of a held button presses the unmodified button

### ISSUE THREAD

**Issue by therealcharmics** [Ryochan7/DS4Windows#1721]
**Describe the bug**
The program will press a button which is no longer being modified by a shift modifier. More of an undesirable behavior / edge case than a real bug.

**To Reproduce**
1. Assign a button (ex R2) to an input (ex Right Trigger)
2. Give the button a shift modifier (ex L2) and assign it to a different input (ex Left Mouse)
3. Save profile
4. In-game, hold the shift modifier (ex L2)
5. Hold the modified button (ex R2 -> Left Mouse)
6. Release the modifier (ex L2)
Undesired consequence: The program depresses the unmodified button (ex R2 -> Right Trigger)

**Expected behavior**
The program should ignore a held button if the modification state is changed until it is pressed again, or, there should be an option.

**Additional Notes**
This same applies to the reverse: a held button will activate it's modified input if the modifier is pressed while it is held. Ideally' there would be individual options to control this behavior, but in general, it is undesirable. I noticed while using the bow in Horizon Zero Dawn with a custom mouse-gyro profile: Aloy would perform a heavy attack when sheathing a drawn bow.

**Desktop (please complete the following information):**
 - Sony DS4
 - Windows 10 
 - DS4Windows Versions both 2.1.22 and 2.2.1

**Additional context**
[log.txt](https://github.com/Ryochan7/DS4Windows/files/5759299/log.txt)
[log2.txt](https://github.com/Ryochan7/DS4Windows/files/5759324/log2.txt)

**Comment by Ryochan7** [comment]
That is the intended behavior. Mode Shifts work the same in Steam Input. Don't really understand why you would expect it to work differently. Not a bug

**Comment by therealcharmics** [comment]
First of all, thank you very much for the response and consideration. If this is intended, I can respect that, but it does surprise me to hear. Please hear me out.

This means that held inputs cannot be released at the same time as the shift modifier changes, without also sending an undesired input. They must be released before. This can cause an issue in any game that requires two or more buttons to be held in sequence to perform an action. 

One of the more common use-cases for shift modifiers, I imagine, is for modification while aiming down sights or using a bow, performed on L2. Consider games like Horizon Zero Dawn, Breath of the Wild, certain Skyrim configurations, Plague Tale, and more. In these games, the bow is then drawn using R2, and a drawn bow is cancelled by releasing the bow button before or at the same time as releasing R2. R2 is ignored until it is released again.

This behavior - releasing the first button in a sequence of held buttons to cancel the entire action - is common in the industry. I would be useful if we could set that first button as a shit modifier without compromising that behavior. In the input mapping screen, there could be an option under "normal" and "shift modifier" settings, "ignore held buttons on state change" or something. 

Again, thank you for your consideration.

**Comment by therealcharmics** [comment]
I've messed around with this a lot more in a few games [3 hours +], and I can definitely see the reasoning for why it's currently like it is. However, I still feel that an option would be nice. 

Thank you again for your considering and work!
