### ISSUE TITLE
DS4Windows crashing upon attempting to edit controller profile

### ISSUE THREAD

**Issue by prism2001** [Ryochan7/DS4Windows#1723]
**Describe the bug**
The entire program crashes upon pressing the "Edit" button to edit the controller profile.

**To Reproduce**
1. Open DS4Windows, and grant UAC access for exclusive mode
2. Click on 'Edit' in the Controllers tab
3. Program will freeze for a brief second, then close without any error

**Expected behavior**
The profile editor to open up normally without crashing after pressing the "Edit" button.

**Desktop (please complete the following information):**
 - **Controller Make and Model:** Sony DS4 v.2 (CUH-ZCT2U)
 - **OS:** Windows 10 Pro Build 2004
 - **DS4Windows Version:** 2.2.1

**Additional context**
I saw a previous issue page about this problem, where updating/reinstalling the .NET Framework was suggested. I've tried that multiple times to no avail. I've tried completely uninstalling and reinstalling DS4Windows itself multiple times, as well as reinstalling controller drivers, no dice. I've had this problem for months now, and I've run out of options on how to troubleshoot this.

Attached is the crash dump file that was created upon DS4Windows crashing.
[DS4Windows.exe.55904.zip](https://github.com/Ryochan7/DS4Windows/files/5759856/DS4Windows.exe.55904.zip)

**Comment by mika-n** [comment]
What do you see in the logfile? %APPDATA%\DS4Windows\Log folder.
What do you see in Windows EventViewer?

Have you tried to remove all settings and profile files and to start from scratch? To do this close DS4Windows app and remove all files and subfolders from %APPDATA%\DS4Windows \ folder (or take a backup copy).

**Comment by Ryochan7** [comment]
Going to need the DS4Windows log files to possibly diagnose the problem

**Comment by prism2001** [comment]
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/5760793/ds4windows_log.txt)

Here's the log file.

Also,
>Have you tried to remove all settings and profile files and to start from scratch? To do this close DS4Windows app and remove all files and subfolders from %APPDATA%\DS4Windows \ folder (or take a backup copy).

Yes, I have tried this as well. Did not help fix the issue either.

**Comment by Ryochan7** [comment]
Thank you for the log file. I believe that I have found the root issue behind the crash. This looks to be another case of behavior changing in .NET Framework 4.8 causing issues. In this case, the way it handles image color profiles has changed.

This same type of issue was brought up in issue #1650 but I figured there was nothing to be done about it and I could not reproduce it on my end. Changing the Windows color device profile in Color Management allowed me to have DS4Windows crash. I have a workaround in place that works with both **sRGB virtual device model profile** (assuming you are using that) and **System default (sRGB IEC61966-2.1)**.

https://stackoverflow.com/questions/63510630/wpf-bitmapimage-exception-the-image-data-generated-an-overflow-during-processin

**Comment by prism2001** [comment]
That seems to fix it. Interesting. I was using a color profile generated by a program called QuickGamma, since the display settings on my monitor weren't enough. So am I to understand that those two color profiles are the only ones that can be used right now to avoid a crash? The main problem I have with the default Windows color profiles is that they're too bright for my monitor, but I suppose I could simply just set the profile to those ones that work, change whatever I need to in the profile, and then change it back once I'm done.
