### ISSUE TITLE
Controller readings don't show properly when editing the active profile

### ISSUE THREAD

**Issue by Telvran** [Ryochan7/DS4Windows#1724]
The "gray dot" and numerical outputs for altered axis' are not reflected in the controller readings panel when editing the active profile. 

To reproduce, make a profile active and edit it. Change some parameters of LS/RS/Triggers in the axis config panel. Input/output values in controller readings show identical regardless of changes. Change to a different active profile, and edit the first profile again. Input/output values are no longer tied together. The gray dot reappears.

DS4Windows 2.2.1
Win 10 1909

**Comment by Ryochan7** [comment]
Maybe the Profiles list should go away
