### ISSUE TITLE
Dualsense light turning red when starting up PC. conflicting with Steam?

### ISSUE THREAD

**Issue by DavidCreegan** [Ryochan7/DS4Windows#1725]
So, here's what happens when I boot up my PC... the light turns lite blue as what I have set in DS4Windows, but then Steam overrides it and makes it the normal blue with the player one light on...DS4Windows tries to take it back and make it lite blue again...then the light turns red indicating I'm "player two" now. Something isn't right here. And just FYI, I have NO other controller devices on my PC, I have enabled hidden devices in device manager , uninstalled all of them, and rebooted. No change. This happens every time. I'm using this controller over USB btw.

**Comment by Lunahria** [comment]
To avoid this, Steam must start after DS4Windows has started up fully.
Since I avoid running Steam on boot, you will have to find a way to delay Steam a bit so that DS4Windows has time to start.
Maybe Task Scheduler can help.

**Comment by Ryusennin** [comment]
Or you could disable Steam Input and let DS4Windows do its magic.

**Comment by Lunahria** [comment]
> 
> 
> Or you could disable Steam Input and let DS4Windows do its magic.

That's not quite the way Steam handles DualSense.
Unlike DualShock 4, Steam for some reason takes control of DualSense even without turning on PlayStation Configuration Support in Big Picture.

**Comment by Ryusennin** [comment]
I may be mistaken, but I think all controllers supported by Steam go through Steam Input, which is essentially the Valve version of Input Mapper. I don't imagine the DS5 being any different.

**Comment by Lunahria** [comment]
> 
> 
> I may be mistaken, but I think all controllers supported by Steam go through Steam Input, which is essentially the Valve version of Input Mapper. I don't imagine the DS5 being any different.

Well plugging in DualShock 4, and Steam controls nothing, the lightbar stays unlit and DS4Windows can take over if it wants.
Plugging in DualSense and the lightbar instantly lights up despite what you have set up in Big Picture and DS4Windows makes Steam go all wild, assigning it as 2nd controller and whatnot, and they keep applying their own lightbar color and it gets really funny.

HidGuardian solves all the issues, maybe OP can set that up for themselves too if they enjoy using DS4Windows.
