### ISSUE TITLE
Error opening the new version of DS4, DualSense does not appear, and Crash ...

### ISSUE THREAD

**Issue by GuilhermeTutoriais** [Ryochan7/DS4Windows#1729]
Here is the last log file ...

[logs.txt](https://github.com/Ryochan7/DS4Windows/files/5762337/logs.txt)

**Comment by mika-n** [comment]
What do you have in HidGuardian AffectedDevices sysreg entry? Is it empty, or just one entry or multiple entries there?

The easiest way to check this is to use HidNinja tool from DS4Windows\Tools\HidNinja folder. It shows you the list of devices set to be handled by HidGuardian device driver and DS4Windows app.

**Comment by Ryochan7** [comment]
Looks like you messed up the registry when updating or adding the AffectedDevices list. You set it to store the wrong data type. The value must be stored as type **REG_MULTI_SZ** (Multi-String Value). Any other type will not work properly. I am not sure HidNinja would be able to work if the type has been set incorrectly. You might have to delete that registry value and start from scratch.

Path of registry value:
```
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\HidGuardian\Parameters\AffectedDevices
```

Either way, this is likely a user error. Not a bug. Please use HidNinja in the future when configuring HidGuardian. It will make the process a bit easier.
