### ISSUE TITLE
Fake DualSense as DS4

### ISSUE THREAD

**Issue by Makusensu** [Ryochan7/DS4Windows#1734]
Hi,

Games that are supporting DS4 are not detecting DSense.

I wonder if it would be possible to have an option to fake the DS4 so it would be able to play those games with actual PS button icons instead of going to Xinput ?

Cheers

**Comment by mika-n** [comment]
See the Controller profile option. You can choose the type of output virtual controller (xbox360 or ds4)
https://github.com/Ryochan7/DS4Windows/wiki/Settings

**Comment by Makusensu** [comment]
I did set to DS4 in my "DS4" profile in "Other > Emulated Controller", but it seems not doing it, so I was wondering if this option actually just expose actual device type  and not fake it.

For example, Rainbow Six Siege does not recognize a DSense set to a DS4 profile.

**Comment by mika-n** [comment]
Have you enabled "Hide DS4 Controller" option or do you use HidGuardian to hide the original physical controller and leaving just the virtual output controller visible for games?
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

Post the logfile here as TXT attachment file (rename the latest %APPDATA%\ds4windows\logs as .TXT file and drag-n-drop it here). It should tell if the output controller really was ds4 and not xbox360.

**Comment by Makusensu** [comment]
Ho ok I found the issue.

So, I was never using "Hide DS4 Controller", but my DS4 profile had the option "Use Dinput only" enabled. Disabling it makes the game detect it.

Thank you

**Comment by mika-n** [comment]
https://github.com/Ryochan7/DS4Windows/wiki/Settings#use-dinput-only
