### ISSUE TITLE
Detroit become human gyro passtrough not working and UI bug

### ISSUE THREAD

**Issue by Keltere** [Ryochan7/DS4Windows#1735]
Hi, as per title the gyro controls seem to not be recognized by the game, don't know if this is related or not to vigembus but before posting there ill ask here.

I did try to reduce the dead zone to 0 but it didn't help resolving the issue. The touchpad passthrough it's working fine tho.
Strange fact is if i select mouse or just controls and then change to passthrough the window will remain the same, controls option will remain. Don't know if this a bug tho.

![Capture](https://user-images.githubusercontent.com/8084245/103665736-11e5b700-4f74-11eb-9c37-6e39304cec56.PNG)
![Capture2](https://user-images.githubusercontent.com/8084245/103665778-1e6a0f80-4f74-11eb-8908-6d8fb1a78ff1.PNG)

**Comment by Masamune3210** [comment]
Did you make sure you have the latest version of vigem installed?

**Comment by Keltere** [comment]
> Did you make sure you have the latest version of vigem installed?

The latest stable release 1.17.333, yes. Otherwise the touchscreen passthrough wouldn't work

**Comment by Ryochan7** [comment]
Testing gyro passthru on RPCS3 with Gamepad Test since I can now run it. Accel and gyro readings are about the same when using the virtual DS4 with DS4Windows or using the physical DS4 when DS4Windows is not running and reconnecting the controller for extra assurance. Is the real DS4 hidden from the game?

**Comment by Keltere** [comment]
I've found out that gyro doesn't work over BT, just trough wire. Is this expected?

**Comment by Ryochan7** [comment]
If that is true then the answer to my question must be No.

https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

**Comment by Keltere** [comment]
> If that is true then the answer to my question must be No.
> 
> https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

Hiding the controller it won't make it work even with the cable, if i stop ds4windows the gyro will work with no problem.

Wireless ds4windows -> no gyro
Wireless no ds4windows-> controller not recognized by the game
Wireless ds4windows exclusive -> no gyro
Wired ds4windows-> gyro working
wired no ds4windows -> gyro working
Wired ds4windows exclusive -> gyro not working

I did ensure there was no exclusive error before testing the exclusive mode
