### ISSUE TITLE
360 controller has the incorrect name

### ISSUE THREAD

**Issue by NoelShourai** [Ryochan7/DS4Windows#1736]
**Describe the bug**
The 360 controller is being read as a completely different controller entirely by Windows.

**To Reproduce**
1. Plug in a non-DS4Windows controller--in this case, a QanBa Q4RAF arcade stick. The controller is picked up as a "QanBa Joystick Plus". Let Windows automatically set up the controller, etc.
2. Unplug the controller. Plug in a DS4, install DS4Windows, etc..
3. Start DS4Windows as normal.
4. Access joy.cpl for the expected result.

**Expected behavior**
Instead of being picked up as an "Xbox 360 Controller" or similar, the DS4 is picked up as a "Controller (QanBa Joystick Plus)".

**Screenshots**
![image](https://user-images.githubusercontent.com/19917103/103779650-0f31a300-5002-11eb-9de2-64eccf8e111c.png)
![image](https://user-images.githubusercontent.com/19917103/103779584-f6c18880-5001-11eb-8989-eca3fbc7bd3c.png)

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: Windows 10 Pro Build 19042
 - DS4Windows Version 2.2.1
 
**Additional context**
Fresh install of Windows 10 on a brand new PC. Steam seems to recognize the controller as an "Xbox 360 Controller".

**Comment by mika-n** [comment]
DS4Windows app itself has nothing to do with the gamepad driver level and how those physical gamepads registers itself to WinOS (name and so on). That specific joystick must have installed its driver in a "non-standardized" way (it has simply hijacked the existing xbox360 hardware ID and the driver ID). Veeeery shady thing to do. Sounds like the gamepad vendor didn't want to do things properly. You should send a message to the joystick vendor and ask them to fix their driver.

**Comment by Ryochan7** [comment]
A Windows problem. Not DS4Windows related
