### ISSUE TITLE
Warn users if their ViGEmBus driver isn't up to date

### ISSUE THREAD

**Issue by Filoppi** [Ryochan7/DS4Windows#1737]
Sorry, not exactly a bug, but I had some troubles with DS4Windows recently and I found out they were because my ViGEmBus driver wasn't up to date.
See here:
https://github.com/ViGEm/ViGEmBus/issues/68

DS4Windows should warn users with a big annoying message if their driver isn't up to date, to avoid these kind of problems.
I'd add this myself but I really wouldn't know how to do it in a way that @Ryochan7 might like.

**Comment by bslenul** [comment]
Just a quick thank you, got some issues with rumble lately in RetroArch, I wanted to post an issue about it but I didn't know if it was a DS4Windows issue or a RetroArch one, looks like it was something else 😅

**Comment by Ryochan7** [comment]
That used to be the responsibiility of the ViGEm installer but it looks like the auto updater portion does not exist in the 1.17.333.0 setup. I am declaring this out of scope and pure bloat. New users already have the option of installing the latest ViGEmBus driver and that is good enough for me.

I'm giving up my war against Bloat...
https://www.youtube.com/watch?v=-XSIjWTGfx8
