### ISSUE TITLE
Hello, DualSense rumble and color changing still not working in win7x64 via BT, I tried Version 2.2.0 and 2.2.1 ..:(

### ISSUE THREAD

**Issue by Whatsup12345** [Ryochan7/DS4Windows#1738]
01/07/2021 23:33:12: DS4Windows version 2.2.0
01/07/2021 23:33:12: DS4Windows Assembly Architecture: x64
01/07/2021 23:33:12: OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
01/07/2021 23:33:12: OS Product Name: Windows 7 Ultimate
01/07/2021 23:33:12: OS Release ID: 
01/07/2021 23:33:12: System Architecture: x64
01/07/2021 23:33:12: Running as User
01/07/2021 23:33:12: HidGuardian in use. Launching HidGuardHelper.
01/07/2021 23:33:15: Starting...
01/07/2021 23:33:15: Connection to ViGEmBus 1.16.112.0 established
01/07/2021 23:33:15: Searching for controllers...
01/07/2021 23:33:15: Using Exclusive Mode
01/07/2021 23:38:17: Found Controller: 4C:B9:9B:46:93:B1 (BT) (DualSense)
01/07/2021 23:38:17: Plugging in virtual X360 Controller
01/07/2021 23:38:17: Associate X360 Controller for input DS4 #1
01/07/2021 23:38:17: Controller 1 is using Profile "Default". Battery level is 100%

Sorry I'm still bothering you with win7, just if it's an easy FIX, it would be fantastic if it could be solved. 10Q  :*

**Comment by Ryochan7** [comment]
As mentioned in the following post, it is literally impossible to get Win7 to send reports to the DualSense via BT thanks to the horrid Microsoft BT stack. Steam Input suffers from the same problem.

https://github.com/Ryochan7/DS4Windows/issues/1689#issuecomment-753008415

**Comment by Whatsup12345** [comment]
"DS4 BT rumble and lightbar support in Windows 7 was fixed in the latest DS4Windows release though. The Control endpoint is used again if DS4Windows detects that it is running on Windows 7."

Ok, I thought it could be solved, and that it was solved in version 2.2.0

Via cable everything works fine since version 2.1.18, also in Steam without ds4windows everything
