### ISSUE TITLE
Add option to make DS4Windows ignore any Lightbar changes

### ISSUE THREAD

**Issue by justalemon** [Ryochan7/DS4Windows#1739]
After seeing that the DS4 via DS4Windows still sends Lightbar colors to the controller when set to Xbox 360 and "Hide DS4 Controller" disabled, I would really like to see an extra option to make DS4 windows avoid any Lightbar color changes. In other words:

* Lightbar mode get an extra option called Ignore, where DS4Windows will stop sending any Lightbar data to the DS4
* This mode will be the same as having "Enable Output data to DS4" disabled, but without loosing the rumble function
* There are some cases where this would be useful, like a game that only supports XInput controllers getting Lightbar support via mods without having to reimplement the entire controls system (just the Lighbar)

**Comment by Ryochan7** [comment]
There are at least 2 different ways to already do this. Passthru or just use solid Black which will disable the Lightbar via the hardware. Also, AFAIK, that last use case does not exist. Passthru would work for that use case anyway.
