### ISSUE TITLE
Pairing combination not working.

### ISSUE THREAD

**Issue by Kylar55** [Ryochan7/DS4Windows#174]
I downloaded the latest version and it works fine via usb, although it connects as an audio device, but when I want to pair it with bluetooth I cant get it to work. I hold the ps and share buttons but nothing happens. I really need bluetooth to work. How can I fix it?

**Comment by Ryochan7** [comment]
The DualShock version 2 is exposed as two devices when connected via USB (HID-compliant game controller and USB Audio Device). Connecting the DS4 via Bluetooth should be about the same as connecting other Bluetooth devices to your system. Holding PS and Share is only needed until the LED bar start flashing. The rest of the pairing process has to be handled manually in Windows.
