### ISSUE TITLE
controller not detected by Ds4

### ISSUE THREAD

**Issue by decaffeinatedcoffee** [Ryochan7/DS4Windows#1740]
My generic Double shock 4 controller is not recognized by Ds4.

HID \ VID_7545 & PID_1122 /

The controller also has the RGB LED equal to the original dual shock.

**Comment by mika-n** [comment]
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

and read the pinned "Read this before posting a new issue ticket" post.

**Comment by decaffeinatedcoffee** [comment]
> [https://github.com/Ryochan7/DS4Windows/wiki/Troureenshot#detailed-debug-log-file-from-gamepad-connection-problems](https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems)
> 
> e leia a postagem fixada "Leia isto antes de postar um novo tíquete de problema".

thanks for sending this, i had already read it, but for some reason i didn't read the third party controllers part, i'll try to see the log.

**Comment by decaffeinatedcoffee** [comment]
> [https://github.com/Ryochan7/DS4Windows/wiki/Troureenshot#detailed-debug-log-file-from-gamepad-connection-problems](https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems)
> 
> e leia a postagem fixada "Leia isto antes de postar um novo tíquete de problema".


what the log file says:

2021-01-08 13:04:57.1833|INFO|DS4Windows version 2.2.1
2021-01-08 13:04:57.1833|INFO|DS4Windows exe file: DS4Windows.exe
2021-01-08 13:04:57.1833|INFO|DS4Windows Assembly Architecture: x64
2021-01-08 13:04:57.1833|INFO|OS Version: Microsoft Windows NT 10.0.19042.0
2021-01-08 13:04:57.1833|INFO|OS Product Name: Windows 10 Pro
2021-01-08 13:04:57.1833|INFO|OS Release ID: 2009
2021-01-08 13:04:57.1833|INFO|System Architecture: x64
2021-01-08 13:04:57.1833|INFO|Logger created
2021-01-08 13:04:57.2145|INFO|LinkedProfiles.xml can't be found.
2021-01-08 13:04:58.2018|INFO|Running as User
2021-01-08 13:04:59.2368|INFO|Starting...
2021-01-08 13:04:59.2368|INFO|Connection to ViGEmBus 1.17.333.0 established
2021-01-08 13:04:59.2368|INFO|Searching for controllers...
2021-01-08 13:04:59.2368|INFO|Using Shared Mode


should i lose hope of being able to use my controller on ds4?
thanks

**Comment by decaffeinatedcoffee** [comment]
> [https://github.com/Ryochan7/DS4Windows/wiki/Troureenshot#detailed-debug-log-file-from-gamepad-connection-problems](https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems)
> 
> e leia a postagem fixada "Leia isto antes de postar um novo tíquete de problema".


I accessed the log and it says that there are 0 possible devices. What should I do now?

**Comment by mika-n** [comment]
How about posting the logfile just like you were asked to do in the first place?
Rename the latest logfile as .TXT file (file extension) and then drag-n-drop it here as an attachment file.

**Comment by decaffeinatedcoffee** [comment]
> Que tal postar o arquivo de log exatamente como você foi solicitado a fazer?
> Renomeie o arquivo de log mais recente como arquivo .TXT (extensão de arquivo) e arraste e solte-o aqui como um arquivo anexo.

I was going to do this but I'm new here and I don't know how to attach files, but I'll try, thanks

**Comment by mika-n** [comment]
Rename the xxx.log file as xxxx.txt file and then drag-n-drop it from FileExplorer to the comment field here. The file is then added as an attachment to this discussion.

**Comment by decaffeinatedcoffee** [comment]
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/5788917/ds4windows_log.txt)

well, I think that's it, right?

**Comment by mika-n** [comment]
Hmm... The gamepad doesn't seem to have the usual (at least used by DS4 and XBox gamepads) HID usage type. Usually gamepads have Usage=0x5 attribute, but your gamepad seems to have Usage=0x4 attribute.

The debug version has DS4WindowsDebug.exe.config file and there is Debug_CustomHIDUsageFlag option. By default it uses -1 value, but try setting it to value 4 and then try again running DS4WindowsDebug.exe app. Modify DS4WindowsDebug.exe.config file in Notepad and set Debug_CustomHIDUsageFlag option like this:
`<add key="Debug_CustomHIDUsageFlag"    value="4" /> `

Post the new logfile after testing this.

**Comment by decaffeinatedcoffee** [comment]
> Hmm ... O gamepad não parece ter o tipo de uso HID usual (pelo menos usado por gamepads DS4 e XBox). Normalmente os gamepads têm o atributo Usage = 0x5, mas seu gamepad parece ter o atributo Usage = 0x4.
> 
> A versão de depuração possui o arquivo DS4WindowsDebug.exe.config e a opção Debug_CustomHIDUsageFlag. Por padrão, ele usa o valor -1, mas tente configurá-lo para o valor 4 e tente novamente executar o aplicativo DS4WindowsDebug.exe. Modifique o arquivo DS4WindowsDebug.exe.config no Bloco de Notas e defina a opção Debug_CustomHIDUsageFlag como esta:
> `<add key="Debug_CustomHIDUsageFlag" value="4" /> `
> 
> Poste o novo arquivo de log após testá-lo.


well, making this change, ds4 recognizes the controller, the log files are here:
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/5789508/ds4windows_log.txt)

**Comment by mika-n** [comment]
Looks like the gamepad is not fully 100% DS4 compatible in PC. DS4Windows app supports only DS4/DS5 compatible and few other controllers (WiiMote etc).

**Comment by decaffeinatedcoffee** [comment]
and that means i won't be able to use my controller on ds4 windows right?

**Comment by mika-n** [comment]
Jep. DS4Windows was never intended to use xinput gamepads as a source because the idea was doing dinput->xinput output conversion (ie. using dinput gamepads as a source and then making those to appear to games as xinput devices because few years ago very few games supported dinput devices out of the box, but all for sure supported xinput pads).

Nowadays DS4Windows app does a lot more than just dinput->xinput conversion (macros, button re-map rules, output curve changes on the fly, etc etc) and supports even dinput output mode via Nefariou's ViGem device driver.  So, in theory accepting xinput pads as a source could be useful, but the old code base shows its nastiness here. It would not be just "few lines of code" to use xinput pads as a source.

Some DS4 compatible gamepads indeed register itself as xinput devices in PC instead of dinput DS4 device. With some compatible pads this problem could be solved by some settings in drivers to force the pad act like dinput in PC. In some cases removing the vendor specific device driver was required to force the pad to act like dinput. And some pads even has a switch to choose between xinput vs dinput mode.

But, sorry you are on your own here because not many people use that pad (the first time I saw that VID/PID code shown in the logfile). I'm sure there might be some way to force it to register itself as compatible DS4 dinput device in PC, but how? Who knows and next to impossible to debug without having such a hardware...

Even SDL device driver in Linux lists this pad and VID/PID as a bit problematic.
```
// Removing the Giotek because there were a bunch of help tickets from users w/ issues including from non-PS4 controller users. This VID/PID is probably used in different FW's
	// { MAKE_CONTROLLER_ID( 0x7545, 0x1122 ), k_eControllerType_PS4Controller, NULL },	// Giotek VX4 - trackpad/gyro don't work. Had to not filter on interface info. Light bar is flaky, but works.
```

**Comment by decaffeinatedcoffee** [comment]
> Jep. O DS4Windows nunca teve a intenção de usar gamepads xinput como uma fonte porque a ideia era fazer conversão de saída dinput-> xinput (ou seja, usar gamepads dinput como fonte e então fazer com que parecessem jogos como dispositivos xinput porque poucos anos atrás poucos jogos eram suportados dispositivos dinput fora da caixa, mas todos com certeza suportam pads xinput).
> 
> Hoje em dia o aplicativo DS4Windows faz muito mais do que apenas conversão dinput-> xinput (macros, regras de re-mapeamento de botão, mudanças de curva de saída em tempo real, etc etc) e suporta até modo de saída dinput via driver de dispositivo ViGem de Nefariou. Portanto, em teoria, aceitar xinput pads como uma fonte pode ser útil, mas a base do código antigo mostra sua maldade aqui. Não seriam apenas "algumas linhas de código" para usar pads xinput como fonte.
> 
> Alguns gamepads compatíveis com DS4 realmente se registram como dispositivos xinput no PC em vez de dispositivos dinput DS4. Com alguns pads compatíveis, este problema pode ser resolvido por algumas configurações nos drivers para forçar o pad a agir como uma entrada no PC. Em alguns casos, a remoção do driver de dispositivo específico do fornecedor era necessária para forçar o teclado a agir como uma entrada de dados. E alguns pads ainda têm um switch para escolher entre o modo xinput vs dinput.
> 
> Mas, desculpe, você está sozinho aqui porque poucas pessoas usam esse teclado (a primeira vez que vi aquele código VID / PID mostrado no arquivo de log). Tenho certeza de que pode haver alguma maneira de forçá-lo a se registrar como dispositivo dinput DS4 compatível no PC, mas como? Quem sabe e quase impossível de depurar sem ter esse tipo de hardware ...
> 
> Mesmo o driver de dispositivo SDL no Linux lista este pad e VID / PID como um pouco problemático.
> 
> ```
> // Removing the Giotek because there were a bunch of help tickets from users w/ issues including from non-PS4 controller users. This VID/PID is probably used in different FW's
> 	// { MAKE_CONTROLLER_ID( 0x7545, 0x1122 ), k_eControllerType_PS4Controller, NULL },	// Giotek VX4 - trackpad/gyro don't work. Had to not filter on interface info. Light bar is flaky, but works.
> ```

Thanks for the help, I tried to start my control together with the computer instead of plugging it in after turning it on, and ds4 again recognized it, but this time the control finally worked, However returning the value from 4 to -1 he stops, but it finally worked, thank you very much.

**Comment by mika-n** [comment]
Aaah. Interesting. Is there a touchpad, lightbar, rumble and gyro in that gamepad? Does those work? And is it wired only or both wired and BT wireless?

Yes. The "-1" doesn't work with that gamepad, but once this gamepad is added to the official release then it would work without those debug tweaks. But now you have to use the debug version and the "4" tweak.

**Comment by decaffeinatedcoffee** [comment]
> Aaah. Interessante. Existe um touchpad, lightbar, rumble e giroscópio nesse gamepad? Isso funciona?
> E é apenas com fio ou com fio e sem fio BT? Se ele também oferece suporte ao modo sem fio, como o DS4Windows informa o valor da bateria?
> 
> Sim. O "-1" não funciona com esse gamepad, mas uma vez que este gamepad é adicionado ao lançamento oficial, ele funcionaria sem os ajustes de depuração. Mas agora você tem que usar a versão de depuração e o ajuste "4".

It is just usb, the led doesn’t change color, rumble works normally (only software that made this controller’s vibration work with me), I think it doesn’t have gyro, the battery level is show as 75% (it has no battery)  It also doesn't have a touchpad, but it was the only software that detected the button under what should be the touchpad. 
I am very happy to finally be able to make this controller work as it should, thanks again.
