### ISSUE TITLE
[Bug?] Absolute Mouse

### ISSUE THREAD

**Issue by Chrisnetika** [Ryochan7/DS4Windows#1741]
What determines the center when using absolute mouse option for touchpad? I tried it and it kept snapping to lower left my screen.Any option to configure the center? Would be useful for me for what i'm trying to use it for.

**Comment by Ryochan7** [comment]
There is no way to a bounding box for the absolute mouse as of yet. The center of the absolute mouse will be the center of your display(s) as reported by Windows. That will cause problems for some people if they are using more than one monitor.

**Comment by Chrisnetika** [comment]
> There is no way to a bounding box for the absolute mouse as of yet. The center of the absolute mouse will be the center of your display(s) as reported by Windows. That will cause problems for some people if they are using more than one monitor.

ahh that is why it not working right for me, I use 2 displays .. gotcha!
*crossing my fingers that this is somethingthat can be evolved in time(no rush)

**Comment by Ryochan7** [comment]
I should get around to this at some point. The only progress made is that I had found a .NET library for tracking active monitors in Windows but I cannot even remember the name of it anymore.

**Comment by Chrisnetika** [comment]
O cool, sounds good thanks ^^

**Comment by Ryochan7** [comment]
Tested this out with FakerInput and SendInput support. For a single monitor setup, snap to center works fine so the coordinate system is correct. Snap to center on a multi-monitor setup should not snap to the absolute left corner but could gravitate towards that direction depending on the monitor configuration. Haven't really had any real use for Absolute Mouse support still.

Some more recent developments have been happening in my Steam Controller mapper. The output coordinate system was abstracted a bit more and I think the current setup would technically work better for a multi-monitor setup; there is no way to configure which monitor(s) are used so the whole desktop viewport is still used. The WpfScreenHelper NuGet package is used to help keep track of monitor changes.

At some point, I plan to play through Torchlight 2 again and my old config required Absolute Mouse support for character movement.

**Comment by Ryochan7** [comment]
Those changes were moved over to DS4Windows a while ago. Should be good enough. Closing.
