### ISSUE TITLE
[Question/Suggestion] DS4Windows and RPCS3 Synergy

### ISSUE THREAD

**Issue by MonfGeiger** [Ryochan7/DS4Windows#1746]
Here's the deal: I did not know until a week + change ago, that rpcs3 has its own native ps3/ps4 controller support to where I dont need ds4windows to use my ps4 controller and play games on it. This thread of mine is primarily a question thread first, but it may lead into its secondary as a Feature Suggestion

As DS4Windows is now (I'm running v2.2.1), is there a way I can configure it to "turn off" like it does when I click the stop button while rpcs3 is running, but when rpcs3 closes (all processes tagged with it ending as well), ds4windows boots back up and it rehooks into the ps4 controller without needing to force the controller to shut off and boot it up again to free it any

My goal here is automating

**Comment by mika-n** [comment]
Yes, auto-profile feature has an option "temporarily turn off" to turn of DS4Windows app when a certain app is running in foreground.

Another way is to use alternative profile which uses "Use D-Input only" option (if this option is set in a profile then DS4Windows leaves the original gamepad as it is and supports only mouse/kbd mappings. The virtual output controller is not created).

Third way to automate something is to use cmdline interface. Through this technique you can do pretty much whatever and it is up to a custom app to decide when to do something.
https://github.com/Ryochan7/DS4Windows/wiki/Command-line-options

Maybe you can workout something through these options.

**Comment by MonfGeiger** [comment]
I have 2 profiles in ds4windows: default, and a clone of it called AltDefault. AltDefault is my main, with the only options changed from the normal default being it doing rainbow lightbar while plugged in and a pink lightbar while running. I am also using the legacy "Hide DS4 Controller" option to avoid double controller problems

If I were to use Auto Profiles to do this, what do I change to make this work

**Comment by Ryusennin** [comment]
In the Auto Profiles tab, select your RPCS3 profile and enable "Turn off DS4Windows temporarily".

**Comment by MonfGeiger** [comment]
thanks :)
