### ISSUE TITLE
Sprint Issue

### ISSUE THREAD

**Issue by poothief** [Ryochan7/DS4Windows#1747]
Whatever game I try to play using DS4 windows i cant sprint properly. I hold it down or press and it just immediately stops sprintiong

**Comment by Ryusennin** [comment]
Your post is not really useful. There are many ways to sprint in different games, it's impossible to know what's going wrong in your case. I nevertheless suspect a double input issue. You probably need to enable exclusive mode ("hide DS4" option or HidGuardian).

**Comment by Ryochan7** [comment]
Assuming that the input button is bound to a Macro
