### ISSUE TITLE
F1 Challenge 99-02 (DirectInput game) Issues

### ISSUE THREAD

**Issue by vpontin** [Ryochan7/DS4Windows#175]
Hi! I'm trying to use DS4Windows with F1 Challenge 99-02 (a game which only recognizes Dinput gamepads), and seems like it's only picking the default generic "Wireless Controller", so, no rumble nor customized actions for gyro (i've assigned them for WASD, but the game wont react in anyway) for it.

What i need to do to enable features like rumble, remapping on dinput games too?d

Thanks in advance!

**Comment by Ryochan7** [comment]
I am not sure the DInput equivalent Xbox 360 controllers support rumble via DInput so that might be a lost cause.

**Comment by vpontin** [comment]
So... is there any way to "translate" xinput gamepads to dinput just like we do with x360ce (the other way)?

**Comment by vpontin** [comment]
Found this: https://steamcommunity.com/sharedfiles/filedetails/?id=165238623

Worked like a charm for my Dualshock. I will close the issue.
