### ISSUE TITLE
DS4 emulation not recognized by Windows or Steam

### ISSUE THREAD

**Issue by apschultz** [Ryochan7/DS4Windows#1750]
**Describe the bug**
I recently upgraded from the Jays2Kings version (I didn't know this existed!). While going through the new settings I noticed it was possible emulate the ds4 directly while maintaining the rest of the mappings, but I have been unable to get this to work. When emulated controller is set to the xbox 360, the controller (which is a ds4) is seen by everyone. When emulated controller is set to dualshock 4, the controller disappears entirely. Neither windows controller settings nor steam show the controller. Oddly enough, if I don't start ds4windows after rebooting the PC, the controller is seen and usable (I just don't get any of the benefits of ds4windows).

I have accidentally enabled exclusive mode ("Hide DS4 Controller") in the past, but that is currently disabled.

**To Reproduce**
1. ) Connect ds4 controller
2. ) Configure emulated controller as dualshock 4 in controller profile.

**Expected behavior**
Windows and Steam recognized the PS4 controller and provide appropriate button layout.

**Screenshots**
![image](https://user-images.githubusercontent.com/13374240/104132736-3fa07680-534d-11eb-9053-23611bbea5d7.png)
![image](https://user-images.githubusercontent.com/13374240/104132752-547d0a00-534d-11eb-9494-790d630a8097.png)

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: [e.g. Windows 10 Pro 20H2
 - DS4Windows Version" 

**Additional context**
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/5793169/ds4windows_log.txt)

**Comment by mika-n** [comment]
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#steam-doesnt-see-the-virtual-output-controller-if-a-profile-uses-the-dualshock4-output-type-steam-sees-the-ds4-controller-only-if-ds4windows-uses-xbox360-output-controller-type

https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#when-a-profile-uses-dualshock4-output-controller-with-hidguardian-tool-then-both-physical-and-virtual-controllers-are-hidden

**Comment by apschultz** [comment]
Thank you for your help. Unfortunately the problem persists. I updated the driver and renamed the executable to myapp.exe/myapp.exe.config and both windows and steam fail to see any controller.

I haven't used the hid tools, unless you're implying something was done under the covers. I'm happy to remove or reset anything needs to be.

**Comment by apschultz** [comment]
Apologies. It does seem things have changed somewhat. The windows control panel does show two "Wireless controller" entries. The first, which seems to be present also when the xbox controller is listed, properly shows controller inputs. The second, which appeared after switch to dualshock 4 emulation, doesn't show any input from the controller being recognized. Steam still does not show anything.

**Comment by Chrisnetika** [comment]
Doesn't steam have it's own driver to make ds4 work natively with it?

**Comment by Ryochan7** [comment]
Intentional block by Steam. Not my problem.
