### ISSUE TITLE
DualSense triggers Input doesn't match the Output

### ISSUE THREAD

**Issue by RyuMakkuro** [Ryochan7/DS4Windows#1751]
I've noticed that both the triggers reach their full output with only about 75% input. Physical input to be specific. DS4Windows and Windows controller properties both showcase this problem (games obviously as well), be it emulated or not.
You can see the reported input reach 100% at the same time as the output, however the trigger still has room to move. I'd say around 25% of input is just gone.

While this is not a big problem for games that treat triggers as digital input, for those that do rely on analog data it can vary from annoying to outright unplayable. I tried playing Forza Horizon 4 with it and I was constantly locking wheels under braking along with sliding much more due to reaching full input on throttle way too quickly. Extremely jerky driving so to speak. Switched to DS4 to sanity check myself and none of said issues happened. And that's a simcade that has a lot of leeway on your input, not a simulator that requires much more precision like Assetto Corsa Competizione.

If this issue isn't only on my DualSense, I imagine this was intended by Sony due to adaptive triggers providing vibration and extra resistance so that you can maintain that 100% input while the trigger is vibrating. Not to mention extra resistance would inform you when you reach 100%.

Not sure if it would be possible to increase the digital input and output range to match the physical but at least some form of adaptive trigger setting that could "lock" the triggers so they don't move past a certain point would be neato.

**Desktop:**
 - Controller Make and Model: Sony DualSense CFI-ZCT1W
 - OS: Windows 10 Pro 20H2
 - DS4Windows Version 2.2.1

**Comment by Ryochan7** [comment]
Hate to tell you but that is how the DualSense triggers work. It has been confirmed in Hid Report Inspector; finally a use for that app. There is a good amount of throw after the controller reports the max trigger value unlike the DS4 which has a smaller amount of throw left after reporting its max value. Maybe that is to help take into account effects on the Adaptive Triggers but it is a bit of a problem when just using the triggers normally.

**Comment by RyuMakkuro** [comment]
So any chance we could have a setting that would use the adaptive triggers in a way that could lock their max input or at least provide extra resistance past a certain point? Cause once you can tell when the max input happens, muscle memory will naturally start kicking in.

**Comment by Ryochan7** [comment]
I have not gotten around to allowing device specific settings for profiles.
