### ISSUE TITLE
Even if another button is set on the touchpad, the signal of pressing the touchpad is output along with the set button, when the Emulated Controller is set to DualShock 4.

### ISSUE THREAD

**Issue by gwin7ok** [Ryochan7/DS4Windows#1752]
** Describe the bug **
Even if another button is set on the touchpad, the signal of pressing the touchpad is output along with the set button, when the Emulated Controller is set to DualShock 4.

** To Reproduce **
1. Set Emulated Controller to DualShock 4 in profile
2. Set all four touchpad settings to Square and save profile
3. When you press the touchpad, the signal of the touchpad (14) is output along with Square (1).
* When Emulated Controller is set to XBOX, only the X Button signal is output.

** Expected behavior **
Only the button signal set on the touchpad is output

** Screenshots **
Profile settings
![ss002 - DS4Windows](https://user-images.githubusercontent.com/1727775/104270026-e49c8a00-54da-11eb-937e-4bf4e528675b.png)

Signal output at Steps to reproduce 3.
![ss003 - Wireless Controller のプロパティ](https://user-images.githubusercontent.com/1727775/104270083-fed66800-54da-11eb-8096-a87a4c7dc8d2.png)

HidGuardian settings
![ss005 - HIDNinja](https://user-images.githubusercontent.com/1727775/104270124-10b80b00-54db-11eb-87b9-6d7a5cc26ad0.png)

** Desktop (please complete the following information): **
 --Controller Make and Model: Sony DS4 v.2 (cuh-zct2j)
 --OS: Windows 10 Pro Build 2004
 --DS4Windows Version 2.2.1
 --HidGuardian Version 1.14.3.0

**Comment by Ryochan7** [comment]
It has worked that way for a long time as there is no way to fake map a Touchpad click button output. Trying to get the DualSense Mute button and the problems that followed showed how involved mapping more buttons would be due to the code base. As it is, the easiest way around this behavior would be to only pass the Touchpad click action when using Passthru mode.

**Comment by gwin7ok** [comment]
Thank you for your support. Only the signal of the set button is output now.
Version 2.2.2
