### ISSUE TITLE
Controller Freezes on imput (sometimes)

### ISSUE THREAD

**Issue by Cyberb28** [Ryochan7/DS4Windows#1754]
From time to time, when I would plug my controller in, the controller would just freeze, since the controller is frozen and (for users who own a PS5) the PS5 is turned off, so how are you going to turn off the controller? You cant, I tried, I have had to wait until my controller runs out of battery in order for it to turn off before I could use again. 

I have tried every single version that was created since the support for the DualSense controller was added. I have had the same issue with every version. 

So from what I know: 

If the controller is turned off and you plug it into DS4Windows its fine, however if the controller has been on for some time and then you plug it in, (Sometimes) It would freeze and be completely unusable.

**Comment by Masamune3210** [comment]
I know at least on the DS4 there is a button combo you can do to force the controller to turn off if simply holding the ps button or using the reset hole doesn't work. Is there not for the DualSense? Just got mine two days ago so I haven't had a chance to fuzz it much hardware wise

**Comment by Cyberb28** [comment]
I believe there is a reset hole for the DualSense 5, for me, it did not work, the controller becomes completely unusable. I have a PS5 so when my controller freezes, I have a 2nd controller which I just switch over too, to unfreeze the one that got frozen, then I can plug it in again. I have a temporary solution for now, but for people who only have 1 controller and no PS5 yeah thats a problem, I can see this being or becoming a big issue.

**Comment by mika-n** [comment]
are you sure you have the latest ViGem 1.17.333 version and not the old 1.16.xx version in use?
Using the latest DS4Windows app version with an old ViGem driver version may cause some weird bugs.

**Comment by Cyberb28** [comment]
Yes I am using the latest version
