### ISSUE TITLE
PC Shutdown Error

### ISSUE THREAD

**Issue by shinra358** [Ryochan7/DS4Windows#1756]
When the OS has been on for a while, and you finally shutdown the PC, this error pops up which requires to manual press the force shutdown button: 
![20210113_030351_HDR](https://user-images.githubusercontent.com/3978291/104464642-2a139280-5581-11eb-9bee-968f03c29a73.jpg)

Win7u

**Comment by Ryusennin** [comment]
On rare occasions I've seen a similar error on Win10. It's hard to reproduce, in my case it can happen at shutdown after I've been running camb2docker (a Boinc project) for a while.

**Comment by mika-n** [comment]
Windows7 may be out of luck, because this error is not easily re-produced and very few people still use Win7. And it may have something to do with bugs in MediaPlayer notification logic also.

I have never seen reports from Win10 with this error msg. Few times seen reports from Win7 users.
