### ISSUE TITLE
Possible bug: DS4State Touch reporting

### ISSUE THREAD

**Issue by midget35** [Ryochan7/DS4Windows#1759]
Found some interesting and unexpected results when logging out DS4State touch variables. Just because the results were unexpected for me, does not mean this is a bug... but I figure it is possible. So, regarding DS4State, there are 3 curiosities:

1. When the controller is first turned on, the TouchLeft value is 'true' (though the touchpad has not been touched). Is this expected behaviour? Is it right that TouchLeft and TouchRight can never both be 'false' at the same time?

2. TouchLeft and TouchRight can never both be 'true' at the same time, even though each thumb is placed on left and right sides of trackpad.

3. I also find the TouchLeft value can be made to be 'true' when only the right part of trackpad is being touched, and vice versa.

Reproduce:
- Touch the left of the trackpad (withouht pressing the button)
- While touching left, use other thumb to touch right side of the trackpad (still not pressing button).
- Remove left thumb from the left side of trackpad, without moving right thumb.

Outcome:
Though only the right side of trackpad is being touched, TouchRight is 'false' and TouchLeft is 'true'. This is the opposite of what I was expecting.

Hope this makes sense.

**Comment by Ryochan7** [comment]
TouchLeft and TouchRight are with respect to Touch1. The coordinate data for Touch1 will still exist when the left thumb is taken off the Touchpad although the active state will be false. The right thumb will still correspond to Touch2 as that is the way it works in the hardware.

That behavior is the way Touchpad support has always worked AFAIK. In this case, changing the behavior to check for each touch and change the flag might result in odd behavior for the virtual Touch buttons. There would likely be a lot of unintentional button presses as one thumb is released while using the Multi-touch virtual button. It would probably be best to leave this as it is.

**Comment by Ryochan7** [comment]
Outside of the virtual Touchpad buttons, that is why the Touch1Finger and Touch2Fingers flags exist. Those were originally made to work around issues I had with Gyro Mouse triggers when using a Touchpad touch as a Gyro trigger.

**Comment by midget35** [comment]
> Outside of the virtual Touchpad buttons, that is why the Touch1Finger and Touch2Fingers flags exist. Those were originally made to work around issues I had with Gyro Mouse triggers when using a Touchpad touch as a Gyro trigger.

Hey, Ryo. Thank you so much for the detailed explanation.  I will take this new information on board. Much appreciated, sir!

**Comment by CJacobsSA** [comment]
Just to add onto this, Death Stranding currently seems to have issues with this implementation. In that game you have to be holding a finger on the touchpad to use the gyro functions on the map screen and so on. Even with all of the gyro and touchpad functions set to passthru or unbound, something about the implementation of finger touches into DS4W seems to have made the game think the virtual controller is intentionally activating it.
