### ISSUE TITLE
Issues with playing audio from controller

### ISSUE THREAD

**Issue by Kaitoni** [Ryochan7/DS4Windows#176]
When I connect headphones to controller, everything is ok with audio. But once I start DS4Windows, it stops playing and only stopping DS4Windows and unplugging+plugging(it is connected via USB) of device helps.
Am I doing something wrong or there is a way to fix it?

**Comment by Ryochan7** [comment]
I am pretty sure you are using the Jays2Kings version. This has not been a problem with recent builds of DS4Windows for a while.
