### ISSUE TITLE
Can't add windows store game to auto profiler

### ISSUE THREAD

**Issue by TheMasterDingo** [Ryochan7/DS4Windows#1761]
I was trying to add forza horizon(from windows store) and other games from there to auto profiler but could not do it because windows keeps the games as apps the in their magic folder with magical owners and messing with ownership usually brakes the apps (WindowsApps folder).
Is there a way to fix this ?

Thanks

**Comment by mika-n** [comment]
https://github.com/Ryochan7/DS4Windows/wiki/Profile-selection-using-auto-profile-rules

> 
For example Windows Store apps share the same c:\windows\system32\applicationFrameHost.exe process name. Using both path and window title search keywords it is possible to identify different WinStore applications even when the process path is the same for all of them.

**Comment by TheMasterDingo** [comment]
> https://github.com/Ryochan7/DS4Windows/wiki/Profile-selection-using-auto-profile-rules
> 
> > 
> 
> For example Windows Store apps share the same c:\windows\system32\applicationFrameHost.exe process name. Using both path and window title search keywords it is possible to identify different WinStore applications even when the process path is the same for all of them.

i aplogize for not doing my research as i should, i got it to work with that method only in one game (forza horizon), it does not work in hollow knight or in Ori for example even if i leave application frame host without window title which makes it work in weather calendar and other apps, any idea how can i fix it?

**Comment by mika-n** [comment]
enable the debug option in AutoProfile screen and then see the logfile or Logs tab page for more info about the app (the logfile should show you how those apps behave with process and window title names).

**Comment by TheMasterDingo** [comment]
> enable the debug option in AutoProfile screen and then see the logfile or Logs tab page for more info about the app (the logfile should show you how those apps behave with process and window title names).

Yes i did that, tried with reported path, exe name, $, * parameter, none worked.
Even set them to full screen.
Maybe i can do something with the PID?

**Comment by mika-n** [comment]
No, PID is not supported as a "keyword/search key" in DS4Windows auto-profiles. And the pid would be different each time you launch the app anyway (and in WinStore apps the PID often is linked to applicationFrameHost.exe processID).

But maybe you can use the cmdline interface to automate the profile selection and use some external logic to pick up the correct profile? For example make a batch file to launch the game and just before the game is launched you would choose a correct profile via cmdline commands).
https://github.com/Ryochan7/DS4Windows/wiki/Command-line-options

**Comment by TheMasterDingo** [comment]
> No, PID is not supported as a "keyword/search key" in DS4Windows auto-profiles. And the pid would be different each time you launch the app anyway (and in WinStore apps the PID often is linked to applicationFrameHost.exe processID).
> 
> But maybe you can use the cmdline interface to automate the profile selection and use some external logic to pick up the correct profile? For example make a batch file to launch the game and just before the game is launched you would choose a correct profile via cmdline commands).
> https://github.com/Ryochan7/DS4Windows/wiki/Command-line-options
> 
> And if there are some problems accessing external process names from DS4Windows app then have you tried to launch the DS4Windows app with "Run as Administrator" option?

I run it as a task in admin mode, yes i thought about the batch but would really prefer the auto profiler, this is the log for example `DEBUG: Auto-Profile. PID=7236 Path=\\?\volume{11d48397-873b-a502-bb32-9165d1967c1a}\oriandthewillofthewisps-pc.exe | WND=394716 Title=oriandthewillofthewisps`
![Immagine 2021-01-15 113117](https://user-images.githubusercontent.com/75000441/104714533-9929ec00-5725-11eb-9d6b-30f93a2dd72c.png)

**Comment by mika-n** [comment]
How about if you specify following search keywords:
AppName: oriandthewillofthewisps-pc.exe$

This should batch with process names ending with oriandthewillofthewisps-pc.exe string.

**Comment by TheMasterDingo** [comment]
> How about if you specify following search keyword in appName field:
> oriandthewillofthewisps-pc.exe$
> 
> This should match with process names ending with oriandthewillofthewisps-pc.exe string.

Yes i tried when i read the guide you sent, does not work, until now forza is the only game that works all the others don’t switch profile( games are on the same ssd and downloded on the same day)

**Comment by mika-n** [comment]
Have you found any freeware WinStore app where auto-profiler doesn't work? I might try this scenario with such app.

**Comment by TheMasterDingo** [comment]
> Have you found any freeware WinStore app where auto-profiler doesn't work? I might try this scenario with such app.

Tried some now, cinebench r23 doesn't work, try with that

**Comment by mika-n** [comment]
There was actually a bug in autoProfile code, but it is now fixed. The next official release should have the fix.
For now you can test the debug version and verify if it works better there. At least here the Cinebench app now worked and it was possible to define, for example, cinebench.exe$ search keyword in the Path textbox and now it actually works.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

**Comment by TheMasterDingo** [comment]
> There was actually a bug in autoProfile code, but it is now fixed. The next official release should have the fix.
> For now you can test the debug version and verify if it works better there. At least here the Cinebench app now worked and it was possible to define, for example, cinebench.exe$ search keyword in the Path textbox and now it actually works.
> https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems
> 
> Thx for reporting the issue.

I tried the debug version but it can not detect the controller when i connect it
