### ISSUE TITLE
DS4Windows Froze on Connecting Controller

### ISSUE THREAD

**Issue by nicegamer7** [Ryochan7/DS4Windows#1762]
**Describe the bug**
I've never had this happen before, nor do I know how to reproduce it unfortunately. I thought I'd just open an issue to see if anyone can figure out what happened. The issue happened when I tried to connect my controller, it appeared in DS4Windows but then DS4Windows froze and my controller disconnected.

**To Reproduce**
Unsure :(

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: Windows 10 Pro Build 20H2
 - DS4Windows Version 2.2.1

**Additional context**
Here's the log: https://paste.gg/p/anonymous/630f312ca6dd4793912560c60ed3937b

**Comment by Ryochan7** [comment]
> 2021-01-14 21:47:04.0502|ERROR|System.ComponentModel.Win32Exception (0x80004005): The operation completed successfully

What a positive exception. :rofl:

**Comment by nicegamer7** [comment]
Since the stack trace has something to do with ViGEm, I guess it migh be helpful to note I'm using ViGEmBus 1.17.333

**Comment by Ryochan7** [comment]
Not sure what to do about that one tbh. Why throw an exception if the call was successful? I am not sure if it would be safe to catch that exception and just let it go without the fear of catching errors that should cause a program crash.

**Comment by Ryochan7** [comment]
The ViGEmClient code is likely throwing some sort of exception but something else is resetting the last error code before the exception can propagate. The only recourse would be to have DS4Windows close the connection to ViGEmBus and stop the background service.

**Comment by nicegamer7** [comment]
Could this be something to pass onto Nefarius?

**Comment by Cyberb28** [comment]
I also have this problem, I opened a ticket few days ago as well, for me, the controller sometimes freezes and sometimes not therefore I also don't know how to reproduce it.

**Comment by nicegamer7** [comment]
I looked at the issue you opened. This is not the same issue.

**Comment by Ryochan7** [comment]
I don't have any rough data but looking at the source code makes me think the problem likely starts here. The CloseHandle call would likely negate the previous error from appearing later.

https://github.com/ViGEm/ViGEmClient/blob/master/src/ViGEmClient.cpp#L624

```
if (GetLastError() == ERROR_ACCESS_DENIED || GetLastError() == ERROR_OPERATION_ABORTED)
{
    CloseHandle(lOverlapped.hEvent);
    return;
}
```

In that case, no error code is returned to ViGEm.NET which causes the noted exception to be thrown (default clause).

https://github.com/ViGEm/ViGEm.NET/blob/master/ViGEmClient/Targets/Xbox360Controller.cs#L96

```
var error = ViGEmClient.vigem_target_x360_register_notification(Client.NativeHandle, NativeHandle,
                _notificationCallback);

switch (error)
{
    case ViGEmClient.VIGEM_ERROR.VIGEM_ERROR_NONE:
        break;
    case ViGEmClient.VIGEM_ERROR.VIGEM_ERROR_BUS_NOT_FOUND:
        throw new VigemBusNotFoundException();
    case ViGEmClient.VIGEM_ERROR.VIGEM_ERROR_INVALID_TARGET:
        throw new VigemInvalidTargetException();
    case ViGEmClient.VIGEM_ERROR.VIGEM_ERROR_CALLBACK_ALREADY_REGISTERED:
        throw new VigemCallbackAlreadyRegisteredException();
    default:
        throw new Win32Exception(Marshal.GetLastWin32Error());
}
```

I am just going to opt for the idea that I had before. If this error is detected then DS4Windows will just attempt to stop and close its connection to ViGEmBus.

**Comment by Ryochan7** [comment]
Hopefully the change will be enough to allow the process to fail gracefully if the problem pops up again.

**Comment by nicegamer7** [comment]
Okay, I'll wait for the next release and report back if it ever happens again.
