### ISSUE TITLE
Can't use as Dualshock until reboot 

### ISSUE THREAD

**Issue by MrIronstone** [Ryochan7/DS4Windows#1764]
When my DualShock's battery dries, I plug it into my computer to charge it up, I can use it on a charge while Dualshock emulated profile is on but when I unplug my Dualshock, I cannot use Dualshock emulated profile again until reboot.

**Desktop**
 - Controller Make and Model: Sony DS4 v.1 (CUH-ZCT1H)
 - OS: [Windows 10 Version 1909]
 - DS4Windows Version [e.g. 2.2.1]

**Comment by mika-n** [comment]
Logfiles before and after the disconnect/re-connect events?
