### ISSUE TITLE
DS4 Latency has been going up  

### ISSUE THREAD

**Issue by tylxr2119** [Ryochan7/DS4Windows#1768]
Never had any issues up until today. . Ds4 controller is wirelessly connected to the Bluetooth. Controller is flashing red & white and is spiking latency 5ms to 8ms to 10ms.

**Comment by mika-n** [comment]
anything below <10ms is pretty OK. Maybe you should simply increase the latency warning MS value?
Or if you use BT dongle then try to attach it at the end of USB extension cable and this way moving it closer to gamepad and desk level (in case it is attached at the back of PC sitting under a desk).

**Comment by TheMasterDingo** [comment]
I am noticing spikies at 10-11ms ( from 0-1) when rumble is on, is it normal?

**Comment by mika-n** [comment]
The latency time is not scientifically accurate, so I'm sure few ms variation is OK, but I haven't noticed anything suspicious when rumble is activated. And least anything worth noticing.

**Comment by TheMasterDingo** [comment]
> The latency time is not scientifically accurate, so I'm sure few ms variation is OK, but I haven't noticed anything suspicious when rumble is activated. And least anything worth noticing.

Yes was just noticing the lightbar going red when rumble was active and noticed the log saying 10-11ms , but that might be because the info entering the controller is increasing and so the latency?
