### ISSUE TITLE
[Feature Request] Map controller buttons to keyboard

### ISSUE THREAD

**Issue by xuru-thor** [Ryochan7/DS4Windows#1770]
You can already map keys to a button, but it would be very nice if you could do the opposite.
Unrelated, but it would also be great if you could map more than a single key to a button, making it so when you press the button, both keys get pressed.

**Comment by Ryusennin** [comment]
You can do that with JoyToKey.

**Comment by Ryochan7** [comment]
The first request is a case for a completely different mapper. I am not even convinced that mapping a keyboard and mouse to a virtual Xbox 360 controller would work well anyway.

The second inquiry might technically be possible but there are some hurdles that keep it from being implemented. The backend DS4Windows code is not very flexible and changing output bindings to use a List rather than a single value could break all current DS4Windows profiles. I have tried to test this a couple of times and nuked my minor progress.

**Comment by Yohoki** [comment]
The request about mapping multiple buttons to a single button is already possible. Just use the "Record a Macro" function. It will let you assign multiple keyboard OR controller inputs onto a single input. I've used this to map entire Mortal Kombat combos to a single button, if you fiddle with the delays a bit.

**Comment by isaakfawkes** [comment]
> The request about mapping multiple buttons to a single button is already possible. Just use the "Record a Macro" function. It will let you assign multiple keyboard OR controller inputs onto a single input. I've used this to map entire Mortal Kombat combos to a single button, if you fiddle with the delays a bit.

 So how do you record diagonals/ quarter circles/ half-circles with the the D Pad? And can you designate that certain buttons activate at the same time? Ex: ->, -> Triangle +Circle?

I would love a tutorial on macros. Or some form of a common macro database like Steam has for controller configurations.

**Comment by Ryusennin** [comment]
Buttons/keys activate at the same time if you don't specify any delay between them.

**Comment by Yohoki** [comment]
> 
> So how do you record diagonals/ quarter circles/ half-circles with the the D Pad? And can you designate that certain buttons activate at the same time? Ex: ->, -> Triangle +Circle?
> 
> I would love a tutorial on macros. Or some form of a common macro database like Steam has for controller configurations.

You can use the controller to do exactly that. If you press a button, but don't release a button before pressing the next, it will remain held down. So pressing left, then up, then letting go of left, then letting go of up would be diagonal up+left. Same can be done with Tri+Circle.

If you need to record a quarter circle on D-pad, turn on delays. It will put that slight delay in that you naturally do and you can tweak the timings afterwards.

tutorial shouldn't really be needed. Just go in, hit record, and press the buttons you need pressed and hit stop.

> 
> 
> Buttons/keys activate at the same time if you don't specify any delay between them.

They do not activate at *exactly* the same time without delays. There's a tiny delay between each one. My macro for CMD allows me to instantly type in commands that I use frequently, and there are no delays set between them, but they do type out one at a time, just very quickly. This is still okay for games, however. Games don't expect you to be able to press 2 buttons, especially on opposite sides of the controller, at the *exact* same time. There's usually some wiggle room of about a frame or two.
