### ISSUE TITLE
[Feature request] Add option for disconnecting bluetooth controller in command line options

### ISSUE THREAD

**Issue by TheMasterDingo** [Ryochan7/DS4Windows#1773]
For now i am using server stop and then server start with “disconnect on server stop” toggle.
It would be nice to have a command that directly disconnects the controller.
Thanks

**Comment by mika-n** [comment]
You mean something else than there already is?
https://github.com/Ryochan7/DS4Windows/wiki/Command-line-options

**Comment by TheMasterDingo** [comment]
> You mean something else than there already is?
> https://github.com/Ryochan7/DS4Windows/wiki/Command-line-options

I don't see a command to only disconnect the controller, there is shutdown but it closes the program also.
For now i am doing this to disconnect (with disconnect on server stop option enabled)
stop server
timeout 2 
start server 
( i use the timeout because if i put the commands in the script one after the other it fails to connect the controller next time)

**Comment by Masamune3210** [comment]
Correct me if I'm misunderstanding but wouldn't it just be easier to disconnect the controller with the controller itself? By default there is a hotkey assigned to start+ps button to disconnect

**Comment by TheMasterDingo** [comment]
Yes i know that. Well in my case i am streaming with Moonlight and i have made a little script to disconnect the controller after i end the streaming because i am connecting the controller to a bluetooth dongle in VirtualHere(usboverip). So i have to disconnect the controller first and then unplug the bluetooth dongle (terminate virtualhere connection) , if i forget to do so the controller will stay on.

i mean even with server stop-start works fine, just thought it would be useful to have it directly as a command.

**Comment by TheMasterDingo** [comment]
Version 2.2.9 has "Added Disconnect command line option"

Tested it, works great.
Found no info for the command parameters except this:
https://github.com/Ryochan7/DS4Windows/commit/4710528f63945686989aa8e27eb3b21aa160b18f

As i understand 'Disconnect.device' disconnects every controller
and for example 'Disconnect.1' disconnects controller in slot 1

Thanks a lot guys for adding this feature.

**Comment by Ryochan7** [comment]
The current option only disconnects one controller per command. It could be changed to allow disconnecting all wireless controllers if no device index argument is set. Will get that changed in a bit.

**Comment by TheMasterDingo** [comment]
Oh yes i tried it now and 'Disconnect.device' did disconnect only device 1.

**Comment by mika-n** [comment]
Doc page updated to explain the new Disconnect cmdline option
https://github.com/Ryochan7/DS4Windows/wiki/Command-line-options
