### ISSUE TITLE
No Controllers will connect.

### ISSUE THREAD

**Issue by whymaxwhy** [Ryochan7/DS4Windows#1775]
This program used to work really great for me. Until the fateful day i kept getting the message below. im not to smart when it comes to coding so i have no clue what to do. it will not detect any of my controllers but my controllers all connect to steam. please help. ive uninstall everything and reinstalled it all but no luck to prevail.

THE ERROR CODE:
System.AggregateException: One or more errors occurred. ---> System.InvalidCastException: Unable to cast object of type 'System.String' to type 'System.String[]'. at DS4Windows.ControlService.UpdateHidGuardAttributes() at DS4Windows.ControlService.Start(Boolean showlog) at DS4WinWPF.DS4Forms.MainWindow.<>cDisplayClass24_0.<LateChecks>b0() at System.Threading.Tasks.Task.Execute() --- End of inner exception stack trace --- ---> (Inner Exception #0) System.InvalidCastException: Unable to cast object of type 'System.String' to type 'System.String[]'. at DS4Windows.ControlService.UpdateHidGuardAttributes() at DS4Windows.ControlService.Start(Boolean showlog) at DS4WinWPF.DS4Forms.MainWindow.<>cDisplayClass24_0.<LateChecks>b0() at System.Threading.Tasks.Task.Execute()<---

**Comment by mika-n** [comment]
You must have messed up HidGuardian AffectedDevices setting.
Do you see there one or more device entries (use Windows regEdit tool to find this entry)? And is the value single string or an array of strings? It should be an array of strings even when there is just one controller ID listed.

See also this https://github.com/Ryochan7/DS4Windows/issues/1729

**Comment by whymaxwhy** [comment]
holy crap man. im not sure wtf youre saying. how did i mess something up when i never did anything different?

**Comment by whymaxwhy** [comment]
how would you explain the solution to this problem to someone who doesnt code at all. basically a monkey, explain this to me as if i were a monkey

**Comment by mika-n** [comment]
Show the screenshot from the following system registry settings. Just type "regedit" in the run field in Startup menu and run "Registry editor" tool. Then navigate to following three locations there and take a screenshots. Post those pics here (drag-n-drop the image file into a comment field)

```
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\HidGuardian\
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\HidGuardian\Parameters\
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\HidGuardian\Parameters\AffectedDevices
```

**Comment by whymaxwhy** [comment]
![Registry Editor 1_18_2021 4_16_55 PM](https://user-images.githubusercontent.com/77591373/104967318-b15d6d80-59a8-11eb-95de-46ba9c0fb75c.png)

**Comment by Ryochan7** [comment]
You corrupted your HidGuardian settings. You created an invalid AffectedDevices value by using the wrong data type; it is supposed to be saved as a **REG_MULTI_SZ (Multi-String Value)** because it represents a list of values. Not my fault.

HidNinja is bundled with DS4Windows so you don't have to edit the settings manually.

**Comment by whymaxwhy** [comment]
i didnt edit anything manually man i legit came back to it one day and its like this. can you at least explain a fix for me so i can continue to use the program

**Comment by whymaxwhy** [comment]
not my fault either but the least you could do is help with YOUR program since im not a freaking coder. im just a gamer man

**Comment by whymaxwhy** [comment]
Or at least explain how to completely wipe the program from my pc and start
all over again

**Comment by Masamune3210** [comment]
@whymaxwhy just a passerby, but you could do well with being a bit less aggressive if you are wanting people to help you...

**Comment by whymaxwhy** [comment]
dude said "Not My Fault." like i wanted to fuck his program up. im level headed im just wanna know why im not getting help from the guy that made this program. trust me if i knew how to fix the problem i wouldnt of come here, if i knew what to do im sure it would be easy, yet i am just a simple man that needs help and im gonna have to find it else where it seems

**Comment by whymaxwhy** [comment]
shit removing it all together would be best at this point

**Comment by Masamune3210** [comment]
No, they said "Not our fault" because either you or some other program messed up the registry key. You can either recreate the registry key in the correct type or probably, since you seem dead set on being angered by this, just uninstalling hidguardian

**Comment by whymaxwhy** [comment]
damn i feel like the dumb Karen type of customer. im not trying to be angry i just need a step by step on what i need to do. but its okay i will look for help else where.

**Comment by whymaxwhy** [comment]
LOOK MAN SOME ONE HAS TO HELP ME. I deleted hidguardian and now my pc doesnt even recognize my controller. Please Help

**Comment by whymaxwhy** [comment]
Dude this has wrecked my pc man now nothing works, my keyboard doesn’t work
mouse doesn’t work please someone help me

**Comment by whymaxwhy** [comment]
Please help me

**Comment by mika-n** [comment]
First of all "HidGuardian" is not "our product" at all. DS4Windows app doesn't even come with HidGuardian originally. It is an additional tool and downloaded separately from elsewhere. I wonder from where you have download it and what version. You didn't seem to read the pinned "Read this before posting a new issue ticket" post because your post lack all the necessary information (Windows and the app version).

And you did seem a bit aggressive, so that is not very helpful especially when you were told already what to do (fix the registry setting by deleting the AffectedDevices sysreg entry and then re-create it using a correct data type). 

Third you have now messed up your PC even more by trying to uninstall HidGuardian in a wrong way. When it is not uninstalled properly via a proper uninstall tool then this is exactly what may happen.

See this: https://github.com/Ryochan7/DS4Windows/issues/1525 and this https://www.winhelponline.com/blog/edit-registry-offline-windows-re/

**Comment by whymaxwhy** [comment]
Well first off if someone is using your product and telling others about
your product I expect a little compensation as to help. Not everyone knows
how to code like you guys, I’m not a genius, but for sure I know I’m not
coming back to you nor this website because of the lack of care you have
for customer service. Maybe if you would of help a little better the
problem wouldn’t of progressed. You need to stick with what you do and keep
you sticky fingers on the keyboard and mouse and have someone else do your
customer service. No thanks to you I have fixed my computer from the
problems you’ve gotten me Into. Sorry I “pinged” you so many times, it’s
called I needed help and I thought, “hey, maybe the creator might be cool
and explain this and not have any problems, Na not at all, you’re just a
useless entitled keyboard warrior.

**Comment by Ryochan7** [comment]
This has nothing to do with DS4Windows. DS4Windows does not write to the AffectedDevices list nor does the HidGuardHelper app. I don't know what you did at all or what route you even used to install HidGuardian. There are at least 4 different methods to install HidGuardian that I can think of. Only one is recommended by me and that is my test installer mentioned in the Wiki; things can go wrong when doing things manually with devcon.exe especially if you skip a step (such as loss of USB KB+M support).

It looks like you didn't use my installer or this wouldn't be happening. You could be using other software that is writing to the registry value for some reason. I don't know.

I have helped people in other threads today. There was close to nothing here to work on and the problem seemed self inflicted. My comment in issue #1729 (mentioned by Mika) would have been the extent of what could be said here.

https://github.com/Ryochan7/DS4Windows/issues/1729#issuecomment-754960900

As for your current dilemma, it looks like you better follow the advice in Mika's previous post if you don't want to re-install Windows.

**Comment by mika-n** [comment]
> Well first off if someone is using your product and telling others about your product I expect a little compensation as to help. 

HidGuardian is not the same as DS4Windows app. HidGuardian is a completely separate product developed by different people and installed separately if user chooses to do so. We know that in some cases it is the only way to hide the original device, but still it is not DS4Windows product. DS4Windows app and HidGuardian are two different beasts but can live happily together. 

Why HidGuardian sysregistry settings were corrupted/wrong/messed up in the first place in PC? With the information you provided it is impossible to say (you didn't even list app and winOS versions or provided the whole DS4Windows logfile). Anyway, DS4Windows app itself doesn't modify those values at all so someone else or something else must have done it.

And you still haven't posted required minimum information: WinOS and DS4Windows app versions and maybe a logfile.

Developers and other volunteers here do provide help, but in the exchange you have to do your part by reading and following instructions given in the pinned "Read this before posting a new issue ticket" message.
