### ISSUE TITLE
Huge input delay spikes (700ms) through Bluetooth. 

### ISSUE THREAD

**Issue by finbar1** [Ryochan7/DS4Windows#1779]
I am attempting to use ds4windows for the first time, I've reviewed a few videos online about optimal settings, but nothing relating to my issues. the controller works fine on my ps4 and wired to my pc. With Bluetooth the controller will sit idle on my desk at 2ms delay if i don't move the gyro/inputs, but as soon as I pick it up/move the sticks it seems to struggle with all the inputs, first spiking to 40ms for 1s then the program freezes and the next update says 250-700ms input delay depending on how many inputs I spammed at it, it seems to make it worse. Pc is new (5600x/3080) motherboard is asrock tachi x570s onboard intel Bluetooth adapter, do i need to buy a separate adapter would that fix it or is it some sort of software/driver issue? Also is there a way to disable the gyro readings, it seems to lag much worse when the controller is moved about.

**Comment by mika-n** [comment]
Please read the pinned "Read this before posting a new ticket". Your post is missing lots of required information.
