### ISSUE TITLE
I Uninstall HidGuardian/Pc Doesn't Recognize Keyboard and mouse

### ISSUE THREAD

**Issue by whymaxwhy** [Ryochan7/DS4Windows#1780]
Had a problem that i couldnt get fixed before but when i was trying to get rid of all my problems a new one occurs. Please Help me for the love of god. My steam doesnt even recognize my controller anymore please just give me something to work with.

**Comment by whymaxwhy** [comment]
Now it’s absolutely messed up my computer. I can only use my keyboard and mouse to get into bios. After boot I cannot use my mouse or keyboard to go to a previous state. This program has utterly destroyed my pc and the advice that was given to me

**Comment by mika-n** [comment]
https://github.com/Ryochan7/DS4Windows/issues/1775#issuecomment-762636482
