### ISSUE TITLE
problème déconnection manette ps5 en jeu

### ISSUE THREAD

**Issue by elbigo62** [Ryochan7/DS4Windows#1782]
bonjour le logiciel fonctionne très bien mis a part un problème en jeu le logiciel se quitte tout seul se qui déconnecte la manette ps5 après le lancement de ds4 impossible de retourne sur la partie avec la manette je suis obliger de rester en clavier souris je dois redémarrer le pc pour que sa refonctionne jusqu'à ce que le logiciel se quitte de nouveau tout seul.

**Comment by mika-n** [comment]
In English please?

**Comment by elbigo62** [comment]
hello the software works very well apart from a problem in the game the software quits itself which disconnects the ps5 controller after launching ds4 impossible to return to the game with the controller I have to stay in keyboard mouse I have to restart the pc so that its restart until the software quits again by itself.

**Comment by mika-n** [comment]
Please read the "Read this before posting a new ticket" pinned post and provide the minimum required information: DS4Windows app version, WinOS version, the latest %APPDATA%\DS4Windows\Logs ds4windows logfile (rename the log file as .TXT file and drag-n-drop attach it as an attachment here in a comment field).   What game?

Are you using a virtual output controller in dualshock or xbox360 mode?
Are you using dynamic or persistent gamepad slot in OutputSlot settings in DS4Windows?
BT or USB connection? Try either way. Is the result the same?

**Comment by Ryochan7** [comment]
Assuming your are using the DualSense in BT mode. Hopefully the last couple of updates fixed any possible crashes you might have come across. I would need the old log files from that time to have an idea about where DS4Windows crashed.

It is a common hardware behavior that the mode switch performed for the DS4 and DualSense will make the old DirectInput interface for the input BT controller be counted as dead. That is more a Windows issue than a hardware related issue but it is still not avoidable; the same behavior occurs when using Steam Input. Unless something else has gone wrong then you should be able to restart DS4Windows and resume using the controller in Xbox 360 mode fine; DS4 mode would likely not work unless you disconnect the DualSense and then reconnect.

**Comment by elbigo62** [comment]
hello indeed since it is 2 last update no more problem and I thank you for it even steam input I do not encounter any more problem of disconnection of the controller and directly recognized more need to relaunch the game or restart the pc so that it restarts. on the other hand I no longer have the daily data from ds4 because I have reset the pc to zero sorry.
