### ISSUE TITLE
[Feature Request] "dummy," controller connected after idle disconnect

### ISSUE THREAD

**Issue by zachThePerson** [Ryochan7/DS4Windows#1783]
Idle disconnect is great for saving battery, but a lot of games and emulators don't handle it well and will often then get stuck on KBM controls (even after the controller is reconnected) or worst case scenario will get stuck in controller mode but not detect the controller any more (The Sexy Brutale was horrible at this).

I propose that there is an option to leave a "dummy," controller connected even after idle disconnect. Since DS4Win sits between the hardware and the software, when the controller disconnects, DS4Win could still pretend that there is a controller plugged in so as far as the game knows there is no disconnect. This would universally solve the problem across all games, even if the specific game doesn't handle hot-swapping well.

**Comment by Ryochan7** [comment]
That is the main use case for the Permanent Output Slot device type. The feature already exists. I would primarily use the feature with older PC games that only use DirectInput with no hotplug support. It would not be fun to have the controller disconnect and then have to launch the game again so it can detect the new connection. Although, I don't normally use Idle Disconnect.

![ds4windows_output_permanent](https://user-images.githubusercontent.com/581968/105124002-cc120e00-5a9e-11eb-8967-07e9355aafb4.png)

**Comment by zachThePerson** [comment]
Ok, thanks for the screenshot! I looked around the entire program for this feature but couldn't find it. Apparently you have to click on the current controller item _first_ and then the item will appear.

Would be nice if it was always visible but grayed out until you click the controller. I'll go ahead and close this
