### ISSUE TITLE
The new passthru requirement to use touchpad click in ds4mode breaks my setup.

### ISSUE THREAD

**Issue by KBD20** [Ryochan7/DS4Windows#1784]
The new requirement breaks my setup for games that have native support - for example in Yakuza 7 I need to click the touchpad to access the map.
If I put it in passthrough mode it means I cannot use touchpad swipes for macros involving L3 and R3, which I need for accessibility reasons.

If possible can you add a setting to allow this requirement to be toggleable?

**Comment by Ryochan7** [comment]
Conflict of requirements as directed in #1752. Not sure what to do about this.

**Comment by KBD20** [comment]
I did a bit of playing around and I changed the usage of swiping for L3/R3 to a shift modifier for L2/R2, which is what I did when using PS4 Remote play.
So it's not as neccissary as I thought - just took me a bit to figure out.
