### ISSUE TITLE
Please change the Change Log

### ISSUE THREAD

**Issue by maestrini** [Ryochan7/DS4Windows#1788]
Hi,

I personally do not have an issue with it, but others are mentioning an issue on reddit:

Just wanted to say, that you may want to remove that Parler comment from the change log of 2.2.2, [Reddit](https://www.reddit.com/r/DS4Windows/comments/l0yj4l/question_about_the_dev/) is starting to cancel you and your application, calling you all sorts of things.

**Comment by Ryochan7** [comment]
It's Reddit. They are wrong by default.

**Comment by Ryochan7** [comment]
I would think that the still active account on Frog site would have been a bigger problem for those people.
