### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by StarryFate** [Ryochan7/DS4Windows#179]
I'm sorry but I have no idea how to actually open it up. I opened the zip. extracted and now im stuck.

**Comment by Ryochan7** [comment]
One major software requirement is that you have .NET version 4.5.2 or higher installed on your system. Not having that installed would be one reason, that I can think of, that the program would not open at all when executed.

http://www.microsoft.com/en-us/download/details.aspx?id=42642
