### ISSUE TITLE
sn30pro stopped working in xinput mode but only with ds4windows

### ISSUE THREAD

**Issue by budafuko** [Ryochan7/DS4Windows#1790]
for some reason just before the latest update my sn30pro stopped being recognized in xinput mode by ds4windows but xinput checker and gamepad test both see my paddle and all keypresses. if i put the sn30pro into switch pro mode it is then seen by the application but this is not a solution because the gyro doesn't work in this mode. this has been driving me nuts for a couple days i'm hoping i am just over looking something

edit: there is a small chance i noticed my paddle not working after the update but im fairly confident it was before the update

**Comment by mika-n** [comment]
download and test the last known working version to see if it works even there.
See the pinned "Read this before posting a new issue ticket" and provide the required information (versions, logfiles, etc)

**Comment by budafuko** [comment]
thanks i will test the previous version and also go back and read what was in the text bubble and make submissions that are required. out of habbit i cleared it without thinking

**Comment by budafuko** [comment]
ok i have tested previous versions of DS4Windows and for some reason none of them recognize my SN30pro

would you like the log from 2.22 or an other version?
when i first came across the problem i had thought maybe reinstalling DS4windows would solve my problem so the original log is likely gone with the wind :( but i can produce a log file from any version of DS4Windows back to 2.09 as i have them all installed in labelled folders to test my problem

**Comment by budafuko** [comment]
i installed the ViGEmBus driver after this stopped working and thankfully that allowed me to use it in switchpro mode... that never worked until i did that so i am thankful for that.. something else i noticed was that HIDGuardian started launching with DS4Windows around the same time this problem happened. i have no idea what it is and i do not think it launched before this issue although i could be mistaken... i would think i would remember the UAC promt though it is kinda annoying lol
