### ISSUE TITLE
Hori wireless PS4 Mini not recognized

### ISSUE THREAD

**Issue by aburke20** [Ryochan7/DS4Windows#1791]
The Hori PS4 Mini controller appears under "game controllers" on the control panel.

I can even go into HIDNinja, and see it listed, but "adding" its HID Devices IDs does nothing.

DS4Windows just doesn't see it.

 anything else I could try ?

**Comment by mika-n** [comment]
See the pinned "Read this before posting a new issue ticket" and provide the required information (versions, logfiles, etc)

And even better try to run the debug version and provide the logfile from there:
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems
