### ISSUE TITLE
[Enhancement] Use per device (serial) config values for Device Options

### ISSUE THREAD

**Issue by Ryochan7** [Ryochan7/DS4Windows#1792]
It might be better to change the current device settings system to change settings per specific device rather than applying a set of options across each device type. That would make the window behave more like how it currently does in Steam Input. I had considered it beforehand but I got discouraged and just felt like getting a release out there.

Take note that any saved changes will likely not carry over so you will have to start from scratch.

**Comment by mika-n** [comment]
360-steering wheel calibration values are already saved per device (identified by MAC) and saved in the controller-configs.xml file. That file could be used to store other device (not set in a profile) specific tweaks.

**Comment by Ryochan7** [comment]
The changes have been made and they have been merged into the repo.
