### ISSUE TITLE
Menu button stopped work in 2.2.2

### ISSUE THREAD

**Issue by Weaksfx** [Ryochan7/DS4Windows#1795]
Updated Ds4Windows and menu in game not opens when I click touch at ds4v2 controller. Just nothing happends. In 2.2.1 all worked great. Any help?

In profile Other tab - Emulated controller = Dualshock4.

**Comment by mika-n** [comment]
#1786    Try setting the touchpad option in a profile in "Passthrough" mode. The latest version changed this behavior and the touchpad click is forwarded only when the touchpad is in Passthrough mode.

**Comment by Weaksfx** [comment]
Yep. Thanks. Now it works jus fine. That wasn't obvious). Thank you again. Great job on this app.
