### ISSUE TITLE
Touchpad click not working in game 

### ISSUE THREAD

**Issue by edzambrano6599** [Ryochan7/DS4Windows#1797]
Ever since the new update, my touchpad hasn't been allowing me to click it in any game. For example, in COD Warzone, I cant pull out the map when I press the middle or both bottom parts of the touchpad. I haven't changed the setting at all and it was functional before the update.  

**Desktop**
 - Controller Make and Model: PS5 Controller 
 - OS: [e.g. Windows 10 Education 2020]
 - DS4Windows Version [e.g. 2.1.5]

**Comment by mika-n** [comment]
See #1795 

closed as duplicated ticket
