### ISSUE TITLE
ds4windows randomly choose player / controller between player 1 until 4 (it only connected one controller) i'm using ds4windows 2.2.2 (it's also appear on the earlier version)

### ISSUE THREAD

**Issue by nfsmania** [Ryochan7/DS4Windows#1798]
please fix the ds4windows randomly choose player between 1 until player 4 (while it only use one controller not 4), i already try the newest driver but it still has that problem, while the newest driver not require restart to make the controller player 1 again, but it still annoying,

and the problem is appear when i connect and reconnect the ds4 press start and stop on ds4windows or using ps button to turn off the controller while i already press stop on ds4windows, after press start on ds4windows and connect the controller again it become player / controller 2, 3 or 4

and if it likes that (become other than player / controller one) on cemu or rpcs3 many games that only support 1 controller are not recognized the controller like yakuza, god eater 3, senran kagura, etc

it still detect as controller 1 on ds4windows but on cemu or rpcs3 it detects as controller / player 2-4

i already using latest driver, output slot using permanent, and also use recommendation from other user 

also sometimes it needs to restart windows to make the controller detect as player 1 or controller 1 again, please fix that problem

you can check the video if you want to see the issue that i mean

https://user-images.githubusercontent.com/77222204/105464602-b9921180-5cf6-11eb-831c-c898b37728ac.mp4

**Comment by mika-n** [comment]
Have you tried to set the Outputslot 1 as Persistent? Then DS4Windows would try to keep the virtual output controller alive even when the physical source gamepad is disconnected and this way games won't see "disconnect/connect" events and recycle gamepad slots.

**Comment by nfsmania** [comment]
where's the outputslot 1 settings

**Comment by Ryusennin** [comment]
It should be the first controller in your list. Except your list is strangely empty.

**Comment by valentyn-l** [comment]
I have the EXACT same issue! The controller position inside CEMU changes everytime. Also, GTA IV doesn't let me use the D-Pad to browse through the in-game phone unless the controller is set to the 1st position.

**Comment by nfsmania** [comment]
> 
> 
> It should be the first controller in your list. Except your list is strangely empty.

btw there's no persistent option or maybe i can't find on ds4windows app

**Comment by nfsmania** [comment]
> 
> 
> I have the EXACT same issue! The controller position inside CEMU changes everytime. Also, GTA IV doesn't let me use the D-Pad to browse through the in-game phone unless the controller is set to the 1st position.

yeah i hope they'll fix this issue because if this issue appear sometimes must restart windows for get it back normal which is so embarasing

**Comment by mika-n** [comment]
The OutputSlots tab page has "Dynamic vs Permanent" option when a gamepad is connected. Try setting the option on the right side of the slot list as "Permanent" (and press Accept btn) when the gamepad is connected in slot#1. After this DS4Windows tries to keep the virtual output controller alive even when the gamepad is disconnected while an emulator or game is running.
![ds4win_OutputSlotsPermanent](https://user-images.githubusercontent.com/35538525/106242792-ec656980-6210-11eb-8cb3-6c019f4dc30e.png)

DS4Windows app itself doesn't assign those controller numbers, it is up to the WindowsOS and it takes the value from ViGem driver handling these virtual output controllers. Make sure you have the latest ViGem driver 1.17.333 version (if running in Win10. The latest Vigem no longer support Win7).
https://github.com/ViGEm/ViGEmBus/releases

**Comment by nfsmania** [comment]
> 
> 
> The OutputSlots tab page has "Dynamic vs Permanent" option when a gamepad is connected. Try setting the option on the right side of the slot list as "Permanent" (and press Accept btn) when the gamepad is connected in slot#1. After this DS4Windows tries to keep the virtual output controller alive even when the gamepad is disconnected while an emulator or game is running.
> ![ds4win_OutputSlotsPermanent](https://user-images.githubusercontent.com/35538525/106242792-ec656980-6210-11eb-8cb3-6c019f4dc30e.png)
> 
> DS4Windows app itself doesn't assign those controller numbers, it is up to the WindowsOS and it takes the value from ViGem driver handling these virtual output controllers. Make sure you have the latest ViGem driver 1.17.333 version (if running in Win10. The latest Vigem no longer support Win7).
> https://github.com/ViGEm/ViGEmBus/releases

already do this (make the slot list permanent) but sometimes this issue are still there, and if want to back to controller 1 must sign out windows or for the worst case restart windows

**Comment by nfsmania** [comment]
especially after ds4windows crash (not responding) and when i opened the ds4windows again and connect the controller this issue will appear

**Comment by nfsmania** [comment]
> 
> 
> The OutputSlots tab page has "Dynamic vs Permanent" option when a gamepad is connected. Try setting the option on the right side of the slot list as "Permanent" (and press Accept btn) when the gamepad is connected in slot#1. After this DS4Windows tries to keep the virtual output controller alive even when the gamepad is disconnected while an emulator or game is running.
> ![ds4win_OutputSlotsPermanent](https://user-images.githubusercontent.com/35538525/106242792-ec656980-6210-11eb-8cb3-6c019f4dc30e.png)
> 
> DS4Windows app itself doesn't assign those controller numbers, it is up to the WindowsOS and it takes the value from ViGem driver handling these virtual output controllers. Make sure you have the latest ViGem driver 1.17.333 version (if running in Win10. The latest Vigem no longer support Win7).
> https://github.com/ViGEm/ViGEmBus/releases

this issue appear again now, and yeah ds4windows hasn't crash, and again must do sign out or restart windows again wtf, and you guys just say the same thing again and again, it's kinda like you not understand this issue duh

https://user-images.githubusercontent.com/77222204/106369473-a0ecc000-63b6-11eb-8b84-bfc9ed1804a4.mp4

**Comment by mika-n** [comment]
Feel free to fix the problem if you have the issue there. Can't re-produce the error here, so "nothing to be fixed".
You don't seem to have any profiles set for a controller. I'm not sure what happens when there is no profile because usually there should be at least one profile. Try creating a new default profile and set it for a controller.

**Comment by Gianlucas94** [comment]
I have the same problem
