### ISSUE TITLE
DS4 won't connect after update. Can't install Vigembus

### ISSUE THREAD

**Issue by NeroXyn** [Ryochan7/DS4Windows#1799]
After doing the update to ver. 2.2.2 yesterday, the DS4Windows doesn't recognize my controller immediately and instead asks me to install Vigembus. The problem is that I can't install Vigembus and keep getting the prompt saying the vigembus is not available ( as pictured)
![image](https://user-images.githubusercontent.com/77872802/105569912-c87ac300-5cfa-11eb-93aa-fad27b074c55.png)

I have looking for solutions online but nothing fixes it.

I tried reinstalling HID game controller on the device manager, reinstalling any mentioned Visual C++ redistributables, and restarting the PC.

I believe there is nothing wrong on the controller side because Steam still can pick up the controller natively.

Thanks.

**Comment by Ryusennin** [comment]
Try using the stand-alone installer.

https://github.com/ViGEm/ViGEmBus/releases/tag/setup-v1.17.333

**Comment by Ryochan7** [comment]
It looks like DS4Windows is able to download the stand-alone installer fine. It is a process within the installer itself that cannot grab an online resource needed to continue. Maybe the ViGEm server was down at that time? The stand-alone installer is downloaded from GitHub.
