### ISSUE TITLE
Connecting a DualSense at some points will fail or crash DS4Windows

### ISSUE THREAD

**Issue by Serfrost** [Ryochan7/DS4Windows#1802]
Both scenarios may require a few attempts in quick succession before the issue may trigger.

**Scenario 1 (Failure to connect):**

> At times, attempting to connect a DualSense to DS4Windows while DS4Windows has already been started will result in it not finding the DualSense.  You must stop & start DS4Windows for the controller to be found & connect.
> 
> This usually occurs after quickly unplugging / reconnecting the controller in quick succession, but can happen if only done once.  It may have something to do with ViGEmBus failing to remove the previous controller instance before you reconnect the controller.
> 
> This is primarily an issue for those who have bad connections either via bluetooth or wire.  Jostling your connection cable on accident may end up disconnecting and reconnecting your controller, resulting in this issue.

**Scenario 2 (Crash):**

> If you connect a DualSense controller with a Permanent Output slot enabled, either over USB or Bluetooth, DS4Windows will seize up / crash immediately **_at some points_**
> 
> Reproducible by plugging in a cable while it's already connected over bluetooth; the controller will connect but DS4Windows will fail to update the controller listings. It's at this point that if you unplug/replug the controller, the program will freeze or crash.
> 
> After the crash occurs, the next time you open DS4Windows the Permanent Output slot has been reset.

**Rare Scenario**:

> Some instances of reconnecting the controller will only result in DS4Windows saying that an item with the same key has already been added.

**Expected behavior**
The controller should connect and resume activity as expected.

**Desktop:**
 - Controller Make and Model: Sony DualSense (CFI-ZCT1W)
 - OS: Windows 10 Pro Build 2004
 - DS4Windows Version 2.2.2

**Log:**

[crashlog.txt](https://github.com/Ryochan7/DS4Windows/files/5862485/crashlog.txt)

**Comment by Serfrost** [comment]
**Update on this:**

> After manually installing ViGEmBus Setup v1.17.333 this issue seems to have been resolved, at least from what I can tell.  That said, I'd encourage you enforce reinstallation of ViGEmBus with a new DS4Windows update as simply running the driver setup currently will just install ViGEmBus Setup v1.16.112

**Comment by K54M** [comment]
Been having the same issue (Scenario 2.) The DualSense controller's LEDs will turn off & DS4W will stop responding until I end it via Task manager.  When I start it back up, it works again for a random amount of time until it crashes again. For me its been happening via BT.

**Comment by Serfrost** [comment]
> Been having the same issue (Scenario 2.) The DualSense controller's LEDs will turn off ... For me its been happening via BT.

Make sure (if you're using a USB BT adapter) that you turn off USB Selective Suspension off within Windows' Power Plan. 

However, this will only be a band-aid solution to help the dropped connection, unless this is doesn't fit your use case.

**Comment by Ryochan7** [comment]
Other people have reported hotplug problems regarding a certain List changing while still utilized in a foreach loop. I was able to reproduce the problem once. Version 2.2.3 fixed that issue.

Not sure about the XML issue. There is already two forms of synchronization being done (lock and Dispatcher) so there should be no multi-threading issues in that spot.

**Comment by Serfrost** [comment]
I should mention that I haven't really had this problem since you mentioned your changes in 2.2.3 - so if I encounter anything like it again, I'll just inform you here.
