### ISSUE TITLE
Vigembus problem

### ISSUE THREAD

**Issue by GeraltV47** [Ryochan7/DS4Windows#1807]
**Describe the bug**
I got vigembus installed manually, but when i first run ds4windows by ryochan7 and download and install vigembus driver it says: installation failed, please retry, when im retrying to install it i got only repair or remove option so is my vigembus being installed? What cause this problem that ds4windows by ryochan7 doesnt see vigembus driver? Is that related to my OS?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2E)
 - OS: Windows 7
 - DS4Windows Version [e.g. 2.2.2]

**Additional context**

**Comment by mika-n** [comment]
Windows 7 is doomed. The latest ViGem 1.17.333 supports only Win10. And during the last few releases there has been all sort of other weird issues with Win7 installations, so time to upgrade to Win10.

**Comment by Ryusennin** [comment]
Install the stand-alone version of ViGEm 1.16, it will run just fine on Win7 providing you don't use a DualSense.

https://github.com/ViGEm/ViGEmBus/releases/tag/setup-v1.16.116

**Comment by mika-n** [comment]
closed as "Win7 users are on their own soon anyway, so time to upgrade to Win10 is the easiest solution to all sort of Win7 isssues".
