### ISSUE TITLE
UI is not being themed

### ISSUE THREAD

**Issue by Nova77x** [Ryochan7/DS4Windows#1808]
For some reason the UI isn't being themed, except for the edit button.

https://imgur.com/a/KxlSOOq

```
01/25/2021 03:09:20: DS4Windows version 2.2.2
01/25/2021 03:09:20: DS4Windows Assembly Architecture: x64
01/25/2021 03:09:20: OS Version: Microsoft Windows NT 10.0.18363.0
01/25/2021 03:09:20: OS Product Name: Windows 10 Enterprise
01/25/2021 03:09:20: OS Release ID: 1909
01/25/2021 03:09:20: System Architecture: x64
01/25/2021 03:09:21: Running as User
01/25/2021 03:09:22: Starting...
01/25/2021 03:09:22: Connection to ViGEmBus 1.17.333.0 established
```

**Comment by Ryochan7** [comment]
Not sure why that is. Are you using Best Performance mode for Visual Effects? For reference, the Edit button uses a control provided by the Extended WPF Tookit (SplitButton control) rather than one provided by the standard WPF controls.

https://github.com/xceedsoftware/wpftoolkit

**Comment by Nova77x** [comment]
This seems to explain the issue:

https://superuser.com/questions/171175/wpf-windows-dont-cooperate-with-unofficial-themes

A solution to the problem (forces a specific theme, so it doesn't fall back on classic):

```
According to this blog, you can do the following in App.xaml:

<Application.Resources>
    <ResourceDictionary Source="/PresentationFramework.Aero;V3.0.0.0;31bf3856ad364e35;component\themes/aero.normalcolor.xaml" />    
</Application.Resources>
```
https://stackoverflow.com/questions/8604836/wpf-looks-win98ish-with-custom-ms-style
