### ISSUE TITLE
Guide button does not work

### ISSUE THREAD

**Issue by romanad** [Ryochan7/DS4Windows#1809]
Hello, dear developer
Thanks for amazing app.
I have a single problem
Guide button does not show Game bar.
But when I press Win+G it's showing fine

OS Name:                   Microsoft Windows 10 Enterprise x64
OS Version:                10.0.18363 N/A Build 18363
App Version:               2.2.2

Can you please help with this issue?
Or maybe I can try to bind Guide button to Win+G hotkey? I didn't find how to do that.

**Comment by Ryochan7** [comment]
Not sure why that would not work. GameBar is one of the first things I disable on a new install of Windows and PS mapped to Guide makes it pop up beforehand. Do you actually have Guide mapped to PS or is something else mapped to it? Are you using a KB+M preset?

**Comment by romanad** [comment]
Thank you very much, I just installed updates of Windows and it began to work. The issue can be closed.
