### ISSUE TITLE
DS4 Driver Isn't being isn't installing

### ISSUE THREAD

**Issue by zoutiyx** [Ryochan7/DS4Windows#181]
I'm trying to connect my PS4 controller to my laptop, but when trying to install the DS4 driver, it says that it fails. 

I took a look at the main website and realize that it's down. Can that possibly be the reason? Also, is there another way to get the DS4 driver installed like manually or something?

**Comment by Ryochan7** [comment]
I have the ScpVBus archive hosted on my own server. You have to be using one of the releases posted here in order for the program to use the new location. I just uninstalled the Scp VIrtual Bus Driver on my system and tried the installation routine in DS4Windows. It worked just fine for me.

http://23.239.26.40/ds4windows/files/Virtual%20Bus%20Driver.zip

**Comment by TristanYoung** [comment]
When I switched from Jays2Kings fork to Ryochan7's fork, I basically copied the files over-top, never had this problem.

Sounds like a lot of people are trying to get their DS4's working with Windows and landing on J2K's page.  Too bad they're downloading a really old version.

**Comment by Ryochan7** [comment]
Nothing to do here. This only serves as a reminder that I should finally get a domain name.

**Comment by Ryochan7** [comment]
Got a cheap domain. The Virtual Bus Driver archive can be found at the following location.

http://ryochan7.xyz/ds4windows/files/Virtual%20Bus%20Driver.zip
