### ISSUE TITLE
Add option to enable touchpad click in touchpad mode as it was in 2.2.1

### ISSUE THREAD

**Issue by TheMasterDingo** [Ryochan7/DS4Windows#1811]
On 2.2.1 i started the controller with touchpad off and used it for touch click in game, and when switching to desktop i enabled the touchpad ( it is a great feature for gaming in the couch), the 2.2.2 disabled this behaviour.

Can it be re-enabled or added as optional in a future update?

Thanks

**Comment by Ryochan7** [comment]
What benefit would having the touchpad click be in this case as opposed to mapping to the virtual buttons?

**Comment by TheMasterDingo** [comment]
Not sure if I understand correctly, it is faster for me to follow the screen ui and press the button represented there ( touchpad for example) instead of a mapped one.
I use my dualsense and ds4 in bt mode in virtual ds4 nearly all the time.
On 2.2.1 i was using it mapped as tocuhpad click on all areas and when needed the mouse if i switched to the desktop one moment i pressed (ps+touch) to enable mouse navigation. 

P.s ( not related to original problem) The passthrough mode does not work 100% correct, there are games that differentiate betwwen touchpad click right and left and the only way it worked for me was to press everywhere on touchpad for touchpad click left command and two finger press for touchpad click right command( maybe it is an intended behavior)
