### ISSUE TITLE
DS4Windows doesn't see my controller anymore

### ISSUE THREAD

**Issue by GeraltV47** [Ryochan7/DS4Windows#1815]
**Describe the bug**
DS4Windows doesn't see my controller anymore when connected via bluetooth or normal method, controller is being recognised by windows and light bar lights with white light
**To Reproduce**
Im not sure what caused this.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2E)
 - OS: [e.g. Windows 7 Ultimate
 - DS4Windows Version [e.g. 2.2.2]

**Additional context**

**Comment by GeraltV47** [comment]
in log i noticed Gamepad data write connection is lost. Disconnecting the gamepad. LastErrorCode=121

**Comment by GeraltV47** [comment]
Ok i connected my bluetooth dongle to another port and paired my controller again and it works fine.

**Comment by mika-n** [comment]
if the BT dongle is attached directly to the PC then I recommend you to try usb extension cable and this way getting the BT dongle further away from the radio storm caused by PC chassis (and the dongle is closer to the gamepad and not hidden behind desk and PC chassis).
