### ISSUE TITLE
Increased Lag

### ISSUE THREAD

**Issue by Chrisnetika** [Ryochan7/DS4Windows#1817]
**Describe the bug**
-Idk exactly what version it started to happen on, i noticed it been about 1.5 weeks it been going on and usually will update the same day of release or next day so guess around version 2.2.1/2.2.2 where I been getting lag with my controls.Like in a game my char moves on it own or controls not very responsive/or slow regardless if i am using bluetooth or using wired.This report might come off rather vague so i'm wondering what it could be?

**To Reproduce**
-I load up noxplayer(android emulator), load mobile legends(game) then I either plug in my controller or press ps button to connect via bluetooth.Ds4 windows switches to Android profile I setup then emulator recognizes my controller and able to use it.Lag doesn't happen right away but notice it does after a time.I do not notice lightbar flashing to indicate high latency.
Latency ingame seems fine, usually 20-40ms if I play local games.My fps in emulator shows on avg 55-60fps.I will attack log and the profile I am using.Wish I could be more descriptive of the issue but idk where to begin tbh lol.

**Expected behavior**
-To work like it always has untill recent, smoth controls no lag.

**Screenshots**

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: [e.g. Windows 10 Enterprise build 18362.19h1
 - DS4Windows Version [e.g. 2.1.5]: 2.2.2

[Android.zip](https://github.com/Ryochan7/DS4Windows/files/5898382/Android.zip)
[log-ds4.txt](https://github.com/Ryochan7/DS4Windows/files/5898383/log-ds4.txt)

**Comment by Chrisnetika** [comment]
I will revert to 2.2.0 for now to see if I continue to have an issue, will report with results later when I have time to play the game.

**Comment by Ryochan7** [comment]
Release 2.2.0 was busted at launch. 2.2.1 was released around an hour later to fix that error.

**Comment by Chrisnetika** [comment]
ok 2.2.1 works so far, will see how the lag goes and will report what I experience

**Comment by Ryochan7** [comment]
Sort of noticed a change in behavior here. It looks like the main culprit for extra lag is the Gyro averaging routine introduced in version 2.2.3.

**Comment by Chrisnetika** [comment]
I'm still using 2.2.1 as of this moment and did not experience lag so far I can report.The issues I faced most likely were in 2.2.2/2.2.3

**Comment by Ryochan7** [comment]
Hopefully you will have more success with version 2.2.5. Made a couple of different tweaks that definitely help app performance on my machine

**Comment by Chrisnetika** [comment]
Will test 2.2.5, will let you know my experience with it after a day or 2

**Comment by Chrisnetika** [comment]
rolled back, tho I not experienced lag yet what I experience is unresponsiveness meaning cotrols went crazy.. was doing their own thing.I mostly been playing using an android emulator playing a moba MLBB and ingame I was trying move my character and it was like my controls just cutoff and my character was moving on it's own.
Issues I have is mostly on bluetooth as it was this time.When I used the wire it stabilized for me.I wanna be able to use my ds4 wirelessly through bluetooth bc these cheap micro usb connections tend to break/bend easy and already on my 7th wire zzz.
Thank you Ryo for looking into this

**Comment by Ryochan7** [comment]
Turns out some of the issue was with the ViGEm library as well. Errors being thrown in the background were slowing down the process a bit. Version 2.2.7 seems to work out better with the changes to the library

**Comment by Chrisnetika** [comment]
I will give it a try, Now when I think about it the issues did coincide with updating vigem.Thanks for the update Ryo!

**Comment by Chrisnetika** [comment]
Been testing 2.2.7 so far for past few days.I can attest that the lag has been improved alot.I noticed 1 small hiccup yesterday but other than that your on track.After the latest commitsonce it tabulated into a new release under your discretion Ryo you can close this issue.

**Comment by bubin7766** [comment]
I've been having issues with lag as well where for some reason the latency shoots up to the thousands and ive had to revert to using an older version im currently on 2.28 as well
