### ISSUE TITLE
ds4windows randomly choose player / controller between player 1 until 4 (it only connected one controller) please fix this issue and don't kidding me

### ISSUE THREAD

**Issue by nfsmania** [Ryochan7/DS4Windows#1819]
please fix this issue (ds4 randomly choose player) and don't say about you must do output slot permanent and use latest vigem driver because i already do that, but still sometimes this issue appear again duh (must sign out or restart windows to make the controller read as controller 1 or player 1), i'm tired about that word "must do output slot permanent / use latest vigem driver" tbh

so, please fix this issue i'm serious 

you can see the issue that i mean in this video (the video is taken today and i already do what you recommend to)

https://user-images.githubusercontent.com/77222204/106373028-7dd40780-63da-11eb-90c8-fc7ddff7c919.mp4

**Comment by Masamune3210** [comment]
might want to lay off of the demanding of people who don't get paid to do this

issue is already covered in many other issue reports. If the problem was evident or easy to solve, it would be fixed

**Comment by Ryusennin** [comment]
"please fix this issue and don't kidding me"

LOL! Thanks, I had a good laugh.

Seriously though, do **NOT** open a new ticket to repeat the same bug report as #1798.

**Comment by Ryochan7** [comment]
![hello_peter_whats_happening](https://user-images.githubusercontent.com/581968/106418152-489bd980-641b-11eb-9884-c8c75188c3e3.png)

Besides, you intentionally deleted the Default profile. I am not surprised the program goes to an invalid state.

**Comment by mika-n** [comment]
closed as duplicate to 1798

PS. @nfsmania if you are not happy with the development department or with the customer service department then please contact our customer feedback department for a refund. There are tens of people just waiting for messages like this.....
