### ISSUE TITLE
Input lag/delay

### ISSUE THREAD

**Issue by skyline31** [Ryochan7/DS4Windows#1823]
Hi, while using PS4 controller with ds4 through bluetooth the input lag was about 1.5-3, got my ps5 controller, downloaded the latest version, connected through bluetooth, and I'm getting about 10ms input lag, anyway to lower it down?

**Comment by Chrisnetika** [comment]
could be kinda related to issue I had
https://github.com/Ryochan7/DS4Windows/issues/1817

**Comment by Chrisnetika** [comment]
when I mean I had I mean I am using downgraded version for now untill it gets worked out

**Comment by mika-n** [comment]
closed as duplicated #1817
