### ISSUE TITLE
Lightbar Passthru--light off

### ISSUE THREAD

**Issue by kiberegor** [Ryochan7/DS4Windows#1824]
Heavy Rain example
in DS4Windows a profile with Lightbar Passthru is selected when the game starts, this light appears, but after a while this LED goes out and does not light up anymore

**Comment by Ryochan7** [comment]
There are reasons I initially disabled DS4 feedback support after several attempts. For the most part, the data coming in is wrong and unreliable. I didn't re-enable the functionality and the initial problems that I found have never been fixed. I would just suggest you don't use the feature.

**Comment by Ryochan7** [comment]
Related to issue #1389. The problem has been confirmed to be with ViGEmBus and a request has been made for functionality to correct the problem. As it is, there is nothing to be done in DS4Windows until a future ViGEmBus driver is released except maybe disabling passthru lightbar and rumble support again.
