### ISSUE TITLE
Dropdown for trigger effects showing placeholder instead of selected value

### ISSUE THREAD

**Issue by MicaelJarniac** [Ryochan7/DS4Windows#1825]
**Describe the bug**
Dropdown for trigger effects showing placeholder instead of selected value.

`DS4WinWPF.DS4Forms.ViewModels.[TwoStageChoice/TriggerEffectChoice]`

**To Reproduce**
1. Go to **Profiles**
2. Edit a profile or create a new one
3. Under **Axis Config**, scroll down to **L2 & R2**
4. See the dropdown menus at **Two Stage Mode** and **Trigger Effect**

**Expected behavior**
The dropdown menus should display the currently selected values.

**Screenshots**
![Screenshot](https://i.imgur.com/nIEkVWM.png)

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DualSense [DS5]
 - OS: Windows 10 Pro Build 1909
 - DS4Windows Version 2.2.3

**Comment by Ryochan7** [comment]
Not sure why it was working fine before but not here. Guess I should have added a ToString method to the class as a precaution. Fortunately, the actual value should be correct.

**Comment by MicaelJarniac** [comment]
Yeah, it works correctly, it's just a visual thing it seems.

**Comment by Ryochan7** [comment]
This oddity only affects the Dark theme. The proper value name does show up when using the Default theme. :shrug:

**Comment by Ryochan7** [comment]
I didn't modify that portion of the control theme beforehand IIRC; it should have been the vanilla template given by Visual Studio. Anyway, I stumbled upon an extra property via StackOverflow that fixed the issue with that ContentPresenter tag. There is no need to add a ToString method for those Enum classes used for some ComboBox controls. That would have been a valid workaround though.

I will push out an update shortly (probably tomorrow).

**Comment by Ryochan7** [comment]
Version 2.2.4 is now out. It includes the fix as well as Gyro Swipe mode.

**Comment by MicaelJarniac** [comment]
Awesome! I'll close this issue now, then. Thanks for the awesome tool!
