### ISSUE TITLE
Touchpad no longer works in DS4 emulation mode

### ISSUE THREAD

**Issue by RyuMakkuro** [Ryochan7/DS4Windows#1828]
Normally in games that support DS4, touchpad acts as the good ol' "select" button as Sony demands on developers that the Share button cannot be bound into any game actions, therefore touchpad is being used instead. However now it doesn't work as such in DS4 emulation mode despite doing so perfectly before. If I disable DS4Windows and use either DualSense or DualShock 4 on their own, the touchpad is detected normally without issues and in FFXII TZA/Witcher 3 the map is being opened normally.

In version 2.2.2 the touchpad would act as a left on the d-pad. In 2.2.3 it just doesn't do anything at all.

**Expected behavior**
Touchpad performing the Select button actions.

**Desktop:**
 - Controller Make and Model: Sony DS4 v.1 (CUH-ZCT1E) and Sony DualSense (CFI-ZCT1W)
 - OS: Windows 10 Pro Build 19042.746
 - DS4Windows Version 2.2.3

**Additional context**
The problem appeared with the 2.2.2 version of DS4Windows.

**Comment by mika-n** [comment]
See the "passthru" vs "control" option in Touchpad settings

**Comment by RyuMakkuro** [comment]
Thank ye sir that indeed fixed the issue. No idea why it changed to control option or why the "Passthrough DS4 input" was unticked when the update kicked in. But all is good now :D

Back to opening the map every few seconds despite knowing the map like the back of my hand.
