### ISSUE TITLE
2.2.3 does not reassign controller to output slot

### ISSUE THREAD

**Issue by Uiasdnmb** [Ryochan7/DS4Windows#1830]
**Describe the bug**
Controller is not assigned to an output slot if it reconnects with secondary profile loaded.

**To Reproduce**
1. Connect (DS4 bluetooth) controller
2. Pad gets assigned to slot and becomes active (regardless of loaded profile)
3. Use "Special Action - Load Profile" to load another profile
4. Disconnect controller
5. Upon reconnection controller is still in loaded (different from selected) profile and doesn't get assigned to any output slots
6. Switch or load another profile (thru special action or interface) - pad gets assigned to an output slot

Additional details:
Controller connects and shows in controllers correctly. This issue was not present on 2.2.2.

**Comment by Harkirat101** [comment]
what does that mean

**Comment by Uiasdnmb** [comment]
I have to restart DS4Windows to have my controller work as it only assigns controller to an output slot once. After disconnecting and reconnecting the controller I can't do anything.

**Comment by Ryusennin** [comment]
Tested unplug/replug in USB and slot is automatically set to permanent again.

Can you test in wired mode?

**Comment by Ryochan7** [comment]
Works for me

**Comment by Uiasdnmb** [comment]
Ok so now I had some time to play around with it and this is what I came up with:

I've had one of my buttons set as "Special Action - Load Profile" - so i can toggle between profile Default to Profile2.
If I disconnect while my controller is in Default profile then during reconnection it works fine.
If I disconnect while Profile 2 is loaded then pad is not reassigned after reconnecting. It gets assigned only after I switch to another profile.

So right now it seems if upon connection loaded profile is not equal to selected profile then it's not assigned to any output slot.

**Comment by mika-n** [comment]
There are "load a profile" and "load a temporary profile" features in DS4Windows backend. Those are probably something which have been already in the original Jay2Kings version, so the reasoning behind why two different logic is unknown for everyone. LoadProfile changes the default profile, but LoadTempProfile doesn't change it (ie. when DS4Windows is restarted then it won't re-load this temp profile automagically).  Anyway, slot functionality should work no matter how the latest profile was loaded, so it is a bug if slots are broken after temp profiles.
