### ISSUE TITLE
Triggers, lightbar, rumble

### ISSUE THREAD

**Issue by paradise999** [Ryochan7/DS4Windows#1831]
I decided to use trigger effect and two stage mode. I saw that in addition to assigning a key, you can assign a change in the lightbar and rumble when you press the selected button. Well. When trigger is fully pressed, I set a white and red light (left - right) and a light and heavy rumble. After I fully pressed trigger, rumble turned on and does not turn off until I start and turn off test. The lightbar also doesn't return to the default setting. At the same time, on other keys, the lightbar only works on the last assigned key, and after that, on trigger lightbar doesn't turn on either. Is this a bug or have I not configured something?

Edit: Not last assigned key. Its absolutly randomly. I can't find moment, when its stop apply changes. I managed to catch two triggers with the lightbar, then the new keys stopped using the Extra settings

**Comment by Ryochan7** [comment]
Sometimes I really don't like the mapping system. The processing of virtual buttons was causing the issue. With most controls, the binding routine is run no matter if a button is active or not. Two State triggers tries to find the currently active button and then only process that action. That worked fine for output bindings but not for Extras changes.

Now the previous state is taken into account and previously activated virtual buttons are processed accordingly. This same issue would have impacted the Gyro Directional Swipe action buttons as well.

**Comment by Ryochan7** [comment]
Fixed in version 2.2.7
