### ISSUE TITLE
Switch pro gyro output not completely accurate

### ISSUE THREAD

**Issue by CrusadingNinja** [Ryochan7/DS4Windows#1832]
Hello, I have come to believe that the switch pro gyro output is not completely accurate. 

As an example, in Dolphin I am trying to use gyro as an emulated wii remote pointer. However, sometimes dolphin picks up this input as inverted and my pointer is rendered upsidedown. I do not believe this is a Dolphin or a controller issue because I could not replicate this in BetterJoy.

![maddenupsidedown](https://user-images.githubusercontent.com/77567969/106658899-89066f00-6563-11eb-9835-0b33817eb4d2.PNG)

Likewise, in Super Mario Odyssey on Yuzu, many motion inputs do not produce the intended output. For example, gyro pitch up and down are supposed to produce different outputs; however, on the switch pro these both incorrectly produce the same output. I also tested with my DS4 and the gyro inputs on that work as intended, so it is not an issue with the emulator. 

Thank you for the hard work on this amazing piece of software and hopefully this can get fixed!

Tested on:
 - Official Nintendo Switch Pro Controller 
 - Windows 10 Pro 1909
 - DS4Windows 2.23

**Comment by Ryochan7** [comment]
Fixed in version 2.2.7

**Comment by CrusadingNinja** [comment]
Can confirmed fixed with 2.2.7, thanks for the great work!
