### ISSUE TITLE
Not working on ps5 controller

### ISSUE THREAD

**Issue by MoistLightning** [Ryochan7/DS4Windows#1833]
The new version of ds4 2.2.3 is not working on my ps5 controller. The light shows but the buttons and joysticks and triggers don't work. I've tried it on multiple games and still have the same problem.

**Comment by justduy** [comment]
Same with me, the latest update have just stopped working with my dualsense

**Comment by simplehelpingduck** [comment]
Have you tried going to selected profile then pressing default it worked on my ps5 controller

**Comment by Ryochan7** [comment]
Been using my DualSense for the past few days. No problems here

**Comment by rjmxtechnology** [comment]
Dualsense is no longer working for me as well after the 2.2.3 update, I reverted to 2.2.2 and disabled automatically checking for updates in the meantime

**Comment by Animus120** [comment]
I've been using DualSense on 2.2.3 the whole day without noticing any issue.
As for the white light under the touchpad not lit up, isn't it because everyone complained about the implementation not being like its real PS5 counterpart?

**Comment by rjmxtechnology** [comment]
Well at least having the light as an option would seem like a nice feature
in my opinion. I'll have to try 2.2.4 out though and see if my dualsense is
working as it should with this release.

Best Regards,


Rjmx

**Comment by rjmxtechnology** [comment]
> I've been using DualSense on 2.2.3 the whole day without noticing any issue.
> As for the white light under the touchpad not lit up, isn't it because everyone complained about the implementation not being like its real PS5 counterpart?

At least having the light under the touchpad as an option would be a nice feature in my opinion. 
I will test 2.2.4 release when I get a chance and see if my dualsense works better with that version and report back. 

Also, just a theory but do any of the people that had issues with dualsense also have scptoolkit installed? (I have it personally)
