### ISSUE TITLE
DualSense Double Input

### ISSUE THREAD

**Issue by hypeFLOW** [Ryochan7/DS4Windows#1835]
Trying to play Assassin's Creed Odyssey while emulating the DS4 with the DualSense. It seems to be recognize the controller and mouse and keyboard as well, thus unable to use the controller. I tried it with Immortals Fenyx Rising Demo and it emulates DS4 just fine. Emulating the Xbox controller works fine. Seems to be a game issue. Was working fine with DS4 previously.

**Comment by Ryochan7** [comment]
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

**Comment by hypeFLOW** [comment]
Tested other games and works fine. Must be an issue with the game itself and DualSense.

**Comment by hypeFLOW** [comment]
Did some testing and it seems to work fine over bluetooth, just not via USB.

**Comment by rjmxtechnology** [comment]
> https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

@Ryochan7 

It appears that the "hide ds4 controller" option seems to fix the issue on DS4Windows versions after 2.2.2 however (specifically tested 2.2.4), the program prompts me for administrator privileges via UAC in this instance. 

It's odd that this is the case now when it worked without the "hide ds4 controller" option being enabled and thus without administrator privileges on 2.2.2. There must be something causing this. It is very odd that after version 2.2.2 (2.2.3 and up) it has the problems mentioned above and in the other issue that was closed  in which I linked to this one.

I am definitely not crazy as I know this is happening to me, and by the amount of others complaining about dualsense in the github issues I take it I am not the only one.  Hopefully this can get sorted :)

**Comment by Ryochan7** [comment]
It works fine for me. You need to come up with a case where it doesn't if you want my help.

My first guess is maybe ViGEmBus skipped an input slot. You can check that with XInputChecker (link to run it is in the Settings tab). If that is the case, you are probably using ViGEmBus 1.16.116 which I don't support anymore. If you are running Windows 7 then you are unfortunately stuck with that version of the driver thanks to Microsoft and are on your own.

**Comment by Ryochan7** [comment]
Latest ViGEm

https://github.com/ViGEm/ViGEmBus/releases/tag/setup-v1.17.333

**Comment by rjmxtechnology** [comment]
> It works fine for me. You need to come up with a case where it doesn't if you want my help.
> 
> My first guess is maybe ViGEmBus skipped an input slot. You can check that with XInputChecker (link to run it is in the Settings tab). If that is the case, you are probably using ViGEmBus 1.16.116 which I don't support anymore. If you are running Windows 7 then you are unfortunately stuck with that version of the driver thanks to Microsoft and are on your own.



> Latest ViGEmBus
> 
> https://github.com/ViGEm/ViGEmBus/releases/tag/setup-v1.17.333

Going to try updating VIGEm now with the latest build of ds4windows, I will report back with the result
