### ISSUE TITLE
Finer Axis Config values?

### ISSUE THREAD

**Issue by DoinksJR** [Ryochan7/DS4Windows#1836]
[Enhancement]

![Finer Values](https://user-images.githubusercontent.com/75626760/106708626-30fe5580-65c1-11eb-8264-ee6a30156909.PNG)

Could you possibly add finer and negative values to the axis configs ? i want to be able to test different sens in values like " -1.40 " or -"000000.14" this would be a big help thanks!

**Comment by DoinksJR** [comment]
> [Enhancement]
> 
> ![Finer Values](https://user-images.githubusercontent.com/75626760/106708626-30fe5580-65c1-11eb-8264-ee6a30156909.PNG)
> 
> Could you possibly add finer and negative values to the axis configs ? i want to be able to test different sens in values like " -1.40 " or -"000000.14" this would be a big help thanks!

**Comment by Ryochan7** [comment]
A DS4 stick only has a full range of [0-255] with the Negative direction accounting for 128 units. Using more than two decimal places is pretty much pointless as the output value will get cut off to an Integer when converting back to a DS4 stick axis direction.
