### ISSUE TITLE
DualSense battery draining?

### ISSUE THREAD

**Issue by Lusidus** [Ryochan7/DS4Windows#1837]
I don't know if this is an issue with DS4Windows or my controller, but has anyone else had this issue on PC? controller can be fully charged, connect it through bluetooth and use it for an amount of time and then either inputting PS+start to disconnect or clicking stop in DS4W and it's as if my controller isn't actually shutting off? even though the light goes off and stays off, the next time I go to use it the battery is either completely drained or at like 12%..

**Comment by Ryochan7** [comment]
I have experienced that beforehand. Not sure what causes it so unfortunately there isn't much to do about it.

**Comment by Anuskuss** [comment]
@Ryochan7 Disconnect and reconnect until you can repro and then send some packets to the controller and see how it reacts?

**Comment by Lusidus** [comment]
> 
> 
> I have experienced that beforehand. Not sure what causes it so unfortunately there isn't much to do about it.

update: in the last two days i've been testing disconnecting the controller by only holding the playstation button for a few seconds instead of using PS+start to disconnect bluetooth from DS4W and it hasn't drained again since so far.. could it be that the DS4W driver isn't properly shutting the controller off with the PS+start method? (I also own a DS4 and don't remember having this issue using the same method to disconnect it from bluetooth, so if it is the issue here, it would seem to be tied to the dualsense support and not the entire software)

**Comment by Anuskuss** [comment]
Don't know if it's related to this, but sometimes when I reconnect my DS5 the light doesn't even turn on (but it's definitely connected). I don't remember that happening in older versions but I guess I'll try force shutting it down for the time being.

**Comment by pablo5425** [comment]
try changing that macro. for example, i set it to PS + triangle, like steam default config
and it works perfectly for me
