### ISSUE TITLE
Dual Sense Rumble doesn’t work in RocketLeague

### ISSUE THREAD

**Issue by Luc1412** [Ryochan7/DS4Windows#1838]
**Describe the bug**
The rumble feature of a BT connected Dual Sense Controller doesn't work in RocketLeague

**To Reproduce**
1. Get a Dual Sense Controller and connect it to your PC
2. Start Rocket League (free to play in EGS)
3. When joining the game you already notice that it doesn't vibrate during the Countdown 

**Expected behavior**
The Controller provided haptic feedback

**Screenshots**
None

**Desktop:**
 - Controller Make and Model: Sony DS5 (CFI-ZCT1W)
 - OS: [Windows 10 Build 20H2]
 - DS4Windows Version [2.2.4]

**Additional context**
None

**Comment by Ryochan7** [comment]
Assuming you are emulating a DS4. Rocket League uses DirectInput when interfacing with a DS4 and does not support force feedback in DirectInput mode. Rumble only works in the game when using a controller through XInput. If you want rumble, you have to emulate an Xbox 360 controller when playing Rocket League.
