### ISSUE TITLE
Need for input latency using a bluetooth dongle

### ISSUE THREAD

**Issue by djanthony93** [Ryochan7/DS4Windows#184]
I have some serious input latency over 10ms using a CSR bluetooth dongle. I've already set my system in performance mode and disabled every kind of battery saver in device manager but my ds4 still got lag. Is there a way to fix this? I'm using Windows 10 Pro FCU 64-bit and the latest DS4W release

**Comment by Ryochan7** [comment]
I saw a duplicate issue on the Jays2Kings repository. Are you still using the last Jays2Kings build (1.4.52) or the most recent build from here (currently 1.4.108)?

**Comment by djanthony93** [comment]
I've tried both version, same issue. I replaced my CSR dongle with a brand new Broadcom (EDR) one, will do some testing hereafter.

**Comment by TristanYoung** [comment]
CSR based bluetooth dongles were not recommended.  I was using one, but switched when Windows 10 insider preview decided it wasn't going to behave with CSR models.  Microsoft later fixed the issue, so I keep it around purely for testing.

**Comment by Ryochan7** [comment]
My current Bluetooth dongle uses a CSR chip and it has worked pretty well for me.

https://www.newegg.com/Product/Product.aspx?Item=N82E16833166126
