### ISSUE TITLE
DualSense lightbar stays off when the controller is restarted (turning the pad off and on)

### ISSUE THREAD

**Issue by Feranthur** [Ryochan7/DS4Windows#1841]
On version 2.2.4 (and possibly 2.2.3), the dualsense controller lightbar turns off when i restart it. Meaning, at first boot it all works fine, but when i turn the gamepad off (with PS+start) then turn it back on again in the same session the lightbar turns off after connecting to bluetooth (everything else seems to continue to work fine, however).

**Comment by giuseppe3349** [comment]
it does so to me too

**Comment by TheMasterDingo** [comment]
i have encountered this problem also, closing and opening ds4win fixes it

**Comment by h1riz** [comment]
i have this problem too, i need to restart my controller again and restart ds4win tu fix it

**Comment by pablobolanos01** [comment]
the problem is even worse when an output is set as permanent
multiplayer lights always work if its dynamic, but being permanent makes both lightbar and multiplayer lights turn off

**Comment by pablo5425** [comment]
the problem is even worse when an output is set as permanent
multiplayer lights always work if its dynamic, but being permanent makes both lightbar and multiplayer lights turn off

**Comment by Ryochan7** [comment]
This was fixed in version 2.2.6. Different reset flags are used when disconnecting from the DualSense now.
