### ISSUE TITLE
DSWindows changing Windows mouse options

### ISSUE THREAD

**Issue by derrickb** [Ryochan7/DS4Windows#1842]
Hello, I've just started using DSWindows with version 2.2.2, now on latest 2.2.4

Something I've noticed is that when using DSWindows my normal mouse movement changes drastically. Checking the mouse options from control panel shows that the speed has been changed and precision turned on (I always have it off).

Is this intended functionality? Is there a way to disable this? I do not have anything set to Mouse mode in my profile, and no buttons are bound to mouse actions.

**Comment by Ryochan7** [comment]
It must be some other program on your system. DS4Windows does not edit the Windows mouse settings at all.
