### ISSUE TITLE
Nacon Revolution Controller 2 audio Jack issue

### ISSUE THREAD

**Issue by Frascaccia** [Ryochan7/DS4Windows#1844]
Hello and Thank you for your support,
Recently i've been using this controller with my PS4 and of course the audio jack was working.
Then i switched to PC , if i connect the PS4 controller on PC the audio jack is working but if i use the Nacon controller the audio is not working. (both controllers use USB cable)
When the Nacon is plugged in the audio output that can be set from windows is not the same when DS controller is plugged in. If i set the nacon audio output ( only avaliable) i can hear sounds only when adjusting windows volume, otherwise no.
Thank you again

**Comment by Ryochan7** [comment]
That functionality has to be added on a per controller basis. Right now, audio support is only possible through official Sony controllers. With the DS4, the output report has to include the desired audio level. For Sony DS4 controllers, there are checks to find an applicable audio monitor in Windows for the device and then monitor changes in the set audio level on the device. If no Windows audio device is detected for a device then the audio level will be set to 0 and effectively muted. Setting the audio level in Windows after opening the HID device will only work until the first rumble or lightbar change occurs and then it will get muted again.

**Comment by Ryochan7** [comment]
Hopefully version 2.2.5 can grab the audio volume from the audio device. I have no means to test it but it should work so long as the device is detected within Windows.
