### ISSUE TITLE
Program error with >1 DS4 dongle

### ISSUE THREAD

**Issue by etgrieco** [Ryochan7/DS4Windows#1849]
**Describe the bug**
When 2 DualShock4 dongles are connected to the PC and neither controller is connected to its dongle, the program fails to launch. This is likely due to duplicate, non-unique addresses for each individual dongle (i.e. `00:00:00:00:00:00`).

**To Reproduce**
1. Connect 2 DualShock 4 dongles to PC
1. Ensure neither controller is connected to its dongle (can be paired)
1. Program fails to launch with error `An item with the same key has already been added.`

**Expected behavior**

Expected behavior that DS4Windows can support multiple non-connected DS4 dongles.

**Screenshots**
When neither controller connected.
![image](https://user-images.githubusercontent.com/22364063/107129131-2d085700-6891-11eb-8044-9cd5453945e3.png)

When one controller connected
![image](https://user-images.githubusercontent.com/22364063/107129146-44dfdb00-6891-11eb-8779-daae1bf61c5f.png)

**Hardware:**
- DS4Windows version 2.2.4
- Windows 10 Home (x64, release 2009)
- Controller: DS4 CUH-ZCT2U
- Dongle: CUH-ZWA1U

**Additional context**
potentially related issue:
https://github.com/Ryochan7/DS4Windows/issues/1840
logs:
```
02/05/2021 18:23:15: DS4Windows version 2.2.4
02/05/2021 18:23:15: DS4Windows Assembly Architecture: x64
02/05/2021 18:23:15: OS Version: Microsoft Windows NT 10.0.19042.0
02/05/2021 18:23:15: OS Product Name: Windows 10 Home
02/05/2021 18:23:15: OS Release ID: 2009
02/05/2021 18:23:15: System Architecture: x64
02/05/2021 18:23:15: Running as User
02/05/2021 18:23:16: Starting...
02/05/2021 18:23:16: Connection to ViGEmBus 1.16.112.0 established
02/05/2021 18:23:16: Searching for controllers...
02/05/2021 18:23:16: Using Shared Mode
02/05/2021 18:23:17: An item with the same key has already been added.
```

**Comment by Ryochan7** [comment]
That would present a problem. Unfortunately, not blanking the serial number would mess up connecting the controller again via normal BT or USB. I can only see resolving this by forcing the use of a fake serial using the device instance path. Of course, the problem with using fake serials is that it is tied to the USB port you have a device plugged into at the time.

**Comment by C3S4RM3W** [comment]
I have experienced the same issue for quite some time, I just moved on with only having one connected at all the time and use my other 3 controllers with Bluetooth. 
I guess other possible solution ideas can be:
1- Allow duplicated address for Dongles* 
2- Add a proxy variable for more than one Dongle (1) (2) (3) and so on**

* The same way that it detects and tells you that you have a V1 or V2 or dongle connected, you can make a variable that if there is more than 1 Sony WA address can be duplicated.

* * If there is more than 1 Sony WA, any consecutive Sony Wa will have the last digit of it's Address change for the corresponding order of detection (i.e: for the first one 00:00:00:00:00:00, second one 00:00:00:00:00:01, third one 00:00:00:00:00:02 and so on)

**Comment by etgrieco** [comment]
Latest release fixes this issue. Thanks so much! Closing issue.
