### ISSUE TITLE
touchpad keeps repeatedly clicking when used as mouse after update

### ISSUE THREAD

**Issue by bladet5433** [Ryochan7/DS4Windows#185]
i have not updated i long time but after updating to latest today, using the touchpad as mouse no longer working correctly. before update holding down touchpad would work the same as a mouse as your holding the left button, but now it when i hold down touchpad it repeatedly clicks the button. tried all the settings on touchpad it does nothing to help. windows 7 64bit thanks for any help

**Comment by Ryochan7** [comment]
It took a little while to figure this out but I found the culprit. Commit https://github.com/Ryochan7/DS4Windows/commit/e6bab70de2e74daf491597de499220866f997eac caused the problem. DS4Windows had been changed to avoid running the Mouse::synthesizeMouseButtons method for the touchpad unchanged case. However, DS4Windows resets the mouse button count per poll and needs it to be recalculated each poll. That would cause the left mouse button to be released quickly. It should also be mentioned that this is only a problem if the touchpad button bindings are left at default.

I guess the main part of that commit will have to be reverted. For now, you can manually assign mouse button actions to the touchpad to avoid the issue.
