### ISSUE TITLE
DS4Windows 2.2.4 x86 downloads x64 Vigembus

### ISSUE THREAD

**Issue by Danlezama96** [Ryochan7/DS4Windows#1852]
Using the x86 version of DS4Windows 2.2.4 downloads the x64 bits version of the Vigembus driver, this prevents x86 versions of windows from installing the driver so the software becomes useless on  x86 legacy platforms even though x86 versions of Vigembus exist.

Could you please make the x86 version of DS4WIN download the x86 version of vigembus?

**Comment by Ryochan7** [comment]
Didn't take the different method of setup files into account with the latest ViGEm installer(s); the old setup took care of both architectures. Thanks for pointing out this oversight. The issue has been corrected.
