### ISSUE TITLE
DS4Windows Does Not Start Hidden

### ISSUE THREAD

**Issue by SirWobbyTheFirst** [Ryochan7/DS4Windows#1853]
**Describe the bug**
The old DS4Windows used to start up hidden when the hide when minimised option was enabled and the -M parameter specified on the command line. New DS4Windows does not do this and instead opens the window minimised and shown in the taskbar as opposed to showing as an icon. If the window is restored and then minimised the normal way, the application then hides to the system tray.

**To Reproduce**
Steps to reproduce the behaviour:
1. Startup DS4Windows with the -m parameter.
2. Observe the window appears in the taskbar as a button.
3. Click the button and the window restores.
4. Click minimise and the window hides and is shown in the system tray as it should be.

**Expected behaviour**

The application should display no UI when the -M parameter is specified and should only display the system tray icon.

**Screenshots**

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DualShock 4
 - OS: Windows 10 Enterprise 20H2
 - DS4Windows Version: 2.2.4.0

**Additional context**

Application is started as a Task Scheduler job to avoid the issue of being unable to interact with administrator level applications, this has been a staple on the old DS4Windows for the past two years.

**Comment by Ryochan7** [comment]
Tried multiple different scenarios and it works fine for me. Also, note that the command line option is case sensitive. `-M` will not work on the command line. It has to be passed as `-m`. Double checked and that was the case with Jays2Kings as well. `-M` was never valid.

**Comment by SirWobbyTheFirst** [comment]
It is set as -m, using title case is just force of habit and I can recreate it regardless. I even killed the APPDATA folder for DS4Windows and used a fresh configuration, it still shows in the taskbar on startup.

Here's the settings in DS4Windows:

![image](https://user-images.githubusercontent.com/47334951/107280085-c2e9e080-6a4f-11eb-91e6-9b232f758296.png)

And here's the entry in Task Scheduler:

![image](https://user-images.githubusercontent.com/47334951/107280171-e0b74580-6a4f-11eb-9240-9ac58a2c9254.png)

And here it is in the Taskbar just after starting via Task Scheduler:

![image](https://user-images.githubusercontent.com/47334951/107280247-fb89ba00-6a4f-11eb-9470-13c0817aa2da.png)
