### ISSUE TITLE
GTA V does not recognize the controller once I disconnect it.

### ISSUE THREAD

**Issue by boludoz** [Ryochan7/DS4Windows#1854]
**Describe the bug**
GTA V does not recognize the controller once I disconnect it or if I connect it in game.

**Desktop :**
 - Controller Make and Model: Sony DS4 v.2
 - OS: [e.g. Windows 10 Enterprise Build 1803]
 - DS4Windows Version [e.g. 2.2.4]

**Additional context**
I have to restart the game, this with the XBOX controller does not happen, therefore I think it is a bug.

**Comment by Ryochan7** [comment]
> I have to restart the game, this with the XBOX controller does not happen, therefore I think it is a bug.

Nope. That is the fault of DirectInput. GTA V reads the DS4 controller from its DirectInput interface and hardly any games that supports DirectInput has support for controller hotplugging. That feature is provided by the XInput API by default so it is standard that controller swapping works in most games when using Xbox 360 and other XInput controllers.

You would have to make a permanent virtual DS4 controller in the Output Slots section to avoid this problem.
