### ISSUE TITLE
Can't mute ps5 controller mic

### ISSUE THREAD

**Issue by JeremyGamezzz** [Ryochan7/DS4Windows#1857]
Hey I am so confused on the ps5 controller mic, When I try playing with people they can hear me through the ps5 mic. and I try to push the button underneath the ps5 logo to mute it but doesn't do anything?

**Comment by Ryochan7** [comment]
You need to map the "Push To Talk" or "Push To Mute" key(s) for the app you are using to the Mute button. The controller doesn't handle muting the mic on its own but it would likely be bound in the PS5 dashboard software.
