### ISSUE TITLE
Gyro Calibration button missing from most output modes

### ISSUE THREAD

**Issue by Darthagnon** [Ryochan7/DS4Windows#1859]
**Describe the bug**
The recently-added (and very useful) gyro calibration button appears under ```Profile Edit``` >> ```Gyro``` >> ```Output Mode: Controls```. 

It does not appear when ```Output Mode``` is set to anything other than Controls. 

Would it be possible for the calibration button to be added to ```Output Mode:``` Mouse, Mouse Joystick, Directional Swipe? Not sure if it applies to PassThru...

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2, PicTek HD-060/PC263
 - OS: Win10 v1709 Home
 - DS4Windows Version: 2.2.4, 2.2.5

**Additional context**
The Gyro calibration works, and fixed a gyro drift problem on one of my brother's controllers.

**Comment by Darthagnon** [comment]
Thank you so much, Ryochan7!!! ❤

**Comment by AdriandeLima** [comment]
DS4Windows v2.2.6

- Gyro calibration is missing from ```Output Mode: Mouse```
- Calibration function seems to be broken when I switch to Output Mode: Mouse? I click "Calibrate" button under one of the other modes, then switch to "Mouse"/Always On. In v2.2.4, this stopped drift. In v2.2.6, drift occurs again.
