### ISSUE TITLE
Auto Profile Macro Rumble Malfunction

### ISSUE THREAD

**Issue by shinra358** [Ryochan7/DS4Windows#186]
1. When using the auto profile system and doing a macro for a button, if you turn on rumble for that button, if one waits, eventually the rumble starts to malfunction and rumbles for no reason. Even when the program for the auto profile is off.

2. Also, if the button is held down for a bit when you have rumble to it and the program used for the auto profile system has exited, even when button is released, the rumble continues for a long time. If said rumble button is pressed quickly, then you barely feel the rumble as the program used for the auto profiler exits. I would like to ask for a fix for the inconsistency (immediately quit rumbling if program exits). Also allow for 2 secs of rumble after the program used for the auto profiler has exited so that the rumble can be felt when rumble is set to a button that closes said program.

3. while testing rumble in the keybinding section, sometimes when you wait, rumble will start happening for no reason until you turn the controller off and back on.

**Comment by Ryochan7** [comment]
Only scenario 2 has been tested and corrected. The rumble state of a controller is now reset when switching profiles. I have not been able to replicate scenario 1 or 3.
