### ISSUE TITLE
Special actions change aren't being saved

### ISSUE THREAD

**Issue by DevDorrejo** [Ryochan7/DS4Windows#1860]
**Describe the bug**
Hello, i am using the JoyCons (Happen with PS4 controll too) with DS4W, and found that the special actions arent being saved by profile, and neither the second option onwards is maintaining active.

**To Reproduce**
1. Edit a 'Profile'
2. Go To 'Special Actions'
3. Add a new 'Action'
4. Active more than 2 option.
5. save and test that all the options are working.
6. Kill DS4 or Reboot the machine.
7. Open DS4 > Edit Profile > Go to Special Options > Look that all except the first one are deactive.

**Expected behavior**
persistent on active special options

**Screenshots**
![image](https://user-images.githubusercontent.com/7697566/107562754-9b615800-6bb6-11eb-937a-ba629b80b1cf.png)

**Desktop (please complete the following information):**
 - Controller Make and Model: JoyCons 
 - OS: [e.g. Windows 10 Pro Build 2004] Win10 Home 20H2
 - DS4Windows Version [e.g. 2.1.5] 2.2.4

**Comment by Ryochan7** [comment]
Not sure how it gets that far. You cannot use duplicate names for Special Actions as that is its ID used in the file. Most of the code behind classes check for a unique name before saving but maybe the Disconnect BT special action ViewModel does not. This is something to look into but your config is wrong.

**Comment by Ryochan7** [comment]
The check does exists. The GUI displays the appropriate error and stops the save process from occurring.

**Comment by DevDorrejo** [comment]
ok, but i have 2 profile, and when i am saving the special action for one, the other profile is merge with the special action created on the first profile, so i have joycons using it like 1, the red joycon, use ps + option to turn off the bluethooth.

but i add the second special action for the blue joycon, this appear on the profile of the red too, and so they crash or something like that, and each time i have to enable the second special action for the blue joycon, because the special action arent linked per profile.

**Comment by Ryochan7** [comment]
Special Actions are saved outside of profiles and are available to use in any profile. Each profile only saves whether a Special Action is enabled while the profile is loaded; that will determine if the Special Action is checked in the list.

For JoyCon controllers, you only need to account for each individual side per profile. Don't worry about only one check box being checked in the Profile Editor. Just make sure the proper action is enabled for each JoyCon side.

**Comment by DevDorrejo** [comment]
Ok, that made it clear, thank you very much.
