### ISSUE TITLE
Recent regression

### ISSUE THREAD

**Issue by Anuskuss** [Ryochan7/DS4Windows#1861]
5b219ddc92922fb3b55abafc33d5ad7701b623f0 introduced some regressions, mainly
- Can't map physical buttons to non-gamepad keys (keyboard/mouse)
- Existing configurations (e.g. gamepad:left_touch -> mouse:left_click) don't work anymore

**Comment by Ryochan7** [comment]
At that commit, key bindings no longer saved properly. Commit 4d30c85d90ae92ab6381afb45df5750c51529dc7 fixed that issue.

I cannot reproduce the second issue on my end with older profiles.

**Comment by Anuskuss** [comment]
Try v2.2.5 with default config.

**Comment by Ryochan7** [comment]
Had to update the action check as that data will no longer be null in a valid DS4ControlSettings instance.

**Comment by Anuskuss** [comment]
Fixed, thanks!

Btw are you still disagreeing with #1247? I'm tired of having to compile DS4Windows with that patch applied for every release instead of just downloading it from GitHub :sweat_smile:
