### ISSUE TITLE
Updating from the DS4Windows app closes prematurely before update completes

### ISSUE THREAD

**Issue by docmars** [Ryochan7/DS4Windows#1862]
**Describe the bug**
- When the app finishes installing an update, its "app will close" prompt causes the update to fail prematurely because it kills the updater process too
- Reopening the app shows that it hadn't been updated to the version just _installed_

[Clicking **OK** or **Cancel** have the same effect here...]

<img src="https://user-images.githubusercontent.com/758090/107598570-6a474e80-6bdb-11eb-94d7-54075f3b33cf.png" width="320"/>

**To Reproduce**
1. Open an older version of the app (e.g. 2.2.4)
2. Go to Settings > Check for Updates
3. Install the update
4. You will see the message from the screenshot above
5. Click OK
6. The app and updater will both close
7. Relaunch the app and check the current version to see it never updated

**Expected behavior**
Relaunching the app is the updated version just installed

**Desktop (please complete the following information):**
 - Controller: Irrelevant
 - OS: Windows 10 Pro Build 20H2
 - DS4Windows Version: 2.2.4

**Additional Context**
- Note: running DS4Updater.exe by itself without DS4Windows running does update it successfully

**Comment by DoganM95** [comment]
Just had the same issue. By the way, do all your other programs run normally?
I am experiencing weird program crashes (even other applications get closed a couple seconds after i run them).

Just reinstalled my windows yesterday because of this, installed ds4windows again and the crashes are back...

**Comment by AdriandeLima** [comment]
I noticed the same behaviour, too, when I updated from v2.2.4 to v2.2.6.

Before this, it worked fine as far as I remember.

**Comment by Ryochan7** [comment]
Nothing was changed in DS4Updater in that time frame. Cannot reproduce the problem on my end. I ended up making a small change in DS4Updater that might help with the situation though.

I am going to consider this issue resolved unless told otherwise.
