### ISSUE TITLE
Auto-profile not working properly since 2.2.3.

### ISSUE THREAD

**Issue by bslenul** [Ryochan7/DS4Windows#1864]
**Describe the bug**
I have a specific profile for RetroArch tied to retroarch.exe (quick save/load bound to touchpad), it worked great up to DS4Windows 2.2.2, but since 2.2.3 I have 2 issues:

1. If RetroArch is already started and in the foreground, if I turn ON my DS4 it's listed in DS4Windows BUT it won't connect until I Alt+Tab or until RA loses focus.
2. Once connected, my touchpad binds won't work, I have to: close RA and turn OFF the DS4, turn ON the DS4 and start RA, only then it'll work properly.

It's not an issue specific to RetroArch, I tried creating a profile for Notepad++ with touchpad binds, and I have the same issues.

**To Reproduce**
1. Create a new profile.
2. Edit the new profile and set "Output Mode" in the "Touchpad" tab to "Controls".
3. Bind F key to right touch, then save.
4. Add Notepad (or any text editor) in auto-profile and select the new profile for it.
5. Start Notepad, keep it in the foreground and turn ON your DS4, the controller won't connect (but DS4Windows will list it).
6. Alt+Tab, then the controller should be connected.
7. Switch back to Notepad and press touchpad right, nothing will happen.
8. Turn OFF the DS4 and close Notepad.
9. Turn ON the DS4 and start Notepad (in that order), and now it should connect and touchpad right should send F key presses.

**Expected behavior**
DS4 should connect automatically and touchpad binds should work when using auto-profile, no matter if the program is already running and in the foreground or not.

**Screenshots**

https://user-images.githubusercontent.com/33353403/107793691-de5a3180-6d56-11eb-9ffe-77da83331809.mp4

Here you can see the DS4 being listed in DS4Windows when turned ON, but it won't actually connect until RetroArch loses focus. Watch with the sound ON and you'll hear the little Windows jingle playing only when I click the DS4Windows window.

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2E)
 - OS: Windows 10 Pro Build 20H2
 - DS4Windows Version: 2.2.6 (issue started with 2.2.3 tho)

**Comment by bslenul** [comment]
Still happening with 2.2.7, here's some logs with the auto-profile debug messages:

* With the DS4 turned ON while RetroArch is started and in the foreground (controller not connecting until I unfocus RetroArch window + profile ignoring my touchpad binds): [ds4windows_nope2.txt](https://github.com/Ryochan7/DS4Windows/files/6006972/ds4windows_nope2.txt)
* With the DS4 turned ON before launching RetroArch (working properly): [ds4windows_ok2.txt](https://github.com/Ryochan7/DS4Windows/files/6006973/ds4windows_ok2.txt)

Regular logs are exactly the same except for these 3 lines being in a different order:

* With the bug: [ds4windows_nope.txt](https://github.com/Ryochan7/DS4Windows/files/6006977/ds4windows_nope.txt)


```
2021-02-19 01:35:22.0423|INFO|Controller 1 is using Profile "Default". Battery level is 75%
2021-02-19 01:35:25.6957|INFO|Plugging in virtual X360 Controller
2021-02-19 01:35:25.6957|INFO|Associate X360 Controller for input DS4 #1
```
* Working properly: [ds4windows_ok.txt](https://github.com/Ryochan7/DS4Windows/files/6006978/ds4windows_ok.txt)
```
2021-02-19 01:36:23.7975|INFO|Plugging in virtual X360 Controller
2021-02-19 01:36:23.7975|INFO|Associate X360 Controller for input DS4 #1
2021-02-19 01:36:23.8505|INFO|Controller 1 is using Profile "Default". Battery level is 75%
```

**Comment by mika-n** [comment]
When you launch DS4Windows then does it popup as being as a foreground app? 

The message "_02/19/2021 01:55:04: DEBUG: Auto-Profile. Unknown process. Reverting to default profile. Controller 1=Default (default)_" means that DS4Windows app detected that the foreground app is not listed in autoProfile rule list. Therefore the profile is set back to the default profile. However, you can tweak this by unticking the autoProfile option "Revert to default profile on unknown". Then this option is UNTICKED then ds4windows leaves the existing profile active when it detects an unknown process.

If you want to use another profile while focus is in a desktop then you can define c:\windows\explorer.exe autoProfile rule to set a specific profile. But at the same time when you have "revert to default profile on unknown" unticked then some other app which may briefly come and go as a foreground app won't change the profile back to default one.

**Comment by bslenul** [comment]
The thing is I have no idea why it's detecting an "unknown process", I'm just switching to DS4Windows! I'm doing the EXACT same thing as the video I posted in my initial post, I'm not opening any other process in-between.

Unticking the "Revert to default profile on unknown" mada it even worse :p Now the controller never connects, it's still detected and listed in DS4Windows (I can even see the LED changing color) but I never hear the Windows jingle on connection (on disconnect either) and the controller doesn't work at all.

![image](https://user-images.githubusercontent.com/33353403/108490154-b4e35d80-72a2-11eb-98bf-aa0ae8985544.png)

Even after I close RetroArch and turn OFF my controller, if I turn it back ON it will never connect until I close and restart DS4Windows.

And again, to be clear: I use RetroArch as an example but it can happen even with anything else, and it works fine if I revert to 2.2.2.

**Comment by bslenul** [comment]
So to recap (when I say "program" I mean the one I made an auto-profile for):

* No issue up to 2.2.2.
* Auto-profile works fine if the controller is turned ON before launching the program, or if the program is in the background when you turn ON the controller.
* If controller was turned ON while the program is in the foreground then it won't connect until the program isn't in the foreground anymore.
* Binds from the touchpad won't work if you used the background trick to get the controller to connect, other custom binds seem to work fine.
* If "Revert to default profile on unknown" is unticked, if the controller was turned ON while the program is on the foreground, it will NEVER connect until you close and reopen DS4Windows.

**Comment by mika-n** [comment]
hmmmmm..... interesting. I will try to test the scenario you described at some point.

**Comment by bslenul** [comment]
Hopefully this will help, I was able to compile DS4Windows to bisect, looks like the 1st bad commit was 1fbdce9b64091a788db42eec2f04239ec509a955

**Comment by Ryochan7** [comment]
Tested it on my end and it is working as intended. Virtual controllers (X360 and DS4) are plugging and unplugging as intended. This honestly sounds like an experience of depending on wrong behavior. Virtual controllers could have been unplugged when a deleted profile was attempted to be loaded and the backend variables would reflect the previously loaded profile rather than being reset. Sorry for fixing the glitch?

![we_fixed_the_glitch](https://user-images.githubusercontent.com/581968/109033386-36b0fd80-768c-11eb-9c1b-63bed7b8d6e9.jpg)

**Comment by TheMasterDingo** [comment]
> Tested it on my end and it is working as intended. Virtual controllers (X360 and DS4) are plugging and unplugging as intended. This honestly sounds like an experience of depending on wrong behavior. Virtual controllers could have been unplugged when a deleted profile was attempted to be loaded and the backend variables would reflect the previously loaded profile rather than being reset. Sorry for fixing the glitch?
> 
> ![we_fixed_the_glitch](https://user-images.githubusercontent.com/581968/109033386-36b0fd80-768c-11eb-9c1b-63bed7b8d6e9.jpg)

I have the same issue, please check #1884 or the video i uploaded https://streamable.com/vqpmfu , on 2.2.2 it works. Are you sure it should work like this?
I mean if i connect the controller after the game has started it does not plug any virtual controller(you can see my logs)

**Comment by bslenul** [comment]
Video where I reproduce the steps I described in the original post, I'm even extracting DS4Windows, so it can't be a more fresh install, it shows the 2 issues (controller not connecting properly and touchpad binds not working):

https://user-images.githubusercontent.com/33353403/109074809-83322280-76f8-11eb-8ee7-be21b988a933.mp4

What's happening:

**0:00 -> 0:47:** extracting, creating a new profile, changing "Output Mode" to "Controls", binding D and F to left and right touch and setting Notepad++ for the auto-profile

**0:47 -> 1:03:** putting Notepad++ in the foreground then turning ON my controller, the DS4 is listed in DS4Windows but doesn't appear in joy.cpl), you can't see it in the video obviously but I'm pressing left and right touch, no D or F keys appearing :/

**1:03 -> 1:10:** clicking on the joy.cpl window so Notepad++ lose the focus, you can hear and see the controller finally connecting in joy.cpl, then I switch back to Notepad++, still no D and F keys appearing on touch presses

**1:10 -> 1:39:** closing Notepad++, turning OFF the controller, closing DS4Windows, starting DS4Windows, turning ON the controller (this time it appears both in DS4Windows and in joy.cpl), then starting Notepad++, and now it works fine.

**Also, important thing I forgot to show in the video but the profile actually switches properly**, it's only the touchpad binds not working, but if I bind Z and X keys to R1 and R2 for example, then Z and X will appear in Notepad++ when pressing these buttons.

I don't feel like I'm doing anything wrong, and the EXACT same steps work perfectly fine with 2.2.2, controller connects directly even if the program is in the foreground, and touchpad binds work fine.

**Comment by TheMasterDingo** [comment]
to me it does not plug the virtual controller after it switches porfile, but yeah it is the same problem

**Comment by Uiasdnmb** [comment]
Temporary profiles are affected by this as well: https://github.com/Ryochan7/DS4Windows/issues/1830

**Comment by TheMasterDingo** [comment]
Do the devs acknowledge this issue ?

**Comment by TheMasterDingo** [comment]
@Ryochan7 sorry to bother you, i see you closed this issue, but even with the latest update it does not plug a virtual controller when a game is open.
Is this an intended behaviour?

thank you

**Comment by bslenul** [comment]
Yeah I was about to ask why the issue was closed, it's still happening in 2.2.12 :(

**Comment by Ryochan7** [comment]
Because it works for me and nobody has been able to provide a scenario where it breaks on my end

**Comment by TheMasterDingo** [comment]
> Because it works for me and nobody has been able to provide a scenario where it breaks on my end

I understand that, but we are in two that have the same exact problem, are you sure you have tried to replicate it as in the videos we submitted?
If possible, can you please give it another look ?
Thank you

**Comment by bslenul** [comment]
So you don't get the issue by reproducing EXACTLY the 9 steps I described in OP or in the latest video I posted above?

And @mika-n have you tried reproducing it too? I know you guys must be busy, but it takes literally 5 minutes to test.

I mean you can check my latest video, I don't think I'm doing anything wrong and again it was working fine in 2.2.2, I was even able to pinpoint it to a specific commit, I don't know what else I can do to help you guys identify the issue.

**Comment by bslenul** [comment]
Just tried the debug version (from [here](https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems)), it's 2.2.10 but still, here's the logs:

* Working (controller connects with "auto-profiled" program in the foreground, touchpad binds working too): [ds4windows_log_working.txt](https://github.com/Ryochan7/DS4Windows/files/6172981/ds4windows_log_working.txt)
* Not working (controller connects only when the "auto-profiled" program loses focus and touchpad binds not working): [ds4windows_log_not_working.txt](https://github.com/Ryochan7/DS4Windows/files/6172984/ds4windows_log_not_working.txt)

The only difference is in these lines:
```
Plugging in virtual X360 Controller
Associate X360 Controller for input DS4 #1
Controller 1 is using Profile "Default". Battery level is 63%
```
When working it's in this order ^ So "plugging" -> "associate" -> "controller 1 using profile xxx / battery level" and without a pause between the 3 actions.

When it is not working (turning ON DS4 while the "auto-profiled" program is in the foreground) it is like this:
```
Controller 1 is using Profile "Default". Battery level is 54%
^^^ stuck here until the "auto-profiled" program loses focus
Plugging in virtual X360 Controller
Associate X360 Controller for input DS4 #1
```
So "controller 1 using profile xxx / battery level" -> pause until focus is lost -> "plugging" -> "associate" .

Just tell me if you need any other informations/testings!

**Comment by bslenul** [comment]
Well, looks like you fixed it 👍 That last commit works like a charm for me, no issue with auto-profile and foreground program anymore and touchpad binds are working again!

Thank you so much! ❤️

**Comment by TheMasterDingo** [comment]
> Well, looks like you fixed it 👍 That last commit works like a charm for me, no issue with auto-profile and foreground program anymore and touchpad binds are working again!
> 
> Thank you so much! ❤️

how did you test it?

**Comment by Ryochan7** [comment]
Hopefully I will get a hotfix release with the fix out there in the next few hours.

**Comment by Ryochan7** [comment]
Version 2.2.13 is out

https://github.com/Ryochan7/DS4Windows/releases/tag/v2.2.13

**Comment by TheMasterDingo** [comment]
Yes i updated, works fine now.
Had a little problem with the auto updater, it asked to replace the updater exe and sent me to a 404 link so i updated manually.

**Comment by Ryochan7** [comment]
Crap. Forgot to create a DS4Updater release on GitHub. I always forget something.

**Comment by Ryochan7** [comment]
Got the updater issue fixed

**Comment by IceLancerSR** [comment]
> Got the updater issue fixed

Are you sure auto profile switch is working? I tried all versions since 2.2.13 up to v 3.01 and i can't get it to switch

This is my log:

`04/06/2021 14:44:26: DS4Windows version 2.2.13
04/06/2021 14:44:26: DS4Windows Assembly Architecture: x64
04/06/2021 14:44:26: OS Version: Microsoft Windows NT 10.0.19043.0
04/06/2021 14:44:26: OS Product Name: Windows 10 Pro
04/06/2021 14:44:26: OS Release ID: 2009
04/06/2021 14:44:26: System Architecture: x64
04/06/2021 14:44:26: Running as Admin
04/06/2021 14:44:26: HidGuardian in use. Launching HidGuardHelper.
04/06/2021 14:44:27: Starting...
04/06/2021 14:44:27: Connection to ViGEmBus 1.17.333.0 established
04/06/2021 14:44:27: Searching for controllers...
04/06/2021 14:44:27: Using Exclusive Mode
04/06/2021 14:44:27: UDP server listening on address 127.0.0.1 port 26760
04/06/2021 14:44:43: The gamepad DS4 v.2 (BT) uses custom feature set (MonitorAudio)
04/06/2021 14:44:43: Found Controller: F4:93:9F:94:A0:51 (BT) (DS4 v.2)
04/06/2021 14:44:43: Plugging in virtual X360 Controller
04/06/2021 14:44:43: Associate X360 Controller for input DS4 #1
04/06/2021 14:44:44: Controller 1 is using Profile "Default". Battery level is 75%
04/06/2021 14:46:21: DEBUG: Auto-Profile. PID=5428  Path=c:\windows\explorer.exe | WND=131342  Title=program manager
04/06/2021 14:46:23: DEBUG: Auto-Profile. PID=5948  Path=e:\igre\retropie\emulationmix\roms\pc games\rise of the tomb raider\rottr.exe | WND=1314618  Title=rise of the tomb raider v1.0 build 767.2_64
04/06/2021 14:46:37: DEBUG: Auto-Profile. PID=6988  Path=c:\windows\systemapps\microsoft.windows.search_cw5n1h2txyewy\searchapp.exe | WND=65968  Title=search
04/06/2021 14:46:39: DEBUG: Auto-Profile. PID=9180  Path=d:\igre\ds4windows_2.1.4_x64\ds4windows.exe | WND=2100584  Title=ds4windows
04/06/2021 14:46:59: DEBUG: Auto-Profile. PID=9180  Path=d:\igre\ds4windows_2.1.4_x64\ds4windows.exe | WND=790234  Title=select export file
`
