### ISSUE TITLE
DS4 cant start with "Exclusive mode" HELP / BUG

### ISSUE THREAD

**Issue by JayTheLordOfTheFishes** [Ryochan7/DS4Windows#1866]
**Describe the bug**

**To Reproduce**

When the program doesnt as FIRST Programm the access is "Shared"
[Screenshot](https://i.imgur.com/CyuDyhr.png)

**Expected behavior**
Where the X is should be a "check mark" saying EXCLUSIVE access.
Then the controllers work.

**Screenshots**

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - Razer Raiju 2019 ULTIATE Edition
 - OS: [e.g. Windows 10 Pro
 - DS4Windows Version Latest

**Additional context**
When the access is "shared" one controller has 2 Controllers, and the R2 button is suddenly the R3 this happens only in shared mode. 

The Programm needs to start first, before steam, Nvidia etc.
The problem is i cant, NVIDIA has a autostart unavoidble. The NVIDIA Container Process starts always.

Is there an Option too 100% start DS4 AS FIRST Programm before NVDIA etc.?

I tried
- .bat file that starts DS4 as admin at launch (too late start)
- The DS4.exe autostart in the program (too late at start)
- Adding DS4 with the "Task scheduler" (didnt launch at all)

**[HERE IS THE LOG.TXT](https://pastebin.com/PaLAMgPD)**

**Comment by JayTheLordOfTheFishes** [comment]
*push*

**Comment by Ryochan7** [comment]
Pull

![pull_curly_stooges](https://user-images.githubusercontent.com/581968/107863158-7b7c9f00-6e17-11eb-974d-c204472c6837.gif)

**Comment by Ryochan7** [comment]
A bit outdated but still relevant thread.

[Notice] "Hide DS4 Controller" option Removed
https://github.com/Ryochan7/DS4Windows/issues/1520

**Comment by JayTheLordOfTheFishes** [comment]
> 
> 
> A bit outdated but still relevant thread.
> 
> [Notice] "Hide DS4 Controller" option Removed
> #1520
> 
> Also,
> https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

Thanks for the answer!
