### ISSUE TITLE
[Question] Exclusive Mode Types

### ISSUE THREAD

**Issue by Chrisnetika** [Ryochan7/DS4Windows#1869]
Just got a Dualsense controller yesterday seeing that it is supported on DS4 (name change to DS5Windows soon? :P)
I got it setup (I think) with hidguardian, still using hide ds4 controller option tho not sure if it is really being used still/working as designed.I connected both my old ds4 controller and new ds5 controller at the same time via bluetooth and notice under exclusive mode they have different icons.Not sure if the check is better or the key? Can anyone shed some light on this?
Version 2.2.1 (bc of the lag/freeze issue on ds4)
![Screenshot 2021-02-13 072514](https://user-images.githubusercontent.com/1711756/107850033-70048600-6dcd-11eb-82cd-3aece03d4dcb.png)

**Comment by Chrisnetika** [comment]
When both connected via wire they both have the key thingie
![Uploading Screenshot 2021-02-13 073424.png…]()

**Comment by Ryochan7** [comment]
The checkmark shows that Exclusive access was achieved from the CreateFile system call. The key icon shows that the device Hardware ID is covered by HidGuardian and should only be accessible by apps that use HidGuardian. By default, the device is still opened with Shared access when using HidGuardian unless you also have **Hide DS4 Controller** enabled. There are some cases where you might want multiple apps to have access to an HidGuardian blocked input device at the same time; one example that pops up in my head is DS4Windows and OBS for using a Browser source to display a gamepad overlay.

In your case, the DS4 connected via BT is not listed in the HidGuardian Affected Devices list. BT Hardware IDs are slightly different than the USB connected Hardware ID. Using a more generic Hardware ID would be possible to have one entry cover both devices but I think the next layer down would be an entry based on VID only; that would case HidGuardian to block many more Sony devices than possibly just gamepads.

Also, there is a basic tooltip that pops up if you mouse hover the icon in the list.

**Comment by Chrisnetika** [comment]
In other words hidguardian is working correctly for both on wired but only working on ds4 in bt?

**Comment by Chrisnetika** [comment]
ok now I got it all configured properly with hidguardian
![Screenshot 2021-02-13 182516](https://user-images.githubusercontent.com/1711756/107864294-e387b100-6e28-11eb-9c86-9243c4a59daf.png)
Had the wrong Device ID selected

**Comment by Chrisnetika** [comment]
essentially I can turn off hide ds4 now right?

**Comment by kalamalka** [comment]
Can you guide me through how you were able to tinker with things using hidguardian and what version you are using?

Thanks!
