### ISSUE TITLE
Gyro Calibration Special Action not working 

### ISSUE THREAD

**Issue by valentyn-l** [Ryochan7/DS4Windows#1870]
The Gyro Calibration is not working when assigning a Special Action button to it. I

For example, I have tried assigning the R2 Full Pull button to be held for 1 second to trigger the Gyro Calibration, but this does nothing. 

Also, whenever I try to edit the action, it crashes DS4Windows and I must re-open it. It also lists it as Multi-Action Button instead of the intended "Calibration of Sixaxis Wheel Calibration."

I'm using the Gyro through passthru mode on a DualSense controller. 

<img width="732" alt="2021-02-13" src="https://user-images.githubusercontent.com/60371520/107851411-f474fa00-6e09-11eb-86ba-8be2a78cc707.png">

**Comment by Ryochan7** [comment]
Confirmed

**Comment by Ryochan7** [comment]
Fixed in version 2.2.7
