### ISSUE TITLE
[Question] Is possible to a software detect programatically what type of device is connected via DS4W?

### ISSUE THREAD

**Issue by vico93** [Ryochan7/DS4Windows#1871]
If it is a DualShock 4, DualSense, JoyCon or SwitchPro?

I'm asking because i'm requesting in GTA:RE (reverse enginereed engine alternative for GTA III/VC) repo [for support for DS4Windows](https://github.com/GTAmodding/re3/issues/1041) (change button icons, maybe support for gyro, etc).

Thanks for all information!

**Comment by mika-n** [comment]
There are cmdline interface to tell if the virtual output controller is in DS4 or XBox360 mode, but it doesn't tell the type of source (physical) gamepad.
https://github.com/Ryochan7/DS4Windows/wiki/Command-line-options

But there are options to find out DeviceVIDPID, DevicePath and DisplayName properties of the physical gamepad. Maybe you can workout something through those options?
`DS4WindowsCmd.exe -command Query.1.DeviceVidPid`

https://github.com/mika-n/DS4WindowsCmd/blob/master/ExampleScript.bat

**Comment by vico93** [comment]
Interesting. Unfortunately the dev of RE project doesnt want to integrate DS4W to the project (to use the versatibility of add support to four different type of controller at once), instead they want to "add DualShock 4 auto-detection the way it is done in modern games without need to emulate it as 360 pad". It's a shame because in my honest opinion reinventing the wheel for a single device is just add more complexity to the project.

BTW thanks for the info, i will close the issue but will take it in consideration if i get stumbled in a similar subject.
