### ISSUE TITLE
[Bug] Cancelling a new profile causes crash

### ISSUE THREAD

**Issue by TzakShrike** [Ryochan7/DS4Windows#1872]
**Bug Description**
DS4Windows crashes to desktop silently after cancelling out of making a new profile

**To Reproduce**
From the "Profiles" tab:
Click "New"
Choose anything you like and adjust any settings you want to
Without clicking "Save", click "Cancel".

**Expected behavior**
Return to profiles tab without creating a new profile

**Desktop (please complete the following information):**
 - Controller Make and Model: None or any
 - OS: Windows 10 Pro 64 Build 2004
 - DS4Windows Version 2.2.6

**Additional context**
I was running as Administrator while testing this, although I'm reasonably sure I remember this happening while running as Task as well. I didn't test running as standard user.

**Comment by Ryochan7** [comment]
Needed to elaborate that the crash happens when starting a New Profile from the Profiles tab. The same routine from the Controller listing works fine.

**Comment by Angelblack35** [comment]
У меня dual Sense подключается но ни одна кнопка работает

**Comment by Ryochan7** [comment]
Fixed in version 2.2.7
