### ISSUE TITLE
Data Write Connection Issue

### ISSUE THREAD

**Issue by shinra358** [Ryochan7/DS4Windows#1876]
[bug.txt](https://github.com/Ryochan7/DS4Windows/files/5988909/bug.txt)
So I had my controller on, it was working in retroarch. Movements were fine. Joy.cpl was fine. Then I noticed I needed to recharge. So I plugged in a cord to the controller that was connected to my pc (I think it has a short in it) and this happened. controller was on bluetooth before I plugged it in. The controller ceased to work until I pressed stop and then start. Joy.cpl showed 2 microsoft controllers and one generic controller in the joy.cpl during this time.

**Comment by mika-n** [comment]
know issue with some gamepad. If you need to charge the gamepad while the pad is connected over BT then try using wall plug instead of hotplugging the gamepad to PC
