### ISSUE TITLE
All profiles are reseting sometimes

### ISSUE THREAD

**Issue by GeraltV47** [Ryochan7/DS4Windows#1879]
**Describe the bug**
When i start windows, sometimes 2 controllers are being registered instead of 1(i got only1) and sometimes all profiles are being reset to default, i mean all profiles are becoming the same, deadzone is set to 0 etc.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2E)
 - OS: [e.g. Windows 10 Pro Build 2004]
 - DS4Windows Version [e.g. 2.2.2]

**Additional context**

**Comment by Ryochan7** [comment]
From version 2.2.3 Changelog text:

> Fixed issue with missingSettings being set for fallback value lookup on Profile load. Constantly re-saved profiles

Why not update?
