### ISSUE TITLE
Ps5 controller crashes pc. 

### ISSUE THREAD

**Issue by Xeroxman** [Ryochan7/DS4Windows#1881]
Hi all I can't find anyone experiencing the same so here goes. I wanted to upgrade to using a ps5 controller on my pc already using ds4 for my ps4 controller. Now the ps5 controller works fine with steam but if I need to use ds4 for games not in steam.  I open ds4 plug in the controller. And get hit with blue screen of death.  With an error message along the lines of irql_not less or equal. Any ideas what I can do to stop this?

**Comment by Xeroxman** [comment]
Sorry I should add, the pc is 2 months old, and up to date. Also running latest version of ds4

**Comment by Ryochan7** [comment]
Going to assume you were running into ViGEm issues. Not sure if you would have better luck with version 2.2.7 and the fixed ViGEm libraries. I have been using my DualSense to play Metal Gear Rising: Revengeance and it works fine for me.

**Comment by Xeroxman** [comment]
That may help, as the issue only seemed to start happening after updating to version 2.2.6

**Comment by pyromancer5** [comment]
same happened to me and i solve it...1 dont use steam beta...2 uncheck the box for xbox future controller in big picture trust its happening because of that shity thing in steam remove that xbox driver by unchecking the second box for xbox controller and u will be fine

**Comment by Xeroxman** [comment]
Ok updated to 2.2.7 which has stopped the blue screen of deat thank you. I now however can't get it to recognise the controller, and when it does i try using it in a game and nothing happens (even though it shows up in ds4). Maybe I have a dodgy controller. But thanks so much for your help so far

**Comment by Mr-Korben-Dallas** [comment]
I have memory (64gb) leak (and it crash my window), with - steam+ps5 controller+DS4_2.2.7

**Comment by mika-n** [comment]
> I have memory (64gb) leak (and it crash my window), with - steam+ps5 controller+DS4_2.2.7

Logfiles? See %APPDATA%\ds4windows\logs folder and the latest file there. Any errors there?

How did you monitored the memory leak? DS4Windows app is created using c#/.NetFramework and those have their own memory management. If there is enough free RAM then .NETFramework may keep stuff in a cache until the app is closed, so "big memory usage" is perfectly normal (why leave memory unused if it is available? .NET does garbage collecting automatically when some other app requests memory and cache needs a cleanup).

But, ViGem device driver is in C++ and there it is easier to create memory leaks, but if there would be a serious memory leak then I guess it would have been noticed long time ago.

Make sure you have the latest 1.17.333 ViGem driver installed
https://github.com/ViGEm/ViGEmBus/releases

**Comment by mika-n** [comment]
> Ok updated to 2.2.7 which has stopped the blue screen of deat thank you. I now however can't get it to recognise the controller, and when it does i try using it in a game and nothing happens (even though it shows up in ds4). Maybe I have a dodgy controller. But thanks so much for your help so far

See "Read this before posting a new issue ticket". You should provide more details (log files, versions, Windows EventViewer error messages?)

**Comment by Ryochan7** [comment]
> I have memory (64gb) leak (and it crash my window), with - steam+ps5 controller+DS4_2.2.7

Consume all the memory. Anyway, the .NET Runtime should be performing garbage collection on occasion and it is supposed to enforce a cap on application memory based on your system. Looks like neither safeguard is taking effect. Memory usage stays constrained on my end and memory usage can get as low as 11 MB depending on how much memory other apps request.

You can possibly try disabling server-mode garbage collection for DS4Windows and see how the app performs then; memory usage will be lower but input performance will be much worse. Edit the **enabled** value for the **gcServer** tag in the DS4Windows.exe.config file and set it to false. Then open DS4Windows and see how the app runs.

```
<gcServer enabled="false"/>
```

**Comment by Mr-Korben-Dallas** [comment]
Thanks **mika-n** and **Ryochan7**
Everything works now

I bought ps5 controller in fifth december, then I installed DS4Windows
Everything worked fine 

But I stopped playing, at the beginning of the year
A few days ago (DS4Windows was auto updated), I decided to play in steam game - **Spirit of the North**

When the game started, all I saw was a black screen
PC did not respond, so I reset it

When I repeat all my actions
Game started, and I got to the main menu
I thought it was a problem with the game
I set up the graphics, then I start and everything freeze again 

But this time, I was able to call task manager with ctrl + alt + del
And I saw that my memory was 99% utilized 
But in the list of applications, there were no applications, that would drain all the memory 

I could only reset my PC
Then I repeated again all my actions, with same result

Installing the latest driver helped me 
https://github.com/ViGEm/ViGEmBus/releases

Log:

<details>
  <summary>Then it works</summary>
  

> 
> 2020-12-13 11:46:02.8967|INFO|DS4Windows version 2.1.20
> 2020-12-13 11:46:02.8967|INFO|DS4Windows exe file: DS4Windows.exe
> 2020-12-13 11:46:02.8967|INFO|OS Version: Microsoft Windows NT 10.0.18362.0
> 2020-12-13 11:46:02.8967|INFO|OS Product Name: Windows 10 Enterprise
> 2020-12-13 11:46:02.8967|INFO|OS Release ID: 1903
> 2020-12-13 11:46:02.8967|INFO|System Architecture: x64
> 2020-12-13 11:46:02.8967|INFO|Logger created
> 2020-12-13 11:46:03.7515|INFO|Running as Admin
> 2020-12-13 11:46:04.7674|INFO|Starting...
> 2020-12-13 11:46:04.7674|INFO|Connection to ViGEmBus 1.16.112.0 established
> 2020-12-13 11:46:04.7674|INFO|Searching for controllers...
> 2020-12-13 11:46:04.7674|INFO|Using Shared Mode
> 2020-12-13 11:46:04.8665|INFO|Found Controller: A0:AB:51:C3:C6:B0 (BT) (DualSense)
> 2020-12-13 11:46:04.9506|INFO|Plugging in virtual X360 Controller
> 2020-12-13 11:46:04.9506|INFO|Associate X360 Controller for input DS4 #1
> 2020-12-13 11:46:04.9766|INFO|Controller 1 is using Profile "Default". Battery level is 100%
> 2020-12-13 11:46:08.6810|INFO|Request App Shutdown
> 2020-12-13 11:46:08.6810|INFO|Stopping Virtual Output Controllers
> 2020-12-13 11:46:08.6810|INFO|Closing connection to ViGEmBus
> 2020-12-13 11:46:08.7390|INFO|Disassociate X360 Controller for input DS4 #1
> 2020-12-13 11:46:08.7400|INFO|Unplugging virtual X360 Controller
> 2020-12-13 11:46:08.7400|INFO|Stopping DS4 Input Controllers
> 2020-12-13 11:46:08.7400|INFO|Stopped DS4Windows

</details>




<details>
  <summary>Then I get memory leak</summary>
 

> 2021-02-19 22:27:03.9668|INFO|DS4Windows version 2.2.2
> 2021-02-19 22:27:03.9768|INFO|DS4Windows exe file: DS4Windows.exe
> 2021-02-19 22:27:03.9768|INFO|DS4Windows Assembly Architecture: x64
> 2021-02-19 22:27:03.9768|INFO|OS Version: Microsoft Windows NT 10.0.18362.0
> 2021-02-19 22:27:03.9768|INFO|OS Product Name: Windows 10 Enterprise
> 2021-02-19 22:27:03.9768|INFO|OS Release ID: 1903
> 2021-02-19 22:27:03.9768|INFO|System Architecture: x64
> 2021-02-19 22:27:03.9768|INFO|Logger created
> 2021-02-19 22:27:05.4031|INFO|Running as Admin
> 2021-02-19 22:27:06.4381|INFO|Starting...
> 2021-02-19 22:27:06.4381|INFO|Connection to ViGEmBus 1.16.112.0 established
> 2021-02-19 22:27:06.4381|INFO|Searching for controllers...
> 2021-02-19 22:27:06.4381|INFO|Using Shared Mode
> 2021-02-19 22:27:42.7361|INFO|Request App Shutdown
> 2021-02-19 22:27:42.7411|INFO|Stopping Virtual Output Controllers
> 2021-02-19 22:27:42.7411|INFO|Closing connection to ViGEmBus
> 2021-02-19 22:27:42.7411|INFO|Stopping DS4 Input Controllers
> 2021-02-19 22:27:42.7411|INFO|Stopped DS4Windows
> 
> 2021-02-19 22:27:49.5964|INFO|DS4Windows version 2.2.7
> 2021-02-19 22:27:49.6014|INFO|DS4Windows exe file: DS4Windows.exe
> 2021-02-19 22:27:49.6014|INFO|DS4Windows Assembly Architecture: x64
> 2021-02-19 22:27:49.6014|INFO|OS Version: Microsoft Windows NT 10.0.18362.0
> 2021-02-19 22:27:49.6014|INFO|OS Product Name: Windows 10 Enterprise
> 2021-02-19 22:27:49.6014|INFO|OS Release ID: 1903
> 2021-02-19 22:27:49.6014|INFO|System Architecture: x64
> 2021-02-19 22:27:49.6014|INFO|Logger created
> 2021-02-19 22:27:50.4211|INFO|Running as Admin
> 2021-02-19 22:27:51.4391|INFO|Starting...
> 2021-02-19 22:27:51.4391|INFO|Connection to ViGEmBus 1.16.112.0 established
> 2021-02-19 22:27:51.4391|INFO|Searching for controllers...
> 2021-02-19 22:27:51.4391|INFO|Using Shared Mode
> 2021-02-20 00:29:22.9216|INFO|Found Controller: A0:AB:51:C3:C6:B0 (BT) (DualSense)
> 2021-02-20 00:29:23.0367|INFO|Plugging in virtual X360 Controller
> 2021-02-20 00:29:23.0367|INFO|Associate X360 Controller for input DS4 #1
> 2021-02-20 00:29:23.0677|INFO|Disassociate X360 Controller for input DS4 #1
> 2021-02-20 00:29:23.0677|INFO|Unplugging virtual X360 Controller
> 2021-02-20 00:29:23.0677|INFO|Controller 1 was removed or lost connection. Charge the battery
> 2021-02-20 00:29:33.0378|INFO|Found Controller: A0:AB:51:C3:C6:B0 (BT) (DualSense)
> 2021-02-20 00:29:33.0378|INFO|Plugging in virtual X360 Controller
> 2021-02-20 00:29:33.0378|INFO|Associate X360 Controller for input DS4 #1
> 2021-02-20 00:29:33.0378|INFO|Controller 1 was removed or lost connection. Charge the battery
> 2021-02-20 00:30:05.1295|INFO|Request App Shutdown
> 2021-02-20 00:30:05.1295|INFO|Stopping Virtual Output Controllers
> 2021-02-20 00:30:05.1295|INFO|Closing connection to ViGEmBus
> 2021-02-20 00:30:05.1295|INFO|Stopping DS4 Input Controllers
> 2021-02-20 00:30:05.1295|INFO|Stopped DS4Windows
> 
> 2021-02-20 00:30:11.3041|INFO|DS4Windows version 2.2.7
> 2021-02-20 00:30:11.3041|INFO|DS4Windows exe file: DS4Windows.exe
> 2021-02-20 00:30:11.3041|INFO|DS4Windows Assembly Architecture: x64
> 2021-02-20 00:30:11.3041|INFO|OS Version: Microsoft Windows NT 10.0.18362.0
> 2021-02-20 00:30:11.3041|INFO|OS Product Name: Windows 10 Enterprise
> 2021-02-20 00:30:11.3041|INFO|OS Release ID: 1903
> 2021-02-20 00:30:11.3041|INFO|System Architecture: x64
> 2021-02-20 00:30:11.3041|INFO|Logger created
> 2021-02-20 00:30:12.0928|INFO|Running as Admin
> 2021-02-20 00:30:13.1097|INFO|Starting...
> 2021-02-20 00:30:13.1097|INFO|Connection to ViGEmBus 1.16.112.0 established
> 2021-02-20 00:30:13.1097|INFO|Searching for controllers...
> 2021-02-20 00:30:13.1097|INFO|Using Shared Mode
> 2021-02-20 00:30:53.9289|INFO|Stopping Virtual Output Controllers
> 2021-02-20 00:30:53.9289|INFO|Closing connection to ViGEmBus
> 2021-02-20 00:30:53.9289|INFO|Stopping DS4 Input Controllers
> 2021-02-20 00:30:53.9289|INFO|Stopped DS4Windows
> 2021-02-20 00:30:55.0334|INFO|Starting...
> 2021-02-20 00:30:55.0334|INFO|Connection to ViGEmBus 1.16.112.0 established
> 2021-02-20 00:30:55.0334|INFO|Searching for controllers...
> 2021-02-20 00:30:55.0334|INFO|Using Shared Mode
> 2021-02-20 00:31:00.6715|INFO|Request App Shutdown
> 2021-02-20 00:31:00.6715|INFO|Stopping Virtual Output Controllers
> 2021-02-20 00:31:00.6715|INFO|Closing connection to ViGEmBus
> 2021-02-20 00:31:00.6715|INFO|Stopping DS4 Input Controllers
> 2021-02-20 00:31:00.6715|INFO|Stopped DS4Windows

</details>

I think the problem appears in the combination of 2.2.7 version of DS4Windows and 1.16.112.0 driver
