### ISSUE TITLE
Controller readings are wrong.

### ISSUE THREAD

**Issue by adoion** [Ryochan7/DS4Windows#1882]
Hi, just wanted to note that the gyro and accelerometer readings are swapped i.e. gyro should be accelerometer and wise versa. Also the y axis isn't doing nothing useful really, it just moves along with the other 2.

I didn't find any post with this issue so just wanted to point it out.

Thanks

**Comment by Ryochan7** [comment]
Wrong

**Comment by Ryochan7** [comment]
And yes. The Y axis is not used in DS4Windows. It is used by the UDP Server though.
