### ISSUE TITLE
Touchpad does not work for me in 2.2.7 (dualsense)

### ISSUE THREAD

**Issue by TheMasterDingo** [Ryochan7/DS4Windows#1883]
Noticed today touchpad did not work no matter which profile i used for the controller. Tested with a new profile also.
I think (but not sure) it did not work even in 2.2.6.

**Comment by kin-patsu** [comment]
I'm having the same issue, however it seems to be on a game-to-game basis.
With Hollow Knight it works perfectly, while with Monster Hunter World (Steam Input force-disabled) it won't work no matter what.

A few more details:

**Desktop:**
 - Controller: Sony DualSense
 - OS: Windows 10 20H2 (build SO 19042.804)
 - DS4Windows Version: 2.2.7
 - Touchpad: Set to Passthru

I hadn't tried MHW with previous versions, so I can't say if it's something that happened only recently.
@TheMasterDingo what game were you playing?

**Comment by TheMasterDingo** [comment]
> I'm having the same issue, however it seems to be on a game-to-game basis.
> With Hollow Knight it works perfectly, while with Monster Hunter World (Steam Input force-disabled) it won't work no matter what.
> 
> A few more details:
> 
> **Desktop:**
> 
> * Controller: Sony DualSense
> * OS: Windows 10 20H2 (build SO 19042.804)
> * DS4Windows Version: 2.2.7
> * Touchpad: Set to Passthru
> 
> I hadn't tried MHW with previous versions, so I can't say if it's something that happened only recently.
> @TheMasterDingo what game were you playing?

For me it does not work in any game, even desktop, tried switching touchpad on-off, nothing moves

**Comment by Ryochan7** [comment]
Going to assume this is actually a UAC permissions issue rather than a mapping problem. For some games, you would likely need to run DS4Windows as the admin to work around UAC issues. I normally run DS4Windows as the admin so I run into those problems far less.

**Comment by TheMasterDingo** [comment]
i always run it as admin, i will test a few other versions to tell which was the latest it worked

**Comment by TheMasterDingo** [comment]
> i always run it as admin, i will test a few other versions to tell which was the latest it worked

So i tested and it does work in 2.2.7 when launching normally, but if the controller is connected to the pc with a game started that is set with autoprofile and doing problem #1884 then touchpad doesn't work, it does not work even after exiting game and it connects the virtual controller, so i think my real problem is #1884
