### ISSUE TITLE
Auto-profile not connecting controller after game has started

### ISSUE THREAD

**Issue by TheMasterDingo** [Ryochan7/DS4Windows#1884]
It used to work that when i had started the game and i connected the controller to the pc then ds4win would plug the virtual controller and it would work normally.
Now, as of 2.2.7(maybe 2.2.6) if i have started the game and i connect the controller to the pc, it changes the light to the correct profile, does not plug any virtual controller to the pc(im checking it with the gamepad control panel), a fix is to go to desktop then to the game and i can hear the sound of a device pluged in.
this is the log after connecting the controller with game running, it should switch to my xbox profile
02/19/2021 08:22:32: DS4Windows version 2.2.7
02/19/2021 08:22:32: DS4Windows Assembly Architecture: x64
02/19/2021 08:22:32: OS Version: Microsoft Windows NT 10.0.19042.0
02/19/2021 08:22:32: OS Product Name: Windows 10 Pro
02/19/2021 08:22:32: OS Release ID: 2009
02/19/2021 08:22:32: System Architecture: x64
02/19/2021 08:22:32: Running as Admin
02/19/2021 08:22:33: Starting...
02/19/2021 08:22:33: Connection to ViGEmBus 1.17.333.0 established
02/19/2021 08:22:33: Searching for controllers...
02/19/2021 08:22:33: Using Shared Mode
02/19/2021 08:22:55: Found Controller: 4C:B9:9B:48:D5:9A (BT) (DualSense)
02/19/2021 08:22:55: Controller 1 is using Profile "ds". Battery level is 100%

EDIT: Latest working version is 2.2.2
 here a video of the problem :   https://streamable.com/vqpmfu
on  2.2.2 it just plugs the right virtual controller as soon as i connect the controller physically
This feature is very important for me since i use my controller with GameStream and i always have to connect it after the game starts.
Please fix it, thank you

**Comment by wdt888** [comment]
same problem here

**Comment by TheMasterDingo** [comment]
is this a bug or is intended?

**Comment by bslenul** [comment]
Definitely a bug, I already opened an issue about this with logs and bisect (#1864), hopefully the devs will be able to fix it soon! 🤞

**Comment by TheMasterDingo** [comment]
> Definitely a bug, I already opened an issue about this with logs and bisect (#1864), hopefully the devs will be able to fix it soon! 🤞

oh i see we have the same exact problem, let's hope they fix it soon

**Comment by mika-n** [comment]
closed as duplicate #1864
