### ISSUE TITLE
DS4 not plugging in 2.2.7

### ISSUE THREAD

**Issue by wdt888** [Ryochan7/DS4Windows#1886]
As of 2.2.7 my DS4 controller is not recognized if I turn it off and on again.

When I first turn on DS4Windows it recognizes the controller. The Active box in Output Slots is marked. Then if I turn the controller off and on again, the Active box will not be marked until I restart DS4Windows.
When the Active box is empty, the Control Panel is also empty.

**Comment by mika-n** [comment]
Logfiles?
Or even better run the debug version and provide that logfile here.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

**Comment by wdt888** [comment]
Sorry mika-n, this is my first github post so I'm very noob here. I'll try to get logfile from the debug version.

**Comment by wdt888** [comment]
The debug file (BT2021) is asking for a password to unzip, what is it?

**Comment by wdt888** [comment]
mika, I just downloaded the debug and I now the issue is not happening anymore. It was happening everyday. But 4 days ago I stopped using 2.2.7 and started using 2.2.1, which was working fine. Today I installed 2.2.7 again to log the issue and it is not happening anymore. If it starts happening again I'm gonna run the debug to log it.

**Comment by wdt888** [comment]
It sounds very similar to issue #1864. I even closed my own issue here once, because I thought it was the same thing. But I opened it again because of a few differences. Like, the only thing that fixed my problem was restarting DS4Windows, while on #1864 bslenul said it could be fixed by going back to the desktop.
If it happens again I'll log it, but it's probably the Auro-profile thing that he mentions.

**Comment by wdt888** [comment]
bslenul seems to be much more experienced than me in detecting AND reporting the problem. So any mods can feel free to close this issue if you want to.
