### ISSUE TITLE
Unticking check for updates still checks for updates at startup

### ISSUE THREAD

**Issue by dankjan** [Ryochan7/DS4Windows#1887]
I am greeted with the message to update the program almost every boot. Yes, skip version does ignore it, but only until the next version comes out. It should not check for updates when I untick the box. I really don't use it for anything else than the DS4 support and that works just fine on the version I'm on, right now(2.2.1). And yes, this has been going on for several versions now(even older ones too)

**Comment by Ryochan7** [comment]
Your Profiles.xml config file must be corrupt or something. I have several older versions of DS4Windows on my PC and my Windows 7 VM that has the **Check for updates at DS4Windows startup** setting unchecked. The setting works on my end for each of those versions.
