### ISSUE TITLE
Two Stage Trigger mode no longer engages default Soft Pull binding

### ISSUE THREAD

**Issue by pablo5425** [Ryochan7/DS4Windows#1888]
**Describe the bug**
the latest 2.2.7 made dualsense triggers stop working _while emulating xbox buttons_. if i make it use dualshock/dualsense buttons it works perfectly

**To Reproduce**
connect any dualsense controller in ds4windows
[ds4windows_log_20210220.0.txt](https://github.com/Ryochan7/DS4Windows/files/6013719/ds4windows_log_20210220.0.txt)
 and use it normally. neither games or gamepad testers detect any trigger when you press them

**Expected behavior**
i mean, triggers should work

**Comment by pablo5425** [comment]
[ds4windows_log_20210220.0.txt](https://github.com/Ryochan7/DS4Windows/files/6013723/ds4windows_log_20210220.0.txt)

**Comment by Ryochan7** [comment]
Both issue threads were wrong. Almost made me think there was no issue but I found one. Two Stage Trigger soft pull is what does not work. Full pull seems to work fine.

**Comment by pablo5425** [comment]
![image](https://user-images.githubusercontent.com/34631489/108596492-b33e9600-7385-11eb-8aba-6368b4e0cd27.png)
i tried with this configuration. its not working with two stage disabled either
unless that soft pull is permanently enabled
