### ISSUE TITLE
Open release page in browser for manuel updates

### ISSUE THREAD

**Issue by CodingAir** [Ryochan7/DS4Windows#1889]
**Describe the feature**
Sometimes the ds4 updater can't update itself and we have to download a new update, which is quite annoying. To improve this, the updater should open the release page automatically so we don't have to search for the release page ourselves.

Thank you very much for your great work!

**Comment by Darthagnon** [comment]
I've noticed that the ```Hotkeys/About``` window in DS4Windows, with links to all the official social channels, doesn't include a link to this official GitHub repo, too - Would it be possible to add that, if/when the Discord link is updated?

**Comment by CodingAir** [comment]
Thanks!
