### ISSUE TITLE
Gatillos adaptativos PS5

### ISSUE THREAD

**Issue by Saaber09** [Ryochan7/DS4Windows#1890]
Hola, me gustaria saber si esta implementado lo de los gatillos adaptativos

**Comment by mika-n** [comment]
In English?  Or in Finnish, but I guess there are more people a bit more familiar with English :-)

**Comment by Hexality** [comment]
_"Hi, I wanna know if the adaptive triggers are already implemented"_ (not a 100% accurate but its basically what s/he said)
