### ISSUE TITLE
Windows not detecting DS4 Headphone jack

### ISSUE THREAD

**Issue by Mordius** [Ryochan7/DS4Windows#1891]
I have a DS4 V1 controller and even if I connect it through USB Windows doesn't seem to detect the Headphone jack, I tried with another USB cable, connecting earphones to the controller jack and then the controller to the PC, but nothing seems to work.

Also, I don't know if the V1 controller is not supported for audio, but a friend brought his V2 controller and Windows detected the Headphone jack as soon as I connected it through USB. I know my controller is not damaged since is new, I bought it just a week ago

edit: I just checked and my controller model is CUH-ZCT2E which (based in a video i saw in youtube) is V2, but DS4Windows detects it as a V1 controller, is this normal?

**Comment by Ryochan7** [comment]
The V1 controller does not offer headphone jack audio output on PC. That was a change with the V2 controller.

**Comment by Mordius** [comment]
Didn't know that, thanks for the answer
