### ISSUE TITLE
Discord Gone?

### ISSUE THREAD

**Issue by MonfGeiger** [Ryochan7/DS4Windows#1893]
So, I've been ignoring my discord channel list for a while, and only now noticed that the ds4windows discord is gone? I don't know if there was any drama behind what happened to it or whatever, so if there is, I'm not trying to inflame it at all, but just so I could know......what happened to the ds4windows discord that got it erased? voluntary closure, discord tech-staff closed it because some ToS violation, a hacker being a dick, what's up?

**Comment by Darthagnon** [comment]
I've noticed that the ```Hotkeys/About``` window in DS4Windows, with links to all the official social channels, doesn't include a link to this official GitHub repo, too - Would it be possible to add that, if/when the Discord link is updated?

**Comment by Corgano** [comment]
Discord disappeared for me too.

**Comment by Erquint** [comment]
https://github.com/Ryochan7/DS4Windows/commit/b29429a6566da09860b76be2d89c5c9b6c879541
Check this commit out.
What is going on and why is it so hush-hush?

**Comment by Skynet19972029** [comment]
I noticed this too. I wonder what happened.

**Comment by Mircosfot** [comment]
what is the name of the old Discord-server?

**Comment by BitGrub** [comment]
Years of being on the discord channel and I've never needed it. Now I finally encounter some critical bugs and there's no discord to ask about them in 😢

**Comment by mika-n** [comment]
This Github site is better place for tech support because after all people are from all around the world, so Discord has the timezone problem. Also, Discord has a bad habit to loose old messages and new people don't easily find answers to questions already answered (hundreds of times). This forum is easier place to search the history and share links to old answers and docs, so I don't see where the problem is.

**Comment by nefarius** [comment]
People, don't forget that running a Discord server is an additional workload on the people running this project. If it helps them focus more on the core work of improving the software and documentation I'd say it's a good thing. And as mentioned; if a certain piece of information only exists in some Discord channel, it is prone to get buried and is not easily accessible to the public anymore. Speaking of experience 😅

**Comment by kalamalka** [comment]
If the Discord is officially gone I must say I am truly disappointed. That server was very helpful to me on many occasions. I am not even sure there are as many sections on this GH as there were there.

**Comment by mika-n** [comment]
I would be very surprised if Discord had something which is not already covered in issue tickets (open and closed tickets, use the search feature to find those) or in the wiki docs. And remember this project is open for community contributions then if you think something is missing from the documentation then please contribute new issue ticket or add a new topic to the wiki docs.
https://github.com/Ryochan7/DS4Windows/wiki

**Comment by kalamalka** [comment]
> I would be very surprised if Discord had something which is not already covered in issue tickets (open and closed tickets, use the search feature to find those) or in the wiki docs. And remember this project is open for community contributions then if you think something is missing from the documentation then please contribute new issue ticket or add a new topic to the wiki docs.
> https://github.com/Ryochan7/DS4Windows/wiki

I am not sure Github was designed for what a forum would be better for. For example, where would you suggest future feature request discussion go ? What about people who wish to share profiles? I cant remember all the cool channels that were on the Discord now, but I feel like Github doesn't have the same functionality of adding new sections (or the equivalent of channels. I do agree though that Discord also isn't the best, as its essentially a stream. I think the GH could have potential if there were a way to categorize help/requests/community type discussions. 

The other problem is that a quick Google search for the DS4WIndows is still producing this:
https://github.com/Jays2Kings/DS4Windows

Which I believe is deprecated but there is still a **HUGE** influx of people going there not knowing that this is the active GitHUb for DS4Windows. Is there a way to get that other GH page shut down or edited for redirect? Or maybe even create a bot to reply to new all new postings for a redirect? Who even manages that other GH? Can we get in touch with the author to have it merged or something?

Cheers

**Comment by mika-n** [comment]
Issue ticket can be tagged with "Feature Request" tag or title. 
Profiles and logfiles can be shared as attachments in issue tickets.

The author of the Jays2Kings site is lost in hyperspace, so no one can do anything about the old obsolete site. I'm sure GitHub admins would not delete or set it in read-only mode it someone asks about it. Only if GitHub would have some mechanism to keep track of when the admin logged in the last time and if it was >X months ago then the site would go in read-only state or moved to some archive area.
