### ISSUE TITLE
Used DS4, after closing and reopening program wont open.

### ISSUE THREAD

**Issue by DonJuanzap** [Ryochan7/DS4Windows#1894]
I got a PS5 control and successfully used it for gaming one night. The following day I go to reopen DS4 and the program will not open the window. 
I reinstall, download old versions, newer versions, reboot, restart, uninstalled my latest updates etc and NOTHING is working. I have done all possible research to fix this issue and even when I start from scratch the DS4 window will not open after I start the program. NOTE: I have already connected the PS5 control to DS4 before and have used it easily and successfully. I do not know what else to do please help. 

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony PS5 control (CFI-ZCT1W)
 - OS: [Edition	Windows 10 Home
Version	20H2
Installed on	‎12/‎26/‎2020
OS build	19042.804
Experience	Windows Feature Experience Pack 120.2212.551.0

 - DS4Windows Version [e.g. 2.2.1]

**Comment by mika-n** [comment]
Read the "Read this before posting a new issue ticket" and provide the minimum required information: Logfile and warning/error mesage in Windows EventViewer
