### ISSUE TITLE
Cannot Rebind Share Button To Touchpad Click (DualSense Controller)

### ISSUE THREAD

**Issue by atom0s** [Ryochan7/DS4Windows#1895]
**Describe the bug**

Remapping everything on the controller seems to work fine except the Share Button cannot be remapped to Touchpad Click for some reason.

**To Reproduce**
1. Download latest release from this repo.
2. Run the program, select to store everything in the program folder.
3. Edit the Default Profile and turn on Touchpad forwarding and change 'Emulated Controller' to DualShock 4.
4. Save and leave all other options default.
5. Attempt to remap the Share button to Touchpad Click.
6. Go in-game and press the share button, nothing happens.

**Expected behavior**
In a game like Immortals Feynx Rising, the touchpad click opens the inventory screen. Attempting to remake the Share button to do this same thing does not work. However, it can be remapped to any other button on the controller and works fine.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DualSense (PS5) CFI-ZCT1W
 - OS: Windows 10 Pro Build 1909
 - DS4Windows Version 2.2.7 (Downloaded latest release as of today.)

**Additional context**
As mentioned above, nothing else in the profile is changed. This is 100% stock install of DS4Win with no fiddling at all. 
The only thing I changed was 'Touchpad' to 'Passthru' mode to make it work properly and not act like a mouse.

Outside of that, the controller works 100% fine, except the Share button. Testing other remaps works fine, such as remapping Share to R2 works fine. So the button is seen and works, just not with the touch click instead.

**Comment by Ryochan7** [comment]
It looks like the latest Touchpad Mouse passthru click option has broken this. The binding gets set to false if the option is not being used.
