### ISSUE TITLE
outright crashes on windows 10 

### ISSUE THREAD

**Issue by RealUn2ken** [Ryochan7/DS4Windows#1896]
Activation context generation failed for "G:\applications\DS4Windows\DS4Windows.exe".Error in manifest or policy file "G:\applications\DS4Windows\DS4Windows.exe.Config" on line 0. Invalid Xml syntax.

this happens on at least 2 of the latest builds

**Comment by Ryochan7** [comment]
Sounds like that file is corrupt on your end. It works fine when I unpack the 7zip archive on my end. You will probably have to extract the archive again.

**Comment by RealUn2ken** [comment]
i did that multiple times. checking on different versions.  the way i resolved is to not load ds4windows on start up.  if it manages to load earlier with a steam client that has configured  controls the problem gets actually worse. it will not just crash but just practically hangs the entire OS makes the system unresponsive randonly but i happens a lot .

**Comment by mika-n** [comment]
The latest logfile? %APPDATA%\DS4Windows\Logs
Windows EventLog error messages?

For sure errors in xxx.config file would have seen by hundreds of users already if that would be the case. So I believe the error is in the workstation. Maybe out-of-date runtime libaries (.NET Framework and/or VC++). Try updating those just-in-case. And make sure you have downloaded the correct bitness (32bit or 64bit version of DS4Windows. I guess you have 64bit Windows10 maybe? 32bit is relevant only with veeeeeeery ancient PCs).
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#link-list

**Comment by RealUn2ken** [comment]
found the solution. I basically disabled telemetry . im windows insider program... i left but yeah telemetry is causing some major issues.
