### ISSUE TITLE
Quick Charge Bluetooth to Usb Issue

### ISSUE THREAD

**Issue by shinra358** [Ryochan7/DS4Windows#19]
This has been a problem ever single Jay2Kings added the quick charge feature at my request, where if you are on bluetooth mode and then you plug in the controller with a usb cord, the light is supposed to stay on or switch to whatever the usb cord color is supposed to be. Instead, when plugged at said time, the light turns off and the controller becomes unresponsive and doesn't charge. 

So basically, when on bluetooth mode, and the controller is plugged in, it's supposed to switch to cord mode and still work with the quick charge option on. And this probably concludes the list of problems I had with the program over the years.

**Comment by Ryochan7** [comment]
I have never tried that feature but the status message for it does say that it is an experimental feature. I am not sure how the current code goes about trying to make that feature work. That will have to be looked over sometime soon.

**Comment by Ryochan7** [comment]
The routine for switching to the different device was in the wrong place. A couple of other minor tweaks were also needed to get this feature working. Now DS4Windows will close the Bluetooth controller and switch to using the USB controller when this mode is enabled.

**Comment by shinra358** [comment]
Hi, it does as it should now but afterwards, it breaks xinput and the controller stops working properly. When I turned on bluetooth and then plugged it in, it switched to plugged but the windows notification sound didn't play properly. Then I tried switching xinput ports and ds4 crashed with this error;

Application: DS4Windows.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at DS4Windows.DS4StateFieldMapping..ctor(DS4Windows.DS4State, DS4Windows.DS4StateExposed, DS4Windows.Mouse)
   at DS4Windows.Mapping.MapCustom(Int32, DS4Windows.DS4State, DS4Windows.DS4State, DS4Windows.DS4StateExposed, DS4Windows.Mouse, DS4Windows.ControlService)
   at DS4Windows.ControlService.On_Report(System.Object, System.EventArgs)
   at DS4Windows.DS4Device.performDs4Input()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()


Faulting application name: DS4Windows.exe, version: 1.4.63.0, time stamp: 0x58fc736c
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x000007fe90ebdc5a
Faulting process id: 0x1cb4
Faulting application start time: 0x01d2bc3d8aa4dd1f
Faulting application path: E:\Users\T Dean Jr\My Documents\Games\MAIN\DS4Windows - J2K\DS4Windows.exe
Faulting module path: unknown
Report Id: 50acf64d-2833-11e7-89a7-8056f2ad9956

**Comment by shinra358** [comment]
Afterwards, xinput no longer wrks until i reapply the xinput ports and not
do the quick charge.

**Comment by Ryochan7** [comment]
I encountered that problem when initially working on getting Quick Charge to work but the changes that I made fixed the problem for me. I have added a couple of other relevant checks to the code that should fix this problem. The main problem come from the issue that there is an odd chance that an input report can be read before a device is fully disconnected but the device reference no longer exists in the main array.

**Comment by shinra358** [comment]
Cool, awaits download for fixed version.

**Comment by shinra358** [comment]
Version 1.4.64

xinput portion of the controller still ceases to work. can only access dinput when plugged in. I am still unable to play any game.

**Comment by Ryochan7** [comment]
As long as the Scp Virtual Bus Driver is working, there shouldn't be a problem within DS4Windows. Is the Virtual Bus disabled in the Device Manager? I would ask about your controller since I had encountered problems before with Exclusive Mode keeping a device disabled but it seems that your controller still works outside of DS4Windows. Trying an older version of DS4Windows with Quick Charge disabled might be necessary to work this issue out. Also, out of curiosity, have you tried a recent release of InputMapper? If you have then maybe HidGuardian is causing problems.

I will re-open this issue until this problem is worked out.

**Comment by shinra358** [comment]
Nothing is wrong with the scp driver. I haven't touched it. Xinput worked fine before this fix was integrated besides the port or quick charge issues. Now xinput just doesn't work at all. I'm on Win7 Ultimate x64. My controller is a ds4 (no official dongle internal bluetooth within laptop). Yes, ds4windows still works with xinput when I go back to Jays old version before I switched to this.

I don't like inputmapper because it is missing alot of fixes and features that this version has. I am the guy that asked for 75% of these features in this program that jay put in xD

**Comment by shinra358** [comment]
Well, i guess something was wrong with the driver. I uninstalled it and reinstalled it now it works. But here is the problem now:

1. Bluetooh on + then plug in controller = (wireless controller + xbox360 in joy.cpl). Bluetooth emblem still shows in ds4windows instead of usb icon. So Hide DS4 option isn't working when you plug the controller in from bluetooth mode.

2. Removing the usb cord after this is supposed to turn the controller off completely.

3. Afterwards when trying to activate bluetooth, xinput ceases to work again.

**Comment by Ryochan7** [comment]
Does the disconnect bluetooth option work on your system when running older versions of DS4Windows? There is the special action but it would probably be better if you try to disconnect by right clicking on the bluetooth icon in the main form; the two methods work slightly differently and the right click version more closely resembles what is being done with Quick Charge. I don't really like how DS4Windows handles hotplugging devices. I have done some minor refactors but multiple full controller scans are being performed for each hotplug event.

As for InputMapper, I think it is an interesting project and I test it out on occasion. Although, out of the main options for using a DS4 on a Windows PC, I find it to not work as well as other alternatives; Steam's support for the DS4 has InputMapper beat although the Steam implementation is a bit too laggy for my liking.

**Comment by shinra358** [comment]
"Does the disconnect bluetooth option work on your system when running older versions of DS4Windows?"
Yes. I also have a button on my laptop to disable bluetooth as well. The last version of ds4windows I used before this version was the teokp fix 1st version. Also, can't get the trackpad to work nor can I get bluetooth connection to work anymore either. So even if I just use my bluetooth button, the controllers just don't function properly anymore like they use to with xinput. It's even gotten harder to find the correct xinput ports.

**Comment by Ryochan7** [comment]
The disconnect bluetooth routine has been reverted to the old behavior. The old behavior didn't quite work for Quick Charge while developing 1.4.63 but the latest changes seem to allow the routine to work fine on my rig. A new release is scheduled to get published on Friday.

**Comment by shinra358** [comment]
![geebs](https://cloud.githubusercontent.com/assets/3978291/25552279/1ceef1ee-2c63-11e7-9886-fbeadebbc70b.png)
redid all the profiles from scratch. It didn't help. I remember having to go into the device options and setting the drivers to the controllers individually and that fixed the problem in the past. Can't get that trick to work now. Seems like the controller drivers aren't being allocated properly when installed.

**Comment by Ryochan7** [comment]
Is there an error in the log that says something like **Could not connect to Scp Virtual Bus Driver**? That log message was just added in the last version. If not then the connection to the bus driver should work fine. The only other problem would be that maybe the Quick Charge check is happening in the wrong place so the XInput controller is never created.

**Comment by shinra358** [comment]
No error in the log that says that.

**Comment by shinra358** [comment]
.68 version is working good! cursor still only wants to work on my blue controller and not for the p1 controller even when I paired it last

**Comment by Ryochan7** [comment]
I can only think of one place in the code that the code would fail to react to the touchpad. Can you test the other controller in Hid Report Listener? I am thinking that maybe the touchpad packet is being ignored since maybe a byte in the input report does not have an expected value of 1 or greater. The relevant byte that matters in this case is byte 33 for USB or byte 35 for Bluetooth. The value should be between 1 to 4 when the touchpad is being touched. If the byte stays zero then that could explain why no touchpad activity happens with that controller.

https://inputmapper.com/downloads/download/5-tools/75-hid-report-listener

**Comment by shinra358** [comment]
I dnt see ant change when i touch the touchpad on either controller.

**Comment by shinra358** [comment]
Also, the code needs tightening up because when youre in bluetooth mode and you plug it in and then take it out, the controller is supposed to be off. Yet sometimes randomly, it is still on.

And during this time when plugged in when previously on bluetooth mode, it still says youre on bluetooth mode.

**Comment by Ryochan7** [comment]
Ironically, a lot of issues that have popped up lately have been from trying to tighten up the code. Most of that work has gone to just making routines run faster in order to speed up controller responsiveness. Only some later work has gone into fixing problems inherit with the program. DS4Windows does not really take precautions when it comes to its multi-threaded behavior. With version 1.4.69, I am hoping some other issues have been ironed out now that SynchronizationContext is used to force some device removal routines to run in the main thread.

As for the touchpad issue, if nothing is appearing in HID Report Listener then something is severely wrong. It works about as low level as can be done for a user mode application working with HID devices. Even though it was mainly written to help users contribute to InputMapper, the program has many uses outside of InputMapper. I have used it myself to help validate behavior in DS4Windows.

**Comment by shinra358** [comment]
As far as the cursor is involved, for me, inputmapper has the same issue.

**Comment by shinra358** [comment]
quick charge issue seems fixed on test build. but it's hard to tell for sure because i keep getting xinput failed randomly or write errors.

**Comment by shinra358** [comment]
Seems fixed in newest newest test build.
