### ISSUE TITLE
DS4 bluetooth broken for all use cases after upgrading to ryochan7 fork of ds4windows

### ISSUE THREAD

**Issue by marquesj** [Ryochan7/DS4Windows#1900]
**Describe the bug**
We were using the old jays2kings version, and sometimes just plugging normally and letting steam handle it. Both Bluetooth and wired connection worked.
I downloaded this version (2.2.7_x64) and tried to use it. The wired connection was fine, but bluetooth broke completely. It can't be used in any ds4windows version, or even with just steam. The controller doesn't even maintain the connection after pairing, lasting just 1-2 seconds, and doesn't pop up in ds4windows or in steam at all.

I have tried to clean up all drivers related to both this version and the old version of ds4windows, the only software i used for this matter was these 2 forks of ds4windows. I know about the tricks of enabling the driver when it gets disabled and I tried the turning off of the controller, the reset of the controller, removing drivers and devices, updating bluetooth drivers, and restarted when needed. I also took care to have no other applications running that could use the controller, like steam and edge.

This happened with 2 controllers both V2. Same computer. If i plug them to another computer with just steam running, they get detected and work fine. This is isolated to the computer where we upgraded to this fork.

I have been now testing under 2.1.23_x64.
I may be missing something very trivial, or doing something wrong, but I have been searching for a long time now and can't figure it out. Any help appreciated.

**Expected behavior**
DS4 working over bluetooth after upgrading to new ds4windows version.
Other programs recognizing the DS4 the same way as before upgrading.

**Desktop (please complete the following information):**
 - Controller Make and Model: MSI gs63 7re
 - OS: Windows 10 Home 1909 (Microsoft Windows NT 10.0.18363.0)
 - DS4Windows Version 2.2.7_x64  and  2.1.23_x64

**Additional context**

Log - Bluetooth tentative connection on 2.1.23_x64:
https://pastebin.com/ELa92jZa

**Comment by Masamune3210** [comment]
make sure that scp vbus or anything involving the old scp program isn't installed, and make sure you have vigem installed

**Comment by mika-n** [comment]
Jay2Kings uses the ancient ScpVBus driver and it is known to cause problems (the ScpvBus does some not-so-official Windows driver tricks especially in BT). You need to cleanup every single bit of ScpvBus driver. Use google to find instructions how to uinstall all traces of it before installing the newer ViGem bus driver (used by this newer Ryochan7 fork of DS4Windows).

And you should try to run the debug version and provide the debug logfile here as .TXT attachment
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems
