### ISSUE TITLE
Disconnect BT does not trigger while charging

### ISSUE THREAD

**Issue by fchud** [Ryochan7/DS4Windows#1901]
Special Action **Disconnect BT** does not trigger while charging.

**Steps to reproduce the behavior**:
1. Add new action 'Disconnect from Bluetooth' with any trigger.
2. Disconnect USB from charger and PC.
3. Check if it works.
4. Connect USB to charger or PC.
5. Try again step 3.

**Expected behavior**
Don't know if it is intended, but I'd like to be able to disconnect from BT while charging via a special action, since holding PS for 10 seconds is ridiculous.

**Setup**:
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: Windows 10 x64, probably last update.
 - DS4Windows Version 2.2.6.

It's being a while since I notice this behavior, probably since before even version 2.

**Comment by Ryochan7** [comment]
This has been the case since at least Jays2Kings 1.4.52 if not earlier.

**Comment by fchud** [comment]
So, would it be addressed?

**Comment by Ryochan7** [comment]
That is the intended behavior so there is nothing to address. To do otherwise would interfere with the basic use of charging the controller while using the higher poll rate of the BT connection.

**Comment by ceedveed** [comment]
I noticed this too. But I just disconnect bluetooth before connecting to USB for charging.

**Comment by Ryochan7** [comment]
Just activate the **Quick Charge** option in the Settings tab. That will disconnect the Bluetooth controller when the app detects a USB connection if that is what you want. Again, the **Disconnect BT** special action is working currently as intended.
