### ISSUE TITLE
DS4 Windows droping/losing input wrapping

### ISSUE THREAD

**Issue by MrHuggles** [Ryochan7/DS4Windows#1903]
**Describe the bug**
While playing games like Dragon's Dogma: Dark Arisen or Dark Souls: Remastered the ds4 is having momentary lose of being disguised as an xbox controller and defaults back to being read by the game as a generic wireless controller (as windows sees it).  This results in confused button inputs as games will sometimes read certain inputs as "Wireless Controller" and others as "Xbox Controller".  This is being experienced over a wired connection with the controller.
**To Reproduce**
1. Boot up a game that actively changes hud to reflect when input methods are changed (such as switching between keyboard and gamepad).  Dragon's Dogma is a good test for this as it shows different inputs for keyboard, microsoft controller, and wireless controller.
2. Go into options to see the differences in default button layouts for wireless and xbox controllers.  Notice how d-pad inputs maintain xbox button hud, while face buttons and shoulder buttons are read as wireless controller inputs (by the change in button overlay in bottom right of screen).
3. Go into game and notice that buttons aren't resulting the the actions they should (i.e. Heavy Attack is Heavy Attack as found in xbox controller default setting; Light Attack is Heavy Attack as found in wireless controller default setting).

**Expected behavior**
For inputs to only be read as coming from an xbox controller.

**Screenshots**
Video - https://www.youtube.com/watch?v=q1Z-v3uxv-4

**Desktop (please complete the following information):**
 - DS4; CUH-ZCT2U
 - OS: Windows 10 Pro; Ver. 2004; Build 19041.804
 - DS4Windows Version [e.g. 2.1.5]

**Additional context**
It has been some time since I needed to use DS4Windows so multiple updates have since rolled out.  I did not have this problem on the last build I had used for the program.  My best estimate for when I used the program was 6-12 months ago.

**Comment by Ryochan7** [comment]
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues
