### ISSUE TITLE
Feature Request: LED Color data output to text file. 

### ISSUE THREAD

**Issue by nntb** [Ryochan7/DS4Windows#1904]
some games like Destiny 2 on Steam offer sending color data to the controller as you play the game. i would really like it if DS4 Windows could take this data and output it to a file, so i could use it to control stream elements or my monitors LED backlights ect.

**Comment by Ryochan7** [comment]
Out of scope. Also, the current virtual DS4 lightbar feedback routine is wrong and cannot be fixed without an update to the ViGEmBus driver. A request has been made upstream to provide the info needed to fix the problems with virtual DS4 controller feedback data.

Related to issue #1389
