### ISSUE TITLE
ds4windows freaks out on madagascar 2 escape to africa

### ISSUE THREAD

**Issue by minuteworld1** [Ryochan7/DS4Windows#1905]
when you start the game normally  without ds4, only the triggers, shoulder buttons and sticks work and they're mapped wrong. the game has native hotplugging support for xbox 360 controllers so i started the newest version of ds4windows and it automaticly picked it up as a 360 pad. every button works as supposed to however when using the stick, the game freaks out and switches constantly between xinput and the generic controller 1 2 3 4 buttons thus impeding progress.

**To Reproduce**
1. start mad2.exe with ds4 on and start game with dpad
2. once you're ingame, dpad no longer works to move, switch to using sticks. 
3. once you use the sticks, the character starts spazzing out and the on screen button prompts will change from "A B X Y" to "1 2 3 4"
TO NOTE- I am using the dualsense

**Expected behavior**
it was working as a 360 pad, was disappointed when the controls were conflicting

**Screenshots**

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: [e.g. Windows 10 Pro Build 2004]
 - DS4Windows Version [e.g. 2.1.5]

**Additional context**

**Comment by Ryochan7** [comment]
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues
