### ISSUE TITLE
Touchpad as mouse does not work after waking from sleep

### ISSUE THREAD

**Issue by ceedveed** [Ryochan7/DS4Windows#1908]
**Describe the bug**
After waking PC from sleep, the touchpad as mouse does not move the mouse cursor. Mouse button inputs still work. DS4 connected through bluetooth.

**To Reproduce**
1. Touchpad as mouse working before PC sleep, DS4Windows running
2. Sleep PC
3. Wake PC
4. Turn on DS4 controller.
5. Touchpad does not move mouse cursor
**Expected behavior**
Touchpad should still work as mouse cursor after PC wakes.

**Screenshots**

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: Windows 10 Pro Build 20H2
 - DS4Windows Version 2.2.7

**Additional context**
This can be resolved by stopping and starting DS4Windows (using the stop/start button, no need to exit). I typically don't have a mouse handy while using this PC in the living room, so this solution requires a mouse. Toggling Touchpad (PS + touchpad action) does not resolve issue.

I am not sure which version this started, but version 2.2.1 does not require stopping and starting DS4Windows in order to get touchpad as mouse working again after PC wakes. So I am using 2.2.1 for now.

**Comment by Ryochan7** [comment]
I cannot test Sleep functionality on my PC; it never wakes up. This would be on you to debug, fix and then send a pull request.

**Comment by Ryochan7** [comment]
Maybe the recent change for Auto Profile option loading might have fixed this issue?

**Comment by ceedveed** [comment]
> Maybe the recent change for Auto Profile option loading might have fixed this issue?

Thanks for updating this thread. I just jumped from 2.2.1 to 2.2.13. The issue is fixed!

I'm guessing the following change in 2.2.13 fixed it?:
"Have device hotplug routine enforce profile settings when using a temp auto profile"
