### ISSUE TITLE
[Issue] [8BitDo SN30 Pro+] Xinput produces drifting when analog sticks are in neutral

### ISSUE THREAD

**Issue by RavenMacDaddy** [Ryochan7/DS4Windows#1913]
**Describe the bug**

I use a SN30 Pro+ controller from 8BitDo.

I'm currently using the latest firmware at the time of writing which is 5,00, but I recall seeing this no matter the firmware version used for the controller.

This controller is used in Switch Pro mode which enables gyro functionality and the two extra buttons on the bottom left and right side if I'm using DInput.

When I use XInput through DS4Windows, the analog sticks input when in neutral are read as significantly off center resulting in drifting.

This is not the case if I use BetterJoy for XInput, or if I use Dinput only through DS4Windows.

Since I don't have a Switch Pro controller I don't know if this issue affects that controller as well when running XInput.

I'm posting this issue since I didn't see an open bug report when searching for "switch" on the github and haven't noticed the same issues when using a DS4 controller with XInput - hopefully I didn't miss anything.

**To Reproduce**

1. Make sure the controller is running firmware version 5,00 since this is the latest at the time of writing and hasn't produced any other apparent issues for the controller.
2. Use the controller with XInput provided by DS4Windows.
3. Run any of the following scenarios:

- Run the _Set up USB game controllers_ control panel in Windows and check the readings for the _Controller (XBOX 360 For Windows)_ entry; XInput, and you'll see that both of the analog sticks will be slightly off when looking at the readings - however, the following scenarios will produce much more easily visible results, and I will provide screenshots from those.
- Run the emulator Yuzu and check the readings when using the controller through XInput.
- Run the emulator Cemu and use the controller in either DSUClient mode or XInput directly - as long as XInput is the underlying API, the results will be the same.

**Expected behavior**

When in neutral, the readings for the analog sticks should not produce any sort of drifting as this is not the case when using XInput provided by the software BetterJoy or using the controller in DInput mode.

**Screenshots**

![image](https://user-images.githubusercontent.com/67732686/109378241-440af980-78d1-11eb-8f1e-caeb3a32a7e2.png)

![image](https://user-images.githubusercontent.com/67732686/109378422-b16b5a00-78d2-11eb-98f3-e6efaf430f1d.png)

**Desktop (please complete the following information):**
 - Controller Make and Model: 8BitDo SN30 Pro+ with firmware version 5,00
 - OS: Windows 10 Pro 20H2
 - DS4Windows Version 2.2.8

Thank you for your time.

**Comment by Techflame93** [comment]
i have got the same problem with a different "Pro Controller"

**Comment by Ryochan7** [comment]
More time put into writing the post than it would take to solve the issue

https://github.com/Ryochan7/DS4Windows/wiki/Settings#axis-zone-mapping
