### ISSUE TITLE
DS4Windows Virus

### ISSUE THREAD

**Issue by Saaber09** [Ryochan7/DS4Windows#1914]
I have installed ds4 version 2.2.7 and it gave me a blue screen after a few hours, does the program have any type of virus?

**Comment by Bastiti** [comment]
It doesn't, check for your blue screen error type. It might be 100 others reason.

**Comment by mika-n** [comment]
If is not possible to generate a blue screen of death screen from an application running in WinOS user space. Only hardware or device drivers running in kernel space are capable of generating BSOD errors. So, check your hardware and device drivers. But which one? Impossible to say from here with that little information you provided. DS4Windows uses ViGem device driver and it is running in kernel space, but you didn't specify which version of the driver you are using or WinOS version or DS4Windows logfiles.

**Comment by Ryusennin** [comment]
> does the program have any type of virus?

LOL, what kind of question is that? As if the developer would include a virus as part of the feature set /facepalm

**Comment by Ryochan7** [comment]
Use of ViGEmBus 1.16.112.0 is highly discouraged nowadays although it is the last ViGEmBus driver available for people not running Windows 10. Random failures in ViGEmBus have led to BSOD errors in the past. Virus scans have come up clean for the DS4Windows archives
