### ISSUE TITLE
Workaround for double inputs when wired?

### ISSUE THREAD

**Issue by LNBZero** [Ryochan7/DS4Windows#1915]
Hey there,

It's not exactly a bug but just how everything works which leads to annoyances. I mainly use my Dualshock 4 over blutooth and this is no problem at all. Has worked flawlessly for years thanks to DS4Windows. But more and more games seem to support it themselves which I actually find annoying rather than useful. Sticking to blutooth the games usually won't see the controller, even in Windows it won't receive inputs for the permanently added "Wireless Controller". Which again that's fine since DS4Windows adds an emulated 360 controller.

The problem starts when my controller is starting to run out of battery and I have to plug it in. Windows suddenly gets a second "Wireless Controller" which it does get input readings from. Some games do read those inputs as well resulting in double inputs. And yes, I know I can set up an Auto Profile for those specific games but since this only occurs when it's plugged in the games won't have any input when it's not wired.

Is there some method to avoid getting that extra controller when plugging it in? So you would only rely on the 360 emulated controller. That would be a workaround for me and possibly others that have this same issue.

**Comment by mika-n** [comment]
If the gamepad has the same MAC address both in BT and USB mode then DS4Windows knows that the usb connected device is actually the same gadget and won't create a new connection. But if the gamepad has different MAC addresses then DS4Windows assumes the new device is a new DS4.  Some fake copy-cat copies have different MAC addresses in BT and USB.

Alternative solution is to find a usb cable which can change the gamepad, but doesn't carry over DS4 data. I have several of those kind of mobile phone usb cables.

**Comment by LNBZero** [comment]
Thanks for your reply mika-n!

I don't have a copy-cat controller but an official Sony V.2 Dualshock 4 so we can rule that one out. DS4Windows also gives me the same MAC address in the HUD with both the Blutooth and Wired.

However the "Wireless Controller" (even though wired) that gets added to the devices isn't added by DS4Windows. It's being added even if DS4Windows isn't running. Maybe because Windows 10 has support for Dualshock by itself nowadays?

I still can't clarify where the other Wireless Controller is coming from. It doesn't get input from anywhere and is permanently there. I think the driver from ViGEmBus adds it during the installation but it just strikes me as odd seeing it's never used.

I would be interested in knowing what cable you're using. All cables I can find in webshops in my country all have data transfer. There's simply no market here for cables that only charge and don't have data transfer.

**Comment by mika-n** [comment]
those "charge only DS4 cables" came with various mobile phones, but don't know why those are "charge only" cables.

Anyway, you can make your own "charge only" usb cable by taping over the middle two pins in the USB header.
https://www.instructables.com/USB-Condom/

**Comment by LNBZero** [comment]
I've tried this method with 3 different cables today without success. The controller won't receive power at all if you cover up the 2 center pins.

**Comment by Bananasunn** [comment]
Hi folks,

I have the exact same problem. When I am using bluetooth the gamepad is perfectly working on my current game. Once I wire it even if ds4windows detect it correctly it seems windows is now able to get the controller and the game is switching in a broken xbox layout mapping.

I tried hide ds4windows, turning off steam for any interactions and emulating xbox 360 to workaround with the broken mapping but nothing successful. 

Windows detect multiple "wireless controller" when wired while only 1 when bluetooth is used (ds4windows' probably)

There is a way to test input in windows and something that I noticed is that L2/R2 triggers are mapped as on/off input on BT mode that is working. Once wired there is other input mapping and L2/R2 are now returning 0-100% input.

good luck to you I'll post something here if I have anything to try to fix it.

**Comment by Bananasunn** [comment]
My next test when I can : https://github.com/Ryochan7/DS4Windows/issues/1900#issuecomment-784865133

**Comment by LNBZero** [comment]
> Hi folks,
> 
> I have the exact same problem. When I am using bluetooth the gamepad is perfectly working on my current game. Once I wire it even if ds4windows detect it correctly it seems windows is now able to get the controller and the game is switching in a broken xbox layout mapping.
> 
> I tried hide ds4windows, turning off steam for any interactions and emulating xbox 360 to workaround with the broken mapping but nothing successful.
> 
> Windows detect multiple "wireless controller" when wired while only 1 when bluetooth is used (ds4windows' probably)
> 
> There is a way to test input in windows and something that I noticed is that L2/R2 triggers are mapped as on/off input on BT mode that is working. Once wired there is other input mapping and L2/R2 are now returning 0-100% input.
> 
> good luck to you I'll post something here if I have anything to try to fix it.

Hey Bananasunn,

Thanks for your input! Always glad to hear if there's other people with the same issue.

While no solution I can clarify something for you perhaps: The inputs you struggle with aren't "broken 360" inputs. They are native Dualshock inputs and Sony by default has a different mapping on their controllers. Among the lines of "Button 2" is the X (left) face button of an XBox controller but it's the Triangle (top) face button on a Dualshock controller. No idea why they ever did that, perhaps to avoid patent wars. It was the same problem in the past when we switched from Direct Input to 360 controllers/layouts.

**Comment by LNBZero** [comment]
Why was this closed? I just wasn't replying because I was waiting on a solution still.
