### ISSUE TITLE
Macro setting "repeat while held" doesn't save/work

### ISSUE THREAD

**Issue by WhiteSp1rit** [Ryochan7/DS4Windows#1916]
**Describe the bug**
Setting "Repeat while held setting" on a macro in Special Actions -> Hold Trigger doesn't save and doesn't work, it resets to "Play once" always and only plays once.

**To Reproduce**
1. Go to Special Actions -> New Action, select Multi-Action Button
2. Set trigger as "Square"
3. Go to "Hold Trigger", "select a macro"
4. press "Record", tap and release square, press "Stop record"
5. Select "Repeat while Held", save

**Expected behavior**
While you hold square button, square being continuously pressed and released is sent as output

**Desktop:**
 - Controller Make and Model: Sony DS4 v.1
 - OS: Win 7 Ultimate SP 1
 - DS4Windows Version 2.2.8 (didn't work in any earlier versions either)

**Comment by Ryochan7** [comment]
The "Repeat While Held" option only works for normal Macro actions. It does not work for Macros contained in a Multi-Action Button special action. That window needs to be changed to disable that combobox when editing such a Macro.
