### ISSUE TITLE
Huge delays between button presses and macro activation for Multi-action button

### ISSUE THREAD

**Issue by WhiteSp1rit** [Ryochan7/DS4Windows#1917]
**Describe the bug**
Using Special Actions -> Multi-action button introduces a huge delay between a keypress and macro activation.

Testing in the game reveals that recording and using a simple "press X, wait 30ms, release X" macro introduces a huge lag between key press and the game registering the input. 

Meanwhile if I map the same button that I used as a trigger for macro as X directly, game responds instantaneously.

**To Reproduce**
1. Go to "Special Actions"
2. Create a new action, set any Trigger as Square, set Multi-action button
3. Under "Tap trigger", select a macro
4. Record one square key press as a macro

**Expected behavior**
Pressing Square should register immediately, not after a huge delay

**Desktop:**
    Controller Make and Model: Sony DS4 v.1
    OS: Win 7 Ultimate SP 1
    DS4Windows Version 2.2.8

**Comment by mika-n** [comment]
the multi-action macro has those additional Tap/Hold/DoubleTap trigger options. The old macro code has certain "delays" there trying to identify if the button is just tapped, hold or double tapped before it knows what to do. It is not perfect logic, but the code is derived from a veeeeery old DS4Windows version and haven't been touched ever since. To be honest the whole macro logic would need a complete re-write.

**Comment by Ryochan7** [comment]
The delay times are not configurable but how do you think the app is supposed to distinguish between a Tap, a Hold, and a Double Tap? Just bind to a normal Macro if that is the behavior you want.

**Comment by WhiteSp1rit** [comment]
> The delay times are not configurable but how do you think the app is supposed to distinguish between a Tap, a Hold, and a Double Tap? Just bind to a normal Macro if that is the behavior you want.

I need to continuously press the same button as the one being held, while if you just press and release the same button it functions normally. How exactly do I accomplish this? If I bind a macro it will always execute
