### ISSUE TITLE
DS4windows will not recognise DS4 controller unless the program is stopped and started again

### ISSUE THREAD

**Issue by BitGrub** [Ryochan7/DS4Windows#1921]
**Describe the bug**
Been using a my DS4v2 for ages without issue, but recently this started happening. The first connection (via bluetooth or usb) after a computer restart works fine, but after disconnecting/turning off the controller, there's **no way** to connect it again without restarting the DS4Windows service. I mean, it connects to the PC I think, since the lightbar stops flashing and stays solid, but no devices are detected in the DS4Windows window.

**To Reproduce**
1. Connect DS4(v2) controller using your preferred method
2. Turn off/disconnect the controller
3. Try connecting again later
4. try not to cry

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2
 - OS: Windows 10 Pro N for Workstations 20H2 build 19042.844, Windows Feature Experience Pack 120.2212.551.0
 - DS4Windows Version: 2.2.8

**Additional context**
Restarting the DS4Windows service BEFORE attempting to reconnect doesn't work. Controller needs to be connected while the service starts for it to be recognised

**Comment by mika-n** [comment]
log files? Or even better, download the debug version and provide the debug logfile:
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

**Comment by Ryochan7** [comment]
Not sure if just a generic Hotplug problem or something else. Nothing to work with.

**Comment by BitGrub** [comment]
Really sorry for not being very helpful. Unfortunately I've had to reinstall windows, and the problem has gone away on its own. I'll post logs next time (if it happens again).

At least I know the problem isn't with my hardware
