### ISSUE TITLE
DualSense Charging shows 0% battery always

### ISSUE THREAD

**Issue by ACarvalhaes** [Ryochan7/DS4Windows#1927]
**Describe the bug**
When the Dualsense is charging it always shows 0%+, but if you unplug the USB and connect it through Bluetooth, it shows the real battery percentage.

**Screenshots**
![image](https://user-images.githubusercontent.com/68425924/110206841-0d585480-7e78-11eb-98fc-97f1db39b252.png)
![image](https://user-images.githubusercontent.com/68425924/110206853-1ea16100-7e78-11eb-8846-51536b98b8e5.png)

**Desktop (please complete the following information):**
 - Controller Model: Sony DualSense
 - OS: Windows 10 Pro 20H2
 - DS4Windows Version 2.2.9

**Comment by Ryochan7** [comment]
I have the opposite problem. I always get the proper reading when connecting the controller via USB. The reading when using BT is wrong sometimes with an invalid offset. Based on the readings from HID Report Inspector, I am going to blame this problem on the hardware.
