### ISSUE TITLE
Feature Request - change the power-down time

### ISSUE THREAD

**Issue by kalamalka** [Ryochan7/DS4Windows#1928]
This is not really bug, although this is something that bugs me about the DS4 controller. I am wondering if it would be possible to change the power-down time on the controller with some code. Presently I have to sit there for at least 10 seconds holding a button to power off the controller. I know it sounds silly, but 10 seconds times 10 times a day, times 10 days is 16  minutes! That's 16 minutes of time I would rather not be sitting around holding a piece of plastic doing nothing. Now imagine the time tally over a year's time.. I could imagine it being well into HOURS of time wasted, maybe even a day or more. 

I don't know if someone is savvy enough to figure out what part of the firmware has this delay, or if we are even able to alter the firmware, but I would really appreciate it !

**Comment by Ryochan7** [comment]
First off, 10 seconds of time is not that important. Second, that time delay is built into the DS4 and DualSense hardware; it has nothing to do with the software. And finally, the Disconnect BT special action (defaults to PS + Options) exists which occurs in software and happens instantly. This has been a non-issue for several years.
