### ISSUE TITLE
Any way to switch language?

### ISSUE THREAD

**Issue by djanthony93** [Ryochan7/DS4Windows#193]
I'd like to keep the app in english

**Comment by arkhillneo** [comment]
If you only want to keep in English, just delete this file "DS4Windows.exe.config", or Lang folder.
To switch to another language manually seems still in developing:
https://github.com/Ryochan7/DS4Windows/issues/169

**Comment by Ryochan7** [comment]
The next version of DS4Windows should have a functioning language switcher. As it is now, you have to either delete the folder associated with the locale that is being used (Japanese being under Lang\ja) or set your system locale to English.
