### ISSUE TITLE
Dualsense image pls!

### ISSUE THREAD

**Issue by Mircosfot** [Ryochan7/DS4Windows#1930]
Hi,

When my Dualsense is connected, i get always a Dualshock 4 image. But i want to use the mute button on my Dualsense to config also.
mybe it isnt a bug or issue, otherwise replace the thread, thank you.
So far great work with this awesome tool.

![DUSE1](https://user-images.githubusercontent.com/60817048/110317051-dfa41480-800b-11eb-9471-153b640f0f55.jpg)
![DUSE2](https://user-images.githubusercontent.com/60817048/110317063-e3d03200-800b-11eb-8a76-f40d105e9ca2.jpg)

**Comment by TheMasterDingo** [comment]
you have the mute button in the button list below the immage

**Comment by Mircosfot** [comment]
![DUSE3](https://user-images.githubusercontent.com/60817048/110353004-daa88a80-8036-11eb-9ffa-673902c4709f.jpg)
Yes, thank you. found it. but an image were better. i hope it will comming soon.

**Comment by pinospin** [comment]
Well, even Joy-Con and NS Pro controller don't have their own image but reuse Dualshock 4
So just treat Dualshock 4 as a generic controller

**Comment by mika-n** [comment]
sure it would be nice to have a specific image for all supported source gamepad types, but it is quite a lot of work to create and maintain those images (if there are some new button re-map features and those need an update to these images also). There is now already two images to maintain. Anyway, I don't see this image issue as prio-1 thing, but if someone wants to create a new image with all required hotspots then it would help

**Comment by Ryochan7** [comment]
Nobody seems to use the proper option that associates the Profile Editor with a currently connected input controller anyway. The Profile Editor does not inherently associate with an input controller when loaded from the Profiles tab; the Controller Readings tab will just keep checking for a controller in slot 1 during checks. As such, other images and associated control layouts would likely never get used if implemented.

It is not a big deal to me so it probably won't get done.
