### ISSUE TITLE
Is it possible to add touchpad output mode right stick or left stick ?

### ISSUE THREAD

**Issue by TheoPhilm** [Ryochan7/DS4Windows#1934]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: [e.g. Windows 10 Pro Build 2004]
 - DS4Windows Version [e.g. 2.1.5]

**Additional context**

**Comment by Ryochan7** [comment]
Not sure it would be useful. The DualSense touchpad seems easier to reach than the DS4 touchpad for me. However, it still seems like a second class input control for the DS4 unlike the Touchpads on a Steam Controller.

**Comment by Ryochan7** [comment]
Even with the DualSense controller, trying to use the Touchpad as a virtual LS or RS does not feel feasible. Need to change grip to even use half of the Touchpad and then the normal buttons become less accessible.
