### ISSUE TITLE
Mute button toggle?

### ISSUE THREAD

**Issue by Hexality** [Ryochan7/DS4Windows#1937]
Hi, is there a way to set up a macro toggle to the mute button that when pressing it, sends the macro and also turns the light on? (considering the pulsating/static set in the dualsense settigns)

Example: set the macro to toggle Discord mic on/off, toggle light on/off pressing the button (not connected to discord, just reactive to when you press the button)

**Comment by Ryochan7** [comment]
That is a good idea but I don't know how I would go about implementing that. Besides the changed light state, having the light state act as a toggle while keeping the output binding act as a press would be an issue.
