### ISSUE TITLE
Not able to open map in Warzone after updating to new DS4 release

### ISSUE THREAD

**Issue by CodexJeff** [Ryochan7/DS4Windows#1938]
**Describe the bug**
After updating to release 2.2.10 from 2.2.1,  the touchpad which usually opens the map in warzone, does not work. Reverting back to 2.2.1 has everything in a working state.

**To Reproduce**
1. Update driver 
2. Open warzone
3. Click on touchpad while in a game
4. Nothing happens

**Expected behavior**
Map of Verdansk should open when touchpad is single tapped in game.

**Screenshots**
N/A.

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony Dualsense
 - OS:  Windows 10 Education Build 20H2
 - DS4Windows Version 2.2.10

**Additional context**
I noticed that if I spam click the touchpad its sometimes work, but very rare. Also, it seems that releases after 2.1.1 all have the issue of it not working. At least from the releases I tried.

**Comment by clusidc** [comment]
I had the same issue with SnowRunner... Setting the Touchpad Mode to paasthrough fixed it for me:

![grafik](https://user-images.githubusercontent.com/2925320/111074782-04edc280-84e5-11eb-8ac5-2687721aa4de.png)

**Comment by CodexJeff** [comment]
Bless up, thanks so much it worked!
