### ISSUE TITLE
DS4Windows Not Launching

### ISSUE THREAD

**Issue by WyverianBrazenn** [Ryochan7/DS4Windows#1939]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: [e.g. Windows 10 Pro Build 2004]
 - DS4Windows Version [e.g. 2.1.5]

**Additional context**

I have the latest DS4Windows version but it won't start for some reason, it worked before resetting my laptop but now it won't. When I double click it, the circle loading thing near the cursor appears but it won't launch.

**Comment by mika-n** [comment]
logfiles? See %APPDATA%\DS4Windows\Log folder.
Windows EventViewer has any clues?
The latest version of .NET framework?
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#link-list

**Comment by Ryochan7** [comment]
Nothing to work with here. Closing
