### ISSUE TITLE
Cross anti-deadzone

### ISSUE THREAD

**Issue by Atyne** [Ryochan7/DS4Windows#1941]
Is there any way how I can set up cross anti-deadzone? Most games (where I would like to use anti-deadzone) have cross deadzone hardcoded (for example Assassin's Creed 3), so radial anti-deadzone doesn't help. Thank you.

**Comment by Ryochan7** [comment]
This is a feature people have requested before but I never got around to implementing; I didn't have an immediate use for it myself. I remember playing the AC3 DLC Tyranny of King Washington and it worked fine.

**Comment by Atyne** [comment]
It's so hard to aim with cross deadzone. Cross anti-deadzone is IMO the most lacking feature.
[https://www.youtube.com/watch?v=ULhOyHXK_3o](url)

**Comment by Ryochan7** [comment]
Got it implemented but I don't know if I like it. Maybe it will be something like the Square Stick feature. I didn't see a need for that feature when it was implemented. I finally found a direct use case for it later on; in that case, older DirectInput games benefited from it especially Shadows of the Empire where I used it.

The oldest issue I can find asking for this kind of feature is issue #685. Even with that issue, I made a comment stating that the feature was requested previously.

**Comment by Ryochan7** [comment]
Ended up installing AC3 to try out the new control scheme in the game. Control does feel better using a cross dead zone config especially when running. Radial works okay but it does feel a bit off by comparison.

**Comment by Atyne** [comment]
Thank you! To my surprise, I found out that AC3 is for some reason using 50% cross deadzone for looking around and 30% radial deadzone for aiming (combined with a little bit of axial deadzone on the vertical axis), so I probably won't be using it here anyway. But there are many other games using cross deadzone exclusively, like Hellblade, Life is Strange: BTS...most 3rd person games actually.

**Comment by Ryusennin** [comment]
Many games of the PS3 generation have different curve sensitivities for the left and right sticks, usually radial on the left and cross on the right. The cross deadzone is particularly aggravating in some FPS (Resistance, Metro, Rage).

In Dead Space 1 on PC, I had to make a profile to remap the right stick camera to the mouse -- with great results, but that doesn't work in all games. In Dark Souls 2, the movements with the left stick are more or less limited to 8 directions and cross anti-deadzone could prove very useful to improve that.

**Comment by Ryochan7** [comment]
Went back and forth on maybe changing the naming before publishing version 2.2.11. I ended up sticking with using Axial rather than Cross in the program. If I remember correctly, I think that is how InputMapper refers to that dead zone type as well.

**Comment by Atyne** [comment]
I like it, cross is basically axial on both X and Y axis combined, so axial is more general and it only makes sense since you can set it independently. It's much better now, thank you again! But it's not perfect. The next step would be to make it possible to combine axial anti-deadzone with radial deadzone, so we can get rid of that cross deadzone completely. Alternatively, being able to calibrate the right stick would also help.

**Comment by Ryusennin** [comment]
The axial anti-deadzone makes the camera significantly better in Assassin's Creed 2/Brotherhood/Revelations. It helps in AC3 but not by much, this game has an awfully bad curve sensitivity which is aggravated by high frame rates.

Still many games to test, but so far it's a welcome feature.
