### ISSUE TITLE
Gyro Output Mode: Mouse - calibration is broken

### ISSUE THREAD

**Issue by AdriandeLima** [Ryochan7/DS4Windows#1942]
## Describe the bug
If you have a problematic gyro, setting the gyro to ```Output mode: Mouse``` will result in the mouse constantly drifting. https://github.com/Ryochan7/DS4Windows/pull/1776 (gyro calibration option) fixed this in v2.2.4, but it broke again in v2.2.5 and has remained broken since (currently v2.2.10).

### Earlier related issues about this:
sorry to mention it again 😭😢, and thank you for your time and support!
https://github.com/Ryochan7/DS4Windows/issues/1878
https://github.com/Ryochan7/DS4Windows/issues/1727
https://github.com/Ryochan7/DS4Windows/issues/1859

### v2.2.10
1. Connect controller with glitchy gyro to DS4Windows, and edit the profile (```Gyro``` tab)
2. Set ```Output mode:``` to ```Mouse``` and save the profile
3. The mouse starts drifting. 
4. (```Gyro calibration``` is now available on all Output Mode pages) Click on ```Gyro calibration``` and save the profile
5. **The mouse continues drifting**

### v2.2.4
1. Connect controller with glitchy gyro to DS4Windows, and edit the profile (```Gyro``` tab)
2. Set ```Output mode:``` to ```Mouse``` and save the profile
3. The mouse starts drifting. 
4. Switch ```Output mode:``` back to ```Controls``` and click on ```Gyro calibration``` 

EDIT: 4.5. Then switch back to ```Output mode: Mouse``` and save the profile (reason for this is that ```Gyro calibration``` button only exists on ```Output mode: Controls``` page in v2.2.4)

5. **The mouse stops drifting**

## Additional notes
I tested the other gyro output modes (except ```Mouse Joystick``` - couldn't get it to do anything; and ```Passthru``` - no way for me to test) in v2.2.10, and calibration seems to work fine for them (or not be needed? the other modes didn't output any repeated noise/keypresses indicative of drift). It just seems to not be working with ```Output Mode: Mouse```.

## Screenshot
Here are my settings in version v2.2.4; I use exactly the same settings in v2.2.10
![image](https://user-images.githubusercontent.com/68482408/110864521-27e85e80-82ba-11eb-93f6-0d2eeb3448b2.png)

**Desktop (please complete the following information):**
 - Controller Make and Model: PICTEK HD-060 with gyro problem
 - OS: Win10 Pro v1909
 - DS4Windows Version: v2.2.4, v2.2.10

**Comment by Ryochan7** [comment]
Switch to Gyro Controls and mouse drift is removed. Image my shock.

On a related note, fixed device startup Gyro Calibration. Now the routine is reset when the initial input loop is started.

**Comment by AdriandeLima** [comment]
Re-read what I'd written, and indeed, 'twas ridiculous. 

I'd meant to say:

>## Expected behavior
>### v2.2.4
>1. Connect controller with glitchy gyro to DS4Windows, and edit the profile (```Gyro``` tab)
>2. Set ```Output mode:``` to ```Mouse``` and save the profile
>3. The mouse starts drifting. 
>4. Switch ```Output mode:``` back to ```Controls``` and click on ```Gyro calibration``` 
>
>EDIT: 4.5. Then switch back to ```Output mode: Mouse``` and save the profile (reason for this is that ```Gyro calibration`` button only exists on ```Output mode: Controls``` page in v2.2.4
>
>5. **The mouse stops drifting**

I've corrected the original post

**Comment by Ryochan7** [comment]
Ended up making a few changes regarding Gyro Continuous Calibration in the latest release. Fixed several cases when it would either not be used at all or have very few samples. Turns out I had not been using it pretty much the whole time even when using the DS4 or DualSense because the timers were set up to start too early; data would contain very few samples.

**Comment by AdriandeLima** [comment]
Thank you for implementing that! Testing v2.2.11 at the moment.

## Preliminary test results:
- Gyro drifts still, as since v2.2.4; calibration doesn't seem to do anything.
- Putting a deadzone of ```43``` seems to be a cutoff point - any lower, and it drifts. 
- Any higher, e.g. ```45```, and it doesn't drift noticeably when the controller is still. Need to test with some more games, as it feels a bit like the gyro mouse still tends to "settle" downwards during gameplay.

Wondering, did v2.2.4 accidentally implement some sort of increased deadzone, or did it do calibration differently?
