### ISSUE TITLE
Sony buttons on warzone

### ISSUE THREAD

**Issue by Danielo958** [Ryochan7/DS4Windows#1948]
is it possible to put the buttons on sony? I have my ps5 controller connected and I get xbox buttons in warzone. I have seen youtube videos where you can see the sony buttons

Thank u

**Comment by Mircosfot** [comment]
ist very simple to get this runnin:
![image](https://user-images.githubusercontent.com/60817048/111051933-1b4d3d00-8457-11eb-94b9-e138229b2b3d.png)
just emulate ''Dualshock4'' n have fun.
