### ISSUE TITLE
DS4Windows Fails to Launch when running as admin if Task Scheduler entry is removed/modified

### ISSUE THREAD

**Issue by rjmxtechnology** [Ryochan7/DS4Windows#1949]
**Describe the bug**
If you run DS4Windows as admin and set the startup to run as a task, then delete the task or modify it (I had exported it before deleting so I tried importing it but that didn't seem to fix it) , it will fail to launch when running as admin the next time

**To Reproduce**
1. Run DS4Windows as admin
2. Go to "run on startup" and set it to "Task"
3. Close DS4Windows
4. Run DS4Windows as admin again (will crash)

**Expected behavior**
Try to run DS4Windows as Admin again, but it will crash and show something similar to the logfile attached here in the logs
[ds4windows_log_20210313.6_taskschedcrash.txt](https://github.com/Ryochan7/DS4Windows/files/6135777/ds4windows_log_20210313.6_taskschedcrash.txt)

**Screenshots**

**Desktop (please complete the following information):**
 - System: Ryzen 2700x, RTX2070, 32GB DDR4@2667Mhz
 - Controller Make and Model: Sony DS3 Sixaxis
 - OS: Win10 2009 (20H2)
 - DS4Windows Version 2.2.1.0

**Additional context**
I went through with RegScanner and removed all the registry entries made on 3/13/21 (today) because that is when I first encountered the issue today, and that seemed to fix it, or it could have been fixed by running an older version of DS4Windows (tried v2.2.9 after a bunch of fussing around with trying clean installs) but I am inclined to believe it was something to do with the registry entries. This is because even on a clean install of DS4Windows in a new folder the issue would present itself.

**Comment by Ryochan7** [comment]
I'm sorry but this seems more like a user error more than anything else. You can delete the Task in Task Scheduler and DS4Windows will handle that scenario just fine. If you edit the registry manually or use some other means to try to remove the assigned RunDS4Windows Task then that is on you. It looks like the Task Scheduler package is finding some remnants of the original Task entry so DS4Windows will assume that it still exists.

The final call that fails is when the bat file path assigned to the Task does not correspond to the current DS4Windows directory. At that point, DS4Windows will try to delete the old Task entry and then fail.

**Comment by rjmxtechnology** [comment]
The task.bat was still there and it was producing this error. What I am saying is that it didn't seem to handle the scenario just fine otherwise I wouldn't have made the issue. Either way, I seemed to have fixed it but thought I would provide some feedback
