### ISSUE TITLE
disable light bar

### ISSUE THREAD

**Issue by shogunreaper** [Ryochan7/DS4Windows#195]
When the controller is off (or idle disconnected) the lightbar is  pulsing yellow while its charging.

how do i disable this?

**Comment by arkhillneo** [comment]
To disable light bar, simply set all RGB value to 0.
For the charging light, following picture, try to set it to "Normal".

![2018-01-18_093002](https://user-images.githubusercontent.com/35409070/35076245-67d1f572-fc32-11e7-8327-858188e7d916.jpg)

**Comment by shogunreaper** [comment]
thats what i have mine at.

**Comment by arkhillneo** [comment]
@shogunreaper 
1.Set all RGB to value 0
Or
2.At "While Charging" try to set "Color" to Black.
That's all what I do and it will turn off lightbar while charging and using.

**Comment by shogunreaper** [comment]
thats what i have it at

https://i.imgur.com/u0RWj0C.png

**Comment by arkhillneo** [comment]
@shogunreaper 
Are you using 1.4.109? If negative, try to update to latest version.
If it is latest version, then I have no idea. The setting works on my system.

It looks like you are using Windows7, I am using Windows10. Not sure if this makes different or not.

**Comment by shogunreaper** [comment]
yeah i'm on .109

**Comment by randu1459** [comment]
I believe that the yellow pulsing light (while charging) is a hardware feature. So if the controller is not actively connected to DS4Windows, the hardware is controlling the light. If I'm understanding your situation correctly, I don't believe that DS4Windows has any control over the controller in this state.
