### ISSUE TITLE
My PS5 controller doesnt start up

### ISSUE THREAD

**Issue by 214AnthonyP** [Ryochan7/DS4Windows#1950]
It used to work on an old version but now it doesn't on the newer version
[ds4windows_log_20210313.3.txt](https://github.com/Ryochan7/DS4Windows/files/6136128/ds4windows_log_20210313.3.txt)

2021-03-13 22:31:49.3001|WARN|ViGEm Device Plugin Failed. Closing connection.

**Comment by Ryochan7** [comment]
It is an internal ViGEmBus error. No choice but to reboot Windows. Be warned, you will get a BSOD when shutting down Windows.

**Comment by Ryochan7** [comment]
Finally got around to changing the severity of that log message with commit 69bd69af001174ca58e356ef95b3bed62bf8f1bb
