### ISSUE TITLE
Special action problem

### ISSUE THREAD

**Issue by MeHigh1101** [Ryochan7/DS4Windows#1951]
Hi, i use a dualsense controller and i have a problem when i want to save a special action. I tried to set the ps button as trigger to check battery life. Everytime i click save the ds4windows crushes. Any help pls?

**Comment by Ryochan7** [comment]
Need your log files. Also, just tried it and that works for me.

> Please provide a logfile as text file attachment with the new ticket (drag-and-drop the text file into a comment field, don't just copy-paste the logfile content as text because sometimes logfiles are quite long. You may have to rename the log file as TXT file before drag-and-dropping the file to a comment field).
>
> See "%APPDATA%\DS4Windows\Logs" folder for the latest logfile or use Logs tabpage in DS4Windows app to export the log content.

**Comment by MeHigh1101** [comment]
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/6137578/ds4windows_log.txt)
[ds4windows_log_20210314.3.txt](https://github.com/Ryochan7/DS4Windows/files/6137579/ds4windows_log_20210314.3.txt)
[ds4windows_log_20210314.4.txt](https://github.com/Ryochan7/DS4Windows/files/6137580/ds4windows_log_20210314.4.txt)
[ds4windows_log_20210314.5.txt](https://github.com/Ryochan7/DS4Windows/files/6137581/ds4windows_log_20210314.5.txt)
[ds4windows_log_20210314.6.txt](https://github.com/Ryochan7/DS4Windows/files/6137582/ds4windows_log_20210314.6.txt)
[ds4windows_log_20210314.7.txt](https://github.com/Ryochan7/DS4Windows/files/6137583/ds4windows_log_20210314.7.txt)
[ds4windows_log_20210314.8.txt](https://github.com/Ryochan7/DS4Windows/files/6137584/ds4windows_log_20210314.8.txt)
[ds4windows_log_20210314.9.txt](https://github.com/Ryochan7/DS4Windows/files/6137585/ds4windows_log_20210314.9.txt)

**Comment by MeHigh1101** [comment]
[txt.txt](https://github.com/Ryochan7/DS4Windows/files/6137589/txt.txt)

**Comment by Ryochan7** [comment]
What is the status of your Actions.xml file? The crash text makes it look like the file is corrupt.

**Comment by MeHigh1101** [comment]
It looks like that file was the problem. I deleted it and i tried again to save a special action and it works. Thanks a lot!! You are great! Keep doing great work!

**Comment by Ryochan7** [comment]
Bummer about the file. I ended up adding some exception handling at that point with commit a5b17d4b2aa47b1a2b67f9d15d4b5bc80b712d00. At least this type of problem would not result in an app crash anymore.
