### ISSUE TITLE
Cannot edit profiles names from within the app

### ISSUE THREAD

**Issue by Kanuan** [Ryochan7/DS4Windows#1953]
**Describe the bug**
DS4Windows doesn't let me edit the profile's name from withing the app, I need to manually edit it in the profile file name. 

**Expected behavior**
DS4Windows should let me rename the profiles from the profile editor screen

**Screenshots**

![image](https://user-images.githubusercontent.com/24910442/111089370-55c3e200-850a-11eb-89ff-29fbd6cbae78.png)

**Desktop:**
 - Controller Make and Model: Unrelated, as the problem occurs even when no controllers are connected.
 - OS: Windows 10 Pro 20H2 (19042.804)
 - DS4Windows Version 2.2.10 (though the same behaviour is happening in older versions now. Also tested on 2.2.9 and 2.2.6)

**Additional context**
- Profiles are located in the Program Folder and all the tests were made in folders that don't require elevated privileges to be accessed/edited (e.g.: Desktop)
- Profiles can be edited as usual, just can't change the name
- Running DS4Windows as an administrator makes no difference
- I think this started when I recently tried running DS4Windows as a task on version 2.2.10. Reverting this and running it as a program makes no difference. No changes to the task scheduler were made in other places that were not in the DS4Settings tab
- I was temporarily using the Beta Build of DS4Windows until version 2.2.10 was released, though I could edit profile names there
- HIDGuardian is installed, but I've been using it for over a year without problems
- Trying to edit the profile while DS4Windows is stopped makes no difference
- Log file of the latest Beta Build running inside DS4Windows 2.2.10 folder: [ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/6138072/ds4windows_log.txt)
- No anti-virus changes were made. Running Windows Defender

**Comment by Ryochan7** [comment]
I cannot remember why I changed that behavior but it is intentional; the answer is likely in a previously posted issue here. The only way to rename a profile currently is to rename the XML file in Explorer while DS4Windows is not running. Not really sure about changing this.
