### ISSUE TITLE
Right JoyCon not working correctly with DS4 emulation

### ISSUE THREAD

**Issue by jonathan570** [Ryochan7/DS4Windows#1956]
**Describe the bug**
When emulating JoyCons as a DS4 controller the right one bugs out. The joystick moves on its own

**To Reproduce**
1. Connect joycons
2. Set emulated controller as "Dualshock 4" Instead of Xbox 360 in the profile
3. Try to use the joycons in PS Remote play. The left one will work fine but the right one will bug out

**Expected behavior**
Both joycons to work just fine 

**Desktop (please complete the following information):**
 - Controller Make and Model: Nintendo Switch JoyCons
 - OS: Windows 10 Home 20H2
 - DS4Windows Version 2.2.10

**Comment by Ryochan7** [comment]
Not sure if you would have better luck with the latest release (2.2.11). It is working out fine for me there.
