### ISSUE TITLE
Sony DualSense controller disassociates at random, then reconnects itself

### ISSUE THREAD

**Issue by Zero-Starlight** [Ryochan7/DS4Windows#1957]
**Describe the bug**
It's unclear exactly what is going on, but without warning or any clear indicator, my DualSense will suddenly dissasociate itself and disconnect, only to reconnect a few seconds later.

**To Reproduce**
Steps to reproduce the behavior: None available that I have been able to determine.

**Expected behavior**
DualSense controller should continue to maintain connection either until I am done using it and power it off, or until the battery runs out.

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DualSense Wireless Controller (CFI-ZCT1W)
 - OS: Microsoft Windows 10 Pro 10.0.19042 Build 19042 (64 Bit)
 - DS4Windows Version 2.2.10 (Both public and debug)

**Additional context**
This issue does not appear to be caused by Exclusive Mode or HIDGuardian, and does not seem to be a faulty PS button as the macro I had set to swap profiles to indicate a faulty PS button did not trigger when this issue occured.
Debug Log File:
[Log 20210315.txt](https://github.com/Ryochan7/DS4Windows/files/6144358/Log.20210315.txt)

**Comment by mika-n** [comment]
Does this automatic disconnection occur after the gamepad has been idling for a long period of time? DS4Windows profile has "Idle Disconnect on BT" option.

If you don't use DS4Windows profile "idle disconnect" feature then it is possible that the PC has power-saving features to send USB and BT hosts to sleep state when there is no traffic for a while. Check those settings (deviceManager).

**Comment by Zero-Starlight** [comment]
I've gone ahead and disabled every single idle disconnect I could find, but I've had it happen during gameplay as well. We'll see what happens.

**Comment by Ryochan7** [comment]
Since the removal routine is run, I don't think some exception is happening in the input thread. This would make me think that there is maybe some read error at some point or the CRC32 checks fail more than 10 times in a session. That really should be 10 consecutive fails so that will have to be fixed in the DualSenseDevice class. Need to make sure to log those errors if they happen.

**Comment by Zero-Starlight** [comment]
I won't pretend I know what you're talking about there, but I appreciate you looking into it. I've made a few different changes to my setup, we'll see how it turns out.
Removed HIDGuardian, since the Exclusive Mode option has worked for my purposes just fine, and the switch didn't resolve this issue. I'll reinstall if necessary (or use HIDHide if/when it becomes available).
Tested potential signal interference due to a Bluetooth receiver on my desk being on during gameplay. (Left Dualsense on for a 30 minute period, BT receiver off, no disconnects.)
Swapped from the built in BT module on my motherboard (ASRock A520 AC) to a USB Bluetooth Dongle on the front of my case, had the controller on for several hours, no apparent disconnects, BT receiver was on.

I want to say the issue was simply signal interference, but that would suggest that the receiver is overpowering the controller but not the other way around, and with how infrequent and difficult to pin down the issue seems to be I'm not ready to call this resolved, as it could just as easily return this evening or tomorrow or next week. I'll keep using the debug version and will post the logs if and when more issues occur, and I'm happy to install any new versions you release in order to provide more detailed log files.

**Comment by mika-n** [comment]
DS4Windows app sends and read hundreds of packets within a second over BT. There has been cases with some copy-cat DS4 gamepads that those may work fine in so called "Pc-friendly mode" (=DS4 special features not enabled in BT mode), but fails to work once DS4Windows commands the DS4 pad to switch over to "native DS4 mode" and this way the BT traffic is increased (a lot more data coming in and a lot more data written out to BT link, ie two-way traffic).

Nefarious, who has created the ViGem virtual gamepad driver used by DS4Windows, find out during the latest DsHidMini+DS3+DS4Windows tests that some DS3 pads seem to die or get stuck if the pad is read or data written to too fast over BT. Probably some firmware bug or limitation in some DS3 copy-cats. Anyway, maybe this "flooding the pad with too fast too much" issue is something which applies to some DS4 and DS5 pads also? Or even BT hosts?

**Comment by Ryochan7** [comment]
At least now the CRC-32 issue has been fixed with the DualSense device class. It probably won't matter for the initial problem but at least this issue made me discover that problem.

**Comment by Zero-Starlight** [comment]
Hey folks, just wanted to pop in to add the log files I've got for the last 3 days. I unfortunately forgot to enable the debug build for today's log, but at this point I'm relatively certain that either the addition of the new bluetooth dongle, or the changes made in the most recent update to DS4Windows (or perhaps a combination of both) have resolved the issue. I'll close the issue for the time being, and hopefully I won't need to reopen it, though do let me know if you need me to provide further debug files or anything else.

[Log 20210317.txt](https://github.com/Ryochan7/DS4Windows/files/6173293/Log.20210317.txt)
[Log 20210318.txt](https://github.com/Ryochan7/DS4Windows/files/6173291/Log.20210318.txt)
[Log 20210319.txt](https://github.com/Ryochan7/DS4Windows/files/6173292/Log.20210319.txt)
