### ISSUE TITLE
Dulasense not rumble anymore after last update

### ISSUE THREAD

**Issue by PSerban93** [Ryochan7/DS4Windows#1958]
After last update ver. 2.2.10 my Dualsense Controller not vibrate anymore in games on Dualshock 4 options only on Xbox Controller option. If i test the rumble in DS4Windows it's works but in games it's show as DS4 but without rumble. If i install other version is working perfectly.

**Comment by mika-n** [comment]
Intentional. Rumble was temporarily disabled in DS4 output mode because of few issues with rumbling. But the good news is that the rumble is re-enabled in the next version.

**Comment by PSerban93** [comment]
Thank you very much for your answer!
