### ISSUE TITLE
Non Nintendo but Offically Licenced Switch Pro Controller not detected

### ISSUE THREAD

**Issue by AnUrbanPenguin** [Ryochan7/DS4Windows#1959]
I have a PowerA Enhanced Wireless Switch controller as found here (https://www.powera.com/product/powera-enhanced-wireless-controller-for-nintendo-switch-running-mario/).  Although this is not a nintendo product, it is an offically licenced switch pro controller and works perfectly on the switch console.

The controller is deteced and works in Steam fine with motion.  It is also deteced and works fine in Cemu and Yuzu which is where I would like to use it most often, but the motion is not natively supported, a third party tool, such as DS4Windows is required.

Upon opening the DS4Windows app there are no detected controllers. I have checked through the settings and everything appears correct with support for Switch pro controllers turned on.

As per the Wiki guide I downloaded the debug program but the output had nothing particuarly useful - see below

_03/15/2021 23:49:00: Starting...
03/15/2021 23:49:00: Connection to ViGEmBus 1.17.333.0 established
03/15/2021 23:49:00: Searching for controllers...
03/15/2021 23:49:00: Using Exclusive Mode
03/15/2021 23:49:05: Stopping Virtual Output Controllers
03/15/2021 23:49:05: Closing connection to ViGEmBus
03/15/2021 23:49:05: Stopping DS4 Input Controllers
03/15/2021 23:49:05: Stopped DS4Windows
03/15/2021 23:49:05: Starting...
03/15/2021 23:49:05: Connection to ViGEmBus 1.17.333.0 established
03/15/2021 23:49:05: Searching for controllers...
03/15/2021 23:49:05: Using Shared Mode_

The controller is connected to the PC via a PCIE Wifi / Bluetooth card which is Intel AX200 with the latest (Feb 2021) intel drivers installed.  The bluetooth version is 5.1.  In the device manager the controller shows as "Lic Pro Controller" [Presumably _licenced pro controller_?]  Steam straight up identifies it as Switch Pro Controller.

Any advice or ideas you have to resolve this would be greatly appreciated.  It would be really handy to have the Gyro working on WiiU / Switch games as some of them require it.

**Comment by mika-n** [comment]
The logfile content you copied is not from the debug version or not the full logfile (you removed something?). There should be several "DEBUG: xxxx" logfile lines. Did you run the DS4WindowsDebug.exe app instead of the DS4Windows.exe app?
Take a look at %APPDATA%\DS4Windows\Log folder and take the latest logfile from there, rename it as xxx.log.txt filename and drag-and-drop it here as an attachment.

**Comment by AnUrbanPenguin** [comment]
Im an idiot.  No wonder it didnt work properly, I ran it inside a sub folder of DS4Windows.  Not the root.  I have uploaded the log file.
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/6149020/ds4windows_log.txt)

**Comment by Ryochan7** [comment]
It looks like the only possible gamepad device does not have an exposed VID nor PID (both are listed as 0x0000). I don't see that particular controller on the official Steam Supported Controller database either but maybe that document is just out of date. As it is, there is nothing to work with. Besides the Debug build, maybe you can try HidNinja and find the gamepad device listed in that app; HidNinja is linked within DS4Windows under the Settings tab. That will list the device's exposed VID and PID along with the associated Hardware IDs given for the device.

https://support.steampowered.com/kb/5199-TOKV-4426/supported-controller-database

**Comment by AnUrbanPenguin** [comment]
Thanks for getting back to me.  I have attached the screenshot from HIDNinja.  it gives a little more information which should hopefully be something to work with.

I assume the steam list is outdated as it works flawlessly and identifies as a Switch Pro Controller straight away.  I also found this article on the steam community with input from Valve which suggests these controllers in some form or another have been supported since 2018? 
https://steamcommunity.com/app/353370/discussions/1/1752358461531576359/
https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/1705073202075628993
![HID Ninja](https://user-images.githubusercontent.com/80722888/111545668-50ff6800-876e-11eb-8ed9-e12fc1f20eaa.png)

**Comment by AnUrbanPenguin** [comment]
I have been doing some searching online and had a look through the issues listed on BetterJoyForCemu and users there have also reported issues with this controller not working with that application, most likely due to PID and VID being 0x0000.

Interestingly someone had posted the Hardware ID of their controller at in this comment [https://github.com/Davidobot/BetterJoy/issues/268#issuecomment-643425989] and it identical to mine posted in the screenshot above. Both are;

_HID\{**00001124-0000-1000-8000-00805F9B34FB**}_VID&00020000_PID&0000_

Could it be that the key to getting these controllers to work is that the hardware ID is used?

**Comment by AnUrbanPenguin** [comment]
After doing some further research it appears that hardware ID will not be of any use as that particular hardware ID is a generic one.  

However I did have a further idea.  It has a USB charging port.  Perhaps that port can be used for other things?  So I plugged it in and windows seemed to recognise a device.  Strangely it was nor recognised as normal USB device or Game controller though.  So after doing some digging I found it under Human Interface Devices just listed as "USB Input Device".

Upon inspecting some of the properties it shows under the "Bus reported device description" as _NSW Enhanced Wireless Controller Rechargable_.

It now also shows in HID Ninja WITH a PID and VID when connected to USB.  I would assume the PID and VID would be the same via Bluetooth and USB?  Hopefully!
![Controller](https://user-images.githubusercontent.com/80722888/111725810-aa938f80-885f-11eb-9cd6-ed52be0296da.png)

**Comment by mpgiii** [comment]
Just wanted to comment how Steam handles the controllers with no PID or VID (coming up with 0s).

https://github.com/ValveSoftware/steam-devices/blob/master/60-steam-input.rules#L50

They seem to check for its name.

**Comment by Ryochan7** [comment]
That is a bad way of checking and Steam is not a good example anyway. Valve failed with their own Steam Controller in many ways. Steam Input is now even worse than it was thanks to the Deck UI.

In the end, you bought a terrible controller
