### ISSUE TITLE
Dualsense not recognized anymore.

### ISSUE THREAD

**Issue by LuuisRomero** [Ryochan7/DS4Windows#1960]
So a few hours ago everything was fine until an hour ago. Whenever I try to start Ds4windows with my dualsense, the program automatically stops, I press start again and the controller got recognized by a second and then it stops again. Version is 2.2.10 and Windows version is the last one.

**Comment by mika-n** [comment]
logfiles?
rebooted?

**Comment by LuuisRomero** [comment]
Yes, Even rebooted the problem persisted yesterday. But today I’ve powered up my pc and the controller was regnogniced by DS4Windows but not in Warzone for some reason.
