### ISSUE TITLE
Some Chinese language localization caused UI issues

### ISSUE THREAD

**Issue by arkhillneo** [Ryochan7/DS4Windows#197]
There are seems some localization caused UI location shift issues on Chinese language UI.
Tested with Language-Switch branch merged version. OS Windows 10 Pro x64.

This is Englis language UI(to be as a reference):
![2018-01-18_185356](https://user-images.githubusercontent.com/35409070/35094944-d77dbde4-fc81-11e7-9aaf-6ad2066a6df4.jpg)

This is Traditional language Chinese UI.
1.Touch pad area disappear issue at bottom.
2.Flush HID option overlapping issue.
3.Hotkey/About option disappear issue.
![2018-01-18_185109](https://user-images.githubusercontent.com/35409070/35095045-1fc445dc-fc82-11e7-819f-0b7eeed9915a.jpg)

This is Simplified Chinese language UI:
1.Mouse Acceleration option too close to right side issue.
2.Hotkey/About option disappear issue.
![2018-01-18_185853](https://user-images.githubusercontent.com/35409070/35095305-f2ae7292-fc82-11e7-9fe8-526ff29c91fc.jpg)

**Comment by arkhillneo** [comment]
@Ryochan7 
Hi, thanks fixed the issue.
But the "hotkey/about" option is still missing in Chinese UI(Both zh-Hans and zh-Hant)

English UI:
![2018-01-26_130239](https://user-images.githubusercontent.com/35409070/35425844-46d7ba88-0299-11e8-958e-b0ba8c35c63e.jpg)

Traditional Chinese UI:
![2018-01-26_130154](https://user-images.githubusercontent.com/35409070/35425845-48231b4e-0299-11e8-8ea9-f791fcae2acd.jpg)

**Comment by Ryochan7** [comment]
That location of that label was set outside the bounds of the main form so it was not visible. The About label has been re-positioned and it is now visible in both translations.

**Comment by arkhillneo** [comment]
It is fixed, thanks.
