### ISSUE TITLE
my controller is not working properly anymore after windows/ds4 update

### ISSUE THREAD

**Issue by CarlosSSC** [Ryochan7/DS4Windows#1974]
**Describe the bug**
i updated windows yesterday in the night and updated ds4 today in the morning, and now my buttons are mirrored (i believe), my right stick is my left stick, my a button is now the b button, pause is now select and so on, does anybody have or had this problem? i have already restarted and i have already made 3 new profiles in case that the buttons were not configured properly but it is not the case, i am also using an original ds4 and yesterday in the morning everything was working correctly before i updated everything.
also when trying to use gamepad tester buttons appear correctly but they have latency or something because i have to wait a few seconds for them to show on screen, I have already downloaded ds4 2.2.9 in case it was an app problem but it didn't changed anything.

**Expected behavior**
for the buttons to work correctly

**Screenshots**
my settings 
![image](https://user-images.githubusercontent.com/80538989/111662601-4d4efe00-87cd-11eb-9e78-e6276850ebd6.png)
![image](https://user-images.githubusercontent.com/80538989/111663953-850a7580-87ce-11eb-9781-90fc591282d1.png)

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: [e.g. Windows 10 Pro Build 20H2]
 - DS4Windows Version [e.g. 2.2.11]

**Additional context**
i am also seing 2 controllers on gamepad tester and a "wireless controller" on control panel but i haven't configured anything like a wireless controller, also buttons appear correctly and on time when i check on Xinputchecker, but not when i check on gamepad test

**Comment by Ryochan7** [comment]
> i am also seing 2 controllers on gamepad tester and a "wireless controller" on control panel but i haven't configured anything like a wireless controller

https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues
