### ISSUE TITLE
Touchpad doesn't work in game.

### ISSUE THREAD

**Issue by ActionSlacks** [Ryochan7/DS4Windows#1976]
**Describe the bug**
Ever since version 2.2.0 the DS4 touchpad doesn't respond in-game. On the Windows OS screen, the touchpad still works as a mouse in every way, just not in games.

**To Reproduce**
I copied my DS4Windows folder so I have two identical start points.
Folder A I let update to the newest version; Folder B stays at v2.1.23
I launch the newest version, make sure the emulated controller is DS4, and play a few different DS4 compatible games. The touchpad fails to register.
I close down the new version, load 2.1.23, play the same games and the touchpad works.

**Expected behavior**
The touchpad to work as intended.

**Screenshots**

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: Windows 10 Pro Build 19042
 - DS4Windows Version 2.1.23

**Additional context**

**Comment by mika-n** [comment]
Have you tried "Passthru" touchpade mode in a profile settings?
There is now 2.2.13 version also which you might wanna give a test run.

**Comment by ActionSlacks** [comment]
That seems to have done it. Thank you so much.
