### ISSUE TITLE
Copycat function doesn't stick after Disconnection or Reboot

### ISSUE THREAD

**Issue by Techflame93** [Ryochan7/DS4Windows#1977]
**Describe the bug**
i need the Copycat function enabled to use my controller but it doesn't stick after a reboot or a controller disconnection
**To Reproduce**
1. Go to Settings--> Device Options--> Select your controller-->enable copycat
2. Disconnect the bluetooth DS4 controller
3. Connect it again, the copycat function will not be enabled
4. in C:\Users\YourUserNameHere\AppData\Roaming\DS4Windows\ControllerConfigs.xml
there actually is a file which should tell DS4Windows to mantain the copycat option enable by telling it the controller's MAC address but it doesn't work
5. DS4Windows says "ControllerConfigs.xml can't be found." after the connection but the file is actually there

**Expected behavior**
The option Copycat should stay after a reboot or after i diconnect the controller
**Screenshots**
https://ibb.co/MSwM1bv

**Desktop (please complete the following information):**
 - Controller Make and Model: Chinese Sony DS4 v.2 Knockoff. it is idendified by DS4Windows as a (DS4 v.1)
 - OS: Windows 10 Pro Build 2009
 - DS4Windows Version 2.2.11
Wed, 17 Mar 2021 20:05:46 GMT

**Comment by Ryochan7** [comment]
The file does not get saved until the window is closed.

**Comment by Techflame93** [comment]
> The file does not get saved until the window is closed.

i know that, i opened it to show you the content of the file

**Comment by Ryochan7** [comment]
Okay. Confirmed that the setting is not read back in when reconnecting a DS4. The binding will still show the proper checked status  when the Device Options window is opened again while the controller is still connected.

**Comment by Ryochan7** [comment]
Broke this in commit c8b9fc928ca07362ad4f77b80f8bf40270b7bbae. Device specific settings were never loaded in this case. The invalid element tag has been changed and extra error checking for wheel calibration data has been added for loading.

**Comment by Ryochan7** [comment]
This was a big enough issue to push out a hotfix release immediately. Version 2.2.12 fixes this problem.

https://github.com/Ryochan7/DS4Windows/releases/tag/v2.2.12

**Comment by Techflame93** [comment]
> This was a big enough issue to push out a hotfix release immediately. Version 2.2.12 fixes this problem.
> 
> https://github.com/Ryochan7/DS4Windows/releases/tag/v2.2.12

Thank you very much! works perfectly now! i will also donate some money, you deserve it
