### ISSUE TITLE
Sensitivity

### ISSUE THREAD

**Issue by crunchycrouton** [Ryochan7/DS4Windows#1978]
Hi, does the sensitivity reduce the maximum output? I was doing some testing and it seems like that's the result. I assumed sensitivity would reduce it's responsiveness, not the max output...

![Untitled](https://user-images.githubusercontent.com/6507066/111834910-a3ee3200-88ca-11eb-9500-3a193d1a51da.png)

**Comment by Ryochan7** [comment]
It acts as a simple multiplier. If you set the sensitivity below 1.0 then it will limit the max output. The Sensitivity modifier is the most basic modifier and left in for backward compatibility with older Jays2Kings build profiles. Changing, at least, Dead Zone and Max Zone would probably be what you are looking for. That will change the minimum and maximum input points that generate output. Anti-dead Zone and Max Output can then be used to change the output range if you want; I don't use the Max Output modifier in any of my profiles.
