### ISSUE TITLE
audio bug with some specific games

### ISSUE THREAD

**Issue by Ghostlyboo** [Ryochan7/DS4Windows#198]
hey i've recently noticed a weird audio bug with my headphones that are plugged into my DS4, which is plugged into my PC with a USB cable.
it started with fortnite, most audio would only play on the left channel (mostly only audio effects happening the 3D of the game, like gunshots/other players walking), but audio like the music and some menu effects play on both channels as normal, i thought it was a problem with the game that'll get patched out someday, but today when i tried playing a game called the turing test i've noticed the same exact problem, menu effects/game music play as it normally would, but things in the game world only come out from the left channel.
at first i tried uninstalling and reinstalling my motherboard's realtek audio driver until i noticed it uses it's own driver.
so what i tried to do is plugging my headphones to my monitor (which is connected with hdmi to my GPU), and the problem got fixed, also plugging my headphones directly to my PC fixes it.
after that i tried running jays2kings DS4Windows to see if it's a new bug, but it had the same problem, i also tried without any DS4Windows running and it had the same problem.
im not too sure, but i guess the problem is with the driver? ScpDriver? if that's the case is it even possible to solve this bug on DS4Windows's end?
ill try uninstalling ScpDriver and trying without it later and report back, if audio works at all without it

**Comment by Ryochan7** [comment]
All DS4Windows does is control the volume of the audio device. I don't know what could be causing the problems that you are describing especially when only one channel works at some times but both channels work in other situations. If you plug the controller, don't run DS4Windows and then the problem still occurs then something else is happening that is outside the control of the program.

I use a BT connection most of the time so I do not test the audio device regularly.

**Comment by Ryochan7** [comment]
I don't know if the recent updates (version 1.4.114 and later) would have done anything about this issue. The only issue that I noticed that has been resolved is that volume transitions seem smooth now. Beforehand, the audio would crack sometimes when changing the volume of the audio device. I had used the Sony adapter for a few hours while watching videos and I did not run into any audio problems.
