### ISSUE TITLE
Mario Cart 8 Deluxe - FitGirl Version - Cant detect controller and crashes

### ISSUE THREAD

**Issue by puscinator** [Ryochan7/DS4Windows#1981]
Tried to install latest DS4 windows, (Configured 1 & 2 Player)
Installed Mario Cart 8 Deluxe - Fitgirl Version (Yuzu)
Run Game and selected 2P game
On load of screen it loads Yuzu control popup - Pressed OK
Crashes

Note:
Single Player works properly

**Comment by Ryochan7** [comment]
Sounds more like a beta broken emulator to me. I honestly didn't even know a Switch emulator existed until this. Try it with physical Xbox 360 controllers if you can.

**Comment by AdriandeLima** [comment]
There's 2 Switch emulators that I know of: [Ryujinx](https://ryujinx.org/) and [Yuzu](https://yuzu-emu.org/). They're both in very early development, so bugs like this are expected. For some reason, the repacking/piracy scene has recently decided to start packing Switch games with emulator builds and distributing them as standalone games, despite the emulators being at very early (and buggy) stages of development.
