### ISSUE TITLE
No rumble on emulated DualShock

### ISSUE THREAD

**Issue by kin-patsu** [Ryochan7/DS4Windows#1982]
**Describe the bug**
Despite 2.2.11 supposedly bringing back rumble to emulated DualShock controllers, controller still refuses to vibrate

**To Reproduce**
1. Try any game that supports rumble (tested RetroArch playing Crash Bandicoot 3 - Warped and Dead Cells)
2. Do any action supposed to make the controller vibrate
3. Controller doesn't vibrate

**Expected behavior**
Controller should vibrate

**Desktop:**
 - Controller Make and Model: Sony DualSense
 - OS: Windows 10 20H2
 - DS4Windows Version: tested latest (2.2.13) and 2.2.11

**Comment by Ryochan7** [comment]
Doubt DirectInput support in RetroArch supports rumble at all. Gamepad Test vibration tests work fine when emulating a DualShock 4. The rumble option is mainly meant for games that have true native DualShock 4 support (reading HID reports directly).

**Comment by kin-patsu** [comment]
> Doubt DirectInput support in RetroArch supports rumble at all. Gamepad Test vibration tests work fine when emulating a DualShock 4. The rumble option is mainly meant for games that have true native DualShock 4 support (reading HID reports directly).

I'm fairly sure that several DS4Windows versions ago the rumble used to work in RetroArch, without using 360 emulation. I will give a try to older versions just to be sure
