### ISSUE TITLE
Special Action - Load a profile trigger conflict 

### ISSUE THREAD

**Issue by UnknownLink** [Ryochan7/DS4Windows#1984]
**Describe the bug**
When any input on the controller is set to a keyboard action it interferes with special action Load a Profile

**To Reproduce**
1. Launch DS4Windows
2. Edit Profile, change any button to keyboard output.
3. Switch to Special Actions, create New Action with Trigger set to same button that had been changed to keyboard action.
4. Set action to Load a profile, set desired profile to switch to and save all settings.
5. Upon Trigger sequence action is not loaded.

**Expected behavior**
Switch to specific profile via trigger buttons

**Desktop (please complete the following information):**
 - Sony DualSense
 - OS: Windows 10 Pro Build 20H2
 - DS4Windows Version 2.2.13

**Additional context**
Using other special actions work fine 
Swipe Touchpad To Switch Profiles and -command LoadTempProfile.<controller#>.<profile name> also bypass this

**Comment by mika-n** [comment]
seems to work here. Maybe this is a specific type of macro and button mapping issue? Maybe you should post the profile you use and specialActions.xml file as zipped attachment?

**Comment by UnknownLink** [comment]
[DS4W.zip](https://github.com/Ryochan7/DS4Windows/files/6215900/DS4W.zip)
Here you go and It's still present in 2.2.15

**Comment by Maxis-BUG** [comment]
Same problem on version 3.0.6 (fresh install). Tested with DualSense and DualShock 4 in 64-bit Windows 10 (20H2). If you bound the SPECIAL ACTION to a mouse or a controller it will work, but not with a keyboard button (Microsoft Digital Media Keyboard 3000).
