### ISSUE TITLE
Gyro reading (DualSense controller)

### ISSUE THREAD

**Issue by MatteoRTX** [Ryochan7/DS4Windows#1985]
**Describe the bug**
When I put the controller on the table or on the floor, the Gyro reading is not at the center of the square but slightly below. When I turn the controller from left to right or vv. , or from up to down and vv. sometimes the behaviour of the reading isn't linear but seems a bit sinusoidal.

If I put the gyro on mouse mode and I put the controller on the table, the mouse doesn't move, so probably the reading is fine. But sometimes if I power on the Joystick and DS4 handling it in my hand, and then I put the controller on the table, the mouse tends to move at costant speed upwards, slowly.

If I perform the calibration, DS4 **doesn't** correct the reading and the point is still below the middle point of the square in the reading tab, but it corrects the self-movement of the mouse, which now doesn't move if I don't move the controller.

**To Reproduce**
1. Launch DS4Windows, connect DualSense controller and put it on a flat surface
2. Click on 'Edit'
3. Go to 'Readings' tab

**Expected behavior**
I expect the reading of the gyro to be exactly on the center point.

**Screenshots**
This is the reading when I put the controller on a flat, in plane surface.
![gyro](https://user-images.githubusercontent.com/72089528/112169948-f002e480-8bf2-11eb-9c33-8d8b7cdaf46d.jpg)

**Desktop (please complete the following information):**
 - Sony DualSense Wireless Controller (DS5) CFI-ZCT1W
 - OS: Windows 10 Pro 20H2
 - DS4Windows 2.2.13

**Comment by baesik** [comment]
Gyro drift has been prevalent in DS4Windows for me since forever. Even on a brand new DS4 controller. There's also no documentation on proper calibration methods. Hope this gets resolved because having my controller drift steadily to the left with BOTW is frustrating.

**Comment by Ryochan7** [comment]
> I expect the reading of the gyro to be exactly on the center point.

You ever notice the grips make the controller naturally slope down when resting on a surface? Seems like you have not.

I do notice the non-linear behavior of Tilt Left and Tilt Right with the DualSense. The only data conversion being done is a simple division. The range seems accurate so I guess it is just how the IMU in the DualSense presents the data; the IMU in the DS4 seems to behave a bit differently. I'll look into it but I doubt anything in DS4Windows is at play.

**Comment by Ryochan7** [comment]
Yes. The raw data from the DualSense IMU seems to confirm that a curve is applied at the hardware level to the Accel X coordinate.
