### ISSUE TITLE
Issues with Rewired Unity plugin?

### ISSUE THREAD

**Issue by liandris** [Ryochan7/DS4Windows#1986]
Hello. I'm having issue trying to make a DS4 work with a recent Unity engine game, which uses Rewired plugin for controller support.

It works with Steam Input enabled, and with Steam Input disabled. But if I let ds4windows manage the controller, the game refuses any input while still detecting controller presence. Tried both xbox and ps4 mode.

Is there something that can be done about this?

**Comment by liandris** [comment]
I see now that disabling exclusive mode makes the game work. Even if I use xbox mode it will detect the ps4 controller though. But that seems strange, like it just refuses to work with whatever ds4windows tries to feed it. Is this a known thing?
I wonder if there is something ds4windows doesn't do enough or if there is something in the game or Rewired plugin that deliberately detect stuff similar to ds4windows and block its data.

**Comment by mika-n** [comment]
Must be game specific thing or exclusive mode doesn't work (ie. the game still see both physical DS4 and the virtual xbox360 gamepad). The DS4Windows logfile should tell you if exclusive mode works. Or if you take a look at JOY.CPL controlPanel applet (run joy.cpl command) then you should see just one gamepad if the exclusive mode worked.

There is a new sheriff in town doing the hiding thing. Tool called "HidHide" from the same author who wrote the ViGem virtual gamepad driver.
https://github.com/ViGEm/ViGEmBus/releases
https://github.com/ViGEm/HidHide/releases/tag/v1.0.30.0

**Comment by liandris** [comment]
Actually, I found in this specific case that somehow Steam was the issue.
If I launch the game from Steam - gamepad doesn't work. If I launch it from .exe - it all works like expected, but Steam overlay doesn't load. Everything else Steam-related worked, so it's not the case of some kind of no-Steam mode.

I see HidHide is W10 only so I can't test it.
