### ISSUE TITLE
ViGEm Device Plugin Failed.

### ISSUE THREAD

**Issue by Reconer000** [Ryochan7/DS4Windows#1990]
**Describe the bug**
Ds4Windows starts, then immediately stops. This happens with and without a controller connected.

**To Reproduce**
1. Open DS4Windows
2. Wait ~1 second

**Expected behavior**
DS4Windows to stay running.

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DualSense (CFI-ZCT1W)
 - OS: Windows 10 Pro 20H2
 - DS4Windows Version 2.2.13

**Additional context**
I havent been able to get ds4windows working for me at all for the longest time, for various reasons.

[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/6199316/ds4windows_log.txt)

**Comment by Ryochan7** [comment]
The advice is right there in the Log message. Not much to do but reboot Windows like it says. It is an internal error in ViGEmBus.
