### ISSUE TITLE
DualSense accelerometer and gyroscope are interchanged in UDP server 

### ISSUE THREAD

**Issue by gimdh** [Ryochan7/DS4Windows#1992]
**Describe the bug**
When connected to DS4Windows' UDP server, each gyro values represent accelerometer values and vice versa.

**To Reproduce**
Connect DualSense, set gryoscope mode as passthrough, turn on UDP server, and then attach UDP client. In my case, I used latest Dolphin emulator (5.0-13603).

**Expected behavior**
Send data of gyro as gyro and of accelerometer as accelerometer

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DualSense (CFI-ZCT1G)
 - OS: Windows 10 Pro Build 20H2
 - DS4Windows Version **2.2.14**

**Comment by Ryochan7** [comment]
Another issue where the poster does not know the difference between a Gyroscope and an Accelerometer. PadTest shows the data is being passed to the UDP server as expected. Also, profile settings don't matter with the UDP server. Raw values are passed from the raw state.
