### ISSUE TITLE
[REQUEST] Add emulated Razer Hydra mode

### ISSUE THREAD

**Issue by pinospin** [Ryochan7/DS4Windows#1994]
So recently I found out that there are some kind of motion controller specifically designed for PC games
It is compatible with many PC games, either native or custom designed
Basically I think it's a good idea to let Joy Con emulate the Razer Hydra movement (although Razer Hydra use other kind of motion control)
Also it has just enough amount of buttons that Joy Con have
![image](https://user-images.githubusercontent.com/71922495/112662702-93215b80-8e8a-11eb-97b9-b0f57e874348.png)

**Comment by Ryochan7** [comment]
> It is compatible with many PC games, either native or custom designed

False statement. Hardly any PC games had native support for it; the main PC game that had any form of native support that I know of was a mod for Portal 2. Almost all PC games have to be played using KB+M emulation with SendInput like DS4Windows already does. There is no gamepad emulation support in the mapping software used with the Razer Hydra.

There is no current way to emulate a Razer Hydra controller that I know of. The only benefit I could see from doing that would be to then emulate Oculus Rift controls through another mapping layer. That is not really practical. Just emulate from the JoyCon data directly and skip a processing pass.

From what I have seen from the DirectedInput YouTube channel, DS4Windows can provide better controls than what the Razer Hydra is capable of even though the JoyCons are inferior hardware. There are some extra binding options in the Razer Hydra software that is not possible in DS4Windows but Mouse controls seems worse with the Hydra software.

https://www.youtube.com/user/directedinput
