### ISSUE TITLE
assign rumble extra option has a problem

### ISSUE THREAD

**Issue by asp0909** [Ryochan7/DS4Windows#1997]
**Describe the bug**
assigning the rumble option to multiple buttons does not work

You can assign the rumble option to multiple buttons and functions, but ds4 only takes a single assignment.

the test is being carried out on a dualsense control in bluetooth signal

ds4 version, the last one to date .... but the problem persists for a long time, I do not have a dualshock 4 to compare but before switching to dualsense this function worked correctly assigning rumble in multiple buttons
![Captura](https://user-images.githubusercontent.com/29218473/112710470-7dfafb80-8e8f-11eb-919f-961066644d48.PNG)

**Comment by Ryochan7** [comment]
The extras values are assigned but only the last one listed in the profile XML file is used. Will look into this.

**Comment by asp0909** [comment]
exactly ..... thank you friend

**Comment by Ryochan7** [comment]
Found the root of the problem. The other buttons not being active force the rumble state to 0,0 before any rumble can be fired.

**Comment by asp0909** [comment]
I forgot to tell you that the same thing happens if the color of the led is changed ...

**Comment by Ryochan7** [comment]
This change seems to be good enough.

**Comment by Ryochan7** [comment]
The change is included in version 3.0.0

https://github.com/Ryochan7/DS4Windows/releases/tag/v3.0.0

**Comment by asp0909** [comment]
tested ... works perfect now! Thank you
