### ISSUE TITLE
Pro Controller Weird Analog readings

### ISSUE THREAD

**Issue by Techflame93** [Ryochan7/DS4Windows#1999]
Hello! if i connect my (fake) pro Controller while using DS4Windows it just makes the analogs work like this
https://ibb.co/pL2JLdz
basically they are not centered, is there any setting that i should change to make it work properly?
If i connect the controller WITHOUT using Ds4Windows the website https://gamepad-tester.com shows that the analog are centered correctly

**Comment by Ryochan7** [comment]
Dead controller more stable than active controller. Also,

https://github.com/Ryochan7/DS4Windows/wiki/Settings#axis-zone-mapping
