### ISSUE TITLE
Mute microphone

### ISSUE THREAD

**Issue by diogocalgaro** [Ryochan7/DS4Windows#20]
I use the Sony dongle and a cellphone headset plugged in the DS4 audio jack. When I open the DS4Windows.exe, the microphone gets muted. I can only use it again when I reboot my PC.
The output audio remains working fine.

**Comment by Ryochan7** [comment]
This probably has to do with the output report being used to activate rumble. There is a workaround to make sure the headphone output volume stays the same. I guess something similar will have to be done to make sure the microphone volume does not change either. I don't know which byte in the output report would be used for microphone volume. Also, I don't know if the current class being used to monitor the headphone volume can be used to monitor the microphone volume as well.

**Comment by diogocalgaro** [comment]
Just to complete the info: the audio output to the earphones works fine, apparently, before and after open ds4win. Just the microphone input is that stops working. However it came back to work after closing ds4windows, it doesn't need to reboot the PC.

**Comment by Ryochan7** [comment]
I am just getting around to testing this. After looking around, I didn't find any information about what might control the microphone volume control in the output report. Some exploratory testing seems to have led me to an answer to this problem. When no output reports are sent, the microphone still functions as expected. It is only after output reports are being sent to the controller that problems being.

Through trial and error, it looks like byte 21 in the output report controls the microphone volume of the DS4. Recording works fine when sending output reports with a value being sent for that byte. It looks like it should be possible to keep the microphone working when the controller is being used in DS4Windows. The major hurdle is grabbing the appropriate volume level.

**Comment by Ryochan7** [comment]
A minor change to the DS4Audio class was all that was needed to grab the Windows volume for the microphone and use it in output reports.

**Comment by Ryochan7** [comment]
It looks like the proposed change should work just fine and this issue will be fixed in the next release. I hardly even use the headphone jack on the DS4 so having access to the microphone wouldn't have been something I would have worried about. It will probably help out quite a few people so it is good that a fix was found.

**Comment by diogocalgaro** [comment]
It is working fine now.
Thanks!
