### ISSUE TITLE
Updater Hangs on saying yes to application close for new version installation

### ISSUE THREAD

**Issue by rjmxtechnology** [Ryochan7/DS4Windows#2000]
Upon a new version being available, I click install and then it just freezes after clicking yes to close the program for the update. Not sure why this is occurring. Could it be due to running ds4windows as admin?

 - Controller Make and Model: DS3 with bthps3 and dshidmini
 - OS: Win 10 20H2
 - DS4Windows Version 2.2.15

Not sure what logs would be helpful if any for this. What is interesting is that I am able to update by manually overwriting the files in the folder with the ones from the new version and then the new version is installed and works without issues, only the updater doesn't work.

**Comment by Ryochan7** [comment]
> Could it be due to running ds4windows as admin?

If you launch DS4Updater manually as a normal user then that explains it. The updater would get stuck in a loop attempting to kill DS4Windows but it will fail due to lack of permission. The updater will continue to see DS4Windows running and try to kill it again.

**Comment by rjmxtechnology** [comment]
> If you launch DS4Updater manually as a normal user then that explains it. The updater would get stuck in a loop attempting to kill DS4Windows but it will fail due to lack of permission. The updater will continue to see DS4Windows running and try to kill it again.

The thing is I am running it as admin not a normal user, so I am confused as to what is going on
