### ISSUE TITLE
ViGEm Device Plugin Failed (DS4 v.2 wired)

### ISSUE THREAD

**Issue by Liebloss** [Ryochan7/DS4Windows#2002]
**Describe the bug**

Starting DS4Windows connects my DS4 v.2 controller for about half a second before it disconnects with the error in the log attached. "ViGEm Device Plugin Failed"

Re-tested with the debug version of DS4Windows with the error in the other log attached. "Sequence contains no matching element"

**To Reproduce**

1. Launch DS4Windows.
2. Connect my DS4 controller.
or..
1. Connect my DS4 controller.
2. Launch DS4Windows.

**Expected behavior**

For the controller to connect and work.

**Desktop (please complete the following information):**

 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: Windows 10 Home Version 20H2 | Build 19042.867
 - DS4Windows Version: 2.2.15 with normal use. 2.2.13 with debug

**Additional context**

DS4Windows worked flawlessly up until I attempted to connect a 2nd controller (Switch Pro) which failed. Stopping then starting the Plug and Play service fixed this issue. Since then I haven't been able to connect the DS4 v.2 controller or the Switch Pro successfully.

Attempted to reboot pc (as per the request in the log), delete and redownload DS4Windows, reinstall ViGEm, update windows, reinstall controller in device manager, uninstall controller then disable Plug and Play before reconnecting controller. All with no luck.

Controller works fine in steam and inputs are all accounted for in the Windows built in "game controllers" setup.

Controller connects to DS4Windows fine when set to emulate a DS4 controller.

[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/6217239/ds4windows_log.txt)
[ds4windowsdebug_log.txt](https://github.com/Ryochan7/DS4Windows/files/6217240/ds4windowsdebug_log.txt)

**Comment by Ryochan7** [comment]
The only resource then might be to uninstall any previously associated Xbox 360 controllers created by ViGEmBus. Open the Device Manager, expand the View menu and check **Show hidden devices**. Scroll down and find the **Xbox 360 Peripherals** section and expand it. Uninstall any devices that show a Location of **Location [n] (Virtual Gamepad Emulation Bus)** in the device's Properties window

![xbox_hidden_device_man_2](https://user-images.githubusercontent.com/581968/112751976-4dea5000-8f96-11eb-88a7-aa55b0405cbc.png)
.

**Comment by Liebloss** [comment]
Actually almost shed a tear from how simple that was and how much time I put into trying to fix this. Had no idea there was a hidden device list. Fixed 100%. Thank you for the heckin quick as heck response. Much appreciated <3
