### ISSUE TITLE
Bluetooth Dongle vs. Sony Dualshock dongle

### ISSUE THREAD

**Issue by Mister-Curious** [Ryochan7/DS4Windows#2007]
**Describe the bug**

 To describe my issue I must preface this that the DS4Windows controls are still working as intended, but the game is responding to the dongle being present differently, despite that the emulated controller is the one sending input to the game. The issue is that with a normal Bluetooth dongle and DS4W my game (Fallout4) will display correct button prompts, but using the Sony Dualshock 4 dongle and DS4W I get a button prompts bug.

When I was simply using a Bluetooth Dongle along with DS4W, the '_Wireless Controller_' shown in **joy.cpl** would be disabled, and only the emulated device would respond to input. Sony Dualshock 4 dongle _BOTH_ of the devices are receiving input, (with the Dualshock device locked at the top slot). I thought that perhaps the game was receiving input from the actual DS4 controller, but while troubleshooting unmapping a few buttons in DS4W proved the game was indeed receiving input from the emulated controller (XBox). 

The mismapped texture issue is a [known bug](https://www.nexusmods.com/fallout4/mods/395/?tab=bugs&BH=0) but this issue is not present when using a normal Bluetooth dongle. So at this point I am just trying to understand why the game interprets DS4W input differently depending on which BT connection is used. 

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS:  Windows 10 Pro Build 20H2
 - DS4Windows Version: 2.2.14.0

**Comment by Ryochan7** [comment]
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues
