### ISSUE TITLE
Dualsense Haptic Feedback stops working when enabling DS4Windows

### ISSUE THREAD

**Issue by LyG23** [Ryochan7/DS4Windows#2009]
When i first connect my Dualsense controller it comes with a driver and gets detected as both a Wireless Controller and Audio Device.
I can then go to the sounds settings for the controller and enable speaker fill in the audio enhancements tab, this results in me getting haptic feedback.
But when i launch and enable DS4Windows the haptic feedback is suddenly lost and the only way for me to get it back is by disabling DS4Windows then removing and reinstalling my Wireless controller Device from the control panel.

**Comment by orangpelupa** [comment]
workaround: completely uninstall DS4 windows and install a fresh one. Then use the DEFAULT profile. DO NOT TOUCH the profile option.

now HD vibration and rumble works with DS4windows (the LED will stay purple/pink instead of blue)

**Comment by Ryochan7** [comment]
Copy pasta from another post

> Comments about video: Bad idea and wrong info.
>
> Anyway, this will likely never happen. I have tried audio based rumble and I hate it. It is not HD rumble and it feels very wonky. I used Voiceemeter to expose the haptic speakers to Windows apps in my tests.
> 
> DS4Windows will continue to utilize the rumble emulation provided by the DualSense hardware by default. If you want audio based haptics, the option is still available. Just uncheck the **Enable Rumble Emulation** setting, close the Controller Type Options window, and finally re-connect the controller. Re-connecting the controller is necessary to reset some flags on the hardware.
> 
> ![dualsense_rumble_emu_setting](https://user-images.githubusercontent.com/581968/113026601-de6b9080-914e-11eb-8223-53991d5a65f4.png)

**Comment by LyG23** [comment]
> Copy pasta from another post
> 
> > Comments about video: Bad idea and wrong info.
> > Anyway, this will likely never happen. I have tried audio based rumble and I hate it. It is not HD rumble and it feels very wonky. I used Voiceemeter to expose the haptic speakers to Windows apps in my tests.
> > DS4Windows will continue to utilize the rumble emulation provided by the DualSense hardware by default. If you want audio based haptics, the option is still available. Just uncheck the **Enable Rumble Emulation** setting, close the Controller Type Options window, and finally re-connect the controller. Re-connecting the controller is necessary to reset some flags on the hardware.
> > ![dualsense_rumble_emu_setting](https://user-images.githubusercontent.com/581968/113026601-de6b9080-914e-11eb-8223-53991d5a65f4.png)

Nice that worked! Thank you :p
