### ISSUE TITLE
[TODO] Might need help with HidGuardian AffectedDevices list template

### ISSUE THREAD

**Issue by Ryochan7** [Ryochan7/DS4Windows#201]
Some minor helper methods for HidGuardian have been added to DS4Windows. Among those methods is a way to have DS4Windows write an AffectedDevices list to the system registry. So far, only entries for my two controllers have been added (USB and BT). The current template looks like this.

```
HID\VID_054C&PID_05C4
HID\VID_054C&PID_09CC&MI_03
HID\VID_054C&PID_0BA0&MI_03
HID\{00001124-0000-1000-8000-00805f9b34fb}_VID&0002054c_PID&05c4
HID\{00001124-0000-1000-8000-00805f9b34fb}_VID&0002054c_PID&09cc
```

Community involvement will likely be required to add more relevant devices to this list. I will also take a look at the InputMapper version of the AffectedDevices list and see what relevant entries can be taken from that file.

**Comment by TristanYoung** [comment]
I added all of the input devices used in the InputMapper version.  I assumed they were all various DS4-compatible game controllers.  There's at least 4 wireless game controllers I know of, but only have the PID's for two of them.  I can try to find others if you'd like.
