### ISSUE TITLE
[feature request] Dualsense HD haptic vibration by mirroring audio into "wireless controller speaker rear channels"

### ISSUE THREAD

**Issue by orangpelupa** [Ryochan7/DS4Windows#2011]
Even better if it have low-pass filter option. so only low freq audio triggers the hd haptic vibration.

this video may give more context: https://www.youtube.com/watch?v=uFxMT2Pg_PU

**Comment by Ryochan7** [comment]
I forgot that the flag is reset when closing to the connection to the DualSense as well. So you can just hit **Stop** and then **Start** to reset the controller and allow audio based haptics. That was put in place mainly with Steam in mind.

**Comment by orangpelupa** [comment]
thank you, unfortunately, that disables rumble. with steam, the fake HD vibration works alongside with legacy rumble.

while on DS4windows (with rumble emu enabled) hd vibration works alongside legacy rumble as long as the LED color didn't change to blue. Dunno why.
