### ISSUE TITLE
Using with DS5 it doesn't work into PS4 game titles on Playstation Now

### ISSUE THREAD

**Issue by honeycube** [Ryochan7/DS4Windows#2012]
Good afternoon!

I have PC, Dualsense 5 Controller, Windows 10, latest DS4Windows 2.2.15, installed PS Now latest version 11.5.

I tried using DS4Windows with DS5 (connected via Bluetooth), and it's doesn't work only into PS4 game titles on Playstation Now, but  it works fine into PS3 game titles.

When I launch the game, it is launched. Then I see on screen: "press any button to start" . I pressed any button on my DS5 controller and nothing is happened. 

It doesnt't detected i on PS4 titles (on Playstation Now), for e.g.,
1. Ace Combat Skies Unknown
2. Detroit: Become a Human
3. Horizon Zero Down.
4.  ... others

And the reWASD works fine with my DS5 on this titles, so problem is in DS4 Windows only.

Please, check.

**Comment by Ryochan7** [comment]
I don't have access to Playstation Now so I have no way to test it. First off, is Exclusive Mode working for the DS5 controller? If not then the PS app will likely attempt to open the real controller interface which would be a dead controller due to the mode switch.

Other than that, maybe the app does not like way the extended API works in ViGEmBus. I am going to assume the lack of Exclusive Access is the more likely problem.

**Comment by honeycube** [comment]
> I don't have access to Playstation Now so I have no way to test it. First off, is Exclusive Mode working for the DS5 controller? If not then the PS app will likely attempt to open the real controller interface which would be a dead controller due to the mode switch.
> 
> Other than that, maybe the app does not like way the extended API works in ViGEmBus. I am going to assume the lack of Exclusive Access is the more likely problem.

@Ryochan7  Thanks for response. I've just turned on option "Hide DS4 Controller". The PC was restarted. And still nothing changed in this case, I see the same behaviour.

It seems that it's ViGEmBus' issue.

**Comment by ZleMyzteX** [comment]
Yes, that means exclusive mode. If you look into the log section, are there any errors mentioning exclusive mode? 
To my knowledge there are some programs that block the use of exclusive mode, maybe it didn't work?

**Comment by hak8or** [comment]
Just chiming in here to say I am seeing the same issue, with Vermintide 2 as another example game (PS4) on PS Now with a PS5 DualSense controller. I also tried the "Hide DS4 Controller" in DS4Windows with no luck. Humorously enough, the "X" button does work when pressing the PS logo on the controller to bring up options, and then navigating in there for "Vibration Settings" or selecting anything else. It's just not getting past the dreaded "press x to start" start screen. For comparison, I have no issues with the PS3 games (Resistance 3 as an example, wow it's a fuzzy low resolution mess on PS Now for some reason).

Also tried in "HID Hide Configuration Client" hiding the "Sony Interactive Entertainment Wireless Controller" (with of course "Enable HID Hiding" checked) while leaving the "Sony Computer Entertainment Wireless Controller" un-hidden, with similarly no luck.

@Ryochan7 if you still do not have access to PlayStation Now, I would be happy to send you $20 for 3 month's access, with the assumption that if you don't get it to work by end (or just take the money and spend it on some pizza instead without working on this) then then that's life. :laughing: 

```none
06/02/2021 21:05:14: DS4Windows version 3.0.6
06/02/2021 21:05:14: DS4Windows Assembly Architecture: x64
06/02/2021 21:05:14: OS Version: Microsoft Windows NT 10.0.19042.0
06/02/2021 21:05:14: OS Product Name: Windows 10 Pro
06/02/2021 21:05:14: OS Release ID: 2009
06/02/2021 21:05:14: System Architecture: x64
06/02/2021 21:05:15: Running as User
06/02/2021 21:05:15: HidHide control device found
06/02/2021 21:05:15: DS4Windows not found in HidHide whitelist. Adding DS4Windows to list
06/02/2021 21:05:16: Starting...
06/02/2021 21:05:16: Connection to ViGEmBus 1.17.333.0 established
06/02/2021 21:05:16: Searching for controllers...
06/02/2021 21:05:16: Using Exclusive Mode
06/02/2021 21:05:23: Found Controller: A0:AB:51:C7:B8:45 (USB) (DualSense)
06/02/2021 21:05:23: Associate DS4 Controller for input DS4 #1
06/02/2021 21:05:23: Controller 1 is using Profile "ps4". Battery level is 100%
```
