### ISSUE TITLE
[Question] First commit to implement DualSense?

### ISSUE THREAD

**Issue by tnt-debug** [Ryochan7/DS4Windows#2015]
Hi,

This is the first commit to implement compatibility with DualSense?

https://github.com/Ryochan7/DS4Windows/commit/99c29b44120afbd42791debe1d58e48485e9551b

Thanks and great job.

**Comment by Masamune3210** [comment]
DS4Windows already has support for the DualSense... Or is this in addition to what already exists?

**Comment by tnt-debug** [comment]
I mean, i have a fork from Jun 2020, and I want to know which is the first commit of DualSense to apply on my fork.

Thanks!

**Comment by Ryochan7** [comment]
Not going to look further in the Git log but that is probably it. DS4Windows version 2.1.17 (released 2020-11-19) was the first public release to support the DualSense in any capacity. At that point, rumble and lightbar support only worked over USB as full communication over Bluetooth had not been figured out yet. Version 2.1.18 (released 2020-11-28) added support for rumble and lightbar support over BT.

Despite having added support for the DualSense around the time the controller was released to the public, I have only recently had a chance to really use it for playing some games. More time was spent working out JoyCon support and getting some more unique play cases figured out. The DualSense does not offer much more for PC use than a DS4 does although the form factor of the DualSense is better.
