### ISSUE TITLE
Update opens the wrong web page when failing

### ISSUE THREAD

**Issue by CodingAir** [Ryochan7/DS4Windows#2017]
**Describe the bug**
The updater tries to open `https://github.com/Ryochan7/DS4Updater/releases/tag/v%7BUPDATER_VERSION%7D` which leads to an 404 GitHub page since the placeholder will not be replaced by the version.

**To Reproduce**
Update to a new version and let the updater fail (v2.2.15 -> v3.0.0).

**Expected behavior**
Open the correct updater repository.

**Screenshots**
![image](https://user-images.githubusercontent.com/23747243/113406192-59c97e00-93ab-11eb-95d5-530b7ec2f1ef.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - DS4Windows Version 2.2.15

**Comment by Ryochan7** [comment]
Not sure what happened with that string. Got the URL generation fixed now

**Comment by CodingAir** [comment]
Thanks a lot!
