### ISSUE TITLE
Can't see Dualsense controller after 3.0.0 update

### ISSUE THREAD

**Issue by avsha114** [Ryochan7/DS4Windows#2018]
**Describe the bug**
After the latest update (3.0.0) DS4WINDOWS stopped recognizing my DualSense controller.
I updated to .NET 5.
I've been using the app for a long time with no problems. I configured the device IDs in HIDNINJA and that's always worked.
Now the program just won't recognize any controllers.
So I tried to reinstall DS4WINDOWS and it recognized my controller in shared mode (shows twice in control panel). So I added it to HIDNINJA again and restarted my PC and it stopped recognizing again. the controller light stays blue and DS4WINDOWS shows no controllers.
How to make my Dualsense controller to show up in the new version with exclusive mode?

**To Reproduce**
Just connect the controller wirelessly with bluetooth.

**Expected behavior**
It should recognize my controller with exclusive mode.

**Screenshots**

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DualSend
 - OS: W10 20H2
 - DS4Windows Version 3.0.0

**Comment by Ryochan7** [comment]
I forgot to bundle the .NET 5 version of HidGuardHelper app

**Comment by coryetzel** [comment]
My 1st gen DS4 no longer works either.

**Comment by avsha114** [comment]
> I forgot to bundle the .NET 5 version of HidGuardHelper app

Ok good to know it's not on my end...
Waiting for the fix :)

**Comment by Ryochan7** [comment]
Got an update out

https://github.com/Ryochan7/DS4Windows/releases/tag/v3.0.1

**Comment by Ryusennin** [comment]
Hotfix works neat with DS4 v1 and v2.

Also tested on Win7 + ViGEm 1.16 and it seems to be a-ok (played RDR2 half an hour online).

**Comment by adrijeet** [comment]
I am still facing this issue on W10 v20H2. Not detecting DS4 v1.
