### ISSUE TITLE
'Color by Battery %' for Lightbar not working - UPDATED

### ISSUE THREAD

**Issue by Mister-Curious** [Ryochan7/DS4Windows#2020]
**Describe the bug**
The Lightbar is not changing color while the status of the battery changes. 

**To Reproduce**
1. Go to 'Lightbar Tab.'
2. Click on _'Color by Battery %'_ 
3. Move Full Slider to Green and empty Slider to Red
4. Witness that even on full charge light is never green and on empty does not turn red. 

**Expected behavior**
When the battery percentage is showing at 100% that the Lightbar display the color green, and when the battery percentage is showing at 0% that the Lightbar display the color red. 

**Screenshots**
![image](https://user-images.githubusercontent.com/81539091/114316324-e8c74c00-9ab7-11eb-819a-06d8d2b4e647.png)

**Desktop (please complete the following information):**
 - Controller Make and Model: Dualshock 4 (numerous models)
 - OS Windows 10 Pro Build 20HN
 - DS4Windows Version 2.2.1.4

**Additional context**
I cant for the life of me figure out how to get _'Color by Battery %'_ working with DS4Windows. I can say that the profile color option works fine, but when I edit a profile and chose 'Color by Battery %' in the Lightbar tab, hit Apply to the changes in the profile and save, nothing changes and the profile color is still present on the controller. Color by % is ticked. 

Also like to add one thing; When I close DS4Windows (or stop the service) the lightbar color is not released, meaning I have to power off my controller and power it on again to see its default color. Is this normal?

Any help is appreciated!

**Comment by Mister-Curious** [comment]
oh I would also like to add one thing; When I close DS4Windows (or stop the service) the lightbar color is not released, meaning I have to power off my controller and power it on again to see its default color. Is this normal?
Thanks!

**Comment by shinra358** [comment]
If you mean closing the process manually by saying stopping the service, I am also having this issue. It's not that it's not releasing the lightbar color, it's just not turning the controller off when it is closed through the process (i made an issue for it)

**Comment by Mister-Curious** [comment]
@shinra358 Yes, this is my issue as well. I thought it wasn't released but that was because my default color was the same as the chosen color. It was only after I changed my default color in DS4Windows that I realized this as well. 

By chance are you able to get 'Color by Battery %' working properly? I have posted here and on the Reddit with no replies about how to get it working effectively.

**Comment by shinra358** [comment]
Color by battery % works for me. But unchecking the option makes ds4windows crash.

**Comment by Mister-Curious** [comment]
I got mine working (**sort of**) 
Using the settings for colors seen above will go from WHITE to RED (when it should be going from GREEN to RED).
