### ISSUE TITLE
Updater Often Fails and Needs to be Opened Manually

### ISSUE THREAD

**Issue by Peekofwar** [Ryochan7/DS4Windows#2024]
**Describe the bug**
Quite often when DS4 Windows gets an update, it will fail to update and ask that I redownload it. This usually brings me to a missing page on the updater Github page. What I've found is that I can manually open the updater executable as administrator, and it works fine.

**To Reproduce**
1. When prompted to update at restart, hit "yes."
2. Occasionally it will fail.
3. It will open a page in your default browser that throws a 404 error.
4. Navigate to your DS4 Windows installation directory and open DS4Updater.exe as administrator.
5. There should be no error this time.

**Expected behavior**
When I initiate an update from an update prompt at login, it should update with no issues.

**Screenshots**
![ds4updater_404page](https://user-images.githubusercontent.com/10189526/113485769-2d256d00-9464-11eb-9658-1b12faa7883c.JPG)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 Pro version 20H2 (OS build: 19042.867)
 - DS4Windows Version 3.0.0 (updating to 3.0.1)

**Additional context**
This is not the first time I've had this problem. I've had it happen in previous versions as well.

**Comment by Ryochan7** [comment]
Fake portable programs are a bad idea. People are going to use them wrong and place them intentionally where they don't have write access. And then blame the programmer for it.

Also, that URL string was fixed in version 3.0.1. Somehow the `$` string interpretation prefix was not omitted.
