### ISSUE TITLE
DS4Windows fails to install ViGEmBus drivers

### ISSUE THREAD

**Issue by eXhumer** [Ryochan7/DS4Windows#2025]
**Describe the bug**
ViGEmBus drivers fails to install successfully with the driver install menu on DS4Windows. Need to manually install ViGEmBus for DS4Windows to properly work.

**To Reproduce**
1. Open DS4Windows for first time (with selecting user data path as AppData).
2. Click on step 1 on driver install page and check ViGEmBus install status.

**Expected behavior**
Embedded ViGEmBus installer to work without requiring to download anything externally.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro Build 20H2
 - DS4Windows: 3.0.1

**Comment by benjaminjacobreji** [comment]
I face this issue too, even with Program Folder option, same issue
I am on a fresh install of Windows 10

**Comment by phiter** [comment]
Had the same problem. I fixed it by installing manually downloading it from https://github.com/ViGEm/ViGEmBus/releases

**Comment by eXhumer** [comment]
This has been fixed in the master branch, it will be fixed in the next release. You will have to manually download it manually from the link provided above until the next release is live.

**Comment by benjaminjacobreji** [comment]
Ahh okay, no worries.
Thank you
