### ISSUE TITLE
Input delay on DS4 v1 controller when using HidHide in conjunction with DS4Windows

### ISSUE THREAD

**Issue by tonebacas** [Ryochan7/DS4Windows#2026]
Input delay when using HidHide from  ViGEm to hide a physical Dualshock 4 v1 controller, emulating a virtual DS4 controller (basically pass-through with some analog stick filtering and macros).
I've whitelisted DS4Windows, and selected only the physical controller to hide it from other applications (see:  https://github.com/ViGEm/HidHide#user-guide ). The option 'Hide DS4 Controller' is disabled in DS4Windows.
However, there's a noticeable input delay using this setup, which was not observed previously when I did not use HidHide, and instead used the 'Hide DS4 Controller' option in DS4Windows.

I'm using DS4Windows v3.0.1 and HidHide Drivers v1.0.30, on Windows 10 x64, with a Dualshock 4 v1 controller.

**Comment by Ryusennin** [comment]
HidHide is a brand new replacement for HidGuardian, you should probably report your findings to Nefarius github.

**Comment by nefarius** [comment]
No thank you 😁 HidHide works by denying device open requests, nothing more, nothing less, it has no role once I/O is actually traveling through the driver stacks so something else is not right here.

**Comment by Ryochan7** [comment]
And yet you report issues here? I thought HidHide was still in very early ALPHA. I have never tested that driver so I don't have any real input when it comes to that driver.

**Comment by nefarius** [comment]
Anyway, to clarify; HH works by denying devices **open** requests, it has no involvement in the actual I/O for **allowed processes**, I'll try to replicate myself with the software and hardware mentioned but from an architectural perspective the claimed issue makes no sense (and there is no data to back it up in the issue description).

**Comment by nefarius** [comment]
Alrighty, I just tested on/with:

- Windows 10 20H2 x64
- DS4Windows 3.0.1 x64
- HidHide 1.0.18
- Sony DualShock 4 Rev1

## HidHide OFF

![image](https://user-images.githubusercontent.com/286631/114072010-0fac3500-98a2-11eb-90cf-196f0d725c0c.png)

## HidHide ON

![image](https://user-images.githubusercontent.com/286631/114072044-18047000-98a2-11eb-8e8b-2d99734f55b6.png)

(basically exactly the same, including measurement tolerances)

It also "feels" exactly the same 😁 

Using configuration:

![image](https://user-images.githubusercontent.com/286631/114072167-3cf8e300-98a2-11eb-869f-131af033dd57.png)

![image](https://user-images.githubusercontent.com/286631/114072187-42562d80-98a2-11eb-92ba-f414b5b4a216.png)

So yeah, kindly back up your claim with data/more info or this won't lead anywhere I'm afraid 🙂

**Comment by Ryochan7** [comment]
Played around with the latest HidHide driver for a bit. Seems promising so far but I can feel a bit of a difference in performance compared to when the driver is disabled. I am playing Oddword: Abe's Exoddus from GOG using a virtual DS4 created by ViGEmBus.

Ended up downloading and experimenting with the HidHide source. It took a bit of time to learn the code structure. I carried over some of the changes that I had made with HidGuardian to the HidHide source. Switching out the event forwarding IO queue and using some different build settings for Release builds seem to get performance in line with native file handle performance.

https://github.com/Ryochan7/HidHide/tree/ryochan_changes

**Comment by nefarius** [comment]
Thanks, compiler optimization flags I'll carry over. 

I'll evaluate again if we need a default I/O queue as well and can just let the framework handle the forwarding instead. 

As for changing the I/O type I quote MS Docs:

> Calling WdfDeviceInitSetIoTypeEx from a KMDF filter driver has no effect. For KMDF filter drivers, the framework uses the I/O type that the next-lower driver in the driver stack specifies.

**Comment by tonebacas** [comment]
I completely forgot to mention that in my testing I was using the controller via Bluetooth, both with and without HidHide. After reading your replies it seems like something that I should have mentioned originally. Sorry about that.

**Comment by nefarius** [comment]
Same test on wireless:

## HidHide OFF

![image](https://user-images.githubusercontent.com/286631/114221971-46e81800-996e-11eb-93ec-898317276116.png)

## HidHide ON

![image](https://user-images.githubusercontent.com/286631/114221979-49e30880-996e-11eb-98e2-b93ba5337604.png)

Welp... @tonebacas what about your values? 🙂

**Comment by Ryochan7** [comment]
Not a very good indicator but this might give an idea about how the driver works out for me. Compares native file handle, vanilla HidHide, and the custom HidHide changes. I'm sure the input delay reading shown in DS4Windows would be about the same in all situations but it feels like the input packets are behind maybe 1 or 2 frames time with vanilla HidHide.

Unscientific Experiments - HidHide
https://www.youtube.com/watch?v=SsnIGdmzA0g

> As a filter driver you are a "guest" in the device stack, you can not and must not change properties that would violate how the stack would operate without the filter present.

Missed that detail about WdfDeviceInitSetIoTypeEx for filter drivers. I will have to try the driver out with that portion of the changes omitted.

**Comment by Ryochan7** [comment]
Commented out the WdfDeviceInitSetIoTypeEx setup portion and the driver performs fine without it.

At this point, it looks like HidHide will replace HidGuardian on my system. Thank you @nefarius

**Comment by nefarius** [comment]
> At this point, it looks like HidHide will replace HidGuardian on my system. Thank you @nefarius

That means a lot, thanks for the feedback (and the *other* gesture 😉 )  👍 

[It also has the API documented](https://vigem.org/projects/HidHide/API-Documentation/) so the driver can be utilised without the GUI client. Still a bit rough and stuff missing but it should get the adventurous developer going.

**Comment by nefarius** [comment]
@Ryochan7 we've removed the I/O queue from the driver wit the referenced PR. Be my guest to test on your end. Fill be included in an upcoming release.

**Comment by nefarius** [comment]
Nice! 😲 We indeed [took out some code](https://github.com/ViGEm/HidHide/pull/12) that could've/should've been the culprit, performance improvement is included in the next HidHide release.

**Comment by tonebacas** [comment]
Oddly enough, I can't perceive any major input delay in games that use xinput 1.4 (tested on Cemu and RetroArch) or DInput 8.
However, Rain World, along with another game I tested called Butcher -- both of them use xinput 1.3, and that's where the lag is really noticeable.

**Comment by Kanuan** [comment]
I know it will be probably fixed in the next version but:

With HidHide installed, regardless if it is activated or not, a emulated DS4 in Hollow Knight will have what it feels like ~200ms of input delay. When using an emulated Xbox 360 controller there doesn't seem to exist any input delay.

Strangely, The same DS4 setup with Cuphead doesn't have any noticeble input delay.

Uninstalling HidHide fixes the issue in all cases.

**Comment by nefarius** [comment]
Keep those testing setup in mind once the next version drops! 👍

**Comment by Yohoki** [comment]
Just came to mention that I also noticed my v1's lightbar consistently flashing (high latency) while playing 'It Takes Two', but not the v2 controller. This occurred when wired or wireless.

It seems like you've already got a fix planned, so I'll check again after an update is dropped. :)
