### ISSUE TITLE
Unable to launch DS4Windows after renaming executable (workaround for games that ignore DS4Windows DS4 input)

### ISSUE THREAD

**Issue by stramner** [Ryochan7/DS4Windows#2027]
**Describe the bug**
Some games block DS4 windows input (eg Celeste). Workaround was to rename DS4Windows.exe. After updating from 2.2.4->3.0.1, DS4Windows won't launch after being renamed.

**To Reproduce**
1. Rename DS4Windows.exe to a different name
2. Try launching the exe

**Expected behavior**
Exe should launch, as it did in 2.2.4

**Desktop (please complete the following information):**
 - Controller Make and Model: Irrelevant
 - OS: Windows 10 Edu 2004
 - DS4Windows Version 3.0.1

**Additional context**
This worked well in the past. I know it probably isn't a bug in true sense of the word as it's not typical requirement for app to work after being renamed, but as far as I'm aware, there's no other workaround so far for the issue of DS4Windows DS4 input being blocked by some games.

**Comment by Ryusennin** [comment]
Don't manually rename the executable. Go to Settings tab and type the name you want in the relevant field "Custom Exe Name".

**Comment by stramner** [comment]
Thanks, I tried checking change log for something like this beforehand but didn't find anything. So that solves it.
