### ISSUE TITLE
Would it be possible to get a new host for the website, or at least the drivers?

### ISSUE THREAD

**Issue by Sonickyle27** [Ryochan7/DS4Windows#203]
While the website is viewable through Google's cache, the download for the DS4 driver fails once the bandwidth limit has been hit (at least the last time I set up DS4Windows a few months ago). Unless there's a manual method that I'm not aware of, this makes setting up controllers to be used with DS4Windows seemingly impossible, and waiting until the end of the month isn't fun (especially when that's half way through the next week!)

Is there anything preventing the driver from being hosted on a standard file storage service like Google Drive? If there's no API for downloading directly from Google Drive you could at least ask users to download the zip, drop it into a certain directory and let the program take it from there.

**Comment by Ryochan7** [comment]
This fork does not use ds4windows.com for downloading the Scp Virtual Bus Driver archive. That archive is hosted on my own web space. There is no website for this version of DS4Windows though. You can download the archive from the following link and install the driver.

http://ryochan7.xyz/ds4windows/files/Virtual%20Bus%20Driver.zip

**Comment by Sonickyle27** [comment]
Ah, that must mean that I grabbed the Jay2Kings version before. No wonder it didn't work. oops.

I'll close this myself.
