### ISSUE TITLE
Special Actions involving XInput triggers don't register any input

### ISSUE THREAD

**Issue by xv0t** [Ryochan7/DS4Windows#2031]
**Describe the bug**
Creating a special action that involves XInput triggers never activates its macros

**To Reproduce**
1. While editing a profile, go to Special Actions
2. Click on New Action
3. Name the Special Action "Test"
4. Select a Trigger (Triangle for this example)
5. Select Multi-action Button as Action
6. For Tap Trigger, record a Triangle press
7. For Hold Trigger, record a Square press
8. For Double Tap Trigger, record a Circle press
9. Save the Special Action
10. Select "Test" from the Special Action list
11. (not necessary) Press the Apply button next to the Profile name
12. No recorded macros register as pressed.

**Expected behavior**
Monitoring inputs with either gamepad-tester.com, a game or Win10's own "Set up USB game controllers" control panel option, it should show the following behavior:
Pressing Triangle once: register the press of the button corresponding to Y on the emulated Xbox 360 controller
Holding Triangle: register the press of the button corresponding to X on the emulated Xbox 360 controller
Pressing Triangle twice: register the press of the button corresponding to B on the emulated Xbox 360 controller

**Screenshots**

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DualSense (CFI-ZCT1W)
 - OS: Windows 10 Pro 20H2 Build 19042.906
 - DS4Windows Version 3.0.1

**Additional context**
Using keyboard keys as macros instead of controller input works as intended.
Restarting DS4Windows and/or reconnecting the controller doesn't change the witnessed behavior.

[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/6255345/ds4windows_log.txt)

**Comment by Ryochan7** [comment]
The macro system has always been inadequate and I never use it myself. Looking at the behavior, at least the Tap Trigger and Hold Trigger are working as intended. Unfortunately, macros execute too quickly to sometimes even show up in some tools including Gamepad Tester. You have to add a Wait period before the Button Down and Button Up events in order for the event to be detected.

I ended up finding a bug with Wait periods not saving for the Double Tap Trigger. Will have to look into that. Other than that issue, everything is working as intended.

**Comment by xv0t** [comment]
Thanks, inserting Waits before each button press does the trick indeed, what I find odd behaviour is that such thing is not necessary when using keyboard keys for the macros' inputs.
Cheers!
