### ISSUE TITLE
Using more than one trigger doesn't activate Gyro

### ISSUE THREAD

**Issue by xv0t** [Ryochan7/DS4Windows#2032]
**Describe the bug**
Selecting more than one button to enable the Gyro results in the selected buttons not registering any input and not activating Gyro

**To Reproduce**
1. Open a profile to edit
2. Click on Gyro
3. Select either Mouse or Mouse Joystick as Output Mode
4. in the Triggers section, select both L1 and L2
5. Apply and Save the changes to the profile
6. Both L1 and L2 stop registering any input as well as not activating Gyro

**Expected behavior**
Gyro gets enabled whenever pressing either L1, L2 or both, while also registering the L1 and L2 input

**Screenshots**
![](https://i.imgur.com/KJrhsrq.png)

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DualSense (CFI-ZCT1W)
 - OS: Windows 10 Pro 20H2 Build 19042.906
 - DS4Windows Version 3.0.1

**Additional context**
Restarting DS4Windows and/or reconnecting the controller doesn't change the witnessed behavior.

[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/6255345/ds4windows_log.txt)

**Comment by Ryochan7** [comment]
Eval Cond already exists. Use **Or**

**Comment by xv0t** [comment]
Just tested this on the new 3.0.2 version, and found the following results:
- More than one button set as a Gyro trigger do register input now
- The Gyro is not enabled by pressing any of the buttons set as triggers
![image](https://user-images.githubusercontent.com/29744893/114432437-ecbda180-9b7d-11eb-9936-b92f187bf3d6.png)
So in this example, all 3 buttons now do register their respective inputs but neither of them do enable the Gyro
