### ISSUE TITLE
High CPU usage after quitting Wreckfest

### ISSUE THREAD

**Issue by tordenflesk** [Ryochan7/DS4Windows#2033]
**Describe the bug**
After quitting Wreckfest, DS4Windows.exe pegs a single core

**To Reproduce**
1. Exit/Alt+F4 Wreckfest
2. experience laggy cursor, high single core CPU usage.
3. kill ds4windows.exe
4. restore sanity

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2E)
 - OS: W7 x64
 - DS4Windows Version 3.0.1

**Comment by mika-n** [comment]
DS4Windows log files when this happens?
You seem to be on ancient Win7. The support for Win7 is lone gone in ViGem driver (the latest version of ViGem supports only Win10) and Win7 support in DS4Windows app itself is becoming "run at your own risk" thing. Time to move on to Win10?

**Comment by tordenflesk** [comment]
This only happens occasionally, nothing shows up in the log when quitting Wreckfest. Stop/Start in DS4Windows doesn't help.
The particular thread is **vigemclient.dll!vigem_target_x360_get_user_index+0x5f08**

**Comment by Ryochan7** [comment]
My little hotplug program is able to produce errors with the User Index routine in ViGEmBus 1.16.112.0 pretty easily if it is probed soon after the virtual Xbox 360 controller is plugged in. Issues with the User Index is why I have never used that property in DS4Windows in some capacity. As it is, this is purely a ViGEmBus issue. You are pretty much stuck unless you want to update Windows to have access to the latest ViGEmBus driver.
