### ISSUE TITLE
DS4windows keeps asking me to choose where to store settings on startup

### ISSUE THREAD

**Issue by TacticalTurtleneck** [Ryochan7/DS4Windows#2035]
Expected behaviour: Only asks where to store settings the first time I start DS4windows.
[ds4windows_log_20210405.1.txt](https://github.com/Ryochan7/DS4Windows/files/6256870/ds4windows_log_20210405.1.txt)

**Comment by TacticalTurtleneck** [comment]
Also, profiles aren't saving. Each time I restart the program my changes have not saved.

**Comment by TacticalTurtleneck** [comment]
FIXED: I fixed the problem by moving the DS4windows install folder out of my programs folder.

**Comment by Masamune3210** [comment]
Just a heads up in case you have other programs in those folders unless a program is formally installed with an installer and everything it usually is a bad idea to put it in Program Files or (x86). It causes a whole bunch of permission issues

**Comment by schroef** [comment]
Dang lost my profiles. As i was reading this i moved the DS folder outside the program files and moved the update ds exe to the appdata > roaming > ds folder. I delete my existing profiles. Kinda weird when i only moved the exe file to that folder?!

When i opened it, it showed in the dialog "multiple install folders found" also stated deleted others with a checkbox which i did not check.

**Comment by schroef** [comment]
OKay i stepped over that mishap, but it still keeps asking where to save. I first moved the DS folder outside program files, then run ds it still asked for what folder to pick. Then completely removed the other folder and stilll ask for what folder to pick.

I just updated to latest version
