### ISSUE TITLE
Hidguardian hiding my V2 gamepad

### ISSUE THREAD

**Issue by IceLancerSR** [Ryochan7/DS4Windows#2036]
Hey there. . everything tells that my V2 gamepad should not be hidden and yet it is.
CUH-ZCT2E
HidGuardianInstaller_20191218
win10 x64 21H1

i tried multiple combinations. Restart PC, no ds4windows , just connect gamepad to BT. Windows shows wireless controler in devices , but thats about it. Accessing joy.cpl results in empty , no gamepad shown. 

Same thing happens with ds4windows ON and enable dualshock mode. Gamepad still hidden.

Maybe this isn't best place to ask? But i am going nuts here so any help would be welcome. 

my main problem is wanting to play some older games which have sixaxis and or original dualshock button icons support , but it seems i cant do it now...

I would gladly stay out of hidguardian as it causes me this issues, but i have problem without it, which causes my gamepad to be non functional upon reconnecting from idle disconnect

It would be soo good if HIDguard would drop all that hiding nonsense and just concentrate on making gamepad exclusive :-/

**Comment by Kanuan** [comment]
I'm assuming your ds4v2 is being detected by ds4windows and works when emulating a Xbox controller , but not when emulating a DS4.

In this case: DS4Windows -> Settings tab -> Open HIDNinja -> Remove entry `HID\VID_054C&PID_05C4` if it exist. It causes HIDGuardian to Hide the emulated DS4 controller

**Comment by IceLancerSR** [comment]
> I'm assuming your ds4v2 is being detected by ds4windows and works when emulating a Xbox controller , but not when emulating a DS4. If this is the case, HIDGuardian is doing exactly what it should be doing: hiding the DS4v2 and only letting DS4Windows see it. The problem is that DS4Windows default settings also hide every DS4v1_USB device, which causes the emulated DS4 that is created to also be hidden
> 
> To fix this: DS4Windows -> Settings tab -> Open HIDNinja -> Remove entry `HID\VID_054C&PID_05C4` if it exist. It causes HIDGuardian to Hide the emulated DS4 controller.
> 
> After that, reconnect your controller and the emulated DS4 should then be visible. Because the real controller is always hidden, you will always have to use DS4Windows to use your controller (real DS4 hidden, emulated DS4 visible)

That's the problem. Its blocking my DS4v2 as well. With or without ds4windows. So i can't even use my dualshock without it being emulated as xbox and i need it for multiple games especially those with sixaxis. On top of all i can't play nativly suported ds4 games (v1) tombraider, old directinput games, batman..

**Comment by Kanuan** [comment]
As I said, that's working as intended. DS4v2 should be hidden at all times except for ds4windows and will remain hidden with DS4Windows opened or not.

If you want to use your controller as an actual DS4 for games that support it, then you need to emulate a DS4v1 _with_ DS4Windows. Create a new profile in DS4Windows, on this profile settings -> `Other` tab choose `Emulated controller: DualShock 4`. Save this profile then switch to it on the `Controllers` tab. Done. Assuming you did what I told on HIDNinja -> Removing the `HID\VID_054C&PID_05C4` entry it before doing this it should work

**Comment by IceLancerSR** [comment]
> As I said, that's working as intended. DS4v2 should be hidden at all times except for ds4windows and will remain hidden with DS4Windows opened or not.
> 
> If you want to use your controller as an actual DS4 for games that support it, then you need to emulate a DS4v1 _with_ DS4Windows. Create a new profile in DS4Windows, on this profile settings -> `Other` tab choose `Emulated controller: DualShock 4`. Save this profile then switch to it on the `Controllers` tab. Done.
> 
> Remember to go on HIDNinja -> Remove the `HID\VID_054C&PID_05C4` entry and reconnecting the controller, otherwise HIDGuardian will end-up hiding the emulated DS4v1

Hm i was under the impression that V2 is never suppose to be hidden by HIDguardian by default. Only V1?
Alright its way too late now to do anything i am barely typing . But i will try tomorrow what you suggested. 
Thanks

**Comment by IceLancerSR** [comment]
> As I said, that's working as intended. DS4v2 should be hidden at all times except for ds4windows and will remain hidden with DS4Windows opened or not.
> 
> If you want to use your controller as an actual DS4 for games that support it, then you need to emulate a DS4v1 _with_ DS4Windows. Create a new profile in DS4Windows, on this profile settings -> `Other` tab choose `Emulated controller: DualShock 4`. Save this profile then switch to it on the `Controllers` tab. Done.
> 
> Remember to go on HIDNinja -> Remove the `HID\VID_054C&PID_05C4` entry and reconnecting the controller, otherwise HIDGuardian will end-up hiding the emulated DS4v1

Ok this HID\VID_054C&PID_05C4 certainly worked to a degree.  My dualshock V2 is now visible and apps even recognize it. But there is other issue. That registry is for DS4 V2 but how to unhide V1?
Games like Tomb Raider have native support for dualshock and provide Playstation button prompts. But Only for V1 gamepad. V2 is invisible. What registry would Un-Hide V1?

**Comment by Kanuan** [comment]
HID\VID_054C&PID_05C4 -> DS4v1_USB (real or emulated, they are the same)

Your DS4v2 is probably still hidden (as it should be). the visible one is the emulated DS4v1

**Comment by IceLancerSR** [comment]
Well its reverse. V2 is visible , retroarch recognize it. Windows see it. But Tomb Raider reverts to xbox buttons , so it doesnt see it

**Comment by IceLancerSR** [comment]
For test purposes i unhide dualshock in ds4windows i get two of them which is normal. But neither of them is V1
https://i.imgur.com/5f5BHbT.jpg
https://i.imgur.com/aBMa5EB.jpg

**Comment by Kanuan** [comment]
![image](https://user-images.githubusercontent.com/24910442/113708653-e3cd5b80-96b7-11eb-9633-d9c3dcab614f.png)

This in the image above is the emulated DS4v1 controller, I'm 100% sure.

![image](https://user-images.githubusercontent.com/24910442/113708789-0d868280-96b8-11eb-95e7-5088788cea1b.png)

**Comment by IceLancerSR** [comment]
Yes u are right image above VID_054C&PID_05C4 definitely is V1. But game doesn't recognize it :-/ Thats weird.

**Comment by Kanuan** [comment]
well, that's 100% unrelated to the issue here. As things are now, they are working as they should. Real ds4v2 hidden, emulated ds4v1 visible. There's no way to emulate a ds4v2 with ds4windows, but it's not necessary since I have yet to find a game that doesn't work as it should with a ds4v1_usb (it kinda is the standard supported ds4 controller)

**Comment by IceLancerSR** [comment]
> well, that's 100% unrelated to the issue here. As things are now, they are working as they should. Real ds4v2 hidden, emulated ds4v1 visible. There's no way to emulate a ds4v2 with ds4windows, but it's not necessary since I have yet to find a game that doesn't work as it should with a ds4v1_usb (it kinda is the standard supported ds4 controller)

AH! Ok reboted PC. Now game sees DS4 V1 Properly !!
Finally! I wish wiki was as eloquent and to the point as your guide!
Thanks!
Will close the issue
