### ISSUE TITLE
Cant connect bluetooth

### ISSUE THREAD

**Issue by prtmrj** [Ryochan7/DS4Windows#2037]
05/04/2021 19:18:33: Starting...
05/04/2021 19:18:33: Connection to ViGEmBus  established
05/04/2021 19:18:33: Searching for controllers...
05/04/2021 19:18:33: Using Shared Mode
05/04/2021 19:18:47: The gamepad DS4 v.2 (BT) uses custom feature set (MonitorAudio)
05/04/2021 19:18:51: Found Controller: 90:89:5F:87:29:70 (BT) (DS4 v.2)
05/04/2021 19:18:51: Plugging in virtual X360 Controller
05/04/2021 19:18:51: Associate X360 Controller for input DS4 #1
05/04/2021 19:18:51: 90:89:5F:87:29:70 disconnected due to read failure: 0
05/04/2021 19:18:51: Disassociate X360 Controller for input DS4 #1
05/04/2021 19:18:51: Unplugging virtual X360 Controller
05/04/2021 19:18:51: Controller 1 was removed or lost connection. Charge the battery

**Comment by Masamune3210** [comment]
Please fill out the issue template, its there for a reason. This is missing a lot of information needed to even begin helping

**Comment by Ryochan7** [comment]
Blatantly omitting useful info. No help for you.
