### ISSUE TITLE
Getting "ERROR. vJoy Initialization failed ..." when selecting Vjoy1 X-Axis

### ISSUE THREAD

**Issue by agostini01** [Ryochan7/DS4Windows#2039]
**Describe the bug**

Applications cannot see Vjoy1 inputs.

I was playing with the configurations of a DualSense Controller
1. In Gyro > 360 Steering Wheel
2. I activated Steering wheel axis: VJoy1 X-Axis.

But at the bottom of the application window, I get the following message:
```
"ERROR. vJoy initialization failed. Make sure that DS4Windows application can find vJoyInterface.dll library file".
```

**Expected behavior**
Vjoy should be sent as an output.

**Screenshots**
![image](https://user-images.githubusercontent.com/3741033/113722798-c223a280-96be-11eb-9d6b-81d714ba9b62.png)

**Desktop**
 - Controller Make and Model: Sony DualSense
 - OS:  Windows 10 Pro Build 2004
 - DS4Windows Version 3.0.1

**Comment by mika-n** [comment]
Do you have the vJoy driver installed and the vJoyInterface.dll file on the same folder where you have DS4Windows.exe app?
