### ISSUE TITLE
Window Position issue

### ISSUE THREAD

**Issue by arkhillneo** [Ryochan7/DS4Windows#204]
Hi,
Is there possible to support a feature that can save window position and size forever of DS4Windows's main window?

I have some reason to setup my task-bar on the top of the monitor.

Sometimes I call DS4Windows from task-bar by click the min-icon, DS4Windows roll-back it's position to top-left of the desktop(seems from 0,0) and default window size for unknown reason. 

![2018-01-27_095603](https://user-images.githubusercontent.com/35409070/35467350-59db99ce-0348-11e8-8707-8dd15cc5a642.jpg)

I do not touch profile or xml file but it still do so. This action makes the task-bar overlapping with DS4Windows.

**Comment by Sonickyle27** [comment]
Same issue here. In the meantime, if you press the Windows Key + Up, it'll maximise the window which will then let you drag it wherever you need it.

**Comment by mika-n** [comment]
the latest version has some window positioning bug fixes
