### ISSUE TITLE
DS3Windows

### ISSUE THREAD

**Issue by bastiro03** [Ryochan7/DS4Windows#2041]
In short, DualShock3/Sixaxis controller support for DS4Windows. Implementing this feature would likely be easier by integrating Better DS3/DS3Tool/MotioninJoy, and/or SixaxisPairTool into the program. Even without those this doesn't seem to hard, the DualShock 3 probably uses similar connection technology to the DS4 and DS5, as it is possible to use a DS4 on a stock PS3 system (i haven't checked if it works the other way around as well).

**Comment by mika-n** [comment]
DS3 already works in DS4Windows both in wired and wireless mode. The key is to use revolutionary DsHidMini device driver with DS4Windows app and ViGem driver (DsHidMini is actually created by the same person, Nefarius) who created the ViGem driver used in DS4Windows app).
https://vigem.org/projects/DsHidMini/

DsHidMini has DS4 output mode and it makes the DS3 to look like DS4 compatible gamepad and DS4Windows app can use this "fake" DS4 gamepad as a source.

**Comment by Kanuan** [comment]
> Even without those this doesn't seem to hard, the DualShock 3 probably uses similar connection technology to the DS4 and DS5, as it is possible to use a DS4 on a stock PS3 system

Actually it's a lot more complicated than that but it's already been solved with DsHidMini and BthPS3

**Comment by mika-n** [comment]
ds3 already works when DsHidMini driver is installed on Win10
