### ISSUE TITLE
DS4Windows by Ryochan7 doesn't work with generic controller

### ISSUE THREAD

**Issue by salangoncalves** [Ryochan7/DS4Windows#2043]
Hi!

I have a 7&z generic DS4 control (recognized as Gioteck VX4) connected via the USB port, actually using the 3.0.1 version of the DR4Windows. By the way, despite being connected sucessfull, no buttons work.

Accessing the control panel, there are two joysticks (Gamepad and XBOX 360 controller), and when i disable one of them, the other is also disabled. I have already used other versions of DS4Windows by Ryochan7, as it is the only one that connects to my computer, although it does not work.

However, when i configure the windows joystick ("Gamepad"), all buttons work normally. But, when i try to configure the virtual XBOX 360 controller after "start" on the program, no command is received by the computer, nor can I change the light on the touchpad or any other function of the controller.

In addition, as you can see in the photo, the controller readings tab is always stucked and with a flashing green circle in the upper right corner.

Comments:
1. I have already tried shared mode and exclusive mode.
2. I have already tried the "Dimput only" mode.
3. I have already uninstalled the hid controller driver and installed it again.
4. All prerequisite software has been met.
5. The program was installed on different windows installations.
6. My generic controller work fine on Steam Big Picture.

hope you guys can help with this issue. Thank you!

Screenshots:
![1223](https://user-images.githubusercontent.com/82117144/113924516-4447c000-97c0-11eb-86bf-1168016a451b.JPG)
![424244](https://user-images.githubusercontent.com/82117144/113924517-4578ed00-97c0-11eb-8a49-859ca453991d.JPG)
![53535555](https://user-images.githubusercontent.com/82117144/113924520-46118380-97c0-11eb-9264-9333070b550b.jpg)
![454545454545](https://user-images.githubusercontent.com/82117144/113924523-4742b080-97c0-11eb-96c6-3ecce669175a.JPG)

Log:
[ds4windows_log_20210405.1.txt](https://github.com/Ryochan7/DS4Windows/files/6274258/ds4windows_log_20210405.1.txt)
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/6274275/ds4windows_log.txt)

Profiles:
[Profiles.zip](https://github.com/Ryochan7/DS4Windows/files/6274267/Profiles.zip)

**Comment by mika-n** [comment]
Do you see any activity in ControllersReading page when a gamepad is connected?

The "big red area and green circle" is for gyro and it should not have anything to do with gamepad connection issues. Anyway, you have invalid value in sixaxis deadzone settings (probably 25.00) and this is why the whole gyro movement box is one big deadzone (=red). Change the deadzone value of sixaxis axies to 0.25 value.

**Comment by salangoncalves** [comment]
Hi, @mika-n

After several days of researching different software for the generic control, the problem was solved by installing "reAWSD", which created a new drive for the XBOX 360 control, even making DS4Windows recognize the control as original.

However, I still cannot use the gyroscope. ReAWSD indicates that the control has a gyro axis, but no buttons are activated with the movement of the control.

So, is there any way to test the gyroscope on windows? Do I need to press any buttons on the controller?

**Comment by mika-n** [comment]
The virtual reWASD gamepad driver should not have anything to do how the physical gamepad driver works in PC. You probably had something wrong in HID device list and the HID driver for the physical gamepad was not working or in disabled state in DeviceManager. Installing reWASD just happened to "fix" this problem. The virtual reWASD driver is a spinoff of ViGem virtual gamepad driver used in DS4Windows and does pretty much the same thing as ViGem driver.

DS4Windows and ControllerReadings tab page should show the gyro activity if it works (ie. the system is able to read those events from the physical gamepad). Earlier you just had buggy deadzone setting in gyro settings because the whole gyro activity box was one big red deadzone, but still you should see if those dots are moving on the gyro box.

**Comment by salangoncalves** [comment]
> The virtual reWASD gamepad driver should not have anything to do how the physical gamepad driver works in PC. You probably had something wrong in HID device list and the HID driver for the physical gamepad was not working or in disabled state in DeviceManager. Installing reWASD just happened to "fix" this problem. The virtual reWASD driver is a spinoff of ViGem virtual gamepad driver used in DS4Windows and the virtual reWASD gamepad driver does pretty much the same thing as ViGem driver.
> 
> DS4Windows and ControllerReadings tab page should show the gyro activity if it works (ie. the system is able to read those events from the physical gamepad). Earlier you just had buggy deadzone setting in gyro settings because the whole gyro activity box was one big red deadzone, but still you should see if those dots are moving on the gyro box.

@mika-a
Even with sixaxis deadzone fixed at 0,25, is still not registering movement of the gyroscope. As you can see at photo, gyro Y is always set on the right side bar. The gyroX and giroZ does not change anyway. Other words: none of the gyro's bars is moving with the controller.

![wvwvwvwvwvwvwv](https://user-images.githubusercontent.com/82117144/114036971-e4502880-9856-11eb-8bff-27516b4926e8.JPG)


Do you know if the Gioteck VX-4 controller actually features a gyroscope? I didn't saw anything about that motion function with the manufacture's website. Thanks!

**Comment by Ryochan7** [comment]
> DS4Windows by Ryochan7 doesn't work with generic controller

![good_grumpy_cat](https://user-images.githubusercontent.com/581968/114054215-4445cf80-9855-11eb-9749-369a979fa7a1.jpeg)

**Comment by salangoncalves** [comment]
> > DS4Windows by Ryochan7 doesn't work with generic controller
> 
> ![good_grumpy_cat](https://user-images.githubusercontent.com/581968/114054215-4445cf80-9855-11eb-9749-369a979fa7a1.jpeg)

Nice cat :)~ . Was your message sarcastic?

It is strange, but the program was not really working with the generic control. I tried in every way possible to get it to work on the DS4w, and then finally got it.

Now, the gyroscope problem like be is more physical than logical. But I need to be sure before throw it in the trash, especially because it was recent bought, right!? ( :D ). There is a hope of gyro support for that shitty controller?

**Comment by mika-n** [comment]
Someone with the actual hardware (=copycat gamepad wanna-be ds4) should debug the gyro thing because it is next to impossible to debug it from here without having an actual hardware. If it used to work in some of the older DS4Windows versions then try installing the old version in a separate new folder (works just fine along side the latest DS4Windows version). If the gyro still doesn't work then I guess it is a hardware or device driver issue there.

**Comment by salangoncalves** [comment]
Nah, all attempts have been exhausted and the generic control will probably be sold to buy an authentic one. It's funny, because the only function i wished was precisely the gyroscope (for simulators with steering wheel and racing games), and that was just what failed. Isn't it sad? Anyway, thanks for your help (@mika-n).

**Comment by Masamune3210** [comment]
Gyros on third party controllers don't have a super good track record with being any good even if they do work, so you probably lucked out in the end honestly

**Comment by salangoncalves** [comment]
> Gyros on third party controllers don't have a super good track record with being any good even if they do work, so you probably lucked out in the end honestly

I'm not sure about that... :|

After installing thousands of program versions of DS4w and game controller drivers, at the end, resulted an PS2 controller for simple games, also considering the fact of older PS2 is plug and play.

**Comment by mika-n** [comment]
and often those copycats struggle especially over BT, but may work a bit better over USB. Anyway, the easiest and cheapest (if time costs money) is to purchase a genuine DS4 or DS5 gamepad.
