### ISSUE TITLE
Killing DS4Windows Process Doesnt Turn OFF Gamepad

### ISSUE THREAD

**Issue by shinra358** [Ryochan7/DS4Windows#2046]
When DS4W process is killed, the controller stays on. If DS4W is restarted and gamepad idles off, the Controller 1,2,3,4 is still left in the DS4 taskbar menu. If gamepad is turned off manually, the Controller 1,2,3,4 disappears correctly.

OS: any

Issue: controllers remain on when force closing ds4w process in the process manager (ctrl alt delete)

Replication: have wireless controller activated. Force close DS4w in the process manager. When ds4w closes, it will not turn off the controller like other methods of it shutting down (like OS shutdown)

Desired Effect: When process is closed, the app detects and shuts controllers off before close finishes.

Edit: @masamune3210 I dropped my phone when making this so when I picked it up, the thread was made with no content so I just put what I wanted in a reply. I pushed edit on this and the template not there.

**Comment by shinra358** [comment]
When DS4W process is killed, the controller stays on. If DS4W is restarted and gamepad idles off, the Controller 1,2,3,4 is still left in the DS4 taskbar menu.

**Comment by Masamune3210** [comment]
Please go back and fill out the issue template instead of just deleting it. It has the information needed to even start helping you

**Comment by Ryochan7** [comment]
It just depends. If some app still has an open handle on the virtual Xbox 360 controller then the controller will likely still be active after killing DS4Windows. If no app has a open handle on the virtual controller then ViGEmBus will close and disconnect the controller automatically. Tested killing DS4Windows on my end via Task Manager and ViGEmBus closes the virtual controller.

**Comment by shinra358** [comment]
https://youtu.be/hm9dJHGisEg

seems wireless controller is always stuck to on in joy.cpl when force closing process. turning ds4win back on, virtual controller stays checked and can never be unchecked. i will check my vigem thingy to see what version it is.

**Comment by shinra358** [comment]
nvrmnd, had an older version installed

**Comment by shinra358** [comment]
Upgraded to windows 10 and it still does it as in the video. No apps are on but firefox to type this. Vigembus is up to date with yours. Win10Pro.

**Comment by gahtoh** [comment]
Also had this issue after installing 3.0.2
Deleted the folder and reinstalled, fixed the issue.
Be sure to check in Settings

![12 avr 16h13m02](https://user-images.githubusercontent.com/11335008/114408743-0543b100-9baa-11eb-83b1-7e1dc8b931e1.png)

**Comment by shinra358** [comment]
disconnect from bt is already checked
