### ISSUE TITLE
GyroDrift even after gyro calibration 

### ISSUE THREAD

**Issue by NexDeLly** [Ryochan7/DS4Windows#2047]
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/6287543/ds4windows_log.txt)

Controller: Ps DS4 v2
Problem: I'm experiencing gyro drift even after trying to use the "gyro calibration" in application(ver 3.0.1) which was drifting left. I tried reverting back to previous version and ver. **2.2.10** gyro calibration seems to execute and work perfectly, which fixed it. 

The game/application i observed this issue in: CEMU(with cemuhook)- Legend of zelda BOTW

**Comment by Mircosfot** [comment]
My Gyro is dancin like hell :-( If i use Steaminput my Gyro works very well.
