### ISSUE TITLE
DualSense TouchPad is not working properly

### ISSUE THREAD

**Issue by Viruskiller94** [Ryochan7/DS4Windows#2049]
I'm using the DualSense emulating a Dualshock 4, with Lightbar, Gyro and Touchpad on "Passthru".
The problem is that the touchpad swipes doesn't work. It happens wired and wireless.

I tested the same with a Dualshock 4 and it worked properly, so i guess there is a problem with the drivers not recognizing the swipes on the Dualsense

My version of DS4Windows is the latest (3.0.1).

I used PS Remote Play for this tests, with 2 games, Ghost of Tsushima and Days Gone (both have obvious menus or actions swiping the touchpad) but this can be done with any game with native support of DualShock 4 too.

Sorry if there are any grammatical errors, English is not my native language.

Greetings and thanks for all your work

**Comment by Ryochan7** [comment]
This just gives me more incentive to start enforcing more restrictions. You are likely running an older version of ViGEmBus (prior to 1.17.333.0) which do not have Touchpad emulation support. Only the most recent ViGEmBus driver (1.17.333.0) has support for Touchpad and Gyro data passthru. Enabling those options in DS4Windows when using older versions of ViGEmBus will do nothing.

https://github.com/ViGEm/ViGEmBus/releases/tag/setup-v1.17.333

**Comment by Viruskiller94** [comment]
I'm running the latest version of ViGEmBus (1.17.333), that was the first thing I checked before writing this post. And as I said before, with DualShock 4 there is no problem, touchpad, gyro and lightbar are working as intended. The only problem I have is Touchpad Swipes with DualSense, Touchpad clicks, Gyro and Lightbar are working fine.
I mean, if a game ask me to press Touchpad to open a menu, that works, but if the game ask me to swipe right to open the map, that doens't work. But it works with Dualshock 4.

I tested it on PS5 and obviously works, so my controller is not faulty. 

Can you check? I have everything up to date, it has to be a bug with the new Dualsense.

Thanks.

**Comment by jono100** [comment]
Working 100% for me. Swipes to switch profiles with passthrough enabled. I'd suggest removing everything and adding again. This is not a DS4Windows issue.

**Comment by Viruskiller94** [comment]
Swipes to switch profiles is working for me too. That's not a passthru function.
I reinstalled DS4Windows and Vigembus drivers, and the problem still remains
Please, check in a game with native Dualshock 4 support.
