### ISSUE TITLE
SCP Driver installer UI does not follow the Language-Switching feature

### ISSUE THREAD

**Issue by arkhillneo** [Ryochan7/DS4Windows#205]
Hi,
As you can see, I set DS4 to Traditional Chinese UI but SCP Driver installer is still in English. This issue also happens on other languages so I wonder this is driver installer UI issue that it does not merge the new language-switching feature.
![2018-01-27_212005](https://user-images.githubusercontent.com/35409070/35472324-2a19f8b0-03a8-11e8-8aea-4defac611bb2.jpg)

Under Chinese locale OS the driver installer UI is following the locale language.
![2018-01-27_213814](https://user-images.githubusercontent.com/35409070/35472458-75fba628-03aa-11e8-8e6a-b2961c00ad58.jpg)

**Comment by Ryochan7** [comment]
DS4Windows launches another instance of itself to bring up that window; this is mainly needed to elevate program privileges if the original instance is not launched as the administrator. The loading of the specified language pack happens in the main DS4Form which does not get loaded in this instance. As it is, I am looking into replacing that window with a separate installer program so this might not be a big concern. Besides that, I am not sure if that program would need to respect any specified language setting for DS4Windows.

**Comment by arkhillneo** [comment]
Hi, Thanks for the reply.

I also think, this window may be no need to do that:
![2018-01-28_040221](https://user-images.githubusercontent.com/35409070/35475802-17f4dcbc-03e0-11e8-993b-d6e82f338e98.jpg)

But, for others, especially the driver installer window has much text, I think this is still needed for if someone is using language-switching, he/she would like to see all windows respect the same language setting after setting that. Sometimes you need to remove and re-install the SCP driver.

This is not only limited to Chinese or Japanese language users, but also affect people who is using non English locale OS but want to use English UI.

The other reason is, if I am doing language pack editing, it is good if all windows follow the same language setting so I can view them without go back to old style that have to switch my OS's language setting.

Just my two cents.

**Comment by arkhillneo** [comment]
@Ryochan7 
Hi, thanks for looking at this.
But is the new commit is for this issue fix? I just tested it but it seems not working. Or am I misunderstanding anything?

I test this feature by manual launching "Controller/Driver Setup" option since my system already has SCP driver installed.

![2018-02-07_035535](https://user-images.githubusercontent.com/35409070/35881215-14e087d2-0bbb-11e8-88ed-ca20404c5d07.jpg)

**Comment by Ryochan7** [comment]
I swear it worked before I made the one commit. Either way, the proper order is now used.

**Comment by arkhillneo** [comment]
@Ryochan7 
Hi, it's fine.
it's working now after the new commit.
Thanks :)
