### ISSUE TITLE
DS5 stuck at 0% battery

### ISSUE THREAD

**Issue by TheFabbiusCorp** [Ryochan7/DS4Windows#2051]
**Describe the bug**
[Using version 3.0.1]
When I pair my DS4 (either BT or USB) battery percentage status seems to work fine.
When I pair my DS5 (either BT or USB) battery percentage status gets stuck at 0%.

I'm very sure the battery itself is fine because the controller has no issues while charging.

It wouldn't be much of a problem if it wasn't for the fact that the software thinks the controller actually has a 0% battery and fallbacks to a sudden disconnection of the device (on BT mode, this doesn't apply to USB).

**Expected behavior**
The expected behavior would be the display of the correct battery percentage for DS5.

**Screenshots**
![image](https://user-images.githubusercontent.com/8267992/114271541-296c8a00-9a12-11eb-90d9-c25b2a09418e.png)
![image](https://user-images.githubusercontent.com/8267992/114271693-f4146c00-9a12-11eb-9eaf-90df9c4fd1d3.png)

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS5
 - OS: Windows 10 Pro 20H2
 - DS4Windows Version 3.0.1

**Comment by Ryochan7** [comment]
Something else is going on. DS4Windows does not disconnect a BT controller based on its battery level. The battery level can report as 0% for some time and still work before a device will finally die and disconnect. Some functions would not work as expected, like lightbar by battery level, but output mapping should work just fine.

**Comment by TheFabbiusCorp** [comment]
Never mind, it was just the controller.
After 3 hours of charging, DS4Windows now tells me the controller is at 12%... it's just freaking slow.
Thanks, @Ryochan7, for looking into it!
I will close the issue.
