### ISSUE TITLE
To run this application you need .net

### ISSUE THREAD

**Issue by HASKADOG** [Ryochan7/DS4Windows#2052]
**Describe the bug**
To run this application you need .net, but I already have .net installed from the program link

**To Reproduce**
1. Download D4Windows
2. Click on programs'
3. See error

![image](https://user-images.githubusercontent.com/27897422/114277933-08b62b80-9a36-11eb-960f-fdd8507aa46b.png)

**Comment by Ryochan7** [comment]
Still up in the air whether I will drop x86 support for DS4Windows

**Comment by mika-n** [comment]
Now when ViGem 1.17.x supports only Windows10 and DS4Windows is moving to support only Windows10 then is there really anyone using a Win10 gaming rig on 32bit x86 OS? Probably all Win10 gaming rigs are on 64bit x64 OS.
