### ISSUE TITLE
After update to 3.0.0/3.0.1 DS4 can't be detected anymore

### ISSUE THREAD

**Issue by titlekungCh** [Ryochan7/DS4Windows#2055]
**Describe the bug**
After Updating to 3.0.0 Everything else is able to detect the DS4 but DS4Windows Can't
(Then I tried update to 3.0.1 but that didn't fix the problem)

**To Reproduce**
1. Launch DS4Windows
2. Plug in the DS4
3. System.AggregateException: One or more errors occurred. (Index and count must refer to a location within the string. (Parameter 'count')) 
4. OR Index and count must refer to a location within the string. (Parameter 'count')

**Expected behavior**
DS4 Detected and show in Controller List Tab

**Screenshots**
![image](https://user-images.githubusercontent.com/39591436/114303153-db7d8200-9af6-11eb-9dfa-dfffaec3512d.png)

**Desktop (please complete the following information):**
 - DS4 v.2 (CUH-ZCT2G)
 - Windows 10 Home Build 20H2
 - DS4Windows Version 3.0.1

**Additional context**

[error log ds4w.txt](https://github.com/Ryochan7/DS4Windows/files/6291660/error.log.ds4w.txt)

**Comment by Ryochan7** [comment]
I can see where the error is supposedly occurring but I don't get why it is happening unless something else is going wrong on your system. A properly formatted device path should never fail but it is failing to find the chosen delimiter to convert the path to its Instance ID.

I'll look into it and maybe add a couple of extra checks as a pre-caution.

**Comment by titlekungCh** [comment]
Bluetooth, Wi-Fi (all Wireless Connection) on my device is currently committed not alive itself for the past week now
I connect the ds4 through wired tho
