### ISSUE TITLE
[Enhancement] Re-Add Run Program with DS4W

### ISSUE THREAD

**Issue by shinra358** [Ryochan7/DS4Windows#2056]
I know it is under controller profiles and it is still cool and needed but I've found a reason to have it when the actual ds4w starts. It's needed by myself to easily pass admin rights to apps that I'm working on for the user to not have to worry about the admin rights prompt. Having it in the controller profile is great for starting game launchers and games themselves that need admin rights and ensures a keyboardless interaction. My app, I want it to be started when ds4 does (not when controller is turned on) so that whatever my app does, it will be already ready. If I use it in controller profile, I would have to wait some time instead of keeping it moving. This is no big rush deal, but I would love if you would re-add the feature to ds4w. Thx.

**Comment by Ryochan7** [comment]
I have thought about it before but I have never had a need for the functionality myself. Although, I was thinking about adding a sort of command system like InputMapper 1.7 has to maybe allow adding more than just program execution at certain points of the program.
