### ISSUE TITLE
Vigembus issues with update 3.0.2

### ISSUE THREAD

**Issue by nikhil-dutt** [Ryochan7/DS4Windows#2058]
With update 3.0.2, I am having issues with Vigembus drivers. I installed version 1.17.333 but DS4 windows seems to not recognize it. It keeps saying unsupported Vigembus found. Please install version 1.17.33

**Comment by Ryusennin** [comment]
Which OS?

Although it is not mentioned in the release notes, DS4W 3.0.1 is the very last version compatible with Windows 7. DS4W 3.0.2 specifically requires ViGEmbus 1.17, which only works on Win10.

**Comment by halpz** [comment]
yep it's also broken for me, tried reinstalling Vigembus driver, but no luck

https://i.imgur.com/XEKFeUZ.png

**Comment by halpz** [comment]
version 3.0.1 is still working fine for me, so it must be the new Vigembus version checking feature in 3.0.2

**Comment by Ryochan7** [comment]
And yet no one posts any screenshot confirming that ViGEmBus 1.17.333.0 is indeed installed; (Device properties screenshot, App list showing the Nefarius program). Massive X

**Comment by Ryochan7** [comment]
This **WAS** tested prior to release with ViGEmBus 1.17.333.0 and 1.16.112.0. DS4Windows allowed connecting to ViGEmBus 1.17.333.0 as intended. DS4Windows would display the error message and bring up the Driver installer window if it detected ViGEmBus 1.16.112.0. Upgrading from ViGEmBus 1.16.112.0 to 1.17.333.0 worked fine.

**Comment by Ryochan7** [comment]
DS4Windows 3.0.3 has reduced the ViGEmBus restriction to allow driver version 1.16.112.0 to work again. Now Parsec's flawed ViGEmBus install works again and older versions of Windows are temporarily supported again.

I will keep stating this. **PLEASE DON'T MAKE ME REGRET THIS**.
