### ISSUE TITLE
Issues with update 3.02 and VigemBus Drivers

### ISSUE THREAD

**Issue by nikhil-dutt** [Ryochan7/DS4Windows#2059]
I am still having issues with ds4windows not recognizing the VigemBus Driver 1.17.333.0. I have tried installing it through the popup that ds4 windows has and through  GitHub but neither works. Is there a certain location we should be saving the Vigembus driver to? I am including images of what I think is useful. Let me know if there is anything else you want to see. Thanks
![image](https://user-images.githubusercontent.com/61534874/114459240-42aa3d80-9bae-11eb-9a36-3d5a09c02bf4.png)
![image](https://user-images.githubusercontent.com/61534874/114459458-8ef57d80-9bae-11eb-9932-0e944a71bba5.png)

**Comment by JustSch** [comment]
I had this same issue but Driver Store Explorer  showed there was an older version of the vigem driver installed alongside the new one and removing the older version solved the issue

**Comment by nikhil-dutt** [comment]
Thanks, that worked. Just in case anyone else has this issue, go to device manager, system devices, and delete the old gamepad emulation bus drivers manually.
