### ISSUE TITLE
[Request] Add yaw control for gyro control output mode and allow mapping accelerometer

### ISSUE THREAD

**Issue by pinospin** [Ryochan7/DS4Windows#2061]
The control output mode in gyro tab has 2 rotation axis (roll and pitch), I'd like to have yaw motion beside roll and pitch to have more choice of controls (E.g: Control the plane that need all yaw, roll and pitch movement). If not needed it can unbind anytime.
About the accelerometer can you make it mappable like in dolphin, but with G value that upon reach the amount of acceleration at certain direction it start to output any value that it bound (E.g: As flick stick alternative, when you need to reserve the right stick). In Splatoon 2 they do quick turn by shake the controller to their desired direction.

**Comment by Ryochan7** [comment]
There is currently no way to attempt to try to fake a Flight Stick with Gyro mapping in DS4Windows. That would definitely require a new output mode to perform some form of sensor fusion to attempt to track the controller's current absolute orientation. Doing that is not possible using the Gyro or Accelerometer data separately.

I guess the closest example would be how the PadTest UDP utility works to discern the absolute orientation of the controller using the data passed from the UDP server. Not sure how that program does it and I am not sure it would be worth trying to experiment with it.

**Comment by pinospin** [comment]
But what about yaw motion for control output mode?

**Comment by nickajeglin** [comment]
> 
> 
> But what about yaw motion for control output mode?

I am using controller pitch and yaw to control the same axes in elite dangerous. Isn't there a checkbox that allows you to use controller yaw instead of roll?
