### ISSUE TITLE
Unsupported ViGEmBus found when Parsec also installed

### ISSUE THREAD

**Issue by manksalot** [Ryochan7/DS4Windows#2062]
**Describe the bug**
When Parsec is also installed on Windows 10, DS4Windows reports that "Unsupported ViGEmBus found." However, ViGEmBus 1.17.333.0 was already installed, and re-installing it does not change the error in DS4Windows.

**To Reproduce**
1. Run DS4Windows 3.0.2
2. Install ViGEmBus 1.17.333.0
3. Test, it works fine
4. Install Parsec
5. Now DS4Windows gives the error when launched

**Expected behavior**
DS4Windows correctly detects the ViGEmBus 1.17.333.0 installation

**Desktop:**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: Windows 10 Pro Build 20H2
 - DS4Windows Version 3.0.2

**Screenshots:**
![2021-04-13_11-31-45](https://user-images.githubusercontent.com/4773584/114579771-34126380-9c4c-11eb-95ab-b5dee0a7e099.png)
![2021-04-13_11-41-23](https://user-images.githubusercontent.com/4773584/114581119-738d7f80-9c4d-11eb-98de-383783130603.png)

**Comment by aburke20** [comment]
Damn, awesome job on figuring out that it was the interacting with parsec.

Have the exact same issue (Win 10, DS4, Parsec combo): doesn't matter how I install VigEm (through DS4 or manually), it shows message as "unsupported VigEm" in DS4.

**Comment by Corbi** [comment]
Same issue. I have uninstalled parsec to test it, and now it starts.

**Comment by aburke20** [comment]
Some other poster actually figured out a fix that worked for me:

**Comment by manksalot** [comment]
> Some other poster actually figured out a fix that worked for me:
> 
> > nope, but I think it is to do with the latest Vigembus installing as a seperate device, the installer of which doesnt remove the old one properly -
> 
> > i have just resolved this by going into Device Manager and under "System Devices" uninstalling 'Virtual Gamepad Emulation Bus' and then disabling then re-enabling the new one that is prefixed with 'Nefarius',
> 
> > fixed the problem for me
> 
> Thanks again @halpz

That solves it for me too! Thanks so much @aburke20 and @halpz (and @Ryochan7 for maintaining this great fork)

**Comment by Ryochan7** [comment]
Confirmed after a lot of waiting; great time for forced Windows updates. Parsec force installs ViGEmBus 1.16.112.0 and even removes the newer Nefarius device that the 1.17.333.0 installer created. Adding Parsec to my sh*t list.

**Comment by Ryochan7** [comment]
Bloated Parsec wants to autostart with Windows. Also, I am pretty much going to have to clean out the Driver Store and be forced to re-install ViGEmBus 1.17.333.0 to get things back to normal. What a terrible app

**Comment by Ryochan7** [comment]
DS4Windows 3.0.3 has reduced the ViGEmBus restriction to allow driver version 1.16.112.0 to work again. Now Parsec's flawed ViGEmBus install works again and older versions of Windows are temporarily supported again.

I will keep stating this. **PLEASE DON'T MAKE ME REGRET THIS**.
