### ISSUE TITLE
ViGEmBus version issue

### ISSUE THREAD

**Issue by halpz** [Ryochan7/DS4Windows#2063]
**Describe the bug**
when updating to 3.0.2, it asks me to install the latest ViGEmBus version, I do so and DS4Windows can't detect it,
I've tried uninstalling and re-installing the ViGEmBus to no avail, there is a warning showing in device manager that I can't resolve here is a screenshot of my issue:

https://i.imgur.com/9pCw1Cw.png

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: Windows 10 20H2
 - DS4Windows Version 3.0.2

**Comment by aburke20** [comment]
You happen to also have Parsec installed ?

The posted "issue" right below yours seems to think it's the interaction between DS4 and Parsec which is messing up the VigEm.

I have the same exact issue.

**Comment by halpz** [comment]
nope, but I think it is to do with the latest Vigembus installing as a seperate device, the installer of which doesnt remove the old one properly - 
i have just resolved this by going into Device Manager and uninstalling 'Video Game Controller Emulation device' and then disabling then re-enabling the new one that is prefixed with 'Nefarius',

fixed the problem for me

**Comment by halpz** [comment]
> Do you mean "Virtual Gamepad Emulation Bus", under "System Devices" ? Because I also see a "Nefarius Virtual Gamepad Emulation Bus" that's showing a little warning sign.

Yes sorry that’s what I meant

**Comment by aburke20** [comment]
Oh dang, that totally fixed it ! A million thanks, you genius !

**Comment by Ryochan7** [comment]
DS4Windows 3.0.3 has reduced the ViGEmBus restriction to allow driver version 1.16.112.0 to work again. Now Parsec's flawed ViGEmBus install works again and older versions of Windows are temporarily supported again.

I will keep stating this. **PLEASE DON'T MAKE ME REGRET THIS**.
