### ISSUE TITLE
[bug] DS4Windows.exe -command query.1.profilename not working

### ISSUE THREAD

**Issue by bernspedras** [Ryochan7/DS4Windows#2066]
I'm trying to read info from DS4Windows via commandLine i have the software running in the background and then execute it again via command line like this:

DS4Windows.exe -command query.1.profilename

it does not crash, but nothing is printed on the console

 I tracked the issue to this line in App.xaml.cs

 Console.WriteLine(WaitAndReadIPCResultDataMMF(ipcNotifyEvent));

Console.WriteLine is not writing to console because it is a Windows application... is there a way to make it work? am I missing something?

**Comment by Ryochan7** [comment]
Maybe this worked before moving to .NET 5. Console.WriteLine does not work in the Visual Studio output window anymore so Debug.WriteLine would be needed when looking at output in the IDE. I am guessing Console.WriteLine does not work by default anymore when creating a Windows GUI application with .NET. It looks like there might be a way to re-enable that functionality but I have to check if it would work.

Breaking change: OutputType set to WinExe for WPF and WinForms apps
https://docs.microsoft.com/en-us/dotnet/core/compatibility/windows-forms/5.0/automatically-infer-winexe-output-type

**Comment by Ryochan7** [comment]
That isn't going to work out. Having to change the OutputType to Exe as well causes a console window pop appear as well as the GUI window.

**Comment by bernspedras** [comment]
I think this might help..

https://stackoverflow.com/a/31980468/15611765

**Comment by Ryochan7** [comment]
It looks like the **Query** command needed mika-n's DS4WindowsCmd program in order to work with DS4Windows 2.x. For some reason, that program does not work for connecting to DS4Windows 3.x.

https://github.com/mika-n/DS4WindowsCmd/releases

**Comment by Ryochan7** [comment]
Never mind about it not working. Just had DS4Windows 3.0.2 running as Admin but ran DS4WindowsCmd as a normal User. It was just a Permission issue. DS4WindowsCmd works fine with DS4Windows 3.x.

**Comment by mika-n** [comment]
Yes, I think it is best not to mess the new 5.x DS4Windows version with console tricks and just use the DS4WindowsCmd console interface. Makes things simpler to manage in the main app. Maybe at some point there could be a workaround to this, but it is not priority-1 thing because the DS4WindowsCmd interface works already.
