### ISSUE TITLE
Not detecting DS4 controller

### ISSUE THREAD

**Issue by PietroArsi** [Ryochan7/DS4Windows#2068]
Hi, I extracted the files on my desktop, started the program, installed the drivers but my controllers has a yellow light, I tried disabling and enabling the driver but didn't solve the issue. What can I do?

**Comment by bjornstevens** [comment]
Try to see what Windows says. And:
- are you using bluetooth?
- try to see what it does connected to a different usb port

The yellow light makes me think of the casual charing light. Check connection.

**Comment by PietroArsi** [comment]
It's cabled. Same port, same computer works with original version of DS4Windows.

**Comment by bjornstevens** [comment]
try manually installing this: https://github.com/ViGEm/ViGEmBus/releases

**Comment by PietroArsi** [comment]
Still not working, windows makes a sound when I connect it so the PC is detecting it, but DS4Windows is not.

**Comment by bjornstevens** [comment]
Restarting computer? I don't really know much about the cord connected devices as I always use mine on bluetooth. So can't help u there sadly 😢

**Comment by PietroArsi** [comment]
Tried restarting but it's not working :(

**Comment by Masamune3210** [comment]
Try looking in Device Manager for any yellow exclamation points or red X marks

**Comment by PietroArsi** [comment]
Reconnected with bluetooth and turns out it only works with bluetooth! Maybe it's a bug that prevents it from working via USB cable?

**Comment by Masamune3210** [comment]
Its more likely either a bad port/cable or a conflict with something else on your system

**Comment by PietroArsi** [comment]
Like what?

**Comment by Ryochan7** [comment]
https://github.com/Ryochan7/DS4Windows#requirements

**Comment by Ryochan7** [comment]
Pointless
