### ISSUE TITLE
Remove URL from GitHub project description

### ISSUE THREAD

**Issue by JarnoVgr** [Ryochan7/DS4Windows#207]
URL on top of the GitHub project page still points to the outdated website. It might confuse people.

**Comment by Ryochan7** [comment]
This has not been a big concern since there is no dedicated website for this fork. I have a mirror of the site so maybe I should host it somewhere and link to it instead.

**Comment by JarnoVgr** [comment]
If you want to I can get a domain name of your choice and put a github powered site on it. No worries if you want to do it yourself. :)

**Comment by Ryochan7** [comment]
You don't have to worry about that. Such a small site doesn't need a dedicated domain. I think I will just put something up using Github Pages.

**Comment by mitchellmebane** [comment]
@Ryochan7 On a whim, I decided to purchase ds4windows.info.  Right now, it just redirects to https://ryochan7.github.io/ds4windows-site/.  I can set it up as a [GitHub Pages Custom Domain](https://help.github.com/articles/using-a-custom-domain-with-github-pages/) if you'd like.
