### ISSUE TITLE
[BUG] Input Delay on new controller won't change

### ISSUE THREAD

**Issue by baasking** [Ryochan7/DS4Windows#2075]
**Describe the bug**
I recently bought a new controller but I found some input delay. I checked on DS4Windows and the Input Delay is still between 4 - 5ms on BT (10ms on USB) while I having the 1ms setting. With my old controller it feels and does 1ms on Input Delay.  May it be a fake controller?

**To Reproduce**
1. Connect the controller to your pc via Bluetooth or Usb
2. Open DS4Windows -> Profiles -> Edit profiles -> Controller readings
3. See error

**Expected behavior**
I would have thought the Input Delay of the new controller would change to 1ms.

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: [e.g. Windows 10 Home Build 2009]
 - DS4Windows Version [e.g. 3.0.3]

**Additional context**

**Comment by baasking** [comment]
> I recently bought a new controller but I found some input delay. I checked on DS4Windows and the Input Delay is still between 4 - 5ms while I have set the setting to 1ms. With my old controller it feels and does 1ms on Input Delay. Any fix?

May it be a fake controller?

**Comment by Masamune3210** [comment]
Are you using usb or bluetooth

**Comment by Masamune3210** [comment]
Also please fill out the issue template

**Comment by baasking** [comment]
> Are you using usb or bluetooth

Both. With bluetooth it has between 4-5ms and with usb around 10ms.

**Comment by mika-n** [comment]
Do you still have the old controller and does it "feel" snappier? Anyway, there is not much DS4Windows app can do about how the physical gamepad responds. Some fake copycats don't even react to the BT frequency configuration option (probably has only one built-in pre-fixed frequency in the copycat firmware).

**Comment by Ryochan7** [comment]
> I recently bought a new controller but I found some input delay. I checked on DS4Windows and the Input Delay is still between 4 - 5ms on BT (**10ms on USB**) while I having the 1ms setting

I would think the extra latency for the USB connection would be a bigger concern. I am going to assume that it is a copycat controller so there is likely nothing that can be done in software. Be careful where you buy from in the future.

**Comment by baasking** [comment]
I think we all have come to a conclusion that is is a copycat controller. Unfortunately the Input Delay can't be changed. Thank you all for the help and tips.

**Comment by baasking** [comment]
Btw small question. Is there like a way to unlock/reopen the BT poll rate inside of the controller? I've tried to search on the internet but couldn't find an answer so I thought let me ask here. Sorry for the dumb question.

**Comment by mika-n** [comment]
short answer: no
long answer: theoretically yes if you find time and energy to debug the gamepad to see if it just needs some additional commands/bit flags to set those properties within the HW firmware.
