### ISSUE TITLE
ViGEmBus Driver 1.17.333.0 not working properly

### ISSUE THREAD

**Issue by EviLDoGGeR** [Ryochan7/DS4Windows#2079]
After update 3.0.3 from version 3.0.0 I have installed ViGEeBus 1.17.333.0 driver but DS4windows is not working becouse it thinks i am still using older ViGEmBus 1.14.3.3
I tried to install ViGEmBus 1.16.115 but it said I am already using newer version 
Now i cant use my PlayStation 5 DualSense Wireless Controller because DS4windows isnt capable finding controller via cable and bluetooth

**To Reproduce**
1. Go to DS4windows 3.0.3
2. Click on install ViGEmBus Drivers
3. Install drivers
4. Restart Pc
5. DS4windows still say I am using old ViGEmBus 1.14.3.3

**Expected behavior**
After instaling newer Drivers (and restarting Pc) DS4 windows should be using newer Drivers and should find my Dualsense controller via bluetooth

**Screenshots**
![Screenshot_97](https://user-images.githubusercontent.com/82712975/115115115-ddca5b00-9f92-11eb-8233-c7326b61ddd5.png)
![Screenshot_91](https://user-images.githubusercontent.com/82712975/115115155-04889180-9f93-11eb-9a18-779822088fc8.png)
![Screenshot_92](https://user-images.githubusercontent.com/82712975/115115157-07838200-9f93-11eb-8cc6-7d9326cbfdfe.png)

**Desktop:**
 - Controller Make and Model: PlayStation 5 DualSense Wireless Controller
 - OS: [Windows 10 Home]
 - DS4Windows Version [3.0.3]

**Additional context**
Version 3.0.0 of DS4windows worked properly for me
I tried Uninstalling ViGEeBus 1.17.333.0 and reinstalling drivers but it didnt worked

**Comment by mika-n** [comment]
Closed as duplicate #2067

**Comment by Ryochan7** [comment]
What else are people installing?
