### ISSUE TITLE
Touchpad Binding

### ISSUE THREAD

**Issue by Xemiru** [Ryochan7/DS4Windows#208]
I've always thought it'd be useful to bind the touchpad to a specific area of the screen, or a specific offset from a window position. This could be useful in mouse-based games where you have a menu that's always at a certain spot, or in the case of something like emulators, you could bind the touch pad to certain types of inputs allowed by the emulated system. Android and DS emulators come to mind, as well as Luma3DS's input redirection that allows you to give touchscreen input to your 3DS from your computer.

The things that I feel would be a part of implementing this:
- [ ] Profile section binding the touchpad ..
  - [ ] .. to a static screen region
  - [ ] .. to an application and positional offset + size definition
- [ ] Profile section modifying the touchpad's "stretch" mode
  - [ ] Toggle for whether or not out-of-bounds input counts as touching the very edge of the region
- [ ] Allowing touch input to directly translate as mouse dragging
- [ ] Debug option showing the area the touchpad is translating to as well as where current input is seen

To clarify what I mean by "stretch," I mean an option to choose whether or not the program should fit the screen region to the touch pad, or if the touch pad should just stretch across the screen region. Think about if I defined a square screen region and decided I wanted the touchpad to respond only to the center square and not the outer 5ths of the pad (and the toggle is for whether or not I want input on those outer 5ths to count at all).

Mouse input through touchpad is already implemented so it seems like it shouldn't be too much to write, though I don't know the specifics.

**Comment by Ryochan7** [comment]
Having the touchpad act as an absolute mouse might be helpful but I have not had a use case for attempting to try it yet. Getting the touchpad to work as a relative mouse has been the priority and that is reasonable doable now with trackball mode enabled.

Some of the requests could probably be added without much trouble but the Debug option would likely be the most difficult. Some kind of overlay being drawn on-screen showing the area that an absolute mouse pointer would occupy would make mapping so much easier but it would not be possible to render such an overlay over a proper full screen game. Also, I am not sure about semi-transparency being an option for such an overlay. Two reference points that I could probably use for looking into that type of functionality would be Touchmote and Controller Companion.

**Comment by Xemiru** [comment]
There could be other ways to implement the debug feature. Windows' own Snipping Tool comes to mind and performs by freezing the screen (probably just screenshotting and then putting it on top that temporarily) for you to draw a region to "snip." For keeping track of how the binding reacts in relative mode, you could capture an image of the touch region's current area to be previewed in the configuration menu. An overlay shouldn't necessarily be present at all times anyway; it would become a distraction. It should simply serve as a guide to make sure the binding was correct.

**Comment by Ryochan7** [comment]
Finally refactored some Touchpad options to allow more than two different output modes. Over two years later and basic absolute mouse support has finally been added to the Touchpad. So far, the absolute mouse binds to the whole virtual desktop and maximum zone cutoffs for the Touchpad can be defined; it is really hard to reach the very edges of the desktop if using the normal Touchpad coordinate range.
