### ISSUE TITLE
DS4 not appearing via BT

### ISSUE THREAD

**Issue by djesys** [Ryochan7/DS4Windows#2082]
Hi!
Just spent several hours trying to get the DS4 to appear via BT.

What I did:
-  updating intel BT drivers
-  uninstalling HID gaming controller
-  Pair the DS4 via Bluetooth 

no luck, it does not show up under "controller"

USB works fine though.

Any ideas ?

thanks

**Comment by mika-n** [comment]
fake chinese copycat of DS4 gamepad and not a genuine DS4 pad?

**Comment by djesys** [comment]
it´s genuine. It also worked in the past instantly with the version downloaded from jays2kings.
now it doesn´t anymore. When paired, in shows up as "Wireless controller" under "devices".
It´s properties however shows mostly as "unknown". Is that normal ?

**Comment by mika-n** [comment]
So you have used Jays2Kings version of DS4Windows? And in that case you still have ScpVBus virtual gamepad driver installed? ScpVBus used to be the only app doing what it does, but it has been replaced years ago by ViGem driver. ScpVBus did some nasty tricks to work in the first place and cause issues like you have now (ie. BT doesn't work properly). You should clean up the PC and get rid of everything relating ScVBus before installing this DS4Windows/Ryochan7 version and the ViGem/Nefarious driver.

See this: https://vigem.org/projects/ScpToolkit/ScpToolkit-Removal-Guide/

And after following that guide then re-install the latest version of ViGem driver from here: https://github.com/ViGEm/ViGEmBus/releases

And then install the latest version of DS4Windows from here: https://github.com/Ryochan7/DS4Windows/releases

**Comment by djesys** [comment]
I followed the removal guide already. will try the latest driver and report back, thanks
