### ISSUE TITLE
DS4 reconnects as controller #2 after Windows sleep

### ISSUE THREAD

**Issue by zadpos** [Ryochan7/DS4Windows#2084]
To reproduce:
While DS4Windows is running, put windows to sleep. When woken up, DS4 would reconnect as XInput controller #2, making most games not recognize it.

Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2K)
OS: Windows 10 Pro Build 19042.928
DS4Windows Version: Ryochan7 build (version 2.2.10)

Additional Context:
Shutting down DS4 before sleep & re-launching it after wake doesn't seem to cause this behavior.

[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/6343390/ds4windows_log.txt)
[ds4windows_log_20210419.0.txt](https://github.com/Ryochan7/DS4Windows/files/6343391/ds4windows_log_20210419.0.txt)
[ds4windows_log_20210419.1.txt](https://github.com/Ryochan7/DS4Windows/files/6343392/ds4windows_log_20210419.1.txt)
[ds4windows_log_20210420.0.txt](https://github.com/Ryochan7/DS4Windows/files/6343394/ds4windows_log_20210420.0.txt)
[ds4windows_log_20210420.1.txt](https://github.com/Ryochan7/DS4Windows/files/6343395/ds4windows_log_20210420.1.txt)
[ds4windows_log_20210420.2.txt](https://github.com/Ryochan7/DS4Windows/files/6343396/ds4windows_log_20210420.2.txt)
[ds4windows_log_20210420.3.txt](https://github.com/Ryochan7/DS4Windows/files/6343397/ds4windows_log_20210420.3.txt)
[ds4windows_log_20210420.4.txt](https://github.com/Ryochan7/DS4Windows/files/6343398/ds4windows_log_20210420.4.txt)

**Comment by Ryochan7** [comment]
That is one use case that I cannot test on my machine. It never wakes up from sleep; DS4Windows is not a factor there. I would not know if there is still somehow an open handle to an old virtual device or if it more of a driver issue. I will take a look at the method that runs upon suspend to see if anything can be improved.

**Comment by re11ding** [comment]
> 
> 
> That is one use case that I cannot test on my machine. It never wakes up from sleep; DS4Windows is not a factor there. I would not know if there is still somehow an open handle to an old virtual device or if it more of a driver issue. I will take a look at the method that runs upon suspend to see if anything can be improved.

I would like to add that this was an issue with SCPToolkit as well, so you are likely right. I would appreciate you looking into it! It can also happen without sleep mode, as my controller is being detected as player 2 now with no means to readjust.

**Comment by Ryochan7** [comment]
The only change made was that I set the Stop routine to take out the device unplug delays and have the disconnect happen immediately. I can only guess that the extra delays means that Windows will not wait and instead put the system to sleep before the actual unplug routine would run.
