### ISSUE TITLE
Problems with GTA V

### ISSUE THREAD

**Issue by Oduliolol** [Ryochan7/DS4Windows#2085]
I've been using DS4Windows for a while now and I didn't have any problems with it, but now with the new updates I cant get it to work in GTA V, it works when I open the game when the controller is already plugged in, but it used to work if I plugged it while I was playing too. It also does not work in FiveM, a modification for GTA V, that stopped working completely for me.

**Comment by ArgusLi** [comment]
I suggest resubmitting your ticket after going through this guide https://github.com/Ryochan7/DS4Windows/issues/1196

**Comment by Ryochan7** [comment]
This is most definitely a double controller problem. GTA V can read the DS4 as a DirectInput controller so you need to hide the input DS4 if you want to remap the controller with DS4Windows. Were you using the old **Hide DS4 Controller** setting or were you using HidGuardian to hide the input controller before? HidHide is now the preferred way to hide HID devices as it is a much improved driver compared to HidGuardian.

https://vigem.org/projects/HidHide/

I still haven't even played GTA V beyond the intro mission yet. Probably would be more likely to go back and play Vice City instead.
