### ISSUE TITLE
Switch Pro controller. Pairs fine over BT first time I add device, but afterward it always fails to connect. 

### ISSUE THREAD

**Issue by andyktaylor** [Ryochan7/DS4Windows#2087]
DS4Windows works fine for my Playstation DS4, but not for my Nintendo Pro controller.

What happens:

On frst add of Pro controller to my PC using the Bluetooth program, it sucessfully pairs. 
DS4Windows recognises the device, adds it and maps it as an xbox360 controller.

If I then unpair it by either pressing the pair button on the controller, or using a macro in DS4W it then fails to repair. 
Only way to get it to pair again is delete the device from my Bluetooth devices then add again as a new device

Log attached showing it first pairing, me disconnecting it then trying to reconnect:

04/22/2021 09:12:40: DS4Windows version 3.0.3
04/22/2021 09:12:40: DS4Windows Assembly Architecture: x64
04/22/2021 09:12:40: OS Version: Microsoft Windows NT 10.0.19042.0
04/22/2021 09:12:40: OS Product Name: Windows 10 Pro
04/22/2021 09:12:40: OS Release ID: 2009
04/22/2021 09:12:40: System Architecture: x64
04/22/2021 09:12:41: Running as User
04/22/2021 09:12:42: Starting...
04/22/2021 09:12:42: Connection to ViGEmBus 1.17.333.0 established
04/22/2021 09:12:42: Searching for controllers...
04/22/2021 09:12:42: Using Shared Mode
04/22/2021 09:13:16: Found Controller: 98:B6:E9:43:27:3F (BT) (Switch Pro)
04/22/2021 09:13:16: Plugging in virtual X360 Controller
04/22/2021 09:13:16: Associate X360 Controller for input DS4 #1
04/22/2021 09:13:16: Controller 1 is using Profile "Default". Battery level is 100%
04/22/2021 09:14:52: Disassociate X360 Controller for input DS4 #1
04/22/2021 09:14:52: Unplugging virtual X360 Controller
04/22/2021 09:14:52: Controller 1 was removed or lost connection
04/22/2021 09:15:04: Found Controller: 98:B6:E9:43:27:3F (BT) (Switch Pro)
04/22/2021 09:15:04: Plugging in virtual X360 Controller
04/22/2021 09:15:04: Associate X360 Controller for input DS4 #1
04/22/2021 09:15:20: System.AggregateException: One or more errors occurred. (A task was canceled.)
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.IO.FileStream.FlushWriteBuffer(Boolean calledFromFinalizer)
   at System.IO.FileStream.Flush(Boolean flushToDisk)
   at DS4Windows.InputDevices.SwitchProDevice.Subcommand(Byte subcommand, Byte[] tmpBuffer, UInt32 bufLen, Boolean checkResponse)
   at DS4Windows.InputDevices.SwitchProDevice.SetOperational()
   at DS4Windows.InputDevices.SwitchProDevice.StartUpdate()
   at DS4Windows.ControlService.HotPlug()
   at DS4WinWPF.DS4Forms.MainWindow.InnerHotplug2()
   at DS4WinWPF.DS4Forms.MainWindow.<WndProc>b__86_0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---

**Comment by Ryochan7** [comment]
I think I had experienced this before with prior Windows updates. Sometimes Windows liked to keep disconnected devices as available so DS4Windows would find them in its device enumeration process. Obviously the exposed device would not be valid and the final connection process would fail.

Luckily later Windows updates seemed to fix the problem. I have not experienced the problem in the last couple of months at least. As it is, this seems to be more a Windows problem and a DS4Windows issue.
