### ISSUE TITLE
DS4W detection only finds x64 version

### ISSUE THREAD

**Issue by dogstarrb** [Ryochan7/DS4Windows#2088]
DS4Windows is prompting me to install .NET 5, I had already had it installed, uninstalled and reinstalled it, repaired it through their installer, and still, DS4W is telling me I don't have it so it won't run. I finally tried getting the x64 version despite having x86 version for everything else I use, and now it runs fine.

**Comment by mika-n** [comment]
If you have 64bit Windows then YOU HAVE TO use the 64bit (=x64) version of DS4Windows.
