### ISSUE TITLE
[Request] Using headset jack on DS4 v1

### ISSUE THREAD

**Issue by slodias** [Ryochan7/DS4Windows#2089]
Are we going to be use a headset on DS4 version one ? What is the problem? Is it impossible or tough? Do you mind If you explain to us? Thanks. You are doing great work.

**Comment by Ryochan7** [comment]
I have mostly given up hope on that ever getting done. Too many other tasks to worry about and the experimental routine did not work 100% reliably. Haven't messed with that project in a while.

**Comment by Ryochan7** [comment]
Finally got a chance to experience real audio streaming from a PS4 last week. It is definitely higher quality audio than what is possible using the SBC approach.

**Comment by xillmera** [comment]
@Ryochan7 
Hello, I’ve found this [paper](https://habr.com/ru/post/302356/) about this problem helpful. If u r need (engl)translate - I can make it. Text about reversingeneering of captued sound packages from DualShock 4 and description of information composition in it. It’s material, like I can see, directly for this problem.

**Comment by mirh** [comment]
That was already discussed a bazillions times #1268
Btw there's no reason SBC has to be limited to low bitrates (or not sure if DS4 couldn't also support mSBC)
https://habr.com/en/post/456476/

**Comment by Ryochan7** [comment]
Okay. This is getting closed now. That same link that has been posted countless times in a number of threads for years. You aren't helping. The following link is a much better resource and it is what I have used when testing this.

https://sensepost.com/blog/2020/dual-pod-shock-emotional-abuse-of-a-dualshock/

> Btw there's no reason SBC has to be limited to low bitrates/quality (or not sure if DS4 couldn't also support mSBC)

With the SBC approach, you are pretty much stuck with a fixed audio frequency (32 kHz) or the controller will fail to play it properly and induce audio glitching. I cannot remember how much space is given in the output report for the audio packet but it is not a large amount of bytes. Higher quality audio would only be possible if you could somehow access the Wireless BT audio interface of the controller that is separate from the output report. The output report data was only ever meant to play short audio sounds AFAIK.

Sample project:
https://gitlab.com/ryochan7/ds4-audio-test-windows/-/tree/master/

Example SBC conversion command:
https://gitlab.com/ryochan7/dual-pod-shock/-/blob/ryochan-changes/example_sbc_conversion.txt

**Comment by mirh** [comment]
I get that frequency is fixed.. But I find hard to believe bitrate would be too. 
Moreover, there are all the mysteries with SBC mentioned in my link below and here
https://drive.google.com/file/d/1J40QF_gZfW7Lo35lc_pgpGi8MZEeWGVt/view

For instance.. you seem to use a bitpool of 25 in your example (contrarily to the 19 reported by Cristofaro). Couldn't you at least double it?

**Comment by destroyerimo** [comment]
> 
> 
> I get that frequency is fixed.. But I find hard to believe bitrate would be too.
> Moreover, there are all the mysteries with SBC mentioned in my link below and here
> https://drive.google.com/file/d/1J40QF_gZfW7Lo35lc_pgpGi8MZEeWGVt/view
> 
> For instance.. you seem to use a bitpool of 25 in your example (contrarily to the 19 reported by Cristofaro). Couldn't it be at least doubled?
> EDIT: also, see [Pecacheu/dualshock@65e7615](https://github.com/Pecacheu/dualshock/commit/65e7615570afb503729f832fc5d46bf81c9158d9) throwing out DS4W code

this could be it! maybe?
nice find @mirh I did some searching and found this 
https://github.com/signal11/hidapi/issues/378 
and subsequently what he did is 
https://github.com/signal11/hidapi/issues/378#issuecomment-366102817
perhaps he could contribute, hope this could be of help what do you think? @Ryochan7

**Comment by Ryochan7** [comment]
Why do I bother to show the current progress? I have seen that project before and my sample project that I posted earlier is far ahead of that old code. Locking this issue now.
