### ISSUE TITLE
Windows 7 not asking for pairing code.

### ISSUE THREAD

**Issue by brothan323** [Ryochan7/DS4Windows#209]
I am unable to connect my ds4 controller to my bluetooth dongle as Windows 7 never asks for a pairing code, even on a fresh install. How do I fix this issue?

Edit: So it paired, but the controller does not work except the touchpad that controls the mouse.

**Comment by Ryusennin** [comment]
I have no such issue on the same OS. You paired your controller with "0000"?

**Comment by brothan323** [comment]
Windows never asks for a paring code. The DS4 controller will randomly pair(most of the time failing,) but when it does pair the only thing that works is the touch pad to control the mouse. A fresh install doesn't fix this.

**Comment by brothan323** [comment]
Ok now a new issue is rising. The LED will sometime blink red if it's connected to bluetooth device.

**Comment by czukowski** [comment]
Blinking red indicates the connection latency is over a certain threshold, unless it blinks like it often you don't need to worry about it.

As for the controls, click the 'Control Panel' link in the Settings tab, then double click on XBOX controller and a testing window will open. The screenshot below is from an old version of the program, but it gives the idea.

![Settings](http://ds4windows.com/images/settings.png)

If there's no XBOX controller listed or the controls don't work in the testing window, search through the other issues here and try the suggestions you find there.

**Comment by Ryochan7** [comment]
Which version of DS4Windows are you running? If you are running the last Jays2Kings release (1.4.52) then I would recommend that you update to the most recent version posted here (1.4.109).

Before trying your DS4 on any games, you might want to go to the Game Controller Settings window by clicking the Control Panel link in the Settings tab. Check that the virtual Xbox 360 controller is working and that the DS4 has been hidden from the system. The DS4 might necessarily need to be hidden in order for it to be usable on some games but double input and other problems come up often enough that you will likely want the DS4 hidden from the system at all times while using DS4Windows.

The blinking red lightbar shows that the average latency between gamepad polls is at least over 10 ms; it could be a different number depending on your settings (defaults to 20 ms). Besides application problems, your BT dongle might be a problem. I would recommend that you have a BT 4.0 dongle for pairing a DS4 to although using a BT 2.1 dongle could work. I have two BT dongles for testing but I primarily use my newer Rosewill RNX-BT401. Even though the input delay averages slightly higher with my newer dongle when using one controller, it can handle multiple controllers without any issue; using my older Rocketfish BT 2.1 dongle with multiple controllers paired results in massive fluctuations in input delay unless the BT poll rate is set at 8 ms or higher. You can also try various values for the BT Poll Rate in your profile and see if that helps with your problem (located under the Other section).

**Comment by Ryochan7** [comment]
Even though there is no control over the problem, it does not help that the MS Bluetooth Stack is pretty terrible. I wish the old Toshiba Bluetooth Stack was usable on Windows 10.

**Comment by brothan323** [comment]
Ryo I am using the most recent version (1.4.109) and I have the broadcom 4.0 usb device.

**Comment by Ryochan7** [comment]
I checked both of my BT dongles. My newer one uses a CSR chipset but my old Rocketfish uses a Broadcom chipset.

One other option that I can suggest is for you to check your computer's Power Plan setting. I would recommend that you use the **High Performance** power plan if it is not enabled.

**Comment by czukowski** [comment]
FWIW, I've had far better experience with my crappy Asus BT-400 by connecting it to a couple meters long USB extension cord and dropping it closer to a place the controller is used the most. Moving it around may have dramatic effect on latency, depending on distance and whether there are any objects in between. Even people standing between the BT receiver and the controller affect the latency. Your mileage may vary, of course.

**Comment by brothan323** [comment]
The odd thing here is that my controller did connect to my bluetooth, once, and I played db fighterz for a bit. Now it's just not wanting to connect:\ 

I remember when I was using the SCP ds3 wrapper, I had to used a specific program that came with the DS3 wrapper, and install their own driver over my bluetooth's driver to get the ds3 to connect...would this be the problem I am having here? That I need to install a driver over the one windows 7 installed for me?

**Comment by czukowski** [comment]
No, the DS3 required a dedicated Bluetooth dongle because its own Bluetooth communication did not support anything compatible with Windows. There's no such problem with DS4.

Some of the options you could try at this point, some of them have helped me before:

- See the Settings tab, and if Hide DS4 controller is enabled, try disabling it. It may cause it to not work with some apps or games, but it also there tend to be less connection issues with this option disabled (Ryochan7 has implemented some improvements over time, but some issues connected to it are outside of his control)
- Try changing x-input channel from its current (not shown on the screenshot above) number to a higher one, then try to reconnect
- Try pulling out the Bluetooth dongle from the USB port and reconnect after a few seconds
- Also, try opening the Devices and Printers control panel and see if the controller doesn't have a small icon over it that indicates it is disabled, if it is, try enabling it
- Re-pairing the controller to the computer may also help
- Restart the computer, that should fix any non-permanent issue

**Comment by czukowski** [comment]
@brothan323 if you managed to find a solution, feel free to post it, it may be helpful to the others with the similar issues.
