### ISSUE TITLE
ds4 reading ps5 dualshock but input in game does not work.

### ISSUE THREAD

**Issue by alexson3** [Ryochan7/DS4Windows#2092]
**Describe the bug**
have connected my Ps5 dualshock to ds4 windows it reads the device and connects but when i go in the game it doesnt acknowledge any inputs except the touchpads.

I have redownloaded the file and multiple times it will connect to the controller. 

it will indicate that it is connected but as soon as i run a menu start up game there is no input acknowledged by the pc except the touch pad on the controller.

 - Controller Make and Model: Sony dualshock 5 )
 - OS: Windows 10 Pro Build 2004
 - DS4Windows Version 3.303

**Comment by mika-n** [comment]
please see the "Read this before posting a new issue ticket" post and provide the latest logfile (%APPDATA%\ds4windows\logs folder) as a TXT file attachment (rename the latest logfile as .TXT file and drag-n-drop here in the comment field).

BT or USB connection?
Are you using "Hide DS4 Controller" (=exclusive mode) option?
Or are you using HidHide tool to hide the physical gamepad?

https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues
