### ISSUE TITLE
the gamepad ds4 v.2 (USB) uses custom feature set (MonitorAudio)

### ISSUE THREAD

**Issue by Gallade321** [Ryochan7/DS4Windows#2094]
I extracted the files on the folder i downloaded and when I run the exe file it always says "the gamepad ds4 v.2 (USB) uses custom feature set (MonitorAudio)" at the bottom and i can't use my ds4. How can i fix this?
![error](https://user-images.githubusercontent.com/83169635/115994385-53749d80-a609-11eb-84aa-521182849015.PNG)

TIA :)

**Comment by Masamune3210** [comment]
Please go back and make a new issue. This time actually fill out the issue template instead of just blowing it away, it has information that will help people figure out your issue
