### ISSUE TITLE
Bluetooth audio stream with dualsense issue

### ISSUE THREAD

**Issue by SeRoM** [Ryochan7/DS4Windows#2095]
**Describe the bug**
Hello,

I have a strange problem with dualsense and headphones Bose QC 35 II.
When I pair the controller with the PC. Audio is transmitted intermittently.

As soon as I turn off the controller, the sound is again correctly played through the headphones.

I use the native bluetooth of a Maximus XI Formula. A bluetooth 5.0 chipset. I never had a problem with this setup and the DS4 controller.

Have you ever encountered this kind of problems?
Thank you for your comeback,
cordially

**To Reproduce**
1. Connect bluetooth audio headphone (sound ok)
2. Connect DualSense with bluetooth
3. Test in sound dialog or launch a game
4. Audio stutter or audio disconnect/reconnect 

**Expected behavior**
The controller must not saturate the connection

**Screenshots and Logs**
![image](https://user-images.githubusercontent.com/7047226/116125851-479ae100-a6c6-11eb-90fa-37f68daf5b7b.png)
![image](https://user-images.githubusercontent.com/7047226/116126175-9d6f8900-a6c6-11eb-960f-4d104ba3430e.png)

**Desktop (please complete the following information):**
 - Controller : Sony DualSense (CFI-2CT1W)
 - OS: Windows 10 Pro Build 2004
 - DS4Windows Version [e.g. 3.0.3]
 - Motherboard : ASUS ROG Maximus XI Formula

**Comment by SeRoM** [comment]
Hello, 
I think the "BT Poll Rate" parameter is the cause of my problem.
Set another value other than 1ms is not saved or used. Input Delay show always : 1ms 

Am I the only one in this configuration?

**Comment by soredake** [comment]
Did you managed to solve the problem?

**Comment by SeRoM** [comment]
Unfortunately no. I live with it, it's so random.
Glad to see that I'm not the only guy in this situation.
Someone had provided an explanation here: https://github.com/Ryochan7/DS4Windows/issues/2101#issuecomment-830678655

Apparently, the bluetooth built into motherboards are not very efficient (which is still surprising).
The situation should improve with time and updated drivers.

(Sorry for the wrong post just before)
Regards,
