### ISSUE TITLE
Special Actions / Switch Profile / ADS (AIM DOWN SIGHT) For sticks

### ISSUE THREAD

**Issue by NoElitesRUS** [Ryochan7/DS4Windows#210]
Hello Travis. First I would like to thank you for your software, amazing program. I ran into a problem.
I need that, when the button of the gamepad is clamped, I decrease the sensitivity of the stick. And when the button is released, the sensitivity becomes the same. How can I do that? The first thing that comes to mind is switching profiles, but they can be switched only by pressing and not by clamping.
(*I apologize for Google translator, I do not speak English.) <img src='https://i.imgur.com/Y7xAdwh.jpg' />

**Comment by Ryochan7** [comment]
There is no way to do that currently. Using a shift modifier would probably be what you would want but those only affect the base output binding. Shift modifiers in DS4Windows don't work like mode shifts in Steam. The only alternative available is to use the **Change Mouse Sensitivity** option that could be used if you are using a mixed gamepad and mouse profile or using a KB+M profile.

![button_bind_crop](https://user-images.githubusercontent.com/581968/35889238-5380fb94-0b60-11e8-97bd-c77d3f488ac1.png)

**Comment by NoElitesRUS** [comment]
Oh, very sorry.( Unfortunately, this is not what I need. Can you make it so that the profile would switch only for a while while the button is clamped? Tell me how difficult it is to implement this in future updates? After all, the program already knows how to switch profiles on the "fly". I think it will be useful not only for me. Many people find it hard to aim at a gamepad, and not in all games do developers implement the ADS function. Yours faithfully and thanks that responded. :)
![rrterte45454](https://user-images.githubusercontent.com/36156137/35900620-fda63cc8-0be3-11e8-8394-525c7779c0f5.jpg)

**Comment by NoElitesRUS** [comment]
By the way in the early versions of the program such an opportunity was. https://www.youtube.com/watch?time_continue=183&v=d8OMwcdvWtQ

**Comment by Ryochan7** [comment]
That fork of DS4Windows is different than the one from Jays2Kings. That type of functionality does not exist in the version derived from Jays2Kings. You can give InputMapper a try and see if it will work out.

As for aiming with the stick, that is why I usually choose to use emulated mouse for the right stick in any shooter games. Some games have problems with mixed gamepad and mouse input so a full KB+M profile is needed in those cases which is a bummer. One recent example of a game that I played with those kind of problems is Warhammer 40K: Space Marine. The mouse sensitivity would get drastically reduced if gamepad input was detected so a full KB+M mapped profile was needed to have proper mouse sensitivity.

**Comment by NoElitesRUS** [comment]
>  Yes indeed there it is possible to make such a macro, but it does not work either.)) Fack... https://inputmapper.com/forum/inputmapper-1-5-support/835-ads-aim-down-sight-macro
