### ISSUE TITLE
DS4WINDOWS connects to Dualsense but doesn't detect input

### ISSUE THREAD

**Issue by Hierro3000** [Ryochan7/DS4Windows#2103]
It looks like recently I'm not the only one with this problem.
My Dualsense gets connected with DS4WINDOWS but doesn't detect input (therefore it doesn't link with Stadia).

This started happening after I tried to update Windows 10 (it didn't suceed the first time) a week ago. 
I've been playing without DS4Windows as a generic/Dualshock 4. But I want to play with the rumble again.

I've tried reinstalling DS4WINDOWS, ViGEmBus and the Windows 10 update. Tried to play via USB aswell (although I never do because it screws the audio), Messed with the "Hide DS4 Controller" option. Tried testing it on GeForce Now. It's always the same problem. 
[logfile.txt](https://github.com/Ryochan7/DS4Windows/files/6411537/logfile.txt)

**Comment by Kanuan** [comment]
according to your LOG:
`05/02/2021 15:50:52: Controller 1 is not using a profile. Battery level is 100%`

it is stuck in a no profile state. Changing to another profile should fix the issue

**Comment by Kanuan** [comment]
> Tried to play via USB aswell (although I never do because it screws the audio)

On USB, Windows has access to the controllers Audio port and will auto-change to it. You just need to change back to your desired audio device
![image](https://user-images.githubusercontent.com/24910442/116823386-9b8c4680-ab5a-11eb-8b65-be4f18e76fad.png)

**Comment by Hierro3000** [comment]
Damn thank you so much!
