### ISSUE TITLE
DualSense 0% battery after fully charged

### ISSUE THREAD

**Issue by Whatsup12345** [Ryochan7/DS4Windows#2104]
Hello,

I have this problem which seems to persist, I charge the controller 100% in the evening, and next day when I try to connect via BT, is dead=0% battery. 
I searched a bit on the internet and this often encountered, and DualSense controller update via ps5 should solve the problem. However I don't know somebody with ps5, and I want to ask, is there any possibility to update the controller via DS4Windows app?

10x!

**Comment by Masamune3210** [comment]
there is currently afaik no way to update the firmware of the dualsense other than a ps5. the only way that will change is if someone reverses the update process and extracts the controller firmware from the main update or sony decides to update it themselves through something like ps now unfortunately

don't feel bad, I'm in the same boat

**Comment by Whatsup12345** [comment]
That's sad:(
10q for reply

**Comment by Ryochan7** [comment]
I have encountered that problem every once in a while. Not sure why it happens but at least it is good to know that a firmware update would fix the problem. I don't own a PS5 nor do I know anybody that owns one either. Unfortunately, it looks like we are going to have to live with the problem for a while. I am not optimistic about firmware updating getting deciphered to allows updates from a PC.

**Comment by Whatsup12345** [comment]
Well, there are some stores near me, where I can find ps5 pay/to play, and I"ll try to ask someone there if they can allow me  to change the firmware on my controller, and I'll come back here to say if that solved the problem, but it may take some time.
Now I have another problem...doesen't want to charge..., I have to "walk" through all usb ports until I find one that works, I have also a usb C port on the MB, and not even that one doesen't charge it, with a usbC to usbC cable.

**Comment by leronoa** [comment]
If you haven't tried, try resetting the controller holding the button on the back for 3 to 5 seconds, that fixed it for me.

**Comment by Whatsup12345** [comment]
Tried that, already twice:(

**Comment by Lunahria** [comment]
My controller is up to date as I have a PS5 on hand, battery is still 0% for me with 3.0.5.

**Comment by Whatsup12345** [comment]
That's sad, it's happen random and I don't if you can ask for a replace, I suppose that's a software problem, not a hardware one.

**Comment by Kanuan** [comment]
> Wireless performance for me is latency infested, we're talking over 40 ms of lag and beyound because I put my hand on the back of my controller for a second or put it on my lap or similar. The BT dongle is right next to me, it's not even at a meter distance from the front-top USB panel of my PC case,

Regarding latency, is your BT dongle in a USB 3.0 port? Some 3.0 ports cause wireless interference with BT dongles

**Comment by Lunahria** [comment]
> Regarding latency, is your BT dongle in a USB 3.0 port? Some 3.0 ports cause wireless interference with BT dongles
> ## EDIT 1
> 
> A good test would be having a (high quality) USB extensor, so the BT dongle sits far away from the case

I don't wanna derail the topic with this but if I have to keep my dongle glued to the controller, I might as well use a cable. I gave up on wireless on PC many years ago, if I want that, I would just use my Xbox One controllers with their wireless adapter.

**Comment by Whatsup12345** [comment]
I have a MB with bluetooth 5.1(Asus b550 e gaming), and it use an antenna to improve the signal, so in my case I have 0 issues with latency even at a few meters from antenna. Being a wireless controller, I want to use it that way, I just don't like it cabled, not to mention if you have 2 or more, to connect 4 controllers via cable, and try to find a place in the room without tangling the cables:))

**Comment by Lunahria** [comment]
> That's sad, it's happen random and I don't if I/you can ask for a replace, I suppose that's a software problem, not a hardware one.

I think I misinterpreted your original post, you are saying your controller is dead pressumably because it's still working when it should be off, correct?

**Comment by Whatsup12345** [comment]
Yes, that's what I think is happening.., I charge it in the evening 100%, I turn it off, and the 2nd day it's dead=0 battery. So I think that even if it's turned off and the led is also off....he is still on. Also if it happens often, it will degrade the battery very quickly.
And for me is happen quite often, for now I switched off BT from motherboard, to see if that has any effect.

**Comment by Lunahria** [comment]
> Yes, that's what I think is happening..
My bad for the 0% battery posts then, I was thinking about the battery reading. I have not tested if it happens with updated firmware as I use cable for consistency.

**Comment by Idearum** [comment]
> Yes, that's what I think is happening.., I charge it in the evening 100%, I turn it off, and the 2nd day it's dead=0 battery. So I think that even if it's turned off and the led is also off....he is still on. Also if it happens often, it will degrade the battery very quickly.
> And for me is happen quite often, for now I switched off BT from motherboard, to see if that has any effect.

After you've "turned the controller off", open the Settings app in Windows and navigate to Devices -> Bluetooth & other devices and check if the "Wireless Controller" has status "Paired" or status "Connected".

I experienced this weird "battery drains overnight" issue myself and after having troubleshooted it a while today I noticed that the controller doesn't actually disconnect properly from Windows, so even though the lights were off and it looked dead it was still connected. It kept doing this whenever I "turned it on" and "turned it off" on and on until I re-paired the controller entirely with Windows.

Once I had it working properly again I could start to troubleshoot it a bit more by testing what worked and what didn't, and what I noticed was that seemingly the issue would began after I had launched DS4Windows and allowed it to manage the controller. If I "turned off" the controller while DS4Windows was running, everything went as expected and the controller powered off properly. But the moment I stopped DS4Windows' service (while the controller was powered off) and powered on the controller (while DS4Windows was still open, but its service not running) the issue began anew.

After that point, no matter what I did the controller wouldn't power off properly unless DS4Windows was running, or I started DS4Windows (at which point it would detect the connected controller and hit a read error and force-power it off).

I haven't really nailed down the specifics yet, and it's fully possible DS4Windows (or ViGEmBus) isn't entirely the cause of the issue, but at least now I know how to work around it -- have DS4Windows (and its service) running while powering off the controller, and then verify through Settings > Devices that the controller switches over from "Connected" status to "Paired" status properly.

**Comment by Lunahria** [comment]
The described above occurred to me on a DualShock as well!

**Comment by Whatsup12345** [comment]
> > Yes, that's what I think is happening.., I charge it in the evening 100%, I turn it off, and the 2nd day it's dead=0 battery. So I think that even if it's turned off and the led is also off....he is still on. Also if it happens often, it will degrade the battery very quickly.
> > And for me is happen quite often, for now I switched off BT from motherboard, to see if that has any effect.
> 
> After you've "turned the controller off", open the Settings app in Windows and navigate to Devices -> Bluetooth & other devices and check if the "Wireless Controller" has status "Paired" or status "Connected".
> 
> I experienced this weird "battery drains overnight" issue myself and after having troubleshooted it a while today I noticed that the controller doesn't actually disconnect properly from Windows, so even though the lights were off and it looked dead it was still connected. It kept doing this whenever I "turned it on" and "turned it off" on and on until I re-paired the controller entirely with Windows, which solved the broken power off behaviour.
> 
> Once I had it working properly again I could start to troubleshoot it a bit more by testing what worked and what didn't, and what I noticed was that seemingly the issue would began after I had launched DS4Windows and allowed it to manage the controller. If I "turned off" the controller while DS4Windows was running, everything went as expected and the controller powered off properly. But the moment I stopped DS4Windows' service (while the controller was powered off) and powered on the controller (while DS4Windows was still open, but its service not running) the issue began anew.
> 
> After that point, no matter what I did the controller wouldn't power off properly unless DS4Windows was running, or I started DS4Windows (at which point it would detect the connected controller and hit a read error and force-power it off). The issue even persisted across restarts of the computer even though DS4Windows wasn't configured to launch with Windows.
> 
> I haven't really nailed down the specifics yet, and it's fully possible DS4Windows (or ViGEmBus) isn't entirely the cause of the issue, but at least now I know how to work around it -- have DS4Windows (and its service) running while powering off the controller, and then verify through Settings > Devices that the controller switches over from "Connected" status to "Paired" status properly.

**Comment by Whatsup12345** [comment]
"Idearum" ...10x for your explanations. I remember that I saw on reddit I think, that some users had the same problems with DS used only with ps5, and someone said that updating controller firmware solved the problem. So the idea is that some unlucky units came with this problem, and apparently can be solved with controller update, which can be done only on a ps5.
For me, I didn't have time to use the controller lately, but what I did last time is that I switch BT to off (disabled from windows) and no battery drain  until now. So I'm guessing that when the controller find the BT source on which was connected, DS will try to pare without stopping until battery die, and if don't find the BT source it might go to sleep. It's still early to say for sure, I'll keep checking.

**Comment by DaRkL3AD3R** [comment]
This is a huge problem but I am 99% sure it has nothing to do with DS4Windows or PC at all. I think it's just a DualSense problem that even regular PS5 users face. It seems to be the easiest solution is, when you plug in the controller to charge it and then it's done charging and you unplug it, quickly turn it on via Bluetooth then turn it off. There seems to be a problem when you plug it in and disconnect it where it stays in some false powered on state not connected to anything but not fully asleep. By cycling the Bluetooth connection, this puts it in a proper deep sleep and saves battery. It's just annoying that you have to do this every time you charge it because you never know when the glitch will happen again.

**Comment by mika-n** [comment]
and make sure DS5 gamepad has the latest firmware. At the moment hooking it into PS5 console is the only way to update ds5 firmware.

**Comment by Whatsup12345** [comment]
> This is a huge problem but I am 99% sure it has nothing to do with DS4Windows or PC at all. I think it's just a DualSense problem that even regular PS5 users face. It seems to be the easiest solution is, when you plug in the controller to charge it and then it's done charging and you unplug it, quickly turn it on via Bluetooth then turn it off. There seems to be a problem when you plug it in and disconnect it where it stays in some false powered on state not connected to anything but not fully asleep. By cycling the Bluetooth connection, this puts it in a proper deep sleep and saves battery. It's just annoying that you have to do this every time you charge it because you never know when the glitch will happen again.

Ok, I'll try this also until I'll find a ps5 to update the firmware. Also disable BT from windows seems to work for me, but is not a solution if you need to connect something else via BT. 
10x

**Comment by Zaazu** [comment]
I'm planning on buying one of the new Midnight Black DualSense controllers, but I don't have a PS5 so update the firmware. Does anyone have the new controller and can test if it's running the latest firmware out of the box?

**Comment by shazzaam7** [comment]
I just got Cosmic Red variant and the battery indicator is sadly also acting weird. When charging it's either 12% or 25% and when it's not charging it's usually shows 50%. I even mapped mic button to check battery and it works sometimes (Super inconsistent). Overall it's pretty inconsistent and I don't think it shows the right value even when it's not 12,25 or 50%.

**Comment by Zaazu** [comment]
That's disapointing.

**Comment by DaRkL3AD3R** [comment]
Picked up my midnight black dualsense today and so far everything seems to be working flawlessly. I even seem to have better battery life compared to my old vanilla white dualsense with no firmware updates applied (don't have a PS5). LOVING this thing.

**Comment by Zaazu** [comment]
I ended up buying one too, arrives soon. Hopefully it works fine but worst case is, I'll just use it wired and wait for one of my friends to buy a ps5 or something :D

**Comment by mika-n** [comment]
and while waiting for it send a msg to Sony and ask them to add DS5 firmware update logic into PSRemotePlay PC app.

**Comment by mika-n** [comment]
closed because DS5  battery draining or battery %-value is not a DS4Windows app issue. It is more an issue with the DS5 firmware and the only way to update it is to hookup the DS5 into PS5 console.
