### ISSUE TITLE
Sometimes GeForce Now isn't detecting gamepad with DS4Windows

### ISSUE THREAD

**Issue by FilipCCz** [Ryochan7/DS4Windows#2105]
Games on GFN doesn't always recognise gamepad input, so you can't actually use it and only "fix" I have found is to restart your pc until it works. Stopping DS4Windows doens't help, nor reinstalling GFN and/or DS4Windows (both with clearing AppData folder)
Any ideas how to fix it or anything?
Thanks

**Comment by Ryochan7** [comment]
GeForce Now is useless bloatware. Don't use it.

More practical advice would be to install and configure HidHide. You likely need to hide the real DS4 controller from GeForce Now.

https://vigem.org/projects/HidHide/
https://vigem.org/projects/HidHide/Simple-Setup-Guide/

**Comment by Masamune3210** [comment]
Could you be thinking of GeForce Experience? GeForce Now is the game streaming service

**Comment by FilipCCz** [comment]
> GeForce Now is useless bloatware. Don't use it.

You probably mistook it with GeForce Experience, GeForce Now is a gamestreaming service which I use for games that my PC can't run. 
Otherwise they released an update yesterday and I didn't need to restart to get my gamepad working, so it seems to be working, for now.
