### ISSUE TITLE
Special Actions to launch programs not working after updating to 3.0.3

### ISSUE THREAD

**Issue by Mister-Curious** [Ryochan7/DS4Windows#2106]
**Describe the bug**
After updating to 3.0.3 none of my  previously saved Special Actions are working, nor am I able to create new ones (that involve launching a program), that function at all. 

**To Reproduce**
1. Download and install DS4Windows 3.0.3
2. Click on 'Edit Profile'
3. Scroll down to 'Special Actions' then use 'New Action'
4.  Navigate to 'Select an Action' and select 'Launch a program'
5. Choose any exe file on your computer that you feel is safe to launch for testing. 
6. Choose an action to trigger the event in the 'Trigger' section on the left hand side panel. 
7. Just beneath the 'Arguments' field, click the Save button. 
8. Next to 'Profile' at the top of the window click save. 
9. Execute action specified in step 6
10. NOTHING HAPPENS. 

**Expected behavior**
Expected this to work as previously designed. In this case the expected behavior would be to execute the desired Special Action. 

**Screenshots and Logs**
05/03/2021 18:27:58: DS4Windows version 3.0.3
05/03/2021 18:27:58: DS4Windows Assembly Architecture: x64
05/03/2021 18:27:58: OS Version: Microsoft Windows NT 10.0.19042.0
05/03/2021 18:27:58: OS Product Name: Windows 10 Pro
05/03/2021 18:27:58: OS Release ID: 2009
05/03/2021 18:27:58: System Architecture: x64
05/03/2021 18:27:58: Running as User
05/03/2021 18:27:59: Starting...
05/03/2021 18:27:59: Connection to ViGEmBus 1.17.333.0 established
05/03/2021 18:27:59: Searching for controllers...
05/03/2021 18:27:59: Using Exclusive Mode
05/03/2021 18:27:59: The gamepad Sony WA (SONYWA) uses custom feature set (MonitorAudio)
05/03/2021 18:27:59: Found Controller: A4:AE:11:55:C2:4F (SONYWA) (Sony WA)
05/03/2021 18:27:59: Plugging in virtual X360 Controller
05/03/2021 18:27:59: Associate X360 Controller for input DS4 #1
05/03/2021 18:27:59: Controller 1 is using Profile "Fallout 4". Battery level is 100%

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2
 - OS: Windows 10 Pro Build 20H2
 - DS4Windows Version 3.0.3

**Additional context**
I reverted back to an older version of DS4Windows (2.2.1) to test this out. While the currently saved Special Actions would not work, I was able to at least make new ones that worked, whereas I could not do this in 3.0.3

I can also confirm that in another test reverting to DS4 Windows 2.2.15 that I was able to create new working Special Actions to launch programs, but loading my previously saved profiles that included Special Actions to launch programs did not work at all. 

And lastly, I can also confirm that recreating a profile from scratch in 2.2.15 (and saving it to file, then placing this file in the 'Profiles' folder of 3.0.3 had no effect. I am not sure if this is because the Profiles.xml file also needs to be updated with the newly added profile or not.

**Comment by Ryochan7** [comment]
Assuming some of those processes need to be run elevated. Otherwise, the routine should have worked as it was. Either way, another place to set UseShellExecute for ProcessStartInfo.

**Comment by Ryochan7** [comment]
It should work in DS4Windows 3.0.4.
