### ISSUE TITLE
vigembus driver isn't detected in ds4windows

### ISSUE THREAD

**Issue by Exjected** [Ryochan7/DS4Windows#2107]
**Describe the bug**
Okay so, everytime when I restart my PC, DS4Windows asks me to install the vigembus driver, tho i have it installed.

**To Reproduce**
1. Download DS4Windows 3.0.3
2. Wait for the controller to work (sometimes it works)
3. Restart your PC.
4. and you have the error

**Expected behavior**
One of my games were being stupid so I decided to restart my PC for it to work (this happens a lot, restarting your PC will fix the issue most of the time)

**Screenshots and Logs**
![dense](https://user-images.githubusercontent.com/73783394/117067928-e957a900-ad2a-11eb-8c8c-ee9d335867d8.png)
No logs cuz idk where it went

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS5 v.1 (CFI-ZCT1W)
 - OS: Windows 10 Pro Build 20H2
 - DS4Windows Version 3.0.3

**Additional context**
nah

**Comment by K54M** [comment]
Do you have an HP laptop or pc ? Cause if you do I would recommend you to follow this > https://github.com/ViGEm/ViGEmBus/issues/99. I see the ViGemBus 1.14.3.3 message on the bottom right. Pretty sure thats your issue.

**Comment by Exjected** [comment]
actually, i have a prebuilt hp (omen) pc yea

**Comment by Ryochan7** [comment]
I am considering almost all older ViGEmBus inquiries invalid due to a recently discovered terrible and extremely outdated HP fork of ViGEmBus. DS4Windows 3.0.4 should be able to skip that flawed fork and attempt to use the latest official ViGEmBus driver.

**Comment by Exjected** [comment]
aight, i'll close this issue.
