### ISSUE TITLE
REQUEST - Display all file types when choosing a file to launch

### ISSUE THREAD

**Issue by Mister-Curious** [Ryochan7/DS4Windows#2109]
Thanks for fixing the Special Actions launch issue in 3.0.3. I am hoping to see a small fix that would allow us to display all file types whe choosing a file to launch with Special Actions. 

Currently when we choose 'Launch a Program' from the options in Special Actions, there is a 'Browse' button that opens a window. In this window we are only allowed to see .exe and .bat files. It would be great to be able to chose any file type (like .ahk for example) as scripts are often part of game play. For certain games using AHK is the only way to send keyboard input, so its kind of imperative. 

Apologies for the somewhat double post (I asked something similar in the comments of the previously mentioned Special Actions launch issue in 3.0.3 commit page, but not sure if anyone saw it or if it was the right place to post. 

Thank you !

**Comment by mika-n** [comment]
The problem with AHK script type is that from DS4Windows app it would not work even when it would just "run" the AHK script itself. DS4Windows should lookup the file mapping table you have set in WinOS settings and then use the AHK assigned executable to run the AHK script itself.

You can run AHK scripts directly from FileExplorer by double clicking the file, but in that case FileExplorer does the same and lookups which app is set to handle and "run" AHK scripts by default. Sure DS4Windows app could do the same, but it doesn't at the moment.

Instead you can bind AHK scripts to DS4Windows buttons by launching the AutoHotKey.exe app itself and pass the AHK script name in the argument field.
![ds4win_AHKLaunch](https://user-images.githubusercontent.com/35538525/117566666-aac24580-b0c0-11eb-89d2-8bd2ddd4f508.png)

Or you can turn AHK scripts as EXE apps in AutoHotkey if you find this "run authotkey.exe with an argument" too troublesome to setup.

**Comment by Ryochan7** [comment]
I'm not sure the Process class could work directly with arbitrary files that way. Other than executable files like .exe, .bat, and .msi, most every other file would need to be launched through explorer.exe in order to launch in your chosen preferred program for that file type. It would probably just be easier to link to a small batch script that makes the call to open the AHK script and have DS4Windows launch that.

**Comment by Mister-Curious** [comment]
Thanks for the replies but the solutions you both posted are unnecessary. The thing is this; DS4Windows launches the AHK scripts just fine from Special Actions, but I have to manually cut/paste the directory and file name. For example, when I use the 'Browse' button I look for sciprt, but I cant see it (only exe and bat show up), so as a workaround I can simply type:

_C:\Users\User\Documents\SCRIPTS\DS4_001.ahk_

So really its just a matter of changing what file types are allowed to be seen.

**Comment by mika-n** [comment]
hmm...... very interesting that the process execution code in DS4Windows works out-of-the-box with AHK scripts. The process class in C# must somehow make the lookup to the app responsible to handle a certain file extension. Okey, maybe the dialogbox should have "all (*.*)" file filtering option.

**Comment by Mister-Curious** [comment]
Thank you kindly for your consideration.

**Comment by Ryochan7** [comment]
I'll have to check this as there is an explanation for why it might work in cases. If DS4Windows is running under the Admin user, a routine is run to launch any program through explorer.exe so the other program will not be running with elevated privileges. That is done for security purposes.

**Comment by Mister-Curious** [comment]
ok. For the record, I think this function was working while running DS4Windows without elevated permissions. I can confirm it does work with elevated though as that is how I run it now.

**Comment by Ryochan7** [comment]
Confirmed that it does work even as a normal user. I'm guessing some layer is likely using the preferred association set in explorer.exe to open the file. I'll get the change committed.

**Comment by Mister-Curious** [comment]
Thank you for implementing this!

**Comment by Mister-Curious** [comment]
@Ryochan7 Could I make a small request related to this one? It would handy if the Windows Explorer pop-up window for 'Launch Program' in Special Actions remembered the last directory opened, or if users could set a directory. Presently it defaults to Program Files (which I can see being useful), but it would be nice to set our own defaults for this. 

Thanks!
