### ISSUE TITLE
My profiles get deleted everytime I reopen DS4Windows

### ISSUE THREAD

**Issue by NSH-2814** [Ryochan7/DS4Windows#2110]
**Describe the bug**
Whenever I close then reopen DS4Windows it asks me where to save my profiles (program folder or appdata). Whenever I choose any of them, the problem still persists.

**To Reproduce**
1. Open DS4Windows
2. Close DS4Windows (using the X button on the top right corner, without the "close minimizes" option checked)

**Expected behavior**
Using my saved profiles as usual without them getting deleted.

**Screenshots and Logs**
![image](https://user-images.githubusercontent.com/68939092/117246784-46984b00-ae4e-11eb-8b9d-8b3b8a7d0415.png)
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/6432003/ds4windows_log.txt)
[ds4windows_log_20210429.0.txt](https://github.com/Ryochan7/DS4Windows/files/6432004/ds4windows_log_20210429.0.txt)
[ds4windows_log_20210430.0.txt](https://github.com/Ryochan7/DS4Windows/files/6432005/ds4windows_log_20210430.0.txt)
[ds4windows_log_20210506.0.txt](https://github.com/Ryochan7/DS4Windows/files/6432006/ds4windows_log_20210506.0.txt)
[ds4windows_log_20210506.1.txt](https://github.com/Ryochan7/DS4Windows/files/6432007/ds4windows_log_20210506.1.txt)
[ds4windows_log_20210506.2.txt](https://github.com/Ryochan7/DS4Windows/files/6432008/ds4windows_log_20210506.2.txt)

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 CUH-ZCT2
 - OS: Windows 10 Home Version 10.0.18363 Build 18363
 - DS4Windows Version 3.0.4

**Additional context**
I used to use the jay2kings version before upgrading to Ryochan7's version.
Edit: I know a similar question has been asked, but no actual solution was given in that thread.

**Comment by Kanuan** [comment]
- Press `Win + R` to open Windows' run tool
- Type `%appdata% and then select `OK`
- In the appearing folder, locate the `DS4Windows` and delete it, move it or rename it

- Back to your normal DS4Windows folder (the one that has `DS4Windows.exe`), make sure that it is in a normal user folder (e.g.: `downloads`, `documents`, `desktop`). If it is in a folder that needs elevated permission (e.g.: root of the Disk, inside `Program Files`) it will not have permission to write files
- Execute `DS4Windows.exe` as normal and test if the selected option now behaves as normal

**Comment by mika-n** [comment]
I have seen few similar bug reports. Turn out to be an issue if DS4Windows app was installed under a roaming user profile folder. Try installing DS4Windows app to, for example, c:\games\DS4Windows\ folder.

And try to avoid c:\program files (and program files(x86)), desktop folder or a folder below "My docs" because those folders may have extra security tweaks in Win10 and if some bit is not set correctly then DS4Windows may have problems writing files below these folders.

**Comment by NSH-2814** [comment]
Thank you all for your help, it works perfectly now!

**Comment by mika-n** [comment]
@NSH-2814 please post here the solution because others may find it useful

**Comment by Ryochan7** [comment]
The early decision of making DS4Windows a "portable" application was honestly a mistake. Not even sure why the decision was ever made as several extra components have to be installed on a system to use DS4Windows at all. It causes far more problems than it is worth just for the convenience of having everything contained in one folder (except when it isn't).
