### ISSUE TITLE
DS4 Updates causes DS4 to close and not able to reopen from file.

### ISSUE THREAD

**Issue by DDXXChase** [Ryochan7/DS4Windows#2111]
So DS4 updater tells me there is a new update, everytime i update the app it closes out and nothing happens. When i go to click on my DS4 shortcut, it tells me that the program is deleted and that the shortcut is bad and needs to be deleted. Then when i try to launch DS4 from the file location it doesnt work, neither with my permission nor the admins permission.

This has been going on for the last several updates to the point where i dont update because this is always a constent issue.

**Comment by Kanuan** [comment]
Where is your DS4Windows folder located in your computer?

If it is in a folder that requires elevated permission (root of disk, program files) it won't be able to write files.

It's better if it is in a user folder, like desktop, downloads, documents etc

**Comment by DDXXChase** [comment]
I have put it in a desktop folder, what happens is when i update DS4 it deletes the DS4 icon out of the folder and i cant find it to click. and when i run DS4 updater, it just closes when it updates and doesnt open the program.

**Comment by Ryochan7** [comment]
The only problem I found with the Updater lately is that it did not take the newer app config files into account. That would only affect people actively using the **Custom Exe Name** option though. In that case, the Updater would fail to copy the old now not present DS4Windows.exe.config file and likely crash.

The latest DS4Updater version fixes that problem by checking for the newer .NET 5 app config files before copying them.
