### ISSUE TITLE
Feature request: Hotkey to start/stop DS4 Windows

### ISSUE THREAD

**Issue by aloofbit** [Ryochan7/DS4Windows#2112]
Hi ty for this project it is really awesome.

Sometimes when I connect my controller I need to click stop/start button in DS4Windows for it to recognize my controller.

Sometimes I'm already in game and have to minimize or close the game to do this. It would be helpful if there was a button I could press on my keyboard (possibly configurable) that could toggle the stop/start

**Comment by Mister-Curious** [comment]
WOUld be a handy feature for sure. You could always write an AutoHotkey script that would act as a toggle to close and open the program itself. If the service started when the program opened this could be a potential workaround.

**Comment by mika-n** [comment]
There is a command line interface and DS4WindowsCmd.exe tool you can use to command DS4Windows to do various things. One this the cmdline interface can do is to stop-start the DS4Windows service or even close the whole app.
https://github.com/Ryochan7/DS4Windows/wiki/Command-line-options

You can bind a BAT/CMD script to SpecialAction-RunProgram trigger and the BAT/CMD script could do stop-start cycle.

**Comment by Ryochan7** [comment]
It might be nice to have some type of command output binding type. It would likely be possible to fit it into the current mapping system. Other than the Start/Stop command mentioned here, not sure about what other types of commands would be allowed.

This probably won't be added anytime soon (if ever) though. Mostly a lack of motivation.

**Comment by mika-n** [comment]
closed as not priority-1 thing and can be implemented via external tools (for example AutoHotKey and DS4WindowsCmd.exe command line interface to send control commands to DS4Windows via shortcut keys bind in AHK script)
