### ISSUE TITLE
everything works fine, I made profile KB+mouse for trying to play my favourite game with Dualsense. But when I started the game luncher and try to move mouse on launcher mouse doesent respons ..nothing works. And when i move mouse out from that to desktop or simlpy windows everyting works fine,, simpy works onli in windows not in the game. Need help with that.. THX

### ISSUE THREAD

**Issue by Aliusblack** [Ryochan7/DS4Windows#2113]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots and Logs**
If applicable, add screenshots to help explain your problem. Also, please add the most
log file (ds4windows_log.txt) from the Logs folder in your DS4Windows config folder.

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: [e.g. Windows 10 Pro Build 2004]
 - DS4Windows Version [e.g. 3.0.3]

**Additional context**

**Comment by mika-n** [comment]
subject like is supposed to be short but descriptive, not the whole story.

But, do you mean that the KB+M profile works with every other app but not with the specific game? What game is it? 
Have you tried to run DS4Windows with "Run as Administrator" privileges if it makes any difference?

Anyway, the way kb+m messaging works in the current DS4Windows version then there are some games which simply don't work with it (after all those simulated kb+m events are not exactly the same thing as physical kb+m events handled by the kb+m device driver system).

**Comment by Aliusblack** [comment]
I knwo my mistake,, im here for fist time, by the way, I was trying to play WOWs with game pad,, maybe it just dont work..

**Comment by Ryusennin** [comment]
Please move your "title" in your bug description and use a shorter title. Thanks.

**Comment by Aliusblack** [comment]
I cant write to the description
