### ISSUE TITLE
The controller stops responding randomly on wireless connection

### ISSUE THREAD

**Issue by DannyAyman** [Ryochan7/DS4Windows#2114]
The controller works all right while on Wired connection but when on BT connection it disconnects randomly, the controller light bar is still on but gives no readings nor response (0% battery, 0 ms, no sticks readings). The only way I can fix it is to close Bluetooth and reconnect the controller again.

Note: I have the newest version installed

**Comment by Kanuan** [comment]
Are you using an integrated bluetooth card or a bluetooth dongle?

**Comment by DannyAyman** [comment]
I USE a generic v5.0 BT Dongle

**Comment by Masamune3210** [comment]
Im going to lean on the bluetooth adapter not being up to snuff. Talking back and forth to the controller is a lot more data than usually happens, so it can cause issues with Bluetooth adapters that arent made well or are lacking in some way

**Comment by Kanuan** [comment]
Check if your adapter doesn't require a specific driver for it (check the store page where you bought it).

Another user that I helped recently had a issue where its 5.0 BT dongle appeared perfectly normal under Device Manager, Windows recognized it as a generic BT dongle as most appear, but they had lots of different issues that were solved after installing this dongle's correct driver from the manufacturer page

**Comment by DannyAyman** [comment]
> Im going to lean on the bluetooth adapter not being up to snuff. Talking back and forth to the controller is a lot more data than usually happens, so it can cause issues with Bluetooth adapters that arent made well or are lacking in some way

I had a FAKE DS4 before and the dongle worked all right but currently, with the original ds4 it doesn't work+It is weird that it disconnects without any specific time sometimes 3 hours, 15 minutes, 5 minutes

**Comment by DannyAyman** [comment]
> Check if your adapter doesn't require a specific driver for it (check the store page where you bought it).
> 
> Another user that I helped recently had a issue where its 5.0 BT dongle appeared perfectly normal under Device Manager, Windows recognized it as a generic BT dongle as most appear, but they had lots of different issues that were solved after installing this dongle's correct driver from the manufacturer page

Windows doesn't recognize it as a BT dongle instead, it recognizes it as [that](https://prnt.sc/12pkln8)
In [control panel](https://prnt.sc/12pkoay)

**Comment by Kanuan** [comment]
same thing. Generic Bluetooth Radio, generic Bluetooth adapter etc

Check the BT's dongle store page and manufacter's website to see if it requires an specific driver

**Comment by DannyAyman** [comment]
> same thing. Generic Bluetooth Radio, generic Bluetooth adapter etc
> 
> Check the BT's dongle store page and manufacter's website to see if it requires an specific driver

no it doesnt require any drivers, plug & play

**Comment by mika-n** [comment]
If these tips don't help then you may be out-of-luck. 
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#gamepad-connection-over-bluetooth-bt

Sometimes BT is a big mystery why it doesn't work (driver, dongle, gamepad compability combination). DS4Windows logfile in %APPDATA%\DS4Windows\Logs\ may show something, but most often in these scenarios is just shows "read or write failure" error and it doesn't help to diagnose why BT fails to read or write data with the physical gamepad.

**Comment by DannyAyman** [comment]
he

> If these tips don't help then you may be out-of-luck.
> https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#gamepad-connection-over-bluetooth-bt
> 
> Sometimes BT is a big mystery why it doesn't work (driver, dongle, gamepad compability combination). DS4Windows logfile in %APPDATA%\DS4Windows\Logs\ may show something, but most often in these scenarios is just shows "read or write failure" error and it doesn't help to diagnose why BT fails to read or write data with the physical gamepad.

here are the [logs](https://app.mediafire.com/yyl4fyl44fbxw) it helps

**Comment by mika-n** [comment]
Logfiles have nothing obvious why BT communication fails sometimes or it is veeeeeery slow. The log file is just stating this fact. This is often clear indication of incompatibility issues between DS4 and BT dongle. What you could try is to untick "Enable output data to DS4" option in a profile options. Some PCs/BTs have problems both reading and writing data over BT in a high frequency. Unticking this option means that DS4Windows app will send a lot less data to DS4, the app mostly just reads data from DS4. But you will loose lightbar and rumble support when the option is unticked.

```
2021-05-09 10:59:17.0656|INFO|Gamepad data write connection is lost. Disconnecting the gamepad. LastErrorCode=997
2021-05-09 11:09:20.0492|WARN|Controller 1's latency over 10ms (11609.9 ms)
```

Just go through those BT tips linked in the previous post. Surprisingly often people have found help from using USB extension cable at the end of BT dongle (if you have bt dongle and not internal bt chipset). The usb extension cable takes the BT dongle further away from the radio storm caused by PC chassis and closer to desktop level and the gamepad.
