### ISSUE TITLE
Ds4 v.2 Bluetooth not working - update 3.0.4

### ISSUE THREAD

**Issue by Pylon69** [Ryochan7/DS4Windows#2115]
My v.2 ds4 controller doesn't work with Bluetooth since 3.0.4 update. My v.1 controller works perfectly fine.
If I use a usb cable it also connects perfectly fine.
I rolled back to 3.0.3 and its working just peachy

 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2E)
 - OS: latest Win 10 pro 
 - DS4Windows Version 3.0.4

Don't mean to be rude but is it possible for you to have a built in roll-back function in ds4windows? Just makes life alil easier this is honestly my 3rd issue. I understand things have been bumpy due to net 5.0 and vigembus library changes. But just a consideration

Thank you so much for everyone's work on this project.

**Comment by Kanuan** [comment]
You see that only one controller appears on the controller list? That's your DS4v1. Your DS4v2 seems to be hidden by HidGuardian.

If you are on 64bits Windows 10, I recommend you to unninstall HidGuardian and install it's successor, HidHide. It is easier to set up and you will end up less confused.

 HidHide guide's already cover how to uninstall HidGuardian before installing it. After HidGuardian is unninstalled and hidHide is installed and configured you won't have more troubles.

https://vigem.org/projects/HidHide/Simple-Setup-Guide/

**Comment by Kanuan** [comment]
Be sure to give a good read on the guide and to UNDERSTAND what HidHide does. If you don't understand what it is supposed to do you won't know where to look when trying to identify if things are working correctly or not

**Comment by Ryochan7** [comment]
I can confirm that HidGuardian support still works in DS4Windows 3.0.4. I still have it set up on my Windows 7 VM as HidHide is not available to install on Windows 7. The only likely scenario when HidGuardian support would break between DS4Windows 3.0.3 and 3.0.4 would be if you somehow have **both** HidGuardian and HidHide installed on your system at the same time; maybe only the device present in Device Manager was removed but the driver is still preset.

If both are installed at the same time, the current logic in DS4Windows will only attempt to use HidHide. OR logic is used. The app checks for HidHide and will then check for HidGuardian if HidHide is not found. If HidHide is found, the HidGuardian setup routines will be skipped.
