### ISSUE TITLE
Dpad diagonal keybinds

### ISSUE THREAD

**Issue by prov007** [Ryochan7/DS4Windows#2117]
I am trying to keybind my PS4 controller Dpad diagonal directional presses. Up, Down, Left, Right are fine, is there a way to keybind the diagonal directions ? i have tried to make a macro and recorded Up and Right pressed to see if that would work but i can't apply the macro to my profile as it never saves.
I'm not sure if what i am asking is possible or i am missing something really straightforward to achieve what i am needing.

Thank you for all your hard work into making this great application, for everything else i need it for it works flawlessly

**Comment by mika-n** [comment]
the macro editor and recorder is a bit weird, but it there are actually two "Save" buttons you need to press in order to save changes.

**Comment by Ryochan7** [comment]
There is no support for an 8-way DPad with separate diagonal bindings. I probably wouldn't try to play a rouge-like game with a DS4. Also, there would likely have to be a small delay added for direction changes so a cardinal direction binding is not activated by accident.

**Comment by prov007** [comment]
Thank you for responding so quickly, i was trying to get it to work playing Oblivion but will use my Xbox 360 controller and Antimicro just for that game.
I appreciate all the hard work that goes into making a program like DS4, thank you and I will continue to support your amazing work
