### ISSUE TITLE
Custom settings reverting to default 

### ISSUE THREAD

**Issue by LudicrouslyLiam** [Ryochan7/DS4Windows#2118]
Anti-dead zone (on LS and RS) resets to 0.20, normal deadzone resets to 0.08
Max zone on L2/R2 resets to 1.00
BT poll rate resets to 4ms

As far as I can tell just saving the profile and after using it for a few days it seems to reset the above settings. My custom binds and every other setting seems to be unaffected,

I'm using the most up-to-date version of Windows and DS4Windows.

**Comment by mika-n** [comment]
hmmm.... sounds weird. There has been reports about profiles being reset but those cases turn out to be permission issues (ds4windows app didn't have enough permissions to write or read profile files form certain folders) or the app was installed in a roaming profile folder and WinOS/domain reset the roaming profile back to some previous state.

Where have you installed the DS4Windows app?
Where are the profile and config files in your setup?

**Comment by LudicrouslyLiam** [comment]
Yeah this was a recurring problem for me the last time I used this version of DS4W which was a year ago (I ended up switching back to the older fork). It's strange because like I say, my custom binds on my controller remain unchanged within the profile (along with other settings like idle disconnect time), it's just the aforementioned settings that seem to revert to default.

The app and all the files are installed in my documents folder (C:\Users\myuser\Documents\DS4Windows) and my profiles etc are in my roaming folder (C:\Users\myuser\AppData\Roaming\DS4Windows). 

The only thing I can think might be causing a problem is having the older fork of DS4W still installed, but I haven't opened it since trying the new version again. Last time I tried this version it was still doing this even with the older fork uninstalled though so I'm stumped. 

Let me know if providing a log would help wasn't sure if it was applicable.

**Comment by Ryochan7** [comment]
Not sure why DS4Windows was ever set up to use the Roaming AppData folder rather than LocalAppData. This has likely been a problem in the past but people did not investigate the problem. Shouldn't need to share a config over network user profiles.

 I guess DS4Windows better be changed to prioritize the use of LocalAppData over AppData. Too bad AppData will have to still be searched otherwise that would force many users to have to start from scratch.
