### ISSUE TITLE
BUG 

### ISSUE THREAD

**Issue by serelmo98** [Ryochan7/DS4Windows#2119]
some buttons are inverted in certain games, how to solve?

**Comment by Masamune3210** [comment]
Go back and this time fill out the issue template please

**Comment by Kanuan** [comment]
Delete this issue and make a new, proper one this time, with proper information.

If you don't know exactly _how_ to describe your issue or what kind of information to include, then we can also conclude that everything is working fine and you just don't know how to use/setup
