### ISSUE TITLE
Ps4 controller dpad

### ISSUE THREAD

**Issue by tamokhn** [Ryochan7/DS4Windows#2120]
Hi my ps4 controller dpad stops working the following day if setup a new controller and save profile it works but if restart the pc it stops working can you help please

**Comment by mika-n** [comment]
please see the pinned "Read this before posting a new issue ticket" posts

**Comment by tamokhn** [comment]
What's the pinned ?

**Comment by mika-n** [comment]
"pinned post" is shown on top of the Issues list when you browse through existing issue tickets and try to create a new ticket. The pinned Troubleshooting post answers lots of questions asked over and over again and if nothing else helps then it provides instructions what you need to include in a new issue ticket as a background information. There is not much anyone can do if you don't provide all necessary details of your setup and app versions and logfiles and the profile file itself
