### ISSUE TITLE
DS3 controller

### ISSUE THREAD

**Issue by samael85000** [Ryochan7/DS4Windows#2121]
Hi,
I am using version 3.0.4 and i see in the log that there is support for the ps3 controller.
Is it possible to connect it to bluetooth?
For the moment i can not get it to work either with usb or bluetooth, what should I do?
Ps4 controllers work fine.
thanks.

**Comment by Kanuan** [comment]
DS3 requires:
- DsHidMini driver
- BthPS3 for it to connect over Bluetooth
- the controller being in DsHidMini's "DS4Windows Mode"

Follow the guides:
https://vigem.org/projects/DsHidMini/
https://vigem.org/projects/DsHidMini/DS4-Mode-User-Guide/

**Comment by Ryochan7** [comment]
Kanuan's post explains it well. I still have not tried the DsHidMini driver on my system. Need to do that sometime. Have only used my DS3 once for the FireShock experiments. The controller has been collecting dust in my closet ever since.

**Comment by samael85000** [comment]
Thank you for your quick reply.
I thought everything would work with this new version without installing other programs like with scptoolkit.
I will stay with my ps4 controller for now then.
thank you again for your explanation.

**Comment by Kanuan** [comment]
DsHidMini is ScpToolKit's successor.
It is a lightweight driver and actually has good code now. Same creator (regarding nefarius' scptoolkit at least).

It is a trustworthy driver, give it a test when you can

**Comment by samael85000** [comment]
Hi,
I try to test the ps3 controller and it s works.It s works in bluetooth too.
But the problem its i don t see the controller in the ds4windows program. 
it s normal?

**Comment by Kanuan** [comment]
is the controller in DS4Windows Mode? Everything is covered in the second link (DS4 Mode guide) as long as you follow it step by step

![DS4ModeDS4W](https://user-images.githubusercontent.com/24910442/117550801-9f1b4400-b018-11eb-8a1e-1b1eba85b84e.png)

**Comment by samael85000** [comment]
I didn't know about the double input problem, I didn't encounter it with my ps4 controllers.
I followed the instructions and it worked for the ps3 controller.
Thank you for your patience.

I have one last not very serious problem with the ps4 touchpad shortcuts, they don't work in most games even with the scan code option.
Is it normal or is there something to do that i did not understand?
For example i put a shortcut on the right pad of the touchpad to go to the next track of music.
It works on the desktop but not in-game.
this is not taken into account for halo mcc and skyrim se games for example.

Thanks for your work with ds4windows.

**Comment by Kanuan** [comment]
> I have one last not very serious problem with the ps4 touchpad shortcuts, they don't work in most games even with the scan code option.

Since this is not related to the current issue at hand, it's better if you close this one since it is already solved and create another specific to the shortcuts problem, though I never used them so I can't offer help on this

**Comment by mika-n** [comment]
the original topic "DS3 connectivity" seem to be resolved. closed.
