### ISSUE TITLE
[TODO] Port scpvbus_draft code to current .NET 5 base

### ISSUE THREAD

**Issue by Ryochan7** [Ryochan7/DS4Windows#2124]
Making this to place on the Work Board. Ended up deciding that having some access to ScpVBus might still be useful. I have already merged the code and resolved the conflicts. The next release of DS4Windows will have a test ScpVBus build.

**Comment by Kanuan** [comment]
Sorry for the noob question, but is this to keep Win7/8 support?

**Comment by Ryochan7** [comment]
Not really. That branch was originally made for regression testing. Updating to the 3.x code base was just for fun. It can be useful to compare ScpVBus and ViGEmBus performance.

There is a binary release this time around. If someone uses it, make sure to disable automatic updates.

https://github.com/Ryochan7/DS4Windows/releases/download/v3.0.5/DS4Windows_ScpVBus_3.0.5_x64.7z
