### ISSUE TITLE
Anyway to get DS4Windows to recognize a DS4 while using Mayflash adapter?

### ISSUE THREAD

**Issue by Jayinem** [Ryochan7/DS4Windows#2125]
It doesn't recognize it at all says no controllers connected.  It's a legit DS4 but it's using xinput through mayflash magic ns adapter. 

I used to use those apps to install DS3 and DS4 but I find them mostly nothing but trouble. Mayflash is so easy just plug it in set it to the right type (xinput) and plus in the DS4 with a usb and then it works wirelessly, no issues.

**Comment by Ryusennin** [comment]
The Mayflash Magic is a hardware XInput emulator. DS4Windows is a software XInput emulator. It doesn't make any sense to use both simultaneously. If you need macro/remapping functions for your Mayflash adapter, have a look at JoyToKey.

**Comment by Jayinem** [comment]
Joytokey doesn't allow me to use touchpad which is my goal.

**Comment by Jayinem** [comment]
My problem is a bit unique I guess.  I have a bluetooth but I need the Dualshock 4 to be player 1 at all times. I also have a Xbox 360 wireless adapter hooked up because I have an arcade stick and the mayflash hooks up both the dualshock 4 wireless and a steering wheel wired and the mayflash adapter is automatically player 1 at all times. Before I used it, I would go to play a game with my steering wheel or DS4 and the controls wouldn't work and it turned out it was because it wasn't player 1. Mayflash solved all those problems. 

But I don't expect anyone to make any changes due to my unique issue. I figured out how to sort of mimick the touchpad in certain streaming apps. I am streaming the PS4 to PC and Switch, and the app Chiaki has touchpad set to T. If I hit T on the keyboard it worked. I was able to use joytokey to map T to right analog stick down. So it mimicks the touchpad.

**Comment by Kanuan** [comment]
@Jayinem 

To achieve what you want, you can:

- Disable the Xbox 360 wireless adapter temporarily on device manager
- After it's disabled, open DS4Windows -> `Setting` tab -> Select `XinputChecker`
- Verify on `XInputChecker` if Slot 1 is free (nothing connected to it)
- Connect your DS4 controller over bluetooth as normal so DS4Windows can pick it
- When DS4Windows creates the virtual Xbox 360 controller it should connect to Xinput Slot 1 (Verify XinputChecker` again)

From here, when enabling again the X360 wireless adapter it won't "take over" slot 1.

If when following these steps the virtual X360 controller plugs in Slot 2, even when there is no controller connected to Slot 1, that means some process is keeping an active connection to the Slot 1. Even if it does happen it is fixable.

if you can, try the steps above to test if it will work. if it does not, be very detailed on exactly what you did and where it did not work so we can work from there

**Comment by Jayinem** [comment]
But see that would leave the steering wheel not working in some racing games if it's not player 1. I'm pretty sure only Mayflash can let me hook up both a controller and a steering wheel to it and have them both be player 1.
