### ISSUE TITLE
Feature Request/Suggestion: Combine Pulse and Full Click Trigger Effects into Customizable Click on DualSense

### ISSUE THREAD

**Issue by emilois** [Ryochan7/DS4Windows#2127]
The triggers reach 255 input at around 75% pull, and the click on Full Click takes effect also at around the same level.
Due to this, the triggers reach 255 input and the 2nd stage of two stage mode even though the triggers haven't clicked yet.
We can't utilize full click together with two stage mode in this case.

Since the issue where DualSense registers 255 at around 75% pull is a hardware issue that can't be fixed, how about having a feature where we can adjust at what pull level the click takes effect in place of Pulse and Full Click?
Click would be adjustable to take effect anywhere between 5% to 75%, where 5% simulates Pulse and 75% would simulate Full Click.
With this, we can adjust the click to be around 60~70% so we can be sure that the 1st level of two stage mode is before the click and the 2nd stage is after the click.

**Comment by Ryochan7** [comment]
I am still of the opinion that the adaptive triggers are mostly pointless unless game context is involved. That is the main reason why DSX (1.x at least) with game mods initially made sense as that was a hacked way to get game context and adapt the triggers based on game data. Too bad that the two bigger mods do not even work anymore and support was not even incorporated in DSX 3.

Having access to use more trigger effects might be somewhat useful if some form of action switching were possible. The mapper in DS4Windows is not capable of doing. Not really worried about it for my other mapper either.
