### ISSUE TITLE
WINDOWS DETECTS A MOFOING TROJAN WTF

### ISSUE THREAD

**Issue by 1234throww** [Ryochan7/DS4Windows#2131]
when downloading the .zip windows detected a file that's legit a trojan no shit download the x86 .zip

**Comment by Danlezama96** [comment]
I've been downloading every single release and I've not had a problem,not a single time....people complaining about false positives is tiresome, get a better AV

**Comment by mika-n** [comment]
not much DS4Windows app can do about false positives
