### ISSUE TITLE
Auto profile is not switching profiles!

### ISSUE THREAD

**Issue by Shadoware** [Ryochan7/DS4Windows#2133]
**Describe the bug**
Since the DS4Windows updates here from version 3.0.3 to 3.0.4 the profiles are not changing when the games starts. Only if I changed it manually it works correctly.

**To Reproduce**
Just start a game that uses a profile other than default.

**Expected behavior**
Profile change when the game starts.

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS3 with DsHidMini
 - Windows 10 Pro Build 2004]
 - DS4Windows Version 3.0.4

**Comment by Shadoware** [comment]
I get some debug messages from autoprofile:


05/12/2021 01:00:45: DS4Windows version 3.0.5
05/12/2021 01:00:45: DS4Windows Assembly Architecture: x64
05/12/2021 01:00:45: OS Version: Microsoft Windows NT 10.0.19042.0
05/12/2021 01:00:45: OS Product Name: Windows 10 Pro
05/12/2021 01:00:45: OS Release ID: 2009
05/12/2021 01:00:45: System Architecture: x64
05/12/2021 01:00:45: Running as User
05/12/2021 01:00:45: HidHide control device found
05/12/2021 01:00:46: Starting...
05/12/2021 01:00:46: Connection to ViGEmBus 1.17.333.0 established
05/12/2021 01:00:46: Searching for controllers...
05/12/2021 01:00:46: Using Shared Mode
05/12/2021 01:01:58: The gamepad DualShock 3 (DS4 Emulation) (USB) uses custom feature set (NoGyroCalib, VendorDefinedDevice)
05/12/2021 01:01:58: Found Controller: 34:C7:31:9E:2B:07 (USB) (DualShock 3 (DS4 Emulation))
05/12/2021 01:01:58: Plugging in virtual X360 Controller
05/12/2021 01:01:58: Associate X360 Controller for input DS4 #1
05/12/2021 01:01:58: Controller 1 is using Profile "Bike Counter Sterring". Battery level is 100%
05/12/2021 01:02:05: Controller 1 is using Profile "Default". Battery level is 100%
05/12/2021 01:08:55: Controller 1 is using Profile "Bike Counter Sterring". Battery level is 100%
05/12/2021 01:09:50: Controller 1 is using Profile "Default". Battery level is 100%
05/12/2021 01:09:52: DEBUG: Auto-Profile. PID=8452  Path=c:\windows\explorer.exe | WND=65686  Title=
05/12/2021 01:09:53: DEBUG: Auto-Profile. PID=6044  Path=e:\arquivos de programas 2\steam\steam.exe | WND=722190  Title=
05/12/2021 01:09:54: DEBUG: Auto-Profile. PID=6044  Path=e:\arquivos de programas 2\steam\steam.exe | WND=263810  Title=ride: game — steam
05/12/2021 01:09:56: DEBUG: Auto-Profile. PID=6312  Path= | WND=132604  Title=
05/12/2021 01:09:57: DEBUG: Auto-Profile. PID=6312  Path= | WND=591536  Title=ride
05/12/2021 01:10:00: DEBUG: Auto-Profile. PID=6312  Path= | WND=329338  Title=ride
05/12/2021 01:10:11: DEBUG: Auto-Profile. PID=8452  Path=c:\windows\explorer.exe | WND=65686  Title=
05/12/2021 01:10:12: DEBUG: Auto-Profile. PID=8452  Path=c:\windows\explorer.exe | WND=263836  Title=alternância de tarefas (means window alternation)
05/12/2021 01:10:13: DEBUG: Auto-Profile. PID=6312  Path= | WND=329338  Title=ride
05/12/2021 01:10:20: DEBUG: Auto-Profile. PID=8452  Path=c:\windows\explorer.exe | WND=65686  Title=
05/12/2021 01:10:23: DEBUG: Auto-Profile. PID=6312  Path= | WND=329338  Title=ride
05/12/2021 01:11:37: DEBUG: Auto-Profile. PID=8452  Path=c:\windows\explorer.exe | WND=65686  Title=
05/12/2021 01:11:41: DEBUG: Auto-Profile. PID=9112  Path=e:\arquivos de programas 2\programas portateis\ds4windows\ds4windows.exe | WND=262292  Title=ds4windows
05/12/2021 01:14:52: DEBUG: Auto-Profile. PID=9112  Path=e:\arquivos de programas 2\programas portateis\ds4windows\ds4windows.exe | WND=1443284  Title=select export file

**Comment by mika-n** [comment]
AutoProfile rules seem to work here.
https://github.com/Ryochan7/DS4Windows/wiki/Profile-selection-using-auto-profile-rules

Make sure you have set WindowTtitle and/or ProcessName options of the autoprofile rule correctly. 
For example test the feature by choosing c:\windows\system32\notepad.exe as an application, set it for some other profile (and tweak lightbar color for the rule) and save the settings.

Then open Notepad and see if the new rule kicks in.

**Comment by Ryochan7** [comment]
It doesn't  look like you ever mentioned the game in question that the switcher is not working with. Is the game running as a UWP app? That would be one obvious case when the switcher might not work.

**Comment by Shadoware** [comment]
The game is Ride, released in 2015 I think. The first in the series.

**Comment by mika-n** [comment]
`05/12/2021 01:10:23: DEBUG: Auto-Profile. PID=6312 Path= | WND=329338 Title=ride`

The debug log msg shows ride as a window title, but with an empty PATH value. It is a bit weird, but shouldn't be a problem. How you have defined the auto-rule for this game? Show the screenshot of the processPath and windowTitle search keywords.

Anyway, you could leave the processPath as empty and define just windowTitle search keyword with ride keyword and it should work.

But, have you tried to run DS4Windows with "Run as Administrator" option? Maybe there is a permission issue and DS4Windows doesn't have permissions to read the path of the ride process?
