### ISSUE TITLE
DS4Windows.exe file gets deleted when updating the program on Win10 if it's currently located in Program Files (or other restricted folder)

### ISSUE THREAD

**Issue by PurpleTunic** [Ryochan7/DS4Windows#2135]
This has been ongoing for quite a few releases from my experience.

OS: Windows 10, rev 20H2
Install location: C:\Users\<username>\Downloads\DS4Windows_3.0.5_x64\DS4Windows
Steps to reproduce: Download DS4Windows, move to a restricted folder (like above location), run the program as administrator, run the update process. The update process will terminate normally, however the .exe file will be deleted, and no replacement .exe will be generated in the folder.

Problem: When updating the program (run as administrator), the .exe file gets deleted, but no new .exe file is generated.

I have been circumventing this by running the update, and then manually downloading the .exe file, and moving it to the Program Files directory. This seems to be working.

I guess this would most likely require some sort of elevated access or a prompt beyond simply running as administrator, unsure.

**Comment by Ryochan7** [comment]
This just screams we wanted an installer even though we explicitly said don't make one. The updater is broken in some places still but you should NOT be placing DS4Windows under Program Files for a fake install.
