### ISSUE TITLE
Gyro No Longer Toggling ON

### ISSUE THREAD

**Issue by projektsoul** [Ryochan7/DS4Windows#2136]
**Describe the bug**
GYRO MOUSE JOYSTICK STOPPED SUDDENLY STOPPED WORKING ON COD WARZONE BUT STILL WORKS ON COLD WAR

**Expected behavior**
When pressing L2 to ADS, I expect Gyro to be toggled ON.

**Screenshots and Logs**
N/A

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: Windows 10 Pro 
 - DS4Windows Version 3.0.4

**Additional context**
Gyro seems to activate when playing COD Cold Ware but not when playing COD Warzone.

**Comment by Ryochan7** [comment]
MAYBE I'LL CATCH THEIR ATTENTION WITH LARGE CAPITAL LETTERS

Also, works for me
