### ISSUE TITLE
Support adaptive

### ISSUE THREAD

**Issue by MidzakiKayo** [Ryochan7/DS4Windows#2137]
Hi friends! Maybe someone has already asked before, but still. I found software written by one person that allows adaptive triggers to work. Will this be added to the support program?

[https://github.com/Mxater/DualSenseSupport/releases](url)

**Comment by Masamune3210** [comment]
The problem isn't lack of support, as you can actually mess with the triggers in the latest versions, it's the fact that no PC games have built in support for haptic /adaptive triggers

Even Microsoft's own Xbox controller barely gets support for the feature on PC, for exactly the same reason

**Comment by Ryochan7** [comment]
People have asked for more configuration options for the adaptive triggers. I have not thought about it much. The mapper should try to be as device agnostic as possible and I have not thought about how device specific options could be added to profiles. The one use case of faking a full click is about as much support as you can get right now.

No PC games have any form of support for the adaptive triggers.

**Comment by Esirei** [comment]
> People have asked for more configuration options for the adaptive triggers. I have not thought about it much. The mapper should try to be as device agnostic as possible and I have not thought about how device specific options could be added to profiles. The one use case of faking a full click is about as much support as you can get right now.
> 
> No PC games have any form of support for the adaptive triggers.

Metro Exodus Enhanced Edition does now. 😍
Unfortunately requires the dualsense to be plugged in via usb and without using ds4windows.

**Comment by Ryochan7** [comment]
I just heard about Metro Exodus adding native DualSense support with working adaptive triggers. Not sure it would be worth buying just to check that out though. Unfortunately, you can't use DS4Windows for remapping since the game needs to work with the native input device.
