### ISSUE TITLE
REQUEST - Special Actions sorting

### ISSUE THREAD

**Issue by Mister-Curious** [Ryochan7/DS4Windows#2138]
Presently all user Special Actions are listed in order of the creation date. It would be useful to be able to sort the view of the Special Actions based on the name. I use dozens and dozens of special actions and often find it hard to find a specific one with the present setup. Having the option to sort by date, or name would be helpful. 

Thank you.

**Comment by Ryochan7** [comment]
I didn't know how to allow sorting in views until fairly recently. It should be fairly easy to sort the list by action name.

**Comment by mika-n** [comment]
As a "quick-and-dirty" solution (until the app GUI has anything like this) you can re-order those specActions by editing %APPDATA%\DS4Windows\Actions.xml file in Notepad. Just re-order ACTION entries there.

**Comment by Mister-Curious** [comment]
thank you both! I look forward to this enhancement.

**Comment by Ryochan7** [comment]
Finally got a chance to implement this.
