### ISSUE TITLE
Something clicking in the conrroller

### ISSUE THREAD

**Issue by etojorik** [Ryochan7/DS4Windows#2139]
Have Dualshock 4 v.2, when using DS4 every 5 seconds something clicking in the controller. What is this?

**Comment by Ryusennin** [comment]
Push the button.

![](https://static.wikia.nocookie.net/lostpedia/images/0/09/CounterZeroHieroglyphic.jpg)

**Comment by Ryochan7** [comment]
> Have Dualshock 4 v.2

Cheap Chinese knock-offs don't count.

Fix the problem and submit a pull request. Otherwise, my advice is to actually get a first party Sony DS4 controller.
