### ISSUE TITLE
What did your program do to my pc:(

### ISSUE THREAD

**Issue by brothan323** [Ryochan7/DS4Windows#214]
#I don't know what the heck is going on. Your program seems to have installed two gamepad drivers onto my pc, a generic gamepad and an xbox controller. Some games are unplayable because they are reading two controllers at once. Dragon's Dogma is a perfect example of this, the main menu is stuck scrolling up, and if I do get in game somehow, the game tells me I am using BOTH an xbox controller and a gamepad controller, rendering DD unplayable. This is happening for multiple games, uninstalling EVERY SINGLE driver installed during the DS4windows installation, then reinstalling DS4Windows doesn't fix this issue. I can literally uninstall the spcdriver, and this problem will still persist.

And the odd thing about this is your program was working fine earlier today via bluetooth, I turned off the controller(PS button + options.) A few hours pass and I press the ps button to turn the controller on and BAM, this problem that won't go away no matter what I do. Even plugging the DS4 controller directly into my pc won't solve this issue.

One thing to note is that when I plug the DS4 controller into my pc(to reinstall the drivers on a fresh install) my pc will install multiple usb devices(even though it's ONE controller.) This didn't happen on my first installation of this program.

**Comment by Ryochan7** [comment]
Exclusive mode is always finicky and even simple changes across many applications (including DS4Windows) can affect the success rate of getting exclusive access. The most reliable way to get exclusive mode working currently is to install HidGuardian and use that driver. DS4Windows can use HidGuardian but you have to run DS4Windows as admin.

**Comment by brothan323** [comment]
I found out the problem, had to activate the 360 on steam big picture mode. The DS4 still doesn't work when connected to my bluetooth dongle, and Windows 7 still doesn't ask for a pairing code(which is very confusing.)
