### ISSUE TITLE
*** FIX included *** Having Nvidia GeForce running causes "Warning: Could not open DS4 exclusively. You must quit other applications like UWP..."

### ISSUE THREAD

**Issue by andyktaylor** [Ryochan7/DS4Windows#2140]
**Describe the bug**

With Nvidia GeForce running, DS4 windows always states "Warning: Could not open DS4 1C:96:5A:2E:01:9B exclusively. You must quit other applications like UWP apps (Netflix), Steam, Uplay, Edge, NVIDIA IN-GAME before activating the 'Hide DS4 Controller' option. For more info check https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

**To Reproduce**
1. Launch DS4Windows
2. Plug in DS4 controller
3. Log shows the warning

**Expected behavior**
DS4 should be in exclusive mode.

**Solution**

Here's how to resolve it.

You can either manually open Task Manager, click on Services, find NvContainerLocalSystem and stop it, launch DS4Windows then restart the service, or you can make a batch file that does it for you.

 Copy the below text and paste it into notepad, save as "DS4fix.bat" or whatever you want to call it and then you can run it to automate the above. Change the path to where your DS4Windows.exe is located

@echo off
net stop NvContainerLocalSystem
Timeout 5
C:\Windows\System32\cmd.exe /C start C:\DS4Windows_3.0.5_x64\DS4Windows\DS4Windows.exe
Timeout 5
net start NvContainerLocalSystem

If you don't want to do this each time, what you could do is go into Task Scheduler and create a task to run on startup that runs the batch, or use Autohotkey or some other method to launch it when you open your games.

I hope that has helped others who have encountered this problem.

**Comment by andyktaylor** [comment]
Actually, seems someone else had the same idea and has made a rather awesome script that puts mine to shame!

https://github.com/ZleMyzteX/DS4Help

**Comment by Kanuan** [comment]
Even if the "Hide DS4 controllers" work now with GeForce experience closed, it can fail in any number of different scenarios.

The `Hide DS4 controllers` should be view as a legacy option and a last case scenarion.

If you are on 64 bits Windows 10, it's recommended not using it anymore and using HidHide instead to fully solve the double input issue by hiding the original controller.

https://vigem.org/projects/HidHide/Simple-Setup-Guide/

**Comment by Ryochan7** [comment]
The endorsed fix is to install and configure HidHide.
