### ISSUE TITLE
[DualSense] Mass effect legendary edition not detecting controller

### ISSUE THREAD

**Issue by Rajackar** [Ryochan7/DS4Windows#2143]
Using a DualSense controller I can't get it to work in Mass Effect legendary edition. It works sometimes in the launcher where you select the game but in-game it always fails.
I've tried both USB and Bluetooth and also with and without the "hide controller" option.
Of course it could be an issue somewhere else but after spending hours on this I'm out of ideas.

**Comment by Kanuan** [comment]
- Connect your controller
- press `Win + R` then type `joy.cpl` and press OK
- Send here a screenshot of the appearing window (USB controllers something)
- On DS4Windows,  go the log tab, save/export the log and then send upload it here too

**Comment by Ryochan7** [comment]
I'm going to just blame the game this time. Wonderful current Bioware quality control.

Mass Effect only had 2 games. Anything after ME 2 does not exist.

**Comment by Rajackar** [comment]
> I'm going to just blame the game this time. Wonderful current Bioware quality control.
> 
> Mass Effect only had 2 games. Anything after ME 2 does not exist.

I'm with you on this one. 
I've been messing around with it some more and it seems like one of the three(!) launchers is hogging the controller and it won't work in the actual game.
I managed to get it to work using Steam big picture mode and controllers setting forced from steam. I've also been messing around with controller priority using modded direct input DLL's so it's hard to say which one fixed it. But it's definitely not DS4windsows related.
Sorry for taking up your time ;-)

**Comment by Kanuan** [comment]
> Connect your controller
press Win + R then type joy.cpl and press OK
Send here a screenshot of the appearing window (USB controllers something)
On DS4Windows, go the log tab, save/export the log and then send upload it here too

**Comment by Ryochan7** [comment]
Based on some reviews, the game exhibits negative mouse acceleration which screws up mouse control. The PC port is pretty much broken completely. Classic Mass Effect is the way to go.
