### ISSUE TITLE
REQUEST - Android Support

### ISSUE THREAD

**Issue by Hierro3000** [Ryochan7/DS4Windows#2145]
Sorry if I'm doing wrong format.
I'd like to know if there's any way of remapping Dualsense buttons on android, currently it's essentially unplayable.

**Comment by Kanuan** [comment]
This is completely out of the scope of this project. DS4Windows is a Windows software, not android.

**Comment by mika-n** [comment]
closed as non relevant in the context of DS4Windows app. This app is purely for Windows platform, there is (was?) spinoff for Linux, but not for Android as far I know.

**Comment by Ryochan7** [comment]
Got enough work to do on the Windows front. Some form of Linux support would be much more likely and that is probably never going to happen at this point; kind of a shame but I have even been neglecting my Python 3 SC Controller fork. I don't game on Android.
