### ISSUE TITLE
Question and or feature request regarding toggling macros on/off with a button press.

### ISSUE THREAD

**Issue by C4rgo** [Ryochan7/DS4Windows#2147]
**Describe the bug**

Not really a bug, more of a question or potential feature request. 

Is it possible to loop or toggle a macro on and off some how?

Example:   I need to cast a spell every ~5 seconds and I'd rather not remember to cast it every 5 seconds. I just want to press triangle at the beginning of the match, and then it will press itself every 5 seconds until I press triangle again to turn it off when the match is over. 

I thought I could get it to work using the toggle box check box  and then recording the macro and selecting repeat while pressed but the toggle selection doesn't stay after selecting record macro. 

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: Windows 10 Home Build 19042.985
 - DS4Windows Version 3.05

**Comment by Mister-Curious** [comment]
This is what AutoHotKey scripts are best at doing. AHK works well with DS4Windows. The possibilities are endless.

**Comment by mika-n** [comment]
closed as not priority-1 thing within DS4Windows app and the existing macro engine is very limited without major re-writing, especially when "almost something like this" can be done with "repeat while held" macros (does require user to keep pressing the trigger key)
