### ISSUE TITLE
[Request] Add relevant info regarding output slots to the Log

### ISSUE THREAD

**Issue by Kanuan** [Ryochan7/DS4Windows#2148]
[Issue based on DS4Windows 3.0.5]

There is no info related to output slots on the log, which makes harder to troubleshoot user issues based on the log file alone.

Missing info:
- If a slot is set to permanent, stopping/starting DS4Windows creates no data line regarding it, even though it does plug in the virtual controller
- Though DS4Windows Log does create a data line when a virtual controller is manually plugged/unplugged on the `output slots` tab, it doesn't state if it is associated to a permanent or dynamic slot
- When a controller is picked by DS4Windows, it does not states if it is connecting it to a virtual controller in a dynamic slot or to a permanent one that is already plugged in.

**Comment by mika-n** [comment]
jep, log functionality would benefit from few tweaks. For example having debug/verbose option as part of the main build would be useful for diagnosing purposes.  This slot thing is something which for sure would be nice to know when trying to analyze the story behind a logfile.

**Comment by mika-n** [comment]
https://github.com/Ryochan7/DS4Windows/commit/3d1f8c1eb4deceaebefd8c552ddf729feca199d9
