### ISSUE TITLE
Get stuck in some games

### ISSUE THREAD

**Issue by djanthony93** [Ryochan7/DS4Windows#215]
When I play Rocket League for example sometimes my DS4 will get stuck on one command and I need to turn off/on to recover it

**Comment by Ryochan7** [comment]
Can you share the profile that you are using and your Actions.xml file? I haven't tested Rocket League extensively in a while but playing Rocket League has worked fine in the past. The last time I played the game was when I was testing force feedback support with ViGEm a few weeks ago.

**Comment by JarnoVgr** [comment]
RL works fine on my end with a mostly default profile. Rocket League has limited DS4 support, maybe it's an exclusivity issue?

**Comment by BibleBeliever** [comment]
What I'm saying is that after each disconnect I have to go through the process of remembering my device again in the Bluetooth menu. You can imagine that it's quite tedious and bothersome.

**Comment by Ryochan7** [comment]
Finally got a few rounds of Rocket League in. Everything worked fine for me.
