### ISSUE TITLE
my doubleshock 4 is recognized as gioteck vx4 in ds4 windows from ryochan

### ISSUE THREAD

**Issue by DarkAngel9041** [Ryochan7/DS4Windows#2152]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots and Logs**
If applicable, add screenshots to help explain your problem. Also, please add the most
log file (ds4windows_log.txt) from the Logs folder in your DS4Windows config folder.

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: [e.g. Windows 10 Pro Build 2004]
 - DS4Windows Version [e.g. 3.0.3]

**Additional context**

**Comment by DarkAngel9041** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/84359315/118573947-2b053c80-b78c-11eb-845c-64516783daee.png)

**Comment by Kanuan** [comment]
When connected to windows, a device (the controller) provides it's VID/PID as a form of identification. DS4Windows takes this provided identification and see if it is in the supported device list.

Though only Ryochan7 or mika-n can fully confirm this, my guess is that both your doubleshock and the gyoteck VX4 uses the same VID/PID, which is not that uncommon considering fake/copycat controllers.

If this is the case, there is not much that can be done.

Does your controller works as normal? Is there some feature that is not working as it should? If everything is working as it should, then your only problem is a not accurate device name

**Comment by DarkAngel9041** [comment]
HID\VID_7545&PID_1122&REV_0100
of my controller and vibration in game not working

**Comment by Kanuan** [comment]
Go to the `log` tab, export the log and upload the log file here

**Comment by DarkAngel9041** [comment]
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/6497652/ds4windows_log.txt)

**Comment by DarkAngel9041** [comment]
i will send you some pictures with my controller

**Comment by DarkAngel9041** [comment]
![IMG_20210518_040947_947](https://user-images.githubusercontent.com/84359315/118576922-20e63c80-b792-11eb-861c-fec1ed929a26.jpg)

**Comment by DarkAngel9041** [comment]
![IMG_20210518_040955_320](https://user-images.githubusercontent.com/84359315/118577144-86d2c400-b792-11eb-8a36-a14359536ff1.jpg)

**Comment by Kanuan** [comment]
This picture is not helpful. Do you have some hard proof that this controller can even rumble? Does it rumble on a real PS4?

As I said, send the official website page of this controller that list it's features.

Besides that, your last 4 comments could be merged into a single one. If possible, edit your posts to merge them

**Comment by DarkAngel9041** [comment]
the controller i bought from media galaxy 2 years ago from the country i live Romania
and i trhow away the box he came with long time ago

**Comment by DarkAngel9041** [comment]
if i unplug and then plug it back sometime it recognize him different

**Comment by DarkAngel9041** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/84359315/118577815-c352ef80-b793-11eb-8297-ff62476a0138.png)
that is how it recongnize him when i unplug it and plug it back and it rumble 100% when i test it with test heavy from ds 4 windows

**Comment by Kanuan** [comment]
Send the log file of when the controller is recognized as the Armor 3 LU Cobra controller

**Comment by mika-n** [comment]
Looks like someone has sold you a copycat of DS4 gamepad and not the genuine one. Or for some reason your PC has screwed up HID device drivers in such a way that Windows is picking up wrong driver (veeeery unlikely scenario because the VID/PID identifier is coming from the hardware unless some fancy driver does something along the way).

Armor3 and GioTeck gamepads are just different brands for the almost the same gamepad. Both of those are probably manufactured by the same copycat factory because those have the same VID vendorID code.

There is nothing DS4Windows app can do about it if you have a copycat fake hardware.

**Comment by DarkAngel9041** [comment]
thank you what you said it answer to all my questions
