### ISSUE TITLE
Issue with controller Output slot

### ISSUE THREAD

**Issue by K54M** [Ryochan7/DS4Windows#2158]
So I've had this issue for a while & i've been doing some digging trying to find a solution for it & found this thread from a while ago #1983. So, whenever I either turn off DS4W or my controller disconnects from Bluetooth so I can use my Xbox One controller (Cause I like switching between a few controllers) & then turn back on DS4W, the controller output is set to # 2, # 3 or # 4 in the xinputchecker tool. For a lot of games (Rocket League & Modern warfare) it creates problems as it either detects the controller as player 2 or doesnt detect any controllers as there arent any assigned to output slot #1. Is there a way or a tool I can use to re-assign the output slots on the fly & is the only option to reboot Windows ? Because restarting Windows is tedious & I have to reopen all the programs I had opened just to change controllers. Any help would be appreciated. Thanks !

**Comment by Ryusennin** [comment]
You could have posted in the thread you mentioned, in order to keep things tidy.

**Comment by mika-n** [comment]
#1983 see this duplicate ticket and discussions about ViGem driver version and DS4Windows slot Persistent vs Dynamic discussions.
