### ISSUE TITLE
Touchpad clicks in Macros (mainly for DS4 mode)

### ISSUE THREAD

**Issue by SharinDarkSide** [Ryochan7/DS4Windows#2159]
When I create a Macro using the Record function, DS4Windows detects all the DS4 inputs except for the Touchpad actions, especially Touchpad clicks.

Some PS4 games that I play via PS4 Remote Play for PC have features linked to the Touchpad click, which I cannot include in my Macros so far.

Is it even possible to include DS4 Touchpad actions (mainly clicks) in Macros via DS4Windows? What is the Touchpad click code for Macros (like 262 for the DS4 Circle Button) so I can eventually edit my macros manually instead of using the Record function?

Thank you very much for this great tool, the regular updates and your support for this matter.

**Comment by Ryochan7** [comment]
Touchpad Click is not available to map in Macros. There is still enough room in the values to add an extra code to allow Touchpad Click to be mapped.

**Comment by Ryochan7** [comment]
Looked into it.  I have given up on the idea of changing this. It really ties to the main mapping loop and conflicts with the existing 4 virtual Touchpad buttons. Sorry

**Comment by SharinDarkSide** [comment]
Thank you very much for trying and for your feedback, appreciated.

I found a workaround for those interested in a solution: binding a keyboard key to the DS4 Touchpad in PS4Macro (another utility for DS4 macros) and then map that keyboard key to the Touchpad under the DS4Windows settings. It is not perfect but it works...

**Comment by Ryochan7** [comment]
Ended up finding a way around the initial problem. Got a version implemented.
