### ISSUE TITLE
Days Gone Swiping Menus

### ISSUE THREAD

**Issue by efremzero7** [Ryochan7/DS4Windows#2160]
Swiping to access different menus in Days Gone isnt working, do i need to change some setting?

**Comment by Ryusennin** [comment]
I forgot the PS4 version had swiping functions to display the map, inventory, etc. I checked the game with emulated DS4 controller mode and indeed everything works (including touchpad click) except swiping. ViGEm version is 1.17 and touchpad passthrough is enabled.

My alternative suggestion is to set the touchpad output mode to Controls instead of Passthrough and configure each swipe to a keyboard key (for reference: up as J, down as O, left as I, right as M). It works with emulated X360 controller mode.

**Comment by Mircosfot** [comment]
Wired in DInput- Mode works also very nice.

**Comment by tonebacas** [comment]
When you set emulated controller to Dualshok 4 and use Output mode as Passthru, it should work, both via wired and via bluetooth.

**Comment by Ryochan7** [comment]
> I forgot the PS4 version had swiping functions to display the map, inventory, etc.

But this issue probably refers to the PC port. I would not expect it to work as I doubt the PC port has any native support for the DS4. PCGamingWiki just says that it has DS4 button prompt support (no lightbar support even) so I would assume that it just reads the DS4 as a DirectInput device.

https://www.pcgamingwiki.com/wiki/Days_Gone

Besides, Days Gone is just a spyware app. You should probably just request a refund and forget the port ever existed.

I swear it would just be a lot easier just to remove emulated DS4 support at this point. People making assumptions about features that don't exist in a game and call it a DS4Windows bug. Can't have nice things

**Comment by Ryusennin** [comment]
"You should probably just request a refund and forget the port ever existed."

Nah. it's a good port and I'm fine with telemetry. Playing it on PS4, I didn't have a choice anyway, so why would I get bothered now by Sony monitoring my fantastic zombie skull bashing performances on PC? Or the time it takes me to click options in the menus? Contrary to Copeland, I'm not that paranoid.

"People making assumptions about features that don't exist in a game [...]"

Fair point, but Days Gone on PC specifically (or supposedly) supports gyro and touchpad swiping via native DS4.

![](https://thumbnails.pcgamingwiki.com/b/b3/DaysGone_ControllerSettings.png/528px-DaysGone_ControllerSettings.png)

**Comment by efremzero7** [comment]
It worked plugged via USB and without using ds4windows.

**Comment by Gianlucas94** [comment]
Hi, create a profile with the name DS4, in other use the emulated controler as Dualshock4

![image](https://user-images.githubusercontent.com/38408614/119753446-29670300-be75-11eb-8091-774767beccf9.png)

And put LightBar, TouchPad and Gyro as Passthru.

If you use HidHide, hide the physical DS4 and whitelist the emulated one
