### ISSUE TITLE
After clicking on 'Start' my controller is connected but after few seconds. It's turns to disconnected.

### ISSUE THREAD

**Issue by kazhybride** [Ryochan7/DS4Windows#2162]
The problem is that I can't connect my controller with USB Cable, I don't have Wireless on my computer so I have to use USB Cable. When I run the app and click on "start". My controller is connected, but after a few seconds, it's turns to disconnected by itself. I have installed all requirements for DS4Windows.

Here are the logs : 

21/05/2021 13:03:32: Starting...
21/05/2021 13:03:32: Connection to ViGEmBus 1.17.333.0 established
21/05/2021 13:03:32: Searching for controllers...
21/05/2021 13:03:32: Using Shared Mode
21/05/2021 13:03:32: Found Controller: A0:AB:51:C0:22:5B (USB) (DualSense)
21/05/2021 13:03:32: Plugging in virtual X360 Controller
21/05/2021 13:03:32: Associate X360 Controller for input DS4 #1
21/05/2021 13:03:32: Controller 1 is using Profile "Default". Battery level is 100%
21/05/2021 13:03:33: ViGEm Device Plugin Failed. Likely an internal ViGEmBus problem. Closing connection. If the issue persists, please reboot Windows. WARNING: You will likely get a BSOD on Windows shutdown.
21/05/2021 13:03:33: Stopping Virtual Output Controllers
21/05/2021 13:03:33: Closing connection to ViGEmBus
21/05/2021 13:03:33: Stopping DS4 Input Controllers
21/05/2021 13:03:33: Stopped DS4Windows

 - Controller Make and Model : Sony PS5 Controller
 - OS : Windows 10 Professionnel
 - DS4Windows Version [e.g. 3.0.5]

**Comment by mika-n** [comment]
Hi. Looks like some issues with ViGemBus installation. Or maybe you have multiple versions of ViGem bus installed (for example some HP laptops/PCs may have a copy of ViGem driver HP "stole" from Nefarius and released without bothering to change driver ID or even updating and keeping the HP copy up to date. Big shame on HP).

Anyway whatever the situation is there I recommend you to do this
- Uninstall existing ViGem driver (look in DeviceManager and uninstall all drivers with a keyword ViGem)
- If you are unsure then you could use DriverStoreExplorer which makes it a bit easier to see what kind of drivers you have installed at the moment and nuke unnecessary drivers (in this case all existences of ViGem driver): https://github.com/lostindark/DriverStoreExplorer
- After uninstall ViGEm download the latest ViGem driver version from https://github.com/ViGEm/ViGEmBus/releases and install it (make sure to install ViGEmBusSetup_x64.msi 64bit version because you probably have 64bit WindowsOS).
- Then make sure you download and install the latest 64bit version of DS4Windows app from https://github.com/Ryochan7/DS4Windows/releases and download the DS4Windows_versionTagGoesHere_x64.zip version (ie. 64bit version of DS4Windows if and most probably you do have 64bit WinOS).

If you have accidentally installed x86 32bit version of ViGem or DS4Windows then you may see weird ghost bugs.

**Comment by Kanuan** [comment]
Also, check the [troubleshooting section](https://vigem.org/projects/ViGEm/How-to-Install/#troubleshooting) of the Vigem's `How to Install/Remove` article

**Comment by kazhybride** [comment]
Ok, so, I have followed step by step everything to remove and purge ViGEmBus. I have used Driver Store Explorer to delete vigembus.inf. I have re-install the lastest version according to the installation section and reboot my computer.

My computer is not a laptop.

Here is the configuration :

Motherboard : ASUSTeK COMPUTER INC. TUF GAMING Z490-PLUS Rev 1.xx
Operating System : Microsoft Windows 10 Professionnel (64 bits) 2009 (10.0.19042)

I have installed ViGEmBusSetup_x64.msi
And I'm using DS4Windows_3.0.5_x64.zip

And here is the logs after everything I did : 

05/22/2021 09:33:09: DS4Windows version 3.0.5
05/22/2021 09:33:09: DS4Windows Assembly Architecture: x64
05/22/2021 09:33:09: OS Version: Microsoft Windows NT 10.0.19042.0
05/22/2021 09:33:09: OS Product Name: Windows 10 Pro
05/22/2021 09:33:09: OS Release ID: 2009
05/22/2021 09:33:09: System Architecture: x64
05/22/2021 09:33:09: Running as User
05/22/2021 09:33:10: Starting...
05/22/2021 09:33:10: Connection to ViGEmBus 1.17.333.0 established
05/22/2021 09:33:10: Searching for controllers...
05/22/2021 09:33:10: Using Shared Mode
05/22/2021 09:33:10: Found Controller: A0:AB:51:C0:22:5B (USB) (DualSense)
05/22/2021 09:33:10: Plugging in virtual X360 Controller
05/22/2021 09:33:10: Associate X360 Controller for input DS4 #1
05/22/2021 09:33:10: Controller 1 is using Profile "Default". Battery level is 62%
05/22/2021 09:33:11: ViGEm Device Plugin Failed. Likely an internal ViGEmBus problem. Closing connection. If the issue persists, please reboot Windows. WARNING: You will likely get a BSOD on Windows shutdown.
05/22/2021 09:33:11: Stopping Virtual Output Controllers
05/22/2021 09:33:11: Closing connection to ViGEmBus
05/22/2021 09:33:11: Stopping DS4 Input Controllers
05/22/2021 09:33:11: Stopped DS4Windows

It seems like it's the same problem. I don't understand why but yeah. After rebooting my computer, It does the same thing.

Controller Make and Model : Sony PS5 Controller

**Comment by Ryochan7** [comment]
At some point, I need to write some small utility to purge any ViGEmBus created virtual Xbox 360 controllers from the Device Manager. I ended up making a similar issue happen during some odd tests. Rebooting Windows didn't even fix the problem. I didn't do it but re-installing ViGEmBus would likely not fix that problem either. Only by opening the Windows Device Manager, selecting the **Show hidden devices** option, and then removing all Xbox 360 controllers allowed ViGEmBus to operate properly again.

You might get lucky and Device Manager might show an icon in the device display for the XInput controller or the corresponding HID DirectInput device.

![107984782-4c3c6e00-6f8e-11eb-9634-93345716801b](https://user-images.githubusercontent.com/581968/120242111-bcaf8800-c229-11eb-8456-f59a665c1ccd.png)

**Comment by kazhybride** [comment]
> At some point, I need to write some small utility to purge any ViGEmBus created virtual Xbox 360 controllers from the Device Manager. I ended up making a similar issue happen during some odd tests; I cannot remember what I was doing at the time. Rebooting Windows didn't even fix the problem. I didn't do it but re-installing ViGEmBus would likely not fix that problem either. Only by opening the Windows Device Manager, selecting the **Show hidden devices** option, and then removing all Xbox 360 controllers allowed ViGEmBus to operate properly again.
> 
> You might get lucky and Device Manager might show an icon in the device display for the XInput controller or the corresponding HID DirectInput device.
> 
> ![107984782-4c3c6e00-6f8e-11eb-9634-93345716801b](https://user-images.githubusercontent.com/581968/120242111-bcaf8800-c229-11eb-8456-f59a665c1ccd.png)

**Comment by kazhybride** [comment]
> At some point, I need to write some small utility to purge any ViGEmBus created virtual Xbox 360 controllers from the Device Manager. I ended up making a similar issue happen during some odd tests; I cannot remember what I was doing at the time. Rebooting Windows didn't even fix the problem. I didn't do it but re-installing ViGEmBus would likely not fix that problem either. Only by opening the Windows Device Manager, selecting the **Show hidden devices** option, and then removing all Xbox 360 controllers allowed ViGEmBus to operate properly again.
> 
> You might get lucky and Device Manager might show an icon in the device display for the XInput controller or the corresponding HID DirectInput device.
> 
> ![107984782-4c3c6e00-6f8e-11eb-9634-93345716801b](https://user-images.githubusercontent.com/581968/120242111-bcaf8800-c229-11eb-8456-f59a665c1ccd.png)

Can you add me on Discord ?

AS | Kazhy#4938

I still can't do anything.

**Comment by Ryochan7** [comment]
> Can you add me on Discord ?

I deleted my Discord account when I deleted the DS4Windows server. I do not want to use that service anymore.

Anyway, you might want to check out the new PurgeOldXInput tool bundled with DS4Windows 3.0.9; it is located in the Tools folder. That will find the various XInput controller interfaces and delete all the associated controllers.
