### ISSUE TITLE
Feature request: Change LED colour for different player controllers

### ISSUE THREAD

**Issue by Pixxel123** [Ryochan7/DS4Windows#2163]
I have two DualShock 4 controllers, and I have set Player 1 to Default profile with a blue lightbar colour, whereas Player 2 has a profile named Player 2 bound to it with a red lightbar.

However, I have set bindings and lightbar colours for different programs, it would be nice to have the ability to just change the lightbar for each controller while keeping the profiles so that different profiles don't have to be created.

![image](https://user-images.githubusercontent.com/36304206/119206750-f8ad5500-ba93-11eb-9892-8af3fed0ccdc.png)

Perhaps this screen could be extended? An "Auto" option could also be handy, in which it will look at the profile colour set and pick the next corresponding or opposite colour on a colour wheel.

**Comment by Ryochan7** [comment]
There is already the option to use a specific lightbar color per controller slot along with setting a lightbar color in a profile. This request seems like overkill and destroys the relationship of one profile per controller.

**Comment by Pixxel123** [comment]
Makes sense to me!
