### ISSUE TITLE
Gyro Passtrough DS4 Mode

### ISSUE THREAD

**Issue by Gianlucas94** [Ryochan7/DS4Windows#2164]
Hi, some games don't work with Gyro Passtrough in Emulated DS4 Mode.
Sorry if was the game problem

Games that didn't worked:
1 - Days Gone
2 - Horizon Zero Down (I think that devs dont implmented in PC)

Games that Worked:
1- DOOM & DOOM 2 Classic
1 - Death Stranding

Controller: DS4v2 in bluetooth
DS4Windows: 3.0.5
VIGEM: 1.17.333.0
HidHide: Hide the real controller.

This is my settings
![Profile Others](https://user-images.githubusercontent.com/38408614/119229207-38545b00-baed-11eb-8082-32769f307204.png)

![Profile Gyro](https://user-images.githubusercontent.com/38408614/119229208-39858800-baed-11eb-8814-aafc4653e572.png)

**Comment by Ryochan7** [comment]
> 2 - Horizon Zero Down (I think that devs dont implmented in PC)

That is a definite **no** on the PC port. The passthru modes are mainly meant for people trying to play PS4 games through PS4 Remote Play. Very few PC games have any form of native support for the DS4 and its more advanced features. Most games would treat it as a basic DirectInput gamepad.

My main way to test Gyro passthru is with RPSC3 and its Gamepad Test app.

**Comment by Gianlucas94** [comment]
Thanks, in GamePad Test app worked very whell.

So all passthru features works very whell. I'll close this issue.

Thanks again!
