### ISSUE TITLE
Lightbar keeps turning red whenever latency is over 10ms.  

### ISSUE THREAD

**Issue by Hiccupcc** [Ryochan7/DS4Windows#2165]
**Describe the bug**
I'm not sure if this is a feature or a bug, but whenever my controller has high latency, the lightbar keeps flashing between red and the color I want. 
**To Reproduce**
1. Open DS4Windows
2. Have high latency that's over 10ms
3. Your controller will turn red and green depending how fast your latency changes. If it's under 10ms it'll be the color you want, if it's over 10, it'll turn red
**Is that a feature or a bug? If it's a feature, can I turn it off?**

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.1 (CUH-ZCT2U)
 - OS: Edition: Windows 10 Pro, Version: 20H2, OS BUILD: 19042.985
 - DS4Windows Version: 3.0.5

**Comment by Kanuan** [comment]
It's a feature.

Go to the `Settings` tab -> Disable or adjust 
 `Flash Lightbar at high Latency`

**Comment by Hiccupcc** [comment]
Noted, thanks!
