### ISSUE TITLE
Zpevdo.b virus upon updating

### ISSUE THREAD

**Issue by ReadyP1ayerTwo** [Ryochan7/DS4Windows#2166]
![image](https://user-images.githubusercontent.com/53491846/119241908-d6651700-bb27-11eb-8b5b-10870b4d3fd5.png)

**Comment by Masamune3210** [comment]
Not a virus, Windows Defender being overly careful and causing a false positive. Disable and try again

**Comment by Ryochan7** [comment]
I have a couple of other tasks to test but this looks to be beyond just being a false positive from anti-virus engines. This looks like it is legitimately flat out extortion.

https://github.com/Ryochan7/DS4Windows/issues/2161#issuecomment-846488505

**Comment by Ryochan7** [comment]
Also, as far as the backtrace shown there, it looks like the exception is happening when the routine tries to move the temporary updated copy of DS4Updater.exe to the DS4Windows install folder.

https://github.com/Ryochan7/DS4Windows/blob/8e63ae66f7639b45b39279c09a7c1adae06df62b/DS4Windows/DS4Forms/MainWindow.xaml.cs#L344

**Comment by Danlezama96** [comment]
Another day another false positive, I wonder why it never happens to me...
