### ISSUE TITLE
Feature request: 8bitdo BT Adapter support

### ISSUE THREAD

**Issue by axxo** [Ryochan7/DS4Windows#2167]
Hey there,

It would be fantastic to add 8bitdo BT adapter support:
https://www.8bitdo.com/wireless-usb-adapter/

Are there any plans to support this BT adapter in the future?

Many thanks & keep up the great work.

Best

**Comment by mika-n** [comment]
Duplicate issue #1970 
The adapter seem to expose games as xinput devices and the original intention of this application was to convert dinput->xinput. If the gamepad is already exposed to WinOS/games as xinput then there is no need to do xinput->xinput conversion.

If the adapter can expose DS4/DS5 gamepads as native DS4/DS5 dinput device interfaces then DS4Windows would probably work out of the box. But for now it doesn't work if 8Bitdo uses xinput interface. 

In theory it would be possible to add support for xinput devices, but it is not likely to happen in anytime soon. And none of the devs have that 8bitdo gadget, so it is next to impossible to debug and test it. Someone else with an actual hardware should try to add the support.
