### ISSUE TITLE
Question: not 100% override the button mapping. Is it possible?

### ISSUE THREAD

**Issue by Mhitra** [Ryochan7/DS4Windows#2168]
First of all,
I'm sorry if I'm using GitHub for this question, but I didn't find another way where I can ask.
I'm wondering if it's possible to not fully override the button mapping.

Let me try to explain with my case:

In my favorite game, I need to map the "left" and "right" button with "1" and "2", but also I need that "left" and "right" are the current "left" and "right" because when I need a combination of buttons "L2 + left", unfortunately, DS4 does "L2 + 1" and in my case is wrong.

Basically, I need to replace "left" with "left AND 1" & "right" with "right AND 2". So, if I press just "left", I get 1,
but if I press "L2 + left" I will get "L2 + left + 1" and it's perfect because the game catch "L2 + left" anyway.

Right now I'm using a different 3rd party application, and that's how this 3rd party application works,
but I'd really love to move to DS4 for many reasons.

Anyone can help me? Or any idea to work around this?

I tried with macro, but it doesn't work.

Thank you

**Comment by Mhitra** [comment]
Ok, it seems macro with delay works.
If you have a better way for this, I'm happy to listen, otherwise, feel free to close.
Thanks

**Comment by mika-n** [comment]
indeed macros can do this. Not sure if you can do it by shift modifiers also.
The macro and key remapping support in DS4Windows is not perfect and it would need a bit of work here and there. Maybe sometimes in the future when/if new version of mapper is available.

**Comment by Ryochan7** [comment]
DS4Windows is not really meant for more advanced button mapping. Mostly the basic mapping cases are covered by this app. There will be some games that will likely not be able to have an ideal mapping due to mapping restrictions (Elder Scrolls 4: Oblivion is one such example).

**Comment by Mhitra** [comment]
DS4Windows does an amazing job, I think it covers pretty much 99% of the scenario.
Unfortunately in my case and in my game (FFXIV) doesn't work properly and for me was mandatory rollback to my prev 3rd party application (Pinnacle Game Profiler).
Thank you all anyway for your amazing job!
