### ISSUE TITLE
DS4Windows only supports .NET 5.0.0

### ISSUE THREAD

**Issue by maicol07** [Ryochan7/DS4Windows#2169]
**Describe the bug**
Currently, DS4Windows requires only .NET 5.0.0 and newer versions like 5.0.6 can't work with it.

**To Reproduce**
1. Install .NET 5.0.6 (latest version)
2. Run DS4Windows
3. See error

**Expected behavior**
DS4Windows should work with all 5.x versions (or at least 5.0.x)

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2E)
 - OS: Windows 10 Pro Build 21387
 - DS4Windows Version 3.0.5

**Comment by Ryusennin** [comment]
I have 5.0.6 and DS4Windows works correctly.

It did crash while Windows was updating .NET, but a reboot fixed the issue.

**Comment by komawoyo** [comment]
I have .NET 5.0.6 on a clean Windows 10 install. .NET 5.0.6 was installed directly after running DS4Windows for first time. No reboot needed.

**Comment by Ryochan7** [comment]
Using .NET 5.0.6 right now and it works fine
