### ISSUE TITLE
[Request] Auto restart DS4Windows on update

### ISSUE THREAD

**Issue by pralima87** [Ryochan7/DS4Windows#217]
So this is a request for a improvement of the Auto-update feature.
Right now the auto-update will require closing DS4Windows making the controller stop working.
Them the user needs to reopen the app using KB+M.

So it would be great if DS4Windows would auto restart itself after the update is done.

**Comment by Ryochan7** [comment]
That can be done easy enough. The default option will still be manually for the times people run the updater directly. A command line switch will be used for telling the updater to launch DS4Windows immediately after updating completes.

**Comment by pralima87** [comment]
nice ;)!
