### ISSUE TITLE
Cronus Max type devices not working

### ISSUE THREAD

**Issue by Lazur0** [Ryochan7/DS4Windows#2173]
**Describe the bug**
whenever i connect my ps4 controller through my strikepack and start DS4Windows it keeps showing the first setup window, the one telling you to install ViGEmBus drivers (also every time tells me that i have an older driver like version 1.14.xx even if i install the newest one) and shows you how to connect your controller via bluetooth, and when i press the finish button at the end of this setup window nothing happens.

**To Reproduce**
1. Connect Controller through Cronus max type device
2. Launch DS4Windows.exe
3. The software asks to install the latest ViHEmBus driver 
4. Press the install driver button
5. press the finish burron at the driver and controller setup window
6. nothing happens
7. repeat forever

**Expected behavior**
should install the driver and the controller should show up in the controller tab and should be working

**Screenshots and Logs**
log file: [ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/6531152/ds4windows_log.txt)

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2E)
 - OS: Windows 10 Pro Education Build 2009
 - DS4Windows Version 3.0.5 (but i've experienced it i think since 3.0.3 or 3.0.2 so i sticked with an older version)

**Additional context**
i know some people will call me out for using a strikepack and say it's cheating but for that people, this device i so hard to setup that i only use it for the paddle feature

**Comment by mika-n** [comment]
nuke all instances of ViGem drivers (some other apps may have force installed old versions of ViGem), reboot pc, install the latest 1.17.333 ViGem 64bit x64 driver version, reboot PC.

**Comment by Kanuan** [comment]
As mika-n said, your DS4Windows is not using the latest version of Vigem.

Follow, carefully, the [troubleshooting section of the vigembus how to install guide](https://vigem.org/projects/ViGEm/How-to-Install/#troubleshooting)

**Comment by Lazur0** [comment]
thank you guys a lot now everything works
