### ISSUE TITLE
"L1" button doesn't work on version 3.0.6 

### ISSUE THREAD

**Issue by disawoll** [Ryochan7/DS4Windows#2177]
**Describe the bug**
After I updated to 3.0.6 my L1 button stopped working. I had to revert to 3.0.5 to regain functionality.

**To Reproduce**
1. Update to the latest release 3.0.6.
2. Connect DS4 V1 via bluetooth.
3. L1 button doesn't respond.

**Expected behavior**
All buttons should work as intended.

**Screenshots and Logs**
[ds4windows_log_20210527.1.txt](https://github.com/Ryochan7/DS4Windows/files/6555833/ds4windows_log_20210527.1.txt)

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.1 (CUH-ZCT1U)
 - OS: [e.g. Windows 10 Pro Build 20H2]
 - DS4Windows Version [3.0.6]

**Additional context**
Thanks for this awesome app!

**Comment by Ryochan7** [comment]
Now I finally got to test the theory. People seriously pushing this garbage. 3.0.6 is literally **identical** to version 3.0.5. Quit trolling
