### ISSUE TITLE
DS4WindowsDebug.exe fails to start

### ISSUE THREAD

**Issue by Uudarson** [Ryochan7/DS4Windows#2178]
I am trying to product a debug log for a USB disconnecting issue.  When I start debug it fails.  The log is attached.
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/6563675/ds4windows_log.txt)

**Comment by mika-n** [comment]
The debug version works only alongside with the latest 2.x version of DS4Windows app. The debug version doesn't work with 3.x DS4Windows versions. So, download the latest 2.x from releases page, unzip it to a new folder and place the debug version there until there is possibility to enable debug logging in 3.x version.
