### ISSUE TITLE
Game freezes when bluetooth disconnects

### ISSUE THREAD

**Issue by Soren01** [Ryochan7/DS4Windows#2179]
**Describe the bug**
If for any reason the controller loses the bluetooth connection, the game freezes.

**To Reproduce**
Simply disconnect the controller while the game is running.

**Expected behavior**
Game continues to run, regardless of active connection.

**Screenshots and Logs**
If applicable, add screenshots to help explain your problem. Also, please add the most
log file (ds4windows_log.txt) from the Logs folder in your DS4Windows config folder.

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: Windows 10 Pro 
 - DS4Windows Version 3.0.6

**Comment by mika-n** [comment]
most probably a game specific issue.

**Comment by Soren01** [comment]
I tested it on some games: Biomutant, Desperados 3, Lost Words and Persona Strikers

Buuut your tip worked perfectly! Thanks!

I'm using the Windows Insider latest version btw. If the stable version ever presents this problem, the solution is already registered here.
