### ISSUE TITLE
can't get bluetooth to work

### ISSUE THREAD

**Issue by someusernamei** [Ryochan7/DS4Windows#2180]
ds4windows works fine if I connect the controller via USB, but in bluetooth it says the battery is at 0% and it doesn't work

![bt](https://user-images.githubusercontent.com/85050436/120093777-e0bc7d80-c0f2-11eb-8b50-a8eca75176ba.png)
![usb](https://user-images.githubusercontent.com/85050436/120093779-e619c800-c0f2-11eb-86d6-f847c94beab2.png)

I know my bluetooth and controller are fine because they work with steam big picture

**Comment by mika-n** [comment]
something like this has been an issue with some copycat DS4 gamepads (ie. are you sure you have genuine DS4 gamepad?)

**Comment by someusernamei** [comment]
yes

**Comment by someusernamei** [comment]
I can get it to work with Jays2Kings but not with Ryochan and I'm pretty sure it was working a few months ago but atm not a single version works

**Comment by mika-n** [comment]
how the logfile looks like? Take a look at the %APPDATA%\ds4windows\log folder, rename the latest logfile as .TXT file and drag-n-drop attach it here in the comment field.

What do you see in JOY.CPL controlPanel applet when you connect the gamepad over BT? run JOY.CPL command.
When you edit a profile then what do you see in ControllerReadings tab page?

**Comment by someusernamei** [comment]
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/6571498/ds4windows_log.txt)

joy.cpl with ds4 closed
![with ds4 closed](https://user-images.githubusercontent.com/85050436/120223128-7bae7800-c217-11eb-8558-5942a24550c2.png)

with ds4 open
![with ds4 open](https://user-images.githubusercontent.com/85050436/120223148-8406b300-c217-11eb-9295-416fa2b34066.png)

controller readings
![controller reading](https://user-images.githubusercontent.com/85050436/120223171-8cf78480-c217-11eb-804e-233e86060afa.png)

**Comment by mika-n** [comment]
`2021-05-31 13:38:16.6645|INFO|Connection to ViGEmBus 1.16.112.0 established`

You have an old version of ViGem virtual gamepad driver. You should download and install the latest 1.17.333 version (make sure to download 64bit x64 version of DS4Windows app and driver because you have 64bit WindowsOS)
https://github.com/ViGEm/ViGEmBus/releases

**Comment by someusernamei** [comment]
updating ViGem didn't fix it

[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/6571949/ds4windows_log.txt)

**Comment by Kanuan** [comment]
Just for testing sake, disable the `Hide DS4 controllers` in the `Settings` tab od DS4Windows and reconnect the controller, then check the controllers readings

**Comment by someusernamei** [comment]
there was no difference 

![no change](https://user-images.githubusercontent.com/85050436/120235582-c12b6f00-c230-11eb-91ef-63235ad03a71.png)
