### ISSUE TITLE
HidHide Configuration Client app link in Settings tab not work?

### ISSUE THREAD

**Issue by SyaoranChang** [Ryochan7/DS4Windows#2181]
Hi,

I installed HidHide Driver, and then I try Click HidHide Configuration Client button in Settings tab,
but seems not open HidHide Configuration Client exe.

![Snipaste_2021-05-31_01-25-58](https://user-images.githubusercontent.com/18550228/120113992-af55b780-c1af-11eb-8237-b097f84ba273.png)

**Comment by Ryochan7** [comment]
The HidHide Configuration Client has to be installed on the same drive as DS4Windows or the link won't do anything.
