### ISSUE TITLE
Issue regarding Dynamic Output Slots

### ISSUE THREAD

**Issue by Hubert365** [Ryochan7/DS4Windows#2183]
I'm very sorry if this has been brought up before (feel free to close this if that's the case), but I've found an issue where Output Slots aren't cleared when DS4W is "Stopped". The way to replicate this is to repeatedly click "Stop" then "Start", over and over in DS4W. Eventually all slots are "used" and no virtual controller is output, even though DS4W detects the controller. DS4W has to be completely closed to get all the Output Slots back to "empty".

As a sidenote, it was my understanding that the Output Slots showing X360 more or less were representing Xinput Slots numbers, but the virtual xinput controller actually stayed in Xinput Slot 1 even when moving from Output Slot 1 to 8 in DS4W. I've read in an issue about the virtual xinput controller being stuck in slot 2 and not going back to 1 that changing the Output Slot in DS4W to "Permanent" could help with that issue, how are those 2 kinds of "slots" related to each other?

Test done with a plugged (USB) DualShock 3 on Win10 64bit 20H2. DS4W 3.0.6 + ViGEm 1.17.333.0 + DSHidMini 1.4.222.0

Output Slots 1-7 being "Used" and pushing the controller to 8, while seemingly having no effect on the actual xinput slots:
![image](https://user-images.githubusercontent.com/79023565/120119921-d00b1680-c189-11eb-8c7d-3d19b95c3dbc.png)

Controller being completely pushed out of the Output Slots, effectively stopping all virtual controller output until DS4W is manually closed:

![image](https://user-images.githubusercontent.com/79023565/120120010-5889b700-c18a-11eb-8f77-aa0fac2cdf5e.png)

The way DS4W shows the controller no matter the Output Slot (even when it's been completely pushed out of all Output Slots):

![image](https://user-images.githubusercontent.com/79023565/120120049-8c64dc80-c18a-11eb-9782-c7f914f06ccd.png)

**Comment by Kanuan** [comment]
__I may be wrong on what I'm about to say. Let's see if mika-n/ryochan7 appear later to confirm or rectify the following info.__

The "Slots" in the `Output Slots` tab of DS4Windows are not directly related to the XInput Slots. 
- __DS4Windows Output Slots:__ it's just a representation of the number of controllers DS4Windows supports, 8 in total. If it's in the 1st or the last slot it does not mean much.
- __XInput Slots:__ Windows' way of keeping track of xbox controllers order.

When DS4Windows spawns a virtual xbox controller, it will be connected to the first available XInput slot, regardless to what slot in the  `Output Slots` tab it is in.
DS4Windows can't choose which XInput slot a virtual Xbox controller will be connected to.

**Comment by Hubert365** [comment]
I see, "Permanent" keeps the virtual controller alive (fakes a physical controller never disconnecting), which in turn keeps the Xinput slot alive? That does seem to work, although it seems to cause even more problems when "Stop / Starting" DS4W. Also, wouldn't that mean that those 8 controllers showing "Current" "X360" (instead of "Empty") are supposed to be 8 alive virtual controllers (possibly all using / trying to use Xinput slots)?

![image](https://user-images.githubusercontent.com/79023565/120121322-4e6bb680-c192-11eb-9a92-8f7a527381ad.png)

**Comment by Ryochan7** [comment]
The core issue is that a reverse Dictionary was being cleared before all output slots were detached. When it came time to detach the output slot, the slot number corresponding to the device reference could not be found so the routine was skipped. Now the events should work out fine. It solves the issue on my end anyway.

**Comment by mika-n** [comment]
@Ryochan7 Now output slot releasing and re-using seem to work when a gamepad is disconnected/re-connected (for example usb cable removed or BT connection cut off).

But, there still seem to be something wrong when using Stop/Start button (on the bottom right corner in DS4Windows GUI) to disconnect and re-connect gamepads when a default profile doesn't have the same type as the permanent slot. 
- Set the first slot to be x360 Permanent
- Change the default ds4 profile to use dualshock4 output mode
- Disconnect gamepad and re-connect by removing usb cable (or disconnect BT). OutputSlots work OK.

But, now leave the gamepad connected (using a default profile in dualshock4 output mode) and use the Stop/Start button in DS4Windows GUI and keep eye on the OutputSlots list. Ghost slots are left behind and after few times pressing stop/start DS4Windows runs out of available slots.
![ds4_OutputSlotStopStartBtnBug](https://user-images.githubusercontent.com/35538525/120301194-48cab980-c2d5-11eb-8c9d-1990693ffac3.png)

**Comment by Hubert365** [comment]
I just built with the above commit and the initial issue seems to have been fixed (along with another issue I've found in the meanwhile, don't know if it was limited to that specific case, but setting Slot 1 to X360 / Permanent / Plugged + having the physical (Active) controller in Slot 2 set to X360 (Default profile) / Dynamic, then repeatedly pressing "Start / Stop" would freeze the button on "Stop" and make it un-clickable - now I can't reproduce that freeze). I've also tried reproducing the exact issue mika-n describes above and wasn't able to.

**Comment by shinra358** [comment]
This is literally the bug I was talking about for months when I had windows 7 and no one knew what I was talking about. Now it's fixed after updating to 10 and 7 support stopped ...... >:(

Win10 is awful, how could you recommend this trash xD

**Comment by mika-n** [comment]
@shinra358 this was a nasty bug which popped up only in certain scenario (ie. using start/stop button because things worked ok when a gamepad was simply disconnected/re-connected while keeping DS4Windows in running state. And there was mix of xbox and ds4 output profiles).

Anyway. I used to be Win7 user, skipped Win8 completely, then moved on to Win10 and after a while got used to it. Now I think Win10 is the best WinOS release Microsoft has made so far. If you like the Win7 interface then there is OpenShell tool which makes Win10 to look like Win7 even when you still have Win10 benefits under the hood:
https://github.com/Open-Shell/Open-Shell-Menu

**Comment by shinra358** [comment]
win10 requires caching to be oñ for the search feature to work bcuz
everything is not easily accessable like win7. This causes micro stutters
and unresponsive ui from time to time. If i turn it off like win7,
everything is going to be hard to get to. i really only updated for kingdom
hearts. I tried a tool like that to make it appear like 7 and it completely
blocked me out of the inbuilt defender and it kept deleting things and i
couldnt get them out of quarantine. then i kept 10 for too long so ot
deleted my windows.old folder so i couldnt downgrade. this whole thing was
a complete nightmare 😩.  but anyway, wish this could been dealt with b4
the os change. now im getting exclusive issues with ds4 that i never had in
win7 arrrrgh 🤣. But glad yall finally got this situated and now you know
im not crazy 🤣

**Comment by Ryochan7** [comment]
> This is literally the bug I was talking about for months when I had windows 7 and no one knew what I was talking about. Now it's fixed after updating to 10 and 7 support stopped ...... >:(

lol. Sorry. This scenario was fairly easy to re-produce on my end.

> Win10 is awful, how could you recommend this trash xD

I don't like Win10 either. It is pretty much a forced to use it situation. I can't be a contrarian by promoting Linux anymore since I don't even like what has been happening in the Linux space over the last few years. The world needed Terry Davis to make the PC holy land OS.
