### ISSUE TITLE
DS4 disconnects in the middle of a game.

### ISSUE THREAD

**Issue by Uudarson** [Ryochan7/DS4Windows#2185]
I will be playing a game.  DS4windows will disconnect the controller (getting a read error). Then it will reconnected to the controller and will not be able to get it exclusively.  I have to leave the games (some button no longer work) and re-establish exclusively to be able to play again.  This is a USB device, so I do not understand how it can be getting a read error.  Attached are the logs. 
I am running DS4Windows Debug to get debug information, normally I run version 3.0.5, where the errors first started.

[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/6581113/ds4windows_log.txt)
[DS4 error log.txt](https://github.com/Ryochan7/DS4Windows/files/6581114/DS4.error.log.txt)

**Comment by mika-n** [comment]
based on the logfile I would say this is an issue with a loose usb cable connection

**Comment by Uudarson** [comment]
It's not a loose USB cable connection, a bad cable maybe.  I am going to replace the cable and move to a different USB port.  Please keep this open till Friday, the longest I've gone without a problem is two days.

**Comment by Uudarson** [comment]
After three day with no issues, I have to say it was a bad cable.  Thanks for your help and you can close this issue.
