### ISSUE TITLE
Feature Request: Passthru option for output mode on LS and RS

### ISSUE THREAD

**Issue by NLPalm** [Ryochan7/DS4Windows#2187]
Hello! Love the ds4windows software i use it for almost all my games for both remapping and for the emulated 360 controller. One thing I would really appreciate to see in a upcoming  update would be a passthru option on the Output mode for the analog sticks since some games have custom input curves and they have the possibility to collide from the application and the game.

**Comment by Kanuan** [comment]
Isn't this achievable by just disabling all dead-zones and setting the sticks output curve to linear?

**Comment by NLPalm** [comment]
I’m not exactly sure since I feel Ike it is still a difference when I have my output curve on linear and for an example dynamic S curve in call of duty warzone.

**Comment by Ryochan7** [comment]
> I’m not exactly sure since I feel Iike it is still a difference in the curve when I have my output curve on linear in ds4windows and for an example dynamic S curve in call of duty warzone.

I would assume that you probably have not set the anti-dead zones for LS and RS to 0.00.

Other than that, one other factor that would be an influence is that DS4Windows lowers the HID buffer size for the device when it first opens the controller. That would cause a slight change in output responsiveness even when DS4Windows is not running. The buffer size would only be set back to the Windows default when you disconnect and then reconnect the DS4 to your PC. Personally, I like the feel of the reduced buffer size so there has been no need to revert the buffer size to the larger default value that Windows uses.
