### ISSUE TITLE
Issue regarding FPS fluctuations/spikes

### ISSUE THREAD

**Issue by jinwk00** [Ryochan7/DS4Windows#2189]
![image](https://user-images.githubusercontent.com/15257326/120579253-321b8400-c3f5-11eb-9086-deb348449fa0.png)

As one can see from this picture, if I have my controller connected, my frametime keeps spiking about every second, and this has been annoying me as it is visible while playing games. (Even other games too)

What I did so far to my controller is using hidusbf to overclock to 500Hz. Would this cause that issue? Or where is the problem coming from?

Controller is connected via wired using USB-C to USB-C cable.

**Comment by mika-n** [comment]
difficult to say if this issue is even coming from DS4Windows app. How you diagnosed it that DS4windows app and a gamepad is causing the issue? What happens when you keep the gameapd connected without DS4Windows app? Or use the gamepad via Steam client?
