### ISSUE TITLE
[Request] Gamecube type Trigger action.

### ISSUE THREAD

**Issue by puckle** [Ryochan7/DS4Windows#219]
Hi,  wonder whether it would be possible to have some sort of 2 stage trigger type function for the L2 and R2  triggers? Maybe for the first 75% of it's travel it acts as a normal analogue trigger and the final 25% it registers as a separate button press?
This could be a useful setting for emulating Nintendo Gamecube controllers.
Thanks again for this great software.

**Comment by OptimalJew** [comment]
Presumably you'd want to emulate a GC controller for use with Dolphin and fortunately Dolphin already allows you to do exactly what you're asking. Bind L and L-Analog to L2, R and R-Analog to R2, and set the threshold to 75%. As you meet the threshold you've set, the L or R digital press is activated.

**Comment by Seeker14491** [comment]
Duplicate of #77?

**Comment by Ryochan7** [comment]
The feature has been implemented. Not sure when the next DS4Windows release will come out though.

**Comment by Ryochan7** [comment]
Version 2.2.3 is now out.
