### ISSUE TITLE
ViGEmBus Driver installs wrong version and i can't run the program and my controller doesn't work.

### ISSUE THREAD

**Issue by ZIGAG4899** [Ryochan7/DS4Windows#2192]
when i download any of the new versions past 2.1.13 and it asks to install ViGEmBus but when i install it, it installs 1.14.3.4 and the program asks for 1.17.333.0 and i'm not able to run the program.

and yes i have downloaded that version of ViGEmBus on its own. it just tells me to install the older version.

**Comment by Ryochan7** [comment]
This is unbelievably wrong so I am just going to assume you are trolling. Recent versions of DS4Windows have this issue resolved. No matter what, this is legitimately Hewlett-Packard's fault. Buy a better PC next time and don't support companies that **steal** from open source projects.

ViGEmBus Driver 1.17.333.0 not working properly
https://github.com/Ryochan7/DS4Windows/issues/2079

**Comment by Kanuan** [comment]
Check [ViGEm's troubleshooting section](https://vigem.org/projects/ViGEm/How-to-Install/#troubleshooting)
