### ISSUE TITLE
[Question] HidHide?

### ISSUE THREAD

**Issue by shinra358** [Ryochan7/DS4Windows#2193]
So I've installed the hidhide program. I set DS4W as the app that looks past the app's action. If I choose to hide the sony interactive controller, ds4w wont function with the controller. If I choose to hide the xbox gamepad name instead, ds4w will work but games wont see input. How am I supposed to use this program correctly?

Massive exclusive issues on Win10 that weren't on Win7!

**Comment by Kanuan** [comment]
See [HidHide Simple setup guide](https://vigem.org/projects/HidHide/Simple-Setup-Guide/).

Read it carefully to understand how to use it.

**Comment by shinra358** [comment]
Can you elaborate? Obviously I came from that page.

**Comment by Kanuan** [comment]
- The real DS4 controller (`Sony Interactive something`) must be hidden with HidHide. 
- The fake/virtual controller should not be hidden with HidHide
- DS4Windows must be whitelisted by HidHide in the `applicatications` tab (the latest version of DS4Windows, v3.0.7, will auto-whitelist itself if it's not already whitelisted.

If everything is setup correctly, then on Windows' `USB Game Controllers` (Press `Win + R` -> Type `joy.cpl` -> Select Ok):
- the real controller (`Wireless Controller`) should not appear on the list
- DS4Windows should still detect the real controller
- On `joy.cpl` the fake/virtual Xbox controller should be on the list (assuming you are using default DS4Windows settings)

**Comment by shinra358** [comment]
I just figured it out:

"After that, fully close then reopen your application (in case it was running) for it to detect the hidden devices. Alternatively, just reconnect your controllers."

It's says alternatively I can just reconnect the controllers but that's not true. I had to completely close ds4w and relaunch it. Then it worked properly when I hid the sony controllers.

**Comment by Kanuan** [comment]
Since this is now solved, mark this issue as closed
