### ISSUE TITLE
Version 3.0.7 It is sorted by the action column on the right end

### ISSUE THREAD

**Issue by gwin7ok** [Ryochan7/DS4Windows#2194]
![ss002 - DS4Windows](https://user-images.githubusercontent.com/1727775/120880381-269ea780-c605-11eb-95b2-04edcc5943be.jpg)
>Version 3.0.7
>•	Sort Special Action list by action name
It is sorted by the action column on the right end, but wasn't it intended to sort by the name column on the left end?
In addition to the function to sort automatically, it would be more convenient and helpful to have the function to change the order with drag and drop and up and down buttons.

**Comment by Ryusennin** [comment]
I'm a bit confused as well. I thought the 3.0.7 update would sort the special actions by their name, not by their action type.

**Comment by Ryochan7** [comment]
Sorted by the wrong property. My quick scan of the class missed the proper defined Action name in the class. I need to continue to add more comments to the code.
