### ISSUE TITLE
8BitDo Pro 2 Gyro stops working

### ISSUE THREAD

**Issue by Kralle160** [Ryochan7/DS4Windows#2195]
**Describe the bug**
I'm trying to use the Gyro on my 8BitDo Pro 2 via the Switch mode which works for a couple seconds and then there is no Gyro output. Tried it with 2 controllers same model and in Botw in Cemu where it works for a couple seconds and then ceases.

**To Reproduce**
1. Connect 8BitDo Pro 2 on Switch mode
2. Gyro works
3. wait a couple seconds
4. Gyro no longer works (see screenshot)

**Expected behavior**
Working Gyro

**Screenshots and Logs**
Gyro Output in Edit section:
![image](https://user-images.githubusercontent.com/11779571/120880812-c2f88800-c5cc-11eb-92f2-b4ef68b0d759.png)

[log.txt](https://github.com/Ryochan7/DS4Windows/files/6602040/log.txt)

**Desktop:**
 - Controller Make and Model: 8BitDo Pro 2
 - OS: Windows 10 Pro Build 19042.985 / 20H2
 - DS4Windows Version: 3.0.7

**Comment by TheCarrotCR** [comment]
I guess it's a problem with some of your PC hardware or software: i got my Pro 2 just a few days ago and gyro works almost flawlessly in BOtW, almost no differences with DualSense. Spent my sunday toying with gyro aiming and shrine riddles. I can answer your questions lately if you ask.

**Comment by mika-n** [comment]
@Kralle160 You seem to have 100% deadzone (the red area in the sixaxis readings box), so that's why there is no output. You probably have 25.0 in sixaxis deadzone setting. Try changing it to 0.25 value (0 = 0% 1.0 = 100%)

**Comment by TheCarrotCR** [comment]
> @Kralle160 
This area is red for me as well, gyro works though. But maybe there's something about how gamepad API interacts with ds4windows as it works glitchy and if it's possible for output to represent wrong picture. By "glitchy" I mean that my Pro 2 has troubles with charge percent detection (only values I've seen in few days are 75÷ and 50÷), also joy axes sometimes stuck in polar positions when I connect gamepad, usually left joy Y in upper position or right stick stuck in it's in upper left (restarting ds4windows with button in window's bottom left always fixes it). These aren't hardware problems as everything works flawlessly in other connection modes, or over Steam, or after restart, so it seems like ds4windows works with Pro 2 with troubles and it could be linked with red square and/or subject. I also have about 35-40 ms input delay on info tab, and I've been told that's common for Pro 2 even if an actual Nintendo Pro has ~10-15 ms.

To be said, _my_ configuration actually works good, it's just not perfect. Everything works except where I pointed before, for me the biggest problem is not being able to see battery percent, which is not such a big deal with gamepad's capacity.

**Comment by Kralle160** [comment]
> @Kralle160 You seem to have 100% deadzone (the red area in the sixaxis readings box), so that's why there is no output. You probably have 25.0 in sixaxis deadzone setting. Try changing it to 0.25 value (0 = 0% 1.0 = 100%)

Oh my god how did I get a 2500% deadzone... I can't even set it that high now that I changed it.
Maybe the it changed from 25 meaning 25% to 0.25 = 25% at some point.
Anyway it works now.
Thanks
