### ISSUE TITLE
How to make lightbar passthru work?

### ISSUE THREAD

**Issue by AkrumQassem** [Ryochan7/DS4Windows#2197]
I've searched around in the issues and I'm still confused as to what I'm doing wrong.
I have my Lightbar Mode set to: Passthru
and I'm playing Days Gone however the lightbar is just fixed to one color, not interactive.
I've tried to change Emulated Controller from Xbox 360 to DualShock 4, and that just made my game not detect my controller at all.
I have HidGaurdian installed and in HidNinja I have DS4Windows as the only Allowed App.

When I shut down DS4windows completely (and disable HidGaurdian), and I try the game, it works and my ds4 controller is detected and lightbar is interactive and everything is great.

So my question is, how do I make Lightbar Passthru work without shutting down DS4Windows?
And can it work while emulating an Xbox 360? or do I have to switch to DualShock 4? and if so how do I make my pc detect it? cuz I think hidgaurdian is hiding it

**Comment by AkrumQassem** [comment]
Also is there a way to make DS4Windows work with Aurora? or are those 2 just not compatible with one another?

**Comment by Kanuan** [comment]
Send a screenshot of the HidNinja screen

**Comment by AkrumQassem** [comment]
![image](https://user-images.githubusercontent.com/47395272/120896275-89a23580-c629-11eb-90a1-4bee1b14090d.png)

Here you go, btw I've followed your advice from here [https://github.com/Ryochan7/DS4Windows/issues/2036#issuecomment-813701720](url) and it still didn't work

**Comment by Kanuan** [comment]
Ok, do the flowing:
- On HidNinja, select the `bulk edit` option, copy all the entries to a .txt file somewhere so you have a backup. After that, delete everything there and save the changes. Doing so, on the main HidNinja window the `affected device list` should be empty
- after that, replug your controller
- verify in `joy.cpl` (USB game controllers window) if 2 wireless controller appear now, the real and virtual
- export and send here the log file from DS4Windows log tab

**Comment by AkrumQassem** [comment]
[log.txt](https://github.com/Ryochan7/DS4Windows/files/6602812/log.txt)

![image](https://user-images.githubusercontent.com/47395272/120897580-91fd6f00-c62f-11eb-824e-475a3062b600.png)

Yep, looking good,  2 wireless controllers are there and they both work when tested in the joy.cpl

**Comment by Kanuan** [comment]
Go back to HidNinja, select your controller (I guess it's PID is 0x09 and hide only the first entry (the one that has REV written somewhere), then reconnect the controller and test again.

Also, HidGuardian is kind of obsolete right now. It has been replaced with HidNinja which is just easier to use. I didn't recommend you replacing HidGuardian right now because currently HidHide has a issue where virtual DS4 controllers have high input latency in some specific games and I don't know if days gone is one of them

**Comment by AkrumQassem** [comment]
Ok I've done that, and it seems to be working better now. However there is a couple of issues.

1. in Days Gone: the lightbar is off most the time and only flashes a certain color when triggered (for example if my health is lowered, it flashes orange for a second then goes off again
2. in Days Gone: the Select (Share) button doesn't work? not detected
3. in Death Stranding: the lightbar seems to be functioning well, and the share button too, however my in-game button prompts are toggling like crazy between Xbox buttons and PS4 buttons, non-stop flickering between the two

I appreciate your help!

Also regarding my question from earlier, can I benefit from game-controlled lightbar while emulating Xbox 360? or do I have to be emulating DS4? and is Aurora compatible?

**Comment by Kanuan** [comment]
- Send a screenshot of `joy.cpl` so we confirm the real controller is hidden (screenshots are always more trustworthy)
- Send the current log file 
- you can't use any related passthrough function when emulating a Xbox controller
- I guess days gone uses the touchpad to open the menu? You need to enable touchpad passthrough. While you are at that, also enable motion passthrough
- Aurora?

**Comment by AkrumQassem** [comment]
![image](https://user-images.githubusercontent.com/47395272/120898899-a7759780-c635-11eb-96c7-816942d6663f.png)

Okay yeah you are right about Days Gone, I made everything passthru and now the touchpad works to open the menu (both clicks and swipes work!) however light is still off all the time until an event triggers it, idk maybe that's how it should be? no idea

also [Aurora](https://www.project-aurora.com/) is an RGB software that adds more support to unsupported games (for example Dead Cells)

**Comment by AkrumQassem** [comment]
Actually now that I think about it, Death Stranding has always had issues with controllers, when I used regular Xbox 360 emulation it still detected the DS4 one and it cause double-input (even tho hidninja was set up perfectly and I faced no problems with any other game). I even found this in PCGamingWiki
![image](https://user-images.githubusercontent.com/47395272/120899308-bcebc100-c637-11eb-8a0b-aa00352b0a32.png)
idk maybe it bypasses the hidninja

**Comment by Ryochan7** [comment]
This issue has given me an incentive to entirely remove HidGuardian support from DS4Windows. I'm done dealing with it. It makes me feel like making the HidNinja GUI app was a mistake in the first place. Thought it was at least better than having to rely on batch scripts or manually edit the registry.

Sorry Windows 7 users. You get screwed again. HidHide is the only supported HID blocking driver from here on out.

**Comment by AkrumQassem** [comment]
I don't mind switching to HidHide I honestly didn't even know it existed, I've always just used HidGuardian cuz it worked fine (for the most part).
But say I want to switch to HidHide, could you lead me to a guide or a tutorial on what I need to do?
I found the `(Optional) Step 4: Install HidHide Driver` and I did it, and now `HidHide Configuration Client` in my DS4windows but I don't know what to do with it, I'm not that good with this stuff

**Comment by Kanuan** [comment]
As I said, I didn't outright recommend switching to HidHide because:
> currently HidHide has a issue where virtual DS4 controllers have high input latency in some specific games and I don't know if days gone is one of them

Anyway, here is [HidHide Setup Guide](https://vigem.org/projects/DsHidMini/DS4-Mode-User-Guide/)

Regarding Aurora or the lightbar not working as expected (flashing the correct color sometimes instead of being constant, I have no idea)

**Comment by AkrumQassem** [comment]
Thank you so much for your help! I've switched to HidHide for now I'll test it, if anything goes wrong I'll just return to HidGuardian.
I'll close the issue.
