### ISSUE TITLE
ver.3.0.8 An action different from the selected special action is edited 

### ISSUE THREAD

**Issue by gwin7ok** [Ryochan7/DS4Windows#2199]
**Describe the bug**
Since the order of special actions and the order of actions.xml are different, actions different from the selected special action are edited. 

**To Reproduce**
1. Selected special action 
![ss001 - DS4Windows](https://user-images.githubusercontent.com/1727775/120915501-fc211d00-c6de-11eb-9ab4-79a734e1f30e.jpg)
2. Special actions that are actually edited 
![ss002 - DS4Windows](https://user-images.githubusercontent.com/1727775/120915512-11964700-c6df-11eb-8da9-357d2c63b5d4.jpg)
3. Order of actions.xml
![ss003 - C：￥Program Files￥DS4Windows￥Actions xml - EmEditor](https://user-images.githubusercontent.com/1727775/120915523-1ce97280-c6df-11eb-904b-c50d4902044f.jpg)
 

**Expected behavior**
The selected special action is edited 

**Screenshots and Logs**
If applicable, add screenshots to help explain your problem. Also, please add the most
log file (ds4windows_log.txt) from the Logs folder in your DS4Windows config folder.
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/6603756/ds4windows_log.txt)

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 
 - OS: Windows 10 Pro Build 2004
 - DS4Windows Version 3.0.8

**Additional context**
If return to ver.3.0.6, will be able to edit correctly.

**Comment by Mister-Curious** [comment]
I thought I would comment here too since my issue is directly related to Special Actions. When I initially asked for this Special Actions sorting it was my hope that this feature would be optional, but it seems that the alphabetical sorting is hardcoded now. It was my impression from @Ryochan7 that there would be the ability to choose which way we wanted to sort Special Actions, perhaps by simply clicking on the columns in the Special Actions window and that a 'Date' column would be created but this is not the case.

**Comment by gwin7ok** [comment]
> I thought I would comment here too since my issue is directly related to Special Actions. When I initially asked for this Special Actions sorting it was my hope that this feature would be optional, but it seems that the alphabetical sorting is hardcoded now. It was my impression from @Ryochan7 hat there would be the ability to choose which way we wanted to sort Special Actions, perhaps by simply clicking on the columns in the Special Actions window and that a 'Date' column would be created but this is not the case.

**Comment by Ryochan7** [comment]
It would be nice if WPF offered some direct index virtualization support when sorting. Too bad it does not.

**Comment by gwin7ok** [comment]
Version 3.0.9
This bug is still occurring

**Comment by islbro** [comment]
Hello! I can confirm that this bug with special action sorting occurs on versions 3.0.7 and onward. Reverting to 3.0.6 returns this function as desired.
