### ISSUE TITLE
Using ALT in Macros is broken since 3.07

### ISSUE THREAD

**Issue by FJRMaverick** [Ryochan7/DS4Windows#2202]
**Describe the bug**
Since 3.07 using ALT in Macros seems to be broken. I am using the predefined macro for switching programs (alt+tab) since long, but it is not working anymore. I have downgraded to 3.06 and it is working.

**To Reproduce**
1. Define a macro using alt (or use the predefined one for switching programs)
2. try to switch programs (does not work)
3. using the macro in notepad reveals it is only sending the tab-key

**Comment by Ryochan7** [comment]
Macro editing got screwed up from the sorting change. This is probably fixed in the code now. Going to have to wait for version 3.0.9 for the fix.

**Comment by FJRMaverick** [comment]
okay, I will check it as soon as 3.09 arrives

**Comment by gwin7ok** [comment]
Version 3.0.9
This bug is still occurring

**Comment by FJRMaverick** [comment]
problem is not solved with v3.0.9

**Comment by FJRMaverick** [comment]
not solved with 3.0.10
