### ISSUE TITLE
DualShock 4 not detected in v3.0.8

### ISSUE THREAD

**Issue by MysteriousAeon** [Ryochan7/DS4Windows#2203]
Used to work flawlessly in v3.0.7, was using HidGuardian. Did a fresh install of DS4Windows to see if that would help. Removed all related drivers, removed bluetooth device etc. but it still doesn't see the controller. Doesn't see it when I plug it in wired as well. Exclusive mode isn't disabled either, checked device manager.

Installed everything, including optional drivers.

```
06/06/2021 17:49:41: DS4Windows version 3.0.8
06/06/2021 17:49:41: DS4Windows Assembly Architecture: x64
06/06/2021 17:49:41: OS Version: Microsoft Windows NT 10.0.19041.0
06/06/2021 17:49:41: OS Product Name: Windows 10 Pro
06/06/2021 17:49:41: OS Release ID: 2004
06/06/2021 17:49:41: System Architecture: x64
06/06/2021 17:49:41: Running as Admin
06/06/2021 17:49:41: HidHide control device found
06/06/2021 17:49:41: DS4Windows not found in HidHide whitelist. Adding DS4Windows to list
06/06/2021 17:49:42: Starting...
06/06/2021 17:49:42: Using output KB+M handler: FakerInput 0.1.0.0
06/06/2021 17:49:42: Connection to ViGEmBus 1.17.333.0 established
06/06/2021 17:49:42: Searching for controllers...
06/06/2021 17:49:42: Using Shared Mode
```

This is how the log looks, nothing more.

Edit:
Just set v3.0.7 up again and it works perfectly with no issues still... But doesn't get detected in v3.0.8.

**Comment by Kanuan** [comment]
- HidGuardian support was removed in v3.0.8 in favor of HidHide
- If HidGuardian is installed and still hiding the controller then DS4Windows won't be able to detect it anymore
- It's recommended that HidGuardian is uninstalled and replaced with HidHide, with all related steps on this conversed in [HidHide Setup Guide](https://vigem.org/projects/HidHide/Simple-Setup-Guide/)

**Comment by MysteriousAeon** [comment]
> 
> 
>     * HidGuardian support was removed in v3.0.8 in favor of HidHide
> 
>     * If HidGuardian is installed and still hiding the controller then DS4Windows won't be able to detect it anymore
> 
>     * It's recommended that HidGuardian is uninstalled and replaced with HidHide, with all related steps on this covered in [HidHide Setup Guide](https://vigem.org/projects/HidHide/Simple-Setup-Guide/)
> 
>     * HidHide is Windows 10 only, and for now there is no 32 bits version

Uninstalling HidGuardian solved the issue.

Something to add though, when I updated my DS4Windows there wasn't anything telling me to uninstall HidGuardian, so your average user updating from v3.0.7 might have no idea why the controller just doesn't work anymore for some random reason. I did read the change-log specifying it's no longer supported, so I assume it would just stop using the exe and switch to using HidHide.

Might want to make that a bit clearer. Something like "HidGuardian must be uninstalled if you have it installed, starting from v3.0.8!"
