### ISSUE TITLE
Latest Version not working on Windows 10

### ISSUE THREAD

**Issue by JulioGarou** [Ryochan7/DS4Windows#2205]
Don´t know nothing about coding. Just wanted to report that the latest version (3.0.8) is not working on Windows 10. The controller´s not recognized. 3.0.7 works like a charm.

If I can help with anything, just gimme a shout.

**Comment by Kanuan** [comment]
HidGuardian is not supported anymore as of v3.0.8 and needs to be uninstalled/replaced with HidHide. [better explained here](https://github.com/Ryochan7/DS4Windows/issues/2203#issuecomment-855415778)

**Comment by JulioGarou** [comment]
Thanks!
