### ISSUE TITLE
DS4Windows detects controller, then forcibly stops. Every time the application starts a new controller is added to device manager.

### ISSUE THREAD

**Issue by gcaorsiw** [Ryochan7/DS4Windows#2206]
**Describe the bug**
DS4Windows detects controller for a second, then stops. Every time I click "start" on DS4Windows, it gets detected, Windows adds another "Xbox 360 Controller for Windows" device (device manager) and DS4Windows stops. This happens both via Bluetooth and cable.

**Expected behavior**
Controller should be detected but DS4Windows shouldn't forcibly stop.

**Screenshots and Logs**
Device manager screenshot:
https://i.imgur.com/qvolSfF.png

LOG:
> 2021-06-07 20:33:20.4863|INFO|DS4Windows version 3.0.8
> 2021-06-07 20:33:20.4863|INFO|DS4Windows exe file: DS4Windows.exe
> 2021-06-07 20:33:20.4863|INFO|DS4Windows Assembly Architecture: x64
> 2021-06-07 20:33:20.4863|INFO|OS Version: Microsoft Windows NT 10.0.19042.0
> 2021-06-07 20:33:20.4863|INFO|OS Product Name: Windows 10 Home
> 2021-06-07 20:33:20.4863|INFO|OS Release ID: 2009
> 2021-06-07 20:33:20.4863|INFO|System Architecture: x64
> 2021-06-07 20:33:20.4863|INFO|Logger created
> 2021-06-07 20:33:20.7209|INFO|LinkedProfiles.xml can't be found.
> 2021-06-07 20:33:22.0391|INFO|Running as Admin
> 2021-06-07 20:33:23.9840|INFO|ViGEmBus is not installed
> 2021-06-07 20:33:26.5653|INFO|ViGEmBus is not installed
> 2021-06-07 20:34:22.6449|INFO|Starting...
> 2021-06-07 20:34:22.6449|INFO|Using output KB+M handler: SendInput
> 2021-06-07 20:34:22.6449|INFO|Connection to ViGEmBus 1.17.333.0 established
> 2021-06-07 20:34:22.6449|INFO|Searching for controllers...
> 2021-06-07 20:34:22.6449|INFO|Using Shared Mode
> 2021-06-07 20:34:22.7028|INFO|Found Controller: AC:FD:93:8A:58:3E (BT) (DS4 v.1)
> 2021-06-07 20:34:22.7678|INFO|Plugging in virtual X360 Controller
> 2021-06-07 20:34:22.7678|INFO|Associate X360 Controller in slot #1 for input DS4 v.1 controller #1
> 2021-06-07 20:34:22.7678|WARN|AC:FD:93:8A:58:3E disconnected due to read failure: 997
> 2021-06-07 20:34:22.7860|INFO|Controller 1 was removed or lost connection. Charge the battery
> 2021-06-07 20:34:23.7832|WARN|ViGEm Device Plugin Failed. Likely an internal ViGEmBus problem. Closing connection. If the issue persists, please reboot Windows. WARNING: You will likely get a BSOD on Windows shutdown.
> 2021-06-07 20:34:23.7832|INFO|Stopping Virtual Output Controllers
> 2021-06-07 20:34:23.7832|INFO|Closing connection to ViGEmBus
> 2021-06-07 20:34:23.7832|INFO|Stopping DS4 Input Controllers
> 2021-06-07 20:34:23.7832|INFO|Stopped DS4Windows
> 2021-06-07 20:34:25.0657|INFO|Starting...
> 2021-06-07 20:34:25.0657|INFO|Using output KB+M handler: SendInput
> 2021-06-07 20:34:25.0657|INFO|Connection to ViGEmBus 1.17.333.0 established
> 2021-06-07 20:34:25.0657|INFO|Searching for controllers...
> 2021-06-07 20:34:25.0657|INFO|Using Shared Mode
> 2021-06-07 20:34:25.0657|INFO|Found Controller: AC:FD:93:8A:58:3E (BT) (DS4 v.1)
> 2021-06-07 20:34:25.0794|INFO|Plugging in virtual X360 Controller
> 2021-06-07 20:34:25.0794|INFO|Associate X360 Controller in slot #1 for input DS4 v.1 controller #1
> 2021-06-07 20:34:25.0794|WARN|AC:FD:93:8A:58:3E disconnected due to read failure: 997
> 2021-06-07 20:34:25.0794|INFO|Controller 1 was removed or lost connection. Charge the battery
> 2021-06-07 20:35:09.5430|INFO|Found Controller: AC:FD:93:8A:58:3E (USB) (DS4 v.1)
> 2021-06-07 20:35:09.5430|INFO|Plugging in virtual X360 Controller
> 2021-06-07 20:35:09.5430|INFO|Associate X360 Controller in slot #2 for input DS4 v.1 controller #1
> 2021-06-07 20:35:09.5536|INFO|Controller 1 is using Profile "Default". Battery level is 100%
> 2021-06-07 20:35:10.5474|WARN|ViGEm Device Plugin Failed. Likely an internal ViGEmBus problem. Closing connection. If the issue persists, please reboot Windows. WARNING: You will likely get a BSOD on Windows shutdown.
> 2021-06-07 20:35:10.5474|INFO|Stopping Virtual Output Controllers
> 2021-06-07 20:35:10.5474|INFO|Closing connection to ViGEmBus
> 2021-06-07 20:35:10.6104|INFO|Disassociate X360 Controller from slot #1 for input DS4 v.1 controller #1
> 2021-06-07 20:35:10.6104|INFO|Unplugging virtual X360 Controller
> 2021-06-07 20:35:10.6104|INFO|Stopping DS4 Input Controllers
> 2021-06-07 20:35:10.6104|INFO|Stopped DS4Windows
> 2021-06-07 20:35:17.8655|INFO|Starting...
> 2021-06-07 20:35:17.8655|INFO|Using output KB+M handler: SendInput
> 2021-06-07 20:35:17.8655|INFO|Connection to ViGEmBus 1.17.333.0 established
> 2021-06-07 20:35:17.8655|INFO|Searching for controllers...
> 2021-06-07 20:35:17.8655|INFO|Using Shared Mode
> 2021-06-07 20:35:17.8784|INFO|Found Controller: AC:FD:93:8A:58:3E (USB) (DS4 v.1)
> 2021-06-07 20:35:17.8784|INFO|Plugging in virtual X360 Controller
> 2021-06-07 20:35:17.8784|INFO|Associate X360 Controller in slot #1 for input DS4 v.1 controller #1
> 2021-06-07 20:35:17.8784|INFO|Controller 1 is using Profile "Default". Battery level is 100%
> 2021-06-07 20:35:18.8811|WARN|ViGEm Device Plugin Failed. Likely an internal ViGEmBus problem. Closing connection. If the issue persists, please reboot Windows. WARNING: You will likely get a BSOD on Windows shutdown.
> 2021-06-07 20:35:18.8811|INFO|Stopping Virtual Output Controllers
> 2021-06-07 20:35:18.8811|INFO|Closing connection to ViGEmBus
> 2021-06-07 20:35:18.9446|INFO|Stopping DS4 Input Controllers
> 2021-06-07 20:35:18.9446|INFO|Stopped DS4Windows
> 2021-06-07 20:36:05.1909|INFO|Request App Shutdown

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.1 
 - OS: Windows 10 Home Build 19042
 - DS4Windows Version: 3.0.8

**Additional context**
Ever since 3.0.7 I've had this issue. I thought 3.0.8 was going to fix it, but it didn't. I tried using older versions but they broke as well. Tried reinstalling ViGEmBus several times.

**Comment by mika-n** [comment]
See this BT tips:
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#gamepad-connection-over-bluetooth-bt

If nothing there helps then you may have a bad luck with BT dongle/chipset or you have a copy-cat DS4 revision1 gamepad and not a genuine Sony gamepad. Often those copy-cats struggle over BT in native DS4 mode.

**Comment by Ryochan7** [comment]
At least I finally got around to looking into workarounds for problem number 2. The key to correcting the ViGEmBus problem is to delete the virtual Xbox 360 devices in the Device Manager. You would have to enable **Show hidden devices** and there are really 3 exposed devices per Xbox 360 controller.

![xbox_hidden_device_man_2](https://user-images.githubusercontent.com/581968/121244274-48e23080-c864-11eb-9e60-a10b0c8f49c1.png)

![107984782-4c3c6e00-6f8e-11eb-9634-93345716801b](https://user-images.githubusercontent.com/581968/121244260-4384e600-c864-11eb-82f8-9d2f4f7c6491.png)

 I finally looked into automating finding and deleting the virtual devices. There were a lot of old entries on my system from previous experiments. Might have to include something with DS4Windows at some point.

**Comment by Ryochan7** [comment]
https://github.com/Ryochan7/PurgeOldXInput

**Comment by moltyhero** [comment]
Lately I get "ViGEm Device Plugin Failed" in the log when using a profile with "Dualshock 4" as emulated controller (in other) and then the app crash. Xbox 360 emulation works fine.

I tried a couple of different DS4Windows and versions, with full clean installs, deleting drivers, reboot, using the PurgeOldXInput all crash.

**Comment by moltyhero** [comment]
Managed to fix it by uninstalling ViGEm driver and installing ViGEm version 1.16.115

**Comment by elielgdc** [comment]
> Managed to fix it by uninstalling ViGEm driver and installing ViGEm version 1.16.115

I had already tried everything and nothing had worked, but following your tip I managed to solve my problem "closing connection to output handler sendinput".

Thanks!I had already tried everything and nothing had worked, but following your tip I managed to solve my problem "closing connection to output handler sendinput".

Thanks!
