### ISSUE TITLE
Can't connect 2 DS4 controllers simultaneously via native mobo bluetooth

### ISSUE THREAD

**Issue by three36ixx** [Ryochan7/DS4Windows#2207]
I turn one on, it connects. I turn the other on...it may connect after 30 seconds and immediately disconnects. The following screenshot contains the log. I turned one on, tried to turn on the other and got nothing. Turned off the first one, turned on the second one (you can see they have different id numbers) and it would connect for a second and turn off.

 I am trying to connect the controllers via the motherboard's integrated bluetooth (yes the antenna is plugged in). Steam has no issue using both of these controllers together, but this software does.

This was not a problem on my last motherboard from 2013. (edit: Asus Z87 Pro on an i7 4770K)

Any insight is apprecaited.
![1](https://user-images.githubusercontent.com/74925665/121116570-c2d2d500-c7e4-11eb-8c27-71464f6491cb.png)

**Comment by Masamune3210** [comment]
Considering the controller is disconnecting due to a read failure, I'm willing to bet your Bluetooth adapter just cant handle the sheer amount of throughput two DS4's require. Considering it supposedly worked fine as well with your old board only leads more into that idea. You could try disabling writes to the controllers to see if they work then, but you would lose lightbar and vibration

**Comment by Ryochan7** [comment]
What I don't get is that the FileStream class in .NET is supposed to handle overlapped IO operations on its own. There should be no reason that the returned Win32 error code should be ERROR_IO_PENDING (997). Something else must be happening in the backend but the exception thrown by .NET is masked in the HidLibrary used by DS4Windows.

https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--500-999-

**Comment by three36ixx** [comment]
Masamune3210 you missed the part where i said both controllers bluetooth and work on steam no sweat.

Ryochan7 what's the fix brother? I appreciate everything you do for this application, but this issue is driving me crazy!

**Comment by three36ixx** [comment]
I have tried removing the devices etc multiple times to no avail
