### ISSUE TITLE
DualSense Wired Steam

### ISSUE THREAD

**Issue by hypeFLOW** [Ryochan7/DS4Windows#2210]
I'm running into an issue where when using the controller wired it's detected in games, however inputs on the controller do nothing. It works when using Bluetooth for the same games and non-steam games. I tested with another wire same issue. Tested my old DS4 and it works fine wired and wireless. Could it be a steam API issue with DualSense wired?

**Comment by McNippleson** [comment]
Worked fine for me when I used steam as a driver for a bit. Moved back to DS4windows now though.

**Comment by hypeFLOW** [comment]
Not sure what's causing the issue. It works fine over Bluetooth though which is how I play normally. However, I'm aware some features may only work when plugged in directly. Strange.

**Comment by Kanuan** [comment]
With Steam closed and DS4Windows running, do the following:

- Connect your DualSense wired
- Send a screenshot of DS4Windows `controllers` tab
- Press on your keyboard `Win + R` -> Type `joy.cpl` and press OK -> __Send a screenshot of Window's `USB Game Controllers` Window__
- Go to the `log` tab, export the log file and send it here

Repeat the same steps above, but now with the controller connected via Bluetooth.

When sending the files here, send them all in a single comment, with the log files and images organized/correctly name so we don't get confused

**Comment by hypeFLOW** [comment]
![ds4](https://user-images.githubusercontent.com/45800157/121822858-67369a80-cc6f-11eb-916e-0af50a4753c5.png)
 Wired

Bluetooth
![ds4 b](https://user-images.githubusercontent.com/45800157/121822867-71f12f80-cc6f-11eb-901c-45933f264ef0.png)

USB Game Controllers, shows the same thing Wired and through Bluetooth
![coontr](https://user-images.githubusercontent.com/45800157/121822882-87fef000-cc6f-11eb-8542-1f5f20b12ebc.png)

Wired Log
[log.txt](https://github.com/Ryochan7/DS4Windows/files/6644717/log.txt)

Bluetooth Log
[log b.txt](https://github.com/Ryochan7/DS4Windows/files/6644719/log.b.txt)

Steam Settings (Wired & Bluetooth, DS4Windows app closed)
![steam](https://user-images.githubusercontent.com/45800157/121822897-afee5380-cc6f-11eb-92d9-fecd9466ef46.png)

**Comment by Kanuan** [comment]
Ok, everything looks great (except for the double-device on the list which we'll solve later). 

With the controller wired and DS4Windows running, open the [Gamepad tester website](https://gamepad-tester.com/) and 2 controllers should appear on the list after pressing some buttons on the controller.

Report here if both controllers on the list respond to you moving the sticks/pressing buttons, and if one of them don't them which one is the non-responsive one.

**Comment by hypeFLOW** [comment]
They both respond to all the same button presses. The above which I assume is DS4Windows emulation shows vibration test.

![image](https://user-images.githubusercontent.com/45800157/121823249-11afbd00-cc72-11eb-8018-34d9823842aa.png)
Is this the screenshot you're referring to? The same as earlier one.

**Comment by Kanuan** [comment]
- Send a screenshot of the gamepad tester website (I forgot to ask for it)
- Also, a screenshot of DS4Windows with your real DualShock 4 connected (not DualSense)

**Comment by hypeFLOW** [comment]
Test website DualSense
![image](https://user-images.githubusercontent.com/45800157/121823318-8125ac80-cc72-11eb-9fdc-f7d7e238ff4b.png)

DS4 Controller tab
![image](https://user-images.githubusercontent.com/45800157/121823380-eda0ab80-cc72-11eb-96c0-f6e0656ca42c.png)

DS4 Log
[log.txt](https://github.com/Ryochan7/DS4Windows/files/6644756/log.txt)

Test Site DS4
![image](https://user-images.githubusercontent.com/45800157/121823440-4112f980-cc73-11eb-9ebe-3646ce84c5a5.png)

**Comment by Kanuan** [comment]
Ok, I have a guess on what is happening but it's easier to just outright test ->[Install and configure HidHide](https://vigem.org/projects/DsHidMini/DS4-Mode-User-Guide/):

- Remember to reboot your computer after installing it
- On HidHide Configuration Client, Hide only the DualSense controller (Stop DS4Windows so there is only one controller on the list otherwise you will get confused on which controller is the real one that needs to be hidden and which is the virtual DS4)
- You need to hide the controller 2 times: one when it's wired and another when connected by Bluetooth
- After hiding the real controllers (USB and BT), fully close DS4Windows if it was running and then reopen it
- After that, send a screenshot of the gamepad tester website (there should only be 1 controller now, Vendor 054c Pid 05c4
- Test in-game and report back

**Comment by Kanuan** [comment]
Man, I linked the wrong link on the HidHide thing in the first line. My bad. It's fixed now

**Comment by hypeFLOW** [comment]
Should it be like this? in HidHide
![image](https://user-images.githubusercontent.com/45800157/121823884-0fe7f880-cc76-11eb-9acd-0ec26e56547a.png)

**Comment by hypeFLOW** [comment]
Gamepad test site shows no controller detected, connected to DS4 Windows however.

**Comment by Kanuan** [comment]
- Send a screenshot of DS4Windows controllers tab
- Press on your keyboard `Win + R` -> Type `joy.cpl` and press OK -> __Send a screenshot of Window's `USB Game Controllers` Window__
- Send the log file of DS4Windows

**Comment by hypeFLOW** [comment]
![image](https://user-images.githubusercontent.com/45800157/121824225-956ca800-cc78-11eb-9dc0-28ba41dd78af.png)

Doesn't show up in DS4Windows now

**Comment by hypeFLOW** [comment]
It works fine wired with DualSense on non-steam games. Possibly Steam API interference?

**Comment by hypeFLOW** [comment]
Welp I just disabled Steam Controller Input for the games and now its working wired. Thanks for all your help. Appreciate it!

**Comment by Kanuan** [comment]
You need to fully close DS4Windows and open it again for it to white-list itself again on HidHide, as shown in the image below:
![image](https://user-images.githubusercontent.com/24910442/121824519-28aadb00-cc83-11eb-8816-71eb6891692c.png)

Otherwise, DS4Windows won't be able to detect the controller since it's hidden now.

Alternatively, you can directly whitelist DS4Windows in HidHide on the `applications` tab

**Comment by Kanuan** [comment]
> Welp I just disabled Steam Controller Input for the games and now its working wired. Thanks for all your help. Appreciate it!

Well, if it fixed your issue then don't forget to mark this issue as `closed`.
Also, if you don't need HidHide, you can uninstall it on Windows `Apps and features` 

![image](https://user-images.githubusercontent.com/24910442/121824608-c43c4b80-cc83-11eb-8458-9335d04f7d81.png)
