### ISSUE TITLE
[Feature Request] Button & Touchpad readings in Controller Readings tab

### ISSUE THREAD

**Issue by MVail88** [Ryochan7/DS4Windows#2211]
Currently the Controller Readings tab in the Profile editing window only includes readings for the sticks, triggers, and motion controls. No info is displayed about button or touchpad states. This information would be very useful for end users to determine if seemingly faulty input detection is due to hardware failure or some misconfigured setting.

**Comment by Ryochan7** [comment]
I can see a case for including Touchpad readings to that screen. Buttons state can easily be seen using HTML5 Gamepad Tester or even the built-in Windows Game Controllers window. There isn't much of a need for displaying the button state on the Controller Readings screen as well.

Either way, there would need to be a ScrollView added to that section as there is no room to add any extra controls now.

**Comment by Ryochan7** [comment]
Not going to bother with it after all. People misunderstand the current info on the Readings tab as is.
