### ISSUE TITLE
DS4Windows simply doesn't start at all

### ISSUE THREAD

**Issue by TheBloodEagle27** [Ryochan7/DS4Windows#2212]
This MIGHT be an issue on my end, but for the time being (v3.0.8.), the application won't do anything after double clicking it. I've already uninstalled it, even deleted the appdata folder, still nothing. Downloaded a fresh .zip, same issue. Idk what happened tbh, it was working just fine before I updated it.

**Comment by mika-n** [comment]
see the pinned "Read this before posting a new issue ticket" and provide required information. Now we can only call a psychic to look at the issue.
