### ISSUE TITLE
[TODO] Investigate Need For Virtual Device Plugin Delay

### ISSUE THREAD

**Issue by Ryochan7** [Ryochan7/DS4Windows#2214]
As people have noticed before, there is currently a 500 ms delay before most virtual device plugin and unplug routines. This was an attempt to work around an issue with XInput slot skipping that occurred with older versions of ViGEmBus. Especially now that DS4Windows skips older ViGEmBus versions (including HP's botched secret fork), keeping the delay in those routines might not be needed anymore. I am fairly certain that it is not needed with the latest ViGEmBus version (1.17.333.0). Testing will be needed for version 1.16.112.0 to see if a delay would be deemed necessary with that version.

Removing that delay would make those tasks simpler and it might remove the need to use a Dispatcher in the OutputSlotManager class.

**Comment by mika-n** [comment]
I recommend removing the delay and the use of dispatcher events in OutputSlotManager because it has caused all sort of difficult to trace slot bugs. Few of those were recently fixed, but there are still scenarios when DS4Windows somehow uses a wrong slot number (when there are mix of ds4 and xbox360 permanent slots and the default profile is in ds4 mode and Start/Stop button or Start/Stop cmdline is used to stop/start ds4 service).

**Comment by Ryochan7** [comment]
I only know of a recent issue regarding Log messages. The recent slot messages in the Log were wrong a lot of the time because the messages were generated too early so the index was wrong. Those messages needed to be generated from the Dispatcher to make sure they were generated after the virtual controller was actually plugged in and used the current index.

https://github.com/Ryochan7/DS4Windows/commit/e6ae959cbc347c3140cd79f649ba95cf30714882

Hopefully the current queue locker will be enough to allow the multi-threaded calls to work as intended. Maybe this change will be a thing with version 3.0.10. Only going to worry about the Log message change for version 3.0.9.

**Comment by Ryochan7** [comment]
Okay. I can see the problem with different output controller types causing the wrong index to show up. The index of the OutSlotDevice will not necessarily match the index in the displayed list if the output controller type differs. The delay in one device unplug will cause a different OutSlotDevice to get grabbed before the pending unplug event will release the other OutSlotDevice.

**Comment by mika-n** [comment]
yes, something like that. "Something" because I never really quite understood why and what exactly happened there when the OutputSlots screen was showing a bit weird results. And sometimes it worked. Those "ghost type of" issues are nightmare to track downl

**Comment by Ryochan7** [comment]
Testing with ViGEmBus 1.16.112.0 now. Seems to work fine. I guess I will just make the change and maybe revert it later if someone runs into an issue.
