### ISSUE TITLE
How to map horizontal scroll?

### ISSUE THREAD

**Issue by BitGrub** [Ryochan7/DS4Windows#2215]
Sorry for submitting a whole issue for this, but I want to map  "shift + scroll wheel" to "right stick left/right", but scrolling isn't detected in the macro capture window. Is there no way to do this or am I missing something?

**Comment by Ryochan7** [comment]
The DS4Windows mapper does not have support for Horizontal Wheel support at all. I know that the Horizontal Wheel actions aren't used all that much but SendInput does support outputting those type of actions. I have never had a need for it in a profile so not having support has not been a big deal to me. Not even sure there is enough space in the output values to cram in 2 more output actions. Going to have to look into this.
