### ISSUE TITLE
Question: Rumble only on X360 Emulation?

### ISSUE THREAD

**Issue by istalo** [Ryochan7/DS4Windows#2216]
Does the rumble not work at all when using the DualShock 4 emulation? I'm using a DualSense controller and would like to get native PS controller inputs in games that support it but the rumble feature doesn't seem to work when using that and I couldn't find anywhere else about this in mind so I figured I'd just ask it here, tried both wired and bluetooth communications.
So... does it not work at all? Will there be a way to implement it in the future somehow?

**Comment by Kanuan** [comment]
On my tests, with a real DS4v2 connected by USB and without using DS4Windows, I discovered that most games that support the DS4 doesn't support its rumble.

Games that I testes (on Steam, `Playstation Controller Support` was disabled):
- Devil May Cry 5 (Steam)
- Blasphemous (GOG)
- Enter the Gungeon (GOG)
- Hollow Knight (Steam)
- Fall Guys (Steam)

Of all the games above, only Fall Guys has working Rumble. Besides that, using the controller with `PS remote play` while playing PS4 games in a real PS4 also has working rumble as expected.

A interesting thing about this is that some games on Steam have working rumble only when using Steam's `Playstation Configuration Support`. I can't remember the exact game now, but a user reported a while ago that without said configuration enabled, the game only had the PS icons, and with the configuration enabled the game had both PS icons and working rumble. Steam seems to be doing some API hooking directly to the game to do that.

In the end, this all boils down to developers not properly implementing DS4 support and there isn't much DS4Windows can do on this front. Set 2 profiles, 1 for xbox emulation and the other for DS4, do a quick test to check if everything works as expected with DS4 emulation and if it does not then just revert to Xbox emulation. After some time playing you'll just get used to the xbox button prompts.

**Comment by Ryochan7** [comment]
> A interesting thing about this is that some games on Steam have working rumble only when using Steam's Playstation Configuration Support. I can't remember the exact game now, but a user reported a while ago that without said configuration enabled, the game only had the PS icons, and with the configuration enabled the game had both PS icons and working rumble. Steam seems to be doing some API hooking directly to the game to do that.

Maybe it is a case of some games implementing SIAPI support rather than trying to interface with the DS4 directly or using DirectInput. That API layer would offer rumble and PS button glyph support. Days Gone is the newest game, that I know of, that directly uses SIAPI when launched from Steam.

Most PC games that offer any form of DS4 support rely on DirectInput mode and there will be no rumble support in that case.

**Comment by istalo** [comment]
> On my tests, with a real DS4v2 connected by USB and without using DS4Windows, I discovered that most games that support the DS4 doesn't support its rumble.
> 
> Games that I tested (`Playstation Controller Support` was disabled on Steam):
> 
> * Devil May Cry 5 (Steam)
> * Blasphemous (GOG)
> * Enter the Gungeon (GOG)
> * Hollow Knight (Steam)
> * Fall Guys (Steam)
> 
> Of all the games above, only Fall Guys has working Rumble. Besides that, using the controller with `PS remote play` while playing PS4 games in a real PS4 also has working rumble as expected.
> 
> A interesting thing about this is that some games on Steam have working rumble only when using Steam's `Playstation Configuration Support`. I can't remember the exact game now, but a user reported a while ago that without said configuration enabled, the game only had the PS icons, and with the configuration enabled the game had both PS icons and working rumble. Steam seems to be doing some API hooking directly to the game to do that.
> 
> In the end, this all boils down to developers not properly implementing DS4 support and there isn't much DS4Windows can do on this front. Set 2 profiles, 1 for xbox emulation and the other for DS4, do a quick test to check if everything works as expected with DS4 emulation and if it does not then just revert to Xbox emulation. After some time playing you'll just get used to the xbox button prompts.
> 
> ## EDIT 1
> I didn't use a DS4v1 when testing the games above, but since the result is exactly the same between using a real DS4v2 and using _whatever gamepad_ + DS4v1 emulation then it probably doesn't matter.

Interesting enough, I tried that option on Steam but it gives me Xbox inputs instead of PS ones so it pretty much works like DS4Tools if I were to use the integrated Xbox 360 controller emulation.

**Comment by Kanuan** [comment]
> Interesting enough, I tried that option on Steam but it gives me Xbox inputs instead of PS ones so it pretty much works like DS4Tools if I were to use the integrated Xbox 360 controller emulation.

That depends on the Game. This option doesn't "fix" things around for you, it forces whatever configuration Steam thinks the game supports. In some cases, this means working rumble and PS icon, in most other Steam will just present your gamepad as a Xbox controller for the game since it's what most games support.
