### ISSUE TITLE
FakerInput breaks support for mouse scroll speed

### ISSUE THREAD

**Issue by GreenSaint** [Ryochan7/DS4Windows#2218]
Using right stick to scroll, never had an issue before but after doing a fresh windows reinstall the speed is insanely fast.
I remember there being an option to set the scroll speed but after looking in every menu I couldn't find it.
I've tried lowering the sensitivity, vertical scale, and max output to their lowest values (being 0.50, 0.01, 0.01 respectively) but this still ends up being way too fast in my opinion.
Why can't the sensitivity be lower than 0.50?

**Comment by Ryochan7** [comment]
> I remember there being an option to set the scroll speed but after looking in every menu I couldn't find it.

There has never been an option to change the scroll speed for the sticks. Not even in the Jays2Kings version. In fact, in the Jays2Kings version, there was no analog support so it was a constant speed no matter the stick travel. You must be thinking of a different app.

The max speed is set as a constant in the mapper. The max speed value used to be lower in older versions (probably before 2.0) when the output scroll speed was not variable. Once the scroll speed could change with stick travel, the max speed was increased. The current max speed is fine for me so I have had no need to worry about exposing that value as a setting.

**Comment by GreenSaint** [comment]
So apart from those 3 settings, there isn’t any other way of making it slower? 
like I’m saying even on those settings on the lowest I can put them, the slightest touch puts me like 3 pages down, it’s literally unusable, I will post a video of how unusable it is if you would like. 
I had updated to the most recent version sometime last week before my windows reinstall and it wasn’t anything like it is now, is there some kind of log I could provide in the case there is something messed up?

**Comment by GreenSaint** [comment]
Fixed it myself

**Comment by GreenSaint** [comment]
FakerInput breaks support for mouse scroll speed:
https://www.youtube.com/watch?v=EUectD6Xg7E
This sucks because you need to use FakerInput to use the windows on-screen keyboard otherwise it wont accept any input, even trying to use steam's desktop controller as an alternative, you still can't use on-screen keyboard.
On-screen keyboard is kind of essential to using a controller as a keyboard mouse whilst not sitting at the PC IMO, any workarounds for this?

**Comment by Ryochan7** [comment]
Okay. Now I can see the problem. Didn't change a portion of mapping code to use the new coordinate system for wheel scroll. The analog stick to mouse wheel routine still assumes SendInput is used.
