### ISSUE TITLE
ver.3.0.9 Problems related to special actions have not been fixed yet 

### ISSUE THREAD

**Issue by gwin7ok** [Ryochan7/DS4Windows#2219]
I saved the ver.3.0.9 file in a new folder and tried to execute it, but the following problems occurred as before. 
https://github.com/Ryochan7/DS4Windows/issues/2202#issue-912814858
https://github.com/Ryochan7/DS4Windows/issues/2199#issue-912674829

**Comment by FJRMaverick** [comment]
I confirm that #2202 is not fixed with 3.09, I updated 3.06 to 3.09 and tested that, before reverting to 3.06 again

**Comment by Ryochan7** [comment]
Damn. I suck. Could have sworn that a recent change fixed things but the index values are the same. Filing this under "I have no idea what I'm doing".

![ihavenoidea](https://user-images.githubusercontent.com/581968/121949065-ad4a3780-cd1d-11eb-846d-64d239ea3c1b.jpg)

**Comment by FJRMaverick** [comment]
#2202 still not solved with 3.0.10
