### ISSUE TITLE
Stay under profile tab after saving/closing a profile

### ISSUE THREAD

**Issue by iamPanka** [Ryochan7/DS4Windows#2220]
Hi, as sad in the title, can you add an option to remain in the "Profiles" tab after saving or closing a profile, instead of redirecting the focus on the "Controllers" tab? Sorry for my bad english and thanks for your work!
![immagine](https://user-images.githubusercontent.com/16743807/121803976-4ad13880-cc44-11eb-955f-82c219611378.png)
![immagine](https://user-images.githubusercontent.com/16743807/121803982-50c71980-cc44-11eb-9d43-8bf7ab3ccbdc.png)

**Comment by mika-n** [comment]
don't see this as a big issue because there is "Apply" button which is used to apply changes and to stay in profile editor.

**Comment by iamPanka** [comment]
> 
> 
> don't see this as a big issue because there is "Apply" button which is used to apply changes and to stay in profile editor.

Sorry, probably I didn't explain my suggestion very well. I think it would be preferable to remain in the Profiles tab, not in the editor, after saving in order to do other thing like creating a new profile, duplicate an exsisting one etc

**Comment by Ryochan7** [comment]
If I completely had my way, I would completely remove the Profiles tab.
