### ISSUE TITLE
Custom percent trigger to a button assignment.

### ISSUE THREAD

**Issue by MFS2020** [Ryochan7/DS4Windows#2221]
I can assign 100% R2 throttle for example to R1 button, but I cannot assign lets say 28%, is there a way of editing the amount of throttle assigned in the custom profile text file? 

If so where is that text file with profile settings saved?

Also, is there a user manual that explains what each option does? I have no clue what synchronized run or scan code does and hence I don't use those features.

**Comment by Ryochan7** [comment]
No there is not. There is only a Soft Pull action (past dead zone) and a Full Pull action (max value) allowed for the triggers. There is nothing in the mapper backend to allow arbitrary actions at certain axis percentages.
