### ISSUE TITLE
Could not connect to Vigembus :( does this since 4 or 5 days not resolved with 3.09

### ISSUE THREAD

**Issue by Halba** [Ryochan7/DS4Windows#2222]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots and Logs**
If applicable, add screenshots to help explain your problem. Also, please add the most
log file (ds4windows_log.txt) from the Logs folder in your DS4Windows config folder.

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: [e.g. Windows 10 Pro Build 2004]
 - DS4Windows Version [e.g. 3.0.3]

**Additional context**

**Comment by Kanuan** [comment]
- Go to DS4Windows' log tab, export the log file and send it here
- Also, check [Vigem's troubleshooting section](https://vigem.org/projects/ViGEm/How-to-Install/#troubleshooting) on how to verify if Vigem is functioning correctly and to fix common vigem issues

**Comment by mika-n** [comment]
closed as "not providing enough information in the bug report". Please read the pinned "read this before posting a new issue ticket" post and provide all required information (versions and most of all a logfile)
