### ISSUE TITLE
Axis is not being received in DS4

### ISSUE THREAD

**Issue by kmskmichael** [Ryochan7/DS4Windows#2224]
**Describe the bug**
My controller axis is not being received in DS4 while every other setting is fine, it is a switch controller. The web gamepad tester shows everything works fine.

**Desktop (please complete the following information):**
 - Controller Make and Model: some random producer in china -- HSY-019-1
 - OS: Windows 10
 - DS4 Windows Version 3.0.8

**Comment by mika-n** [comment]
make sure you don't have too big deadzone setting. What do you see in ControllerReadings tab page in profile editor? Send a screenshot
