### ISSUE TITLE
Game doesn't see virtual gamepad

### ISSUE THREAD

**Issue by shuhrat199** [Ryochan7/DS4Windows#2226]
Hello everybody. I played rainbow six siege on controller (Dualsense) and I used rebind L1 to L2, R1 to R2 but after game update it stopped working. Rainbow six siege sees only my physical controller. hide ds4 controller doesn't work.

**Comment by mika-n** [comment]
See the pinned "Read this before posting a new issue ticket" and provide necessary information (versions and most of all logfile).
Also, read through the troubleshooting tips and explanation of "Hide DS4 Controller" (=exclusive mode) option (linked in the pinned post)
