### ISSUE TITLE
Ds4windows cannot emulate the windows or alt keys

### ISSUE THREAD

**Issue by DebugKirby** [Ryochan7/DS4Windows#2227]
On the most recent version of DS4windows even if I bind Lalt, Ralt or Lwindows, Rwindows to a button,  hitting it does nothing
Is this something to do with the new keyboard emulation?

**To Reproduce**
1. Go to bind a key
2. Bind it to leftwindows, rightwindows or leftalt, rightalt
3. Try to use the button

**Comment by gwin7ok** [comment]
If you revert to ver.3.0.6, it will probably work. 
https://github.com/Ryochan7/DS4Windows/issues/2202#issue-912814858
https://github.com/Ryochan7/DS4Windows/issues/2219#issue-919733250

**Comment by Ryochan7** [comment]
I would assume that is probably the root issue. The keys work on my end with the current code fixes. Not sure when a new release will get pushed out.

**Comment by gwin7ok** [comment]
> I would assume that is probably the root issue. The keys work on my end with the current code fixes. Not sure when a new release will get pushed out.

Thank you to the corresponding. I will wait for the fix to be released. Until then I use ver.3.0.6

**Comment by FJRMaverick** [comment]
#2202 still not solved with 3.0.10

**Comment by Ryochan7** [comment]
Fixed in 3.0.11
