### ISSUE TITLE
[DualSense] Lightbar Initializes as Incorrect Color

### ISSUE THREAD

**Issue by TodUntoten** [Ryochan7/DS4Windows#2228]
**Describe the bug**
Upon starting the DS4Windows process, the lightbar on my genuine Sony Midnight Black DualSense controller flashes Blue for a second (the correct color), and then turns Red on the sides and White in the middle.  Upon clicking the "Edit" profile button, the DualSense controller immediately switches itself back to the correct color (Blue). I do not have "Color by Battery %" enabled, and the "While Charging" setting is set to "Normal".  Controller is plugged in via USB as I do not have Bluetooth on my PC.

**To Reproduce**
1. Go to 'DS4Windows'
2. Click on 'Start'
3. See incorrect lightbar color
4. Go to 'Controllers'
5. Click on 'Edit'
6. See correct lightbar color

**Expected behavior**
Dualsense Lightbar should remain solid Blue.

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DualSense (CFI-ZCT1W)
 - OS: Windows 10 Pro Version 2004
 - DS4Windows Version 3.0.9

**Photos & Logs**
[ds4windows_log_061520211733.txt](https://github.com/Ryochan7/DS4Windows/files/6658922/ds4windows_log_061520211733.txt)
![DSLightBar](https://user-images.githubusercontent.com/85967760/122127942-ec51b900-ce01-11eb-8b18-dbe9fdef5720.jpeg)

**Comment by Ryochan7** [comment]
I am just going to assume you have Steam Input enabled at the same time and it has a connection to the DualSense as well.

**Comment by Kanuan** [comment]
As Ryochan7 said, try one of the following (if possible, both at the same time before testing):

- Disable `Playstation Configuration Support` on Steam (see the picture below) and restart it
- Make sure that Steam is fully closed (confirm that there is no Steam related process on Windows' Task Manager)

Then you plug your DualSense with DS4Windows running and check if the lightbar behaves as expected

![image](https://user-images.githubusercontent.com/24910442/122448847-930d9500-cf7b-11eb-850b-53f32186dc38.png)

**Comment by TodUntoten** [comment]
Hello Ryochan7 and Kanuan,

I have verified that I had the PlayStation Configuration Support disabled in Steam Big picture while experiencing this issue earlier this week.  However, for some reason I am not able to get the issue to repeat today and the lightbar is operating as expected.  This may have been a first-use issue that worked itself out?
