### ISSUE TITLE
DS4W does not show the controller or sees it.

### ISSUE THREAD

**Issue by infolycal** [Ryochan7/DS4Windows#2229]
_I am using a genuine DS4 controller, The one that came with with the console.
I am trying to connect using bluetooth, I followed all the troubleshooting steps in the wiki, Nothing seems to work._

 I wanted to play forza horizons 4 with a DS4 controller, I connected my controller, **then** opened DS4W, the controller did not appear in the application (DS4W) but is connected to windows (10) using bluetooth (EXACT same result with wired), It doesn't show up in joy.cpl, I've reached a dead end, I don't see anything else I can do, I've reset the controller about 20 times now, I've done a fresh start, I've restarted my computer many times, I've reinstalled DS4W about 3 times now, I have never used Jays2Kings DS4Windows on this computer, The debug version does not show a window at all. It used to work a few days ago (normal DS4W),
 I don't know what to do anymore.
 
  ![DS4Windows_KV1RpFThre](https://user-images.githubusercontent.com/44573650/122234936-f0dfa580-cec5-11eb-9b12-7d7888f213b5.png)

**Comment by Kanuan** [comment]
Press `Win + X` -> On the appearing window select `Device Manager` -> on the top of the device manager, select `view -> Devices by connection` -> send a screenshot of the `device manager` with NOTHING expanded (the screenshot should show every category on the device manager with nothing expanded)

**Comment by infolycal** [comment]
> Press `Win + X` -> On the appearing window select `Device Manager` -> on the top of the device manager, select `view -> Devices by connection` -> send a screenshot of the `device manager` with NOTHING expanded (the screenshot should show every category on the device manager with nothing expanded)

![image](https://user-images.githubusercontent.com/44573650/122240046-1ec6e900-ceca-11eb-9acc-49f522489eb1.png)

**Comment by Kanuan** [comment]
You have hidguardian installed and hiding your controller.
Check [my comment here](https://github.com/Ryochan7/DS4Windows/issues/2203#issuecomment-855415778)

**Comment by islbro** [comment]
> > You have hidguardian installed and hiding your controller.
> > Check [my comment here](https://github.com/Ryochan7/DS4Windows/issues/2203#issuecomment-855415778)
> 
> Finally! It works, but I have one last issue here, There are 2 controllers instead of one, Not sure if this can cause issues or not but, before all of this happened (when it used to work a few days ago) there was 1 controller only.
> ![eevA1ZvrFL](https://user-images.githubusercontent.com/44573650/122245091-1670ad00-cece-11eb-8ea0-d6b920d5b6c2.gif)

Can you confirm the "Hide DS4 Controller" box is ticked under the settings tab of DS4Windows? Perhaps this will solve 2 controllers instead of one.

**Comment by Kanuan** [comment]
This is common. The 2 controllers are your real DS4 one and the other is the virtual Xbox 360 controller that DS4Windows creates.

HidGuardian existed so you could hide the real controller (while only ds4windows could see it).
Follow HidHide's guide that's on the link I've sent you. You need to:
- install hidhide
- reboot
- Configure hidhide so it hides your controller

Everything is covered on HidHide's guide, there is even an explanation on how HidHide works there.

Since your original issue is solved, I recommend you marking this issue as __Closed__

**Comment by infolycal** [comment]
![image](https://user-images.githubusercontent.com/44573650/122253382-cb0dcd00-ced4-11eb-9aaf-7abcedcfebcd.png)
This happens when I connect a controller.

**Comment by infolycal** [comment]
It just disconnects it after a few mins
