### ISSUE TITLE
Settings not saving after reboot or shutdown

### ISSUE THREAD

**Issue by porterballs** [Ryochan7/DS4Windows#223]
hello having a problem with DS4windows remembering my settings, mostly the profile settings such as the light bar brightness and the touchpad settings. Everytime i start up my pc or restart i have to set them again, any help or solutions thanks.

**Comment by BibleBeliever** [comment]
I am having problems due to the controller not connecting if I do not forget and reconnect it after each reboot. Did you pair your controller with 0000?

**Comment by Ryochan7** [comment]
I have tested this and I did not run into any problems. As long as you make sure to save the profile then the settings should persist and be restored upon loading the profile after rebooting. Does your user account have permission to save a file in the Profiles folder wherever you have it on your system?
