### ISSUE TITLE
Action to turn off controller turns off all Sony Wireless Adapters

### ISSUE THREAD

**Issue by C3S4RM3W** [Ryochan7/DS4Windows#2231]
The built-in function for turning off the controllers with PS + Options works perfectly for Bluetooth connected controllers, however, when you use the official Sony Wireless Adapters, it turns off all the controllers connected to them, the only way of turning them individually is right-clicking on the Bluetooth icon on the GUI.

**Comment by Ryochan7** [comment]
Both of those actions link to the same method. There should be no reason that the Special Action and the right-click BT icon action should work differently. I only have one Sony Wireless Adapter so I would have no way to test the scenario directly.
