### ISSUE TITLE
Virus Total Reports Critical issue  2 out of 68

### ISSUE THREAD

**Issue by robertheadley** [Ryochan7/DS4Windows#2232]
**Describe the bug**
Virus Total reports DS4Windows as Trojan

**Screenshots and Logs**
https://www.virustotal.com/gui/file/9ed27a2cfe9325aa82e4a5c9529375f0f04315e796f92c4a9de35cc670b12157/detection
![image](https://user-images.githubusercontent.com/1780455/122317055-7ffab680-cee2-11eb-98af-4807f3c9da78.png)

Starting today, windows was booting up and crashing in a loop because of ucrtbase.dll
I investigated what applications were using that and ds4window is one of those, I did a virustotal sweep using autoruns and there were two positives, positives don't necessarily mean anything bad, but the "
1 match for rule TAIDOOR - Chinese RAT by Ariel Millahuel from SOC Prime Threat Detection Marketplace" was pretty concerning

**Comment by Masamune3210** [comment]
You can look at the millions of other issues with the same sort of subject and get the entire spiel, but short and sweet is there is no malicious code in this project, never has been, it's all false positives. 

if you got anything it's from either somewhere else or from downloading this project from somewhere other than this GitHub page

**Comment by Ryochan7** [comment]
Both are from the new PurgeOldXInput Tool. 1 is just an unsafe flag since it has to run as Administrator. The other is definitely a false positive. VirusTotal is just a major thorn in my side that offers no benefits.

**Comment by robertheadley** [comment]
I didn't mean any offense. I just wanted to bring it to your attention. I know your software is legit and I thank you for working on it. It is easily the best software of it's type. Thanks.
