### ISSUE TITLE
Installing .NET

### ISSUE THREAD

**Issue by TKDKahoh** [Ryochan7/DS4Windows#2233]
It says that I needed to download NET 5.0 Runtime (v5.0.0-preview.1) which I did here: 
![error](https://user-images.githubusercontent.com/79991257/122326809-77aa7780-cef2-11eb-8fe7-9eb5b23c2a50.png)
![error#2](https://user-images.githubusercontent.com/79991257/122326886-9f99db00-cef2-11eb-85af-bc60b1af9584.png)

but DS4 still has not been able to detect the software

**Comment by mika-n** [comment]
try installing the latest official version of .NET 5.x AND make sure you install the 64bit version (x64) version of .NET because you probably have 64bit Win10.
https://dotnet.microsoft.com/download

**Comment by Ryochan7** [comment]
People must really want me to stop distributing an x86 build.

**Comment by zebrax87** [comment]
Hey i'm having the same problem just reinstalled windows and all c visuals etc + net frameworks but still get this error related to Microsoft.WindowsDesktop.App not being found. NET5 is the problem here plz help me fix it

**Comment by mika-n** [comment]
@zebrax87 make sure you installed 64 BIT (=x64) version of .NET 5.x for DESKTOP runtime and 64bit version of DS4Windows app itself. You have probably accidentally installed one of these as x86 32bit version.
