### ISSUE TITLE
DS4 Joystick autoconnecting to wrong pc

### ISSUE THREAD

**Issue by JoakoLP** [Ryochan7/DS4Windows#2235]
**Describe the bug**
I have 2 dongles for 2 DS4 for 2 PCs in the same room. And when I turn on one joystick almost always it connects to the PC that shouldn't. I tried everything I found to disable the bluetooth discovering on both PCs, but it keeps enabled.
If anyone knows a way to disable the discovery mode on bluetooth or block the connection of the DS4 in the PC that I don't want to be connected I will appreciate to telling me.

**To Reproduce**
1. Connect 2 PCs in the same place with a dongle bluetooth on each one.
2. Config each joystick only in the PC that you want to use it.
3. Turn on the DS4

**Expected behavior**
Turning the DS4 on and autoconnects to the PC that shoulds.

**Screenshots and Logs**
![image](https://user-images.githubusercontent.com/82276442/122333147-17293380-cf0e-11eb-8111-cf208ceb5eee.png)
_It's in spanish, but I think that you will get that the discovery mode should be disabled, instead of enabled._

**Desktop (please complete the following information):**
On both PCs:
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: [e.g. Windows 10 Pro Build 20H2]
 - DS4Windows Version [3.0.9]

**Comment by Kanuan** [comment]
Open Windows' `Device Manager` and the Bluetooth MAC Address of each dongle. If both BT dongles have the exact same MAC Address then the controller can't differentiate between them and will connect to the first dongle that responds.
![image](https://user-images.githubusercontent.com/24910442/122334079-86535780-cf0f-11eb-9e4a-75229619d54b.png)

**Comment by JoakoLP** [comment]
I've just check that and yes, both have the same MAC. I'm going to see if I can get a refund for the last one I bought and buy another with a diferent model and MAC, but same 4.0 version.
Thanks for the tip

**Comment by Kanuan** [comment]
The 2 BT dongles I've bought from AliExpress came with the same MAC address. There is a tool that can update the dongles firmware to change it. The problem with using it is that there is no way to tell before hand if it won't just fry the dongle and kill it.

If you want to take the risk:
https://macaddresschanger.com/download-bluetooth-mac-address-changer

**Comment by JoakoLP** [comment]
Maybe that could help me. Just to know, you tried this software?

**Comment by Kanuan** [comment]
Yes, it worked on mine. I just used the exact same MAC address but changed the last number.

But still, remember, __nobody is responsible for the result you get. Even though it _should_ work, there are no guarantees this won't kill your dongle.__

**Comment by JoakoLP** [comment]
Ok, I will try. I will do like you did, you wrote manually al the MAC less the last number?
It shows me a random MAC address
![image](https://user-images.githubusercontent.com/82276442/122422749-c8a68400-cf63-11eb-88d6-4e5d0b9fe80a.png)

**Comment by JoakoLP** [comment]
![image](https://user-images.githubusercontent.com/82276442/122423106-0efbe300-cf64-11eb-9c4d-fb34ad8ba43c.png)
Something like this will be ok? If all goes good

**Comment by Kanuan** [comment]
Yes, that number should work. After changing the Mac address remember to replug the dongle (or just mark the `Auto reset Bluetooth adapter` checkbox)

**Comment by JoakoLP** [comment]
![id dongle](https://user-images.githubusercontent.com/82276442/122427409-79fae900-cf67-11eb-9a98-cfb71b64ee87.PNG)
It worked!! Thank you so much!

**Comment by Kanuan** [comment]
Nice!
Remember to mark this issue as __Closed__ later!
