### ISSUE TITLE
Listed items in Special Actions section out of order (3.0.9)

### ISSUE THREAD

**Issue by spinningacorn** [Ryochan7/DS4Windows#2237]
Description:
In the Special Actions section, items are being sorted alphabetically on the GUI, but when going to the "Edit" option, you get the item index as listed in the Actions.xml file (not sorted alphabetically)
Also related, the "Touch" trigger options are out of order too. The "Right Touch" trigger actually reads the Upper Touch.

Reproduce:
Create more than two Special Actions and rename them after creation so they'll be listed alphabetically differenly as the order in which they were created.

DS4Windows Version 3.0.9
My profiles have been carried over from several versions before this one (3.0.4 at least). I have not tried whether the problem happens on a fresh 3.0.9 install with no previous settings.

**Comment by gwin7ok** [comment]
https://github.com/Ryochan7/DS4Windows/issues/2199#issue-912674829
https://github.com/Ryochan7/DS4Windows/issues/2219#issue-919733250
If you revert to ver.3.0.6, it will probably work.

**Comment by spinningacorn** [comment]
Thanks for the reply, I didn't realize it was already reported.
Opening Actions.xml to verify the actual order of items is enough of a workaround for now, I don't need to modify these settings that often. Just wanted to report it in case it wasn't already known.
