### ISSUE TITLE
No Controller Connection 3.08 3.09

### ISSUE THREAD

**Issue by ChaosOrdeal** [Ryochan7/DS4Windows#2238]
My DS4 controllers simply don't appear in DS4Windows, although they ARE connected via Bluetooth to Windows 10.  Reverting to 3.07 instantly fixed the issue.

1. Turn on Controller(s)
2. "No Controllers Connected (Max 8)" still appears in Controller tab.

**Expected behavior**
obvious

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2
 - Windows 10 Pro Build 21H1
 - 3.07 works fine; 3.08, 3.09 do not

I tried rebooting, re-pairing, running as admin -- no help.  Reinstalling 3.07 instantly fixed the issue, so it seems that the new DS4Windows version must be the culprit (we can say that BT connection and my hardware are "known good" if they work with 3.07).
I imagine it has something to do with changes to Hid, but I certainly can't be sure.

As always, thanks for all the effort on this project.

**Comment by Kanuan** [comment]
You probably have HidGuardian installed and hiding your controllers. DS4Windows does not use HidGuardian anymore (it won't HidGuardian for hidden devices access), therefore it can't see your controllers.

Read [my comment here](https://github.com/Ryochan7/DS4Windows/issues/2203#issuecomment-855415778) on how to solve this

**Comment by ChaosOrdeal** [comment]
Thanks for the quick reply.

This fixed my issue.  You can close the ticket.

I saw the note about HidHide on 3.08 Releases page, but I didn't realize that it was a manual process.

A link or a note there would probably help you avoid some similar tickets.

Again, DS4Windows is awesome and I very much appreciate your work on this software.

DL

________________________________

**Comment by dodgegrim** [comment]
> You probably have HidGuardian installed and hiding your controllers. DS4Windows does not use HidGuardian anymore (it won't request HidGuardian for hidden devices access), therefore it can't see your controllers.
> 
> Read [my comment here](https://github.com/Ryochan7/DS4Windows/issues/2203#issuecomment-855415778) on how to solve this

but how uninstall hidguardian? there zero guides in internet

**Comment by Kanuan** [comment]
HidHide's Setup Guide that is on my linked my comment covers how to uninstall HidGuardian

**Comment by dodgegrim** [comment]
oh ty sir
