### ISSUE TITLE
What bluetooth dongles do you use?

### ISSUE THREAD

**Issue by brothan323** [Ryochan7/DS4Windows#224]

**Comment by Ryochan7** [comment]
The main BT dongle that I use now is a Rosewill RNX-BT401.

https://www.newegg.com/Product/Product.aspx?Item=N82E16833166126

My older BT dongle is a Rocketfish RF-FLBTAD.

https://www.rocketfishproducts.com/pdp/RF-FLBTAD/8819282

**Comment by brothan323** [comment]
hmm. I'm using an Asus BT400, and I can connect and use my ds4 controller on that bluetooth, but only once and from a fresh install of the bluetooth drivers. When the ds4 controller disconnects from the dongle, I can reconnect it but windows/steam does not see an xbox controller, they just see a wireless controller.
