### ISSUE TITLE
Special Action autodisabled.

### ISSUE THREAD

**Issue by JoakoLP** [Ryochan7/DS4Windows#2240]
**Describe the bug**
I've been trying to play minecraft with a mod that allows to use the controller. To do this I use the _Special Actions_ to use the mod's keybindings.
The problem came when I tried to set the _Special Actions_:
**First**, the order was broken, so when I tried to edit one, it opened other that I hadn't selected. I fixed this downgrading the version to 3.0.6.
**Second**, _it happens also on the version 3.0.9_; when I already have all the _Special Actions_ configured, I can't enable it all. As example, when I tried to enable the _Special Action_ "_Habilidad mob / Recipe inv_"(Screenshot), and I click on save, it doesn't enables, if I go back to settings, it shows unchecked again.

**To Reproduce**
1. Use the version 3.0.9 or the 3.0.6 of DS4Windows.
2. Set the _Special Actions_(I keybinded 10)
3. Try to check it all.
4. Try to use it all.

**Screenshots and Logs**
![image](https://user-images.githubusercontent.com/82276442/122606258-059b7500-d04f-11eb-8684-24c825cf2a04.png)
**Screenshot 1**: _I checked it all._

![image](https://user-images.githubusercontent.com/82276442/122606329-28c62480-d04f-11eb-982c-9a254b907182.png)
**Screenshot 2**: _After saving the changes, I saw that it wasn't working and went to settings again. To see that it was unchecked._

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: [e.g. Windows 10 Pro Build 21H1]
 - DS4Windows Version [3.0.6//3.0.9]

**Comment by JoakoLP** [comment]
I've just seen another bugs, like even if it shows checked, some doesn't work. And some changes I do don't get saved. I think I will try to use _Special Actions_ later

**Comment by gwin7ok** [comment]
In ver.3.0.6, if you change the name of the special action and save it, it will move to the last order (you can change the order using the specifications), and the check will be automatically removed. If you check it again and save it, it will work. Is this not relevant?

It is a bug of ver.3.0.7 or later that the edit screen of another special action opens when you try to edit a special action.
https://github.com/Ryochan7/DS4Windows/issues/2199#issue-912674829
https://github.com/Ryochan7/DS4Windows/issues/2219#issue-919733250

**Comment by JoakoLP** [comment]
Sorry for taking too much time to answer, but it worked! Thanks!
![image](https://user-images.githubusercontent.com/82276442/122703585-54503700-d228-11eb-8196-88c1084fdd07.png)

**Comment by JoakoLP** [comment]
Same version, 3.0.6
I haven't tested yet on 3.0.9, I guess it will be a little bit harder to find the wanted "Special Action" but it will work for sure.

**Comment by mika-n** [comment]
#2237 
probably related to these other bugs. Seem to work in the development version here with the latest fixes, so just wait for the next release or compile the development version and give it a test run
