### ISSUE TITLE
Emulated controller doesn't work

### ISSUE THREAD

**Issue by Bevan0** [Ryochan7/DS4Windows#2241]
**Describe the bug**
The emulated controller does not work. It plugs and shows as an Xbox 360 controller but non of the buttons do anything in Joy.cpl. This is with default settings and all "optional" drivers

**To Reproduce**
1. Plug in a controller and press Start
2. It doesn't work

**Expected behavior**
The emulated controller to work

**Screenshots and Logs**
If applicable, add screenshots to help explain your problem. Also, please add the most
log file (ds4windows_log.txt) from the Logs folder in your DS4Windows config folder.

**Desktop (please complete the following information):**
 - Controller Make and Model: SZMY-POWER PC Gamepad, advertised as a DS4 and shows in DS4Windows as "Gioteck VX4" (which based on the pictures, it isn't)
 - OS: Windows 10 Home 20H2
 - DS4Windows Version: 3.0.9

**Additional context**
The gamepad has worked before on this PC although it was an older version of Windows 10
When DS4Windows is closed, Steam and Joy.cpl see it perfectly functioning with all the buttons working

**Comment by Masamune3210** [comment]
This likely isnt enough information to really tell whats going on, please do what the template says and attach a log

**Comment by Bevan0** [comment]
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/6679636/ds4windows_log.txt)
This is the log file. As you can see, nothing that appears to be wrong causing this issue (why I didn't attach it earlier)

**Comment by Kanuan** [comment]
- Connect your controller and have DS4Windows running
- Send a screenshot of DS4Windows `controllers` tab
- Send a screenshot of DS4Windows `Output Slots` tab
- Press on your keyboard Win + X -> Select `Device Manager` -> On the top, select `view -> devices by connection` -> Send a screenshot (DO NOT expand anything)

**Comment by mika-n** [comment]
what do you see in the ControllerReadings tab page in DS4Windows profile editor? Any trigger key or LS/RS stick activity there? Send a screenshot of that page also.
