### ISSUE TITLE
Do I need HIDGuardian anymore for exclusive mode?

### ISSUE THREAD

**Issue by CorpusBava** [Ryochan7/DS4Windows#2242]
I noticed that with latest versions of DS4Windows, if I use the latest ViGEmBus driver (v1.17.333) with HIDGuardian and the "Hide DS4 Controller" option in DS4Windows ticked, it disables DS4Windows from recognizing my DS4 controller.  Is HIDGuadian even needed anymore or does DS4Windows still have issues with certain games not working correctly with DS4Windows due to the dual input issue?

**Comment by mika-n** [comment]
Yes and No.
No = No need to use HidGuardian
Yes = HidGuardian is replaced with HidHide tool and it does the same, but is newer and better and more reliable and easier to configure and maintain.

https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

**Comment by CorpusBava** [comment]
Great!  I downloaded the app, installed it, selected the Sony Wireless Controller that showed up in the devices pane once I turned my controller on with DS4Windows, and it then showed it as HID-Compliant Controller with the little red lock icon next to the tick (see image below).  And that's it, no further configuration, right?  Really nice.  I was having major trouble with certain games and programs with the dual input issue like Retroarch and used to use HIDGuardian to correct the problem.  Glad to see it's basically been updated.   Thanks for your help.

![Clipboard01](https://user-images.githubusercontent.com/38111068/122646819-2c10ed00-d0ef-11eb-8e9c-0fd590091fd4.jpg)

**Comment by Kanuan** [comment]
After installing HidHide you need to reboot your PC for it to start working.
Besides that, follow the [_Verifying if the controllers are hidden_ section](https://vigem.org/projects/HidHide/Simple-Setup-Guide/#verifying-if-the-controllers-are-hidden) of HidHide to confirm the controller is hidden (make sure to have DS4Windows Stopped or fully closed so you don't mistake a virtual controller with the real one when verifying).

Besides that, everything should work as expected. Be sure to mark this issue as __Closed__ later!

**Comment by CorpusBava** [comment]
> 
> 
> After installing HidHide you need to reboot your PC for it to start working.
> Besides that, follow the [_Verifying if the controllers are hidden_ section](https://vigem.org/projects/HidHide/Simple-Setup-Guide/#verifying-if-the-controllers-are-hidden) of HidHide to confirm the real controller is hidden (make sure to have DS4Windows Stopped or fully closed so you don't mistake a virtual controller with the real one when verifying).
> 
> Besides that, everything should work as expected. Be sure to mark this issue as **Closed** later!

I think Mika-N closed it for me ;)  I tested it using the info in the link you posted and no controllers show up so I suppose it works.  However, even with DS4Windows in Start mode with my controller on and emulated it still doesn't show up.  Is this normal?  The only micro-issue I noticed is that it now takes about twice as long for my controller to turn on with DS4Windows (about 6 seconds).  No biggie though.
