### ISSUE TITLE
Question: Can I turn off the light on NS Pro controller?

### ISSUE THREAD

**Issue by CarterLi** [Ryochan7/DS4Windows#2243]
![image](https://user-images.githubusercontent.com/6134068/122627899-27dfd200-d0e5-11eb-9499-fde9223db314.png)

I don't know if NS Pro is officially supported by DS4Windows, it works pretty well for me. The only issue is that after connected with DS4Windows, the light on the controller is turned on and I can't turn it off.

![image](https://user-images.githubusercontent.com/6134068/122628232-94f46700-d0e7-11eb-85dd-7baaaceb16b0.png)

Thing I have tried: modify configs in Profile->Lightbar; disconnect (both DS4Windows and Bluetooth). None of them works. The light keeps being on until the controller runs out of battery.

**Comment by Masamune3210** [comment]
Have you tried turning R G and B all the way down? Since its a fake controller there might not be much that can be done about it if it doesn't adhere to the expected protocol and commands of a actual ds4

**Comment by CarterLi** [comment]
> Have you tried turning R G and B all the way down?

Yes, I have. Changing configs in Profiles->Lightbar (including R/G/B) doesn't have any effect.

> Since its a fake controller there might not be much that can be done about it if it doesn't adhere to the expected protocol and commands of a actual ds4

But the light will be turned on only when it's connected to DS4Windows. Connecting bluetooth has no effect on the light

**Comment by CarterLi** [comment]
Just find this
![image](https://user-images.githubusercontent.com/6134068/122637529-bd00bc00-d121-11eb-82c2-ce18562d7436.png)

**Comment by Masamune3210** [comment]
Is the controller emulating a Switch Pro? I assumed it was trying to emulate a DS4, hence the comment. If its trying to be a Switch Pro controller then yeah that checkbox should work

**Comment by Ryochan7** [comment]
Not sure about third party Switch controllers but the **Enable Home LED** option works fine with the official Switch Pro controller. Not sure if there is a tooltip but that setting is only taken into account when you first connect the controller. If you disable the option, it will not take effect until you disconnect and then re-connect the controller.

**Comment by CarterLi** [comment]
> Not sure about third party Switch controllers but the **Enable Home LED** option works fine with the official Switch Pro controller. Not sure if there is a tooltip but that setting is only taken into account when you first connect the controller. If you disable the option, it will not take effect until you disconnect and then re-connect the controller.

Thanks.

BTW there is no tooltip
