### ISSUE TITLE
Special Actions time can't have non-integer number of seconds

### ISSUE THREAD

**Issue by artur-ag** [Ryochan7/DS4Windows#2244]
**Describe the bug**
The "Hold for X seconds" field on the Special Actions menu doesn't let you input a fractional number like `0.2`, it always rounds it to an integer. I think letting the user set any arbitrary value is better, at least with one decimal place.

**To Reproduce**
1. Go to Profiles
2. Press Edit
3. Go to Special Actions tab
4. Create or edit an action
5. Type in `0.5` or some other decimal number on the "Hold for X secs" up/down control
6. Press Save
7. The value will be rounded down to 0, or the relevant integer. The action will be triggered in this amount of rounded seconds, not the value that the user typed.

Note: If you edit the `Actions.xml` file and manually type the desired value in the `<Details>0.3</Details>` field, it works, and the action is triggered after the specified amount of decimal seconds. So the problem is just on the GUI.

**Expected behavior**
The value should stay `0.5` or what the user typed in. The action should be triggered in this amount of seconds.

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2
 - OS: Windows 10.0.19043.0
 - DS4Windows Version: 3.0.9

**Comment by mika-n** [comment]
Implemented, the next update should have this possibiilty (Hold for X secs using decimal values with the precision of 2 decimals, the default increment by 0.5 in the editor but user can type in any decimal value)
