### ISSUE TITLE
Controller does not show up anymore in DS4, nothing has changed. It worked the past year.

### ISSUE THREAD

**Issue by JayTheLordOfTheFishes** [Ryochan7/DS4Windows#2250]
**Describe the bug**
The controller does not show up in DS4 when plugged in.
Windows sees the controller in the Gamepad configurator and the Xinput Gamepad Tester shows that the controller works as well.

**To Reproduce**
1. Plugin Controller
2. nothing happens

**Expected behavior**
When i plug the controller in it should pop up in DS4.

**Screenshots and Logs**
06/22/2021 12:44:33: DS4Windows version 3.0.9
06/22/2021 12:44:33: DS4Windows Assembly Architecture: x64
06/22/2021 12:44:33: OS Version: Microsoft Windows NT 10.0.19042.0
06/22/2021 12:44:33: OS Product Name: Windows 10 Pro
06/22/2021 12:44:33: OS Release ID: 2009
06/22/2021 12:44:33: System Architecture: x64
06/22/2021 12:44:33: Running as User
06/22/2021 12:44:33: HidHide control device found
06/22/2021 12:44:33: DS4Windows not found in HidHide whitelist. Adding DS4Windows to list
06/22/2021 12:44:34: Starting...
06/22/2021 12:44:34: Using output KB+M handler: SendInput
06/22/2021 12:44:34: Connection to ViGEmBus 1.17.333.0 established
06/22/2021 12:44:34: Searching for controllers...
06/22/2021 12:44:34: Using Exclusive Mode

After "using exclusive mode" i plug in the controller and nothing happens.
NOTE: i dont know why its mentioning HidHide because i didnt install any extras except VigEmBus

**Desktop (please complete the following information):**
Edition	Windows 10 Pro
Version	20H2
Installiert am	‎07.‎03.‎2021
Betriebssystembuild	19042.1052
Leistung	Windows Feature Experience Pack 120.2212.2020.0
DS4 Version: 3.09

**Additional context**
The controller worked without a flaw with DS4 the past year.
I didnt change anything, and i have no clue why.

**Comment by mika-n** [comment]
I suspect something wrong with HidHide/HidHuardian side and DS4Windows app is no longer whitelisted in those tools hiding gamepad devices. 
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

Please read the linked page to make sure you understand the difference between physical and virtual gamepads, why the physical gamepad often need to be hidden from games and ALTERNATIVE ways to hide the physical gamepad. Uninstall HidGuardian in case you have installed it sometime in the past and install (re-install?) HidHide tool and configure it properly (ie. set DS4Windows app as whitelisted process to let see the physical gamepad, but other processes should not see the physical gamepad)

**Comment by Kanuan** [comment]
- Press `Win + X`
- On the appearing window select `Device Manager`
- On the top of the device manager, select `view -> Devices by connection`
-  Send a screenshot of the device manager with NOTHING expanded (the screenshot should show every category on the device manager with nothing expanded)

**Comment by JayTheLordOfTheFishes** [comment]
> 
> 
>     * Press `Win + X`
> 
>     * On the appearing window select `Device Manager`
> 
>     * On the top of the device manager, select `view -> Devices by connection`
> 
>     * Send a screenshot of the device manager with NOTHING expanded (the screenshot should show every category on the device manager with nothing expanded)

![Screenshot 2021-06-23 100627](https://user-images.githubusercontent.com/31579027/123060084-b5376500-d40a-11eb-9041-bc33631b4062.png)

**Comment by mika-n** [comment]
you seem to have both the ancient ScpVirtualBusDriver and the ViGem (Virtual Gamepad Emulation Bus) drivers installed. It is a recipe for disaster and is not supported. If/When you have ScpVBus installed then you are on your own.

I would recommend you to start from scratch. Uninstall ViGem, HidHide and ScpVBus drivers and then 
- Install ViGem driver and test DS4Windows using "Hide DS4 Controller" (=exclusive mode)
- If it works then great, but be aware that HideDS4Controller option easily breaks and reasons are beyond the control of DS4Windows app
- If the exclusive mode doesn't work then untick the option and install HidHide tool and setup it properly

https://vigem.org/projects/ScpToolkit/ScpToolkit-Removal-Guide/
https://vigem.org/projects/HidHide/Simple-Setup-Guide/
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

**Comment by JayTheLordOfTheFishes** [comment]
@mika-n 

i removed Vigem Bus and SCP with "ReVo" and uninstaller software that should remove everything.
After removing both i restarted my machine.

I installed DS4 windows, installed VigemBus with the Prompt that opens up.
I did not install anything else Optional.

And, no controller is showing.
Windows sees the controller.
DS4 does not.

![Screenshot 2021-06-24 115357](https://user-images.githubusercontent.com/31579027/123243134-0450c900-d4e3-11eb-9c69-bc0470ae2536.png)

LOG:

06/24/2021 11:54:32: DS4Windows version 3.0.10
06/24/2021 11:54:32: DS4Windows Assembly Architecture: x64
06/24/2021 11:54:32: OS Version: Microsoft Windows NT 10.0.19042.0
06/24/2021 11:54:32: OS Product Name: Windows 10 Pro
06/24/2021 11:54:32: OS Release ID: 2009
06/24/2021 11:54:32: System Architecture: x64
06/24/2021 11:54:33: Running as User
06/24/2021 11:54:34: Starting...
06/24/2021 11:54:34: Using output KB+M handler: SendInput
06/24/2021 11:54:34: Connection to ViGEmBus 1.17.333.0 established
06/24/2021 11:54:34: Searching for controllers...
06/24/2021 11:54:34: Using Exclusive Mode

again same results. See screenshot, the controller is connected.

**Comment by mika-n** [comment]
when the "Enable verbose log" is set then is there anything in the logfile when you disconnect the gamepad and then re-connect it?

Did you uninstall HidHide also because the earlier screenshot was showing HidHide?

**Comment by Ryochan7** [comment]
Might be better off starting by inspecting the device with HID Report Inspector. Decided not to bundle it with DS4Windows even with the 3.0 release once .NET 5 use became a requirement. It has been useful to me on several occasions including right now with some Steam Controller experiments.

https://github.com/Ryochan7/HidReportInspector/releases/download/v0.0.1/HidReportInspector_0.0.1_x64.7z

![HID Report Inspector Preview](https://user-images.githubusercontent.com/581968/103692037-cffd4680-4f5c-11eb-8e7c-ab3273d77bd1.png)

**Comment by mika-n** [comment]
closed because of inactivity, issue is assumed to be fixed
