### ISSUE TITLE
Terminator: Resistance

### ISSUE THREAD

**Issue by Leoxur** [Ryochan7/DS4Windows#2251]
**Describe the bug**
Controller works (except for "home button to open game bar") but in the game terminator doesn't respond to command

**To Reproduce**
1. Associate DS4 through bluetooth
2. Open DS4Windows
3. Go to "Option/Gamepad Test" and try (it works)
4. Open game Terminator resistance
5. Game does not responde to gamepad command

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2E)
 - OS: Microsto Windows NT 10.0.19043.0
 - Windows 10 Pro 2009 x64
 - DS4Windows Version [e.g. 3.0.10]
 - ViGEmBus 1.17.333.0

**Comment by Leoxur** [comment]
https://user-images.githubusercontent.com/9626769/122975681-e6288300-d393-11eb-87a3-1fb84235afc7.mp4

**Comment by Kanuan** [comment]
Accordingly to [Terminator: Resistance page on Pc Gaming Wiki](https://www.pcgamingwiki.com/wiki/Terminator:_Resistance#Input) this game has no support for DualShock 4 controller input. 

From your video, your profiler in DS4Windows is set for `DualShock 4 emulation`. You need to change your profile to use `Xbox emulation` in the profile's `Other` tab settings, as shown in the image below:

![image](https://user-images.githubusercontent.com/24910442/122976289-9386a100-d36a-11eb-8583-7d409b6814ab.png)

If changing this solves your issue do not forget to mark this issue yourself as __Closed__

**Comment by Leoxur** [comment]
Yes I tried also Xbox360 config, same issue

https://user-images.githubusercontent.com/9626769/122977396-a5316e00-d395-11eb-8887-726e181bc0fb.mp4

**Comment by Kanuan** [comment]
You edited profile `4`, but your controller on the `Controllers` tab is set to profile `Default`
As you can see on the Gamepad Tester on the end of the video, there are still 2 Wireless Controllers being show (your real controller and the virtual one created by DS4Windows), meaning the `Default` profile you are actually using probably is still set to DS4 emulation

**Comment by Leoxur** [comment]
Thank you very much, that was the issue. It's strange because even of i change the profile with right click on the icon on start's, It remain on "4" profile. I deleted it and set "default" modifying it to xbox360, now It works! Thank you again

**Comment by Leoxur** [comment]
Terminator Resistance does not support DS4, so the profile need to be setted on "xbox360" emulation
