### ISSUE TITLE
[Regression] Stick to mousewheel seem to be broken

### ISSUE THREAD

**Issue by nyakze** [Ryochan7/DS4Windows#2253]
**Describe the bug**
Mousewheel bind to right stick doesn't scroll anymore (scrolls for a moment and then stops, and for some reason it's reversed)

**To Reproduce**
Bind mousewheel up/down to right stick
Try to scroll something

**Expected behavior**
Scroll should happen normally

**Screenshots and Logs**
-

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2E)
 - OS: Windows 10 Pro 20H2 [19042.1055]
 - DS4Windows Version 3.0.10

**Additional context**
Works fine after rollback to 3.0.9

**Comment by Ryochan7** [comment]
Fixed in 3.0.11
