### ISSUE TITLE
Undesired dampening with Gyro: Output Mode: Mouse Joystick or possible bug

### ISSUE THREAD

**Issue by agostini01** [Ryochan7/DS4Windows#2257]
**Describe the bug**
I could not find a way to disable the dampening effect from Gyro when `Output Mode` is selected to `Mouse Joystick`

**To Reproduce**
1. Using a Dual Sense controller
2. Created a new profile
3. Click Gyro Tab and select `Output Mode` : `Mouse Joystick`
4. In game, if I move the controller from the center to a new position, the spaceship moves slightly on the correct direction, but then the displacement vector is dampened and the new position is now the new center, which stops the spaceship movement.
5. Assuming the output is a joystick axis value, the game has no settings to control this dampening.

Looking at the `Controller Readings` for the gyro. It looks like the input being used in `Mouse Joystick` mode is based on the `Gyro` readings (that reset/dampen to center after 0.5seconds) instead of the `Accel-X,Y,Z` readings that keep the displacement for a given controller position.

**Expected behavior**
I would like to have similar behavior to `Output Mode` : `Mouse`. If I keep the controller on the new position the simulated joystick values keep the displacement until I move the controller back to center.

Or perhaps to have a way to dramatically reduce the dampening effect. 

**Screenshots and Logs**

![image](https://user-images.githubusercontent.com/3741033/124345840-4fd13a00-dba9-11eb-9752-3b60aa6b6ded.png)

```
07/03/2021 00:14:43: DS4Windows version 3.0.10
07/03/2021 00:14:43: DS4Windows Assembly Architecture: x64
07/03/2021 00:14:43: OS Version: Microsoft Windows NT 10.0.19041.0
07/03/2021 00:14:43: OS Product Name: Windows 10 Pro
07/03/2021 00:14:43: OS Release ID: 2004
07/03/2021 00:14:43: System Architecture: x64
07/03/2021 00:14:43: Running as User
07/03/2021 00:14:44: Starting...
07/03/2021 00:14:44: Using output KB+M handler: SendInput
07/03/2021 00:14:44: Connection to ViGEmBus 1.17.333.0 established
07/03/2021 00:14:44: Searching for controllers...
07/03/2021 00:14:44: Using Shared Mode
07/03/2021 00:14:44: UDP server listening on address 127.0.0.1 port 26760
07/03/2021 00:14:51: Found Controller: <redacted> (DualSense)
07/03/2021 00:14:51: Plugging in virtual X360 Controller
07/03/2021 00:14:51: Associate X360 Controller in slot #1 for input DualSense controller #1
07/03/2021 00:28:05: Controller 1 is using Profile "Squadrons". Battery level is 25%
```

**Desktop:**
 - Controller Make and Model: Sony Dual Sense (CFI-ZCT1W)
 - OS: Windows 10 Pro Build 2004
 - DS4Windows Version 3.0.10

**Additional context**

I have been trying to get a better experience during flight games (specially Star Wars Squadrons - SWS). SWS does not seem to allow simultaneous Joystick + Mouse movements. If I move the mouse, the Joystick loses control. If I move the joystick the mouse displacement resets. For this reason I am looking into the Joystick + ` Mouse Joystick` options

**Comment by agostini01** [comment]
First, thank you for the great work. This application is a must and I really appreciate that you keep supporting it.

After inspecting the code, it appears that the values queried are in fact the `Gyro-Yaw,Pitch,Roll`, as observed on the implementation of this function: https://github.com/Ryochan7/DS4Windows/blob/a8f62d8c1ab720009f16aadaf178992de403f792/DS4Windows/DS4Control/Mouse.cs#L386

Is there a way to enable an option to switch between  `Accel-X,Y,Z` and `Gyro-Yaw,Pitch,Roll` for the `Output Mode : Mouse Joystick`? Or prevent the fast dampening from `Gyro-Yaw,Pitch,Roll`.

It is unclear to me why we would want these fast relative movement being dampened.

**Comment by agostini01** [comment]
I am not familiar with the codebase, but I am almost sure that the damping factor comes from the nature of the `Gyro-Yaw,Pitch,Roll` reading in `class SixAxis.gyroYawFull` member. If it is the case that the reading always "reset to center". Then, maybe the final values to update the `Mapping.gyroStickX[deviceNum]` position should read the previous position of the stick and add it to the new update with an alpha factor.

Code to be modified:

https://github.com/Ryochan7/DS4Windows/blob/a8f62d8c1ab720009f16aadaf178992de403f792/DS4Windows/DS4Control/Mouse.cs#L529

**Comment by agostini01** [comment]
After testing `Output Mode : Mouse Joystick` with different games, the behavior is somewhat inconsistent. For FPS games, it actually works remarkably well, moving the motion controller moves the aim and the range of the movement covers a lot of the screen. But a third person shooters (such as Control) had this problem of "resetting the aim", where the "gyro dampening" makes it hard (requires a lot of controller movement) to "cover" the screen area. If sensitivity is dramatically increased to compensate, then fine grain aiming with motion control is impossible.

Then comes the issue of the spaceship games, which I am having a hard time to find a suitable configuration such that, as I am shooting something, I can fine grain aim with the motion controls.

I am closing this issue, as now I realize that this is much more of a game problem than a problem with DS4Windows.

**Comment by Ryochan7** [comment]
Sounds like Gyro Mouse Joystick is working as intended. That output type is mainly meant for use in FPS games that do not like mixed input support so Gyro Mouse output cannot be used (Halo Master Chief Collection). Also, like with Steam's version, you will have to adjust the camera sensitivity in the game to increase the output range available.

There is no type of Gyro output mode that would attempt to use some form of IMU fusion to try to track the absolute controller position. There is no way to make a fake flight stick.
