### ISSUE TITLE
Mapping mouse wheel to sticks stops scrolling at midpoint

### ISSUE THREAD

**Issue by Yohoki** [Ryochan7/DS4Windows#2259]
**Describe the bug**
I think the new "outer binding" option has messed with mouse scrolling a bit. Binding mouse wheel  to sticks used to produce a smooth scroll that could be reduced or increased by tilting the stick more or less. It still somewhat does this, except now at the midpoint (128), it stops scrolling entirely and then past the midpoint it begins scrolling slowly again.

I think the issue is the outer binding option. If it is turned on, there would be two circles that can have different effects. I suspect that these two circles are still being used when no outer binding is set, but just mapped to the same key. Normally this wouldn't be an issue, except for mouse wheels, where the code needs to know how fast to scroll the wheel. Having the 2 zones simply resets the scroll to slow speed when entering the outer zone.

The outer zone would need to be removed entirely when not using outer bindings to avoid this issue.

**To Reproduce**
1. map mouse wheel to right stick. (probably left also works)
2. go to large website (youtube is infinite, it works well)
3. scroll down with right stick held at midpoint (-128).

**Expected behavior**
With no outer binging set, expected behavior is that mouse wheels have a linear increase in speed as the stick is pushed down.
With outer binding set, this is probably the expected behavior.

**Comment by Yohoki** [comment]
Just checked in Visual Studio. https://github.com/Ryochan7/DS4Windows/commit/e93e906b4f97cd45b9866395b66584ad37deb259 Does fix the issue.

**Comment by Ryochan7** [comment]
Getting to the point where I am forgetting how some methods work. Been starting to add more comments to the code.
