### ISSUE TITLE
[Bug] Right Stick doesn't have midpoint at Y

### ISSUE THREAD

**Issue by Renzo904** [Ryochan7/DS4Windows#2260]
**Describe the bug**
Using a DS4, when i try to emulate another DS4, the right stick doesn't have a midpoint at the vertical axis, if i go up a little bit it goes all the way up(A similar behaviour can be adquiered with the Anti-dead zone at 100%)

**To Reproduce**
1. Go to 'Edit' in the profile
2. Go to 'Other'
3. On 'Emulated Controller' select 'Dualshock 4'
4. Go to "Game Controller Settings" in control panel
5. Select the emulated Dualshock 4
6. The Z Rotation doesn't have midpoint

**Expected behavior**
The Z Rotation should go with the movement of the stick

**Screenshots and Logs**
Logs:
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/6759078/ds4windows_log.txt)
Screenshots:
-Control Panel of **Emulated** DS4:
![joystickbien](https://user-images.githubusercontent.com/63516530/124367675-efd1a680-dc2f-11eb-8152-54435975065a.gif)
-Contorl Panel of **Native** DS4(Without DS4Windows):
![Native DS4](https://user-images.githubusercontent.com/63516530/124367678-f3652d80-dc2f-11eb-8e55-2d2ad4505eb0.gif)
-Comparision of DS4Windows Readings and Control Panel Readings(More explanation in "Additional context"):
![ds4w   Control Panel](https://user-images.githubusercontent.com/63516530/124367701-21e30880-dc30-11eb-90f7-d85d545a912a.gif)
-Profile Settings of Right Stick:
![Settings](https://user-images.githubusercontent.com/63516530/124367712-2c9d9d80-dc30-11eb-9e8f-85feb824d294.png)

**Desktop:**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: Windows 10 Pro Build 21H1
 - DS4Windows Version: 3.0.11(Also tested with commit d48dd9d62fdce90b296916365f0472fd001d123e, the problem persists)

**Additional context**
-This only happens when i select DS4, when emulating a Xbox360 controller the right stick works as expected
-The DS4Windows Readings works as expected, but when playing doesn't

I'm open to share more information if it's needed

**Comment by Yohoki** [comment]
There were a few changes to the sticks in the last update, and he's already fixed some of the bugs with them. Check this version here that has some of these bugs fixed and see if it still happens.
https://github.com/Yohoki/DS4WindowsEx/releases/tag/v3.0.11.1

If this version fixes your issue, then either use it or switch back to 3.0.9 for the time being. If it still doesn't work, come back and let us know.

**Comment by Renzo904** [comment]
Thanks for the reply!! Unfortunately, none of the versions seems to work. In fact, I tested many versions of DS4Windows down to 1.7.6(First version with DS4 Emulation) and none of them worked. I'm starting to think that it doesn't have anything to do with DS4Windows.

**Comment by Ryochan7** [comment]
It works fine on my end with my main DS4 output profile.

**Comment by mika-n** [comment]
if DS4Windows would have such a "built-in" bug with LS/RS then I'm sure it would have been reported by zillions of people over the years. Maybe you should attach the profile file you use here as TXT attachment (drag-n-drop the profile file as .txt renamed file) or try to create a new empty profile in DS4Windows and give a try without tweaking any settings.

And when you use the gamepad in https://gamepad-tester.com/ web site WITHOUT DS4Windows running then how LS/RS behaves?
