### ISSUE TITLE
DS4Windows with Forza Horizon 4

### ISSUE THREAD

**Issue by kleelue** [Ryochan7/DS4Windows#2261]
Hey there, 
I'm using this to get the ps4 controller going for Forza Horizon 4 from the Windows Store. However, 3.0.10 works with the "Hide DS4 Controller"-Option enabled. 3.0.11 doesn't anymone and the option got removed, so I need to stay in 3.0.10 for it to work. Any workaround for me, to get the newer Version to work with Forza? I'm willing to test stuff out or send you logs if needed (:

Greetings, Luette

**Comment by jeek-midford** [comment]
Please install HidHide on your computer. It's better than "Hide DS4 controller".

**Comment by mika-n** [comment]
https://vigem.org/projects/HidHide/Simple-Setup-Guide/

use HidHide solution
