### ISSUE TITLE
GeForce NOW not detecting input

### ISSUE THREAD

**Issue by Hierro3000** [Ryochan7/DS4Windows#2263]
I can link my Dualsense with DS4WINDOWS but it doesn't work in the cloud gaming service NVIDIA GeForce NOW. It works fine with Stadia. I've tried switching on and off the "Hide DS4" option.
I can play without DS4WINDOWS but I'd really like to have rumble. Thanks

**Comment by mika-n** [comment]
GeForceNow with DS4Windows mapped gamepad seem to work here. Just tested it with Enlisted game on GeForce (free-to-play game on GeForceNow, so you can test it there also). This game for sure supports xbox gamepad, so DS4Windows profile using xbox360 output profile works.

If it still doesn't work then I suspect you have a "double controller issue" and you have failed to hide the original physical gamepad. HidHide is nowadays the recommended way to hide the physical gamepad from games and leaving just the virtual output gamepad device visible.
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues
https://vigem.org/projects/HidHide/Simple-Setup-Guide/
