### ISSUE TITLE
Apex Legends Xbox Only Issue

### ISSUE THREAD

**Issue by HDZEE** [Ryochan7/DS4Windows#2265]
Hi,

I have two profiles, one xbox and one playstation. Each one emulates their respective controllers. I can't for the life of me figure out how to get it to recognize the playstation one in Apex Legends. When I swipe to change between the two, sometimes the on screen icons will change to the plyastation icons and sometimes all the icons disappear so it goes back to keyboard and mouse. While in the playstation profile I can still use the touchpad as a mouse. However, nothing else works. The controller only works when in the xbox profile. I've tried HidHide and the older version of DS4W with the hide dualshock 4 option, but nothing works. I just wan to use my DS4 and Dualsense controllers with Apex Legends and use the proper onscreen icons (not the xbox ones). Any thoughts?

**Comment by Ryochan7** [comment]
Never played Apex Legends so I am mostly in the dark about this. PCGamingWiki claims the game has some form of DS4 support and should show PS button prompts. I don't know if it depends on whether you launch it from Steam or Origin.

https://www.pcgamingwiki.com/wiki/Apex_Legends

**Comment by HDZEE** [comment]
Yeah the game definitely has support for it so no issues there. I launch the game from steam but have all the steam controller settings off. I only let DS4W recognize my controllers. Any ideas?

**Comment by HDZEE** [comment]
By the way this also happens with TitanFall 2.
