### ISSUE TITLE
[TODO] Add some form of Action Set support

### ISSUE THREAD

**Issue by Ryochan7** [Ryochan7/DS4Windows#2266]
Really wanting to play some Mass Effect 1 and 2 (Classic) at some point. With those games, having some form of situational configs is pretty much required. I don't know if I have my old antimicro profiles that I used for those two games. I cannot remember how many Action Sets my old config used; I am wanting to think my old Mass Effect 2 config used at least 3 separate Action Sets.

**Comment by mirh** [comment]
I hope I'm not *that* guy, but what's wrong with ME1Controller and ME2Controller?

**Comment by Ryochan7** [comment]
I never tried the old Mass Effects mods that try to add Xbox 360 controller support to the game. I guess my main reason for not using it would be that I want to use the virtual mouse to control the camera. Not sure if mixed input would work well or at all with the mod enabled.

**Comment by mirh** [comment]
IIRC (at least for ME1) the mod breaks the keyboard input at least to some extent.. You get the proper controller interface though at least. 
On the other hand, there's another little [alternative tinkering](https://www.pcgamingwiki.com/wiki/Mass_Effect#Simultaneous_Mouse_and_joystick_support_for_Steam_Controller_users), which is what you'd recommend to steam controller users. You enable analog controls, and profit. 
...
But I'm a bit lost on what this "Action Set" idea would mean on top of this then. Using some button (say, one of the triggers) in order to change the meaning of all the other ones? Macros?

**Comment by Ryochan7** [comment]
This feature is still on the wishlist. My other experiments led me to create a better Action Set and Action Layer system than I had implemented previously; the Action Layer system is sort of a mess with how property carry over is handled but at least it is fast. It would be nice to try to get at least an Action Set feature in DS4Windows eventually. I have thought a little about how to try to change the BackingStore class but always stopped myself when I thought about the amount of refactoring that would be involved.

Steam Controller sample mapper project:
https://gitlab.com/ryochan7/steam-controller-test

Example Elder Scrolls 4: Oblivion profile utilizing Action Sets and Action Layers:
https://gitlab.com/ryochan7/steam-controller-test/-/raw/77621d795fb155da2e5f775f2b3bccf31bbbd439/example_files/Oblivion.json

**Comment by Ryochan7** [comment]
Have thought about this a couple of times since the previous post here but it is not worth attempting to implement in DS4Windows. The initial code structure not abiding by proper OOP (object oriented programming) would make the problem much harder than necessary. Also, I have plenty of other problems with other software projects and AFK tasks that need my attention much more. I would get almost no benefit from attempting to modify the source with some form of Action Set system.

I already have a superior system than what would be possible here. Being able to play through Oblivion again was nice.
