### ISSUE TITLE
Left Stick Y Axis Not Working At All

### ISSUE THREAD

**Issue by Sephius** [Ryochan7/DS4Windows#2268]
**Describe the bug**
No matter what button or Axis is bound to the Left Y Axis it will not report any value changing on the virtual Controller (Xbox For Windows), making impossible to use.

Tested on Dualshock4 and DualSense. The real input from those controllers works fine if bound to other buttons or axis. Left Y Axis will never report values changing at all. 

**To Reproduce**
1. Open DS4Windows.
2. Plug a DS4 or DualSense.
3. Open Control Panel.
4. Select "Controller (Xbox 360 for Windows)".
5. Click in "Properties".
6. On "Test" tab, move the Left Stick in multiple directions.

**Expected behavior**
The "Axis" visualization showing the cross moving up and down if Left Stick is moving up and down. 
Left Axis actually working on games, engines and other applications. 

**Screenshots and Logs**
https://user-images.githubusercontent.com/3932483/124566764-b9f01600-de19-11eb-9ab3-76d84524db74.mp4
(https://github.com/Ryochan7/DS4Windows/files/6768475/ds4windows_log_20210706.0.txt)

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DualSense (CFI-ZCT1W) / Dualshock CUH-ZCT2U
 - OS: Windows 10 Pro 20H2 19042.1052
 - DS4Windows Version 3.0.11

**Additional context**
It seams to be a problem in reporting the input since all physical inputs actually works if bound to other buttons axis.

**Comment by mika-n** [comment]
check LS/RS/L2/L1 (whatever analog axis) deadzone value.
Post a screenshot from ControllerReadings tab page in profile editor (the read area within LS/RS/L2/R2/gyro is the size of deadzone. If it is accidentally set to 100% then that axis doesn't output anything to a virtual ViGem gamepad interface)

**Comment by Sephius** [comment]
No value was modified from default. Deadzone settings seams normal. Also on ControllerReadings input seams to work fine. Problem happen only on the interface itself.

<img width="596" alt="Screenshot 2021-07-06 080406" src="https://user-images.githubusercontent.com/3932483/124590077-1f033600-de31-11eb-8d77-0da7e32b39fc.png">

https://user-images.githubusercontent.com/3932483/124590418-7f927300-de31-11eb-9aff-4505b214881e.mp4

**Comment by Sephius** [comment]
Note that to reproduce the problem, there is no need to actual use left stick on the game pad. Bind any button to Left Axis Y will also not work. As shown below:
![image](https://user-images.githubusercontent.com/3932483/124590687-ced8a380-de31-11eb-9b3c-dbb523ebc39a.png)

https://user-images.githubusercontent.com/3932483/124590894-09424080-de32-11eb-850d-9613fdd7ddb2.mp4

**Comment by mika-n** [comment]
LS stick movement works here.
Also, mapped X button to LS Y+ (and tested LS Y-) analog axis and worked great.

What do you see in JOY.CPL (run this cmd) when dS4Windows is running and the gamepad is connected? Do you see one or two gamepad devices? If you see two devices then you have failed to hide the original physical gamepad. This "double controller issue" may have nasty side effects when input is coming through two devices at the same time. Nowadays HidHide is the recommended way to solve double-controller issue.

https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues
https://vigem.org/projects/HidHide/Simple-Setup-Guide/

**Comment by Sephius** [comment]
Creating new profile solved the problem. Probably some conflict in the config? I used DS4Windows for years. Maybe it was some settings from older version.

That 2.0 scale on vertical scale was not the problem, cause i remember changed that in order to try to fix the problem. Latter i change the settings back but forgot to set that one. 

Thanks for the support.

**Comment by mika-n** [comment]
there has been few cases where some old option has caused issues/conflicts in the newer version of DS4Windows (or combination of values here and there). DS4Windows app does try to keep profile file logic backward compatible and in few cases upgrades/modifies values on the fly to make those compatible with the new version, but there are always some corner case possibilities.
