### ISSUE TITLE
.Net 5.0.7 not supported?

### ISSUE THREAD

**Issue by JupiterSky11** [Ryochan7/DS4Windows#2269]
I very much have it installed, but when I try running the DS4Windows.exe it asks for the 5.0.0 .Net version.
Do I have to downgrade my .Net install?  Or is this something else?

**Comment by Kanuan** [comment]
You need the [**Desktop** Runtime](https://dotnet.microsoft.com/download/dotnet/5.0/runtime)

**Comment by JupiterSky11** [comment]
Thank you, kind of a silly mistake on my end.  I'm getting a seemingly unrelated crash now, but I'll work it out.

**Comment by mika-n** [comment]
closed. .Net Core 5.x for DESKTOP 64bit x64 version is required for DS4Windows 64bit x64 app version (nowadays probably 99.9999% of PCs are using 64bit Windows OS, so x64=64bit version is the way to go. Forget x86=32bit version).
