### ISSUE TITLE
Can't connect DS4 and DualSense at the same time

### ISSUE THREAD

**Issue by MaxSoneback** [Ryochan7/DS4Windows#2270]
**Describe the bug**
Whenever I try to connect any number of DS4 controllers + a DualSense controller, all the DS4 controllers disconnects. I can have 4 DS4-controllers connected without problems, however adding a DualSense controller to the mix, even when using just 1 DS4 and 1 DualSense controller, the issue arises.

**To Reproduce**
1. Connect any number of DS4 controllers.
2. Connect the DualSense controller.

OR

1.  Connect the DualSense controller.
2. Try to connect a DS4 controller

**Desktop (please complete the following information):**
 - DS4 controllers tested: DS4 V.1 and V.2
 - OS: Windows 10 Windows 10 Home 20H2
 - DS4Windows 3.0.11
 - Dell XPS 15 (9500) 

**Additional context**
I have tried unchecking "Enable Output data to DS4" on all controllers. The following error log is produced:

`
07/06/2021 13:40:01: Starting...
07/06/2021 13:40:01: Using output KB+M handler: SendInput
07/06/2021 13:40:01: Connection to ViGEmBus 1.17.333.0 established
07/06/2021 13:40:01: Searching for controllers...
07/06/2021 13:40:01: Using Shared Mode
07/06/2021 13:40:05: The gamepad DS4 v.2 (BT) uses custom feature set (MonitorAudio)
07/06/2021 13:40:05: Found Controller: 4C:B9:9B:3E:3E:40 (BT) (DS4 v.2)
07/06/2021 13:40:05: Plugging in virtual X360 Controller
07/06/2021 13:40:05: Associate X360 Controller in slot #3 for input DS4 v.2 controller #1
07/06/2021 13:40:05: Output data to DS4 disabled. Lightbar and rumble events are not written to DS4 gamepad. If the gamepad is connected over BT then IdleDisconnect option is recommended to let DS4Windows to close the connection after long period of idling.
07/06/2021 13:40:05: Controller 1 is using Profile "Blue". Battery level is 100%
07/06/2021 13:40:13: Found Controller: 1C:66:6D:9F:9D:09 (BT) (DS4 v.1)
07/06/2021 13:40:13: Associate DS4 Controller in permanent slot #1 for input DS4 v.1 controller #2
07/06/2021 13:40:13: Output data to DS4 disabled. Lightbar and rumble events are not written to DS4 gamepad. If the gamepad is connected over BT then IdleDisconnect option is recommended to let DS4Windows to close the connection after long period of idling.
07/06/2021 13:40:13: Controller 2 is using Profile "White". Battery level is 100%
07/06/2021 13:41:57: 1C:66:6D:9F:9D:09 disconnected due to read failure: 997
07/06/2021 13:41:57: Disassociate DS4 Controller from slot #1 for input DS4 v.1 controller #2
07/06/2021 13:41:57: Unplugging virtual DS4 Controller
07/06/2021 13:41:57: Controller 2 was removed or lost connection
07/06/2021 13:42:57: 4C:B9:9B:3E:3E:40 disconnected due to read failure: 997
07/06/2021 13:42:57: Disassociate X360 Controller from slot #3 for input DS4 v.2 controller #1
07/06/2021 13:42:57: Unplugging virtual X360 Controller
07/06/2021 13:42:57: Controller 1 was removed or lost connection
`
EDIT:
Added information about which laptop I use.

**Comment by Masamune3210** [comment]
I almost guarantee it's more of a issue with your Bluetooth chipset or adapter not being able to handle the amount of data, as I've connected my v2 and DualSense at the same time many different times without issue

**Comment by MaxSoneback** [comment]
> I almost guarantee it's more of a issue with your Bluetooth chipset or adapter not being able to handle the amount of data, as I've connected my v2 and DualSense at the same time many different times without issue

Have you done any special configurations for this to work? I am using the built-in bluetooth in my Dell XPS 15 9500, and while I do admit that I don't know much about technical details regarding bluetooth, it does feel a bit... weird that a laptop of that calibre would have trouble handling 2 controllers at the same time. Especially when it works without any issues when using up to four DS4 controllers.

**Comment by Yohoki** [comment]
Since you're on a laptop, I'm going to assume you're using the built-in bluetooth adapter. My wife's laptop is also an XPS and I just recently added bluetooth to it. So, here's some surprising info you might not realize.

The Bluetooth modules on many laptops are actually using the Wi-Fi module, since they use the same antenna. So, if you are using a Wi-Fi card for bluetooth, it has to share the bandwidth and everything. 

For that particular laptop, I see two wi-fi card options, and a few people are reporting that they have Bluetooth issues when using things as simple as a mouse attached to it. It seems to prioritize WiFi usage over BT usage if the two are fighting eachother. I don't know if that's the issue you're running into, but you could try disabling WiFi and try connecting both controllers to see if that fixes the issue. If it does, a simple upgrade or bluetooth dongle might be an easy fix.

Here's some people talking specifically about the two cards that might be in your laptop. :)
https://www.reddit.com/r/Dell/comments/ihae8h/ax_500_vs_ax1650_wifi_card_in_xps/

**Comment by MaxSoneback** [comment]
> Since you're on a laptop, I'm going to assume you're using the built-in bluetooth adapter. My wife's laptop is also an XPS and I just recently added bluetooth to it. So, here's some surprising info you might not realize.
> 
> The Bluetooth modules on many laptops are actually using the Wi-Fi module, since they use the same antenna. So, if you are using a Wi-Fi card for bluetooth, it has to share the bandwidth and everything.
> 
> For that particular laptop, I see two wi-fi card options, and a few people are reporting that they have Bluetooth issues when using things as simple as a mouse attached to it. It seems to prioritize WiFi usage over BT usage if the two are fighting eachother. I don't know if that's the issue you're running into, but you could try disabling WiFi and try connecting both controllers to see if that fixes the issue. If it does, a simple upgrade or bluetooth dongle might be an easy fix.
> 
> Here's some people talking specifically about the two cards that might be in your laptop. :)
> https://www.reddit.com/r/Dell/comments/ihae8h/ax_500_vs_ax1650_wifi_card_in_xps/

Thank you for this very insightful comment, I'll make sure to look into it! On a different note, I have read somewhere that some people succeeded with pairing both DS4 and DualSense controllers by unchecking the "Enable Output data to DS4", do you know if this is a requirement or if those people are outliers, so to speak? It would be such a shame to lose the rumble function on 3 out of 4 of my controllers.

**Comment by MaxSoneback** [comment]
> Thank you for this very insightful comment, I'll make sure to look into it! On a different note, I have read somewhere that some people succeeded with pairing both DS4 and DualSense controllers by unchecking the "Enable Output data to DS4", do you know if this is a requirement or if those people are outliers, so to speak? It would be such a shame to lose the rumble function on 3 out of 4 of my controllers.

I tried turning off WiFi but no luck there. I also tried turning ds4windows off and used steam inbuilt controller support, which seems to be working just fine (for now) with all 4 controllers even with the wifi turned on. I'd rather not use Steam controller Support since I find it incredibly unreliable and it has historically given me a lot of headache, but I guess I'll have to settle with it for now..

**Comment by Yohoki** [comment]
> Thank you for this very insightful comment, I'll make sure to look into it! On a different note, I have read somewhere that some people succeeded with pairing both DS4 and DualSense controllers by unchecking the "Enable Output data to DS4", do you know if this is a requirement or if those people are outliers, so to speak? It would be such a shame to lose the rumble function on 3 out of 4 of my controllers.
If the issue you're running into IS a bandwidth issue, then disabling the output data should also help.

I don't use the steam controller support at all, though. So, I can't really say for certain why that would work and not D4W. That seems like something one of the contributors might be able to shine some light on.
