### ISSUE TITLE
Outer Bind Analog stick "Invert" not working.

### ISSUE THREAD

**Issue by islbro** [Ryochan7/DS4Windows#2271]
**Describe the bug**
The analog stick outer bind "Invert" option (under Left Stick Controls > Outer Btn Dead) does not function at all. 

**To Reproduce**
1. Go to LS (left stick)! Output mode: Controls and Dead Zone type: Radial
2. Click on 'Outer Bind' and set it to any keyboard/controller button.
3. Scroll down to 'Outer Btn Dead' and set to .75
4. Tick and enable the "Invert" box

**Expected behavior**
It works perfectly without the Invert Button ticked. However, when it is ticked, the outer bind (when assigned) is supposed to fire before reaching a certain threshold. The action then releases once the threshold has been exceeded. 

**Screenshots and Logs**
![ds4 bug 2](https://user-images.githubusercontent.com/85831473/124640277-30f9ce80-de5b-11eb-9a69-67a3a7de205f.jpg)

**Desktop:**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 -  Windows 10 Pro Build 21H1
 - DS4Windows Version 3.0.11

**Additional context**

**Comment by Ryochan7** [comment]
You have no dead zone on L2.

This was one of my test cases so it works for me. I had to compare the output from the test to how Steam Input would handle the situation when mapping to an analog output. Testing showed the Steam Input will treat the Outer Ring binding as a normal button (no analog) and will output the max value while the binding is active. For now, the Outer binding in DS4Windows is treated as a virtual trigger so the output will change depending on the position in that Outer Ring. When Invert is used, LT will start out max and then gradually go to 0 as the threshold is reached.

**Comment by islbro** [comment]
So it works for you? I would love to replicate your success. For me, it still doesn't function correctly even when the outer bind is set to a keyboard button or non-analog controller button. I fiddled around with the dead zones and still no luck. I've upgraded to the latest version as well.

**Comment by mika-n** [comment]
@islbro maybe you should post the profile you are using?

**Comment by Ryochan7** [comment]
Now it does not work on my end. Weird. I will look into it.
