### ISSUE TITLE
Stick off center with Mayflash Magic-NS

### ISSUE THREAD

**Issue by famus484** [Ryochan7/DS4Windows#2272]
I am trying to use DS4Windows with DS4 wirelessly connected to the Mayflash Magic-NS in Switch pro mode (purple). The reason is that I also use the controller on my Switch, and it is much, much more convenient to just plug/unplug to usb stick and not have to re-pair everytime. Moreover, the connection to the magic-NS is very stable (unlike Windows, although not related to DS4Windows).

The reason it relates to DS4Windows is that I want to use the gyro controls, hence Switch pro mode. The Magic-NS is correctly detected as a switch pro controller, and all buttons work just as they should (except the touchpad, but not a problem). Even the gyro itself works quite well (a bit off-axis in the game I tried, but that would be another issue, and not necessarily of DS4Windows). 

The issue is that both sticks are off-center, with rest position appearing in the lower-left. They work normaly in a direct connection with DS4Windows, and they work normally when Magic NS is used in xinput mode (where I can't use the gyros). 

A possible solution would be to add the option to calibrate/recenter the sticks. Another could be to change center reference per output file. To help, I could also provide data that shows how the MagicNS sticks are interpreted by DS4Windows. I feel that DS4Windows is very, very close to working well with the MagicNS.

**Comment by famus484** [comment]
Btw deadzone wouldn't work. What happens is that even when pushing the joystick to the far right, the input does not get past center, same for pushing up.

**Comment by famus484** [comment]
So after a little more testing on "Controller Readings", I get some interesting resuls (on the left joystick, similar results with the right).

The rest position on the x axis is  63=2^6-1, while it should be about 127=2^7-1. the position on the most left is 0, as it should be, and the far right is 127 when it should be 255.
For the y-axis, the position is 191=2^8-2^6-1=2^7+2^6-1, while it should be, again, 127. The upper-most position is 127 (instead of 0), and the lower-most is 255 (as it should be).

With that information, my intuition tells me that all the readings are somewhere right bit-shifted (divided by 2). A quick patch would be to left bit-shift results along the line.

If I'm wrong and that has nothing to do with bitshifts, then a solution would be to to normalise the ouput the formulas:

LX= 2*LX;
LY= 255-2*(255-LY)

Another, more general way to do it would be to be able to set the center, min and max values for each axis of each sticks in the settings, and let the code normalise the results.

**Comment by famus484** [comment]
By the way, I don't have a switch pro controller to test, but doesn't it cause the same issues when plugged wired? I'm pretty certain the Nintendo has never written any code to allow third party controllers to work properly when they fake being switch pros, so I wonder where does the thing came from...

**Comment by Ryochan7** [comment]
DS4Windows, along with BetterJoy, pulls the stick calibration data given by the controller. That data is used to determine the stick axis range used for converting to the mapper DS4 axis range. You would have to run DS4Windows in the Visual Studio debugger to see what stick calibration data is being given by the Magic-NS.
