### ISSUE TITLE
All macros broken after FakerInput

### ISSUE THREAD

**Issue by BitGrub** [Ryochan7/DS4Windows#2273]
**Describe the bug**
3.0.12 made all my KB+M macros stop working completely, AND for some bizarre reason I think is somehow related, mapping the "Volume+" function to a button/analog/trigger opens some Microsoft Office help page instead of increasing the volume.

Also I'm using a DS4 v2 controller

**To Reproduce**
1. Update to DS4Windows 3.0.12 from 3.0.11 or below

**Expected behavior**
Keyboard shortcuts like Ctrl+Tab, or Ctrl+Shift+Tab, or Win+Tab, or Ctrl+Win+O, should work, but don't

**Additional context**
Thank you for bringing back the Hide DS4 option. That checkmark really means a lot to me (for sentimental reasons)
[yes, that is a joke, but the issue I'm having isn't]

**Comment by BitGrub** [comment]
Going back to an older version fixed the Volume+ button, but the macros remain busted

**Comment by BitGrub** [comment]
Nevermind, I'm a fool, the issue was with FakerInput

**Comment by Ryochan7** [comment]
The mapping was wrong again.

**Comment by apoklyps3** [comment]
is there any fix for this?
remove fakerinput???

**Comment by FrostyWolf** [comment]
I am also not able to get Marcos to work.  Trying to just get Home+J working and getting nothing.
