### ISSUE TITLE
F13 to F24 doesn't work since 3.0.7

### ISSUE THREAD

**Issue by FakeMichau** [Ryochan7/DS4Windows#2279]
Keys from F13 to F24 aren't sent with the newer versions.
Other keys like F12 work just fine. I understand that those keys aren't physically on most keyboards but they are very useful then it come to macros and special functions. 

1. Make a macro that uses one of those keys (I use a logitech mouse to press that button but I've seen that a config file can be modified so that it works without needing additional software - bind F12 and just add an offset to it)
2. Assign to a key or an action
3. Test it and it doesn't work

Running Windows 11 22000.51
DS4 v2
Happen on every version since 3.0.7, 
3.0.6 works just fine
FakerInput is installed

**Comment by Ryochan7** [comment]
There is no supported mapping for F13 to F24 in the FakerInput mapping class. The driver supports it but the wrapper DLL does not. Never would have had a reason to use those keys so support does not exist.

**Comment by FakeMichau** [comment]
If it isn't complicated, support would be much appreciated. Like I said, it's really useful when using all sorts of macros.

**Comment by FakeMichau** [comment]
It doesn't seem to work. Function PerformKeyPress inside the fakeinputhandler reports the keydown but nothing happens.
If I modify the wrapper so that all F keys are grouped together (and therefore move all the other keys by an offset of 0x0C) it thinks it's F24 with a value of 0x51 but DownArrow is triggered instead as it originally had the value of 0x51. 
I've tried to find why it presses the original keys but that's kinda beyond me.
