### ISSUE TITLE
For General Questions, Please Use 'Discussions' Section

### ISSUE THREAD

**Issue by Ryochan7** [Ryochan7/DS4Windows#2281]
A Discussions forum section has been opened for this repository. For general program usage questions or to brainstorm on some ideas, it would probably be better to post in that section going forward. That section should be more open to community involvement than the current 'Issues' section would be.

**Comment by xabybalck** [comment]
i download and is says that the 
vigembus is not installed

try to install ps5 controller

**Comment by IDAZIZ** [comment]
ds4w won't detect my controller anymore after updating

reinstalled all the drivers and got the latest ds4w version, tried wireless and wired tried different usb ports for wired and got another ds4 controller to test with but still not working.

here is the log file:
[log.txt](https://github.com/Ryochan7/DS4Windows/files/6835971/log.txt)

i tried using inputmapper which emulates the ds4 controller to an xbox360 controller and it works.


thank you Ryo for the continuous updates cheers.

**Comment by crazydownload** [comment]
will there be support for virtual dualsense so that you can play through any bluetooth dongle via remote play? Or is it not possible with dualsense?

**Comment by Ryusennin** [comment]
Did you read the topic title?

https://github.com/Ryochan7/DS4Windows/discussions

**Comment by crazydownload** [comment]
I just do not know where to write and this question is why I wrote here

**Comment by mar0000000** [comment]
DualSense is not detected on latest version of ds4windows. Do I need to update controller firmware? Cause I can't I don't have access to a ps5. Thanks.
