### ISSUE TITLE
when i download it it says .exe at the end and all the tutorials dont

### ISSUE THREAD

**Issue by Bugsyboi** [Ryochan7/DS4Windows#2284]
so im tryna download ds4 and everytime i download the file
it says  ds4windows.exe or ds4updater.exe instead of ds4windows and ds4updater , also when i open them it says i need .NET and when i download .NET it still doesnt work. advice?

**Comment by mika-n** [comment]
if you have 64bit Windows (most likely you do have) then make sure you download x64 version of DS4Windows app and .NET Core 5.x for DESKTOP versions.
