### ISSUE TITLE
Scroll Wheel Reset

### ISSUE THREAD

**Issue by Dallo43** [Ryochan7/DS4Windows#2288]
I use DS4 when I play fortnite. I binded my scroll wheel reset to my controller. On the latest update, it got very slow. Not sure why.

**Comment by Ryochan7** [comment]
The scroll speed bound to a button was decreased by half speed in version 3.0.12. I felt the old default was too fast to get exactly one tick reliably which would really impact weapon switching. My test case was Doom 3 BFG so maybe not such a good test.

https://github.com/Ryochan7/DS4Windows/commit/740cc7ec262fe21573fc0d91ad4ffdd96ea9247e

**Comment by Dallo43** [comment]
It really wasn’t that fast it was very fair against mouse and keyboard players lol I wish you guys wouldn’t change it back 😢

**Comment by Dallo43** [comment]
Do you guys think you will change it back ? If not is there a way I can get the old version back I’m going crazy lol.

**Comment by Yohoki** [comment]
If you need the old version back, 3.0.11 or 3.0.9 should be the version you need. :)

3.0.9 was before a few changes to mousewheel were implemented.
3.0.11 was after most changes, but before the delay was added.
3.0.10 has some bugs, so I would avoid it.

**Comment by Dallo43** [comment]
Do I have to delete the current version I have ?

**Comment by Yohoki** [comment]
either delete, or copy files over and just overwrite. It shouldn't matter there, I don't think. Or, you can have 2 versions of d4w in separate folders. I've done that a few times. You just can't use both at once is all.

Looks like Ryochan's also tweaked the sensitivity a bit in the next version as well.

It's kind of a hard thing to get just right, so it might take a few versions to get it where majority are happy with it. :P

**Comment by mika-n** [comment]
or maybe there should be a slider to let users to adjust the sensitivity per profile?

**Comment by Ryochan7** [comment]
Mostly out of lack of motivation. It was planned at one point.

From TODO.md:
> * Add Button Wheel sensitivity setting of some kind. (Forget it. Just increase the current time delta used)

https://github.com/Ryochan7/DS4Windows/blob/jay/TODO.md

**Comment by Dallo43** [comment]
All good. Finally got an old version to work I kept getting an error code trying to extract the files. I just won’t ever update it.

**Comment by mika-n** [comment]
jep, it is not "cheap" trying to find a good place from GUI for all sort of new options. Sometimes it is a pain to figure out the best place. Half way solution would be to use profile file option WITHOUT gui option (or to use grid list as a "raw" list of options) and then people who really really want to tweak the setting could open the profile file in a Notepad and tweak the default option.
