### ISSUE TITLE
Microsoft says its unsafe

### ISSUE THREAD

**Issue by SuperHurley** [Ryochan7/DS4Windows#2289]
**Describe the bug**
Windows pops up the Windows protected you pc popup

**To Reproduce**
1. Go to 'DS4Windows' 
2. Click on 'DS4.exe'
3. See error

**Expected behavior**
Runs and windows does not interfere

**Comment by Masamune3210** [comment]
not a issue with DS4Windows, false positive

**Comment by Ryochan7** [comment]
I don't have $500+ per year for an EV certificate to keep Microsoft from displaying that SmartScreen message about an unknown publisher. It is somewhat random if the message pops up anyway with the current OV certificate.

https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-overview

Relevant text:
> Microsoft Defender SmartScreen determines whether a downloaded app or app installer is potentially malicious by:
> ...
> Checking downloaded files against a list of files that are well known and downloaded by many Windows users. If the file isn't on that list, Microsoft Defender SmartScreen shows a warning, advising caution.
