### ISSUE TITLE
How do we install this?

### ISSUE THREAD

**Issue by iiPostMaster** [Ryochan7/DS4Windows#229]
I'm looking at the files I've just downloaded from the jay branch and I have no clue how to compile them. I don't think it's possible to run the program from what we get there without some external software, so give me instructions, boss.

**Comment by Ryochan7** [comment]
The only major extra requirements for building the project should be Visual Studio 2017 and the Windows Software Development Kit. There is one external Nuget package (Task Scheduler) that the project depends on but Visual Studio will take care of downloading and installing the required package.

https://developer.microsoft.com/en-US/windows/downloads/windows-10-sdk

**Comment by iiPostMaster** [comment]
Okay, but once I have everything installed, how do I package it?

**Comment by Ryochan7** [comment]
After building the solution in Visual Studio, you would have to copy over the relevant files manually and put them in a zip file. There is no post-build command in the project to perform that task. The only post-build command that is available is to build the localization assemblies and copy them to a Lang folder. If you want Visual Studio to perform that extra step, go to Project > Properties > Build Events, find the **Post-build event command line** textbox and change the line `GOTO END` to `::GOTO END` to comment out the skip step.

**Comment by iiPostMaster** [comment]
I have no idea what any of that means. ;-;

**Comment by czukowski** [comment]
@iiPostMaster are you looking to develop or make some changes to DS4Windows, or just play some games with it?

**Comment by iiPostMaster** [comment]
@czukowski just play some games with it

**Comment by Couls** [comment]
just click clone or download choose download zip and extract somewhere then use the exe

**Comment by Couls** [comment]
https://github.com/Ryochan7/DS4Windows/releases

**Comment by czukowski** [comment]
@iiPostMaster then you can just see the link above and download the latest pre-compiled release.

**Comment by Ryochan7** [comment]
@iiPostMaster The source code is only needed if you want to edit and compile the program yourself. The compiled binary builds are in the Releases section.

https://github.com/Ryochan7/DS4Windows/releases

Latest release (1.4.112):
https://github.com/Ryochan7/DS4Windows/releases/download/v1.4.112/DS4Windows_1.4.112_x64.zip
