### ISSUE TITLE
DualSense vibration not working in 3.0.13

### ISSUE THREAD

**Issue by balthamossa2b** [Ryochan7/DS4Windows#2291]
**Describe the bug**
Vibration in DualSense stopped working on 3.0.13. I rolled back to 3.0.11 and it works fine again.

**To Reproduce**
Use DualSense, and test vibration in Edit Profile.

**Expected behavior**
The controller should vibrate heavy and light in test vibration (and in games).

**Screenshots and Logs**

**Desktop (please complete the following information):**
 - Controller Make and Model: Dual Sense
 - OS: Win10 build 19041
 - DS4Windows Version 3.0.13

**Additional context**

**Comment by mika-n** [comment]
#2275
