### ISSUE TITLE
Infinite rumble on Xinput with DS4

### ISSUE THREAD

**Issue by jbjohnaici** [Ryochan7/DS4Windows#2292]
**Describe the bug**
DS4 infinite rumble with XInput mode. 

**To Reproduce**
a good way I found to reproduce the bug is with the new D&D: Dark Alliance. Just install the game (it's in the PC game pass, if you have it) and create a character (they're original game characters, so they're ready to go)

1. Go to training dummies (located on the left side of the map - according your initial position after select "play")
2. I use the character named Cattie-brie. I execute the basic combo (just press X or RB repeatedly or/and just press the buttons one time.

**Expected behavior**
I just wish the rumble didn't get infinite

**Screenshots and Logs**
I can't get the rumble logs. If you have any way to get it, I could provide this information.

**Desktop (please complete the following information):**
 - Controller Make and Model: DS4 v.2
 - OS: Windows 10 Pro Build 20H2
 - DS4Windows Version 3.0.13

**Additional context**
I tested in Steam and other softwares they use the VIGem drivers (InputMapper and Parsec). The rumble is perfectly, I did a lot of research and saw some of your conversations with the person responsible for VIGem. I know this is a frequent problem on the emulated DS4 as it also needs the lightbar bits, but it's strange that it also happens with the emulated Xinput. If possible, taking advantage of the opportunity, a solution for the emulated DS4 could be litgbar commands turned off?

**Comment by jbjohnaici** [comment]
I updated my .NET Framework Runtime to 5.x

I thought I had it installed, but I probably only had 4.x

I tested it here and performed over 1200 hits on the training dummy. Vibrating almost every hit. There was no infinite rumble.

I don't know much about programming, but is there any chance the .net framework could influence this?

**Comment by Ryochan7** [comment]
It would probably depend on which version of DS4Windows you were running previously. The main factor would likely be the Nefarius.ViGEm.Client.dll library. Various experiments have happened in the past and some releases of DS4Windows made around the release of ViGEmBus 1.17.333.0 used vanilla versions of the ViGEm client library. Notifications queues were added back in after infinite rumble issues started to resurface.

Other software probably are AnyCPU apps which tend to run much slower and probably with extra buffering happening. Native CPU targets are used in DS4Windows and related libraries as processing speed and reducing latency are top priorities.

**Comment by jbjohnaici** [comment]
@Ryochan7 , thanks for the reply.

I ever install the lastest update. I even tried to do some downgrades to see if the problem solved. I will stay tuned and test more the current state of my DS4Windows to see if the problem persists.

**Comment by mika-n** [comment]
closed as inactive
