### ISSUE TITLE
Controller disconects almost instantly

### ISSUE THREAD

**Issue by MrYourself** [Ryochan7/DS4Windows#2299]
**Describe the bug**
So I'm trying to use the Razer Raiju on my PC via Bluetooth and DS4. But after it connects the latency is over 50ms and then disconnects. I've tried the HidHide Driver and the Faker Driver. When I'm using a usb cable it all works perfectly fine.

**Expected behavior**
It should stay connected

 Controller is a Razer Raiju. RZ06-0261
Windows 10 Pro 21H1 19043.1083
 - DS4Windows Version 3.0.13

**Comment by FakeMichau** [comment]
It looks like you are getting a bad signal. Try putting the controller next to the your usb dongle / bt antenna and see if it drop connection. Some cheap usb dongles have really bad range.

**Comment by MrYourself** [comment]
So, I've tried the antenna which came with my motherboard. I also tried trying to connect while the controller was put in the case. The Bluetooth chip is build on my mainboard. If there is a way to export a more in dev look log I'm willing to do that.

**Comment by MrYourself** [comment]
ok, i found the options with more details in the log 


[log.txt](https://github.com/Ryochan7/DS4Windows/files/6797042/log.txt)
