### ISSUE TITLE
Assingn gamepad buttons to the touchpad not working anymore since 1.4.62

### ISSUE THREAD

**Issue by pralima87** [Ryochan7/DS4Windows#23]
In the "select an action for [...]" assigning **gamepad buttons** to the **touchpad** is no longer working since 1.4.62.
The touchpad responds fine to keyboard or mouse commands but it does not respond to gamepad buttons.

Like making the **left touch** the **start** or the **back** buttons.
When going back to 1.4.61 it works fine ;)

**Comment by Ryochan7** [comment]
I messed up when refactoring code. The routine has now been corrected and tested.

**Comment by Ryochan7** [comment]
The new release that fixes this issue and the lightbar color change problem is now uploaded.

https://github.com/Ryochan7/DS4Windows/releases/download/v1.4.64/DS4Windows_1.4.64_x64.zip
