### ISSUE TITLE
DS4 freezing only with DS4Windows in action games

### ISSUE THREAD

**Issue by jbjohnaici** [Ryochan7/DS4Windows#2301]
**Describe the bug**
Controller freezing up and need to power off to reconnect. This problem happens more in games that need to use the controller quickly and pressing many buttons. This happens to me when I play D&D: Dark Alliance and FIFA 21. In games like Divinity Original Sin 2 (turn-based RPG) that doesn't happen.

**To Reproduce**
It's very random. I notice the problem more when I'm playing FIFA 21. When I play about 3 matches, in one of them it happens.

When I use InputMapper, it doesn't happen.

**Expected behavior**
Controller don't freenzing any time.

**Screenshots and Logs**
I'm attaching the log. This was what I thought was the most interesting information.
[ds4windows_log_20210711.1.txt](https://github.com/Ryochan7/DS4Windows/files/6797317/ds4windows_log_20210711.1.txt)

But I believe it was the one that was generated when the problem happened.
[ds4windows_log_20210711.2.txt](https://github.com/Ryochan7/DS4Windows/files/6797329/ds4windows_log_20210711.2.txt)

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2
 - OS: [e.g. Windows 10 Pro 20H2
 - DS4Windows Version 30.3.13

**Additional context**
When the problem happened, I had trouble closing DS4Windows to reopen it and reconnect the controller.

**Comment by Ryochan7** [comment]
Log makes it look like something in the "xbox l off" profile might be the main culprit. Going to need that profile. Once the second problems occurs (ViGEm Device Plugin Failed), you are going to likely have to reboot Windows and then run the PurgeOldXInput tool from the Tools folder.

**Comment by jbjohnaici** [comment]
Sorry, I deleted this profile. It was just a profile where i tried to turn the lightbar off. Even though, the issue keeps happening. The last time it happened was when I was playing Sea of Thieves. No fast action happened , but out of nowhere the control locked up again.

This log  was the one generated when the problem happened.
[ds4windows_log_20210713.2.txt](https://github.com/Ryochan7/DS4Windows/files/6819961/ds4windows_log_20210713.2.txt)

**Comment by Ragga95fr** [comment]
same problème with Assassin s Creed (red light and freezer but very random)

**Comment by mika-n** [comment]
the issue is probably bad BT connection (bad radio reception or BT dongle/chipset is not up to the task with DS4/DS5 pad). Red light usually means "lag warning". Logfile would tell this for sure
#1196 

Follow BT tips in Troubleshooting documentation page (linked in the #1196 post). If you have BT dongle attached at the back of PC chassis then try using usb extension cable and attach the BT dongle there (takes the dongle further away from the radio storm caused by PC chassis and closer to the gamepad).

**Comment by mika-n** [comment]
closed as inactive
