### ISSUE TITLE
Bluetooth audio stream with dualshock4v2 issue

### ISSUE THREAD

**Issue by soredake** [Ryochan7/DS4Windows#2303]
**Describe the bug**
mostly copied from https://github.com/Ryochan7/DS4Windows/issues/2095 report

I have a strange problem with dualshock4v2 and bluetooth headphones.
When I pair the controller with the PC. Audio is transmitted intermittently.

As soon as I turn off the controller, the sound is again correctly played through the headphones.

I use the Orico BTA-403 adapter (CSR 8510 chip). No such problem with other xinput controller through x360ce+bluetooth, also no such problem in linux, if this matters.

**To Reproduce**
1. Connect bluetooth audio headphone (sound ok)
2. Connect dualshock4v2 with bluetooth
3. Test in sound dialog or launch a game
4. Audio stutter or audio disconnect/reconnect

**Expected behavior**
The controller must not mess up the bt audio.

**Screenshots and Logs**
If applicable, add screenshots to help explain your problem. Also, please add the most
log file (ds4windows_log.txt) from the Logs folder in your DS4Windows config folder.

**Desktop (please complete the following information):**
 - Sony DS4 v.2 (CUH-ZCT2E)
 - Windows 10 Pro 21H1 19043.1083
 - 3.0.13

**Additional context**

**Comment by SeRoM** [comment]
Unfortunately no. I live with it, it's so random.
Glad to see that I'm not the only guy in this situation.
Someone had provided an explanation here: https://github.com/Ryochan7/DS4Windows/issues/2101#issuecomment-830678655

Apparently, the bluetooth built into motherboards are not very efficient (which is still surprising).
The situation should improve with time and updated drivers.

Regards,

**Comment by soredake** [comment]
Tested with different adapter and without ds4windows, nothing changed, so it's either windows bt drivers or gamepad problem.

**Comment by pinospin** [comment]
Which version is your adapter?

**Comment by soredake** [comment]
Bluetooth v4.0

**Comment by mika-n** [comment]
These BT related issues are sometimes a mystery and often not even related to DS4Windows app itself. 
Closed as "potentially not DS4Windows app issue".
