### ISSUE TITLE
Touchpad and Gyro Passthru doesn't work DS4 Emulation.

### ISSUE THREAD

**Issue by Valek2000** [Ryochan7/DS4Windows#2306]
Touchpad and Gyro Passthru doesn't work on DS4 Emulation. I have a dualsense and use to play PS4 remote Play, tried many times but both doesn't work.

Windows 10 x64
Dualsense
Vigem 1.7.333 installed. 
Controller connected in Bluetooth 5.1 adapter.

**Comment by Ryochan7** [comment]
> Vigem 1.7.333 installed.

Wouldn't be the first case of someone outright lying to me about that.
