### ISSUE TITLE
DS4 Not Opening 

### ISSUE THREAD

**Issue by SixPathsOfDrip** [Ryochan7/DS4Windows#2311]
**Describe the bug**
When DS4 is being open there is no indication that it trying to open outside of an empty space on my taskbar but when hovered it disappears. Even when using the updater, which works, opening the program from there still does not work.

**To Reproduce**
1. Click on DS4 exe 
2. Wait
3. Proceeds to "Close"
4. No error log is obtained

**Expected behavior**
For the DS4 to run like normally

**Screenshots and Logs**
If applicable, add screenshots to help explain your problem. Also, please add the most
log file (ds4windows_log.txt) from the Logs folder in your DS4Windows config folder.

![image](https://user-images.githubusercontent.com/87409901/125569816-fd201532-11d2-47d9-a066-949dfece79a4.png)
![image](https://user-images.githubusercontent.com/87409901/125569943-91adea26-447c-4873-ae53-bdd466bbe0a0.png)

**Desktop (please complete the following information):**
 - Controller Make and Model: PS5 Controller
 - OS: Windows 10
 - DS4Windows Version 3.0.13

**Comment by mika-n** [comment]
#1196 

Are you sure you have the correct version of .NET runtime libraries and DS4Windows app itself? Make suer you use x64 (=64bit) versions from both components. Check %APPDATA%\DS4windows\log logfiles.

**Comment by SixPathsOfDrip** [comment]
[ds4windows_log_20210714.4.txt](https://github.com/Ryochan7/DS4Windows/files/6816598/ds4windows_log_20210714.4.txt)
[ds4windows_log_20210714.3.txt](https://github.com/Ryochan7/DS4Windows/files/6816599/ds4windows_log_20210714.3.txt)
[ds4windows_log_20210714.2.txt](https://github.com/Ryochan7/DS4Windows/files/6816600/ds4windows_log_20210714.2.txt)
[ds4windows_log_20210714.1.txt](https://github.com/Ryochan7/DS4Windows/files/6816601/ds4windows_log_20210714.1.txt)
[ds4windows_log_20210714.0.txt](https://github.com/Ryochan7/DS4Windows/files/6816602/ds4windows_log_20210714.0.txt)
[ds4windows_log_20210713.3.txt](https://github.com/Ryochan7/DS4Windows/files/6816603/ds4windows_log_20210713.3.txt)
[ds4windows_log_20210713.4.txt](https://github.com/Ryochan7/DS4Windows/files/6816604/ds4windows_log_20210713.4.txt)
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/6816605/ds4windows_log.txt)

**Comment by mika-n** [comment]
https://github.com/Ryochan7/DS4Windows/search?q=System.Management.ManagementException&type=issues

You have disabled or you have a broken Microsoft WMI services in WinOS level. Read through those old cases and follow the "reset wmi repository" solution.
