### ISSUE TITLE
Random change Xinput virtual controller number 1-3 (0-2) when reconect DS4.

### ISSUE THREAD

**Issue by Softernet** [Ryochan7/DS4Windows#2312]
**Describe the bug**
Problem exist throughout existence DS4Windows. Random change Xinput virtual controller number 1-3 (0-2) when reconect DS4. After this happens XInputChecker process consumes a lot of CPU time.

**To Reproduce**
1. Simply connect and reconnect DS4 in emulated controller Xbox 360 mode, until it happens.
2. See that.

**Expected behavior**
This shouldn't happen. The Xbox 360 Virtual Controller must remain at number 1 (0). 

**Screenshots and Logs**
![Снимок экрана (4)](https://user-images.githubusercontent.com/31589009/125650697-9a358961-0d75-45c9-85e9-4fac943007e3.png)
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/6817273/ds4windows_log.txt)

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2E)
 - OS: Windows 10 Pro Build 20H2
 - DS4Windows Version 3.0.11/3.0.12/3.0.13.

**Comment by Kanuan** [comment]
This is a Windows issue, not a DS4Windows. Something in your system is keeping a open connection to the xinput dll which prevents windows from properly releasing the XInput slot. You can use process explorer to verify what process might be the culprit

https://user-images.githubusercontent.com/24910442/123340694-05a1e600-d523-11eb-9e83-8d90ea1738f4.png

**Comment by Softernet** [comment]
> This is a Windows issue, not a DS4Windows. Something in your system is keeping a open connection to the xinput dll which prevents windows from properly releasing the XInput slot. You can use process explorer to verify what process might be the culprit
> 
I dont thing so.
Before a problem after several reconnection: 
![Снимок экрана (6)](https://user-images.githubusercontent.com/31589009/125673763-5dcd8775-1967-4120-b608-eb336329e323.png)
After changing the number:
![Снимок экрана (7)](https://user-images.githubusercontent.com/31589009/125676681-c7ba1e74-1902-4ba6-9426-676516b23fcb.png)
![Снимок экрана (8)](https://user-images.githubusercontent.com/31589009/125676682-38bb05e6-3d3e-4da5-baba-49029dc9cf18.png)

**Comment by mika-n** [comment]
Try using "Persistent Slot" in OutputSlots tab page to workaround the xinput slot issue when gamepads come and go. It is Windows OS issue (or maybe Vigem driver issue also) when gamepads come and go. PersistentSlot makes the WinOS and games less sensitive go gamepad disconnections and re-connections.

**Comment by Softernet** [comment]
> Try using "Persistent Slot" in OutputSlots tab page to workaround the xinput slot issue when gamepads come and go. It is Windows OS issue (or maybe Vigem driver issue also) when gamepads come and go. PersistentSlot makes the WinOS and games less sensitive go gamepad disconnections and re-connections.

Thanks for yours solution but permanently connected virtual controller while hardware controller disconnected it does not suit me.

**Comment by Masamune3210** [comment]
Well, as stated above, you can find out which program is keeping a hold on the controller and deal with that if you want the issue to be resolved. It is a issue with the OS, not with this program

**Comment by Softernet** [comment]
> Well, as stated above, you can find out which program is keeping a hold on the controller and deal with that if you want the issue to be resolved. It is a issue with the OS, not with this program

Well, as stated above, no program is keeping a hold on the controller.

**Comment by Kanuan** [comment]
>Well, as stated above, no program is keeping a hold on the controller.

From your screenshots, it shows both the Nvidia software and Opera. From my own experience, I've never had the nvidia web helper actually lock the XInput slots, but I do had many times where chrome would for some reason lock up XInput Slots. Maybe Opera is doing the same thing? Have you tried fully closing Opera so its handle on the xInput dll vanishes and then try reconnecting the controller?

**Comment by Softernet** [comment]
> Maybe Opera is doing the same thing? Have you tried fully closing Opera so its handle on the xInput dll vanishes and then try reconnecting the controller?

I don't tried this. In the next time, when is happens, I'll tried this and reported.

**Comment by Ryochan7** [comment]
> I've never had the nvidia web helper actually lock the XInput slots, but I do had many times where chrome would for some reason lock up XInput Slots.

I can confirm that I have experienced similar behavior with Google Chrome in the past. I don't think I have run into that issue with more recent versions of Chrome though.

**Comment by BParks21** [comment]
I don't have opera installed or Nvidia software and I'm able to reproduce the same issue on windows 10. Setting the slot to permanent does prevent this.

**Comment by mika-n** [comment]
closed as "permanent slot" feature is one way to workaround the issue. And the issue (when hit) is beyond the control of DS4Windows app. 

(well, there used to be few bugs if DS4Windows app was stopped and started using Start/Stop button in DS4Windows GUI, but the latest version fixed few of those bugs).
