### ISSUE TITLE
ps4 wired controller not detected

### ISSUE THREAD

**Issue by 0lm** [Ryochan7/DS4Windows#2315]
im using the newest version of ds4windows 3.0.13. plugging in my controller, but ds4windows doesnt detect it. while steam detects it perfectly. any ideas why?

**Comment by Ryochan7** [comment]
Clearly not using a first party Sony DS4. This post is going to go nowhere. I don't have access to Valve level funds.

**Comment by 0lm** [comment]
Hello and thank you for taking your time for answering. But if you allow me to comment: It is kinda rude to immediately expect me not using a first party Sony DS4. I am using an original Nancon PS4 Controller, with original PS4 lable and whatnot. Everything on my PC recognized the PS4 controller, also VigemBus and similar. It is just DS4Windows not recognizing it, and I am not sure why. I followed all instructions (in past, I used VigemBus Drivers etc by Neferius anyways, to make my DS3 controllers work back then, with the help of Fireshock and Shibari). It is not like I am a beginner and I know how to tell apart an original Sony controller or not.

That aside, I will try ot solve it myself, since it seems like you dont want to help out. That's totally fine by me though, it is up to one self to decide if you want to help or not. It just felt kinda rude that you instantly expected me not using an original and closed the issue, although others might know how to solve it or have similar problems.

**Comment by Kanuan** [comment]
@0lm create a new discussion topic on the [DS4Windows discussions page](https://github.com/Ryochan7/DS4Windows/discussions) with all the informations related to your controller. Since we don't know if it's an actual issue with DS4Windows it will be better if we continue there

**Comment by 0lm** [comment]
Thank you for the Link, Kanuan. I didnt think of checking the DIscussion Page. I will try to describe the problem more exactly there then. (since this post might be very short, I agree with that, if anyone complained about how short it was)
