### ISSUE TITLE
Using DS4 sometimes causes programs to open without focus. 

### ISSUE THREAD

**Issue by BParks21** [Ryochan7/DS4Windows#2319]
**Describe the bug**
Not every time but sometimes when using DS4 and connecting a controller I notice programs will suddenly open without focus. Like Libre Office, some emulators like RetroArch, Yuzu and many others. 

**To Reproduce**
Just launch DS4 and connect a controller a few times. It will eventually cause the issue. I can reproduce it eventually every single time I use the program. This issue never occurs on my PC unless I use DS4. Only logging out or restarting the computer fixes the issue. This has been happening for a couple years now. Even with clean windows installs. You can see in the screenshots that these two programs opened without focus because the title bar is white. 

**Expected behavior**
My programs should continue to open with window focus from the get go when launching them.  

**Screenshots and Logs**
![Screenshot (3)](https://user-images.githubusercontent.com/12180630/125869173-04c17395-a394-4045-a380-85a4281b7f6c.png)
![Screenshot (4)](https://user-images.githubusercontent.com/12180630/125869174-81d53c1a-d84a-4e20-83d9-2d031e837e32.png)
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/6826717/ds4windows_log.txt)

**Desktop (please complete the following information):**
 - Dualsense and Dualshock 4
 - Windows 10 Pro  21H1 Build 19043.1110
 - DS4Windows Version 3.0.13
 - CPU i7 8086K
 - GPU GTX 1080 Ti
 - 32GB DDR4

**Additional context**
I cannot find a cause or solution to this

**Comment by Ryochan7** [comment]
I can only assume your chosen profile (or some Special Action) has some keyboard key bindings and those are active while you are launching a different program before the window is shown. In that case, whatever app (or just the desktop) you have in the foreground at the time would have active focus as opposed to the new window.

**Comment by BParks21** [comment]
This lack of focus happens even after I disconnect the controller and close DS4.

**Comment by BParks21** [comment]
> I can only assume your chosen profile (or some Special Action) has some keyboard key bindings and those are active while you are launching a different program before the window is shown. In that case, whatever app (or just the desktop) you have in the foreground at the time would have active focus as opposed to the new window.

I found out it's actually a Windows bug. It has to do with how the notification panel is handling programs generated notifications focus. I know how to reproduce it every time. It's not caused by DS4 Windows. When DS4 or any program generates a notification in the notification panel and you click on the notification panel quickly before the notification moves into the panel area and hit clear notifications, it's these exact steps that reproduce this bug. After reopening the notification panel and clicking anywhere the problem is gone. I can reproduce this at will now. Sorry for thinking DS4 was the cause.
