### ISSUE TITLE
How to uninstall drivers

### ISSUE THREAD

**Issue by metjuo** [Ryochan7/DS4Windows#2320]
How t ouninstall all controllers drivers?

**Comment by Kanuan** [comment]
- **DS4Windows**: it is a portable application, just deleted the folder the program is in
- **ViGemBus**: driver used by DS4Windows to create the virtual xbox 360 or virtual DS4 controllers, can be uninstalled on Windows' `Apps and Features` as a normal program
- **HidHide**: used to "hide" the physical devices. It's an options driver and you may or may not have it installed. In case you have it installed you can uninstall it on Windows' `Apps and Features` as a normal program, but you need to reboot it after uninstalling it
- **HidGuardian**: an old driver that was previously used by DS4Windows but is not used anymore. You can verify if it's installed and uninstall it in case it is by following only [this its own section on HidHide's guide](https://vigem.org/projects/HidHide/Simple-Setup-Guide/#verifying-if-hidguardian-is-installed-and-uninstalling-it)

![image](https://user-images.githubusercontent.com/24910442/125995093-2781698e-149e-476b-9dfe-014488d4b8e2.png)
