### ISSUE TITLE
Touchpad Swipe Stopped Working after update from v2

### ISSUE THREAD

**Issue by Heartbreaker714** [Ryochan7/DS4Windows#2321]
Not sure how to fix the issue. The touchpad swipe has just stopped working/respond. I imported the profile from when it worked but still nothing. 
Has something change? Is there a setting I need to adjust or anything

**Comment by Yohoki** [comment]
Touchpad (and a few other features) have gotten a bit more complicated. Make sure to set the touchpad output mode to "Controls" in the touchpad tab.
![image](https://user-images.githubusercontent.com/44595371/126002944-24b6309b-7a86-4c27-8efc-5af77b8cd9ec.png)

**Comment by Heartbreaker714** [comment]
Correct. The profile has it already like that but with specific keys like so. CIs there anything else necessary to make it work?
![touchpad](https://user-images.githubusercontent.com/48901812/126004221-f0721e67-bb3e-422a-9118-2a87defe69cd.JPG)

**Comment by Heartbreaker714** [comment]
Looks like this was the culprit. Apparently when I upgraded it checked this box adnd it needs to be unchecked to work the swipes
![touchpad](https://user-images.githubusercontent.com/48901812/126015954-462f8a39-86db-4bfa-893e-d16ad68b8c1d.JPG)
