### ISSUE TITLE
Controller is not detected by DS4W

### ISSUE THREAD

**Issue by IDAZIZ** [Ryochan7/DS4Windows#2324]
Describe the bug:
ds4 controller is not being detected by ds4w, and i get no raw input from the controller when wired or wireless but it works when i use inputmapper which is a program that emulates the ds4 into an xbox360 controller, even when i try to use the controller through steam it doesn't detect it.

To Reproduce:
when i updated ds4w the problem appeared, i don't really know how to fix the problem to reproduce it
could be a driver issue.

Screenshots and Logs:
![Screenshot_3](https://user-images.githubusercontent.com/87600888/126064795-09219200-a74b-4fd9-9ad9-f892253579aa.png)
![Screenshot_4](https://user-images.githubusercontent.com/87600888/126064825-b8396050-37c2-4262-9864-4855241067d9.png)
[log.txt](https://github.com/Ryochan7/DS4Windows/files/6836107/log.txt)

Desktop:
 - Controller Make and Model: Sony DS4 (CUH-ZCT1U)
 - OS: [e.g. Windows 10 Pro Build 19043.1110]
 - DS4Windows Version [e.g. 3.0.13]

Additional context:
i read all the instructions and installed all the requirements, i tried reinstalling things and restarted a few times also tried using different usb ports and got another ds4 controller to test with but the problem still remains the same, i tried previous versions of ds4w hoping it would work again but to my disappointment it didn't, if there is any information i can provide to help solve the problem please do tell.

PS. thanks Ryo for the continuous updates and your contributions cheers.

**Comment by mika-n** [comment]
Try enabling the "Settings / Device Options / Enable Verbose Log" option and re-connect the gamepad.

But, you said you have used InputMapper. Did you install HidGuardian tool with InputMapper app? If you did then HidGuardian is probably hiding the physical gamepad from DS4Windows app.

Anyway, HidGuardian is not recommended anymore and it has been replaced with HidHide tool.
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

Make sure you don't have HidGuardian and then try again.

**Comment by Kanuan** [comment]
A simple way to check if your controller is hidden by HidGuardian is by opening the Windows' `USB Game Controllers` by pressing on your keyboard `Win + R` -> Typing `joy.cpl` then selecting **OK**.
With both DS4Windows and InputMapper fully closed your controller must appear on the `USB Game Controllers` list as a **Wireless Controller*

**Comment by IDAZIZ** [comment]
it was indeed HidGuardian, it was hiding my controller from ds4w.

cheers guys
