### ISSUE TITLE
Left analog flickering

### ISSUE THREAD

**Issue by VermillionFury007** [Ryochan7/DS4Windows#2325]
Character keeps stuttering when moving. when I opened controller readings tab I noticed the small dot flickering
Happens in every game, tested on 2 ps4 controllers and 2 pcs
Is there any options to ease this flicker thing?

https://user-images.githubusercontent.com/74694229/126082283-8f8203b3-6d7d-44c8-a4f8-4fe2511cd249.mp4

**Comment by mika-n** [comment]
#1196 
https://github.com/Ryochan7/DS4Windows/wiki/Settings#deadzone
