### ISSUE TITLE
Flick stick real world calibration capped at 100

### ISSUE THREAD

**Issue by augustofretes** [Ryochan7/DS4Windows#2328]
Using a DualSense, gyro aiming feels a bit too erratic using the default sensibility (100). My workaround is to set the gyro sensibility to its maximum (500) and turn the in-game sensibility down (e.g. 0.1 in Valorant). Doing that, gyro aiming with DS4Windows feels as smooth as it does with JSM (which for some reason always felt better than anything else I've tried).

The only problem is I can't get flick stick to work then, because real world calibration is capped at 100. Is it possible to remove or increase that cap? (alternatively, an in-game sensibility field could be added, that's what JSM does).

**Comment by augustofretes** [comment]
P.S. It's just a UI restriction, you can set real world calibration to whatever value (and it works just fine), by editing the profile manually.

**Comment by Ryochan7** [comment]
I cannot remember my reasoning at the time but leaving out an in-game sensitivity variable was a deliberate decision. 100 for the RWC cap was an arbitrary decision as I figured there would be no need to have a value even that high. It is only enforced in the editor. That does mean that the cap will be saved back to the profile whenever you save the profile again within DS4Windows.

**Comment by Ryochan7** [comment]
A simple issue that got lost in the shuffle due to getting slammed by people about an issue that was not my fault followed by my original rage quit. I only ended up increasing the limit to 200.

https://github.com/Ryochan7/DS4Windows/commit/f5772cde923c85db28fc9b15aa4ddc1b19096acf
