### ISSUE TITLE
DS4 won't run until I install ".NET version 5.0.0"

### ISSUE THREAD

**Issue by MikefromTexas** [Ryochan7/DS4Windows#2331]
DS4 won't run until I install ".NET version 5.0.0", which I've already done twice. Everytime I try to run it, it just keeps telling me to download that file, over and over.

**To Reproduce**
1. Go to DS4Windows.exe.
2. Click
3. Error message pops up, saying "To run this application, you must install .NET"

**Expected behavior**
I expected DS4 to run normally like it did an hour ago, before I deleted my original file.

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4
 - OS: Windows 10
 - DS4Windows Version 3.0.3

**Additional context**
DS4 worked last night. It worked an hour ago. I decide to delete it and try using my PS4 controller through Bluetooth, but it doesn't work. I download the latest version of DS4 7z, now it asks me to download a file I've never needed before.

**Comment by Ryochan7** [comment]
Broke your own setup needlessly but it becomes my fault somehow.
