### ISSUE TITLE
Ps5 Vibration Not working

### ISSUE THREAD

**Issue by jmilanek10** [Ryochan7/DS4Windows#2332]
I am having issues with my PS5 Controller not vibrating. I have tried everything. Completely uninstalling everything, redownloading,  Checking all settings in App and profiles and even downloading old versions. This issue is with all of my Dual sense controllers and i have tried to emulate as a Xbox controller and still nothing. Any recommendations? Or just wait for an update? This is for any game stream or not but i mainly use it for Cold War. I've used this for about a year and the problem just began on 3.0.11. 

Thanks

**Comment by mika-n** [comment]
#2275 

Rumble is disabled on purpose when the output virtual controller type is dualshock4 (until few bugs have been fixed). But rumbling should work when a profile uses the xbox360 output controller type.

**Comment by jmilanek** [comment]
Awesome thank you!
