### ISSUE TITLE
Windows thinks i connected an XBox Controller

### ISSUE THREAD

**Issue by igobythisname** [Ryochan7/DS4Windows#2336]
Windows thinks I connected an XBox Controller and the game I'm playing, GTA 5, is showing me in game buttons for XBox Controller, but I'm using a PS4 controller not an XBox Controller

**Comment by Yohoki** [comment]
What controller you're actually using doesn't matter much, since DS4Windows is showing the game a fake controller. You can tell it which controller type to show the game under the options in the profile you're using. Open D4W and go to the "Profiles" Tab and double click the profile you're using.  Click the "Other" and set the "Emulated Controller" to "Dualshock 4".
![image](https://user-images.githubusercontent.com/44595371/126401238-03501c04-b798-4a30-b8fb-c0da5582082c.png)


If this does not solve the issue, then the game you're playing is not programmed to use a ps4 controller (Pretty common), and may not have Playstation button prompts. You'll have to either get used to the controlls or look for a mod to add PS Button Prompts.

**Comment by igobythisname** [comment]
Thanks! I guess that's what I was looking for! at least partially...

**Comment by Yohoki** [comment]
Which part is still giving you trouble? I'd be glad to help. :)

**Comment by igobythisname** [comment]
actually, you got it 100%, thanks! I thought I included something about lag/delay but i see now that I did not. the first time i installed the outdated (not ryochan7) version and i noticed a lag/delay while playing, seems better w/the ryochan7 one; is there a setting for delay/response?

**Comment by igobythisname** [comment]
also, should i be turning it (my controller) off when i'm not using it? is that even possible (to turn it off, either w/DS4Windows or on the controller itself)? i play for like 6-8hrs at a time, i'm sure the battery on my controller won't last that long

**Comment by Yohoki** [comment]
> 
> 
> actually, you got it 100%, thanks! I thought I included something about lag/delay but i see now that I did not. the first time i installed the outdated (not ryochan7) version and i noticed a lag/delay while playing, seems better w/the ryochan7 one; is there a setting for delay/response?
There's not REALLY a setting to adjust for lag/delay. It sends signals to the PC as fast as it can. There are a few things you can do though.
- If you're using Bluetooth, getting the receiver AWAY from the signal mess that is your PC case helps. Using a short USB extender cable or hub can get the receiver a few feet away from the PC case to get a better signal.
- If you're using a wired setup, a shorter cable means less travel time, and less input lag.
- You can also send LESS info over the connection. IIRC by default, the controller tries to send and receive all info, including lightbar data and rumble data. You can turn this off in your profiles by going to the "Other" tab and unticking the "Enable output data to DS4". This will use less BT or USB bandwidth.



> 
> 
> also, should i be turning it (my controller) off when i'm not using it? is that even possible (to turn it off, either w/DS4Windows or on the controller itself)? i play for like 6-8hrs at a time, i'm sure the battery on my controller won't last that long

I use my controller as a mouse, so it's on 24/7. If you need to turn it off, you can unplug a Bluetooth controller by using a combo. I believe the default for this is Options+PS, but this can be changed in the "Special Actions" tab of your profiles.

If you're concerned about damaging the battery, I can say from years of gaming on the PS4, the battery is just fine being left on all the time while you're playing. But, it IS a normal chargeable battery, and they suffer from reduced charge over their lifetime. If you want to keep the battery charge from getting shorter and shorter, make sure to charge it when the battery is low, not when it's only been used for a short time.

**Comment by igobythisname** [comment]
thanks SO much for the helpful and useful info, i really appreciate it! i have 3 controllers so i'll just switch em if the battery dies. seems like switching it from xbox to dualshock 4 controller in the settings made the joystick stop working, so i switched it back to xbox, very strange!

**Comment by Yohoki** [comment]
I took a quick look for you on the google. It looks like GTAV doesn't have DualShock support, so gamepad won't work right, and there are no PS button prompts. There are mods to fix that, but you can be banned for using them (which is just stupid....). So, probably best to just get used to the XBox controls for that game. Sorry, about that. That's kind of a Game Dev issue.

**Comment by igobythisname** [comment]
**_THANK YOU_**
