### ISSUE TITLE
DualShock 4 phone jack

### ISSUE THREAD

**Issue by vpontin** [Ryochan7/DS4Windows#234]
When i connect a DualShock via USB using 1.4.113 a new audio device appears on my sound settings, but plugging a normal earphone i dont get any audio of it,

![image](https://user-images.githubusercontent.com/3485505/37172353-4cec9c2e-22ef-11e8-8d1f-c5a53caffd2e.png)

In the image, the first device appears when plugging dualshock

Is this normal?

**Comment by fehmi1907** [comment]
Sounds like issue #182

**Comment by Ryochan7** [comment]
I believe the latest release should fix this problem. Looking at your screenshot, I am betting that the search string that was being used in DS4Windows was wrong. That would cause DS4Windows to not grab the audio device volume, assume that the volume is 0 and then mute the audio device upon sending an output report. The search string has been changed to be not dependent on format as much.

https://github.com/Ryochan7/DS4Windows/releases/download/v1.4.120/DS4Windows_1.4.120_x64.zip
