### ISSUE TITLE
Audio problem when activate ds4

### ISSUE THREAD

**Issue by KhawanC** [Ryochan7/DS4Windows#2341]
I have a Nacon Revolution Pro controller (it's USB) and I usually use the controller for "audio extension", everything works fine but when I activate the DS4 i just can't listen anything. I click on the audio manager to adjust the volume and I can hear the windows sound and other audions running but just for 2 or 3 seconds, after this the audio stops again.

Don't know what to do, can anyone help me ?

**Comment by VladWinner** [comment]
![image](https://user-images.githubusercontent.com/13555921/127771136-ad858c53-3e16-497d-9637-33dfa1934b71.png)
Just check in the sound system settings which communication and listening device is used by default.

**Comment by mswift98** [comment]
when you connect your controller, Windows changes the audio output to your controller headphone jack. you need to change it once by clicking on the sound icon in the taskbar and then click on "Speakers (Wireless controller)" and change it to your regular speakers. Hope that helps you.
