### ISSUE TITLE
No macros/custom keybinds works on Genshin Impact

### ISSUE THREAD

**Issue by Animus120** [Ryochan7/DS4Windows#2354]
**Describe the bug**
Whenever I'm playing Genshin Impact, any macros/rebind keys I use on my DS4Windows doesn't work.

**To Reproduce**
1. Go to 'Profiles'
2. Set any buttons on the Controller to any other button (ie. Change X to press O, Use Triangle to trigger Alt+F4 macro)
3. Go in-game
4. Press said button

**Expected behavior**
Any changes that I made in the Profile never work in-game. Right now, I'm using the CREATE button on the DualSense to press PRTSC to take screenshot. While in-game, I cannot take any screenshot, yet when I alt-tab to desktop or any other application, pressing the CREATE button will create a screenshot of the screen.

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DualSense (CFI-ZCT1W)
 - OS: Windows 10 LTSC Build 1809
 - DS4Windows Version: 3.0.13

**Additional context**
I set my Genshin profiles to emulate DualShock 4.

**Comment by mika-n** [comment]
if those kbd mappings work outside of the specific game (for example in Notepad) then this is most likely a game specific issue. One thing you could try is to launch DS4Windows.exe app using "Run as administrator" fileExplorer option (right mouse button click on top of DS4Windows.exe app name in FileExplorer).

**Comment by Animus120** [comment]
> 
> 
> if those kbd mappings work outside of the specific game (for example in Notepad) then this is most likely a game specific issue. One thing you could try is to launch DS4Windows.exe app using "Run as administrator" fileExplorer option (right mouse button click on top of DS4Windows.exe app name in FileExplorer).

Oh wow, that completely solved this issue. Is there a way to make it always permanent so that I don't have to start DS4W with Admin right first? Cause I set DS4W to launch with my Windows.

**Comment by mika-n** [comment]
You could setup a Windows TaskScheduler job to run DS4Windows.exe app and bind the job, not to a timestamp, but to Windows event like "user logon". And then tick an option "Run with highest privileges" in the taskScheduler job properties.

And numerous other tricks: https://www.raymond.cc/blog/run-programs-administrator-ctrl-shift/

Anyway, this is unfortunately WindowsOS "issue" and not a DS4Windows app issue and there is nothing DS4Windows app can about it if a game is too picky how kbd and mouse events are sent.

**Comment by Animus120** [comment]
Thank you for the explanation, at least this mystery has been solved for me.
