### ISSUE TITLE
Make both Joycons in joined mode send motion data separately.

### ISSUE THREAD

**Issue by FaeTalan** [Ryochan7/DS4Windows#2358]
DS4Windows currently is sending the motion data of only one of the 2 joycons when used in joined mode.
As you may know, Nintendo has recently released Skyward Sword HD, and emulators can run it beautifully. Since the game uses motion data coming from both joycons separately (left for shield, right for sword), could you please make DS4Windows send motion data separately for each joycon?

Ps.: I've tested it on the Ryujinx emulator. The separate motion data from both joycons work correctly with BetterJoy, but the motion data is much more precise with DS4Windows, so it would be lovely if you added this feature.

**Comment by Ryochan7** [comment]
Just got around to testing how BetterJoy handles this. Even in Joined mode, the program still presents the UDP server with two output controllers. The base controller state (buttons, axes, etc.) will be the same across both controllers but BetterJoy transmits each IMU state independently. NonJoined mode works roughly the same as it does in DS4Windows currently.

In theory, this use case would be doable; probably would never have a use for it myself. DS4State would likely have to store a second motion state object that holds the data for the non-primary JoyCon controller. Also, the non-primary controller would have to be exposed to the UDP server.

**Comment by Ryochan7** [comment]
Messed around last night and it is easier to get that configuration working than I thought. Just need a couple of tweaks in the ControlService class to make it work. Got a diff with the change but I am not sure if I will end up committing it to the repo yet.

**Comment by Ryochan7** [comment]
Ended up committing the change with commit 1848e620f5eeea03889f3738cd04729659efec8d

**Comment by Ryochan7** [comment]
This feature now exists in version 3.1.1. It likely would not have happened if it weren't for editing the UDP server and changing the message payload.
