### ISSUE TITLE
Exclusive mode are not working (in almost) all time/ Cant set Output Curve of Triggers

### ISSUE THREAD

**Issue by OSRAGAMER** [Ryochan7/DS4Windows#2364]
**Describe the bug**
HI, im Alive again, after my ds4 controller die, i bought another one, 
the last i remember is the rewriten of the program in NET5, 
the problem whit the exclusive mode is i wasnt enable to make it work, 
i follow the guide of exclusive mode but when i found this
![image](https://user-images.githubusercontent.com/73681619/127100664-b9e5c88a-b5ab-46c1-9bff-1a2ac9b3ad27.png)
i dont know if system always take the control, so this is normal, maybe,
any workaround ?
the other thing, i cant set the output curve of the Analog Triggers, but i set that one moment earlier, and i see it working,
i reset the pc, now is in linear output whatever i select,

**To Reproduce**
1. any moment, open DS4Windows, turn on the controller,
2. Controller up in Shared mode
3. cry

**Expected behavior**
a explanation, i dont know whats happen here

**Screenshots and Logs**
![image](https://user-images.githubusercontent.com/73681619/127102540-37d90a81-3aea-40e0-88b6-0aaf6f8aa0b2.png)

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.1 (CUH-ZCT1)
 - OS: Windows 11 Pro Build 22000.100
 - DS4Windows Version 3.0.13

**Additional context**

**Comment by mika-n** [comment]
Read following tips and make sure you understand why sometimes exclusive mode (=Hide DS4 Controller option in DS4Windows app settings) doesn't work because of reasons beyond the control of DS4Windows app itself.
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

And if you cannot get the exclusive mode to work then save yourself from the trouble and give a test run to alternative HidHide solution (the linked web page talks about this also).

**Comment by mika-n** [comment]
And don't mix different topics into the same issue post. The other question was about custom output curves of L2/R2 triggers. Seem to work just fine here (cubic vs linear options really show different I=input and O=output values in ControllerReadings tab page).

**Comment by Yohoki** [comment]
If you don't have it setup already, you should probably also get [HidHide up and running](https://vigem.org/projects/HidHide/Simple-Setup-Guide/). That makes getting exclusive access much easier.

**Comment by OSRAGAMER** [comment]
Hello, very thanks, Hidhide works perfect, i think it cant be done but works, uff so nice, very thanks,

about Custom Output Curve, i reinstall DS4W and still not working, i dint use it in the sticks, but not work in the sticks to, 
custom output curve only works for the gyro,
by now, Clean Profile folder, clean ds4windows program data, no fix
or maybe im lucky and im the only one wit this problem o.O

**Comment by mika-n** [comment]
well, there were some mapping bugs in previous versions and the latest development version has those fixes. I'm naturally using the latest development version, so it could be one explanation. You should keep eye on the Releases web page once the next official version is released.
