### ISSUE TITLE
DS4 instantly crashes upon boot.

### ISSUE THREAD

**Issue by Chubbulus** [Ryochan7/DS4Windows#2365]
**Describe the bug**
The app simply crashes the second it is started without any devices being plugged in, or even with devices plugged in. It flashes up in the system tray, then closes and that's it.

**To Reproduce**
Run the app.

**Expected behavior**
The app should at least open.

**Screenshots and Logs**
Can't provide a log as there is no "Config" or "Log" folders.

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DualSense (CFI-ZCT1W)
 - OS: Windows 10 
 - DS4Windows Version 3.0.13

**Comment by mika-n** [comment]
#1196 

Closed until the linked and pinned "Read this before posting a new ticket" post is read and understood and the required information is provided.

**Comment by mika-n** [comment]
closed as inactive
