### ISSUE TITLE
Even with Hidhide fully configured, I am unable to play Sekiro which requires the controller to be hidden.

### ISSUE THREAD

**Issue by tkkema** [Ryochan7/DS4Windows#2376]
I have finished the Hidhide configuration, I have checked that the emulated controller is the only one visible, but I'm still unable to play Sekiro.

**Comment by Kanuan** [comment]
1. Sekiro supports only Xbox controllers. Double check if the profile you are using is set to Xbox emulation in the `profile editor -> other` tab
2. Check if the Xbox controller is on `XInput slot 1| by going into `settings` tab -> XInput checker

**Comment by tkkema** [comment]
> 1. Sekiro supports only Xbox controllers. Double check if the profile you are using is set to Xbox emulation in the `profile editor -> other` tab
> 2. Check if the Xbox controller is on `XInput slot 1` by going into `settings` tab -> XInput checker

Thank you for the fast response. I checked everything and it all checks out with what you've described. The Xbox controller is in slot 1, and I am emulating a Xbox controller

**Comment by mika-n** [comment]
Does the virtual gamepad work in other games?
Could you send a screenshot of JOY.CPL (run this cmd in Start menu) gamepad list when DS4Windows app and HidHide are running and a gamepad is connected. There should be only one gamepad with xbox360 name and not "Wireless Controller" (=ds4 gamepad name in JOY.CPL).

**Comment by Ryochan7** [comment]
Probably not configured all the way. Firstly, make sure to reboot Windows after installing HidHide. Windows won't load the filter driver until you do. Secondly, after changing the hiding status in the HidHide Configuration Client, you have to disconnect and re-connect the device to the PC in order for the change to take affect. Due to the way the driver works, the change only takes affect when you first connect the device to your PC.

**Comment by tkkema** [comment]
> Does the virtual gamepad work in other games?
> Could you send a screenshot of JOY.CPL (run this cmd in Start menu) gamepad list when DS4Windows app and HidHide are running and a gamepad is connected. There should be only one gamepad with xbox360 name and not "Wireless Controller" (=ds4 gamepad name in JOY.CPL).

I tested and after checking that Hidhide was doing it's job, I tested on a different game and the controller worked fine. Here is a screenshot of the joy.cpl result
![joycpl](https://user-images.githubusercontent.com/88140023/127553762-ff3fda55-bb7b-4af0-aa44-bc33dfd7b02a.PNG)

**Comment by tkkema** [comment]
> Probably not configured all the way. Firstly, make sure to reboot Windows after installing HidHide. Windows won't load the filter driver until you do. Secondly, after changing the hiding status in the HidHide Configuration Client, you have to disconnect and re-connect the device to the PC in order for the change to take affect. Due to the way the driver works, the change only takes affect when you first connect the device to your PC.

I followed all your steps, double checked joy.cpl, and tested on a different game. Everything was fine on the other game, but no input registered in Sekiro.

**Comment by Kanuan** [comment]
I personally tested Sekiro (on Steam) and I confirm it works as normal with the virtual Xbox controller (with or without using Steam's Xbox Controller Support).

Another user appeared recently having the same issue as the OP and the only difference we've found between my setup and theirs is that I was using a legit version of the game from Steam and theirs was a pirated/cracked one.

**Comment by tkkema** [comment]
> I personally tested Sekiro (on Steam) and I confirm it works as normal with the virtual Xbox controller (with or without using Steam's Xbox Controller Support).
> 
> Another user has appeared recently having the same issue as the OP and the only difference we've found between my setup and theirs is that I was using a legit version of the game from Steam and theirs was a pirated/cracked one.

Is there no solution for cracked copies?

**Comment by mika-n** [comment]
> > I personally tested Sekiro (on Steam) and I confirm it works as normal with the virtual Xbox controller (with or without using Steam's Xbox Controller Support).
> > Another user has appeared recently having the same issue as the OP and the only difference we've found between my setup and theirs is that I was using a legit version of the game from Steam and theirs was a pirated/cracked one.
> 
> Is there no solution for cracked copies?

Yes, purchase the legit version. No one here is going to waste time supporting pirated copies of games.
