### ISSUE TITLE
Start DS4Windows at machine startup instead of user login

### ISSUE THREAD

**Issue by alpharou** [Ryochan7/DS4Windows#2379]
I'm trying to start the program at startup with a task.

It starts quickly with or without the "store password" ticked and I'm able to login using on screen keyboard thanks to FakerInput, all profiles load and interact with HidHide no problem, but it seems to be executed with another user and the taskbar icon and interface are not accesible.

Then, if you open DS4Windows after login it starts as a new instance and now you have two virtualized controllers.

I suppose it's a problem with the way I set up the task, could someone share an exported task that starts at power on and is accesible from the user it was executed once logged in?

EDIT: It seems like DS4Windows does not run a service backend, so I understand why it does not work as intended outside of a desktop environment.

**Comment by Ragga95fr** [comment]
It's been more than 4 versions that mine does the same. You run the application it loses its settings and no longer uses the default config. But I do not run the application automatically.

**Comment by mika-n** [comment]
closed as "not being able to duplicate the bug, so impossible to investigate further". Anyway, in few cases problems like this has been because of roaming profiles and PC was set to cleanup a profile in logoff.
