### ISSUE TITLE
[Feature Suggestion] Multiple shift modifiers 

### ISSUE THREAD

**Issue by taoliu12** [Ryochan7/DS4Windows#2386]
Right now each button can have one shift modifier. It would be great if there can be more shift modifiers per button. 

For example, the shift modifier dropdown menu would display:

Shift modifier 1
Shift modifier 2
Shift modifier 3

**Comment by Ryochan7** [comment]
Don't ever plan on doing that with this project. I already have a different mapper that has Action Set and Action Layer support but it might not ever be worthy of a 1.0 release. Also, it only works with the Steam Controller even though the project's original target device was the Switch Pro controller. I have found it useful in its current state.

https://github.com/Ryochan7/SteamControllerTest

Older Switch Pro prototype:
https://gitlab.com/ryochan7/switchpromappertest/-/tree/action_ideas
