### ISSUE TITLE
Not properly switching between BT/Wire

### ISSUE THREAD

**Issue by Chrisnetika** [Ryochan7/DS4Windows#2389]
**Describe the bug**
Have controller Plugged in via wire, then disconnect it then connect via BT

**Expected behavior**
For controller to work via bluetooth

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 cfi-zct1w
 - OS: Windows 10 Ent Build 19044.110 (21H1)
 - DS4Windows Version: 3.0.13

**Additional context**
Only way to fix the issue is to reboot my computer, even if I plug it back into wire as shown it still does not work.Also it is not accurately reading the power levels in the controller as well.. it gives different readings on BT and on Wire. I notice it can happen vice versa meaning If I begin on BT then I wanna charge it so I plut it in and same issue.It for some reason does not properly wanna switch over.

Attachables:
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/6913708/ds4windows_log.txt)
![Screenshot 2021-08-01 202931](https://user-images.githubusercontent.com/1711756/127790479-2da777ae-d585-41f0-ad28-a77ec3549c19.png)

**Comment by DeusMalsith** [comment]
I had this issue when using my Dualshock 4. I noticed if I turned on all output slots 1-4 then it would work (plugging in a USB cord each time would switch the output slot each time). For some reason it seems to have completely fixed itself to where I only need output 1 to be "plugged in" even if I switch from BT to USB.

**Comment by mika-n** [comment]
`2021-08-01 20:23:14.2847|WARN|4C:B9:9B:40:32:DE disconnected due to read failure: 997`

If you reboot PC and then connect the gamepad using BT (ie. without connecting USB at all) then does it work? If even this doesn't work then this could be simply BT connectivity issue and not really DS4Windows app issue because the logfile shows "read failure" error after the gamepad was connected via BT.

**Comment by Chrisnetika** [comment]
Yes it works on BT, only get the issue when switching to wire or wire to bt vice versa.

**Comment by Chrisnetika** [comment]
> I had this issue when using my Dualshock 4. I noticed if I turned on all output slots 1-4 then it would work (plugging in a USB cord each time would switch the output slot each time). For some reason it seems to have completely fixed itself to where I only need output 1 to be "plugged in" even if I switch from BT to USB.

Yea .. your right I am now noticing this, I did what you said and this time bt works but noticed it is on diff slot now.

**Comment by Chrisnetika** [comment]
Ok I kinda see the issue that is happening here, when I start on either wire or bt the controller takes an output slot, by default the 1st.Issue I am having is when I switch the connection whether it being BT > wire or Wire > BT it does no release the 1st slot, instead it makes another controller/uses next avail output slot as the old DESIRED behavior is for it to release the old slot then reuse it on connection switch seamlessly. As of now the current fix is to switch controller ingame which is pain in ass everytime I either wanna plug in my controller to charge it if i'm using bluetooth and not viable if i'm stuck in a dungeon/raid in a game where every second does matter and since the power readings not accurate it hard to prempt mitigate that issue.
My hopes is that old desired behavior returns and that it gets figured out why the slot is not releasing correctly.
Thank you Devs for the time and effort!

**Comment by Ryochan7** [comment]
Works on my end

**Comment by Chrisnetika** [comment]
guess that means i gotta reinstall everything

**Comment by mika-n** [comment]
did you try setting an OutputSlot to Permanent type instead of using the default dynamic outputSlot mode?

**Comment by Chrisnetika** [comment]
Seems to be ok now after cleaning out ds4/vigem/hidhide and clearing out all drivers and settings then reinstalling, yes I have output as perm.Was able use wire.. switch to BT and then back to wire and maintain operation of gamepad.
