### ISSUE TITLE
DS4Windows clashes with nVidia Shield TV

### ISSUE THREAD

**Issue by keem85** [Ryochan7/DS4Windows#239]
So, I want to use DS4Windows (the new test version) with Cemu emulator and use the motion tracking. Button mappings and everything seems fine, until I launch my Breath Of The Wild startup .bat file from my nVidia Shield TV.. What happens is that Shield is taking control over "Xinput", rendering DS4Windows useless.. My DS4 controller which is connected via DS4Windows cannot coexist with nVidia Shield TV's controller-support, unless I choose "DirectInput" instead of "Xinput".. But I want the rumble effect that "Xinput" gives... Is there a fix for this?

**Comment by Ryochan7** [comment]
I am not familiar with how the nVidia Shield TV handles remote controller input but your report does not sound like it would. Do you have a real XInput controller to test out whether controller input on the local machine would still work?

**Comment by keem85** [comment]
Hmm good question. I remember using that real Xinput controller for a second hand controller, and that worked. When streaming Mario Kart 8 for example, I was able to use my local Xbone controller at the same time as the nVidia one, but they didn't share the same "Controller 1", like in this case. So I would have to test that out. I'm not sure if this is even possible to fix, since nVidia is taking control over the Xinput either way, which is in most cases a good thing. But in this case I wanted my DS4 to work directly to my computer.

There is always this workaround: https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#using-a-gamepad-connected-to-the-pc-instead-of-the-streaming-device
But I'd rather not tamper with how nVidia handles the controller. Would rather love for them to coexist instead.

**Comment by keem85** [comment]
I found a workaround. I'm just making a script to disable rxinput dll file from nvidia whilst Cemu is running.
