### ISSUE TITLE
Detecting 2 controllers in Rocket League

### ISSUE THREAD

**Issue by zPorto** [Ryochan7/DS4Windows#2394]
Hi,

I've searched for a while now for a fix for this problem. Recently when I enabled the 'Hide DS4 Controller' option, it would fix and Rocket League would only detect 1 controller, but for some reason (maybe a Windows update), I can't make it to work now. Even with the 'Hide DS4 Controller' option on, Rocket League is detecting 2 controllers.

Any solutions?
Thanks

**Comment by Kanuan** [comment]
Here -> take your time to read this carefully https://kanuan.github.io/DS4WSite/guides/solving-double-input/

For Mika-n/Ryochan7, I hope there's no problem for me to link users to this site

**Comment by zPorto** [comment]
Was able to fix using the HidHide :)
Thank you! 

I had it installed but didn't bother to open the client and configure it.
