### ISSUE TITLE
FakerInput 0.1.0 crashes sometimes and cannot be uninstalled

### ISSUE THREAD

**Issue by alpharou** [Ryochan7/DS4Windows#2395]
**Bug Description**
FakerInput sometimes stops working and halts DS4Windows. The Start/Stop button gets greyed out and will stay that way until pc restart.

Also, cannot uninstall FakerInput 0.1.0, "installer ended prematurely"

**Comment by Ryochan7** [comment]
I cannot remember how to start MSI logging. The uninstaller works on my end though.

**Comment by alpharou** [comment]
It fails on both of my pcs, ds4windows worked flawless in both until I installed FakerInput, then crashes around 30 minutes after using it, or when reconnecting the controller if it gets disconnected by being idle. Cannot start/Stop

**Comment by Ryochan7** [comment]
Too bad I can't really go back to working on FakerInput. Don't have a valid OV cert anymore so I wouldn't be able to redistribute any potential changes. Luckily, I have not run into issues like this with FakerInput even when debugging and crashing mappers on purpose. Maybe I can add some extra checks in DS4Windows to fall back to SendInput if the connection fails; thought there might have been checks already but probably not.

I would assume that a reboot would have been required to work around your issue and allow the uninstaller to do its job. Either way, I think I would go with a different installer package for an update. Going to have to examine the other FOSS options that exist as I believe the WiX Toolset is still dependent on portions of .NET Framework. Eventually I will need to use a different one for other apps.

**Comment by alpharou** [comment]
It's all right, uninstaller didn't work at the end, did a fresh win10 install as I'm used to and nothing of value was lost. I'll close this issue as it won't be worked upon I suppose.

Really looking forward to new updates and refinement, DS4Windows has accompanied pc geeks as me for many years now
