### ISSUE TITLE
Windows Service? Multi-user environment tips?

### ISSUE THREAD

**Issue by Rast1234** [Ryochan7/DS4Windows#2396]
I have 2 users, both want to use DS4Windows with access to UI and settings. Issue is, Windows 10 automatically starts all programs for last-logged-in user after a reboot, so if user1 reboots PC after user2, DS4Windows is started under user2 account...

What is the recommended way to run app in multi-user environment with working UI, settings, etc without extra manual steps to start/kill app between users? I've seen task scheduler workarounds where people start app with system account but this disables UI, right?

**Comment by Kanuan** [comment]
Though this is may not be what you are looking for, you can disable the "Windows re-opens apps from last logged user" behavior on Windows' Settings -> Accounts -> Sign-in options

**Comment by Rast1234** [comment]
Thanks, this would work of course, but only for a reboot :) Switching users still a thing..

**Comment by mika-n** [comment]
how about create Windows TaskSchduler job and link the job to system events instead of time? There are user logon/logoff taskSchduler trigger events and you could shutdown and restart DS4Windows app whenever user logoffs/logon.
https://github.com/Ryochan7/DS4Windows/wiki/Command-line-options

**Comment by Rast1234** [comment]
Great idea, have to try it and probably document if it works well
