### ISSUE TITLE
Windows 11: Games not picking up controller after resume from sleep / hibernate

### ISSUE THREAD

**Issue by SirEvilJebus** [Ryochan7/DS4Windows#2401]
When resuming from hibernation or sleep, games don't seem to pick up the controller. It's recognised in DS4Windows and picks up all the button presses and stick movements but they don't seem to be passed on to the game itself. One it's rebooted it works fine but it then lost again after resuming from sleep or hibernation. Doesn't matter whether using a wired or bluetooth connection or changing USB ports, the pad is recognised but any of the input doesn't seem to be passed on although it is recognised in DS4W.

Is does the same whether using a DS4 or Dual Sense, I tried switching between them but neither are recognised by games until you reboot. I tried exiting DS4W and restarting it but still nothing until a reboot.

It did previously work flawlessly with Win10.  I know Win11 is currently in beta but though it might be worth mentioning

[aftersleep.txt](https://github.com/Ryochan7/DS4Windows/files/6931929/aftersleep.txt)

**Comment by Kanuan** [comment]
Might be related to this:
[The following link leads to a not-directly related, unofficial DS4Windows troubleshooting website that's under construction]
https://kanuan.github.io/DS4WSite/troubleshooting/xinput-slots-order/

There was other issues recently having the same issue on Windows 11, but we are not sure if it's an issue with Win11 that's causing the wrong xinput slot problem to a greater degree or just coincidence

**Comment by Ryochan7** [comment]
Unfortunately, my PC does not like to either Sleep or Hibernate properly so I cannot test this myself. I think my PC can handle Sleep from Linux but not Windows 10 for some odd reason.

Going to at least attempt to check the current behavior of the power management methods used in the app.

**Comment by Ryochan7** [comment]
I did as much as I can attempt to do. The Suspend and Resume routines have been tweaked slightly to make it a bit more readable. I doubt the few tweaks would help with this problem though. Will keep this open for now but it will be closed soon.
