### ISSUE TITLE
PS5 Controller Triggers

### ISSUE THREAD

**Issue by Khanssz** [Ryochan7/DS4Windows#2407]
Hi, Everytime i launch Cold War and play. There is an extremely high tension in the triggers when i shoot or ADS. I have my L2/R2 trigger effects off on my controller axis configuration but this still seems to happen. I have trigger haptics turned off in the Cold War Settings too. I have also turned it off on the PS5 but when i run/use ds4 windows ps5 controller for PC to play Cold War, the trigger haptics comeback. This issue does not occur in Warzone, just Cold War so far. Any Idea on how to fix this? Thank You!

**Comment by mika-n** [comment]
#1196 

closed until the pinned "Read this before posting a new issue ticket" post is read and understood. 
Anyway, the first thing to do with DS5 gamepads is to hook up those into PS5 console and update the firmware.
