### ISSUE TITLE
[Feature Request]only gyro udp server support mode

### ISSUE THREAD

**Issue by Fly-Cat-github** [Ryochan7/DS4Windows#2408]
Profiles set Disable virtual contoller = Enable
run steam can't find my ps5 contoller.
If you run steam first and then open DS4 windows,strange AB reversal and key setting problems will occur
like the:
https://www.reddit.com/r/DS4Windows/comments/oojq8a/using_ds4win_for_gyro_aiming_and_steam_input_for/
So I hope you can provide only gyro udp server support the mode.
like the: https://github.com/FrogTheFrog/steam-gyro-for-cemuhook

**Comment by Ryochan7** [comment]
I am looking at the repo code right now. You are wrong, mixing Steam Input and DS4Windows is invalid, and Reddit is demonic. Invalid ticket all around.

https://github.com/FrogTheFrog/steam-gyro-for-cemuhook/blob/b646887688c4ab6f7031056acf6c68ff57542980/src/backend/lib/steam-device/steam-hid-device.ts#L469
https://github.com/FrogTheFrog/steam-gyro-for-cemuhook/blob/master/src/backend/lib/udp-server/index.ts#L416

**Comment by Kanuan** [comment]
@Fly-Cat-github If you want to use Steam input for controller remapping but maintain DS4Windows for the UDP server, you need to:

- Disable the virtual controller in your profile settings
- Make DS4Windows run under a custom .exe name. Steam ignores playstation controllers if it detects DS4Windows is running

The following link leads to an unofficial, not-directly related DS4Windows website:
[Running DS4Windows under a custom name](https://kanuan.github.io/DS4WSite/guides/ds4w-custom-name/)
