### ISSUE TITLE
Cannot get DS4 to work properly with fortnite after updating.

### ISSUE THREAD

**Issue by ellagent** [Ryochan7/DS4Windows#2409]
Whenever I open Fortnite now any little movement transitions between PS5 Controller buttons and X360 buttons. I've tried the "Hide DS4 Controller" option. Uninstalled VigEmBus driver and FakeInput/HidHide and reinstalled all etc etc and still no success. Cannot get it to function no matter what I do.

**Comment by ellagent** [comment]
Someone please try to help me? Is anyone else having issues with DS4 since update?????? I'm using PS5 Controller and have never had issues except having to restart it after switching from Steam games to Epic games, now I have ZERO issues playing steam games and it reading but in Epic Games (specifically Fortnite) it COMPLETELY DOES NOT WORK!

**Comment by Kanuan** [comment]
This is exactly the type of stuff that pisses off developers: people installing random software or drivers without trying to understand why they are needed or how they work and then creating "help plz!" requests on the ISSUE TRACKER and even demanding to have a non-issue answered in less then a hour. __Not knowing how to use the things you install is NOT AN ISSUE!__ Fully expect this to get closed the instant a moderator appears. 

I'm going to give you a nice hint: there is an option around this page on the right side calling "__convert to discussion__". Use it to convert this issue in a discussion topic and maybe the moderators will be less pissed when they see this.

Nobody is goint to hand-hold you on this kind of stuff. I'm going to take my time to properly giver you the links that you need. Your job is to CAREFULLY READ THEM and understand the information being given. If you think it is too much text or whatever then it's your fault and you will continue to have problems. 

1. Information about the issue you are having and how to solve it: [_Preventing the double controller / double input issue in games_ page](https://kanuan.github.io/DS4WSite/guides/solving-double-input/)
2. [How to install and properly configure HidHide](https://vigem.org/projects/HidHide/Simple-Setup-Guide) 
3. This one I'll straight up tell you: the FakerInput driver is related to DS4Windows functions that make use of keyboard and mouse and therefore is unrelated to your current issue.

Good luck and nice reading!
