### ISSUE TITLE
[REQUEST] Can we get motion controls to work on remote/streaming computers?

### ISSUE THREAD

**Issue by grymfel** [Ryochan7/DS4Windows#241]
Brand new to GitHub so I hope I'm not out of turn on etiquette or some such. I asked a question on another post about a possible change to the IP address UDPServer uses, but never got a definitive response. It wasn't really the right thread for it, anyways, so I figured I'd post it here:

Can UDPServer be modified so that instead of listening on "ipaddress.loopback" (127.0.0.1) it listens on "ipaddress.any" (0.0.0.0)? That way people who are using a streaming application can have the host machine/software (Cemu via the cemuhook.ini file) looking for motion control data on the client side (Moonlight, Parsec, Steam, etc.), where DS4Windows is running.

I don't know if this opens any kind of gaping security hole or not. To go as far as making it enableable and customizable in the options (thanks for the idea rajkosto) might be even better, but would probably also add a lot more rewriting of code.

**Comment by Ryochan7** [comment]
It has been discussed before but I have not gotten around to working on it. That will be worked on at some point.

**Comment by mika-n** [comment]
This has been implemented few version releases already. The current DS4Windows + UDPServer supports "listen any public interface / specific interface" configuration option (and I know some people use it to access the DS4Windows/UDPServer service from outside of the local network. However, DS4Windows app itself doesn't include any kind of encryption/authentication so it is up to the user to setup secure extranet access via VPN pipes if needed).
