### ISSUE TITLE
Lightbar doesn't update

### ISSUE THREAD

**Issue by rainkeebs** [Ryochan7/DS4Windows#2410]
**Describe the bug**
Lightbar remains 100% brightness, white, regardless of settings.

**To Reproduce**
1. Turn on the controller
2. Change any lightbar option
3. Observe no change

**Expected behavior**
The lightbar should change color.

**Screenshots and Logs**
[log.txt](https://github.com/Ryochan7/DS4Windows/files/6948745/log.txt)

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: Windows 10 Pro Version 20H2, Build 19042.1110
 - DS4Windows Version 3.0.14

**Additional context**
:)

**Comment by Masamune3210** [comment]
looks like either that's not the whole log or it never found your controller. there should be a lot more after shared mode

**Comment by rainkeebs** [comment]
[log.txt](https://github.com/Ryochan7/DS4Windows/files/6948772/log.txt)
Here's (hopefully) a better one

**Comment by Masamune3210** [comment]
All I can see from a cursory glance is that the controller was disconnected at one point due to a read failure of some kind. Will take someone who knows about what they are talking about to help more

**Comment by rainkeebs** [comment]
That was just me turning off the controller 😅

**Comment by mika-n** [comment]
Lightbar in "Normal" mode seem to work here and the light is changed when I slide those RGB color sliders in DS4Windows profile editor. So, I assume this is just an issue in a fake cheap Chinese copy-cat DS4 controller you may have. Are you sure you have a genuine DS4 gamepad? Does it work over USB connection?

**Comment by rainkeebs** [comment]
It works over USB, and looks decently genuine. Something I forgot to note in the issue is that the light bar worked with Jays2Kings fork, but then not with this one.

**Comment by Kanuan** [comment]
Does rumble work? Check if the "Enable Output data to the controller" option is enabled on the profile editor' `Other` tab. Even if it's enabled, try disabling and enabling it again.

**Comment by mika-n** [comment]
Lightbar in Normal mode works here both in BT and USB mode, so difficult to say why it doesn't work there. The bad news is that problems like this are very common especially in BT mode when the gamepad is using non-genuine DS4 firmware.
Anyway, copy the profile file as xxxx.txt file and attach it here for closer inspection if you have something weird in the profile itself.

**Comment by rainkeebs** [comment]
just got another ds4 controlelr in today.... looks like my original one is a counterfeit. New one's lightbar updates instantly, touchpad works better, rumble works. Curious that the fake worked with the other fork of ds4win I mentioned previous (light bar and rumble) but not this one. Welp, thanks for the help :)
