### ISSUE TITLE
Latency Variation

### ISSUE THREAD

**Issue by Wafelesse** [Ryochan7/DS4Windows#2416]
**Hi

Since yesterday my latency has been looking like it:

08/07/2021 23:55:39: Controller 1's latency over 10ms (51 ms)

08/07/2021 23:55:39: Controller 1's latency now under 10ms

08/07/2021 23:57:16: Controller 1's latency over 10ms (50.9 ms)

08/07/2021 23:57:16: Controller 1's latency now under 10ms

08/07/2021 23:57:28: Controller 1's latency over 10ms (50.7 ms)

08/07/2021 23:57:28: Controller 1's latency now under 10ms

08/07/2021 23:59:40: Controller 1's latency over 10ms (51.45 ms)

08/07/2021 23:59:40: Controller 1's latency now under 10ms

08/08/2021 00:06:59: Controller 1's latency over 10ms (51.05 ms)

08/08/2021 00:06:59: Controller 1's latency now under 10ms

08/08/2021 00:10:12: Controller 1's latency over 10ms (50.9 ms)

08/08/2021 00:10:12: Controller 1's latency now under 10ms

Everything was okay until yesterday. I didn't change anything and  it started to happen. I already reinstalled DS4 3 times and nothing happens. I also uninstalled latest windows update, bunch of applications and scanned PC for viruses, nothing was found.

Do you have any solution?
Controller is connected by wire 

DS4 version 3.0.14
Dualshock 4 v2

**Comment by Kanuan** [comment]
99% chance of the latency problem to not be caused by DS4Windows itself.

Check the [Unofficial DS4Windows page regarding latency issues in Bluetooth](https://kanuan.github.io/DS4WSite/troubleshooting/input-delay-bt/)

**Comment by mika-n** [comment]
Try 
- different usb cables
- different usb ports (back and front panel ports, usb2 vs usb3)
- update .NET 5.x 64bit x64 libraries
- try the latest version of DS4Windows app and then compare the results one by one using older versions to see if any of the versions make any difference (you can install older versions into a separate new folder side by side with other versions)

https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#link-list

**Comment by Wafelesse** [comment]
> Try
> 
> * different usb cables
> * different usb ports (back and front panel ports, usb2 vs usb3)
> * different DS4 gamepad
> * remove all other USB devices and disable WIFI and BT in the PC
> * update .NET 5.x 64bit x64 libraries
> * try the latest version of DS4Windows app and then compare the results one by one using older versions to see if any of the versions make any difference (you can install older versions into a separate new folder side by side with other versions)
> 
> https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#link-list

I have to try different usb cable but
- already tried every port, still the same
- i dont have different gamepad
- my pc doesnt have either wifi or bt
- updated already
- im pretty sure i have the latest version

**Comment by mika-n** [comment]
`im pretty sure i have the latest version`

Yes, but the idea was to test one by one older versions side by side to see if certain version makes a difference.

**Comment by Wafelesse** [comment]
> `im pretty sure i have the latest version`
> 
> Yes, but the idea was to test one by one older versions side by side to see if a certain version makes a difference.

until the issue happened i used 1.4.52 version, then switched to the newest one hoping it will help

**Comment by Wafelesse** [comment]
I found a new usb cable and for now im pretty sure the issue was foulty cable
