### ISSUE TITLE
Battery percentage incorrect (Dualshock 4)

### ISSUE THREAD

**Issue by Boerny41** [Ryochan7/DS4Windows#2421]
The battery percentage shown is very inaccurat for me. No matter for how long I charge it, it won't go above 54% with wired connection. 
If I unplug it, and connect it via bluetooth, it jumps to 75% but again it won't go above no matter how long I leave it charging. 

At this battery level it will stay for a while untill dropping normally to 0% however it is not empty than but it got battery left for another 5 or 6 hours.

Until now I let it run out completly, charged it with the PS4 to make sure the PC-USB ports are not the problem, changed the cable, and reinstalled/relaunched DS4 a couple of times.

**To Reproduce**
I don't know if it is reproducible, if so, charge your controller.

**Expected behavior**
The correct battery percentage.

**Screenshots and Logs**
Log is attached
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/6951172/ds4windows_log.txt)

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 CUH-ZCT2E (don't know if it is "v.2")
 - OS: Windows 10 Pro 20H2 (19042.1151)
 - DS4Windows Version - newest

**Comment by Masamune3210** [comment]
Battery level is reported by the controller itself, so if it's lying to us there isn't much that can be done. I don't think it's a issue with DS4Windows or more people would likely be complaining

**Comment by asp0909** [comment]
This problem is occasional... some days it happens and others it doesn't! I know because I use the gamepad every day, and it is more frequent in dualsense

**Comment by asp0909** [comment]
This problem is occasional... some days it happens and others it doesn't! I know because I use the gamepad every day, and it is more frequent in dualsense

**Comment by Ryochan7** [comment]
When it comes to the DualSense, it might be best to update the controller's firmware now that the option is available for Windows users. I have not done it myself so my DualSense controller is still using day 1 firmware.

https://controller.dl.playstation.net/controller/lang/en/fwupdater.html

Doubt there can really be anything done within DS4Windows itself at this point. The battery level update event works and the level is interpreted as it even is on the PS4 based on my experience. People had complained about 0% appearing for so long when connected via BT despite a 0 bar battery icon showing up on the PS4 for a long time; don't have a PS4 or PS5 so I didn't get to experience the intended behavior until playing some Doom Eternal elsewhere. Going to mark this invalid until shown that something can be done within DS4Windows to improve battery level accuracy.
