### ISSUE TITLE
FIFA 21 crashes on start when I connect PS5 & PS4 controllers

### ISSUE THREAD

**Issue by MahmoudTarek** [Ryochan7/DS4Windows#2426]
Hello,

Thanks for the great app. It works fine when I connect my PS5 controller alone, but the game crashes when I connect both PS5 and PS4 controllers at the same time.

Is this common issue or am I doing something wrong?

**Comment by Kanuan** [comment]
Maybe it's related to the "double controller" issue? Are your physical controllers hidden on Windows? If not, when using both the DS4 and DS5 with DS4Windows you end-up with a total of 4 controllers (the 2 real ones and 2 virtual controllers created by DS4Windows). 

Don't know if this could be the case or possibly other issue, but it's worth testing. 

For more information about the double controller issue and how to prevent it, check here: https://kanuan.github.io/DS4WSite/guides/solving-double-input/

**Comment by MahmoudTarek** [comment]
Yes this exactly what happens, I find 4 controllers. Let me check the solution you provided. Thanks!
