### ISSUE TITLE
Doesnt work with steam, after win10 update

### ISSUE THREAD

**Issue by spooll** [Ryochan7/DS4Windows#2427]
DS4Windows version 3.0.15
Windows 10 20H2 (Build 19042.1151)
PS DualSense joy.

Hello there! :)
I think, it started since 20H1, all worked fine till that update.

If you choose DS4 Virtual Controller, STEAM cant recognize gamepad, with emulated XBOX controller, probably better, BUT Controller Companion shows that only 10 (instead of 14) buttons available for setup.
I`ve tried my best...

As issue report:

STEAM cant find joypad if DS4 controller emulated. Stop DS4 doesn`t help at all, you should EXIT program to find your device via STEAM.

[Active DS4Win](https://i2.paste.pics/ef8cdd04195776d157e8e1b34798c053.png)
[Stopped DS4Win](https://i2.paste.pics/3b03516493945be6b304c361804acc35.png)
[Quit from DS4Win](https://i2.paste.pics/af25ad6cef7c6b38ae97d5a056a43aff.png)

Heeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeelp!!! :(

**Comment by Kanuan** [comment]
https://kanuan.github.io/DS4WSite/guides/ds4w-custom-name/

**Comment by spooll** [comment]
I came to ask, because it works perfectly earlier, all crashed when win.update bring me new build.
After an hour, i think i fixed it with your help @Kanuan 

It shows 2 gamepad - PS4 and PS5 (PS5 The real one, PS4 - emulated.), and only ps4 can be set.
It`s much better, when you see what you get, but i think its fine, till STEAM will bring full PS controllers support.

Assassin's creed valhalla and steam, do the first step with partially PS5 controller features and this is awesome!
Appreciated for your help and best luck with projects! :)

**Comment by spooll** [comment]
Workaround finded 🥇
