### ISSUE TITLE
Controller Connects Successfully, but DS4W Does Not Detect It.

### ISSUE THREAD

**Issue by infolycal** [Ryochan7/DS4Windows#2430]
**│** *Describe the Issue*

I tried connecting my DS4 controller, In the windows settings, it successfully connects and maintains a stable connection meanwhile DS4W does not see the controller at all.

**│** *Expected behavior*
The controller is supposed to connect with no issues.

**│** *Screenshots and Logs*

```
2021-08-10 01:43:55.6202|INFO|DS4Windows version 3.0.16
2021-08-10 01:43:55.6285|INFO|DS4Windows exe file: DS4Windows.exe
2021-08-10 01:43:55.6285|INFO|DS4Windows Assembly Architecture: x64
2021-08-10 01:43:55.6285|INFO|OS Version: Microsoft Windows NT 10.0.19043.0
2021-08-10 01:43:55.6285|INFO|OS Product Name: Windows 10 Home
2021-08-10 01:43:55.6285|INFO|OS Release ID: 2009
2021-08-10 01:43:55.6285|INFO|System Architecture: x64
2021-08-10 01:43:55.6285|INFO|Logger created
2021-08-10 01:43:55.7144|INFO|LinkedProfiles.xml can't be found.
2021-08-10 01:43:57.3080|INFO|Running as User
2021-08-10 01:43:58.3753|INFO|Starting...
2021-08-10 01:43:58.3753|INFO|Using output KB+M handler: SendInput
2021-08-10 01:43:58.3753|INFO|Connection to ViGEmBus 1.17.333.0 established
2021-08-10 01:43:58.3753|INFO|Searching for controllers...
2021-08-10 01:43:58.3753|INFO|Using Exclusive Mode
```
![inScHixAE2](https://user-images.githubusercontent.com/44573650/128784680-05a8cee0-29f3-4e54-b770-a0eca61347c0.gif)

**│** *Desktop (please complete the following information):*
 - Controller Make and Model: Sony DS4 v.2 (Unknown? It's an original controller but the sticker on the back peeled off due to the amount of usage this controller has seen.)
 - OS: W10 Home 21H1
 - DS4Windows 3.0.16

**│** *Additional context*
I do not have HidGuardian installed, neither do I have HidHide.

**Comment by Kanuan** [comment]
1. Does your controller appears on the [gamepad Tester website](https://gamepad-tester.com/)? What is your controller's VID/PID there?
2. Open Windows' Device manager change the view to `Devices by container` and send a screenshot of your controller 

![image](https://user-images.githubusercontent.com/24910442/128785254-31803bc5-3792-4c0f-b326-0798f42eb73d.png)

**Comment by infolycal** [comment]
1. It does not appear.
2.
![image](https://user-images.githubusercontent.com/44573650/128785477-6abdd948-1209-482e-a07a-ee5130a2c577.png)

3. I had to restart my computer because I was installing an application, now whenever I connect the controller, It disconnects.

**Comment by infolycal** [comment]
> 1. Does your controller appears on the [gamepad Tester website](https://gamepad-tester.com/)? What is your controller's VID/PID there?
> 2. Open Windows' Device manager change the view to `Devices by container` and send a screenshot of your controller
> 
> ![image](https://user-images.githubusercontent.com/24910442/128785254-31803bc5-3792-4c0f-b326-0798f42eb73d.png)

1. It does not appear.
2.
![image](https://user-images.githubusercontent.com/44573650/128785477-6abdd948-1209-482e-a07a-ee5130a2c577.png)

3. I had to restart my computer because I was installing an application, now whenever I connect the controller, It disconnects.
4.

**Comment by Kanuan** [comment]
[Remove your controller from Windows' device list](https://kanuan.github.io/DS4WSite/troubleshooting/bt-connection-issues/#remove-a-paired-controller-from-windows) and [properly re-pair it to the computer](https://kanuan.github.io/DS4WSite/troubleshooting/bt-connection-issues/#pairing-it-to-windows-using-the-correct-method)

3. Following (2) from my previous comment, open the properties of `HID-Compliant game controller` inside your controllers containers -> Go to the `Details` tab and check if the Propertiy `Class Upper filters` exist and, if yes, send a screenshot of it

![image](https://user-images.githubusercontent.com/24910442/128785782-3a528552-a63b-4115-8070-e9813218c7d5.png)

**Comment by infolycal** [comment]
> Your controller is not properly paired to windows or your BT dongle is failing to let it reconnect after restart/suspend actions. [Remove your controller from Windows' device list](https://kanuan.github.io/DS4WSite/troubleshooting/bt-connection-issues/#remove-a-paired-controller-from-windows) and [properly re-pair it to the computer](https://kanuan.github.io/DS4WSite/troubleshooting/bt-connection-issues/#pairing-it-to-windows-using-the-correct-method)
> 
> If after PROPPERLY repairing (follow the instructions in the link /) the controller it still does not appear, then:
> 
> 1. Following (2) from my previous comment, open the properties of `HID-Compliant game controller` inside your controllers containers -> Go to the `Details` tab and check if the Propertiy `Class Upper filters` exist and, if yes, send a screenshot of it
> 
> ![image](https://user-images.githubusercontent.com/24910442/128785782-3a528552-a63b-4115-8070-e9813218c7d5.png)

That worked! Thank you for the help.
