### ISSUE TITLE
ds4 recognized as player 2 slot when plugged usb

### ISSUE THREAD

**Issue by davipinhati** [Ryochan7/DS4Windows#2432]
**Describe the bug**
when my ds4 runs out of battery i plug it in the usb to charge like everyone, when i do this ds4 recognizes it as players 2 controller, even whit no controller is pluged in player 1 slot, if i connect and disconnect again the slot changes to #3 player.

**To Reproduce**
 start pc and connect the ds4 in bt, so disconnect it and use the cable now, maybe you will need to restart the pc

**Expected behavior**
when plug ds4 in usb whit no other controller conected, it should stay in player 1# slot

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 cuhzct2a

**Additional context**
this just happens when i swap to bt to usb, if i charge my ds4 in any other device, this does not happen

**Comment by Kanuan** [comment]
Too much information missing:

1. Where is most of what is required on the ["Read this before posting a new issue ticket requesting help"](https://github.com/Ryochan7/DS4Windows/issues/1196 pinned post
1. What kind of slot? you mean in-game or the XInput Slots in XInputChecker?
1. Have you fully prevented the double input / double controller issue? 

All in all, it's impossible to offer help with so much missing information

**Comment by DeusMalsith** [comment]
Try re-installing the ViGEmbus driver. I had this issue along with another person and we both found that re-installing the driver fixed the issue. Before I had done that I found that "plugging in" outputs 1-4 was a temporary fix because each time you plugged in a USB cable the output would switch to the next output. So that at least had you covered.

**Comment by mika-n** [comment]
#2388 

It is because of "double controller issue" or "rolling xinput slot" issue. Read the linked duplicated ticket about these issues.

**Comment by davipinhati** [comment]
> #2388
> 
> It is because of "double controller issue" or "rolling xinput slot" issue. Read the linked duplicated ticket about these issues.

can you please link double controller issue ticket?

**Comment by Kanuan** [comment]
This a guide from a unofficial, non-directly related DS4Windows website

It explains why the issue happens and how to fix it

https://kanuan.github.io/DS4WSite/guides/solving-double-input/
