### ISSUE TITLE
Lightbar settings only take effect if DS4Windows opens after controller connects

### ISSUE THREAD

**Issue by jacksoncooper12** [Ryochan7/DS4Windows#2434]
My controller's lightbar is set to be off. If it disconnects because of idle timeout, or the Bluetooth connection is terminated, the lightbar returns to the previous color upon reestablishing the connection. Stopping and restarting fixes this, but it would be nice if the lightbar settings took effect regardless.

**Comment by Masamune3210** [comment]
The way it works on my system at least is the controller connects, controller defaults to blue, ds4windows grabs the controller and sets the mode and appropriate settings, if the controller disconnects and later reconnects the same things happen

**Comment by Ryochan7** [comment]
Just going to assume that Steam or some other app is interfering until proven otherwise
