### ISSUE TITLE
PS4 controller headphone audio not working

### ISSUE THREAD

**Issue by jamespui** [Ryochan7/DS4Windows#2435]
I have connected the headphone to the ps4 controller but only heard the buzz sound not the games sound from Steam ... seems like the controller not support audio jack (even connected by Wired/Bluetooth)?

**Comment by Kanuan** [comment]
The headphone/mic jack of the controller can only be used:

- With a DS4 version 2 only when wired
- With a DS4 version 1 or 2 wirelessly if the user is using the official Sony Wireless USB Adapter

In both cases a new audio device will be recognized by Windows as normal and the user must switch to it
