### ISSUE TITLE
Bluetooth PS5 controller on PC loses connection intermittently despite seemingly perfect condition?

### ISSUE THREAD

**Issue by DJ-Specter** [Ryochan7/DS4Windows#2437]
Hello - I posted this on Tom's hardware and didn't get any responses, so figured as I haven't been able to rule out the problem being due to DS4 windows, I would request some help from this group of fine people :) Please let me know if I can provide any more detailed info to diagnose! Logs of some kind, maybe? 

Hi everyone,

I bought a PS5 controller to use on my living room TV that has a gaming computer connected to it. The controller occasionally flickers red, signalling connection loss, then re-establishes connection. During games, this is obviously a big problem. The connection issue manifests in some locations in the room than others - resting the controller in my lap while I'm playing, while holding it up in front of my chest fixes it.

I have a PS4 with a PS4 controller that's literally on top of the computer, and that controller works absolutely perfectly from exactly the same distance - I can even walk out of the room and around the house, and it'll still control the PS4! So, it must be something to do with my computer's bluetooth setup. I know it's not the PS5 controller, because I also experience the same issue when I connect the PS4 controller to the computer.

The sofa is probably a little over 3 meters from the computer, so it can't be a range thing.

I use DS4Windows to facilitate communication between the controller and games - they released one for the PS5 controller (still confusingly called DS4Windows), so I'm using the latest version of that (3.0.14).

I thought it might have been the crappy £10 USB dongle I'd been using for years, so I invested in a more substantial one here: https://smile.amazon.co.uk/gp/product/B07Y2MYK4N/

I'm on the latest May feature update of Windows with all the recent updates (which I believe had some bluetooth tweaks in it). i7-7700k / Z170X-SOC FORCE / 16GB RAM / GTX980ti

It's so frustrating as the playstation handles the bluetooth controller situation perfectly, but somehow this is failing intermittently - any ideas guys?

Cheers in advance!

**Comment by Kanuan** [comment]
If it also happens to your DS4 then it must be a crappy BT adapter or radio interference near of it.

Check the following page: [troubleshooting high input delay/latency issues](https://kanuan.github.io/DS4WSite/troubleshooting/input-delay-bt/)

**Comment by Etaash-mathamsetty** [comment]
I remember having this issue on windows, then when I switched to linux, it was magically gone
so I don't think it's just having a bad bluetooth adapter, maybe drivers?
