### ISSUE TITLE
Failed to read serial# from a gamepad (0x054C/0x05C5) issue

### ISSUE THREAD

**Issue by alpturkay** [Ryochan7/DS4Windows#2438]
**Describe the bug**
I use a Cronus StrikePack to have back paddles on my PS4 controller. Whenever I plug my controller DS4 recognizes the controller as DS4 v.2. Whenever I plug my strikepack and controller I receive the following error message: 

"Failed to read serial# from a gamepad (0x054C/0x05C5). Generating MAC address from a device path. From now on you should connect this gamepad always into the same USB port or BT pairing host to keep the same device path."

This happens on some USB ports not all.

**To Reproduce**
I am unsure if you can without a strikepack but plugging in strikepack any port but the USB 3.0 port on the motherboard fail.

**Screenshots and Logs**
![image](https://user-images.githubusercontent.com/34047701/176481538-37b7738c-4646-4076-81eb-7c9cf6b742a4.png)
(https://github.com/Ryochan7/DS4Windows/files/9012121/ds4windows_log.txt)

**Desktop (please complete the following information):**
 - Controller Make and Model: DS4 v.2 and CronusMax (PS4 Mode))  [not sure why it says CronusMax]
 - OS: Windows 11 Pro 21H2
 - DS4Windows Version 3.0.18

**Comment by Ryochan7** [comment]
Not sure how the use of a Cronus StrikePack would affect reading a controller's serial number especially if it supposed works when connected on some USB ports. Maybe Steam is interfering somehow? Is Steam running? Even when PlayStation Configuration Support is disabled for Steam Input, I believe Steam will still open and do some form of configuration on a DS4 controller. I know I have encountered situations when something similar has happened but I cannot remember the scenario when it would become a major issue.

Maybe you can hide the controller with HidHide and see if the same behavior persists.

**Comment by Ryochan7** [comment]
I am not sure the recent changes would matter but you might want to try again. I found an issue with the DS4Windows project file where a compilation symbol was not being passed to the compiler that would affect the behavior of the HidDevice.ReadSerial method. The symbol was stripped out probably around version 3.0 when DS4Windows migrated to .NET 5. I would assume that the use of the Cronus StrikePack causes the other code path in that method to get executed which could cause issues for third party DS4 devices; almost everything else would not touch that code path. The use of different data types is needed there unfortunately.

```
            else
            {
                byte[] buffer = new byte[126];
#if WIN64
                ulong bufferLen = 126;
#else
                uint bufferLen = 126;
#endif
                if (NativeMethods.HidD_GetSerialNumberString(safeReadHandle.DangerousGetHandle(), buffer, bufferLen))
                {
                    string MACAddr = System.Text.Encoding.Unicode.GetString(buffer).Replace("\0", string.Empty).ToUpper();
                    MACAddr = $"{MACAddr[0]}{MACAddr[1]}:{MACAddr[2]}{MACAddr[3]}:{MACAddr[4]}{MACAddr[5]}:{MACAddr[6]}{MACAddr[7]}:{MACAddr[8]}{MACAddr[9]}:{MACAddr[10]}{MACAddr[11]}";
                    serial = MACAddr;
                }
            }
```

https://github.com/Ryochan7/DS4Windows/blob/master/DS4Windows/HidLibrary/HidDevice.cs#L498

**Comment by alpturkay** [comment]
Thanks for the reply. I just saw the first one. Replying both answers:

- I don't have Steam installed on the PC
- I updated DS4 but no luck. I think my case's USB ports are the problem. Mobo's USB ports work perfectly fine. This is a pretty cheap case, I am not very surprised to see an issue. 

USB ports on the case do work in general, but it somehow breaks DS4's reading capability. I would be willing to send more logs if necessary, in case this is something you want to take a look at.

**Comment by CompaSinner444** [comment]
![same issue](https://user-images.githubusercontent.com/113354869/189650564-d035d53a-ff30-424a-b524-333f44ffc6e0.PNG)
I have the same issue

**Comment by zachyingling** [comment]
I was able to recreate this issue with the CronusMax was having the same troubles. Here are a couple of things I used to help resolve this issue...

- Create two profiles (One for controller, one for paddles)
- The warning message went away whenever unlinking the ID/Profile from both devices
- In the paddle profile, make sure you aren't using the virtual controller setting
- In the controller profile, use an emulated DS4
- In the application's settings, enable "Hide DS4 Controller"

Although, I fixed the original thread issue, it doesn't take away that the "Link Profile/ID" checkbox doesn't want to work with this CronusMax device unfortunately. Found this out because I wanted to set special actions to the CronusMax device and not the DS4 device
