### ISSUE TITLE
Controller is disconnecting briefly in 1.4.116

### ISSUE THREAD

**Issue by Corrodias** [Ryochan7/DS4Windows#244]
The exact circumstances under which this happens are unclear, but I'll give you what detail I can.

I updated to 1.4.116 today, then started playing The Witcher 3. During combat, with a lot of action going on and the rumble feature being used, DS4Windows would claim the controller briefly disconnected and would request UAC authorization to get it back into exclusive mode. This disconnection happened pretty consistently, 3 fights in a row. I then switched back to 1.4.115 and was able to play for another hour, completing several more combat encounters, without it happening. Prior to today, I had also been using 1.4.115 with this game without incident.

Performing a rumble test (both heavy and light, individually or simultaneously) in 1.4.116 doesn't cause it to disconnect. I thought for sure that was going to be the cause, but apparently it's not that simple.

In the past, I've had trouble with a shoddy USB cable that would cause disconnections if bent in a certain way, but the cable that I'm using now has never given me trouble, and I was holding the controller nearly entirely still while playing when the disconnections occurred.

OS: Windows 7
DS4W Version: 1.4.116
Last good version: 1.4.115
Gamepad: Sony DS4, version 2 (CUH-ZCT2U)
Connection: USB

**Comment by Corrodias** [comment]
Well, never mind, it took quite a while, but it just happened in 1.4.115 as well. Now I'm not sure what to do with myself.

**Comment by Ryusennin** [comment]
I too have occasional disconnections with my average Micro-USB cable, especially when rumble starts to kick in. I think unfortunately the DS4 plug itself is not very reliable, and that's the reason why there is no real USB mode between the DS4 and the PS4 (your controller is *always* running in BT mode, USB is only used for charging the battery).

**Comment by Ryochan7** [comment]
I have experienced similar problems with USB cables and the DS4. I have swapped out two micro USB cables due to the connection getting loose over time. I might have to try that paper trick and check how much that changes the fit of the connection.

**Comment by Corrodias** [comment]
I snipped a narrow strip off a bit of paper, folded it in half, and put it in there under the plug. It's pretty snug. It behaved while playing for a few hours today, so that's a good sign.

My only worry would be that it might encourage the jack to loosen up more, over time, but if it's already sporadically disconnecting, I can't exactly make it a whole lot worse, eh?

At this point I think it's pretty safe to say the cause wasn't a defect in this software. I'll comment if anything interesting happens after this. Thanks for following along, and sorry for potentially worrying anyone with the report.

**Comment by Ryusennin** [comment]
It might not be entirely hardware. See new issue #247.

I have to say I'm getting a surprising amount of disconnections lately in driving games like Project Cars and Euro/American Truck Simulator, which I didn't experience that much in previous DS4Windows versions. For now I've disabled vibration entirely and the wired connection works stable so far, but I'm still not sure if the Micro-USB plug is the real culprit.

**Comment by Corrodias** [comment]
I will admit that I'm not certain that I had 1.4.115 before I updated. All I knew was that I updated to 116, then I downgraded to 115 and it seemed to help. But I may have had 113 or another version before the upgrade. It was precisely during vibrations that it would disconnect, but it's definitely not every time. My gut feeling is that DS4W might have somehow gotten more sensitive to a timeout.

Another nugget: The controller continued working fine in The Witcher 3 while this went on. It does support the DS4 natively. So I'm not 100% sure that it's Windows disconnecting the device briefly or if it was DS4Windows losing its connection and removing the emulated xinput device.

**Comment by Corrodias** [comment]
Okay, it just happened even with the plug snugged up by paper. There's no way the USB cable moving was the cause of this. I'll try 114, then 113 if it happens again.

**Comment by Ryusennin** [comment]
I've just spent an hour in Euro Truck Sim 2 with version 113 and I didn't encounter a single disconnection, despite vibration being quite active during my whole trip (I even toyed with the cable on occasion just to provoke disconnections, thankfully without success).

It's safe to say that some modifications in 114+ have made DS4Windows excessively sensitive to vibrations. Or could it be a bug with vibrations/gyro commands that trigger disconnections?

**Comment by Ryochan7** [comment]
I will have to look into it. There was a definite change to sending output reports in version 1.4.114. From the release notes for version 1.4.114.

_* Changed USB and SONYWA connections to use a dedicated output thread_

The reason for that was that it helped reduce input lag on my tests. I have only tested out rumble functionality in the profile options form and I have not encountered any disconnect problems when doing that. I will have to play something when the controller is connected via USB and see if I run into any problems; I primarily use a Bluetooth connection but I have been using the Sony adapter more lately for media viewing (mainly for headphone support).

**Comment by Corrodias** [comment]
Let me know if there's any kind of debug logging I can turn on to help diagnose **why** it decides it has lost the connection.

**Comment by Ryochan7** [comment]
I have played a couple of longer sessions of Euro Truck Simulator 2 while utilizing a USB connection but I did not run into any problems. I was running version 1.4.116.

**Comment by Corrodias** [comment]
I'm not intimately familiar with the game; does it feature much vibration? That seems to be a common thread with my disconnections and that other fellow's: they happened right around the time of strong vibrations. But it wasn't *every* vibration, and running a vibration test in the profile editor didn't cause one. The Witcher 3 vibrates frequently during combat, with hits and explosions.

**Comment by Ryusennin** [comment]
In my case, it's very easy to provoke disconnections with ATS/ETS2. I just drive with my truck on any rumble strip (sleeper line) and the pad will start vibrating gently. Up to DS4Windows v113, the wired connection remains stable for any duration. From v114 onwards, the pad will regularly disconnect/reconnect every few seconds.

**Comment by Ryochan7** [comment]
ETS 2 does support force feedback but most of the vibrations will be on the lighter side. Strong vibrations would likely only happen when crashing your truck. If driving on the strip is enough to get the problem to surface then I will have to try driving on the shoulder for a long period of time and see what happens.

ETS 2 is the only game mentioned so far that I can currently test. I own ATS but I never ended up running the Linux version enough to break the 2 hour mark; the purchase was made on SteamOS back in December and the game was run once so the purchase should have counted as a Linux sale. After the backpedal of a Witcher 3 SteamOS port, the Witcher 3 is on my boycott list so I would not even bother playing the Windows version or playing it on console.

**Comment by Corrodias** [comment]
Hmm... I'd test out some other games, but it's hard to know what we have in common. Here's my Steam game list. If you see something on there that you also have that you know vibrates a lot, I can try it on my system with 114+.

https://steamcommunity.com/id/Corrodias/games/?tab=all
(It turns out that Steam made game lists hidden from the public by default, now; you have to set it to public explicitly now for people to see it. Surprise, me!)

**Comment by ceedveed** [comment]
I'm using DS4Windows v 1.4.117 on Windows 7 using the official Sony wireless adapater with a DS4 v1.
I haven't had any disconnection issues with v1.4.112, but when I updated straight to 1.4.117, I was disconnecting during battle in Witcher 3. It will quickly reconnect, but I haven't experienced this before. Here is an excerpt from the log when it disconnects:

4/14/2018 11:41:34 AM: X360 Controller # 1 unplugged
4/14/2018 11:41:34 AM: Controller 1 was removed or lost connection
4/14/2018 11:41:35 AM: Found Controller:1C:96:5A:4A:2A:E4 (SONYWA)
4/14/2018 11:41:35 AM: Plugging in X360 Controller #1
4/14/2018 11:41:35 AM: X360 Controller # 1 connected
4/14/2018 11:41:35 AM: Controller 1 is using Profile “Xinput"
4/14/2018 11:41:46 AM: Controller 1's latency over 10ms
4/14/2018 11:41:47 AM: Controller 1's latency now under 10ms
4/14/2018 11:53:32 AM: Touchpad Movement is now Off
4/14/2018 12:49:39 PM: X360 Controller # 1 unplugged
4/14/2018 12:49:39 PM: Controller 1 was removed or lost connection
4/14/2018 12:49:40 PM: Found Controller:1C:96:5A:4A:2A:E4 (SONYWA)
4/14/2018 12:49:40 PM: Plugging in X360 Controller #1
4/14/2018 12:49:40 PM: X360 Controller # 1 connected
4/14/2018 12:49:40 PM: Controller 1 is using Profile “Xinput"
4/14/2018 12:51:43 PM: X360 Controller # 1 unplugged
4/14/2018 12:51:43 PM: Controller 1's latency over 10ms
4/14/2018 12:51:44 PM: Controller 1's latency now under 10ms

**Comment by Ryochan7** [comment]
I have finally reproduced the problem on my Windows 7 VM while testing Broforce; the problem does not occur when running Broforce on Windows 10. VirtualBox can just barely handle running Broforce but at least there was a game that I could test. At least now I can experiment and see what might make a difference.

Also, I guess I should have Windows 7 installed in its own partition rather than using a VM.

**Comment by Ryochan7** [comment]
The problem appears to be fixed. I was able to play Broforce for over half an hour without any problems and rumble was active a majority of the time. A new version of DS4Windows with this fix should be available sometime later today.

**Comment by Ryusennin** [comment]
Interesting that Win7 only seems to be affected. I've added my OS version in my bio profile for future reference.

**Comment by Ryochan7** [comment]
New version is now up.

https://github.com/Ryochan7/DS4Windows/releases/download/v1.4.118/DS4Windows_1.4.118_x64.zip

**Comment by Ryusennin** [comment]
I extensively drove half an hour over rumble strips in both ATS and ETS2 with v118, and I didn't encounter any disconnection. In v114~117 it would happen repeatedly in a matter of seconds. Thanks for your hard work!

**Comment by Corrodias** [comment]
I assume you made that section threaded for a reason, so it's unfortunate the only clear way to stop it is to undo that, but it ought to be a pretty darn solid fix, at least.
