### ISSUE TITLE
NET 5 is EOL make it NET6 then 

### ISSUE THREAD

**Issue by techdexiss** [Ryochan7/DS4Windows#2440]
net 5 is end of life so make it net6 so people dont install not secure frameworks

**Comment by Masamune3210** [comment]
You do realize that's generally not how frameworks work, right? The amount of things that still require VS Redists below latest should probably have been a clue

**Comment by Seeloewen** [comment]
Changing the .NET Version isn't as easy as you think, there is a lot of stuff that can break. Also, why shouldn't it just stay on .NET 5? It still is secure even after its EOL, why should MS release versions that get unsecure after just some months?

**Comment by Ryochan7** [comment]
Microsoft killed .NET 5 pretty quickly. Haven't started on migrating to .NET 6 for my Steam Controller test mapper but that will probably happen shortly. Besides the app, the FakerInput client library and ViGEmClient library would have to be updated to target .NET 6 as well. Getting the libraries ready will likely be the more difficult task. I would assume there would be no performance regressions but I would have to check and make sure.

Any update for DS4Windows would likely happen after those tasks are done.

**Comment by techdexiss** [comment]
> Changing the .NET Version isn't as easy as you think, there is a lot of stuff that can break. Also, why shouldn't it just stay on .NET 5? It still is secure even after its EOL, why should MS release versions that get unsecure after just some months?

yes no security updates since  November 10, 2020 is surely a good idea :-) 
Its not just the net version also the package dependencies and there is a lot of them.
And yes most of the time it is as easy as switching the version.
sure in this case its not just switching the versionnumber, i tried it and there will be some problemes but it should be done anyways

good look and thank you to ryochan7

**Comment by snr-k** [comment]
Hi, I had the same issue and found this video https://www.youtube.com/watch?v=Z7T0H85MUdg
Its working for me now :)

**Comment by Masamune3210** [comment]
> > Changing the .NET Version isn't as easy as you think, there is a lot of stuff that can break. Also, why shouldn't it just stay on .NET 5? It still is secure even after its EOL, why should MS release versions that get unsecure after just some months?
> 
> yes ... no security updates since  May 10, 2022 is surely a good idea :-) 
> Its not just the net version also the package dependencies and there is a lot of them.
> And yes most of the time it is as easy as switching the version.
> sure in this case its not just switching the version number, i tried it and there will be some problems but it should be done anyways
> 
> good look and thank you to ryochan7
> 
> 

The impetus is on the dev to change the framework when they need to, usually for newly offered features, security issues due to framework version changes almost never occur 


@snr-k please don't comment unrelated things on issues

**Comment by Ryochan7** [comment]
Made the initial move to using .NET 6 for my Steam Controller test mapper; that app uses mostly the same software stack with a few exceptions. Fortunately it didn't take much work and performance feels better in .NET 6. The most work was on the ViGEm.NET library as the previously used version was targeting .NET Core 2.2. I can make some .NET 6 migration tests on my old local copy of DS4Windows but it looks like I complicated some other matters that were in the works. Going to have to wait and see what happens.

**Comment by PaulusParssinen** [comment]
.NET 5 to 6 transition should be trivial and there _shouldn't_ be any breaking changes for this project functionality.

**Comment by Ryochan7** [comment]
The first step has been done and my current Steam Controller mapper is now using .NET 6. The only major issue I ran into was that it looks like the behavior of the Garbage Collector changed so the GarbageTask workaround used in DS4Windows had to be implemented. It seemed to be the only way to keep memory usage down while maintaining a desired performance level; oddly, .NET 5 did not have this problem and memory usage was well controlled even when using server-mode garbage collection mode.

**Comment by PaulusParssinen** [comment]
That GC hack seems pretty bad so I think it'd be better to start tackling the underlying reasons that are causing that memory usage. I have begun to slowly refactor/clean the project in [my draft fork](https://github.com/PaulusParssinen/DS4Windows/tree/code-maintenance) and I'll have a look at that memory use. It'd be pretty helpful if others could also provide traces or/and dumps showing the memory use getting out of control.

**Comment by Ryochan7** [comment]
Tested the change to .NET 6 locally and app performance is definitely better in .NET 6; part of the improvement is probably from migrating the ViGEm.NET library to target .NET 6. Going to let DS4Windows run for a while but memory usage seems normal.

**Comment by Ryochan7** [comment]
> That GC hack seems pretty bad so I think it'd be better to start tackling the underlying reasons that are causing that memory usage. I have begun to slowly refactor/clean the project in [my draft fork](https://github.com/PaulusParssinen/DS4Windows/tree/code-maintenance) and I'll have a look at that memory use. It'd be pretty helpful if others could also provide traces or/and dumps showing the memory use getting out of control.
> 
> I also updated the [ViGEm.NET to .NET 6](https://github.com/ViGEm/ViGEm.NET/pull/16) just a moment ago so that might help you too smiley

Part of the big issue is my insistence on using server-mode garbage collection rather than the default workstation mode. The performance difference is huge between the two modes. Can only affect memory usage so much as the behavior is dependent on the underlying runtime. I haven't found any major memory leaks in my own code but the runtime continues to keep unreferenced objects in memory for a long time.

**Comment by PaulusParssinen** [comment]
> >...
> 
> Part of the big issue is my insistence on using server-mode garbage collection rather than the default workstation mode. The performance difference is huge between the two modes. Can only affect memory usage so much as the behavior is dependent on the underlying runtime. I haven't found any major memory leaks in my own code but the runtime continues to keep unreferenced objects in memory for a long time.

I see. Well, I'll have atleast have a look at it. I believe I'll be able to eliminate big chunk of allocations once I get there. First I'm trying to untangle these god classes a bit and maybe seperate code to own projects and other clean-ups. There's a lot of low-hanging fruits in there 😅

**Comment by PaulusParssinen** [comment]
Just now I found out about https://github.com/CircumSpector/DS4Windows and that project seems to have done what I was planning to do.. Oops

**Comment by nefarius** [comment]
> Just now I found out about https://github.com/CircumSpector/DS4Windows and that project seems to have done what I was planning to do.. Oops

Aye, we had quite the run the last couple months 😛

**Comment by Ryochan7** [comment]
The .NET 6 change has been made to the `jay` branch.

**Comment by sitiom** [comment]
> .NET 5 to 6 transition should be trivial and there _shouldn't_ be any breaking changes for this project. You can follow this chart and see if the project or its dependecies use any of the following: [docs.microsoft.com/en-us/dotnet/core/compatibility/6.0](https://docs.microsoft.com/en-us/dotnet/core/compatibility/6.0)

I agree. Porting .NET Framework to Core was quite more work (https://github.com/Ryochan7/DS4Windows/pull/1875).

**Comment by sitiom** [comment]
> Just now I found out about [CircumSpector/DS4Windows](https://github.com/CircumSpector/DS4Windows) and that project seems to have done what I was planning to do.. Oops

Looks promising. I have made a PR to scoop for this (https://github.com/ScoopInstaller/Versions/pull/573). @nefarius You wouldn't mind, right? I see the [pre-release](https://github.com/CircumSpector/DS4Windows/releases/tag/v3.1.908) has disabled auto-updates; Scoop would certainly help for easy updating.

**Comment by nefarius** [comment]
> > Just now I found out about [CircumSpector/DS4Windows](https://github.com/CircumSpector/DS4Windows) and that project seems to have done what I was planning to do.. Oops
> 
> Looks promising. I have made a PR to scoop for this ([ScoopInstaller/Versions#573](https://github.com/ScoopInstaller/Versions/pull/573)).
> 
> @nefarius You wouldn't mind, right? I see the [pre-release](https://github.com/CircumSpector/DS4Windows/releases/tag/v3.1.908) has disabled auto-updates; Scoop would certainly help for easy updating.

I don't mind but we have a few changes in mind anyway:

- Name change to not confuse users since there won't be a collaboration between the repositories
- Our own auto updater framework and installer once we're at a certain stage

Feel free to continue this discussion over on the other repo.

Cheers

**Comment by sitiom** [comment]
> Feel free to continue this discussion over on the other repo.

The repo is still limited to collaborators 🤔

**Comment by nefarius** [comment]
> > Feel free to continue this discussion over on the other repo.
> 
> The repo is still limited to collaborators 🤔

Haha, oh yeah, right. I'll see what I can do later 😉

**Comment by Kanuan** [comment]
@sitiom you can continue this discussion in the [CS's DS4WDocs repository](https://github.com/CircumSpector/DS4WDocs/discussions) for now while we decide how to proceed regarding keeping the main repo locked or not.

Let's not flood this issue tracker with discussions that are not directly related to it.

**Comment by Ryochan7** [comment]
With the initial migration published, now I am working on some related secondary items. Updated the dependency NuGet packages to the latest versions; only ended up updating System.Management with the last stable build. Had to make some code changes to migrate the project to use H.NotifyIcon.Wpf.

Still satisfied with most of the packages that are used but I don't really like the WPF Extended Toolkit anymore. Although I don't see myself changing to a different controls package for DS4Windows.

Lately, I have playing around with the HandyControl package instead and I am liking it. It has many more bundled controls that might come in handy and some nicely put together themes. The official docs are in Chinese so I have to use the docs from a forked version of the project to get documentation written in English.

https://github.com/HandyOrg/HandyControl

Going to leave this issue open until version 3.1.1

**Comment by sitiom** [comment]
> With the initial migration published, now I am working on some related secondary items. Updated the dependency NuGet packages to the latest versions; only ended up updating System.Management with the last stable build. Had to make some code changes to migrate the project to use H.NotifyIcon.Wpf.
> 
> Still satisfied with most of the packages that are used but I don't really like the WPF Extended Toolkit anymore. Although I don't see myself changing to a different controls package for DS4Windows.
> 
> Lately, I have playing around with the HandyControl package instead and I am liking it. It has many bundled controls that might come in handy and some nicely put together themes. The official docs are in Chinese so I have to use the docs from a forked version of the project to get documentation written in English.
> 
> [HandyOrg/HandyControl](https://github.com/HandyOrg/HandyControl)
> 
> Going to leave this issue open until version 3.1.1

@Ryochan7 you might be interested with this one: https://github.com/lepoco/wpfui
