### ISSUE TITLE
Left and Right stick not working

### ISSUE THREAD

**Issue by joinhc** [Ryochan7/DS4Windows#2444]
i have a thunderobot G50 gamepad, when i connect it via USB port, DS4Windows dectect it as a switch pro controller.
and is just fine with me.
but the problem is both left and right stick reads are going crazy left top, not centered.
i've try new default proflie, not working.
and the funning thing is, when i open gamepad-tester.com, both sticks reads shows good.
so i dont know how to deal with this, i need help, please.

**Desktop**
 - Controller Make and Model: thunderobot G50
 - OS: Windows 11(21H2)
 - DS4Windows Version 3.0.18

screenshot:
![controller2](https://user-images.githubusercontent.com/40158305/177021909-e1fbf61c-5aa8-452c-b83c-a55e2b3ddf50.png)

ds4windows log:
[controller.txt](https://github.com/Ryochan7/DS4Windows/files/9033965/controller.txt)

**Comment by Ryochan7** [comment]
Not sure what the problem would be. Maybe something is wrong with the stick calibration data that is generated? The current routine works with my official Nintendo Switch Pro and Joy-Con controllers. All I know is that at least DS4Windows handles the controller handshake and the input reader thread is active. Not much that can be done without the hardware to examine.

**Comment by gitlucc** [comment]
happens to me with an official switch pro controller.
i have to disconnect my controller, close ds4windows, open it again then connect my controller.
