### ISSUE TITLE
Controller disconnects when trying to use new profile

### ISSUE THREAD

**Issue by dwazirl** [Ryochan7/DS4Windows#2447]
When creating a 'New Profile' in DS4W it disconnects the DS controller and it cant be seen by PC and/or Playstation Plus.

It appears to happen when changing the 'Emulated Controller' option on the 'Other tab' from 'Xbox 360' to 'DualShock4' and clicking 'Save' profile

When switching back to 'Default' profile it is detected instantly by PC and/or Playstation Plus. but 'Default' profile is set to 'Xbox 360' and the Touchpad cannot be configured.

**Comment by Ryochan7** [comment]
This sounds more like behavior related to the virtual output controller. That will vary per app depending on controller type and maybe controller order. Is the real input DS4 hidden from the system using HidHide? For the most part, the assumption is that a game or app would only accept gamepad input from an Xbox 360 controller. The few apps that can read a DS4 would likely try to read from the input DS4 first if the controller is not hidden from the system.
