### ISSUE TITLE
Touchpad and Gyro passthru is not working

### ISSUE THREAD

**Issue by realschokk** [Ryochan7/DS4Windows#2454]
Touchpad and Gyro passthru is not working, tried everything, different versions of vigem, ds4, it doesn't work

Logs and screenshots
[log.txt](https://github.com/Ryochan7/DS4Windows/files/9073905/log.txt)
![image](https://user-images.githubusercontent.com/108944838/178038478-7d706654-2eba-4658-ab19-24aa3ffe01e7.png)
![image](https://user-images.githubusercontent.com/108944838/178038490-cecdd5e4-0e6a-4500-911b-784814e3f5f0.png)
![image](https://user-images.githubusercontent.com/108944838/178039315-3f5fe212-6608-4ca1-8769-71ac4ff2e8b0.png)

 - Dualsense
 - Windows 11 x64
 - Vigem 1.17.333 

 - DS4Windows Version 3.0.18

**Comment by Kanuan** [comment]
## General info

- Touchpad passthru is broken when a DualSense is being used in the current Ryochan7's latest version. Gyro I don't recall, but it should be working as expected
- You can use the following custom version for now which has the fix already applied for the TP Passthru while Ryo7's version doesn't have the fix: [CircumSpector's DS4Windows release page](https://github.com/CircumSpector/DS4Windows/releases)
    - Once R7's version has a new release with the issue fixed I'll delete the CircumSpector's release to prevent confusion on the user base

# For the devs / Ryo7

- The commits you need are for the touchpad conversion fix can be found in [this PR](https://github.com/CircumSpector/DS4Windows/pull/1/commits)
- I've found and fixed some other issues, like settings not saving or wrong UI bindings. I'll make a list of the ones that I think are of your interest so you don't have to dig through the commit history

**Comment by Ryochan7** [comment]
@Kanuan I'll have to take a look at that PR in a bit. Tbh, I don't think I have ever test DS4 Extended output while using the DualSense. Always tested it against the DS4 and both passthru modes were working with my DS4 the last time I tried it.

**Comment by Ryochan7** [comment]
Finally got around to checking that PR. Confirmed the problem and made the change with commit e17caca21bf532da1cefb069eb1e3408b81979d3. Thank you for finding and fixing that problem.

Trying to get around to making a new release. Still need to test a few more things.
