### ISSUE TITLE
[Question] DS4 Windows Administrator rights - UAC

### ISSUE THREAD

**Issue by lorenzolazzarato** [Ryochan7/DS4Windows#246]
Hi, is there any way to execute the program without administrator rights and to execute it without the UAC prompt popping up? It's especially annoying if you choose to make Ds4 windows run at startup.

**Comment by vpontin** [comment]
For startup you could shedule the launch on task scheduler, and setting the highest priority for the task.

**Comment by Ryochan7** [comment]
The task scheduler method is the only workaround. Otherwise, you have to disable the **Hide DS4 Controller** option in the Settings to not have DS4Windows bring up the UAC prompt when connecting a controller.
