### ISSUE TITLE
exclusive mode requires pressing "stop" and "start" button to work when gamepad is connected on windows 11

### ISSUE THREAD

**Issue by soredake** [Ryochan7/DS4Windows#2462]
**Describe the bug**
When i connect gamepad while some game/app like yuzu is running exclusive mode is not working, but if i press "start" and "stop" button it works.

**To Reproduce**
1. Connect gamepad while yuzu is running
2. Oh no exclusive mode is not working!
3. But it works after pressing buttons.

**Expected behavior**
I dunno, ds4windows can do this automatically?

**Screenshots and Logs**
If applicable, add screenshots to help explain your problem. Also, please add the most
log file (ds4windows_log.txt) from the Logs folder in your DS4Windows config folder.

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2E)
 - OS: [e.g. Windows 11 Pro
 - DS4Windows Version 3.1.0

**Additional context**

**Comment by marlop352** [comment]
If you are not using HidHide I would highly recommend doing so.
HidHide Simple-Setup-Guide: https://vigem.org/projects/HidHide/Simple-Setup-Guide/
Remember to add DS4Windows to the list of allowed applications and to disable the hide DS4 option on the DS4Windows settings, after a reboot everything should be working.

**Comment by Ryochan7** [comment]
HidHide is the only really useful way to get Exclusive access working nowadays. Many apps, including Windows bundled apps (Windows Store), interfere with the old Hide DS4 Controller workaround. Tried to remove the Hide DS4 Controller option from DS4Windows before and people did not like that.

https://vigem.org/projects/HidHide/Simple-Setup-Guide/

**Comment by soredake** [comment]
Can ds4windows installer install hidhide and configure it by default?

**Comment by soredake** [comment]
I realized that ds4windows already have button to install hidhide.
