### ISSUE TITLE
3.1.0 update opens invalid URL and prompts for actions that don't result in updating

### ISSUE THREAD

**Issue by adamlwgriffiths** [Ryochan7/DS4Windows#2463]
**Describe the bug**
When starting up DS4Windows, the 3.1.0 update prompt appears:
![image](https://user-images.githubusercontent.com/1239156/178174038-11e7e231-24d1-4045-aea1-bd56934904ef.png)

Pressing "yes", leads to a "windows command processor" allow prompt, which then leads to this message box:
![image](https://user-images.githubusercontent.com/1239156/178174104-c90ba2c4-d0b3-4341-8726-77116db4363a.png)

Which then opens the following URL:
![image](https://user-images.githubusercontent.com/1239156/178174172-85646d6c-6270-4c4c-824b-0462ee337cad.png)

That URL should infact be:
https://github.com/Ryochan7/DS4Windows/releases/tag/v3.0.18/DS4Updater.exe
ie, /s/DS4Updater/DS4Windows/

Having gone to the correct url, the message box prompt (replace DS4Updater) doesn't match the files available to download.
It's not clear what the correct course of action is here.

**Desktop:**
 - DS4Windows Version 3.0.18

**Comment by adamlwgriffiths** [comment]
Taking the 3.1.0 updater out of the DS4Windows archive and placing it in the installation directory (Program Files/DS4Windows) results in:
![image](https://user-images.githubusercontent.com/1239156/178174666-da2a32ca-04f8-4ae4-ad28-819c3110fbb0.png)

I had to run the updater binary specifically as administrator.

After having done this, DS4Windows is now at 3.1.0.
![image](https://user-images.githubusercontent.com/1239156/178174720-4b164c04-f922-4f14-9d75-3bd2acd25d48.png)

**Comment by Ryochan7** [comment]
Looks like the original attempt to download DS4Updater_x86.exe failed but that method would have used the proper URL. The code that calls that MessageBox does generate the wrong URL though. Should clean up the RunUpdaterCheck method and probably move that to a ViewModel finally. There is a lot of code still contained in the MainWindow class code behind that really should not be there; took the easy way out when making the initial migration from Windows Forms to WPF with DS4Windows 2.0.

**Comment by adamlwgriffiths** [comment]
I hadn't had any issues previously with your updater, in fact it was quite seamless.
Not sure what changed.
