### ISSUE TITLE
Unable to set axial deadzone when radial sensitivity map is enabled

### ISSUE THREAD

**Issue by GeraltV47** [Ryochan7/DS4Windows#2465]
**Describe the bug**
There is just no possibility to set up an axial, permanent deadzone for all range of both X and Y axies, when sensitivity map is set to radial, then after the stick reach the deadzone border it is being disabled resulting in less accuracy when aiming at minimal horizontal/vertical degree.

**Comment by Ryochan7** [comment]
Sensitivity does not get used when using Axial Deadzone by design; I double checked the back end code as well. Sensitivity is an old carry over that does not provide much configuration over the axis output. Settings Dead Zone and Max Zone settings offer a bit more control over the output and it is the only method available for editing the base axis output when using Axial.

**Comment by GeraltV47** [comment]
i just mean that when the axis output will cross the deadzone border, there is no possibility to make micro moves, and when setting axial deadzone, when applying curve there is almost impossible to make circle move with the stick, it just makes rhombus instead
![dz](https://user-images.githubusercontent.com/75566547/178413202-cb20722b-960e-438a-9d62-b23c36997e35.jpg)

**Comment by GeraltV47** [comment]
it should look like this:
![dz2](https://user-images.githubusercontent.com/75566547/178414116-ca95ba88-edc9-427d-beff-03908dfc46e2.jpg)

**Comment by GeraltV47** [comment]
When using the mouse emulating in shooter games i found aiming at the angles between for example to the right - in like 89/91degree almost impossible, it jumps from 85 to 95 instead, making aiming in horizontal a very difficult, setting the deadzone to axial doesnt solve this issue, i found also very difficult aiming in WarThunder, where near centre aiming is really nice, but after leaving the deadzone, aiming in horizontal/vertical is very limited because there is no adjustable deadzone, my suggestion is to add two types of deadzone at once - axial and radial, preserving the radial style of aiming, where the output and curve apply points are still coordinated in one line with the centre.
