### ISSUE TITLE
Versions 1.4.115 and up disconnect my DS4 upon any vibration

### ISSUE THREAD

**Issue by Stoofoo** [Ryochan7/DS4Windows#247]
Any version of DS4Windows version 1.4.115 and onwards has an issue on my PC where it will quickly disconnect on any sort of vibration, and reconnect seconds afterwards. This always repeats.

The last version where this doesn't occur is version 1.4.113.

It's directly connected via USB.

**Comment by Ryusennin** [comment]
Bluetooth or USB?

**Comment by Stoofoo** [comment]
Direct USB connection. Didn't mean to leave out details like that.

**Comment by Ryochan7** [comment]
Similar to issue #244. This problem also affects version 1.4.114. Version 1.4.113 does not have this problem.

**Comment by Stoofoo** [comment]
Late, but I wanted to mention testing with 1.4.117. My DS4 still disconnected on vibration, but I can note that this took minutes longer than it did before, where the disconnect was often seconds after vibration.

[DS4Windows 1.4.117 Log.txt](https://github.com/Ryochan7/DS4Windows/files/1917153/DS4Windows.1.4.117.Log.txt)

**Comment by Ryochan7** [comment]
I was finally able to reproduce the issue in a Windows 7 VM and fix it last night. Oddly enough, the disconnect problem never occurred for me when running DS4Windows on Windows 10. A new version of DS4Windows with the fix has been uploaded.

https://github.com/Ryochan7/DS4Windows/releases/download/v1.4.118/DS4Windows_1.4.118_x64.zip

**Comment by Stoofoo** [comment]
Sounds good. I'll give it a shot later and report back with results.

**Comment by Stoofoo** [comment]
Tested 1.4.118 with GRID, and there were zero disconnects upon vibrations. No issues. Thanks a lot.
