### ISSUE TITLE
Feature request: support for ARM64

### ISSUE THREAD

**Issue by jorbig** [Ryochan7/DS4Windows#2470]
Since ViGEmBus [finally works](https://github.com/ViGEm/ViGEmBus/issues/83#issuecomment-1169920601)  on ARM64, will you support this as well?

**Comment by Ryochan7** [comment]
That would be up to somebody else via a PR. I don't have any ARM64 hardware to test anything on.

**Comment by ballo** [comment]
Why close this? Just because you don't have the hardware currently doesn't mean this isn't an issue
