### ISSUE TITLE
3.1.0 copycat vibration&LED color issue (3.0.18 was fine)

### ISSUE THREAD

**Issue by psycodeoday** [Ryochan7/DS4Windows#2471]
Two clones of PS4 pads. Kruger&Matz GP-200 (different year production, well made, not the cheapest ones)

DS4 v1 (mainboard rev.1) works fine with all versions.
and
DS4 v2 (mainboard rev.2, different BT chip) works fine up to 2.1.0 version but with high latency delay during games)
above 2.1.0 there is no vibration and no LED color and also high latency.

in 3.0.18 version there is possibility to go to Settings-> device options-> ds4 v.2 ->and select/apply "copycat" checkbox.
after that it works as it should be (vibration, LED color are back and no high latency delay)

**but new 3.1.0** version brakes it again. No matter if the "copycat" checkbox is selected or not - the DS4 v.2 have no vibration and LED color anymore, but there is no latency lag as it was in 2.1.0

When I start 3.0.18 (portable), then vibration and colors works fine again, so it looks like the issue is in 3.1.0

**Comment by Ryochan7** [comment]
Going to have to check the default copycat flags but I thought I carried the most recent changes over. Ended up changing the default feature flags that are used for the DS4 to remove the use of audio flags in the output report. The change allowed simplifying keeping rumble output from muting the headphone and mic volume levels if you use the DS4 headphone jack; had to use a monitor class for select devices to make it work before.

Those flags had not been documented anywhere that I ever found IIRC. I found them just by playing around.

Also, which version of Windows are you using? In case the flags are fine, I need to know if you are still running Windows 7 or not. Several Windows 7 BT workarounds were intentionally removed with the latest DS4Windows release. Windows 7 will not be supported moving forward. Besides, Windows 8.1 is getting the ax from Microsoft next January.

**Comment by Ryochan7** [comment]
Yes. The feature flags change was carried over; actually still using the Speaker Volume feature flag although that won't really matter. The main use for the Copycat setting was to remove the use of the Flash flag since it was discovered to be the main incompatibility with copycat DS4 controllers. The Flash flag is still not used when the Copycat settings is enabled.

At this point, I am going to assume you are running Windows 7 so Bluetooth support just no longer works.

**Comment by psycodeoday** [comment]
thank you for answer.
Unfortunately, I'm using clean, fresh Windows 10 64bit ver 19044 updated to today. 

And also usb bluetooth 5.0 dongle with chip realtek 8761buv

Pad cannot be faulty, because I have third pad, the same one.

All three are the same brand and model but different year production. I've took them apart and the best one is the earlier production rev 1 with larger chips with legs 
And two newest ones are rev2 with small bga chips inside and those required 2.1.0 or "copycat" checkbox selected In 3.0.18. And as I said in 3.1.0 vibration and color stops working.

So they have used newest generation bt chips on the beards but worst than older, bigger one? I bet they don't even know about this complications.

**Comment by psycodeoday** [comment]
DS4 v.1 which is working fine with all versions has **mainboard code: G-C18077-191107-V1.1** (191107 I think is the date: 2019 11 07) and it's using large **ATS2819 Bluetooth chip**. 
I've attached PDF datasheet (very detailed one, maybe it will help you in some way)

**Link:** [DS4 v.1 ATS2819_Datasheet.pdf](https://github.com/Ryochan7/DS4Windows/files/9125710/ATS2819_Datasheet_V1.9.pdf)

mainboard pictures:
![v1-1](https://user-images.githubusercontent.com/9746260/179354671-50df7c93-f063-42d4-9048-9857c44cc045.jpg)
![v1-2](https://user-images.githubusercontent.com/9746260/179354703-752fb5f7-3137-4e5b-ae06-8cab4d7fdc51.jpg)




DS4 v.2 works fine up to 2.1.0 (with lag) or with "copycat" enabled in version 3.0.18 (fine without lag). 3.1.0 breaks it again. 
The mainboard code: **HP4-077-V0.2** (date 2021 08 19, so it's newer that the first one). 
It's using smaller ** Bluetooth chip BP02650** - which must be a china clone of something typical, but unfortunately I cannot find any information about this chip model.

mainboard pictures:
![v2-1](https://user-images.githubusercontent.com/9746260/179354742-e466b2b7-0f5a-4fb9-9932-9a642dd8da70.jpg)
![v2-2](https://user-images.githubusercontent.com/9746260/179354745-6961d204-bdd6-4b83-ad9a-625e2b11446a.jpg)

![gp-200](https://user-images.githubusercontent.com/9746260/179355027-13c17c37-1e46-4560-8468-14fdcc45eb09.jpg)

**Comment by psycodeoday** [comment]
I've noticed new 3.1.1 version. I've seen changelog, and understand that there is no new changes about broke "copycat" feature (on some pads) . But I've checked it anyway, and still the same - one pad is working fine, and those two v.2 no color and vibration.

I wonder, why you cannot add another special checkbox option with clear warning "this is not recommended/do it to your own risk" - to bring back older version of copycat from 3.0.18 for people who want to have fresh newest code changes and bugs fixes, but with old full working copycat feature to bring some game pads to full operate? 
Because now I'm forced to use 3.0.18 to have vibration in all three pads.

**Comment by DevL0rd** [comment]
Same here

**Comment by DevL0rd** [comment]
@Ryochan7 After checking yeah completely the same, but sadly I can't run 3.0.18 because it says I ened to install .net, then clicking ok does nothing. haha I already have .net, but besides that the latest version still runs without that issue.

So i'm just stuck on not having it working haha

**Comment by Agustinso** [comment]
Same here, it was working before, not working with the latest version. 
Also tried installing net5.0 to make the old work but its still asking for .NET

**Comment by elnenez** [comment]
It seems that the change that made not working lightbar in the HP4-077-V0.2 board is related with the output report type. In 3.0.18 it was used report id 15 and in 3.1.0 it changed to 11.

**Comment by psycodeoday** [comment]
> Same here, not working with the latest version, but it does with the 3.0.18 Installing net5.0 x64 desktop runtime fulfilled the .net requirement of the old one

**to force 3.0.18 to work,** be sure that you have Net.Framework 6 already installed, 
and then go to ds4windows files, and edit "DS4Windows.runtimeconfig.json" file,
go to "version": "5.0.0"  and change it to "version": "6.0.0", save and start ds4windows.

![verr](https://user-images.githubusercontent.com/9746260/210120427-c24063d1-8e68-484a-8eb9-0d1572ea4c2f.jpg)

**Comment by psycodeoday** [comment]
> It seems that the change that made not working lightbar in the HP4-077-V0.2 board is related with the output features byte. In 3.0.18 it was used COPYCAT_OUTPUT_FEATURES = 0xF3 and in 3.1.0 it changed to COPYCAT_OUTPUT_FEATURES = 0x03. I've tested the latest version of DS4Windows with this change and I can confirm it works OK.

As author of this thread, I confirm, that in **3.1.18** color lights and vibration works perfectly on both pad (copycats).

From 3.1.1 to 3.1.10 no lights (only white color with no reaction during color-picking/changing) and no vibration.

Since **3.1.11, and 3.1.12** still no lights, but vibration start to work again but with different behaviour: 
During "test heavy" or "test light" it gives me only one quick shot and stops itself. I have to click on and off repeatedly to produce constant vibration test. (in 3.0.18, one button click produce constant vibration, until I click again to stop it)

(copycat checkbox in settings-device options gives no changes)

**Btw.** When I connect those two pads via/trough usb cabe (bypassing Bluetooth), then all issues disappear (lights works fine, and vibration test is produce constant vibration), so the issue is not with lights and vibration compatibility itself, but with bluetooth comuniaction.
