### ISSUE TITLE
Issues with a custom profile for Minecraft (Java version)

### ISSUE THREAD

**Issue by vpontin** [Ryochan7/DS4Windows#248]
Hey!

I set up [this profile](https://gist.github.com/vpontin/e2ff1efd9881e4c635e6f20eed4afdff) to use with Minecraft: Java Version (which didnt have any native support or mod for the version i'm playing), but as soon i activate the profile the player begin to move errantically (i assigned WASD w/ scan code to left stick) and the camera sometimes pans slowly to right (assigned mouse to right stick).

I tried lowering the sensitivity to 0.5 for all axis, with no relief of the problems.

Is there something i can do to refine this? I'm using b116.

Thanks in advance!

**Comment by Ryochan7** [comment]
Sounds like you need to raise the dead zones for your sticks. Especially in keyboard mode, you need to enable dead zones as there are no implicit dead zones when the settings are set to 0 like DS4Windows used to have. I would recommend using either 0.09 or 0.10 for the stick dead zones as I usually use 0.09 on my profiles.
