### ISSUE TITLE
Imput mapper seems to be dead, any chance for xbox one gamepad support in ds4 to take its place?

### ISSUE THREAD

**Issue by 14142000** [Ryochan7/DS4Windows#2480]
It would be nice to be able to have the option to bind buttons system wide even in games that do not support steam input and have finer deadzone control, Games like Call of duty, and rainbow six on Ubisoft launcher actively block steams controller configurator.

**Comment by Ryochan7** [comment]
I believe InputMapper used the XNAGuardian filter driver to hide any physical XInput controllers from the rest of the system. That driver is defunct AFAIK and I do not think there is a replacement filter driver to handle that task. Something like the SharpDX package was probably used to read the actual XInput controller state into the program.

I don't see XInput input controller support ever happening.

**Comment by Kanuan** [comment]
HidHide can hide XInput devices. The only problem is that, currently, there is an issue with the HidHide Configuration Client in which causes it not properly hide the correctly device instance paths (so the Xinput devices remains visible), but one can manually hide the corrent related instances via HidHide CLI which will be effective.

**Comment by 14142000** [comment]
Yea Glosc uses it to hide the physical controller from the games so only the steam input virtual 360 controller will be registered
