### ISSUE TITLE
3.1.0&3.1.1 can't select chinese language package

### ISSUE THREAD

**Issue by EAPermanent** [Ryochan7/DS4Windows#2483]
3.1.0&3.1.1 can't select chinese（zh-cn&zh-tw） language package

**Comment by Ryochan7** [comment]
The language assemblies exist in the archive but the app does not pick them up for some reason. Might have to check the whole language pack list to see if any others are missing from the list. My main translation checks were against the Japanese pack and that one works in the app with the .NET 6 changes.

**Comment by Ryochan7** [comment]
Looks like Microsoft changed those language codes for .NET 6. Even the more locale specific equivalents (zh-Hans-CN and zh-Hant-TW) don't seem to work. It looks like the parent locale codes (zh-Hans and zh-Hant) have to be used instead.

https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo?view=net-6.0
