### ISSUE TITLE
Crash & Doesn't Show Tray Icon

### ISSUE THREAD

**Issue by christantoan** [Ryochan7/DS4Windows#2484]
**Describe the bug**
After updating to 3.1.1, DS4Windows no longer shows notification area icon (all the time). And when a controller is connected, it will crash (so far only happens when DS4Windows is started via Task Scheduler).

**To Reproduce**
Steps to reproduce the behavior (not sure if everything is relevant):
1. Run DS4Windows as administrator (I already renamed the executable to "DS4Win")
2. Set DS4Windows to run at startup via a task
3. Reboot
4. After logon, DS4Windows icon is not in notification area but it's running in Task Manager
5. Connect a controller
6. The controller isn't detected and DS4Windows disappears from Task Manager

**Expected behavior**
DS4Windows runs normally at startup, icon exists in notification area, and my controller is detected without crashing.

**Screenshots and Logs**
My settings and no notification area icon:
![image](https://user-images.githubusercontent.com/7300310/180599982-1f3ec5b4-c24d-4176-b657-8304df0d7798.png)
Crashing log:
[ds4windows_log_20220723.0.txt](https://github.com/Ryochan7/DS4Windows/files/9173476/ds4windows_log_20220723.0.txt)

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony CECHZC2E A1
 - OS: Windows 10 Version 21H2 Build 19044.1826
 - DS4Windows Version 3.1.1

**Additional context**
Currently none.

**Comment by freepizzas-dev** [comment]
I think I'm experiencing a similar tray icon-related crash. However, my controller works fine, until DS4Windows crashes an hour or two into a session with:

`2022-07-23 20:54:26.4390|ERROR|Thread Crashed with message Cannot access a disposed object.
Object name: 'TrayIcon is disposed.'.`

Also on Windows 10 21H2 19044, DS4Windows 3.1.1, DS4 v.2.

Attached is my full log
[ds4windows_log_20220723.2.txt](https://github.com/Ryochan7/DS4Windows/files/9174920/ds4windows_log_20220723.2.txt)
.

**Comment by JanKiel2000** [comment]
If the name of the DS4Windows.exe program changes to some other, it stops appearing in in notification area.

**Comment by Ryochan7** [comment]
I'll have to check the Custom Exe Name option and see if it has anything to do with it. The error stack trace seems to show that the thread errors out when updating some tooltip text outside of DS4Windows code; don't even see a reference to DS4Windows routines in there.

As for the Run As Task option, the tray icon should still show up but it would likely just show up later on startup as more Windows elements get fully loaded.

**Comment by JanKiel2000** [comment]
The current version of the DS4Windows works.
You can change the name by "custom names". A file called in the field is created. We have two files: one ds4windows.exe the other as we gave ourselves in the field. Then when we run the DS4Windows.exe file, the program works ok, there is an icon at the watch but Steam sees that we have a program launched. When we launch a new program with a changed name, Steam does not see that we have a program mapping the pads. Unfortunately, then the icon at the watch does not appear.

**Comment by Ryochan7** [comment]
Found the core point when H.NotifyIcon fails.

```
if (!TrayIconMethods.TryCreate(
    id: Id,
    handle: WindowHandle,
    additionalFlags: additionalFlags,
    toolTip: ToolTip,
    uCallbackMessage: MessageWindow.CallbackMessageId,
    iconHandle: new HICON(Icon)))
{
    throw new InvalidOperationException($"{nameof(TrayIconMethods.TryCreate)} failed.");
}
```

https://github.com/HavenDV/H.NotifyIcon/blob/master/src/libs/H.NotifyIcon/Core/TrayIcon.cs#L253

It looks like the code leading into this from TaskbarIcon expects the assembly and the executable to be the same base name. A TrayIcon instance can be created with a unique identifier and then it will show up when running the program under a custom name. The TaskbarIcon class used for displaying context menus and used for data binding does not allow changing the identifier string passed to its TrayIcon instance.

https://github.com/HavenDV/H.NotifyIcon/blob/master/src/libs/H.NotifyIcon.Shared/TaskbarIcon.cs#L123

Also relevant

```
/// <summary>
/// Creates a unique Guid for the entry assembly simple name using hashing.
/// </summary>
/// <returns></returns>
public static Guid CreateUniqueGuidForEntryAssemblyLocation(string? postfix = null)
{
    var assembly =
        Assembly.GetEntryAssembly() ??
        throw new InvalidOperationException("Entry assembly is not found.");

    return CreateUniqueGuidFromString($"{assembly.Location}_{postfix}");
}
```

https://github.com/HavenDV/H.NotifyIcon/blob/master/src/libs/H.NotifyIcon/Core/TrayIcon.cs#L200

**Comment by Ryochan7** [comment]
Didn't know Windows directly associates trayicon GUID instances with the executable path. I do not believe calls to Shell_NotifyIcon was using GUIDs with the older Hardcodet NotifyIcon package; the source code seems to indicate it was not. Both executables would unintentionally be using the same GUID because the main assembly DLL (DS4Windows.dll) full file path is being hashed and used to generate the GUID for the tray icon. Funny enough, Windows will change the tray icon GUID association for different file paths if the EXE is signed. More pay to play nonsense.

https://stackoverflow.com/a/8853273

I have found a couple of different approaches around this problem with a modified version of H.NotifyIcon. Both approaches require being able to manually edit the GUID used by the TrayIcon instance. Using the TrayIcon.CreateUniqueGuidForEntryAssemblyLocation static method with the base exe file name as the passed suffix argument seems to be enough to get the tray icon working for a secondary Custom Exe Name executable.

**Comment by christantoan** [comment]
A question if I may. As far as I understand, this should be an old problem, right? Then why it suddenly pops up in this version? I've been using these settings from a few months ago without problems.
Thanks!

**Comment by Masamune3210** [comment]
Just a guess but .NET 6 changed a lot of behaviors from previous versions, so that's probably why this is suddenly showing up, at least partially

**Comment by JanKiel2000** [comment]
I fix this in `"MainWindow.xaml.cs"
Line 94 
`            trayIconVM = new TrayIconViewModel(App.rootHub, profileListHolder);
            notifyIcon.CustomName = System.Diagnostics.Process.GetCurrentProcess().MainModule.FileName;
            notifyIcon.DataContext = trayIconVM;`

**Comment by Ryochan7** [comment]
> A question if I may. As far as I understand, this should be an old problem, right? Then why it suddenly pops up in this version? I've been using these settings from a few months ago without problems.

It is not. Previous versions of DS4Windows (version 2.0 - 3.0.18) had used the older wpf-notifyicon NuGet package to provide the tray icon and that did not utilize a GUID for the NOTIFYICONDATAA struct.

https://github.com/hardcodet/wpf-notifyicon

That old package was flagged as deprecated with H.NotifyIcon being offered as the currently supported package to migrate to. That package changes how the underlying Shell_NotifyIcon Windows system call is used. It wouldn't affect most people but it would affect anyone using the Custom Exe Name setting in DS4Windows as there would be a GUID conflict between the two exes; both executables would use a GUID generated from the underlying assembly dll DS4Windows.dll. Windows does not even provide a call to unregister a previously associated GUID; would need to alter the registry directly to unassociate a GUID.

A new update has been published for H.NotifyIcon that offers more control over the GUID that the underlying TrayIcon instance uses. The new CustomName dependency property will used to hash the associated executable location and generate a GUID. The tray icon now works properly for a Custom Exe in the current code. Not sure when a new DS4Windows release will be published. Working on a couple of other tasks. It will likely be before next Friday.

**Comment by DreadfulDrummer** [comment]
Update 3.1.2 has fixed the issue.
Good work! Thank you!

**Comment by christantoan** [comment]
> Update 3.1.2 has fixed the issue. Good work! Thank you!

Agree!

**Comment by eskoONE** [comment]
i think im still experiencing the same issue. ds4windows crashes when i have it started via task scheduler and switch to my external monitor. the icon disappears but the controller remains functional until i switch the profile to something else, where it hard crashes and stop working completely.

this does not happen when i manually start the program without task scheduler starting it for me prior.

**Comment by fewdji** [comment]
> ds4windows crashes when i have it started via task scheduler and switch to my external monitor

Same problem. Fix it please

**Comment by 7e3J4y** [comment]
> i think im still experiencing the same issue. ds4windows crashes when i have it started via task scheduler and switch to my external monitor. the icon disappears but the controller remains functional until i switch the profile to something else, where it hard crashes and stop working completely.
> 
> this does not happen when i manually start the program without task scheduler starting it for me prior. this was happening before i changed the name of the executable and after it.
> 
> im on 3.1.2. is there anything i can do to help any further with this issue?

I am still experiencing crashes as well, under these exact same circumstances. DS4Windows is started as a task on startup, switching to an external display and connecting my controller, it will usually work for a minute but usually crashes quickly. I've never tried to pinpoint what was causing it, but it sounds like you have @eskoONE. I am swapping between two profiles as well, a default game controller profile and a PC navigation profile. And just as you said, it does not crash again once it's restarted and loaded as a program instead of a task.

**Comment by DreadfulDrummer** [comment]
Okay but that's not this issue with the tray icon not showing caused by changing the exe name. Please open or find an issue relevant to the problem you're having.

**Comment by eskoONE** [comment]
> Okay but that's not this issue with the tray icon not showing caused by changing the exe name. Please open or find an issue relevant to the problem you're having.

It is the same issue? The icon disappears when switching the display and crashes after a while or when changing the profile. I mean i dont have a problem with opening up a new thread but i thought it would fit here.

**Comment by 7e3J4y** [comment]
I can't get it to crash in a consistent way. Most of the time, I connect the external display, use the controller as navigation to load a video or whatever, set it down and awhile later I notice it hasn't idle-disconnected. The controller no longer does anything, DS4Windows crashed as some point.

I'm testing with it now and I immediately noticed the task bar icon is gone, though DS4Windows is still running... I let it sit for a while and the controller remained working. I disconnected and reconnected it but nothing appears to be happening. DS4Windows is still running according to task manager

**Comment by Wis76** [comment]
I'm getting issues starting from version 3.1.2.

This is the log (at least the part which seems relevant to me:

2022-08-18 14:25:34.8983|ERROR|Thread Crashed with message Cannot access a disposed object.
Object name: 'TrayIcon is disposed.'.
2022-08-18 14:25:34.9118|ERROR|System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'TrayIcon is disposed.'.
   at H.NotifyIcon.Core.TrayIcon.EnsureNotDisposed()
   at H.NotifyIcon.Core.TrayIcon.UpdateToolTip(String text)
   at H.NotifyIcon.TaskbarIcon.WriteToolTipSettings()
   at H.NotifyIcon.TaskbarIcon.OnToolTipTextChanged(String oldValue, String newValue)
   at H.NotifyIcon.TaskbarIcon.<>c.<.cctor>b__39_14(DependencyObject sender, DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.PropertyPathWorker.RefreshValue()
   at MS.Internal.Data.ClrBindingWorker.ScheduleTransferOperation(Object arg)
   at MS.Internal.Data.DataBindEngine.ProcessCrossThreadRequests()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Unfortunately It's crashing like twice per hour.
Thanks for all your hard work.
The program is great!

**Comment by Ryochan7** [comment]
Likely a different problem than what was happening in the OP. Most likely related to issue #2510. That problem has already been fixed in the code but no new release has been made with the fix yet. Besides RDP sessions, changing font scaling causes early Dispose calls as well; resolution changes seem to not invoke the problem code in H.NotifyIcon.

I probably should get around to at least posting an issue on the H.NotifyIcon GitHub regarding the early Dispose issue as the code does not seem to be working as intended.
