### ISSUE TITLE
No Mouse Emulation possible with open task manager

### ISSUE THREAD

**Issue by Dampfbonbon** [Ryochan7/DS4Windows#2485]
https://user-images.githubusercontent.com/109895959/180639114-13c305ce-202a-49a8-a051-d5390703b839.mp4

As you see the task manager over permits the ds4 aplication.

**Comment by Yohoki** [comment]
Try running DS4Windows as admin.

- Right click 'Ds4windows.exe'
- "Properties"
- "Compatibility" Tab
- Tick box for "Run as Administrator" and Apply
- Exit D4W completely and Restart the program.

**Comment by Ryochan7** [comment]
That is a UAC security "feature" in Windows. To work around that behavior, you would have to run DS4Windows as Admin like Yohoki mentioned or install and use the FakerInput driver within DS4Windows.

**Comment by Dampfbonbon** [comment]
Thx
