### ISSUE TITLE
ColorPickerWindow - transparency not working

### ISSUE THREAD

**Issue by abi-21** [Ryochan7/DS4Windows#2486]
Using version 3.1.1, slider for changing color transparency is not doing anything.

**Comment by Ryochan7** [comment]
The DS4Color struct has no concept of an alpha channel; neither does the DS4 output report section for the lightbar color. I don't remember the WPF Extended Toolkit color picker having a way to hide the alpha slider but it looks like the option does exist in the current package. Will likely just change that property to hide the alpha slider for future versions of DS4Windows.
