### ISSUE TITLE
DS4Windows | Crashing/Not Launching

### ISSUE THREAD

**Issue by juastins** [Ryochan7/DS4Windows#2488]
### DS4Windows Crashing Upon Launch

Hello!
Recently, **DS4Windows has stopped launching**. Ever since a few weeks ago, it stopped working. I have not made any changes to my PC. I have tried my best trying to solve this solution to the best of my ability without making a post here. Now I am here.

**What happens when I launch DS4Windows with & w/o Administrative Privileges'**
![issue](https://user-images.githubusercontent.com/109973680/180807184-b2f9593d-333f-4df2-b72d-7203100aeb97.gif)

**What have I done?**
- Reinstalled all runtime requirements
- Uninstalled any required drivers
- Updated or reinstalled any required drivers
- Followed the many methods posted on the DS4Windows subreddit
- Followed the many methods posted on 3rd party sites
- Ran DS4Windows with elevated privileges' 

and everything else in the book...

I have taken the time to see what error might occur within the 'Event Viewer' on Windows, this is what I got!

```
Fault bucket 1680054911418598179, type 4

Event Name: APPCRASH

Response: Not available

Cab Id: 0



Problem signature:

P1: DS4Windows.exe

P2: [3.1.1.0](https://3.1.1.0/)

P3: 62b2fac5

P4: KERNELBASE.dll

P5: 10.0.19041.1826

P6: 299341e8

P7: e0434352

P8: 0000000000034fd9

P9:

P10:



Attached files:

\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9F9B.tmp.mdmp

\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9FFA.tmp.WERInternalMetadata.xml

\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA01A.tmp.xml

\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA02A.tmp.csv

\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA05A.tmp.txt



These files may be available here:

\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_DS4Windows.exe_67b98b84345cdcb37d173b959efc21699c4f22_dd9ad86c_9055f4ec-7d0c-486c-aed8-85b007f4574b



Analysis symbol:

Rechecking for solution: 0

Report Id: 9ede5807-6bbe-4253-ac03-e9ecd7041004

Report Status: 268435456

Hashed bucket: 312f1330f09dd6c3e750c10a66418323

Cab Guid: 0
```

Furthermore, DS4Windows does not even open. The moment I double click the application, my mouse has the loading circle for 2 seconds then returns to the normal cursor. Nothing else happens. It is pure nothingness.

I have even tried opening up the other applications within DS4Windows, like XInputCheck & DS4Updater, they will not even open.

If anyone is able to help me out and give me some support, it will be much appreciated!

Thank you, so much!

***Extra Info:***
- Windows 10 Home
- DS4Windows Version 3.1.1 x64

**Comment by juastins** [comment]
### Note:
Does anyone have a copy of their AppData settings for DS4, I back tracked and the issue started to persist when I removed the contents within the AppData folder for DS4Windows.

**Comment by KungFuDonkey** [comment]
[DS4Windows.zip](https://github.com/Ryochan7/DS4Windows/files/9195584/DS4Windows.zip)
Note: I am not a developer of this repo, but I saw your question and I just installed DS4, so here is my appdata/roaming/ds4windows folder

**Comment by critchi** [comment]
I was having exactly the same problem. 
Solved by [updating .NET Runtime (from 6.0.1 to 6.0.7).](https://dotnet.microsoft.com/en-us/download/dotnet/6.0/runtime)
Once that was done DS4windows.exe worked and asked where to store the configuration files (app data or program folder).

Process monitor was showing the last usable file before crashing as:
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.1\kernel32.dll

My winver:
Microsoft Windows 11 Pro
Version 21H2 (OS Build 22000.832)

Hope this helps, thanks for thread.

**Comment by Ryochan7** [comment]
So something was wrong in that version of .NET 6? I have only used .NET 6.0.7 on my system so that is the version I recommend. Ideally, any version of .NET 6.x should work but that doesn't appear to be the case. Good job Microsoft
