### ISSUE TITLE
Lightbar is flashing blue-red

### ISSUE THREAD

**Issue by goodmusic11** [Ryochan7/DS4Windows#249]
Hello,

Everything  is working fine for the moment but the only problem that I have is while in game, the light bar flash blue-red indefinitely and it supposed to stay just the blue color (by default)

I use the DS4Windows 1.4.116 version

Thanks for helping me

**Comment by Ryochan7** [comment]
I think I experienced something similar while charging my controllers last night. The lightbar stays blue as expected when the battery is fully charged. However, the pulse transition while charging does not work as expected anymore and it will transition to red sporadically.
