### ISSUE TITLE
using ds4 controller disconnect immediately on launch of Modern Warfare and does not allow me to use my scuf with MW.

### ISSUE THREAD

**Issue by NinjaMedic93** [Ryochan7/DS4Windows#2490]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots and Logs**
If applicable, add screenshots to help explain your problem. Also, please add the most
log file (ds4windows_log.txt) from the Logs folder in your DS4Windows config folder.

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: [e.g. Windows 10 Pro Build 2004]
 - DS4Windows Version [e.g. 3.0.3]

**Additional context**

**Comment by Yohoki** [comment]
I'm sure some people would love to help you..... but you didn't fill out the form..... We need a little more info than "It broke, fix".

Specifically, the log files and that whole area that says "Please complete the following information" would really be helpful.

As a small bit of early help, can you launch D4W AFTER modern warfare? does that work or does the controller still disconnect?
