### ISSUE TITLE
Connect with driver

### ISSUE THREAD

**Issue by Yany1944** [Ryochan7/DS4Windows#2492]
I installed the driver both from the github and from the application, he does not want to find it, I can constantly install it through the menu (this happened after I tried to connect dualshok 3 to the PC P.S it didn’t work, although everything was fine before via scp)
I will attach the log
Imgur - https://imgur.com/a/o7pBO0O , https://imgur.com/a/BZDpr2x

**Comment by Ryochan7** [comment]
The easiest recourse is to reboot Windows. It is an internal ViGEmBus issue that has never been isolated.

**Comment by Yany1944** [comment]
yes, I have already solved this problem, I don't know how it turned out,
but everything is already fine)

сб, 13 авг. 2022 г., 05:49 Travis Nickles ***@***.***>:
