### ISSUE TITLE
DS4 controller losing connection after update while in game. Log attached

### ISSUE THREAD

**Issue by mikmuleh** [Ryochan7/DS4Windows#2498]
ps5 controller wired by USB to pc keeps losing connection in games after latest update . Tried swapping cables, USB ports, reinstalling the program but still disconnects
Log below
[log.txt](https://github.com/Ryochan7/DS4Windows/files/9271990/log.txt)

**Comment by Yohoki** [comment]
Looks like a short to me. Either in the cable or the charger port on the controller. Nothing seems odd in the logs.

Try a few of these options and see if you can find the short:
- A different cable, but the same controller (Test for short in cable)
- A different controller, but the same cable (Test for short in Dualsense)
- Connecting with Bluetooth (Test for error in D4W's code, or major issue in controller)
- Connect a different device (Like a phone or USB Hard drive) into the same cable, and wiggle it around a bit to see if it disconnects repeatedly (Another test for short in cable)

**Comment by Ryochan7** [comment]
Not much to go off of there. Really seems more likely to be a hardware issue.
