### ISSUE TITLE
Beep beep sound and mouse lag

### ISSUE THREAD

**Issue by bibekmhz123** [Ryochan7/DS4Windows#2499]
when using this new version , while playing games there is sometimes beep beep sound and pc becomes laggy I think it is due to overclocking of my controller but the thing is that if i use previous version (any) then there is no any such bug. 
I am the only one??
i fixed it by rolling back to old version 3.1.0

**Comment by Masamune3210** [comment]
Check if your mouse or keyboard support a high polling rate and try turning it down if it does, a driver update might have reset it to something higher than before. Beeping randomly during input is usually a sign that the input message handler in Windows is getting overwhelmed, at least with my experience

**Comment by Yohoki** [comment]
A "Beep Beep" sound isn't very descriptive. Is this the sound you're hearing? https://www.youtube.com/watch?v=9omajpF7v-o

If it is, something is connecting and disconnecting (Might be the physical controller). A log file might help see if that's what's going on. 

### DS4Windows Log locations ###
- Open a file explorer and navigate to "%AppData%\DS4Windows\Logs" or "C:\Users\USERNAME\AppData\Roaming\DS4Windows\Logs"
- Copy the text inside the newest file into a post, or rename the file to .ZIP and drag it into the post to upload it.

**Comment by Masamune3210** [comment]
If it doesn't sound like this, which I am assuming is the generic connection or disconnection noise and instead just sounds like a old DOS-style Beep noise, its probably more what I was describing
