### ISSUE TITLE
DS3 Support

### ISSUE THREAD

**Issue by hyakki-** [Ryochan7/DS4Windows#25]
Do you think you can you add in DS3 support, at least only USB support

**Comment by JarnoVgr** [comment]
Check this issue: https://github.com/Ryochan7/DS4Windows/issues/5

**Comment by Ryochan7** [comment]
Unfortunately I am going to keep this project focused on only working for DS4 controllers. There has been enough work trying to improve the performance of the program without adding support for other devices. It would seem like ScpToolkit would be your best bet for DS3 support.

https://github.com/nefarius/ScpToolkit/

**Comment by Ryochan7** [comment]
As a side note, I wrote a tool before that would work as a fallback for any game controller that exposes itself to Windows as a DirectInput device. Concurrently playing with both that small project and DS4Windows ended up improving both projects. Here is an archive if anyone is curious.

https://drive.google.com/open?id=0B6yGHDx0CFzDcGRnNHdjU0V4eHc
