### ISSUE TITLE
can someone add the "Fightstick Alpha" from madcatz in that software here?

### ISSUE THREAD

**Issue by Tsubajashi** [Ryochan7/DS4Windows#250]
i wanna play with my fightstick.
what do i need to provide so someone could add it?

**Comment by vpontin** [comment]
[This one](https://gameidealist.com/news/first-look-at-the-mad-catz-street-fighter-v-fightstick-alpha-and-fightpad-pro/)?

Anyway, i think the situation (not device) is similar to #230
