### ISSUE TITLE
Windows recognizes two controllers when I connect via usb

### ISSUE THREAD

**Issue by victorLessa** [Ryochan7/DS4Windows#2500]
Windows recognizes two controllers when I connect via usb.

**Comment by Masamune3210** [comment]
Hide the actual controller using HidHide, by default no hiding is performed of the original controller so both the actual controller and the virtual controller will appear to Windows

**Comment by Kanuan** [comment]
Check the following page: [Preventing the double controller / double input issue in games](https://docs.ds4windows.app/guides/solving-double-input/)
