### ISSUE TITLE
"Load profile" Special Action crashes app

### ISSUE THREAD

**Issue by Linnshet** [Ryochan7/DS4Windows#2502]
I tried to make an improvised profile switching mechanism, by applying a "load profile" action on each of the two profiles I mainly use (one for DS4 and one that emulates Xbox, when a game's DS4 incompatible). Though definitely could be cooler, if I could switch between profiles freely, to change color of the lightbar, but I digress.

When I switch profile, the gamepad responds like it should, by changing the color lightbar to the scheme I've chosen for the other profile. But, in the app itself, it says "DS4 stopped" in the corner, and after approximately 10 seconds or so, it stops responding, so you have to force close the app and open it again.

I've tried both this trigger, which I thought might've been the issue, but I also tried something nonsensical like L3 and multipad right touch, same result.

![image](https://user-images.githubusercontent.com/52015410/183306902-bf2aaecc-eff1-4c78-a077-7c09da1bbd91.png)

**Comment by Yohoki** [comment]
Can we get a log file added from after the crash or showing the "DS4Windows Stopped"?

I also use load profile special actions for a few profiles. I haven't used them in the newest update, though. I'll check in the morning if mine still work, because my battery is dead right now.

It might also be an issue with the controller profile. Does that profile work when used by itself?

###DS4Windows Log locations###
- Open a file explorer and navigate to "%AppData%\DS4Windows\Logs" or "C:\Users\USERNAME\AppData\Roaming\DS4Windows\Logs"
- Copy the text inside the newest file into a post, or rename the file to .ZIP and drag it into the post to upload it.

**Comment by Linnshet** [comment]
Both the controller profiles work perfectly, and I just figured out the "swipe touchpad to switch profiles" function, which did the same. I did both in the recent logfile.

My DS4W apparently haven't put logs into my AppData folder, didn't find a folder for it there, but found the logs in its Program Files folder.

[ds4windows_log_20220808.1.txt](https://github.com/Ryochan7/DS4Windows/files/9279471/ds4windows_log_20220808.1.txt)
[ds4windows_log_20220808.2.txt](https://github.com/Ryochan7/DS4Windows/files/9279472/ds4windows_log_20220808.2.txt)
.

**Comment by Yohoki** [comment]
I've also just checked the special actions and swapping profiles. It DOES work on my end. I tried also swapping profiles that use different controllers and it is still working with no crash. Here's my [log file](https://github.com/Ryochan7/DS4Windows/files/9284296/SpecialActionProfileSwapTest.txt)
.
Some one else might need to look at what's going on here. A copy of your profiles folder might help them. You might also follow the error's advice and run the "PurgeOldXInput" file in the tools folder. Please also check if swapping to a different profile still causes a crash or not.

**Comment by Ryochan7** [comment]
> My DS4W apparently haven't put logs into my AppData folder, didn't find a folder for it there, but found the logs in its Program Files folder.

Automatic user error as you are using Windows wrong. Don't manually store apps under Program Files. Also, the Load Profile special action works for me just fine. Ended up adding a small extra check if a profile does not actually exist.

Also, I need to update that log message as PurgeOldXInput is no longer bundled with DS4Windows. Thank VirusTotal and false positives deciding the app is doing suspicious activity. When that ViGEm issue happens, it is usually best to just reboot Windows at that point.
