### ISSUE TITLE
DualSense Battery not recognizing it

### ISSUE THREAD

**Issue by DevDorrejo** [Ryochan7/DS4Windows#2505]
**Describe the bug**
The battery show incorrect level

**To Reproduce**
1. Connect the Device Thought USB/BT 
2. Look the Battery Level
3. Not See a correct current value

**Expected behavior**

**Screenshots and Logs**
![image](https://user-images.githubusercontent.com/7697566/183332234-be71e8de-201f-42b6-afcb-2b9d618eefef.png)
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/9278478/ds4windows_log.txt)

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony Dual Sense CFI-ZCT1W
 - OS: Windows 11 Enterprise 21H2
 - DS4Windows Version 3.1.2

**Additional context**
The control is new, and dont have ps5 to test it.

**Comment by AsheX1** [comment]
my brother seems to have the same problem his PS5 controller allways showing 0% battery on the other hand i have 2 PS 5 controllers but they never seem to charge to 100% 87% max never seen it hit 100%

**Comment by JanKiel2000** [comment]
For me, when I connect a DualSense to a USB port, regardless of what (USB2, USB3) on the back of the computer, the controller does not charge, it only discharges. Only connecting it to the USB port at the front, where there is your own power supply, or connecting to a powerful USB power supply, e.g. from a smartphone, charges this controller.

**Comment by DevDorrejo** [comment]
Don't follow the ds4w charger status is erroneously reading the battery param and at the same time the windows driver is not 100% working.

If I use conected it with steam and shutdown the machine it will stay with the profile active.

**Comment by Masamune3210** [comment]
Driver works fine, and ds4w is doing what it does normally, the reason it doesn't charge isn't because of some software configuration because it simply cant be lol. The reason the dualsense doesn't charge on things the ds4 does easily is simply because the dualsense uses more power while on. It charges fine while In standby because the controller isn't actively doing anything and is in low power mode

**Comment by DevDorrejo** [comment]
> Driver works fine, and ds4w is doing what it does normally, the reason it doesn't charge isn't because of some software configuration because it simply cant be lol. The reason the dualsense doesn't charge on things the ds4 does easily is simply because the dualsense uses more power while on. It charges fine while In standby because the controller isn't actively doing anything and is in low power mode

I will have to ask to my motherboard manufacturer about the USB PD (Power Deliver)
