### ISSUE TITLE
Ryochan DS4Windows pogram, Disabling SixAxis (Accel)

### ISSUE THREAD

**Issue by 4mulala** [Ryochan7/DS4Windows#2508]
**Describe the bug**
When I updated my ds4windows I seen a sixaxis for motion controls, does anyone know how to disable the Disabling SixAxis (Accel)?

**Comment by Yohoki** [comment]
In your profiles, you can see a gyro tab. You can set the gryo options there.
![image](https://user-images.githubusercontent.com/44595371/183569817-7729f964-0805-4d05-8346-8111dc43115a.png)

**Comment by Ryochan7** [comment]
Nothing is mapped to the SixAxis (Accel) by default
