### ISSUE TITLE
When connecting my ps5 controller, its not being recognized but the light comes on. however my ps4 controller connects jus fine

### ISSUE THREAD

**Issue by truewolf7** [Ryochan7/DS4Windows#2509]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots and Logs**
If applicable, add screenshots to help explain your problem. Also, please add the most
log file (ds4windows_log.txt) from the Logs folder in your DS4Windows config folder.

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: [e.g. Windows 10 Pro Build 2004]
 - DS4Windows Version [e.g. 3.0.3]

**Additional context**

**Comment by Ryochan7** [comment]
You need to enable support for the DualSense in Device Options or the initial setup window. Blame Steam Input.
