### ISSUE TITLE
[Request] support for nacon Wired Compact Controller

### ISSUE THREAD

**Issue by marvercraft** [Ryochan7/DS4Windows#251]
Hello I saw the help from @Yuki-nyan 

and I wanted to ask if its possible to port it to the wired compact controller version.
VID/PID:
HID\VID_146B&PID_0603&IG_01 [I copied it from hardware manager Idk if its Right....]

I hope this is enough to help because the most is already in there  and the controller is like a Lite version of the pro it has no gyros in it, no audio  and only X-Input 

greetings marv

sry for my bad english

**Comment by vpontin** [comment]
Just FYI, this situation (not device) is similar to #230

**Comment by marvercraft** [comment]
I would be grateful if you could buy one and figure it out @Yuki-nyan

**Comment by Yuki-nyan** [comment]
I've ordered one from Amazon and it should be here mid next week.

**Comment by Yuki-nyan** [comment]
It's arrived but it doesn't look good I'm afraid. When plugged into a PC it appears as an XInput controller rather than a DInput one and short of using a USB analyser with the controller plugged into a PS4 I'm not sure how I'd figure out a way around that - unfortunately I don't have one.

**Comment by REAL-NEIL** [comment]
Thanks for trying I've hit a brick wall trying to make this work, gave in and bought a real ps4 pad as this is properly detected and works fully in DS4 with farcry 5 including the dpad and both triggers. Don't suppose this would be any use https://freeusbanalyzer.com/ or would you need to analyse it in use on a ps4 to see what it was outputting?
