### ISSUE TITLE
DS4 (DualShock 4) BT (Bluetooth) connection fail on non-original/OEM/clone versions

### ISSUE THREAD

**Issue by MMavrick23** [Ryochan7/DS4Windows#2514]
- ### Problem Description
Even though I tried DS4Windows with several controllers and it works flawlessly (Thanks to the developers and the community), yet some controllers, which after further experimentations I found to be related with being clone (non-original) controllers, fail to work properly with the app via BT (Bluetooth) connection, it works fine when using the USB however.

- ### Symptoms & Problem Replication
Replicating such issue is fairly easy, just try pairing a non-original (clone) or even an original DS4 (DualShock 4) controller via BT (Bluetooth) connection, after pairing the app can successfully identify the controller and assign its profile and it works fine for about 1 second before it disconnects (gets removed from DS4Windows menu) for bout 3 seconds, then it loops again with the same sequence.

Note that when disconnection occurs, DS4Windows status logs a battery reading related issue.
![Screenshot 2022-08-10 235305](https://user-images.githubusercontent.com/24808868/184027350-3be62ccd-3723-4f82-9207-98e526eaecea.jpg)

In earlier versions of DS4Windows, the application would read 0% battery level and report it as an issue before disconnecting, the same reading can still be verified even in the latest version by connecting via USB to get the same battery reading.

![Screenshot 2022-08-10 235812](https://user-images.githubusercontent.com/24808868/184027740-a3078bb4-049c-4066-ad4e-15c0efaf0866.jpg)

- ### Troubleshooting Steps Taken
In the process of identifying and fixing the issue, I have tried all of the following:
1. Reinstalling DS4Windows.
2. Reinstalling all the related drivers (either for DS4Windows or for the Bluetooth).
3. Used external BT (Bluetooth) module V5.0 instead of the one built in my laptop.
4. Tried multiple BT (Bluetooth) driver stacks including Microsoft, Toshiba, CSR and others.
5. Did a full reset for the controller and did battery health check as well as verifying the BMS circuitry is working properly.
6. Tried the same controller on other on DS4Windows devices such as Android phone, PS4, Smart TV. All proven working fine.
7. Tried a couple of original controllers with DS4Windows. One worked fine, another had the same issue but on much longer intervals.

- ### Operating Environment
> - **System:** Microsoft® Windows™ 10 Pro - x64.
> - **CPU:** Intel® Core™ i7-8750H @ 2.20GHz.
> - **RAM:** 16.0 GB @ 2667MHz.
> - **Application Running Disk:** Samsung SSD 870 EVO 500GB.
> - **GPU:** NVIDIA GeForce GTX 1050 Ti, NO OVERCLOCKING.
> - **Bluetooth Version:** HHCI 7.11 / LMP 7.34850 (Bluetooth 4.1).

- ### Suggested Solutions
1. Add an option to bypass (skip) battery level checking before disconnection (Using a checkbox or something).
2. Use the native BT (Bluetooth) battery level reading from the operating system (Microsoft® Windows™) itself.
3. Automatically ignore 0% battery level as it is practically not possible and treat it as a reading issue to skip.
4. Identify clone (or other versions with the same issue) and handle them differently.

- ### Side Note
I tried adding the option to skip or override the battery level checking my own, but I was busy with other projects and could not find my way through the code to the section where the battery level checking logic occur. Maybe I will give it another shot and do a pull request if I got a progress with that.

**Comment by MMavrick23** [comment]
Does closed as completed mean it is fixed? 😂❤

**Comment by Ryochan7** [comment]
> Does closed as completed mean it is fixed? 😂❤

> non-original/OEM/clone versions

That says it all. Can't support hardware I do not own. Make a pull request
