### ISSUE TITLE
Date in Profiles.xml changing when app is closed

### ISSUE THREAD

**Issue by masterflitzer** [Ryochan7/DS4Windows#2520]
**Describe the bug**
Everytime DS4Windows is closed, the date in the comment in line 2 of Profiles.xml gets updated. As this is a comment anyway, what use does it have? I have my profiles in git version control and the file basically changes every day but the actual content besides this line is the same

**To Reproduce**
1. check content of Profiles.xml (PS: `cat $env:appdata/ds4windows/profiles.xml`)
1. close DS4Windows (open and close when not opened already)
1. check file again

**Expected behavior**
don't have variable comments that are written on every launch, date is useless and is not needed afaik

**Screenshots and Logs**
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/9315074/ds4windows_log.txt)
![1](https://user-images.githubusercontent.com/60170948/184322493-352523f8-4897-4118-bdad-fff1dd8b527c.png)
![2](https://user-images.githubusercontent.com/60170948/184322500-6a331575-c9f9-4ad6-850c-705e54ad4fb3.png)

**Desktop (please complete the following information):**
 - Controller: Sony DualSense (but not relevant here)
 - OS: Windows 11 Pro 21H1 Build 22000.856
 - DS4Windows Version: 3.1.2

**Comment by Ryochan7** [comment]
The modified date in the file is more for my own benefit than for the end user. Need to know how recent the file is sometimes.

**Comment by masterflitzer** [comment]
fair enough but this can easily be done using metadata of the file (last modified), I'd really appreciate if the file wasn't constantly changing
