### ISSUE TITLE
ViGEmClient Notification Queue still required for ViGEmBus 1.18.367.0

### ISSUE THREAD

**Issue by Ryochan7** [Ryochan7/DS4Windows#2521]
Cannot remember where I posted about possible feedback changes related to updated ViGEmBus drivers so just going to post a quick post here. Finally got around to rebuilding ViGEmClient without the Notification Queue and tried it with ViGEmBus 1.18.367.0. Infinite rumble occurs very quickly in RetroArch when playing Legend of Zelda: Ocarina of Time using the ParaLLel N64 core.

Tests just confirm that the Notification Queue code is still required.

**Comment by nefarius** [comment]
Once you fully ported to the new full report API you can throw out this sad chapter of history 😅
