### ISSUE TITLE
DS4Windows disappearing from tray (and crashing shortly after) first time after startup when connecting an external display

### ISSUE THREAD

**Issue by 7e3J4y** [Ryochan7/DS4Windows#2523]
I left some comments about this in the other thread about the disappearing from tray bug, but was told this should be its own issue. I've done some troubleshooting and info gathering and this is what I've found. I can make DS4Windows reliably crash by doing this:

* Restart computer, it does not matter if DS4Windows is started automatically, it also does not matter if it is configured as a task or a program
* Start DS4Windows and connect a controller
* Connect an external display and enable it in windows (maybe HDMI only? clarification later)
* DS4Windows is removed from the system tray. It will sometimes crash immediately, or remain active until the controller is disconnected, which then it will also crash immediately when the disconnect command is sent

For whatever reason, I can only get this to happen once, the first time the display is connected after a reboot. Restarting DS4Windows and attempting to recreate the crash was not successful, the program behaves at it should, hence the computer restart is necessary.

I also want to provide some transparency and clarification to my display setup. The display in question is an HDMI TV in another room that is enabled or disabled as needed. I attempted to recreate this crash by disconnecting and reconnecting one of my non-HDMI monitors but was not successful. I usually connect the HDMI TV by pressing a key combo on the controller that triggers a hotkey in a different software called Monitor Profile Switcher, though I tested connecting the display without using this software and DS4Windows still crashed.

[ds4windows_log_20220815.7.txt](https://github.com/Ryochan7/DS4Windows/files/9338338/ds4windows_log_20220815.7.txt)
[ds4windows_log_20220815.9.txt](https://github.com/Ryochan7/DS4Windows/files/9338339/ds4windows_log_20220815.9.txt)
[ds4windows_log_20220815.10.txt](https://github.com/Ryochan7/DS4Windows/files/9338340/ds4windows_log_20220815.10.txt)
[ds4windows_log_20220815.11.txt](https://github.com/Ryochan7/DS4Windows/files/9338341/ds4windows_log_20220815.11.txt)

Running Windows 10 64-bit
ViGEmBus version 1.17.333.0
This is a new issue and has happened since DS4Windows began getting updated again ~a month ago.

**Comment by 7e3J4y** [comment]
For some reason, I can't add these files to the main post. Just incase it helps, I will also post dxdiag for both the TV connected and disconnected:
[DxDiag-TV OFF.txt](https://github.com/Ryochan7/DS4Windows/files/9338427/DxDiag-TV.OFF.txt)
[DxDiag-TV ON.txt](https://github.com/Ryochan7/DS4Windows/files/9338428/DxDiag-TV.ON.txt)

**Comment by Ryochan7** [comment]
Probably related to issue #2510. Working on that one

**Comment by Ryochan7** [comment]
Should be fixed with commit b9bb9f7e1413c8069e7cbc0f0929d02862ea49dd

**Comment by 7e3J4y** [comment]
Compiled with that commit and it does look like it's fixed, thank you @Ryochan7 !
