### ISSUE TITLE
How to uninstall

### ISSUE THREAD

**Issue by Suiyuanlongtao** [Ryochan7/DS4Windows#2525]
I want to uninstall now

**Comment by Masamune3210** [comment]
Just uninstall HidHide, FakerInput if you have them installed, and then delete DS4Windows. The program itself doesn't have a installer

**Comment by mooms06** [comment]
You should also uninstall ViGEmBus.

**Comment by Kanuan** [comment]
[Uninstalling DS4Windows and related drivers](https://docs.ds4windows.app/guides/uninstalling-ds4windows/)
