### ISSUE TITLE
Improvement request: Make more flexible "Color by battery percent" settings

### ISSUE THREAD

**Issue by phatal** [Ryochan7/DS4Windows#2527]
Hi, thanks for continuous support, tools is awesome. This is my suggestion that might make ds4windows a little better.

Nowaday this settings has only 2 position "full" and "empty" which is not informative what colour will be between. Will be much better if we (users) can set number of colors (if colour by battery percent is ON) which we want to set for example (4). (look at screen point 1). 

After will be appear block right to colour picker (again look at screen point 2) at which we can select specific battery percents number (this percents set programmatical by dividing 100 and number of colours setted at previous step) and set colour for this number. For example i can set green for 100% yellow for 75%  orange for 50% and red for 25%.

Regards.
ps. sorry for low english. I tried my best :3

![possible view](https://i.imgur.com/cYdRH3Y.png)

**Comment by Ryochan7** [comment]
The proposal does not really make sense to me. Not much of a reason for the color transition when you have more than two colors.  Having multiple gradients in place would be more confusing. The current behavior is good enough for me.
