### ISSUE TITLE
Could you update to support strikepack for ps4?

### ISSUE THREAD

**Issue by soondol007** [Ryochan7/DS4Windows#253]
Hello ryochan7

I have a favor to ask you
Could you update to support strikepack for ps4? (http://collectiveminds.ca/strikepack/)
Strikepack is an accessory that attaches to the DS4 controller
It is expected to be available if you add device VID and PID
Here's hardware ID of mine

strikepack alone -> "USB\VID_1209&PID_2FE7"
strikepack+ds4  -> "HID\VID_054C&PID_05C5"

Best regards,

**Comment by vpontin** [comment]
see https://github.com/Ryochan7/DS4Windows/issues/230#issuecomment-373948915

**Comment by Ryochan7** [comment]
I can try to add the VID + PID combination for the stickpack+ds4 and post a test build here. If just adding the VID + PID combination does not work then there is nothing else that I can do because I do not have access to that hardware.

**Comment by kurisu-gh** [comment]
I'm also interested in getting support for the Strikepack FPS Dominator with DS4. I can confirm that the above strikepack+ds4 v.1 VID+PID combinations are the same as mine (SONY VID and 0x05C5 -> increment of the PID of the ds4 v.1's PID).

I cloned the DS4Windows project and simply added `
            new VidPidInfo(SONY_VID, 0x05C5, "Strikepack + DS4 v.1"), //Collective Minds Strikepack FPS Dominator add-on + DS4 controller` to the `knownDevices` array, built the solution, and ran the DS4Windows.exe but unfortunately it could not find the controller. @Ryochan7, would that be the correct first try? I'm not so familiar with the codebase, was just hoping it would be as easy as that.

The Strikepack+DS4 combination does not show up under the Game Controllers panel. Does this matter? The Strikepack+DS4 combination does show up under Device Manager as an HID. 

On a separate note, the Strikepack+DS4 combination can be successfully used with [ScpToolKit](https://github.com/nefarius/ScpToolkit). But I'd prefer to get this to work in DS4Windows somehow. If you can help point me in the right direction on how to develop this, I can give it a try.
