### ISSUE TITLE
[Feature] Add support for DSU Client (emulate controller from remote DSU server)

### ISSUE THREAD

**Issue by nb-programmer** [Ryochan7/DS4Windows#2531]
**Type**: Feature request

**Version**: 3.1.3 (current as of issue)

**Details**: The current version of DS4Windows has support for acting as a DSU Server, which is nice for Dolphin and CEMU. But I have a DSU server running already which connects to my DS4. I would like DS4Windows to have an option to connect TO a DSU server (and enumerate controllers, bindings, etc.) and emulate an XBox controller from that input. Touch pad, gyro, buttons and rumble are all transmitted through the DSU protocol. Only issue might be lightbar color I think

**Comment by ld892012** [comment]
Good idea, at this time there is no way to emulate a controller from a DSU client
