### ISSUE TITLE
[TODO] Stick Delta Acceleration

### ISSUE THREAD

**Issue by Ryochan7** [Ryochan7/DS4Windows#2534]
While playing Mass Effect 2 a few months ago, I wanted to try to test out a form of delta acceleration for stick mouse to help speed up the mouse pointer. After some tweaking, got a version made that improved the experience even compared to prior attempts. I cannot remember how much of the game I ended up playing with stick delta acceleration enabled though. Stopped using the implementation after that as I started doing some Steam Controller experiments and that type of acceleration is sort of pointless for touchpads. It might be nice to try to add some form of delta acceleration option for LS and RS especially when playing FPS games.

https://gitlab.com/ryochan7/switchpromappertest/-/blob/action_ideas/switchpromappertest/StickActions/StickMouse.cs#L219

**Comment by Ryochan7** [comment]
Got around to making a short video showing what the current state of the feature is. Using Mass Effect 2 in the video as that was the first game I played with the updated routine. The video starts with a gameplay segment showing stick delta acceleration enabled. The same area is played again with stick delta acceleration disabled. Not a side by side but the difference is very apparent.

Switch Pro Stick Delta Acceleration Demo
https://www.youtube.com/watch?v=HDaozGzURrM

**Comment by Ryochan7** [comment]
First draft. Just enough work was done to shoehorn the code into the Mapping class. Does seem like an improvement though. Need to add some exposed settings

https://github.com/Ryochan7/DS4Windows/tree/deltaaccel_testing

**Comment by Ryochan7** [comment]
More commit. Settings are now exposed and configurable.

**Comment by Ryochan7** [comment]
I think it is pretty much finished. Will probably merge the changes into master soon and try to get this feature in the next DS4Windows release.

**Comment by Ryochan7** [comment]
This code has been merged into the master branch.

**Comment by gfxpixeldesigns** [comment]
Would there be any possibility for this to work with regular analog joystick movements (none mouse input)

**Comment by Ryochan7** [comment]
Does not really make sense when converting from one ABS coordinate system to another. That mode is mainly meant for dealing with converting from the stick's ABS coordinate system to the relative coordinate system used for the virtual mouse. There are plenty of other options for tweaking the output curve used when it comes to converting ABS coordinate systems.

**Comment by gfxpixeldesigns** [comment]
Ahh ok i might have misunderstood how this works. I was thinking of it as a traditional ramp up time sensitive type of acceleration value.
