### ISSUE TITLE
[Request] Switch Wired Controller (3rd Party)

### ISSUE THREAD

**Issue by mc711** [Ryochan7/DS4Windows#2535]
just wanted to request, if you could add switch wired controllers (no wireless). i got one of those powerA enhanced wired switch controllers for cheap. although it's completely barebones, it's really light and would be a great windows controller too. the only thing i found to work was XOuput from https://github.com/CaptainProton42/XOutput but it uses the deprecated SCP Virtual Bus Driver. thanks

**Comment by aneesdev** [comment]
@mc711 try this one https://github.com/csutorasa/XOutput (it uses ViGEm)

**Comment by Ryochan7** [comment]
Cannot support hardware I do not have. That task would be up to you to perform on your machine and then submit a pull request to get the changes included. If you want me to do it then you have to gift me a PowerA controller for my own use so I can properly test compatibility.

**Comment by mc711** [comment]
@Ryochan7 i appreciate it, but in the meantime i've found much better solutions. at the time i was hoping for a AIO solution, but
aneesdev's recommendation fills the ViGEm issue i was worried about, also i found reWASD has a virtual bluetooth controller emulator that allow pairing any controller (even wired) to external devices like PS4, Switch, iOS and Android Devices.

thank you for the effort. maybe if i find a really cheap one again ill forward it to you :D
