### ISSUE TITLE
Tray icon gone / causes crashes in 3.1.3 with custom exe-name. Crashed with message TrayIcon is not created.

### ISSUE THREAD

**Issue by nyankatt** [Ryochan7/DS4Windows#2545]
On my main computer DS4Wins trayicon is gone after updating from 3.1.2 when using custom exe-name, and the application crashes when disconnecting a controller while it's minimized. If the application window is open there's no crash. Version 3.1.2 works as intended without any issues.

However this does not appear to happen on my laptop, running the exact same version of windows (installed from same medium) so they should be somewhat identical. 3.1.3 works perfectly fine on that, trayicon and all with custom exe-name. Because of this I tried removing all trace of 3.1.3 then downgrade to the version I initially installed on my laptop then use the updater to update, but I still get the same issue. I even tried using the same custom exe-name but that didn't seem relevant.

[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/9439687/ds4windows_log.txt)

**Comment by Yohoki** [comment]
There's some issues with the trayicon and custom names right now. Some of these issues have been addressed already and will be pushed in the next update. The push to the newer .Net 6 broke a couple things.

Check version 3.1.4+ when they release and see if that version has fixed the issue. For now, [version 3.0.18](https://github.com/Ryochan7/DS4Windows/releases/tag/v3.0.18) is the last version before the .Net 6 changes. It _should_ still work fine for you.

**Comment by Yohoki** [comment]
[Version 3.1.4](https://github.com/Ryochan7/DS4Windows/releases/tag/v3.1.4) was released today and has the newest fixes in it, relating to the taskbar icon and custom names. Give that a go and see if it fixes your problem. Come back and give a reply so we know if it's all good. :)

**Comment by nyankatt** [comment]
All good!

Thanks!
