### ISSUE TITLE
Possible to temporary disable gyro whilst holding another button?

### ISSUE THREAD

**Issue by keem85** [Ryochan7/DS4Windows#255]
So here's my scenario.. Activating gyro with L1, so that in GTA5 that means I'm aiming with the gyro.. But while I'm aiming with the gyro, I'd also like to have smooth turning with my right thumb joystick.. So that the gyro can be temporarily disabled by the right thumbstick whilst still holding the original L1 button.
Is that possible somehow?

**Comment by Ryochan7** [comment]
That is not possible with the current mapping options. There is no mode shift for gyro controls or set support in DS4Windows. That type of functionality would be needed to allow that kind of mapping to be possible.
