### ISSUE TITLE
Add support for Thrustmaster Eswap Pro (PS4)

### ISSUE THREAD

**Issue by miroslav-suvada** [Ryochan7/DS4Windows#2553]
This was already discussed under #2188 but never resolved. I would like to help with providing needed information for implementation.

**Comment by Kanuan** [comment]
Controller info:

VID: 0x044F
PID: 0xD00E

## Questions

1. Is this a wired only controller?
2. Of those, which functions does this controller have?
    - Lightbar
    - Rumble
    - Motion (gyroscope, accelerometers)
3. Does it has a headphone jack? Does Windows detect it when connected via cable?

## Provide the following info

1. Download [Ryochan7's HidReportInspector software](https://github.com/Ryochan7/HidReportInspector/releases/tag/v0.0.1)
    - It's the .7z file, which you will need the 7zip software to open and extract
    - Not sure if WinRAR can open .7z files
1. Execute the HidReportInspector
    - It may ask you to download a database of HID devices, accept it
1. Locate your controller in the list
1. Send a screenshot of its window. It should look more or less like the image below:

![image](https://user-images.githubusercontent.com/24910442/186779275-f555df9e-5175-4ac0-a453-41748a1dad61.png)

**Comment by miroslav-suvada** [comment]
1. Wired only
2. Supports only rumble
3. Has headphone jack

I'm unable to run the HidReportInspector.exe
![image](https://user-images.githubusercontent.com/23190737/187968371-4a1cf1a8-1bec-48b8-a1a5-0cbc6a241324.png)

I have .NET 6 SDK and runtime installed. When I click Yes nothing happens. What version of .NET should I install?

**Comment by Masamune3210** [comment]
Make sure you have the desktop runtime installed and not just the console runtime, its a common issue reported

**Comment by Kanuan** [comment]
I _think_ .NET 5. Link: https://dotnet.microsoft.com/en-us/download/dotnet/5.0/runtime

![image](https://user-images.githubusercontent.com/24910442/187968931-d5abbea9-4140-4748-ba0a-ac8d23d4778e.png)

**Comment by miroslav-suvada** [comment]
Alright I have .NET runtime 6.0 as well as 5.0 both x64 and x86 (double checked by downloading installers) but it still won't run. I'm on Windows 11.

**Comment by Kanuan** [comment]
Try downloading version 0.0.1

**Comment by miroslav-suvada** [comment]
![image](https://user-images.githubusercontent.com/23190737/187975712-50a2aa70-cca6-4cde-9ad8-b318f8445416.png)

**Comment by Kanuan** [comment]
Yeah, that's not good. The controller presents itself as a Xinput device ("Xbox like" controller) to Windows, which DS4Windows doesn't support

Here an image comparing the structure of a Xbox 360 controller:

![image](https://user-images.githubusercontent.com/24910442/187976381-b6378a04-af42-40e2-bd1b-889199b447c0.png)

The question is: is this native from the controller, which would make it unsupportable, or is this the work of a driver from the manufacture?

1. Open Windows' Device Manager
2. Change the "View" at the top to "Devices by CONTAINER"
3. Locate your controller's container then expand it
4. Send a screenshot of the container and sub-items

**Comment by miroslav-suvada** [comment]
![image](https://user-images.githubusercontent.com/23190737/187991875-90172d39-a23e-4c63-b51f-112123854bdd.png)

**Comment by Ryochan7** [comment]
Unless you can find a way to get the controller to initialize as an HID compatible controller then this is a non-starter. The controller switching to XInput mode on PC makes adding any form of support impossible. Maybe you need to install a special filter driver to get the controller working outside of XInput mode.

**Comment by SakifX9** [comment]
> Unless you can find a way to get the controller to initialize as an HID compatible controller then this is a non-starter. The controller switching to XInput mode on PC makes adding any form of support impossible. Maybe you need to install a special filter driver to get the controller working outside of XInput mode.
Hey, I am using the controller without the drivers installed and Steam recognises it as a PS4 controller apparently, is this what you are looking for? 
![image](https://user-images.githubusercontent.com/16516667/189521702-3f522caa-13e5-4037-8865-fd5e9b6ed39b.png)

**Comment by Kanuan** [comment]
> Hey, I am using the controller without the drivers installed and Steam recognises it as a PS4 controller apparently, is this what you are looking for?
> ![image](https://user-images.githubusercontent.com/16516667/189521702-3f522caa-13e5-4037-8865-fd5e9b6ed39b.png)

Ok, this seems promising. I won't be home until tomorrow, but I'll compile a test build once I'm back.

From the input report it looks like it doesn't have gyro, through we need to test (I think?) with the correct flags to test for gyro and touchpad assuming the controller can communicate as normal with DS4Windows

**Comment by Lunahria** [comment]
I could only get feature report 0x03 to show something and this is what I got:
```
03 21 27 04 CD 00 2C 56 00 00 00 00 00 00 00 00
00 00 0D 0D 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00
```
I'm not sure if this controller has gyro, it has been a while since I used it though.

**Comment by miroslav-suvada** [comment]
I can confirm that after uninstalling Thrustmaster drivers HID Report Inspector is reading the controller as HID-compliant game controller and reads inputs as expected. AFAIK there is no motion tracking hardware inside. I'm pretty sure I read it somewhere but can't find where. Thrustmasters website is pretty shy when it comes to tech specs...

**Comment by miroslav-suvada** [comment]
Alright after adding VidPidInfo to DS4Windows/DS4Library/DS4Devices.cs I can also confirm that DS4Windows registers controller and works as expected. I'm not a C# developer so couldn't update the code required to report only available features but I can at least confirm that gyro and lightbar are not working. Rumble and touchpad are working.

**Comment by Lunahria** [comment]
I just did the same as above with this VidPidInfo:
```csharp
new VidPidInfo(0x044F, 0xD00E, "Thrustmaster eSwap Pro", InputDeviceType.DS4, VidPidFeatureSet.NoGyroCalib | VidPidFeatureSet.NoBatteryReading)
```
And everything seems to be in order, analog axis are correct, touchpad, multi-touch and touchpad click, both rumble motors and all the buttons present on the controller are working.
One issue remains, and that would be adding the back buttons to the list and letting them be assignable.

**Comment by miroslav-suvada** [comment]
> I just did the same as above with this VidPidInfo:
> 
> ```cs
> new VidPidInfo(0x044F, 0xD00E, "Thrustmaster eSwap Pro", InputDeviceType.DS4, VidPidFeatureSet.NoGyroCalib | VidPidFeatureSet.NoBatteryReading)
> ```
> 
> And everything seems to be in order, analog axis are correct, touchpad, multi-touch and touchpad click, both rumble motors and all the buttons present on the controller are working. One issue remains, and that would be adding the back buttons to the list and letting them be assignable.

Well I'm afraid it won't be possible as it looks like those buttons are mapped directly through TrustMapper software and then written to internal memory of controller itself because even after uninstalling the software all mappings stayed intact. I have one profile with all back buttons unbind and those are not reporting any values after being pressed. On the other profile with mapping to let's say square button it just reports square button input.

**Comment by Lunahria** [comment]
> Well I'm afraid it won't be possible as it looks like those buttons are mapped directly through ThrustMapper software and then written to internal memory of controller itself because even after uninstalling the software all mappings stayed intact. I have one profile with all back buttons unbind and those are not reporting any values after being pressed. On the other profile with mapping to let's say square button it just reports square button input.

That would require some reversing of ThrustMapper or the driver then. In this case it's a bit of a shame that they are packaged together by the company and likely depend on each other for interacting with the controller.

**Comment by SakifX9** [comment]
> Alright after adding VidPidInfo to DS4Windows/DS4Library/DS4Devices.cs I can also confirm that DS4Windows registers controller and works as expected. I'm not a C# developer so couldn't update the code required to report only available features but I can at least confirm that gyro and lightbar are not working. Rumble and touchpad are working.

could you send me this build

**Comment by miroslav-suvada** [comment]
> > Alright after adding VidPidInfo to DS4Windows/DS4Library/DS4Devices.cs I can also confirm that DS4Windows registers controller and works as expected. I'm not a C# developer so couldn't update the code required to report only available features but I can at least confirm that 
[DS4Windows_eswap_3.1.4.zip](https://github.com/Ryochan7/DS4Windows/files/9591230/DS4Windows_eswap_3.1.4.zip)
gyro and lightbar are not working. Rumble and touchpad are working.
> 
> could you send me this build

Sure

**Comment by Lunahria** [comment]
> Does the controller has an actual lightbar? Or just that LED and people are not sure if it should change colors?

It does not have lightbar for sure, gyro is up in the air but it probably does not have it.

[USB_Tree_View_eSwap.txt](https://github.com/Ryochan7/DS4Windows/files/9608735/USB_Tree_View_eSwap.txt)

**Comment by Kanuan** [comment]
Thx for the answer. If possible, also send the USB Tree View info with the controller in ds4 mode

**Comment by miroslav-suvada** [comment]
New release built with eswap support

[DS4Windows_eswap_3.1.6.zip](https://github.com/Ryochan7/DS4Windows/files/9631306/DS4Windows_eswap_3.1.6.zip)
