### ISSUE TITLE
[Feature Req.] "finger on touchpad" to button mapping

### ISSUE THREAD

**Issue by AudioDuplication** [Ryochan7/DS4Windows#2554]
I would like to request another "button" to be added to the "Controls" tab.

So that "When a finger is touching the touchpad" press button x once
And "When finger stops touching touchpad" press x again (once)

Thanks for considering my feature request. I would much appreciate it.

**Comment by Ryochan7** [comment]
Been needing to at least add an option to assign On Touch button mapping for a long time. Not sure about this type of mapping behavior though; probably would just need a different flag to set the output behavior. Would need a definite use case for it and I cannot think of one.

**Comment by AudioDuplication** [comment]
Yes that is what I mean, thanks for clarifying.

**Comment by Ryochan7** [comment]
Need to get around to adding some form of property group for Touchpad button behavior. That seems like the path of least resistance. Got a couple of other features incorporated from my other experiments though.

**Comment by Ryochan7** [comment]
Testing changing the touchpad button behavior. Going with the simpler version which would allow button activation on Touch or Click. Trying to set up a Release option would involve a much bigger change. Would need something else to maintain a set button down event for a Release option. Including the draft in its own branch.

https://github.com/Ryochan7/DS4Windows/tree/touchbuttons

**Comment by Ryochan7** [comment]
Got a Release activation routine working

**Comment by Ryochan7** [comment]
Changed the MultiTouch action behavior on Release; routine now waits until Touchpad has no touches before activating action. Also, jumped the gun and merged the changes to the `master` branch.

**Comment by Ryusennin** [comment]
Can "click" and "on touch" be used in the same profile, or are they mutually exclusive?
In 3.1.7 it looks like I have to use one or the other.

As a practical example, I'm thinking about a game like Horizon 1, where you can call the map by clicking the touchpad, and you can temporarily display the dynamic HUD by just tapping it.

**Comment by fsmid** [comment]
> Can "click" and "on touch" be used in the same profile, or are they mutually exclusive? In 3.1.7 it looks like I have to use one or the other.
> 
> As a practical example, I'm thinking about a game like Horizon 1 on PS4, where you can call the map by clicking the touchpad, and you can temporarily display the dynamic HUD by just tapping it.
I also want to combine a seperate action for touch, click and release.

I am trying to accomplish the following
Touchpad touch: Key1 is send
Touchpad click: key2 is send
Touchpad release: key3 is send
I believe that was the original intend of the @AudioDuplication
