### ISSUE TITLE
[Feature Req.]A function (checkbox) that does not execute when the button is released if another Special Action with the same triggering button is executed first

### ISSUE THREAD

**Issue by gwin7ok** [Ryochan7/DS4Windows#2557]
Implemented a function (checkbox) that prevents a Special Action with "Run on Trigger Release" from being executed even if the button is released if another Special Action combined with that button was executed first. can't you?

example:
Special Action A: PS "Run on Trigger Release"
Special Action B: PS + UP

Current specs:
1.PS(down) and UP(down) - Run Special Action B
2.PS(up) - Run Special Action A

Desired specifications
case A: The checkbox is ON with Special Action A - 2. Special Action A is not executed
case B: The check box is OFF in Special Action A - 2. Special Action A is executed

**Comment by Ryochan7** [comment]
Seems like a bad idea to be honest. Some form of hold or tap detection would probably work better for that scenario. Based on what currently exists, it looks like you are more likely wanting to assign Special Action A as a **Multi-action Button** using only the Tap Trigger. Special Action B can stay bound to a normal Macro. That way, Special Action A will be activated if the PS button was only tapped. Only Special Action B would get executed if you press both buttons as long as PS is held down for a bit.

Be mindful that the tap duration is static in the code and it is set to 150 ms.

**Comment by gwin7ok** [comment]
> Seems like a bad idea to be honest. Some form of hold or tap detection would probably work better for that scenario. Based on what currently exists, it looks like you are more likely wanting to assign Special Action A as a **Multi-action Button** using only the Tap Trigger. Special Action B can stay bound to a normal Macro. That way, Special Action A will be activated if the PS button was only tapped. Only Special Action B would get executed if you press both buttons as long as PS is held down for a bit.
> 
> Be mindful that the tap duration is static in the code and it is set to 150 ms.

I forgot the presence of the Multi-action Button setting.
By doing the settings as you said, I was able to achieve the desired processing.
Thank you
