### ISSUE TITLE
UDP Server not working

### ISSUE THREAD

**Issue by BlizzBlu** [Ryochan7/DS4Windows#2574]
I spent four hours trying to figure out why Cemuhook wouldn't accept my DS4Windows inputs, only to find out that not even a localhost connection via PadTest yielded any results. Connecting via a remote IP didn't work either, which is what I've been trying to do in the first place.

Port has been forwarded, the firewall isn't blocking anything. I even went as far to check whether I can host a Minecraft server to test the connection - it just doesn't work, even though the log states that it's listening to a connection.

What am I doing wrong?

**Comment by Yohoki** [comment]
Are you running DS4Windows on the same machine as Cemu, or are they on separate machines?

For Cemu, there doesn't seem to be an option to choose the IP address that it connects to, so you have to have DS4Windows running on the same machine.

**Comment by BlizzBlu** [comment]
Cemu is running on a different machine, though Cemuhook is supposed to let you provide an IP and port by editing the cemuhook.ini file.

But since PadTest is unable to find the UDP server from DS4Windows on a local machine (using 127.0.0.1), there's something else that's not working here.

**Comment by Ryochan7** [comment]
PadTest is working fine for me on my machine. Is some other app using the port number that the UDP server is trying to use? The UDP server would fail to start if that were the case and an error should show up in the Log although I don't think that has ever been tested.
