### ISSUE TITLE
Suggestion : Update to latest HidHide client

### ISSUE THREAD

**Issue by TheMasterDingo** [Ryochan7/DS4Windows#2581]
Just a reminder that HidHide is a few versions ahead, maybe DS4 should update the link and integration. Tried with latest version but DS4 does not show the "key" icon when the physical controller is hidden

**Comment by TheMasterDingo** [comment]
> The HidHide check is working as normal on the latest versions of HidHide and DS4Windows.
> 
> Make sure that the HidHide Client is closed when starting DS4Windows otherwise the verification will fail since HidHide check access will be already busy with the client

Oh no it works as it should with the version that DS4windows installs (1.1.50 iirc) , i was suggesting to update it to the latest 1.2.98 ( but i think this is not done on purpose according to the release notes of DS4w 3.1.1) 
Anyway i removed 1.1.50 and installed the latest 1.2.98 but looks like ds4w does not work well with it

**Comment by TheMasterDingo** [comment]
After a reboot it showed, sorry for the dumb report.

**Comment by TheMasterDingo** [comment]
Thank you for the explanation. I can confirm that it works fine with the latest version 1.2.98, only thing is that it does not link to HidHide from Ds4windows from the settings ( due to the default directory change in HidHide).

**Comment by Ryochan7** [comment]
Done with commit c13b5a990d1fb171ccd5ddaf737efe32bea0fd09. Not really much of a point for me at least. Not really any new defining feature I would use that was not available in 1.1.50.0. Also, I still had to compile my own driver to get one that performs according to my requirements. Performance of vanilla HidHide 1.2.98 is about the same as vanilla 1.1.50.0 though.
