### ISSUE TITLE
Special Actions don't import / export with profiles

### ISSUE THREAD

**Issue by khowe085** [Ryochan7/DS4Windows#2583]
**Describe the bug**
Special Actions appear under the profile editor, but do not export with the profile.  They appear to be global instead of profile specific.

**To Reproduce**
1. Edit a profile
2. Goto special actions
3. Add a special action
4. Export profile
5. Profile XML will have the name of the action, but not the action itself. 
6. Delete the profile
7. Create a new profile, you will see the actions from the previous profile

**Expected behavior**
Actions should live with the profile and import / export in a XML collection with said profile. 

**Additional context**
If actions were implemented this way for sharing across profiles, then a much better approach would be to have an import / export on the special actions tab.  Having the actions be global doesn't really make sense as the triggers are controller type specific.

**Comment by Yohoki** [comment]
This wouldn't be a bad thing, really. I don't know about anyone else, but pretty much all of my special actions are used for one profile only. The only one that's universally shared between my profiles is disconnect BT.
![image](https://user-images.githubusercontent.com/44595371/190300575-7bd234ba-bacb-44fd-a088-e0ffaa4b92aa.png)

I know, Ryochan is just now working on the save/load process and is testing out a couple new ones and possibly making a new custom one. So, if he's wanting to add any big changes like this to it, now would probably be a good time to bring them up.

**Comment by Ryochan7** [comment]
That's the way Special Actions have worked since at least the Jays2Kings build;I don't know about any earlier than that. Special Actions have always been global across the app rather than saved to a profile. Profiles can link to saved special actions to have them enabled or disabled as needed. I don't really use Special Actions other than the Disconnect BT action in my config.

**Comment by Yohoki** [comment]
> That's the way Special Actions have worked since at least the Jays2Kings build

I think he's requesting a feature, more than reporting a bug. :P 

It wouldn't hurt to have the special actions tied to specific profiles. It's already in the profile area anyway and they only apply to specif profiles. But, I also haven't looked at how they are coded or how easy it would be to make the list per-profile.

**Comment by khowe085** [comment]
I could see it going either way... but I'm leaning towards making them profile specific as it makes more sense to me.

If they were to stay global, then it would probably make more sense to move them to their own tab and give them an import / export function.  When you import a file it would then just merge the imported XML file with the XML file stored in app data.

My use case: 
I was trying to use [this mod](https://github.com/AzureBlood2/xivcrossbar), but wanted to replace AutoHotKey with DS4W.  This mod requires that AHK or DS4W hold CTRL + function key. 

Holding CTRL+ F11 (Left trigger) and CTRL+F12 (Rightt rigger) activates the mod and then while holding this combo you press F1-F8  (Face buttons) to activate an in-game action.  There is also additional functionality for pressing and holding F9 (Share) and F10 (Options) and using the face buttons.

I can't do chords, macros can't hold a key until, and I can't have multiple shift modifiers so I ended up using special actions to switch to an alternate profile that had the face buttons mapped to F1-F8.  The special actions run on trigger soft pull and a full pull is the corresponding F-Key. 

I wanted to export this profile so that other people could use it and that is when I found out actions are global. Currently the mod just auto-launches the AHK script (Scary this is even a thing... which is why I don't want AHK on my system) , so Importing even one profile is annoying. 

Due to the current implementation of special actions my setup instructions have the user edit the profile and create the special actions.  It was either that or tell them to copy / paste files and potentially break their other DS4W profiles by overwriting the Actions.xml in appdata. Having actions be global but importable would simplify things, but having them be part of the profile would be much better. 

My ideal wold would to have shift modifiers switch to a nested profile and chords would be supported natively... but that is outside the scope of what I'm reporting here. 

(Attached the profiles if you are interested in seeing how I implemented this)
[Profiles.zip](https://github.com/Ryochan7/DS4Windows/files/9588473/Profiles.zip)

**Comment by Yohoki** [comment]
I've used AutoHotKey on a few profiles for a similar reason. Valhalla is the one I remember easily, because it's hotbar required pressing 1-0 on the keyboard to select the item/tool. Obviously, having 10 hotbar keys on a controller is infeasible, so I use an AHK script to scroll through the bar instead.

More useful I think would be to allow multiple shift modifiers. For instance have the option to set L2 as a shift modifier and ANY additional buttons would have a second input. That way you could use L2 or R2 as a kind of 'global' modifier, each able to affect all the other buttons separately.

But, that's a different topic, and might add quite a bit of confusion.... not to mention a pretty heavy rework of the input mapper code.

**Comment by khowe085** [comment]
That is how all keyboard mappers I've used have worked. You press a key and the entire keyboard shifts into what is essentially a different profile. Your shift key can either be momentary or toggle, and you can also have a key in the shift profile fallback to the root profile. 

That is what I kind of setup with special actions and a second 'alt' profile. It would be better to have that second profile not show up in the main list, since it was a sub profile... but yeah that is a lot of work
