### ISSUE TITLE
Not lunching 

### ISSUE THREAD

**Issue by ikenna2001** [Ryochan7/DS4Windows#2584]
Since I got the new version of DS4 it has not launched and I have tried all fixes I have found on youtube and Reddit.

**Comment by Yohoki** [comment]
That's still not any info to go on... "All the fixes" is not very helpful for a program that's almost 10 years old and has been constantly getting updates.

Ok, what version were you on before you updated? Try [Version 3.0.18](https://github.com/Ryochan7/DS4Windows/releases/tag/v3.0.18) and see if it works. If this one works, you need to update your .NET runtimes.

If that doesn't work, give us a bit more info.
- Windows version
- last working DS4W version
- What "All the fixes" have you tried?
- Do you have any logs, and can we see them?
- What does "Not launching" look like? Is nothing happening, is it showing up in task manager, is it crashing with an error?

**Comment by Kanuan** [comment]
# Verifying if you have the correct version of the .NET Desktop Runtime installed

1. Open Windows PowerShell
2. Type and run the `dotnet --info` command
3. Verify if in the end of the list appears the `Microsoft.WindowsDesktop.App 6.0.X [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]`
    - Attention to the "WindowsDESKTOP.App" part 
    - Check the image below
    - ![image](https://user-images.githubusercontent.com/24910442/190564451-d0a67a92-2cc2-4003-b18d-c21954794eb2.png)
4. If you don't have the latest version check the following link: [[x64 .NET 6.0 Runtime](https://dotnet.microsoft.com/download/dotnet/6.0/runtime)](https://dotnet.microsoft.com/download/dotnet/6.0/runtime)
    - ![image](https://user-images.githubusercontent.com/24910442/190564483-ef419369-d2d9-4213-a755-c836007cc1b9.png)

# Checking if DS4Windows settings are not corruped

Maybe your DS4Windows user data got corrupted? I recommend fully deleting DS4Windows and its user data and then start clean again by download the latest version. Check the following:

**Fully deleting DS4Windows**

DS4Windows data may be in 2 different folders. To get fully rid of everything, follow the "Main program" and the "Settings and user data" **SUB-SECTIONS** of the following page: [Uninstalling DS4Windows and related drivers](https://docs.ds4windows.app/guides/uninstalling-ds4windows)

After that, re-download the latest x64 .zip version from the releases page of this github.

**Comment by ikenna2001** [comment]
hello, i am sorry for being vague in my original post. the fixes I'm referring to is completely removing ds4 from my windows and reinstalling it. i have also tried downloading the correct version .net runtime and also the vigembus software as well, i have also tried older versions of ds4 and the .net runtime which all end the same and i have as far as resetting my pc and all have not worked

**Comment by ChotaFallen** [comment]
I have the same problem. I can´t run version 3.1.4. I installed the .net 6.0.0 several times but at lunch it comes always the same error tht the framework is not installed. Nothing helped

**Comment by Kanuan** [comment]
@ChotaFallen  Did you check the instructions in my previous comment in this thread on how to verify if you have the correct build of .NET framework installed?

**Comment by ChotaFallen** [comment]
It open automatically the website, and that was the wrong one.
So I go to 
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.9-windows-x64-installer
that worked for me.
Your link didt worked for me. Dont know why. But now it is fine.

Thank you for the great programm

**Comment by ikenna2001** [comment]
i tried that and it still did not work. i think it's crashing upon me trying to launch the program.

**Comment by alpharou** [comment]
Same for me. Running it as administrator does not crash the program, but it cannot be run at pc startup, which is what I want. For now I will roll back to a version that doesnt use .NET6
