### ISSUE TITLE
PS3 DualShock connection issues on working hardware

### ISSUE THREAD

**Issue by cjsio** [Ryochan7/DS4Windows#2585]
**Describe the bug**

I have 2 official PS3 DualShock controllers in great working condition. The 1st controller has worked great with DS4Windows for the last few months ever since install. I followed all the install directions at the time and set up 3 button layout profiles along with some auto profiles more recently.

Everything has worked great until I tried to get the second PS3 controller detected in parallel. No matter which secondary USB port I plugged the second controller into, DS4Windows would not detect it. I then unplugged the first controller's cable and plugged it into the second controller, and DS4Windows immediately detected the second controller so long as it was connected to the first controller's USB port.

So I believe this is a driver issue. I was thrilled to ditch BetterDS3 for the much better, more robust DS4Windows, but something I've struggled with regarding both applications is making sure the correct driver is installed for each controller. During my troubleshooting, I uninstalled the working PS3 controller's driver, and now neither controller is detected by DS4Windows no matter which port each one is in.

I've followed every piece of troubleshooting info I've found so far and no luck. Most recently, in this GitHub repo, it suggests looking for an "HID-compliant game controller device" inside Device Manager's HID section, but there are no such devices here. However, there is a Nefarius HID Devices section that shows up whenever I have at least one controller plugged in. This section contains 2 "PLAYSTATION(R)3 Controller" devices and 2 corresponding "XINPUT compatible HID device" records.

**Question:** Are these the correct drivers / device types to show up? And if not, which driver should each have, and if applicable, is there somewhere the needed driver(s) can be downloaded from?

I have tried many combinations of driver updates per controller device. Inside my local driver selection, I can select "DS3 Compatible HID Device", "USB Input Device", or "MotioninJoy Virtual Xinput device for Windows" - but none of these got DS4Windows to detect either controller.

With the aforementioned drivers inside Device Manager's Nefarius HID Devices section, I'm able to use both controllers to interact with Rocket League and PCSX2 properly, _**except**_ that I am unable to use my custom defined profiles, which is a must for some games.

Please give any pointers or advice on how to proceed. It would be fantastic if there were a built-in driver check to verify PS3 controllers had the correct driver installed to work with DS4Windows.

Thank you for your time.

**Expected behavior**

Both controllers should show up inside DS4Windows.

**Desktop**

 - Official PS3 DualShock controllers
 - OS: Windows 11 Pro
 - DS4Windows Version 3.1.4
 - ViGEmBus 1.17.333.0

**Screenshots and Logs**

2022-09-16 00:01:01.2002|INFO|DS4Windows version 3.1.4
2022-09-16 00:01:01.2002|INFO|DS4Windows exe file: DS4Windows.exe
2022-09-16 00:01:01.2002|INFO|DS4Windows Assembly Architecture: x64
2022-09-16 00:01:01.2002|INFO|OS Product Name: Windows 10 Pro
2022-09-16 00:01:01.2002|INFO|OS Release ID: 2009
2022-09-16 00:01:01.2002|INFO|System Architecture: x64
2022-09-16 00:01:01.2002|INFO|Logger created
2022-09-16 00:01:01.2424|INFO|LinkedProfiles.xml can't be found.
2022-09-16 00:01:02.0508|INFO|Running as User
2022-09-16 00:01:03.0729|INFO|Starting...
2022-09-16 00:01:03.0729|INFO|Using output KB+M handler: SendInput
2022-09-16 00:01:03.0729|INFO|Connection to ViGEmBus 1.17.333.0 established
2022-09-16 00:01:03.0729|INFO|Searching for controllers...
2022-09-16 00:01:03.0729|INFO|Using Shared Mode
2022-09-16 00:01:07.7288|INFO|Stopping Virtual Output Controllers
2022-09-16 00:01:07.7288|INFO|Closing connection to ViGEmBus
2022-09-16 00:01:07.7288|INFO|Stopping DS4 Input Controllers
2022-09-16 00:01:07.7288|INFO|Stopped DS4Windows
2022-09-16 00:01:08.9899|INFO|Starting...
2022-09-16 00:01:08.9899|INFO|Using output KB+M handler: SendInput
2022-09-16 00:01:08.9899|INFO|Connection to ViGEmBus 1.17.333.0 established
2022-09-16 00:01:08.9899|INFO|Searching for controllers...
2022-09-16 00:01:08.9899|INFO|Using Shared Mode

**Comment by Kanuan** [comment]
> This section contains 2 "PLAYSTATION(R)3 Controller" devices and 2 corresponding "XINPUT compatible HID device" records.

Your controllers are in XInput mode. You need to use the DsHidMini Control UI (DSHMC.exe) to change the controllers into DS4Windows mode.

For more info: [DsHidMini HID Device Modes Explained](https://vigem.org/projects/DsHidMini/HID-Device-Modes-Explained/)

**Comment by cjsio** [comment]
> > This section contains 2 "PLAYSTATION(R)3 Controller" devices and 2 corresponding "XINPUT compatible HID device" records.
> 
> Your controllers are in XInput mode. You need to use the DsHidMini Control UI (DSHMC.exe) to change the controllers into DS4Windows mode.
> 
> For more info: [DsHidMini HID Device Modes Explained](https://vigem.org/projects/DsHidMini/HID-Device-Modes-Explained/)

Lifesaver! Had forgotten entirely about DsHidMini but sure enough I still had it downloaded. Hope this helps a passerby or two. Don't forget to run as admin. Cheers
