### ISSUE TITLE
DS4 Is not detecting this joystick 

### ISSUE THREAD

**Issue by cygnuswaves** [Ryochan7/DS4Windows#2586]
HID\VID_146B&PID_0603&IG_00
HID\VID_146B&UP:0001_U:0005
HID_DEVICE_SYSTEM_GAME
HID_DEVICE_UP:0001_U:0005
HID_DEVICE

I did everything recommended, even tried in two different computers (laptop and desktop) but i couldn't make it appear on the list. Is there something wrong with this particular joystick? Is a Nacom joystick i can add pictures if necesary

Thank you in advance

**Comment by Kanuan** [comment]
This matter was investigated already in the following discussion page: #2589 

Basically: the controller behaves as a x360 replica by itself, no third-party drivers involed. We have no idea how to make the controller "switch" to ds4 mode, so this can be closed for now
