### ISSUE TITLE
Changing Deadzone/curve/sensitivity in profile xml?

### ISSUE THREAD

**Issue by the4rpro** [Ryochan7/DS4Windows#259]
Hey,

I was wondering if there's any change to override the default 5.00 sensitivity for the R2/L2 as well as going further than 1.5 for RS/LS. Reason why I'm asking is because I'm into my R2/L2 reacting as soon as possible, especially since the R2 sensitivity only reaches around 20%, now can reach 100% if pressed extremely hardly. Sensitivity for the RS/LS so I can move/look around with just quick flicks would be amazing too.

**Comment by Ryochan7** [comment]
I don't use the sensitivity options all that much. I could raise those options in the program to allow a little more range than what is available now. As an alternative, you can change the max zone and anti-dead zone settings for the triggers or analog sticks to achieve a similar effect.

**Comment by the4rpro** [comment]
Sure thing, how would I be able to change the max zone/anti-dead zone for the triggers? I finally fixed my hardware issue regarding my analog sticks, but my triggers aren't working at all, most games don't recognise that they're being pressed, as well as DS4Windows itself only showing the R2 bar going 1/4 of the way up.

**Comment by Ryochan7** [comment]
There are tabs in the mapping options screen for configuring the max zone and anti-deadzone settings for the sticks and triggers. Changing the max zone seems like it would be helpful as you can assign a 0.25 max zone on R2 and the output for RT on the virtual Xbox 360 controller will be at 100%.

**Comment by Ryochan7** [comment]
A new release is out that allows a larger cap for sensitivity settings. Stick and sixaxis maximums have been raised to 5 and trigger maximum has been raised to 10.

https://github.com/Ryochan7/DS4Windows/releases/download/v1.4.120/DS4Windows_1.4.120_x64.zip
