### ISSUE TITLE
High Input Delay via Bluetooth connection 

### ISSUE THREAD

**Issue by AnriRB26** [Ryochan7/DS4Windows#2591]
**Describe the bug**
When connecting a Dualshock 4 controller to DS4Windows and viewing the "controller readings" tab there is a very high and unstable input delay reading and it is very noticeable in games.

**To Reproduce**
Steps to reproduce the behaviour:
1. Connect Dualshock 4 controller to DS4Windows via Bluetooth pairing
2. Click on 'Edit'
3. Set BT Poll Rate to "Max(1ms)"
4. Click on "Controller Readings"
5. Notice high input delay (>4ms) 

**Expected behaviour**
Normally when connected via Bluetooth the Dualshock 4 V2 controller should have an input delay of 0.5-1.5ms when setting the BT Polling Rate setting to Max(1ms) and the controller should never exceed 3ms input delay.

**Screenshots and Logs**
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/9609654/ds4windows_log.txt)
![ds4issue](https://user-images.githubusercontent.com/114002049/191315134-baac2bac-238b-4ca6-967b-2d215ebdfe01.PNG)

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: [Windows 10 Home 21H2 19044.2006]
 - DS4Windows Version 3.1.4

**Additional context**
This high and unstable input delay issue has never been a problem before the 3.1.4 update and after experiencing this problem with this version, no matter what version of DS4Windows I try they all have high input delay with all controllers I have tried. I managed to get the input delay back down to 0.5ms by reinstalling ver 3.1.0 but then after disconnecting and reconnecting the controller to DS4Windows the issue came back.

**Comment by IceLancerSR** [comment]
if you are on PC (not laptop) i really suggest to buy ur self extension usb cable and connect Bluetooth to it.
There is a lot of interference coming from back of  PC case , numbing BT signal. 
i did it for my self, and put cable with BT under the monitor. Sit on couch and it works no latency
