### ISSUE TITLE
Driver error when quitting a game

### ISSUE THREAD

**Issue by Newtype14** [Ryochan7/DS4Windows#2593]
**Describe the bug**
Sometimes when I quit a game, everything seems to close normally, but if I attempt to launch a game again, it will not launch, it will freeze instead and I have to force close it through Task Manager. This is the case for both Steam and RetroArch, no matter the core, no matter the game. When that happens, if I go in DS4Windows and disconnect the controller (connected via Bluetooth), the main window will show that the controller is disconnected, but if I check XInputChecker, Controller 1 still shows as Connected. Attempting to then reconnect the controller in DS4Windows will fail. In Windows, if I go in Settings => Devices, HID-compliant game controller (I believe this is the emulated Xbox controller) will show "Driver error". The only solution to all of this is to restart the PC. However, this is when things go from bad to worse. When this error occurs, restarting the PC will cause a BSOD with the error _Driver Power State Failure_. Then, the PC fails to restart and the UEFI restores itself back to factory settings. I AM NOT KIDDING YOU. **Basically, it seems that on occasion, quitting a game will cause the emulated Xbox controller driver to fail and that creates a range of issues.**

**To Reproduce**
I have honestly spent a year trying to solve this issue on my own because it cannot be reproduced. I just play a game either in Steam or in RetroArch and once I'm done playing, I quit the game. The problem is intermittent. It can happen once in two weeks, like it can happen three times in two days. In all that time, I have never been able to find that one thing that would trigger the problem consistently. It just seems to happen for no reason. Finding out that the problem was related to the controller was pure luck. For a while, I didn't even know that this was a controller issue and I wasted a lot of time.

**Some of the solutions that I've tried**

- Made sure PlayStation and Xbox Configuration Support are disabled in Steam.
- Made sure that HidHide is set up properly and that the key symbol appears in DS4Windows.
- Made sure that "Hide DS4 Controller" is unchecked.
- Uninstalling and reinstalling DS4Windows, ViGEmBus and HidHide several times.
- Uninstalling the controller in Device Manager and reinstalling it.
- Uninstalling and reinstalling .NET and Visual C++ 2015-2019.
- Making sure everything is up to date (software and drivers).
- Playing with Windows' and NVIDIA's power options.
- Turning off vibration both in DS4Windows and in-game.
- Changing controller's poll rate.
- Finally, I formatted my PC and did a clean install of the most recent version of Windows 10.

**Solutions I'm currently testing**

- Stopped assigning buttons to the Touchpad and set Touchpad Output Mode back to "Mouse" instead of "Controls".
- Disabled the "Check Battery Life" special action.
- Disabled the RTSS/MSI Afterburner overlay by turning off "On-screen Display Support" in RTSS.

**Screenshots and Logs**
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/9612151/ds4windows_log.txt)
The following are from when the issue last occurred, right after my Steam game refused to launch and froze:

In DS4Windows, I disconnected my controller. This screenshot shows that it's disconnected.
![No Controller Connected](https://user-images.githubusercontent.com/49800083/191392055-45025f84-07d4-456b-b97b-0327dce90103.png)

In XInputChecker, it still shows as connected.
![Controller Connected](https://user-images.githubusercontent.com/49800083/191392526-a67961ab-47b1-40bb-8765-ead40b9a135f.png)

The emulated Xbox controller doesn't show in HidHide.
![HidHide](https://user-images.githubusercontent.com/49800083/191392842-0a0c1923-9192-4d11-8617-4347124646f2.png)

Driver error in Settings => Devices.
![Controller Driver Error](https://user-images.githubusercontent.com/49800083/191392930-9745769e-ce3b-43f0-8668-ea95a6628c83.png)

Yellow triangle in Device Manager (only happens when the issue occurs).
![Device Manager](https://user-images.githubusercontent.com/49800083/191393102-10cb33b6-fa59-4feb-936a-a4497b076b1c.png)

**Desktop**
 - Controller: Sony DS4 v2 (CUH-ZCT2U) connected via motherboard's Bluetooth (ASRock Z390 Taichi)
 - OS: Windows 10 Enterprise LTSC 21H2 (also Windows 10 Enterprise LTSC 1809 previously)
 - DS4Windows version 3.1.4 (Issue happened with previous versions)
 - ViGEmBus version 1.18.367.0 (Issue happened with previous versions)
 - HidHide version 1.2.98 (Issue happened with previous versions)

**Additional notes**
Please note that because this problem is intermittent, testing potential solutions can take a lot of time.

**Comment by Ryochan7** [comment]
ViGEmBus has always been buggy. Was willing to let some issues slide as no alternatives existed for Windows 11 users. Now ViGEmBus is officially dead and the successor will most likely be proprietary. ScpVBus was a much better driver.

I really regret ever giving into user requests and adopting ViGEmBus. Lots of wasted energy and added stress.
