### ISSUE TITLE
Ps4 shows as Xinput

### ISSUE THREAD

**Issue by Nikarionbruh** [Ryochan7/DS4Windows#2595]
I have deleted DS4 but now my ps4 controlller gest shown like this even after hard resetting. i know it dosent seem like a big deal but i really care about this ![Immagine 2022-09-22 224418](https://user-images.githubusercontent.com/114190059/191847466-e9c283da-ee76-4fc7-b1c2-00a1dd355888.jpg)

**Comment by Kanuan** [comment]
This is not a DS4Windows issue. DS4Windows cannot influence in any shape or form your controller if it's not running. 

There is an option here that you can use to "convert into discussion" this issue. A discussion is more appropriate for your case. Once this is converted into a discussion topic I'll try helping

**Comment by Nikarionbruh** [comment]
i dont see the option

**Comment by Ryochan7** [comment]
Just going to assume you are using a third party DualShock 4 that is designed to present itself as an Xbox 360 controller when connected to a PC
