### ISSUE TITLE
DS4Windows doesn't start, "Could not load file or assembly 'Nefarius.Utilities.DeviceManagement"

### ISSUE THREAD

**Issue by dmpanch** [Ryochan7/DS4Windows#2599]
**Describe the bug**
DS4Windows doesn't start on Windows 11, please check the logs, possibly because of broken dependencies.

**To Reproduce**
1. Download the latest version
2. Install all the dependencies
3. Open an app
4. Press start in the right bottom corner

**Expected behavior**
Work as usual

**Screenshots and Logs**
[log.txt](https://github.com/Ryochan7/DS4Windows/files/9629970/log.txt)

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 
 - OS: Windows 11 Pro N 22H2
 - DS4Windows Version [e.g. 3.1.5]

**Comment by goooroooX** [comment]
Got the same error after DS4Windows auto-update. Windows 10 v. 21H1 build 19043.2075.

**Comment by Kanuan** [comment]
Same as #2598 

Error explained here: https://github.com/Ryochan7/DS4Windows/issues/2598#issuecomment-1255653310

**Comment by Edu-Nov** [comment]
Same

**Comment by bmijnendonckx** [comment]
Having the same issue since today's update.
OS: Windows 11 Pro 22H2 22621.607

**Comment by MGxFF** [comment]
Having the same issuee...how can I fix it?????

**Comment by nefarius** [comment]
Calm down, folks, fixed version 3.1.6 has been released.

**Comment by MGxFF** [comment]
havent been able to connect my controller...any help pls?

**Comment by Ryusennin** [comment]
Please don't post the same message in multiple topics.

If you have a specific problem, open a new issue.
