### ISSUE TITLE
[Request] Multi-Action Button - Scan Code option

### ISSUE THREAD

**Issue by pralima87** [Ryochan7/DS4Windows#26]
So I requested this back when J2K was still around.
He did planned to add this in a future release but the development stoped before he release it.
So just a request for consideration.

Also would be great of stead of just macros "Multi-Action Button" would also show the full "select a action screen" with the keyboard/mouse/gamepad and the macros options.

Thanks for all the updates!
Cheers!

**Comment by Ryochan7** [comment]
The scan code option is considered deprecated since keyboard events use both virtual key and scan code information by default; the scan code option might be removed in the future. Scan codes should be sent for multi-action button actions in recent releases of DS4Windows. The current scan code option only acts as a way to only send a scan code without the corresponding virtual key. Based on my experience, fake keyboard events really should contain both a virtual key and a scan code in all circumstances.

**Comment by pralima87** [comment]
Humm them I think the Multi-Action Button is just not working ;)

**Comment by Ryochan7** [comment]
I broke it. The current state was being compared against itself.

**Comment by pralima87** [comment]
Unfortunately without the "Scan Code" option in the Multi-Action Button some games do not detect the input.
Skyrim for instance is quite a mess and sometimes it only detects inputs with "scan code" enable.

So I would greatly appreciated this option to be considered ;)

**Comment by Ryochan7** [comment]
> Skyrim for instance is quite a mess

That is all that needed to be said. Anyway, it might be better if you shared the profile you are using to play Skyrim. Based on my experience, that is one game where you have to make the choice to play with either KB+M controls or full gamepad controls. You cannot use a mixed mode configuration without running into some major problems. It makes using the Steam Controller on Skyrim a much bigger hassle than it should be.

When using pure KB+M controls with DInput only enabled in a profile to unplug the virtual XInput controller, a Multi-Action button macro works perfectly fine in game. Also, the expected code path is being run.

**Comment by Ryochan7** [comment]
I would also need your Actions.xml file as well.

**Comment by pralima87** [comment]
Sorry for the late response!
Here is my profile and special actions.
[Skyrim Profile Action](https://www.mediafire.com/file/8q28k8876l6ving/Skyrim%20Profile%20Action.zip)
For Skyrim there is a SKSE dll to improve Gamepad features and circunvent the engine limitations.
The plugin is a must for gamepad users:
[Better Mouse and Gamepad support (an SKSE Plugin)](https://www.nexusmods.com/skyrim/mods/71444/?)

**Comment by pralima87** [comment]
Did some more testings and the issue is not related to Scan code ;)
Some combinations are just too fast for the Apps to detect them.
So using the "Record Delays" will fix most of the issues!

**Comment by Ryochan7** [comment]
That is one big reason that I do not use the macro system. A system more
like Xpadder for making complex assignments would have been better.
