### ISSUE TITLE
Keymapping to KB/M bot working

### ISSUE THREAD

**Issue by faddanicolo** [Ryochan7/DS4Windows#2605]
**Describe the bug**
Title

**To Reproduce**
Try mapping any key to a keyboard or mouse press

**Expected behavior**
The key gets pressed

**Screenshots and Logs**
[log.txt](https://github.com/Ryochan7/DS4Windows/files/9649598/log.txt)

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony Dualsense CFI-ZCT1W
 - OS: Windows 11 Pro 10.0.22000
 - DS4Windows Version: 3.1.6

**Additional context**
Worked until a month ago, tried reinstalling every driver, removing appdata files and redownloading ds4.

**Comment by Ryochan7** [comment]
I don't condone botting. Invalid issue

**Comment by faddanicolo** [comment]
I'm sorry botting? What about this issue is related to botting exactly?
