### ISSUE TITLE
Version 1.4.118 Borked Audio on my revolution pro

### ISSUE THREAD

**Issue by JonathonSunshine** [Ryochan7/DS4Windows#261]
Wired Nacon Revolution Pro  and on  V1.4.118 headset audio doesn't work at all, with a ticking sound when you raise or lower volume.

On v1.4.117, I would have to raise or lower the volume to "initialize" or kickstart audio output in Forza Horizon 3 but it was fine apart from that.

Rolling back fixed it.

**Comment by Ryochan7** [comment]
With recent changes, output reports will likely be sent less frequently so proper volume control should mainly be handled outside of DS4Windows. DS4Windows will only need to update the volume level for the output report when lightbar or haptic feedback data changes.

**Comment by Ryochan7** [comment]
Hopefully this problem is fixed in version 1.4.119.

**Comment by JonathonSunshine** [comment]
Sorry, tested it then with Forza 3 doing the same thing. Point me to any
logs I can send you and I'll try in about 12 hours.

Apart from that, if there aren't other people clamoring about this issue, I
fine using 117. Tbh, I only came over here after ce360 didn't support Forza
3 at all. Probably M$ store related.

Have a good day!
