### ISSUE TITLE
A new defaut app pop up appeared after the W11 22H2 update

### ISSUE THREAD

**Issue by Fenghuang19** [Ryochan7/DS4Windows#2630]
**Describe the bug**
Since the W11 22H2 update, a pop up appear every time after plug my ds4 controler if the xbox gamebar app is removed.
It told me "you need an new app for open ms-gamebar link", search an app on the MS store.

**To Reproduce**
Update your W11 to 22H2 
Remove the xbox gamebar app with the cmd Get-AppxPackage *Microsoft.XboxGameOverlay* | Remove-AppxPackage
then Get-AppxPackage *Microsoft.XboxGamingOverlay* | Remove-AppxPackag
Start DS4W
Plug any DS4 controler.

**Expected behavior**
Can you add in the next ds4w release to be able to grab the ms-gamebar link for select it on the pop up.

**Desktop (please complete the following information):**
Sony DS4 v.1
Windows 11 22H2 build 22621.525
DS4 windows 3.1.6

**Additional context**
Since the last update, 3 new gamebar process are started after plug an controler.
It's better to stay away from any new MS unstable process in principle even if the controler are working fine but this new pop up is too annoying.

**Comment by Ryochan7** [comment]
You broke Windows functionality. Should have just disabled the Xbox Gamepad in Windows settings. Not anything related to DS4Windows.

**Comment by lonewolf0708** [comment]
Simpler solution: open Xbox game bar settings, go to Controller bar and remove both checkmarks
![16701355558501129781600231252294](https://user-images.githubusercontent.com/51030924/205477872-870d9e77-1637-4235-b57b-90ccef4c146d.jpg)

**Comment by Masamune3210** [comment]
Simplest solution: Don't uninstall system apps

**Comment by silasporth** [comment]
https://wpguru.co.uk/2021/10/how-to-fix-the-ms-gaming-overlay-popup-message-in-windows-10/
