### ISSUE TITLE
Rumble not working in bluetooth

### ISSUE THREAD

**Issue by sonic-linux** [Ryochan7/DS4Windows#2632]
Rumble works in DS4 and X360 mode but only in USB but when connected through Bluetooth it doesn't work.

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2E)
 - OS: Windows 10 Pro Build 22H2
 - DS4Windows Version 3.1.6

**Hardware ID**
HID\VID_054C&PID_09CC&REV_0100&MI_03
HID\VID_054C&PID_09CC&MI_03
HID\VID_054C&UP:0001_U:0005
HID_DEVICE_SYSTEM_GAME
HID_DEVICE_UP:0001_U:0005
HID_DEVICE

Apps used are Dolphin emulator, Cuphead and FURI the game. I have tested without DS4W in bluetooth and rumble works.

**Comment by Yohoki** [comment]
Something isn't set up right. I can confirm that rumble works on BT.

Dolphin, iirc, only works via XBox emulation. I do have FURI and can test in a few minutes after I've finished cooking dinner.

**Comment by sonic-linux** [comment]
Everything is in stock setting. let see if I did set everything right.
*Downloaded net 6.0 runtime and installed it 
*Installed  ViGEm bus driver version 1.21.422
*Paired my ps4 controller and opened DS4W
