### ISSUE TITLE
ViGem Error swapping between XBox/DS4 under high CPU load

### ISSUE THREAD

**Issue by Yohoki** [Ryochan7/DS4Windows#2636]
**Describe the bug**
Pretty much title. When the PC is lagging, swapping from XBox to DS4 mode, or vice versa, throws a "ViGEm Error" in the logs and D4W tries to shut itself down. (not fully shutting down is probably a different issue)

**To Reproduce**
1. Open D4W and connect a controller as DS4
2. Start a CPU intensive application that changes the controller to XBox via Auto-profile
3. See logs freak out.

**Expected behavior**
Don't bug out when changing profile types.

**Screenshots and Logs**
<Details>
<Summary>Log File (9/5/22)</Summary>

```
09/05/2022 09:40:06: DS4Windows version 3.1.4
09/05/2022 09:40:06: DS4Windows Assembly Architecture: x64
09/05/2022 09:40:06: OS Version: Microsoft Windows NT 10.0.19044.0
09/05/2022 09:40:06: OS Product Name: Windows 10 Home
09/05/2022 09:40:06: OS Release ID: 2009
09/05/2022 09:40:06: System Architecture: x64
09/05/2022 09:40:24: Running as Admin
09/05/2022 09:40:24: HidHide control device found
09/05/2022 09:40:25: Starting...
09/05/2022 09:40:25: Using output KB+M handler: SendInput
09/05/2022 09:40:25: Connection to ViGEmBus 1.21.442.0 established
09/05/2022 09:40:25: Searching for controllers...
09/05/2022 09:40:25: Using Exclusive Mode
09/05/2022 09:40:27: Plugging in virtual DS4 Controller
09/05/2022 09:40:27: Associate DS4 Controller in slot #1 for input DS4 v.2 controller #1
09/05/2022 09:40:28: Controller 1 is using Profile "Mouse Control". Battery level is 100%
09/05/2022 09:40:49: Disassociate DS4 Controller from slot #1 for input DS4 v.2 controller #1
09/05/2022 09:40:49: Unplugging virtual DS4 Controller
09/05/2022 09:40:49: Plugging in virtual X360 Controller
09/05/2022 09:40:49: Associate X360 Controller in slot #1 for input DS4 v.2 controller #1
09/05/2022 09:43:20: Controller 1 is using Profile "Yuzu v2 (Controller)". Battery level is 100%
09/05/2022 09:46:47: Controller 1 is using Profile "Yuzu v2 (Mouse)". Battery level is 100%
09/05/2022 09:46:49: Controller 1 is using Profile "Yuzu v2 (Controller)". Battery level is 100%
09/05/2022 11:37:08: Disassociate X360 Controller from slot #1 for input DS4 v.2 controller #1
09/05/2022 11:37:09: Unplugging virtual X360 Controller
09/05/2022 11:37:13: Plugging in virtual DS4 Controller
09/05/2022 11:37:13: Associate DS4 Controller in slot #1 for input DS4 v.2 controller #1
09/05/2022 11:37:15: Controller 1's latency over 10ms (285.15 ms)
09/05/2022 11:37:15: Controller 1's latency now under 10ms
09/05/2022 11:37:17: ViGEm Device Plugin Failed. Likely an internal ViGEmBus problem. Closing connection. If the issue persists, please close DS4Windows and then reboot Windows.
09/05/2022 11:37:17: Stopping Virtual Output Controllers
09/05/2022 11:37:17: Closing connection to ViGEmBus
09/05/2022 11:37:24: Controller 1 was removed or lost connection
09/05/2022 11:37:24: Stopping DS4 Input Controllers
09/05/2022 11:37:24: Stopped DS4Windows
```

</Details>

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: Windows 10
 - DS4Windows Version: 3.1.6, probably 3.17, many previous versions. (I'll check 3.17 later tonight to be sure)

**Additional context**
Does not happen with no controllers connected.
Does not happen if controller type remains the same.
Newer ViGEm DLL does not fix issue.
Doesn't usually happen when switching controller types, only during heavy CPU loads. (This is the main reason why I'm not sure if it's a ViGEm error at cause, or D4W)
Sometimes it will throw the error on starting a game, sometimes it will throw it when exiting the game. Sometimes it just happens when Alt+Tab back to another application. Very Rarely, it just doesn't happen at all. But it's always during the swapping of controller types.

The only way to reconnect controllers is to force close, or the X button if settings are set up for it. But that's probably a separate issue. I don't think the Stop() method is set up right, and IIRC it results in Visual Studio throwing a "Not referencing an instance of the object" kind of error. The Stop() method doesn't fully finish stopping, and is never able to recover after the error.

**Comment by Yohoki** [comment]
@Ryochan7 @nefarius
Figured I'd make it an issue, now that I know when the issue happens and how I can reliably replicate it.

**Comment by nefarius** [comment]
As I've written in the discussion, these errors are non-recoverable, maybe the system at this point is so low on resources that it can't even spawn new devices reliably anymore? This case will not be solvable by anything we could do in software I'm afraid.
