### ISSUE TITLE
Controllers Shows "Paired" in Windows but disconnects from DS4Windows

### ISSUE THREAD

**Issue by Aymack** [Ryochan7/DS4Windows#264]
My controller will connect via USB and show up in DS4Windows, but when i connect via BT it connects, shows up in DS4Windows and disconnects after about 3 seconds. It will still remain "connected" and "paired" in my BT settings in Windows. Battery shows "0%+" while connected via USB (which I'm assuming is intentional). When it auto disconnects from DS4Windows, it says "Controller 1 was removed or lost connection. Charge the battery". Used the old DS4Windows last night for the first time and everything was good. I left it plugged in overnight to charge, and then this started happening. I downloaded your version assuming it would fix the issue but it's still happening. Idk what to do, I've tried everything I can think of

**Comment by Aymack** [comment]
Okay, so I uninstalled and reinstalled literally everything again. And I seem to have a working BT connection in DS4Windows now. But my battery life still shows 0%?

**Comment by Ryochan7** [comment]
I have only seen that type of behavior with battery level from reports of people attempting to use third party controllers. I only support the use of official Sony DS4 controllers as that is what I have on hand to test.
