### ISSUE TITLE
Cannot bind Decimal

### ISSUE THREAD

**Issue by Axce** [Ryochan7/DS4Windows#2640]
**Describe the bug**
When creating a custom profile, if I bind the Decimal character ("." the dot on the NumPad) to any button, then this button does nothing.

**Expected behavior**
Pressing the gamepad button should press the Decimal key (displaying "." in a text editor, for example).

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS5 (CFI-ZCT1W)
 - OS: Windows 10 Pro Build 21H2
 - DS4Windows Version 3.1.7

**Comment by Ryochan7** [comment]
Which event generator are you using? SendInput (default) or FakerInput? The key mapping is likely wrong in one of the two.

**Comment by Axce** [comment]
I was using FakerInput, and it now works as expected after uninstalling FakerInput and rebooting.

**Comment by Ryochan7** [comment]
Mapping has been fixed in commit 092ebcc18ad79521d50002fcc9646995ab526be0
