### ISSUE TITLE
Контроллер постоянно отключается

### ISSUE THREAD

**Issue by chebupell** [Ryochan7/DS4Windows#2641]
Использую я оригинальный ds4 по bluetooth к пк через программу ds4windows, при подключении геймпада через bluetooth пропадает вибрация, и каждые примерно минут 20 геймпад перестаёт реагировать, фиксится всё только переподключением, если использовать его без ds4windows но также без провода, то никаких проблем нет, ни с вибрацией, ни с работой, также проблем нет если его использовать по проводу и с ds4windows,  вибрация фиксится только если эмулировать xbox360
вот что происходит в log 
10/16/2022 08:44:54: DS4Windows version 3.1.6
10/16/2022 08:44:54: DS4Windows Assembly Architecture: x64
10/16/2022 08:44:54: OS Version: Microsoft Windows NT 10.0.19044.0
10/16/2022 08:44:54: OS Product Name: Windows 10 Pro
10/16/2022 08:44:54: OS Release ID: 2009
10/16/2022 08:44:54: System Architecture: x64
10/16/2022 08:44:54: Running as User
10/16/2022 08:44:56: Starting...
10/16/2022 08:44:56: Using output KB+M handler: SendInput
10/16/2022 08:44:56: Connection to ViGEmBus 1.16.112.0 established
10/16/2022 08:44:56: Searching for controllers...
10/16/2022 08:44:56: Using Shared Mode
10/16/2022 08:44:56: Found Controller: A0:AB:51:54:BA:1F (BT) (DS4 v.2)
10/16/2022 08:44:56: Plugging in virtual DS4 Controller
10/16/2022 08:44:56: Associate DS4 Controller in slot #1 for input DS4 v.2 controller #1
10/16/2022 08:44:56: Controller 1 is using Profile "Default". Battery level is 100%
10/16/2022 08:54:02: Disassociate DS4 Controller from slot #1 for input DS4 v.2 controller #1
10/16/2022 08:54:02: Unplugging virtual DS4 Controller
10/16/2022 08:54:02: Plugging in virtual X360 Controller
10/16/2022 08:54:02: Associate X360 Controller in slot #1 for input DS4 v.2 controller #1

**Comment by mika-n** [comment]
jep, devs don't understand Russian. Only English, Finnish and Japanese, so feel free to pick the easiest one :-)

**Comment by Yohoki** [comment]
I also can help in Spanish. :)

**Comment by chebupell** [comment]
> Привет. Извините, я не говорю по-русски, и я не думаю, что разработчики тоже. Надеюсь, я еще смогу помочь.
> 
> Попробуйте заменить [этот файл DLL](https://ci.appveyor.com/api/buildjobs/l9makps170jnd7o6/artifacts/bin%2Fnet6.0%2FNefarius.ViGEm.Client%2FNefarius.ViGEm.Client.dll) в папке DS4Windows. . Тот, что шел с 3.1.6, имел ошибку.
> 
> English: Привет. I'm sorry, I do not speak Russian, and I don't think that the developers do either. I hope I can still help.
> 
> Try replacing [this DLL file](https://ci.appveyor.com/api/buildjobs/l9makps170jnd7o6/artifacts/bin%2Fnet6.0%2FNefarius.ViGEm.Client%2FNefarius.ViGEm.Client.dll) in your DS4Windows folder. The one that came with 3.1.6 had an error.

Спасибо, но ds4windows уже обновился, и проблема с bt работой исправилась, но теперь в эмуляции ds4 вообще не работает вибрация, в эмуляции xbox360 всё отлично

**Comment by Yohoki** [comment]
Which update are you using? I think vibration is working again in 3.1.9 . Try going to the profile editor in DS4 mode, and try testing the rumble with the buttons. Also try enabling output data.
![image](https://user-images.githubusercontent.com/44595371/198484491-a5bd2bc8-e343-4e33-800d-aca3bfd2e546.png)

**Comment by chebupell** [comment]
Vibration appeared, but the problem with disconnecting was not solved.

**Comment by Yohoki** [comment]
Have you updated  the [ViGEmbus driver](https://github.com/ViGEm/ViGEmBus/releases/tag/v1.21.442.0)? It had a few fixes that may help.

Other than that, you'll have to be more specific. You didn't mention a disconnect issue before.

**Comment by chebupell** [comment]
I updated, by the problem about disconnecting, I meant what I wrote about at the very beginning in the appeal, disabling management

**Comment by chebupell** [comment]
> Have you updated the [ViGEmbus driver](https://github.com/ViGEm/ViGEmBus/releases/tag/v1.21.442.0)? It had a few fixes that may help.
> 
> Other than that, you'll have to be more specific. You didn't mention a disconnect issue before.

Any ideas?

**Comment by mika-n** [comment]
I have to say I'm a bit confused now what is still a problem and what has been resolved because this issue ticket seem to talk about several different problems. Please be more specific: explain in more details what do you try to do and what doesn't work there? logfiles? screenshot? record a video demonstrating the issue?

**Comment by chebupell** [comment]
> I have to say I'm a bit confused now what is still a problem and what has been resolved because this issue ticket seem to talk about several different problems. Please be more specific: explain in more details what do you try to do and what doesn't work there? logfiles? screenshot? record a video demonstrating the issue?

I have a problem in ds4windows, if I connect ds4, then every +- 20 minutes the control is turned off (the gamepad works and is displayed in ds4windows, but the control does not work), everything is fixed only if you close ds4windows, or disable ds4, this problem is only in bt connection, if you connect via usb, then no there will be no problems with this, I hope that I have clearly told you
