### ISSUE TITLE
DS4Windows hijacking hostfxr.dll in .net directory

### ISSUE THREAD

**Issue by InfurnoHD** [Ryochan7/DS4Windows#2644]
DS4Windows kept the file C:\Program Files\dotnet\host\fxr\6.0.10\hostfxr.dll alive which messed up the runtime when programming software through Rider with .net.

I don't frankly know how to reproduce the error, however the fix was to close down the program. Figured it might be nice to put it out there though as the expected behavior would be to read and close the file, not keep it open.

**Comment by mika-n** [comment]
i think it is .NET runtime libraries controlling the use of that assembly file, so nothing DS4Windows app can do about it. Other than trying to figure out which feature requires that assembly and removing the feature. Not going to happen anytime soon.
