### ISSUE TITLE
how to fix 

### ISSUE THREAD

**Issue by hengvisal99** [Ryochan7/DS4Windows#2645]
disconnected due to read failure: 0

[ds4.txt](https://github.com/Ryochan7/DS4Windows/files/9843927/ds4.txt)

**Comment by Heisenberg2980** [comment]
I am having the same issue now, as soon as I open any game the controller disconnects and I can see the error "disconnected due to read failure: 0" in the log. @hengvisal99 @Ryochan7 did you find out how to solve this issue?
