### ISSUE TITLE
High CPU usage while idle

### ISSUE THREAD

**Issue by pulsemod** [Ryochan7/DS4Windows#2649]
**Describe the bug**
After updating to version 3.1.8, there is high CPU usage while idling, regardless of whether a controller is currently connected or not. On my machine, it is using around 25–30% CPU.

**To Reproduce**
1. Open DS4Windows

**Expected behavior**
Low CPU usage. 3.1.7 idles around 0.5–1% CPU on my machine with a controller connected, less otherwise.

**Screenshots and Logs**
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/9856656/ds4windows_log.txt)

**Desktop (please complete the following information):**
 - Controller Make and Model: N/A
 - OS: Windows 10 Pro Build 19043
 - CPU: Intel Core i3-4170
 - DS4Windows Version 3.1.8

**Comment by Morrowind87** [comment]
Yes, I have the same fault

**Comment by jojofofo36** [comment]
same

**Comment by transam617** [comment]
Same issue, reverted to previous version fixes issue.

**Comment by Ryochan7** [comment]
I do not experience this issue on my machine.

**Comment by Ryochan7** [comment]
Looking at the log. Definitely update your ViGEmBus driver installation. That driver is from October 2018 and many updates have been released since then.

**Comment by apiks** [comment]
Can confirm that updating the ViGEmBus driver has fixed the issue on my end.

**Comment by jojofofo36** [comment]
fixed for me too

**Comment by Ryochan7** [comment]
Can confirm this issue occurs when using ViGEmBus 1.17.333.0. Will have to investigate this further.

**Comment by Ryochan7** [comment]
The CPU usage spikes right after connecting to ViGEmBus. Skipping the rest of the DS4Windows startup routine does not matter. High CPU usage occurs even when no controllers are connected so no virtual controllers would be made. The CPU load goes down right after performing a disconnect from ViGEmBus.

Also, tried the latest vanilla ViGEm.NET library and the same problems occur. Carrying over the old Nefarius.ViGEm.Client.dll files from DS4Windows 3.1.7 brings the CPU usage back to normal. Looks like the underlying problem is with the embedded ViGEmClient.dll library.

If a quick hotfix would be made then virtual DS4 output feedback support will be disabled yet again. That is the one feature that would not work with the older library.

**Comment by HollyCeuin** [comment]
I am also getting this behaviour

**Comment by nefarius** [comment]
Oops, I know why. Patience.

**Comment by nefarius** [comment]
1. Affected folks, [**update ViGEmBus**](https://github.com/ViGEm/ViGEmBus/releases) 😉 
2. I know what's causing it, preparing a fix, hold your horses

**Comment by nefarius** [comment]
@Ryochan7 latest native client master branch contains the fix, pre-built DLLs for testing [available here](https://buildbot.vigem.org/builds/ViGEmClient/master/1.21.222.0/bin/release/)

Cheers

**Comment by coinkillerl** [comment]
> 1. Affected folks, [**update ViGEmBus**](https://github.com/ViGEm/ViGEmBus/releases) 😉
> 2. I know what's causing it, preparing a fix, hold your horses

This also fixed the issue for me.

**Comment by Bocharick** [comment]
same

**Comment by johanwintgens** [comment]
Updating ViGEmBus fixed it for me too. It would be nice if DS4Windows did that automatically upon updating itself. In any case thank you guys so much for maintaining this fantastic piece of software! ♥

**Comment by kongomongo** [comment]
Updating ViGEmBus fixed it for me too

**Comment by pulsemod** [comment]
> before upgrading driver, i was also receiving crash errors upon windows reboot/shutdown . There were similar issues opened in the past (now closed)
> 
> ![f39ae1a20cebdbc4c3c842fce75a86caddda17d7ff4ed7b08832f1408bc329f9](https://user-images.githubusercontent.com/7840350/197879485-8f18d35a-0feb-4e53-bfab-eab0cec9ae0a.jpg)

Anecdotally, I also had a similar issue where the machine isn't behaving properly in general and won't shutdown properly (used to be commonplace). However, it was before upgrading to 3.1.8. It's probably an unrelated issue.
