### ISSUE TITLE
Support for PowerA Fusion Pro

### ISSUE THREAD

**Issue by LAN021** [Ryochan7/DS4Windows#2650]
Hello,
I'm creating this to see if it's possible to get support for the [PowerA Fusion Pro](https://www.powera.com/p/playstation/playstation-4/controllers/fusion-pro-wireless-controller-for-playstation-4-1513638-01/) controller.
It's an officially licensed PS4 controller with all the standard functions, which it even says on the site:
"Classic PS4 features: Capacitive Touch Pad, lightbar LED, built-in speaker + Share Button, PS & Options buttons."

It has three modes: PS4 Bluetooth, PS4 USB and PC USB.
PC USB mode is XInput only, so I suppose it won't work. Doesn't have touchpad anyway.
In PS4 USB mode, which I use, it is seen as an HID DInput device, but not a standard DS4.
Don't know if PS4 Bluetooth works on PC as I don't have bluetooth on my PC or an adapter.
In reWASD, it works as a regular DualShock 4, so there is at least some way to get it to work
as such. I only know because I had a trial version. Even the touchpad worked fully, although
it's only seen as one button in DInput mode.

Answering the questions from [the thread](https://github.com/Ryochan7/DS4Windows/issues/2553) about the Thrustmaster eSwap Pro:

**1. Is this a wired only controller?**
No, but I don't know if wireless works on PC.

**2. Of those, which functions does this controller have?**
**Lightbar
Rumble
Motion (gyroscope, accelerometers)**
It should be all of them, but I don't know if all of them work on PC.

**3. Does it have a headphone jack? Does Windows detect it when connected via cable?**
Yes and yes.

![powera_fusion_pro_hid2](https://user-images.githubusercontent.com/116631092/197737572-e4a3ef0b-6580-4a3b-98b6-2d57a91b98b6.jpg)
[DS4WindowsDebug_log.txt](https://github.com/Ryochan7/DS4Windows/files/9859519/DS4WindowsDebug_log.txt)

Thank you in advance for any help, good community.

**Comment by LAN021** [comment]
A bump for visibility. Can anyone help out with this? I'd love to use my controller with DS4Windows.

**Comment by ayeball** [comment]
Dont know if this gonna help you , but check so you have the latest firmware for that controller. 
https://www.powera.com/support/xbox-xs-one-product-support/firmware-updates-for-xbox-one-controllers/

Check so you have the latest DS4 Software installed.  Also check so you have right utils installed from DS4 app.

If you want to get it work with bluetooth this is a good bluetooth device . https://www.asus.com/networking-iot-servers/adapters/all-series/usb-bt500/

At the moment , you can test https://beta.inputmapper.com/  and see if this work for you . 

I have DS4 with latest firmware and ASUS BT500 Bluetooth . Connection as a "Dualsense" -> X360 . And everything works great. Also working great with USB A to USB C.  Windows 11 .
And Steam have their way to connect the controller. 


Dont think its use same firmware version and update as Dualsense 4 , but that maybee the support for "Power A Fusion " can answer to. 
https://controller.dl.playstation.net/controller/lang/en/fwupdater.html

**Comment by LAN021** [comment]
Well, I'm asking for this specific controller to be added as a known device to DS4Windows.
The firmware updates are for Xbox One/Series controllers, I don't think there's any for the PS4 Fusion Pro.
The other things you mentioned doesn't have to do with the controller working with DS4Windows; it works fine otherwise on PC.

**Comment by LAN021** [comment]
Asking again since Steam Input is now being replaced by the barely functional new UI.

Just tell me what I need to provide and I'll do it.

Here's HID images from windows, if they can give something.
![powera_fusion_pro_hid](https://user-images.githubusercontent.com/116631092/216277064-c9b87e04-52a8-4a92-b665-b43b268f67b1.jpg)

**Comment by cuxsoulhunter** [comment]
bump up for visibility. I also just got this controller and it is superb! On Amazon it is constantly listed as #1 alternative PS4 controller so I guess a lot people have it and would be happy to use it wirelessly with Windows.

**Comment by LAN021** [comment]
Thank you for the bump, but I wouldn't get too hopeful, this has mostly been ignored. The controller was only released in Europe and that may be part of the issue. It does work perfectly with reWASD, however, which also has DS4 emulation (and everything else). If you think reWASD is worth the money, that is. On Steam Input, it works fine in PS4 USB mode, but it's seen as a generic DInput device, not a standard DS4. You can still set the controller type to PS4 to get the right prompts in-game for the games that use Steam Input's helper function. If the game doesn't have an option for changing prompts, you'll have to rely on mods.

Don't know how it works wirelessly, however, since I don't have a bluetooth adapter. Have you tried it?

I agree that it's a superb controller, too. It's actually my all-time favorite now. The shape and feel are just terrific, I really like a larger controller myself so it suits me perfectly.

**Comment by cuxsoulhunter** [comment]
I only tried the controller wired with no tools but I need it wireless over Bluetooth because the cable is not long enough for my needs. How does it work with reWASD and do the gyro/touchpad work? I don't mind different prompt icons.

I also tried the extremeRate controller case with an original PS4 controller that does work but is not even close as nice as the fusion pro und feels mushy.

**Comment by LAN021** [comment]
Ok, can't speak on wireless since I don't use it, not even sure if it works wirelessly on PC. You can always get an USB extension cable, although I'm not sure about added latency (worked fine for me for another controller). Have you tried in PS4 BT mode with a BT adapter? (If you need one, that is.)

The touchpad and LED work in reWASD, but I can't get gyro to work. It might be that I don't have all the features, not sure (I only have 1). Could be disabled in wired PS4 mode. If you really want gyro compatibility, I'm sure you can write to the reWASD team and ask them to add it, they're quite helpful. I have the log for USBTreeView, which I sent to the Cronus Zen team in the hopes that they can add the controller to the Zen. It currently only works in PC Wired mode with both touchpad and PS button unusable. If you happen to use a Cronus Zen, maybe you can post in the thread (I only use it for mapping and as a controller adapter, not for any scripts). I'm attaching it here, too.

[powera_fusion_pro_ps4_wired_mode_ps4.txt](https://github.com/Ryochan7/DS4Windows/files/12064602/powera_fusion_pro_ps4_wired_mode_ps4.txt)

**Comment by LAN021** [comment]
I also have to ask, have you tried using other thumbsticks with the controller, if you have any? I'm interested in getting Scuf Instinct thumbsticks, but I'm not sure if they fit. The attachment base looks very similar, however, so it's possible.

**Comment by cuxsoulhunter** [comment]
I just wrote a message to DS4Windows and reWASD team but didn't hear anything yet. I need bluetooth because I am in two rooms so cable is useless. I tried the controller with a bluetooth dongle for PS4 which works perfectly. On Windows I can connect easily with the build in bluetooth but I can't use it in games and it doesn't get detected by DS4Windows even though it's listed in my bluetooth devices. 

What is Cronus Zen?

I haven't tried Scuf Instinct since I am more than satisfied with the ones from the Fusion Pro. What are the benefits for you?

**Comment by LAN021** [comment]
Ok, good that BT works on Windows at least.

Cronus Zen is an adapter that lets you use various controllers on different platforms. It also has various other features, such as mapping and game scripts. See [here](https://www.cronusmax.com/).

I want to try the Scuf sticks, or any other sticks, just because I prefer concave ones. The standard ones on the Fusion Pro have too sharp rounded edges for me, so I use thumb grips on them. It works fine, but I might look into replacing the sticks altogether.

**Comment by cuxsoulhunter** [comment]
The reply from the reWASD team:
"Thank you for contacting our support team.
We do not officially support this device. However, there is a chance that it will be detected as a Switch, DS4 or Xbox One / 360 controller, depending on the modes in which it can work.
Thank you for your suggestion."

How do you use the Cronus, is it for different consoles I assume?

**Comment by cuxsoulhunter** [comment]
Yeah sure I believe with USB mode it works but does it work with bluetooth? At least my fusion pro won't get detected by re WASD in bluetooth mode.

Ah sounds like a great thing the Zen. I don't really do console gaming so I wasn't aware of it.

**Comment by LAN021** [comment]
Ah, right, BT mode might need additional work by the reWASD team. Have you tried it yourself? reWASD offers a free trial.

**Comment by LAN021** [comment]
I see, hope it get can get added then. Is it the same with Steam?
