### ISSUE TITLE
Abnormally high CPU usage - v3.1.8

### ISSUE THREAD

**Issue by GhostOfJericho72** [Ryochan7/DS4Windows#2651]
Hi, Ryochan.

As always, thank you so much for your hard work!

Since the 3.1.8 update (possibly before), DS4Windows has abnormally high CPU usage.
It always sits between 10% and 12% in Task Manager.

[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/9862492/ds4windows_log.txt)
![Screenshot 2022-10-25 181022](https://user-images.githubusercontent.com/90412368/197839427-a5174935-ea37-4f41-8e74-01d38696707d.png)

 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: Windows 10 21H2
 - OS Build: 19044.2130
 - DS4Windows Version: 3.1.8

**Comment by Kanuan** [comment]
Please, always search the issue tracker and check the release discussions before creating a new issue.
#2649

**Comment by GhostOfJericho72** [comment]
> Please, always search the issue tracker and check the release discussions before creating a new issue. This is already being covered in #2649

Apologies.
