### ISSUE TITLE
bluetooth suggestions

### ISSUE THREAD

**Issue by shogunreaper** [Ryochan7/DS4Windows#266]
Can anyone suggest me a bluetooth adapter that has good range and works with ds4?

My official adapter broke and my old usb adapter is garbage, it has high latency anytime i try to use it 8 or so feet away. If i put it behind a bodypart or under a blanket it disconnects.

**Comment by jonaaa20** [comment]
I use one of these CSR adapters, I get 1,25 - 2ms max at a considerable distance, I don't have any problems with it

**Comment by shogunreaper** [comment]
CSR? You have a link to it?

**Comment by jonaaa20** [comment]
CSR 4.0 Class 2, you can easily find it on eBay or any other place, really easy to find.

**Comment by jonaaa20** [comment]
Same here, I can't use the driver of my CSR too, same error, "index and blah blah blah", so I'm using the generic driver from windows.

**Comment by InstallGentoo11** [comment]
No point in the small thingies, except maybe if they are maybe more expensive.
I am using a 45-50 dollar wifi card that also has bluetooth with it. Works great. Though this fork currently has some bluetooth problems it seems.

**Comment by jonaaa20** [comment]
I don't have Bluetooth problems for now.

**Comment by czukowski** [comment]
As @arkhillneo noted, computer case may disrupt Bluetooth signal (as can most other sizable objects in the way between the controller and receiver). It may help to plug Bluetooth dongle to a USB extension cord and put it some place closer to where you're going to use the controller. Note that USB cord can add latency too, especially if it's very long or of a bad quality.

**Comment by Ryochan7** [comment]
I use a Rosewill RNX-BT401. It uses a CSR chipset and it has worked pretty well for me. It looks like it is currently out of stock on Newegg though.

https://www.newegg.com/Product/Product.aspx?Item=N82E16833166126
