### ISSUE TITLE
Ds4windows disables my Dualshock 4 driver

### ISSUE THREAD

**Issue by ZoroDibuja** [Ryochan7/DS4Windows#2661]
Since I restored my PC due to some inconveniences that it had, Ds4windows began to have some failures when I used it again. Previously I could use Ds4Windows and the new Version of the Cemu 2.0 emulator had my Ds4windows set to start once I turned on the pc, and in the Cemu 2.0 settings I could choose to use the xbox 360 virtual controller or the Play station 4 controller However, now the Play Station 4 controller option does not appear available to me, and only the virtual controller appears, that is, the Xbox 360 controller, and I need the dualshock option to be available to use the sensor and the gyroscope in some games. I have had to use the controller without opening the ds4 windows so that the emulator can recognize the ps4 controller and does not disappear from the options, however, when opening Ds4windows to use in other games where it does not recognize the Dualshock 4, when closing the program completely disables the Dualshock 4 controller, not even in the control panel test does it register the movements made on the control. I would like to know if this has to do with the fact that the original controller of the remote disappears in the emulator and if it has any kind of solution, the truth is that I loved it when I did not have to do anything with the program since it started by itself and had access to both drivers. I tried to reinstall Ds4windows and all the drivers but it still doesn't work, also the program stopped having the driver in exclusive mode even though it is the only program that uses the device, I hope you can help me to have my Ds4windows as it was at the beginning.

**Comment by Masamune3210** [comment]
Please next time use proper grammer or at least try. Linebreaks are a wonderful thing.

If you need the DS4 to show up to programs, either close DS4Windows when you want to use the raw controller or unhide the controller in DS4Windows so both controllers show up

**Comment by Yohoki** [comment]
You have several options to get Cemu to work like you want it to.

- Auto-Profile: Turn Off DS4Windows
In your "AutoProfiles" tab, add Cemu to the list."Turn off DS4Windows Temporarily". This will turn off DS4Windows while Cemu is running.

- UDP Server
In the "Settings" tab, enable the UDP Server. In Cemu, under the controller options, you should see a + icon to select an API as the source for buttons and motion. I believe Cemu calls it DSU. Mess with the options in there to get it working via the server.

- Close DS4Windows
It's pretty easy to just close the DS4Windows if you don't need it open.
