### ISSUE TITLE
Joycon Left is not working properly after the update [Combined]

### ISSUE THREAD

**Issue by RyuSushie** [Ryochan7/DS4Windows#2663]
**Describe the bug**
Im using joycons but after the update my left joycon isn't working properly. 

heres the reading on my controller:
![image](https://user-images.githubusercontent.com/113040739/198673444-31c39a60-7ddf-41cb-b3f8-508745c99889.png)

**Comment by Ryochan7** [comment]
Maybe it was a fluke? I do not experience this issue on my end. Xbox 360 emulation and UDP transmission work as expected with joined JoyCons.

**Comment by RyuSushie** [comment]
Yes, I think It has some minor error communicating with my joycons. I've already tried this feature before and now when I tried to use it again this happened. ( or get a new pro controller :kek )

**Comment by Ryochan7** [comment]
The handshake technique has gotten a little better over time. Seems to work for me but I will not guarantee that it will work every time. Closing.
