### ISSUE TITLE
Steam overriding DS4Windows and not showing virtual controller

### ISSUE THREAD

**Issue by Kazserah** [Ryochan7/DS4Windows#2668]
I'm using DS4Windows for my DualSense and everything worked great until they added official DualSense support, now Steam makes my controller show up as PS5 Controller instead of an Xbox controller and seems to completely ignore DS4Windows

**Comment by Masamune3210** [comment]
Steam intentionally behaves differently when it detects DS4Windows as being open on the computer. Either close steam when using DS4Windows, close DS4Windows when using Steam, or use a custom exe name for DS4Windows so Steam cant detect it and automatically change its behavior

**Comment by Kazserah** [comment]
> Steam intentionally behaves differently when it detects DS4Windows as being open on the computer. Either close steam when using DS4Windows, close DS4Windows when using Steam, or use a custom exe name for DS4Windows so Steam cant detect it and automatically change its behavior

Thanks, but I changed the name of the .exe and nothing changed. Still not detecting it.

**Comment by Ryusennin** [comment]
Several solutions:

1. Make sure Steam Input is globally disabled.
2. Make a copy of ds4windows.exe as ds4win.exe and launch the new exe, not the old one (common mistake).
3. Use HidHide to hide your physical DS5 controller and leave the virtual XBO one visible.

**Comment by FatalitySonicX** [comment]
It does seem like the hiding is temporary since the "New Big Picture" beta. Despite DS4Windows being open on the custom EXE, Steam Input globally disabled and HidHide set up, next Steam restart, the new Big Picture detects the PS5 controller natively again and makes double inputs in the menu.
