### ISSUE TITLE
UI: Application can become locked in "rebind button" mode

### ISSUE THREAD

**Issue by LimEJET** [Ryochan7/DS4Windows#267]
![input-popup.gif](https://user-images.githubusercontent.com/4407285/39271590-c99e4fc8-48d9-11e8-8449-091614138333.gif)

### Summary
During certain conditions, DS4Windows interprets every input from a connected controller as a rebind command, regardless of where in the application the user is. Can only be fixed by restarting DS4Windows.

### Software configuration
DS4Windows release 1.4.118 x64.  
Windows 10 Pro 1709, build 16299.371.  

### Steps to reproduce
1. Connect a DS4 controller.
2. Open DS4Windows and go to the Controllers tab.
3. Press "Edit".
4. Switch from the Profiles tab to the Controllers tab.
5. Press "Edit".
6. Press "Cancel".

Now, the application thinks the Profile>Controls tab is open all the time, and there's no way to close it without restarting the program.

**Comment by Ryochan7** [comment]
I am going to count this issue as invalid. There should be no reason to switch out main tabs while editing a profile in the first place.

The technical reason that the behavior is happening is because an instance of the Options form is still in memory after performing those steps.

**Comment by LimEJET** [comment]
That's fair. I spent about an hour confused because of this since I left in the middle of the process and forgot where I was, but I admit that's a very rare occurrence.

At least now it's documented.
