### ISSUE TITLE
Windows doesn't recognize dualshock 4 as a gaming device after updating DS4Windows

### ISSUE THREAD

**Issue by Noxalasz** [Ryochan7/DS4Windows#2670]
Hello and good morning/afternoon/evening to whoever reads this, my issue may seem simple but I must assure you that I've tried every common fix under the sun, even the tangentially related ones, more than one time to no avail before deciding to open a thread here. I've also read other listed issues and wasn't able to find one which is similar to my case.

Before anything, here are the requested informations as per mika-n's troubleshooting tips post:
- Microsoft Windows 10 Home v10.0.19045 X64
- Previous DS4Windows version was some of Jays2Kings's releases (unsure of which) / Current is Ryochan7's v3.1.9
- ViGemBus driver v1.21.442.0
- I have Microsoft .NET v6.0.10 X64 runtime library installed 
- My joystick's a genuine Sony DS4 v2 (CUH-ZCT2U)
- I see no point in attaching a log file since the program doesn't even recognize my joystick, but I'll attach it either way
[ds4windows_log_20221031.0.txt](https://github.com/Ryochan7/DS4Windows/files/9904711/ds4windows_log_20221031.0.txt)

Here's what happend - Last friday (28/10/2022) I wanted to play a game called Stonefly and started my DS4Windows (Older version before Ryochan's takeover) since it didn't support my dualshock 4, the program worked but presented an annoying bug where the in-game control icons flickered between the keyboard's and the xbox's. After that, it came to mind that Steam has a built in dualshock 4 driver so I added the non steam game to my library and started it, the controller was recognized and functioned properly, everything A-OK. But I wanted to update my DS4Windows before progressing with my game session to see how the newer versions were doing (big mistake), and thus my controller stopped being recognized by both DS4Windows and Steam.

It must be noted that the controller is still recognized by Windows when pairing through bluetooth, not so much using a USB connection (the light blinks in yellow once), although once I plug the cable it's possible to see the device's drivers being installed anew in Device Manager (if they were unninstaled before). Checked joy.cpl and it doesn't list the dualshock 4 as a game controller, even if it's connected through either USB cable or bluetooth. Checked HidHide and it recognizes the dualshock 4 as a "HID-compliant game controller" but it'll hide this device if I check the "Gaming devices only" box. Lastly, I'm fairly certain that this isn't a hardware issue since the joystick was perfectly functional before and is still giving signs of life.

Moving on, I've tried many fixes found online (most more than once), which I'll proceed to list now for the sake of clarity. Here it goes:
1 - Removing/Reintroducing the Wireless Controller device through USB and Bluetooth
2 - Updating/Installing/Unninstaling as well as Enabling/Disabling the corresponding Human Interface Drivers (including HID-compliant game controller drivers)
3 - Unninstaling ScpToolkit and ScpVBus
4 - Updating my system's VC++ and .NET runtime libraries
5 - Deleting all previous files and profile subfolders in the %APPDATA%\DS4Windows\ folder
6 - Factory resetting my Dualshock 4
7 - Rolling back to a previous Windows update
8 - Running Tweaking.com's Windows Repair Free v4.13.1
9 - Offering my firstborn to a techdemon (he wasn't able to figure it out either)

I don't know if it's possible but my bet is that the updating process has somehow messed with my OS' internal files in a way that's not necessarily seen as a system corruption, but still renders my joystick unusable. 

As a last resort, formatting the OS seems to be an option but I think it might be wasted time since I'm not tech savvy enough to understand the nature of the issue, there's a discussion on a Steam forum from someone who ran into a similar problem and one of the posters tried to fix it with a clean windows installation, bearing no results. The OP wasn't able to fix it either and gave up on the whole thing, but came back and said it "fixed itself" at a later time, in an uknown way. It's in Portuguese but it might still be understandable using Google's translator:
https://steamcommunity.com/discussions/forum/27/1639788130289896598/?l=english

Anyway, troubleshooting in forums/discussions is understandably hard, and I can't really afford another joystick right now, so I tried to provide as much information as clearly as possible upfront for you guys in hopes of finding a solution. Have a great day and until then.

**Comment by TomieAi** [comment]
I have weird issue that it only detects the controller if I start the DS4Windows.. but when DS4Windows is off it wont detect xD
