### ISSUE TITLE
The controller is constantly shutting down

### ISSUE THREAD

**Issue by chebupell** [Ryochan7/DS4Windows#2679]
I have a problem in ds4windows, if I connect ds4, then every +- 20 minutes the control is turned off (the gamepad works and is displayed in ds4windows, but the control does not work), everything is fixed only if you disable ds4, this problem is only in bt connection, if you connect via usb, then no there will be no problems with this.
here's what happens in log:
11/06/2022 16:13:13: DS4Windows version 3.1.9
11/06/2022 16:13:13: DS4Windows Assembly Architecture: x64
11/06/2022 16:13:13: OS Version: Microsoft Windows NT 10.0.19045.0
11/06/2022 16:13:13: OS Product Name: Windows 10 Pro
11/06/2022 16:13:13: OS Release ID: 2009
11/06/2022 16:13:13: System Architecture: x64
11/06/2022 16:13:13: Running as Admin
11/06/2022 16:13:14: Starting...
11/06/2022 16:13:14: Using output KB+M handler: FakerInput 0.1.0.0
11/06/2022 16:13:14: Connection to ViGEmBus 1.21.442.0 established
11/06/2022 16:13:14: Searching for controllers...
11/06/2022 16:13:14: Using Shared Mode
11/06/2022 16:13:15: Found Controller: A0:AB:51:54:BA:1F (BT) (DS4 v.2).
11/06/2022 16:13:15: Plugging in virtual DS4 Controller in output slot #1
11/06/2022 16:13:15: Associated input controller #1 (DS4 v.2) to virtual DS4 Controller in output slot #1
11/06/2022 16:13:15: Controller 1 is using Profile "Default". Battery level is 50%

**Comment by THE-EXP** [comment]
you might want to try 2 things:
 1. in profile editor go to "other" section and uncheck "idle disconnect" if it's checked
 2. on the same page try checking "disable virtual controller" if unchecked

**Comment by chebupell** [comment]
> you might want to try 2 things:
> 
> 1. in profile editor go to "other" section and uncheck "idle disconnect" if it's checked
> 2. on the same page try checking "disable virtual controller" if unchecked

I did it all and checked it out

**Comment by THE-EXP** [comment]
ah, i had assumed you already did update to newes version, hope the newer verison helps you out, good luck

**Comment by Yohoki** [comment]
I don't see anything in the logs where it says your controller has turned off or stopped responding at all. Everything looks right. I would assume it might be hardware related (BT adapter). What adapter are you using? Can you try using another device on the Adapter, like a different controller or headphones. When the disconnect happens, can you go to your controller settings or a gamepad tester and see if it can still detect the controller?

**Comment by chebupell** [comment]
> ah, i had assumed you already did update to newest version, hope the newer verison helps you out, good luck

That's it, I finished checking, there was some kind of error in the ds4 emulation, I turned off emulation and everything worked fine for more than 2 hours, but when I turned it on again, the problem appeared

**Comment by chebupell** [comment]
> I don't see anything in the logs where it says your controller has turned off or stopped responding at all. Everything looks right. I would assume it might be hardware related (BT adapter). What adapter are you using? Can you try using another device on the Adapter, like a different controller or headphones. When the disconnect happens, can you go to your controller settings or a gamepad tester and see if it can still detect the controller?

but this problem is not in the gamepad and not in the adapter (there are no problems without ds4widows), and it feels like it depends on the number of clicks, the gamepad itself continues to work properly, but emulation stops and if something was pressed at that moment, then it sticks

**Comment by chebupell** [comment]
> ah, i had assumed you already did update to newest version, hope the newer verison helps you out, good luck

I do not know how to check this, because if I use it in a game that recognizes a gamepad without ds4windows, it may just stop working at some point and I will not notice, there is only one option, it is to hold down the button and leave the gamepad for a while

**Comment by chebupell** [comment]
There is another question, I installed a new version of vigembus, but passthru on the touchpad still does not work

**Comment by chebupell** [comment]
> ah, i had assumed you already did update to newest version, hope the newer verison helps you out, good luck

There is more information, ds4windows stops responding, and if you turn on test heavy, nothing will happen

**Comment by chebupell** [comment]
in log I noticed this recently:
Gamepad data write connection is lost. Disconnecting the gamepad. LastErrorCode=995

**Comment by chebupell** [comment]
> I don't see anything in the logs where it says your controller has turned off or stopped responding at all. Everything looks right. I would assume it might be hardware related (BT adapter). What adapter are you using? Can you try using another device on the Adapter, like a different controller or headphones. When the disconnect happens, can you go to your controller settings or a gamepad tester and see if it can still detect the controller?

?
