### ISSUE TITLE
DS4Windows Not Seeing My DS4

### ISSUE THREAD

**Issue by FingersIsMe** [Ryochan7/DS4Windows#268]
Whenever I booted up DS4Windows, installed the virtuall bus, and made sure to follow every instruction given to me on how to get DS4Windows working. DS4Windows just doesn't work. It doesn't even see my Dual Shock 4 controller. It doesn't show up in device manager at all or in the "Control Panel" in the options menu of the DS4 UI. If any one could help me out with this, that'd be fantastic. 

also, i'd like to mention that my controller does work with the SCP Toolkit provided by nefarius.

**Comment by Ceril-Skye** [comment]
Also having this issue, however my controller worked perfectly fine with SCP Toolkit
