### ISSUE TITLE
Shift Modifier using PS Button + Triangle on DS4 causes a disconnect

### ISSUE THREAD

**Issue by DaveACG** [Ryochan7/DS4Windows#2680]
Whenever a shift modifier is used involving the PS button as the modifier and the active button being the Triangle on a Dualshock 4 controller, DS4 Windows disconnects. 

Basically it seems to be acting as if the default Special Action PS Button + Options is being sent. If the Special Action disconnect is disabled for the profile, this still occurs.

Shift modifiers for other buttons do not reproduce this, or using another shift modifier (such as finger on touchpad) with the triangle button.

**Comment by andreycout** [comment]
Does this happen if Steam is closed? PS + Triangle is the default steam button chord shortcut for turning off the controller.

**Comment by DaveACG** [comment]
Ah crap, apologies. New system install this morning and forgot to disable Steam controller support, doh.
