### ISSUE TITLE
Controller Vibration after 3.1.4 so bad and weak

### ISSUE THREAD

**Issue by pyromancer5** [Ryochan7/DS4Windows#2684]
first ty for the awesome software wich i always try to Leave and  use just steam input but i cant always getting back to ds4windows.
now am using ps5 controllers wich work great with 3.1.4 BUT i want to update to the last version but the Vibration is so bad for real what happen? i want to update to 3.1.10 while i keep the same Vibration future in 3.1.4 i always try new updates since the start of 3.1.5 hoping this bad new Vibration go away but it wont its still the same even in 3.1.10 so i had to report now and try to get an answer since i want to update..ty thats all

**Comment by Kanuan** [comment]
Same issue as #2603 . Please, close this issue and continue the discussion there
