### ISSUE TITLE
DS4 Windows seems to prevent Windows task bar from being used. 

### ISSUE THREAD

**Issue by JRyan54** [Ryochan7/DS4Windows#2686]
**Describe the bug**

When I launch DS4 Windows and try to use the task search bar or right click on any icons on the task bar there is no response. However the second I end DS4 from running I have full functionality of the task bar again.

**Comment by JRyan54** [comment]
Weird but easy fix that I hope stays. I didn't think about it at the time but I just unplugged and plugged back in my PS5 controller and I have full functionality of my task bar with DS4 open again.

**Comment by Yohoki** [comment]
Try running DS4W as admin, or use FakerInput.

I usually see this kind of behavior when D4W doesn't have the right permissions. Either of those solutions should fix it.

**Comment by Ryochan7** [comment]
Maybe you have a virtual mouse button active when you do not mean to. That would be a reason that task bar interaction cannot happen while running the mapper.
