### ISSUE TITLE
[Feature Request] Send key combinations

### ISSUE THREAD

**Issue by IngwiePhoenix** [Ryochan7/DS4Windows#2697]
Hello!

I am using a Razer Raiju Ultimate without the XInput drivers, so it behaves and is recognized as a regular PS4 controller.

I wanted to assign `ctrl+alt+i` to the touchpad press to trigger the screen magnification's color inversion feature so that i dont have to reach for my keyboard while playing a game.

Problem is, I can only seem to select exactly one key... So I would love to request this as a feature! ^^ 

Thank you and kind regards,
Ingwie

**Comment by Ryochan7** [comment]
It probably won't happen in DS4Windows. Trying to eventually make a successor mapper a reality but I keep stumbling over my own ideas. I have a working prototype of a different mapper system but it only works with the Steam Controller currently; there was an earlier revision that worked with the Switch Pro but that code base is extremely out of date now and had no GUI. Multiple action output already works in that mapper but having Action Set and Action Layer support is something that has been very useful. I have already played through several games with it.

A DS4 version is fairly close to the prototype stage but need to decide how the backend mapper class will handle some Touchpad reading quirks (equivalent to the TouchUnchanged routine in DS4Windows). Trying to get controller abstraction established so the same project can handle multiple controller types. I will probably push the current code to GitHub soon although it is not ready for general usage; mainly just want to have an online backup of the code.

Here is a video example of the mapper in use. It is a fairly simple profile mainly demonstrating Gyro Mouse controls. Seems better than examples I have seen showing Steam Input usage.

Metal: Hellsinger Played with Steam Controller (Gyro):
https://www.youtube.com/watch?v=1-Vf0SYaV2k

Experimental mapper for Steam Controller:
https://github.com/Ryochan7/SteamControllerTest

**Comment by IngwiePhoenix** [comment]
Oh... thats unfortunate. Thank you for your response though! Guess i'll keep my keyboard around then ^^'

**Comment by Ryochan7** [comment]
Got the abomination source uploaded. Only works with the DS4 v.2. Still got a couple of enumerator decisions to make before expanding device detection for other devices.

https://github.com/Ryochan7/DS4MapperTest

**Comment by Ryochan7** [comment]
Flawed but here is a compiled build. Only tested with DS4 v.2 USB so far.

https://github.com/Ryochan7/DS4MapperTest/releases/tag/v0.0.1
