### ISSUE TITLE
My Ds4windows disables the use of my second DS4

### ISSUE THREAD

**Issue by ZoroDibuja** [Ryochan7/DS4Windows#2698]
Hello community, I would like to ask about something that has been happening with DS4Windows lately.

**Bug Description**
I recently bought a PS4 controller to play some cooperative games with my partner, however after opening the DS4windows controller, the program reads both controllers, but a second later it stops reading the second one and the controller goes completely crazy.
the led light stays on but the DS4 appears disconnected from the PC, I try to turn it off but it doesn't work, it's as if it canceled all the options of the controller. This is the second time this has happened to me, there was an occasion where I connected it without problems, however it happened again, and just as in the first time I have to let the remote turn off by itself and leave it still for a while because the pc stops to recognize it for several days, until it turns on and works normally.
 It should be noted that when I use the controller in games where the use of DS4Windows is not required, the controller works normally, so it makes me think that perhaps it is due to the DS4Windows driver, I hope you can help me with this issue, and not have to be at the expectation that ds4windows does not disable the use of the controller for several days and not being able to play

**How do I make the connection?**
So far, I can only confirm that the error occurs when the controller is connected via bluetooth, I haven't had the chance to connect it via cable yet, so the controller is new.
The child steps:

**1.** I connect both devices via Bluetooth first, my own controller, and then the new controller (the one with the Bug)
**2.** I open DS4windows (Sometimes I do it just to know how much battery the devices have, since the game in which I use them does not need them)
**3.** Ds4 windows detects the devices normally, but a second later it disconnects the second one and disables it as explained above.

**As I normally expect it to work**
As I already explained, there was a time when it worked normally, the first time I used it, this error occurred and I took the remote to the technical service thinking that it was a problem with the remote, since it didn't even work when charging, while the remote was there, it turned on normally and when I brought it back the connection worked without problem, today, which was the third time I connected it, the problem from the beginning occurred again and here I am reporting normally I hope that the controller detects my remote and works, not that it disables it use.

**Screenshots and Logs**
This is the image of the controller as it turned out, the light was green when ds4windows detected the controller 2 after disconnecting it remained green and when trying to turn it off it changed to purple
![WhatsApp Image 2022-11-21 at 23 05 14](https://user-images.githubusercontent.com/116844553/203219157-f92b6cda-2963-4f5d-81a5-2b6521826969.jpeg)

This is the image of what happens when I connect the controller after the error occurs, it is not detected by ds4windows at all
![WhatsApp Image 2022-11-21 at 23 04 54](https://user-images.githubusercontent.com/116844553/203219399-984a25a1-720d-4197-8371-2a5c0ab0d72f.jpeg)

Here is a screenshot of how windows detects the DS4 after connecting it by cable to the pc. Is where it says "Dispositivo USB desconocido (error solicitud de descriptor de dispositivo"
![Captura de pantalla (74)](https://user-images.githubusercontent.com/116844553/203219533-e8232734-7fdd-4f60-a17e-5b45969a2da2.png)

And here a few images of my Ds4windows and its configuration
![Captura de pantalla (75)](https://user-images.githubusercontent.com/116844553/203219854-f6589081-195e-4499-b373-6a92b7611a69.png)
![Captura de pantalla (76)](https://user-images.githubusercontent.com/116844553/203219858-30f0fda4-86cf-4da1-ab10-1bc36ef90408.png)

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: Windows 10 Home Single Language
 - DS4Windows Version [e.g. 3.1.3]

**Additional context**
I would like to please have advice regarding the problem, or fully know if it is a DS4 error

**Comment by Masamune3210** [comment]
Controller is misbehaving or cable/bluetooth is misbehaving, USB Device Descriptor Request Failed means the system tried to ask the controller for its information so it could correctly identify it and the controller either responded with incorrect information, corrupted information, or didn't respond at all

**Comment by ZoroDibuja** [comment]
It happened again, I attach here an image of what the Ds4windows registered when connecting the second controller via bluetooth, before connecting it by bluetooth I tried it by cable and it worked correctly, I want to know if this error can be solved because apparently it is from Ds4Windows, since when trying it with my other remote (connecting it by bluetooth after the new one) the same thing happens
![Captura de pantalla (77)](https://user-images.githubusercontent.com/116844553/203643186-4af98e2c-7a02-4b73-8c42-39c9731e8555.png)

**Comment by Trihy** [comment]
Both work when connecting individually?

If that is correct, get a better BT adapter.
