### ISSUE TITLE
 DS4Windows doesnt see a connected gamepad via bluetooth

### ISSUE THREAD

**Issue by GeraltV47** [Ryochan7/DS4Windows#2699]
DS4Windows doesnt see a connected gamepad, tried many ways of resolving this on google but didnt succeeded

**Comment by GeraltV47** [comment]
OK problem solved all i had to do was to erase my gamepad from bluetooth devices, restart pc, run settings from start menu -> update and security -> troubleshooting -> bluetooth -> run troubleshooting and after it find error click close, press windows key + r, type services.msc find the bluetooth support service, disable and enable it then i connected my gamepad through bluetooth again and finally ds4windows find the controller

**Comment by GeraltV47** [comment]
if it does not help replugging in the bt dongle may help

**Comment by lonewolf0708** [comment]
Could try toggling Bluetooth off and on again in Bluetooth settings.
