### ISSUE TITLE
Passthru mode in Lightbar, Touchpad and Gyro tab doesn't work

### ISSUE THREAD

**Issue by kraftaksvk** [Ryochan7/DS4Windows#2709]
Passthru mode in Lightbar, Touchpad and Gyro tab doesn't work. It will say that it needs newer ViGEmBus even if I downloaded and installed the newest version.

1. Open DS4Windows
2. Open a profile
3. Click on tab Lightbar, Touchpad or Gyro
4. Select Passthru mode
5. this error pops up "Only works with ViGEmBus 1.17.333.0 and newer"

It should do just what it describes (let the input pass thru to the game)

![image](https://user-images.githubusercontent.com/119131011/204104488-20bc16b0-5a0a-4180-b040-969ead05d4b9.png)

 - Controller Make and Model: Sony DualSense (CFI-ZCT1W)
 - OS: Windows 11 & Windows 10
 - DS4Windows Version : 3.1.7

**Comment by Masamune3210** [comment]
Thats not talking about passing input in, that's for passing output out, as in lightbar data and vibration

**Comment by kraftaksvk** [comment]
yes i meant that

Dňa so, 26. nov 2022, 20:43 Masamune3210 ***@***.***>
napísal(a):

**Comment by kraftaksvk** [comment]
okay, thanks

Dňa po, 5. dec 2022, 22:08 Yohoki ***@***.***> napísal(a):
