### ISSUE TITLE
Mapping gyro to R-stick for MAME lightgun

### ISSUE THREAD

**Issue by midget35** [Ryochan7/DS4Windows#2712]
Hi guys. Delighted to see this project is seeing new releases :)

I have been trying to set MAME lightguns to use DS4 gamepads for a long time, using gyro for reticle movement. I can set gyro to use Mouse OK, for a lightgun proxy, but I have been trying to set each DS4 to be a separate lighgun for multiplayer MAME lightgun input by 'hijacking' the right stick.

What I've tried:
1) Set Gyro > Output Mode = Mouse Joystick
2) Set Output Stick = Right Stick

In addition, I've also tried setting Axis Config > RS Output Mode = None...

Unfortunately, reticle movement is very jerky and it always seems to 'snap back' to the screen center when I stop moving the DS4 gamepad around.

I am wondering: have any of you tried this setup with more success? As an aside - I think it would also be nice to see the Controller Readings > Right Stick graphic update in real-time when 'Mouse Joystick' is set and the DS4 is moved around.  

Thanks for any help :)

**Comment by Ryochan7** [comment]
There is no way to map output to work like that. Gyro Mouse Joystick is mainly meant to be used for camera control for games that do not support mixed input; it was initially introduced around the release of Halo: Master Chief Collection. Output is supposed to go to zero when the controller is no longer being moved. Not really sure trying to use Gyro output for a simulated lightgun would be a very good idea.

I have heard of people attempting to use a PlayStation Move controller as a lightgun. That would be a much better option if someone has access to that hardware. Another option that people try is to use the Wiimote as a lightgun.

**Comment by midget35** [comment]
> There is no way to map output to work like that. Gyro Mouse Joystick is mainly meant to be used for camera control for games that do not support mixed input; it was initially introduced around the release of Halo: Master Chief Collection. Output is supposed to go to zero when the controller is no longer being moved. Not really sure trying to use Gyro output for a simulated lightgun would be a very good idea.
> 
> I have heard of people attempting to use a PlayStation Move controller as a lightgun. That would be a much better option if someone has access to that hardware. Another option that people try is to use the Wiimote as a lightgun.

Thanks, buddy. That use case explains a lot :)

I've had a lot of joy modifying the DS4Device.cs' performDs4Input() method.

There's just a bit of drift that maybe could be fixed with smoothing, but I haven't quite got it down.

In said method - I have the below code. Note that I added a GetLastMouseMovementXY() function to Mouse.cs that in turn calls the MouseCursor.cs class. So long as a mouse object is attached to each DS4 profile, I get good (just not quite good enough) results. The SPJ.cs reference below is just a static helper class taht keeps numbers in bye range. So the code is like: 

```
if ( use lighgun hack )

int newX = SPJ.Clamp(
    lastMousePositionXY.X + mouse.GetLastMouseMovementXY().X
);
cState.RX = Convert.ToByte(newX);
lastMousePositionXY.X = newX;

int newY = SPJ.Clamp(
   lastMousePositionXY.Y + mouse.GetLastMouseMovementXY().Y
);
cState.RY = Convert.ToByte(newY);
lastMousePositionXY.Y = newY;
```

Thanks
