### ISSUE TITLE
[Bug] Keeps monitors awake

### ISSUE THREAD

**Issue by averon420** [Ryochan7/DS4Windows#2717]
**Describe the bug**
Monitors are unable to sleep, while DS4Windows is running.

**To Reproduce**
1. Set sleep timer to 1min
2. Wait 1min
3. nothing happens

**Expected behavior**
Monitors should able to sleep, without the need for closing DS4Windows 

**Desktop (please complete the following information):**
 - OS: Windows 10 10.0.19044
 - DS4Windows Version 3.1.11

**Additional context**
I have this issue for a while, hoped an update will fix it

**Comment by SurlyVagrant** [comment]
Currently on 3.2.7 and I've had this happening for a month or two. I think I just discovered it only happens with the controller plugged in. Unplug the controller and the monitors will sleep. Would still be nice to not have to remember to do that, though.

**Comment by Ryochan7** [comment]
I swear this has to be from people using poor quality third party controllers and not setting dead zones for the sticks. My PC can sleep but never resume under any circumstance but sleep works fine for me while DS4Windows is running. The one major factor that would affect whether the sleep routine kicks in is if the PC detects some form of input which could happen from faulty analog sticks. In that case, it is likely the physical controller itself that is causing the problem and not DS4Windows.

**Comment by SurlyVagrant** [comment]
I have an official DS4, using the default dead zones, which I just checked and I couldn't get either stick to rest outside the dead zone.

I used to unplug the controller when it was done recharging, but I got lazy and stopped doing it until I figured out that was why my monitors wouldn't sleep. So the timeline might be skewed a bit.

**Comment by SurlyVagrant** [comment]
Don't know if anything changed in 3.2.8, but I just noticed my monitors were asleep with the controller plugged in. Thought that had been the case a few other times recently, but I wasn't paying attention until today.
