### ISSUE TITLE
System.NullReferenceException:“Object reference not set to an instance of an object.”  messageReceived is null。

### ISSUE THREAD

**Issue by lidawei97688** [Ryochan7/DS4Windows#2729]
https://github.com/Ryochan7/DS4Windows/blob/3e1bb7a35ead7402bf5488c586d2959d777280f6/DS4Windows/DS4Control/ControlService.cs#L245
![Snipaste_2022-12-08_19-51-29](https://user-images.githubusercontent.com/58324866/206440427-0760c409-d77a-4fc9-b1ce-d33018255aa3.png)

**Comment by Ryochan7** [comment]
Not sure why that is happening there. Should be easy enough to work around.

**Comment by Ryochan7** [comment]
Changed in commit a17fa9e0278d18843412d6bf855d0423629b7f7e
