### ISSUE TITLE
Simulating a square gate

### ISSUE THREAD

**Issue by aidenn** [Ryochan7/DS4Windows#273]
Hi!

Currently, I see that I can increase overall sensitivity to 130%, which lets me hit the corners but then cardinals are a bit too sensitive. There is an external tool for this (http://kalma.kapsi.fi/rldurazno/) but it's xinput-only. Would it be a great hassle to integrate this kind of functionality into DS4Windows?

**Comment by Ryochan7** [comment]
This was discussed in another issue. Work was attempted to add similar functionality but I ended up scraping the idea. The assemblies that would have been used for that routine slowed down DS4Windows even when not being used. I don't see myself going back to revisit this issue and try to implement a couple of helper routines myself. Knowing my luck, the prototype code would not perform well enough and it would get scrapped.

**Comment by Ryochan7** [comment]
Duplicate of issue #341

**Comment by Ryochan7** [comment]
It looks like this feature will be included in the next release of DS4Windows.

https://github.com/Ryochan7/DS4Windows/commit/1dbf9abb026726655e3d58649e02fa9158a0fc21
