### ISSUE TITLE
 Color panel settings stopped working on copycat

### ISSUE THREAD

**Issue by ExLimeX** [Ryochan7/DS4Windows#2734]
**Describe the bug**
 Color panel settings stopped working on copycat

**Expected behavior**
The color bar settings no longer work on new versions. On version 3.0.18 everything works. Copycat is enabled in the settings. After reinstalling Windows, the old version requires downloading .Net, although net 6 and 7 are installed. New versions are launched

**Desktop (please complete the following information):**
 - Controller Make and Model: Fake Sony DS4 v.2 (CUH-ZCT2E)
 - OS: Windows 11 22H2
 - DS4Windows Version 3.1.11

**Comment by Ryochan7** [comment]
I don't support the use of copycat controllers. I would assume that any breakage that happened was probably due to a change made to accommodate a user who posted a fix for getting a different copycat controller working; that was probably a couple of versions ago.

**Comment by Ryochan7** [comment]
Does not really matter now but I think I would seriously just stop accepting pull requests for hardware I do not own. There is no resolution if something breaks as people will not stick around to help maintain support.
