### ISSUE TITLE
Audio for Dualsense via bluetooth

### ISSUE THREAD

**Issue by whoisalireza** [Ryochan7/DS4Windows#2738]
Hey, this is no bug but more of a request or smth.
I really dont know any other way of doing this, so I am sorry if I did this wrong.

So basically I and many more probably would just love if we could connect our Dualsense to the PC via bluetooth and still be able to talk to our friends via discord for example using the Dualsense as the audio device.

I would connect my headset via the headphone jack to the Dualsense and choose the Dualsense Wireless Controller in the Windows settings to be the audio in- and output.

Why? Because this way I could just for example connect my PC via HDMI cable to my TV, connect my Dualsense to the PC and connect my headset to it and just lay on my bed or couch and play my games on the TV as if I would play a PS5.

However the major upgrade is that I can fully use discord at the same time which is not possible on PS5 right now unfortunetly.

Thanks in advance!

**Comment by Ryochan7** [comment]
Discord is full of ped0bears and FBI agents. Don't use it.

Also, AFAIK, that is not possible at the hardware level. The audio interface is only exposed when connected via USB.
