### ISSUE TITLE
[Enhancement] Support Joy-Cons connected via USB-C using the Joy-Con Charging Grip (`HAC-012`)

### ISSUE THREAD

**Issue by akemin-dayo** [Ryochan7/DS4Windows#2739]
This is a _really_ low-priority enhancement, but it would be nice to see DS4Windows eventually support this feature.

Steam and Chromium (as of [this commit](https://github.com/chromium/chromium/commit/b37eb129399993dd308eddf033509a03cc540e62)) are the only two applications I'm aware of that are able to properly initialise and read input from the Joy-Con Charging Grip.

Any other application that attempts to read the Joy-Con Charging Grip's HID reports (such as XOutput, SDL2, Parsec, etc.) will only receive broken data. (※ Please exercise caution when testing this — it is extremely easy for the controller to _very_ rapidly navigate UIs and press things you do not intend to!)

**Comment by Ryochan7** [comment]
Been trying this out with no success. On the rare occasion, I can get one JoyCon to complete the handshake and send input reports. It would be nice to use the Charging Grip like this but I am about ready to give up.

Also ended up trying the Steam Input implementation. The new beta Deck UI update is trash on my system. Extremely unstable. Also, it does not seem like gyro is implemented when the JoyCons are docking in the grip. The profile editor becomes unusable when I try to map anything to the gyro and I have to start a fresh profile to do anything else.

**Comment by Ryochan7** [comment]
Haven't entirely given up yet. Something is wrong with the handshake procedure when the JoyCons are docked in the Charging Grip. I have gotten both JoyCons to complete the handshake and send input reports by accident a few times. Never any consistency as to when it will decide to succeed though. Mapping works fine when the JoyCons are actually working. To be fair, it does not seem like Steam Input connects every time either.

**Comment by Ryochan7** [comment]
Looks like I finally got the handshake to work consistently. Mapping works in DS4Windows and gyro and other extra JoyCon features work like they do in Bluetooth mode.

**Comment by Ryochan7** [comment]
Test branch with the changes. Too bad the poll rate is still limited to 16 ms when connected to the Charging Grip. 

https://github.com/Ryochan7/DS4Windows/tree/joycon_grip

**Comment by akemin-dayo** [comment]
Just built and tested the `joycon_grip` branch — I can confirm that Joy-Cons connected via USB work pretty much about as well as they do over Bluetooth!

The only potentially user-expectation-subverting behaviour I can really comment on is the fact that connecting/removing Joy-Cons while the USB device is still connected ends up in a completely non-working controller until the USB device is re-connected. But this is… probably a limitation of the charging grip itself. (※ I haven't dumped and looked at the USB traffic yet with my OpenVizsla — this is all pure speculation.)

Aside from that, the only other issues I've noticed are _really_ minor ones that occur with Bluetooth Joy-Cons as well (which I should file as proper issues sometime later):
* **[UI]** Entries for USB/BT Joy-Cons in the Device Options preference pane (`ControlServiceDeviceOptions`) will show the DS4 "Copycat" preference.
* **[Player LED]** When in joined mode, each USB/BT Joy-Con side has mismatched player LEDs.
* **[Probably not related to DS4w]** Certain applications (I've specifically _only_ been able to reproduce this with RetroArch) are unable to make virtual DS4s vibrate if the underlying controller is not a DS5/DS4.
	* This actually reproduces with ViGEmBus instances spawned by other applications (such as Parsec) as well, so I think this is most likely either an issue with ViGEmBus upstream, or with RetroArch's implementation.

---

> Too bad the poll rate is still limited to 16 ms when connected to the Charging Grip.

Huh, that _is_ kinda odd. Kinda wonder why — as far as I can tell, the actual Switch/horizonOS will never accept input from the Joy-Con Charging Grip over USB either (it only does this for Pro Controllers).

The most it'll do is pair with the Joy-Cons in the grip, and then attempt to connect to them via Bluetooth. (※ You can test this by disabling Bluetooth via Airplane Mode.)

It's possible that accepting input via the Joy-Con Charging Grip was never meant to be a feature (or was scrapped during development for some reason), hence the strange behaviour.

**Comment by Ryochan7** [comment]
> EDIT: Actually, I just noticed another issue. When the controller is in the above state, trying to stop DS4Windows will cause ControlService to get stuck somewhere here (I'll look into debugging this properly sometime later):

Got this fixed already. The routine would hang in the StopUpdate method waiting for the JoyCon input thread to exit. That input thread would be stuck waiting for the next report from the HID device. Had to add an explicit IO cancel to make sure Windows stops trying to read from the dead device so the input thread can exit.

Might test it a bit more but I am thinking that JoyCon hotplugging is not going to be an option when using the grip. You would have to disconnect the USB cable from the grip to have DS4Windows disconnect the devices. Haven't looked if the grip sends any form of report when a device is disconnected. This is a small edge case so I am not too worried about it.

UPDATE: Looks like the grip does send a report when a JoyCon is disconnected or reconnected

**Comment by Ryochan7** [comment]
Don't think I will take the code much further so I merged it into the master branch. I doubt I will use the functionality myself. I mostly use the JoyCon controllers split with JoyCon R being used for Gyro. I would rather use the Switch Pro for having a single device for emulating an Xbox 360 controller or mapping KB+M controls to sticks.

**Comment by akemin-dayo** [comment]
Yeah, that's fair — I pretty much only use my DS5 and DS4v2 anyway (as I greatly prefer the ergonomics on those compared to… pretty much anything else ;P)

I just figured it would be nice if DS4Windows also supported Joy-Cons over USB, hence why I created this issue.

In any case, I've tested the latest commit (SHA1 6f0413b883a543b67329f7d40e0821e29367ccf6) and all seems well (pretty much the same as BT Joy-Cons)!
