### ISSUE TITLE
Lightbar and rumble

### ISSUE THREAD

**Issue by WolfgangSchrag** [Ryochan7/DS4Windows#2748]
Lightbar issues not saving preset colors and not on at all

rumble issues very faint rumble and no light
connect xbox one controller as well to PC then the rumble hits the ps4 controller and not the xbox but is actually good feedback and the light flashes to the rumble at the same time

**Comment by Ryochan7** [comment]
This just sounds made up. Nothing in ViGEmBus would cause this to happen.
