### ISSUE TITLE
Lightbar not Changing

### ISSUE THREAD

**Issue by who-is-thiss** [Ryochan7/DS4Windows#2751]
**Describe the bug**
Whenever I try to change the lightbar in any way, it doesn't change at all. I tried in the "Controllers" menu, I clicked on the colored bar, set a custom color, and nothing happens.

**To Reproduce**
1. In the controllers menu, click the colored bar next to the "Edit" button.
2. Click "Use custom color"
3. Select any color
4. Lightbar doesn't update

**Expected behavior**
The lightbar should change color.

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2E)
 - OS: Windows 10
 - DS4Windows Version 3.1.12

**Additional context**

**Comment by restush** [comment]
Same here. I did upgrade firmware dualsense and latest ds4windows. Seems like the software broken and it has been a year but no fix.

**Comment by Masamune3210** [comment]
Software works fine, my lightbar changes perfectly fine. Whatever the issue is, its either sporadic and not widespread, or its an issue with your particular setup

**Comment by Ryochan7** [comment]
> Same here. I did upgrade firmware dualsense and latest ds4windows. Seems like the software broken and it has been a year but no fix.

No fix to a potential problem that I am not able to reproduce on my end. **Use Custom Color** color works fine for me with version 3.2.21. I have no obligation to do anything for you. You do not pay my bills.
