### ISSUE TITLE
DualSense (DS5) controller disconnects when computer loads anything

### ISSUE THREAD

**Issue by Wahtthehellnoway** [Ryochan7/DS4Windows#2757]
**Describe the bug**
(Not entirely sure if this goes under bug reports but I am not any wiser)
Everytime my computer loads something, say like a page on a browser or launching and loading a game, my DS5 controller disconnects and stays disconnected until my computer has stopped loading whatever it was loading, most of the time it just kind of seems like it's in a loop of reconnecting. (and maybe sometimes stays disconnected even after that, kind of hard to tell if it is loading something or not when I'm doing nothing).

**To Reproduce**
1. (not sure if anyone but me and my horrible luck can reproduce the problem)
   Connect the controller
2. Start up DS4Windows

- Controller is connected and functions normally

4. Start a game or load a page on a browser
5. Controller disconnects immediately

**Expected behavior**
Uh expected it to like not disconnect, although didn't really surprise me that _of course **I**_ would have problems??

**Screenshots and Logs**
Just going to send logs, also I tried disabling the virtual controller for a bit to see if that would help (it did not) so that might show up in the logs
[DS5 logs 1.txt](https://github.com/Ryochan7/DS4Windows/files/10346703/DS5.logs.1.txt)

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DualSense (CFI-ZCT1W)
 - OS: Windows 10 Pro
 - DS4Windows Version 3.1.12

**Additional context**
Oh and my old DS4 controller stopped working too after I tried to use it again since the DS5 clearly didn't want to work.
And they both use different cables so unless the one I used for the DS4 broke while it was disconnected from my computer (roughly 2 hours, I think) and laying on the ground, resulting in there being a possibility both cables were broken or something, but that would be unlikely as well it's 2 cables and I doubt they other one broke while doing nothing, so I don't think it's that the cables broke or that my USB-A to USB-C converter can't transfer enough data or inputs or whatever fast enough, also the cable was bought like 30 minutes before I tried using it.

**Comment by KorvinEC** [comment]
Have you managed to find a solution?
