### ISSUE TITLE
Can get admin command prompt/explorer window from this program

### ISSUE THREAD

**Issue by Dwedit** [Ryochan7/DS4Windows#2762]
**Describe the bug**
This is more of an issue with Windows itself, but any time a program runs as Admin, and is capable of displaying the standard Windows file dialogs, you can launch a command prompt or Explorer window as administrator from that program.

The easiest way to resolve this is to use a child process that isn't running as Admin just to open the file dialog box.  But this is tedious and tricky to do, need to write all that interprocess communication glue code.

**To Reproduce**
1. Have the program run as a scheduled task
2. Open a Windows file dialog, one way to do it is "Add Programs -> Browse for other programs" from the "Auto Profiles" tab
3. From within that Open dialog, Shift+Right Click on a directory
4. Click "Open PowerShell Window Here"
5. You now have an admin powershell window without any UAC prompt.

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2 (19045.2354)
 - DS4Windows Version 3.1.12

**Comment by Masamune3210** [comment]
This is a "already across the airtight hatchway" problem. If you can launch a program with admin creds and successfully pass UAC, then it doesn't matter if you can then use some fiddling to get a admin explorer window or command prompt. You could just as easily launch them directly as you did the program used to get them
