### ISSUE TITLE
Configuration Location Bug causes Controller not to be detected and Profile Editing to Crash

### ISSUE THREAD

**Issue by v0idp** [Ryochan7/DS4Windows#2773]
**Describe the bug**
If you select program folder on first startup as your config location, DS4Windows will not detect your PS5 Controller and it will crash upon opening any Profile Editing. Tried in both Sharing and Exclusive mode, reinstalled the software and selected appdata as location and that fixed both issues.

**To Reproduce**
1. Install DS4Windows including all the drivers
2. Start DS4Windows for the first time (important!)
3. It will ask you to select where to save configs/settings (program folder or appdata)
4. Select "Program Folder"
5. Controller should not be able to be detected by DS4Windows
6. Editing any Profile will lead to a crash

**Expected behavior**
PS5 (Dualsense) Controller should be detected in Sharing/Exclusive Mode and Profile Editing should work

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony PS5 Controller (DualSense)
 - OS: Windows 11 Pro Version 22H2
 - DS4Windows Version: 3.2.3

**Comment by Ryochan7** [comment]
I think this has been resolved in a couple other issues. Going to close this old one.
