### ISSUE TITLE
Shift modifier macro crashes when applying 

### ISSUE THREAD

**Issue by Breakmyday** [Ryochan7/DS4Windows#2783]
**Describe the bug**
When setting a shift modifier to a recorded macro DS4 will report that ERROR|Thread Crashed with message An item with the same key has already been added
I have had a shift modifier macro recorded on a profile since the summer and am now unable to make changes to it unless I fully remove these macros. This only happens when they are set as a shift modifier. 

**To Reproduce**
1. Create profile
2. Click a controller button and select the Shift Modifier radio button
3. Click any key other than its default to set it (If you record the macro right away it does not save)
4. Click the same button and go to Shift Modifier again
5. Click Record Macro and record any input
6. Save and apply the profile
7.Crash

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DualSense (white) CFI-ZCT1W
 - OS: Windows 11 Pro 10.0.22621 Build 22621
 - DS4Windows Version 3.2.6

**Additional context**
Profile was created sometime this summer and only recently attempted to modify a button unrelated to the macro. 
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/10416483/ds4windows_log.txt)

**Comment by sonny-dev** [comment]
Yup have had this issue for a few patches now :( 
Trying to set up right face buttons (X,O,^,[ ]) with shift modifier of R1, and as soon as I save, it crashes the app

**Comment by Psykill972** [comment]
Hello, i have the same issue when trying to save a profil with a new macro.
I will try downgrade my ds4windows version so :(

**Comment by sonny-dev** [comment]
> Hello, i have the same issue when trying to save a profil with a new macro. I will try downgrade my ds4windows version so :(
> 
> Edit : working fine with version 3.1.8

Thank you for finding a working version - can confirm this is working for me now, downgraded to 3.1.8

**Comment by Ryochan7** [comment]
Might have to look into the issue further but the main crash should be fixed with commit 2ecc21a9554d009ea432510538943b17bceb8c8d

**Comment by Ryochan7** [comment]
Commit 140fbdb6b1c8cb682a69a046a438a749f69dd058 should fix the problem documented in step 3. Shift Trigger choice was not being carried over so the binding would revert to default.
