### ISSUE TITLE
Setup L2 & R2 either as axis or button inputs

### ISSUE THREAD

**Issue by PirateSeal** [Ryochan7/DS4Windows#2785]
**Describe the bug**
Sorry if duplicate.

Not a bug but i'd like to be able to force my triggers to be a button input instead of axis one because I cannot force it in-game (DCS World). By extension, I would like to use the second stage feature to map multiple button inputs depending on the type of pulling (soft or full).

TL:DR : Add drop down option to the triggers allowing emulation of a new button input from the controller (without having to bind a keyboard key to it). Second stage behavior would be the same, just button input depending on the pull type.

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS5
 - OS: Windows 11 Pro 22H2 22621.1105
 - DS4Windows Version 3.2.6

**Comment by Ryochan7** [comment]
I am limited to the way the emulated output gamepad is exposed (Xbox 360 or DS4). There is no option to create an arbitrary DirectInput device to only expose items as buttons or something similar.
