### ISSUE TITLE
DualSense not picked up on Win 11 (Build 22621.1105)

### ISSUE THREAD

**Issue by kftX** [Ryochan7/DS4Windows#2787]
**Describe the bug**
The controller isn't detected by either of my two machines running the latest version of Windows 11, I've tried both with cable and bluetooth and same result. Windows does pick up the controller and all its inputs and so does Gamepad Tester.

(HidGuardian is **not** installed. These are both fresh installs of Windows.)

This controller was successfully used in the past to play in this same hardware, just as a note.

**To Reproduce**
1. Open DS4Windows
2. Turn On the DualSense (I would have tested with other PS controllers but I don't have any)
3. Just... nothing happens.

**Expected behavior**
DS4Windows should pick up the controller and list it.

**Screenshots and Logs**
![Screenshot_20230116_201250](https://user-images.githubusercontent.com/47950410/212758893-fdbff81e-8281-4280-9b22-290b581c4d22.png)
(Pressing Button 1 (Square) to show it is working in Windows.)

[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/10429166/ds4windows_log.txt)

**Desktop (please complete the following information):**
 - Sony PlayStation DualSense CFI-ZCT1W
 - OS: Windows 11 (Build 22621.1105)
 - DS4Windows 3.2.6 (but I went down as far as 3.2.0 and same thing)

**Comment by samueljosino** [comment]
I`m having the same problem!

**Comment by samueljosino** [comment]
I actually think i solved it, go to de Settings tab, on the right click on Device Options, and on then mark DualSense Controller Support. After doing this, on the main Controllers tab my dualsense showed up

**Comment by Acursedtrey** [comment]
> I actually think i solved it, go to de Settings tab, on the right click on Device Options, and on then mark DualSense Controller Support. After doing this, on the main Controllers tab my dualsense showed up

Worked for me. Really simple, surprised i didnt notice this myself
