### ISSUE TITLE
Could you please allow latest version of .NET

### ISSUE THREAD

**Issue by elnoelsi** [Ryochan7/DS4Windows#2791]
title says it

**Comment by Masamune3210** [comment]
Thats not how libraries work. Programs run on whatever they are built with, they are built with whatever version they need. You don't just run a later one just because it's newer

**Comment by Ryochan7** [comment]
Still run into issues with the migration to .NET 6 mostly thanks to being forced to use the H.NotifyIcon.Wpf NuGet package. Maybe some tests can be done at some point but there is probably no real need to consider migrating to .NET 7 right now. The performance difference was significant between .NET 5 and .NET 6.

**Comment by elnoelsi** [comment]
I was actually refering to latest version of .NET 6 because for s ome reason the runtime i had installed (6.0.13) wasnt being detected. Would only launch with the one currently linked (6.0.10). Anyway it is obviously working just fine with latest, probably at the time downloaded incorrect runtime by mistake.
