### ISSUE TITLE
Is it possible to map double tap of a button to do some action?

### ISSUE THREAD

**Issue by jmriego** [Ryochan7/DS4Windows#2792]
**Describe the bug**
Is it possible to map double taps of a button? In "Special Actions" I can see it's possible to map long presses to do certain actions, but I'm looking for mapping to a double tap.

**To Reproduce**
I'm looking at the interface and I think this is a case of requesting a new feature more than any bug report.

**Expected behavior**
For example, if I double tap the Select button, I'd like DS4Windows to press the Esc key.

**Screenshots and Logs**
N/A

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4
 - OS: Windows 10 Pro
 - DS4Windows Version [3.2.4]

**Additional context**
N/A

**Comment by Ryochan7** [comment]
That is only semi-possible when using a Special Action. There is no way to perform that type of action at the profile level. There are no plans to add more advanced mapping functionality to DS4Windows. I have another mapper project that is being worked on that would be better for that purpose. It already has a double tap (Double Press) mapping option but I do not think that mapping option is exposed in the GUI as of yet; I have not had a use for it myself so it is still not exposed.
