### ISSUE TITLE
light can't custom via bluetooth but can custom via usb

### ISSUE THREAD

**Issue by ghost** [Ryochan7/DS4Windows#2794]

**Comment by tadestak** [comment]
.

**Comment by SB67-nWo** [comment]
Does the lightbar stay a light blue and doesnt do anything to let you know if the controller needs charging while using it wirelessly?

**Comment by Ryochan7** [comment]
Guess Ted (The Ghost Hunter) Sheckler left

![ted_sheckler_ghosts](https://user-images.githubusercontent.com/581968/222321381-c87e5598-4470-449e-9bbd-3a0e9d98932a.jpg)

Ted the Ghosthunter:
https://www.youtube.com/watch?v=q9P5G_ktmw4
