### ISSUE TITLE
Move input delay information to controllers tab

### ISSUE THREAD

**Issue by JarnoVgr** [Ryochan7/DS4Windows#28]
Would it be possible for the input delay information to be per controller, and have it moved to the controllers tab? It doesn't make much sense to me to appear in the profiles tab.

**Comment by Ryochan7** [comment]
As long as sending those extra events doesn't impact the performance of the GUI too much then it should be possible.

**Comment by Ryochan7** [comment]
Haven't looked at this issue in a while. However, the functionality actually already existed. You have to mouse hover over the controller ID and the current input delay will be displayed for a controller. That is only active for controllers connected via Bluetooth. Having that information displayed no matter which connection type is being used would probably be a good idea.
