### ISSUE TITLE
Crash on startup if executable is named "DS4Windows.exe" (case sensitive) - but only through NTFS junctions

### ISSUE THREAD

**Issue by Rohaq** [Ryochan7/DS4Windows#2805]
**Describe the bug**
DS4Windows crashes on startup if the filename of the executable is default `DS4Windows.exe`, and is accessed through an NTFS junction.

Installing DS4Windows through [scoop](https://scoop.sh/) results in the filename `DS4Windows.exe` - this filename is directly from the latest release zip file (v3.2.7 at time of writing). Running the app through default means (shortcuts point to `C:\Users\%username%\scoop\apps\ds4windows\current\DS4Windows.exe`) results in DS4Windows crashing.

Renaming the executable to `ds4windows.exe`, `ds4Windows.exe`, or even `dS4Windows.exe` results in the crash not occurring, and DS4Windows starts and can be gracefully shut down as normal.

Running the app directly from `C:\Users\%username%\scoop\apps\ds4windows\3.2.7\DS4Windows.exe` runs in DS4Windows starting successfully, and can be shut down as normal.

**To Reproduce**
1. Ensure all [prerequisites](https://docs.ds4windows.app/guides/install-setup/#prerequisites) are installed.
2. Install DS4Windows through [Scoop](https://scoop.sh/). This installs the latest release zip, where the filename for 
3. Attempt to run DS4Windows either through the Start menu shortcut, or from the NTFS junction created by scoop to point to a specific version (usually `C:\Users\%username%\scoop\apps\ds4windows\current`). DS4Windows briefly starts up and appears in the Windows taskbar, but crashes soon after. Logfile output: [ds4windows_log_20230128.4.txt](https://github.com/Ryochan7/DS4Windows/files/10527740/ds4windows_log_20230128.4.txt)
4. Rename the `DS4Windows.exe` executable to `ds4windows.exe`, `ds4Windows.exe`, or `dS4Windows.exe` and run it.
5. DS4Windows starts successfully, and can be closed gracefully. Logfile output [ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/10527757/ds4windows_log.txt)
6. Rename the executable file back to the default `DS4Windows.exe`.
7. Run the executable directly from the version directory referenced by the NTFS function for current (`C:\Users\%username%\scoop\apps\ds4windows\3.2.7\DS4Windows.exe` in my case).
8. DS4Windows starts successfully, and can be closed gracefully. Same logfile output as Step 5.

**Expected behavior**
Ideally, the casing/name of the executable, or whether it's been run through an NTFS junction should not be causing a crash on start - and the logs should output something clearer for troubleshooting purposes.

**Screenshots and Logs**
Logfile from running with default executable name `DS4Windows.exe`:
[ds4windows_log_20230128.4.txt](https://github.com/Ryochan7/DS4Windows/files/10527740/ds4windows_log_20230128.4.txt)

Successful logfile from running with renamed executable name `ds4windows.exe`:
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/10527757/ds4windows_log.txt)

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS5 (CFI-ZCT1W)
 - OS: Microsoft Windows 10 Pro v10.0.19045 Build 19045
 - DS4Windows Version: 3.2.7

**Additional context**
The logs suggest that this is probably an issue in the H.NotifyIcon library trying to create a system tray icon, so it looks like it's a bug in there that's probably worth logging with them too. But it would be nice to see a workaround in the meantime!

**Comment by Ryochan7** [comment]
Is it a case where Explorer is not running? Either way, I guess I will add a small check to make sure that a tray icon was created each time before attempting to show a notification.

**Comment by Rohaq** [comment]
explorer.exe is definitely running as my shell, if that's what you mean?
