### ISSUE TITLE
Low resolution tray icon on HIDPI screens

### ISSUE THREAD

**Issue by likeaross** [Ryochan7/DS4Windows#2811]
Would it be possible to up the resolution of the tray icon(s)?
![Screenshot_20230131_092744](https://user-images.githubusercontent.com/483960/215959316-48864259-d6c3-461d-a69a-ce174e319da9.png)

**Comment by Ryochan7** [comment]
Not sure if the most recent DS4Windows version would have affected this problem. I added a 512x512 image in the ico files that are used so hopefully Windows would use those versions of the icon on larger displays. I want to think it looks slightly better on my end but that could just be wishful thinking.
