### ISSUE TITLE
The setting of the gyroscope cannot be saved.

### ISSUE THREAD

**Issue by Aimochier** [Ryochan7/DS4Windows#2813]
Questions about the gyroscope: If two trigger keys, such as R2 and L2, in the "Eval cond" button in the lower part of the interface, only "and" can be save,"or" can be choose,but it cannot save,This problem lasted several versions.

Sony daulsense

 - DS4Windows Version [3.1.11-3.2.7]

**Comment by Aimochier** [comment]
Output mode:mouse joystick

**Comment by Ryochan7** [comment]
Just looked and the setter method is wrong. It converts the read value but does not store it. Quick fix. Thank you for pointing out the problem.
