### ISSUE TITLE
Binding Dpad buttons to Left Analog Stick

### ISSUE THREAD

**Issue by androiduser3** [Ryochan7/DS4Windows#282]
So I have been trying to bind Dpad buttons to Left Analog Stick but as soon as I finished binding and I open Snes9x the keys are always pressed. I tried increasing deadzone to 0.09 and I thought it fixes it, but only partial. If I move the left joystick to the left or right, the up or down button is also pressed resulting to diagonal output. Is there any way to fix this? I don't want to use InputMapper because that program has trouble getting Exclusive Mode without HIDGuardian and does not support gyro for Cemu. Yes I use Udp version of DS4Windows and I prefer to use only this program for my DS4. 

EDIT: Just to add, I am trying to double bind the Dpad buttons so I can use both analog and Dpad on the Snes9x.

Thanks

**Comment by Ryochan7** [comment]
Analog stick to dpad mapping should work as expected on version 1.4.119.

**Comment by androiduser3** [comment]
Thanks for this! Just to let you know I had to compile the udp version myself. Maybe release udp versions too next time? I mean I'm sure other people out there use Cemu too and want udp version.

Anyway thanks again for this it is working perfectly.

**Comment by Ryochan7** [comment]
I posted links to updated udp builds in the dedicated issue but the links are a bit buried in the discussion. It is cumbersome to have the extra builds but I have not gotten the udp feature integrated in a way that does not hinder the main functionality of this application. It would be better if the server were just an option that someone could toggle if desired but even having the routine available but disabled causes unwanted latency. The .NET Runtime acts weird sometimes.

http://ryochan7.xyz/ds4windows/test/DS4Windows_1.4.119_UdpServer_x64.zip
http://ryochan7.xyz/ds4windows/test/DS4Windows_1.4.119_ViGEm_UdpServer_x64.zip

**Comment by androiduser3** [comment]
Hmm that is weird. I never had any latency issues using udp versions. Played hours of games with udp version. If that is the case, maybe just put the links in the release section? I don't know if you can even do that as I am not a developer.
