### ISSUE TITLE
An Option to Support "Inverse Application Cloak" on HidHide

### ISSUE THREAD

**Issue by LimitedEdiition** [Ryochan7/DS4Windows#2821]
DS4windows is working great except when I have to use HidHide for specific games like Rocket League. I have HidHide set up the way I want it where it masks the Dualsense in favor of the emulated (Dualsense) Xbox controller, but I like using the Inverse Application Cloak setting for HidHide where it hides it only for the applications listed in HidHide. This causes a problem with DS4windows because DS4Win will automatically add itself to the application list for HidHide whenever it is launched (presumably because it anticipates the user not selecting the Inverse Option), so I have to remove it from the list in HidHide (otherwise the controller would be hidden in DS4windows because it is hidden in HidHide, Stop DS4windows, and then start it again for it to behave the way I want it.

I am asking to consider adding an option where it won't automatically add itself to HidHide, so it won't interfere with the Inverse Application Cloak feature. Thank you.

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony Dualsense
 - OS: Win 11 2H22
 - DS4Windows Version 3.2.8
 - HidHide 1.2.98.0

**Comment by Ryochan7** [comment]
I'll have to look over that one. It will not happen for the next release for sure.

**Comment by Ryochan7** [comment]
Long time coming. Been way too busy. The feature is now in the code but I have still not gotten around to bundling a new DS4Windows release with the feature included.

https://github.com/Ryochan7/DS4Windows/issues/3037
