### ISSUE TITLE
[Bug] Steam keeps overriding lightbar over DS4 windows, dispite disabled steam input is on.

### ISSUE THREAD

**Issue by darkedone02** [Ryochan7/DS4Windows#2823]
**Describe the bug**
This bug is mostly on the lightbar, My PS4 controller lightbar is green on full, empty on red, and will pulse at 20% when it is low. However when I was playing hogwarts legacy, with no controller support turned on on steam's end, as well as I went to properties menu to disabled steam input. When I am playing, my lightbar quickly went from green to red, I alt-tab out of the game, the lightbar went back to green.

I am assuming you missed something on the latest update that caused this issue, as I had not had this issue in the previous version of this program. 

**To Reproduce**
Turn On DS4windows, turn on controllers, set up light bars from green on full, red on Empty, pulse at 20%
Turn on [Disabled steam input] on properties under Hogwarts Legacy
Launch Hogwarts Legacy on steam
watch if any button inputs suddenly turn your lightbar to red
Alt-tab out of the game, and see if your lightbar turned back to green
If your battery has reduced to where the light turned to slight yellow, go back to the game, see if the lightbar turned back to red
Alt-tab out of the game, and see if your lightbar turned back to yellow.

**Expected behavior**
Lightbar will only change color depending on the battery percentage is left at, showing yellow meaning halfway on battery, though orange showing low battery, then pulsing when below 20%. 

**Screenshots and Logs**
Log: https://drive.google.com/file/d/1UhebblmlMy79lEWPeTRIojkr_OtOX5qj/view?usp=sharing

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: Windows 10 Home Build 19045.2486, version 22H2
 - DS4Windows Version 3.2.8

**Additional context**
At this moment I did not test other games outside of hogwarts legacy.

**Comment by Masamune3210** [comment]
Steam is known to cause issues with DS4Windows. Hide the physical controller with HidHide to keep it from being able to do things to it.

**Comment by Ryochan7** [comment]
Even though HidHide is considered an optional component, it is becoming increasingly necessary to have HidHide (or similar driver) installed and enabled at all times when using any external mapper besides Steam Input; reWASD bundles a similar driver and enables it by default. Even when Steam Input is completely disabled, Steam will still go through its initialization process for a controller and possibly change controller options; only the mapper portion will be disabled.

**Comment by darkedone02** [comment]
Alright, so I got it to where my controller has hidhide access, however I still noticed the filkering between lights when i play though steam games for some reason, between green and red.

**Comment by Kanuan** [comment]
From your LOG:

> 02/12/2023 10:54:56: Controller 1's latency over 10ms (16.9 ms)
> 02/12/2023 10:54:57: Controller 1's latency now under 10ms

Maybe you have the "flash lightbar at high latency" setting enabled in the Settings tab?

**Comment by darkedone02** [comment]
That may have been it, but I never expect it to turn red when it suppose to flash or pulse like it suppose to do.
