### ISSUE TITLE
Scoop Installation does not work, but regular installation works right out of the box

### ISSUE THREAD

**Issue by vvirtues** [Ryochan7/DS4Windows#2824]
I tried endlessly to make it work with scoop, but it just doesnt detect the controller. I check gamepad tester and it is picked up right away, and windows settings finds it as well. I gave up and installed the regular release (from github) and it worked instantly. Seems to be a problem with the scoop release?

**Comment by Ryochan7** [comment]
I do not support the use of Scoop for pretty much anything. Based on reports, it seems to be more of a problem than a helpful tool.
