### ISSUE TITLE
DS4Windows bluetooth baseus does not see the gamepad

### ISSUE THREAD

**Issue by boltozor** [Ryochan7/DS4Windows#2825]
[Log.txt](https://github.com/Ryochan7/DS4Windows/files/10721309/Log.txt)
![Screen](https://user-images.githubusercontent.com/69398339/218435487-e65c58d1-eb69-426f-97e8-b95f16a04359.png)
[ds4windows_log_20230213.13.txt](https://github.com/Ryochan7/DS4Windows/files/10721397/ds4windows_log_20230213.13.txt)

**Comment by Ryochan7** [comment]
I can only see one possible path where this might happen. Looks like the hardware is likely sending an invalid response when NativeMethods.HidD_GetSerialNumberString is called. The call is successful so the ReadSerial method will take the buffer, create a string, and then format it to the expected format in DS4Windows. This seems more like a hardware problem than a software problem but I guess I can add a length check before attempting to create the final serial string. It also looks like the fake hardware serial would have to be used for that device once the other routine fails.

https://github.com/Ryochan7/DS4Windows/blob/8bacbc3aa6b1c587f9737429076927d04ea1fde4/DS4Windows/HidLibrary/HidDevice.cs#L509

**Comment by boltozor** [comment]
> I can only see one possible path where this might happen. Looks like the hardware is likely sending an invalid response when NativeMethods.HidD_GetSerialNumberString is called. The call is successful so the ReadSerial method will take the buffer, create a string, and then format it to the expected format in DS4Windows. This seems more like a hardware problem than a software problem but I guess I can add a length check before attempting to create the final serial string. It also looks like the fake hardware serial would have to be used for that device once the other routine fails.
> 
> https://github.com/Ryochan7/DS4Windows/blob/8bacbc3aa6b1c587f9737429076927d04ea1fde4/DS4Windows/HidLibrary/HidDevice.cs#L509

I had the option not to use the driver with this usb whistle, ds4windows works there, but worse, the headphones do not work well. Therefore, I want everything to work with the baseus native driver. I tried xbox360ce it works but no vibration.
Thanks for the help, if you can get it to work that would be great.

**Comment by boltozor** [comment]
> 

Build through visual studio everything works. Thank you very much :)
