### ISSUE TITLE
Exits/crashes when disconnecting controller from USB

### ISSUE THREAD

**Issue by tordenflesk** [Ryochan7/DS4Windows#283]
DS4W v. 1.4.118, Windows 7 x64
I've no idea whether it's a regular exit or a crash, but the tray icon/running process disappears when disconnecting from USB and the controller stops working.
My current "solution" is adding ds4windows.exe to [Restart on Crash](https://w-shadow.com/blog/2009/03/04/restart-on-crash/)

**Comment by Ryochan7** [comment]
I have never experienced that problem. I will test that scenario on version 1.4.118 and 1.4.119 and see if I run into that problem.

**Comment by Ryochan7** [comment]
Doesn't crash for me when I disconnect a USB controller. I tested it in a
Windows 7 VM as well as Windows 10.
