### ISSUE TITLE
Dualsense: no controllers connected

### ISSUE THREAD

**Issue by Paromc** [Ryochan7/DS4Windows#2831]
All versions from 3.2.8-3.2.0 is not detecting my dualsense controller.
Version 3.1.12 works fine.
Other software like x360ce works fine too

**Comment by Zaephyyr** [comment]
Having the same issue here neither bluetooth nor wired work i'm on W11 with Cosmic purple dualsense

**Comment by bradleypregon** [comment]
Ensure "DualSense Controller Support" is enabled in Settings > Device Options.
Here is a troubleshooting guide as well - https://ds4-windows.com/troubleshoot/not-detecting-controller/

**Comment by Paromc** [comment]
> Ensure "DualSense Controller Support" is enabled in Settings > Device Options. Here is a troubleshooting guide as well - https://ds4-windows.com/troubleshoot/not-detecting-controller/

That it. Thank you
