### ISSUE TITLE
Windows 11 ARM binary?

### ISSUE THREAD

**Issue by cwscws** [Ryochan7/DS4Windows#2833]
The 64bit version works with Windows 11 ARM but it would be nice to have a native build.

**Comment by Ryochan7** [comment]
Checking that the libraries could compile to ARM would probably be the most difficult task for making an ARM binary. Many of the packages from NuGet target AnyCPU but there are a few packages used that use specific arch targets. I'll look into it.

**Comment by Ryochan7** [comment]
Seem to be running into the following problem when attempting to get an ARM64 binary built. Failing on the translation assemblies mostly. Changing parameters does lead past that point only to then complaint about FakerInputWrapper and the ViGEm.NET assemblies targeting a different platform despite other tools confirming that they are built for ARM64. It seems like a Visual Studio problem that is likely beyond my control. 

https://developercommunity.visualstudio.com/t/ALINK-alexe-does-not-support-ARM64-Wi/1325460

**Comment by cwscws** [comment]
Weird. I wonder how other projects are compiled for ARM. Nevertheless ViGEm is arm64.
