### ISSUE TITLE
can't find the DS4Windows.exe

### ISSUE THREAD

**Issue by Brazenpo** [Ryochan7/DS4Windows#2836]
nothing more to say i think... just downloaded the zip file, and once here, can't find the exe file, asked to dowload DS4

**Comment by haiiasii** [comment]
having a similar issue i think. forgive lack of description as im not familiar with all this but i downloaded it and i just got a folder with all the assets in it. where can i find the actual program?

**Comment by Ryusennin** [comment]
Maybe you are downloading the source code?

The executables are here:
https://github.com/Ryochan7/DS4Windows/releases

Look for packages named *DS4Windows_3.2.8_x64.7z* or *DS4Windows_3.2.8_x64.zip*
