### ISSUE TITLE
Is it possible to change the color of the gamepad via the command line to use this technique in your game?

### ISSUE THREAD

**Issue by MrKsiJ** [Ryochan7/DS4Windows#2838]
I am interested in the possibility of using DS4 Windows as a command-line shell, through which I would run my own console application in the background, which would connect to DS4Windows by passing DS4Device to the input and change the color of the geimpad to the one that would be required in the game, for example, red when I was attacked, or blue color, when everything is in order, I would also be able to connect vibration to my game, for example, when firing a weapon, or when attacking a player. Is it possible to implement this trick using DS4 Windows?

**Comment by MrKsiJ** [comment]
OK I did it and it works

**Comment by ld892012** [comment]
How you changing lightbar color with command line ? I find any information to do this
