### ISSUE TITLE
How to turn off mouse drifting/momentum?

### ISSUE THREAD

**Issue by MakiseKurisu** [Ryochan7/DS4Windows#284]
Currently after I move the mouse cursor with touchpad and stop finger movement, the cursor will still move for a slight distance. I couldn't find a way to turn it off. Any help?

**Comment by Ryochan7** [comment]
I have tested this with the old Jays2Kings version as well and it seems like there is some momentum inherit from the controller. Maybe there is some smoothing being done at the hardware level? There is no smoothing that happens in DS4Windows for normal touchpad operation. There is a buffer that is used for trackball emulation mode but that is only enabled if the touchpad is no longer being touched.
