### ISSUE TITLE
Ds4window crashes on start up

### ISSUE THREAD

**Issue by narumkung15** [Ryochan7/DS4Windows#2847]
My ds4window crash on start up facing this problem for about 1 weeks and cannot fix it up i don't know what to do

![image](https://user-images.githubusercontent.com/88785533/222085797-eddea469-e66c-43f0-b8ae-df922d693908.png)

**Comment by Ryochan7** [comment]
That would be a failure with the WMI hook to catch suspend and resume events. I would expect any sort of class failure to occur earlier in the ManagementScope class when making the first connection but apparently not. Not sure why it now just started failing on your end. Wouldn't put it past Microsoft to push a late update for Windows 8 to cripple it on purpose.

I added an extra catch clause to catch that exception if it would occur again; commit 9ec581273a75cffa25dbc07cae83e64519937d1a. I try to be lenient when it comes to exception catching as that seems to slow down the .NET Runtime to perform a bulk Exception catch.

**Comment by Ryochan7** [comment]
I believe this should have been resolved a while ago. Closing
