### ISSUE TITLE
Latest Windows Update removed the option to "Middle Click to Close" in the System Tray

### ISSUE THREAD

**Issue by dropdan** [Ryochan7/DS4Windows#2848]
**Description:**
I don't know if this fall under a "bug" category, but I just thought it should be mentioned.
Since the latest Windows Update (info below), the shortcut to close the app from the System Tray doesn't seem to be working anymore, this is probably to deal with the small appearance tweak Microsoft added to the new System Tray.

**Windows Version Info:**
Edition	Windows 11 Pro
Version	22H2
Installed on	‎28/‎09/‎2022
OS build	22621.1344
Experience	Windows Feature Experience Pack 1000.22639.1000.0

**Behaviour**
It is likely that this was intentional and won't be coming back.
The only update to DS4Windows would be remove to the "(Middle Mouse) info in the "Exit" option when we right click the application icon on the System Tray.

Hopefully this is the right place to report this.

**Comment by Ryochan7** [comment]
The initial firing of the event is up to H.NotifyIcon. DS4Windows just hooks into that event to setup the callback. Not sure if an update to H.NotifyIcon could possibly work around the issue to restore the TrayMiddleMouseDown event for Windows 11. It still works on Windows 10 for now.

I guess removing the tip in the tray menu would be the only thing that can be done right now.
