### ISSUE TITLE
DS4. Does not see the gamepad when connected via Parsec

### ISSUE THREAD

**Issue by boltozor** [Ryochan7/DS4Windows#2849]
![423423](https://user-images.githubusercontent.com/69398339/222194801-25093b3c-1e78-4c7d-987a-a0dd8baecc68.png)
The dualshock 4 is connected to the pixel 6 phone, I want to make it vibrate in games. But Ds4windows doesn't see it. It is possible to somehow add it to the program. Thanks.

**Comment by Ryochan7** [comment]
I would assume that DS4Windows probably detects it as a virtual gamepad and skips it. I have never dealt with Parsec. The hardware ID for the Parsec gamepad bus device (in Device Manager) would be needed so it can be added to the exclude list. That way the underlying check in Nefarius.Utilities.DeviceManagement will not skip over the emulated gamepad device.

**Comment by boltozor** [comment]
> I would assume that DS4Windows probably detects it as a virtual gamepad and skips it. I have never dealt with Parsec. The hardware ID for the Parsec gamepad bus device (in Device Manager) would be needed so it can be added to the exclude list. That way the underlying check in Nefarius.Utilities.DeviceManagement will not skip over the emulated gamepad device.

![2023-03-02 092752](https://user-images.githubusercontent.com/69398339/222362341-9644e73c-a813-486e-b9df-e0d238dd41b8.png)
![2023-03-02 093743](https://user-images.githubusercontent.com/69398339/222362398-dad723fd-36f0-4707-becb-ab49408f6785.png)

**Comment by boltozor** [comment]
Now connected, but it shows 0% battery and vibration does not work.
[ds4windows_log_20230302.10.txt](https://github.com/Ryochan7/DS4Windows/files/10869087/ds4windows_log_20230302.10.txt)

**Comment by Iceboy-6** [comment]
Hi, @boltozor.

Please, could you explain how you solved this problem? I'm having the exact situation (sharing 4 controllers as dualshock 4 from a notebook to a host with parsec and none of them are recognized by DS4Windows application on the host).

Thank you.

**Comment by RempelOliveira** [comment]
I have the same issue and I would like to use DS4Windows with Parsec. I tested other applications and it appears to be not possible because the joystick is not a phisical pad :/
