### ISSUE TITLE
Quick Disconnect Combo

### ISSUE THREAD

**Issue by rafsanjani** [Ryochan7/DS4Windows#285]
Can we have a quick disconnect combination for where for example pressing key combinations such as (R1 + R2 + PS) will disconnect automatically without interracting with the software. I think this will be a very handy feature and will also improve user experience as well.
Thank you

**Comment by TristanYoung** [comment]
There is already the ability to disconnect the controller by pressing PS for a configurable amount of time.  I find that works way easier than having to press 3 buttons simultaneously.  It allows me to quickly swap out controllers mid-trial in ESO.

When you say, 'without interacting with the software' - are you referring to the game itself?  If so, the PS disconnect feature in DS4Windows does that.

If you're talking about not interacting with DS4Windows - not possible.  The controller is a rather simple device, the only ways the controller disconnects itself from the PC is through a loss of power, loss of signal, pressing the reset button (loss of power?), and pressing the PS button for 10+ seconds - I believe.

**Comment by rafsanjani** [comment]
Without interacting with the software, I meant the DS4Windows, not the game. "Pressing the PS button for 10+ seconds" is exactly my problem because it seems to be a lot of delay in my experience. Something which could have been triggered in less than a second with a combination of keys takes 10+ seconds with the PS key.  

Better still it could be implemented as an option so that users could choose between using a key combination to disconnect it instantly or use the PS button for 10+ seconds.

**Comment by TristanYoung** [comment]
Hello @rafsanjani ,

Unfortunately the controller's built-in PS Button 10s shutdown feature is not programmable.

However the behavior you want can be done in software with DS4Windows very easily.

DS4Windows->Tab: Profiles->Edit an existing profile or create a new profile ->Tab: Special Actions -> New Action -> Name: enter a unique name -> Trigger Checkbox: Check the box beside PS -> Select an Action: Disconnect from Bluetooth -> Hold for: set the number of seconds.

I recommend picking a value for seconds that won't shut your controller down if you accidentally press the button combo, but isn't so long that it causes grief while you're in action and discover you need to swap controllers before your battery totally gives out.  I selected 2 seconds - long enough that I have to do it deliberately, but not so long as to add much delay if I'm in an active group raid.

I hope this helps.

**Comment by rafsanjani** [comment]
Hi @TristanYoung 
Thank you very much for pointing me in the direction where I can manually configure it without meddling with the source code. I didn't know an option like that exists, honestly, I haven't played around with the profile options much so I will definitely give that a try.

**Comment by TristanYoung** [comment]
You're welcome.  Have fun.
