### ISSUE TITLE
DS4Windows PS3 Controller issue

### ISSUE THREAD

**Issue by TimmyTurner51** [Ryochan7/DS4Windows#2859]
Hello, I've switched to DS4Windows from dshidmini to test this out with PS3 Controllers. I have an OEM controller I'm trying to connect, but it will not connect. Looking at the logs, I see:

Using Shared Mode
Found Controller: 12:15:3F:B8:20:00 (USB) (DualShock 3 (SXS)).
Plugging in virtual X360 controller (XInput slot #1) in output slot #1
Associated input controller #1 (DualShock 3 (SXS)) to virtual X360 Controller in output slot #1
Disassociated virtual X360 Controller in output slot #1 from input controller #1 (DualShock 3 (SXS))
Unplugging virtual X360 Controller from output slot #1

It finds the controller, then disconnects immediately, and looping this behavior.
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/10918785/ds4windows_log.txt)

I've also followed the guide to uninstalling dshidmini. I don't see any leftovers of it now, and rebooted my pc multiple times.

**Comment by Ryochan7** [comment]
I have only used a DS3 controller when using DS4Windows mode in dshidmini. At least with that configuration, it works fine on my end; it works better than the XInput output mode is in dshidmini. That would be the way I would suggest that you use a DS3 controller on PC.

Although, the DS3 has been the least useful controller in my small collection. Never liked the DS3 back during the PlayStation 3 days either. Not really worth spending the Corona bucks to buy one imo.
