### ISSUE TITLE
Controller Stops Working Randomly While Playing GTA V (Windows 10)

### ISSUE THREAD

**Issue by GeodesicDragon** [Ryochan7/DS4Windows#286]
I'm using DS4Windows while playing Grand Theft Auto V, as I find it easier to use a controller rather than a keyboard to do certain things (like flying).

After a while, however, the controller will stop working; I will hear a noise from Windows which implies a device has been disconnected, yet when I unplug it and plug it back in, the controller still won't work. I have to restart the game in order for it to register that I have a controller plugged in.

I am using the Steam version of GTA V, if that helps at all. I am also using the 64-bit version of Win10.

If you need more information, let me know.

**Comment by Ryusennin** [comment]
Probably related to the exclusive mode, which has been covered at length in various bug reports. Have a look at them for more context, and give a try to the HID Guardian driver mentioned in topics like #270 

http://ryochan7.xyz/ds4windows/test/DriverInstaller_Test_20180402.zip

**Comment by Corrodias** [comment]
Also ensure you have version .118 or higher; there were some disconnection issues when using USB between 114 and 117.

**Comment by Ryochan7** [comment]
Exclusive mode might be an issue since GTA 5 might end up grabbing the DirectInput device instead of the virtual Xbox 360 controller. If the exclusive mode workaround does not work, you might want to try using HidGuardian to hide original DS4 controller from the system.

**Comment by Midoriin** [comment]
Edit: Apperantely, that's an issue with the game. Check out these links:

https://steamcommunity.com/app/271590/discussions/0/2425614539592400447/
^ second comment. 
https://www.reddit.com/r/gtaonline/comments/7m8ndh/cant_connect_gamepad_during_session/
