### ISSUE TITLE
DINPUT missing

### ISSUE THREAD

**Issue by SeanPost** [Ryochan7/DS4Windows#2861]
DS4WINDOWS needs DINPUT to XBOX controller allowing ANY DINPUT controller to take advantage of it. Having to use REWASD to gain these functions is painful as I prefer DS4Windows over all other DINPUT to XINPUT apps. PLEASE add DINPUT to XINPUT allowing any controller with DINPUT

**Comment by Ryochan7** [comment]
I do not see this ever happening. Even with a DInput device reader, there would still need to be a way to map buttons and axes by position to the DS4 layout for use in the output mapper. Probably would have to do what Steam does and rely on SDL2 GameController mapping strings to set the mapping.

I would rather continue to work on improving mapper capabilities and getting more use of already supported devices.

**Comment by SeanPost** [comment]
Okay I guess I have no choice but to purchase REWASD. That does switch and dinput (DS4 is dinput method is it not?). Anyhow I have greatly enjoyed using DS4Windows and thank you for making this available to us. I would use REWASD and DS4Windows together allowing me to have 1 for my PS5/PS4 controllers and other for switch/Dinput pads but they conflict and it makes a mess so I am stuck with one or other. Thanks for the reply and awesome work, I really appreciate everything you have done.
