### ISSUE TITLE
Lightbar is not set when powering DS4 controller on with profiles with "Output data to DS4" disabled

### ISSUE THREAD

**Issue by alexkiri** [Ryochan7/DS4Windows#2865]
**Description:**
As the title describes, when powering on the DS4 controller, and the current profile has the "Enable Output data to DS4" setting disabled, the Lightbar color is not set. If I switch to a different profile (that has the above setting enabled), the Lightbar is setup correctly.
Even though, by disabling the setting, it's expected that the lightbar and vibration functions will not work, I do expect that this means that the lightbar is no longer dynamic (as in controlled by the game). The color of the light should be correctly set initially. I use the color to differentiate between different profiles, and I disable the Output data in order to save battery and get the best latency.

**Steps to reproduce the behavior:**
1. With the DS4 controller powered off, start DS4Windows
1. Create a profile with "Enable Output data to DS4" setting disabled, and select this profile
3. Power on the controller

**Expected behavior:**
The initial color of the Lightbar should be set up, regardless of the "Enable Output data to DS4" setting

**Desktop:**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2E)
 - OS: Windows 11 Version 22H2 Build 22621.1344
 - DS4Windows Version 3.2.9
 - Connection method: Bluetooth

**Comment by Ryochan7** [comment]
I believe there are 3rd party DS4 clones that depend on the current **Output date to DS4** behavior. This will likely not be changed.

**Comment by alexkiri** [comment]
Ok, but I still think this is an issue that can be fixed without affecting the DS4 clones.
This is why I think this. Let's have this scenario:
ProfileA has "Enable Output data to DS4" setting disabled
ProfileB has the setting enabled
Here are some behaviors I observed:
- Power on with ProfileA (light is off); switch to ProfileB (light is set up); switch back to ProfileA (light is set up to the correct color)
- Power on with ProfileB (light is set up); switch to ProfileA (light is set up to the correct color)

The issue happens only when you power the controller on
