### ISSUE TITLE
Nintendo deluxe face off red controller is not being detected 

### ISSUE THREAD

**Issue by destroylonelym** [Ryochan7/DS4Windows#2866]
so i downloaded  ds4 windows and notice that the controller was being detected so i look up some videos and it would not help somebody told me to redownload and use sxs mode but i don't see that either

**Comment by Kanuan** [comment]
> Nintendo deluxe face off red controller

If this controller has a different hardware identification (VID/PID) than Nintendo's legit one then DS4Windows won't recognize it.

Send a screenshot of its VID/PID by:

1. Connecting the controller via cable
2. Opening the [gamepad tester website](https://gamepad-tester.com/)
3. Sending a screenshot of the controller info

> and use sxs mode

SXS Mode is related to DualShock 3 ("PS3") controllers running under DsHidMini and is completely unrelated to Nintendo controllers

**Comment by destroylonelym** [comment]
![Image](https://user-images.githubusercontent.com/127589416/224521452-df5e7611-33cd-4a42-afe1-02edd5314a23.png)


![image_2023-03-11_215026685](https://user-images.githubusercontent.com/127589416/224521473-86d32a8d-4a71-403f-920b-a090c669dd34.png)

**Comment by Ryochan7** [comment]
No help. Expecting a hobo to buy a bunch of game controllers. People do not even make these kinds of expectations when it comes to Valve; Steam Input has legit been broken in several ways since the launch of the Steam Controller in 2015.
