### ISSUE TITLE
PS Remote Play ignoring virtual DS4

### ISSUE THREAD

**Issue by Kanuan** [Ryochan7/DS4Windows#2868]
# The issue

This is not an issue with DS4Windows per-se, but anyway: ever since the PS Remote Play version 6.0 it seems the app is ignoring vigem created controllers.

The "controller connected" icon shows and might even display the charging animation while connected to the console, but inputs will be fully ignored.

From what I know, no one is sure if the app is directly ignoring vigem controllers or just checking for something vigem or the remapper app is doing incorrectly.

# Some testing

I tried testing if the issue could be some counter not being properly emulated by DS4Windows but no dice: even by fully copying a DS4v2 USB Input Report directly into ViGEm's Virtual DS4 the behavior is the same. I kinda spaghetti coded an app just to test this and might have done something wrong, but the virtual controller works as normal in Steam and on the GamepadTester website, so not sure what could be wrong.

**Comment by Ryusennin** [comment]
I observe the same behaviour since updating to PS Remote Play 6.0.

Renaming the DS4Windows executable doesn't have any impact either.

**Comment by Kanuan** [comment]
Accordingly to Nefarius (ViGEm developer), the app is sending a request to the controller and then waits for the proper response. Unfortunately the ViGEmBus does not currently emulates the required response. Because almost all current controller emulation softwares use ViGEm to spawn virtual controllers they are all affected.

There is no estimate for now on if/when this will be fixed.

**Comment by Ryochan7** [comment]
That is a shame. At least it looks like the breakage was not intentional.

**Comment by BlackGuedes** [comment]
Não entendo por que a Sony não permite nativamente usarmos o controle em modo bluetooth no windows, sendo que pra Android funciona.

**Comment by Walter-o** [comment]
I'm here to confirm this is real.

I have a bunch of known working code that is suddenly broken by PS4 Remote play updates since that is the only change in my environment.

Also just did a bunch of tests with different virtual controller methods and i can't get past it with any.
I only managed to get in 1 single button press when reconnecting a virtual controller and i could not replicate it again
(kind of further proves it's a special check added by sony)

Hoping that ViGEm devs patch this soon, if i find a workaround i'll post here.

**Comment by Ryochan7** [comment]
Not going to get an updated driver so this issue will not be resolved. I cannot attempt to do anything myself as there is a literally paywall attached to the problem.

**Comment by Ryusennin** [comment]
As suggested by another user, [Chiaki](https://git.sr.ht/~thestr4ng3r/chiaki) does a very good job replacing PS4 Remote Play.

**Comment by Ryochan7** [comment]
Never heard of that client before. Sounds like it would be a good workaround.
