### ISSUE TITLE
App breaks after waking from Sleep / Hibernate

### ISSUE THREAD

**Issue by TimberAngry** [Ryochan7/DS4Windows#2869]
After waking from sleep or hibernate, DS4Windows doesn't detect the controller, and shows the following error:

"ViGEm Device Plugin Failed. Likely an internal ViGEmBus problem. Closing connection. If the issue persists, please close DS4Windows and then reboot Windows."

Perhaps it was trying to start too quickly or something?

If you then try to click 'Start' button manually it doesn't start properly (see last 5 lines in attached log, nothing happens beyond that)
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/10964616/ds4windows_log.txt)

There doesn't seem to be any way to recover from this state, and the app must be closed, and works fine when you launch it fresh.

**Comment by Ryochan7** [comment]
For a brief period, I was able to test Suspend / Resume functionality. Made some recent changes to try to work around the problem. The inherent problem seems to be that DS4Windows gets restored before ViGEmBus is ready for connections. In the current code, the Resume routine has been changed and a much longer wait period has been added before DS4Windows will attempt to automatically connect to ViGEmBus. Not sure when I will get around to making a new release with the change in place.

**Comment by TimberAngry** [comment]
Thanks Ryochan7, I tested this and it works! Much appreciated.

Though... the wait period is excruciatingly long haha, and somewhat defeats the purpose of using Suspend / Resume (which is to pick up playing your game again quickly!)

It seems to be exactly 2 minutes. Surely just a few seconds would be enough for ViGEmBus to initialize? I suppose it would differ slightly for different systems, perhaps the wait time could be configurable?

Anyway, thanks again, love your work.

**Comment by cnapolit** [comment]
I thought this fix was a bug for a sec 😅

My environment wasn't seeing the issue on wake and DS4W would immediately function prior to the latest update, but now it takes the full 2 minute wait time.
I think @TimberAngry is correct. It's easier to either restart DS4W or power off altogether.

Is there a way to attempt a connection to ViGEmBus, and wait a few seconds to re-attempt a certain number of times if that connection throws/fails?

**Comment by R3t4o** [comment]
Is there any way to make the wake from suspend wait time configurable like @TimberAngry suggested? 150 seconds is a rather long wait for my controller to connect!

Absolutely love the work you guys do tho, it’s one of my favourite apps!

**Comment by v3i1r4in** [comment]
The fix just made everything worse... I had the crash issue before too, but I just have to remember to relaunch DS4Windows when I wake my PC up which just take a few seconds. Now I have to either wait for 2 minutes, or I have to manually kill DS4Windows and then relaunch it.

Please fix this!!! Make it either shorter or configurable.

**Comment by Masamune3210** [comment]
Quite literally from the last release's changelog. If you are going to complain about something, at least try to make sure that an effort to fix it hasn't already been made
![image](https://github.com/Ryochan7/DS4Windows/assets/1053504/afd99f93-cd8d-4e4b-b51f-b2dc99da5da3)

**Comment by v3i1r4in** [comment]
> Quite literally from the last release's changelog. If you are going to complain about something, at least try to make sure that an effort to fix it hasn't already been made ![image](https://user-images.githubusercontent.com/1053504/251216222-afd99f93-cd8d-4e4b-b51f-b2dc99da5da3.png)

Ok, my bad. I assumed people would update the issue, if it's fixed.

**Comment by cnapolit** [comment]
@Masamune3210 A little harsh. It's not an unfair assumption if the ticket is still open.

**Comment by TimberAngry** [comment]
Confirming that the issue is fixed for me, controller is now reconnecting perfectly. Issue can be closed, thank you very much!

**Comment by Masamune3210** [comment]
> @Masamune3210 A little harsh. It's not an unfair assumption if the ticket is still open.

Its also not an unfair assumption that if someone makes a issue or comments on a issue that they would be also actively at least looking out for changes to test. Watching for a new release to see if the issue still exists isn't that hard of an ask and not every project has devs who have the time to constantly and consistently keep up with every issue report
