### ISSUE TITLE
Turn off DS4 with PS button?

### ISSUE THREAD

**Issue by pragma-** [Ryochan7/DS4Windows#2870]
Is there an easy way to turn off the DS4 controller by simply pressing the PS button? The only way I know of to turn off my gamepad is to hold down the PS button for 10 seconds, which often feels like an eternity. I want to be able to simply just tap the button.

I see there is a way to set "special actions" that trigger when the PS button is pressed. One of the special actions is "Disconnect BT". Would it be possible to add "Turn off gamepad"?

Does anybody know of an app to turn off the DS4 gamepad or a way to customize the firmware to change the timing for how long you have to hold the PS button down to turn off the gamepad?

**Comment by Masamune3210** [comment]
Ps button + start by default turns off the controller in ds4windows

**Comment by pragma-** [comment]
"Disconnect BT" actually turns off the controller! I didn't realize this. I configured this to be just the PS button instead. Goal achieved. Thanks!

**Comment by Masamune3210** [comment]
No problem

**Comment by Mister-Curious** [comment]
> Ps button + start by default turns off the controller in ds4windows

Is there a way to map this out another way? The combo you suggested doesn't work for me, and I'm wondering if its due to my PS button being remapped.

**Comment by Masamune3210** [comment]
Just go into the profile and map Disconnect BT to a different combo if you don't or cant have it on PS + Start

**Comment by Mister-Curious** [comment]
> Just go into the profile and map Disconnect BT to a different combo if you don't or cant have it on PS + Start

Thank you. How to map Disconnect BT though? I don't see it anywhere

**Comment by pragma-** [comment]
@Mister-Curious ![](https://i.imgur.com/Q5VF772.png)
