### ISSUE TITLE
Controller lose connection every 30 min

### ISSUE THREAD

**Issue by thekingm249** [Ryochan7/DS4Windows#2874]
Hello everyone

I have a weird problem .
I have a genuine Sony DS4v2 controller and i am using it exclusively on PC. My DS4 keep losing connection every 30 minutes.
I have disabled power saving and selective usb on pc and i am using Windows 10. 
[
[ds log.txt](https://github.com/Ryochan7/DS4Windows/files/11056679/ds.log.txt)

The log file is attached .
Hope you can help me find a fix for this issue.

Thanks

**Comment by Ryochan7** [comment]
Looks like a hardware problem. Windows error code 1167 is for the status `ERROR_DEVICE_NOT_CONNECTED`.
