### ISSUE TITLE
DS4Windows no longer detects my controllers via bluetooth

### ISSUE THREAD

**Issue by Zoooook** [Ryochan7/DS4Windows#288]
I just bought a new controller. After pairing it with my computer via bluetooth, neither my old or new controller are recognized by DS4Windows via bluetooth. The light on the controller is solid white, which I think indicates it is paired with the PC. They pop right up when I plug them in with USB. Running Windows 8.1, just ran Windows Update to try to resolve it, with no luck.

**Comment by rafsanjani** [comment]
did you pair it using the option + share combinations or u just pressed the options key? Pressing just the options key will not work so you will have to press and hold both the (options + share) buttons for about 5 seconds. This puts the controller in discoverable mode (white led will blink 3 times every second or so) . After pairing with your pc, it should display in the dashboard of DS4Windows. 
I hope this helps

**Comment by Ryochan7** [comment]
The lightbar color for a controller connected via BT should be more of a light blue. The lightbar would be solid white if you have Steam's PS4 Controller support enabled in the Steam client. If that is enabled then DS4Windows cannot use the controller. You might also want to check the Windows Device Manager and make sure that the DS4 BT device is not marked as disabled and make sure that Windows can actually see the DirectInput device.
