### ISSUE TITLE
Problems registering a gamepad with extra buttons

### ISSUE THREAD

**Issue by Relobum** [Ryochan7/DS4Windows#2883]
First I would like to express my incredible appreciation for what you do. Without your software... I don't know what I would have done.

To the point.

Purchased a custom DualSense Dragonfly with additional buttons the other day. Unfortunately, they won't work with DS4Windows no matter what I do.

- It does not register presses. I cannot reassign the additional buttons to individual functions. That is, I can not find such a feature in general.

I will be very grateful if you tell me where to look for a solution :)

**Comment by Masamune3210** [comment]
Third party controllers are not guaranteed to work completely on PC, it entirely depends on how the company decided to implement their extra functions and how much they decided to mess with the standard protocol or not

**Comment by Relobum** [comment]
> Third party controllers are not guaranteed to work completely on PC, it entirely depends on how the company decided to implement their extra functions and how much they decided to mess with the standard protocol or not

Вас понял. Благодарю за помощь :)
