### ISSUE TITLE
Switching profiles via Special Actions not working.

### ISSUE THREAD

**Issue by Mister-Curious** [Ryochan7/DS4Windows#2884]
**Describe the bug**
I recently tried binding a two buttons to launch a separate profile in DS4Windows through 'Special Actions' but it doesn't work when I press the buttons. I have saved the Special Action, made sure it was checked in the profile, and made sure I saved the profile as well, yet nothing happens. 

Is this a bug with 3.2.9?

**To Reproduce**
1. Go to 'Special Actions'
2. Click on 'New Action', then click on the 'Select an Action' filed and choose 'Load a Profile'
3. Underneath that there is a field that says (none). Select the desired profile there. 
4. On the left hand pane, chose which buttons will trigger the Special Action.
5. In the Special Actions section press save. Then hit Apply at the top, then save, so all changes are saved to profile.. 
6. Check to make sure the Special Action has been saved and is activated in the profile with a checkmark. 
7. Press the buttons that were assigned in step 4
8. Nothing happens. 

**Expected behavior**
Profile should switch to assigned profile in Special Actions

**Desktop (please complete the following information):**
 - Controller Make and Model: 88:03:4C:5F:FF:AA (SONYWA) (Sony WA).
 - OS: Windows 10 Pro Build 22H2
 - DS4Windows Version 3.2.9

**Comment by Mister-Curious** [comment]
EDIT - It seems the profile is switching, but the name doesn't update in the main window, so users can't tell if the profile has been loaded or not. It would be useful if the title updated. Thank you!

**Comment by Ryochan7** [comment]
Unfortunately, that is actually a feature. Been that way since at least the Jays2Kings builds if not earlier. DS4Windows has the concept of a temp profile. It loads but does not override which profile is shown as selected in the GUI. It is used for Auto Profiles as well. I decided to just keep the original behavior rather than try to change it.
