### ISSUE TITLE
FakerInput stops working sporadically after restart

### ISSUE THREAD

**Issue by Capo-m2c** [Ryochan7/DS4Windows#2889]
**Describe the bug**
Instead of SenderInput I installed FakerInput to map 'F8' key to 'SHARE' button on PS5 DualSende controller.
It works just fine in any usecase, but stops working after a restart (not always!). 
DS4Windows is set to autostart as task (tried as programm as well), it will always start in admin mode. 
I can see in the log tab, that FakerInput is in use and correctly loaded. 

**To Reproduce**
Tried using it as admin and as standard user
Tried using autostart as task or as program
Tried without autostart option manually
Tried with autostart via cronjob in windows
Reinstallation (repair as well) of FakerInput always helps 

**Expected behavior**
After every start of DS4Windows (autostart/ manually) it should map F8 key corretly to SHARE button when launching programs, especially games. 

**Screenshots and Logs**
If applicable, add screenshots to help explain your problem. Also, please add the most
log file (ds4windows_log.txt) from the Logs folder in your DS4Windows config folder.

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DualSense CFI-ZCT1W
 - OS: Windows 11 Pro 22H2 
 - DS4Windows Version 3.2.9

**Additional context**
If it helps: I use online keyboard tester to check if FakerInput works correctly after every start. If it does not work on the tester, it will not in games. If it does work, it will also work in games. 
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/11091495/ds4windows_log.txt)
[ds4windows_log_20230328.9.txt](https://github.com/Ryochan7/DS4Windows/files/11091496/ds4windows_log_20230328.9.txt)
[ds4windows_log_20230328.10.txt](https://github.com/Ryochan7/DS4Windows/files/11091497/ds4windows_log_20230328.10.txt)
[ds4windows_log_20230328.11.txt](https://github.com/Ryochan7/DS4Windows/files/11091498/ds4windows_log_20230328.11.txt)
[ds4windows_log_20230328.12.txt](https://github.com/Ryochan7/DS4Windows/files/11091499/ds4windows_log_20230328.12.txt)
[ds4windows_log_20230328.13.txt](https://github.com/Ryochan7/DS4Windows/files/11091500/ds4windows_log_20230328.13.txt)
[ds4windows_log_20230328.14.txt](https://github.com/Ryochan7/DS4Windows/files/11091501/ds4windows_log_20230328.14.txt)
[ds4windows_log_20230328.15.txt](https://github.com/Ryochan7/DS4Windows/files/11091502/ds4windows_log_20230328.15.txt)
![Screenshot 2023-03-28 180308](https://user-images.githubusercontent.com/129202258/228300025-293ab217-5283-4a44-b63d-6323df9b0690.png)

**Comment by negahdari** [comment]
I have the same problem. 
on some machines it works perfectly but on some machines after restarting the HID driver cannot be accessed anymore and generates IO error: 
Failure: Could not find our HID device

the driver is installed and looks working. after direct installing it works but after first windows restart it won't work anymore

**Comment by negahdari** [comment]
Ok. i could solve the issue. 
There was a bug in fakerinput.dll souces where it access the HID,
fakerinputclient.cpp : 395
one of FILE_SHARE_READ should become FILE_SHARE_WRITE.

**Comment by Ryochan7** [comment]
Never ran into the problem myself but that code does seem botched. Looked back at the old vmulti client code and it has the same problem; FakerInput is a UMDF driver port of vmulti with some changes. I'll give that a test and include an updated DLL file with the next release of DS4Windows. One main disadvantage is that an updated FakerInputDll.dll file will not be digitally signed. Hopefully that will not cause Windows to bring up additional complications.

```
file = CreateFile ( deviceInterfaceDetailData->DevicePath,
                            GENERIC_READ | GENERIC_WRITE,
                            FILE_SHARE_READ | FILE_SHARE_READ,
                            NULL, // no SECURITY_ATTRIBUTES structure
                            OPEN_EXISTING, // No special create flags
                            0, // No special attributes
                            NULL); // No template file
```

https://github.com/Ryochan7/vmulti/blob/master/client/client.c#L592

Thank you negahdari for finding the problem with the client code.

**Comment by Capo-m2c** [comment]
Well guys thank you so much for looking into it. 
Looking forward to the update. 
Great work! :)
