### ISSUE TITLE
Not working properly after PC restart

### ISSUE THREAD

**Issue by jermiez** [Ryochan7/DS4Windows#289]
I'm using DS4Windows to play FortNite with a PS4 controller and it was working fine until I turned my computer off. The next time I turned it on, it stopped working properly. I was getting double input when using the D-pad and some of the other buttons, as well as "X" not working on some parts of the games menu as far as I can tell. 

I reinstalled FortNite and deleted DS4Windows in the appdata folder and the folder containing the program (couldn't find an uninstall.exe) and everything worked again, but when I turned my computer off and on again, it stopped working. I tried reinstalling repeatedly with no success. 

I went into settings and checked the box "Hide DS4 Controller," but even with no other programs open at all, it keeps giving me a warning message at the bottom "**Warning: Could not open DS4 AC:FD:93:0E:7B:A5 exclusively. You must quit other applications like Steam, Uplay before activating the 'Hide DS4 Controller' option.**"

I'm running Windows 7 Ultimate, have the Xbox 360 controller drivers installed, have the latest .Net framework 4.7.2, and am running DS4W as administrator. I've also tried different USB ports.

**Comment by Corrodias** [comment]
Double input corroborates the warning that it can't open it in exclusive mode. If the program is running as admin, though, this would be the first time I've heard of it failing to grab exclusive use. It seems like something on the system is aggressively getting ahold of it first. Have you tried plugging it in while no other applications (including Steam) are running?

You can try using HIDGuardian, https://github.com/Ryochan7/DS4Windows/wiki/DS4Windows-and-HIDGuardian---Install-and-Setup-Guide

**Comment by jermiez** [comment]
@Corrodias I just tried out that setup you linked and it didn't work. I ignored the Windows Driver Kit part because I'm on Windows 7. It's also worth noting that everytime I reinstall DS4Windows, it always pops up with the last color from my previous install even though I'm deleting the appdata folder and the program folder. Is there a proper way to uninstall it? Or anything else I may be doing wrong?

**Comment by Corrodias** [comment]
Hmm, the article never indicates what devcon.exe is supposed to be used for. Guess it probably(?) isn't needed. But in that case I don't know how to help, sorry. I also don't know offhand where the DS4Windows settings are stored. The color of the light bar should be stored in the profile, which is in appdata\roaming, but if that's not it, then I don't know how it would be keeping the color.

**Comment by jonaaa20** [comment]
devcon.exe is needed to install the hidguardian driver.

**Comment by Corrodias** [comment]
Well, that would handily explain why it didn't work. Step 4, "This will install the HIDGuardian filter driver.", must have failed, but when run the way it's described, you won't get to see error messages because the window will immediately close.

**Comment by jermiez** [comment]
I'm doing a complete reformat and just reinstalling my OS. Ty for all the responses.
