### ISSUE TITLE
Feature request: An exe installer is needed

### ISSUE THREAD

**Issue by youcefv** [Ryochan7/DS4Windows#2891]
There must be a exe windows installer, the only way to use the app currently is download the zip or 7z packages from releases page,
The installer must have these feature:

- Registers the program entry alongside the other installed programs on:
(Setting > Apps > Apps & features) and (Control Panel\Programs\Programs and Features).

- Adds register entries for the app only if needed.

- It shouldn't begin installation automatically after being executed, it MUST have a start button to begin or proceed the installation process.

-It must have the option to choose the path of installation, with the default path being "C:\Program Files\DS4Windows".

Note: Most installers have these feature, I'm just being quite explicit.

**Comment by Masamune3210** [comment]
There are a lot of demands here but I don't see a lot of willingness to help or do it. You don't NEED a installer, portable apps have been a thing almost since the start of computers and will continue being a thing for probably quite a bit longer lol

**Comment by Ryochan7** [comment]
The idea of DS4Windows ever being considered a portable program was a bad one. It has caused so many problems with people outright putting the program in bad places were permission issues come up constantly. Also, any app that requires custom drivers to be installed on the PC should not be considered portable.

Been evaluating installer frameworks but not much has been done yet. Made the most progress with NSIS out of all the options I have tried. Inno Setup would likely not do what I want and Qt Installer Framework is too bulky and not well supported anyway. At least now I have a general idea of how the installer will work out.

https://github.com/Ryochan7/SteamControllerTest/issues/11

Lots of checks need to be in place in the installer (.NET installation, drivers check, possibly previous install check).

**Comment by Ryochan7** [comment]
It should be noted that any accompanying program used by the installer will likely have to be written in C or C++. AFAIK, on a standard Windows 10 install, .NET Framework 4.5 is the only guaranteed .NET version that programs will have access to. .NET Framework has been deprecated for a long time so it should not be relied upon for new programs.

**Comment by Ryochan7** [comment]
Made an attempt at making a similar installer for another project using WiX Toolset. Did not quite work out the way I wanted; I could not get full parity with the NSIS version of the installer. Also, I had to resort to use C# Custom Actions even though I wanted to avoid doing so. Still not sure which installer system I would end up using.

SteamControllerTest_installer.exe (NSIS)
https://drive.google.com/file/d/1v6s2MGen53k2RL_J3ZmhKHiTNhGqTVwp/view?usp=sharing

SteamControllerTest_SetupProject.msi (WiX)
https://drive.google.com/file/d/1FonUNLBGnhPSHFoQMz3L6xrZ-gCGdhux/view?usp=sharing

SteamControllerTest_NSIS_files_20230506.7z
https://drive.google.com/file/d/1wvgZqbMP_lrOD-CWYKeNh3Tlum0ht8Ld/view?usp=sharing

WixSteamControllerSource_20230506.7z
https://drive.google.com/file/d/1q2xH5O-hiZKZO3dCREdFRYe8GnJdYDqB/view?usp=sharing

**Comment by youcefv** [comment]
I would suggest you go with NSIS.
