### ISSUE TITLE
Enhancement: Add implicit theme selection.

### ISSUE THREAD

**Issue by youcefv** [Ryochan7/DS4Windows#2892]
There are two options when the user selects a theme: Default (Light) and Dark.

- I suggest that a third option should be added which follows the current system theme, and should be called "System (implicit)".
- This new option should be at the top of the list and serves as the new Default option.
- "Default" should be renamed to "Light".

**Comment by Ryochan7** [comment]
This feature is in DS4Windows 3.2.13 now. Not sure how useful it will be though.
