### ISSUE TITLE
PC doesn't go to sleep when DS4Windows is running

### ISSUE THREAD

**Issue by bugoutfr** [Ryochan7/DS4Windows#2894]
**Describe the bug**
When running DS4 Windows (I usually leave it in the system tray), my PC stops going to sleep and doesn't put my screen into standby mode either.

**To Reproduce**
- Launch DS4Windows
- Leave it in the system tray
- Wait until the time set for screen standby and/or PC automatic sleep has elapsed
- Result: PC doesn't go to sleep and monitors stay on

**Expected behavior**
PC should automatically go to sleep mode according to the rules defined defined in the Windows power control panel .

**Desktop:**
 - Controller Make and Model: No need for a controller to be plugged (but I generally use a PS4 DualSense)
 - OS: Windows 11 Pro Build 22621
 - DS4Windows Version 3.2.3 x64

**Comment by Masamune3210** [comment]
You likely have a slightly leaning joystick or something else, Windows won't go to sleep if there is any input

**Comment by bugoutfr** [comment]
Hi, thanks for the answer.
It's a good suggestion, but I still have the problem after disconnecting the controller (which I only use through its usb cable connection).

Simon
________________________________

**Comment by Ryochan7** [comment]
Are you using the UDP or OSC server? Maybe some network traffic could be causing the computer to not go to Sleep mode.

**Comment by bugoutfr** [comment]
Hi, you are probably right about the drift, I've noticed that my controller is aging.
I thank you for your help and the great job on maintaining DS4Windows 👍
