### ISSUE TITLE
[Feature request] A way for this software to behave like connecting the DS4 to the USB port

### ISSUE THREAD

**Issue by epigramx** [Ryochan7/DS4Windows#2898]
I noticed most games don't behave well directly with the DS4 on a bluetooth connection but they can deal with it on a USB connection.
The big advantage of that would be to see the "PS button graphics" consistently in-game instead of a mixed experience.

**Comment by Masamune3210** [comment]
Connect DS4 through Bluetooth
Go into options for profile in ds4windows
Set it to emulate a DS4 instead of a Xbox controller

or

Just use a mod to change the controller icons if you can because its a lot easier and keep it on Xbox mode

**Comment by epigramx** [comment]
> options for profile

oh I didn't know that option existed. it should be probably advertised more when the program is first run because it's such a common problem for a game to support USB directly but not Bluetooth.

I have not tested yet because currently I didn't have a game installed that needs it.

**Comment by Masamune3210** [comment]
Its rare that a game supports the DS4 correctly, games usually just fall back to the crappy default DirectInput interface, which lacks a lot of things, including vibration and button mappings that make logical sense. You would be surprised how little it comes up
