### ISSUE TITLE
Cannot change color and vibrate in DS4, but working fine on inputmapper 1.6

### ISSUE THREAD

**Issue by hideandseekstheorder** [Ryochan7/DS4Windows#2901]
when I try to use InputMapper, my PS4 Stick can be used to change the color of the stick and adjust the vibration, but on the DS4 it's not the case, and there is one of my PS4 Sticks that can adjust the color of the stick and adjust the vibration, please add the MAC address of my problematic stick

this is the log of my ps4 stick problem (image1)
![image](https://user-images.githubusercontent.com/24226435/230195211-abf825b8-a075-45f5-9bec-43eeefa1beb7.png)
image1

this is the log of my other ps4 stick working fine (image2)
![image](https://user-images.githubusercontent.com/24226435/230195877-e62a9b1e-fdcc-4a71-8479-db40a40ef22b.png)

i am using new 3.2.9 
![image](https://user-images.githubusercontent.com/24226435/230196213-85a68240-e158-4fad-8d6f-5a2f4ef0638c.png)

**Comment by hideandseekstheorder** [comment]
This is my controller mac address cant set controller color and controller vibration

Found Controller: 16:32:6E:6A:8B:19 (BT) (DS4 v.2).

**Comment by Ryochan7** [comment]
Pretty sure you are using a fake copycat controller. Maybe try to enable the **Copycat** setting under Settings > Device Options > Controllers and then re-connect your controller. Some fake controllers require workarounds since they do not work like a real first party Sony DS4.
