### ISSUE TITLE
Dualsense Edge battery level

### ISSUE THREAD

**Issue by ghost** [Ryochan7/DS4Windows#2909]
The battery level doesnt show up correctly. Im at 100% charge when plugged in after 4hours. When the controller is on Bluetooth, the battery  instantly drops to 87% and wont go past that.

Edit 1: The controller was updated to the latest firmware. still no change with the battery level.

Edit 2: Tried with a second Dualsense Edge controller with was updated from a PS5 instead of the Official pc updater from Sony, the problem still persist. Will try a 3rd controller soon.

Edit 3: Charge goes randomly from 100% to 87%, then back to 100% when plugged in, Bluetooth off.

**Comment by Masamune3210** [comment]
Please search for existing issues first before opening new ones.

**Comment by Watch251** [comment]
> h

I already search and there was no other posts.

**Comment by Masamune3210** [comment]
....I will do what I please within the rules given. If you already commented on the other issue, there is no need to open your own issue.

**Comment by Watch251** [comment]
I'm just going to block you. Go troll elsewhere.
