### ISSUE TITLE
Sensitivity

### ISSUE THREAD

**Issue by Eudritch** [Ryochan7/DS4Windows#2929]
The sensitivity of the Virtual Controller DualShock 4 and Xbox 360 differs; the DualShock 4 feels more natural, while the Xbox 360 feels like there's a multiplier. Please help, I'm having problems in a game that has a high deadzone from the DualShock 4 emulator, so I have to use the Xbox, but the sense is not good for competitive games.

**Comment by Ryochan7** [comment]
Ranges:
Xbox: [-32768, 32767]
DS4: [0, 255]

No duh there is a multiplier
