### ISSUE TITLE
Unability to set up deadzone precisely, i.e. 0.029666 for example

### ISSUE THREAD

**Issue by GeraltV47** [Ryochan7/DS4Windows#2931]
I miss very, very, VERY much precise deadzone and sensitivity setup possibility, i wont even mention that deadzone shouldn't be applied in 0-100 scale, just 0-128 scale as the pad axies have 256 bit potentionometers, imo its should look like, for example deadzone 3 bits into one side and adjustable axis negative or positive offset of deadzone, for example 0.001% to adjust sensitivity of first bit or just let for setup custom deadzone with many digits after the comma which should allow for manipulating the offset of the first bit, i found DS4W deadzone setting very inaccurate, in games, if there is only a built-in deadzone adjustment possibility then i use it, its though the only one game that i know that offers that, its TrackMania United Forever, where for my DualSense i set deadzone 0.029666 for thumbstick because on 0.029665 car turned without my intention, i know that sensitivity of curves can be set for example 0.376452, 0.213065, 0.78119, 0.7320698, im trying to set up my SIXAXIS profile for this game and all is fine except that deadzone setting, i got it now 0.05 because 0.04 is too small and i got strong feeling that 0.05 is too much, i need something between, i would start from 0.049 and then add next digits after the comma, i REALLY miss the set up posiibility of more precision settings, if its only possible to add this to DS4W then how long coding would take? i bet its 5 minutes for you :-)

**Comment by Ryusennin** [comment]
Not willing to doubt your experience, but I have serious doubts that 0.029666 is making any difference when even brand new DS4/DS5 start drifting after a few weeks of use and you need a whole 5% (if not more) to stabilize their dead zone. Sony analog sticks are notoriously crappy, there's a reason why Sony is facing an on-going lawsuit.

**Comment by Ryochan7** [comment]
I am calling BS on this. Considering each direction would have at most 128 units, that would make a 1% change roughly equal to 1.28 units. Considering the final value will be an integer, the number will be rounded to the closest integer; I would have chosen to floor the value but DS4Windows has always done rounding and there was no real reason to change that. You are not going to be able to feel a ~0.00033 value difference in almost any context.

The only change that could be made would be to no longer round the decimal percentage but use a floor operation instead. Also of note, DS4Windows saves the stick deadzone value as a measure of the short end of a stick axis (0-127 value); it is interpolated when applied to the longer end of the axis. That has always been the way the value has been represented in profiles.

**Comment by GeraltV47** [comment]
anyway i would like to see precise deadzone setting for allow for manipulate the first bit sensitivity offset, because i feel drastical difference betwen precise 0.029666 or with offset 0.029713 and between 0.03 and i see no sense to not adding that to ds4windows also the micromoves doing mouse emulation are very unprecise, i am almost unable to make headshot the way i do it on console games because of that when it reaches the first axis bit the sensitivity is about 1%, for headhots i would require like 0.3-0.5% which is one of the reasons why i created this issue even adjusting Bezier curve doesnt solve the first bit mouse emulation sensitivity, i also would be glad if you could add negative mouse offset function to decrease sens of first bit when emulating the mouse because as i said doing headshot was easier even on logitech profiler or xpadder and i dont plan to use these programs anymore when i have ds4w
