### ISSUE TITLE
special action to toggle hide ds4 controller.

### ISSUE THREAD

**Issue by shogunreaper** [Ryochan7/DS4Windows#294]
can you add this please.

**Comment by Ryochan7** [comment]
The mode change that DS4Windows performs to get extra data from the controller (touchpad, gyro, accelerometer) makes that option not feasible. Once a BT controller is connected to DS4Windows, the old DirectInput device is not usable unless an application has already opened a handle to the DirectInput device. There will be no input for the DInput controller. The only way to get the DInput version to work again when using a BT connection is to disconnect and re-connect the controller. If I remember correctly, this problem does not occur when using a USB connection.
