### ISSUE TITLE
Can't Install Ds4 Drivers

### ISSUE THREAD

**Issue by Lannnyy** [Ryochan7/DS4Windows#295]
When I open up Ds4 for the first time, it usually gives a popup that asks to install the drivers. Now, when I open it up or click "Controller/Driver Setup", my screen flashes black and nothing else happens. The logs read:

![image](https://user-images.githubusercontent.com/39604247/40516023-c3647de2-5f74-11e8-959c-81ff6e14a674.png)

I don't know what this means, and I couldn't find anything about it online. 
Thanks for helping.

**Comment by Ryochan7** [comment]
It looks like DS4Windows can see that an ScpVBus device exists since the popup does not appear. However, it seems like the device might be disabled. Have you checked the status of the Scp Virtual Bus Driver device in the Device Manager?

**Comment by Lannnyy** [comment]
I can't seem to find the Scp Virtual Bus Driver in my Device Manager. Is there any other way to check the status of this Driver?

**Comment by Ryochan7** [comment]
The device should be listed under System devices > Scp Virtual Bus Driver. You could possibly try InputMapper and see if you have any luck with it. Touchmote is one other application that I use on occasion, when playing with the Wiimote, that utilizes ScpVBus.

I have checked the driver check and install procedure within DS4Windows and it still works as intended.
