### ISSUE TITLE
Dualshock 3 controllers can't be toggled off separately like the others in the device options menu

### ISSUE THREAD

**Issue by dude98** [Ryochan7/DS4Windows#2953]
**Describe the bug**
it can't be toggled on and off separately from DS4 controllers like the dualsense, joycons, and pro controller can be.

**To Reproduce**
Start DS4Windows
Plug in Dualshock 3
Go to settings tab
Open device options
There's no "DS3 Support" checkbox
Toggling "DS4 Support" also enables/disables DS3 controllers

**Expected behavior**
They should be separated, because if your DS4 is already working in the game and you have someone who wants to use a DS3 but isn't working right, it'll be annoying to have to hide your DS4 from the game, and make two virtual ones (one for your DS4, and the other for the DS3) every time.

**Desktop (please complete the following information):**
 - Controller Make and Model:  Sony DS3 CECHZC2U
 - OS: Win 10 Home
 - DS4Windows Version 3.2.10

**Additional context**
More of a nitpick than anything, it's just weird that everything else was separated and this one controller type wasn't.

**Comment by Ryochan7** [comment]
Being able to disable DS3 detection was probably overlooked. I did not add DS3 support and I have barely tested it. Maybe it would be better off if DS4Windows did not try to detect a connected DS3 by default. Not sure if I will get around to changing it.
