### ISSUE TITLE
I dont find .exe

### ISSUE THREAD

**Issue by rainybecoding** [Ryochan7/DS4Windows#2955]
yeah, that

**Comment by Masamune3210** [comment]
You didnt try very hard, did you.....
![image](https://github.com/Ryochan7/DS4Windows/assets/1053504/b72a50f1-291a-4dce-a144-e482c4aaab27)
![image](https://github.com/Ryochan7/DS4Windows/assets/1053504/f3720a45-fe53-450c-a919-3d4267bbb28d)

**Comment by Ryochan7** [comment]
> You didnt try very hard, did you.....

He clearly downloaded the source code. Clicked first big green button (labelled **Code**) as opposed to checking under releases (like every other project on GitHub) or reading the README. Probably has plenty of viruses on his computer.
