### ISSUE TITLE
System.BadImageFormatException - Can't open DS4Windows

### ISSUE THREAD

**Issue by Susjin** [Ryochan7/DS4Windows#2973]
Description:
My Windows detected an error in the C: disk and automatically started and _chkdsk_ when I restarted.
After the correction, I noticed a few bugs in DLLs on some games, but got them working after a reinstall.
But, when I tried to open DS4 windows, got the following crash log:

![image](https://github.com/Ryochan7/DS4Windows/assets/20406827/96bacf02-916e-405c-8714-33733a7cf692)

So I downloaded the latest version of DS4Windows and extracted it in another folder. The program doesn't even open, no logs, no nothing. From the task manager, I can see that it opens and rapidly closes.

What am I missing?

**Comment by Masamune3210** [comment]
Look at what it's saying is corrupted. It's not DS4Windows, it's one of the system redistributables. Honestly, your best bet is probably just to back up your user data and reinstall windows. Who knows what else might be corrupted.

**Comment by Susjin** [comment]
Reinstalled the Microsoft .NET 6.0 Runtime Desktop and the 
Visual C++ 2015-2022 Redistributable. Got it working again!

Thanks for the help!
