### ISSUE TITLE
Program Crashes when no profiles are found

### ISSUE THREAD

**Issue by FrodoSynthesis05** [Ryochan7/DS4Windows#2976]
If the user were to delete all profiles and then try to click on the edit button, the program will inevitably crash. The program should alert the user that there are no profiles to edit and then prompt the user to create one.

**Comment by Ryochan7** [comment]
Should not happen under normal circumstances. I added a small safeguard to skip trying to open the Profile Editor in that case. Not going to worry about having a nag message box.

https://github.com/Ryochan7/DS4Windows/commit/9148deddda9014d9ac5d1a8d6add529ecc225012
