### ISSUE TITLE
Touchpad Click with Switch Pro controller

### ISSUE THREAD

**Issue by TheREALDownloader** [Ryochan7/DS4Windows#2977]
I'm using the 8bitdo ultimate bluetooth controller in switch mode, which is basically a Switch Pro controller.
I was using a DS4 controller for dolphin but when I try this one it is missing the touchpad click, my home button.
Any way to bind the screenshot button to the touchpad click ?
Already tried the "Capture" control, doesn't work for me

**Comment by Ryochan7** [comment]
It is possible to map any input button to DS4 Touchpad Click when using DS4 passthru. I have not tested it in a long time but it should still work; the code has it bound differently so the mapping is not dependent on an actual touchpad packet.
