### ISSUE TITLE
Pressing L2 is making Y axis move on the left stick

### ISSUE THREAD

**Issue by Ziexer** [Ryochan7/DS4Windows#298]
First off thank you for continuing the wonderful work of updating Ds4windows. ( I was using the last owner as my latest one since yesterday infact and was mentally prepared to lose my internet everytime i used it since it brakes it for me, after i updated to yours i fixed it after many years. Thanks again!! ) 
But aparently i stumble upon another problem, and that is as the title saids. By pressing L2 it triggers my left stick ass if i was moving it to the left, hence makes me move to the left while aiming. Quite frustrating i thought of lowering the stick sensitivity as a temporal fix or try to uninstall it completely to reinstall it but prefer to refer this bug to you instead. Please let me know if you need anything in specific, more info or pics.

**Comment by jonaaa20** [comment]
Look, I had a V2 DS4 with this problem, and... It was a hardware problem, when I used on my PS4, the same problem occurs so... If you have a PS4, test it, if it happens there, the problem isn't ds4windows but your DS4.

**Comment by Ziexer** [comment]
thanks for the reply! unfortunately i don't so i can't test it. :( 
ps: sorry for my English/punctuation

**Comment by fehmi1907** [comment]
Why don't you just connect the DS4 to your computer via USB without running DS4Windows? That should help you diagnose if it is a software vs hardware issue. You don't even need to run a game - game controller setup in control panel should suffice.

**Comment by Ziexer** [comment]
sorry for the late reply. 
update; i reinstalled windows, download and install ds4windows again.
unfortunately, i got a new problem now.. since the new patch update my internet speed goes down when i connect my controller( that problem happend with the jay2king version),  but i can confirm is does not do the L2 glitch with that version just the download speed lowers drastically like .01 mbps.

**Comment by Ryochan7** [comment]
I have a similar weird problem with my version 1 DS4. Moving LS around causes some minor activity with RS sometimes. This happens with the normal DirectInput controller so it is a weird quirk with the controller. Setting an appropriate dead zone for RS would work around the problem but it does make using sensitive mouse movement a problem.

The short version is that the problem is probably with the controller itself.
