### ISSUE TITLE
gamepad hd-060 works fine when playing a game , after leaving it the controller crash and when reconnecting the controller , it is paired but not connected ( i should restart the computer every time i leave a game ) 

### ISSUE THREAD

**Issue by Anonymey0** [Ryochan7/DS4Windows#2990]
gamepad hd-060 works fine when playing a game like AC Creed ( ubisoft connect) fall guys (epic games) dbx2 (steam), after leaving it the controller crash and when reconnecting the controller , it is paired but not connected ( i should restart the computer every time i leave a game ) OS: WIN 11

 1. connecting the gamepad to Bluetooth ( works fine)
 2 .Click on a game and play it
 3. leave the game
 4. controller CRASH
 5. after reconnecting the pc263 paired but not connected
 
before playing
![before](https://github.com/Ryochan7/DS4Windows/assets/137336540/44cd7684-865f-4466-9f12-848882377699)
after playing
![after](https://github.com/Ryochan7/DS4Windows/assets/137336540/87964a89-8769-4b3d-a611-5f798aa5b187)

hd-060 gamepad :https://www.alibaba.com/product-detail/Wireless-Elite-game-controller-for-PS4_60854500059.html
Brand: unknown
it considered as ds4 v2

**Comment by Ryochan7** [comment]
Does not sound like an issue with DS4Windows at all. Also that controller looks like cheap garbage. Seems like a case of buyer beware. Buy a real DS4 next time. I do not support knockoffs at all.
