### ISSUE TITLE
DS4 windows close when controller connected

### ISSUE THREAD

**Issue by roxyhardy** [Ryochan7/DS4Windows#2992]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots and Logs**
If applicable, add screenshots to help explain your problem. Also, please add the most
log file (ds4windows_log.txt) from the Logs folder in your DS4Windows config folder.

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: [e.g. Windows 10 Pro Build 2004]
 - DS4Windows Version [e.g. 3.0.3]

**Additional context**

**Comment by roxyhardy** [comment]
im using a ps5 controller could that be why

**Comment by Ryochan7** [comment]
No info given. Not even going to bother with this. Go away
