### ISSUE TITLE
Exception H.NotifyIcon_(<a long string of numbers>) DS4Windows

### ISSUE THREAD

**Issue by Luna-Nocturna** [Ryochan7/DS4Windows#2993]
**Describe the bug**
There was another ticket (https://github.com/Ryochan7/DS4Windows/issues/2880) which just got closed so I guess I attempt a new one. (I went with "Please reply in existing tickets instead of making a new one.") At least I can supply more information than the original poster:

Often during the shutdown process it hangs with a pop up notification with "Exception H.NotifyIcon_(<a long string of numbers>) DS4Windows" What may be related is I've turned off Fast Boot in Windows. By default Windows 10 has some hibernation-ish shut down so it boots faster but then a lot of caches aren't cleared. It also prevents Wake-on-Wan signals which I require for work so enabling that for me personally is not possible.

**To Reproduce**
1. Shut down the PC
2. See error during the "Shutting down" spinning circle

**Expected behavior**
PC shutting down without the error notification.

**Screenshots and Logs**
See attachment for log, it has nothing of relevance though, DS4Windows should already been closed at this point of the shutdown. Sscreenshot is hard as it's during shutdown.

**Desktop:**
 - DualSense CFI-ZCT1W
 - OS: Windows 10 22H2 19045.3086
 - 3.2.11 (and earlier)

**Additional context**

I guess at first my apologies for not having provided enough information, I wasn't the ticket creator so I wasn't sure how detailed I had to go. However as someone who has always promoted and even defended DS4Windows VS the hijacking Steam Controller it kind of stings being accused of gaslighting. I hope making a new topic, even though the same issue, at least clears my name on that accusation.

**Comment by Trihy** [comment]
Didnt experience this problem on builds .10 and .11. But I have fastboot on, or I guess so.

**Comment by Luna-Nocturna** [comment]
Hello, ever since I updated to 3.2.12 about 3 weeks ago I've not ran into this error again. (The patch notes did mention a change in the behaviour.)

So much thanks for looking into this and even more for fixing it.
