### ISSUE TITLE
Gyro fail

### ISSUE THREAD

**Issue by jinkazama82it** [Ryochan7/DS4Windows#2998]
**Describe the bug**
I continue to use  ver. 3.2.7 of DS4W because newer have issue with gyro functionality, don't change what option is selected, any option return a broken gyro position in games, more precisely if you turn the controller to the left the output of the gyro return the input of a full right until you reach a 90°, at 90° the gyro output immediately swap to left as intended.

this happens with the official Sony ds4 v2 and any version of DS4Windiws after the Ver.3.2.7
O.S. Windows 10 Ver. 22H2

**Comment by Ryochan7** [comment]
Filing under works for me
