### ISSUE TITLE
Possibly add device support chooser window upon first launch

### ISSUE THREAD

**Issue by Ryochan7** [Ryochan7/DS4Windows#2999]
Apparently there is a big problem that people are not expecting for support for certain device types to be an opt-in choice. Under normal circumstances, it would be easier for device support to be enabled by default but Steam Input makes that impossible as, last I knew, it enables everything by default. Because of that decision by Valve, there would be a guaranteed device conflict issue between the two mappers.

**Comment by Masamune3210** [comment]
afaik, yes, steam by default will have all of its handlers enabled unless explicitly disabled
