### ISSUE TITLE
Toggle L2/R2 Buttons/Axis

### ISSUE THREAD

**Issue by Mako88** [Ryochan7/DS4Windows#300]
Would it be possible to have a setting that would allow you to toggle L2/R2 between triggering an axis, a button, or both? Currently they always default to both, which causes some games to pick up the button instead of the axis (or vice-versa).

**Comment by Ryochan7** [comment]
That is a limitation of the driver used for the DS4 controller. I am not sure if emulating a virtual DS4 controller would work around that problem. As it is, I don't think ViGEm has any way to create an arbitrary DirectInput controller similar to how vJoy works.
