### ISSUE TITLE
DS5 with latest firmware (0356) not connecting in 3.2.12 of DS4Windows

### ISSUE THREAD

**Issue by Pancres** [Ryochan7/DS4Windows#3003]
I tried to connect my ds5 controller, how it used to work, but now it doesn't work.
with hidhide installed and DS4W connected it didn't work and gamepad tester did detect my controller after turning off hidhide
![image](https://github.com/Ryochan7/DS4Windows/assets/138213159/7a704211-0fab-45f2-b919-d03b86672565)
![image](https://github.com/Ryochan7/DS4Windows/assets/138213159/eec9dfbf-d4e1-40b5-a439-c9ad2188de3c)

**Desktop**
 - Controller Make and Model: Sony DS5 
 - OS: [Windows 11 Home 21H2]
 - DS4Windows Version [3.2.12]

**Comment by mguc** [comment]
I'm having exactly the same issue.

**Comment by mguc** [comment]
Hey have you tried enabling the "DualSense Controller Support" under "Settings"->"Device Settings"? This worked for me. It seems that this option is not enabled by default:
![grafik](https://github.com/Ryochan7/DS4Windows/assets/1260390/f2a3284b-dd26-462e-80fd-8e151efef833)

**Comment by Rachid90** [comment]
> Hey have you tried enabling the "DualSense Controller Support" under "Settings"->"Device Settings"? This worked for me. It seems that this option is not enabled by default: ![grafik](https://user-images.githubusercontent.com/1260390/251671059-f2a3284b-dd26-462e-80fd-8e151efef833.png)

Thank you very much. It worked for me.

**Comment by Ryochan7** [comment]
Okay. Was going to update my DualSense later and try it but it looks like the issue was resolved. Probably should still update my DualSense anyway just in case. I need to get around to finally changing the DS4Windows first launch routine to give device support options.

**Comment by Ryochan7** [comment]
Got the 0356 firmware installed on my DualSense. Confirmed to work fine on my end.

**Comment by ppperamaki** [comment]
had to login just to say thank you. I've been battling with this for days lol

> Hey have you tried enabling the "DualSense Controller Support" under "Settings"->"Device Settings"? This worked for me. It seems that this option is not enabled by default: ![grafik](https://user-images.githubusercontent.com/1260390/251671059-f2a3284b-dd26-462e-80fd-8e151efef833.png)

**Comment by Ryochan7** [comment]
This should not be so much a problem in the future. Added a window on first launch to allow enabling controller support for non-DS4 controllers.

https://github.com/Ryochan7/DS4Windows/commit/aacc79544c58cd60033b8dd33f995a9546df408f

**Comment by artlp** [comment]
There could be some sort of a bug, because I've had it enabled, and used everything for a year without any hardware/software changes and yesterday my controller just stopped being seen by DS4W. This option helped me reenable it.

**Comment by Vladgina** [comment]
> There could be some sort of a bug, because I've had it enabled, and used everything for a year without any hardware/software changes and yesterday my controller just stopped being seen by DS4W. This option helped me reenable it.

Maybe this happened due to the bug I'm having: #2728

All my settings reset (The options on the SETTING tab only, not every setting like profiles), including that option. Perhaps your other settings are default so you didn't notice that they reset.

@Ryochan7 having the option to select controllers in that spot seems odd to me. It feels very hidden. Not obvious at all.

**Comment by Ryochan7** [comment]
> @Ryochan7 having the option to select controllers in that spot seems odd to me. It feels very hidden. Not obvious at all.

Works almost the same way in Steam Input yet nobody complains to Valve. It is literally Valve's fault that non-DS4 devices are not opened in DS4Windows by default.
