### ISSUE TITLE
Ghost input bug with DS5 on version 3.2.12

### ISSUE THREAD

**Issue by CreepyGiantz** [Ryochan7/DS4Windows#3010]
With the DS5 connected via bluetooth, on version 3.2.12. At random intervals it looks like there are random inputs to the left. Input time isn't consistent. Can't identify what triggers it.

As far as I'm aware, it only happens when the controller is connected. Doesn't matter whether it's actually in use. It happened while using Keyboard and Mouse, but the controller was still connected over bluetooth. I have not tested further whether the issue persist when using a cable as it took a while to initially find which program was causing this.

 - Sony Dualsense 5
 - Windows 11 Pro
 - DS4Windows Version 3.2.12

Issue happened for a couple days, and when downgrading to version 3.2.11, the issue seems resolved.

**Comment by andreycout** [comment]
You probably have stick drift, unfortunately. It's very common on the DualSense.

**Comment by CreepyGiantz** [comment]
> You probably have stick drift, unfortunately. It's very common on the DualSense.

It counters my input to the right. And sometimes even overwrites it. For instance I'm holding down right on my joystick yet somehow it goes left. Stick drift would not explain this behavior.

**Comment by andreycout** [comment]
> > You probably have stick drift, unfortunately. It's very common on the DualSense.
> 
> It counters my input to the right. And sometimes even overwrites it. For instance I'm holding down right on my joystick yet somehow it goes left. Stick drift would not explain this behavior.

Your description is pretty consistent with drift symptoms actually. I've had two brand new DualSense controllers get drift each with less than 2 months of use. The exact way in which the potentiometer will fail is very unpredictable, but it will at times override directions completely, not simply add an arbitrary direction

If you still think it's a DS4 issue, I'd suggest just uninstalling and playing a game that has native support for some days and see if it happens again. The thing about drift is that, unless the potentiometer is VERY SERIOUSLY damaged, it will only present symptoms at random times, not all the time, so it might be hard to diagnose.

If it's still under warranty, I'd suggest asking Sony for a replacement. I did and they got me a new one, even though it eventually started getting drift again...

**Comment by CreepyGiantz** [comment]
> > > You probably have stick drift, unfortunately. It's very common on the DualSense.
> > 
> > 
> > It counters my input to the right. And sometimes even overwrites it. For instance I'm holding down right on my joystick yet somehow it goes left. Stick drift would not explain this behavior.
> 
> Your description is pretty consistent with drift symptoms actually. I've had two brand new DualSense controllers get drift each with less than 2 months of use. The exact way in which the potentiometer will fail is very unpredictable, but it will at times override directions completely, not simply add an arbitrary direction
> 
> If you still think it's a DS4Windows issue, I'd suggest just uninstalling and playing a game that has native support for some days and see if it happens again. The thing about drift is that, unless the potentiometer is VERY SERIOUSLY damaged, it will only present symptoms at random times, not all the time, so it might be hard to diagnose.
> 
> If it's still under warranty, I'd suggest asking Sony for a replacement. I did and they got me a new one, even though it eventually started getting drift again...

It appears you were right as the issue keeps popping up, although not as prominent as it first was. But that very well could be coincidence so I will be returning it for repairs.
