### ISSUE TITLE
A small request

### ISSUE THREAD

**Issue by Jenuca** [Ryochan7/DS4Windows#3012]
请问能不能把Ｌ２（LT）和Ｒ２（RT）作为陀螺仪触发键时的死区改为０，或者死区可调？我习惯用两个扳机键来触发陀螺仪，现在的情况应该是在大约５０％时才能触发，这在同时把扳机分配为两段式功能键时会有些不便，我觉得就像Ｓｔｅａｍ的设计那样会比较好
![ds4w](https://github.com/Ryochan7/DS4Windows/assets/33145871/b661753d-025f-4675-8e75-0f18020fbe30)

**Comment by Ryochan7** [comment]
Steam Input and reWASD work the same way when it comes to using triggers to activate gyro. For now, I am still going to consider such a feature as bloat and not worry about it.
