### ISSUE TITLE
gyro drift

### ISSUE THREAD

**Issue by Newtypeman** [Ryochan7/DS4Windows#3013]
**Describe the bug**
When reconnect the controller while using ryujinx, cemu, and yuzu, a gyro drift phenomenon occurs.

**To Reproduce**
1. play with ryujinx, cemu, yuzu.
2. Reconnect Dualshock4

**Expected behavior**
Gyro drift occurs

**Screenshots and Logs**

**Desktop (please complete the following information):**
 - Controller Make and Model: CUH-ZCT1K
 - OS: WIN10
 - DS4Windows Version 3.2.9

**Additional context**

Additionally, tests show that this does not happen when you are not using ds4windows.

**Comment by Ryochan7** [comment]
> Additionally, tests show that this does not happen when you are not using ds4windows.

X to doubt
