### ISSUE TITLE
Feature Request: Adjustable Gyro Activation Input Value

### ISSUE THREAD

**Issue by edible-funk** [Ryochan7/DS4Windows#3015]
When using either L2 or R2 as the trigger to enable gyro, the gyro will not engage until the trigger's input value reaches 130. Would it be possible to make this value adjustable, to have the gyro enable at a custom input value set by the user?

**Comment by Ryochan7** [comment]
Works the same in Steam Input and reWASD yet nobody complains. Will only complain when it comes to me. Not going to benefit me at all so no.

**Comment by edible-funk** [comment]
Well that's not at all how steam input works, it activates the gyro much earlier.  I guess I appreciate the honesty, if not the hostility.
