### ISSUE TITLE
Gyro Failing on Pro Controller at random

### ISSUE THREAD

**Issue by CherenTheCat** [Ryochan7/DS4Windows#3020]
**Describe the bug**
While using a Pro Controller with Gyro Passthru enabled, when initially connecting, the gyro works fine, but after less then 5 minutes, the gyro data seems to stop being received entirely, as the gyro gets locked at 0, 0, 0. The only way to fix it is to reconnect the controller, which makes it work for about 5 minutes again.

**Expected behavior**
I expect the gyro output to remain functional.

**Screenshots and Logs**
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/12088752/ds4windows_log.txt)
![image](https://github.com/Ryochan7/DS4Windows/assets/18288725/391b0972-94c0-412b-bafc-280a69bbcfa9)
Gyro functioning, at 3:30 PM
![image](https://github.com/Ryochan7/DS4Windows/assets/18288725/2e6ead3b-c6f5-45e7-af06-61fec30d5ee2)
Gyro suddenly not working, at 3:31 PM.

**Desktop (please complete the following information):**
 - Controller Make and Model: Nintendo Switch Pro Controller
 - OS: [e.g. Windows 11 Pro Build 21H2]
 - DS4Windows Version [e.g. 3.2.12]

**Additional context**
This is specifically being used for Fortnite, but it happens regardless of if the game is open.

**Comment by Ryochan7** [comment]
Filing this under works for me
