### ISSUE TITLE
Crash when Connecting DS4

### ISSUE THREAD

**Issue by VorgonBattlecruiser** [Ryochan7/DS4Windows#3022]
**Describe the bug**
DS4windows closes apbruptly whenever i connect either of my two DS4's.
Used to work yesterday, but doesnt anymore. No windows- or DS4windows updates since.

**To Reproduce**
1. start DS4
2. Connect Gamepad either wired or wirelessly
3. DS4windows instantly shuts down

**Expected behavior**
For it to run normally without shutting down when gamepads are connected.

**Screenshots and Logs**
If applicable, add screenshots to help explain your problem. Also, please add the most
log file (ds4windows_log.txt) from the Logs folder in your DS4Windows config folder.

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2E)
 - OS: [e.g. Windows 10 Enterprise Build 19045]
 - DS4Windows Version [e.g. 3.2.12]

**Additional context**
[ds4windows_log_20230722.3.txt](https://github.com/Ryochan7/DS4Windows/files/12135352/ds4windows_log_20230722.3.txt)
[ds4windows_log_20230722.4.txt](https://github.com/Ryochan7/DS4Windows/files/12135353/ds4windows_log_20230722.4.txt)
[ds4windows_log_20230722.5.txt](https://github.com/Ryochan7/DS4Windows/files/12135354/ds4windows_log_20230722.5.txt)
[ds4windows_log_20230722.6.txt](https://github.com/Ryochan7/DS4Windows/files/12135355/ds4windows_log_20230722.6.txt)
[ds4windows_log_20230722.7.txt](https://github.com/Ryochan7/DS4Windows/files/12135356/ds4windows_log_20230722.7.txt)
[ds4windows_log_20230722.8.txt](https://github.com/Ryochan7/DS4Windows/files/12135357/ds4windows_log_20230722.8.txt)
[ds4windows_log_20230722.9.txt](https://github.com/Ryochan7/DS4Windows/files/12135358/ds4windows_log_20230722.9.txt)

**Comment by Ryochan7** [comment]
Something in the profile (suspecting controls bindings) does not seem to be set but no profile was uploaded here. It does not really matter at this point anyway. If it has not been fixed by now then it will likely never get fixed.
