### ISSUE TITLE
Cannot export/import Special Actions

### ISSUE THREAD

**Issue by raeleus** [Ryochan7/DS4Windows#3030]
**Describe the bug**
When exporting a profile and importing it on a fresh install, the "Special Actions" are not copied. Only the default "Disconnect Controller" is visible.

**To Reproduce**
1. Open the profiles menu and click a profile that has Special Actions. Select "export" from the first computer
2. Create a fresh install of DS4Windows on a new computer.
3. Go to profiles and select import. Choose the exported xml from step 1.
4. Edit the profile and look at the special actions menu.

**Expected behavior**
All profile settings, including special actions, should be exported to the xml

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DualSense Edge
 - OS: Windows 10 Pro 21H2
 - DS4Windows Version: 3.2.13

**Comment by Ryochan7** [comment]
Special Actions are a separate entity than Profiles. Special Actions are saved per application config rather than per profile. Profiles only save the name of a Special Action so DS4Windows can find the associated special action and use it.

It is working as intended.
