### ISSUE TITLE
developer licnese

### ISSUE THREAD

**Issue by maddog7051** [Ryochan7/DS4Windows#3031]
keep getting the developer license expired.  Happens every time i open ds4.  I am thinking also it happens when i first log on to my laptop.

- Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U): PS 4 dual shock
 - OS: [e.g. Windows 10 Pro Build 2004] : Windows 11 home build 22621.1992
 - DS4Windows Version [e.g. 3.0.3]  3.2.13
**Describe the bug**

**Additional context**
![IMG_3055](https://github.com/Ryochan7/DS4Windows/assets/140890548/1d37bf2b-de44-414b-9457-3d61804babf3)
![IMG_3054](https://github.com/Ryochan7/DS4Windows/assets/140890548/49ba3aea-24ca-46b8-8e03-4e66e6b9f656)

**Comment by Masamune3210** [comment]
This dialog has nothing to do with DS4Windows. I'm not sure what it's from, but I can tell you with certainty that it's not this.

**Comment by maddog7051** [comment]
Thank you for the quick reply.  


Sent from Yahoo Mail for iPhone


On Saturday, July 29, 2023, 07:27, Masamune3210 ***@***.***> wrote:




This dialog has nothing to do with DS4Windows. I'm not sure what it's from, but I can tell you with certainty that it's not this.
