### ISSUE TITLE
First Launch

### ISSUE THREAD

**Issue by tofik45** [Ryochan7/DS4Windows#3035]
First Launch

.NET Runtime x64
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.16-windows-x64-installer
.NET Runtime x86
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.16-windows-x86-installer

* Added Resource workaround in project file to remove then add files. Performance bump. .NET is a weird beast.
* Added missing JoyCon controls for Special Actions Unload Triggers
* Added remainder cutoff for Touchpad Mouse and Gyro Mouse
* Added FirstLaunchUtilWindow. Currently used to specify which devices the mapper should read
* Added extra attribution for DsHidMini project in first launch window
* Change single app instance check to use EventWaitHandleAcl.TryOpenExisting
* Added profile switch notifications for Auto Profile system
* Added implicit Default theme logic. Have default app theme change based on Windows app color setting
* Prevent lock recursion in OutputSlotManager if ViGEmFailure is encountered
* Added Vietnamese language. Contribution by **taolatao147**

<hr /><em>This discussion was created from the release <a href='https://github.com/Ryochan7/DS4Windows/releases/tag/v3.2.13'>Version 3.2.13</a>.</em>

_Originally posted by @Ryochan7 in https://github.com/Ryochan7/DS4Windows/discussions/3024_

**Comment by Ryochan7** [comment]
Nani?
