### ISSUE TITLE
[Feature] Option to Prevent DS4Windows from including itself in the HidHide Application list.

### ISSUE THREAD

**Issue by NFaR31** [Ryochan7/DS4Windows#3037]
Hello, DS4Windows is _awesome_, but in my case I only use it for a few specific programs (since most of them detect my controller without problems).
 
So to make things easier, I use HidHide with the _Inverse application cloak_ box checked.
This allows me to turn the Applications list into a neat little blacklist, where none of the programs added to it can detect my physical controller.

**Describe the bug**
I have the impression that DS4Windows automatically adds itself to the HidHide Applications list (which prevents DS4Windows from reading my controller, since I have the option above on).

Because of this, I am left with a futile workaround:
Manually remove DS4Windows from the HidHide Applications list after every DS4Windows boot).

**To Reproduce**
1. Open HidHide.
2. Clear all entries in the Aplications list.
3. Activate the _Inverse application cloak_ option.
3. Open DS4Windows.
4. See how DS4Windows has included itself in the HidHide Applications list.

**Expected behavior**
DS4Windows should not be in the HidHide Applications list without user approval.

**Desktop**
 - Controller Make and Model: Original Nintendo Switch Pro Controller
 - OS: Windows 10 Pro Build 22H2
 - DS4Windows Version: 3.2.13

**Additional context**
That is why I was wondering if it would be possible to add an option to DS4Windows that prevents its automatic inclusion in the HidHide Applications list.

Thank you very much and sorry for the inconvenience.

**Comment by Ryusennin** [comment]
Here's another solution.

You could make two profiles: a default DS4 (passthrough) one and a XInput one. You would assign the latter to your specific list of games through the auto-profiles tab. Thus no need to disable HidHide or invert the cloaking process.

**Comment by CourageT3** [comment]
Hi.
I've been running into this problem for a while now.

I thank Ryusennin for his suggestion, but I think the ideal would be not to rely too much on these kind of workarounds, and that DS4W would officially support the Inverted application cloak option of HidHide without conflicts, as NFaR31 said.

Personally I only need one xinput profile, and I would like to keep it as follows.

**Comment by Ryochan7** [comment]
HidHide support has not been changed much since its initial integration. I am not even sure **Inverse application cloak** was an option back then. It should not be that hard to check for that setting at startup and skip checking the HidHide whitelist in that case. Just would need to check what the IOCTL code for that setting would be in the driver itself.

I am pretty sure the call would cleanly fail on older versions of HidHide so a change should not affect people still using an older version of the HidHide driver.

**Comment by Ryochan7** [comment]
Added the check in and confirmed it reads the setting made in the HidHide client. Should be good enough

https://github.com/Ryochan7/DS4Windows/commit/a2c30810eb6564b8989dcc379741d2faf02d5a7c
