### ISSUE TITLE
direct input controller support?

### ISSUE THREAD

**Issue by HighPingTek** [Ryochan7/DS4Windows#3040]
Is it possible to add support for direct input controllers? I can't find quality alternatives like ds4windows

**Comment by Ryochan7** [comment]
I think this has been discussed before but I am not completely sure. It would technically be possible but I am not sure if it would be worth spending the time to get working. The biggest technical hurdle would be having a way to map a generic Direct Input controller to a DS4 so the mapper can work. The easiest way to do that would likely be to use the mapping strings from the SDL_GameControllerDB project and use the SDL 2 GameController spec; Steam Input uses a similar approach for its generic Direct Input controller support.

Obviously that approach would only allow direct button and axis translations with no access to any advanced features that a controller might have available.

https://github.com/gabomdq/SDL_GameControllerDB
