### ISSUE TITLE
Issues with motion sensors on 8bitdo Ultimate BT

### ISSUE THREAD

**Issue by mrrobboss** [Ryochan7/DS4Windows#3043]
The gyro seems to work for the first few seconds on connect, but as soon as it reads the battery, motion controls give up.

I am trying to connect a 8bitdo Ultimate BT controller (Switch pro controller) and emulate as a PS4 controller, it reads motion controls on connect for a second and then stops reading any motion suddenly. The rest of the inputs work fine though. Im not sure how to  give any logs on it so if anyone got any advice for that please respond with some

**Comment by Ryochan7** [comment]
If other input is still being registered then I doubt that having the logs would help diagnose the problem. Would likely need to debug the program as it is running in Visual Studio to find out what is wrong. Using a real Switch Pro controller still works fine on my end.

**Comment by Ryochan7** [comment]
People expect me to shell out a lot of money for a whole game controller collection when I cannot even afford groceries. No help from people asking for a resolution either.
