### ISSUE TITLE
Switching profile to a Low-Lag profile without Output data don't reduce input lag until i disconect reconnect.

### ISSUE THREAD

**Issue by nixxou** [Ryochan7/DS4Windows#3044]
I have two profile, a default one, and a LowLag.
On the lowlag profile, i have uncheck output data.

If i connect my gamepad with the Default profile, i get around 8ms lag.
If i do the same with the low lag profile, i'm around 3 or 4.

But, if i connect as Default and i switch profile to LowLag, i have still 8ms lag.
The only way to get the benefits is to disconect and reconnect.

https://youtu.be/2_ZXSQKegbE

**Comment by Ryochan7** [comment]
The disable output data option is only supposed to be enabled if you encounter unknown frequent disconnects mainly due to rumble (mainly 3rd party knockoff controllers). As it is, the option is working as intended.
