### ISSUE TITLE
Lightbar changing to full light blue if PS button is pressed on DS4

### ISSUE THREAD

**Issue by TacticalTurtleneck** [Ryochan7/DS4Windows#3045]
This is a new problem for me that started a couple of weeks ago. Whenever I press the PS button the lightbar changes to full light blue instead of the profile colour and stays that way until I change the colour to custom and back to profile colour to reset it. This is undesirable because the light is very distracting and noticeably drains the battery.

**To Reproduce**
Press the PS button.

**Expected behavior**
Before this problem started, pressing the PS button did not change the lightbar colour.

**Log**
[ds4windows_log_20230811.2.txt](https://github.com/Ryochan7/DS4Windows/files/12321899/ds4windows_log_20230811.2.txt)

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2E)
 - OS: Windows 10 Home
 - DS4Windows Version : 3.2.13

**Additional context**
The PS button is crucial and cannot be avoided.

**Comment by Masamune3210** [comment]
I mean, crucial is pushing it, but ok. Do you have HidHide properly set up and enabled? Sounds maybe like you have two programs trying to control the controller at once

**Comment by TacticalTurtleneck** [comment]
Thanks for replying.

Well, yeah, the PS button is crucial to my controller's functionality. It is the 'shift' button for all my special actions and I use it for toggling fullscreen on Kodi.

You are definitely on to something. Steam seems to be the culprit. It has never been a problem before. Valve must of changed something on their end. I've never had a need for HidHide before so I haven't installed it. I'll play around with it and see if it can fix my problem.

**Comment by TacticalTurtleneck** [comment]
I looked into HidHide. I don't want to hide my controller from Steam so that's a bust. I think I'll have to just stop Steam from starting with Windows so it doesn't foul my desktop experience.

Or can I hide my DS4 input from Steam from within DS4windows? That way it's hidden for some controller profiles and not others? eg. Mouse and keyboard profile hides dinput and my PS4 and Xbox profiles unhide dinput and xinput respectively? Unlikely, but I thought I'd ask.

**Comment by Masamune3210** [comment]
The hide function in ds4windows itself rarely ever works, which is why HidHide is pushed so much to begin with. Unfortunately, the best solution really is to just not have ds4windows and steam running at the same time if you don't want to deal with HidHide

**Comment by TacticalTurtleneck** [comment]
Thanks.

**Comment by Ryochan7** [comment]
> I tried HidHide. I don't want to hide my controller from Steam so that's a bust. I think I'll have to just stop Steam from starting with Windows so it doesn't foul my desktop experience.

That is Steam's doing. Steam will still try to put the controller in DS4 mode even if you have **PlayStation Configuration Support** disabled in Steam Input. Part of that process also causes the lightbar color to change.
