### ISSUE TITLE
Workaround for non-exclusive mode

### ISSUE THREAD

**Issue by Mister-Curious** [Ryochan7/DS4Windows#3048]
Over the years of using DS4Windows I have found it best practice to start it before any other program that might hook into the controller. For example, I always start DS4Windows before starting Steam, but there are times when I forget to do this, and the result is that I can not use exclusive mode. 

What I have to do in this situation is to close all programs and exit Windows (log off), and log back in again. If there aren't that many programs open this is no big deal, however there are times when I have multiple projects on the go and closing everything and logging off, then opening everything back up again is a real time-waster. 

So what I am wondering is if there is a way to sever this hook that happens with Steam, even after I exit Steam? I'd like to be able to reconnect to DS4Windows in exclusive mode without having to log off. Is there some Windows process or service that I can restart that will reset the handshake with Windows and my controller?

Thank you!

**Comment by Kanuan** [comment]
Do not use the "hide ds4 controllers". It's prone to fail. Instead, install and configure HidHide.

https://circumspector.github.io/DS4WDocs/guides/solving-double-input/

**Comment by Mister-Curious** [comment]
Thank you so much. I have seen this around for a while, but never knew how well it works to just block out other apps from taking control of the controller connection. This is absolutely perfect.
