### ISSUE TITLE
DS4Windows does not run since 7/24 update

### ISSUE THREAD

**Issue by Moltresrider** [Ryochan7/DS4Windows#3051]
I opened DS4Windows on my Windows 7 PC after not using it for several weeks and it told me that there was an update.

I let the update download and install and instead of running after the update downloaded, it did not.

Double clicking the DS4Windows exe file does not run the program either.

Looking into this, I open task manager only to find that when I click the exe to run DS4Windows, it only opens as a process for a few seconds before the process self terminates.

This occurs every time I try to run DS4Windows. Restarting PC does not fix the issue. 

The date modified on the most recent files in the directory is 7/24/2023 and so I figure that is the date of the update. 

It appears that that is a broken update that simply does not run.

**Comment by Ryusennin** [comment]
Which version were you previously using?

The last functional version for Win7 is 3.0.6 (it was the last one still supporting HidGuardian). It was released two years ago.

**Comment by Ryochan7** [comment]
There is nothing to do without the Logs included in the Logs folder.

As it is, Windows 7 has not been supported for a long time by Microsoft nor the ViGEm project drivers. Windows 7 support has not been tested in a long time and there has been no reason to worry about running a Win 7 VM; too bad that my old PC does not have enough RAM to run Win 10 in a VM for testing. There are only a couple of significant changes between DS4Windows 3.2.12 and version 3.2.13: one minor locking issue and the use of EventWaitHandleAcl.TryOpenExisting (used for single app instance check).

**Comment by Ryochan7** [comment]
Not sure it would matter but hopefully the following commit fixes things on your end. Not sure when I will get around to pushing a new DS4Windows release with the change.

https://github.com/Ryochan7/DS4Windows/commit/9391e23232158221ee3106370d92495fa3fe60bd

**Comment by Ryochan7** [comment]
No update
