### ISSUE TITLE
 DS4Windows.exe the app starts and closes after 3 seconds

### ISSUE THREAD

**Issue by Dovegs** [Ryochan7/DS4Windows#3053]
**Describe the bug**
when running the DS4Windows.exe the app starts and closes after 3 seconds

**To Reproduce**
1. Go to folder
2. Click on DS4Windows.exe
3. program started
4. waiting ~3 seconds
5. close

**Expected behavior**
start and normal work programm

**Screenshots and Logs**
If applicable, add screenshots to help explain your problem. Also, please add the most
log file (ds4windows_log.txt) from the Logs folder in your DS4Windows config folder.

Desktop:
 - Controller Make and Model: Sony DS4 v.2
 - OS: Windows 10 Pro 19045.2965
 - DS4Windows Version 3.2.13_x86

**Additional context**
PS: Runtime installed

**Comment by Dovegs** [comment]
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/12337447/ds4windows_log.txt)

**Comment by Dovegs** [comment]
Never mind. I fixed that. if someone has the same error, then you need to allow the rights for the user to all folders individually in this path: 'C:\Users\"name user"\AppData\Local\Temp\Costura\A82D679D82243148DCCFC699695DB1F1\32'

**Comment by Ryochan7** [comment]
Not sure why you lock down the AppData folder for your user; that is not default Windows behavior. The problem stemmed from the ViGEm.NET library as that uses Costura to temporarily extract the C++ library that is used to interface with the ViGEmBus driver.

**Comment by Dovegs** [comment]
> Not sure why you locked down the AppData folder for your user; that is not default Windows behavior. The problem stemmed from the ViGEm.NET library as that uses Costura to temporarily extract the C++ library that is used to interface with the ViGEmBus driver.

I didn't lock /appdata/. /costura/ and other folders in it were locked by default
