### ISSUE TITLE
BUG load a profile maybe rewrite the old one

### ISSUE THREAD

**Issue by syakiba** [Ryochan7/DS4Windows#3054]
**profile will be covered after loading new profile**

**To Reproduce**
1. Go to 'special actions - new action'
2. Click on 'L3,TiltUp' - 'load a profile' - 'name_of_one_profile' - 'set unload Trigger' - 'L3,TiltUp' - 'save' - 'accept' - 'save profile'
3. execute 1st'L3+TiltUp' - 2nd'L3+TiltUp'
4. See error : 
   [1st] the info on the bottom of DS4Win tells me it changed to the profile which I specified **AND all the setting of the last profile is the same as the specified profile**
   [2nd] nothing happened and I cant find any way to recover my profile, I missed it.

**Expected behavior**
[1st] it will change to the profile which I specified 
[2nd] It will change back to the precedent
every profile need to be exclusive

**Desktop (please complete the following information):**
 - DS4
 - Win10 21H2
 - DS4Windows Version 3.2.13

**Comment by Ryochan7** [comment]
1. I have never liked the idea of temp profiles used for the special actions and the auto profiles system. Having two conflicting profile loading systems is not a good idea. Although, there was no personal need to mess around and change the behavior so I never bothered to change it; something would probably go wrong if I tried.

2. You cannot use the same button combination for the trigger as well as the unload trigger. The unload trigger will just get executed immediately after the profile switch from the regular trigger. In effect, the original profile will always be used.

**Comment by syakiba** [comment]
> 1. I have never liked the idea of temp profiles used for the special actions and the auto profiles system. Having two conflicting profile loading systems is not a good idea. Although, there was no personal need to mess around and change the behavior so I never bothered to change it; something would probably go wrong if I tried.
> 2. You cannot use the same button combination for the trigger as well as the unload trigger. The unload trigger will just get executed immediately after the profile switch from the regular trigger. In effect, the original profile will always be used.

OK I see. Thanks for your description and idea!
