### ISSUE TITLE
Can't Pair PS4 Controller After Install

### ISSUE THREAD

**Issue by UnitedDugout27** [Ryochan7/DS4Windows#3057]
**Describe the bug**
I am unable to pair my PS4 controller after installing the ViGEmBus driver.

**To Reproduce**
I'm able to successfully pair my controller to this particular PC, prior to installing that driver. After the driver is installed, I get an error saying that "we didn't get any response from the device. try connecting again."

I've tried the same exact Windows build on other computers (Intel® Compute Stick STK2m3W64CC) and had no issues. The Bluetooth adapter and driver that I have is realtek. driver date: 11/3/22/ driver version 1.9.1051.3010. I believe there's some type of incompatibility with the Bluetooth adapter / driver and the ViGEmBus driver that DS4Windows uses. 

**Expected behavior**
My ps4 controller should pair with my PC.

**Screenshots and Logs**
none

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: Windows 10 LTSC_1809 & Windows 10 Pro_22H2
 - DS4Windows Version 3.2.13

**Additional context**

**Comment by Kanuan** [comment]
the vigembus driver does not directly communicate in any way, shape or form with the real controllers you are using, neither via cable nor via bluetooth, so it's almost impossible that having the vigembus driver installed could cause issues with Windows' Bluetooth

**Comment by UnitedDugout27** [comment]
All I know is, before installing the vigembus driver, I can pair my controller, then after it is installed, I can't.

**Comment by Ryochan7** [comment]
I have never experienced that with the ViGEmBus driver. If anything, I would think that the HidHide driver would be the package more likely to cause a problem like this as it works as an HID filter driver. I believe I have heard DSX users bring up similar issues but that also uses both ViGEmBus and HidHide. Not much that can be done without more info though.

Also, probably going to be stuck with the current state of ViGEmBus regardless. The move from the old ScpVBus driver years ago was almost pointless except for Windows 11 users.
