### ISSUE TITLE
DS4 V2 Audio problems over USB

### ISSUE THREAD

**Issue by webodan** [Ryochan7/DS4Windows#306]
Hello,

I've experienced problems using the latest public release of this program with my DS4 V2 connected to a USB3 hub and wired headphones. Audio randomly stops working while ingame and I need to alt tab and click the speaker icon in my task bar so the audio will come back. Any suggestions?

Thanks in advance.

**Comment by Ryochan7** [comment]
I am hoping that the latest change to the source code fixes the problem you might be having. There was an issue with output reports being constantly sent for USB and SONYWA connections when not needed. Maybe the volume level was being reset at some point.

I have not used headphone support in a few weeks as I have not spent much time running Windows. I will test headphone support later tonight and see if I run into any problems.

**Comment by webodan** [comment]
Thanks for your swift reply! Let me update on my issue:

It didn't happen in any other game except for Resident Evil Revelations, what kept happening was that as i pressed the buttons during gameplay it kept switching from "keyboard controls" to "controller controls". It seems this game has compatibility problems with your fork of DS4Windows. It does work MUCH better than the older, original version, as in the case of that one, I couldn't even use the analog sticks (they were mapped improperly) and also, during the usage of the older DS4Windows I couldn't use the headphone output, so despite this odd issue with this particular game, your fork is a definite improvement for me! 

If I can do anything to help debug the issue, just let me know.

Thanks again.

**Comment by Ryochan7** [comment]
Can you share the profiles that you are using? Definitely the switching between keyboard control icons to XInput control icons should not happen in game unless you are using a mixed XInput + KB+M configuration.

Also, I do not own either of those games so I cannot directly test that scenario.

**Comment by Ryochan7** [comment]
This is an old issue but I have not had a problem with audio output in a long time. I mainly use the Sony Wireless Adapter for using the DS4 wirelessly and I use the headphone jack often now.
