### ISSUE TITLE
DS4Windows is unable to see my Dualsense

### ISSUE THREAD

**Issue by Treviso** [Ryochan7/DS4Windows#3060]
**Describe the bug**
DS4Windows is unable to see my Dualsense, Steam Input as well as other games and software that support the Dualsense can still find it

**To Reproduce**
1. ...I wish I knew, sorry

**Expected behavior**
The Dualsense should pair, it has also worked for me in the past and to my knowledge I did not remove any drivers or software.

**Screenshots and Logs**
[ds4windows_log_20230821.1.txt](https://github.com/Ryochan7/DS4Windows/files/12396289/ds4windows_log_20230821.1.txt)
[ds4windows_log_20230821.2.txt](https://github.com/Ryochan7/DS4Windows/files/12396290/ds4windows_log_20230821.2.txt)
[ds4windows_log_20230821.3.txt](https://github.com/Ryochan7/DS4Windows/files/12396291/ds4windows_log_20230821.3.txt)
![firefox_2023-08-21_15-06-35](https://github.com/Ryochan7/DS4Windows/assets/26863516/50404003-58f4-45b4-9974-156e851b3d48)

**Desktop**
 - Controller Make and Model: Sony Dualsense CFI-ZCT1W
 - OS: Microsoft Windows NT 10.0.19045.0
 - DS4Windows Version 3.2.13 (also tested with 3.2.12 and 3.1.0)

**Additional context**
I think this issue stems from a broken or missing driver that DS4Windows relies on, but I have no clue how to best troubleshoot that.

**Comment by Treviso** [comment]
No idea how this happened, but issue solved

![image](https://github.com/Ryochan7/DS4Windows/assets/26863516/0758e78a-9ffc-417b-9887-c43fdd764cc0)

**Comment by Ryochan7** [comment]
Only DS4 support is enabled by default in the program. That decision was made to try to avoid extra conflicts with Steam Input. The latest release of DS4Windows at least now makes that more obvious. When a new config is being made, DS4Windows will now pop up a window asking which device types you want the program to open. After that, you would have to do to the Device Options window to enable or disable device types as needed.

![device_selection_ds4win](https://github.com/Ryochan7/DS4Windows/assets/581968/78946c3c-a197-48f2-bfe5-8f54b29c61bc)
