### ISSUE TITLE
Dead link in readme

### ISSUE THREAD

**Issue by nathan67003** [Ryochan7/DS4Windows#3064]
**Describe the bug**
The link to the installation and setup guide is not working.

**To Reproduce**
1. Go to the main github page
2. Scroll down to the Installation Tutorial section of the readme
3. Click on the link within the section
4. See that the link does not send to a working web page.

**Expected behavior**
The link leads to an installation and setup guide, as mentioned.

**Additional context**
This is unintended behaviour of the web part of this project, so I have deleted the hardware and software section.

**Comment by TheShiningRose** [comment]
same issue

**Comment by Ryochan7** [comment]
I never controlled that web page. It has been taken offline so it is no longer available. Might as well just remove that section for now.

**Comment by Ryochan7** [comment]
https://github.com/Ryochan7/DS4Windows/commit/95a3ff3425d028a3b16f8c5f89808564d3f865a7
