### ISSUE TITLE
[Feature] Flydigi Vader 3 Pro support

### ISSUE THREAD

**Issue by AterialDawn** [Ryochan7/DS4Windows#3065]
I am very interested in adding support to DS4Windows for the Flydigi Vader 3 Pro. The software that comes with this controller is very lacking. I managed to obtain USB communication dumps and some code that describes the communications that the usb controller performs with a windows pc in Dongle mode (DInput mode is similar).

Would this be something that can be added to DS4Windows? I can assist with anything related to this request

**Comment by Ryochan7** [comment]
Not sure if it would be possible. If the controller can be read as an HID device then it would make the process of making a device reader much easier. If the device can be read as an HID device then you can probably use my old HidReportInspector app to check which bytes of the input report correspond with the buttons and axes on the controller. Getting the gyro working properly would be a bit more of a challenge as you would need to figure out the input range and sensitivity of the gyro.

https://github.com/Ryochan7/HidReportInspector

Last release:
https://github.com/Ryochan7/HidReportInspector/releases/tag/v0.0.3

Making a DS4 equivalent mapping for the controller would not be that difficult. The Flydigi Vader interested me a bit more than the Apex Series controller. I would probably pick one up if I had some money to put down on a new controller.

**Comment by AterialDawn** [comment]
I'll give a quick review of my findings so far

The controller has 3 modes, Dongle, Bluetooth and Nintendo Switch. The report for Dongle and BT are identical, it just changes the connection method for the controller, with bluetooth having noticeably higher latency.
In Dongle and BT mode, the controller self-reports as a Xbox One Wireless Controller. The report json is the file starting in `0x045E-0x02E0`.

In switch mode, the controller's report format changes to a nintendo switch pro controller. Notable is this is the only mode that reports the gyro. Triggers are also changed to digital to match a real procon. Report for that is attached in file starting with `0x057E-0x2009`. There's a lot of extra bytes at the end of the gyro data that are always 0. Not sure if this is identical to a real procon.

Unfortunately, for all 3 modes, the extra buttons do not report at all over HID. All buttons seem to be remapped at the controller level. The default is C/Z report as L3/R3 joystick press buttons, and the rear buttons report as Dpad buttons. Using your report inspector i can confirm that the HID report confirms this.
[reports.zip](https://github.com/Ryochan7/DS4Windows/files/12491020/reports.zip)

I'll dig around some more in the drivers, maybe there's a command that allows the extra buttons to be sent over as well as the gyro data. Will report with my findings when i can.

**Comment by Ryochan7** [comment]
Those features seem to work in the bundled app. I would think that maybe there is some command that has to be sent to the controller before it switches modes so all buttons and gyro data are sent. I have never tried to do any USB packet sniffing so I do not know how that process works.

**Comment by AterialDawn** [comment]
> Those features seem to work in the bundled app.

Annoyingly in XInput mode, even the flydigi tester shows the C/Z and rear buttons as their remapped components

I do have some good news though, If you change the controller mode to DInput (by holding the O + A button for a few seconds), the controller successfully reports ALL of its buttons even in HID mode!
AND the controller sends gyroscope data in a separate HID Device!!! I got a hint about this one by looking at the decompiled service exe's code. The service exe sniffs a second device to convert the received gyroscope data into mouse inputs if you put the controller into device mode.

Now that i can confirm that all of the useful data from this controller can be parsed, i think we have enough info to get this thing mapped into DS4Windows. How would you like to go about this? I have busdog usb dumps we can look at, i can send over reports from your HIDReportInspector app, i can screenrecord me pressing actions and moving the controller around to get gyro data, i can even hand over the decompiled sources for parsing the gyroscope data.

Here's some fun screenshots
In DInput mode the controller shows up as 2 separate devices
![firefox_23-09-01_16-19-08](https://github.com/Ryochan7/DS4Windows/assets/15097070/196a9f54-2d5c-47f0-b318-dc04d97f74f7)
Here's a screenshot of me pressing one of the rear buttons, the extra C button in the front, and the Dpad at the same time
![rundll32_23-09-01_16-20-12](https://github.com/Ryochan7/DS4Windows/assets/15097070/f75017cb-2dfd-4d44-8b9e-428b5f256d8d)


I would greatly prefer if you would be willing to communicate over discord to do this a bit faster than over github issues if that's something you'd be willing to do as well!

**Comment by AterialDawn** [comment]
got it working

**Comment by HoshinoHikaru** [comment]
> > Those features seem to work in the bundled app.
> 
> Annoyingly in XInput mode, even the flydigi tester shows the C/Z and rear buttons as their remapped components
> 
> I do have some good news though, If you change the controller mode to DInput (by holding the O + A button for a few seconds), the controller successfully reports ALL of its buttons even in HID mode! AND the controller sends gyroscope data in a separate HID Device!!! I got a hint about this one by looking at the decompiled service exe's code. The service exe sniffs a second device to convert the received gyroscope data into mouse inputs if you put the controller into mouse mode.
> 
> Now that i can confirm that all of the useful data from this controller can be parsed, i think we have enough info to get this thing mapped into DS4Windows. How would you like to go about this? I have busdog usb dumps we can look at, i can send over reports from your HIDReportInspector app, i can screenrecord me pressing actions and moving the controller around to get gyro data, i can even hand over the decompiled sources for parsing the gyroscope data.
> 
> Here's some fun screenshots In DInput mode the controller shows up as 2 separate devices ![firefox_23-09-01_16-19-08](https://user-images.githubusercontent.com/15097070/265142687-196a9f54-2d5c-47f0-b318-dc04d97f74f7.png) Here's a screenshot of me pressing one of the rear buttons, the extra C button in the front, and the Dpad at the same time ![rundll32_23-09-01_16-20-12](https://user-images.githubusercontent.com/15097070/265142994-f75017cb-2dfd-4d44-8b9e-428b5f256d8d.png)
> 
> I would greatly prefer if you would be willing to communicate over discord to do this a bit faster than over github issues if that's something you'd be willing to do as well!

Hi Aterial.
I have some issue with flydigi software for use stable gyro setup. (Also flydigi Vader 3 Pro)
and I accident find your post from google, could you teach me how to do on DS4 windows software?
I don't mind communicate on discord, as long as can solved my problem.
I'm 1st time to gifthub, not sure If I could whisper you mine discord Id or not.

**Comment by Yentis** [comment]
Please detail how you solved your issue instead of just commenting that you got it working, this way you can help people that have the same issue in the future. @AterialDawn

**Comment by AterialDawn** [comment]
Oh, I thought nobody else was interested tbh.
I started using this controller on my switch so i lost interest in fully integrating the controller with ds4w's ui. My implementation was very hacky, and the extra buttons were just hardcoded in.
Regardless, i still have the class i was using in combination with HID Report Inspector to read the controller data out
```c#
public class FlydigiVader3ProController
{
    public Dpad Dpad { get; private set; }
    public Sticks Sticks { get; private set; }
    public Triggers Triggers { get; private set; }
    public StandardButtons StandardButtons { get; private set; }
    public ExtendedButtons ExtendedButtons { get; private set; }
    public FlydigiVader3ProController(byte[] hidData)
    {
        Dpad = (Dpad)(hidData[5] & 0b00001111);
        Sticks = new Sticks(hidData);
        Triggers = new Triggers(hidData);
        StandardButtons = new StandardButtons(hidData);
        ExtendedButtons = new ExtendedButtons(hidData);
    }

    public override string ToString()
    {
        return $"{Sticks} {Triggers} {Dpad} {StandardButtons} {ExtendedButtons}";
    }
}

[Flags]
public enum Dpad
{
    None = 0b00001111,
    Up = 0b00000000,
    UpRight = 0b00000001,
    Right = 0b00000010,
    DownRight = 0b00000011,
    Down = 0b00000100,
    DownLeft = 0b00000101,
    Left = 0b00000110,
    UpLeft = 0b00000111
}

public class Sticks
{
    public int LeftX { get; private set; }
    public int LeftY { get; private set; }
    public int RightX { get; private set; }
    public int RightY { get; private set; }
    public Sticks(byte[] hidData)
    {
        LeftX = (int)hidData[1];
        LeftY = (int)hidData[2];
        RightX = (int)hidData[3];
        RightY = (int)hidData[4];
    }

    public override string ToString()
    {
        return $"{LeftX} {LeftY} {RightX} {RightY}";
    }
}

public class Triggers
{
    public int LeftTrigger { get; private set; }
    public int RightTrigger { get; private set; }
    public Triggers(byte[] hidData)
    {
        LeftTrigger = (int)hidData[8];
        RightTrigger = (int)hidData[9];
    }

    public override string ToString()
    {
        return $"{LeftTrigger} {RightTrigger}";
    }
}

public class StandardButtons
{
    public bool A { get; private set; }
    public bool B { get; private set; }
    public bool X { get; private set; }
    public bool Y { get; private set; }
    public bool Start { get; private set; }
    public bool Select { get; private set; }
    public bool LB { get; private set; }
    public bool RB { get; private set; }
    public bool L3 { get; private set; }
    public bool R3 { get; private set; }
    public StandardButtons(byte[] hidData)
    {
        A = (hidData[7] & (1 << 7)) != 0;
        B = (hidData[7] & (1 << 6)) != 0;
        X = (hidData[7] & (1 << 4)) != 0;
        Y = (hidData[7] & (1 << 3)) != 0;
        Start = (hidData[6] & (1 << 4)) != 0;
        Select = (hidData[6] & (1 << 5)) != 0;
        LB = (hidData[7] & (1 << 1)) != 0;
        RB = (hidData[7] & (1 << 0)) != 0;
        L3 = (hidData[6] & (1 << 3)) != 0;
        R3 = (hidData[6] & (1 << 2)) != 0;
    }

    public override string ToString()
    {
        return $"{(A? "A " : "")}{(B ? "B " : "")}{(X ? "X " : "")}{(Y ? "Y " : "")}{(Start ? "Start " : "")}{(Select ? "Select " : "")}{(LB ? "LB " : "")}{(RB ? "RB " : "")}{(L3 ? "L3 " : "")}{(R3 ? "R3 " : "")}";
    }
}

public class ExtendedButtons
{
    public bool C { get; private set; }
    public bool Z { get; private set; }
    public bool M1 { get; private set; }
    public bool M2 { get; private set; }
    public bool M3 { get; private set; }
    public bool M4 { get; private set; }
    public bool Home { get; private set; }
    public ExtendedButtons(byte[] hidData)
    {
        C = (hidData[7] & (1 << 5)) != 0;
        Z = (hidData[7] & (1 << 2)) != 0;
        M1 = (hidData[6] & (1 << 1)) != 0;
        M2 = (hidData[6] & (1 << 0)) != 0;
        M3 = (hidData[5] & (1 << 7)) != 0;
        M4 = (hidData[5] & (1 << 6)) != 0;
        Home = (hidData[5] & (1 << 4)) != 0;
    }

    public override string ToString()
    {
        return $"{(C ? "C " : "")}{(Z ? "Z " : "")}{(M1 ? "M1 " : "")}{(M2 ? "M2 " : "")}{(M3 ? "M3 " : "")}{(M4 ? "M4 " : "")}";
    }
}
```

Note that this is with the controller in DInput mode (refer to the manual for how to enable this mode)
The small O button cannot be detected this way, but byte 9, bit 2 is set to 1 when the controller's mouse emulation mode is enabled via this button.
This should be enough to get the controller added to DS4Windows, sans gyroscope support. I did not bother trying to dissect gyroscope data, as i had no use for it at the time. 

The path of the device (according to HID Report Inspector) is `\\?\hid#vid_04b4&pid_2412&mi_00#7&37a3fec1&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}`
