### ISSUE TITLE
Rumble not working for DS3

### ISSUE THREAD

**Issue by Redyn** [Ryochan7/DS4Windows#3073]
I connected my legit DS3 to DS4Windows using DsHidMini and BthPS3. DS4Windows detects it, and I can use it to play games, but I get no rumble whatsoever. Even though the rumble works just fine when I test it with DS4Windows itself.

These are my settings:

![image](https://github.com/Ryochan7/DS4Windows/assets/20376420/97d19980-5519-4726-91fa-6b92f1592f4e)
![image](https://github.com/Ryochan7/DS4Windows/assets/20376420/993be390-3fdd-4e63-ad7c-12c110272e21)
![image](https://github.com/Ryochan7/DS4Windows/assets/20376420/80f3ec87-7ece-4f26-88fe-309de4b15753)

I've been advised to mark my DS3 as "Copycat" in Device Options, but it changes nothing. Still no rumble in games.

**Comment by Redyn** [comment]
Update: I managed get it to start working by changing the Rumble settings (percentage, strength level and such) to something else and then changing it back, but it stops working again if I reboot my computer.

**Comment by Kanuan** [comment]
Does the emulated Virtual Xbox 360 controller rumbles if you use the rumble button in the [Gamepad Tester Website](https://hardwaretester.com/gamepad)? If it does, then things are working as expected and the issue lies elsewhere.

**Comment by Ryochan7** [comment]
> I've been advised to mark my DS3 as "Copycat" in Device Options, but it changes nothing. Still no rumble in games.

I do not believe that option applies to the DS3 as that option mainly applies to DS4 controller support. That view is likely busted and the wrong control is being used. I will look into it.

I had to temporarily install DsHidMini again to test this; not going to keep it installed as it is unoptimized and slows my computer down big time just by being installed. When using Xbox 360 controller emulation, rumble works fine in HTML5 Gamepad Tester as well as when playing Streets of Rage 4. Rumble also works when using the rumble tests in the Profile Editor.

**Comment by Kanuan** [comment]
> I had to temporarily install DsHidMini again to test this; not going to keep it installed as it is unoptimized and slows my computer down big time just by being installed

Is there a test I can do to replicate this slowdown you are talking about? On my PC, having dshidmini installed or not doesn't seem to make any difference in performance, regardless if using or not the controller

**Comment by Hopyoprop** [comment]
I have a slightly different issue with the rumble for DS3 using the latest DsHdMini as well. I have the latest ViGemBus installed, latest DS4Windows and latest BthPS3 as well. 

Somehow the Rumble doesn't work when DS4Windows uses the Dualshock 4 preset with the DsHdMini DS3 in DS4Windows mode. When using the XBOX360 preset the rumble works.

**Comment by Redyn** [comment]
The problem seems to have gone away for me. After the last time I did the "change the rumble settings" trick, it has been working well, even after reboots.

Weird. In previous instances, the fix didn't stick.

**Comment by Hopyoprop** [comment]
> > Strangely testing the rumble using the Dualshock 4 preset for the DS3 works in the rumble section "Test Heavy" and "Test Light" but it doesn't work in games that do support it
> 
> If you use the rumble button in the [Gamepad Tester Website](https://hardwaretester.com/gamepad) while emulating a DS4 and it vibrates then things are working as expected and the issue lies elsewhere. Probably the game you are trying to play doesn't have working rumble with actual DS4 controllers

Oh I think I realised something. Its a steam controller input problem. When the controller is connected but in Dualshock 4 Preset, when I go into steam's settings to test the rumble it doesn't work. When the controller is in XBOX 360 Preset, the test rumble in the steam settings works. Kinda weird.
