### ISSUE TITLE
[Enhancement] Adding a Replica / Copy Cat Controller

### ISSUE THREAD

**Issue by forzaportante** [Ryochan7/DS4Windows#3082]
Since I recently got a third-party switch pro controller, a nyxi chaos, and windows recognizes it as a pro controller while ds4windows doesn't, could you add it to the list of controllers?

**Comment by Ryochan7** [comment]
The first step would be to grab the VID and PID for said controller. That information is available to view when using HTML5 Gamepad Tester.

https://hardwaretester.com/gamepad

After that, an entry would have to be added for the device enumerator in the DS4Devices class to flag it as a Switch Pro device that DS4Windows should look for. Then you would have to test it and make sure there are no extra complications when it comes to that hardware.

**Comment by forzaportante** [comment]
The index is 98:b6:e9:a7:5e:ef
![Screenshot 2023-09-16 103312](https://github.com/Ryochan7/DS4Windows/assets/101893515/fc2c3818-cdbb-4281-b444-fce65194ea45)

**Comment by Ryochan7** [comment]
Looks like an exact copycat as it uses duplicate VID and PID info as the official Switch Pro controller. Probably something happening wrong in the Init sequence. Cannot do anything without said hardware. Next time, buy the real controller.
