### ISSUE TITLE
higher latency over BT 5.0 than 2.0

### ISSUE THREAD

**Issue by Bubser** [Ryochan7/DS4Windows#3084]
When using DS4Windows with my new 5.0 BT dongle, my log looks like that :

09/16/2023 03:30:30: Controller 1's latency now under 10ms
09/16/2023 03:30:30: Controller 1's latency over 10ms (10.35 ms)
09/16/2023 03:30:30: Controller 1's latency now under 10ms
09/16/2023 03:30:30: Controller 1's latency over 10ms (10.35 ms)

over and over again.
There is no problem with my old 2.0 dongle.
I am using an official ds4 controller, all drivers are up to date, windows 10 pro

edit : it's not always exactly 10.35 ms, it varies a little, max I saw was 11.1 ms

**Comment by Kanuan** [comment]
Probably your 5.0 dongle is bad. Though the version is higher, sometimes the chipset in the dongle suck
