### ISSUE TITLE
Old bug with deleting Special Action profiles

### ISSUE THREAD

**Issue by vsub** [Ryochan7/DS4Windows#3087]
This bug have been there for a very long time.
1.Create a new special action and select it
2.Click on the "Remove Action" and you will see that something ELSE is removed from the list,not the one you selected
It is actually removing what you have selected but it is making you think you did a mistake and delete something you did not want.

When you click on cancel and go back,you will see that what you have selected was removed,not the one you see it was removed.

**Comment by Ryochan7** [comment]
Looks like that method was never updated after adding a CollectionView to sort the list by action name. Will fix that.

**Comment by Ryochan7** [comment]
576828fd9ced8d571cea4876477daf23432f2313
