### ISSUE TITLE
Mapping controls while editing a profile doesn't save.

### ISSUE THREAD

**Issue by cxj05h** [Ryochan7/DS4Windows#3096]
**Describe the bug**
Mapping controls while editing a profile doesn't save.

**To Reproduce**
1. Make a profile
2. Edit paddle buttons to XBox button (in this case, right paddle = A)
3. Apply/Save
4. Move over to XinputChecker
5. Right paddle shows it corresponds with button 'B'

**Expected behavior**
The right paddle should be mapped to button 'A'

**Screenshots and Logs**
If applicable, add screenshots to help explain your problem. Also, please add the most
log file (ds4windows_log.txt) from the Logs folder in your DS4Windows config folder.

**Desktop (please complete the following information):**
 - Controller Make and Model: SCUF Reflex
 - OS:  Windows 11
 - DS4Windows Version 3.2.14/15

**Additional context**

I had originally mapped this on something else, I can't remember, maybe for COD in [battle.net](https://battle.net/) settings, because 'B' was right paddle, but I want to make a new profile for another game and it looks like it's being overridden by something else somewhere else. No matter what combinations I do it's not working.

I even downloaded reWASD and changed them from there after having it become a virtual controller through DS4 which means I "lose" a button in the process since reWASD does not support SCUF Reflex.

I can map there and have it save no problem, which makes me think the problem is in DS4 somewhere unless I'm missing something.

**Logs:**
[ds4logs.txt](https://github.com/Ryochan7/DS4Windows/files/12719094/ds4logs.txt)

https://github.com/Ryochan7/DS4Windows/assets/22186535/e354c069-a597-4a4a-9c31-3bd359b31503

**Comment by Ryochan7** [comment]
Imagine spending over $200 on a game controller during a global depression. I cannot even afford groceries. Literally have no way to test this. It will be up to you.

![FRRh5BYaAAAtGXc](https://github.com/Ryochan7/DS4Windows/assets/581968/cf5bffc3-16e7-45fb-b1cc-543e93a3bbb5)
.

**Comment by cxj05h** [comment]
> Imagine spending over $200 on a game controller during a global depression. I cannot even afford groceries. Literally have no way to test this. It will be up to you.
> 
> ![FRRh5BYaAAAtGXc](https://user-images.githubusercontent.com/581968/270751025-cf5bffc3-16e7-45fb-b1cc-543e93a3bbb5.jpeg) .

Lol yeah, I regret it to this day. Wife still has no idea. 
Only thing I'll say was it was working a few updates ago...so maybe someone else will have something to say about it that might help and we can work together to figure it out!

**Comment by cxj05h** [comment]
> Ok, wait, why am I just now finding out that you can use DS4W for mapping SCUF paddles 🤯...
> 
> I have a SCUF controller as well. I'll test this out and report back.

Oh great! 
Yeah, that would help me narrow down whether or not is has to do with some previous settings in other apps that might be causing the issue...even though I uninstalled them.
This is also through "wired" connection btw. Ever since I started playing with it, I can't get windows 11 to connect via BT. The BT connection was established inside Windows 10 which apparently was grandfathered in but trying to get it in Windows 11 doesn't seem to work.

**Comment by iitzRichie** [comment]
> https://github.com/Ryochan7/DS4Windows/issues/3096#issuecomment-1737013949 I have a SCUF controller as well. I'll test this out and report back.

Apologies for the late reply.

So, yeah, with my own testing it looks like it doesn't end up applying it even if you do assign a button and click "Apply" + "Save". I do know though that in order to rebind the Paddles on SCUF controllers you need to use the magnetic tool that comes in the box, but you're saying even reWASD is able to successfully rebind them? I don't use reWASD, so I don't know much about it. But if you're saying it does work in reWASD, then yeah something is up with DS4 Windows.

**Comment by cxj05h** [comment]
> > [#3096 (comment)](https://github.com/Ryochan7/DS4Windows/issues/3096#issuecomment-1737013949) _"I have a SCUF controller as well. I'll test this out and report back."_
> 
> Apologies for the late reply.
> 
> So, yeah, with my own testing it looks like it doesn't end up applying it even if you do assign a button and click "Apply" + "Save". I do know though that in order to rebind the Paddles on SCUF controllers you need to use the magnetic tool that comes in the box, but you're saying even reWASD is able to successfully rebind them? I don't use reWASD, so I don't know much about it. But if you're saying it does work in reWASD, then yeah something is up with DS4 Windows.

Oh I did not see any magnetic anything.... I'll look that up, but pretty sure I didn't receive anything like that. 
But no, I was saying it was working with reWASD but you just essentially "lose" a button in the process since you are remaping an existing button
Ok well thanks for checking!

**Comment by iitzRichie** [comment]
> Oh I did not see any magnetic anything.... I'll look that up, but pretty sure I didn't receive anything like that.

Oh, wait, my bad, you have a SCUF Reflex, and remapping the Paddles works differently than previous SCUF controllers. I'm still using a SCUF 4PS (DualShock 4).

> But no, I was saying it was working with reWASD but you just essentially "lose" a button in the process since you are remaping an existing button

Wait, so does that mean if a Paddle is mapped to say X for example, if you remapped it using reWASD that the X button itself would also be remapped to a different button?

**Comment by cxj05h** [comment]
> Wait, so does that mean if a Paddle is mapped to say X for example, if you remapped it using reWASD that the X button itself would also be remapped to a different button?

Well, I have no control over what the paddle is mapped to anymore. Currently, the right paddle is mapped to 'B' so I'm actually taking reWASD and remaping 'B' to 'A' which essentially removes the button "B" since there's no where else to map it to as paddles were a "duplicate" of whatever existing buttons there are.

**Comment by Ryochan7** [comment]
Reviewed everything I could and everything seems to work as intended. The proper button codes are being used in a profile and the proper bindings are being saved. The DS4StateFieldMapping instances are using the proper button codes for the paddles so mapping would be linked properly there. As long as the DualSenseDevice ReadInput method is reading the paddles properly then I do not see a reason why mappings would not work or be swapped with other button codes.

Not sure @steffalon would be available to help. Not sure how remapping works when hooked up to the PS5 console because I obviously do not have a PS5 console either; never owned a PS4 console either.

**Comment by cxj05h** [comment]
Ok cool, maybe he can chime in.

**Comment by cxj05h** [comment]
omg. the rabbit hole of youtube led me to a video showing me you can "hardwire" button assignments on the controller itself. i must have inadvertently done that and that explains the a/b replacement. 

this can be closed. the issue has been totally fixed. after i changed that, the controller started connecting wirelessly again because that same video also explained the right button combinations to hold for correct pairing. wow. i mean the SCUF REFLEX can with literally no explanation. swear to god. 

anyways. sorry to disturb. you did great work and i really appreciate it. would easily pay money for this app so you should consider it. i know there are probably a few hundred that would, so why not?  at least make it an option.
