### ISSUE TITLE
Unable to execute .ps1 script using powershell with special action "Launch a program" in ver.3.2.15

### ISSUE THREAD

**Issue by gwin7ok** [Ryochan7/DS4Windows#3097]
**Describe the bug**
Unable to execute .ps1 script using powershell with special action "Launch a program" in ver.3.2.15

probably,
“Have Launch Program Special Action try to de-elevate when launching a program”
seems to be related to

It will be executed if in ver.3.2.14 or earlier

The contents of the .ps1 script that will be executed are below.
```
cd "G:\Games\reshade uwp\Genshin impact Reshade"
Start-Process -FilePath "G:\Games\reshade uwp\Genshin impact Reshade\inject.exe" GenshinImpact.exe -verb RunAs
Start-Process -Filepath "G:\Games\Genshin Impact\google\Genshin Impact\Genshin Impact game\GenshinImpact.exe"
```

Is it possible to make it executable even after ver.3.2.15?

**Screenshots and Logs**
![ss001 - DS4Windows](https://github.com/Ryochan7/DS4Windows/assets/1727775/51062428-de04-43b8-a3fe-99e8ef1f8ffe)

[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/12719063/ds4windows_log.txt)

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: Windows 10 Pro Build 22H2
 - DS4Windows Version 3.2.15

**Comment by mika-n** [comment]
how about creating a CMD/BAT file and launching it from DS4Windows and this CMD/BAT file then runs PS script:
`Powershell.exe -ExecutionPolicy Bypass -File "c:\games\genshin\blueProtocolWithReshade.ps1"`

**Comment by gwin7ok** [comment]
> how about creating a CMD/BAT file and launching it from DS4Windows and this CMD/BAT file then runs PS script: `Powershell.exe -ExecutionPolicy Bypass -File "c:\games\genshin\blueProtocolWithReshade.ps1"`

I was able to do it that way, thank you
