### ISSUE TITLE
Controller shutdown via STOP button or exit no longer works in v3.2.x

### ISSUE THREAD

**Issue by madcrow** [Ryochan7/DS4Windows#3098]
**Describe the bug**

After updating to 3.2.0 from 3.1.12, the controller no longer shuts down after hitting the stop button or closing the app.
Affected versions: all releases after and including 3.2.0
Controller: DS4v2
Adapter: SONYWA
OS: Win10Pro 22H2

**To Reproduce**

_Prequisites:_ DS4Windows 3.2.x, one SONYWA adapter and one DS4v2 paired together

Start DS4Windows
Turn on controller via the PS button
Click on the STOP button at the bottom right corner
_Expected behavior:_ Controller shuts down (lights off)
_Actual behavior:_ Controller remains powered on (indicator light unchanged)
Click the START button at the bottom right corner
Click on the exit botton (X) at the top right corner
Click yes on the diaog
_Expected behavior:_ Controller shuts down (lights off)
_Actual behavior:_ Controller remains powered on (indicator light unchanged)

**Screenshots and Logs**

```
09/27/2023 20:23:01: DS4Windows version 3.2.0
09/27/2023 20:23:01: DS4Windows Assembly Architecture: x64
09/27/2023 20:23:01: OS Version: Microsoft Windows NT 10.0.19045.0
09/27/2023 20:23:01: OS Product Name: Windows 10 Pro
09/27/2023 20:23:01: OS Release ID: 2009
09/27/2023 20:23:01: System Architecture: x64
09/27/2023 20:23:02: Running as Admin
09/27/2023 20:23:03: Starting...
09/27/2023 20:23:03: Using output KB+M handler: SendInput
09/27/2023 20:23:03: Connection to ViGEmBus 1.17.333.0 established
09/27/2023 20:23:03: Searching for controllers...
09/27/2023 20:23:03: Using Exclusive Mode
09/27/2023 20:23:03: Found Controller: 00:00:00:00:00:00 (SONYWA) (Sony WA).
09/27/2023 20:23:06: Plugging in virtual X360 controller (XInput slot #1) in output slot #1
09/27/2023 20:23:06: Associated input controller #1 (Sony WA) to virtual X360 Controller in output slot #1
09/27/2023 20:23:06: Controller 1 is using Profile "Default". Battery level is 87%
09/27/2023 20:23:18: Stopping Virtual Output Controllers
09/27/2023 20:23:18: Closing connection to ViGEmBus
09/27/2023 20:23:18: Disassociated virtual X360 Controller in output slot #1 from input controller #1 (Sony WA)
09/27/2023 20:23:18: Unplugging virtual X360 Controller from output slot #1
09/27/2023 20:23:18: Controller 1 was removed or lost connection
09/27/2023 20:23:18: Stopping DS4 Input Controllers
09/27/2023 20:23:18: Stopped DS4Windows
```

**Misc hints and notes**
Disconnect & power off by the PS+Option hotkey works fine though.

**Comment by Masamune3210** [comment]
I can find nothing about this Sonywa adapter, what is it?

**Comment by Ryochan7** [comment]
https://github.com/Ryochan7/DS4Windows/commit/c2a895f6b396854245e9eb9950eb2623f3fdc313

**Comment by madcrow** [comment]
> I can find nothing about this Sonywa adapter, what is it?

[Sony DUALSHOCK 4 USB Wireless Adapter](https://www.amazon.com/Sony-DUALSHOCK-USB-Wireless-Adapter-4/dp/B01KHFIO82/ref=sr_1_1?keywords=dualshock+4+usb+wireless+adapter&qid=1695882213&sr=8-1)
Ds4Windows simply refers to it as "SONYWA", (meaning "SONY Wireless Adapter", I assume).

**Comment by Masamune3210** [comment]
Ahh, good to know

**Comment by Vladgina** [comment]
Are you using wireless? Under **Settings** there's an option **Disconnect from BT when Stopping**. That might be it.

**Comment by Masamune3210** [comment]
considering ryochan linked a commit, im assuming its more a coding issue than a setting issue

**Comment by madcrow** [comment]
> [c2a895f](https://github.com/Ryochan7/DS4Windows/commit/c2a895f6b396854245e9eb9950eb2623f3fdc313)

Confirmed. Working. Thanks!
