### ISSUE TITLE
After recording a macro some functions stop working

### ISSUE THREAD

**Issue by pralima87** [Ryochan7/DS4Windows#31]
So this is a old bug but right now is really easy to reproduce.

Action 1 - Set a light-bar color to any button in the "Select an action" menu
Action 2 - Record a macro for any button in the "Select an action" menu or special actions.

Result - The light bar will stop responding when pressing button from Action 1.
"Shift Modifiers" will also stop working.

**Comment by Ryochan7** [comment]
I had encountered similar problems when finding the problem with the multi-action button feature. At that time, I was just concerned with getting the action type working again so I need to go back and check this.

**Comment by Ryochan7** [comment]
I am looking into this again. After testing recording macros a bit, I have not been able to encounter the problem that I had experienced before. Maybe changes fixed this problem but more testing will have to be done just to make sure.

**Comment by pralima87** [comment]
I think this is still not 100% fixed.
Did did a test on the multi-action button macros. 
After recording a macro the Lightbar still stops working.

**Comment by Ryochan7** [comment]
I will re-open this issue for the time being. However, I cannot duplicate the problem on my system. The only thing that I can look in the code for is a time where the recording macro flag is not reverted. That flag still being set would be the most likely culprit for this problem occurring.

**Comment by pralima87** [comment]
Here is a profile to test this issue:
[DS4_Steam.xml](http://www.mediafire.com/file/cuw61ff2611was1/DS4_Steam.xml)

Pressing the PS button change lightbar to blue.
After recording a macro pressing the PS will not change the bar color.

**Comment by Ryochan7** [comment]
Can you share your Actions.xml file as well? That will be needed to test the bound special actions.

I only looked around at this today and there were circumstances when the recordingMacro flag would not get reset. That would cause all special bindings to not work. I just made a small change to explicitly reset the flag when closing that form instead of relying on the status of the recording button. It should be enough to work around the problem. I can post a test build in a little while.

**Comment by Ryochan7** [comment]
New test build

https://drive.google.com/open?id=0B6yGHDx0CFzDQkJyZUtRN01WWkU

**Comment by pralima87** [comment]
Yep the test build is working fine after recording macros!
Cheers!

Here is my actions profile: 
[Actions.zip](http://www.mediafire.com/file/jej7bsbl961g11c/Actions.zip)
