### ISSUE TITLE
'Tap' doesn't work every time

### ISSUE THREAD

**Issue by Geroyuni** [Ryochan7/DS4Windows#310]
[This option is what I'm referring to](https://i.imgur.com/qGCREr6.png) - I observed this issue in Cemu Emulator (while attempting to tap on things in the games). Actually pressing the touchpad works every time though.

**Comment by Geroyuni** [comment]
Made some tests recently with various programs recently and I can reproduce it with other emulators such as Citra and DeSmuME. This doesn't really happen in normal programs (I tested browsers and electron apps such as Discord and Atom Editor, Windows' UI, some adobe suite programs, and some games).

**Comment by Ryochan7** [comment]
The option works for me. My main guess is that UAC permission issues were making the virtual mouse click events get ignored. As it is now, DS4Windows now has to run as administrator so that issue should not exist for normal applications.
