### ISSUE TITLE
Special actions with arguments not working any longer 3.2.16

### ISSUE THREAD

**Issue by Qumojo** [Ryochan7/DS4Windows#3101]
**Describe the bug**
Special actions that launches python scripts with arguments are no longer working. An explorer.exe is launched but doesn't resolve. The task hangs in the Task Manager indefinitely. It was working fine in 3.2.13. If the arguments is removed from the input box, then it does run just fine. Right now, I just duplicate my script into 4. Makes it harder to keep it updated as now I have to update 4 scripts instead of just one... :( Having the argument was such a nice QoL, thanks for fixing it.

**Comment by Ryochan7** [comment]
A consequence of commit 230145f224cc5b16793c304362620229a2e7cda1 to work around issue #2762

Thinking about it, this type of behavior is likely contributing to the false positives that VirusTotal brings up. It is very likely that heuristic analysis is detecting all that user switching as suspicious behavior and flagging DS4Windows as a result. And the same people will complain about those false positives and defame my work while using other software that VirusTotal has flagged with worse results. Looks like the only way around this problem anyway would likely require editing the registry to place the cmd arguments.

At this point, I am just going to revert that commit and stop supporting this roundabout user hackery. Between HidHide and FakerInput being incorporated, there has been no real need to run DS4Windows as admin for a long time.
