### ISSUE TITLE
Dualsense light bar dim blue light flashing

### ISSUE THREAD

**Issue by weishen1121** [Ryochan7/DS4Windows#3112]
I usually have a dark red color set for my lightbar on my DualSense but kept noticing some weird light flash in my peripheral vision. 

I set all the lightbar sliders to the left to just turn off the lightbar and now there is a very dim blue light flashing going on... It's really weird and random. 

I thought it might be the "Flash lightbar at High Latency" setting so I turned it off, turned off the controller and restarted DS4Windows but it's still randomly happening.

I also have two controllers that I swap in between with while charging and its happening on both. 

Any ideas?

**Comment by Ryochan7** [comment]
It is likely Steam Input or some other program trying to take control of the controller. You need to hide the physical DualSense controller.

**Comment by Ryochan7** [comment]
Found the likely culprit. 7f11dabec637d12efb5640f2d06758072c6b709a

Seems to affect a BT connection more as I do not experience the slight appearance of a blue lightbar when connected via USB. The main issue is that the input thread is still running while the next profile is being loaded. Once the old profile properties are reset, the default lightbar color of blue will be used. XmlSerializer is reflection based so it is likely a bit slower than the old loading routine. The input thread will then proceed to use the blue lightbar color until the next profile is loaded and then the chosen color will be used.

With the change, the input thread is temporarily paused until profile loading has finished.

**Comment by Ryochan7** [comment]
Made a couple of small tweaks since the last post. This issue is resolved.
