### ISSUE TITLE
NFS Unbound and DualSense don't work.

### ISSUE THREAD

**Issue by KoleckOLP** [Ryochan7/DS4Windows#3113]
**Describe the bug**
Can't play Need For Speed Unbound, with DualSense and DS3Windows, if I set the controler to Xbox360 or DS4 neither work with this game.
The controller works on the game just fine if I close DS4Windows.
And Mincraft for Windows 10 works just fine if set to VirtualGamepad Xbox360.

**To Reproduce**
Connect DualSense to DS4Windows enable VirtualGamepad (Xbox360/DS4)
Apply settings
Launch game, and the game will never recognise the controller
even disabling VirtualGamepad doesn't fix this

**Expected behavior**
What I wanted it to change the color of the light bar, and check battery and play the game,
Is there a way to just Passtrough the DualSense?

**Screenshots and Logs**
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/12807682/ds4windows_log.txt)

**Desktop (please complete the following information):**
 - Sony DualSense CFI-ZCT1W
 - OS: Windows 10 IoT Enterprise LTSC 2021
 - DS4Windows version 3.2.17

**Additional context**
Once again I would just like to passtrough the controller while changing it's lightbar color based on battery %

**Comment by Ryochan7** [comment]
Shared Mode is used and HidHide is not detected. The game is likely picking up the now dead DirectInput interface for the physical BT connected DualSense controller. You will likely have to hide the BT controller so the game does not try to open it and see no input.
