### ISSUE TITLE
[Bug]DS4Windows is crashing while trying to open HidHide

### ISSUE THREAD

**Issue by vsub** [Ryochan7/DS4Windows#3116]
from the settings page in DS4Windows
This is probably because my HidHide(installed separately)is an old version which I did not update(1.0.30.0)but everything else is working fine so didn't update it

And btw,for a while now I see the changelog mention it multiple times but do I still need Nefarus HidHide installed to use DS4Windows or the program have a build in feature to hide the real controller?

**Comment by Ryochan7** [comment]
https://github.com/Ryochan7/DS4Windows/commit/e0f3b338a6bfe9ac8033e7ab030a92a221518416

HidHide is still considered an optional component. Although, the old exclusive mode workaround does not really work anymore. Most of the time, you would want only DS4Windows seeing the original DS4 controller so HidHide is pretty much essential in that case.
