### ISSUE TITLE
How to emulate two wireless joycon as one controller?

### ISSUE THREAD

**Issue by RexYuan** [Ryochan7/DS4Windows#3118]
Currently, I set up DS4Windows and Hidhide like this:
![image](https://github.com/Ryochan7/DS4Windows/assets/5001650/87e591cd-8cb5-493f-94ff-4b94cbb7b8d2)

Each joycon gets emulated as a separate controller. In most games this works fine. But in elden ring this doesn't work. You can't use both joycon simultaneously. The game will only listen to one joycon at a time.

Is there a way to emulate two joycon as one controller so that this problem goes away?

I'm using DS4Windows v3.2.17

**Comment by SgtSweetieBelle** [comment]
would also like help with this

**Comment by Ryochan7** [comment]
![ds4win_joycon_joined](https://github.com/Ryochan7/DS4Windows/assets/581968/c12c3287-f585-4c35-8454-7891d7962c84)

The option is available in the Controller Type Options window accessed from Device Options in the Settings. The default is supposed to be to have the JoyCon controllers marked as Joined but that was not the case. Fixed that in the AppSettingsDTOclass.

https://github.com/Ryochan7/DS4Windows/commit/a473661bd309dc693210ce7839d1da6ba0006616

**Comment by SgtSweetieBelle** [comment]
> ![ds4win_joycon_joined](https://user-images.githubusercontent.com/581968/275344151-c12c3287-f585-4c35-8454-7891d7962c84.png)
> 
> The option is available in the Controller Type Options window accessed from Device Options in the Settings. The default is supposed to be to have the JoyCon controllers marked as Joined but that was not the case. Fixed that in the AppSettingsDTO class.
> 
> [a473661](https://github.com/Ryochan7/DS4Windows/commit/a473661bd309dc693210ce7839d1da6ba0006616)

I just checked this, and it doesn't seem to appear that way. My JoyCon are being read as "Switch Pro", so there's no option to turn on Link Mode.

![image](https://github.com/Ryochan7/DS4Windows/assets/2397955/744f4cb8-e77f-4b7f-81fe-29b3e03accb5)

**Comment by Ryochan7** [comment]
Don't buy cheap third party controllers off Amazon

**Comment by SgtSweetieBelle** [comment]
they’re ergonomic controllers that i bought for accessibility reasons. the standard Joycons were inflaming my RSIs.

steam input reads them as joycons. betterjoy sees them as switch pro controllers, but provides an option to interpret each one as a left and right joycon, and then join them together into a single xinput controller. i was wondering if there was similar functionality for ds4win, since betterjoy doesn’t have button remapping.

**Comment by RexYuan** [comment]
@SgtSweetieBelle What controllers are you using exactly?

**Comment by RexYuan** [comment]
Thanks for the heads up @Ryochan7 my setup now correctly emulates two joycon as one xbox360 and they work perfectly in elden ring!
![image](https://github.com/Ryochan7/DS4Windows/assets/5001650/f64d4022-757e-4601-9114-ae11ebe6ece4)

**Comment by SgtSweetieBelle** [comment]
These guys:
https://www.amazon.com/dp/B0CDLN7YYS
