### ISSUE TITLE
Dualsense Edge additional buttons not bound correctly when used as trigger for the gyro mouse joystick function

### ISSUE THREAD

**Issue by zegamemaster** [Ryochan7/DS4Windows#3120]
**Describe the bug**
When using the paddles or the function keys as trigger for the gyro mouse joystick function, the trigger end up being bound to the wrong button, or not bound at all.

Manually typing the keycode in the controller profile and restarting DS4Windows works fine (code 23 to 26 according to the case statement in Mouse.cs)

**To Reproduce**
1. In the profile editor, go to the Gyro Tab 
2. Select Mouse Joystick as Output Mode
3. Select either Bottom Left Paddle, Bottom Right Paddle, Function Left or Function Right
4. Save and test in game / look as the keycode in the profile file
5. The trigger either does not work, or is mapped to the wrong button

**Expected behavior**
Pressing the selected trigger should activate the gyro mouse joystick just as the standard buttons do.

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DualSense Edge
 - OS: Windows 11 Pro Build 10.0.22621.0
 - DS4Windows Version [e.g. 3.2.17]

**Additional context**
After investigating the code, I found that the problem was that the case statement in the file "Mouse.cs" (line 1068) includes two additional buttons, SideL and SideR. These buttons are not present in the menu used to setup the gyro mouse joystick triggers (ProfileEditor.xaml, line 1835). The function "UpdateGyroMouseStickTrig" in ProfileSettingsViewModel.cs (line 3275) relies on the index of the menu items being the same as the values in the case statement in Mouse.cs, which is not the case as it is missing two entries. 

Hope that helps.

**Comment by Ryochan7** [comment]
https://github.com/Ryochan7/DS4Windows/commit/89bc2cc5e93264729d79794ab2b6572335784168

The update definitely helped. Thank you. That VM relies on the index of MenuItem instances in that list to act as the trigger code. It would be better to abstract the code from the index in a list but I just went with the easier route when writing that code.

My test mappers has the codes abstracted and can show buttons that only apply to a specific controller. Quite a bit of extra code required to make that work though.

**Comment by Ryochan7** [comment]
Old commit was actually wrong. https://github.com/Ryochan7/DS4Windows/commit/caa073194f964d8bfee1e4a1c30ed364fc451a62
