### ISSUE TITLE
Log points to docs.ds4windows.app for mouse troubleshooting

### ISSUE THREAD

**Issue by hello-party** [Ryochan7/DS4Windows#3121]
The 'Some applications may block controller inputs... Please go to...' error directs us to nonexistent documentation

[link to code](https://github.com/Ryochan7/DS4Windows/blob/e0f3b338a6bfe9ac8033e7ab030a92a221518416/DS4Windows/DS4Control/ControlService.cs#L1548)

**Comment by Ryochan7** [comment]
Not really a big concern but I guess I can change that since the old docs have been moved over by Kanuan.

**Comment by Ryochan7** [comment]
https://github.com/Ryochan7/DS4Windows/commit/575ab2b1860fa7bafee1998e0429c2c5a29fa950
