### ISSUE TITLE
Whats the last version that had support for windows 8.1?

### ISSUE THREAD

**Issue by ExGuestCJ** [Ryochan7/DS4Windows#3123]

**Comment by Ryochan7** [comment]
In theory, the current version of DS4Windows should still work on Windows 8.1 fine. The main limitation is that you would be stuck using ViGEmBus 1.16.116 as that was the last version of ViGEmBus to offer Windows 8.1 support. Any later version of ViGEmBus requires that a PC run at least Windows 10.

**Comment by ExGuestCJ** [comment]
i tried both the 7z file and the setup file but both didnt work
