### ISSUE TITLE
DS4 exclusive mode (with hidhide) not working with nvidia Geforce experience, is there any work around?

### ISSUE THREAD

**Issue by ab22070** [Ryochan7/DS4Windows#3126]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots and Logs**
If applicable, add screenshots to help explain your problem. Also, please add the most
log file (ds4windows_log.txt) from the Logs folder in your DS4Windows config folder.

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: [e.g. Windows 10 Pro Build 2004]
 - DS4Windows Version [e.g. 3.0.3]

**Additional context**

**Comment by ab22070** [comment]
essentially the title, when gamingon dual shock controller on PC, my instant replay setting will turn off. i do not get this problem when im using kb&m

**Comment by catscarlet** [comment]
Read [this](https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues).
Disable GeForce in-game overlay feature in NVIDIA options or enable it only after you have started DS4Windows tool.

**Comment by Ryochan7** [comment]
You probably do not have HidHide configured correctly. If nothing else, maybe you launched DSX at some point and it disabled the **Enable device hiding** option in HidHide upoon exiting. DS4Windows leave configuring HidHide to the end user so as not to clobber settings when it comes to other programs.

Also, you probably should not be using GeForce Experience in the first place.

**Comment by ab22070** [comment]
> Read [this](https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues). Disable GeForce in-game overlay feature in NVIDIA options or enable it only after you have started DS4Windows tool.

I have tried this however GFE still turns itself off when im in games and is generally buggy

**Comment by ab22070** [comment]
> You probably do not have HidHide configured correctly. If nothing else, maybe you launched DSX at some point and it disabled the **Enable device hiding** option in HidHide upon exiting. DS4Windows leaves configuring HidHide to the end user so as not to clobber settings when it comes to other programs.
> 
> Also, you probably should not be using GeForce Experience in the first place.

I have configured hidhide fine as it shows the key under exclusive mode

**Comment by IceLancerSR** [comment]
> > You probably do not have HidHide configured correctly. If nothing else, maybe you launched DSX at some point and it disabled the **Enable device hiding** option in HidHide upon exiting. DS4Windows leaves configuring HidHide to the end user so as not to clobber settings when it comes to other programs.
> > Also, you probably should not be using GeForce Experience in the first place.
> 
> I have configured hidhide fine as it shows the key under exclusive mode

It's working just fine even on win11. 
I use geforce experience for recording/screenshots with desktop enabled even.
You must have missed some step in configuring hidhide , nothing can get past hidhide and hijack controler if setup properly.

![Screenshot 2023-11-25 110822](https://github.com/Ryochan7/DS4Windows/assets/4452102/c94cbd86-82b8-4f0c-9d8e-4b63453e631b)
