### ISSUE TITLE
DS4 controller keeps connecting/disconnecting when using USB cable

### ISSUE THREAD

**Issue by ah1salehi** [Ryochan7/DS4Windows#3127]
Aftermarket DS4 controller keeps connecting/disconnecting when using USB cable (tested different cables and ports)
If I close DS4windows, it stays connected with no problem

As you can see it is working fine with BT, only issue is when I switch to USB

10/14/2023 02:25:59: Found Controller: D0:27:96:4C:20:50 (BT) (DS4 v.2).
10/14/2023 02:26:00: Associated input controller #1 (DS4 v.2) to virtual X360 Controller in permanent output slot #1
10/14/2023 02:26:00: Controller 1 is using Profile "Default". Battery level is 100%
10/14/2023 02:26:13: Found Controller: D0:27:96:4C:20:50 (USB) (DS4 v.2).
10/14/2023 02:26:13: D0:27:96:4C:20:50 disconnected due to read failure: 997
10/14/2023 02:26:13: Disassociated virtual X360 Controller in permanent output slot #1 from input controller #1 (DS4 v.2)
10/14/2023 02:26:13: Controller 1 was removed or lost connection
10/14/2023 02:26:15: Associated input controller #1 (DS4 v.2) to virtual X360 Controller in permanent output slot #1
10/14/2023 02:26:15: Disassociated virtual X360 Controller in permanent output slot #1 from input controller #1 (DS4 v.2)
10/14/2023 02:26:15: Controller 1 was removed or lost connection
10/14/2023 02:26:18: Found Controller: D0:27:96:4C:20:50 (USB) (DS4 v.2).
10/14/2023 02:26:18: Associated input controller #1 (DS4 v.2) to virtual X360 Controller in permanent output slot #1
10/14/2023 02:26:18: Controller 1 is using Profile "Default". Battery level is 90%
10/14/2023 02:26:18: Disassociated virtual X360 Controller in permanent output slot #1 from input controller #1 (DS4 v.2)
10/14/2023 02:26:18: Controller 1 was removed or lost connection

**Comment by JaegerFox** [comment]
that happened to me when upgrading to the latest version, try unzipping DS4Windows to another directory, open and configure the settings to be saved in the current directory to have a clean install, see if that solves your problem.
otherwise uninstall and reinstall vigem drivers

**Comment by ah1salehi** [comment]
> that happened to me when upgrading to the latest version, try unzipping DS4Windows to another directory, open and configure the settings to be saved in the current directory to have a clean install, see if that solves your problem. otherwise uninstall and reinstall vigem drivers

I tried your suggestion but it didnt help, even tried V3.1.0 still has that issue. I can use the controller with x360ce but I really like DS4windows. Can anyone help please?

**Comment by Ryochan7** [comment]
> Aftermarket DS4 controller

That is enough to seal the fate of this issue. Also apples and oranges comparison. Comparing a program that uses the DirectInput interface as opposed to switching to DS4 mode. Get a real DS4 or submit a pull request.
