### ISSUE TITLE
Setting "Custom Lightbar Colors" not working on any of my fake DS4s. (past version 3.0.18)

### ISSUE THREAD

**Issue by golimonkey** [Ryochan7/DS4Windows#3128]
As the title says. I cannot change lightbar color after updating from 3.0.18 to any newer version.
I used copycat option and tried 2 different versions of fake DS4s. (totaly different internals and small differences in functioning) Result is the same.

In 3.0.18 after applying copycat option lightbar color changes to color set in custom color picker, but in versions after that nothing changes.

I would not ask for bug fix but I would like to update because 3.0.18 has bug where you cannot set controller buttons to toggle keyboard keys. It has options to do it but keys do not toggle, as soon as you lift up keys lift. (It would be useful for toggling shift for running)

Tnx

DS4Windows: 3.2.17
Windows 10 21H2
Controller: Fake DS4

[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/12907968/ds4windows_log.txt)

**Comment by Ryochan7** [comment]
Not a pull request so this is instantly invalid. People expect me to perform some KingCobraJFS black magic and just make things work for hardware I do not have.
