### ISSUE TITLE
Double input or 'Button Chatter' Issue (HidHide Enabled/Steam Input Disabled)

### ISSUE THREAD

**Issue by ButtermilkBackshots** [Ryochan7/DS4Windows#3135]
I have an issue that's been prevalent for years now (looking for a solution now because it's getting worse than its ever been) where I'll physically press a button once but it'll register two button presses immediately, causing an immediate double input error, adversely affecting my execution in competitive games. These symptoms are basically the controller equivalent of what's known as ['key chatter'](https://www.google.com/search?q=what+is+key+chatter&rlz=1C1JSBI_enUS1077US1077&oq=what+is+key+chatter&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIMCAEQABgUGIcCGIAEMgwIAhAAGBQYhwIYgAQyCAgDEAAYFhgeMgoIBBAAGIYDGIoF0gEIMzMxM2owajeoAgCwAgA&sourceid=chrome&ie=UTF-8).

Was wondering if there's a setting I'm missing that could aid this issue. Maybe something that filters out inputs made too rapidly by ignoring any following repeat inputs up to a certain amount of milliseconds?

For the record:
- This happens on an official Dualshock 4 
- HidHide is properly running with a "key" icon showing under the "Ex" section in DS4Windows and all Steam controller inputs are disabled in Big Picture Mode. 
- DS4Windows, HidHide and Windows 10 are all up to date. 
- Issue is prevalent on basically every Dualshock 4 I've ever owned.
- I use the Dualshock 4 exclusively in wired mode.

**Comment by Ryusennin** [comment]
Just to be sure, in HidHide you cloaked the physical Sony controller, not the virtual Xbox controller?

Another thing to try with Steam is to change the name of your DS4Windows executable (I personally use ds4win.exe) because Steam is known to circumvent DS4Windows when it detects "ds4windows.exe" running.

**Comment by ButtermilkBackshots** [comment]
> Just to be sure, in HidHide you cloaked the physical Sony controller, not the virtual Xbox controller?
> 
> Another thing to try with Steam is to change the name of your DS4Windows executable (I personally use ds4win.exe) because Steam is known to circumvent DS4Windows when it detects "ds4windows.exe" running.

Yes, double checked that only the physical Sony controller is cloaked and I never heard of Steam doing that before but I went ahead and renamed it to what you suggested.
