### ISSUE TITLE
UpperTouch of DS4 is recognized as either RightTouch or LeftTouch

### ISSUE THREAD

**Issue by gwin7ok** [Ryochan7/DS4Windows#3136]
**Describe the bug**
If the flat cable of the touch panel of the Dualshock 4 controller is connected properly
RightTouch, LeftTouch, and Multitouch function normally, but UpperTouch is recognized as either RightTouch or LeftTouch no matter what part you press.

If the flat cable of the touch panel of the Dualshock 4 controller is not connected
All SingleTouch and Multitouch are recognized as UpperTouch

*This phenomenon occurs with both ver.1 and ver.2 Dualshock4.
*This phenomenon has been occurring since a very old version.

**To Reproduce**
1. Assign inputs from "1" to "4" to each Touch in the DS4 profile settings
2. Perform an input test for each Touch while focusing on Notepad.
3. Only UpperTouch outputs the number assigned to RightTouch or LeftTouch.
*To connect and disconnect the touch panel flat cable, disassemble the DS4.

**Expected behavior**
UpperTouch is recognized correctly

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 and v.1
 - Windows 10 Pro Build 22H2
 - DS4Windows Version ver.3.2.17(Including previous versions)

**Comment by Ryochan7** [comment]
Works fine on my end

**Comment by gwin7ok** [comment]
I retested in my own environment and UpperTouch was recognized properly.
In previous tests, the touchpad was pressed incorrectly.
Sorry for posting the wrong bug report.
