### ISSUE TITLE
Is it possible to completely disable DS4 Bluetooth/charging when connected via USB?

### ISSUE THREAD

**Issue by Darthagnon** [Ryochan7/DS4Windows#314]
Title says it all; I was wondering if I start the DS4, connected by USB to the computer (running DS4Windows) whether it's set (or can be set) to disable Bluetooth completely. I was also curious whether it's possible to limit charging the DS4 battery in DS4Windows?

I noticed, in the Settings tab, there's the "Quick Charge" option, which is labelled "EXPERIMENTAL: Auto-Disable BT when connecting to USB". Does this disable BT? Does it work, since it is "Experimental"? Seems slightly confusing mismatch between the checkbox name and the tooltip?

**Comment by Ryochan7** [comment]
The Quick Charge option is what you probably want. That option will close the BT connection if DS4Windows detects that you plug a controller in via USB.

The feature did not work when I started working on this fork and it took many revisions to get the feature working in a sensible way. I don't really use the Quick Charge feature but it should work just fine and be safe to use nowadays.

**Comment by Darthagnon** [comment]
Thank you very much, @Ryochan7 :D
