### ISSUE TITLE
DS Edge function buttons as shift modifier

### ISSUE THREAD

**Issue by EndThior** [Ryochan7/DS4Windows#3141]
Hi, would you be able to add the function (and possibly paddle) keys to the shift modifier selection?

**Comment by Ryochan7** [comment]
https://github.com/Ryochan7/DS4Windows/commit/e914d6608bc7f70d112625da7c3ece0cad98ea8c

**Comment by EndThior** [comment]
> [e914d66](https://github.com/Ryochan7/DS4Windows/commit/e914d6608bc7f70d112625da7c3ece0cad98ea8c)

Thank you :)
