### ISSUE TITLE
After installing 3.2.18 DS4Windows suggests to *update* to 3.2.17

### ISSUE THREAD

**Issue by Xottab-DUTY** [Ryochan7/DS4Windows#3143]
**Describe the bug**

**To Reproduce**
1. I had DS4Windows 3.2.17
2. See a notification that 3.2.18 has been released.
3. Update immediately within 5-10 minutes
4. Launch DS4Windows
5. See a window that appears and suggests to update to the new 3.2.17 version, which is actually older.
6. After few more minutes, the window doesn't appear.

**Expected behavior**
Correct version checking behaviour. Even if the update server still has outdated data for 10-15 minutes after release, the installed DS4Windows should determine that it is newer than the version returned by the server.

P.S. I have no idea how version check/update functionality works, so It's just a wild guess.

Thanks for this awesome software!

**Screenshots and Logs**
![image](https://github.com/Ryochan7/DS4Windows/assets/2989212/eec2685b-e1b5-4adb-a088-101016517747)
![image](https://github.com/Ryochan7/DS4Windows/assets/2989212/8ce67268-eee2-41a1-9049-61b525f45b42)

**Desktop (please complete the following information):**
 - DS4Windows Version 3.2.18

**Comment by Ryochan7** [comment]
Did you mean a GitHub notification or the standard alert in DS4Windows? If you downloaded 3.2.18 directly from GitHub then you probably downloaded it a bit too early. The file that states which version is the latest release (newest.txt) is usually uploaded shortly after creating a new release on GitHub. Also, GitHub seems to slightly delay when file mirrors are updated so there might be a chance that the server you are connecting to has the old version of the file. Give it a little time and the problem should go away.

**Comment by Xottab-DUTY** [comment]
> Did you mean a GitHub notification or the standard alert in DS4Windows?

The first one. An email notification.

> Give it a little time and the problem should go away.

Yes, it has gone even before I've opened this issue.

But what I'm suggesting here is to change the version check so that if the newest.txt contains an older version than the application locally installed, it wouldn't show that update window.
