### ISSUE TITLE
how can i manage to change the name of the ensambly

### ISSUE THREAD

**Issue by fromdr29** [Ryochan7/DS4Windows#3146]
hi, can someone tell me pls why do i get this errror. ** FileNotFoundException: Could not load file or assembly 'DS4Windows, Culture=neutral, PublicKeyToken=null'= ** when i change the name of the ensambly wich is the ds4windows to some random name and i compile it and executes it executes verywell but when i click in edit profile i get that error.

_Originally posted by @fromdr29 in https://github.com/Ryochan7/DS4Windows/discussions/3142#discussioncomment-7436058_

**Comment by Ryusennin** [comment]
Please change the title...

**Comment by Ryochan7** [comment]
There are some resources loaded using a Uri with the assembly name; I think some ImageSource instances are created using assembly resource uris. You will need to find all `DS4Windows;component/Resource` strings in the project and replace with the relevant assembly name; VS would make that task fairly easy with a basic Find and Replace.

Those are definitely old string as the DS4Windows.Global class includes a RESOURCES_PREFIX constant that could be used instead; I probably added that around the time of porting the code to .NET 6 but I cannot be sure. That string is located rn at DS4Windows\DS4Control\ScpUtil.cs:L583. You will also need to change the ASSEMBLY_RESOURCE_PREFIX const string right above RESOURCES_PREFIX as it uses DS4Windows for the assembly name; ProfileEditor.xaml.cs uses that const heavily.

At some point I should probably update the relevant code to use the const RESOURCES_PREFIX instead.

**Comment by fromdr29** [comment]
> There are some resources loaded using a Uri with the assembly name; I think some ImageSource instances are created using assembly resource uris. You will need to find all `/DS4Windows;component/Resources` strings in the project and replace with the relevant assembly name; VS would make that task fairly easy with a basic Find and Replace.
> 
> Those are definitely old strings as the DS4Windows.Global class includes a RESOURCES_PREFIX constant that could be used instead; I probably added that around the time of porting the code to .NET 6 but I cannot be sure. That string is located rn at DS4Windows\DS4Control\ScpUtil.cs:L583. You will also need to change the ASSEMBLY_RESOURCE_PREFIX const string right above RESOURCES_PREFIX as it uses DS4Windows for the assembly name; ProfileEditor.xaml.cs uses that const heavily.
> 
> At some point I should probably update the relevant code to use the const RESOURCES_PREFIX instead.

TY!!!!!!1

**Comment by Ryochan7** [comment]
https://github.com/Ryochan7/DS4Windows/commit/750f2faefc4916645b6785f89c9c3c26f0df50fe
