### ISSUE TITLE
Touchpad as Trigger for Gyro doesn't work

### ISSUE THREAD

**Issue by Basfet** [Ryochan7/DS4Windows#3154]
**Describe the bug**
DS4 is not detected Touchpad as Trigger for Gyro On/Off. If you select "Share" as the trigger, Gyro will switch when you press the touchpad.

**To Reproduce**

1. Plug DualSense(DS4) controller. Edit current profile. Gyro -> Output Mode - "Mouse" -> Triggers - "Touchpad Click"
2. Press on Touchpad -> Nothing happens
3. Gyro -> Output Mode - Mouse -> Triggers - "Share"
4. Press on Touchpad -> Gyro controls the mouse

**Desktop:**
 - Controller: Sony DualSense controller, DS4(v1) controller
 - OS: Windows 10
 - DS4Windows Version 3.2.19

**Additional context**
"Options" button is not working as Trigger for Gyro too. I checked versions 3.2.13-3.2.19, the issue exists.

**Comment by Ryochan7** [comment]
Confirmed. None of the Touchpad related triggers work anymore. That is a problem for me as sometimes I do use Finger on Touchpad as a Gyro Trigger.

Adding the DualSense Edge specific buttons probably screwed up the ids in the list.

**Comment by Ryochan7** [comment]
The result of a couple of botched commits. Earliest one seems to be commit b3dbd8483154a98358a5dc53460322c5c6ebed57. The problem is actually due to the placement of the JoyCon SideL and SideR buttons in the list.

**Comment by Ryochan7** [comment]
https://github.com/Ryochan7/DS4Windows/commit/caa073194f964d8bfee1e4a1c30ed364fc451a62

**Comment by Ryochan7** [comment]
Problem has been fixed
