### ISSUE TITLE
Touchpad Passthru is no longer supported after ViGEm Bus Driver Update

### ISSUE THREAD

**Issue by Serfrost** [Ryochan7/DS4Windows#3158]
**Describe the bug**
ViGEm Bus 1.22.0 / 1.21.442.0 is not being detected as supported for Touchpad Passthrough. 
Cannot use the touchpad after updating.

**To Reproduce**
1. Install the latest ViGEm driver
2. Edit your controller profile in DS4Windows
3. Open the Touchpad Tab
4. Set the Output Mode to Passthru

**Expected behavior**
As the driver is newer, and assuming nothing has changed, Passthru should be available.

**Screenshots and Logs**

<img width="707" alt="Passthru" src="https://github.com/Ryochan7/DS4Windows/assets/19275542/643f0a93-cb00-46f4-888d-da3677727a9d">

Log File: [Log.txt](https://github.com/Ryochan7/DS4Windows/files/13327074/Log.txt)

**Desktop:**
 - Controller Make and Model: Sony Dualsense (CFI-ZCT1W) - Firmware 0402
 - OS: Windows 11 Pro 23H2
 - DS4Windows 3.2.19

**Comment by Ryusennin** [comment]
For info: the 1.22 driver is supposed to be exactly the same as the previous version, only the installer has changed.

**Comment by Ryochan7** [comment]
That window does not check for the installed ViGEmBus version. It appears regardless. The message was initially added when ViGEmBus first introduced Touchpad Passthru as an option to let people know only certain driver versions supported it.

I guess I could include a check to not render the message if the minimum ViGEmBus version is installed but it did not matter to me before.

**Comment by Serfrost** [comment]
Ah, interesting. I guess the reason this confused me is because my touchpad has stopped responding to input, whereas it used to work correctly.  Guess I'll need to troubleshoot.

**Comment by Ryochan7** [comment]
https://github.com/Ryochan7/DS4Windows/commit/e2617179542780504a480be04216b252a5f87a9a
