### ISSUE TITLE
8BitDo Lite 2, connected over Bluetooth in Switch mode, fails to initialize in DS4Windows

### ISSUE THREAD

**Issue by shockdude** [Ryochan7/DS4Windows#3159]
**Describe the bug**
DS4Windows fails to initialize an 8BitDo Lite 2 controller in Switch mode when connected over Bluetooth. It should be detected as a Switch Pro controller.

**To Reproduce**
1. Connect 8BitDo Lite 2 to PC over Bluetooth in Switch mode.
2. Launch DS4Windows
3. Controller fails to initialize

**Expected behavior**
Controller is recognized as a Switch Pro controller.

**Screenshots and Logs**
[ds4windows_log_20231114.4.txt](https://github.com/Ryochan7/DS4Windows/files/13358877/ds4windows_log_20231114.4.txt)

**Desktop (please complete the following information):**

 - Controller Make and Model: 8BitDo Lite 2 (80KA)
 - OS: Windows 10 Pro 22H2
 - DS4Windows Version: 3.2.19

**Additional context**
8BitDo Lite 2 works with DS4Windows when wired, just not over Bluetooth.
[ds4windows_log_20231114.7.txt](https://github.com/Ryochan7/DS4Windows/files/13358908/ds4windows_log_20231114.7.txt)
~~8BitDo Lite 2 works with Steam Input, both wired and Bluetooth, properly detected as a Switch Pro controller.~~ seems Steam Input no longer recognizes it over Bluetooth, it worked fine like a month ago.

**Comment by Ryochan7** [comment]
I do not have access to that hardware so I have no way to support it.

**Comment by shockdude** [comment]
I was able to get the 8BitDo Lite 2 to work with both Steam & DS4Windows, after significant effort. I think this is an 8bitdo hardware/firmware issue, it just fails to connect to the PC consistently.
You first have to pair the controller correctly with the pairing button (not just the Home button), and then you have to flip the S/D switch several times until the controller finally re-connects to the PC in Switch mode properly.
