### ISSUE TITLE
[Request] Option to tap touchpad to activate assignment, instead of clicking

### ISSUE THREAD

**Issue by felixlang** [Ryochan7/DS4Windows#316]
Simply the ability to activate an assignment by tapping on the touchpad, instead of having to click it all the way down. So for example I could assign tapping the right touchpad as the Enter key, tapping left touchpad for the Space bar, and so on.

It seems like a minor thing, but that little bit of effort saved adds up over time if we use the touchpad a lot, which I typically do.

**Comment by Cupbox** [comment]
I'm interested in this as well. I use a DS4 for Anki and it's wearing down my joints. Option to remap taps from right and left click to remappable buttons would be very welcome.

**Comment by Ryochan7** [comment]
That feature might be feasible but it might be hard to find a place to stick that functionality in the code. I can see how extensive use of the trackpad click button could wear on the hand a bit. A few other options would probably be desired to help tune the feature. Tap Press, Tap Release, and Tap Threshold activation would be some obvious options that would be useful.

**Comment by Cupbox** [comment]
The Tap press and release sounds very convenient. By any chance, are the other keys mappable like that? (Triangle-down, Triangle-release) and the like?

**Comment by Ryochan7** [comment]
That is not possible with the current mapping system. Most of the mapping system would likely have to be completely re-written in order to allow for a more complex mapping system. I have spent time working on other problems that would be easier to tackle with the current code base. Most of the time, I try to use Mixed mode (XInput + Mouse) so a lot of games would be playable with a fairly simple profile. More complex mappings would be much more useful for playing pure KB+M driven games although there are some use cases for XInput customization using Commands.

**Comment by Ryusennin** [comment]
Horizon: Zero Dawn on PS4 allows to temporarily display the HUD by tapping the touchpad, which is a great feature (ie. no constant HUD in your face while exploring around).

On the PC version, unfortunately, you need to hold either the left touchpad or the H key for about 350 ms, which quickly becomes tiring. I've somehow replicated the PS4 behaviour in a custom profile by simply assigning the keyboard HUD function (H key) to swipe up, and it works rather nicely, albeit with some tolerable input lag.

If the touchpad tap could be supported in DS4W, that would be even better.

**Comment by Ryochan7** [comment]
Trying this out now and I am not sure I like it. Especially with the amount of play that can occur with the Touchpad on the initial touch, my initial idea did not pan out so well. At this point, I find that initiating a Mouse Button press on Tap Release with a small Tap Threshold seems to work okay. A small displacement is checked in the routine to try to determine if a deliberate move has occurred or not.

**Comment by Ryochan7** [comment]
Not going to happen. Maybe if the virtual buttons were only exposed as a separate output mode then there might have been a chance. I doubt people would want to lose Touchpad Mouse support just to not have to press the Touchpad in to activate a virtual button.

**Comment by plane** [comment]
That's too bad.  This is the only feature I miss from Steam Input that seems to be unavailable in DS4Windows.  I would never want my touchpad to act like a mouse, but touch left makes a convenient rear view mirror bind in Rocket League.

**Comment by Ryochan7** [comment]
I could try looking into this again. I pretty much use the DS4 Touchpad as a mouse at all times myself. At least with the Steam Controller and Steam Input, it makes more sense to define a dedicated dead zone and allow all other input to count for the virtual buttons. I cannot remember how Steam Input handles any defined dead zone when it comes to the DS4 Touchpad. Should look into that.

**Comment by Ryochan7** [comment]
This feature was finally added in version 3.1.7 released on 2022-10-12. I do not use the feature in any of my profiles though. Kind of a waste really.

**Comment by Ryusennin** [comment]
A feature is a feature. Thanks for the hard work 👍
