### ISSUE TITLE
Feature Request: Support Nacon Revolution 5 Pro

### ISSUE THREAD

**Issue by svensvond** [Ryochan7/DS4Windows#3160]
I would like to see the latest Nacon PC / PS4 / PS5 Gamepad supported - like it was for Nacon Revolution Pro.

**Comment by doenergit** [comment]
is this still a problem or was there a fix/workaround? my friend got the controller and nothing works

**Comment by svensvond** [comment]
@Ryochan7 Is it really? I dont see a commit for this - nor changelog.
