### ISSUE TITLE
i need a macbook pro m1 or m2 version to customize my ps5 controller please

### ISSUE THREAD

**Issue by dylanshees** [Ryochan7/DS4Windows#3164]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots and Logs**
If applicable, add screenshots to help explain your problem. Also, please add the most
log file (ds4windows_log.txt) from the Logs folder in your DS4Windows config folder.

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: [e.g. Windows 10 Pro Build 2004]
 - DS4Windows Version [e.g. 3.0.3]

**Additional context**

**Comment by Ryochan7** [comment]
I NEED employment. That is never going to happen either.
