### ISSUE TITLE
[Minor] Dark theme "Unload Trigger" text is white on a white background

### ISSUE THREAD

**Issue by LoScienzo** [Ryochan7/DS4Windows#3167]
**Description**
The header of the button list when setting the Unload Trigger of a "Load a profile" special action has white text on white background when using the dark theme.

**To Reproduce**
1. (Using dark theme)
2. Go to "Profiles"
3. Edit a profile
4. Go to "Special Actions"
5. Create or edit an action
6. Select the "Load a profile" action
7. Click on "Set Unload Trigger"
8. See the header of the button checkbox list now having white-on-white text

**Expected behavior**
The text should instead be white on a dark background, like the "Trigger" header is.

**Screenshots**
<details>
<summary>This is how the regular trigger header looks like</summary>
<img src="https://github.com/Ryochan7/DS4Windows/assets/32672927/c481e410-0efa-484c-be33-4940943e865f" alt="Regular trigger header"/>
</details>
<details>
<summary>This is how the regular trigger header looks like on mouse hover</summary>
<img src="https://github.com/Ryochan7/DS4Windows/assets/32672927/d7788d4e-d08a-4de8-9223-cfb40cb454a7" alt="Regular trigger header hover"/>
</details>
<details>
<summary>This is how the unload trigger header looks like</summary>
<img src="https://github.com/Ryochan7/DS4Windows/assets/32672927/a05e2163-6cca-4d7e-8c54-691d326a1716" alt="Unload trigger header"/>
</details>
<details>
<summary>This is how the unload trigger header looks like on mouse hover</summary>
<img src="https://github.com/Ryochan7/DS4Windows/assets/32672927/9b9e9583-a177-471b-b1c4-c5f5d2c16a11" alt="Unload trigger header hover"/>
</details>

**Desktop:**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2E)
 - OS: Windows 10 Pro 22H2 Build 19045.3693
 - DS4Windows Version: 3.2.19

**Comment by Ryochan7** [comment]
https://github.com/Ryochan7/DS4Windows/commit/f4a41e340ae6e9f19bfb7dba229b0c1aaf597bb5
