### ISSUE TITLE
[Request] Remember auto profile settings after a game is uninstalled

### ISSUE THREAD

**Issue by felixlang** [Ryochan7/DS4Windows#317]
Currently, if an auto profile is assigned to a game's executable and that game is later uninstalled or deleted, then the next time it is installed the auto profile setting will need to be assigned again.

It would be very helpful if DS4Windows remembered this setting so that when a game is re-installed, the auto profile is automatically re-assigned without needing to go through the process again.

**Comment by Ryochan7** [comment]
I don't use the auto profile system so I had to check this out. DS4Windows does purge any auto profile entries upon startup if the executable no longer exists. I don't think that I like that behavior either so that will probably be changed.
