### ISSUE TITLE
Battery meter broken

### ISSUE THREAD

**Issue by Redyn** [Ryochan7/DS4Windows#3177]
**Describe the bug**
DS4Windows tells me that my Dualshock 3's battery is at 100% at all times

**To Reproduce**
I just connect my DS3 via bluetooth as usual

**Expected behavior**
Battery should show the correct percentage

**Desktop (please complete the following information):**
Dualshock 3
Windows 10
DS4Windows 3.2.20 (also tried 3.2.17; same result)

**Comment by Ryochan7** [comment]
I have rarely used my DualShock 3. I did not write the DS3 device reader so my understanding of the process is limited; [sunnyqeen](https://github.com/Ryochan7/DS4Windows/commits?author=sunnyqeen) is the writer of the DS3Device class. AFAIK, DS4Windows does not directly interact with the DS3 hardware but reads the information populated by the DsHidMini driver based on how it interprets the custom input packets sent from the controller. The battery level routine seems to be fine in the ReadInput method.

I have never tried to play with the DualShock 3 in Bluetooth mode as I did not want to install the extra driver (BthPS3) needed to make it work. I do not have DsHidMini driver installed currently as that driver slows down my PC a lot. I only have that driver installed while testing. Hopefully I can run down the battery on my DualShock 3 and test this case via USB. I will have to try that later.
