### ISSUE TITLE
[Question] Support gyroscope for The Legend of Zelda: Breath of the Wild

### ISSUE THREAD

**Issue by narutoxboy** [Ryochan7/DS4Windows#319]
Hi bro
Thank you for update version of DS4Windows.
I have a question: can you support gyroscope for aim in The Legend of Zelda Breath of the Wild.
Thank you.

**Comment by juliankid** [comment]
Its supported, download this http://ryochan7.xyz/ds4windows/test/DS4Windows_1.4.120_UdpServer_x64.zip paste it on ds4windows main directory, and it will show up on cemu

**Comment by narutoxboy** [comment]
Many thank <3

**Comment by Ryochan7** [comment]
That feature is very experimental. I don't use that feature myself and even having the option available impedes normal XInput emulation. That is the main reason that feature is still in its own build.
