### ISSUE TITLE
"Enhanced Wireless Controller for Nintendo Switch" not being detected

### ISSUE THREAD

**Issue by TheLadForTheJob** [Ryochan7/DS4Windows#3190]
This controller won't be detected by ds4windows for some reason. I doubt it would help but here is a link to the controller:

https://www.powera.com/p/nintendo/nintendo-switch/controllers/wireless/enhanced-wireless-controller-rechargeable-for-nintendo-switch-black-1509988-03/

Also, the controller is wireless only, it doesn't output any data through the cable, only through bluetooth. Rewasd and steam seem to pick it up, so its not completely undetectable but ds4windows doesn't work with it.

**Comment by Syonico** [comment]
+1 - I have the wired version of this exact controller. Was coming here to ask the same thing.

**Comment by Ryochan7** [comment]
This will not lead to a pull request so it is a waste of time. I should probably just go against my word and close this repo early. Making requests that require money to solve.
