### ISSUE TITLE
Gyro server issue

### ISSUE THREAD

**Issue by IceLancerSR** [Ryochan7/DS4Windows#3198]
Hello, something is wrong with new update and Gyro server.
I tried DSU control test.  and a few games and gyro is not working.

So i had to go and turn off/on UDP server in ds4windows and gyro works again.
That is until i switch profiles. Gyro stops working again. To fix it i have to turn off server and start again.

win11 x64
DS4V2

DS4Windows_3.2.21_x64 works fine!
DS4Windows_3.3.0_x64 Does not

**Comment by Ryochan7** [comment]
Sort of experiencing this on my end. Looks like it can no longer handle a client disconnect. When it comes to switching profiles, that works on my end when running PadTest. It might depend on the client you are connected to.

When a new profile is being loaded, the Report event is not being fired anymore to keep some routines (mapping, lightbar) from being run so the reset default settings will not be used. The UDP delegate is not being run either so there will be a lapse between packets. Maybe a client would drop the connection after a shorter period of time than PadTest.

I'll look into it.

**Comment by Ryochan7** [comment]
Not sure why but it looks like Microsoft changed the way SocketAsyncEventArgs are used and they cannot be reused. At least that is the case when it comes to different connections. Changing the RemoteEndPoint later does not seem to matter. Using a new SocketAsyncEventArgs instance with each call to Socket.SendToAsync allows the UDP server to work when a client disconnects and then reconnects.

The instance reuse was mainly done to reuse the byte array buffer. Looks like the byte array will have to be handled in the UdpServer class and then set for use in SocketAsyncEventArgs when created. I will have to check memory usage as well.

**Comment by Ryochan7** [comment]
https://github.com/Ryochan7/DS4Windows/commit/483c366daa1b38fba52380051cd7d4aafb44a820

**Comment by Julinkk** [comment]
How do we install this update please?

**Comment by IceLancerSR** [comment]
> How do we install this update please?

Be patient, he will compile release

**Comment by Julinkk** [comment]
Ok no problem, I really like this program and I use it a lot.
And thank you for offering it for free.

**Comment by Ryochan7** [comment]
Version 3.3.1 is up. I wanted to get an update out sooner but my time is not my own; been that way almost this whole year.

https://github.com/Ryochan7/DS4Windows/releases/tag/v3.3.1

**Comment by Julinkk** [comment]
I still have the problem, am I missing something?

**Comment by IceLancerSR** [comment]
Dunno works fine for me. I can switch profile no  problem fyro keeps working. All good
Thanks

**Comment by IceLancerSR** [comment]
> Version 3.3.1 is up. I wanted to get an update out sooner but my time is not my own; been that way almost this whole year.
> 
> https://github.com/Ryochan7/DS4Windows/releases/tag/v3.3.1

There is a new issue now , tho.
My gyro says that my gamepad is in spinning constantly..and it wont stop, its turning to the left

**Comment by Julinkk** [comment]
Ok weird, I still have this problem of profile which remains stuck on Default.
