### ISSUE TITLE
Launch Program With Profile Not Working

### ISSUE THREAD

**Issue by shinra358** [Ryochan7/DS4Windows#32]
Just tried to make Bigbox launch with turning the controller on with said feature and it's not working. Also, if you fix it, make sure it doesn't launch the same program again if the process is still in the process list when the controller is initiated again. Thanks in advance.

**Comment by Ryochan7** [comment]
I have not played with that option. Looks like that will have to be tested.

**Comment by Ryochan7** [comment]
The feature did work for the most part. All I ended up doing was making some tweaks. The first being that the process now launches from the executable's directory. Also the process list is checked to make sure the process is not already running before attempting to launch the process.

**Comment by Ryochan7** [comment]
A new release is available with this change included.

https://github.com/Ryochan7/DS4Windows/releases/download/v1.4.69/DS4Windows_1.4.69_x64.zip

**Comment by shinra358** [comment]
Thanks, but there's a problem. It autostarts with dswindows. It's supposed to just autostart when a controller comes on with a profile you set the option to on with.

**Comment by Ryochan7** [comment]
The way it is set up now, DS4Windows will typically launch the program whenever a profile is loaded. Unfortunately that will happen when DS4Windows first launches. Changing the behavior should be a matter of adjusting one flag upon startup.
