### ISSUE TITLE
Trojan:Win32/Wacatac.H!ml

### ISSUE THREAD

**Issue by Luke56784** [Ryochan7/DS4Windows#3200]
file: C:\Users\...\AppData\Local\Temp\DS4WinInstall\apps\ConsoleApplication2.exe

Windows Defender does not let me install the latest version.

**Comment by Ryochan7** [comment]
Did multiple updates and scans on various systems. Seems like a false positive to me. So again, this is a problem that would require money to truly solve; I would need a signing certificate to bypass many false positives. Society has deemed I am not worthy.

**Comment by Ryochan7** [comment]
Also, quick notice. Going to have to delete this thread as well so Google does not index it and it gets used for various slander campaigns against me. Already several in the DSX group
