### ISSUE TITLE
Dualsense Edge Not Working 

### ISSUE THREAD

**Issue by Zmorasch** [Ryochan7/DS4Windows#3201]
My Dualsense Edge Controller's Paddle inputs are not correct for whatever reason; the right once is just stuck to R1 and the left one is R2 and i cannot change them at all. When looking at the raw inputs it is actually only inputting as those

 - Controller Make and Model: Sony DualSense Edge
 - OS: Windows 11
 - DS4Windows Version 3.0.3

**Comment by Ryochan7** [comment]
I am just going to consider this a flex rather than a real question. I obviously do not own a DualSense Edge and have no means to get one.

**Comment by Zmorasch** [comment]
I’m sorry if it came off as a flex, but it’s an actual issue I’m having and wanted to know if there were any possible fixes
