### ISSUE TITLE
Says .NET install was not found despite .NET being installed

### ISSUE THREAD

**Issue by github-account1111** [Ryochan7/DS4Windows#3202]
**Describe the bug**
I have .NET 6 installed, but DS4Windows seems to be unable to find it.

**To Reproduce**
1. Run the installer

**Expected behavior**
The install goes through.

**Screenshots and Logs**

![image](https://github.com/Ryochan7/DS4Windows/assets/5728319/d4f5ea74-c898-4d3c-a444-62e10fb4865d)

```
> winget list | Where-Object { $_ -match 'net' }
Microsoft Windows Desktop Runtime - 6.0.… Microsoft.DotNet.DesktopRuntime.6          6.0.25                      winget
```

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: Windows 10 21H2
 - DS4Windows Version 3.3.0

**Additional context**

**Comment by Ryochan7** [comment]
> .NET 8 release. Waste of time really. Make sure to download and install the appropriate .NET 8 Desktop Runtime package depending on the build you are using

https://github.com/Ryochan7/DS4Windows/releases/tag/v3.3.0

Did not get around to updating the README. Better do that

**Comment by github-account1111** [comment]
I installed a bunch of things mentioning .NET 8 and I'm still getting the same error.

```
> winget list | Where-Object { $_ -match 'net' }
Microsoft ASP.NET Core 8.0.0 - Shared Fr… Microsoft.DotNet.AspNetCore.8              8.0.0                       winget
Microsoft .NET Runtime - 8.0.0 (x64)      Microsoft.DotNet.Runtime.8                 8.0.0                       winget
Microsoft .NET 8.0.0 - Windows Server Ho… Microsoft.DotNet.HostingBundle.8           8.0.0                       winget
Microsoft .NET Runtime - 8.0.0 (x86)      Microsoft.DotNet.Runtime.8                 8.0.0                       winget
Microsoft ASP.NET Core 8.0.0 - Shared Fr… Microsoft.DotNet.AspNetCore.8              8.0.0                       winget
Microsoft Windows Desktop Runtime - 6.0.… Microsoft.DotNet.DesktopRuntime.6          6.0.25                      winget
```

**Comment by github-account1111** [comment]
@Ryochan7
