### ISSUE TITLE
Bluescreen when connecting a controller

### ISSUE THREAD

**Issue by Seeloewen** [Ryochan7/DS4Windows#3204]
**Describe the bug**
When I'm trying to connect my DS4 v1 Controller my PC suddenly freezes or bluescreens. This has only been happening since early December. I've added added 3 dump files of the past crashes, all of them seem to be caused by some issue with ntoskrnl.exe. I suppose that's a driver issue. I'll monitor it further over the next couple of days and add new information if I find any.  Also, I'm connecting my controllers over bluetooth, not sure if the issue also occurs when using USB. I'm using a seperate cheap bluetooth stick, which has always worked in the past few years though.

**Screenshots and Logs**
I don't have the DS4 Windows log, however here are the dump files of the bluescreens:
[120723-15640-01.dmp](https://github.com/Ryochan7/DS4Windows/files/13727850/120723-15640-01.dmp)
[121223-15296-01.dmp](https://github.com/Ryochan7/DS4Windows/files/13727851/121223-15296-01.dmp)
[122023-15281-01.dmp](https://github.com/Ryochan7/DS4Windows/files/13727852/122023-15281-01.dmp)

**Environment:**
 - Controller Make and Model: Sony DS4 v.1
 - OS: Windows 11 Home 23H2 Build 22631.2861
 - DS4Windows Version 3.3.0
 - Processor: Intel Core i7-9700KF
 - Graphics Card: Nvidia Geforce RTX 2070 Super
 - RAM: 32GB (4x 8GB) DDR4 2666MHz

**Comment by Ryochan7** [comment]
I'm not even going to bother looking into this. ViGEmBus is a dead driver and you people decided I am not allowed the autonomy to go my own path. Bringing up a problem that would require a good sum of money (yearly) to really solve while knowing I am a hobo. And people wonder why I want to quit.

**Comment by Seeloewen** [comment]
This might be the biggest overreaction I've seen so far. Not once have I said anything about you going your own path. How should I have known that it is a extensive problem that requires a bunch of resources to solve? It could've very well been a simple fix as well. I was simply asking for help, but I guess you're not in the mood for that.
