### ISSUE TITLE
questions, requests and problems

### ISSUE THREAD

**Issue by HighPingTek** [Ryochan7/DS4Windows#321]
hello, first of all thanks for the excellent program, then

1. Is it normal that the inputlag is lower in bluetooth than in the cable? 1.2ms vs 4ms
2. Is it possible to connect the cable to the controller while it is running in bluetooth and automatically switch to wired mode and unplugging the cable back to the bluetooth?
3. If you start a game that supports dualshock 4 natively without active ds4windows you will lose the pairing with bluetooth
4. Is it normal for my analogs to behave in this way without me touching anything? I bought the controller yesterday,my old 9-year-old dualshock 3 does not have this problem
https://streamable.com/vozm2
https://streamable.com/5flye
https://imgur.com/a/cTDNuqS

**Comment by Ryusennin** [comment]
1. Recommended BT rate is 4 ms.
2. Have you tried the Quick Charge option in the Settings tab?
4. DS4 controllers are very sensitive, you should set some amount of dead zone for the analog sticks (I'm using 0.10).

**Comment by HighPingTek** [comment]
1.can I decrease the latency below 4ms when connected with the cable?
2.fast charging was what I wanted, thanks
3.do your analogs also behave this way? I would like to have absolute certainty that it is not a problem

**Comment by Ryochan7** [comment]
1. No. That rate is set by the DS4 hardware and it cannot be changed. The Sony adapter has a locked poll rate of 8 ms. The DS4 hardware only allows for a BT connection to have a configurable poll rate.
2. Cool
3. It is possible to have some small jitter when the stick is supposedly centered; that behavior is visible when using the regular DirectInput device as well. You probably want to add a small dead zone to the analog stick; I currently prefer 0.10 for LS and 0.09 for RS. There are cases when you might want to have an even smaller dead zone. You might be able to get away with 0.05 for a dead zone setting. You might also want to edit the anti-dead zone for the sticks depending on the dead zone setting for a game; I currently prefer about 0.18 for LS and 0.20 for RS. I have been thinking about either no longer using 0.00 as the default or maybe adding an implicit dead zone again.

**Comment by HighPingTek** [comment]
1.ok, is it possible to see the delay of the ps3 controller that I use with motionjoy?
I do not want to increase the dead zone, I like to have very sensitive sticks, I get the jitter even if the analogs are not centered, I will replace the controller
https://streamable.com/u8grd

**Comment by HighPingTek** [comment]
it is possible to change color when there is a high delay
and decrease the brightness when the battery reaches the established percentage?

**Comment by HighPingTek** [comment]
new problem,the automatic profile you assign to an application will be disabled if you turn the controller off and on again during the game

**Comment by Ryochan7** [comment]
If I remember correctly, DS4Windows assigns an auto profile under a temporary basis so the actual profile is not listed in the main configuration file. I would hope that DS4Windows would only temporarily use the last manually selected profile before switching to the auto profile again but I guess it is not.

**Comment by Ryochan7** [comment]
Some minor tweaks to the code allow that functionality to work although it seems to cause lag in the application. I will give this another try and see if I can make something acceptable.

**Comment by Ryochan7** [comment]
I tried and failed. Looks like the auto profile hotplug problem will continue to exist.
