### ISSUE TITLE
Share and Options buttons can't be remapped to Touchpad

### ISSUE THREAD

**Issue by Ryusennin** [Ryochan7/DS4Windows#33]
One great feature of DS4Windows is the possibility of directly assigning the Touchpad buttons (Left, Right, Upper) to any other button/trigger of the controller, without configuring tedious macros.

In the last 1.4.68 build however, it works for all buttons except Share and Options. Those two buttons can be remapped to the Touchpad in the Profile tab, but they don't have any effect ingame, not even in the Windows Control Panel.

For example I can assign Triangle to Right Touch and it will work as intended in the Control Panel. All other buttons/triggers/sticks will work too, except Share and Options.

**Comment by Ryochan7** [comment]
This issue affected all mapped action bindings for those buttons. This problem was enough to justify putting out a new release.

**Comment by Ryusennin** [comment]
It's all green, thanks!
