### ISSUE TITLE
Input delay 15ms with cable 18ms with bt

### ISSUE THREAD

**Issue by nycoh** [Ryochan7/DS4Windows#331]
So far i tried everything reinstalling all trying diferent drivers, always the same result 15ms delay with cable and 18 with bt. im using a new CUH-ZCTU controller and i cant find why im getting this input delay

**Comment by jonaaa20** [comment]
I have no problems here, 4ms on BT/Cable here, maybe the problem is on your Hardware/USB.

**Comment by nycoh** [comment]
i tried all my computer usbs, im gonna format my had drive now and see if that solves it

**Comment by nycoh** [comment]
I got my and on an other computer, same problem, is the controller malfunctioning or it need some kind of update, i never conected it to a ps4

**Comment by jonaaa20** [comment]
Probably is your DS4, mine is working fine.

**Comment by nycoh** [comment]
Close this, the controller was a fake or defectuous i bought CUH-ZCT2U and now i have 4ms calbe 1.30ms with bt with 6ms spikes
