### ISSUE TITLE
Controller doesn't work after you disconnect and reconnect it (USB/Bluetooth)

### ISSUE THREAD

**Issue by jonaaa20** [Ryochan7/DS4Windows#336]
I'm having this problem on GTA San Andreas and RetroArch (emulator), when you connect it for the first time, it works, but when you disconnect it and reconnect it, same problem occurs on USB and Bluetooth, anyway, when you reconnect it and when you go to RetroArch or GTA: SA, the Controller just doesn't work... This problem also happens on older DS4Windows versions...

How to "fix" it? Restart the system and it will work again but i can't disconnect it because if i disconnect the controller, it doesn't work on these applications.

I'm using the Windows 10 x64 1803 and the latest DS4Windows with HIDGuardian (latest).

**Comment by Ryusennin** [comment]
I suppose you're using the standard SCP version. Have you tried the ViGEm build available on the front page?

**Comment by jonaaa20** [comment]
Yes sir, i am using the vigem build and the issue persists.

**Comment by jonaaa20** [comment]
Problem solved, i did a clean install of Windows (again) and instead of installing the SCP Driver, i've installed VIGEm Bus Driver and HIDGuardian and the problem was solved, probably a driver conflict or something else...

Case closed.
