### ISSUE TITLE
Unbinding stubborn games

### ISSUE THREAD

**Issue by vvilkommen** [Ryochan7/DS4Windows#337]
First, hello again and thank you for this wonderful software!

Ok, I've recently started playing a game that has unmodifiable button controls, but also support for mouse keyboard input/play.

Would it be possible to make it so that ds4w could set an arbitrary button(s) as "unbound*", like unbound, but only for a specific .exe process (like a shift modifier, but with .exes)? That way I could prevent the game from recognizing button presses, but allow a program like xpadder or antimicro to continue to recognize button presses so it can emulate keyboard presses within the game.

edit: I was going to suggest the alternative ability of ds4w *only* recognizing input from a specific process, like joytokey, but I don't know how that would work out since those programs are not that active process when playing a game.

If this is possible, that would be awesome because it would finally allow ds4w to fully customize stubborn games with hardcoded buttons, no stick axis flipping, no mouse flipping, and all the little nuisances to playing a game in a way comfortable to the player, I think.

**Comment by Ryochan7** [comment]
You might want to try setting up some auto profiles. That way, DS4Windows can change the currently enabled profile depending on the game that you are currently playing. You can use different profiles to change bindings, unbind certain buttons if they are not needed or unplug the virtual XInput controller if using KB+M exclusively.

If it weren't exclusive mode problems then using DS4Windows at the same time as Xpadder or antimicro might be more useful. Xpadder or antimicro would need access to the DS4 DirectInput controller but that can present problems with some games. Also, losing access to the DirectInput controller when using BT makes using multiple software mappers impossible in that case. This type of functionality would be easier on Linux and I had done it before using xboxdrv and antimicro at the same time for playing some games; Shadow Warrior 2013 is one game that I can remember playing that way.
