### ISSUE TITLE
Issues if more them 1 Multi-Action Button is activated in the same profile

### ISSUE THREAD

**Issue by pralima87** [Ryochan7/DS4Windows#34]
## Description

If more the 1 Multi-Action Button is selected only the first in the "Special Actions" list will work properly
Changing the order of the "Multi-Action Button" in the list will also change the results. 
So the first in the list will be always be the result of TAP and HOLD in all the other Multi-Action Buttons created.
The Double-Tap function will still work regardless of the number of Multi-Action Buttons Selected.
So maybe the fix is in the Double-Tap function itself.

## Expected behavior
Each Multi-Action Button should work independently and return the set macro.

## Actual behavior
Only the fist Multi-Action Button in the list is working 100%

## Steps to reproduce the bug
**Multi-Action Button 1** - TAP "a" / Hold "b" / DoubleTAP "c"
**Multi-Action Button 2** - TAP "d" / Hold "e" / DoubleTAP "f"
**Multi-Action Button 3** - TAP "g" / Hold "h" / DoubleTAP "i"

**Multi-Action Button 1** Returns - "a" / "b" / "c"
**Multi-Action Button 2** Returns - **"a"** / **"b"** / "f"
**Multi-Action Button 3** Returns - **"a"** / **"b"** / "i"

So the result shows that the only DoubleTAP is working when more them 1 Multi-Action Button is set.

## Version/Commit
1.4.71

**Comment by pralima87** [comment]
@Ryochan7 Sorry to bother but did you take a look at this?

**Comment by Ryochan7** [comment]
I'm sorry but I was looking into other issues for the last release. Also, I have been using DS4Windows to finally play through a couple of games.

Looking at the code now, the problem stems from multiple actions using the same shared variables between all multi-action buttons. Although there is likely a better approach, changing the shared bool variables to dictionaries to account for different actions is enough to make multiple multi-action buttons work properly.

**Comment by pralima87** [comment]
Thanks for the answer! I was not sure you had time to see this report!

**Comment by Ryochan7** [comment]
Here is a test build that you can try out.  I ended up just adding some new fields to the SpecialAction class. That should be much faster than using dictionaries for this functionality.

https://drive.google.com/open?id=0B6yGHDx0CFzDZUp4djhYeGN0bjA

**Comment by pralima87** [comment]
Yep! Working fine! tested with 4 multi-action buttons and all performed as expected ;)
cheers!

**Comment by Ryochan7** [comment]
I might have to move some time fields over since there are still some shared variables being used across all multi-action buttons. Trying to activate more than one multi-action button at the same time would still not work correctly. That scenario would hardly ever happen though. Thank you for letting me know that it is working for you now.
