### ISSUE TITLE
Setting a custom output curve. 

### ISSUE THREAD

**Issue by Mrcnarine** [Ryochan7/DS4Windows#341]
Good day. I was wondering if it was possible to create my own output curve? I want to do a squaring function where I stretch the circle-ish shape to get a square-ish output. This would be the result https://imgur.com/4LMAKIV

I learned about this squaring function from this http://theinstructionlimit.com/squaring-the-thumbsticks (Attempt 5)

Any help I can get would be very appreciated.

**Comment by Ryochan7** [comment]
I have thought about ways to possibly add custom curve functionality and I believe someone else asked about possibly adding a square option for the sticks before. It might be nice to have that functionality but I don't have an immediate need for it so it might not get implemented anytime soon. My time with DS4Windows is getting more limited lately partially out of frustration with the .NET Runtime; I would be more inclined to try if it weren't for continuous issues. Also, I am using a Steam Controller (using Kozec SC Controller) for my current gaming sessions of Might and Magic 7 so my DS4 controllers have gotten little use lately.

Thank you for the link about the squaring function. The article presents a use case that I had not considered before and it was a good read.

**Comment by Mrcnarine** [comment]
I appreciate you taking the time to explain everything. I also use a Steam Controller for most of my gaming sessions. However, the game I play the most is Rocket League. I have almost 6k hours with the SC but the higher I got in the competitive ranks the worse the SC felt to me. I then heard about a tool that creates a "squared" input border for your controller and I had to try it with the DS4 but it felt fantastic. The tool is called Durazno^2 by MakkaraLiiga based off the original by KrossX.

I tried using a combination of Alia5s GloSC to get the tool working with the SC and it kinda worked but I realized that I'm not going to be able to use all these tools at a LAN event, it's illegal to use so many but just Durazno^2 is legal. Problem is Durazno^2 feels kinda "odd" a lot of time, I don't know how to put it into words for you. 

I just wanted to see if I could get someone to take a shot at implementing this function as well and see how it feels. So, if a day comes and you feel like adding it after all the important things are implemented, i'd be eternally grateful. Thanks again

**Comment by Corrodias** [comment]
Vaguely related, I was hoping to do anti-deadzoning of individual axes rather than a stick as a whole. Dark Souls 2 has a massive deadzone for each axis independently.

**Comment by Ryochan7** [comment]
I spent some time trying out the squaring function. I got it working fine but performance has suffered by introducing it. It probably won't make the cut.

**Comment by Ryochan7** [comment]
Narrowed the problem down a little bit. It seems that the deal breaker is the reference to System.Numerics. Just adding a reference to that assembly is enough to degrade performance by a fair margin. Nothing contained in that assembly has to be utilized in code in order for performance to get worse. Removing the reference fixes performance problems but that means the included Vector2 struct cannot be used.

I tested this using my smaller DS4 controller emulation program.

**Comment by Ryochan7** [comment]
I have been playing with the Square stick problem again. A partial solution is working on my end. Performance is fine and it has been confirmed that the diagonals reach the full square range. That feature might get implemented in the next release of DS4Windows.

https://gist.github.com/Ryochan7/70b5495532b1b0c73393054c0dbf873c

**Comment by Mrcnarine** [comment]
> I have been playing with the Square stick problem again. A partial solution is working on my end. Performance is fine and it has been confirmed that the diagonals reach the full square range. That feature might get implemented in the next release of DS4Windows.
> 
> https://gist.github.com/Ryochan7/70b5495532b1b0c73393054c0dbf873c

That's huge man! Thanks for taking the time to implement it. I look forward to trying it out.

**Comment by austinsky9110** [comment]
Just commenting since I saw on a similar post that said you scrapped this feature so I was wondering what the current status was. This is a #1 feature for me.

**Comment by Ryochan7** [comment]
I haven't gone back to this in over a week. Some issues still remain so the square stick routine has not been incorporated as a feature. The feature does work though and I have made an updated patch on my end. Development will be slower than normal over the next few weeks as I only have one working hand at the moment.

**Comment by Ryochan7** [comment]
Square stick appears to work well enough to incorporate now.

**Comment by Mrcnarine** [comment]
> Square stick appears to work well enough to incorporate now.

I sincerely appreciate you for implementing this feature. You're the best!

**Comment by Ryochan7** [comment]
Luckily this got to a point where I felt comfortable including it. It is a shame that struggles with .NET in general is what ended up holding this back for so long. The actual feature was fairly easy to implement thanks to the sample implementation.

**Comment by Ryochan7** [comment]
Beforehand, the square stick output feature was superfluous. Now, I have finally used it in a profile. Star Wars: Shadows of the Empire played a lot better when using the square stick option for LS. Corner turns were very slow without it so that game is an example of a DirectInput game that expects (1.0, 1.0) output for an analog stick.
