### ISSUE TITLE
Hori Onyx Wireless Controller listed as Unknown Device in Device Manager.

### ISSUE THREAD

**Issue by OnesZero** [Ryochan7/DS4Windows#344]
Hi!

As stated in the title, my controller is listed as an unknown device that apparently has no drivers. (Error Code: 28). Could it be that this device doesn't have any drivers for PC? Because i tried searching the Hardware ID on Google, but nothing came up. I really don't know what to do.

Any information about this would be appreciated.

**Comment by Nu2This** [comment]
Did you install the driver for the XBOX Controller?

**Comment by OnesZero** [comment]
I have Windows 10. So it should be preinstalled. And i have used my Xbox 360 Wired controller on this computer.

**Comment by OnesZero** [comment]
No it's under Other Devices and has a yellow triangle next to it. Kinda like this:

https://www.howtogeek.com/wp-content/uploads/2014/07/device-manager-other-devices-withotu-drivers.png

Just replace "Nexus 4" with "ONYX WIRELESS CONTROLLER"

**Comment by Nu2This** [comment]
I would try uninstalling the ONYX WIRELESS CONTROLLER and then doing a computer restart. After that start DS4Windows and try connecting the controller see where you get then.

**Comment by OnesZero** [comment]
Just tried that and after restart Windows started to automatically started to install the controller but it just ended up the same.

https://user-images.githubusercontent.com/41025580/42516810-1adf5198-8467-11e8-80e1-adc1f33fd272.PNG

**Comment by OnesZero** [comment]
If connected through Bluetooth Windows says that it has paired with it, but DS4Windows can't find it.

**Comment by OnesZero** [comment]
Yeah..... Also seems like this controller won't/doesn't have any sort of support from Hori. This controller seems to be only sold in Europe, and Hori UK Doesn't have any mention of this controller in their PS4 Section. Seems like this case is closed then.
