### ISSUE TITLE
Every updates seems to cause more exclusivity connection problems

### ISSUE THREAD

**Issue by powerpuffboysz** [Ryochan7/DS4Windows#345]
With every update more and more programs that previously worked fine with ds4 Windows cause exclusivity connection problems. I used to be able to have Microsoft edge open and run ds4Windows just fine, but now I have to shut it down every time I want to connect the controller. I can reopen the browser once the controller is paired but it's annoying to have to shut it down if I leave the the controller idle for a few minutes.

**Comment by powerpuffboysz** [comment]
Especially if I have like 20+ tabs open at any given time

**Comment by Nu2This** [comment]
Try HidGuardian

**Comment by pralima87** [comment]
Yeah HidGuardian is a godsend.
Would be great if installing it could me more streamlined

**Comment by jonaaa20** [comment]
Indeed, hidguardian works like a charm.

**Comment by Ryochan7** [comment]
hidguardian is necessary in many cases when the old workaround does not work. .NET seems to handle even minor changes to code very differently so the reliability of the exclusive mode routine is very much subject to change.

**Comment by TristanYoung** [comment]
So, no comments recommending avoiding Edge?  Hehehe.  Someone had to say it.

Definitely, use hidguardian. It solved my exclusive issues.
