### ISSUE TITLE
Win10 UWP input overlapping

### ISSUE THREAD

**Issue by pralima87** [Ryochan7/DS4Windows#347]
Not sure there is any solution to this but Win10 offers come kind of gamepad support.
Is possible to navigate settings and some options using a controller dpad and joystick, as well as UWP apps.

This causes a lot of overlapping with DS4W and other controller solutions (Controller Companion, steam controller, and so on).

A option to stop Win10 from using the controller would be really appreciated.

**Comment by Nu2This** [comment]
In settings there is a checkbox that says "Hide DS4 Controller." If you tick that, DS4Windows will try to run in exclusive mode. You need to have the controller connected before you open Steam for this to work correctly 100% of the time(in my experience). I usually also turn off Nvidia services before connecting the controller.

**Comment by jonaaa20** [comment]
Or use HIDGuardian.

**Comment by pralima87** [comment]
Sorry guys but that is not exactly my point here.
Maybe I'm not able to explain it right since my english is limited.
I use HIDGaurdian just fine ;),
This issue is not related to the exclusive mode.

Is more like a Win10 feature that causes some issues with DS4 if you use the controller to navigate the desktop replacing the KB/M

**Comment by Nu2This** [comment]
What are you trying to do that does not work? I have a separate profile for KB&M control and I have not run into any issues for what I do.

**Comment by Ryochan7** [comment]
This does sound like an exclusive mode problem. Are you sure that the original DS4 HID device is actually being hidden from Windows? You might want to check out the "Game controller settings" window in "Devices and Printers" and make sure that HID Guardian is hiding the device. I will test this on my end later.

**Comment by Ryochan7** [comment]
Just tested this. The Microsoft Store app looks like it only works with XInput devices. The original DS4 device does nothing but navigation is possible when emulating an Xbox 360 controller. Even using shared mode and having the DS4 device visible to the system does not cause problems. You mentioned using other controller mapping applications in your original post. Are you sure that all other controller mapper applications are disabled while using DS4Windows? I know the PS4 controller support in Steam can be a problem if you leave it enabled when you don't need it at the time.
