### ISSUE TITLE
[Feature request] Stop x360 emulation - keeps other functions

### ISSUE THREAD

**Issue by pralima87** [Ryochan7/DS4Windows#348]
Any chance of a option to just disable the X360 emulation on some profiles?
I know that there is a option to "Turn off DS4Windows temporary" but this option also stops all DS4 functions like custom commands and so on ;)

**Comment by Ryusennin** [comment]
Disabling X360 emulation basically means reverting back to DInput, and you can already do that by creating a profile with the option "Use DInput Only" activated.

**Comment by Ryochan7** [comment]
"Use DInput Only" mode is probably what you want. That will unplug the virtual Xbox 360 controller associated with the DS4. That way, you can either use KB+M bindings exclusively or use some of the extra functionality aside from control mapping like changing the lightbar.

As an aside, this just got me thinking of something I have never tried though. With the mode change that occurs when using DS4Windows, I wonder if there is a change in the input response when using USB or the Sony Wireless Adapter connection when used this way; Bluetooth is not an option though. I will test that.

**Comment by Ryochan7** [comment]
Tested in Rocket League using a USB connection. The mode switch in DS4Windows does make the controller more responsive than just using the DirectInput device in its original state. It still seems like maybe using overlapped IO for the XInput emulation devices actually makes the emulated controller slightly more responsive than using the DirectInput controller.

**Comment by pralima87** [comment]
The only problem is that steam will not recognize the controller if on "Use DInput Only" 
I guess there is no workaround this for now ;/

**Comment by Ryochan7** [comment]
I don't know what you mean at this point. If HidGuardian is doing its job then only the virtual Xbox 360 controller should be visible to the system while DS4Windows is running. The DS4 DirectInput controller should not be visible to any normal process that doesn't use HidGuardian. Using the "Use DInput Only" option should hide the controller from the system entirely at that point.

Maybe you should try to clear out the HidGuardian whitelist if you forced DS4Windows closed at any point. Some old PID references might be in the registry that are being associated with other processes. There is a link in the Settings tab to perform that task; I cannot recall what the label is and I don't have Windows open right now. HidGuardian v.3 is supposed to be more robust and remove that kind of problem.

That is about the only advice that I can give right now.

**Comment by pralima87** [comment]
Sorry man I think I'm not able to really explain what is happening.
For some reason even if "HidGuardian" and Hide DS4 are working Divinity 2 is still detecting 2 controller for me. 
You can close this issue since I'm just causing a confusion right now

**Comment by Ryusennin** [comment]
Try disabling Steam Controller via Big Bicture Mode, it conflicts with the X360 pad (not just DS4W).

**Comment by Ryochan7** [comment]
Checking Steam would be something else to try.

If you want to check for old whitelist entries for HidGuardian, the base location should be something like `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\HidGuardian\Parameters\Whitelist`. All the entries will be subkeys under that location. You can navigate to the location in the registry using the program regedit.

My system currently has some old entries under that location although that might be because I sometimes have to force quit DS4Windows after a bad build. The main reason that any potential keys are not checked upon startup is to not interfere with other programs like InputMapper. Although not necessarily with InputMapper, there could be other programs that use HidGuardian that might need to be able to run alongside DS4Windows.

**Comment by Ryochan7** [comment]
Changing the startup routine to remove possible stale HidGuardian whitelist entries wasn't that difficult. I don't know if I will use it though.
