### ISSUE TITLE
Conflict with wireless Internet???

### ISSUE THREAD

**Issue by shinra358** [Ryochan7/DS4Windows#35]
In the latest version, when I have the controller activated through bluetooth and start surfing the net at the same time, internet seems to slow to a crawl. But resumes as soon as I turn the controller off.

**Comment by shinra358** [comment]
doesn't seem consistent. if it doesn't happen again by saturday, I'll close the thread.

**Comment by pralima87** [comment]
This is a know issue of all WIFI 2.4 and Bluetooth devices.
Is not related to this project.

Is a hardware issue.
To fix this use the cable or buy a 5hz router ;)
