### ISSUE TITLE
DS4Windows doesn't detect controller when wired; HIDGuardian stops it working wirelessly

### ISSUE THREAD

**Issue by PoliteTimesplitter** [Ryochan7/DS4Windows#352]
I've been having some trouble with DS4Windows today, and the different problems probably all have one root cause. Earlier, I was playing Bloodstained CotM wired, for a few hours. Later on I tried to start up the game and it crashed my laptop (couldn't bring up task manager), but I doubt it's relevant.

After restarting the laptop, I had the problem listed above; when wired, I wouldn't get anything. When DS4Windows was Started, it wouldn't detect the controller upon plugging it in USB. Plugging it in then starting DS4Windows also produced no result. All that happened was that the DS4's bar pulsed orange exactly once. If I'm already connected via bluetooth then plug in the USB cable, the controller turns off / disconnects, DS4Windows no longer detects it, and I get that same singular orange pulse.

I'm glad that I can at least play wirelessly, but sometimes I'd like to be able to play while charging or without depleting its battery as this controller is also used for my PS4. I thought it might be an error arising from a full battery, so I left the controller on for a few hours, down to 87%, reconnected, same problem.

To see if it would fix it, I tried installing HIDGuardian, and yes, the lines associated with the controller were in HIDGuardian's registry entry. After a restart, not even Wireless would work, DS4Windows just wouldn't find anything there while the DS4 itself had the solid light blue light associated with being paired with a computer. I've since uninstalled HIDGuardian and it works wirelessly again, but I still have the same problems wired.

As an aside, Uplay and Nvidia Share do NOT interfere with establishing an Exclusive Mode connection on the first connection after boot, even though they start before making that connection, but have to be turned off if I disconnect and want to reconnect later. It's not at all a problem by itself, but if it helps elucidate what the issue might be, I figured it's best to mention it.

Hope this makes sense and that a solution exists!

**Comment by jonaaa20** [comment]
In my opinion, this isn't related to DS4W itselft, but with your system, you said that your laptop crashed right? I had similar problems on 1803 of Windows 10, i reinstalled the drivers and HIDGuardian and it fixed my problem.

**Comment by PoliteTimesplitter** [comment]
Having tried reinstalling HIDGuardian a couple times earlier today that hasn't solved it; strangely though, when I try to reinstall the Drivers in the DS4Windows program, it downloads, says 'installing' for some time, then I get a 'install failed, please retry' message and the driver folder opens, presumably prompting me to try running ScpDriver.exe again; after doing that and restarting, the driver install is still giving me that problem.

**Comment by RedKage** [comment]
I'm gonna share a maybe similar behavior I encountered.

I had a DS4Windows ViGEm build, and it was working fine using wired pads.
Then I installed HIDGuardian, and applied a .reg with AffectedDevices.
Upon restarting my OS, the pads were not getting detected.
--> I simply had to start DS4Windows as Administrator for them to instantly appear.

It looks like DS4Windows + HIDGuardian = DS4Windows requires admin rights to 'see' the pads

NOTES: My DS4Windows install is in portable mode, I just have the folder on my Desktop. It's in user space

**Comment by Ryochan7** [comment]
That assumption is correct. Using HidGuardian with DS4Windows requires running DS4Windows with admin rights. Admin permissions are required to edit the whitelist registry key needed by HidGuardian. Except for testing, I always run DS4Windows as the admin because it does yield better input performance.

**Comment by RedKage** [comment]
Then it is possible this bit is missing from the documentation somewhere.
I'm thinking here https://github.com/Ryochan7/DS4Windows/wiki/DS4Windows-and-HIDGuardian---Install-and-Setup-Guide

Cheers man!
