### ISSUE TITLE
[Feature Request] Send touchpad data via UDP

### ISSUE THREAD

**Issue by vpontin** [Ryochan7/DS4Windows#354]
I think emulators could have better use receiving the touch data via udp, like cemu does with sixaxis motion data.

Plus we can free mouse movement/clicks to use with other commands (or to not have the chance to accidentally minimize a window while trying to use the touchpad.

**Comment by Ryochan7** [comment]
The whole state of the DS4 is available when connected via UDP including the data regarding the two touchpad touches; PadTest does confirm this. I think that the cemu hook only uses the gyro data, accelerometer data, and the timestamp data from the DS4 state object.

![padtest_demo_data](https://user-images.githubusercontent.com/581968/42855185-f11eb1b6-8a04-11e8-8f81-8752245879a7.png)

**Comment by vpontin** [comment]
Oh great to hear that! I hope more devs (like Dolphin emu) use that! Thanks!
