### ISSUE TITLE
Root element missing

### ISSUE THREAD

**Issue by thechumdinger** [Ryochan7/DS4Windows#356]
Hello all!

I have been trying to get this to work but:
7/18/2018 12:12:59: DS4Windows version 1.4.123
7/18/2018 12:12:59: LinkedProfiles.xml can't be found.
7/18/2018 12:12:59: Starting...
7/18/2018 12:12:59: Connection to Scp Virtual Bus established
7/18/2018 12:12:59: Searching for controllers...
7/18/2018 12:12:59: Using Shared Mode
7/18/2018 12:12:59: Found Controller:00:00:00:00:00:00 (USB)
7/18/2018 12:12:59: Root element is missing.

I have no idea how to fix this. I followed all the steps on the DS4Windows and HIDGuardian Install and Setup Guide wiki page.

**Comment by Ryochan7** [comment]
I want to think that something is wrong with the profile that is attempting to get loaded. Can you share the profile that DS4Windows is trying to load when this happens? Also, I don't know why the log is showing a blank serial for a controller connected via USB. The only time that a blank serial should ever show up is when DS4Windows detects the Sony wireless dongle when no controller has been synced to it; the serial would update once a controller is synced.

**Comment by thechumdinger** [comment]
First off thank you, Thank You, THANK YOU! For all the time that you devote to this project. Second, I think I fixed my issue. There was no Default profile and the profile that was available was the first profile I ever tried to make. I'm not going to upload the profile in question because it was literally blank. The serial number is still blank. I'm using a Raiju so maybe that affects the resolution of the serial?
