### ISSUE TITLE
Is there any (remote) chance to see Pro Controller (and other consoles controllers) being supported?

### ISSUE THREAD

**Issue by vpontin** [Ryochan7/DS4Windows#357]
I know this would be a very hard work, but if possible it would ease a lot the life of gamer people who hates the Xbox One controller design.

Plus the chance to have a lot of different modern controllers being supported by a single utility (rather than install several software which could disrupt each other) would be a great differential!

When i talk about Pro Controller i mean [this one](https://www.amazon.com/Nintendo-Switch-Pro-Controller/dp/B01NAWKYZ0?th=1) for Switch.

Anyway thanks a lot for this tool!

**Comment by Ryochan7** [comment]
I don't think that I would get around to working on a more extensive program. It would be great to have a program that supported many types of controllers and that allowed a more complex mapping configuration than what is available with DS4Windows. I keep hitting walls while tweaking DS4Windows so attempting to add support for non-DS4 devices seems like it would be nightmare fuel. Hopefully a larger community project would come along at some point that attempts to tackle that problem.

I have never held the Switch Pro Controller but I keep hearing great things about it. Even though most people would probably not want it, I would want an alternative controller mapper for the Steam Controller to be available on Windows. Linux has the Kozec SC Controller program and that makes the controller far more useful and the Steam Controller has been my preferred controller for many games.
