### ISSUE TITLE
[Notice] Version 1.5 Compromise

### ISSUE THREAD

**Issue by Ryochan7** [Ryochan7/DS4Windows#358]
I am glad that I waited before dubbing a release of DS4Windows as version 1.5. Many changes have gone down the pipeline that have improved XInput emulation performance. Despite not having a new version of ViGEmBus available, I don't feel like holding off on making a version 1.5 release anymore. DS4Windows version 1.5 will unfortunately still depend on ScpVBus rather than using ViGEmBus like what was originally planned. I guess the move to using ViGEmBus will result in a version 1.6 release of DS4Windows.

**Comment by TristanYoung** [comment]
Can't wait to see v1.5, regardless of ViGEmBus.  After trying ESO with a keyboard, I can't believe how much faster I can control things with the DS4; I rely on DS4Windows.  Anything that can provide optimizations and responsiveness, even a minuscule or unnoticeable amount is a good thing.

Thank you for all the hard work on DS4Windows.

**Comment by Ryochan7** [comment]
I never planned on taking DS4Windows as far as I have. As it is, I think I have gotten the current code base as far as I will be able to take it. There are a couple of small fixes that I would have liked to incorporate that I have not been able to keep in the code without .NET making the whole application run slower. There has been so much fighting with .NET that it has impeded some progress that I would like to try to make.

I am considering making a small test application using newer standards to see if a different design might help .NET cooperate better. Having a more proper object oriented design might allow for the JIT to make some optimizations that cannot be made with the highly static method design that is currently being used. Making something small like my old test C++ application would at least give me an idea about whether refactoring would be a good use of my time.

https://bitbucket.org/Ryochan7/xinput_scpcontrol_test/src/master/

This issue mainly served as a task for a milestone. Since version 1.5 has been released, this issue can be closed so the milestone is marked as complete.
