### ISSUE TITLE
cant install drivers

### ISSUE THREAD

**Issue by Razile89** [Ryochan7/DS4Windows#359]
Hi, i unistalled the drivers because i thought they were giving me problems but now i cant reinstall them, this is the log

SCP Driver Installer 1.2.2.175 [21/07/2018 01:37:14]

Detected - Microsoft Windows 10 Pro (6.2.9200.0 AMD64)
Selected DEFAULT configuration.

SUCCESS - Virtual Bus Created
INFO - ENTER: DriverPackageInstallW
INFO - Looking for Model Section [SCProductions.NTamd64]...
INFO - Installing INF file 'D:\Programmi\DS4Windows\Virtual Bus Driver\System\ScpVBus.inf' (Plug and Play).
INFO - Looking for Model Section [SCProductions.NTamd64]...
INFO - Installing devices with Id "root\ScpVBus" using INF "C:\WINDOWS\System32\DriverStore\FileRepository\scpvbus.inf_amd64_21ca245c0e23d7a5\scpvbus.inf".
INFO - ENTER UpdateDriverForPlugAndPlayDevices...
ERROR - RETURN UpdateDriverForPlugAndPlayDevices.
ERROR - Installation failed.
ERROR - PnP Install failed.
INFO - Attempting to rollback ...
INFO - No devices to rollback
INFO - RETURN: DriverPackageInstallW (0x2)

Install Succeeded.

-- Install Summary --
Bus Device

what can i do?

**Comment by Ryochan7** [comment]
The log doesn't really help so I can only offer vague suggestions. First check the Device Manager and see if any other Scp Virutal Bus Driver device exists under System devices. Delete any existing device that might exist before starting the installer again. Also, make sure you are running the ScpVBus installer as the system administrator.
