### ISSUE TITLE
Wired controller not working in DS4Windows. 

### ISSUE THREAD

**Issue by ToniFlamboni** [Ryochan7/DS4Windows#361]
When I try to connect a Dualshock 4 controller to my PC using DS4Windows and a micro USB cable, it keeps connecting as a Bluetooth device. In that case, I want it to connect as a wired device because of latency issues I've been having. How do I fix this USB issue, and if I can't, is there a way to fix the latency issue with bluetooth? (at least with multiple controllers connected)

**Comment by ToniFlamboni** [comment]
> You probably still have the controller synced up with your Bluetooth adapter. You have to disconnect the Bluetooth connection. When a controller is connected via Bluetooth and USB, DS4Windows prioritizes the Bluetooth connected device and ignores the USB connected device. There is the Quick Charge option available in the Settings tab which can be used to have DS4Windows automatically disconnect the Bluetooth connection for a controller and use USB exclusively.

I've tried enabling the quick connection option, but when I do that while my controller is plugged in and I power it on, the controller just shuts down immediately. I've also tried desyncing it with my computer, and when I power the controller on, it will just resync the device with Bluetooth again. If I do this with Bluetooth disabled, it just won't connect at all.

**Comment by Ryochan7** [comment]
Have you checked the Device Manager in Windows to see if the USB HID device associated with the DS4 has been disabled? That is a far less common problem than it used to be but it does pop up on occasion. If you see a down arrow icon for an HID-compliant game controller then it has been disabled and you should re-enable it.

![Disabled Device Example](https://raw.githubusercontent.com/Ryochan7/DS4Windows/jay/disabled_device_example_small.png)

 I wanted to experiment with another workaround to the old exclusive mode trick but I could not get runtime performance to work well enough. The only real way to avoid the problem while allowing exclusive mode to work is to use HidGuardian.
