### ISSUE TITLE
Lightbar flashing during rumble

### ISSUE THREAD

**Issue by zsohu** [Ryochan7/DS4Windows#362]
Hi,
I'm on the latest version of DS4Win. Before I start a game the lightbar is showing the color I selected, but after the first rumble occasion in a game it stays off and only flashing in the same pattern as the rumble goes in-game.

Is this a new feature or is this a bug?

**Comment by TristanYoung** [comment]
That's odd.  I don't experience this behaviour.

I doubt I can solve your issue, but a few more details might help others who can.

Are you connecting via bluetooth, or wired?

Does this happen as well when connected to your PS4?

How old is your DS4?

If I experienced this, and playing with DS4Window's settings (low battery flashing, etc.) didn't solve it, this is what I would do as part of the diagnostics:

Try pairing it with a PS4, and see if the behaviour follows the controller.  If it doesn't, then there could be some weird DS4Windows issue.

Check inside the controller to make sure the flat lightbar/USB cable is properly connected.  I would re-seat it (pull it out, then push it back in), then re-test.

If it happens on the PS4 as well, and re-seating the lightbar/USB cable doesn't solve it, then you could have a faulty controller.  I wonder if a weak battery could cause this?  The rumble motors draw more power than the electronics, so maybe the battery is unable to sustain the power requirements, causing a drop in the light bar when the motors energize.  I'm only guessing.  I would think a low power event would trigger the controller to disconnect, crash or shut down.

I hope you find the solution.  Good luck!

**Comment by Ryochan7** [comment]
I have not experienced behavior like that before. The lightbar worked as expected while rumble was active when I last tested Rocket League. I will test this scenario in Rocket League again soon.

**Comment by zsohu** [comment]
Hi,

Thanks for the suggestions. I don't have a PS4 so I couldn't test it. I did a re-install of DS4Widows (finally got HID Guardian working) and I'm not experiencing the same behavior. The controller works as expected. Not sure what caused the issue but indeed my controller is pretty "old" I have it for about 4 years. There were longer periods when I wasn't used and charged at all, so maybe the battery acting up.

**Comment by TristanYoung** [comment]
You may want to pick up a second controller - not only useful for verifying some issues surrounding game controllers, it's good to have a spare while gaming.  I have 4 controllers, and I rotate through them.  I've had it happen before where I'm in a raid and sure enough the battery goes low.  I could plug in to the USB, but micro-USB ports are easy to destroy, and if you're a traveling gamer such as I (move around a lot physically), it won't take long before you destroy the micro-USB ports.
