### ISSUE TITLE
Dinput with bluetooth paired ?

### ISSUE THREAD

**Issue by midoukanehikaru** [Ryochan7/DS4Windows#363]
in DS4 setting have option with Dinput only but need wired, is there any way to make it work via BT ? thanks

**Comment by Ryochan7** [comment]
Unfortunately there is no way to make it work via BT. Once DS4Windows changes the input mode of the controller, the exposed DInput controller is pretty much useless until disconnecting and reconnecting the DS4 outside of DS4Windows. USB and Sony Wireless Adapter connections do not have the same issue. DInput only mode is mainly useful for BT connections for creating KB+M profiles and playing games that have problems with mixed gamepad and KB+M input.

**Comment by vpontin** [comment]
I could be mistaken, but once i managed to play F1 Challenge 99 02 (dinput only) using my Dualshock with Hide Controller on. I always thought windows exposes a dinput equivalent for any xinput device, and Hide Controller just hide the duplicated dinput device "Wireless Controller"
