### ISSUE TITLE
doesnt see nacon revolution

### ISSUE THREAD

**Issue by ysfbz** [Ryochan7/DS4Windows#364]
i tried everything but it doesnt see nacon revoution pro controller

**Comment by narutoxboy** [comment]
You can't connect nacon revoution pro to PC ?
what problem are you talking about?

**Comment by Ryochan7** [comment]
Unfortunately, I cannot provide support for any third party controllers. Solving problems for devices like the Nacon Revolution Pro would be up to the community since I do not have access to that controller.
