### ISSUE TITLE
Launch Program with Profile Still Not Working

### ISSUE THREAD

**Issue by shinra358** [Ryochan7/DS4Windows#37]
This Feature still not working. When ds4windows displays a controller in its list of controllers, and said controller has this checked in it's profile, then the program is supposed to launch.

EDIT: However, it does work if you switch the controller profile manually and then switch back to the profile that has the option checked.

**Comment by Ryochan7** [comment]
Profiles are loaded before controllers are detected so programs will not be launched when a new controller is found. It looks like an extra check will have to be added to the hotplug routine.

**Comment by shinra358** [comment]
Seems fixed in new test version. Thanks.
