### ISSUE TITLE
in some programs the options button acts like the escape key.

### ISSUE THREAD

**Issue by powerpuffboysz** [Ryochan7/DS4Windows#370]
in some programs, mainly emulators like epsxe and pcsx2, whenever I hit the options button which is normally configured as the start button it acts like the escape key which in those programs closes out the emulator. my controller is using exclusive mode and hide ds4 option is enabled. I also have hidguardian installed if that makes a difference

**Comment by Ryochan7** [comment]
I have never encountered that problem but I believe that it has been brought up before. Can you share the profile that you are using for PCSX2 that exhibits the problem?

**Comment by powerpuffboysz** [comment]
in ds4 windows I use the default profile. I have since figured out what was causing it though. for whatever reason this bug only occurred if steam was open regardless of exclusivity
