### ISSUE TITLE
Rocket League keeps turning off my ds4

### ISSUE THREAD

**Issue by tonysantoro** [Ryochan7/DS4Windows#372]
It happens quite few times in SFV.

**Comment by Corrodias** [comment]
This isn't much information to go on. Can you describe how to recreate the issue? Have you tried using a different cable? Cables are often the cause of disconnections.

**Comment by anphetamina** [comment]
It is a Sony DS4 v2 controller. Deleting the AffectedDevices key from the HidGuardian fix the issue but I need to know the correct way to remove the HidGuardian driver properly.
