### ISSUE TITLE
Can't get my ds4 working anymore

### ISSUE THREAD

**Issue by anphetamina** [Ryochan7/DS4Windows#373]
I've connected both via bluetooth or cable my ds4, windows will recognize it and pair with it but it won't be detected in ds4 windows nor inputmapper nor Steam.

**Comment by Corrodias** [comment]
Is it a Sony DS4 or is it made by someone else? What's the model number?

**Comment by anphetamina** [comment]
It is a Sony DS4 v2 controller. Deleting the AffectedDevices key from the HidGuardian fix the issue but I need to know the correct way to remove the HidGuardian driver properly.

**Comment by Ryochan7** [comment]
https://docs.vigem.org/#!hidguardian-v1-installation.md#Driver_removal
