### ISSUE TITLE
Microsoft Edge Running in the Background Prevents Exclusive Mode

### ISSUE THREAD

**Issue by ajhix36** [Ryochan7/DS4Windows#374]
Hello, I've been having great trouble getting exclusive mode to work, and after going through the list and killing apps one by one, it was Microsoft Edge. And btw, I never use Microsoft Edge, but apparently just at startup, it runs shit in the background to keep it there always.

**Comment by powerpuffboysz** [comment]
install hidguardian

**Comment by ajhix36** [comment]
I have previously, am I supposed to reinstall it after every update?

**Comment by TristanYoung** [comment]
I don't know if it matters if using Ryochan7's HIDGuardian installer, but you certainly do for the older Windows Driver Kit devcon.exe method.  I use the older method, and re-install the filter driver after every update.

Ah yes, Microsoft Edge - the sh***y browser Microsoft keeps trying to force people to use. I very much prefer to not put that s**t on everything.  Firefox all the way.  I wish Edge could be uninstalled, or blocked from execution.

**Comment by Ryochan7** [comment]
HidGuardian should not need to be messed with after installation. Although I have not experienced it myself, I have heard people mention problems with Windows Updates making registry changes that affected HidGuardian; both DS4Windows and InputMapper have been affected by issues like this. Links are available in the Settings tab to browse the main AffectedDevices registry entry and also rewrite the template text if that would be needed. A full re-install of HidGuardian should not be necessary.

I also would encourage people to not use Microsoft Edge except to download an alternative browser. My primary browser of choice lately has been Brave but I also use Chrome and Firefox.

https://brave.com/

**Comment by Ryochan7** [comment]
I tested this and I can confirm that I experience the same problem when Microsoft Edge is running. The HidGuardian whitelist can be empty and it won't matter.

**Comment by Ryochan7** [comment]
I guess that I can take back what I said earlier about Windows Updates not affecting my system. The UpperFilters registry key needed by HidGuardian is gone. I still have the driver installed and I am pretty sure that I did not edit the registry key manually. I have been using the older exclusive mode workaround lately so that made me not detect the change until now.

**Comment by Ryochan7** [comment]
I ended up reinstalling HidGuardian and that fixed the issue. The lack of an UpperFilters registry key was the root cause of the problem. You should just uninstall and then reinstall HidGuardian.

**Comment by TristanYoung** [comment]
I found that I don't have to uninstall HidGuardian before reinstalling it.  I keep a shortcut handy to quickly install it after a Windows version update.  I still use devcon.exe, so I don't know if that is why I don't have to uninstall first or not.

I generally avoid edge and ie altogether.  I keep an up-to-date copy of firefox installer on an ftp server, and can pull it quickly from command line.  The only time that doesn't work is on a machine that's isolated from the internet - so I break out the USB flashdrive that I update once in a while.

I really don't like/distrust Microsoft browsers.

**Comment by ajhix36** [comment]
Do you guys have links to the HidGuardian installer? Googling gives me a couple different options, and I'm not really sure which one is which anymore

**Comment by Ryochan7** [comment]
I use my own installer to install HidGuardian. It does the job well enough. It also writes a template AffectedDevices file if one does not exist and it sets up the UpperFilters registry value to include HidGuardian if it is not already included. You should not need the extra utilities used by the other method if you use that installer.

http://ryochan7.xyz/ds4windows/test/DriverInstaller_Test_20180402.zip

The only other automated installer that I know of is the old InputMapper HidGuardian installer. That one includes a very old version of HidGuardian that does not include some changes that improved performance so I would not recommend it. I think the InputMapper installer also bundles a custom service that edits the HidGuardian whitelist for InputMapper.

**Comment by Ryusennin** [comment]
That very functional installer should be put somewhere in the wiki or on the front page.

**Comment by ceedveed** [comment]
Can I install your HidGuardian from 4/2/18 over the older version? I have one from you with filename DriverInstaller_Test_20180218.zip

**Comment by jonaaa20** [comment]
@ceedveed https://docs.vigem.org/#!hidguardian-v1-installation.md

**Comment by Ryochan7** [comment]
You can run the newer DriverInstaller program without any issues. Up until a few days ago, both installers pointed to the same version of HidGuardian. However, the URL used for the HidGuardian archive has changed so the old 20180218 installer would no longer work. Luckily, the newer driver installer reads the archive URL from a remote JSON file. The URL has been updated and 20180418 can install the latest version of HidGuardian. You should be able to update the HidGuardian driver without any issue.
