### ISSUE TITLE
Auto update for version Gyro motion

### ISSUE THREAD

**Issue by narutoxboy** [Ryochan7/DS4Windows#375]
Dear Ryochan7
Can you make a DS4Updater.exe only for Gyro motion.
If i use DS4Windows normal this tools update version normal.
If i use Gyro motion version this tools update Gyro motion version.
Thank you for best DS4Windows version.

**Comment by Ryochan7** [comment]
Version 1.5.3 now has the UDP server integrated. It took a long time to find a way to get performance where I wanted it. Now I don't have to worry about maintaining a separate build. Cemu barely works on my computer so I don't have a real use for the UDP server feature. It is interesting though.

Thank you for the kind words.

**Comment by narutoxboy** [comment]
Thank you for reply,
I'm download latest version 1.5.3 with integrated UDP server, using cemu version 1.13.0f.
Confirm worked correctly on game the legend of zelda breath of the wild with aim function.
One again thank you.
