### ISSUE TITLE
Changing exe to .config

### ISSUE THREAD

**Issue by SkittleySkit** [Ryochan7/DS4Windows#376]
I launched the updater and it changed my .exe into this:

http://prntscr.com/kekzud

Why?

**Comment by Ryochan7** [comment]
The DS4Windows.exe.config file is supposed to be there. That file is used to change some parameters used by the .NET Runtime. It looks like the DS4Windows.exe file did not copy over though. I have not changed the updater in a while but it worked fine the last time I tried it. I will have to test it later.

**Comment by Ryochan7** [comment]
I tested the auto updater on my Windows 7 installation and it worked fine for me.

**Comment by Corrodias** [comment]
I have not had any issues with the updater on Windows 7, either; just got an update yesterday.

Perhaps you have some security software that deleted the .exe file? Check the logs and quarantine. It doesn't sound like a reproducible bug, otherwise.
