### ISSUE TITLE
devcon.exe failed

### ISSUE THREAD

**Issue by anphetamina** [Ryochan7/DS4Windows#378]
Hello,
I'm trying to follow the steps for the HidGuardian installation but when it comes to use the .exe file to install the HidGuardian I get devcon.exe has failed. twice. I've previously installed HidGuardian from the IM site and I already have a set of HidGuardian files into my System32 folder, how to get rid of them?

**Comment by Ryochan7** [comment]
I have not tried the method to install HidGuardian that is documented on the Wiki. I use my small test installer when I want to install or uninstall HidGuardian. That installer does not use devcon.exe. Instead, it uses an assembly that uses various SetupAPI calls.

http://ryochan7.xyz/ds4windows/test/DriverInstaller_Test_20180402.zip

I use a program called DriverStoreExplorer to check if any old driver files are installed on my system and remove them. It has come in handy a few times. Although, the version of HidGuardian packaged by IM should have included an uninstaller which you can run to get rid of the driver and the included background service if it still exists.

https://github.com/lostindark/DriverStoreExplorer
https://github.com/lostindark/DriverStoreExplorer/releases/download/v0.9.10/DriverStoreExplorer.v0.9.10.zip

**Comment by anphetamina** [comment]
Ok now I've set up everything correctly. The problem is that sometimes in any game like Rocket League or Street Fighter V the controller will stop working for about 2-3 seconds, an over 10ms input latency will be registered in the log, and then it will start working back. This happens randomly. My bluetooth dongle (Broadcom) is plugged into a usb 2 port, the device power saving option is disabled, and it's near my controller. How can I provide more information to fix this?

**Comment by Ryochan7** [comment]
I don't know if the issue could be software related or an issue with the dongle itself. It is only on rare occasions when I see a latency message pop up in the log and that is usually when another application or game hogs system resources for a couple of seconds. Is there some background service that is sporadically consuming a lot of system resources particularly hitting the Disk hard? You might want to check in Task Manager for that.

**Comment by anphetamina** [comment]
Could it be the old bluetooth drivers? I see that I'm using a 2006 old ones, maybe an update will help? My bluetooth dongle ID is BCM20702A0 but in the Microsoft update catalog I can only find BCM20702 (http://www.catalog.update.microsoft.com/Search.aspx?q=BCM20702). Are them compatible?

**Comment by anphetamina** [comment]
Windows 10 1803.

**Comment by RedKage** [comment]
Hey there,

I'm new to DS4Windows and I installed it yesterday.
I encountered a similar problem.

It was simply because the folder in which there is the `HIDGuardian x64.bat` helper file, must be located in a space-free path.

There is an issue with the following line in the .bat
`"%programfiles(x86)%\Windows Kits\10\Tools\x64\devcon.exe" install %~dp0\HidGuardian.inf Root\HidGuardian`

There should be quotes around "%~dp0\HidGuardian.inf"
`"%programfiles(x86)%\Windows Kits\10\Tools\x64\devcon.exe" install "%~dp0\HidGuardian.inf" Root\HidGuardian`

**Comment by RedKage** [comment]
Additionally I also had the "devcon failed" message.
For this ... I simply restared my Win10 OS and after that it was running fine

**Comment by anphetamina** [comment]
I tested today with the newest bluetooth drivers and it happened once. I don't know if this is a driver problem but you have to know that I have a cordless and a wifi modem 1 meter near the bluetooth dongle. If that were the problem, should lag spikes be more consistent or frequent?

**Comment by nefarius** [comment]
*Mööp mööp!* https://docs.vigem.org/#!hidguardian-v1-installation.md

**Comment by Ryochan7** [comment]
I have to give HidGuardian v.3 a try sometime. Hopefully the extra dependencies to use the new process filtering setup don't cause any issues.

**Comment by anphetamina** [comment]
I hope it solves the latency and the random disconnect issues

**Comment by nefarius** [comment]
Don't bother with v3, v4 is nearly production-ready. More features, less dependencies, clean API.

**Comment by TristanYoung** [comment]
> 
> 
> Hey there,
> 
> I'm new to DS4Windows and I installed it yesterday.
> I encountered a similar problem.
> 
> It was simply because the folder in which there is the `HIDGuardian x64.bat` helper file, must be located in a space-free path.
> 
> There is an issue with the following line in the .bat
> `"%programfiles(x86)%\Windows Kits\10\Tools\x64\devcon.exe" install %~dp0\HidGuardian.inf Root\HidGuardian`
> 
> There should be quotes around "%~dp0\HidGuardian.inf"
> `"%programfiles(x86)%\Windows Kits\10\Tools\x64\devcon.exe" install "%~dp0\HidGuardian.inf" Root\HidGuardian`

@RedKage Thank you for noticing the error.  I've fixed the script (it was present on both x86 and x64 versions).  The wiki entry has been updated with the updated zip file.

I don't know if anyone is going to use this method, since there's an installer now.  I'm pig-headed, and still use this method.  I can automate it to launch after a new build of Windows 10 is installed, to make sure it's installed.
