### ISSUE TITLE
Vigem Build (unable to set Xinput Port value)

### ISSUE THREAD

**Issue by DristMax** [Ryochan7/DS4Windows#381]
Hello Ryochan, I tried to set the "use Xinput Ports" value to something different but nothings happen in Vigem build.

I'm using Scptoolkit for ps3 controllers and the vigem build for ps4 controllers but they get overlapped because they have the same xinput ID.

Do you know how to fix this?

Thanks

**Comment by Ryochan7** [comment]
Did the test and it worked fine for me. Both virtual Xbox 360 controllers worked and each one respected the different mapped settings from each program.

**Comment by DristMax** [comment]
I sent you a tip through paypal!
Thanks for your help and work ! !
