### ISSUE TITLE
Trackpad issues on DS4 v2

### ISSUE THREAD

**Issue by RedKage** [Ryochan7/DS4Windows#382]
Hello,

I have both a DS4 v1 and a DS4 v2.
For the DS4 v2, the trackpad sensitivity is too high, or you could say the trackpad has a 'low resolution' issue.

When using the trackpad of the v1, the mouse cursor movement is super smooth.
When I put the mouse on the left edge of my screen and drag it to the right, the cursor arrives to approximately 70% of my horizontal space.
v1 is perfect.

Now I do this with the v2 pad, and the movement is super jerky.
Sensitivity feels super high. But maybe not. It's just that when I drag on the touchpad, the mouse does not move pixel by pixel, but instead it feels like the mouse cursor 'jumps' 10px by 10px.
This is why I talk about 'low resolution'
When I put the mouse on the left edge of my screen and drag it to the right, the cursor arrives to approximately 50% of my horizontal space.
So the distance is not the same as for the v1

To have the same distance on v2 as for the v1 I had to set "Slide = 52" for my v2, while "Slide = 100" is for my v1.
For both the v1 and v2, I disabled the mouse acceleration option.
And both have "Sensitivity = 25"

NOTE:
I tried this with InputMapper 1.6.10 and I think I saw the same behavior with the v2 trackpad. Before the app disconnected my v2 pad with a "write failure" that is...

**Comment by Ryochan7** [comment]
I have a v1 and a v2 and both work as expected for me. The sensitivity seems consistent and the cursor is smooth. I will recommend that you try out HID Report Listener and see what data is presented there but I don't know if that would help too much. When connected via USB, the relevant starting data byte would be 33.

https://inputmapper.com/downloads/download/5-tools/75-hid-report-listener

**Comment by RedKage** [comment]
I was but I was experiencing the same behavior before using HidGuardian.
It's was also doing it in InputMapper.

I guess it's hardware related.
