### ISSUE TITLE
When you select "Minimize to taskbar" it actually minimizes to the system tray

### ISSUE THREAD

**Issue by davidpoko** [Ryochan7/DS4Windows#383]
Title.

**Comment by jnk22** [comment]
Same thing happening here, since about v1.5.0 I think.

System is Windows 8.1 x64. Still happening on version 1.5.3.

**Comment by Ryochan7** [comment]
I ended up inverting the clause. Fixed the problem with the latest commit.

**Comment by Ritaku01** [comment]
I'm having the opposite problem; since 1.5, I've had no problem with it minimizing to taskbar, now with 1.5.4 it's minimizing to the system tray instead.

**Comment by Ryusennin** [comment]
@Ritaku01 

Make sure "Minimize to Taskbar" in your Settings tab is not unchecked.

**Comment by Ryochan7** [comment]
The default behavior is to minimize to the system tray. I ended up unintentionally changing that with version 1.5.0 and the behavior was reverted with version 1.5.4. You have to check "Minimize to Taskbar" in the Settings tab in order to have the application minimize to the taskbar.

**Comment by Ritaku01** [comment]
Yeah, realized yesterday that I was mixing up the taskbar and system tray. One heck of a facepalm moment.
