### ISSUE TITLE
Left Stick Doesn't work properly through Xinput

### ISSUE THREAD

**Issue by Wakkowarner123** [Ryochan7/DS4Windows#384]
No analog, just wonky diagonals, and it only happens for some programs.

![ds4windows](https://user-images.githubusercontent.com/12213547/43929155-8ec1f870-9be8-11e8-97a0-0780156587c4.gif)

Analog is shown working fine from the profiles tab.

**Comment by Ryochan7** [comment]
Can you share the profile that you are using? Something like that would happen if you mapped a stick direction to a button or the dpad but mapping from LS should allow analog movement.

**Comment by Wakkowarner123** [comment]
Using the default profile, I'm afraid. It only seems act this way on certain programs, not all of them.

**Comment by Ryochan7** [comment]
It should definitely work fine in the Game controller settings window. I will test a clean install but I am pretty sure it will work fine for me.

**Comment by Wakkowarner123** [comment]
Ah, just managed to get it to work! Although I'm not really sure why it works now. All I did was mess with the game controller calibration option built into windows, going through the calibration process and resetting to default, and it suddenly started working. Hoping it stays that way. Thanks for your help!
