### ISSUE TITLE
Doesn't start up with Windows.

### ISSUE THREAD

**Issue by Omega1084** [Ryochan7/DS4Windows#386]
For whatever reason DS4Windows isn't launching when I log into my account like it used to.
It's enabled on the startup tab in my task manager but it doesn't work.
I was thinking it was maybe because I never uninstalled it and just migrated over to this version from the old one but I don't have an option to uninstall it anywhere, it's not in the Control Panel.
Any ideas?

**Comment by anphetamina** [comment]
Disable the startup option in the application and manually create a new scheduled task for Windows in the Task Scheduler to launch at boot.

**Comment by Omega1084** [comment]
Ay, thanks~
I didn't even know I could do this, I'm an idiot. x'D
