### ISSUE TITLE
Not detected by DS4Win but registers as a 360 controller

### ISSUE THREAD

**Issue by thechumdinger** [Ryochan7/DS4Windows#387]
I am using a Raiju. In Steam the controller is shown as an Xbox 360 controller. In the device manager there is the "Xbox 360 Peripherals -> Xbone 360 Controller for Windows". Under the HID dropdown there is a "Razor Raiju". I have tried to uninstall, delete the driver software for "Razor Raiju", unplug, and plug my controller back in. When I do this, DS4Win will recognize my controller, however, about 15 seconds later the "Razor Raiju" drivers are installed again and the connection to DS4Win is lost. 
I have also turned off automatic device installation in the System Properties but that doesn't seem to have an effect. The Raiju drivers still install.
What can I do?

**Comment by migzzzz** [comment]
I am interested in this issue as well as I am using the same controller.

**Comment by Ryusennin** [comment]
That sounds strange. Does it work natively on the PS4 as a DS4 clone or does it use a specific dongle?

If it's directly recognized by Windows as a X360 controller, I suppose it comes with custom drivers which might interfere with DS4Windows.

**Comment by thechumdinger** [comment]
I don't have a PS4 so I don't think I can answer your question. I might be able to test it though and no specific dongle came with the controller. 

I did find some sort of workaround but I'm not 100% sure what exactly produced the result so I'll try and describe every single action I took as best as I can but I will start with the possible workaround.

Possible fix: After about 2 hours of farting around what ended up producing a result was to roll back the HID driver and then I was able to delete the device and it now stays deleted and I can get the controller working with DS4Win after unplugging (the log shows "X360 Controller # 1 failed. Using DInput only mode") and plugging it back in (now the log shows "X360 Controller # 1 connected").

I think I installed the program and drivers before the very first time that I plugged my controller in. After the initial install of DS4Win I went into device manager and uninstalled w/software delete checked the Razor Raiju in the HID drop-down. For about 5 seconds the log of DS4Win shows that the controller is now able to be recognized. After that short amount of time, the OS installs the Raiju drivers again and the HID drop-down shows the device that I just deleted. (I don't think the audio device drivers have any effect DS4Win's ability to communicate with my controller.) 

After no success, I installed the SPC Toolkit but something interesting happened that might shed some light on some part of the process. The Toolkit installs a libusbK USB Device and I'm not sure exactly how it was interacting with the HID drivers but the possible fix was found shortly after the libusb drivers were installed. I feel like it is somehow able to prevent windows from reinstalling the HID Raiju drivers, but only after I rolled back the HID drivers first. I haven't tried testing whether or not if the libusbK driver from the SCP Toolkit has to be installed.

In the log (and the controller tab shows the same information) "Found Controller:00:00:00:00:00:00 (USB)" is always logged but the SPC Toolkit tray notifications will show that the controller is recognized (and is a virtual Xbox controller? Steam still recognized it as an Xbox controller and worked as expected within the Steam environment) and the tray notification shows the controller's unique 12 digit ID number.

I think there is more that I could share but can't remember it because I tried for 3 hours to get my controller to work with DS4Win a couple days ago. Questions could help my jog my memory.

**Comment by Corrodias** [comment]
If you did the device uninstall with the "delete the driver software" box checked, *and* you disabled automatic driver downloads via Windows Update, then my next guess is that it had more than one driver in the cache. Keep doing the "uninstall & delete driver" method until it winds up using one of the built-in Windows drivers like "Wireless Controller" or something. That's what a DS4 is called by Windows.

**Comment by Ryochan7** [comment]
Going along those lines, I will put out a recommendation for the program DriverStore Explorer. It can be used to purge a cached driver if one still exists for a deleted device. I have had to use it to purge older versions of HidGuardian that were on my system.

https://github.com/lostindark/DriverStoreExplorer
https://github.com/lostindark/DriverStoreExplorer/releases/download/v0.9.10/DriverStoreExplorer.v0.9.10.zip
