### ISSUE TITLE
Auto-Profile & Toggling Profile

### ISSUE THREAD

**Issue by reecespieces** [Ryochan7/DS4Windows#389]
I have 3 profiles: my default profile, and 2 other profiles A and B that I want to switch between when dolphin is running.

Now when I have profile A or B set as my default profile, I can switch between them easily using a special action (I have it set to R1). 

However, when I try to use my regular default profile and setup auto-profile to switch to A or B when dolphin is running, _then_ switching between profiles A and B by pressing R1 no longer works as it should while dolphin is running.

To clarify, both features work but they interfere with each other.

I found the same issue reported in the Jay2Kings version: https://github.com/Jays2Kings/DS4Windows/issues/124

**Comment by Ryochan7** [comment]
Thank you for confirming that the issue existed with the Jays2Kings build. I am glad that I didn't break something. I don't use DS4Windows for much besides the basic translation to XInput so I rarely play around with the extra features. As it is, I might look into it a bit but I am going to file this under won't fix.
