### ISSUE TITLE
Cursor Only Working w/One Controller

### ISSUE THREAD

**Issue by shinra358** [Ryochan7/DS4Windows#39]
Cursor only works with 1st paired controller regardless if the 2nd controller has a first controller profile and the original controller is off.

**Comment by Ryochan7** [comment]
This will be one problem that will have to stay on the back burner for a while. The only testing that I can do is with one controller and a DS4 Wireless dongle acting as a second controller. Touchpad support works fine for me no matter which order devices are detected. Nothing in the code stands out as being a problem.

**Comment by shinra358** [comment]
This can probably be closed now. Bought a new controller to mod with a translucent shell and i have 3 controllers with the cursor working and one that just doesnt. Im sure now that something has malfunctioned in the controller itself.

**Comment by Ryochan7** [comment]
Although this issue is dead, I should note that I have finally purchased a second DS4 controller so I could test this directly. I can use the touchpads on both controllers without any issues.

**Comment by shinra358** [comment]
yeah, i hooked something up wrong when putting translucent shells on my controller.
