### ISSUE TITLE
How to fully uninstall?

### ISSUE THREAD

**Issue by chang023** [Ryochan7/DS4Windows#390]
I do not find an uninstaller and no uninstall option. How do I remove all files related to this application?

**Comment by chang023** [comment]
That will remove the DS4 Driver as well?

**Comment by Ryochan7** [comment]
There is no program to uninstall the ScpVBus driver; I really don't like that DS4Windows ever called it a DS4 driver. You have to go to **Device Manager > System devices > Scp Virtual Bus Driver**, right click and select **Uninstall device** from there. The prompt will give you the option to remove the driver along with the device.

**Comment by BlackPowerade** [comment]
If you want a full install do this:

1.  Find your DS4Windows installation (Wherever you extracted the folder and the exe is located)
2.  Go to $USER\AppData\Roaming and find the DS4Windows folder
3.  Delete both of these folders
4.  (Optional) Do what Ryochan said and remove the Driver
This will remove everything related to DS4Windows on your system, you could also dig through the registry if you feel compelled to, but it is not really necessary.
