### ISSUE TITLE
[Feature Request] DS4W & Steam/Uplay/etc combined launcher

### ISSUE THREAD

**Issue by Alexandroid99** [Ryochan7/DS4Windows#393]
On my system, DS4Windows starts extremely late and Steam is always faster to start up if set to autorun on boot. And since it hooks exclusive mode and apparently doesn't release it after closing down again, DS4W always complains about exclusive mode not being available to it. Now while I do know how to use Task Planner or batch files to make my own launcher that first launches DS4W and then Steam, it would be handy to just have a tick box in the UI that takes care of everything for you. You know, for the inexperienced users. 😄 This would allow DS4W to hook the controller AND Steam to launch without conflict. And while we're at it, the same for Uplay would be nice, too. Just a suggestion. Cheers!

**Comment by shinra358** [comment]
There's already a start program option.
