### ISSUE TITLE
ds4 windows unable to output analog controls(SOLVED!!)

### ISSUE THREAD

**Issue by sefalden** [Ryochan7/DS4Windows#397]
i used to use ds4 windows back in the day and it worked fine, kinda buggy but fine. this one though has one problem, i cannot map any button or trigger to control the analog stick. an example being if i wanted to use the triggers to control the left analog stick i cannot, i mapped the right trigger to the right side of the analog stick and mapped the left trigger to the left side of the analog stick and nothing happens.

i am really hope this is fixible

thank you for you time.

**Comment by Ryochan7** [comment]
I am pretty sure that you don't have a dead zone set for LS. The older versions of DS4Windows had an implicit dead zone set for the analog sticks if one was not set in a profile. I don't like the practice of implicit dead zones so implicit dead zones were removed from the mapping code. The LS mapping would have precedence over the L2 or R2 mappings so the final output would be correlated to the current stick position. I would recommend a dead zone of 0.08 or 0.09 for LS to help with that kind of mapping scheme. Another option is to set the LS direction buttons to Unbound if you don't plan to use the analog stick.

**Comment by sefalden** [comment]
Ryochan7 you are a boss!!!, thank you very much. I really do appreciate your existence.
