### ISSUE TITLE
Rumble 5 seconds

### ISSUE THREAD

**Issue by doyzi2** [Ryochan7/DS4Windows#399]
Really appreciate the work! Thank you!
Just a small thing I noticed, no idea if it is intentional or what. After a google it seems like it has been a thing since the original DS4Windows. And as the title say I mean that the rumble seems to stop no matter what in 5 seconds. I guess most games would usually not need more, but it is still weird. Even the test just stops by itself.

**Comment by jonaaa20** [comment]
I have this on GTA V too.

**Comment by doyzi2** [comment]
Well, just in case so this doesn't remain at this stage, at least I would appreciate some sort of solution to this "problem". Even if it is how the DS4 is made to work and maybe they had some good safeguarding intentions, the XB1 controller doesn't have and it is not dying on us. It might not be top priority, but it is something to consider indeed making, as long as it can be implemented non-intrusively.

**Comment by Ryochan7** [comment]
I tried a couple of different techniques but no luck as of yet. Implementing a routine is simple but output performance gets much worse.

**Comment by Ryochan7** [comment]
This time I was able to get it working well enough without adding application slowdown. With the latest change, at least one output packet is sent to the controller every 4 seconds.
