### ISSUE TITLE
Unable to use it with two controllers

### ISSUE THREAD

**Issue by X4V1** [Ryochan7/DS4Windows#40]
As soon as I connect the second controller, the program starts to disconnect controllers one after another (fake timeout error). The problem happens with the latest version (1.4.70) but it works if I go back to the 1.4.52 (latest by J2K). The program start an infinite loop when I launch it with 2 controllers. The only thing I can do is click on "stop" button, but the software freeze at the same time. If I open the log tab before clicking on stop, I can take a screenshot of latest log entries (in attachment). 

Don't hesitate to tell me if you need some extra information to identify the cause.

Last but not least, thank you very much for the work you are still doing on DS4Windows 👍 

(PS: sorry for my bad english, it's not my native language...)

[UPDATE 1]: No problem with version 1.4.66
[UPDATE 2]: No problem with version 1.4.69. The problem seems to comes with the version 1.4.70.

Log v1.4.70:
![Log v1.4.70](https://img4.hostingpics.net/pics/836884log2controllers.png)

**Comment by shinra358** [comment]
Try this version: https://github.com/Ryochan7/DS4Windows/issues/38

**Comment by Ryochan7** [comment]
Hopefully the new release fixes this problem on your system.

https://github.com/Ryochan7/DS4Windows/releases/download/v1.4.71/DS4Windows_1.4.71_x64.zip

**Comment by Ryochan7** [comment]
There has been no additional feedback so I am going to assume that the problem was fixed. Thank you X4V1 for mentioning this problem.
