### ISSUE TITLE
[Bug] Notification Icon Disappears Eventually / Silent Crashes

### ISSUE THREAD

**Issue by shinra358** [Ryochan7/DS4Windows#401]
Havent been here in a while but I see the connection problem was fixed greatly. Now there's only one windows chime when connecting wirelessly and doesn't seem to be anymore unresponsiveness. However, sometimes the program silent crashes and the process is still in the process menu but not in the taskbar. I had to force close the process. 

To fix this, can you put a check that if there is a process but no taskbar element present, then the program restarts itself via process close and reopen while still obeying whether you have it on admin priviledges or not?

**Comment by shinra358** [comment]
I don't know if it's certain settings that cause this or the longevity on the program running, but eventually the notification icon will disappear but the process will still be running and the controllers will still be working fine.

**Comment by Ryochan7** [comment]
I have run DS4Windows in long stretches and I have not encountered this problem. This is under Windows 10 so maybe I should try this under Windows 7 as well. Either way, the tray icon should exist as long as DS4Windows.exe is still running. Nothing is set up to hide it.

**Comment by shinra358** [comment]
May have something to do with memory. May not. But it does happen. And has been before these new changes. IF you can put in a check for if the notification icon doesn't exist, have ds4windows recreate it, thatll be nice. thx.

**Comment by Ryochan7** [comment]
I will give this issue a little more time before I close it. This problem should be resolved with version 2.0 when it is released.
