### ISSUE TITLE
Second/Multiple shift modes?

### ISSUE THREAD

**Issue by Ulfrinn** [Ryochan7/DS4Windows#408]
Is there any way to have multiple shift modes in this game?  I am attempting to use it for an MMO type game and would like the left trigger to shift the face buttons to a different group of hotkeys, and the right trigger to shift to a third set.  Is this possible?  And if not, it is a feature that should be added.

**Comment by Ryochan7** [comment]
There is no way to set up multiple shift modes for a single control. A more extensive mapping system would have to be created to allow for more advanced configurations to be possible. Most of the time I use fairly basic mappings in my profiles but it would be nice to have at least action set support for some games.

**Comment by jinkazama82it** [comment]
If you need to press shift like another button in combination with one or more extra button yes you can with a macro
![desktop screenshot 2018 08 29 - 11 20 38 61](https://user-images.githubusercontent.com/28483698/44778780-27fe3400-ab7e-11e8-9ff7-b8083f8d1a63.png)
![desktop screenshot 2018 08 29 - 11 22 54 35](https://user-images.githubusercontent.com/28483698/44778791-2e8cab80-ab7e-11e8-99ab-bf30760b83fa.png)
when you record a macro you need to edit it a little for make the rigth action.
first of all Unbound any button or action to the desired Button on controller (I use a PS4 controller so for this howto I use the swipe left action that is unused atm) create a new Special Action so go to edit profile-> clicking the label Special Action-> click New Action-> Put a clearly name for the action-> From dropdown list select "Record a macro"
![desktop screenshot 2018 08 29 - 11 29 48 85](https://user-images.githubusercontent.com/28483698/44779170-0cdff400-ab7f-11e8-811b-7623ab36eb97.png)
Now click on Button "Record a Macro"-> into opened window click Record-> Now press and release one time the first keyboard button (for example shift) and the same for the second one (for example F1) and again the firs button-> now click on stop and you have this:
![desktop screenshot 2018 08 29 - 11 38 01 87](https://user-images.githubusercontent.com/28483698/44779569-1fa6f880-ab80-11e8-8668-bfbc4ce07e3e.png)
at this point you need to edit a little the macro for remove the unneccessary action, we need to press and release at the same time this 2 key so select the firs Up LShiftKey and press cancel on your keyborad
![desktop screenshot 2018 08 29 - 11 41 22 00](https://user-images.githubusercontent.com/28483698/44779796-bc699600-ab80-11e8-823a-0483cd8de921.png)
and this is the result
![desktop screenshot 2018 08 29 - 11 44 36 98](https://user-images.githubusercontent.com/28483698/44779891-f6d33300-ab80-11e8-836d-0da347509ef6.png)
the macro now press both the button at the same time now we need to release the button at the same time witouth press it again, we need to remove the second Down LShiftKey so click on it and press cancel on your keyboard
![desktop screenshot 2018 08 29 - 11 47 42 22](https://user-images.githubusercontent.com/28483698/44780122-84168780-ab81-11e8-82d0-033a2a49775f.png)
and the result is that now you have a macro that press at the same time LShift and F1 and release it at the same time
![desktop screenshot 2018 08 29 - 11 47 59 35](https://user-images.githubusercontent.com/28483698/44780151-90024980-ab81-11e8-9a30-2c60ff882ca7.png)
Click on save-> from the list of controller button pin the desired button for use this special action (for example I selected Swipe Left) -> click on Save at the bottom
![desktop screenshot 2018 08 29 - 11 54 29 54](https://user-images.githubusercontent.com/28483698/44780665-c5f3fd80-ab82-11e8-9542-154b52ad417f.png)
and now your special action is ready to be used in your game for switch set of skill or wathever you want to do with it.

**Comment by Ulfrinn** [comment]
assuming ryochan7 does any kind of development on this project, rather than just hosting the files (i dont know).. then an easy to code solution would be that instead of having to tap a button to switch profiles, and tap it again, or a different one to switch back, what if profiles automatically switched back when the button was released?.. maybe have an option for a toggle here, this would be much easier than coding a second shift mode into the profile, and then people could have as many "shift modes" as they wanted via additional profiles?
