### ISSUE TITLE
Is there a way to disable XInput? only to use the Cemuhook UDP

### ISSUE THREAD

**Issue by rsilva48** [Ryochan7/DS4Windows#409]
So I usually use my controller with steam, so i get ds4 prompts and all in certain games, but now I want to use the touchpad and motion for citra, but I have issues mapping the controller when using DS4W emulating a x360c, but when I'm using steam, I don't have problems at all, So I was wondering if there was a way to just get the motion and touchpad info sent to the Cemuhook UDP without emulating a x360c

**Comment by Ryochan7** [comment]
In DS4Windows, it is possible. You can just set the DInput Only option in a profile to unplug the virtual XInput controller. The UDP server acts independently of ScpVBus or ViGEm and gets a copy of the input state from the controller.

However, using DS4Windows is not possible while using Steam's PS4 Controller Support. Also, it is not possible to use the DS4 outside of DS4Windows, if using a Bluetooth connection, once DS4Windows opens the device.
