### ISSUE TITLE
Light bar changes color on its own

### ISSUE THREAD

**Issue by lewisohn** [Ryochan7/DS4Windows#410]
I have one DS4 v2 controller connected to my PC with a USB cable and running through DS4Windows. I use a custom profile with a light green color for the light bar. Every now and then, however, the light bar changes to bright red, which I assume is the default color, by itself. To fix it, I have to open DS4Windows, choose "Use Custom Color" from the drop-down list, select any color, then go back to "Use Profile Color" to restore my preferred green.

I'm running DS4Windows v1.5.8, but this issue started a few builds ago at least. I use HidGuardian and my OS is Windows 10 version 10.0.17134 build 17134.

**Comment by lewisohn** [comment]
Possibly related: the issue seems to have stopped happening after I unticked the Minimize to Taskbar option in the Settings tab. I haven't seen it in a few days now.

**Comment by Ryochan7** [comment]
This sounds like an issue with the lag color not reverting back once latency goes back to normal. There are very rare occasions that some applications would hog system resources to the point where that would happen with a USB connection. There have been changes to how output reports are delivered for USB and Sony Wireless Adapter connections in recent updates. I am hoping that this issue would be resolved by now.
