### ISSUE TITLE
Pair with any Bluetooth Address???

### ISSUE THREAD

**Issue by ppsspp213** [Ryochan7/DS4Windows#411]
Is there any tool like ScpToolkit Bluetooth Pair Utility (legacy) that allows you to write any Bluetooth Address but for the DS4 instead?, I need to pair it with 
02:00:00:00:00:00 which I think is the default address for all Amazon Fire TV / Stick and the pin 0000.
I tried automatically pairing it with the hold PS and share button and it's recognized as a Wireless Controller but it refeuses to pair cause it still has my PS4 address tied to it.
All I could find is this script https://eleccelerator.com/unpairing-a-dualshock-4-and-setting-a-new-bdaddr/

**Comment by Ryochan7** [comment]
I would not think that type of utility should not be necessary. I don't know of any other tool like that.

**Comment by ppsspp213** [comment]
> 
> 
> I would not think that type of utility should not be necessary. I don't know of any other tool like that.

ah ok, it may still be possible by customizing the Bluetooth Address in windows, I know it's possible on rootable Android devices but i'm not sure if under windows the address is always read directly from the hardware chipsets themselfs or written to those .inf settings files when you install the drivers.
