### ISSUE TITLE
Mouse and Keyboard inputs

### ISSUE THREAD

**Issue by DavidPosher** [Ryochan7/DS4Windows#412]
Ds4Windows is causing the shoulder buttons on my controller to cause inputs from my mouse and keyboard and try as I might, I cannot figure out what is causing it. Any help would be greatly appreciated.

**Comment by BlackPowerade** [comment]
Sounds like it might be corrupted profile, try making a fresh one from scratch and see if that helps.

**Comment by Ryochan7** [comment]
Other people have brought up similar situations before. Something else has to be conflicting as DS4Windows is not set up to do this.
