### ISSUE TITLE
Can't use with Bluetooth after update

### ISSUE THREAD

**Issue by rikusen0335** [Ryochan7/DS4Windows#413]
maybe it is not caused by update, but did you do anything?

**Comment by Tusky** [comment]
Same, DS4windows (I used the original one, and switched to this since it had issues) says using in shared mode, and it's not identifying my controller. The PC does identify it and my game identifies it too, but not DS4Windows.

**Comment by Tusky** [comment]
Removed BT driver (the windows one) manually updated windows (had some cumulative update), reinstalled the driver, and now it seems to detect it.

**Comment by jonaaa20** [comment]
Never use these "Toshiba" or "CSR Harmony" drivers, always use the windows one.

**Comment by Tusky** [comment]
Yeah I never installed any BT driver, that's why I didn't think it was the issue, but even checking for driver updates said latest drivers. So my guess an anniversary update mixed something up.

**Comment by Rikusen0335** [comment]
I don't own Third party hardware. I have only Sony's BT one. Btw, I'm sorry but could you tell me how to recognize where is BT driver, and delete it.

**Comment by Tusky** [comment]
https://support.microsoft.com/en-us/help/4028443/windows-10-update-drivers
https://support.microsoft.com/en-us/help/14169/windows-10-fix-bluetooth-problems
```
In the search box on the taskbar, type Device Manager, and then select Device Manager from the list of results.
In Device Manager, select Bluetooth. Press and hold, or right-click, the Bluetooth adapter name, which may include the word “radio”, and select Uninstall device.
Select the Start  button, then select Power  > Shut down.
After your device shuts down, wait a few seconds, and then turn it back on. Windows will try to reinstall the driver. 
If Windows doesn't reinstall the driver automatically, open Device Manager and select Action > Scan for hardware changes. 
```
