### ISSUE TITLE
R1 button on my ds4 controller is acting up

### ISSUE THREAD

**Issue by MadeThisAccountForThisIssue** [Ryochan7/DS4Windows#414]
So, Im using DS4 windows for about 4 months now and never had a comlaint but like 5 days ago out of nowhere my R1 started doing weird stuff. I was playing GTA V like normal and it crashed so I started it up again but now my R1 was causing the camera to spin around. I know what youre thinking: must be a GTA issue but it isnt cause if I use big picture from steam all works fine and I have the same problem on other games. The problem is that R1 is giving a mouse input even though I have it selected as right bumper. Ive tried downloading ds4 windows again, ran tests too see if it was gta or ds4 windows, made new profiles and more but it just stays the same.

**Comment by BlackPowerade** [comment]
Sounds like it might be your controller or how windows is translating the controller inputs. Try unpairing your controller and removing it from the list of bluetooth devices, then re-setting it up.

**Comment by Ryochan7** [comment]
There isn't much to go on here. All that I can say is that it works just fine for me with other games. I will assume that you either resolved the issue or moved on to using Steam controller mapping support instead.
