### ISSUE TITLE
DS4 v2 vibrates when tilt up.

### ISSUE THREAD

**Issue by MarioPL98** [Ryochan7/DS4Windows#422]
I just bought my first DS4 controller and I have a problem. Every time I pick up the controller (tilt up) it starts vibrating for few seconds. This does not happen when DS4Windows is off.

**Comment by BlackPowerade** [comment]
Be sure you do not have it mapped to vibrate on tilt up. Try making a new profile from scratch or repairing your controller. I have a V2 and have never encounter this issue, but I have had DS4Windows turn use Dinput only on sometimes.
It just does some weird stuff sometimes.

**Comment by MarioPL98** [comment]
Thanks. It worked. It seems like my default profile was corrupted.
