### ISSUE TITLE
Same as other ds4.. always have to change ports (orange light)

### ISSUE THREAD

**Issue by slikk66** [Ryochan7/DS4Windows#425]
This was problem with the other one so I tried here to see if this worked better being newer and all.

When using this program, it will work sometimes but if unplugged, then plug back into same port, the light flashes orange and the controller isn't recognized by Windows 10 or the program.  If you have enough ports, you can usually find one that works but right now I've tried all open 4 ports and all of them flash orange and then nothing.

It was working before the computer restarted.. so what gives?  Any way to "reset" the system so it will work again?

Using 1.5.8

Thanks!

**Comment by slikk66** [comment]
Just found this.. have searched in past but this was only published about 6 weeks ago: https://www.youtube.com/watch?v=ycM-dRk1moQ

**Comment by Ryochan7** [comment]
It is a consequence of the Hide DS4 option. Even recently, I found another problem with the routine that would affect anyone running DS4Windows as a normal user (almost everyone); I almost always run DS4Windows as admin so I did not run into the problem before. There was chance of a device grab happening before the disable and re-enable routine was completely finished. When that happens, the device can become permanently disabled after unplugging the DS4. That fix is not in any binary build yet.

https://github.com/Ryochan7/DS4Windows/commit/13005458f146c2cbd783a5a2153dc28d91772401

Using HidGuardian is a safer option than using the exclusive mode workaround.

**Comment by Ryusennin** [comment]
Just wondering: should exclusive mode be disabled if HidGuardian is installed, or are the two features independant?

**Comment by Ryochan7** [comment]
When only one program is using HidGuardian then the routine should not matter as exclusive access should be obtained on the first pass without using the "Hide DS4 Controller" routine. If multiple programs are using HidGuardian then the "Hide DS4 Controller" routine would likely still attempt to run if you have the option enabled.
