### ISSUE TITLE
Allow changing the Steam Library folder for Auto Profiles "Add Steam Games" functionality

### ISSUE THREAD

**Issue by Earthnuker** [Ryochan7/DS4Windows#426]
I have my Steam Library on a separate drive because i don't want it to clutter up my C: Drive, when i clicked the "Add Steam Games" button in the "Add Program" menu it tried adding games from the default SteamLibrary folder on my C: Drive and as far as i can tell `WinProgs.cs` has the path to the default Steam library hardcoded, would it be possible to add a folder selection dialog to choose an alternate location? (maybe in addition to the current hardcoded paths)

(my current workaround was just patching the path in the executable using dnSpay because i didn't want to compile from source)

**Comment by Ryochan7** [comment]
With how brittle DS4Windows has been, I don't think that this type of feature will be implemented.
