### ISSUE TITLE
Missing quotation marks around the devcon.exe arguments in 'HIDGuardian Helper Files.zip'

### ISSUE THREAD

**Issue by trustin** [Ryochan7/DS4Windows#427]
In the `Install HIDGuardian*.bat` in `HIDGuardian Helper Files.zip` mentioned in [the wiki page](https://github.com/Ryochan7/DS4Windows/wiki/DS4Windows-and-HIDGuardian---Install-and-Setup-Guide), the argument `%~dp0\HidGuardian.inf` must be wrapped with quotation marks, because otherwise the `devcon.exe` will fail when the current directory contains a space. It may work if your filesystem creates a short name, but some users, including me, do not have that enabled.

**Comment by TristanYoung** [comment]
Hello trustin.

Thank you for pointing out the error.  I've updated the script.

https://github.com/TristanYoung/HIDGuardian-Helper-Files/raw/master/HIDGuardian%20Helper%20Files.zip
