### ISSUE TITLE
Silently Uninstall 360 Accessories Guide Button Popup

### ISSUE THREAD

**Issue by shinra358** [Ryochan7/DS4Windows#43]
Can you code into ds4windows to silently uninstall the xbox 360 accessories addon that automatically installs with the xinput drivers? The popup that comes up is annoying everytime you press the guide button. Make a check on startup to see if it resides in its location, and if it does, silently uninstall it. Would prevent this annoyance whenever we would need to reinstall the xinput drivers just in case something goes wrong with the program.

**Comment by pralima87** [comment]
You can disable itself in the "game bar" options.
Also you could set the "guide" button to "unbound" and it will stop acting like that.

**Comment by shinra358** [comment]
I know. But i just unistalled it because its unnessessary. But if i had to
reinstall, i dnt what to have to keep doing it, hence why i want it to be
done for me so i dont have to worry about it.

**Comment by pralima87** [comment]
Dude just press Win+G and in the settings disable "open gamebar using **guide button** on a controller".
Is really that easy.

**Comment by shinra358** [comment]
No. Unnessessary programs on PC are unnessessary. Plus, this is nothing as
far as coding goes. Easy. This aint a help question. This is not an advice
asking post. And everyone benefits from it. So theres no point in fighting
against it :P. Programs are created for the very reason of simplifying
actions. You, squall leonhart, and the creator of desmume should get
together and call yourselves.... 'the non-progressives' xD

**Comment by Ryochan7** [comment]
The game bar feature is annoying but I don't want to have DS4Windows automatically uninstall other unrelated software. This is especially a problem considering the software is bundled with the OS. It is easy enough to disable the Game Bar if you don't want to use it. This whole issue really stems from using Windows 10 in the first place and dealing with Microsoft's bad decisions. There are many reasons why Linux is my primary OS and I mainly use Windows only to play some PC games not available on Linux. I'm sorry but I am going to mark this as wontfix.

Also, this is not Reddit.
