### ISSUE TITLE
Controller automatically goes to #2 after disconnect

### ISSUE THREAD

**Issue by FirionHope** [Ryochan7/DS4Windows#430]
After a disconnect either manual or through idling the controller defaults to being controller 2, and then so on and so forth for every disconnect afterwards. Is there any way to lock it into controller 1 position or at least switch it back? I'm wondering if its not something with steam trying to hijack it even though I have it disabled on steam.

**Comment by Ryochan7** [comment]
I don't know if it is something happening with another program or a problem with ScpVBus. There used to be problems when ScpVBus would not release a port after disconnecting a controller. Those problems have been addressed but maybe some issue could be popping up again; the latest issue mainly affected Windows 7. ViGEm does not have this problem but it is not being used right now.
