### ISSUE TITLE
REQUEST: OR operator in activate gyro trigger

### ISSUE THREAD

**Issue by BlackPowerade** [Ryochan7/DS4Windows#431]
The gyro scope can be activated with one or more triggers, but not one **OR** the other trigger(s).

![or](https://user-images.githubusercontent.com/21957509/45646330-f0a1e980-ba90-11e8-8809-62b99793dd29.png)

Would there be a way have DS4Windows set an OR? Or possibly a way to express it via the XML file?

**Comment by Ryochan7** [comment]
It probably wouldn't be too difficult to allow the trigger condition to behave as an OR condition rather than an AND.

**Comment by Ryochan7** [comment]
There is a new eval condition setting for Gyro Mouse that can be used to have the trigger condition behave as an OR condition rather than an AND. It seems to work fine. I don't know if I would have a use for it myself as I use the most basic use case of using one control for the trigger.

**Comment by BlackPowerade** [comment]
Awesome, thank you @Ryochan7.
