### ISSUE TITLE
Is it possible to add input interpolation/smoothing?

### ISSUE THREAD

**Issue by MarioPL98** [Ryochan7/DS4Windows#433]
Is it possible to set interpolation for controller readings? Especially gyro readings.

**Comment by Ryochan7** [comment]
The only portion where smoothing is enabled currently is when using Gyro Mouse. I have not seen a need for smoothing when using Gyro Controls as it seems to feel fine when using the raw values from the accelerometer. Using smoothing for Gyro Mouse has been useful to get rid of some jitter and to add some minor resistance to the mouse cursor.

A weighted average algorithm is used for Gyro Mouse smoothing. You can only change the weight percentage that is used to change the weight applied to old input values; setting the value to 1.0 would be equivalent to using a simple average. The number of samples in the buffer is set to 3 input values.
