### ISSUE TITLE
The gyro is spinning insane, it's not working for me. Help.

### ISSUE THREAD

**Issue by TwelveV0n** [Ryochan7/DS4Windows#439]
The gyro thing is not working for me, the last 2 are completely at the left and don't move at all, the first just move if i tilt hard my controller. And if i test on PadTest, the ds4 keeps spinning insane. You can se by the number in the description of PadTest. Help, please, i didn't that problem with no one else. If i change to use the gyro as mouse, the program just close.
I use USB connection to play and the last version of DS4Windows.
![screenshot_5](https://user-images.githubusercontent.com/43710624/46250661-e3341a00-c415-11e8-904d-d39ea33efacd.jpg)

![screenshot_4](https://user-images.githubusercontent.com/43710624/46250644-8173b000-c415-11e8-837c-5280fa4e1929.jpg)
![screenshot_2](https://user-images.githubusercontent.com/43710624/46250620-fbf00000-c414-11e8-8548-ec5b3ccead73.jpg)
![screenshot_3](https://user-images.githubusercontent.com/43710624/46250621-fdb9c380-c414-11e8-8c26-6581a57eb856.jpg)

**Comment by Ryochan7** [comment]
The numbers seem to imply that gyro calibration failed. I wouldn't think that it would happen for a USB connection. Which controller model are you using? Only the Nacon controllers have a routine set in place to skip attempting to perform gyro calibration and just use the raw data from the device. Just for reference, I have an official Sony DS4 v1 and a DS4 v2.

**Comment by TwelveV0n** [comment]
Another old versions of this program (before UDP) the gyro was working.

**Comment by TwelveV0n** [comment]
> The numbers seem to imply that gyro calibration failed. I wouldn't think that it would happen for a USB connection. Which controller model are you using? Only the Nacon controllers have a routine set in place to skip attempting to perform the gyro calibration routine. Just for reference, I have an official Sony DS4 v1 and a DS4 v2.

**Comment by TwelveV0n** [comment]
Another old versions of this program (before UDP) the gyro was working.
I have a DS4 V1, if you want i can send a photo of it.

> The numbers seem to imply that gyro calibration failed. I wouldn't think that it would happen for a USB connection. Which controller model are you using? Only the Nacon controllers have a routine set in place to skip attempting to perform the gyro calibration routine. Just for reference, I have an official Sony DS4 v1 and a DS4 v2.

**Comment by Ryochan7** [comment]
I just wanted to make sure that a third party controller was not being used since I have no way to support it. The gyro routine will always attempt to run with a USB connection so flawed numbers could cause some problems (division by zero?). Do you still have a copy of the working version and the version number?

**Comment by Ryochan7** [comment]
Version 1.5.15 has a gyro calibration check that should at least ensure that a division by zero will never occur. If the divisors that would be used for calibration end up being 0 then calibration routines will be skipped and the raw values from the gyro will be used.
