### ISSUE TITLE
Hide DS4 Not Working

### ISSUE THREAD

**Issue by Wakkowarner123** [Ryochan7/DS4Windows#442]
With Steam, Uplay and other suspect programs closed, as well. Tried installing HidGuardian, but gives the same result.

**Comment by Ryochan7** [comment]
Another possible culprit is GeForce Experience if you have it running. The old Hide DS4 option can be very temperamental. I know that I have had Hide DS4 fail more often while Steam is running than in the past but it just seems like a side effect of updates to both pieces of software. There doesn't seem to be a definitive reason why exclusive mode would fail more often. One suggestion that I have is that you might want to run DS4Windows as the admin.

HidGuardian should work fine as long as DS4Windows is launched with admin privileges and the AffectedDevices registry entry is correct. I would suggest that you run DS4Windows as admin either way.

**Comment by Wakkowarner123** [comment]
Ah, the AffectedDevices registry entry was the problem. Now it works
perfectly, thanks! But now my Dinput passthru profile doesn't work at all.
I could choose "turn off DS4Windows temporarily", but then I lose Bluetooth.

**Comment by Wakkowarner123** [comment]
Actually, now I can't seem to *un-hide *my DS4 controller, enabling and
disabling the option doesn't do anything, even on restart.

**Comment by Ryochan7** [comment]
Sort of related. Ever since changing the hotplug routine around Oct. 16, I have not had the Hide DS4 routine fail once while Steam has been running.
