### ISSUE TITLE
Some issues, Idle disconnect does not work.

### ISSUE THREAD

**Issue by dem0z** [Ryochan7/DS4Windows#45]
Been having some issues, Idle disconnect doesn't do anything my ds4 is connected through a cable and idle disconnect is set to 5 minutes and the light just stays on never turns off, same for BT.
Another minor thing, the middle click does not also work usually it's supposed to exit the program.
am using the latest version 1.4.72 on windows 10.

**Comment by pralima87** [comment]
Idle disconnect is just for BT and Sony dongle.
On cable the controller will stay connected.

All of those issues are not happening on my end so it could be that you need a reinstall of the drivers.

**Comment by dem0z** [comment]
well the controller always stays lit up and as i said even in BT, i already removed the drive and reinstalled, with default profile then set idle disconnect, same results always on.

**Comment by Ryochan7** [comment]
Just tested this with Bluetooth and the Sony dongle and idle disconnect works properly on my system. Idle disconnect checks are skipped if the controller is charging via a USB cable so that is working as intended. If idle disconnect activated while charging the controller in a previous version then that version was broken as it was not designed to work that way. Can you share the profile that you are using or at least specify what time interval you are using for idle disconnect?

Also, middle click on the tray icon works on my system fine.

**Comment by dem0z** [comment]
[Default.zip](https://github.com/Ryochan7/DS4Windows/files/1030077/Default.zip)
It's just the default profile with idle disconnect set to 1 minute. 
I deleted everything, removed the driver then reinstalled the driver and middle click is working again, not idle disconnect though, still the same.

**Comment by pralima87** [comment]
Are you on the regular DS4 controller or the **pro** one?

**Comment by Ryochan7** [comment]
The profile works fine on my system. The only thing that I can think of that might cause a problem is maybe the controller idle check is somehow failing. Is there any large jitter with your analog sticks? Is there something on the touchpad that might be causing the program to detect a touchpad press event? The idle disconnect routine is working as intended so I am wanting to think that the problem has to be regarding how the controller state is being interpreted.

**Comment by dem0z** [comment]
Nope this is the normal DS4 and as i can see the controller is clean no dust or what not, it's kinda new too well it's 3 months old. No jitters or anything everything is steady, maybe it's my windows or something messed up and not hardware, no idea.

**Comment by shinra358** [comment]
OP is correct about it supposing to disconnect. I was the one that asked jay for the feature. But, when plugged, the light only is supposed to time out. Controller is not supposed to fully disconnect. Not the charging mode light, but the normal non-charging light is supposed to follow the rules of the idle time. And of course any button press afterwards is supposed to reilluminate said light.

**Comment by Ryochan7** [comment]
Thanks shinra358 for the clarification.  I am taking a look at this with version 1.4.52. It looks like light dimming does not work when the controller is plugged in with that version either. However, the light does dim as the idle disconnect timer winds down when the controller is not plugged in. The latest release works the same way. I will check the code and try to get this functionality working as intended.

Also, the Color by Battery % option has to be enabled in order for light dimming to work with the idle disconnect timer. The option is not enabled in the profile that was posted.

**Comment by Ryochan7** [comment]
Update. I found the problem but I would like clarification about what the behavior should be in one case. Should light dimming always occur when plugged in, when the battery is fully charged, or only while the battery is still charging? In the current code, light dimming will only work when the controller is plugged in if the battery is fully charged.

**Comment by shinra358** [comment]
Yes that is correct. Only when fully charged. No dimming while charging.

**Comment by dem0z** [comment]
Sorry if i confused you or anything it's as shinra said the light used to dim aka idle disconnect while plugged in.

**Comment by shinra358** [comment]
Fix not working.

**Comment by dem0z** [comment]
I can confirm too, it's still the same as before.

**Comment by aurelbdx** [comment]
Same problem here with version 1.4.75. Idle disconnect does not work.
I use DS4Windows v1.4.52 to solve this issue!

**Comment by aurelbdx** [comment]
I have this problem since version 1.4.58. Idle disconnect works with 1.4.57 (2 Apr) but it doesn't work with the next versions.

**Comment by shinra358** [comment]
You mean while wired right? Because it works wireless.

**Comment by aurelbdx** [comment]
Yes only while wired. Idle disconnect works with 1.4.76 with bluetooth

**Comment by shinra358** [comment]
yeah, new version still has the issue.

**Comment by shinra358** [comment]
Noticed an issue with the gradual dimming during the idle time countdown (bluetooth). The max brightness is supposed to be determined by the color bars. At the time brightness is supposed to be determined by battery percent. From there, idle timer is supposed to dim the color even more based on time left of complete idle disconnect. BUT, it only starts doing this in the last 30 seconds. It's supposed to do it as soon as the idle timer has some time built up all throughout until a button is pressed, then it returns to the max color bar number + current battery % until idle timer dims it gradually as time passed without a press.

**Comment by shinra358** [comment]
any update to this issue?

**Comment by Ryochan7** [comment]
I tried looking into this and nothing seemed to stand out. It was the last time I edited DS4Lightbar.cs which was the 18th. I will try to properly debug that section and check what might be happening.

**Comment by aurelbdx** [comment]
This is what you changed since I have this problem:

Version 1.4.58 (8 Apr)
- Added initial support for Sony DS4 Wireless Adaptor
- Allow disconnect from Controllers tab to work with DS4 Wireless Adaptor. Change was made thanks to aspalmer
- Fixed issue with multiple special actions causing program crashes
- Fixed various special action types
- Small changes to improve performance for mapping translation

**Comment by Ryochan7** [comment]
Well I stink. Found an old assumption that kept this functionality from working with USB connections. I have tested it with a recent test build and the most recent change. Idle disconnect light does not work with the test build for a USB connection but it works as intended with the most recent change.

**Comment by shinra358** [comment]
can you upload this build?

**Comment by Ryochan7** [comment]
Work on the Gyro mouse mode is the main task keeping a new release from
being made. Constant tweaking of some base variables is still being done.
It is working fairly well now and I am playing through Turok using Gryo
mouse. I might just put out what has been done so far and assume that the
profile settings will work slighly differently in a future release.

**Comment by Ryochan7** [comment]
Got a new version packaged

https://github.com/Ryochan7/DS4Windows/releases/download/v1.4.81/DS4Windows_1.4.81_x64.zip

**Comment by dem0z** [comment]
Just gave it a try for the test build and it's all sorted out in it, thanks mate :)

**Comment by shinra358** [comment]
yeah, all good here.

**Comment by aurelbdx** [comment]
Same here! Thanks Ryochan7
