### ISSUE TITLE
[bug]Ds4Windows 1.5.9 no longer works wirelessly

### ISSUE THREAD

**Issue by LingKuja** [Ryochan7/DS4Windows#451]
I don't know what happened with this release, but it seems that it won't work wirelessly anymore. 
Here's the log, but, of course, it won't show any failed connection. (between 13:15 and 13:18 there were some connection attempts by my controllers.
[159 2018.txt](https://github.com/Ryochan7/DS4Windows/files/2460149/159.2018.txt)
And these are my settings. 
![ds4windows_2018-10-09_13-22-21](https://user-images.githubusercontent.com/35222780/46666211-613ab280-cbc6-11e8-9769-f9ed703e96d8.png)

Edit: After a while I figured that _maybe_ my damn bluetooth dongle was on the fritz, so I resetted it. so, i'm sorry for having wasted your time. It was my damn bluetooth doing weird stuff on the background. The wireless functionality is still here and works just fine, it was my bluetooth adapter that needed more attention\ a damn reset.

**Comment by Ryochan7** [comment]
Thank you for the update. I tried using Bluetooth on my machine and it worked for my controllers. Lately, I have been using the Sony Wireless Adapter so I haven't tested a BT connection in about a week. I was pretty sure that I didn't edit anything related to device connections though.

**Comment by LingKuja** [comment]
> Thank you for the update. I tried using Bluetooth on my machine and it worked for my controllers. Lately, I have been using the Sony Wireless Adapter so I haven't tested a BT connection in about a week. I was pretty sure that I didn't edit anything related to device connections though.

Indeed it works with bluetooth\wirelessly. as I wrote in the edit, the BT had a driver update that did something that needed me to re-pair the controllers. DS4Windows 1.5.9 works perfectly as for now.
