### ISSUE TITLE
Weird "unhandled exception has occurred in your application" everytime i try to exit and close DS4windows

### ISSUE THREAD

**Issue by Fujosej** [Ryochan7/DS4Windows#452]
![image](https://user-images.githubusercontent.com/37980944/46681704-7d554880-cbf4-11e8-9457-e4309911fd31.png)

This is a full error message 
https://pastebin.com/vHcH1iTh

I have no idea why this happens , everytime i exit DS4windows with plugged Dualshock4 controller ,it shows me this weird error.
Is there a way to resolve this issue? 
Thanks!

**Comment by Ryochan7** [comment]
It does look like problems can pop up if you leave the profile editor open and then try to close the application from a different tab. Objects are likely getting destroyed out of order. This would be a low priority issue for me as the profile editor would be closed after finished editing when I use DS4Windows. I would not run into this error during normal use.

**Comment by Fujosej** [comment]
Got it , thank you!

**Comment by Ryochan7** [comment]
.NET thinks that this problem is not worth fixing. Fixed the routine in a few ways only to have .NET hate each one and bring performance down. Going to file this under won't fix unfortunately.

**Comment by nmcdougal94** [comment]
I am having issues with this bug as well, and with actually getting into the profile editor. It won't allow me to map buttons, it will simply flash the mapping editor incredibly briefly, and then auto assign a button.
