### ISSUE TITLE
Starting screen

### ISSUE THREAD

**Issue by MuteButtonHero** [Ryochan7/DS4Windows#457]
When I start DS4W it always begins on the main display no matter where I last used it. Can you add the ability for DS4W to remember what display it was last used on and start there? Or a mechanism to configure which screen it will start on. 

I like DS4W but it is annoying to have to move it every time I start it.

**Comment by shinra358** [comment]
this is an issue on most programs period. I would suggest the user seek ahk so that his problems can be solved everywhere. I was actually working on a script myself for this issue. havent finished it yet though.

**Comment by mika-n** [comment]
this feature is feasible but not likely to happen in anytime soon. It is just a one-click to open any of those top level tabs.
