### ISSUE TITLE
Text on settings screen is cut off

### ISSUE THREAD

**Issue by MuteButtonHero** [Ryochan7/DS4Windows#458]
The line "Use language pack" is chopped at the top. See attached pic.

<img width="347" alt="ds4w bug" src="https://user-images.githubusercontent.com/43922149/46912043-a9910200-cf31-11e8-9594-ed7dbcb9a9a6.PNG">

**Comment by Ryochan7** [comment]
It looks like the flow layout is not doing its job. That control should be in the next column in this case. Maybe it is a margin problem. I will look into it.

**Comment by Ryochan7** [comment]
I could not duplicate this problem no matter what size I made the main window. Margins and padding for the container seemed fine. I ended up disabling auto size for that control so hopefully that helps somewhat.
