### ISSUE TITLE
[Request] Razer Raiju Ultimate Support

### ISSUE THREAD

**Issue by tokataka** [Ryochan7/DS4Windows#460]
Hi,
Could you update to support Raiju Ultimate?
USB: VID_1532&PID_1004
BT: VID_1532&PID_1009

**Comment by Ryochan7** [comment]
I can add an entry later today and post a test build so you can check that it works. I don't have that controller so I have no way to test it out myself.

**Comment by Ryochan7** [comment]
Test build

http://ryochan7.xyz/ds4windows/test/DS4Windows_RaijuUlt_Test_20181017.zip

**Comment by tokataka** [comment]
It works on USB connection but BT doesn't.

![1](https://user-images.githubusercontent.com/22884343/47149285-17607380-d30e-11e8-8cc8-44c6e214add7.png)
![2](https://user-images.githubusercontent.com/22884343/47149287-192a3700-d30e-11e8-81b1-5d6a356d35ee.png)

**Comment by Ryochan7** [comment]
The blank serial would be an issue with some portions of the application. Also, no BT support is a bummer.

As it stands, there will be no added support for the Razer Raiju Ultimate controller in DS4Windows.

**Comment by jontan1** [comment]
Can I have this version so I can test it out if it works for the tournament edition, dont need BT support wired is fine.

**Comment by Ryochan7** [comment]
I can make an updated build later based on the upcoming version 1.6.11 release. You would have to disable program update checks because the blank serial issue is a show stopper for integration.

**Comment by Ryochan7** [comment]
Here is a build of version 1.6.11 with the Raiju Ultimate entries added.

https://drive.google.com/open?id=1UjdMnCbgo5hZJ40NwtehyAzYumlW8ZYB
