### ISSUE TITLE
DS4 not working in Steam if launched in Tridef3d 7.0 in w10 rs5

### ISSUE THREAD

**Issue by MatthewHunter1983** [Ryochan7/DS4Windows#461]
hi folks this is kind of a weird issue. ever since windows pushed Redstone 5 v10.0.17763 my ds4 windows (now v1.5.11) stopped working in Steam--only when launched with TriDefIgnition.exe (v 7.0)… it used to work with ds4 windows w/ this method of 3d injection to steam, now it doesn't. (with 'hide ds4 controller' activated of course)

unsure if this is steam's issue or tridef's issue but hoping there is some way it can be fixed. ds4 windows does work correctly when launching the game normally via steam shortcut. Launced with Tridef, however, ds4windows does not work (it did work this way before)--and I am forced to use steam's ugly ps4 detection which probably uses maximum Bluetooth polling rate, has a bright ass turquoise light that I hate / drains batteries, and all the other ds4 windows configurations that I love are completely unavailable. (even though i'm glad I finally got the controller to work in tridef 3d on this revision of the OS--didn't want to have to revert my OS just for this. but I still want ds4 windows to work in this new software environment).

the only thing that works w/ ds4 enabled (+ tridef + steam) is pressing the ps4 touch pad = confirm in game. a steam popup that came up one time ever said something about a conflict with controllers. I fiddled with steam's convoluted controller settings (and reset them), tried reinstalling steam--that forced me to reinstall dragon quest xi (game in question … even though it was already on my hard drive. stupid steam....), reinstalled tridef, reinstalled ds4 windows (uninstalling/reinstalling vbus driver), cleaning registry/program data/AppData for everything, tried cleaning up ghost devices in device manager of the hardware IDs associated w/ the controller, using drivecleanup.exe in safe mode to clean more, tried installing things with driver signature enforcement disabled and everything about windows gameDVR disabled, and defaults, tried reverting to ds4 1.4.52 public release same behavior, tried 'write (and clear) hidguardian device list,' tried excluding ds4 folder from windows defender, tried running things in compatibility mode--nothing i have tried is fixing this. please help and ty! <3

**Comment by Ryochan7** [comment]
It sounds like you are launching DS4Windows with the launcher. If that is the case, maybe the virtual XInput controller is seen too late to be detected. I would run DS4Windows outsides of any launcher script. There is no way to switch profiles around from the command line to allow a launcher to engage with an already running instance of DS4Windows though. Profile switching would have to be done manually. It is a pain but that might be best. If nothing else, maybe you can add a long sleep command in a launcher script if you can.

With the issues that I have come across trying to edit Program.cs (used to read command line arguments), there will be no chance of adding a way to switch profiles from the command line.

**Comment by MatthewHunter1983** [comment]
nope. not launching anything but steam > dragon quest xi with "tridef 3d ignition" launcher (and it properly launches / everything used to work). ds4 windows is already running before any of this as always.

but now, when I launch from tridef, then ds4 windows causes everything on the controller to stop working except mouse pad. (unlike before). everything works normal w/ ds4 windows in steam / dqxi if I don't use 3d injection, but If I do controller stops working (except for mouse pad)

**Comment by MatthewHunter1983** [comment]
^ just confirmed the above scenario. launched ds4 windows, connected controller (no errors), open tridef ignition > launch steam game (dqxi) > controller not working (except mouse pad)

exited game (didn't even exit steam) > launched a different non steam game from tridef ignition (ffxv) > controller works fine …

I could test my only other steam game (ff mobius), but I'd have to install it and hate steam w/ every fiber of my being because of situations like this and have a feeling it'll be the same behavior.

**Comment by MatthewHunter1983** [comment]
I figured it out. found a tridef forum on this very topic (ds4 windows functionality in steam) and it said enable launch in big picture mode in steam. that didn't really fix it, but it will launch stream's crap first, then the game, where controller doesn't work still, but then I can exit that instance of the game, alt + tab to windows and stop/start ds4 windows / connect Bluetooth again, then go back to tridef injected big picture steam and the controller is then connected and I can launch the game w/ working ds4 windows @_@;

didn't have to do this before, but I got it working. hopefully this can be fixed, thanks!

**Comment by Ryochan7** [comment]
That sounds really convoluted but it is good that you got it working. I doubt any changes in DS4Windows would have affected the behavior but .NET throws some weird behavior out there every once in a while. It would probably be just a matter of luck if that behavior would change in future updates.

I have my gaming PC hooked up to my TV so BPM has been useful to me in the past although I don't use it now. The Steam Controller Mapper has never been useful to me which is a shame since I have a Steam Controller; I use the SC-Controller program instead which does a much better job but that is a Linux only program.
