### ISSUE TITLE
Latest version enters the number 1 into active text box while connected, occasional disconnects

### ISSUE THREAD

**Issue by SirenBrink** [Ryochan7/DS4Windows#462]
Using release v1.5.12 with DS4 controller via bluetooth

While using DS4Windows and only while a controller is connected, for some reason the number 1 is entered repeatedly into any active text box.

Occasionally, the DS4Windows logo will disappear from the toolbar icons menu. Controller will remain connected but will not register xinput (touchpad mouse works intermittently).

**Comment by Ryochan7** [comment]
The first issue sounds like a dead zone problem. Do you have number keys mapped to the analog stick or triggers? The second issue sounds like a big oddity. The system tray icon should only disappear if the application is closed or if it has crashed. No events should be able to be generated if that were the case. Nothing should be keeping the process alive.
