### ISSUE TITLE
[Request] Option for gyro trigger condition to function as gyro on/off state toggle

### ISSUE THREAD

**Issue by vvilkommen** [Ryochan7/DS4Windows#464]
Hello again!

I am having a lot of fun with this program. It has smoothed my interaction with games, and windows in general... pleasant, really. Now I can finally tell games how I want my controller to be used, rather than the other way around! That alone is a breath of fresh air.

Recently, well with the update allowing for OR gyro trigger condition, I have begun using the gyro functionality. I really don't remember it being this clean -- it is a lot of fun and pleasantly, eerily precise. 

I truly appreciate the cleanness of the work and breadth of improvements. It is scary how good this program has become. 

Anyway, I would like to request, or add my name to the pile if there is already, the ability to toggle the gyro functionality on and off with the specified buttons. I have a game where part of the time is spent in fps and part is spent in "joystick mode," so it would really be nice to toggle gyro on for fps and off for platforming. 

Thank you for reading and thank you for maintaining this program!

edit: When in the toggled on state, I think it would be nice to be able to multitouch (not actually press the touchpad as a button, but rest two fingers on the touchpad) to disable gyro on demand. For example, when in fps mode, an enemy may run away to the side of me, prompting me to follow by rotating the controller. But now that the controller is almost perpendicular to the floor, but the enemy is now right in front of me, if it moves to the side, I would have to rotate even more to an uncomfortable position. If I could touchpad to disable, I could pause gyro (while keeping the enemy in view!), reset the controller position, release touchpad and resume following the enemy in plane with gyro -- all in a simple motion. I think gyro toggle with softpause would be very nice as an alternative to always on until held or always off until held.

**Comment by vvilkommen** [comment]
You and I think the same! I already had two profiles built with the intent to use the same special action in the two different profiles to switch between the two. I think it would closely approximate what I'm looking for (haven't had time to try it out), but I think I'd still like it to be a native feature, as a toggle. Plus it wouldn't have the ability to pause gyro by resting two fingers (not a button press) on the touchpad. I don't think.

**Comment by Ryochan7** [comment]
I am not sure if I really like this but the feature has been incorporated. I would normally use the trigger for locking the aim and have always on active otherwise. Having to press the trigger again to re-activate the aim is probably something I would not use. Multi-touch is an option for the trigger (2 Fingers on Touchpad) so just touching the touchpad, rather than clicking the touchpad button, would work for toggling the current aiming mode.

**Comment by Ryochan7** [comment]
After trying out Gyro Steering with the Steam Controller in the current Steam client, I noticed that the Gyro Behavior Button option has a toggle mode now. The option is available when using Gyro Mouse as well.
