### ISSUE TITLE
DS4Windows crashing, under a few circumstances

### ISSUE THREAD

**Issue by jasoncollege24** [Ryochan7/DS4Windows#465]
OS is windows 10 x64
DS4Windows version 1.5.13 x64
Controller in use is PS4 (BT)

First crash:
1. Pair controller with windows first
2. start (or click start in) DS4Windows.

Controller will appear, and then DS4Windows crashes.

Second:

1. Use motion (like padTest), and either crash, or close DS4Windows
2. Disconnect controller
3. restart DS4Windows.

DS4Windows will crash

Third:

1. Enable "Hide DS4"
2. in some cases, this crashes it immediately, since I can't get it to successfully hide DS4

If you want crash logs from event viewer, I can give them.

**Comment by Ryochan7** [comment]
I tested all three of those scenarios and they work fine on my machine. If there is some useful info in the crash logs then it would be good to post the output here. Otherwise there is not much that I can do.

**Comment by jasoncollege24** [comment]
Sorry for the delay. Life is crazy at times. :)

Looks like rebooting has resolved the first issue, but DS4 still seems to crash randomly, when "Hide DS4" is selected, and then seems to randomly crash after it is unselected, with continuous random crashing, if motion controls are in use (PadTest).

Another reboot will be needed to see if the motion control crashing is only after the first Hide DS4 crash. I can do that right after posting this, so you'll get an update on that in a few minutes.

Each crash gives me 3 source reports in Event Viewer. "Windows Error Reporting", "Application Error" (Specifically DS4), and ".NET Runtime". I'll guess you don't want the error reporting, and you want the other two.

Items in the code block marked with a * are different for each copy of the crash, so if you need all copies of each crash report, based on that, let me know please. Reports are below in XML format. If you need them a different way, let me know.

### Application error report
`- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2018-10-25T18:27:26.502754200Z" /> *
  <EventRecordID>32329</EventRecordID> *
  <Channel>Application</Channel> 
  <Computer>Jay-Desktop</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>DS4Windows.exe</Data> 
  <Data>1.5.13.0</Data> 
  <Data>5bcb7284</Data> 
  <Data>KERNELBASE.dll</Data> 
  <Data>10.0.17134.319</Data> 
  <Data>1e206b26</Data> 
  <Data>e0434352</Data> 
  <Data>000000000003a388</Data> 
  <Data>2bc0</Data> *
  <Data>01d46c8ffaa8b3ff</Data> *
  <Data>D:\DS4Windows\DS4Windows.exe</Data> 
  <Data>C:\WINDOWS\System32\KERNELBASE.dll</Data> 
  <Data>f748662d-bbd6-4bc5-94c9-a63828e81592</Data> *
  <Data /> 
  <Data /> 
  </EventData>
  </Event>`

### .NET Runtime report
`- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name=".NET Runtime" /> 
  <EventID Qualifiers="0">1026</EventID> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2018-10-25T18:27:25.757101000Z" /> *
  <EventRecordID>32328</EventRecordID> *
  <Channel>Application</Channel> 
  <Computer>Jay-Desktop</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>Application: DS4Windows.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.InvalidOperationException at System.Net.Sockets.SocketAsyncEventArgs.StartConfiguring() at System.Net.Sockets.SocketAsyncEventArgs.SetBufferInternal(Byte[], Int32, Int32) at DS4Windows.UdpServer.NewReportIncoming(DS4Windows.DualShockPadMeta ByRef, DS4Windows.DS4State) at DS4Windows.ControlService+<>c__DisplayClass44_1.<HotPlug>b__3(System.Object, System.EventArgs) at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon) at DS4Windows.DS4Device.performDs4Input() at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) at System.Threading.ThreadHelper.ThreadStart()</Data> 
  </EventData>
  </Event>`

**Comment by Ryochan7** [comment]
If the event log is reporting what I think it is, this issue should be fixed as of version 1.5.15. There are safeguards in place to help insure that a System.InvalidOperationException error does not occur while using the UDP server.
