### ISSUE TITLE
[Question] Does DS4Windows support the Dualshock 3?

### ISSUE THREAD

**Issue by Darthagnon** [Ryochan7/DS4Windows#466]
(I don't own either of a DS3 or DS4 yet - planning to get a DS3 first for the pressure-sensitive buttons and MGS3)
As per the title, I was curious, does DS4Windows support the Sony Dualshock 3 and its pressure-sensitive buttons? I realise it's intended for the DS4, but as several non-Sony controllers seem to have had support added, I was just wondering whether it would be possible to use DS4Windows when I get a DS3 or whether I'd have to install the scary-looking SCPToolkit driver...

**Comment by Ryochan7** [comment]
There is no planned support for controllers other than DS4 controllers. The current architecture does not really allow for it as many assumptions are made with the DS4 in mind. Also, I do not own any DS3 controllers. The other controllers that I currently own are an Xbox 360, Steam Controller, and Wiimote.

Getting a DS3 to work would probably require installing ScpToolkit. You might be able to try the newer FireShock driver instead for basic DS3 support. Shibari is supposed to be a replacement for ScpToolkit but it does not seem ready yet.
