### ISSUE TITLE
Application Error and Crash

### ISSUE THREAD

**Issue by Eloeri** [Ryochan7/DS4Windows#467]
I've updated to the latest version, but after a few minutes of running DS4Windows, it just closes. In the eventviewer, I see this:

```
Faulting application name: DS4Windows.exe, version: 1.5.13.0, time stamp: 0x5bcb7284
Faulting module name: KERNELBASE.dll, version: 10.0.17134.319, time stamp: 0x1e206b26
Exception code: 0xe0434352
Fault offset: 0x000000000003a388
Faulting process id: 0x5c0
Faulting application start time: 0x01d46bb067d89a96
Faulting application path: C:\DS4 Windows\DS4Windows.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: b777563e-4fb7-4a30-bbce-f8d9b910430b
Faulting package full name: 
Faulting package-relative application ID: 
```

Any ideas?

**Comment by Ryochan7** [comment]
That log doesn't really say anything useful. Are you using the UDP server and running Cemu when DS4Windows crashes? I am hoping that is the case so the problem might be related to issue #454.

**Comment by Eloeri** [comment]
I am running Ds4 windows, but not Cemu when it crashes.

**Comment by reecespieces** [comment]
> 
> 
> I am running the UDP server with Ds4 windows, but Cemu isn't running when it crashes.

What about Citra? That would probably cause the same issue - since Citra supports motion controls using cemuhooka as well
