### ISSUE TITLE
Output gyro data to Ableton Live/MaxMSP/ other programs

### ISSUE THREAD

**Issue by ryantburke** [Ryochan7/DS4Windows#470]
Is it possible for someone to make it so any program can access gryo data from the HI device? Or via UPD or something?

I want to make music with these outputs.

Thanks!

**Comment by mika-n** [comment]
Isn't there already UDP server functionality in DS4Windows which could be used for that purpose? However, don't ask me how to use it because I have never personally used it but that feature is supposed to be used by client apps to read DS4 controller state.
