### ISSUE TITLE
Using Touchpad Left/Right to Click/Hold LMB

### ISSUE THREAD

**Issue by Anzaru** [Ryochan7/DS4Windows#472]
I have DS4Windows the latest version I think (1.5.14) set up with my PS4 Controller. Everything else works fine but I cannot seem to get the touchpad to hold left click let alone tap left click. I've bound it to other keys and pressing the touchpad works fine but when bound to Left Mouse Button it doesn't seem to do anything.
I've tried to get around this by macro'ing my left mouse button but it doesn't hold LMB down while I hold the touchpad down, just quickly clicks it, so that doesn't work for me as i need to be able to hold LMB.

Is there a way around this? Or is it maybe something I've set up wrong?

**Comment by Ryochan7** [comment]
Touchpad Click works fine for me. Is the problem happening on the desktop or in game? If it is in game, you might need to run DS4Windows as admin. Emulated mouse clicks should work fine on the desktop even if DS4Windows is run as a normal user.

**Comment by Anzaru** [comment]
It was both in-game and on desktop but running it as admin seems to have fixed it for me. Thank you very much!
