### ISSUE TITLE
Can this work along side MFI Gamepad Feeder

### ISSUE THREAD

**Issue by DiegoAce** [Ryochan7/DS4Windows#473]
I haven't been able to get DS4Windows to report the PS4 controller as xinput and have MFI Gamepad Feeder report the mfi controller as xinput. I've tried changing the "Use Xinput Ports" option but no luck. Is it possible to have both work together? 
If I install DS4Windows first and then install MFI Gamepad Feeder afterwards the mfi controller works as xinput but the PS4 controller is only reported as directinput.

**Comment by Ryochan7** [comment]
I don't think I have heard of MFI Gamepad Feeder before. Both that and DS4Windows use ScpVBus so running both at the same time would cause problems initially. Changing the "Use Xinput Ports" option should allow both to work at the same time though. Just make sure that the 4 port range is different. If MFI Gamepad Feeder uses ports 1-4 then DS4Windows needs to be mapped to use ports 5-8; using something like ports 2-5 would not work. Windows will see the virtual Xbox 360 controllers in the order they are detected so the port range only matters to ScpVBus.

Just to mention it, the setting does not take affect until that control loses focus. DS4Windows should close and re-open the connection to ScpVBus once you switch to a different tab.

Another thing that you need to make sure of is that only one Scp Virtual Bus Driver device is detected in the Windows Device Manager (listed under System devices).
