### ISSUE TITLE
Prompting Controller/Driver Setup every single time the application starts

### ISSUE THREAD

**Issue by Turbozpeed99** [Ryochan7/DS4Windows#475]
This happens on my desktop (running windows ver1809), but not my laptop (windows ver1803). Why is this happening? I checked all the settings, updated both, but this only keeps happening on my desktop computer.

**Comment by mika-n** [comment]
Please see https://github.com/Jays2Kings/DS4Windows/issues/254 post. 

Maybe the driver setup fails to download SCPVirtualBusDriver and therefore fails to install it. If this is the case then installer keeps promptin you to re-try the SCPVBus installation.

Ryochan7 has replied in the above linked thread and provided an alternative URL to download the driver via a web browser. Try the link Ryochan7 mentions and install the vbus driver before running DS4Windows (you only have to install SCVBus driver once, not everytime when running DS4Win tool).
https://github.com/Jays2Kings/DS4Windows/issues/254#issuecomment-340226306

**Comment by Ryochan7** [comment]
The first thing to do is to make sure that the proper gamepad emulation driver is installed on your system. You should check the Windows Device Manager to ensure that the driver is installed and enabled. For normal DS4Windows, the necessary driver device is Scp Virtual Bus Driver. For the ViGEm build, the necessary device is Virtual Gamepad Emulation Bus. Both of those devices would be listed under "System devices".

**Comment by Turbozpeed99** [comment]
Thank you! Uninstalling and reinstalling the SCP driver worked. I actually had 2 of them installed (I used other software in the past for my ps3 controller), so I assumed that's what was causing the problem.
