### ISSUE TITLE
Controls change when DS4 loses connection and reconnects in FIFA 19

### ISSUE THREAD

**Issue by egz12** [Ryochan7/DS4Windows#476]
This is happening all the time. When bluetooth lost connection with gamepad, i pushing ds button to connect again and its connecting but controls are changing to like;

R1 = X
R2 = O

and normal buttons changing to like standart arrow keys. Please help about it urgently.

**Comment by Ryochan7** [comment]
That sounds very bizarre. I would think that maybe DS4Windows could not obtain exclusive access to the DS4 in this case but that does not explain that kind of mapping configuration. Even Steam should not cause something like that to happen if the controller mapper is running. Are you using auto profiles? Is some other profile getting loaded when you reconnect the controller?

**Comment by egz12** [comment]
> That sounds very bizarre. I would think that maybe DS4Windows could not obtain exclusive access to the DS4 in this case but that does not explain that kind of mapping configuration. Even Steam should not cause something like that to happen if the controller mapper is running. Are you using auto profiles? Is some other profile getting loaded when you reconnect the controller?

I am always using default profile and nothing changes. When bt disconnected and i pressing again the button after connected it just happening like that ALWAYS. Even in fifa 19 menus. Please do something cause when its happens i cant playing with controller and cant go to windows because fifa 19 cant allow that. I'm using your app for a year and it was perfectly fit before in fifa 18 but now its making me mad

**Comment by egz12** [comment]
i need help urgently about that brotha!

**Comment by Ryochan7** [comment]
Luckily there is a demo for FIFA 19 so I can try this out. I am downloading the demo right now so it might be a while before it finishes and I can test it. My aging PC (circa late 2012) just barely edges out over the minimum system requirements though.

**Comment by egz12** [comment]
Thank you for your interest brotha.

**Comment by Ryochan7** [comment]
Testing on my end show that DS4Windows cannot obtain exclusive access to the DS4 while FIFA 19 is running. FIFA 19 supports both XInput and DirectInput so the game uses the DirectInput controller once the controller is reconnected. It looks like the only way to allow a controller to disconnect and reconnect while FIFA 19 is running is to utilize HidGuardian.

I'm not sure about the arrow key problem. Maybe it is related to a bug with DS4Windows and KB+M action resetting that recently got fixed.

**Comment by egz12** [comment]
KB+M whats that exactly?

**Comment by egz12** [comment]
When we can get an update for this?

**Comment by Ryochan7** [comment]
The 1.5.15 update was pushed out early Nov. 7th. Also, KB+M means keyboard and mouse.
