### ISSUE TITLE
ds4 controller doesnt even charge/get detected/ nothing on windows 8.1

### ISSUE THREAD

**Issue by dipisgood** [Ryochan7/DS4Windows#483]
i have windows 8.1.

ds4 windows does not work at all. start/stopping with disconnecting controller does not do anything, restarting does not do anything.
device manager shows no hid compliant game controller and with hidden devices shown...itll pop up but no options there as far as disable/enable.
.NET framework way up to date.

just bought the ds4 4 days ago. steam doesnt even recognise it. no lights, when ps button pressed i get 6 blue slow flashes and nothing.

when plugged into any of my SEVEN usb ports, still nothing, 3.0 or 2.0. even with a different cable in each of the ports. what in the fucking shit is going the fuck on godamnit?

**Comment by Ryochan7** [comment]
Sounds like you are having issues beyond DS4Windows. If Windows cannot detect the controller then DS4Windows and other software will not be able to use it. Maybe you should perform a hard reset of the DS4 controller itself and see if that resolves the issue. Never had to perform a hard reset myself.

http://askabouttech.com/reset-ps4-controller/

**Comment by dipisgood** [comment]
thank you for replying.

apparently all of my usb charge cords were under par compared to my phone usb charger for my samsung s7. once i used the charge cord for my phone in my usb port it worked flawlessly. immediate recognition of controller.

**Comment by Ryochan7** [comment]
I usually use cables from Monoprice.
