### ISSUE TITLE
[Informational] DS4Windows as-is on Wine (linux)

### ISSUE THREAD

**Issue by epigramx** [Ryochan7/DS4Windows#484]
This isn't exactly an issue or a request because it's not that pressing to me, just letting you know DS4Windows appears to load fully on linux after Microsoft's .NET 4.6.1 is installed (with winetricks) (on a 32bit wine prefix at least), however, the software does not detect the HID of the actual hardware.

We've done some work on wine in the recent past that made Wiimotehook fully load the HID of a Wii Remote (via bluetooth) on a .NET 4.5.2 binary that enumerated HIDs though wine wasn't exactly stable yet at that method so I don't know if it's only some minor debugging needed.

PS. I know this could be ported to a .NET core app and make all that easier but I wasn't looking into that.

**Comment by Ryochan7** [comment]
Between the hid-sony driver and the ds4drv and SC Controller projects, I would assume that support for the DS4 would be covered on Linux. I don't see a real need to look into making DS4Windows attempt to work better in Wine.

I had looked into splitting DS4Library from the program before and some assemblies being used in that package are not available in .NET Core.

As a small tangent, I don't use the DS4 on Linux. My Steam Controller has been my main controller to use when gaming on Linux thanks to the SC Controller project.
