### ISSUE TITLE
windows 10 bluetooth driver error

### ISSUE THREAD

**Issue by radishhh** [Ryochan7/DS4Windows#486]
my dualshock 4 works fine when using a micro-usb cable, but it doesnt work at all when trying to connect through bluetooth. after connecting to it through windows settings (im using windows 10), it pairs successfully and then shuts off a second later. ive tried reinstalling the dualshock 4 drivers, the scp drivers, reinstalling ds4windows, and i havent had any luck. before this, the controller would show up on ds4windows, but it still wouldnt stay connected.

**Comment by Ryusennin** [comment]
Have you paired it manually with 0000?

**Comment by Ryochan7** [comment]
You should first just attempt to get the DS4 detected by Windows and see if it can maintain a connection. DS4Windows will not help at all if the controller is not working in Windows. Pairing with 0000 might be necessary but I cannot remember the last time I had to enter a pin to make the controller pair with my computer.

**Comment by jiliangsoft** [comment]
Have a tips:
  Using force pairing on ds4, and try to connect it. Usually windows will install the driver. at this time,if ds4's light off(meaning exit force pairing), get in pairing again immediately.Generally, restart one time is enough for windows to install driver.
  if continue to fail, DO NOT USE win10 ui settings to add the controller,use legacy control pannel 'device and printer' to add device.
