### ISSUE TITLE
ds4windows and need for speed 2015

### ISSUE THREAD

**Issue by picarito** [Ryochan7/DS4Windows#488]
i dont know if this issue has been resolved or is there a fix but in need for speed 2015, when uising it with ds4windows, the car always has  the handbrake on and does burnouts and cant drive the car.read many slolutions online but none of them work besides moving the throttle sensitivity midhigh which breaks the r2 and l2 buttons so they act like a pressed button rather than pressure sensitive ones

**Comment by Ryochan7** [comment]
That really sounds like a problem with the game and XInput controllers using DirectInput mode. Microsoft decided to have the two triggers of an Xbox 360 controller get mapped to one axis for the DirectInput interface and that can cause problems with some games.

**Comment by mrdc** [comment]
I have Xbox One controller additionally to Dualshock 4 and see that in Win10 when I connect it via Wireless Dongle LT&RT are mapped to one axis, the same Xbox controller in Win7x64 shows separate axis for LT&RT :/

**Comment by Ryochan7** [comment]
I am not sure if different version of XInput adjust the mapping for the Xbox One controller. It does not matter for the Xbox 360 controller though. All versions of XInput map both triggers of an Xbox 360 controller to one axis when using the DirectInput interface.

At this rate, I would suggest that you just not use DS4Windows and rely on the DS4 DirectInput controller exposed to Windows while playing that game if it is possible.
