### ISSUE TITLE
[Question] RMB + Mouse Right/Left

### ISSUE THREAD

**Issue by MuteButtonHero** [Ryochan7/DS4Windows#492]
I've used DS4W on several games and constructed some great profiles but I can't figure out how to do this.

What I want is when I move my left stick to the right it will Mouse Right while depressing the Right Mouse Button. When I move the stick left I want Mouse Left + RMB. I'm not seeing how to combine the analog action of mousing with holding down the RMB. 

I don't know if I just have not considered some capability of DS4W or if this is a bridge too far.

**Comment by mika-n** [comment]
I think this kind of logic is not possible out-of-the-box in DS4Windows. Probably even macros won't work in this scenario because "left/right movement" is not supposed to be macro recorded step.

**Comment by Ryochan7** [comment]
There is no way to set up that kind of mapping in DS4Windows. The main mapping routine mainly accounts for one output per input. Making a macro wouldn't really help accomplish this either.

**Comment by MuteButtonHero** [comment]
Ok, Thanks for letting me know. I suspected that was true but I wanted to see if someone had a clever way to make it work.  I'm trying to use it for SWTOR and their key mapping is unlike anything else I've seen.

**Comment by MuteButtonHero** [comment]
BTW, I did find a solution to this but with a catch. I started using a program called PadStarr from the guy who wrote Pinnacle. It's functionality and user interface concept is awesome. Problem is, the author passed away and the code is not open source. So his parents keep paying the bill to keep the website online and it provides a small income for them (it costs $7). A friend of his operates the forum and when you get on to complain about not getting your software key, he gives you one. Obviously the minor bugs it has never get fixed. It still works but if a Windows update ever breaks it, that's it.

This is a project crying out for a developer who knows this stuff to take it over. Who knows, maybe his parents could be persuaded to let it go open source, or if they are only willing to sell a GoFundMe campaign could be started to buy them out. So if you or anyone reading this are interested, you might check it out.

**Comment by Ryochan7** [comment]
Although I have a license for PGP and PadStarr, I preferred to use Xpadder. PGP and PadStarr had some decent mapping functionality but mouse cursor control was pretty bad no matter what settings I used. There is likely no chance that either piece of software would ever be open sourced.

Even though I wouldn't want to use the same mapping model again, antimicro was able to pull off that type of mapping functionality.
