### ISSUE TITLE
UDP server stops working after a few minutes of playing

### ISSUE THREAD

**Issue by reecespieces** [Ryochan7/DS4Windows#494]
This occurs both in the current latest version (1.5.16) and also in 1.5.15. On Windows 7.

As soon as I load a game it works fine, but after a few minutes of game-play while using motion controls, motion controls completely stop responding. 

___
Latest version with a usable UDP server for me is still 1.5.8. - Everything after 1.5.8 but before 1.5.15 crashes when using Cemu at all (#454)

**Comment by Ryochan7** [comment]
That would be before any type of object reuse was put into affect.

**Comment by Ryochan7** [comment]
This issue might be resolved. PadTest and CemuHook now work over a sustained period again. The main issue seemed to be old invalid buffer arrays being used and exceptions being thrown. Reports were still being generated by DS4Windows.
