### ISSUE TITLE
FIFA 19 INGAME problem

### ISSUE THREAD

**Issue by egz12** [Ryochan7/DS4Windows#497]
Hey Ryo

We were talked about this and it was okay with BT connection only on ingame not in menu but everything was fine. 

But now, its not connecting well again. Last year it wasnt even a problem, it was connecting very healthy and buttons were working. But this year its just going off and after on its not working again. Please do something about this, i just losing my game cause this and i cant make alt+tab ingame because its not allowed in fifa ultimate team. 

Thanks.

**Comment by egz12** [comment]
when i connect it again its always pressing bottom side or upper side. you was fixed it in last patch but its happening again.

**Comment by SamHH** [comment]
Not experiencing this myself.
