### ISSUE TITLE
Hori PS4 Mini causes "Index was outside the bounds of the array" error

### ISSUE THREAD

**Issue by ddekany** [Ryochan7/DS4Windows#498]
Hori PS4 Mini Wired Gamepad, Windows 7 64 bit, DS4Windows 1.5.16

Out of the box (see workaround later), DS4Window fails with the error below while the controller is connected, hence it's not detected:

```
11/23/2018 12:09:49 AM: DS4Windows version 1.5.16
11/23/2018 12:09:49 AM: LinkedProfiles.xml can't be found.
11/23/2018 12:09:49 AM: Starting...
11/23/2018 12:09:49 AM: Connection to Scp Virtual Bus established
11/23/2018 12:09:49 AM: Searching for controllers...
11/23/2018 12:09:49 AM: Using Shared Mode
11/23/2018 12:09:49 AM: Index was outside the bounds of the array.
```

The VID/PID matches the "Hori PS4 Mini Wired Gamepad" in DS4Devices.cs:

```
HID-compliant game controller
  Hardware Ids:
    HID\VID_0F0D&PID_00EE&REV_0100&Col01
    HID\VID_0F0D&PID_00EE&Col01
    HID_DEVICE_SYSTEM_GAME
    HID_DEVICE_UP:0001_U:0005
    HID_DEVICE
```

The problem is caused by this other device (also only appears when the game controller is plugged in), which I had to disable in the Device Manager:

```
HID-compliant device
  Hardware Ids:
    HID\VID_0F0D&PID_00EE&REV_0100&Col02
    HID\VID_0F0D&PID_00EE&Col02
    HID_DEVICE_UP:FFF0_U:0040
    HID_DEVICE
```
After disabling it, DS4Window detected the game controller and subsequently Windows detected it as X360 Controller, and so far it seems everything is working. Of course, the problem is that people have to figure this out.

Let me know if you need help in testing or such!

**Comment by Ryochan7** [comment]
I don't own that hardware so it would be up to the community to figure it out. I am guessing that one interface does not fit the normal DS4 spec so reading the first input report would fail.

It looks like that extra identifier will need to be checked as well. Thank you for figuring this problem out. I will get to this a little later.

**Comment by Ryochan7** [comment]
Col does not seem like a reliable way to distinguish the two interfaces apart. That is generated by Windows when discovered and it seems like it can only be pulled from the device instance path rather than pulling it as an attribute. Can you post the results from HID Report Listener for those two detected devices?

https://inputmapper.com/downloads/download/5-tools/75-hid-report-listener

Looking at the Hardware IDs presented, it might be best to check the Usage attribute for HidDeviceCapabilities in order to isolate the proper device.

**Comment by ddekany** [comment]
For the problematic device `Usage` is `64`, while for the game controller it's `5`. I have attached the two json-s as well (had to rename to txt to be attachable here):
[0x0F0D-0x00EE_HID-game-controller.txt](https://github.com/Ryochan7/DS4Windows/files/2612581/0x0F0D-0x00EE_HID-game-controller.txt)
[0x0F0D-0x00EE_HID-problematic-device.txt](https://github.com/Ryochan7/DS4Windows/files/2612582/0x0F0D-0x00EE_HID-problematic-device.txt)

BTW, I don't know how this thing works, but it's strange that the program dies with such a low level exception. Can't it instead report that it ran into that error when accessing this-and-that device? Would be more helpful for users when it happens in the future with other devices. (Or even, maybe pop up something where the device can be marked to be ignored, especially if there are more devices with the same VID/PID.)

**Comment by Ryochan7** [comment]
It seems like it would be safe to assume that Usage would be equal to 5 for all DS4 controllers. I have a version 1 controller, a version 2 controller, and the Sony Wireless Adapter and they all have the same usage value. Unfortunately, just adding a simple check causes the app to slow down. The check does work though.

**Comment by ddekany** [comment]
I don't know... I know nothing about Windows' device management API-s, but it's so weird that this logic has to be hard wired into the code. There could be a setting under the Settings tab to exclude devices by VID and/or SID and/or Usage. If there's no filtering set by Usage, there's no slowdown. If some device causes "Index was outside the bounds of the array" the application could recommend adding it to this exclusion filter. (Also maybe there should be a setting to force the usage of a device with a certain SID+VID+Usage. So if a new device comes out, users has chance to solve the issue themselves.)

**Comment by mika-n** [comment]
The problematic device seems to have zero length Input and OutputByteLength, so the "other" registered HID device is a bit weird.

**Comment by Ryochan7** [comment]
The main issue is that, based on my experience, .NET is just screwy sometimes. I ended up trying the same change on a couple of trimmed down projects (Windows Forms and WPF) and I got the same results. I tried a bunch of tweaks with mixed results. The last change made seemed to behave consistently so it has been included.

**Comment by ddekany** [comment]
Sorry, tried what on trimmed down projects?

**Comment by Ryochan7** [comment]
Basically this (used in DS4Windows/HidLibrary/HidDevices.cs):

```
if (tempDev.Attributes.VendorId == tempInfo.vid &&
    tempDev.Attributes.ProductId == tempInfo.pid &&
    tempDev.Capabilities.Usage == 0x05)
{
   found = true;
   foundDevs.Add(tempDev);
}
```

The important part is the last clause of the if statement. The differences between this and the final version are that the usage check is placed first and an unused assembly was removed. Minor differences in code.

The other projects were just template projects from Visual Studio with the DS4Library and HidLibrary packages added in along with a minor test class to tie everything together. It was enough to test basic XInput emulation.

**Comment by Ryochan7** [comment]
This issue should be fixed in version 1.5.17.

**Comment by ddekany** [comment]
It worked, now that device need not be disabled. Thanks!

**Comment by Ryochan7** [comment]
That's good. I don't know why some third party DS4 controllers expose different interfaces. Hopefully this change will make supporting other third party DS4 controllers easier.
