### ISSUE TITLE
Question: any way to get battery info?

### ISSUE THREAD

**Issue by emko** [Ryochan7/DS4Windows#499]
i am coding something using node and i am wondering if there is a way to read the battery level from the controllers from DS4windows? sorry for dumb questions would it be possible with https://github.com/node-ffi/node-ffi ?

thanks

**Comment by Ryochan7** [comment]
Doing it using node would be tough. There is a .NET class library that people could use for a project targeting the .NET framework. The only options outside of that would be to implement an HID device reader yourself or read information from the UDP server. The UDP server has almost no documentation. The battery status reported from the UDP server only reports a general level as opposed to a percentage.

https://github.com/Ryochan7/DS4Windows/wiki/UDP-Server-Output-Packet-Information

**Comment by emko** [comment]
thanks a lot, i will use the UDP connection for now

**Comment by emko** [comment]
i assume i have to send a request and then i will receive the data back? in what format do i need to send it in? sorry for so many noob questions

`        enum MessageType
        {
            DSUC_VersionReq = 0x100000,
            DSUS_VersionRsp = 0x100000,
            DSUC_ListPorts = 0x100001,
            DSUS_PortInfo = 0x100001,
            DSUC_PadDataReq = 0x100002,
            DSUS_PadDataRsp = 0x100002,
        };`

**Comment by emko** [comment]
okay i managed to get the data by using wireshark to see what is sent to get a response and now i just send the same seems to work :)
