### ISSUE TITLE
Game Profile Mode Launches Program Multiple times

### ISSUE THREAD

**Issue by shinra358** [Ryochan7/DS4Windows#50]
If you have a program in the launch program with profile section and you are using game profile mode (when process on top is read and if it is the process on top matches, the controller config is used), it keeps launching the program.

For example, if I have the controller to launch bigbox and bigbox comes up, then I load citra because I have a citra controller profile, ds4windows will launch bigbox again making it appear on top of the game.

Will probably need the same check to not launch a program twice for game profile mode as well.

**Comment by shinra358** [comment]
How come you labeled this as an enhancement?

**Comment by Ryochan7** [comment]
It was mainly due to not having messed with that portion of the code myself.

**Comment by shinra358** [comment]
fixed
