### ISSUE TITLE
UDP Server still can't start with 1.5.17

### ISSUE THREAD

**Issue by mooms06** [Ryochan7/DS4Windows#503]
Hi, just updated to 1.5.17 and restarted my computer, I still have to start and stop DS4Windows a few times to make the UDP server working:

> 29/11/2018 08:55:57: DS4Windows version 1.5.17
29/11/2018 08:55:57: LinkedProfiles.xml can't be found.
29/11/2018 08:55:59: Starting...
29/11/2018 08:55:59: Connection to Scp Virtual Bus established
29/11/2018 08:55:59: Searching for controllers...
29/11/2018 08:55:59: Using Exclusive Mode
29/11/2018 08:55:59: UDP server listening on port 26760
29/11/2018 08:55:59: Couldn't start UDP server on port 26760, outside applications won't be able to access pad data (AddressAlreadyInUse)
29/11/2018 09:18:12: Stopping X360 Controllers
29/11/2018 09:18:12: Closing connection to Scp Virtual Bus
29/11/2018 09:18:12: Stopping DS4 Controllers
29/11/2018 09:18:12: Stopped DS4Windows
29/11/2018 09:18:12: Closed UDP server
29/11/2018 09:18:14: Starting...
29/11/2018 09:18:14: Connection to Scp Virtual Bus established
29/11/2018 09:18:14: Searching for controllers...
29/11/2018 09:18:14: Using Exclusive Mode
29/11/2018 09:18:14: UDP server listening on port 26760
29/11/2018 09:18:14: Couldn't start UDP server on port 26760, outside applications won't be able to access pad data (AddressAlreadyInUse)
29/11/2018 09:18:19: Stopping X360 Controllers
29/11/2018 09:18:19: Closing connection to Scp Virtual Bus
29/11/2018 09:18:19: Stopping DS4 Controllers
29/11/2018 09:18:19: Stopped DS4Windows
29/11/2018 09:18:19: Closed UDP server
29/11/2018 09:18:32: Starting...
29/11/2018 09:18:32: Connection to Scp Virtual Bus established
29/11/2018 09:18:32: Searching for controllers...
29/11/2018 09:18:32: Using Exclusive Mode
29/11/2018 09:18:32: UDP server listening on port 26760
29/11/2018 09:18:32: UDP server listening on port 26760

**Comment by Ryochan7** [comment]
Why does it look like the UDP server is trying to launch twice? The last attempt especially seems to indicate that it might be happening.

**Comment by mooms06** [comment]
I don't know, the last entry is the one when it finally succeeded.

**Comment by Ryochan7** [comment]
Can you give this build a try?

http://ryochan7.xyz/ds4windows/test/DS4Windows_UdpChange_20181201.zip

**Comment by mooms06** [comment]
I tried it and restarted a couple times, logged out, logged in three times, it seems to works.

**Comment by reecespieces** [comment]
> 
> 
> Why does it look like the UDP server is trying to launch twice? The last attempt especially seems to indicate that it might be happening.

Every version after 1.5.8 displays the "UDP server listening on port 26760" message twice.


Although, for me 1.5.17 still works fine. I never had this particular issue.

**Comment by Ryochan7** [comment]
The socket instance used to open the port is initialized twice. It was an oversight from testing various changes. I never had any problems with the way it worked but it should not have been set up that way. Recent changes now make sure that the port is only opened once.

**Comment by Ryochan7** [comment]
Depending on the system, it could cause the problem. It worked fast enough on my system to not cause a problem.
