### ISSUE TITLE
Keyboard emulation no longer works with DS4Windows

### ISSUE THREAD

**Issue by the-importer** [Ryochan7/DS4Windows#505]
Hi there,

So after re-installing Windows from scratch, going from 1803 to 1809, keyboard emulation stopped working in DS4Windows when loading a game. I'll describe the issue and changes I did with bullet points for easy reading:

- I did a full format of my SDD and installed Windows 10 build 1809 from my USB Key that I did using Microsoft's official tool for making bootable USB Keys

- I've changed my video card from an old GTX 750 TI to a GTX 1080 prior to the format, but this was the first time that this card was in a clean and formatted Windows 10

- I was using Jays2Kings's version when this problem started happening, the issue is the same with Ryochan7's version

- DS4Windows's Xinput emulation does work, games do think that I'm using a 360 or XBONE controller

- Keyboard emulation works in basic programs like NOTEPAD

- I tried 3 games so far, none of them work with Keyboard emulation in either Window, Borderless or Full Screen

- I tried both  wired and wireless, same issue both way

- "Hide DS4 Controller" is checked in DS4Windows

- I installed 1809 at work using the "Windows on top of Windows" method, works perfectly, no issue with Keyboard emulation (yes, I play games at work during lunch time)
- I did not install any new software besides a newer version of Filezilla, SQL 2014 Express (was using 2012 prior to the format), VLC and a couple of DVDFab programs 
- I've uninstalled the DVDFab programs well as VLC since I didn't need them anyway, no changes to the issue
- The games use to be installed on my main SSD (C drive 240GB) and have been copied prior to the formatting to my new 2TB SSD which acts as my E drive solely for my games. None of my games are technically "installed" in this installation of Windows, they are simply there on the E drive and they do launch
- I tried using the "scan code" boxes in my keyboard mapping, didn't change anything
- I personally don't think this has anything to do with DS4Windows since with Logitech SetPoint program, keyboard and shortcut emulation also doesn't work now. I use Ctrl, Backspace and the Start Menu as shortcuts on my mouse and these use to work in games (Start Menu use to bring me back to my desktop when I needed to go to a website or something without closing everything)

So ya, this is all of the info that I have, any help would be appreciated.

**Comment by the-importer** [comment]
OK, I'm gonna close this now. I tried the old Xpadder and found that I had the same issue, so I googled for that instead of DS4. Back in my previous Windows installation, I disabled I fully disabled the UAC via the registry, something I didn't do this time, so this meant that Xpadder, DS4Windows and SetPoint weren't running in admin mode.

Anyway, fuck MS and their damn UAC and off-topic, Ryochan7, your version of DS4Windows has issues with Exclusive mode. Even if I close all of my programs, I get the Exclusive mode problem, so I reverted to Jays2Kings's version.

**Comment by Ryochan7** [comment]
I always run DS4Windows as the administrator to help avoid UAC problems like that. I tried enforcing it in the program recently but that broke the Run at Startup routine.

The only sure way to avoid problems like this would be to add support for the vmulti driver in DS4Windows in the future. That would add another driver that users would have to install. Also, I think the key codes used for that driver might be different from what SendInput uses. I would have to look at old sample code to find out. I don't see that happening though.
