### ISSUE TITLE
Root Element Is Missing

### ISSUE THREAD

**Issue by tetrakm** [Ryochan7/DS4Windows#508]
Hi everytime i try to edit the Default setting on DS4 I get an error stating that my root element is missing.
2018-12-05 14:01:57: DS4Windows version 1.5.17
2018-12-05 14:01:57: LinkedProfiles.xml can't be found.
2018-12-05 14:01:57: Starting...
2018-12-05 14:01:57: Connection to Scp Virtual Bus established
2018-12-05 14:01:57: Searching for controllers...
2018-12-05 14:01:57: Using Exclusive Mode
2018-12-05 14:01:57: Found Controller:1C:66:6D:46:EB:8D (USB)
2018-12-05 14:01:57: Root element is missing.

**Comment by Ryochan7** [comment]
It looks like a profile that is reference or the Default profile do not exist.

**Comment by mika-n** [comment]
When DS4Win was started for the first time, it asks where (programData or appData folder) you want to store profile and other configuration files. Maybe there was a permission problem to access the selected folder location? Usually appData folder has less permission problems that programData folder.

**Comment by tetrakm** [comment]
> When DS4Win was started for the first time, it asks where (programData or appData folder) you want to store profile and other configuration files. Maybe there was a permission problem to access the selected folder location? Usually appData folder has less permission problems that programData folder.

Changing to the AppData folder worked thanks

**Comment by Ryochan7** [comment]
Most locations should work fine for the Program Folder option. The big exception of course is using any folder under C:\Program Files. I typically have DS4Windows stored in a sub-folder in Downloads. The AppData option is technically the better approach to use but people like to keep settings contained in one folder.
