### ISSUE TITLE
Mapping Square and Triangle through Button Press Bug

### ISSUE THREAD

**Issue by shinra358** [Ryochan7/DS4Windows#51]
If you open a profile and press the square or triangle controller button to map them, they will share which ever key you choose instead of having separate keys. Works fine if you use the mouse to select the buttons instead.

**Comment by Ryochan7** [comment]
Thanks for mentioning this problem. I don't use that functionality so that would have stayed broken. Also, Dpad Right was did not work at all. The problem has been fixed.

**Comment by shinra358** [comment]
Excellent. Thank you for your superb skills ;)
