### ISSUE TITLE
API/Interface to change light bar color programmatically

### ISSUE THREAD

**Issue by bdr99** [Ryochan7/DS4Windows#516]
I would like to have the color of the light bar change in response to some event within the game I am playing. For example, when I am running low on health in a game, the light bar would turn red. Does DS4Windows provide any kind of API or interface that can be used to set the color of the light bar from another program? Even the ability to bind a keystroke to change the color would be sufficient. I am aware of the UDP server, but it doesn't seem to have this capability.

Thanks!

**Comment by mika-n** [comment]
At the moment there is no API for external apps to change the lightbar color. There is ability to change a profile, for example, when touchpad is swiped. You could have different profiles with identical mapping but different lightbar color settings.  But this is not really a programmatical API 3rd party app could use, but a manual thing to do.

**Comment by bdr99** [comment]
Thanks for the replies! In that case, consider this a feature request. I think it would be a nice feature to have. Perhaps it could be part of the UDP server.

**Comment by Ryochan7** [comment]
The UdpServer is probably not going to get changed at this point so this type of feature would not get implemented within that class. I have had a good amount of work improving DS4Windows in general and luckily I have had some releases that have had good results.

**Comment by bdr99** [comment]
I didn't mean to imply that it had to be part of the UDP server. Any method of externally controlling the light bar color would be nice to have.
