### ISSUE TITLE
Blue Screen Error bugcode_usb_driver 

### ISSUE THREAD

**Issue by Vavictus** [Ryochan7/DS4Windows#517]
Hello, the past 2 days I've had this blue screen error occur occur about 5-6 times while playing some games, although it's happened most while playing Dark Souls 3.  

The error is: bugcode_usb_driver if that is typed correctly.

I'm not sure if this is a issue with DS4 since it's really the only other USB peripheral i'm using at any time.  Any help or guidance would be appreciated!

**Comment by mika-n** [comment]
Sounds like a problem in WinOS level or in virtual X360 device driver level. In both cases DS4Win application itself shouldn't be able to cause such a BSOD error because it is "user mode" application.

Are you using ScpVBus x360 virtual driver? Maybe trying another version of that driver.

**Comment by Ryochan7** [comment]
That might be a hardware issue. The only software component that might cause a BSOD would be ScpVBus but I am not sure if it would produce a bugcode_usb_driver error.
