### ISSUE TITLE
can this be used with the steam drivers

### ISSUE THREAD

**Issue by mahoneyd** [Ryochan7/DS4Windows#521]
is there a way to just have udp running and use the steam drivers? That what I can have udp always running, and open my games through the steam interface

**Comment by mika-n** [comment]
How about if you try to enable option "Use DInput only" and don't use "Hide DS4 Controller" option?

**Comment by mahoneyd** [comment]
I was wondering if there is just maybe just udp part that could link to the
ds4 steam drivers. I have it working using ds4 and have steam using just
the Xbox 360 controller, but I don't have access to the ps button or the
mouse pad that way.  I'm wondering if it would be easy to just point the
steam drivers to a stand alone udp. They do it for the steam controller so
it must be possible. Thanks for any info you can provide. Thanks!

**Comment by Ryochan7** [comment]
Steam reads the Steam Controller directly and performs virtual gamepad injection for games similar to how x360ce works.

It might be possible to get the two to cooperate somewhat but I would advise against trying to do it though. There are many cases where the two tools will conflict and getting Steam to work with the controller while both are running takes loading in a specific order. Steam has to get access to the controller first and then DS4Windows can be launched using Shared Mode and with no virtual gamepad present (Use DInput Only). If a virtual gamepad is ever present then Steam BPM will not work correctly until the DS4 is disconnected and reconnected.

It would just be better to use one tool or the other as needed. In my case, I have no use for PlayStation Configuration Support in Steam so I have the option disabled.
