### ISSUE TITLE
Add support for SCUF Vantage

### ISSUE THREAD

**Issue by UnreaI** [Ryochan7/DS4Windows#524]
Current version doesn't recognize the new SCUF Vantage controller, can you please add support for it? Thank you!

**Comment by Ryochan7** [comment]
I do not have the controller so I have no means to support it. The best I can do is add the VID and PID to the controller list, share a test build and then you could check if it works and report the result. I searched and I could not find a site that has the VID+PID combination of the controller listed. Can you check the HID-compliant vendor-defined device entry in Device Manager for the Scuf Vantage and post the report VID and PID for the controller?

**Comment by Ryochan7** [comment]
Thank you. That gave me the information that I wanted. Here is a test build that you can try.

http://ryochan7.xyz/ds4windows/test/DS4Windows_Test_x64_20181226.zip

**Comment by UnreaI** [comment]
It works! Thank you so much 😄  ❤️
