### ISSUE TITLE
HELP - Using DS4W with x360ce (or other Dinput > Xinput translator)

### ISSUE THREAD

**Issue by vpontin** [Ryochan7/DS4Windows#525]
Hi! A very late Happy Christmas for everyone!

Well, i'm currently using DS4Windows (vigem) to connect my two Dualshock 4 via Bluetooth.

But i also have two generic controllers, and i want to use a DirectInput to Xinput translator to resolve both in Xinput controllers too.

Is possible? The first software which came in my mind is x360ce, but i'm afraid both programs doesn't work well. If so there are options?

Note: i dont use Steam so its translator isnt an option for me right now.

**Comment by tremendoza** [comment]
x360ce can do custom configs so you can manually map your generic controller buttons to XInput ones if it doesn't do it properly for you.

**Comment by Ryochan7** [comment]
It is not possible with DS4Windows directly. It would require extra work but I believe that you could make x360ce work alongside DS4Windows. You could use passthrough mode in x360ce for the virtual XInput controllers made by DS4Windows and then use x360ce to map the other DirectInput controllers as needed. I am not sure if the order that devices are plugged in would cause issues though.

I think I remember doing something similar with an older XInput emulation setup before I started using DS4Windows.
