### ISSUE TITLE
Cannot get any program to recognize my ds4 controller.....

### ISSUE THREAD

**Issue by brothan323** [Ryochan7/DS4Windows#532]
This program nor input mapper will recognize my ds4 controller. I have NO idea how to fix this. What's weird is that I've been using this program and my controller for a year and a half and then it just STOPPED working. Uninstalling everything doesn't work.

**Comment by mika-n** [comment]
Bluetooth or USB connection? if you use BT connection then does it work via usb connection?

Do you see the controller in WinOS ControlPanel devices lists? If not then there is not much DS4Win application can do about it if WinOS doesn't see the device in the first place.

Are you using HidGuardian? Try without it.

**Comment by Ryusennin** [comment]
Your bug report is useless.

Please mention the very basics: your OS, your DS4W version, HidGuardian or not.

**Comment by tremendoza** [comment]
Plug in your controller, open Device Manager and expand  Sound and Video Game Controllers, Universal Serial Bus and Human Interface Devices and Look for any disabled devices and enable them. Also, run Command Prompt as Administrator and paste then execute the following:

reg delete HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\HidGuardian\Parameters\ /v AffectedDevices

then choose yes to delete the registry key. Unplug and reconnect your controller and you should be good to go 😀..
