### ISSUE TITLE
Special Actions

### ISSUE THREAD

**Issue by tremendoza** [Ryochan7/DS4Windows#534]
Are special actions supposed to override regular mappings? It would be nice if they did... Question, if I map L2 as the Shift Key in special actions and L2+R2 as Alt+Enter as well, is pressing L2+R2 supposed to maintain the Shift Key press or release it until the Alt+Enter is finished triggering?

Edit: After testing I found that Special Actions don't cancel each other out either. They should I think and maybe fall back to any previous one(s) that was active; like falling back to Shift after the Alt+Enter trigger in the initial post above.

**Comment by mika-n** [comment]
you can unmap regular mapping if you don't want it to conflict with a special action mapping.
