### ISSUE TITLE
Xinput controller number

### ISSUE THREAD

**Issue by freddyarcade** [Ryochan7/DS4Windows#538]
I've got 4 DS4 controllers that I'm using through DS4Windows with exclusive mode (ie hide controllers is checked)

I have the profiles setup and "linked" to a specific controller ID.

That's all good.

Here's question:

Is there any way to control which xinput number is assigned to which controller ID?

if not, do they tend to be persistent?

I'm going to be using these in mame and 'm trying to figure out how to identify each controller

freddy

**Comment by Ryochan7** [comment]
The XInput slot number used is assigned in the order which devices are detected. Slot numbers cannot be assigned manually and they are not persistent. That behavior is due to how the XInput API works.

**Comment by freddyarcade** [comment]
I'm using the DS4 controllers via wired USB to an arcade dedicated PC running windows 10 pro.

will the Xinput slot numbers tend to stay constant as long as no USB devices are unplugged ?
ie will they survive reboots ?

Mine seem constant so far, but I haven't had it set up for very long.

I'm using Mame and I think the Xinput slot numbers are how you identify the controller.  Does that
sound right?

Thanks again for the help

Freddy

**Comment by Ryochan7** [comment]
It is dependent on how the devices are exposed by Windows. I want to think that device enumeration would be fairly consistent between reboots as long as the same controllers are plugged in to the system.

**Comment by freddyarcade** [comment]
Thanks.  Helps a lot.

Is the controller ID that  DS4Windows displays specific to the physical controller and is it persistent?  I’m hoping that it is something that DS4windows reads directly from the controller....ie like a serial number.

I so,then Since my Controllers are USB-wired into USB jacks that I don’t plan to ever change....that controller serial number would be enough for me to know which Player the controller is for.

So, what I’m thinking is that if I could get the controller ID and the Xinput slot # in a table in a text file, then I could parse that text file and automatically rewrite my mame config file on every reboot.  If I was able to do that, then I would be protected in cases where the XInput slot numbers changed on a reboot.

Does this make sense?

If, so is there a way to find out which controller ID is mapped to which xinput slot #. ?
Either via an output file from DS4Windows or some other way?

Thanks again for the help
And DS4Windows is really a great tool 👍

Freddy
