### ISSUE TITLE
Clarification on where to put the 1.63 updater exe

### ISSUE THREAD

**Issue by PoliteTimesplitter** [Ryochan7/DS4Windows#539]
Since the latest update, when I've tried to update ds4windows it's given me a prompt to download a new updater, 'place it in the programs folder, and check for update again'

I've downloaded it to the DS4Windows folder, so DS4Updater_64.exe is in the same folder as DS4Updater.exe and DS4Windows.exe. However, when I check for update again and agree to download 1.63, the same happens - I get the prompt, the browser window to grab the download, and when I check again, it's just the same. No actual update to 1.62. Am I misinterpreting what 'programs folder' is?

**Comment by stealsfromhobos** [comment]
I managed to make it update by putting the new installer where you said, but also deleting the "_x64" at the end of the filename.

**Comment by Ryochan7** [comment]
DS4Windows does expect the file to be named DS4Updater.exe with no arch suffix. The archives on GitHub are mainly meant for DS4Windows to download the latest version when new versions of the updater are released. Outside of that, using the updater exe bundled with the DS4Windows archive files would be the main download method.

It looks like this problem occurs if using the AppData option in DS4Windows. I use the Program Folder option and it works fine in that situation even with the DS4Windows installation folder under Program Files. I didn't just want a DS4Updater.exe under the releases section to minimize confusion but that breaks updating functionality in this situation.

Also, under normal circumstances, if DS4Updater.exe cannot be found and a new version of DS4Windows has been detected, DS4Windows will download the latest updater file before attempting to download the latest version of DS4Windows.

**Comment by Ryochan7** [comment]
This problem has been addressed. The old standard is now being used again with an added note being displayed for the people using the x86 build.
