### ISSUE TITLE
[Multi-Action Button] Touch pad buttons

### ISSUE THREAD

**Issue by pralima87** [Ryochan7/DS4Windows#54]
The Multi-Action Button options do not work for the Touch-Pad Buttons.
Tested with all 4 buttons: Upper/Right/Left/Multi.

**Comment by Ryochan7** [comment]
Only the current state was being preserved for touchpad actions so there was no way to make multi-action buttons work for touchpad buttons. I hacked at the code to make a fix but it isn't exactly good. It does work now though.

https://github.com/Ryochan7/DS4Windows/commit/ce0ac4f04a87568fa9f0ebf579c7a16dd746c8b4

**Comment by pralima87** [comment]
Yep fixed in Version 1.4.75+
