### ISSUE TITLE
Dualshock working only with bluetooth

### ISSUE THREAD

**Issue by matax22** [Ryochan7/DS4Windows#541]
So i can connect only the ds4 with bluetooth (it charges if i wire it, but keep the connection as bluetooth) , if i tried getting a wired connection windows doesnt even recognize my ds, only via bluetooth. Is there a fix for this? i guess the problem is driver related

**Comment by mika-n** [comment]
Try different USB cables. I have several old mobile phone USB cables which don't seem to work with DS4 controller.

**Comment by matax22** [comment]
> Try different USB cables. I have several old mobile phone USB cables which don't seem to work with DS4 controller.

This is it, tried like 4 cables till i got one working, thanks!
