### ISSUE TITLE
DS4Windows 1.6.3 will not open

### ISSUE THREAD

**Issue by zapoqx** [Ryochan7/DS4Windows#543]
So when I tried updating DS4Windows today, I noticed that it was the 2nd time trying to update to 1.6.3.  So I decided to manually update.  I noticed everytime to overwrite the "Microsoft.Win32.TaskScheduler.dll" it was taking a long while.  Anytime launching DS4Windows, in the Task Manager, it seems it would launch, but would immediately go into suspend status.  Since oddly enough, I wasn't getting an error of any sort, I decided to reopen 1.6.2 and throw that back onto the system.  It worked in launching, so I checked event viewer.  This is all I could find on the application:

.NET Runtime:

> Application: DS4Windows.exe
> Framework Version: v4.0.30319
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.Management.ManagementException
>    at System.Management.ThreadDispatch.Start()
>    at System.Management.ManagementScope.Initialize()
>    at System.Management.ManagementEventWatcher.Initialize()
>    at System.Management.ManagementEventWatcher.Start()
>    at DS4Windows.DS4Form..ctor(System.String[])
>    at DS4Windows.Program.Main(System.String[])

Application Error:

> Faulting application name: DS4Windows.exe, version: 1.6.3.0, time stamp: 0x5c308497
> Faulting module name: KERNELBASE.dll, version: 10.0.17763.134, time stamp: 0x1659a33b
> Exception code: 0xe0434352
> Fault offset: 0x0000000000055299
> Faulting process id: 0x2b8c
> Faulting application start time: 0x01d4a7729e078d43
> Faulting application path: C:\Users\(username)\Desktop\Organize\DS4Windows\DS4Windows.exe
> Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
> Report Id: f4f8db88-471c-45bb-8165-d0d41ce76a38
> Faulting package full name: 
> Faulting package-relative application ID: 

Should note I'm using x64 version.

So whats going on here?

**Comment by Ryochan7** [comment]
Something is going wrong with connecting to the Windows Management Instrumentation service. Is the service running? Also, you might want to check that the service has not run into any problems. It looks like you can check that by going to `Control Panel > System and Security > Administrative Tools > Computer Management`, expand Services and Applications in the left bar, right click on WMI Control and select Properties. The textbox in the General tab should show the current status of the service.

**Comment by zapoqx** [comment]
Oh.  Thats interesting.

> Failed to connect to `<local computer>`
> because "WMI: Critical error
> "

Guess I need to fix that.
