### ISSUE TITLE
Does DS4W still not support CSR adapters?

### ISSUE THREAD

**Issue by vpontin** [Ryochan7/DS4Windows#544]
Hi!

Searching in original repo and docs (from Jays) it says DS4W cannot connect with Dualshocks using Bluetooth USB adapters with CSR technology. Is this still true?

If yes, can someone direct me to a USB adapter which work with DS4W? Thanks!

**Comment by jonaaa20** [comment]
No.

I have one of these CSR adapters and they work fine.

**Comment by Ryochan7** [comment]
My primary BT dongle uses a CSR chipset and it works fine.

**Comment by vpontin** [comment]
Great to hear that! Will buy one soon. Thanks for the answers!
