### ISSUE TITLE
DS4 windows broke my ds4 on 2 out 3 usb ports

### ISSUE THREAD

**Issue by Hentlover** [Ryochan7/DS4Windows#545]
So, after using DS4 windows, two out of my 3 usb ports no longer recognize my DS4. They recognize any other device I'd connect, so it's not just a general USB issue. When I plug it in, it will flash orange and WILL NOT be detected in any other way. It's not in any lists of devices on my PC (I am using W10), and neither DS4 nor Input Mapper I used to test it out recognize that there are any controllers plugged in period. 

Last USB port works fine with both DS4W and Input mapper recognize it with one small issue. PC stll doesn't, unless I launch Input Mapper once. After detecting it with Input mapper, I can turn IM off and PC will still recognize it. This is good because there are apps that recognize DS4 natively and I don't need 3rd party tools for those. But it is still worrying, since I am now down to one LAST port that still recognizes the controller, and even then, with hoops, andit was using DS4Windows that caused issues and I have no trust in it not eventually killing the last one, leaving me unable to use my DS4 on PC period. 

For context, I cannot check and repair drivers or anything like that, because as stated, there is no device to inspect and trouble shoot. PC does even realize someting is plugged in when using 2 of no longer working USB... problem that doesn't carry over to any other device I'd plug into them.

**Comment by Hentlover** [comment]
I am terribly sorry, but as soon as I made ths post I was finally able to fix the issue. I suddenly was able to find the entry for device in the manager, see the error, (it was driver error) delete and reinitialize the device and it now works as it used too. I tried before but had no luck, but this time it worked.

**Comment by 1oglop1** [comment]
Glad you have it resolved! Now you can close the issue :)
