### ISSUE TITLE
[Sony Dongle] Can not pair DS4 Controller

### ISSUE THREAD

**Issue by Karpadre** [Ryochan7/DS4Windows#549]
Hi there and thx for your attention :) I just can not seem to get my DS4 Controller to work over Bluetooth with the supposedly best device for it - the official Sony Wireless Adapter since my computer doesnt have bluetooth natively. USB works fine. When im trying to pair the device, the lights start flashing correctly but when im looking in "Bluetooth and other Devices" 
Wireless Controller never pops up. (if relevant - im only able to search by using the bottom option when clicking add Bluetooth Device). Incidentally somehow my sound and mic switched to "wireless controller" 2 times but i cant seem to reproduce this

**Comment by Ryochan7** [comment]
I can't find the box for my dongle but the directions mention that the process is different than a normal BT dongle. The process is handled entirely by the dongle itself and Windows will see the dongle as a wired controller.

In order to sync a controller to the dongle.

1. Plug the dongle into a USB port. Push in the dongle until the light start blinking
2. Hold PS and Share buttons on the DS4 until the LED on the controller starts blinking
3. Wait for the lights on both the dongle and the DS4 to turn solid

The lights on both the controller and the dongle should be solid if the syncing process is successful. You can then check the controller in Devices and Printers (DUALSHOCK 4 USB Wireless Adapter) and make sure that Windows can read events from the controller.

**Comment by Ryochan7** [comment]
To address the other part of the post

> Incidentally somehow my sound and mic switched to "wireless controller" 2 times but i cant seem to reproduce this

The dongle exposes a sound device to Windows. The sound device will allow the headphone jack on the DS4 to work in Windows as an audio output device and microphone. You have to set your normal audio output device as the default output in Windows or Windows will switch to the new audio device when it is detected.

**Comment by Karpadre** [comment]
additional info: Steam doesnt detect any controller either and the only bluetooth device listed related is still the Dualshock 4 USB Wireless Adaptor under Audio. If the damage is too deep im planning on having a clean windows install next week or so

**Comment by Ryochan7** [comment]
HidGuardian is not necessary for basic support. It is meant to allow applications to more easily get exclusive access to specified devices. I don't know which guide you are referring to. When I test HidGuardian, I either set it up manually or use my old test installer to install HidGuardian and write the AffectedDevices list.

If the audio device is seen by Windows but not the controller device then HidGuardian is probably hiding it; you can check for an "HID-compliant game controller" device in the Device Manager to check if the device exists at all as that list is not affected by HidGuardian.

If you are using the devcon.exe method to uninstall HidGuardian, you have to make sure that the classfilter entry is removed from Windows as well as the associated HidGuardian device. HidGuardian will still work even without the device being exposed if the .sys file is still installed in the driver store. Removing the class filter is the step that keeps the HidGuardian driver from being used.

**Comment by Karpadre** [comment]
I finally got it working! Thanks for all your outstanding help. The guide i meant is to be found on this github page if you click on the wiki tab and then under pages on the right. All i did now was to remove some registry entry added by "HIDGuardian Helper Files" which did nothing (maybe relevant who is to say). Then i noticed that the last app installed was "inputmapper hidguardian". I completly forgot that i really installed something. Simply uninstalling that one did the trick. Thanks again

**Comment by Karpadre** [comment]
Not sure if it makes sense to open another issue for this one because i seem to have a minor one.. Everything works like a charm now except the left d-pad button. I almost thought my controller must be broken but everything is fine with cable. Could you throw me a hint once more?

**Comment by Karpadre** [comment]
Alright you can close this one :D i tested everything with XInputTest.exe and it almost worked right out of the box. I totally forgot to check the controller profile in ds4windows itself, where actually 3 dpad buttons were unassigned but 2 of those still worked in XInputTest.exe. Weird. After assigning the 3, everything works fine. Thanks again for everything
