### ISSUE TITLE
Tray icon battery level is not updated

### ISSUE THREAD

**Issue by araujorm** [Ryochan7/DS4Windows#55]
Hello.

First of all, congratulations and thank you for maintaining this wonderful piece of software.

To the point: I have been noticing that the battery level sometimes isn't updated, but today I realized that it seems to only happen on the tray icon, inclusively when the DS4 is disconnected you get as you can see on the attached screenshot.

Steps to reproduce to me were just connect the DS4 via bluetooth (don't know if it matters or not), wait a bit, ensure the DS4Windows main window minimized to tray (having the option to do it when closing), then disconnect the DS4 (keys I use are the default, ps button + options). When you double click the tray icon, you get what you see in the screenshot:

![tray_not_updated](https://cloud.githubusercontent.com/assets/13053489/26765698/501066b0-4979-11e7-8b8c-6d407dde0623.png)

Should you need any more data or details please feel free to ask.

**Comment by araujorm** [comment]
Hello again.

After a gaming session I could confirm that it really seems to be only a tray icon updating issue as it doesn't affect the battery gauge on main window. Attaching another screenshot to show what I'm saying.

![capture](https://cloud.githubusercontent.com/assets/13053489/26766367/5b321f16-4988-11e7-88ad-926084fb0938.PNG)

Best regards.

**Comment by Ryochan7** [comment]
Thanks for bringing this up. There was only one case when the tray icon text was being updated. Some other callbacks have been changed to re-generate the tray icon text as needed.
