### ISSUE TITLE
Win7x64 DS4 not working since 1.6.3 release

### ISSUE THREAD

**Issue by wz256** [Ryochan7/DS4Windows#550]
As in topic... Been not using DS4Windows for a while and since i came back with V1.6.6 the noice Tool suddenly stopped working - App will crash upon start. Going back to my old ver (1.5.14) fixed the issue. So i gradually narrowed down to the cause and it seems that all versions since 1.6.3 do not work for me any more; so i am on 1.6.2 now.
The changelog of 1.6.3 reads:
-Removed use of Microsoft.Win32 namespace
-Changed suspend detection routine to use WMI
I suppose some of those changes affects my ancient Windows 7x64 install? My Dot Net is on latest Version w security updates...

**Comment by Ryochan7** [comment]
This looks like another issue that has come from depending on the Windows Management Instrumentation service. Older versions of DS4Windows depended on it to detect the presence of the ScpVBus driver but its use only got re-introduced with version 1.6.3 to detect power state changes.

I have double checked and the Windows Management Instrumentation service is a standard part of a Windows 7 installation and it is run at startup by default. Either the service has been disabled on your system or something has gone wrong that you will need to look into. I will re-post what I had mentioned in issue #543.

> Something is going wrong with connecting to the Windows Management Instrumentation service. Is the service running? Also, you might want to check that the service has not run into any problems. It looks like you can check that by going to Control Panel > System and Security > Administrative Tools > Computer Management, expand Services and Applications in the left bar, right click on WMI Control and select Properties. The textbox in the General tab should show the current status of the service.

**Comment by wz256** [comment]
Thank you very much for looking into this! The service is up and running for me, set to "Automatic" on system startup (German: "Windows-Verwaltungsinstrumentation"). So seems it must be something else? Anyways, i am ok with 1.6.2 for now. :)

**Comment by Ryusennin** [comment]
I'm also on Win7-64 and I'm currently using version 1.6.7 without any issue.

**Comment by Ryochan7** [comment]
Did you check the Computer Management tool and make sure that the Windows Management Instrumentation service is working fine? The current version of DS4Windows runs fine on my Windows 7 installation. Either way, I will probably have to add a try catch block around the Start call. Utilizing try catch seems to greatly affect performance in .NET so I use that functionality sparingly.

**Comment by wz256** [comment]
Not sure i get what i should check but i fiddled with the services a bit now, yet everything seems to be in order. Anyways, i m onto a fresh install within the next days and will then check if and when the point might occur at which DS4 > 1.6.2 breaks for me.
