### ISSUE TITLE
Features Request

### ISSUE THREAD

**Issue by tremendoza** [Ryochan7/DS4Windows#551]
Left and Right Scrolling support as well as a simple Touchpad Click that ignores touch region. Please and Thanks 🤩 Appreciate the excellent work here as always.

**Comment by mika-n** [comment]
"Touchpad click which ignores touch region" = Why not assigning the same output mapping to all touchpad click regions (left/right/up)? The end result would be the same.

**Comment by tremendoza** [comment]
That would make sense for everything except profile switching which is what I want it for. Simple load and unload with any region touchpad click. Setting a load and unload for every touch region would mess things up.

**Comment by Ryochan7** [comment]
I would prefer setting a mode that allows changing how many touch buttons are exposed. Specifying 1 exposed or 3 exposed buttons could be useful.

I have checked and shift modifiers are not utilized for touchpad buttons despite being able to map one for an exposed button.

**Comment by tremendoza** [comment]
> I would prefer setting a mode that allows changing how many touch buttons are exposed. Specifying 1 exposed or 3 exposed buttons could be useful.
> 
> I have checked and shift modifiers are not utilized for touchpad buttons despite being able to map one for an exposed button.

This too would work. Any chance this could be in the next build 😀

**Comment by Ryochan7** [comment]
Another old request I am going to have to close. Not going to happen
