### ISSUE TITLE
reduce touchpad Y-axis range

### ISSUE THREAD

**Issue by eadmaster** [Ryochan7/DS4Windows#553]
is it possible to reduce the touchpad Y-axis range?

I am feeling uncomfortable reaching the upper part of the touchpad extending on the side of the controller...

**Comment by Ryochan7** [comment]
It is not possible currently. Although, I don't really see the need for it. It would only make sense if you map an exposed touchpad button to a controller axis. I am not sure that type of mapping would be practical.

If you are thinking that it would help with activating the upper touch button easier, it won't matter. The logic behind that button is that the upper touch button is considered activated if a touchpad click is detected but no touchpad touch event is detected.

**Comment by eadmaster** [comment]
Actually i am not using the touchpad for activating virtual buttons, i am using it with [cemuhook](https://cemuhook.sshnuke.net/padudpserver.html) to simulate a touchscreen.

I'd like to reduce the Y and X axis ranges like this so i can easily  reach the borders with my right thumb:
