### ISSUE TITLE
Random USB Ports Freezes

### ISSUE THREAD

**Issue by NightmareVortex** [Ryochan7/DS4Windows#555]
Hello! First of all thank you very much for your continuing support and updates of this awesome software!
I'm having a very weird problem, DS4Windows has been freezing up some of my USB ports randomly and I dunno how to fix it. At first I thought maybe it was USB drivers or a Windows update but nope, I unplugged everything, updated all drivers, BIOS, etc. Everything works fine so far until I plug my DS4 into my PC. I tried different ports too, it happens in all of them, sometimes everything is ok, some other times the controller, my keyboard and my mouse will freeze and everything will work again after I unplug and re-plug the controller, and some other times no matter what I do, even if I unplug the keyboard/controller/mouse and re-plug them, they won't turn on again until I hard-reset my PC. 

Any ideas? I'm going crazy trying to figure this one out. I normally can solve most issues searching on Google and checking the Event Viewer but this time I have no idea how to fix this.

I got a Ryzen 1700, 16GB's of RAM and a GTX970 so no, my PC is not a toaster, just in case. Running Windows 10.

**Comment by Ryochan7** [comment]
It can be a couple of issues. Relying on the old ScpVBus driver could cause problems. I have experienced odd BSODs in the past but that has been rare.

Another possible issue is that some applications do not like the way that the DS4 is hidden if "Hide DS4 Controller" is enabled. With some apps, enumerating over devices will cause input to freeze for about 10 seconds and then resume normal operation. I experience that problem on Windows 7 while launching Broforce. It didn't use to behave like that in previous versions of the game and I have made sure to test with previously tested versions of DS4Windows.

**Comment by catscarlet** [comment]
I'm having a similar issue.

Windows 7 64bit, Hide DS4 Controller" is enabled.

Today I try to play cuphead(for the first time), and suddenly my computer freezed, about 1 mins. I didn't continue the game.

After that, I update DS4Windows from 1.6.12 to 1.7.2, and test on Chrome and Firefox, with [HTML5 Gamepad Tester](https://html5gamepad.com/). Every time I open the tester page, my computer freezed badly.

I even test in a Virtual Machine (using Vmware workstation), and tested  DS4Windows 1.5.9, 1.6.12 and 1.7.2. All of them have this issue.

Is there any way to prevent this?

(I also use ds4drv on linux and doesn't have this issue yet, also I know it's very different on how OS handles drivers between Win and Linux)
