### ISSUE TITLE
[Bug] multi-action button dont work properly

### ISSUE THREAD

**Issue by jinkazama82it** [Ryochan7/DS4Windows#556]
Today I tried to setup a multi-action button, but of 3 option only one work as intended and this is the hold trigger, instead other 2 option don't work properly... more precisely the option "tap trigger" execute the action when you double tap the button and the option "double tap trigger" simply doesn't work.

I use the 1.6.7 version

**Comment by Ryochan7** [comment]
I will check this again but I believe I have tested the multi-action button recently.

**Comment by Ryusennin** [comment]
I use single tap to take screenshots with the Share button (PS4 style) via the built-in screenshot capture of the Radeon driver, so it definitely works. And I just tested successfully the double tap trigger to record videos.

**Comment by Ryochan7** [comment]
I just got around to testing this again. Most of the time all 3 actions works fine. It does look like the state can go out of sync so that a double tap only ends up executing the tap trigger. Tap trigger and hold trigger work fairly consistently for me.

**Comment by Ryusennin** [comment]
I forgot to mention I mainly use DS4W through wired USB connection, though I'm not sure if it makes a difference.

**Comment by jinkazama82it** [comment]
it make a big difference, wired the ds4 have 4ms of delay wireless 8ms of delay, probably the problem is here, or probably simply the nVidia software suffer of lag and don't grab the input. of tap and/or double tap but haven't problem with hold trigger.

**Comment by Ryochan7** [comment]
There was a discrepancy between interval checks and that seemed to be causing issues. I corrected the interval used to initiate double tap and I cannot reproduce the original problem anymore.
