### ISSUE TITLE
[1.6.8] Shift Modifier is Wonky AF

### ISSUE THREAD

**Issue by nocturnums** [Ryochan7/DS4Windows#561]
Unreliable shift function in this version.
e.g. I used R1 as the shifter, but the shifted button keeps reverting back to Return.

For the moment I revert back to use version 1.6.7 which still has the shift function working.

Please lmk if there are any details that you guys need to solve this issue

**Comment by Ryochan7** [comment]
I only have one profile in my installation that uses a shift modifier for volume control. I was able to use it yesterday just fine. As I will mention in an upcoming post, I literally cannot test this now because my gaming PC just decided to die. I am speculating that it is probably a blown power supply based on some observations.

**Comment by Ryochan7** [comment]
I have a temporary setup going so I can look into this. Can you share the profile that you are experiencing shift modifier problems with?

Also, I checked my Media profile and shift modifiers work in that profile. I have L1 set as a shift modifier for both DpadLeft and DpadRight for volume down and volume up respectively.

https://drive.google.com/open?id=1N-e-7I73gSYleuKogR1xFjoW3BZ6AO39

**Comment by nocturnums** [comment]
this is the profile I was working on

https://drive.google.com/open?id=17BwhxkpP_MBtbM5Ak9_kpIoCkvf-nV3h

**Comment by Ryochan7** [comment]
I can see the problem now. The Profile Editor shows wrong bindings for shift modifiers now. However, the correct binding is actually executed by the program when an action is executed.

**Comment by nocturnums** [comment]
glad that sorted out.
thanks for the prompt response!
