### ISSUE TITLE
[Notice] Drama Blog 2019

### ISSUE THREAD

**Issue by Ryochan7** [Ryochan7/DS4Windows#562]
My gaming PC decided to finally take a dive while getting close to the end of Shadow Warrior 2. I just heard a pop and then the PC shut down. Now none of the components receive power. The issue is likely a blown power supply. Without a Windows computer to work on, I will not be able to commit any more changes to DS4Windows for an unknown period of time.

**Comment by Ryochan7** [comment]
Update: Ended up confirming that it was the power supply that died. I am borrowing a weaker power supply with a non-operational fan and my system works with it connected; no other components appear to be having problems. Going to keep the power supply located outside the tower case and leave the side panel open for further testing. I don't know how much I would be able to do with it this way.

**Comment by Ryusennin** [comment]
Happened to me two years ago, except the power supply smelled like molten plastic. The lesson I learnt: don't settle for a dirt cheap no-name supply because that will usually be the weak link in your machine.

**Comment by Ryochan7** [comment]
My old power supply was a fairly decent OCZ 700 W supply. The one that I have hooked up now is a Cooler Master 500 W. The Cooler Master power supply was only replaced after the fan went dead causing the system to get unstable. The person used the problem as a reason to get a better power supply rather than attempting to replace the fan.

For the time being, I guess development is back on and this panic is temporarily over. It really seems like these types of problems are only going to get worse in 2019.

**Comment by Ryochan7** [comment]
My current setup. This is how things are now.

![sdc10937](https://user-images.githubusercontent.com/581968/53140672-160cb500-3553-11e9-8ee5-3c94eac2080b.JPG)

**Comment by Ryochan7** [comment]
Dislocated a knuckle for my right pinky. Right hand is out of commission for now so there will probably be no commits for a couple of days for sure.

**Comment by mika-n** [comment]
Based on how wild the setup looks like then I guess the right hand pinky probably accidentally got in a way of those spinning fan blades. Cats/Dogs/Babies/Fingers would love to take a closer look at those wires and fans.

**Comment by Ryochan7** [comment]
Only have one cat to worry about but she isn't very rambunctious. Rage just kicked in and I paid the price.

**Comment by Ryochan7** [comment]
Update. Went to a clinic today and I learned that I have an injury referred to as a boxer's knuckle. My right hand is bandaged up and I have a follow up appointment.

**Comment by teeedubb** [comment]
Hope its nothing serious mate!

**Comment by Ryochan7** [comment]
Got to go to an orthopedic clinic for the follow up and find out what the next step will be. I have a splint on my hand for now and it does help.

**Comment by Ryochan7** [comment]
I am going to need some pins put in my hand. The bone before my knuckle is out of alignment. That will be done Friday.

**Comment by mika-n** [comment]
Uuuh. Often we dont give a thought to something until it is broken. I remember when I had a small injury in a knee loop. Having half working knee really made many ordinary everyday things difficult to do even when it was such a small piece of something in a body.

**Comment by Ryochan7** [comment]
Update. Got my pins taken out today. The fracture is healed so now I can start working on recovering. I should be starting physical therapy soon; no appointment has been scheduled yet.

**Comment by teeedubb** [comment]
I was actually thinking about this the other day... Good to hear you 
recovery is progressing 👍

**Comment by Ryochan7** [comment]
Minor update. I am still stuck with typing one handed after a week. Fingers are loosening up a bit more each day though.

**Comment by teeedubb** [comment]
Good to hear it's getting better. Take care and follow any treatments - 
hands are very important!

**Comment by teeedubb** [comment]
How is your hand going?

**Comment by Ryochan7** [comment]
Recovery has been slow but it has been progressing. I am pretty much at 1.6 hands now. I am still typing one handed though. My ring finger and pinky are still fairly stiff from being in splints and a cast. I am getting some hand strength back but I still have to be careful with how much I attempt to do with my hand.

**Comment by Ryochan7** [comment]
Update. Physical therapy has been going well. I can at least grip a DS4 with both hands now although I cannot hold it comfortably for that long. I feel like I am around 75% recovered. The pinky is the main limiting factor and it is also limiting the motion of my ring finger a bit.

**Comment by teeedubb** [comment]
Hey Travis, Hows your hand coming along? Getting better?

**Comment by Ryochan7** [comment]
Things have improved a bit. I started being able to make a fist with my right hand a few days ago. My hand doesn't lock up as quickly now but it still happens if I don't stretch it throughout the day. My hand is pretty weak so I have been doing some grip exercises recently. I still can't play vidya with a DS4 and I am still typing one handed; attempting to type with the right hand is very awkward but I can use a mouse with that hand.

One distraction that is somewhat feasible now is that I can play guitar again with a bit of difficulty. My speed is still slower than before and I can lose grip of the pick too easily. Here is a recent playthrough of FantasMic by Nightwish for an example of my current level.

https://www.youtube.com/watch?v=hZ4t_z3ZPvM

**Comment by mika-n** [comment]
Good to hear your hand is getting better. And I could hear your guitar playing of Nightwish loud and clear! Damn you are good because even in half speed I would miss half the notes with two 100% working hands. So, I guess being two handed or one handed is a subjective matter whether it is a major problem or not.

And good thing you picked a song of Nightwish because I can drive over to see them and say that there is a fantastic "almost one handed" guitar player playing their song :-)   Tuomas, Tarja and Erno live few miles from our place (well, sort of live because they are nowadays always on the run and Tarja doing her solo projects in South America).

**Comment by Ryochan7** [comment]
Update. My hand therapy sessions are almost over; got one more appointment left. I am starting to get some extension back so I can do a bit more with my hand now. One big improvement is that I can play vidya again with some added difficulty. Typing is still a problem so I will continue typing one handed.

I have never posted any pics of my hand problem before. Here are some pics that I have taken over time to chart my healing progress.

https://imgur.com/U7oPw44 - After closed reduction surgery. Hand in splint before cast (3/4)
https://imgur.com/t6sobTu - After having pins taken out (4/4)
https://imgur.com/7US7fDL - Current condition (5/29)

**Comment by teeedubb** [comment]
Good to hear its improving.

**Comment by Nerdy314159265** [comment]
I noticed this thread and thought I'd chime in and ask how your hand is doing after another month.

Also after seeing that picture of your PC, I need to ask you to give it a good cleaning. That PC is being used for some really good work and I want to see it taken care of 😛 

Keep up the good work and if you still need a power supply, maybe you should throw up a small crowdfunding campaign for one and post it. Specific goals for funding would probably make donations more likely.

**Comment by Ryochan7** [comment]
Very little progress has been made lately. It is pretty bad when carrying a bag with two loaves of bread and a pack of English muffins can be considered a feat of strength. I am still typing with one hand as my fingers still lock up too often to attempt to type with my right hand for even a short duration. I only recently started getting some use out of my pinky finger again without worrying about damaging it.

I have been more focused on my current situation than any coding projects. My code contributions here have become fairly infrequent. Especially lately, I have not done any work to really warrant anything.

**Comment by Ryochan7** [comment]
I have had crowdfunding options available for a little while. I had not felt like advertising before as I would like to have some more definitive milestones to complete. Just having the money go towards "muh bills" or have 2K go towards a cat reveal is a completely one sided exchange. People can find me on LinkedIn and get a rough idea of my current situation though.

https://patreon.com/user?u=501036
https://subscribestar.com/ryochan7

As for the hand, I am still typing one handed. My hand strength and range of motion of my pinky finger have improved in the past month. It has now been 5 months since the initial operation so I don't know if the hand will ever be fully functional again.

**Comment by Ryochan7** [comment]
Had my last doctor appointment about the hand yesterday. Not much left to do but wait and see what happens. My current hand situation can be seen by the recent Mouse Joystick video that I put out there. Utility is still fairly minimal.

https://www.bitchute.com/video/6FSRiMUpA_M/

**Comment by Ryochan7** [comment]
Quick update on this personal issue. People who check my YouTube or Bitchute channel have probably seen some changes. My right hand has loosened up some and now I can fully bend my right pinky finger with no stretching required. As it could be seen in the latest video (Touchmote Round 4) towards the end, I still have a bit of a claw going on although it is not nearly as bad as it was.

I have finally started being able to type with my right hand again. The fingers need to loosen up more before I can do it regularly.

**Comment by Ryusennin** [comment]
Take it easy and enjoy some Xmas time.
