### ISSUE TITLE
Suggestion for nvidia ingame workaround

### ISSUE THREAD

**Issue by AnessZurba** [Ryochan7/DS4Windows#563]
Hi @Ryochan7 
Thanks so much for supporting this project
I actually discovered your fork a few days ago trying to figure out why "hide DS4 controller" option didn't work in the original project
Long story short, Nvidia ingame overlay prevents this option from working, so I was fiddling with autohotkey to find a solution to keep the ingame overlay but also enable the option
Today it worked, I'm currently using this

```
#g:: RunWait,sc stop "NvContainerLocalSystem",,hide
^#g:: RunWait,sc start "NvContainerLocalSystem",,hide
```
What this does is to stop the service NvContainerLocalSystem before connecting the controller "I have to press windows+g" then after it connects successfully I press windows+ctrl+g to restart the service

I was wondering if this can be added to the source code to be performed automatically if there is a problem with exclusive mode

Thanks again for supporting this project until now.

**Comment by mika-n** [comment]
How about starting DS4Windows app via a batch file which does this?

sc stop "xxx"
DS4Windows.exe
timeout /T /nobreak 10   (ie. wait for 10 secs to give ds4win enough time to connect to the controller)
sc start "xxx"

Anyway, maybe there could be a pre and post batch scripts in DS4Win which it calls when a new controller is detected and after the controller is initialized and HideDS4 thing has been done. This way it would be easy to add new pre/post actions without actually embedding that stuff in the app code.

**Comment by AnessZurba** [comment]
@mika-n  the first way isn't a good idea 
think that you would have DS4Windows always running in the background, then connect the controller and disconnect it when needed
as for the second way, actually that's what I'm thinking about, I figure it can be added as a part of pre connect and post connect routines.
