### ISSUE TITLE
Right analog stuck to Up direction in games.. 

### ISSUE THREAD

**Issue by Schnappi07** [Ryochan7/DS4Windows#565]
Basically after update today every game which use roght analog for camera it was making my camera stuck, like when you look above. Even in Fifa it was messing tricks and movement. Tested on 2 PCs. Reverting back to some old versions worked fine..

Installing last version on both PCs is making this issue present again.

**Comment by mika-n** [comment]
When you open the DS4Win options screen then what it shows as a polling frequency? Does it warn about slow polling frequency while reading the controller input? Logfile should also have complains if this happens.

Have you re-mapped RStick to do something else than the default behaviour? 
Is it really just UP position which is stuck or any direction?
Do you have an another DS4 Controller to test and verify whether this is controller specific issue or happens with any controller?

**Comment by Ryochan7** [comment]
I have tested default RS mapping and remapping LS to RS and it works as expected. Can you post the profile that you are using when you experience those problems?

**Comment by Schnappi07** [comment]
Just to add, sorry for replying after closing issue. Couldn't respond earlier. It seems that my controller broke, that "drift" issue with right analog happened so I need to buy new one. It's not issue with DS4Windows. Sorry :)
