### ISSUE TITLE
PS+Options disconnect only works in exclusive mode with SONYWA

### ISSUE THREAD

**Issue by madcrow** [Ryochan7/DS4Windows#566]
The PS+Options disconnect does not work when DS4 is connected via SONYWA dongle.
However it works fine when using generic BT dongles.

**Comment by Ryochan7** [comment]
That is a hardware problem. The dongle always presents a controller to Windows when it is plugged into a USB port. The PS+Options disconnect option does work when activated but it functions slightly differently than with a BT connected controller. The routine for the Sony Wireless Adapter unplugs the virtual XInput controller and resets the serial number displayed in DS4Windows.

**Comment by madcrow** [comment]
A side-note about the idle timer:
It might be a good idea to reset the timer when the user enables the option **OR changes the timeout**.
Now it can happen that the user decreases the previously set timeout, and as a result the DS4 dsiconnects/turns off **immediately**, because at that point the timer was already past the freshly set value.

**Comment by madcrow** [comment]
<Mapping.cs>
```
                            else if (action.typeID == SpecialAction.ActionTypeId.DisconnectBT)
                            {
                                actionFound = true;

                                DS4Device d = ctrl.DS4Controllers[device];
                                bool synced = tempBool = d.isSynced();
                                if (synced && !d.isCharging())
                                {
                                    ConnectionType deviceConn = d.getConnectionType();
                                    bool exclusive = tempBool = d.isExclusive();
                                    if (deviceConn == ConnectionType.BT)
                                    {
                                        d.DisconnectBT();
                                    }
                                    else if (deviceConn == ConnectionType.SONYWA && exclusive)
```
I've performed some tests. It seems that in my case the reason the DS4 is not disconnected is that excluseive == false.
Is this particular condition really necessary here? And if so, why just here? Disconnection via stop button, status icon right click, tray icon middle click, idle timer do not seem to consider the state of this flag.

Anyway, the weird thing in my case is that "excluseive" remains false even when I tick the "Hide DS4 checkbox" (which according to my understanding is supposed to enable exclusive mode).

**Comment by mika-n** [comment]
When you enable "Hide DS4 Controller" (ie. exclusive lock on the original DS4 HID device) then do you see any errors in logfile (Log tab page in DS4Win options screen)? If there are complains that exclusive access cannot be obtained then it would explain why exclusive variable remains FALSE.   

If this is the case then there are numerous other apps which might prevent the exclusive lock if those apps have opened a HID device handler to the original DS4 Controller before DS4Windows app. Steam if bigscreen controller support is enabled there, NVidiaExperience Overlay, etc....

Search this forum (Issues) for more info about those apps and how to workaround the exclusive lock problems.

**Comment by madcrow** [comment]
You are right, I totally missed that warning!

Yeah, I read about the apps interfering with exclusive mode.
Weird thing is: I've never had Steam or Uplay installed on this PC. And although I do have an NVidia card, I do not have Geforce Experience installed (I opted out of it during the driver installation). The only components present in my system are the NV graphics driver, NV physx driver and NV HD audio drivers.
And AFAIK, the Overlay is supposed to be a feature of the GeForce experience suite.

Do you know of any other SW which might cause a conflict?
But let's not hijack this issue. I copied this comment to the relevant location. We should continue there instead: #502

**Comment by madcrow** [comment]
OK.. back on topic:
Is there any valid reason the "disconnect on hotkey" feature should work only in exclusive mode?
(While all other modes of disconnection are able to operate both in normal and in exclusive mode?)

**Comment by Ryochan7** [comment]
That was a decision made a long time ago and I forgot about it. The Sony Wireless Adapter keeps replaying the last gamepad state after a controller is disconnected. When using the Disconnect BT special action, the Sony Wireless Adapter will continue to broadcast that the PS and Options buttons are held down. Especially having the PS button being seen as held down can cause problems with some application particularly Steam. Requiring exclusive mode means that at least other applications will not see a controller with the PS button being constantly held down.

There has been some talk about changing the behavior to actually perform the disconnect on an action trigger unload rather than performing the action on activation. I have not gotten around to tweaking that functionality but it should be possible. It might be better to wait until the controller goes completely idle before actually launching the disconnect action.

**Comment by madcrow** [comment]
I see. That makes sense.

> There has been some talk about changing the behavior to actually perform the disconnect on an action trigger unload rather than performing the action on activation. 

Good idea! I hope you can find the time to implement it later on.

**Comment by jinkazama82it** [comment]
but the ds4 controller have a native power off function, if you hold the ps button for a while the ds4 power off this work threat when connected via Bluetooth with our without the SONYWA, I'm not sure that this work when the ds4 is connected via USB but you can try.

**Comment by Ryochan7** [comment]
The same problem will exist when using either method. The PS button will be seen as constantly held down due to the Sony Wireless Adapter continuing to broadcast the last gamepad state.

**Comment by Ryochan7** [comment]
This problem was finally dealt with in version 2.0.10. Hooks were put in place to wait for the controller to go idle before attempting to perform the controller disconnect.
