### ISSUE TITLE
[Feature Request] Gyro to Mouse Joystick

### ISSUE THREAD

**Issue by AkrumQassem** [Ryochan7/DS4Windows#569]
Steam Input has a feature where you can assign your gyro to be either a Mouse or a Mouse Joystick
The difference is that Mouse Joystick is actually just the right analog (not an actual mouse) but it moves and feels like a mouse in-game

That option is for games that don't support inputs from controller + KB/M simultaneously (like Resident Evil 7 and 2)

It would be nice to have this in DS4Windows

**Comment by Ryochan7** [comment]
I have tried that option with the Steam Controller a few times and I never liked it. It has always felt wonky to me despite the settings used. I usually prefer mouse aiming anyway so I would opt to use full KB+M emulation for games that do not support simultaneous input. This would definitely be a low priority request. Some experimenting should probably be done to test whether such a feature would be helpful.

**Comment by AkrumQassem** [comment]
I know it won't be as good as the normal "gyro to mouse" but it's the only workaround I can think of, either that or joy2key and that's just .. no.

But yeah I understand why it's a low priority request, and thanks for considering it anyways :)

**Comment by Ryochan7** [comment]
I will experiment with this soon. Using GloSC has shown part of the reason I do not like Steam's implementation. It is way too sensitive even after removing the minimum axis values. Forcing the user to change the output stick sensitivity in game rather than giving some way to set a max zone for the gyro limits how useful that output type is.

**Comment by Ryochan7** [comment]
Also, with the current version of Steam, the mapper does not even map to the full Xbox 360 analog stick range. Left and Down directions are throttled and don't reach their true maximum values. For some games, even negating one unit of value can make a big difference in control. My go-to examples are Duke Nukem Forever and BioShock 1.

**Comment by Ryochan7** [comment]
Tried this out with my Steam Controller as well. The same problem exists when using that controller as well. I tested using the gyro and the right touchpad.

**Comment by Ryochan7** [comment]
Experiments so far have shown that the control type is playable. It seems to be working out better than the Steam version of Mouse-like Joystick. That assessment is based on playing Duke Nukem Forever using both implementations. The tricky part so far has been finding decent values to use for the dead zone, max zone, and anti-dead zones.

**Comment by Ryochan7** [comment]
It is still in the experimental stage. Here is the current code.

https://github.com/Ryochan7/DS4Windows/tree/gyromousestick

**Comment by Ryochan7** [comment]
Here is a small demo showing the output type in action. Since recording the video, I upped the anti-dead zone values slightly and that worked better. Might end up making the new values the default if those values work out better in other games as well..

https://www.youtube.com/watch?v=6FSRiMUpA_M

**Comment by Ryochan7** [comment]
Got some of the extra mapping options worked out and merged the feature into the main jay branch. The only default that might change at this point is the default max zone setting. I don't know when the next version of DS4Windows will come out so the feature will be available. Hopefully it will be no longer than a week.

**Comment by Ryochan7** [comment]
Version 1.7.16 is now out and it has Mouse-like Joystick support for the gyro. I ended up playing through Duke Nukem Forever again while testing settings. Gyro Mouse is still the better option but Gyro Mouse Joystick works surprisingly well. I even had aim assist disabled in game and aiming was still good while emulating an analog stick. Just like with Steam, you will likely want to tweak the stick sensitivity in game along with tweaking gyro settings in the profile.

https://github.com/Ryochan7/DS4Windows/releases/tag/v1.7.16
