### ISSUE TITLE
DS4 windows update

### ISSUE THREAD

**Issue by sbdreamz** [Ryochan7/DS4Windows#571]
My controller has stopped working after the update today. When I try to use it it shows that its connected and the controls on fortnite switch to show R1 etc but I can't move or do anything else.

**Comment by Ryochan7** [comment]
The mapping routine got messed up with the last release. A lot of customization of XInput controls will cause the output state for some controls to get reset. That change will have to be reverted and a new hotfix release will have to get published.

**Comment by Ryochan7** [comment]
Version 1.6.10 should take care of this problem.
