### ISSUE TITLE
Exclusive mode working on boot but not afterwards

### ISSUE THREAD

**Issue by RaydenX93** [Ryochan7/DS4Windows#573]
Hello,
The issue I'm having is likely not a bug in DS4Windows but I didn't know where else to ask. If I try to connect my DS4 via BT soon after my PC is booted up, exclusive mode works correctly. If I wait some time before connecting, I get the error that exclusive mode cannot be used because some other apps are using the controller. No launchers like Steam are open and no nVidia related software is running. I presume some service has started in the background in the meanwhile?

How can I pinpoint the app(s) that is/are causing the problem?

OS: Win 10 x64 1809
DS4Windows 1.6.10

Thanks for the help

**Comment by mika-n** [comment]
https://docs.microsoft.com/fi-fi/sysinternals/downloads/process-explorer
https://docs.microsoft.com/fi-fi/sysinternals/downloads/handle
http://www.imatest.com/2017/01/how-to-determine-what-processes-are-using-a-device/

Mayne SysInternals tools ProcessExplorer and Handle helps to track down which process is using a device. See the third link for more info about how to use those unofficial Microsoft debug tools.

**Comment by Ryochan7** [comment]
Cool. I didn't know there was any way to track down which process has an open handle to a device. I had looked before but I didn't find any information. That information will be really useful. With the Sony Wireless Adapter, there are times after booting Windows when exclusive mode refuses to work for no known reason. Exclusive mode will only work after the adapter is unplugged and plugged in again. It will be worth trying out when that happens again.

**Comment by Ryochan7** [comment]
I just ran across the problem that I described before. I ran Process Explorer and it looks like the process **WinStore.App.exe** has an open handle on my Sony Wireless Adapter for no good reason. Unplugging and plugging the adapter back into my computer makes exclusive mode work. Also, it looks like WinStore.App.exe keeps a handle to the old device open even after unplugging the adapter. Thanks Microsoft.

![process_explore_20190219](https://user-images.githubusercontent.com/581968/53046630-1a9f7380-3456-11e9-826f-c12e5c9ad293.png)

**Comment by mika-n** [comment]
WinStore holding a controller handles may be a result of letting the WindowsStore app to run in background and update apps automatically. If this is enabled (and it is enabled by default) then the app wakes up frequently to check apps. WinStore app supports gamepad navigation in the store catalog.

**Comment by Ryochan7** [comment]
I would expect WinStore to perform that way for XInput controllers but not for HID controllers. It is odd behavior. I ended up disabling that functionality for the Windows Store so I should not run into that kind of problem again. It is too bad that this issue would affect most people running Windows 10.

**Comment by bonethugsgoat** [comment]
I had and still have this problem but they closed the thread I made but apparently someone claimed I couldn't get past step one even though I clearly said I tried everything, oh well I guess I'm too stupid to get it then even though I'm not the only one with the problem, might as well close all the topics then...

**Comment by Ryochan7** [comment]
> ...but apparently someone claimed I couldn't get past step one...

> ...oh well I guess I'm too stupid to get it...

That someone was me the head developer of DS4Windows. Do what is asked next time instead of copping an attitude. Random whining does nobody any good. If you don't want to help diagnose a problem then you should not be posting on GitHub.

Mötley Crüe - Don’t Go Away Mad (Just Go Away) (Official Music Video): https://www.youtube.com/watch?v=QNCM8IjtQ-o

**Comment by IceLancerSR** [comment]
> 
> 
> I just ran across the problem that I described before. I ran Process Explorer and it looks like the process **WinStore.App.exe** has an open handle on my Sony Wireless Adapter for no good reason. Unplugging and plugging the adapter back into my computer makes exclusive mode work. Also, it looks like WinStore.App.exe keeps a handle to the old device open even after unplugging the adapter. Thanks Microsoft.
> 
> ![process_explore_20190219](https://user-images.githubusercontent.com/581968/53046630-1a9f7380-3456-11e9-826f-c12e5c9ad293.png)

Logging out of microsoft store if u arent really using it , might solve the problem. I never used store my self , so without being logged in it shouldnt be able to attach it self

**Comment by perkel666** [comment]
Hi it is pretty much every process that monitors what exe are open.

For me exclusive mode doesn't work when:

- Nvidia in-game overlay is working
- Game Time Tracker is open

So i have to close GTT and switch off in-game overlay in geforce experience for Exclusive mode to work.

**Comment by Ryochan7** [comment]
Never heard of GTT before. Looking at the screenshots, it looks like it does perform controller detection and even saves the number of button presses performed in game stats.

Somewhat luckily in my case, my graphics card is one generation too old to actually support the Nvidia in-game overlay; I don't have the GeForce Experience software running on my system besides. The only minor downside for me of my current card is the lack of Vulkan support.

**Comment by RaydenX93** [comment]
> 
> 
> https://docs.microsoft.com/fi-fi/sysinternals/downloads/process-explorer
> https://docs.microsoft.com/fi-fi/sysinternals/downloads/handle
> http://www.imatest.com/2017/01/how-to-determine-what-processes-are-using-a-device/
> 
> Maybe SysInternals tools ProcessExplorer and Handle helps to track down which process is using a device. See the third link for more info about how to use those unofficial Microsoft debug tools.

I tried your suggestion but could not pin point the app that was using the device. Following what has been said in this discussion, i manually tried to close some win 10 store apps that were running in the background and, apparently, the app that was causing problems for me was Netflix.

I guess we have to consider win 10 store apps as possible responsibles for future problems...

I have solved my problem. Should we keep this issue open for future reference or should we add this discovery to the README.md and close the issue?

**Comment by perkel666** [comment]
I mean it is still an issue.

But ways to deal with exclusive mode apps and specify which (like nvidia in-game overlay, GTT, Netflix etc) that need to be closed before you connect pad should be added to readme.

**Comment by mika-n** [comment]
ExclusiveMode is not perfect way to hide the original HID controller but with some apps it is required (some games crash or behave oddly if both the original and virtual x360 controllers output button presses). Alternative way to hide the original controller from any other apps but from DS4Windows is to use HIDGuardian tool. It goes down to device driver level, so GeForce/WinStore apps cannot steal the original controller. If you use HIDGuardian tool then exclusive mode is not required. Search this "forum" to see instructions how to use HIDGuardian with the current version of DS4Windows if exclustive mode doesn't work in your scenario. Please note that HIDGuardian and WhiteKnight are 3rd party tools so it has nothing to do with DS4Win app itself.

**Comment by Ryochan7** [comment]
WhiteKnight has not been needed since version 1.6.8. DS4Windows will check if HidGuardian is installed and then launch the HidGuardHelper.exe program to manage the whitelist entry. That makes the process of using HidGuardian a little easier.

HidGuardian is the most safe way of obtaining exclusive access to the controller.

**Comment by mburnes** [comment]
> I tried your suggestion but could not pin point the app that was using the device. Following what has been said in this discussion, i manually tried to close some win 10 store apps that were running in the background and, apparently, the app that was causing problems for me was Netflix.

That was it for me too.

**Comment by RaydenX93** [comment]
@Ryochan7 What about creating a wiki page with all the known problematic programs and win 10 apps?

**Comment by mburnes** [comment]
That sounds like a good idea to me. Probably could add functionality. Auto-detecting any running problematic programs and prompting the user to close them (or having the ability to automatically close them) would be a nice quality of life improvement. 

Closing Netflix with commands is kind of tricky, as its being handled by WWAHost.exe.

**Comment by mika-n** [comment]
> @Ryochan7 What about creating a wiki page with all the known problematic programs and win 10 apps?

https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-tips-and-issues

This is a community maintained project, so feel free to update the Wiki page with tips and links to applciations known to cause problems with exclusive mode.

**Comment by Blackbird88** [comment]
Thanks so much for that wiki page! I couldn't ever get exclusive mode to work at all and now it works consistently (so far)
