### ISSUE TITLE
Output curve doesn't work?

### ISSUE THREAD

**Issue by tjr1** [Ryochan7/DS4Windows#574]
No matter the option I select (linear, quadratic, cubic), nothing changes in the controller readings.  Sensitivity does seem to work as a positive control.

**Comment by Ryochan7** [comment]
The controller readings tab works with the raw state object rather than the one that is changed during mapping. Some options like sensitivity and curve (input) are duplicated in the method that renders the panels. That is one portion of the form that I have avoided touching. I will test changing to using the mapped state object later and see if things will work out.

As an alternative, I would suggest that you check out HTML5 Gamepad Tester and see how the output changes after editing a profile.

https://html5gamepad.com/

**Comment by tjr1** [comment]
Thanks for your reply.  I've tried using html5gamepad.com.  Now I'm finding that no changes have an effect.  For instance changing the sensitivity of LS to 0.5 doesn't not change the max value on html5gamepad.com.  Maybe something else is wrong.  I'm sorry.

**Comment by Ryochan7** [comment]
I checked this against version 1.6.10 and sensitivity options work fine for me. Can you share the profile that you are using? I should probably mention that sensitivity changes happen after any dead zone, max zone, and anti-dead zone calculations are taken into account.

**Comment by tjr1** [comment]
I'm quite thankful for your help.  I coppied it here from the xml file.  You can see that the <Sensitivity>0.5|1|1|1|1|1</Sensitivity> is set.  \

Probably unrelated: I'm using the ds4 wired and I'm running windows server 2019. 

Thanks,
tj1


<?xml version="1.0" encoding="utf-8"?>


<DS4Windows>
  <flushHIDQueue>False</flushHIDQueue>
  <touchToggle>True</touchToggle>
  <idleDisconnectTimeout>300</idleDisconnectTimeout>
  <Color>255,255,255</Color>
  <RumbleBoost>100</RumbleBoost>
  <ledAsBatteryIndicator>False</ledAsBatteryIndicator>
  <FlashType>0</FlashType>
  <flashBatteryAt>0</flashBatteryAt>
  <touchSensitivity>100</touchSensitivity>
  <LowColor>255,0,0</LowColor>
  <ChargingColor>255,255,255</ChargingColor>
  <FlashColor>240,240,240</FlashColor>
  <touchpadJitterCompensation>True</touchpadJitterCompensation>
  <lowerRCOn>False</lowerRCOn>
  <tapSensitivity>0</tapSensitivity>
  <doubleTap>False</doubleTap>
  <scrollSensitivity>0</scrollSensitivity>
  <LeftTriggerMiddle>0</LeftTriggerMiddle>
  <RightTriggerMiddle>0</RightTriggerMiddle>
  <TouchpadInvert>0</TouchpadInvert>
  <L2AntiDeadZone>0</L2AntiDeadZone>
  <R2AntiDeadZone>0</R2AntiDeadZone>
  <L2MaxZone>100</L2MaxZone>
  <R2MaxZone>100</R2MaxZone>
  <ButtonMouseSensitivity>25</ButtonMouseSensitivity>
  <Rainbow>0</Rainbow>
  <LSDeadZone>0</LSDeadZone>
  <RSDeadZone>0</RSDeadZone>
  <LSAntiDeadZone>0</LSAntiDeadZone>
  <RSAntiDeadZone>0</RSAntiDeadZone>
  <LSMaxZone>100</LSMaxZone>
  <RSMaxZone>100</RSMaxZone>
  <LSRotation>0</LSRotation>
  <RSRotation>0</RSRotation>
  <SXDeadZone>0.02</SXDeadZone>
  <SZDeadZone>0.02</SZDeadZone>
  <SXMaxZone>100</SXMaxZone>
  <SZMaxZone>100</SZMaxZone>
  <SXAntiDeadZone>0</SXAntiDeadZone>
  <SZAntiDeadZone>0</SZAntiDeadZone>
  <Sensitivity>0.5|1|1|1|1|1</Sensitivity>
  <ChargingType>0</ChargingType>
  <MouseAcceleration>True</MouseAcceleration>
  <LaunchProgram>
  </LaunchProgram>
  <DinputOnly>False</DinputOnly>
  <StartTouchpadOff>False</StartTouchpadOff>
  <UseTPforControls>False</UseTPforControls>
  <UseSAforMouse>False</UseSAforMouse>
  <SATriggers>-1</SATriggers>
  <SATriggerCond>and</SATriggerCond>
  <TouchDisInvTriggers>-1</TouchDisInvTriggers>
  <GyroSensitivity>100</GyroSensitivity>
  <GyroSensVerticalScale>100</GyroSensVerticalScale>
  <GyroInvert>0</GyroInvert>
  <GyroTriggerTurns>True</GyroTriggerTurns>
  <GyroSmoothingWeight>50</GyroSmoothingWeight>
  <GyroSmoothing>False</GyroSmoothing>
  <GyroMouseHAxis>0</GyroMouseHAxis>
  <GyroMouseDeadZone>10</GyroMouseDeadZone>
  <GyroMouseToggle>False</GyroMouseToggle>
  <LSCurve>40</LSCurve>
  <RSCurve>30</RSCurve>
  <ProfileActions>Disconnect Controller</ProfileActions>
  <BTPollRate>4</BTPollRate>
  <LSOutputCurveMode>quadratic</LSOutputCurveMode>
  <RSOutputCurveMode>linear</RSOutputCurveMode>
  <L2OutputCurveMode>linear</L2OutputCurveMode>
  <R2OutputCurveMode>linear</R2OutputCurveMode>
  <SXOutputCurveMode>linear</SXOutputCurveMode>
  <SZOutputCurveMode>linear</SZOutputCurveMode>
  <TrackballMode>False</TrackballMode>
  <TrackballFriction>10</TrackballFriction>
  <Control />
  <ShiftControl />
</DS4Windows>

**Comment by Ryochan7** [comment]
I have tried the profile and it works fine for me. Axis 0 and Axis 1 for the virtual XInput controller are extremely throttled with the options enabled in the profile; it maxes out at about 0.26. The output does change with different sensitivity values as well. Make sure to check the output for the virtual XInput controller rather than a Wireless Controller listing if you are not using the **Hide DS4 Controller** setting in DS4Windows.
