### ISSUE TITLE
Left stick sometimes fail

### ISSUE THREAD

**Issue by incneet** [Ryochan7/DS4Windows#575]
left stick sometimes cant reach the limit in leftside

[https://i.imgur.com/eqrZJDF.png](url) issue
[https://i.imgur.com/ekM2E5M.png](url) normal

playing a game, the character just walk
car games, you cant turn left

**Comment by Ryochan7** [comment]
Is anything special happening during the normal case? Is the profile still using default values or has it been modified? There should be no reason other than hardware problems that would cause the input to reach full negative during some polls and then stop short during other gamepad polls. That reading shows the raw values returned from the controller before any mapping occurs so it should reflect the values pulled from the controller.

You might also want to check the values for the original Wireless Controller in HTML5 Gamepad Tester.

https://html5gamepad.com/

**Comment by incneet** [comment]
but when i use controller with steam, i dont have this problem, its all fine
yes, default profile

**Comment by Ryochan7** [comment]
It's hard to tell. By default, Steam uses a default max zone (Dead Zone Outer) of 85% so it might not be affected by the problem. DS4Windows uses a max zone set at 100% output by default so the stick has to be able to register to the absolute edge. You can decrease the max zone for LS in order to get maximum Left Stick output more quickly.

**Comment by incneet** [comment]
hey Ryochan, its works, thanks man : D

**Comment by Ryochan7** [comment]
I guess I will end this discussion with a shout out to GloSC. It helped with finding out a relative number behind the Dead Zone Outer. It would be nice if Steam gave some kind of numeric value display besides just focusing on number of ticks traveled on the slider.

https://alia5.github.io/GloSC/
