### ISSUE TITLE
Remapping sticks partially results on no inputs from non remapped sections v1.6.10

### ISSUE THREAD

**Issue by Miltrivd** [Ryochan7/DS4Windows#579]
I updated from 1.6.8 today and found that a remap that I use for a racing game (DiRT Rally) does not work anymore.

I have Right Stick Down mapped to L2 so I can map in game L2 to braking but also brake with Right Stick Down. Right Stick Up is untouched and mapped in game to accelerate. The result is that L2 and Right Stick down properly brake in game but Right Stick Up shows no input in game.

Remade the profile from scratch, same results. Tested going back to 1.6.8 and works there with no issues.

**Comment by Ryochan7** [comment]
Can you share your profile? I will need to test the behavior myself to get an idea what might be happening. I have tried to duplicate that config on my end and it works for me. The only advice that I have right now is for you to set dead zones for RS, L2, and R2 if you have not already done so.

With the newer remapping routine, the priority of duplicate inputs has changed slightly. In the old routine, for most actions, the remapped control has higher priority; an example would be Circle and L2 mapped to output LT which would cause Circle to have priority over L2 even if L2 is active. There was an exception for the sticks which only allow an overridden control to be active if the default control was not active; mapping Dpad Down and Right Stick Down to output RS Down would cause Dpad Down to change output RS Down only if input Right Stick Down is not already active.

In the newer routine, remapped controls will always override default controls if both are active at the same time.

**Comment by Miltrivd** [comment]
This is with the profile as is. Got LS and RS deadzones at 0.08, nothing changed on L2. Windows controller settings also can't detect up input on RS.

Tried setting .25 to all deadzones (RS, LS, L2 and R2) and the results are the same.

[DiRT Rally.zip](https://github.com/Ryochan7/DS4Windows/files/2870526/DiRT.Rally.zip)

**Comment by Ryochan7** [comment]
Thank you for sharing the profile. Now I can see the problem. I will take a look into why RS Up is not working.

**Comment by Ryochan7** [comment]
This looks like another state field resetting problem. The remapped RS Down causes both RY controls to get reset which loses the value for RS Up. I don't like the mapping design of DS4Windows that causes an analog stick to be seen as 4 input controls. It would be better to have the stick seen as one input group mapped to multiple output controls instead. This will take some time to figure out unless I want to just revert to using the older slower routine.

**Comment by Ryochan7** [comment]
I ended up having to re-add an extra step to the mapping process to work around this problem. There didn't seem to be a way to avoid adding it. This version should be slightly faster than the old version though.

**Comment by Miltrivd** [comment]
Thanks a lot for looking into it and it's nice to hear you could work out the problem.

**Comment by Ryochan7** [comment]
I am still testing a few things with the current code. Hopefully version 1.6.11 will be released shortly.

**Comment by Ryochan7** [comment]
Version 1.6.11 is out. The Dirt Rally profile should work as intended; I have tested that profile again to confirm.

https://github.com/Ryochan7/DS4Windows/releases/download/v1.6.11/DS4Windows_1.6.11_x64.zip

**Comment by Miltrivd** [comment]
Updated and it's working as intended. Thanks a lot once again.
