### ISSUE TITLE
Razer Raiju Tournament Edition Support

### ISSUE THREAD

**Issue by jontan1** [Ryochan7/DS4Windows#580]
Requires Support:
Anyone had any success in detecting the Raiju Tournament Edition within DS4 Windows?

Does the PID and VID required to be added just like the Raiju Ultimate?

Thanks!

**Comment by Ryochan7** [comment]
Including the PID and VID of the controller would be the first step. If DS4Windows does not work with the controller as is then someone would have to tweak the source code to make the app cooperate. I do not have access to that hardware so I cannot attempt to do it myself.

**Comment by jontan1** [comment]
Travis thanks , is the PID and VID for USB connections us available via the device manager? Will figure it out and feedback to you.

Thanks,
SM Tan

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Ryochan7** [comment]
Yes. I could use the value from either the Device Instance Path or the Hardware Ids given for the device. Both of those properties would contain both the VID and PID.

**Comment by jontan1** [comment]
HI Travis,

Thanks for the help; I tried the ultimate it didn’t work as it was looking at the ultimate PID VID.

So here is the PID VID for the Tournament edition of the Raiju:

HID Compliant Game Controller:

HID\VID_1532&PID_1007&REV_0101&MI_03&Col01
HID\VID_1532&PID_1007&MI_03&Col01
HID\VID_1532&UP:0001_U:0005
HID_DEVICE_SYSTEM_GAME
HID_DEVICE_UP:0001_U:0005
HID_DEVICE

Raiju Wired Sound:

USB\VID_1532&PID_1007&REV_0101&MI_00
USB\VID_1532&PID_1007&MI_00

Does this help?

Thanks,

Sent from Mail for Windows 10

**Comment by mika-n** [comment]
The current version has a pre-fixed list of VID/PIDs in a source code level (and few special rules to ignore certain bogus device IDs exposed by certain devices).  

There was an attempt to replace this pre-fixed list of IDs with an external XML configuration file which can be updated without re-compiling the app. Now when there are certain changes in the core engine of DS4Windows (mainly related how certain objects are allocate/re-created during polling threads and newer C# version) then maybe random garbage collection slowness of .NET engine would not cause those unexplained performance slow downs anymore?
[XML configuration list of recognized DS4 devices](https://github.com/Ryochan7/DS4Windows/pull/272
)

**Comment by Ryochan7** [comment]
Here is a test build with that VID and PID information included. Getting the headphone jack working would take additional work so that is not taken into account. I would need the **Friendly Name** property of the sound device as a string comparison is done to try to find the appropriate sound device; I have not been able to find any better way to isolate sound devices with the API that is being used.

https://drive.google.com/file/d/1Sm2YB9_4ROKnLToq1hKlGz3Z-pfDFfKN

**Comment by jontan1** [comment]
Sorry for the delay; the Friendly Name is:
Razer Raiju Tournament Edition Wired

Thanks it works, its as good as any PS4 controller. 

Sent from Mail for Windows 10

**Comment by Ryochan7** [comment]
Test build with audio search change.

https://drive.google.com/open?id=1VTUTBSEkj97ZmwYDmJznnEJmuDA4EZFF

**Comment by jontan1** [comment]
Thanks I give a go and feedback

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jontan1** [comment]
Travis, thanks it worked really well, thanks again for your time. Would the future versions includes this success?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Ryochan7** [comment]
I am not sure the old diff would apply cleanly at this point. It might have to be re-made. Maybe the changes can make it into version 1.7.8. It looks like version 1.7.7 will be a quick hotfix to correct the DS4 output dpad problem.

**Comment by jontan1** [comment]
Great job mate, please let me know if it's included in the release notes.  Thanks, Su Min

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
