### ISSUE TITLE
Question: Is it possible to make rumbling affect the lightbar?

### ISSUE THREAD

**Issue by JackMiranda** [Ryochan7/DS4Windows#583]
I would like to, say, make the lightbar turn red when heavy rumbling is happening. Is this possible?

**Comment by Ryochan7** [comment]
That functionality is not possible. I'm not sure how useful that would actually be tbh.

**Comment by JackKiefer** [comment]
Well, not useful, but definitely cool! Is the functionality simply not implemented, or is it actually technically impossible? I'd be happy to contribute a patch if the former is the case.

**Comment by Ryochan7** [comment]
It does look like the current lightbar routine does partially take haptics into account for so called distance profiles. The only criteria that I see is that the term distance has to be a part of the profile name. I never tried to use a so called distance profile but it does not seem like a very good idea. It would probably be better to have an explicit mode with some configurable options.

https://github.com/Ryochan7/DS4Windows/blob/jay/DS4Windows/DS4Control/DS4LightBar.cs#L261
