### ISSUE TITLE
(feature request) chatpad  support

### ISSUE THREAD

**Issue by optimus0** [Ryochan7/DS4Windows#585]
please add chatpad support...

**Comment by Ryochan7** [comment]
Does whichever chatpad that you are talking about just act as a bluetooth keyboard? If that is the case then that would involve Windows and have nothing to do with DS4Windows. I don't own a PS4 so I did not know that it supported connecting bluetooth keyboards until searching for chatpad information; I don't own any current gen console.

https://www.reddit.com/r/ffxiv/comments/2p6cz1/would_a_ps4_chatpad_keyboard_attachment_be/

**Comment by Ryochan7** [comment]
An example of a chatpad for the DualShock 4. The video shows the sync process and most other brand chatpads seem fairly similar.

Ortz PS4 Wireless Mini Bluetooth Keyboard Review: https://www.youtube.com/watch?v=CS2L5NzJGSA

**Comment by optimus0** [comment]
thanks so much for clarified this for me 
i tough that i will need some weird driver like the one needed for the 360 controller (xbox one also uses an special driver by microsoft)
thanks
