### ISSUE TITLE
Question: is Nacon Compact Controller supported?

### ISSUE THREAD

**Issue by zetsuya** [Ryochan7/DS4Windows#588]
Title says it all. I've ordered one and should get it in 3 days but I'm afraid this wouldn't be supported.

**Comment by Miltrivd** [comment]
I have one, it's not supported. It works as a Xinput device under Windows.

**Comment by Ryochan7** [comment]
I don't think I have seen that controller before. It is not in the known devices database. Also, it supposedly only works in XInput mode on Windows so there would be no way to support it. There wouldn't be that much of a need for DS4Windows in that case either.

I might need the product link for future reference in searches so I will post it here.

https://www.nacongaming.com/product/controllers/gaming-controllers/compact-controller-ps4/

**Comment by Miltrivd** [comment]
> Title says it all. I've ordered one and should get it in 3 days but I'm afraid this wouldn't be supported.

Btw, if you want customization for Xinput devices you can try Durazno or Xinput Plus (website is in Japanese but the program has other language options).

**Comment by zetsuya** [comment]
> > Title says it all. I've ordered one and should get it in 3 days but I'm afraid this wouldn't be supported.
> 
> Btw, if you want customization for Xinput devices you can try Durazno or Xinput Plus (website is in Japanese but the program has other language options).

Will see when i get it arrived! It is mainly to play Rocket League and Dark souls 3. Thanks
