### ISSUE TITLE
Map X Y and Z axis of gyro?

### ISSUE THREAD

**Issue by hooty7734** [Ryochan7/DS4Windows#591]
I'm not sure if I'm mistaken or not, but it appears this functionality is not available. As of right now I can't seem to use more than two axes at once.

I would enjoy to see the possibility of adding the third axis regardless of using mouse controls or buttons. I currently use pitch and yaw for mouse controls but I would like to use roll simultaneously for flight games and motion control plus emulation.

**Comment by Ryochan7** [comment]
Roll support is not available for tilt controls. It would have limited usage and Steam also does not offer much support for using gyro roll. Roll only tracks the orientation of the controller with respect to the ground so tilting the controller left or right would result in the same output with maximum output being when the controller face is facing the floor.

Maybe what you might want would be something similar to the 360 steering wheel mode when the gyro coordinates are used to determine the orientation angle of the controller. That could be mapped to a joystick as the output. That mode can only be utilized if you map the gyro to tilt controls so it cannot be mixed with mouse mode.
