### ISSUE TITLE
Feature request: 8 controllers

### ISSUE THREAD

**Issue by Alxs10** [Ryochan7/DS4Windows#594]
I always wondered why the program was limited to 4 controllers. It would be nice to be able to connect 8 controllers (super smash bros for example). Is it possible to put a 8 controllers limit instead of 4?

Thanks

**Comment by Ryochan7** [comment]
The biggest reason is because that is the limit with XInput. It supports up to 4 controller connections.

**Comment by Alxs10** [comment]
Makes sense, thanks for clarifying.
