### ISSUE TITLE
Single DS4 is assigned to xinput player 2

### ISSUE THREAD

**Issue by teeedubb** [Ryochan7/DS4Windows#595]
Hi,

I have noticed my controller occasionally is assigned Xinput Player 2/3/4 at random and the only way to get back to Player 1 is to reboot my machine - I have tried a few things to reset the controller with out rebooting but nothing I have tried works. In the example below the DS4 was reconnected after the PC had been suspended but I don't recall if the controller was on or off when it suspended. I have noticed it as well with disconnects and reconnects, but it seems to have gotten better after the latest update to DS4Windows. When this happens, it will cycle through controller numbers, but it never goes back to 1 (you can force it happening by frequently dis/reconnecting the controller and start/stopping DS4Windows).

![image](https://user-images.githubusercontent.com/3460068/53654529-06ebdc80-3ca2-11e9-8dd7-62d57d52c3de.png)

Its really strange because DS4 assigns it as controller #1 and MAME sees the controller as #0, but also as Xinput Player 2. Windows joystick config and Shadow Warrior 2 acts like a controller isnt connected.

[full DS4Windows log](https://github.com/Ryochan7/DS4Windows/files/2920423/ds4win.log.txt)

My machine is running win 10 x64 and is using a Intel 9260 BT card with a the one DS4 and no other controllers attached. DS4Windows is 1.6.12.

EDIT: Windows will see the DS4 if DS4Windows is stopped, but will not once DS4Windows is started again.
![image](https://user-images.githubusercontent.com/3460068/53655145-89c16700-3ca3-11e9-9346-24d163f5ffc1.png)

**Comment by mika-n** [comment]
The log file shows "index out of bound: touchpad" errors. Could be that this has nothing to do with the error but if that exception is thrown during a controller hotplug process then it may leave some "bits in upside down" position. Does it help if you remove all touchpad mappings (I guess you are using touchpad as a mouse)?

**Comment by Ryochan7** [comment]
I will have to confirm but it looks like nothing stops the main controller input routine in USB mode while suspending. That might at least explain the index out of bounds problems.

**Comment by Ryochan7** [comment]
The problem that was discussed before did account for the out of bounds errors. There were some null reference exceptions happening behind the scenes as well. I didn't run into a problem with ScpVBus although I might have just gotten lucky.

**Comment by teeedubb** [comment]
Great, thanks for looking into this issue!
