### ISSUE TITLE
Doesn't save 'Use Custom Color' / CustomLed1

### ISSUE THREAD

**Issue by BoukObelisk** [Ryochan7/DS4Windows#596]
Whenever I want to use the Custom Color option instead of the Profile color (clicking the color bar), DS4 windows never saves my settings when closing the program and re-opening it (or restarting the computer). 

Then if you go into the Profiles.XML file, the setting <CustomLed1>True:0,0,255</CustomLed1> always reverts back to False - even if I set the file to Read-only.

I prefer using the Custom LED since it's profile-independent and it worked fine on the original DS4Windows. For some reason it doesn't work here. Is it something you could look into if or when you have the time? 

Thanks again for an amazing job with this program, it's really excellent.

**Comment by Ryochan7** [comment]
This one ended up being an easy fix. Custom LED was treated like a profile setting and would be reset while switching profiles. Removing the two fields from profile resetting fixes the issue.

**Comment by Ryochan7** [comment]
This problem has been fixed in version 1.6.13.
