### ISSUE TITLE
[Minor request] Could we get an auto-update option? (Skip confirmation)

### ISSUE THREAD

**Issue by sondregronas** [Ryochan7/DS4Windows#597]
Title.

Would be a nice QOL feature if we could toggle the option to automatically update without the confirmation prompt. Helpful for those of us that leave their mouse & keyboard in a different room when starting the app :)

Thanks for your great work!

**Comment by Ryochan7** [comment]
I'm am not sure how I feel about allowing automated updating. I like to perform manually updating of software and it can be annoying when software decides to update automatically like Windows 10.

**Comment by Ryochan7** [comment]
I think I unintentionally proved how this would be a bad idea with the release of DS4Windows 2.0. Also, it proved that some type of Changelog display is needed for update prompts.
