### ISSUE TITLE
User Account Control warns about HidGuardHelper on one computer but not the other

### ISSUE THREAD

**Issue by Turbozpeed99** [Ryochan7/DS4Windows#598]
Sorry if this is a bit of a petty/small issue I'm having, but I installed DS4Windows on 2 different systems, however upon launching the program, it activates UAC about HidGuardHelper.exe on only 1 of my computers and I'm not sure why this is happening, any help is useful, thanks!

**Comment by Ryochan7** [comment]
Maybe you are running DS4Windows as the administrator on one machine; could be that way if set explicitly or if DS4Windows is started as a task. The UAC prompt would appear if DS4Windows is run as a normal user. The HidGuardHelper application has to be run with admin privileges so it can edit the system registry.

**Comment by Turbozpeed99** [comment]
I am admin on both systems. I have also tried poking around with the permissions on both DS4Windows and the HidGuardHelper applications but to no success. I'm not sure if its a system setting or not, but my UAC settings are the same across both systems.

**Comment by sondregronas** [comment]
What I did was create a task in Windows Task Scheduler named `DS4Windows`, set to "Run with highest privileges", and in actions set it to start program: DS4Windows.exe. Then just create a shortcut with target: `schtasks.exe /run /tn "DS4Windows"`

https://www.digitalcitizen.life/use-task-scheduler-launch-programs-without-uac-prompts

**Comment by Ryochan7** [comment]
Running DS4Windows from a Task would force DS4Windows to run with administrative privileges. It does have the downside of running the process with Low IO and Memory priority; that issue should be addressed in the next release with recent code changes.

One simple way to check whether an application has launched with admin privileges is via Task Manager. You can go to the Details tab and look at the value for the **Elevated** column. I cannot remember if that column is visible by default so you might have to enable that column for viewing.

![taskman_elevated](https://user-images.githubusercontent.com/581968/54495324-d36b9d80-48b0-11e9-802e-de2519b19ce2.png)
