### ISSUE TITLE
Best way for wireless functionality?

### ISSUE THREAD

**Issue by AnotherLife** [Ryochan7/DS4Windows#60]
Hello, just found your fork of DS4Windows and I will be using it from now on with my v2, thank you!

I noticed that you added support for Sony's wireless dongle. I don't have any Bluetooth functionality in my PC, what purchase would be best to use with your fork for best connectivity/latency? A generic BT dongle or the official?

**Comment by Ryochan7** [comment]
I don't have a real recommendation about which is best at this time. I have an older Rocketfish Bluetooth adapter that I use most of the time. The official Sony dongle works pretty well but it does have a lower poll rate than other connections (usually around 8 ms per report). The official dongle does seem to have a more solid connection than my Bluetooth adapter and the official dongle supports the headphone and microphone jack on the controller. A couple of big caveats with the Sony dongle is that it only supports connecting one DS4 controller to it and it exposes a controller to Windows at all times even when no DS4 is synced to it.

As for support, Bluetooth will have higher priority than the Sony dongle.

**Comment by AnotherLife** [comment]
I like having only 1 controller showing up in Windows, so I think I will go for a generic BT dongle, then. Thank you and keep up the good work!
