### ISSUE TITLE
Sudden latency issues (latency over 10ms)

### ISSUE THREAD

**Issue by mavkci** [Ryochan7/DS4Windows#601]
First time when I connected my controller with my laptop was with a cable, then I disconnected it and connected via bluetooth. Everything worked just fine for 2-3 days until my battery was almost empty. I decided then just to play via cable and I did. Everything worked the same with the cable. Next day I went to play a game and again I decided to connect to it via bluetooth but now my controller blinking red and showing message in Log windows that latency is switching over 10ms, under 10ms... What could be the cause of that. Tried to restart laptop few times, tried to restart controller few times, deleted profile folder of ds4 but that didn't help either.

**Comment by Ryochan7** [comment]
I don't think any recent change in DS4Windows would have caused that. It works better on my system. Have you checked Task Manager to see if any process is being CPU or disk intensive when that happens?

**Comment by mavkci** [comment]
Yeah I checked, nothing seems out of ordinary. I mean I can live with the cable but it just annoys the shit out of me when I know that i worked properly day ago.

**Comment by Corrodias** [comment]
Perhaps you added some other software or updated some driver, anything that could be causing communication latency with the BT antenna?

**Comment by HadesIzanami** [comment]
I have the same problema, my temporal solution is, disable wifi driver ... Works now fine Bluetooth but maybe the driver or something has wrong ...I don't know what's the issue whit the latency BT

**Comment by mavkci** [comment]
> I have the same problema, my temporal solution is, disable wifi driver ... Works now fine Bluetooth but maybe the driver or something has wrong ...I don't know what's the issue whit the latency BT

weird but this seems to be a good solution. hmmm




> Perhaps you added some other software or updated some driver, anything that could be causing communication latency with the BT antenna?

I did not.

**Comment by Ryochan7** [comment]
Maybe there is some odd interference going on. My main gaming PC is close enough to my main router that I can have it wired. Even when I had the PC in a different room, I tend to have a dedicated router with open firmware acting as a bridge for devices rather than using wifi adapters; my experience seems to show that the router configuration resulted in better connections.

**Comment by mika-n** [comment]
Is your WIFI router using 2.4ghz radio frequency? If the router and your laptop/PC/Chromecast supports 5Ghz frequency then change the WIFI to use that radio frequency.  Sometimes it may help if you can change few of the devices from 2.4ghz band to 5Ghz band if not all your WIFI clients are 5Ghz compatible (less noise in 2.4ghz). Often 5Ghz WIFI routers support both frequencies at the same time.

Bluetooth happens to use 2.4Ghz radio frequency also, so sometimes there is a chance that 2.4ghz radio wave is full of "noise".

If you cannot use 5Ghz WIFI then try to change the channel of 2.4ghz WIFI network (in router configurations). Some other channel may cause less noise in BT frequency.

Also, do you have lots of other WIFI networks near you? Could be that your neighbors are filling the channel with noise and your BT device is a collateral victim.

**Comment by DrConflict** [comment]
I'm having the same problems on Windows 10 build 1809 using v 1.7.4.
I get constant latency spikes over 10ms and it's driving me nuts. I tried
solutions I found online like setting system to performance mode, checking
USB and Bluetooth power options but nothing seems to be working.
Does anyone have any clue what's going on here? Using the latest
drivers as well for everything.

**Comment by mika-n** [comment]
Radio waves (BT or WIFI) sometimes have a mind of their own. 
- Try disabling WIFI (temporarly if you have to use WIFI for networking) to see if it helps. Sometimes cheap integrated WIFI+BT circuits may cause noise to each other.
- If your PC or near by mobile phones have "search constantly for BT and/or WIFI" option enabled then try disabling that option.
- If some of your friends have a different BT usb dongle then try those BT receivers.
