### ISSUE TITLE
Issue with ds4 

### ISSUE THREAD

**Issue by Mattyice505** [Ryochan7/DS4Windows#606]
The scuf vantage just had a new update today, and since then i have been unable to use my scuf controller on my pc.

**Comment by mika-n** [comment]
If Windows itself still detects the controller but DS4Windows doesn't then is there a possibility that the update changed the HID device ID/description name? Check the USB  PID and VID values. See the following post for more info how to check it. https://github.com/Ryochan7/DS4Windows/issues/580

**Comment by Ryochan7** [comment]
Is the original DirectInput controller still seen by Windows? Make sure to check Devices and Printers from the Control Panel and then test the input from the Game Controller settings window.
