### ISSUE TITLE
DS4 won't find wired controller

### ISSUE THREAD

**Issue by fancyhedgehog09** [Ryochan7/DS4Windows#607]
The app can't find the controller, but the computer does and names it "wireless controller". But I cannot use it in any way, nothing happens when i push buttons. Since the app won't find it I'm guessing it isn't working like it should?

**Comment by mika-n** [comment]
What do you see in DS4Windows log messages (Logs tab page in Ds4Windows app)?
What is the controller brand and model? Is it a stock Sony DS4 controller or some 3rd party "compatible" version? 

Those 3rd party controllers may have different USB VID/PID identifiers, so DS4Win app may not recognize a controller as "DS4 Controller". In those cases you should check the USB VID/PID identifiers and post results here. If the controller type is not yet supported then it may be possible to get it working once the new controller type is added to the app code.

See following post for more info about how to check USB VID/PID identifiers: https://github.com/Ryochan7/DS4Windows/issues/580

**Comment by Ryochan7** [comment]
Closing issue due to lack of feedback
