### ISSUE TITLE
Bluetooth auto-disconnect when connecting by USB with an adapter

### ISSUE THREAD

**Issue by Corrodias** [Ryochan7/DS4Windows#609]
I have an adapter device, a Titan Two, that can communicate with the DS4 via bluetooth and present it to the PC as any wired controller, including a DS4. Though there isn't much reason to do this rather than connecting the DS4 directly with a bluetooth adapter (though the T2 can do a few things DS4W can't), I figured I'd try it out. It actually works well, except that the controller automatically disconnects after a few seconds. I believe I tried it without DS4W running, and it didn't disconnect.

Is DS4W sending a disconnect command after connecting by USB? I know the "quick charge" option has help text that says "EXPERIMENTAL: Auto-Disable BT when connecting to USB", but I do not have that option enabled, regardless of whether that would cause this behavior.

**Comment by mika-n** [comment]
What do you see in the Log screen of DS4Win app when this happens?

DS4Win app does have "idle disconnect" feature which disconnects the controller after X mins idling. Not sure if this has anything to do with your problem but is one potential problem area when DS4 controller is connected using T2 gadget.

**Comment by Corrodias** [comment]
Upon further experimentation... what seems to happen is that it disconnects if I turn the LED off entirely. I doubt it's DS4Windows that's the culprit. This is essentially fine, as I like having the LED on anyway, at minimum brightness, so I can tell whether it's currently connected or not.

(The log doesn't show anything other than the usual connection message for the adapter, with nothing after that.)
