### ISSUE TITLE
NullReferenceException on defining custom colors

### ISSUE THREAD

**Issue by rafsanjani** [Ryochan7/DS4Windows#61]
A null reference exception is being raised on my build when user clicks on "Define custom colors" as shown in the screenshot below.

Visual Studio 2017 community edition
Windows 10 with all updates installed

![image](https://user-images.githubusercontent.com/9197459/27009900-be03ec96-4e88-11e7-877e-e7ada150a9ae.png)

![screenshot_1](https://user-images.githubusercontent.com/9197459/27009874-60932b62-4e88-11e7-9615-3a88c30270fa.png)

**Comment by Ryochan7** [comment]
Checked and the event handler was not being checked before invoking. A small change fixes the problem.
