### ISSUE TITLE
Request: Add ability to change profiles on key binding

### ISSUE THREAD

**Issue by RobertoBiundo** [Ryochan7/DS4Windows#610]
I noticed that it is possible to change the current working profile by swiping on the touch pad.
This is so far for me not very reliable and certainly not very useful.
I'm trying to use the controller for mapping more buttons that what the controller has and it would be useful to swipe between those configurations and using the touch pad as a mouse of keys withing the same game without having to swipe with two fingers every time on the touch pad. Example
Profile 1: Mouse + main action buttons
Profile 2: Buttons + other actions buttons

If i could assign in both profiles lets say X or O as "change to next profile" or "change to profile 1-2-3..." then i would be able to control full non-game pad strategy games from the ps4 controller.

Please let me know if you need help with the feature. I consider it to be a nice one and may be able to help and then create a pull request for it if you want.

**Comment by mika-n** [comment]
SpecialActions (see profile editor and Special Actions tab page) has a "load a profile" action type. You can bind any button to a special action and it would load a specified profile. This "special action" definition is a profile specific, so using it to link different profiles to the same key you can implement "cycle through all profiles" type of feature.

DefaultProfile:
- SpecialAction=Share button and Load a profile
- Action profile=FIFA_ingame_profile

FIFA_ingame_profile:
- SpecialAction=Share button and Load a profile
- Action profile=FIFA_inmenus_profile

FIFA_inmenus_profile:
- SpecialAction=Share button and Load a profile
- Action profile=DefaultProfile

As you can see, using the same action key BUT different profile you can implement "cycle through certain profiles by pressing a key" type of functionality. Of course you could use also Btn1 and Btn2 action keys to load a Profile1 and Profile2 if you want to use fixed profiles per certain button.
