### ISSUE TITLE
[Bug] "XBox Controller #1 Failed" after update to 1.6.14

### ISSUE THREAD

**Issue by AceHarmon** [Ryochan7/DS4Windows#611]
I've been happily using DS4Windows to use my DualShock4 in Steam. On the latest update, the log says "Xbox controller #1 failed. Using DInput only mode" Rolling back to the previous version fixed this. Not sure what the cause is. Judging by previous issues, I wonder if the hot-update was the cause. DS4Windows didn't register a problem after manually exiting and restarting the program.

Since this seems to have previously been reported, and it's not an active issue after a restart, I figured I'd still let you know.

**Comment by Ryochan7** [comment]
This issue should not be relevant after the next update. DS4Windows will start using the ViGEmBus driver in the next release and I have never heard of anyone mention this kind of problem with that driver.

**Comment by Corrodias** [comment]
I believe I get that if DS4Windows crashes (often when cancelling an edit to a profile) and I restart it. Using the button in the lower right to stop and start the service back up fixes it.

**Comment by Ryochan7** [comment]
DS4Windows 1.7.0 is now out. Please update DS4Windows and try it out. This type of problem should not happen anymore.
