### ISSUE TITLE
One Issue and Two Requests

### ISSUE THREAD

**Issue by HadesIzanami** [Ryochan7/DS4Windows#612]
I have found that, when you want to change the color in the "Flash at" function, the control does not show a preview of the color you are changing, so it becomes difficult to know how it is, without the need to have a low battery.

![Captura](https://user-images.githubusercontent.com/42960801/54729609-2b710100-4b4a-11e9-8e71-f9fdc9cbb185.PNG)

My two requests are, one, to be able to add a function more than the ones that are the "Pulse At" and the "Flash At", which would be like the function that is in the extra options, that the LED will change color When the battery goes down, example, battery 100% would be green, 50% an orange tone and 20% would be a red.

![Captura2](https://user-images.githubusercontent.com/42960801/54729600-1dbb7b80-4b4a-11e9-86dd-ea6895304384.PNG)

Second, return the function of seeing less than 10% of battery. That is, see 9%, 6% and up to 1%.

Thanks and regards.

**Comment by Ryochan7** [comment]
Sharing a color status box can be confusing. I haven't changed that out of paranoia. The smallest change can have unforeseen performance changes.

The **Color by Battery %** option will probably give you what you want. When you select that option, new controls will appear that you can use to pick an empty color value. The original lightbar color controls will specify the full color value. The lightbar color will transition as the battery level goes down.

The last request is not possible. The battery value range reported by the DS4 is not that big. For a BT connection the values range from 0 - 8 and USB values range from 0 - 11.
