### ISSUE TITLE
Can't reconnect in-game on 1.7.0

### ISSUE THREAD

**Issue by KyleMcStyle** [Ryochan7/DS4Windows#614]
It seems like the latest update makes it so that reconnecting the controller while playing a game makes you have to restart to be able to use it again.

**Comment by Ryochan7** [comment]
Sounds like it might be an exclusive mode problem. Only one relevant change might contribute to that but it should not have. I can post a test build after I get done testing other issues.

**Comment by Ryochan7** [comment]
Test build

https://drive.google.com/open?id=1__12M8xmgqqSKGZLSz8dujioIzf_J0xl
