### ISSUE TITLE
Rumble touch pad stops it

### ISSUE THREAD

**Issue by InstallGentoo11** [Ryochan7/DS4Windows#615]
I just randomly find out the test rumble doesn't stop after 5 seconds like it used to, which is small, but cool addition.
That said I find that when you press the touch pad, no matter where, the rumble stops. That doesn't happen with any other button. Maybe that's something to fix.

**Comment by Ryochan7** [comment]
Do you have any extras mapped to the touchpad? That does not make sense. Can you share your profile and maybe your Special Actions as well?

**Comment by InstallGentoo11** [comment]
Nothing is mapped on the touch pad currently. Only Special Action is the default one.

`<?xml version="1.0" encoding="utf-8"?>


<DS4Windows>
  <flushHIDQueue>True</flushHIDQueue>
  <touchToggle>False</touchToggle>
  <idleDisconnectTimeout>0</idleDisconnectTimeout>
  <Color>0,0,0</Color>
  <RumbleBoost>100</RumbleBoost>
  <ledAsBatteryIndicator>False</ledAsBatteryIndicator>
  <FlashType>0</FlashType>
  <flashBatteryAt>0</flashBatteryAt>
  <touchSensitivity>0</touchSensitivity>
  <LowColor>255,255,255</LowColor>
  <ChargingColor>255,255,255</ChargingColor>
  <FlashColor>0,0,0</FlashColor>
  <touchpadJitterCompensation>True</touchpadJitterCompensation>
  <lowerRCOn>False</lowerRCOn>
  <tapSensitivity>0</tapSensitivity>
  <doubleTap>True</doubleTap>
  <scrollSensitivity>0</scrollSensitivity>
  <LeftTriggerMiddle>0</LeftTriggerMiddle>
  <RightTriggerMiddle>0</RightTriggerMiddle>
  <TouchpadInvert>0</TouchpadInvert>
  <L2AntiDeadZone>0</L2AntiDeadZone>
  <R2AntiDeadZone>0</R2AntiDeadZone>
  <L2MaxZone>100</L2MaxZone>
  <R2MaxZone>100</R2MaxZone>
  <ButtonMouseSensitivity>25</ButtonMouseSensitivity>
  <Rainbow>0</Rainbow>
  <LSDeadZone>0</LSDeadZone>
  <RSDeadZone>0</RSDeadZone>
  <LSAntiDeadZone>0</LSAntiDeadZone>
  <RSAntiDeadZone>0</RSAntiDeadZone>
  <LSMaxZone>100</LSMaxZone>
  <RSMaxZone>100</RSMaxZone>
  <LSRotation>0</LSRotation>
  <RSRotation>0</RSRotation>
  <SXDeadZone>0.25</SXDeadZone>
  <SZDeadZone>0.25</SZDeadZone>
  <SXMaxZone>100</SXMaxZone>
  <SZMaxZone>100</SZMaxZone>
  <SXAntiDeadZone>0</SXAntiDeadZone>
  <SZAntiDeadZone>0</SZAntiDeadZone>
  <Sensitivity>1|1|1|1|1|1</Sensitivity>
  <ChargingType>0</ChargingType>
  <MouseAcceleration>False</MouseAcceleration>
  <LaunchProgram>
  </LaunchProgram>
  <DinputOnly>False</DinputOnly>
  <StartTouchpadOff>False</StartTouchpadOff>
  <UseTPforControls>True</UseTPforControls>
  <UseSAforMouse>False</UseSAforMouse>
  <SATriggers>-1</SATriggers>
  <SATriggerCond>and</SATriggerCond>
  <SASteeringWheelEmulationAxis>None</SASteeringWheelEmulationAxis>
  <SASteeringWheelEmulationRange>360</SASteeringWheelEmulationRange>
  <TouchDisInvTriggers>-1</TouchDisInvTriggers>
  <GyroSensitivity>100</GyroSensitivity>
  <GyroSensVerticalScale>100</GyroSensVerticalScale>
  <GyroInvert>0</GyroInvert>
  <GyroTriggerTurns>True</GyroTriggerTurns>
  <GyroSmoothingWeight>50</GyroSmoothingWeight>
  <GyroSmoothing>False</GyroSmoothing>
  <GyroMouseHAxis>0</GyroMouseHAxis>
  <GyroMouseDeadZone>10</GyroMouseDeadZone>
  <GyroMouseToggle>False</GyroMouseToggle>
  <LSCurve>0</LSCurve>
  <RSCurve>0</RSCurve>
  <ProfileActions>Disconnect Controller</ProfileActions>
  <BTPollRate>4</BTPollRate>
  <LSOutputCurveMode>linear</LSOutputCurveMode>
  <RSOutputCurveMode>linear</RSOutputCurveMode>
  <LSSquareStick>False</LSSquareStick>
  <RSSquareStick>False</RSSquareStick>
  <L2OutputCurveMode>linear</L2OutputCurveMode>
  <R2OutputCurveMode>linear</R2OutputCurveMode>
  <SXOutputCurveMode>linear</SXOutputCurveMode>
  <SZOutputCurveMode>linear</SZOutputCurveMode>
  <TrackballMode>False</TrackballMode>
  <TrackballFriction>10</TrackballFriction>
  <Control>
    <Button>
      <RXNeg>Right X-Axis-</RXNeg>
      <RXPos>Right X-Axis+</RXPos>
      <RYNeg>Right Y-Axis-</RYNeg>
      <RYPos>Right Y-Axis+</RYPos>
      <R3>Right Stick</R3>
      <PS>Start</PS>
      <TouchLeft>Unbound</TouchLeft>
      <TouchUpper>Unbound</TouchUpper>
      <TouchMulti>Unbound</TouchMulti>
      <TouchRight>Unbound</TouchRight>
      <Share>Back</Share>
      <Options>Start</Options>
    </Button>
  </Control>
  <ShiftControl />
</DS4Windows>`

**Comment by Ryochan7** [comment]
I just tested it and I can confirm that it happens to me as well. I will have to look into this.

**Comment by mika-n** [comment]
Touchpad clicking does indeed stop the rumble effect at least when "Test light/Heavy" button in profile editor was pressed and "force feedback" is in test mode. There seems to be "SetRumble(0,0)" call in touchpad click event handler.

**Comment by Ryochan7** [comment]
Been checking other things so I just got back to this. This same behavior happens with version 1.6.14.

**Comment by Ryochan7** [comment]
Not sure why that setRumble call is there but that is the culprit.

**Comment by InstallGentoo11** [comment]
I would guess there wasn't suppose to be a fix fro this in 1.7.1? Just making sure.

**Comment by Ryochan7** [comment]
I have not decided whether to remove that call or leave it there. I guess the call was put there to help keep some unintentional mouse movement from possibly happening due to the controller shaking. Other issues were more important as well which justified making a patch release.

**Comment by Ryochan7** [comment]
The call has been removed. There was not much of a need for it.
