### ISSUE TITLE
Controller Numbering Issues

### ISSUE THREAD

**Issue by JJXB** [Ryochan7/DS4Windows#618]
Running 1.7.0 and the switch to VigEm hasn't solved the issue of Xinput controller numbering on my Windows 10 1809 system being iffy after replugging the DS4 (sometimes being needed to deal with the problem of Hide DS4 Controller still being iffy too).

The log tab always tells me it's X360 Controller #1 whenever this is happening but will read as controller #2,#3 or #4 in whatever i'm trying to run (Example being Perfect Dark Zero/Dead Space 2 in Xenia, Stardew Valley or Dead Space 2 PC version - all cases not liking to be controlled by anything but Controller #1) and the only thing that "fixes" it, is a reboot with the controller connected on bootup. I have uninstalled ScpVBus between reboots so that isn't interfering either (or shouldn't be).

Let me know if i'm missing any information and i'll add when possible.

**Comment by Ryochan7** [comment]
DS4Windows now no longer deals with XInput ports at all. The number shown in logs corresponds to the slot number used only within DS4Windows. Something else has to be interfering.

**Comment by JJXB** [comment]
...i'm not sure what it is that's interfering then. but it does seem to have *now* fixed itself only after typing this out for some stupid reason.

**Comment by Ryochan7** [comment]
I would have mention ScpVBus leaving a dead controller behind but you mentioned rebooting so that should not have been a problem. Hopefully the problem does not occur again.
