### ISSUE TITLE
Random disconnects and reconnects after 1.7.0

### ISSUE THREAD

**Issue by InstallGentoo11** [Ryochan7/DS4Windows#619]
I updated DS4Windows, installed ViGEmBus as it wanted, restarted my PC. Tried also disabling ScpVBus just in case, but it doesn't change anything.
Has happened at least 3 times now It disconnects and it reconnects within the same second.

```
21-Mar-19 22:34:53: Found Controller:70:20:84:67:C2:81 (BT)
21-Mar-19 22:34:53: Plugging in X360 Controller #1
21-Mar-19 22:34:53: X360 Controller # 1 connected
21-Mar-19 22:34:53: Controller 1 is using Profile “Default"
21-Mar-19 22:37:02: X360 Controller # 1 unplugged
21-Mar-19 22:37:02: Controller 1 was removed or lost connection
21-Mar-19 22:37:02: Found Controller:70:20:84:67:C2:81 (BT)
21-Mar-19 22:37:02: Plugging in X360 Controller #1
21-Mar-19 22:37:02: X360 Controller # 1 connected
21-Mar-19 22:37:02: Controller 1 is using Profile “Default"
```

**Comment by Ryochan7** [comment]
I will post a test build in a little bit. Maybe the change to the hotplug delay has caused problems. This does sound like an old problem that I had experienced in the past. The change worked fine for me even on Windows 7.

**Comment by InstallGentoo11** [comment]
Right. I am a Windows 7 pleb. Forgot to include it.

**Comment by mika-n** [comment]
Do you get the same effect in Win7 if you use USB connection instead of BT? 
I haven't experienced this behaviour in Win10 but I'm using usb cable to connect the DS4 controller.

**Comment by InstallGentoo11** [comment]
Right after posting I put on the USB cable to test it. So for now no disconnects, though with BT it seemed like it would happen by now.
Just to say, I have been playing a lot of Yakuza lately, for long hours, so doubt any of my hardware has bricked since yesterday. Though driver fucker after the ViGEmBus wouldn't surprise me.

**Comment by Ryochan7** [comment]
Test build

https://drive.google.com/open?id=1__12M8xmgqqSKGZLSz8dujioIzf_J0xl

**Comment by InstallGentoo11** [comment]
By the time I came back the 1.7.1 was already out so I went it with. Over 2 hours of the controller staying on and not disconnects. Tried even to disconnect it once and left it for another 30 minutes. I would say it has been fixed, so I will close the thread.
