### ISSUE TITLE
Bluetooth idle disconnect maximum always 5 min

### ISSUE THREAD

**Issue by LaaZa** [Ryochan7/DS4Windows#62]
Controller disconnects and shuts off after 5 minutes regardless of profile's idle disconnect setting if it is over 5 minutes, settings under 5 minutes do work as expected. No disconnect happens when controller is in use. 

Connected wirelessly via bluetooth
Version 1.4.76

**Comment by shinra358** [comment]
I just tested this at 10mins and it shut off at 10mins.

**Comment by LaaZa** [comment]
For some reason I'm experiencing this issue though, does not happen on my laptop.

**Comment by Ryochan7** [comment]
Works on my machine&#8482;. Is your idle disconnect setting saved in the profile properly? Can you post your profile here? The only other possibility is that the setting is not being transferred to the DS4Device instance. Transferring the setting is delayed and only takes affect after saving a profile or loading a profile.

**Comment by shogunreaper** [comment]
i got mine at 15 minutes.

if it works on one computer and not another then try doing a fresh install.

**Comment by LaaZa** [comment]
It does get saved in the profile properly as it works if I put it under 5 min and I can see it in the file if I export. I noticed however that when the disconnect happens at 5 min when the setting is higher than that there is no message that the disconnect happened because of the idle disconnect setting, so I belive it is disconnecting for some other reason which just happens to be 5 minutes. Could there be some setting in windows that causes this? I just recently started using DS4Windows and I was on the move so I used it on my laptop first which has built in bluetooth and for my desktop I just got this new usb bluetooth dongle so I have not tested it for other things yet.

**Comment by LaaZa** [comment]
Okay I think I found the culprit. Steam's controller settings(which I had not previously even looked at) had idle disconnect setting set to 5 minutes, I changed it to never and now DS4Windows' idle disconnect works as expected. Can I somehow disable steam's controller support completely because it seems to cause issues?

**Comment by Ryochan7** [comment]
Disabling Steam's DS4 integration can be done in Big Picture Mode under Settings > Controller > Controller Settings > PS4 Controller Support. Any DS4 controllers that are plugged in at the time will have to be unplugged in order for the setting to take affect. I play with Steam's DS4 support every once in a while but I don't use it outside of testing. There are a lot of good mapping options but I don't like the responsiveness of the controls.

**Comment by LaaZa** [comment]
I have that setting disabled so maybe the timeout setting still works regardless :/
Kind of annoying but I guess it's fine now.
