### ISSUE TITLE
Rumble Motors Reversed

### ISSUE THREAD

**Issue by tremendoza** [Ryochan7/DS4Windows#621]
It's as the title says, Left and Right Motors are Reversed when output via Xinput/ViGem. Force Feedback itself works otherwise. Version 1.7.0

**Comment by Ryochan7** [comment]
Confirmed. Found the problem and it is a small parameter mismatch for a method call.

**Comment by Ryochan7** [comment]
It took two versions but this problem has been dealt with entirely. Thank you for bringing up this issue.
