### ISSUE TITLE
Issue with PS4 Pro model (CUH-ZCT2U) on bluetooth

### ISSUE THREAD

**Issue by n0xus** [Ryochan7/DS4Windows#624]
Whenever I connect the newer PS4 Pro model through bluetooth, it connects fine the first time as expected. After powering it off and back on, however, ds4windows nor windows itself detects it in the control panel, and I’m forced to unpair/re-pair it. 

Anyone else experience this? Seems to work fine on USB, which makes me think it’s something to do with my bluetooth adapter? I’m using an older Iogear GBU221 adapter, but it works perfectly for the first gen DS4 model controllers. 

Apologies if this isn’t the right place to ask, as the problem may not be related to ds4windows itself, I just figured I’d get a quality answer here over somewhere else. Thanks in advance.

**Comment by Ryochan7** [comment]
I used to have a similar problem on Windows 7. If the controller was disconnected for more than 5 seconds then it refused to re-connect until I removed the old paired device and re-paired the controller to my BT adapter. Those BT problems don't happen to me anymore for some reason. I think I was using my current BT adapter when I experienced those problems.

Unfortunately, there is nothing that can be done in DS4Windows to fix the issue. That is more an issue with the Windows Bluetooth stack.

**Comment by Corrodias** [comment]
I was experiencing something similar. It would sometimes take multiple attempts to connect and/or not be recognized, and sometimes it'd just refuse to connect at all unless re-paired. I am now using an intelligent adapter (Titan Two) that handles the BT communication, among other things. It is a much smoother experience, but I wouldn't suggest getting it _just_ for that purpose, as it's rather expensive.

**Comment by Ryochan7** [comment]
I finally got a chance to test this again. Both of my adapters work fine with both of my controllers. Disconnecting and re-connecting work fine now. I don't know why it would not have worked in Windows 7 before.

**Comment by Ryochan7** [comment]
I can replicate this type of behavior in a VM installation of Windows 7 using my current BT adapter. I would consider that an edge case though.

**Comment by n0xus** [comment]
I figured out that my problem was indeed my BT adapter. After ordering a Rosewill RNX-BT402 I no longer have the problem - controller detects and connects just fine. Thanks for the info and for maintaining DS4Windows! I’ll close this issue now.
