### ISSUE TITLE
Battery doesn't update on controller connection

### ISSUE THREAD

**Issue by dem0z** [Ryochan7/DS4Windows#626]
Not really an issue but i noticed once i connect my DS4 it always shows 100% battery even though it's not at a 100%. 
Seems to be it's only updating that percentage when the controller drops another precent and triggers like an update which is odd, Why doesn't it detect the actual percentage from the get go just curious.

**Comment by Ryochan7** [comment]
The battery level range reported by the DS4 is not that large. The range of values reported from a BT controller range from 0 - 8 and the values from a USB controller range from 0 - 11. The battery level has to go down a certain percentage before the new value will be reported by the controller which would then be displayed in the application.

**Comment by dem0z** [comment]
Thanks that makes sense :)
