### ISSUE TITLE
Could not connect to ViGemBus.

### ISSUE THREAD

**Issue by microdood** [Ryochan7/DS4Windows#627]
I installed latest version of ViGem drivers but it fails to work on my PC. It says that drivers don't have signature (Error Code 52) in Device Manager. Previously I used Jays2Kings's version and I deleted all stuff affiliated to this version (ScpDriver, main folder etc.). I'm using Win7 and ds4 ver.1.

**Comment by SiTWulf** [comment]
Try to use [HidGuardian Test Installer](https://github.com/Ryochan7/DS4Windows/wiki/DS4Windows-and-HIDGuardian-Install-and-Setup-Guide#hidguardian-test-installer) to install the lastest version of ViGEmBus.
The same installer can uninstall ViGEmBus and reinstall.

**Comment by microdood** [comment]
I don't have issues with downloading latest version of ViGem driver (I have 1.14.3.0 too) it's just my system refuses to accept this driver and tells me the driver isn't signed (not approved by microsoft). Hence DS4W can't connect to the driver :( BTW I tried to use your test installer and I had to use recovery point cuz my mouse and keyboard stopped working after reboot. Seems like I need to force my os boot in 'no driver signature enforcement' mode to 'fix' it.

**Comment by Ryochan7** [comment]
On my native install of Windows 7, it seems like the certificate is not recognized so a warning does come up while installing ViGEmBus. The bus device in the Device Manager also states that the driver is supposedly not digitally signed for some reason. I don't have driver signature enforcement disabled in that installation of Windows but the ViGEmBus driver works on my end. I guess you could try to enable Test Mode in Windows and disable driver signature enforcement and see if DS4Windows can connect to ViGEmBus then.

**Comment by Ryochan7** [comment]
Entering these commands in an Administrator level command prompt should take care of that. Mae sure to reboot afterwards.

```
bcdedit -set loadoptions DDISABLE_INTEGRITY_CHECKS
bcdedit -set TESTSIGNING ON
```

https://gist.github.com/cdwilson/1427923

**Comment by microdood** [comment]
Do you mean that you have a 'not-signed-driver' warning but DS4W still connects to ViGem driver? It does connect to driver when I disable signature enforcement but another issue comes up for me - I can't play Apex while no signature mode is enabled D: (Easy anti cheat says nope). Guess I'd need to manually disable enforcement every time I want to use DS4W.

**Comment by Ryochan7** [comment]
The warning dialog happens during the installation process. I select the option to have the install proceed and the driver will install successfully. DS4Windows will then be able to connect to ViGEmBus after that. I can post a screenshot of the warning in a bit.

Apex Legends checks for that setting? That is a check for anti-cheat software that I had not run across. That would have really hampered my use of vmulti when I had to customize that driver. That driver was used to work around games that blocked SendInput calls from working in game. A new ViGEmBus driver should be released soon and it should be signed differently than previous versions of the driver.

**Comment by mika-n** [comment]
Win7 has problems with certain signed drivers (or Win7 has a bug). Try to go through following web pages and make sure you have installed Win7 hotfixes to workaround signing issues.
https://docs.microsoft.com/en-us/security-updates/SecurityAdvisories/2015/3033929
https://docs.vigem.org/#!vigem-bus-driver-installation.md

**Comment by Ryochan7** [comment]
Warning dialog

![vigembuswarn](https://user-images.githubusercontent.com/581968/54979401-0ed13080-4f71-11e9-8e23-ea0cf4cdfeb2.png)

Device Manager info about driver

![vigembusunsigned](https://user-images.githubusercontent.com/581968/54979434-201a3d00-4f71-11e9-977e-745000068178.png)

**Comment by microdood** [comment]
> Win7 has problems with certain signed drivers (or Win7 has a bug). Try to go through following web pages and make sure you have installed Win7 hotfixes to workaround signing issues.
> https://docs.microsoft.com/en-us/security-updates/SecurityAdvisories/2015/3033929
> https://docs.vigem.org/#!vigem-bus-driver-installation.md

I installed the hotfix and it got hotfixed! Thank you my man! I recently tried to install couple of different hotfixes for windows and it took no effect but this one worked. You're MVP.

**Comment by Ryochan7** [comment]
That's good. I don't know if I have that Windows 7 hotfix but I probably don't.
