### ISSUE TITLE
Another "Warning: Could not open DS4..." Issue

### ISSUE THREAD

**Issue by JackRubino** [Ryochan7/DS4Windows#628]
I'm using the latest version, yesterday it worked no problem. Today i had to stop the micrososft store app but then it worked fine, but now (after I turned off and back on my pc) I can't manage to get it working again. I even uninstalled the microsoft store app, stopped the only nvidia service I have (I DO NOT have geforce experience, which is the one that is known to cause issues, but i tried nonetheless), don't have any steam process open, never even had netflix or uplay installed in this PC, so I have no idea of what's causing the issue. I tried everything I could find on google, and even then the vast majority is people having the problem caused by geforce experience. I just can't understand what's wrong, since it did work earlier. No new softwares were installed, no new hardwares either. Any idea?

**Comment by mika-n** [comment]
See the following post and discussion about how to find out which apps are hold an open handle to DS4 controller.
https://github.com/Ryochan7/DS4Windows/issues/573#issuecomment-462189394
