### ISSUE TITLE
Similar Issue and some requests.

### ISSUE THREAD

**Issue by HadesIzanami** [Ryochan7/DS4Windows#630]
![Captura](https://user-images.githubusercontent.com/42960801/54877558-d3562b00-4de5-11e9-80f4-e71fbb241fc1.PNG)

I have found that, when I select the color in pick color "Empty" a previous one is not shown, same error that happened in the part of the function "Flash At" but that is corrected, thanks @Ryochan7 .

About my requests, one, to add a color pick in the "Full" section to personalize colors more easily. Two, that when the color is changed in "Empty" and "Full" that a combination is not shown, that the colors are totally dependent, this may be confusing for some, it may not be for others, but I want to understand that the function works like that, I explain, when I choose the red color in "empty" and then I choose the green in "full" the colors are not shown independently, this shows a combination of both. And the last one, that in the function of "While charging" in "Pulse" you can add a customizable color. Is all thanks.

PS: Thanks to @Ryochan7 for this amazing job.

**Comment by mika-n** [comment]
there has been some tweaks in lightbar GUI in the latest releases
