### ISSUE TITLE
Issue on DS4 windows

### ISSUE THREAD

**Issue by jpiccini422** [Ryochan7/DS4Windows#634]
Once I connect my controller and select a profile, my computer starts to do things on its own, for example if i was to go and make my volume louder it will automatically start making the volume increase and decrease. If you need a better explanation I can try to get a video of what it does. Thanks

**Comment by Ryochan7** [comment]
The first thing that I need is a copy of the profile you are using.

**Comment by jpiccini422** [comment]
[MW2_PC.zip](https://github.com/Ryochan7/DS4Windows/files/3006001/MW2_PC.zip)

**Comment by mika-n** [comment]
What is the version of DS4Win you are using? One place to see this is Logs tabpage in DS4Win options screen.

The profile file doesn't have all the latest options, so it implies that you are using some old version of DS4Win app or maybe even JayKing edition and not the one in this github repository?

**Comment by Ryochan7** [comment]
It is a dead zone problem. Using 0 dead zone for LS and RS only works when emulating an Xbox 360 controller; it isn't an optimal setting anyway. If you want to emulate KB+M events then you have to set a dead zone. For LS, I prefer around 10% but for RS I keep it low at about 2% or 3% when emulating a mouse. Also, I noticed that you have some controls mapped to gyro tilt controls. 25% dead zone might work fine in some cases but maybe you would want to increase the dead zone for the gyro so a larger tilt is required to activate those controls.

**Comment by jpiccini422** [comment]
Ok I will have to give that try, I will create a profile from scratch and is it possible to leave the gyro controls unassigned/unbound? Version I am using is 1.7.2.

**Comment by Ryochan7** [comment]
Older versions of DS4Windows had implicit dead zones in the code but I removed almost all those a long time ago. Implicit dead zones can be confusing and they take control away from the user. In the future, output modes, like what are used in Steam or SC Controller, can be used to create better defaults depending on which output is being mapped.

**Comment by jpiccini422** [comment]
I have tried setting the dead zone accordingly, but I still have strange inputs on my computer making it virtually impossible to use, I have tried two DS4 controllers and receive the same end result. Not sure what else I can try.

**Comment by Ryochan7** [comment]
I would assume that gyro tilt controls are still being activated. Try setting a very high dead zone for Sixaxis X and Sixaxis Z like 75%. Either that or try unbinding the gyro tilt controls. Unbound or Default will work for that purpose.
