### ISSUE TITLE
Could not connect to ViGEmBus

### ISSUE THREAD

**Issue by Kalio83** [Ryochan7/DS4Windows#635]
I keep getting this error even though the driver is installed and shows no problems in device manager.  I even tried using the driver installer test utility. I can uninstall and re-install the driver with no problems, there is absolutely nothing to indicate any kind of problem but yet I keep getting this error and my controller is not working. Tried rebooting, removing my controller, everything I can think of.

Screenshot:
https://imgur.com/PhhCKcR

Forgot to mention this is Windows 10 64-bit.

**Comment by Pirricli** [comment]
Try to execute the ds4windows.exe as administrator (right clic in your mouse). I had the same problem and it worked.

**Comment by Kalio83** [comment]
I tried that too, actually I pretty much always run it as admin.

**Comment by Ryochan7** [comment]
Can you share the log? Also, running DS4Windows as a normal user works fine so that should not be a factor.

**Comment by Ryochan7** [comment]
Testing has shown that the Visual C++ 2017 Redistributable package is required to be installed on your system to use the bundled ViGEmClient library. Check if the package is already installed and download the appropriate architecture version if it is not installed.

https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by Kalio83** [comment]
I could not find any log from DS4Windows, unless there is a way to enable logging?
The only log I could find is from when I use ViGEmBusInstaller. This log is just me uninstalling and reinstalling it again:

3/28/2019 10:18:24 AM: Checking if ViGEmBus is already installed
3/28/2019 10:18:24 AM: ViGEmBus is already installed
3/28/2019 10:18:27 AM: Start Uninstalling ViGEmBus
3/28/2019 10:18:27 AM: Removing Virtual Gamepad Emulation Bus Device
3/28/2019 10:18:27 AM: Removing ViGEmBus driver from driver store
3/28/2019 10:18:27 AM: Finished

3/28/2019 10:18:30 AM: Start ViGEmBus install
3/28/2019 10:18:30 AM: Start downloading ViGEmBus archive
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 0%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 1%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 1%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 2%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 2%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 3%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 3%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 4%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 4%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 5%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 5%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 6%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 6%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 7%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 7%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 8%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 8%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 9%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 9%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 10%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 10%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 11%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 11%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 12%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 12%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 13%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 13%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 14%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 14%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 15%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 15%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 16%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 16%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 17%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 17%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 18%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 18%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 19%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 20%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 20%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 21%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 21%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 22%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 22%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 23%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 23%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 24%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 24%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 25%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 25%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 26%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 26%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 27%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 27%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 28%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 28%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 29%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 29%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 30%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 30%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 31%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 31%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 32%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 32%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 33%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 33%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 34%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 34%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 35%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 35%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 36%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 36%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 37%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 37%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 38%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 39%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 39%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 40%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 40%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 41%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 41%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 42%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 42%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 43%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 43%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 44%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 44%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 45%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 45%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 46%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 46%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 47%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 47%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 48%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 48%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 49%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 49%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 50%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 50%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 51%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 51%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 52%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 52%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 53%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 53%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 54%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 54%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 55%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 55%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 56%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 56%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 57%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 58%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 58%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 59%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 59%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 60%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 60%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 61%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 61%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 62%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 62%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 63%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 63%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 64%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 64%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 65%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 65%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 66%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 66%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 67%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 67%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 68%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 68%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 69%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 69%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 70%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 70%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 71%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 71%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 72%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 72%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 73%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 73%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 74%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 74%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 75%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 75%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 76%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 77%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 77%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 78%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 78%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 79%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 79%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 80%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 80%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 81%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 81%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 82%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 82%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 83%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 83%
3/28/2019 10:18:31 AM: Downloading ViGEmBus: 84%
3/28/2019 10:18:32 AM: Downloading ViGEmBus: 84%
3/28/2019 10:18:32 AM: Downloading ViGEmBus: 85%
3/28/2019 10:18:32 AM: Downloading ViGEmBus: 85%
3/28/2019 10:18:32 AM: Downloading ViGEmBus: 86%
3/28/2019 10:18:32 AM: Downloading ViGEmBus: 86%
3/28/2019 10:18:32 AM: Downloading ViGEmBus: 87%
3/28/2019 10:18:32 AM: Downloading ViGEmBus: 87%
3/28/2019 10:18:32 AM: Downloading ViGEmBus: 88%
3/28/2019 10:18:32 AM: Downloading ViGEmBus: 88%
3/28/2019 10:18:32 AM: Downloading ViGEmBus: 89%
3/28/2019 10:18:32 AM: Downloading ViGEmBus: 89%
3/28/2019 10:18:32 AM: Downloading ViGEmBus: 90%
3/28/2019 10:18:32 AM: Downloading ViGEmBus: 90%
3/28/2019 10:18:32 AM: Downloading ViGEmBus: 91%
3/28/2019 10:18:32 AM: Downloading ViGEmBus: 91%
3/28/2019 10:18:32 AM: Downloading ViGEmBus: 92%
3/28/2019 10:18:32 AM: Downloading ViGEmBus: 92%
3/28/2019 10:18:32 AM: Downloading ViGEmBus: 93%
3/28/2019 10:18:32 AM: Downloading ViGEmBus: 93%
3/28/2019 10:18:32 AM: Downloading ViGEmBus: 94%
3/28/2019 10:18:32 AM: Downloading ViGEmBus: 94%
3/28/2019 10:18:32 AM: Downloading ViGEmBus: 95%
3/28/2019 10:18:32 AM: Downloading ViGEmBus: 95%
3/28/2019 10:18:32 AM: Downloading ViGEmBus: 96%
3/28/2019 10:18:32 AM: Downloading ViGEmBus: 97%
3/28/2019 10:18:32 AM: Downloading ViGEmBus: 97%
3/28/2019 10:18:32 AM: Downloading ViGEmBus: 98%
3/28/2019 10:18:32 AM: Downloading ViGEmBus: 98%
3/28/2019 10:18:32 AM: Downloading ViGEmBus: 99%
3/28/2019 10:18:32 AM: Downloading ViGEmBus: 99%
3/28/2019 10:18:32 AM: Downloading ViGEmBus: 100%
3/28/2019 10:18:32 AM: Downloading ViGEmBus: 100%
3/28/2019 10:18:32 AM: Creating Virtual Gamepad Emulation Bus Device
3/28/2019 10:18:32 AM: Installing ViGEmBus Driver
3/28/2019 10:18:32 AM: Installing driver from C:\Other\DS4Windows\ViGEmBusInstaller\ViGEmBus\x64\ViGEmBus.inf
3/28/2019 10:18:32 AM: ViGEmBus is now installed

**Comment by Kalio83** [comment]
> 
> 
> Testing has shown that the Visual C++ 2017 Redistributable package is required to be installed on your system to use the bundled ViGEmClient library. Check if the package is already installed and download the appropriate architecture version if it is not installed.
> 
> https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

This worked for me thank you! I installed both the x86 and x64 version just in case but I suspect only the x64 version was needed (since that is what I'm using).

**Comment by Ryochan7** [comment]
It depends on which build of DS4Windows you are using. Most people would end up needing the x64 version of that package. Not many people use the x86 build of DS4Windows.
