### ISSUE TITLE
Right Stick not working

### ISSUE THREAD

**Issue by doctorapple** [Ryochan7/DS4Windows#641]
Hi Ryochan, I just recently updated DS4Windows to the lastest version (v1.7.2). But in any games, my right stick (to rotate camera) doesn't work. I even disabled controller support from Steam and it still doesn't work. I checked in Controller Readings and the Right Stick was still receiving feedback though.

Reinstalling version 1.6.14 and the right stick works as usual. I wonder if this is because of the change of driver from Scp Virtual to the newer one?

**Comment by Corrodias** [comment]
Can you think of any reason your system or your configuration would be different from others'? The right stick definitely works on mine. Include your operating system and whether it's the 32 or 64 bit version.

**Comment by mika-n** [comment]
Try using a new default profile to verify that your existing profile is not a problem.

Can you see activity in right stick in Windows gamepad configuration screen? Run "joy.cpl" command to open the gamepad ControlPanel app.

Do you have Oculus apps installed? Those may have a rip-off version of ViGemBus device driver and it may cause problems with more recent versions of the official ViGemBus drivers.  https://github.com/Ryochan7/DS4Windows/issues/443#issuecomment-475770257

**Comment by doctorapple** [comment]
Well, I'm still using the same Windows 10 64 bit installation with though.

New profile doesn't work. Right stick doesn't have any activity in the Windows gamepad configuration screen while using DS4Windows.

I also don't have Oculus apps installed because...I don't have the VR kit. :D

**Comment by Ryochan7** [comment]
Normal default RS bindings and remapped inverted RS bindings work for me. I don't think that should be any reason why RS mapping would work in 1.6.14 but not in 1.7.0 when using the same profile.

**Comment by Ryochan7** [comment]
Closing due to lack of feedback

**Comment by doctorapple** [comment]
Hi Ryochan7,

I updated DS4Windows to 1.7.3 and the right stick is working now. I even uninstalled ScpDriver and the right stick is responsive in the calibration option of Windows. Looking forward to the next update.
