### ISSUE TITLE
DS4 not connecting to bluetooth after the update....

### ISSUE THREAD

**Issue by brothan323** [Ryochan7/DS4Windows#644]
God damn.......This program is a frustrating mess. Every time I try to connect the bluetooth to the dongle windows will try and fail to install the bluetooth HID driver.

**Comment by brothan323** [comment]
And yes, moving to Version 1.6.14 works flawlessly. So it's the new driver you've added. It does something to Windows 7/bluetooth pairing.

**Comment by mika-n** [comment]
Have you done the required steps to make the new virtual gamepad driver (ViGem) compatible with Win7?  
https://github.com/Ryochan7/DS4Windows/wiki/DS4Windows-and-HIDGuardian-Install-and-Setup-Guide#windows-7-and-vigem-virtual-gamepad-driver-compatibility-fix

**Comment by Ryochan7** [comment]
If that is the case then there isn't much I can do about it. If the problem does exist outside of DS4Windows, you might want to send a report to Nefarius to crack this issue. He is probably going to need to know what BT adapter and possibly BT stack you are using.

https://github.com/ViGEm/ViGEmBus

BT pairing works fine for me and my two BT adapters even on Windows 7.

**Comment by Ryochan7** [comment]
I experienced something similar recently in Windows 7. It worked out fine though. Windows was just being weird that one time with the BT driver. I am going to count this as a Windows fluke so it is likely unrelated to anything in ViGEmBus.
