### ISSUE TITLE
Analog sticks stuck on key no matter what

### ISSUE THREAD

**Issue by jsaue003** [Ryochan7/DS4Windows#648]
I've been using DS4Windows_1.7.3, and mapped the left Analog stick to W, S, A, D for movement in an MMO. However, testing the controller setup in notepad, it spams wwwwwwwwwwwwaaaaaaaawwwwwww when I'm not moving the analog stick at all! Is this a bug or something ? No matter what I try, even a macro for just 'w' it spams it without the stick even moving at all. It's horribly broken...

**Comment by mika-n** [comment]
Maybe you need to set a bigger deadzone to left stick axies?  Remember that those analog sticks are hardly never completely stable, so those keep on sending slight movement data packets. If you use sticks to send out keyboard commands then the result may be just what you described unless you set a big enough deadzones in DS4Win left-stick axies settings.

**Comment by Ryochan7** [comment]
That sounds like a dead zone problem. You have to set some form of dead zone for LS and RS when mapping to KB or Mouse. It will be rare when the sticks will center back at exactly 128. While emulating an Xbox 360 controller, it usually won't matter due to the game's set dead zones for the sticks. That would roughly be around 8,000 (25% range) in XInput coordinates.

**Comment by jsaue003** [comment]
@mika-n and @Ryochan7 Thank you both for the answers. That makes perfect sense now. Are there recommended values or levels for the dead zones? Additionally, where is the setting? Thanks again for the quick response.

**Comment by Ryochan7** [comment]
Dead zone options are available in the profile editor. Other related options such as Anti-Deadzone and Max Zone are available to be able to tweak the responsiveness of the analog sticks. The recommended values depend on the game and whether you are emulating a controller or KB+M. Here are some typical values I use.

**XInput**
```
LS Deadzone: 0.10
LS Anti-Deadzone: 0.18
LS Max Zone: 1.0

RS Deadzone: 0.08
RS Anti-Deadzone: 0.20
RS Max Zone: 1.0
```

**KB+M**
```
LS Deadzone: 0.10
LS Anti-Deadzone: 0.0
LS Max Zone: 1.0

RS Deadzone: 0.02
RS Anti-Deadzone: 0.0
RS Max Zone: 0.9
RS Output Curve: Enhanced Precision
```

The low dead zone for RS in the KB+M config will cause some minor mouse drift that can be compensated but the looseness of the stick is worth it.
