### ISSUE TITLE
Controller not detected

### ISSUE THREAD

**Issue by CloudLouis** [Ryochan7/DS4Windows#649]
DS4Windows won't detect  my controller even though it's properly installed in my windows (it is listed as PS4 Fun Controller in device list and is also set as preferred in the USB Game Controller setting) and works perfectly when used through Steam. I've tried everything I can find, but it simply can't be detected by DS4Windows.
Also, I'm using this controller https://www.gamestop.de/PS4/Games/46480
GameStop in-house brand wired controller. Supposedly officially licensed.
Thanks in advance if anyone can help me

**Comment by Ryochan7** [comment]
There is minimal support for non-Sony branded DS4 controllers in DS4Windows. I don't see that controller listed as a DS4 on Steam's official supported controllers database either. I am guessing that Steam will just use it as a generic DirectInput controller.

https://support.steampowered.com/kb_article.php?ref=5199-TOKV-4426

The first order of business would be that I would need the Hardware Ids given for that controller as displayed from the Windows Device Manager.

**Comment by CloudLouis** [comment]
> There is minimal support for non-Sony branded DS4 controllers in DS4Windows. I don't see that controller listed as a DS4 on Steam's official supported controllers database either. I am guessing that Steam will just use it as a generic DirectInput controller.
> 
> https://support.steampowered.com/kb_article.php?ref=5199-TOKV-4426
> 
> The first order of business would be that I would need the Hardware Ids given for that controller as displayed from the Windows Device Manager.

Thanks for the response, sorry about the late reply. Here's the hardware ID from the device manager 
![image](https://user-images.githubusercontent.com/33645812/56080659-0b102b80-5e04-11e9-9362-95017d46956e.png)

**Comment by Ryochan7** [comment]
Test build

https://drive.google.com/open?id=1PXF2xs5qq4AIyhtx6CZRGKzUt56RcUws

**Comment by CloudLouis** [comment]
> Test build
> 
> https://drive.google.com/open?id=1PXF2xs5qq4AIyhtx6CZRGKzUt56RcUws

Thanks again for the help. I've tried the test build out, and it works well. Detected the controller, every button responsive and all. Haven't extensively test it out, though it doesn't look anything will go wrong so far

**Comment by Ryochan7** [comment]
Cool. I will get that change added to the repository.
