### ISSUE TITLE
[Feature Request] Option to keep the Virtual X360 Controller connected when the DualShock 4 is disconnected for a short period

### ISSUE THREAD

**Issue by RibShark** [Ryochan7/DS4Windows#65]
The USB connector on my DualShock 4 is a bit loose so sometimes when playing the controller will be disconnected. Some games permanently disable Gamepad input when it detects this. If an option was added where the X360 controller would only be disconnected after, say, 5 seconds of the DualShock 4 being disconnected, this would solve that issue.

**Comment by Ryochan7** [comment]
That is like the current state of my nearly broken Xbox 360 controller. Without using tape to hold the wire fairly steady, the controller tends to occasionally disconnect and it is annoying to try to use it anymore.

As for adding a delayed disconnect feature into DS4Windows, there are some parts of the device unplug code that could present a problem. I might look into this at some point.

**Comment by shinra358** [comment]
Sounds like a cool feature. If it ever gets worked out, I'd like to be able to edit the delay in the program. This would also help with games with poor afterplugging support.

**Comment by scrumpyman** [comment]
I was about to write exactly this request. The micro usb connection issue seems pretty common, and makes some games unplayable. I tried changing the wire but it's really the fault of the port on the controller. Also tried getting it connected on bluetooth but that doesn't work at all.

In any case, if this feature is possible, it would be a great addition to the program.

**Comment by SacredAngelBob** [comment]
I've been trying to find a makeshift way to keep the XInput slots connected at all times, but to no avail so far. This feature would really help me out.

**Comment by mika-n** [comment]
the latest version of ds4windows has a new "persistent slot" feature which probably does this
