### ISSUE TITLE
latency problem

### ISSUE THREAD

**Issue by imGlox** [Ryochan7/DS4Windows#650]
Hey,
I got a new DS4 controller today and noticed whilst playing Sekiro that my latency would spike to over 10ms (red warning in the log) a few times then my controller would sometimes disconnect as a result.
I reinstalled drivers, formatted my computer etc, checked the cables but considering that my other DS4 controller works perfectly fine with the same cables, I assume they're not the problem.

any ideas to what could be causing it?
thanks in advance.

**Comment by mika-n** [comment]
Is it an official Sony DS4 controller or some 3rd party compatible controller? 

Do you have a bluetooth capable PC/laptop or BT dongle? How it works over BT? Some people have reported that DS4 latency is actually smaller over BT than USB.

**Comment by imGlox** [comment]
> 
> 
> Is it an official Sony DS4 controller or some 3rd party compatible controller?
> 
> Do you have a bluetooth capable PC/laptop or BT dongle? How it works over BT? Some people have reported that DS4 latency is actually smaller over BT than USB.
> 
> Take a look at this issue discussion in Jays2Kings repository (it is the original but now obsolete old version of the Ryochan7 DS4Win fork):
> [Jays2Kings#62](https://github.com/Jays2Kings/DS4Windows/issues/62)

It is an official Sony controller.
My PC doesn't have bluetooth functionality installed so that'd require me to buy a dongle.
I have tried the solutions that are relevant to me in said previous discussion and they don't seem to work.
I have also noticed that in Device Manager under "Sound, video and game controllers" that my Wireless Controller has a yellow error triangle. Trying to update the driver results in an error message (10) saying it can't start it up.
Thanks.

**Comment by Ryochan7** [comment]
The entry listed under "Sound, video and game controllers" would correspond to the exposed audio device for the DS4 headphone jack. The game controller would be listed under "Human Interface Devices" as **HID-compliant game controller**; you will have to check in the Properties if multiple devices are listed.

Especially with the problem that you posted, I would suggest that you uninstall both devices and attempt to have Windows set them up again. After that, you might want to check your power management settings and make sure the USB ports are not being underpowered. I use the Full Performance power plan but I think another option is to disable the option "Allow the computer to turn off this device to save power" under USB Root Hub > Power Management for each entry listed in the Device Manager.

Under normal circumstances, Input delay should be fairly close to 4 ms while wired unless your system is being over taxed.

**Comment by imGlox** [comment]
> 
> 
> The entry listed under "Sound, video and game controllers" would correspond to the exposed audio device for the DS4 headphone jack. The game controller would be listed under "Human Interface Devices" as **HID-compliant game controller**; you will have to check in the Properties if multiple devices are listed.
> 
> Especially with the problem that you posted, I would suggest that you uninstall both devices and attempt to have Windows set them up again. After that, you might want to check your power management settings and make sure the USB ports are not being underpowered. I use the Full Performance power plan but I think another option is to disable the option "Allow the computer to turn off this device to save power" under USB Root Hub > Power Management for each entry listed in the Device Manager.
> 
> Under normal circumstances, Input delay should be fairly close to 4 ms while wired unless your system is being over taxed.
I see. either way the ds4 headphone jack driver had a yellow triangle on it which prompted me to update its drivers but whilst doing so I would get an error 10 saying it can't start it up.
I also unchecked said option from each USB Root Hub.

However, I am glad to say I managed to fix the problem (I think) - I usually use my front case's USB ports and I figured why not try the back one to see if it works and to my surprise - it did! no latency error in DS4Windows, no yellow error triangle on the DS4's sound driver in Device Manager and controller seems to work great.
I read somewhere that this might be because the PC gives less power to the front ports in comparison to the back one's so if that's true, that's also my solution.

thanks for the help!

**Comment by Ryochan7** [comment]
Thank you for the update. I will have to keep that in mind if people post this type of latency issue in the future. I typically use my tower's top USB ports and I have not run into a problem like that before.
