### ISSUE TITLE
Left Stick cannot reach max boundaries

### ISSUE THREAD

**Issue by SocalMojo** [Ryochan7/DS4Windows#652]
If you look at the picture attached, my LS has two dots, one grey and one black. The grey dot seems to reflect the constraint of movement of the LS. This is with the Default profile. RS has only one black dot. How to fix? Thx.

![LS](https://user-images.githubusercontent.com/49431986/55783085-83709880-5a62-11e9-9e77-43aa4ca7bb9b.png)

**Comment by Ryochan7** [comment]
The black dot represents the raw input position read from the controller. The grey dot represents the output position after dead zone, sensitivity, and other mapping options are taken into account. If the Default profile has not been changed, the grey dot should not be visible as the black dot would cover it. RS is completely centered so the block dot will render over the grey dot.

**Comment by SocalMojo** [comment]
It turns out my sensitivity was changed from the default. I had deleted all profiles and re-created Default, but the old sensitivity value was still stuck in. Thanks for your help!
