### ISSUE TITLE
DS4 / SCUF VANTAGE

### ISSUE THREAD

**Issue by stfuindy** [Ryochan7/DS4Windows#653]
Hey,

I'm trying to get my Scuf Vantage to work for PC. I saw that you said you don't have one so it's hard to support it.

But my Scuf is getting picked up by my PC but it keeps getting picked up as an audio device when wired. DS4 won't pick it up at all. Any tips?

**Comment by Ryochan7** [comment]
Is the controller visible in the Windows Device Manager? The corresponding **HID-compliant game controller** would need to be detected in order to have any luck in getting DS4Windows to see the controller.

**Comment by stfuindy** [comment]
It is visible in the windows device manager but it naturally shows up as an audio device.

**Comment by mika-n** [comment]
> It is visible in the windows device manager but it naturally shows up as an audio device.

Does this mean that it still works as a directInput gamepad controller in Windows10 even when it is listed under audio devices? Or that it doesn't work even without DS4Windows application?

Run "joy.cpl" Joystick/Gamepad controlPanel applet (Start menu and Run...) without running DS4Windows application and HidGuardian filter drivers (if installed).  Do you see the gamepad device in Joy.cpl tool and does it recognize button events and left/right stick movement?

If you don't see the ScufVantage gamepad device in joy.cpl controlPanel applet then there is not much DS4Windows app can do about it if Win operating system doesn't recognize it in the first place.
