### ISSUE TITLE
Controller not found

### ISSUE THREAD

**Issue by nicsman** [Ryochan7/DS4Windows#656]
My controller is a non sony branded dualshock 4 controller. So does it affect the software? It will work on steam but not other softwares

**Comment by mika-n** [comment]
3rd party "compatible DS4" controllers don't work out of the box with DS4Win app if those have a different different device identifiers than any of the currently supported devices (VID/PID prperty values and devie name/description values in device manager behind the device).

Take a look at this dicussion for more info and provide screenshot of your DeviceManager VID/PID/name/description fields (or copy paste here).
https://github.com/Ryochan7/DS4Windows/issues/580

**Comment by Ryochan7** [comment]
Support for non-Sony branded third party controllers has to be done on a per case basis. There are only a few third party controllers that have any form of community support. The first step to getting any support is obtaining some information about the controller. The type of controller that you are using as well as the Hardware Ids as displayed in the Windows Device Manager (VID and PID info). A test build would be made that you could then test and confirm whether it worked.

**Comment by nicsman** [comment]
![image](https://user-images.githubusercontent.com/49552972/56083074-1fc7e000-5e53-11e9-9c9a-312a65de2a62.png)
this?

**Comment by Ryochan7** [comment]
Okay. Someone else was asking about that same controller as well. Test build

https://drive.google.com/open?id=1PXF2xs5qq4AIyhtx6CZRGKzUt56RcUws

**Comment by nicsman** [comment]
Seems working so far. Thanks

**Comment by Ryochan7** [comment]
Version 1.7.4 has support for the controller. Thank you for the information.
