### ISSUE TITLE
Controller not being detected by DS4 Windows

### ISSUE THREAD

**Issue by MickelLovinit** [Ryochan7/DS4Windows#66]
hey so I downloaded the DS4 windows tool and every time i try and use it, my controller isn't being detected. i can hear the sound that my pc makes to let me know something has beeing connected through a usb port but for some reason the DS4 tool isn't reading my controller and i dont know what to do!!?

**Comment by dem0z** [comment]
Maybe try a different USB port, and make sure the drivers for the DS4 are installed and give it a try.

**Comment by Ryochan7** [comment]
It might be the case of DS4Windows not having the proper VID and PID combination of the controller in the software. Can you provide the VID and PID associated with the controller?

**Comment by MickelLovinit** [comment]
Hey guys sorry it took me a while to respond, I figured it out, we'll sort of, and apparently my PS4 needs to be on so I can turn my controller on and have it read. Thank you so much for your help though!
