### ISSUE TITLE
1.7.3 Vibration is invalid

### ISSUE THREAD

**Issue by qqjp** [Ryochan7/DS4Windows#660]
1.7.3 Vibration failed, the old version is no problem.

**Comment by mika-n** [comment]
Please browse through  at least handful of the latest existing issues before posting new questions. https://github.com/Ryochan7/DS4Windows/issues/651

**Comment by Ryochan7** [comment]
Force feedback support has not worked as intended since version 1.7.0. The problem was due to the ViGEmClient library that is used to interface with ViGEmBus. The problem has been solved but I have not gotten around to packaging a new version of DS4Windows with an updated library yet.

**Comment by qqjp** [comment]
Thank you ！

**Comment by Ryochan7** [comment]
Version 1.7.4 is now out. Force feedback support has been re-enabled.

https://github.com/Ryochan7/DS4Windows/releases/download/v1.7.4/DS4Windows_1.7.4_x64.zip
