### ISSUE TITLE
Force Feedback Issues

### ISSUE THREAD

**Issue by tremendoza** [Ryochan7/DS4Windows#662]
Force feedback either doesn't work, is late or duration is too long.
v1.7.4

**Comment by Newtype14** [comment]
Can confirm that I'm having the same problem (v1.7.4). In my case the force feedback is very long. For example, I fire one bullet and it rumbles for 2 seconds.

**Comment by theoldsport** [comment]
Also can confirm same issue, rolled back to 1.7.3 for now

**Comment by Ryochan7** [comment]
I screwed up carrying over the changes to the ViGEmClient library. A new release should come out shortly with that mistake corrected. Updated the Gist.

https://gist.github.com/Ryochan7/f41bd345c5592d88f37ff24773e1e882

**Comment by Ryochan7** [comment]
Version 1.7.5 is out.

https://github.com/Ryochan7/DS4Windows/releases/download/v1.7.5/DS4Windows_1.7.5_x64.zip

**Comment by theoldsport** [comment]
Lookin good now
