### ISSUE TITLE
"Could not connect to ViGEmBus."

### ISSUE THREAD

**Issue by Noxillio** [Ryochan7/DS4Windows#665]
![image](https://user-images.githubusercontent.com/40806092/56478395-fc1d1f00-647c-11e9-91dc-4eb3b89ef4bc.png)

Status is just fine, I don't understand why I'm getting this message.

**Comment by Noxillio** [comment]
Suddenly works now. No idea what changed or how it's working but it is.

**Comment by Ryochan7** [comment]
The usual culprit is that you do not have the Visual C++ 2017 Redistributable package installed on your system. That package became a mandatory requirement for running DS4Windows starting with version 1.7.0. The package is needed in order for the ViGEmClient library to work.
