### ISSUE TITLE
[Notice] New ViGEm Bus Driver Available. A Wild Welcome Dialog Appears

### ISSUE THREAD

**Issue by Ryochan7** [Ryochan7/DS4Windows#667]
A new version of the ViGEm Bus Driver has been released. It is marked as version 1.16.112. The new driver works better than the previous stable release (1.14.3.0) and installing it is easier since it now has an official installer; there is no need to invoke PowerShell. One compatibility issue that has surfaced is that the exposed Hardware Id of the driver has changed. If you attempt to use the new ViGEm Bus Driver with current DS4Windows then the Welcome Dialog will appear on every launch asking you to install the driver. A temporary fix has been added to the current code but I might want to change how DS4Windows checks for the driver.

https://forums.vigem.org/topic/288/vigem-bus-driver-v1-16-112-released

**Comment by DrConflict** [comment]
I installed the latest ViGEm and have this popup on every boot. 
Any status update on resolving this annoying little issue by any
chance? Cheers.

**Comment by Ryochan7** [comment]
A newer check has been added that checks against the exposed device GUID rather than the Hardware Id. It works for the new and old ViGEm Bus Driver. A new DS4Windows release with the change should be out shortly.

**Comment by Ryochan7** [comment]
Version 1.7.6 fixes this problem. I would encourage people to update to the latest version of the ViGEm Bus Driver.

https://github.com/ViGEm/ViGEmBus/releases/tag/v1.16.112
