### ISSUE TITLE
ds4 not recognized on wake.

### ISSUE THREAD

**Issue by vvilkommen** [Ryochan7/DS4Windows#67]
Windows 10
CUH-ZCT2
Sony DS4 USB wireless adaptor 
ds4windows/r7 1.4.76-80

First, thanks so much for picking this up. You've fixed plenty and made this app so much better (thanks for killing the touchpad+psx touch toggle; it was killing me).

However, I've been having an issue:
In order to conserve battery life, I often turn off my ds4 by holding the psx button for its 15 seconds or so. Starting around 1.4.76 (I haven't tried 75, and if this happened in 74, I think it's rare, in jays2kings main, only the LED color customization lapses, [e.g., LED is default blue until battery level forces an update of the color]), I've had the annoying problem where ds4windows locks up upon waking my ds4. If I try to middle click (or right click -> quit) the systray icon, nothing happens. I usually have to task kill it and restart it. 

Worse, 1.4.80 takes it to the next level: touchpad input recognition will completely cease at random (as if I had pressed touch+psx in jays) necessitating a process explorer task kill. The interesting thing is that although the touchpad does not work, the LED color is still customized.

Trying to figure out how to reliably reproduce, though, for me, hitting stop in the application window usually does the same thing: nothing happens attempting to "start," ds4 will not recognize my ds4.

**Comment by vvilkommen** [comment]
If it's any help, the ds4 task tray icon tooltip informs, (1st line: "DS4Windows v[ersion]") 2nd line: "1: SONYWA 100%1: SONYWA 87%1: SONYWA 75%1:S" At this point, I guess the tooltip runs out of room to display more SONYWA. I'm not sure why more SONYWA is being appended for the same Bluetooth controller running on the same Wireless Adaptor, but that it does. The concatenation of SONYWA + remaining battery % resets to just one on task kill via task man. I'll see if I can correlate SONYWA redundancy with increased likelihood of failure to recognize the ds4 on PSX button resumption. Or something.

(It probably does not make a difference, because these other controllers are not paired (to this, affected computer), but in the same area, there is another computer running a SONY DS4 Wireless Adaptor and a ZCT1U)

Thanks!

**Comment by Ryochan7** [comment]
I am not sure how to address the first issue. I do not experience the problems that you described when using version 1.4.80.

As for the tray icon tooltip problem, that issue was fixed in more recent versions of DS4Windows; the fix was included in version 1.4.83. Refactoring was done to better generate the string used for the tray icon.
