### ISSUE TITLE
Double ds4 on Windows 10

### ISSUE THREAD

**Issue by jinkazama82it** [Ryochan7/DS4Windows#671]
with the introduction of emulated ds4 selectable in profile we have a double ds4 when the ds4 is used with the sonywa, and the emulated ds4 don't react when you press the touch, and at the last in games that support ds4 natively through sonywa they suffer of double input, fuor that game ita notte useful enable the direct input that stop the emulation of any type of controller.
not to mention that in Windows 10 the ds4 emulated sees as a simple wireless controller that is managed by games like an x360... not very useful.

**Comment by mika-n** [comment]
If exclusive mode is not enabled (or it failed at startup) or HidGuardian is not used to hide the physical DS4 controller then you may experience double inputs in a game. In fact the double input issue is pretty much the same with X360 virtual output  device also, but it depends on games how those behave when inputs are reported via two devices at the same time.

I guess you have seen this Wiki page: https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues
