### ISSUE TITLE
DPad Up + DPad Back not recognized in DS4 Mode

### ISSUE THREAD

**Issue by NIoSaT** [Ryochan7/DS4Windows#672]
When I run DS4Windows in DS4-Mode the DPad Up + DPad Left combination is not propperly recognized (just DPad Up).
DPad Up + DPad Right IS recognized correctly (diagonal Input).

In 360-Mode both are recognized correctly.

DS4Windows v1.7.6
Windows 10
Asus BT-400 
DS4 v2

Game: Mortal Kombat 11

**Comment by Ryusennin** [comment]
Do you have a DS4 v1 or v2?

**Comment by NIoSaT** [comment]
I have a DS4 V2 (lightbar on top of the touch panel)

**Comment by mika-n** [comment]
Hmmm.... I tested the DPad Up+Dpad Left key combination and indeed it doesn't work in virtual DS4 controller (physical DS4 does detect it). And all other Dpad "two key" combinations work just fine (except up+down or left+right which is of course not supported in the original controller).  In x360 mode dpad up+left works fine.

There seems to be a bug in the V1.7.6 code where it prepares dPad values in a "report" object to be sent to ViGem virtual driver. If does this a bit differently than in x360 output device.  The DS4OutputDevice dpad logic goes through a certain if-then-else chain now it handles dpadUp+RIght combinationin a way that it no longer handle dpapUp+left combination (it falls through dpadUp state).

Fortunately this is easy to fix and I'm sure the fix will be in the next release.

**Comment by NIoSaT** [comment]
If it wasn't for the MK11 tutorial I would have probably not found it.  

I forked and fixed it, should I open a pull request for that?

**Comment by Ryochan7** [comment]
I ended up already committing a fix for this issue. The fix moves the DPadUp+DPadLeft check to happen earlier.

https://github.com/Ryochan7/DS4Windows/commit/90045f7f50c7d4be8a301729034386442ef2cdb4
