### ISSUE TITLE
other apps take control over my controller after windows wakes up from sleep

### ISSUE THREAD

**Issue by marcmy** [Ryochan7/DS4Windows#674]
Hello, it seems that when I have other apps (eg. steam or winstore.app) running when I put my computer to sleep, I lose exclusive mode from ds4windows after waking up. This usually requires me to either restart my computer or shut down those apps and then restart ds4windows to get it to work again. Is there any work around for this? I've tried HidGuardian but I'm not sure if it was the right version or if I installed it correctly. Thanks in advance.

**Comment by Ryochan7** [comment]
You can check which process is causing the problem using Process Explorer. Some service is probably scanning for devices upon resuming and getting access to the DS4 first.

http://www.imatest.com/2017/01/how-to-determine-what-processes-are-using-a-device/

HidGuardian is the most reliable way of getting exclusive access to the DS4. The easiest way to install HidGuardian is via the test installer. It will configure the block devices list as well.

https://drive.google.com/open?id=1hs6AgM6yLeyr3htP9kY0T4N2vklRI2s9

**Comment by marcmy** [comment]
Thank you, process explorer confirmed it was steam.exe, but unfortunately I need to keep this open as I play many games through steam. I'll give the HidGuardian test installer a go. Thanks for all your work!

**Comment by RaydenX93** [comment]
We all do, however you can still get exclusive mode. Follow this guide: https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

**Comment by marcmy** [comment]
HidGaurdian did the trick perfectly. I don't seem to have any issues now, except that I have to constantly recalibrate and re-set my controller settings in game, but that could also be because I'm disconnecting it and switching to bluetooth, using it on android, etc.

**Comment by Ryochan7** [comment]
The DS4 can only re-connect to the most recently connected device. Switching from devices will require removing an old reference, if one exists, and then re-pairing to the system.  That also happens if you boot between various operating systems. This is one thing that the Sony Wireless Adapter helps make easier. Since the connection is independent of the computer and OS, I can more easily switch test targets using a wireless connection.

**Comment by marcmy** [comment]
Ah ok, I see. Thanks again :)
