### ISSUE TITLE
Anyone Having issues with Fortnite

### ISSUE THREAD

**Issue by Demisful** [Ryochan7/DS4Windows#677]
My controller works with every other game but fortnite, i can hear the in game sound telling me i clicked on BR on the start screen but the game never does anything about it. The buttons are all messed up and don't do what they're assigned to, the sensitivity is very high despite me having a low sens in the game settings, sometimes when i click my options menu it rotates the camera to the left. I've tried reinstalling both DS4 windows and Fortnite but it never does anything to fix it. Honestly not sure what the issue is at this point.

**Comment by mika-n** [comment]
Are you using "Hide DS4 Controller" (=exclusive access) option in DS4Windows app options? If you do use that option then what do you see in Logs tabpage of DS4Win options screen? Any warning messages about failing to acquire an exclusive access to the physical DS4 controller device?

Maybe you are experiencing "double input" issue where the game sees both the physical DS4Controller device and the virtual re-mapped gamepad controller (either X360 virtual or DS4 virtual controller depending on the virtual controller output mode in DS4Win options).

See this wiki page: https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

**Comment by Ryochan7** [comment]
The general advice has already been given. I refuse to give Fortnite a try as I am now pretty much boycotting anything new from Epic Games. There isn't much else to discuss so I am closing this issue.
