### ISSUE TITLE
[Feature Request] Adding native Touchpad action

### ISSUE THREAD

**Issue by mohcow** [Ryochan7/DS4Windows#680]
At the moment there is no way to bind the native touchpad action to buttons. For example: Hollow Knight supports DS4 natively and im able to use my controller without DS4Windows(lacking battery info/custom light/fast disconnect etc.) without any problems. Since the latest update of DS4Windows im able to change it to DS4 output and Hollow Knight is recognizing that and changes prompts accordingly. Here is the problem: Hollow Knight is using the touchbad button to open the inventory, but since it runs through DS4Windows there is no action for that it doesnt work. Is there a way to fix that?

**Comment by Ryochan7** [comment]
There is an issue with remapping support that does not carry over the Touchpad Button click when interpreting the input state. That issue has been fixed in the code and a new release of DS4Windows will likely come out Friday.

**Comment by DrConflict** [comment]
I second this! Other games like AC Odyssey and Far Cry 5 have this issue as well.
Pressing touchpad often opens things like maps. It still shows the touchpad button
overlay, but it can't be pressed/used. It would be amazing if this was fixed and 
everything worked as expected. Looking forward to the update that fixes this issue.

**Comment by Ryochan7** [comment]
This is no longer an issue with the latest release.
