### ISSUE TITLE
Controller Connected to DS4 Keys Do NOT Register

### ISSUE THREAD

**Issue by jamesdjkim** [Ryochan7/DS4Windows#683]
I am currently running DS4 v. 1.7.7 and using a PS4 controller. It is connected and using the default profile. I also have used the "Hide DS4 controller" function. However, whenever I attempt to use the controller in any game none of the buttons register. I am also using Windows 10 64-bit.

The above situation arises when connected through bluetooth. When hardwired, a few buttons work but not as they should. For example, the "start" button in game is set to be "options' but only works as the "R2" button on the PS4 controller.

**Comment by jamesdjkim** [comment]
The above situation arises when connected through bluetooth. When hardwired, a few buttons work but not as they should. For example, the "start" button in game is set to be "options' but only works as the "R2" button on the PS4 controller.

**Comment by mika-n** [comment]
What do you see in DS4Windows Logs tabpage when you connect a controller? Post those messages. Any warnings or errors?

What do you see when you run Joy.cpl (run that command)? Does it show both the physical controller and the virtual one (in a scenario where you have connected just one gameapd/joystick)? And when you press "Properties" button in Joy.cpl ControlPanel applet then does the virtual controller register keys correctly?

How about https://html5gamepad.com gamepad test app? How it works when you press buttons? 

And try to test the PS4 gamepad in Joy.cpl and in html5gamepad.com without running DS4Windows app? If you connect the controller over BT and these apps don't show any activity even without DS4Win app then you have BT pairing/compatibility problem in WinOS level. At first you have to sort out BT connectivity issue (not all BT hosts are compatible with DS4 controller).

**Comment by jamesdjkim** [comment]
![DS4 Log](https://user-images.githubusercontent.com/50211781/57098913-32626600-6ce9-11e9-9987-004baf045e10.png)
![joy cpl without DS4](https://user-images.githubusercontent.com/50211781/57098916-32626600-6ce9-11e9-87de-fcb8af618ebb.png)
![joy cpl](https://user-images.githubusercontent.com/50211781/57098918-32626600-6ce9-11e9-8053-48d9a7453a1f.png)


When I ran the Joy.cpl with DS4Windows on, no controller appeared in the popup window.  When I ran the joy.cpl simply through the computer's BT without having DS4Windows open, a controller appeared. When that controller appeared (without DS4Windows open) I went into properties and all the joysticks and buttons on the PS4 controller registered.

When I went to html5gamepad the following happened.

1. With the DS4windows application open, html5gamepad recognized the controller and all button functionality worked only when hard wired through USB. When connected through BT, html5gamepad did not recognize a controller. In the DS4Windows application a controller was connected in both instances (hard wire and BT).

2. With the DS4windows application closed and the PS4 controller connected directly to the desktop via BT, the html5gamepad recognized the controller and all button functionality worked.

**Comment by mika-n** [comment]
Do you use x360 controller option in a profile instead of dualshock4 option? Seems like HideDS4Option works BUT do you have UseDInputOnly option set also? In that case you would end up without any controller.

Untick UseDinputOnly option.

Post your profile file if it still doesnt work.

**Comment by jamesdjkim** [comment]
Im sorry, I am not sure I fully understand your questions. Where do I find out whether I am using a X360 controller option instead of dualshock4? Also where is the "UseDInputOnly" option?

**Comment by mika-n** [comment]
Both are in profile options screen with those names

**Comment by jamesdjkim** [comment]
![Untitled](https://user-images.githubusercontent.com/50211781/57101773-ec5cd080-6cef-11e9-8f34-f529f8e6c5e4.png)


This is the way my profile options are currently formatted. It seems that "Use Dinput Only" is not checked and there are no controllers selected. Does anything need to be changed?

**Comment by mika-n** [comment]
Hmmm... how the Controller option is empty? I should take a look at the code to understand how is it even possible. Or Ryochan7 propably knows how is it possible. Can you see drop down options there?

How about if you create a new default profile? 

Anyway, Controller option should never be empty.  Other options look fine.

**Comment by mika-n** [comment]
And does things work when you select xbox360 option? Or dualshock4?

Remember that it is just the type of output virtual controller, not the type of input physical controller.

See Wiki pages of this website for more info about options and exclusive mode etc..

**Comment by jamesdjkim** [comment]
I've tried it with both the xbox360 and dualshock 4 options selected and none of them work.

**Comment by mika-n** [comment]
Hmm... Check device manager. Are there any hid devices in disabled state or with warning icons?
Try to get it working with usb connection first to eliminate potential BT issues.
Do you see any controllers in Joy.cpl list when you have set controller option non-empty?
Reeboot the pc to workaround weird device issues?
Do you have Oculus apps installed? Those may clash with Vigem driver.
Do you have HidGuardian app installed. Missconfigured hidguardian may hide virtual devices.

**Comment by martincscheele** [comment]
I'm having the same issue here. Updated to 1.7.7 from 1.7.5 today, and buttons are no longer recognized in game. Touchpad mouse still works for me, in and out of game, and the triggers register in the controller readings screen. Absolutely nothing has changed on my computer between the updates either.

**Comment by martincscheele** [comment]
Reverting to 1.7.5 fixes the issue, however reverting to 1.7.6 does not.

**Comment by Ryochan7** [comment]
Confirmed that the empty combobox is possible on a fresh install with the Default profile; oddly, the New  Profile option works fine. An option can be enabled in the profile but the Xbox 360 option should be selected by default.

**Comment by mika-n** [comment]
> Reverting to 1.7.5 fixes the issue, however reverting to 1.7.6 does not.

V1.7.6 was the first version introducing the new virtual DS4 type of virtual controller. All earlier versions supported only x360 virtual output controller. V1.7.7 was just a minor bugfix release on top of V1.7.6 and nothing major was changed in a controller connectivity side.

Could you please send a Logs tabpage messages from V1.7.5 and from V1.7.7 versions? Also please test the DS4Win app with a fresh new default profile without any custom mappings (create a new profile in DS4Win app).

And if your existing profile file is missing the following entry then please try adding it there with "Powered by Notepad" technology. Doesn't matter where you add this line as long it is inside of  DS4Windows xml block:

`  <OutputContDevice>X360</OutputContDevice>
`

Anyway, this xml entry should be automatically added by DS4Win app if it is missing in an old migrated profile files but if there are some permissions issue with the profile folder then DS4Win app might fail to add that entry.

**Comment by jamesdjkim** [comment]
Re: Mika Questions

1. Checked device manager and there are controller devices with a warning icon or disabled.
2. Not sure what you meant by try to get it working through a USB connection. The computer seems to read a usb connection better than the BT in terms of key registry, but the keys that work are completely off. (i.e. Start Button doesnt register with "Options" but rather "R2 Trigger.")
3. From the last section of screenshots I sent you, changing the controller to Xbox360 or Dualshock4 does not change any of the different scenarios in joy.cpl.
4. I have rebooted my computer many times and it does not fix any of the issues. 
5. I do not have Oculus or HIDGuardian installed.

**Comment by jamesdjkim** [comment]
Re: Ryochan Suggestion

Creating a new profile within the DS4windows application made it work, but every time I disconnect the controller whether it be through stopping the app or disconnecting BT / USB Connection, it stops working even within the new profile.

**Comment by Ryochan7** [comment]
The default profile would have to be edited with the Controller option set to Xbox 360. Without that, the requested virtual controller type would be different so the old virtual controller would get unplugged. I probably should not have left the None option in the code but the idea was to maybe deprecate the current "Use DInput only" option.

This problem should be fixed now with version 1.7.8 even with a profile made from this problem.

**Comment by jamesdjkim** [comment]
Version 1.7.8 fixed the issue.
