### ISSUE TITLE
[Feature Request] More deadzone Options?

### ISSUE THREAD

**Issue by MST246** [Ryochan7/DS4Windows#685]
I was wondering if the ability to adjust deadzones for x and y axis independently of each other would be possible? I've been using Better DS3 for this feature (56 year old thumbs with the shakes) for increasing deadzone for x axis to help in golf games. BDS3 has been very buggy for about a year now and a pain to use. I was hoping DS4Windows would have this feature or, matbe it does and I'm missing it.

Thanks

**Comment by Ryochan7** [comment]
I believe both of these features have been requested in the past. Other issues have taken priority so this has never been given a try. DS4Windows uses a circle dead zone for the analog sticks. Implementing a cross dead zone would be required along with the individual dead zone value for each axis. Another big concern is performance.

**Comment by MST246** [comment]
Thanks for the reply. Looks like I'm using two apps. actually faster to unplug the DS3 and click a button to connect the DS4 rather than waiting for a sluggish app to change profiles. Better DS3 is set to launch with my golf profile and fortunately only takes seconds for the launch. But, I was hoping. Thanks
