### ISSUE TITLE
"Enable Touchpad Toggle" has no informative hovertext

### ISSUE THREAD

**Issue by keatsandyeats** [Ryochan7/DS4Windows#687]
I think the profile option "Enable Touchpad Toggle" could use some extra info in a hovertext. The name itself isn't explicit, at least for me personally; I always end up having to search and find this helpful issue https://github.com/Ryochan7/DS4Windows/issues/420.

**Comment by Ryochan7** [comment]
I tend to avoid adding anything to the GUI unless it is necessary. I will put in a hover message and see if it impacts performance of the app at all.
