### ISSUE TITLE
Would it be possible to associate profiles with controller ID?

### ISSUE THREAD

**Issue by Mantaba** [Ryochan7/DS4Windows#69]
I have 2 controllers and need to use a different profile for each because one of them has some problems.
The profiles get attributed to controllers in order of connection.

Example1:
Connect broken controller and select broken profile;
Disconnect broken controller;
Connect good controller.

Now the good controller is using the broken profile.

Example2:
Connect good controller and select good profile;
Connect broken controller and select broken profile;
Disconnect good controller; (There will be only one controller connected but the Broken controller will still be in the second line. The first line is blank. Example in pic). 
Disconnect broken controller;
Connect broken controller;
Connect good controller.

The broken controller will be using the good profile and the good controller will be using the broken profile.

Thanks for your time and for keeping this update.

![image](https://user-images.githubusercontent.com/9088926/27408975-0c8117e4-56d7-11e7-939a-fe1304ac8c8a.png)

**Comment by randu1459** [comment]
@Ryochan7 - Do you mind if I give this a whirl? I'm looking for a project to contribute to as a beginner. I've played around with this a little and I think I can make this a fairly simple addition:

![image](https://user-images.githubusercontent.com/14958225/27742710-3b7d1580-5d7f-11e7-924e-f980ee24801d.png)

- The user can check the check box to link the currently selected profile and controller ID. 
- The profile and controller ID will be saved in the Profiles.xml file.
- If the selected profile is changed and the box is still checked, the software will update the profile saved for the controller ID.
- If the box is unchecked, we'll remove remove any existing mappings.
- Will check for a profile+id mapping during the findControllers method and load the profile and check the box if a saved mapping is found. 

Also: Thank you for maintaining this! I was using Jay's version until I stumbled upon this version.

**Comment by randu1459** [comment]
I'm still pretty much new to git. Those extra commits showing here appear to have come from my amended commits. I only show one in the Pull Request.
