### ISSUE TITLE
hide DS4 controller is not working

### ISSUE THREAD

**Issue by asp0909** [Ryochan7/DS4Windows#691]
I activate 2 controls .... dualshock 4 input 0 xbox 360 controller input 1, what should I do to remove dualshock 4 and only leave active xbox 360 controller in input 0?

**Comment by mika-n** [comment]
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting

**Comment by Ryochan7** [comment]
This is an advanced topic that gets more complex by the month. At this point, too much software that people use cause that old workaround to fail. HidGuardian is the most sure way of getting exclusive access to the DS4.

https://github.com/Ryochan7/DS4Windows/wiki/DS4Windows-and-HIDGuardian-Install-and-Setup-Guide#hidguardian-test-installer
