### ISSUE TITLE
Dongle unplugging results in hangs/crashes

### ISSUE THREAD

**Issue by JarnoVgr** [Ryochan7/DS4Windows#7]
When unplugging my dongle while DS4Windows is running results in several different problems when performing in-app actions afterwards (hangs, high CPU usage and app crashes). For example: Disconnect dongle and press 'Stop' in DS4Windows > hang.

Preferably it should be possible to unplug and plug a Bt dongle in while keeping DS4Windows open.

Tested on commit: a2fb603d

**Comment by Ryochan7** [comment]
I wouldn't expect this to be a normal use case but the issue has been resolved. A new build with the fix should be up in the next day or two.
