### ISSUE TITLE
CronusMax compatibility

### ISSUE THREAD

**Issue by Aidolii** [Ryochan7/DS4Windows#702]
While a CronusMax can be configured to identify as an xbox 360 controller, DS4Windows is one of the more robust controller customization programs and I'd like it if when it is in PS4 output mode that DS4Windows recognizes it as a real PS4 controller. Here is the device information it has while in PS4 output mode:

![image](https://user-images.githubusercontent.com/37132025/57802543-d4d40d80-771b-11e9-857d-5d3e6494ac4f.png)
![image](https://user-images.githubusercontent.com/37132025/57802556-dbfb1b80-771b-11e9-93f8-c3bb33278a5f.png)
![image](https://user-images.githubusercontent.com/37132025/57802564-e2899300-771b-11e9-8c57-4af6c4244fef.png)

Hopefully this is sufficient!

**Comment by Aidolii** [comment]
Just had to add `new VidPidInfo(SONY_VID, 0x05C5), // CronusMax (PS4 Output Mode)` to DS4Devices.cs and compile, easy!

**Comment by Ryochan7** [comment]
I will give that a try later.

**Comment by Aidolii** [comment]
Oh, I closed this when I saw the PR, but then noticed it hasn't been merged yet.

**Comment by Ryochan7** [comment]
The changes are now merged in.
