### ISSUE TITLE
Support more than 4 controllers at once

### ISSUE THREAD

**Issue by Corgano** [Ryochan7/DS4Windows#703]
Is there any chance to get support for more than 4 controllers? Xinput has supported up to 8 controllers now, with either an xbox one receiver and 8 controllers or two xbox 360 receivers with 4 controllers each. Windows 10 is more than capable of handling the input... so where is the limit implemented? Could we give it a try?

**Comment by mika-n** [comment]
It would be possible, but the change would require quite a lot changes to the original code base derived from the original JayKings version. There are "everywhere" assumptions that the max number of controllers is 4, so here-and-there the code makes assumptions based on index value 4 (sort of) and many arrays/tables are created using 4 slots.

**Comment by CookiePLMonster** [comment]
Doesn't the limit of 8 controllers concern Windows.Gaming.Input and not XInput?

**Comment by Corgano** [comment]
The limit right now is 4, not 8. Xinput supports 8 and I'm not sure how
many windows supports

**Comment by Ryochan7** [comment]
It seems like CookiePLMonster might be correct. The normal XInput API only support a maximum of 4 controllers at once. The Microsoft documentation states as much.

https://docs.microsoft.com/en-us/windows/desktop/xinput/getting-started-with-xinput#multiple-controllers

The Windows.Gaming.Input API can support up to 8 controllers being connected at the same time. I don't remember what the controller limit is when using the DirectInput API.

**Comment by Corgano** [comment]
However the documentation linked references items such as a "ring of light,
lit sequentially clockwise" which is definitely a reference to xbox 360.
However the xbox one controllers can be connected in sets of 8, so how does
windows handle them

**Comment by CookiePLMonster** [comment]
Again, I expect this to be valid only for Windows.Gaming.Input as XInput is not being updated with new features (such as impulse triggers).

**Comment by Corgano** [comment]
Maybe there could be an option to support windows.gaming.input directly? X input is pretty old at this point and if it's being superceded by something else we should probably support it

**Comment by Ryochan7** [comment]
This would be an issue to take up with Nefarius and the ViGEm project. This is a driver detail that is beyond the control of a user mode application like DS4Windows.
