### ISSUE TITLE
PS Move Navigation Controller compatibility (PID/VID provided)

### ISSUE THREAD

**Issue by Aidolii** [Ryochan7/DS4Windows#706]
VID_054C (i.e. standard SONY_VID), PID_042F

![image](https://user-images.githubusercontent.com/37132025/57982425-2249c680-7a0b-11e9-8c21-7705bb52a92d.png)

**Comment by Aidolii** [comment]
Unfortunately I think this will require more than just adding it to the device list to work so I'm going to close this.

**Comment by Ryochan7** [comment]
It is a completely different style device with a different input report. There would be no reasonable way to get it working in DS4Windows.

**Comment by Aidolii** [comment]
Seems that way, yes. Unfortunate.

**Comment by Aidolii** [comment]
For what it's worth though, it IS compatible with a CronusMax, so you can use it with DS4Windows in that way, just not directly.
