### ISSUE TITLE
DS4 Controller not getting recognized by PCSX2

### ISSUE THREAD

**Issue by Plecsius** [Ryochan7/DS4Windows#709]
Long story short, I wanted to get back into playing some good old Persona 4. I've updated DS4Windows to the latest version and it works on my PC and other games on it but as soon as I boot up a game in PCSX2 the only thing that will work is the touchpad (to move the cursor around).
The only thing I've observed which may or may not be of help is that the "Could not open DS4" error appears for a second when I boot up DS4Windows but disappears afterwards. I haven't got Steam or anything like that open either.

I went ahead and posted this to the PCSX2 subreddit aswell.

**Comment by Plecsius** [comment]
Fixed by restarting my PC.

**Comment by Plecsius** [comment]
Aaaaaaaaand it's not working again. After a few minutes it disconnected and reconnected and stopped working on PCSX2 again. I honestly don't know what else I could do

**Comment by mika-n** [comment]
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

Maybe you are suffering from "failing exclusive mode" issue? When controller is disconnected in the middle of the game/emulator and then re-connected it could be that the exclusive mode fails after the reconnection if the game/emulator had already stolen the HID device connection.

Are you using "Hide DS4 Controller" option of DS4Windows app or 3rd party HidGuardian device driver to hide the original DS4 controller from the emulator? Please post full logfile of D4Win Logs tab page.

**Comment by Plecsius** [comment]
I've been using an outdated version today and yesterday ( the one from ds4windows.com ) and it seems  to be working fine for now. No idea why an outdated version works and the updated one doesn't but oh well.
