### ISSUE TITLE
Simultaneous Sony Dualshock 4 Wireless USB Adaptor problem

### ISSUE THREAD

**Issue by ATCH1N** [Ryochan7/DS4Windows#71]
Hi, thanks for the incredible work on this fork! 

I have 4 Sony Wireless Adapters to play with some friends. When I connect two or more adapters, the program crashes when pairing/connecting any dualshock 4. The program works perfectly with just one adapter.

**Comment by Ryochan7** [comment]
I am wondering if the use of blank serial numbers is causing the problem. When no controller is connected to the adapter, there is no returned mac address. That address is used in some data structures as a key value which will be updated when a controller is connected to the adapter. Having multiple adapters connected with a blank serial number could probably cause problems with some routines.
