### ISSUE TITLE
New icon invisible on black background

### ISSUE THREAD

**Issue by RaydenX93** [Ryochan7/DS4Windows#714]
I love the new icon design but it is invisible on a black desktop background.

![immagine](https://user-images.githubusercontent.com/26058845/58511147-83576400-819a-11e9-965a-2ae6c01f0630.png)

Maybe a white outline on the icon could help with visibility?

**Comment by carloshbcabral** [comment]
Ping @FuriaESP

**Comment by mika-n** [comment]
DS4Windows app contains an alternaative white icon. The Settings window has an option "White DS4Windows icon", but it changes only the toolbar icon. Unfortunately this white icon is not published in the ds4windows.exe executable as an alternative icon resource for desktop app links.

But there is a workaround. 
- Download the "DS4W - White.ico" icon as a file 
- Choose "Properties" of DS4Windows desktop shortcut 
- Press "Change icon" button and use use "Browse" button to choose the downloaded "white" icon file.

This works with desktop shortcuts.

https://raw.githubusercontent.com/Ryochan7/DS4Windows/jay/DS4Windows/Resources/DS4W%20-%20White.ico

![ds4win_desktopIcon](https://user-images.githubusercontent.com/35538525/58533662-c7c21e80-81f1-11e9-96d4-d0d6c3b1c175.png)

**Comment by Oppion44** [comment]
I agree with Rayden, the icon totally went invisible on my black taskbar as well. If I have to search for a solution and then find "download this white icon" there's definitely something wrong with the design imo.
How about adding a bit of color so there are no problems on black desktops/taskbars to begin with?

https://imgur.com/a/gO2caC1

**Comment by mika-n** [comment]
Possible. Do you have such a version of the icon? Please share it.

**Comment by Oppion44** [comment]
What? Is that imgur link blacklisted that people can't see it?

**Comment by Yohoki** [comment]
Here. Try one of these. I just quickly added borders to the white icon and inverted it for black. They're not perfect, but they have borders.

[DS4W_IconsWBorders.zip](https://github.com/Ryochan7/DS4Windows/files/3332655/DS4W_IconsWBorders.zip)

**Comment by Flowz86** [comment]
I just made this transparent one white:
https://imgur.com/nUsxlcM

**Comment by Ryochan7** [comment]
The icon does not seem to scale well and the black ico file actually contains the white icon for the two smallest entries.

**Comment by Oppion44** [comment]
I made a simple icon that goes away from the copy-pasted Google Images controller design and made it consist of the the four abbreviations D S 4 W with the Playstation button colors. Supports all sizes from 16x16 up to 256x256.

https://mega.nz/#!6s0QDAgQ!s047lBjWYSP5Fvu-2yfa5OuylPNXh2lNrGdIp6hJtzI
