### ISSUE TITLE
Combination: Hold L2+Left Stick to the left + press R2 doesn't work properly.

### ISSUE THREAD

**Issue by Niagav** [Ryochan7/DS4Windows#716]
Combination: Hold L2+Left Stick to the left + press R2 doesn't work properly. The same combination, but with holding the left stick to the right works well. On the xbox gemepad without ds4windows both combination works well.

   The problem lies in the very small recognition zone of the left stick tilted to the left with these buttons held down, because when the left stick is tilted to the right, the zone is as big as on the xbox one gamepad and it works well.

   I tested it in the ue4 project.

**Comment by mika-n** [comment]
Are you sure you haven't tweaked maxZone or sensitivity or curve settings in DS4Win app for left stick? Or enabled squareStick option for LS? If you are in doubt then update to the latest version of DS4Win app and try creating a new default profile without any custom tweaks.

Just tested holding L2 trigger + left stick all the way to left + pressing R2 shoulder button down and worked just fine. It generated the full range. Tested using https://html5gamepad.com/ web page to see raw axis values.

**Comment by Ryochan7** [comment]
I have tested this and that control combination works fine on my end. Can you share your profile so that I can see how controls are being mapped?

**Comment by Niagav** [comment]
Hmm... I have tested it via https://html5gamepad.com/ and it works well, but in the ue4 it works only if i tilte left stick immediatly after i holdeing L2. If i tilte left stick to the right and then roll to the left combination won't work.

And i tested it on three gamepads.
[Default.zip](https://github.com/Ryochan7/DS4Windows/files/3249105/Default.zip)

**Comment by Ryochan7** [comment]
It sound like a mapping problem in the game then. Either that or maybe exclusive mode is not active so both the DS4 and virtual Xbox 360 controllers are being detected by the game. Double input can make some interesting things happen in some games and some games can become unplayable when exclusive mode is not active.

Nothing in the profile would present a problem.

**Comment by Niagav** [comment]
Well, if this is not our mistake with the mapping, then we will write to the Epic Games forum, let them fix it in further engine updates.

Thanks for the help!
