### ISSUE TITLE
Output curve linearity

### ISSUE THREAD

**Issue by Camranbant** [Ryochan7/DS4Windows#719]
Hi, is there any chance of being able to set a custom stick linearity for the enhanced precision output curve, or adding a couple extra output curves that are 2x and 3x the effect of the one that's already there?

Thanks, and thanks for everything you've added to DS4windows, I really appreciate the squared sticks and DS4 output even though they're relatively niche use cases

**Comment by Ryochan7** [comment]
Being able to make some type of custom curve with custom endpoints will not happen as it is. I have thought about adding some more curve options but I have not gotten around to implementing anything. Some extra easeout curves would be doable.

Implementing a power curve option would be nice but that would require changing that segment of the GUI to make room for a slider or numeric input. That would at least give the type of custom curve option that Steam offers.

I have also thought about testing a sort of three point easeout output curve similar to enhanced precision but I have not gotten around to it. As it is, I still find the enhanced precision curve best for mapping an analog stick to a mouse. It has gotten a lot looser over time as I have found better endpoints but it would be always nice to have something faster.

**Comment by Ryochan7** [comment]
Easeout cubic curve was added in the latest version of DS4Windows. I felt comfortable loosening the enhanced precision curve more after playing with some values. I also played with the idea of a easeout version of enhanced precision and I did not like it. It felt worse than using a linear curve. At least that experiment can finally be counted as completed.

**Comment by Ryochan7** [comment]
The Bezier curve option implemented by mika-n should allow you to make a customized curve with custom endpoints.
