### ISSUE TITLE
Controller doesn't turn itself off in ds4 windows when battery 0%

### ISSUE THREAD

**Issue by shinra358** [Ryochan7/DS4Windows#72]
Controller stays in ds4 windows when battery 0 % and turns itself off. Controller is supposed to turn off because no power, but it's still indicated as on inside of ds4windows.

**Comment by Ryochan7** [comment]
The batter level indicator is not very accurate. 0 is likely being reported
by the hardware so I am not sure if there is any different way to interpret
the input report to get a more accurate reading.

**Comment by shinra358** [comment]
Yeah, 0 is being reported by the hardware because it's out of juice. It won't turn on anymore because it has no power left until I charge it. But when the controller turned itself off because of no juice, it still displayed in ds4windows as still active with a power level of 0%. This prevented any other controller from taken p1 position until I pressed stop on ds4windows.

**Comment by Ryochan7** [comment]
I will have to drain my DS4 battery and take a look at this.

**Comment by shinra358** [comment]
ok

**Comment by Ryochan7** [comment]
Finally looked into this. Windows does not recognize that the DS4 has disconnected so the backup timeout thread is required for Windows to see the device as disconnected. The routine works on my end though.

**Comment by shinra358** [comment]
Is this fix on 1.4.82?

**Comment by Ryochan7** [comment]
There has been no change regarding this issue. It seems like there shouldn't be any circumstance when the current routine would fail but it apparently does. I might have to try a couple of other things and see if the routine can be changed without creating input lag.

**Comment by shinra358** [comment]
alot of other problems happen with it reaches 0% like wrong lightbar colors etc. I think an easy fix would be for ds4windows to just turn the controller off when controller is at 1%. If it can't read number precisely like that, turning itself off at 5% would dodge the issue.

**Comment by Ryochan7** [comment]
There is no way to pull that off. The values obtained from the controller are not that precise. While connected via USB, the battery status is in the range of 0 - 11. Bluetooth only reports in the range of 0 - 8. Normally, I have the led color set to black for the empty color. The routine should still work if 0 is reported by the controller but I guess that is not the case.

**Comment by Ryochan7** [comment]
Tried this out and I didn't run into a problem with the lightbar color. The debugger seems to show that the expected code path is being run even when the reported battery level is 0. The only thing that has changed from looking at this is the idle disconnect lightbar color routine. That routine now uses an EaseOutQuad curve rather than a Linear curve. With the Linear curve, the lightbar color did not seem to really change much until about the very end of the countdown when the lightbar would quickly fade to black. Using the EaseOutQuad curve makes the lightbar color fade more quickly at the start of the countdown but more gradually afterwards.

**Comment by Ryochan7** [comment]
It doesn't help much that the controller reports 0 when the battery is almost fully depleted when charging. When the controller is not charging, there is a long period after the reported battery status goes to 0 before the controller will actually disconnect. I haven't tested it in a while but I think I have sometimes experienced a time difference of around an hour before the controller actually dies. The controller could be disconnected early but I don't think I want to do that.
