### ISSUE TITLE
When right clicking icon the menu apears far off

### ISSUE THREAD

**Issue by Sokiane** [Ryochan7/DS4Windows#721]
Hey, when I right click the menu on the process bar it apears like this where some of it is unreachable as this is the bottom part of my 2nd monitor. Only have one process bar which is on the 2nd monitor and my main monitor is a 40" TV 4k resolution where I'm running with zoom 130% zoom or smth. If I drag the process bar over to the main monitor the problem is gone, 

![image](https://user-images.githubusercontent.com/21250407/59044653-d1492780-887e-11e9-9eac-34e80de9d11f.png)

**Comment by mika-n** [comment]
Well, the app uses Windows.Forms Tooltip/NotifyIcon services to "draw" the notification icon and menu list. It is actually these WinForms services which take care of the icon and popup menu drawing, not DS4Windows app itself (it just tells the notifyIcon service what is the icon resource and what are the menu item names).

Are you using vertical taskbar orientation? Does it work if you place the taskbar to the traditional bottom horizontal position? How about when you set the big screen to 1:1 100% zoom level?

**Comment by Sokiane** [comment]
Hmmmm, just right clicked all of my icons there, one of them were off aswell, then suddenly it were back to normal after click all of them, same with the DS4... Hmm, thanks for the heads up tho <.< prolly just need to make windows draw a few boxes before it realise it's wrong xD pfff, coding.... xD

**Comment by Sokiane** [comment]
And yeah, I'm using vertical, not sure if it's at 100% zoom, and 1:1 is that x*x ratio, so no wide ratio like 1080x1920 ? But yeah, it's apparently only first time I click it that it bugs out like that now...

**Comment by Ryochan7** [comment]
It does not look like DS4Windows handles any positioning code for the taskbar icon. It might be a problem with the NotifyIcon component that is being used. I cannot reproduce the issue on my end so I am going to assume that the problem is out of my control.
