### ISSUE TITLE
DS4Windows: Xinput not showing in Settings

### ISSUE THREAD

**Issue by HeavyNorse** [Ryochan7/DS4Windows#722]
I have just bought Killer Instinct in Microsoft Store and wanted to use my Dualshock 4 to play it.
I googled and found this website explaining to me how to set it up:

https://www.pcgamer.com/how-to-use-a-ps4-controller-on-pc/

I followed the instructions, downloaded the latest version of DS4Windows (Version 1.7.9), but once I booted up DS4Windows and went into settings, I noticed there was no checkbox or setting for Xinput, as shown in this image:

![ds4windows-noxinput](https://user-images.githubusercontent.com/51484918/59110508-95c26200-893f-11e9-88be-cc3218c56532.png)

Is the version faulty or am I missing something? How do I fix this?
Thanks in advance. ^^

**Comment by mika-n** [comment]
Screenshots in PCGamer site are from some ancient version. The type of output virtual gamepad is set in a Conntroller option and it is in a profile setting. By default it is already xbox360 (ie. Xinput interface for games). Alternative controller type for remapped virtual gamepad is dualshock4.

**Comment by HeavyNorse** [comment]
> Screenshots in PCGamer site are from some ancient version. The type of output virtual gamepad is set in a Conntroller option and it is in a profile setting. By default it is already xbox360 (ie. Xinput interface for games). Alternative controller type for remapped virtual gamepad is dualshock4.
> 
> Take a look at instructions and tips in https://github.com/Ryochan7/DS4Windows/wiki page

Alright, so far so good. I tried using both the xbox360 and the dualshock4 settings, but I am still unable to do directional moves in the game for some reason. And I'm not sure how I make that work.

**Comment by mika-n** [comment]
What do you see in the Logs tab page in DS4Windows app? Post those messages here in case there are some error messages. 

What do you see when you run "joy.cpl" command or click the ControlPanel link in DS4Win settings screen? Can you see any gamepad/wireless controllers there and can you test button and axis activities of those controllers? Post a screenshot of that screen here.

Are you using a default DS4Win profile or have you customized any of the re-mapping rules? Zip and post a profile file here or try using a new default profile in case you have accidentally done something weird (you can navigate to the profile folder by cliking "Profile folder" link in DS4Win settings screen).

Do you have a standard Sony DS4 gamepad controller or some 3rd party after market controller?

If you are using bluetooth connection then try USB connection at first to make sure the controller and app installation works.

**Comment by Ryochan7** [comment]
That setting was not needed anymore once DS4Windows moved to using ViGEmBus. That setting was needed when using the ScpVBus driver to avoid multiple mapping programs conflicting due to allocating the same port range when connecting to the bus. ViGEmBus is better in that regard as multiple programs can access the bus and not conflict. Device slots will be allocated as requested.
