### ISSUE TITLE
DS4Windows.exe doesn't start

### ISSUE THREAD

**Issue by KimDebroye** [Ryochan7/DS4Windows#723]
Hi
I'm unable to start DS4Windows (Version 1.7.10 and below).
I tried with fresh downloads and my previous working configuration.
No matter what version of DS4Windows I use, I only see a spinning blue circle when I double click the executable and then nothing.
Nothing shows in tray, nothing opens, except for 'Pick where you want settings and profiles to be saved'. It does create an additional Profiles.xml file although nothing else happens. If I double click the executable again, it asks where to save settings and profiles again. I tried both options (Install dir & AppData).

Also, my (official) PS4 controller shows a yellow light for a few seconds when plugged in followed by no light at all. It didn't do that before (used to be blue light).
I already tried to uninstall the drivers via 'Devices and Printers', although nothing seems to work.
I'm kinda clueless so I was hoping one of you knew a possible solution to this matter.

Other information:
* There are no warning icons under "Human Interface Devices" (HID) devices or HID device drivers in disabled state.
* I already reinstalled ViGem bus driver.
* I use Windows 10

**Comment by mika-n** [comment]
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#nothing-works-and-ds4windows-app-and-vigem-driver-connection-silently-doesnt-do-anything

Maybe you are missing Microsoft VisualC++ 2017 runtime libraries? 
Update to the lastest .NET 4.x version.
Any messages in WinOS Event Viewer logs?

**Comment by KimDebroye** [comment]
Hi mika-n
Thanks a bunch for your followup!
Here you'll find some remarks from my side:

> https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting
> https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#nothing-works-and-ds4windows-app-and-vigem-driver-connection-silently-doesnt-do-anything

> Maybe you are missing Microsoft VisualC++ 2017 runtime libraries?
* Visual C++ redistributable packages for Visual Studio 2015, 2017 and 2019 are installed.
> Update to the lastest .NET 4.x version.
* .NET Framework 4.6.2 is installed.
> Any messages in WinOS Event Viewer logs?
* It seems I got the following error:
DCOM got error "2" attempting to start the service winmgmt with arguments "Unavailable" in order to run the server: {8BC3F05E-D86B-11D0-A075-00C04FB68820}
(I'm currently looking further into this. Last week I brought my computer in for some fixing. It didn't boot anymore into post and I remember the guy who fixed my PC saying something about winmgr. Perhaps this could be a clue...)

**Comment by KimDebroye** [comment]
Update:
* It had nothing to do with DS4Windows itself.
* It was due to **W**indows **M**anagement **I**nstrumentation (_winmgmt_) service not starting/properly working anymore. (It complained a file was missing.)
* I fixed it by updating my Windows installation using the Windows 10 Media Creation Tool @
https://www.microsoft.com/en-us/software-download/windows10.
(_Note if anyone might be interested in resolving Windows specific issues: As far as I can tell, I didn't lose any files/programs/settings in the process. It basically repairs and upgrades a Windows 10 installation and thus resolves any issues._)
* DS4Windows runs flawless again.

Thanks @mika-n for pointing me in the right direction by mentioning the WinOS Event Viewer logs.
