### ISSUE TITLE
Set profile by xinput number

### ISSUE THREAD

**Issue by Corgano** [Ryochan7/DS4Windows#726]
Can we have a way to set a profile by xinput number? Then we could say, set xinput 0 to red, xinput 1 to blue, etc. It would be very useful for identifying which controller is which, like what the 360 ring light does.

**Comment by Ryochan7** [comment]
If I remember correctly, the current ViGEm.NET library does not provide a way to obtain the true XInput slot number used for a virtual controller; I believe the C/C++ library does provide a way to do that though. DS4Windows default behavior already loads profiles based on the controller slot number. There is also a second option to force a lightbar color for a controller slot number independent of a profile's settings; it is the "Use Custom Color" option from the main window (click color box).  Those two options should be good enough to distinguish each connected controller from each other.
