### ISSUE TITLE
Device issues

### ISSUE THREAD

**Issue by wingfixer** [Ryochan7/DS4Windows#728]
At first everything works properly. It can keep working for an hour, a day, or several days of uptime.
But randomly, even in the middle of a game, something seems to break. For as long as the game is still running, there will be no interruption and it will keep working properly until you're done. But then any game that attempts to interact with the controller at launch will either just not start and only appear as a background process or hang instantly after launching. This also includes Steam (which may or may not be the culprit). joy.cpl doesn't open either.
DS4W itself still detects input from the controller but that's it. If at that point I stop DS4W, games start, but the virtual devices (HID and X360) error out and say "No drivers are installed for this device." Attempting to disable or uninstall them hangs the device manager indefinitely. Meanwhile DS4W starts using up to 50% CPU seemingly for nothing.  If I re-enable it, it does not detect the controller anymore, but writes the following log every time: https://pastebin.com/KBCQ3eCf Physically disconnecting/reconnecting the controller at this point has no visible effect on anything whatsoever.
Attempting to reboot normally results in a BSOD after several minutes, with "DRIVER_POWER_STATE_FAILURE", then gets stuck trying to create a minidump at 0%. Hard reboot starts this whole thing over.

Tried reinstalling everything related. Tried uninstalling all relevant devices. Tried built-in exclusive mode, no exclusive mode, HIDGuardian. Tried running normally and as administrator. Tried deleting all user settings and reconfiguring. Steam controller support was already completely disabled, but I tried hiding the virtual X360 in it, just in case. None of it helped.

Started happening after a fresh reinstall of Windows 10. This one is 1809, was using 1803 before with no issues.

**Comment by mika-n** [comment]
Indeed, sounds like driver level problems. Driver_power_state_failure is a WinOS kernel level error and DS4Win application shouldn't be able to cause that problem (DS4Win app runs in user mode, not in kernel mode). 

But is the problem ViGem driver or HidGuardian or some other driver? Difficult to tell without using kernel mode debuggers unless you can see some hints in Event Viewer logviewer. 
https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debug-universal-drivers--kernel-mode-

Are you using Oculus apps? 
https://forums.vigem.org/topic/47/psa-oculus-software-can-crash-your-machine

Maybe try to tweak power saving options of some drivers?

I would recommend to uninstall drivers and re-installing them one by one and test when the problem re-occurs:
- Uninstall HidGuardian driver. Use deviceManager AND remember to tick option "completely remove driver files" (or something like that) option to wipe out the driver compltely. Reboot.
- Uninstall VigEm driver the same way as HidGuardian. 
- Reboot.
- Plugin DS4Win via USB cable and test run it without DS4Win app (naturally the gamepad works only in games supporting native DS4 gamepad via directInput interface). If the problem occurs again then you know it is something else than VigEm or HidGuardian driver.

- Re-install the latest VigEm driver by downloading the latest driver file ViGEmBus_Setup_1.16.115.exe and install it before running DS4Win app.
https://github.com/ViGEm/ViGEmBus/releases/tag/v1.16.112
- Try running DS4Win app this way for a while (ie. without HidGuardian).

- Finally re-install  HidGuardian. Use DS4Win test installer to do it. 
https://github.com/Ryochan7/DS4Windows/wiki/DS4Windows-and-HIDGuardian-Install-and-Setup-Guide#hidguardian-test-installer

**Comment by wingfixer** [comment]
WinDbg looks just a little complex for me, to put it mildly. Not a thing in Event Viewer.
Not using Oculus.
Power settings all appear to be default, no different from my previous install.

I can definitely say it's not HIDGuardian. The only reason I even installed HIDGuardian was because I thought built-in exclusive mode could have been causing the issue. Unfortunately, not the case. And as I mentioned, it happens even without any kind of exclusive mode active.
I was about to say it's not ViGem either, based on the fact that it started happening back when I was using an older version of DS4W that used SCP, but that may actually not be much of a fact. My memory isn't great. I'll try to downgrade for now and report back, if at least to rule that out.
I haven't managed to find a way to force it to break, even with rapid physical reconnects and profile switching, so it may take time. It _can_ break in-game but not guaranteed to, and it's not a requirement either.

**Comment by mika-n** [comment]
ViGem installer pkg is in 1.16.115 version tag but the driver version tag within that pkg is still in 1.16.112. The 115 vesion just updated the installer app (bug fixes in installer).

**Comment by wingfixer** [comment]
Nothing's changed. I don't have a clue what I can possibly do with it anymore, but at this point it might be easier to do an OS reinstall. I can't even get a proper minidump, and Verifier leads me nowhere. Can't reproduce it with heavy stress-testing, then it just does this randomly for seemingly no reason.

Doesn't seem like this can go anywhere without digging really deep, and it does seem like an issue unrelated to DS4W, so I'm going to close this. Thank you for your time.
