### ISSUE TITLE
Always pop-up shows when run this software

### ISSUE THREAD

**Issue by rikusen0335** [Ryochan7/DS4Windows#731]
A window always shows up that "Asking update" when I run DS4Windows, from about around 1.7.8.
It will show up if I press both "Yes" or "No".

**Comment by mika-n** [comment]
Are you currently in the latest V1.7.10 version? If not then download it directly and install on top of the old installation. At some point there were some changes in "check for updates" logic.
https://github.com/Ryochan7/DS4Windows/releases

If the latest V1.7.10 version still wants to update everytime it is launched then as a short term workaround simply disable automatic update check in DS4Win options.

**Comment by rikusen0335** [comment]
Thank you for replying.
I am currently v1.7.10 but direct install worked for me! I used auto-update function somaybe it was not updated yet.
