### ISSUE TITLE
DS4 wired sim support disconnecting

### ISSUE THREAD

**Issue by Frank6969420** [Ryochan7/DS4Windows#734]
Every time i use a profile with ds4 sim enabled my controller flashes red and disconnects and turns ds4windows off

**Comment by mika-n** [comment]
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting

Logs content?

And when you say "ds4 sim" then do you mean "DS4 simulation = dualshock4 virtual output Controller type instead of xbox360 mode? (Ie. Controller option in a profile)

Does everything work fine in xbox360 controller mode?

**Comment by Frank6969420** [comment]
![image](https://user-images.githubusercontent.com/51890321/59569571-f6a61480-907a-11e9-974b-17827b7cfa3f.png)
Im talking about this setting and everything works in xbox mode

**Comment by Frank6969420** [comment]
![image](https://user-images.githubusercontent.com/51890321/59569585-3a991980-907b-11e9-8b16-a2dbd33df651.png)
This happens and ds4windows shuts down and disconnects the controller

**Comment by mika-n** [comment]
Have you tried to use a new default profile without any re-mapping tweaks? Just changing the Controller option from xbox360 to dualshock4 option? Maybe there is some weird profile setting in "J" profile causing this bug?

And if a new default profile doesn't help then try to cleanup all existing DS4Win config and profile files (copy/backup. Navigate to ds4win profile folder (and one folder up in the folder hierarchy) and delete all files below DS4Windows folder. The next time you launch DS4Win app it will create new default files.

If this works then please post your existing "J" profile file in case it is causing this crash.

By the way. Are you using the lastest V1.7.10 version?
https://github.com/Ryochan7/DS4Windows/releases

If not then download the V1.7.10 directly from the "releases" web page and install it on top of old installation.

And make sure you have the latest ViGem device driver installed (ViGEmBus_Setup_1.16.115.exe setup file). Run this setup before running DS4Win app.
https://github.com/ViGEm/ViGEmBus/releases/tag/v1.16.112

**Comment by Frank6969420** [comment]
I made a 2nd profile but it didnt work ill post J and ds4
[Profiles.zip](https://github.com/Ryochan7/DS4Windows/files/3294693/Profiles.zip)

**Comment by Ryusennin** [comment]
Do you have a DualShock 4 v1 or v2?

**Comment by Frank6969420** [comment]
v2

**Comment by Frank6969420** [comment]
Ds4windows says its up to date

**Comment by mika-n** [comment]
Do you have Oculus apps installed? 
https://forums.vigem.org/topic/47/psa-oculus-software-can-crash-your-machine

If you use BT connection then how about using USB connection? Does it work better?

**Comment by Ryochan7** [comment]
Screenshots don't match the described problem. Marked as invalid.
