### ISSUE TITLE
DS4 audio support

### ISSUE THREAD

**Issue by 090809** [Ryochan7/DS4Windows#735]
I didn't found PR from man, that do [this research (Rus)](https://habr.com/ru/post/302356/)
If need, I can translate it to Eng.

**Comment by Ryochan7** [comment]
This seems to be the technique that people were testing with ds4drv a long time ago. It didn't really work correctly as it was. Besides, presenting Windows applications with a virtual sound device would likely have to be done at the driver level. It seems that PulseAudio allows it to happen in user mode on Linux. That article is from 2016 so no new research has been done. That is not usable in its current state.

As it is, using the headphone jack with a wireless connection requires using the Sony Wireless Adapter. It is too bad that those are pretty expensive now. That adapter was good hardware although it has some issues.
