### ISSUE TITLE
Repeating Macro issue with 2 controllers plugged in

### ISSUE THREAD

**Issue by Yohoki** [Ryochan7/DS4Windows#737]
I noticed today that when I have 2 controllers plugged in, my profiles have an issue with macros. For instance, in my "Mouse Control" profile, I use share button so switch tabs. It's set up as a macro to press two keyboard buttons (Alt+Esc) once for each press. When I have two controllers plugged in, pressing share on either controller (they're both set up to the same "Mouse Control" profile) causes the macro to be rapidly repeated, despite being set to only play once per press.

Can be fixed by unplugging one controller, and plugging second controller back in causes the issue to happen again.

Can also be stopped by having controller 2 set to a profile which DOESN'T have that Macro bound to the same button. Most of my profiles use Share for switching tabs with macros, but setting either controller to a profile that doesn't use the macro also fixes it.

It isn't a big issue for me, since I only use it to switch tabs, but I could see the issue popping up during Co-Op play when I have macros set up for certain functions for both players.

Example Profile: Mouse Control.xml - Macro on Share Button
~~~~
<?xml version="1.0" encoding="utf-8"?>
<!-- DS4Windows Configuration Data. 6/9/2019 7:20:35 PM -->

<DS4Windows>
  <flushHIDQueue>False</flushHIDQueue>
  <touchToggle>False</touchToggle>
  <idleDisconnectTimeout>300</idleDisconnectTimeout>
  <Color>0,0,255</Color>
  <RumbleBoost>100</RumbleBoost>
  <ledAsBatteryIndicator>False</ledAsBatteryIndicator>
  <FlashType>0</FlashType>
  <flashBatteryAt>0</flashBatteryAt>
  <touchSensitivity>100</touchSensitivity>
  <LowColor>255,0,0</LowColor>
  <ChargingColor>255,255,255</ChargingColor>
  <FlashColor>0,0,0</FlashColor>
  <touchpadJitterCompensation>True</touchpadJitterCompensation>
  <lowerRCOn>False</lowerRCOn>
  <tapSensitivity>0</tapSensitivity>
  <doubleTap>False</doubleTap>
  <scrollSensitivity>0</scrollSensitivity>
  <LeftTriggerMiddle>0</LeftTriggerMiddle>
  <RightTriggerMiddle>0</RightTriggerMiddle>
  <TouchpadInvert>3</TouchpadInvert>
  <L2AntiDeadZone>10</L2AntiDeadZone>
  <R2AntiDeadZone>30</R2AntiDeadZone>
  <L2MaxZone>100</L2MaxZone>
  <R2MaxZone>100</R2MaxZone>
  <ButtonMouseSensitivity>30</ButtonMouseSensitivity>
  <Rainbow>0</Rainbow>
  <LSDeadZone>25</LSDeadZone>
  <RSDeadZone>25</RSDeadZone>
  <LSAntiDeadZone>0</LSAntiDeadZone>
  <RSAntiDeadZone>0</RSAntiDeadZone>
  <LSMaxZone>100</LSMaxZone>
  <RSMaxZone>100</RSMaxZone>
  <LSRotation>0</LSRotation>
  <RSRotation>0</RSRotation>
  <SXDeadZone>0.02</SXDeadZone>
  <SZDeadZone>0.02</SZDeadZone>
  <SXMaxZone>100</SXMaxZone>
  <SZMaxZone>100</SZMaxZone>
  <SXAntiDeadZone>0</SXAntiDeadZone>
  <SZAntiDeadZone>0</SZAntiDeadZone>
  <Sensitivity>1|1|1|1|1|1</Sensitivity>
  <ChargingType>0</ChargingType>
  <MouseAcceleration>True</MouseAcceleration>
  <LaunchProgram>
  </LaunchProgram>
  <DinputOnly>False</DinputOnly>
  <StartTouchpadOff>False</StartTouchpadOff>
  <UseTPforControls>False</UseTPforControls>
  <UseSAforMouse>False</UseSAforMouse>
  <SATriggers>-1</SATriggers>
  <SATriggerCond>and</SATriggerCond>
  <SASteeringWheelEmulationAxis>None</SASteeringWheelEmulationAxis>
  <SASteeringWheelEmulationRange>360</SASteeringWheelEmulationRange>
  <TouchDisInvTriggers>-1</TouchDisInvTriggers>
  <GyroSensitivity>100</GyroSensitivity>
  <GyroSensVerticalScale>100</GyroSensVerticalScale>
  <GyroInvert>0</GyroInvert>
  <GyroTriggerTurns>True</GyroTriggerTurns>
  <GyroSmoothingWeight>50</GyroSmoothingWeight>
  <GyroSmoothing>False</GyroSmoothing>
  <GyroMouseHAxis>0</GyroMouseHAxis>
  <GyroMouseDeadZone>10</GyroMouseDeadZone>
  <GyroMouseToggle>False</GyroMouseToggle>
  <LSCurve>0</LSCurve>
  <RSCurve>0</RSCurve>
  <ProfileActions>Disconnect Controller</ProfileActions>
  <BTPollRate>4</BTPollRate>
  <LSOutputCurveMode>enhanced-precision</LSOutputCurveMode>
  <RSOutputCurveMode>linear</RSOutputCurveMode>
  <LSSquareStick>False</LSSquareStick>
  <RSSquareStick>False</RSSquareStick>
  <L2OutputCurveMode>linear</L2OutputCurveMode>
  <R2OutputCurveMode>linear</R2OutputCurveMode>
  <SXOutputCurveMode>linear</SXOutputCurveMode>
  <SZOutputCurveMode>linear</SZOutputCurveMode>
  <TrackballMode>False</TrackballMode>
  <TrackballFriction>10</TrackballFriction>
  <OutputContDevice>DS4</OutputContDevice>
  <Control>
    <Button>
      <LXNeg>Mouse Left</LXNeg>
      <LXPos>Mouse Right</LXPos>
      <LYNeg>Mouse Up</LYNeg>
      <LYPos>Mouse Down</LYPos>
      <RXNeg>Unbound</RXNeg>
      <RXPos>Unbound</RXPos>
      <RYNeg>Mouse Wheel Up</RYNeg>
      <RYPos>Mouse Wheel Down</RYPos>
      <R3>Middle Mouse Button</R3>
      <Circle>Right Mouse Button</Circle>
      <Cross>Left Mouse Button</Cross>
      <TouchLeft>Unbound</TouchLeft>
      <TouchUpper>Unbound</TouchUpper>
      <TouchMulti>Unbound</TouchMulti>
      <TouchRight>Unbound</TouchRight>
    </Button>
    <Macro>
      <Share>164/27/27/164</Share>
    </Macro>
    <Key>
      <DpadUp>38</DpadUp>
      <DpadRight>39</DpadRight>
      <DpadDown>40</DpadDown>
      <DpadLeft>37</DpadLeft>
      <Options>27</Options>
    </Key>
    <KeyType>
      <Share>Macro</Share>
    </KeyType>
  </Control>
  <ShiftControl />
</DS4Windows>
~~~~

**Comment by Ryochan7** [comment]
I don't have a problem with the macro getting stuck when using multiple controllers. The macro ends up executing twice as fast though. I am betting that a shared variable is being used somewhere in the mapping routine that is causing the macro task to execute early. Personally, I don't use the macro system as I find it flawed in many ways.

**Comment by mika-n** [comment]
Indeed the macro system is a bit flawed. The existing logic is missing some key features like binding a macro to "button released" event. And the code does a lot of repeating re-creation of strings and string lists and int->ToString->ToInt conversions. This slightly hurts performance and memory management if macros are used in common keys and buttons, because these things happen in each gamepad poll cycle.

The behavior you are seeing is probably a result of logic in the macro engine to reset all keys and buttons status and sometimes unnecessarily re-firing EndMacro event. And yes, there are shared variables for example how the macro engine handles waiting between certain key events and macroDone flag status. These could easily get out-of-sync because of multiple controllers and multithreaded async methods.

The whole macro engine should be re-written to support key release event and to make it multithread/multicontroller safe.

I have already done some work with the macro engine and the current devel version supports "key released" macro events. But the macro engine would require a lot more work because any new macro feature seems to require a "spaghetti code injection".

**Comment by Yohoki** [comment]
> 
> 
> I don't have a problem with the macro getting stuck when using multiple controllers. The macro ends up executing twice as fast though. I am betting that a shared variable is being used somewhere in the mapping routine that is causing the macro task to execute early. Personally, I don't use the macro system as I find it flawed in many ways.

It's less that the macro gets stuck, and more that it repeats when it shouldn't. For instance, having a button set to "Play once" will repeat instead... or, as @mika-n says, maybe it's not repeating, but constantly re-firing, which looks about the same.
