### ISSUE TITLE
HidGuardian stopped working

### ISSUE THREAD

**Issue by RHReaper** [Ryochan7/DS4Windows#741]
Hello, good morning or evening to you.

Firstly, apologies if this has been posted already. I couldn't seem to find anything on it recently.

I'm having an issue with HidGuardian, it's stopped working entirely.

I normally keep it disabled, and enable it when I need exclusive mode (for Dark Souls, for example). So I'm not entirely sure when it stopped working.

The changes to my system since it last worked have been updating DS4Windows to 1.7.10 and installing the Windows 10 1903 Feature Update.

I'm unsure if this is something on my end, or if the software needs to be updated for the Windows update, and I'm hesitant to try to reinstall everything again as I tend to dig myself deeper into a hole when I do that. So I thought I'd ask here first.

I hope someone can help.

Thank you.

Kind regards,

**Comment by Ryusennin** [comment]
Maybe your list of hidden devices has been changed/deleted. Read section "Update Windows Registry with list of Affected Devices" in the wiki:

https://github.com/Ryochan7/DS4Windows/wiki/DS4Windows-and-HIDGuardian-Install-and-Setup-Guide

**Comment by RHReaper** [comment]
Oh dear, how did I miss that. I breezed right passed it.

Thank you for your reply and assistance. I followed that part and the part below, and it's working fine now.

And sorry for opening this thread when the answer is posted there.

Thanks and all the best =)
