### ISSUE TITLE
Turning off DS4 toggles Alt+Tab

### ISSUE THREAD

**Issue by Blackbird88** [Ryochan7/DS4Windows#749]
Basically every time I press PS button+Share it changes active window. There's nothing in settings I could find that "turns" this off. Is this some Windows behavior?

**Comment by Ryochan7** [comment]
AFAIK, there is no hotkey mapped to that button combination. I have tried it out on my end and I don't experience that issue. I can only assume that either a macro or special action is being activated when that button combination is pressed.

**Comment by Blackbird88** [comment]
Okay I tested it some more and I _think_ it may be Steam causing it which is weird since I disabled everything in it.
