### ISSUE TITLE
Check For Update Tells Me I'm Up To Date (I'm Not)

### ISSUE THREAD

**Issue by ajhix36** [Ryochan7/DS4Windows#75]
Hi, I am on 1.4.80, and the newest version I can see is 1.4.81. Running the update checker tells me I am up to date.

**Comment by Ryochan7** [comment]
The dedicated DS4Updater.exe works but the one in DS4Windows.exe does not. The app ends up outputting a blank version.txt file so there is no way to compare versions. This needs to be looked into and fixed.

**Comment by Ryochan7** [comment]
The updating routine has been tested and it now works. Thanks for bringing up this problem.
