### ISSUE TITLE
Updater doesn't work when program is minimized to tray.

### ISSUE THREAD

**Issue by Daltz333** [Ryochan7/DS4Windows#751]
When turning on my computer, I'd occasionally get a "update available, update to x.x.x.x?" and I will press yes. However, that does nothing. If I then click on the icon in the tray, go to settings, click on check for updates now, then it installs the update properly. 

Settings: Run on startup, Minimize to tray

Not that big of a deal, but worth mentioning.

**Comment by Pit1209** [comment]
It also happens to me.

**Comment by Ryochan7** [comment]
I will try this out. Sounds like an extremely odd bug.

**Comment by Viscerous** [comment]
Yeah, has been like this for I think around three updates. Not sure. After pressing yes, I always have to go into the main UI and check for update manually, otherwise it doesn't do anything.

**Comment by Nerdy314159265** [comment]
I can confirm that it has been around for awhile. Minimum 3 updates.
It's been such a small problem that I kept forgetting to put in an issue on it.

**Comment by Ryochan7** [comment]
Pretty sure I found the offending commit. The update will only run if a new version of the DS4Updater was found. The manual check does not have that restriction.

Skip updater execution if new version could not be downloaded : https://github.com/Ryochan7/DS4Windows/commit/592a0245b7e98cf25c63b3dd70d8889d0b6d20fa#diff-99c3938709f39b0f1b1777a41a0beb27
