### ISSUE TITLE
(feature request)timed automatic disconnect

### ISSUE THREAD

**Issue by powerpuffboysz** [Ryochan7/DS4Windows#753]
the title probably doesn't make the most sense but I was wondering if it would be feasible to add a feature to automatically disconnect the controller if left idle for 5 minutes or more with a dropdown option to lengthen or shorten the disconnect timer

**Comment by Ryusennin** [comment]
There's already a configurable "Idle Disconnect" option in Profiles > Controls > Other. As far as I can tell, however, it only works for Bluetooth.

**Comment by Ryochan7** [comment]
That feature already exists. It is the profile setting "Idle Disconnect". It is mainly geared towards working with a Bluetooth connection but it can work with a Sony Wireless Adapter if DS4Windows has exclusive control of the device.

**Comment by Ryochan7** [comment]
Scratch that. DS4Windows does not need exclusive control of the Sony Wireless Adapter in order to work. That restriction is required to use the DisconnectBT special action though.
