### ISSUE TITLE
DS4Windows.resources.dll all languages getting detected by Bitdefender

### ISSUE THREAD

**Issue by olokos** [Ryochan7/DS4Windows#755]
Hey,

I've noticed that once again DS4Windows.resources.dll are getting removed by bitdefender as threats for all languages
DS4\Update Files\DS4Windows\Lang\(anything)\DS4Windows.resources.dll
For each and every single one it's triggering and removing it automatically in bitdefender

I've noticed an issue #311 but there's no solution.

Also active threat detection detects and removes both HidGuardHelper.exe and DS4Updater.exe

I've been wondering, what should we do about this? Should I contact bitdefender support about this?

**Comment by mika-n** [comment]
Not much can be done in DS4Windows side if a scanner makes a false alarm. You should either add DS4Win, HidGuardHelper and DS4Updater (or the whole installation folder) to "exclude list" in BitDefender or contact them and ask why BitDefender blocks those files.
https://www.bitdefender.com/consumer/support/answer/13427/

**Comment by carloshbcabral** [comment]
Submit a report about the false positive.
https://www.bitdefender.com/submit/

**Comment by olokos** [comment]
I just did, I also reported HidGuardHelper.exe to bitdefender with Atc4.Detection.

**Comment by Ryochan7** [comment]
I have mainly been using ClamAV and Malwarebytes as my main anti-virus and anti-malware programs. Both of those programs don't detect an issue with those files. I have never tried Bitdefender before but it might be too bulky of a program for me to want to keep installed. Some quick Google searches does seem to show that Bitdefender has regular issues with reporting false positives.

**Comment by olokos** [comment]
It is or was the best antivirus out there for a while, for windows at least. Honestly if I'm not downloading anything obviously shady it's almost always doing well for safe stuff, including github releases which got blocked by smart screen, while bitdefender let it through. ~~I did email bitdefender but haven't got any ~~
https://image.prntscr.com/image/NY3HYeRgS4OiT9RiM92tYA.png
It seems they have indeed solved it, I will update this later if they actually did and close this.

**Comment by olokos** [comment]
I confirm, it is now by default allowing internet connection for ds4windows and not blocking either updater,hidguardian or ds4windows.exe itself, same goes for all languages.

That's a really good move by Bitdefender. 👏
