### ISSUE TITLE
[Feature Request] run macro on button release

### ISSUE THREAD

**Issue by jmriego** [Ryochan7/DS4Windows#756]
I don't know if there is any workaround by editing the xml files (so far I found nothing) but I would love to be able to trigger a macro on button release.

The reason for so is because there are some emulators in which you can trigger a behaviour by pressing some hotkeys. For example, in FS-UAE you can toggle a speed up with F12-W. To go back to normal speed, you would have to press the button again.
It would be amazing if it was possible to trigger this hotkey on a button press and then trigger it again on button release (that would make the speed up active while the button is pressed).

Is it possible to have something like this? Thanks!

**Comment by mika-n** [comment]
SpecialActions have a "multiaction" macro option which make it possible to assign a macro to keydown (tap), double tap and hold down button events. But, this option list is missing the "key release" macro assignment option. I can clearly see many scenarios where that feature could be useful.

Anyway. Here is a link to "auto-fire" type of button and how to do it with DS4Windows macros and key assigments in two different ways (special actions and key specific re-map and macro binding). It doesn't directly help you to do "key down" and "key up" macro sequences, but give it a try if you can workout something semi-useful with that.
https://github.com/Ryochan7/DS4Windows/wiki/Settings#how-to-do-auto-fire-type-of-trigger-button

Anyway, I didn't brainstorm this too long, but to me it looks like that not even specialAction with multiaction key bindings don't do exactly what you described. If multiaction special action had a "key released" event listener then this capability would be easy to do. Multiaction with tap, double tap, hold and release would be quite complete rule set. Who knows if someday there will be "key release" event handler also.

**Comment by Ryochan7** [comment]
There is no way to perform an action on a button release with the current mapping system. The mapping system in DS4Windows is fairly limited compared to something like Steam or Xpadder.

**Comment by jmriego** [comment]
That's what I noticed. I have tried several ideas even with changing profiles with shift key and similar but no luck. It would be great to add this capability
There are workarounds with autohotkey and similar for the moment

**Comment by mika-n** [comment]
> I don't know if there is any workaround by editing the xml files (so far I found nothing) but I would love to be able to trigger a macro on button release.

The latest version of DS4Windows V1.7.16 supports new options in the special action type of "Record macro". There is a new option "Run on release".
https://github.com/Ryochan7/DS4Windows/wiki/Settings#macros-and-special-actions
https://github.com/Ryochan7/DS4Windows/releases

**Comment by jmriego** [comment]
Just checked it and it works perfectly! Thanks a lot for doing this
