### ISSUE TITLE
Pt-br mistype

### ISSUE THREAD

**Issue by furbino** [Ryochan7/DS4Windows#757]
Hello there
First I would like to thank you for the new fork and all the updates! You the real MVP!
There is a mistype on the word **controller** in pt-br the right would be "**controle**" and plural "**controles**". I believe _controlo_ and _controlos_ are the spanish for controller and controllers!
Wish you all the best in the world!

**Comment by Ryochan7** [comment]
It looks like that set of translation files has never been touched in this fork. Translation file work is one area that I have left to contributors. My only non-English language knowledge is in Japanese and I have not studied it in years; I am only JLPT N5 certified so my knowledge is very basic. That change would be easy enough to do so I can get to that later.
