### ISSUE TITLE
[Feature request] Single left mouse click.

### ISSUE THREAD

**Issue by Thisbetterbefood** [Ryochan7/DS4Windows#758]
Not sure if this is a feature already. For some games if you click the left mouse button, hold it then drag, the camera moves where ever the mouse is. Once I click the touchpad it just holds down the mouse, it dosen't release it like I woulld like it to do

**Comment by mika-n** [comment]
You mean the standard mouse trick of doing left mouse click and hold while moving a mouse (click and drag)? The same thing as for example choosing an area of text in Notepad or in a web page by holding down the left mouse button while moving around the mouse cursor.

This does work in DS4Windows, but you have to be aware of that the touchpad area in DS4Windows is divided in a three different regions: Left bottom corner or touchpad as left mouse click, right bottom corner as right mouse click and top of the touchpad area as middle mouse btn click.

If you click and hold a touchpad area on top area or in right bottom corner then it doesn't actually do left mouse click, so the game doesn't see it as left click-and-hold  and mouse movement event.

So, please try again but make sure you click the left bottom corner of touchpad area. If you don't need right and middle clicks in a game then you can re-map those click points of touchpad as left mouse click also, so you don't have to be that precise while clicking the touchpad area.

Here is a picture showing the re-mapping of top area of touchpad. There are also left bottom and right bottom areas and you can re-map those anyway you want.
![DS4Win_TouchpadClickArea](https://user-images.githubusercontent.com/35538525/61154430-c2493b00-a4f6-11e9-84df-72933b603c7b.png)

This type of mouse trick is useful in EurotruckSimulator2 also, but I find it a bit easier to use when I re-map one of the shoulder buttons as mouse left click and then use touchpad as a mouse. It is much easier to manage the toucharea movement when I don't have to try to press and hold down the touchpad area while moving a finger there. It is easier to keep down the shoulder button.

**Comment by Ryochan7** [comment]
I am confused about which behavior you are asking for. Normal mouse click functionality already exists although you have to either keep in mind which touchpad region you press or map multiple regions to the same mouse button. If you want a left mouse press and immediate release from a touchpad click, you would have to use a macro to map that action to a touchpad region. Either way, that functionality already exists.
