### ISSUE TITLE
Closing connectiong to ViGEmBus

### ISSUE THREAD

**Issue by brothan323** [Ryochan7/DS4Windows#763]
Describe the bug
I can connect the controller and it'll work for a while. Yet after a while the controller will loose connection and a message appears on the left side of the bottom bar, it reads "closing connection to ViGEmBus

To Reproduce
Steps to reproduce the behavior (example):

    Start program
    Plug in device '....'
    See error after a bit

System details (please complete the following information):

    OS: Fresh install of Windows 7 Ultimate
    Feeder software: DS4Windows
    Driver Version: 1.7.9

Additional context
I've never had this issue before reinstalling Windows.

**Comment by mika-n** [comment]
Does it work better if you at first connect the controller, wait 10 secs and after that you launch DS4Windows application? Especially if you are using BT connection then some reports have suggested that there may be some timing issues in BT handshaking. It is not yet clear are there really BT handshaking/hotplug timing issues or just random coincidences, but give it a try.  

Does it work without random disconnects over USB connection?

What do you see in Logs tab page of DS4Windows app?
The latest version of DS4Win is V1.7.12: https://github.com/Ryochan7/DS4Windows/releases

**Comment by Ryochan7** [comment]
That message should not appear unless either you manually stop the DS4Windows control service or have an auto profile set up to stop it automatically. That specific message does not appear in any other portion of the program.

**Comment by brothan323** [comment]
@Ryochan7 I think it may be a game that's messing with the driver.

**Comment by brothan323** [comment]
SO this issue came up again, it's a .net framework issue with the driver. When it happens again I'll copy+paste the error I get.

**Comment by brothan323** [comment]
I can't even install the driver after uninstalling it. I keep getting a Install Failed, Please Retry error....

**Comment by brothan323** [comment]
Here's the error I get:
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.IOException: The process cannot access the file 'C:\DS4Windows\ViGEmBus_Setup_1.16.115.exe' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at DS4Windows.Forms.WelcomeDialog.bnStep1_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3416.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
DS4Windows
    Assembly Version: 1.7.12.0
    Win32 Version: 1.7.12
    CodeBase: file:///C:/DS4Windows/DS4Windows.exe
----------------------------------------
Microsoft.Win32.TaskScheduler
    Assembly Version: 2.8.0.0
    Win32 Version: 2.8.0.0
    CodeBase: file:///C:/DS4Windows/Microsoft.Win32.TaskScheduler.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3416.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3429.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by Ryochan7** [comment]
I ended up changing version 1.7.14 to not run the ViGEm installer silently anymore. Now the full manual installation method is used since the manual routine seems to be only method that will receive support. As for the other issue, you might have to use **Driver Store Explorer** to check for an old ViGEmBus driver and force uninstall it. If I remember correctly, the ViGEm uninstaller does not remove the actual driver from the system but it removes the associated device that uses it.

https://github.com/lostindark/DriverStoreExplorer
