### ISSUE TITLE
Issue with the enumeration of controls

### ISSUE THREAD

**Issue by HadesIzanami** [Ryochan7/DS4Windows#765]
I hope it is a mistake of mine and not of the program, but now that I am handling two controls, I am having problems in the way in which it manages "control 1" and "control 2". In the profiles I can see that I can select the control that I want to be either 1 to 4, but when I give it to save, this is not configured. Is this my mistake or is it a problem of the program?
![Captura](https://user-images.githubusercontent.com/42960801/61255513-8e585a80-a72e-11e9-860f-424091c45681.PNG)

**Comment by Ryochan7** [comment]
That is not what that setting does. It is an odd setting but that allows you to set which controller to read from for quickly bringing up the Edit window (press Circle on controller brings up Edit window). You would have to check the checkbox to use that feature as well. I don't use the setting as I am fine just using the form controls for configuring mapping.

Controller slots are assigned as controllers are detected. There is no way to assign an arbitrary slot number to a detected controller.

**Comment by HadesIzanami** [comment]
Thanks for your support!
