### ISSUE TITLE
Is it possible to hold down a key by pressing it once?

### ISSUE THREAD

**Issue by teijiIshida** [Ryochan7/DS4Windows#766]
Title may be confusing but let me explain.

I'm playing Nier Automata. The R1 button makes the pod shoot bullets. And if I hold R1, it will keep on shooting nonstop even if I use other actions like attacking with Square or jumping with X or movements with the joystick. 

The problem is I don't want to keep holding R1 forever in battle. So I was wondering, if it's possible to make R1 into kind of a toggle such that if I press it once, it will shoot nonstop, regardless of my other actions (attacking, jumping, moving, etc.). And if I press it again, it will stop its auto shooting.

Is this possible in v1.7.12? If not, can you implement this feature?

**Comment by Ryusennin** [comment]
Look in Profiles > Special Actions tab. You can experiment with the Press/Toggle Key action.

**Comment by teijiIshida** [comment]
Doesn't work. The pod just shoots normal (and I still have to hold it) even when I make the trigger and unload trigger R1. Also, it needs a keyboard bind (RShift for pod fire) to work, which is not what I wanted. Because I tested holding down the keyboard button for pod fire (RShift) and then spam my attack on my controller and the autofire stops whenever I attack (Square) or use joystick movement. 

The only way this can work is if R1is held down (on the controller, not using any keybind mapping to keyboard), which I am unable to do.

**Comment by Ryochan7** [comment]
It looks like toggle functionality only works when using keyboard mappings. The mapping system in DS4Windows is not that great and it has been a lot of work just improving the basic DS4 to XInput use case.
