### ISSUE TITLE
Gyro Inverted Axis only in Bluetooth (RDP Server) Bug

### ISSUE THREAD

**Issue by kishelraj** [Ryochan7/DS4Windows#767]
Hello fellow DS4 users,

I have tried the software out last week and it works really well in wired mode. However, in bluetooth mode the horizontal axis is inverted. The example in the link is for when i use it with CEMU. However,  I have tested this in padtest and can confirm the results as well. 
This only happens in bluetooth mode. In wired this works properly. 

https://drive.google.com/file/d/1-BPKPyuvFNep2JbCLTJNJamjlZuPha5F/view?usp=drivesdk

This issue has been replicated on another computer as well. Am i doing something wrong here? Or is this a software bug ? Can anyone verify this is a bug or is it something I did wrong?

**Comment by kishelraj** [comment]
Btw, Vertical Axis works fine. It's only inverting the horizontal.

**Comment by mika-n** [comment]
Are you sure you are using the latest version of DS4Win? https://github.com/Ryochan7/DS4Windows/releases

I just tested PadTest1011 using both BT and USB connection and in both cases PadTest did show the correct orientation just fine in all gyro axis.

See the following wiki page for more info about how to provide more details about your environent and logfiles and versions.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting

**Comment by kishelraj** [comment]
Hi Mika,

I have done all this. have both the latest versions of DS4 windows as well as ViGEM bus driver installed. I reinstalled these again for good measure.

I have also done a firmware reset and even tried a different bluetooth dongle. 

Below is the attached zip file. I looked through the troubleshooting page, and I have attached the profiles.

[DS4Windows.zip](https://github.com/Ryochan7/DS4Windows/files/3408661/DS4Windows.zip)

Please let me know if there is anything else required.

**Comment by Ryochan7** [comment]
The profile works on my end when using a BT connnection and testing with PadTest. Is the Sixaxis portion of the DS4Windows Controller Readings tab showing an expected reading for the controller's orientation? Maybe the calibration routine is not working properly. The calibration routine is slightly different for a BT connection. It would be hard to determine that without running the program through a debugger.

Another thing to mention is that the starting orientation of the controller matters when you launch a client. Make sure to have the controller orientated with the touchpad facing up and the grips pointing towards you.

**Comment by kishelraj** [comment]
Hi Ryochan,

Thanks for the reply. I will test this again on another PC to see if the issue is still there.  Orienting the controller correctly as you described did not help. 

The only axis with this problem is the Yaw Axis which seems to be inverted. Pitch and Roll is working fine. Is there any configuration file i can edit to invert the axis on my end for the gyro?

**Comment by kishelraj** [comment]
Hi Ryochan,

I have confirmed this with another PC. Reinstalled with the latest drivers as well. All other axis's work fine except the Yaw which is inverted. 

I have taken a video of both cable and bluetooth behavior.. You will find that the axis for Yaw is inverted in bluetooth.

Controller with Cable
https://drive.google.com/file/d/1chgSkP-6A3JGdBifhc2YiPoF3PKfVca0/view?usp=sharing

Controller with Bluetooth
https://drive.google.com/file/d/1Xh7rieoNP3TC-0lKJcsgz1bZZ6NIlqfL/view?usp=sharing

I do not think the controller is faulty. However, I will test it on another controller once I get my hands on one.  

I just want to know if this issue is replicable on your end. Initially i thought nothing was wrong as well until i tried the Yaw Axis. 

Thanks Ryochan. Sorry if i am disturbing u guys, but I really would like to get this working. Take care.

**Comment by mika-n** [comment]
Your profile file works here, too. Tested it in PadTest using BT connected revision1 DS4 controller. I do have rev2 DS4 controller also, but haven't tested it via BT.

Anyway. The profile does have Sensitivity options set. This option shouldn't cause any "inverted axis" problems, but have you tried the PadTest with a new "empty default" profile file without any tweaks?

It will be interesting to hear how your setup goes with another DS4 controller, because at this point it looks like there are no problems in DS4Win app side. I know there are several people using DS4Windows app with Cemu, Dolphin or Wii emulation (using UDP server to feed gyro). 

Please post a video how the "Controller Readings" tab in DS4Windows looks like when you move the controller. There are graphical representations of LS/RS/L2/R2 and gyro axies.

**Comment by Ryochan7** [comment]
Not with something that works with the UDP server. The UDP server is set up to receive the raw input state without any form of mapping options being used. A temporary state object is used when performing the mapping calculations.

Can you provide a screen capture of PadTest while testing the controller? It might help.

**Comment by kishelraj** [comment]
Hi Ryochan,

No worries. Give me sometime as I will be testing out with another controller as my friend does not have this issue. It works perfectly. Will be heading to his place tomorrow with my laptop to confirm this issue. 

I am suspecting its an issue with the controller. If it's not I will provide the screenshot of the padtest as I dont want to was your time if its a controller issue.

**Comment by brainli13** [comment]
I have the same problerm,did you fix it?

**Comment by kishelraj** [comment]
Sorry for the late reply. I have given up and I am now using the controller in wired mode.

**Comment by mika-n** [comment]
As a test you might try to run "DS4WindowsDebug.exe" version of the app (DeviceDetectDebug zip file in the following page). This debug version won't change anything relating inverted gyro axis, but it shows a detailed log messages about the gamepad communication. If the gamepad sends some non-standard Sony DS4 hid messages then this debug log file should reveal that scenario.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

The debug version generates lost of additional messages in Logs tabpage of DS4Windows app.

Did you have a chance to test another DS4 gamepad (borrow from a friend)? The same issue with all ds4 gamepads in your PC or just this problematic one? 
Is gyro inverted in "Gyro to mouse" functionality (ie. gyro orientation is sent locally as a PC mouse movement) or just in UDP server?

**Comment by Ryochan7** [comment]
That is a shame. Unfortunately there is likely no way to correct this problem without debugging the gyro routine while using that hardware. The gyro calibration routine is similar to the routine used in the hid-sony Linux driver which was a departure from what was posted by rajkosto. His version did not work correctly for me in some cases; I think it might have been regarding Sony Wireless Adapter connections but I cannot remember.

**Comment by mika-n** [comment]
@kishelraj   Please see the linked post for a potential workaround to this "inverted gyro axis in BT" problem.
https://github.com/Ryochan7/DS4Windows/issues/929#issuecomment-566223663
