### ISSUE TITLE
Controller plugged into USB to charge becomes deactivated when waking from sleep

### ISSUE THREAD

**Issue by CorpusBava** [Ryochan7/DS4Windows#768]
Not a serious issue but when I leave my controller plugged into via USB to charge and continue playing with DS4Windows it becomes permanently disabled if I put my PC (Windows 10 box) into Sleep mode then wake my system.  I have to do a full system reboot to get it working again.  It appears to show as working in DS4Windows but games (ie Assassin's Creed Unity) won't recognize the controller anymore until reboot.  I'm on 1.6.13 (very stable for me) because I had issues with auto-switching profiles in later builds.

**Comment by mika-n** [comment]
There has been reports about high cpu usage after PC wakes up from a sleep. Here is a link to a thread discussing it and how to solve it by restarting DS4Win app before PC goes to sleep and auto-starting it when the PC wakes up.
https://github.com/Ryochan7/DS4Windows/issues/730#issuecomment-511190908

The next public release of DS4Win should have few improvements which may help both in automating the stop/start/shutdown of DS4Windows app through batch files attached to system events (going-to-sleep, woke-up-from-sleep events) and how auto-profiling thing works.
https://github.com/Ryochan7/DS4Windows/pull/745#issuecomment-510665102

There will be a new cmdline interface to shutdown (or just stop/start) DS4Windows app, so you could have a batch file doing following command when PC is going to sleep:
ds4windows.exe -command shutdown

And another batch file doing simple "ds4windows.exe" command to launch it automatically when PC wakes up from a sleep (or just start it through a desktop shortcut when needed).

Also, the auto-profile thing went through a complete re-write and it is now much more flexible and uses less CPU/RAM. 

See the following post for more info (note! This new feature is not yet released in public version, so keep eye on the new releases):
https://github.com/Ryochan7/DS4Windows/pull/745#issuecomment-510665102

**Comment by Ryochan7** [comment]
I don't support the use of any build older than 1.7; the old builds can be helpful for testing but nothing more than that. You are more than likely experiencing a bug with the ScpVBus driver than anything else. DS4Windows looks like it can detect and read reports from the original DS4 fine. ScpVBus is likely exposing an old handle for a now dead virtual controller.

A workaround for a suspend issue was recently implemented but even that problem was driver related.
