### ISSUE TITLE
CAnnot install ViGEmBus Driver......

### ISSUE THREAD

**Issue by brothan323** [Ryochan7/DS4Windows#769]
Here's the error I get. This program is getting VERY annoying.

See the end of this message for details on invoking
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.IOException: The process cannot access the file 'C:\DS4Windows\ViGEmBus_Setup_1.16.115.exe' because it is being used by another process.
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.File.InternalDelete(String path, Boolean checkHost)
at DS4Windows.Forms.WelcomeDialog.bnStep1_Click(Object sender, EventArgs e)
at System.Windows.Forms.Control.OnClick(EventArgs e)
at System.Windows.Forms.Button.OnClick(EventArgs e)
at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
at System.Windows.Forms.Control.WndProc(Message& m)
at System.Windows.Forms.ButtonBase.WndProc(Message& m)
at System.Windows.Forms.Button.WndProc(Message& m)
at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
************** Loaded Assemblies **************
mscorlib
Assembly Version: 4.0.0.0
Win32 Version: 4.7.3416.0 built by: NET472REL1LAST_B
CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
DS4Windows
Assembly Version: 1.7.12.0
Win32 Version: 1.7.12
CodeBase: file:///C:/DS4Windows/DS4Windows.exe
Microsoft.Win32.TaskScheduler
Assembly Version: 2.8.0.0
Win32 Version: 2.8.0.0
CodeBase: file:///C:/DS4Windows/Microsoft.Win32.TaskScheduler.DLL
System.Windows.Forms
Assembly Version: 4.0.0.0
Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
System
Assembly Version: 4.0.0.0
Win32 Version: 4.7.3416.0 built by: NET472REL1LAST_B
CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
System.Drawing
Assembly Version: 4.0.0.0
Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
System.Xml
Assembly Version: 4.0.0.0
Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
System.Configuration
Assembly Version: 4.0.0.0
Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
System.Core
Assembly Version: 4.0.0.0
Win32 Version: 4.7.3429.0 built by: NET472REL1LAST_C
CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by brothan323** [comment]
Here's some more error when trying to install the driver....
Problem Event Name:	CLR20r3
  Problem Signature 01:	ViGEmBusInstaller.exe
  Problem Signature 02:	1.0.0.0
  Problem Signature 03:	f21da374
  Problem Signature 04:	System
  Problem Signature 05:	4.7.3416.0
  Problem Signature 06:	5cabfe3e
  Problem Signature 07:	a1e
  Problem Signature 08:	20
  Problem Signature 09:	System.Net.WebException
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	4105
  Additional Information 1:	a63a
  Additional Information 2:	a63a939facc0011561ccce81ddb87480
  Additional Information 3:	f9e0
  Additional Information 4:	f9e012df6c499318a6000a40c5e581b4

**Comment by brothan323** [comment]
Solved it. I had to go here https://github.com/ViGEm/ViGEmBus/releases and download the driver. Some part of the old installation was still kicking around.

**Comment by King-Spartacus** [comment]
> Solved it. I had to go here https://github.com/ViGEm/ViGEmBus/releases and download the driver. Some part of the old installation was still kicking around.

No matter how many times I installed it in the application/rebooted/ran as admin/etc it wouldn't stick. Yours is what got me through. Thank you so much!
