### ISSUE TITLE
Doesn't appear in the start menu

### ISSUE THREAD

**Issue by Ariane-B** [Ryochan7/DS4Windows#770]
Since we only "install" this program by opening a zip, Windows doesn't recognize it as a program to put in its list. So it's not available in the Start menu like the others. I kind of wish I could launch DS4windows by just typing part of its name in the Start menu, and pressing Enter, like I do other programs. Is there a way to do this?

**Comment by mika-n** [comment]
You can pin the DS4Windows.exe executable to Start menu via FileExplorer. Just select the EXE file and choose "Pin to start menu" option from right mouse context menu. After this you can even unpin the app from start menu and the app searching continues to find the executable

**Comment by Ryochan7** [comment]
It is a semi-portable application. It is not supposed to appear in the Start Menu. You would have to Pin the app to your start menu to have a link accessible there.

**Comment by Ariane-B** [comment]
Would it be complicated to also have an "installed" option?

**Comment by Ariane-B** [comment]
I found a solution to add it to the programs directory :
https://superuser.com/questions/493716/add-programs-to-start-menu-search-without-adding-a-tile

Should have looked it up earlier honestly. You saying the words "portable application" kind of woke me up.
