### ISSUE TITLE
Joysticks (usually left) drifting in one direction 

### ISSUE THREAD

**Issue by kik4444** [Ryochan7/DS4Windows#773]
Lately my left joystick has been acting weird. I don't think it's a hardware issue because when I last used ds4windows there were no problems. Now however my left joystick randomly starts moving to the left rapidly. Usually it's only very slightly, but other times it drifts all the way to the left so setting a deadzone is useless. I have tested this with two bluetooth devices with the same controller on the latest version of ds4windows and it's all the same, so I don't think the problem is from my connection either (since I've always connected through bluetooth and this did not happen earlier). However I've noticed this does not happen with a usb connection. 

Any idea what this is?

**Comment by Ryusennin** [comment]
Try without DS4Windows, but it looks like an electronic issue.

I've got a brand new DS4 rev2 controller which has been similarly acting up after only a couple of months (BT or USB). I could somehow mitigate the random drifting by setting an outer dead zone ("max zone") of 0.75.

Ironically, my 4-year old rev1 has no such problems. I blame Sony for their cost reductions leading to poor manufacturing.

**Comment by kik4444** [comment]
I've switched back to version 1.7.10, so far I don't have this problem on this ver but I haven't tested it enough to be sure. I'll report back when I'm certain whether the problem is gone or not.

**Comment by mika-n** [comment]
If gamepad or DS4Win mapping behaves strange after DS4Win upgrade then try cleaning all existing config files and profile files and let the new version to create new default config files. Sometimes there has been cases where some weird profile option combination has caused ghost bugs.

**Comment by kik4444** [comment]
Nope it still happens on ver 1.7.10. Will try mika's solution and delete my config files and take it from there.

**Comment by kik4444** [comment]
Tried it some older versions and the newest versions after deleting my config folder both times, but the problem still happens, this time mostly with the right stick which keeps going all the way up and blinking up and down faster than any human could move their thumb. What's causing this?

**Comment by kik4444** [comment]
As counter-productive as it sounds, I've went all the way back to ver 1.4.52 from jays2kings. Took forever to connect my controller through bluetooth, but now that it works, so far it doesn't have this same problem. Though I was wrong before, so I'll have to test it for one more day to make sure whether it's alright.

**Comment by Ryochan7** [comment]
If it does not happen with a USB connection then this does not really make much sense. The input parsing is practically the same with a different data offset for the BT input report. How have you confirmed the problem? Is the behavior apparent in the Controller Readings tab? Just be aware that there is no locking performed so it is possible that the state might get reset while rendering those controls. The readings could be off sometimes.

Does it happen while playing a game? If that is the case then maybe it would be a problem with DS4 state to ViGEmBus translation routine? Besides playing a game, HTML5 Gamepad Tester is a great tool for examining the input from various controllers. I use it frequently to test the state of emulated controllers.

https://html5gamepad.com/

Also, have you done thorough checks in Windows Game Controller settings to make sure that the original DirectInput controller does not exhibit the same behavior? You would have to connect and test the controller while DS4Windows is **NOT** running . There is always the possibility that this is just a mapping conflict which could be detected by sharing the file.

Since you are trying a version that uses the old ScpVBus driver, maybe you can also give version 1.6.14 a try. That was the last version of this fork of DS4Windows to use the ScpVBus driver.

https://github.com/Ryochan7/DS4Windows/releases/tag/v1.6.14

**Comment by kik4444** [comment]
On the latest 1.7.12 I never played very long with a USB connection, but every time the sticks were acting up, if I plugged it through USB they stopped behaving weirdly. Although on ver 1.7.10 it still happened even through USB. And the weird motions in the controller readings tab are real since they are reflected in games too.

I haven't tested it for very long with https://html5gamepad.com/, but so far everything in it seems fine. And the windows wireless controller properties also show stable motions.

The weird thing is that when I moved to 1.7.10 the weird motions didn't start until a little bit after I began playing something, but when I tried even older 1.7 and 1.6 versions (that were newer than 1.6.14), the weird readings started almost immediately after I moved the joysticks. In one of the older versions actually it was the right stick that was acting up instead of the left one.
So all in all, I don't know how trustworthy these results are at the moment, but so far the problem does not occur with html5gamepad nor with the original 1.4.52.

And again, I'll need to test it more thoroughly, but so far it did not immediately go haywire with ver 1.6.14

**Comment by mika-n** [comment]
Did you test your PC with another ds4 gamepad? Or the problematic pad on another PC?

Maybe you should zip and post the ds4windows profile file here?

**Comment by kik4444** [comment]
I don't have another pad. And it happened on my laptop too with my current one. However so far I've been playing around with ver 1.6.14 for around an hour so I can semi-confidently say the problem does not happen on this version.

**Comment by kik4444** [comment]
I'm now trying another experiment with a BT poll rate of 500Hz on the latest version...

**Comment by Ryusennin** [comment]
You still haven't confirmed if this drifting issue happens without DS4Windows. It might be a general problem with your Bluetooth connection.

**Comment by kik4444** [comment]
> You still haven't confirmed if this drifting issue happens without DS4Windows. It might be a general problem with your Bluetooth connection.

Well I only used html5gamepad for about 15 minutes and check windows's gamepad settings for less than that and they didn't have any problems, but I can't check any games right now cause they don't work with the pad without ds4windows. And again I don't think the issue is from my BT cause the very first time I used ds4windows when I discovered it with the last jays2kings version, I went over 2 games without issues.

**Comment by kik4444** [comment]
Man this has gotten a bit confusing so let me try to write down everything I know about the stick motion bug on each version on DEFAULT settings:

1.7.12: The bug appears relatively quickly on BT but seemingly does not happen through USB

1.7.10: The problem is present on both BT and USB but it took a while to manifest after switching to this version.

1.6.14: I played for several hours on BT with no issues but it did appear to me that the bug re-appeared for a brief moment when I was playing with my friend, but disappeared after I upped the BT poll rate to 300hz. Also playing with USB on this version sends double input.

1.4.52: I haven't spent as much time on this ver as I have on the others, but with the limited time that I did spend I didn't see the bug at all with either BT or USB. The only problem was that it was difficult to get it to detect the controller through BT.

Bonus: I spent about 15 mins on https://html5gamepad.com/ and windows's gamepad settings window WITHOUT ds4windows and they didn't have this bug.

Currently I've gone back to ver 1.7.12 and I've upped the poll rate to 500hz because it had promising results last time, but I won't know for certain if this fixes it until later.

**Comment by kik4444** [comment]
I've come back after playing for more than a full day on version 1.7.12 with a BT polling rate of 500hz. I haven't tried playing in coop with my friend, but so far it hasn't had the drifting problem in any of the spots it did before.

**Comment by Ryochan7** [comment]
Last time someone brought up an issue like this, the problem just ended up being that the person enabled 360 Steering Wheel mode for the gyro while not setting explicit dead zones. The gyro and LS would conflict and the output stick coordinate would be jittery. Steering wheel mode is processed later in the mapping process so the sixaxis controls would be used if both gyro and LR/RS is outside of their assigned dead zones.

Having access to the profile being used might be helpful.

**Comment by kik4444** [comment]
After playing for more than a week, both in local coop with my friend and on my own, I think I can safely say the bug is currently gone. I went back to version 1.7.12 and the only difference between now and back in the beginning is that now I increased the BT poll rate to 500hz. I'm not sure if that's the cause, but the problem is definitely gone for now.
