### ISSUE TITLE
Quick Charge option should check if a controller was plugged before disconnecting it from Bluetooth

### ISSUE THREAD

**Issue by mbc07** [Ryochan7/DS4Windows#778]
So, I have Quick Charge option enabled and it works as it should if, for example, I'm playing through BT, then connect the controller with an USB cable to the same PC. However, I noticed an edge case which wasn't accounted for: charging the controller with an external charger (e.g. a phone charger, power bank, etc)

From what I figured out, when Quick Charge is enabled, DS4Windows simply queries controllers connected through BT to see if they are discharging or recharging. If it detects a controller connected through BT is recharging, it simply disconnects it and hope the controller itself reestablishes the connection through USB.

However, on the scenario that the controller was plugged to a Power Bank, Wall Charger, etc., the controller will simply keep being constantly disconnected by DS4Windows and it obviously won't reestablish the connection through USB because the cable is plugged to something else (on this scenario, an external charger).

I'm not familiar with the code of DS4Windows but perhaps checking if a new wired controller with the same ID as a currently connected BT controller in recharging state "arrived" to the PC before sending the disconnection command to the controller should be enough to cover this edge-case?

**Comment by Ryochan7** [comment]
I think I have run across this type of scenario but I am not sure if it was here or the Jays2Kings issue tracker. The main issue would be what should be given responsibility for this action. I think I had tried this in DS4Devices but I cannot remember why that experiment failed. I doubt that I have an old diff around from when I tried this.

I will give this a try again.

**Comment by dougshell** [comment]
This isn't really directly related, but I think it may be appropriate to discuss here.  I do not use the USB port on my controllers to charge. Far too many broken ports or loose micro USB ports over the years that I try to avoid it. 

I use an ext port docking charger and would love plugging it into the charging port to automatically disconnect the Bluetooth connection in this case as well

**Comment by Ryochan7** [comment]
Long lost issue. Anyway, I finally made an implementation that seems to work fine.

f5717e62540cf9e1e684bd36d3fa74926d694f6b

**Comment by Ryochan7** [comment]
A fix is finally available in version 2.1.10.

https://github.com/Ryochan7/DS4Windows/releases/tag/v2.1.10
