### ISSUE TITLE
Controller Detected by DS4 Windows but not work

### ISSUE THREAD

**Issue by pcaben** [Ryochan7/DS4Windows#781]
When i connect my DS4 controller with usb, I got below log message and the bottom left show "Controller 1 is using Profile “Default" .

1/8/2019 15:08:15: Found Controller:00:1F:E2:F0:68:DE (USB)
1/8/2019 15:08:15: Plugging in X360 Controller #1
1/8/2019 15:08:15: X360 Controller #1 connected
1/8/2019 15:08:15: Controller 1 is using Profile “Default"

However, the Controller "page" show  "No controllers connected (Max 4)" and not thing happen, no light and no input in Controller Readings (Profile Setup). I can find the original wireless controller and the Xbox 360 controller created by DS4 windows in control panel, but the Xbox 360 controller is not receive any input in the gamepad testing.

Actually, I making something in Unreal Engine 4 and I have use the old version DS4 windows before, it was perfectly work until one day with no reason. Then I switch to using 360ce for my DS4 controller, but now I want to add force feedback in my project and just recognize 360ce not support  force feedback for DS4 controller.

I using Window 10 (ver.1809), DS4 controller made at 2016.11,uninstalled the old version and Virtual Bus driver from old DS4 windows, already try close all the software and platform related with game include Nvidia, Run the program as administrator and stop antivirus software.

**Comment by mika-n** [comment]
- Try to uninstall old ViGem driver (and ScpVBus driver if it is still lying around in your PC). When you uninstall a driver via DeviceManager then remember to tick option "remote driver store files" also.
- If you are using HidGuardian driver then uninstall it also to start from scratch.
- Reboot
- Download the latest DS4Windows version: https://github.com/Ryochan7/DS4Windows/releases

Now try to install the latest DS4Windows again and it should prompt to install ViGem driver again if the old vigem driver was successfully removed.

**Comment by Ryochan7** [comment]
So DS4Windows detects a controller but an input report is never received from the controller? That is the only circumstance when the program would behave that way. That should never happen. You might want to check the DS4 controller status in Devices and Printers section of the Control Panel. Open the Game Controller settings window for that DS4 controller and make sure Windows can read any input from the controller.
