### ISSUE TITLE
Dualshock 4 v2 doesn't work wirelessly with a Laptop?

### ISSUE THREAD

**Issue by Morlino** [Ryochan7/DS4Windows#782]
It was working well for over a year with a ds4windows. When last time it was connected i plugged a usb in when it was connected via Bluetooth. But when i unplugged a USB controller, it stopped working via Bluetooth. Controller is connected/Paired to PC but InputMapper, DS4Windows, Steam's Big picture mod desn't see the controller. 
Any ideas what's wrong with my controller, laptop or program?

**Comment by mika-n** [comment]
Have you gone through BT connection/re-connection steps described in the Troubleshooting documentation page?
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting

Try removing the BT pairing and re-pair the controller to PC (and make sure the DS4 gamepad doesn't connect to PS4 console when you press the "PS" button).

Are you using HidGuardian tool to hide the physical controller and leaving just virtual output controller visible to apps?

**Comment by Ryochan7** [comment]
This issue has been solved on Discord. It seems like it was some random fluke with Windows not related to DS4Windows. Windows being Windows.

**Comment by tkytky** [comment]
Hi what is the random fluke ? And how did morlino resolve the issue ?
