### ISSUE TITLE
Battery Level Issue

### ISSUE THREAD

**Issue by HawkEye4** [Ryochan7/DS4Windows#783]
When the controller is connected via bluetooth, battery level is always 0% and the controller light keep blinking. When is connected with USB Cable, battery level shows correctly and there are no problems.

Thanks you.

DS4 Version: 1.7.14
ViGEmBus Version: 1.16.112.0

**Comment by mika-n** [comment]
Are you using an official Sony DS4 gamepad or some 3rd party compatible controller? If it is a 3rd party controller then could be that it registers a bit different battery level values than DS4Win app expects to receive.

If you use an official Sony gamepad then 
- try disabling "Quick charge" option in DS4Windows app (Settings screen, not a profile specific option).
- try tweaking battery "flash at/while charging/color by battery" options in a profile settings.

Anyway. I don't have such a problem in V1.7.14 and Sony controllers (revision 1 and revision 2 gamepads), so maybe it is a controller specific issue or BT chipset issue?

**Comment by HawkEye4** [comment]
I'm using an official Sony DS4 gamepad and i have already changed the "flash at/while charging/color by battery" without success. I noticed that the problem only happens when the controller has a very low battery (around 9-10%). After a partial recharge, the level shown is right again. I will try to disable the Quick Charge.

**Comment by mika-n** [comment]
Aah okey. The battery level value reported by DS4 controller is actually a rough approximation (at least in PC, maybe the controller sends more detailed into to PS4 console), so the behavior you are seeing is probably normal.

USB connection has a bit more range (0...11) in battery level indicator than BT (0...8) connection in PC.

**Comment by Ryochan7** [comment]
The controller is very likely broadcasting 0 for the battery level. The level can be at the 0% level for over an hour before the battery will be drained. The level broadcast by the controller will likely change the moment you plug in a USB cable.

**Comment by HawkEye4** [comment]
> The controller is very likely broadcasting 0 for the battery level. The level can be at the 0% level for over an hour before the battery will be drained. The level broadcast by the controller will likely change the moment you plug in a USB cable.

Is the exact same thing that happen to me, battery level at 0% with BT, connecting the USB cable show right level.
