### ISSUE TITLE
Bezier Curve Function not opening in web page 

### ISSUE THREAD

**Issue by biskits3** [Ryochan7/DS4Windows#784]

**Comment by mika-n** [comment]
By default the "Output Curve / Custom / Custom curve editor" web link tries to use the default browser to open the bezier curve web editor.  This works at least for IE and Chrome browsers. If the default browser is not found then it falls back to use IE browser.

What is your default web browser in Windows settings? 
What do you have in HKEY_Current_User\Software\Microsoft\Windows\Shell\Associations\UrlAssociations\http\UserChoice sysreg entry? You can use sysreg.exe tool to see the content of this reg entry.
Do you have Win7 or Win10?
Do you have BezierCurveEditor\index.html file in DS4Windows installation folder?
Where have you installed DS4Windows app? Are there any special characters in the folder path?

Anyway. If the "custom curve editor" web link doesn't work then as a temporary workaround you have open "<ds4win install folder>\BezierCurveEditor\index.html" web page directly by double clicking it in FileExplorer. It should open the editor in your default browser and then you can copy-paste the existing custom value from DS4Windows custom curve definition field to custom curve field in the web app.


https://github.com/Ryochan7/DS4Windows/wiki/Settings#output-curve
And here is an online version of the web editor: http://htmlpreview.github.io/?https://github.com/Ryochan7/DS4Windows/blob/jay/DS4Windows/BezierCurveEditor/index.html

**Comment by mika-n** [comment]
V1.7.15 release probably solves this issue because the custom bezier output curve web editor was accidentally missing from V1.7.14 installation zip file.
https://github.com/Ryochan7/DS4Windows/releases
