### ISSUE TITLE
Minor typo in UI

### ISSUE THREAD

**Issue by keatsandyeats** [Ryochan7/DS4Windows#789]
Profile tab > Hover over the Duplicate button
The hover text says "Dupliacate" instead of "Duplicate" (note the extra "a").
Apparently that's been there since the Jays2Kings days. 
https://github.com/Ryochan7/DS4Windows/blob/b99b4fbbc045d704e5464235a1faff6187a76907/DS4Windows/DS4Forms/DS4Form.resx#L1819

**Comment by Ryochan7** [comment]
That is an interesting typo. I never even hovered over those buttons long enough to know that a tool tip existed.
