### ISSUE TITLE
[Enhancement] Special Action "Disconnet BT" also disconet controller from Sony Dongle

### ISSUE THREAD

**Issue by pralima87** [Ryochan7/DS4Windows#79]
This is a small request for consideration.

The feature "Disconnect BT" from the Special Actions menu only works for Bluetooth connections.
So I would be great if it could also disconnect controllers connected to the sony dongle.

PS: Thanks so much for the new feature "Change for Sony dongle connection to only have a virtual XInput controller available if a controller is synced to the dongle" really great!!

**Comment by Ryochan7** [comment]
This topic has been discussed recently under issue #70. I have fiddled with the code a bit and I have managed to get the Disconnect BT special action routine to cooperate. There were some initial problems that occurred after enabling it such as the controller no longer being able to reconnect. It seems like those issues have been resolved and enabling the functionality should be feasible.

**Comment by pralima87** [comment]
Nice them this is a duplicate ;)
