### ISSUE TITLE
How to make it work?

### ISSUE THREAD

**Issue by TerracottaPlombir** [Ryochan7/DS4Windows#790]
Simply put, I am new to GitHub. I found out that the new versions of DS4Windows were here (and thank you for making this so much). 
I downloaded the zip files and extracted them with Winrar to a "DS4Windows" folder I created in Windows (C:)> Program Files 
My issue is that I can't find a way to execute it. I can only find files of text. 
Maybe the solution is pretty simple and I'm just being stupid, maybe I missed something, but is there a solution to this problem? I would be grateful to anyone willing to help. 
Thank you for taking your time to read my issue.

**Comment by mika-n** [comment]
I think you have confused GitHub source code package and the DS4Windows application delivery package. GitHub is mainly used to host the source code of the project and collaboration platform between developers all around the world. It is just a bunch of text files and only application developers have any use for those files. I think you acceidentally downloaded this source code package.

If you want to just use the DS4Windows app to play games with DS4 controller or re-map keys/keyboard/mouse to DS4 gamepad then you should download the app package from Releases page. Please try again by downloading the latest release from the following page:
https://github.com/Ryochan7/DS4Windows/releases

There is DS4Windows_1.7.15_x64.zip package and if you unzip it to c:\apps\DS4Windows\folder (or any other folder you prefer to use) then you will get DS4Windows.exe executable and you don't have to worry about those source codes.

**Comment by TerracottaPlombir** [comment]
Hey, thank you so much! I may have confused the source code with the app package. Problem is, I came here from a forum, so I think more people will come here and make that same mistake. Thank you for the help tho!
