### ISSUE TITLE
Typos in UI and in code

### ISSUE THREAD

**Issue by keatsandyeats** [Ryochan7/DS4Windows#791]
I should probably have checked the rest of the hover text before reporting #789, oops.  

There are two related typos here:
1) Profiles tab > Hover over the Delete button  
The hover text says "Delete Selected Profle" instead of "Delete Selected Profile" (note the missing "i").  
https://github.com/Ryochan7/DS4Windows/blob/a54254edfef25cb9459691207cdf2eff6dc854c4/DS4Windows/DS4Forms/DS4Form.resx#L1807  
2) All over [DS4Form.resx](https://github.com/Ryochan7/DS4Windows/blob/a54254edfef25cb9459691207cdf2eff6dc854c4/DS4Windows/DS4Forms/DS4Form.resx) (and its translations), and [DS4Form.cs](https://github.com/Ryochan7/DS4Windows/blob/a54254edfef25cb9459691207cdf2eff6dc854c4/DS4Windows/DS4Forms/DS4Form.cs), "profile" is spelled "profle". This may not strictly be a bug, since I assume everything is internally consistent and working fine.

**Comment by Ryochan7** [comment]
That string is the only one that is visible in the interface so that will get changed. Profile is misspelled for many methods and one button identifier but I am not going to worry about risking performance changes to fix those typos. Thank you for pointing out the typos.
