### ISSUE TITLE
Can't bind DS4's touchpad to original button (select)

### ISSUE THREAD

**Issue by Viscerous** [Ryochan7/DS4Windows#795]
So I've been trying out DS4 mode some, and it looks like you can't set it to use the touchpad for its original intended purpose? I've been playing a game that treats the touchpad as select as it originally was but it doesn't recognise the input, haven't been able to find the option in the mapping menu either.

EDIT: Okay then, after some more fiddling I found that unbinding all the 'touch' buttons works. Maybe it's a good idea to make the touchpad available as option when remapping instead of needing to unbind it? It seems a bit counter-intuitive. Currently the touchpad is unavailable when you try to select it in the mapping menu.

**Comment by Ryochan7** [comment]
DS4 mode in ViGEmBus does not support mapping the touchpad beyond the touchpad click button. It only supports the controls available in the DS4 DirectInput interface. That means no touchpad and no gyro data support.

**Comment by Viscerous** [comment]
Yeah but the problem was that by default it's used as a mouse, and setting "Use touchpad for controls" still doesn't make the touchpad click work in games with native DS4 support. I had to unbind the top four first before it actually worked as it should: 
![Annotation 2019-08-23 200347](https://user-images.githubusercontent.com/7198087/63613469-258fb800-c5e1-11e9-819b-d37779bd78b7.png)

Which is kind of counter-intuitive to figure out in the first place. Hence making at least the native DS4 button here available might make more sense:
![Annotation 2019-08-23 200605](https://user-images.githubusercontent.com/7198087/63613614-730c2500-c5e1-11e9-92c7-ab87d2839ae2.png)

All of the native buttons are available except for touchpad click.

**Comment by Ryochan7** [comment]
Part of the problem stems back to the assumption that the touchpad would almost always be used as a virtual mouse. The virtual touchpad buttons are listed in the mapping list but they are at the bottom. Maybe it would have been better if the virtual touchpad button mapping  were more directly tied to the output mode.

The lack of transparency with the touchpad click is my fault. That is not available as an output binding and can only be bound to the state of the real touchpad click. I figure that adding remapping support for the touchpad click was not worth worrying about. The big reasons being that there is no Xbox 360 equivalent to bind to and Rocket League's DS4 support does not utilize the touchpad click event.

**Comment by Viscerous** [comment]
Yeah that's to be expected, it's not like support is very widespread. In this case tried playing _Observation_ and figured I'd test the new DS4 mode, but that's actually one of the games that needs the touchpad click as the original intended 'select' substitute, so I was basically just figuring out why it wasn't accepting the input.
