### ISSUE TITLE
Infinite Gyro drift with latest release 

### ISSUE THREAD

**Issue by mashakos** [Ryochan7/DS4Windows#797]
Tested using:
- wired usb
- official sony ds4 bluetooth dongle
- PadTest

on both wired and bt connection types the controller continuously rotates around the gyroscope yaw axis. Reverting to rajkosto's DS4Windows v1.4.94-patch1 fork, the same issue does not occur.

**Comment by Ryochan7** [comment]
Finding the root of the problem would require debugging the program when using that hardware. Gryo works on my end perfectly fine with any connection type. The calibration routine of the forked code was wrong when using a Bluetooth connection.

**Comment by mashakos** [comment]
I'm running this on Windows 7 if that helps

**Comment by Ryochan7** [comment]
Going to have to file this under Works For Me. There is nothing I can do without direct access to the hardware.
