### ISSUE TITLE
Vibration issues

### ISSUE THREAD

**Issue by Kqliber** [Ryochan7/DS4Windows#798]
hi
I just recently started playing rocket league on PC with ds4w (used to play on ps4 before) and there is no vibration ingame. Vibration is enabled in ds4w and ingame. When i test the vibration in the software it works fine.

**Comment by Ryochan7** [comment]
You have to emulate an Xbox 360 controller to get rumble support. Using the controller as a DS4 won't work because the game does not support DirectInput force feedback.

**Comment by Kqliber** [comment]
how do i do this? I changed the controller settings to xbox 360 in the profile settings but its still the same. am i missing something else?

**Comment by Ryochan7** [comment]
Does DS4Windows have exclusive access to the DS4? You would have to check the Log tab to find out. An icon in the controller listing would be preferable but performance issues occurred anytime I tried to add one. Anyway, if DS4Windows does not have exclusive access to the controller, there might be the chance the game would use the original DS4 DInput controller handle. Other than that, it should work just fine. I can test it again but it will probably work.

**Comment by Kqliber** [comment]
my fault. I thought I had the program running in exclusive mode before as I had no errors in the log. However I tried just pressing stop and start on the program and it fully booted into exclusive mode.
