### ISSUE TITLE
DS4 emulation don't work

### ISSUE THREAD

**Issue by jinkazama82it** [Ryochan7/DS4Windows#799]
I don't know from when but at the moment when ds4windows is in run steam don't recognize the ds4 not the emulated (on profile option) not the main with hide option disabled, a restart of the pc don't changes or solve the issue.

Actually the only way to make visible the ds4 controller to steam is to stop ds4w and reinstall the ds4 driver (is indifferent if is plugged via usb or official Wi-Fi dongle).

one more thing, when ds4w ruining steam recognize the controller only if a x360 is emulated.

**Comment by mika-n** [comment]
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#steam-doesnt-see-the-virtual-output-controller-if-a-profile-uses-the-dualshock4-output-type-steam-sees-the-ds4-controller-only-if-ds4windows-uses-xbox360-output-controller-type

**Comment by jinkazama82it** [comment]
oh, this is new for me... that idiot of stream developer... why steam developer need to bother user in this way?
anyway thanks for the fast reply and fast solution.
