### ISSUE TITLE
Sony dongle Idle disconnect virtual XInput

### ISSUE THREAD

**Issue by pralima87** [Ryochan7/DS4Windows#80]
Regarding the new feature: 
"Change for Sony dongle connection to only have a virtual XInput controller available if a controller is synced to the dongle"

When the controller is disconnected in the idle option the virtual XInput will remain available.
Now sure if is possible that it could stopped.

**Comment by Ryochan7** [comment]
It works for me when idle disconnect is enabled. The DS4Windows slot associated with the dongle will still remain and be seen in the application but no associated XInput controller should be seen by the system. One use case that I have found when a virtual XInput controller can end up getting connected is if profiles are switched. Code has been added to fix that problem.

**Comment by pralima87** [comment]
Oh right!
I'll close this since is a duplicate them ;)
