### ISSUE TITLE
nacon revolution unlimited v3

### ISSUE THREAD

**Issue by asp0909** [Ryochan7/DS4Windows#800]
please add full compatibility, with the nacon revolution unlimited! I want to map the back buttons with keyboard keys!...... please!

**Comment by mika-n** [comment]
It may be a bit difficult to add support to those non-standard DS4 gamepad buttons if noone who can debug, develop and test that feature doesn't have that controller.

**Comment by Ryochan7** [comment]
All I could do is ask for you to provide the hardware IDs for the controller, have you run a test build and hope for the best. You can pull the Hardware IDs from the Device Manager. Make sure to locate the proper HID-compliant game controller; Devices and Printers section of the Control Panel can help with that. Here is an example of the exposed Hardware IDs for the Sony Wireless Adapter.

![hardware_ids_example](https://user-images.githubusercontent.com/581968/63905090-b519da00-c9d8-11e9-80ea-c9ce8ef693f9.png)

**Comment by mika-n** [comment]
@asp0909   How is it? I understood that the Nacon controller you have already works in DS4Windows app using the standard DS4 buttons, but just that those 4 extra buttons on the backside of the controller (non-standard gamepad keys found only in this after market gamepad) are not recognized by DS4Windows app and cannot be used in re-map and macro rules.

Or did you mean that the controller is not recognized at all in DS4Windows?

**Comment by asp0909** [comment]
so that these 4 back buttons can be mapped independently

**Comment by mika-n** [comment]
@asp0909  I doubt that there will be support for those 4 extra buttons because it would require someone with an actual hardware to debug it and to see how the gamepad reports those extra button events (for sure part of USB/BT report data packets but where exactly in that buffer?). And then GUI interface of DS4Win app should be updated to support mapping of those 4 extra button. Not likely to happen anytime soon.....

**Comment by Ryochan7** [comment]
I was under the assumption that you needed a dedicated program to map those back buttons to become duplicate DS4 buttons. Those extra buttons are not represented in the standard DS4 input report afaik. It would take someone with the hardware to debug the protocol used to interact with the controller and maybe set up a different reader for its unique input report when in PC advance mode. That task is not feasible.
