### ISSUE TITLE
DS4 wont work on Wolfenstein young blood

### ISSUE THREAD

**Issue by DazzaPM** [Ryochan7/DS4Windows#801]
I received Control and Wolfenstein young blood, the latter is the issue with no DS4 working at all.

**Comment by Ryusennin** [comment]
You don't provide enough information.

Which OS? Which platform (Steam, etc)? What do you mean, the DS4 is "not working"? USB? Bluetooth? Can you see it in Windows? Have you tried without DS4Windows?

**Comment by DazzaPM** [comment]
> You don't provide enough information.
> 
> Which OS? Which platform (Steam, etc)? What do you mean, the DS4 is "not working"? USB? Bluetooth? Can you see it in Windows? Have you tried without DS4Windows?

Windows 10 64 bit
Bethesda client
The controller will power on as normal, over blu-tooth but the game wont recognise the emulation.
Xbox one controller works fine.

**Comment by mika-n** [comment]
please see Troubleshooting tips at first:
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting

Version of DS4Windows?
Provide the content of the logfile from DS4Windows app.
Do you use a DS4Win profile with x360 output mode or dualshock4 output mode?
Do you see the virtual output controller in Joy.cpl Windows control panel?
Does it work with other games, but Wolfenstein is the only one having issues?

**Comment by DazzaPM** [comment]
> please see Troubleshooting tips at first:
> https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting
> 
> Version of DS4Windows?v1.7.15
> Provide the content of the logfile from DS4Windows app. no errors, controller connects to sw correctly but doesn't hook into game.
> Do you use a DS4Win profile with x360 output mode or dualshock4 output mode?Xbox360
> Do you see the virtual output controller in Joy.cpl Windows control panel?Yes
> Does it work with other games, but Wolfenstein is the only one having issues?Yes, possibly the Bethesday client,which is not too widely used.

**Comment by Ryochan7** [comment]
Get a refund and pick up a copy of Return to Castle Wolfenstein instead.
