### ISSUE TITLE
Cannot Set Custom Brightness for Rainbow Mode

### ISSUE THREAD

**Issue by LimitedEdiition** [Ryochan7/DS4Windows#802]
I understand that you can adjust the brightness for default static colors by using the slider, but I would like to set the brightness option for always rainbow mode without having to use the dim by battery % option. Something like a universal slider?

**Comment by Ryochan7** [comment]
There is no true brightness setting for the LED. You can only choose to use a darker color to fake dimming the lightbar. Rainbow mode is done through calculations that affect the hue level and the dim by battery % affects the saturation level; not using the option invokes full saturation all the time. I guess a slider can be added to affect the maximum saturation level so darker colors are used more often.

**Comment by Ryochan7** [comment]
This is now possible in version 1.7.17. The new setting acts as a multiplier for the saturation level. It does do its job though.
