### ISSUE TITLE
Any chance to make non-sony PS4 C. get detected?

### ISSUE THREAD

**Issue by TuWHe** [Ryochan7/DS4Windows#803]
I have a Steel Play Metaltech wired controller, shows up as P4 Wired Gamepad.

I have uninstalled both DS4Windows and HID game controller driver, rebooted PC as well.

Windows 10 detects input in Game Controller Settings

Log:
30/08/2019 01:55:17: DS4Windows version 1.7.15
30/08/2019 01:55:17: LinkedProfiles.xml can't be found.
30/08/2019 01:55:17: Starting...
30/08/2019 01:55:17: Connection to ViGEmBus 1.16.112.0 established
30/08/2019 01:55:17: Searching for controllers...
30/08/2019 01:55:17: Using Shared Mode

Thanks for your time.

**Comment by mika-n** [comment]
See #800  Navcon Controller v3 issue ticket for a tip how to check the vid and pid identifiers of the controller. Provide that

**Comment by mika-n** [comment]
Following post discusses about adding a support to Raizu Ultimate Edition gamepad controller. Eventally it started to work over USB connection, but never worked over BT connection. But the point of this post is to run a special debug version of DS4Windows app to get a list of all HID devices DS4Win app detects. One of those is hopefully your controller.

Please see this post and if you don't know how to find out the HID device information for your coontroller then download the "DS4Windows_RazerUltimateBTDebug2.zip" package and run that version of DS4Windows.exe executable (replace/backup existing DS4Windows.exe or place the new EXE with a new name to the same folder with your existing DS4Win installation): 
https://github.com/Ryochan7/DS4Windows/issues/689#issuecomment-493413784

The Logs tab page should show list of HID devices and hopefully one of those is an identifier of your 3rd party DS4 gamepad. Using that information it may be possible to add a support to a new controller.

**Comment by mika-n** [comment]
@TuWHe  Are you still interested in trying to get your 3rd party PS4 compatible gamepad to work with DS4Windows? If you are then please see the posts above and follow those instructions to provide USB vendor and product hardware identifiers here. You can post a screenshot of your DeviceManager screen or post a debug log messages generated by the debug version of DS4Windows app.

**Comment by TuWHe** [comment]
my sincere apologies I forgot to check the mails I used to create this account

here are the IDs
![11](https://user-images.githubusercontent.com/47461585/64264457-9ca64400-cf31-11e9-9c5b-43fc31ef5ca9.JPG)

**Comment by mika-n** [comment]
Looks like few controllers from the same vendor are already supported. Your controller is probably pretty much the same as controllers known with Warrior brand. The same chinese factory manufacturing the same controller as OEM products for several brands.

Here is a test version of DS4Windows.exe executable with an experimental support for 0C12/0E16 controller. You can replace the attached EXE file on top of the official V1.7.16 version of DS4Windows. Hopefully it works. Please posts here the result of your tests
- Analog axis and button activity
- Using DS4Windows with x360 and dualshock4 output modes
- Gyro sensors (if that controller has gyro sensors)
- Rumble motor (if there is a rumble motor)
- Lightbar (if there is a lightbar)

[DS4Windows_SteelPlayMetalTecP4_GamepadTest.zip](https://github.com/Ryochan7/DS4Windows/files/3575369/DS4Windows_SteelPlayMetalTecP4_GamepadTest.zip)

**Comment by TuWHe** [comment]
Both analog sticks are close to center
buttons, I had to start a game to test, works perfectly, xbox or ps4 ouptut
I don't have gyro sensor or at least it's not moving in any way
rumble motor works perfectly
lightbar can be changed in color

Works perfectly to me and I am relieved this beautiful controller I bought for cheap works wonders now. Thank you. If you need me to provide more testing info I'm still here.

**Comment by mika-n** [comment]
Okey, so everything important works. Great. That controller probably doesn't have gyro sensors (numerous other 3rd party controllers lack support for gyro sensors). You can continue to use the test version because it is identical with the latest official version, except that it has support for this new controller type. The next official release should have the support, also.
