### ISSUE TITLE
The new version is great, but there's still a problem.

### ISSUE THREAD

**Issue by qqjp** [Ryochan7/DS4Windows#807]
The new version is very good. Six axes feel better than Steam's. Thank you for your work. But one problem is that when the six axes is working, the right rocker of the handle becomes less sensitive, as if there is a conflict between them.
If the priority level of the right rocker is higher than that of the six axes, can this problem be solved?

**Comment by Ryochan7** [comment]
You have to set a deadzone on RS or there will be a conflict. Also, make sure to set up the gyro triggers like you want them to behave. Based on the current routine, the gyro is processed first but the calculated values are not used until the end of the mapping process. If the output from Mouse Joystick is not default, it would have priority over the physical right stick.

**Comment by qqjp** [comment]
I mean that when you press L2, the six axes and RS can be used compatibly and reasonably at the same time. Steam has done a good job in this respect. You can compare the performance of the two software in the game. I wish you more and more perfect software.

**Comment by Ryochan7** [comment]
That makes the issue less clear. Did you set a gyro trigger or is it still set to Always On? Gyro trigger set to L2 should allow for six axes and RS to be usable when needed.

**Comment by qqjp** [comment]
I set up the L2 trigger, and when I press L2, the six axes work normally. What I want is that when I press L2, the six axes and RS can control the direction at the same time and run well. In the game, when you are in the aiming state (press L2), the six axes can accurately target the target, but sometimes you need to adjust the direction of a larger range,and you do not want to exit the aiming state， then you need to use RS. DS4Windows uses RS and six-axis collisions after I press L2, resulting in inaccurate direction adjustment. This function is completely OK under Steam, you can refer to it.
English is not my language. Thank you for your patience.

**Comment by nr1995** [comment]
I'm no expert or anything,
but it sounds like you're using “Mouse” instead of “Mouse Joystick”.

**Comment by nr1995** [comment]
Actually I take back my previous comment.
I fired up **_Assassin's Creed: Unity_** to try aiming with the gyro,
and now I see what you mean.
I've set my gyro trigger to [L1],
and while holding it down aiming works fine with gyro,
but **if** while holding it down, I also try to aim the regular way with the joystick,
it feels as if the gyro and stick are fighting to override each other.
They're definitely not usable together.

**Comment by Ryochan7** [comment]
I will have to look into how Steam handles this. Maybe it uses the greater of the two values if the gyro and RS are used at the same time.

**Comment by Ryochan7** [comment]
That seems to be exactly what happens. Steam will use which ever mapping is further from center. It does make the behavior weird if you intentionally move the gyro and stick in opposite directions. Adding a small check in the DS4Windows mapping routine should be easy.

**Comment by Ryochan7** [comment]
This should be feasible in version 1.7.17. I will admit that I only tested this in HTML5 Gamepad Tester. I should also try this in a game as well just to make sure it works as intended.

**Comment by qqjp** [comment]
That is great! The problem has been solved.
