### ISSUE TITLE
New icon(s) for issues #714 & #742

### ISSUE THREAD

**Issue by Oppion44** [Ryochan7/DS4Windows#808]
Hi. I made two icons to prevent the all-black icon to disappear on black taskbars/wallpapers (issues #714 & #742).

The first is a minimalistic design simply made out of the letters DS4W and the usual playstation button colors:
https://mega.nz/#!6s0QDAgQ!s047lBjWYSP5Fvu-2yfa5OuylPNXh2lNrGdIp6hJtzI

The second is a Controller variant in case you don't like the first:
https://mega.nz/#!u98BjIgA!-zYGUX2dkI7FLpRCBLfkGEBJ85FkEfUaHiRc4q9coRo

Both support scaling with sizes ranging from 16x16 up to 256x256 pixels.
If you have any suggestions please tell me and I'll look into changing it.

**Comment by Ryochan7** [comment]
Tested the second controller icon and everything seems good. It scales very well and it looks pretty good. A white version would still be needed for the White DS4Windows Icon option. I tried to make the icon white with my limited GIMP skills but the end result does not look good. Can't fix jaggies.

**Comment by Ryochan7** [comment]
I ended up switching the black icon for the colored version of that icon provided by Geroyuni.
