### ISSUE TITLE
UDP Server CRC issue

### ISSUE THREAD

**Issue by rlnilsen** [Ryochan7/DS4Windows#809]
Packets sent from the UDP Server before a controller has been connected will have a wrong header CRC32 field value of 0xffffffff. CRC calculation on _received_ packets is not affected.

The reason is that Crc32Algorithm.InitializeTable() is not called until the DS4Device constructor is invoked when a controller is connected.

I moved the Crc32Algorithm.InitializeTable() call from the DS4Device constructor to Program.Main(), changing the argument from DefaultPolynomial to Crc32Algorithm.DefaultPolynomial. This seems to fix the issue.

Tested with a DS4 v2 wirelessly through a CSR BT adapter on Win10 1809.

**Comment by Ryochan7** [comment]
I would not have ran into that type of problem myself but that probably would affect some users. That call can get moved to the ControlService constructor. I am working on a couple of other tasks right now but this should be done soon.

**Comment by rlnilsen** [comment]
Sounds good. If you want to verify the issue, you can add something like 
`AppLogger.LogToGui($"DEBUG: FinishPacket: crcCalc={crcCalc}", false);` 
to the end of `UdpServer.FinishPacket()` and then use the PadTest utility from [https://cemuhook.sshnuke.net/padudpserver.html](url).
