### ISSUE TITLE
Force close Help Please

### ISSUE THREAD

**Issue by CHiLL8iLL** [Ryochan7/DS4Windows#810]
Hello and thankyou for your awesome work.. I'm not sure why this is happening. I updated to your latest release and it just force closes. Ive tried to run as admin, windows 8, windows 7 and xp service pack 2. I was using a older version not sure which one but pretty old. I deleted it accidentlly and did not check version. The only fix i had to roll back to 1.4.97x64 that is the latest one i could get working. Please help as i would love to be able to stay updated witgh your latest work.Thankyou for your time and awesome work

**Comment by Ryochan7** [comment]
Do you have .NET 4.6.2 installed on your machine? The older versions of DS4Windows mainly relied upon .NET 4.5.2 but updated tools are being used while building DS4Windows now. That would probably be a bigger issue for people running Windows 7. That requirement is listed in the README.

https://www.microsoft.com/en-us/download/details.aspx?id=53344

Also, later on, make sure you have Visual C++ 2017 Redistributable installed on your machine. DS4Windows will launch but it will fail to connect to the ViGEmBus if you do not have it installed.

x64: https://aka.ms/vs/15/release/vc_redist.x64.exe
x86: https://aka.ms/vs/15/release/vc_redist.x86.exe

**Comment by mika-n** [comment]
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#nothing-works-and-ds4windows-app-and-vigem-driver-connection-silently-doesnt-do-anything
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#link-list
