### ISSUE TITLE
Drifting/Spastic Joystick Inputs

### ISSUE THREAD

**Issue by Exa8yte** [Ryochan7/DS4Windows#811]
The past two hours I've been trying to get this version working to use with Cemu. After switching back and forth from the standard Ds4 Windows and this I've found that every time I attempt to use this modded version the inputs are very spastic. I am unable to even set up control mapping because it's almost as if the joysticks are being moved around constantly. When I run xinputtest it shows just that. I made sure to Uninstall all reminents of the original install including the drivers. I tried the hide Ds4 option as well.. Nothing.. I gave up for now.

**Comment by Ryochan7** [comment]
It is likely either a mapping issue or a case of no dead zone for the sticks. The old Jays2Kings version set an implicit dead zone for the sticks if the setting was set at 0.0. This version took that implicit dead zone away a while ago. Only starting with version 1.7.16 is there now default dead zone and anti-dead zone values for a new profile.

**Comment by mika-n** [comment]
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#profile-doesnt-do-what-i-expect-it-to-do-after-re-mapping-keys
https://github.com/Ryochan7/DS4Windows/wiki/Settings#axis-zone-mapping
