### ISSUE TITLE
v1.7.16 “Trigger Behavior - Turns” meaning?

### ISSUE THREAD

**Issue by nr1995** [Ryochan7/DS4Windows#812]
Maybe I'm just being an idiot here,
but in the newest v1.7.16 update, what does “Trigger Behavior - Turns” mean?
In fact there's a couple of things under “Mouse Joystick” I don't quite understand,
and there's no tips to explain them in-app.
Is there some place I can go to read about this stuff properly?

**Comment by mika-n** [comment]
Following page has something about those settings in "Gyro as Mouse" section, but only in very abstract level and not all options explained (especially Gyro as Mouse Joystick is such a new feature that Settings wiki page doesn't have anything about it).  
https://github.com/Ryochan7/DS4Windows/wiki/Settings

"Trigger behaviour - Turns Gyro" means that you need to press the defined trigger key to enable that feature. If you don't press the trigger key then gyro won't drive mouse or mouse-joystick axies. If the "trigger behaviour - Turns Gyro" option is not selected then "gyro mouse or gyro mouse joystick" feature is enabled all the time.

(Note! There is a trigger option "always on" which effectively does the same as unchecking TriggerBehaviour-TurnsGyro" option).

**Comment by Ryochan7** [comment]
Most people would have probably tried the Steam controller mapper so I can almost assume that most people would be familiar with that option; the label is the same for both programs. It is too bad that adding extra tool tips seem to slow the app down and there is no space in the UI to add help text.
