### ISSUE TITLE
Mouse to Stick Stutter

### ISSUE THREAD

**Issue by Terminatr** [Ryochan7/DS4Windows#815]
This is an issue i had with the original version and still exists in the fork as well. When assigning directional mouse movements to either stick, the mouse will move in that direction when told to, but continuous movement appears to "jump" approximately every second. I cannot for the life of me find a work around. I've changed the polling, sensitivity, flushhid, dinput, and every other option available. I've also tried both wired and BT with no success.

**Comment by mika-n** [comment]
Have you tried to use "Enhanced precision" output curve in LS/RS stick when you have mapped it as a mouse?

Maybe posting the profile file here for closer investigation?

See if the following post has something you could try.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting

**Comment by Ryochan7** [comment]
Not sure if this is profile related or related to general system load. As mika-n mentioned, Enhanced Precision is the output curve choice you will likely want to use when emulating a mouse. That curve is the one I always use for my KB+M driven profiles and mouse emulation is that curve's primary purpose. Another factor is to make sure to disable Mouse Acceleration in your profile if it enabled; I never liked that option. One final factor is to increase the value for Mouse Sensitivity in your profile to increase the overall speed of the mouse cursor.

The SendInput API is not really that great for emulating keyboard and mouse events on the system but it is the main API that Windows provides. I preferred the Vmulti driver when it was an option as responsiveness was better and it worked in some situations where SendInput does not work.

**Comment by Ryochan7** [comment]
Also, make sure Flush HID is disabled in your profile. That was a bad option back in the Jays2Kings version to attempt to reduce input latency but it very often lost input state changes in the process. Other methods are used to decrease input latency better than what Flush HID offered. Flush HID has been a deprecated option for a long time and the default value for new profiles is false.

**Comment by mika-n** [comment]
Maybe you could share the profile file here, so we don't have to try to guess how is it mapped? You can zip the profile XML file and add small file attachments directly in this discussion thread or share it in Google/MS/DropBox/Mega/whatEver file sharing service..

**Comment by Terminatr** [comment]
[DS4Windows.zip](https://github.com/Ryochan7/DS4Windows/files/3610367/DS4Windows.zip)

**Comment by Ryochan7** [comment]
Are you getting a consistent poll rate or are there some polls that lag behind others? The mouse routine takes poll time into account to maintain a consistent speed between various polls. If there is a lag spike somewhere then the next cursor movement will be larger than other moves in order to keep the set speed dictated by mouse sensitivity,. This sounds more like a system load problem on your end more than anything else.

**Comment by Terminatr** [comment]
Changing the poll rate to any settings, input delay will fluctuate between -1 ms to +3ms.

**Comment by mika-n** [comment]
The WOW profile with mouse directions mapped as RS-stick worked just fine here. No strange lags and jumps in mouse movements. There must be some environment specific lag issue. When you detect the lag then check the "Log" tab page of DS4Windows if there are warnings about latency issues.

**Comment by Terminatr** [comment]
Thanks @mika-n, I will investigate the Windows environment and see what I can find.
