### ISSUE TITLE
[Question] PS Button (Guide) in retroarch?

### ISSUE THREAD

**Issue by IceLancerSR** [Ryochan7/DS4Windows#817]
Hey ppl!
I was wondering is it possible to somehow make PS button work in retroarch with xinput ?
Right now, now matter what, that button is not recognized by retroarch at all. Input does not register.
 Only in directinput.
Any suggestions ?
Thanks

P.S
i know about newly added (emulation of V2 as V1) that can let me use entire tool like dualshock , instead of xbox and its amazing. I was just curious is it possible to make button work for for xinput? in case i forget to switch etc.. ?

**Comment by Ryusennin** [comment]
By default, the PS button should be mapped as the Guide button in DS4Windows.

I have a V1 and V2 controller, and the PS button works in RetroArch.

**Comment by IceLancerSR** [comment]
Its mapped by default?

**Comment by Ryochan7** [comment]
Works for me just fine. Is exclusive mode working in DS4Windows and is RetroArch set up to use the virtual Xbox 360 controller as player 1 rather than the DS4?

**Comment by IceLancerSR** [comment]
Yeah , Retroarch recognizes gamepad as xbox , uses xinput driver as well.
I am thinking that maybe it has something to do with me disabling xbox live services and everything tied to it in windows.As i read a bit , that is hijacks guide button and if it does and i killed all of it, might be responsible for non functional button while using gamepad as xbox..problem is , its not possible to just turn that back on..

**Comment by IceLancerSR** [comment]
Just did xinput test that comes with x360ce , guide button is totally on reactive to input..
damn.. i need bypass for this..
https://i.imgur.com/VcJIBdP.png

**Comment by IceLancerSR** [comment]
Yeah .. game dvr, xbox live are tied to gamepad button.. if they are disabled button becomes non functional.. fck ur self microsoft !
Any idea how to bypass that?

**Comment by Ryochan7** [comment]
I figured most people would disable the GameBar on their system. It is useless bloatware that MS decided to force on Windows 10 users.

**Comment by IceLancerSR** [comment]
> 
> 
> I figured most people would disable the GameBar on their system. It is useless bloatware that MS decided to force on Windows 10 users.

Ok but how to fix the problem that "fix" created? i cant get that damn button to work without dvr and xbox services.

**Comment by Ryochan7** [comment]
If you disable the GameBar then there should be no problem. Is something else interfering like Steam or NVIDIA In-Game? You might want to check out HTML5 Gamepad Tester and see if the Guide button registers in that app.

https://www.windowscentral.com/how-disable-and-remove-game-bar-windows-10-creators-update
https://html5gamepad.com

**Comment by IceLancerSR** [comment]
I didnt just disable xbox i removed all components from OS tied to it entirely.
Xbox.TCUI
XboxGameCallableUI
XboxGameOverlay
XboxGamingOverlay
XboxIdentityProvider
XboxSpeechToTextOverlay

Here is one test, whats happening. 
I disable nvidia so it doesnt interfere
net stop NVDisplay.ContainerLocalSystem
then start DS4windows. In log it shows using  exclusive mod
->open up profiles click button on gamepad and ds4windows sees input and opens up window for button bind. So up to ds4 button works , but that same button isnt being sent after ds4 anywhere else while all other buttons do work. I used ur html5 for test this time

https://youtu.be/657VBMAi6Ek

**Comment by Ryusennin** [comment]
On Win7 you have to disable XboxStat.exe (which is part of the required Xbox 360 Accessories) with a tool like Autoruns, otherwise the Guide button is monitored all the time by the Microsoft driver.

It's probably a similar issue on Win10 and not directly related to DS4Windows.

**Comment by IceLancerSR** [comment]
I understand its not ds4 issue. Its something in windows. But xboxstat is not part of win10 and as far as i know i removed everything related to xbox services.. i dont know what else i could be missing

**Comment by IceLancerSR** [comment]
UH
i found something..

> I don't know if there are threads on this topic but I just found this fix after "upgrading" to Windows 10 on my laptop. The first thing I noticed after upgrading and firing up Retroarch I noticed the "Guide" button on my controller (the Logitech button on a Logitech controller) no longer brought up the Retroarch quick menu. After searching around a bit there is a solution posted over on the RA forums about some setting in the GameDVR app but I don't have and don't want that app. I found another fix on a Steam forum thread with a simpler solution than installing some app just to get back the functionality of the button. Anyways here is the fix that should work for Xbox and Logitech controller and others. Go to the device manager to Xbox 360 peripherals. Right click and select properties. Go to the driver tab and click update driver, click browse my computer for driver software. Then select "Let me pick from a list". You should now see 2 drivers listed pick the one marked [2009-040-08], should be the bottom one. Reboot system if needed. 

But those xbox drivers are not listed in win10 any more. Yes there are two to choose from but i guess something has changed, maybe both are updated? Ill try to track down old xbox driver

**Comment by IceLancerSR** [comment]
AHH FINALLY!
My button is working!!
pointing to driver file manually didnt work. Had to install that freaking xbox accesories for windows 7
Found here
https://www.microsoft.com/accessories/en-id/d/xbox-360-controller-for-windows
choose for x64 win7 . After install/reboot driver options look like this:
https://i.imgur.com/iLJiWXz.png
As u can see it states i am using drivers from 13 august 2009
Guide button works!

**Comment by IceLancerSR** [comment]
P.S
there might be question of compatibility now? Will all new games work with old driver for xbox?
