### ISSUE TITLE
Bluetooth/connection strength strange behaviour

### ISSUE THREAD

**Issue by nr1995** [Ryochan7/DS4Windows#818]
I hate to start probably the 100th thread about connection quality vaguely being not good.
But I often get strange behaviour in-game.
As I understand, the light bar flashes red when the latency is above 10ms.
For me, the signal strength often very slowly just gets worse and worse
over the course of about an hour,
Until it's flashing red almost constantly,
then commands in-game start to hang there for a second or two,
then the controller just turns itself off.
Just turning it on again usually returns me to a relatively consistent blue bar again,
and from there it may just do the same thing again.
The battery level is fine, and the BT adapter is line-of-sight, 1m away.
Is there any known reason for this, or anything I can do to prevent it?

**Comment by mika-n** [comment]
At first make sure you have the latest version of DS4windows.
https://github.com/Ryochan7/DS4Windows/releases

What do you see in D4Windows Logs tab page when the BT connection starts to slow down?

Please go through the basic diagnosing tips:
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting

**Comment by nr1995** [comment]
Yeah I'm always on the newest version.
What do I see?  Well... a whole lot of this:
![2019-09-09   00꞉57꞉12](https://user-images.githubusercontent.com/53646027/64491588-cd250f80-d29c-11e9-992a-d7d668fc5dd0.png)

**Comment by mika-n** [comment]
Do you have "balanced" or "high performance" power plan in Win10 settings (power & sleep / Additional power settings)? The default is probably balanced power plan. Try setting the PC in high performance mode and see if it makes a difference.

**Comment by nr1995** [comment]
Set to “high performance” years ago.

**Comment by mika-n** [comment]
Does it work better over USB connection? The idea of this test would be to identify if this is purely BT issue or something else which affects USB connection also.

What is the polling rate of BT setting in a profile? Try using the default "250hz (4ms)" value if it is something else.

**Comment by nr1995** [comment]
Over USB there's nothing but pure, solid, blue connection.
It's already set to 250Hz, although I thought the default was 128Hz...
"Flush HID" is off.  I've never touched it.

**Comment by mika-n** [comment]
Do you use WIFI network connection? Try to use BT while WIFI is disabled to see if it makes a difference. Some BT chipsets share some parts with WIFI.

**Comment by nr1995** [comment]
There's Wi-Fi in my flat, but I'm not using it on this machine; my desktop.
I'm using a USB Bluetooth receiver made by Philips.
I should say again, this strange behaviour is only about 20% of the time.

**Comment by mika-n** [comment]
I'm running out of ideas. BT is sometimes a mystery and there are weird incompability things. Maybe you should try to borrow an another BT receiver to see if it works better.  If it starts to slow down after a while then it could be a heat issue, also. Try to place the BT receiver at the end of USB cable and place it away from the hot air blowing from the PC.

**Comment by nr1995** [comment]
I find that restarting DS4Windows fixes the problem.
And makes the app's ability to connect with the controller more reliable.
Usually the problem occurs when it's been up and running for a long while.

**Comment by mika-n** [comment]
Hmm.... Sorry. I don't have any new ideas what could cause this issue. Except that make sure you have the latest BT device drivers installed for both Windows and for the BT receiver.

As a side note, I use one DS4 rev1 gamepad via USB cable and I have couple USB cables which cause similar "latency issue" with the DS4 gamepad. I guess those couple problematic USB cables have a loose connection and this causes some weird connection issue. However, using another USB cable (in fact vanilla Sony DS4 usb cable) has zero problems. This indicates that the connection (BT and USB) between the gamepad and PC must be consistent and reliable or there may be some random latency issues. Naturally BT is a bit more sensitive than USB if usb cables are in good shape.

But, I use DS4 rev2 gamepad via BT connection and I haven't seen this kind of problems with the latest DS4Win version. The laptop has integrated BT and it seems to work just fine with DS4 gamepad.

Maybe you should try to test the gamepad in another PC using the same DS4Win app version with an another BT receiver to see if it makes a difference? And to try out your existing PC/BT setup with another DS4 gamepad or BT receiver? These tests would narrow down the potential problem area (PC, BT, DS4, DS4Win app?).

If DS4Win would have a serious bug in BT communication (memory leak? process overloading?) then I'm sure this kind of problem would be even more wide spread and more users would suffer from it.

**Comment by cristianmars22** [comment]
Have you found a solution ?

**Comment by nr1995** [comment]
No it still happens sometimes.
I can't seen to figure out why sometimes and not other times.
But shutting down / turning off everything and starting again works fairly reliably.

**Comment by cristianmars22** [comment]
What do you mean for shutting down ? I was reading just now did you try to disable the gamepad as the mouse ?

**Comment by nr1995** [comment]
Sorry, to be more clear,
restarting DS4Windows and restarting the controller (or one of those two),
is usually what fixes the problem.
Now that you mention it,
the problem may be linked to using the gyro as a mouse/joystick.
It seemed to happen more with that feature enabled, but it's hard to tell.

**Comment by mika-n** [comment]
The latest version has a new profile option "Enable Output data to DS4". By unticking this some non-100% compatible DS4 gamepads or BT dongle/chipsets may work better.
