### ISSUE TITLE
Prompt when closing.

### ISSUE THREAD

**Issue by puckle** [Ryochan7/DS4Windows#82]
I have a minor issue with the following  adjustment, and wonder if it could be made optional.

"Added prompt when closing the application if any controllers are connected"

When I go to shut down my PC, DS4W now waits for me to confirm if I wish to proceed as windows tries to close the application. I thought I shut down my PC last night, only to get up in the morning and find out that it was waiting for me to to click "yes" in the confirmation box.

Thanks again.

**Comment by Ryochan7** [comment]
Sorry about breaking unattended usage of the app. The relevant event does have a way to determine if a user attempts to close the application or if it is done by the system. The routine will have to be changed to take the status flag into account.

**Comment by Ryochan7** [comment]
This problem has been fixed in version 1.4.84. Thank you for bringing up this problem.
