### ISSUE TITLE
[TODO] Migrate DS4Windows to WPF

### ISSUE THREAD

**Issue by Ryochan7** [Ryochan7/DS4Windows#824]
The successor build is definitely not going to happen in 2019. I would still like to move away from Windows Forms and start utilizing newer development practices though. The big areas of interest would be utilizing Windows Presentation Foundation and MVVM.

**Comment by Ryochan7** [comment]
I really wish I would have saved some of my old test projects. Having to figure out quirks all over again has not been fun.

Anyway, I have set up a repository for developing a WPF version. It will stay in a separate repository for a while. The current status is not as far along as what I had before reformatting but it is getting close. If it works out then the code will be migrated to this repository and a version 1.8 (or 2.0) of DS4Windows would be made.

https://github.com/Ryochan7/DS4WindowsWPF

**Comment by Darthagnon** [comment]
Doesn't WPF mean "Windows 10 exclusive"? If so, please don't make regular DS4Windows like that :'(

**Comment by Ryochan7** [comment]
No. Targeting UWP (Universal Windows Platform) is what would force Windows 10 usage. WPF (Windows Presentation Foundation) has been around since 2006 and is compatible with Windows Vista and later. Windows 7 SP1 is the minimum platform target for DS4Windows so there should be no problem with compatibility.

https://en.wikipedia.org/wiki/Windows_Presentation_Foundation

**Comment by Ryochan7** [comment]
Some progress has been made. The main form has mostly been ported over. Controller hotplugging and profile selection work so the prototype is somewhat usable. Currently, the WPF version is slightly faster than the current Windows Forms version. The next step is to port over the main Options profile mapper form.

**Comment by Ryochan7** [comment]
Now the main profile settings can be edited and saved. The actual binding editing portion has not been made yet. One other positive thing to come out of this is that a few old bugs in the current DS4Windows code have been found and fixed. I need to take some time and bundle a new DS4Windows release.

**Comment by Ryochan7** [comment]
![ds4win_wpf_20191009](https://user-images.githubusercontent.com/581968/66278374-09349b80-e86e-11e9-93a7-c073ddb6689c.png)

**Comment by Ryochan7** [comment]
The base binding window is now functional. The next step will be to work on the RecordBox control to allow mapping macros. The code for that component is going to be a pain to analyze. Very messy.

**Comment by Ryochan7** [comment]
The RecordBox control is now pretty much finished. General macro parsing was the biggest issue to contend with but the new version should be much easier to maintain.  There are other minor tasks to accomplish still but the next major milestone will be to get Special Actions working again.

**Comment by Ryochan7** [comment]
The Special Actions editor is now complete. It has taken one month but the new version finally does everything that I use in DS4Windows. The new version is still not complete though. The next big step will be to get Auto Profile support to work fully.

The current user control has been ported and the new routine scans for apps much faster. One big problem is dealing with expression matching in addition to direct matches.

**Comment by greggameplayer** [comment]
@Ryochan7 will it be possible on WPF version to have the audio jack working on 3rd parties bluetooth dongle ?

**Comment by Ryochan7** [comment]
No it will not work. That process was never fully worked out even in the old experimental Linux code. The only two ways to get the audio jack working will still be via the Sony Wireless Adapter and via USB on the DS4 v.2.

**Comment by Ryochan7** [comment]
I am pretty sure that enough has changed to justify bumping the version number to 2.0 once the WPF version gets a public release.

**Comment by Ryochan7** [comment]
If anyone is curious, here is a test build of the current WPF progress. The test build has been tested on Windows 10 and Windows 7. Make sure to place this build in its own directory and copy over your Profiles folder and other config files if you want. Do not write over the stable DS4Windows build. Appdata support should technically work although it has not been tested.

https://drive.google.com/file/d/1MuIku_lYl9yuVGoLQwbPtSVbOXG9rdlU/view?usp=sharing

**Comment by Ryochan7** [comment]
The Auto Profile system is now working. Some ideas that I had for changes were kind of squashed when it came to dealing with expression entries. I ended up just doing a straight port of the routine. Pulling the various bits from the DS4Form class was an issue. The DS4Form class has been acting as a major God class doing far more than it should.

As it is now, profile switching seems to happen faster with the new version.

**Comment by Ryochan7** [comment]
Updated WPF build. Besides auto profile being usable again, some other updates are fixes to output controller switching, changed Run as Task behavior, and more options added back to the Settings tab.

https://drive.google.com/file/d/1lzyf_2LFzcKYiOfok2gc6t7CwL0bUYD-/view?usp=sharing

**Comment by Ryochan7** [comment]
Updated build. Changes:

* Increasing hotkey timer interval to 20 ms (was 100 ms)
* Fixed old DS4Updater lookup bug
* Fixed touchpad swipe to change profiles functionality
* Periodic garbage collection has been added
* Scan directory option added for Auto Profile tab. Using Ookii Dialogs VistaFolderBrowserDialog

https://drive.google.com/open?id=1rMMmgmvuQxhGI4o6NeG_NX843_fB-9V5

**Comment by Ryochan7** [comment]
The Controller Readings tab conversion is almost finished. Some layout changes will likely happen but the main functionality has been added back. WPF definitely made the process of laying out those controls much easier than the process required for the Windows Forms build. The actual code for the new update process could be better but the dev version is still an improvement.

That should be the last major piece of functionality that had been missing. Apart from localization and other minor tweaks, the build is pretty close to being complete. I will get a new WPF test build posted in a couple of days.

**Comment by mika-n** [comment]
The WPF GUI version seems to work a bit snappier than WinForms version. Here are couple random ordered comments about the WPF version:

- The Github repository doesn't contain VigemClient DLL library files. Compilation works when libs folder is copied from the main branch of DS4Windows project.
- Few GUI items need tweaking (placement and spacing of controls etc minor issues at this point).
- Maybe the order of default profile editing TAB pages should be changed now when the GUI is going through major re-work anyway. The default tab is "Lightbar". Maybe the "Other" tab would be more logical starting place as the first tab in profile editor? And re-named as "Controller" or "Main".
- Rumble "TEST" button does nothing (because "controller for readouts" is disabled). And keyboard mappings don't react to gamepad key presses because of the same reason. Well, this is not a major issue but without this "controller for readout" functionality rumble TEST buttons could be removed.
- 360SteeringWheel "Calibrate..." button crashes. Haven't debugged yet why is this. I'll look into this later on. The 360SteerngWheelEmulation functionality itself works.
- The list of profiles in "Profiles" tab page doesn't open a profile for editing when double clicked. 
- Popup tooltips are missing (for example in SpecialActions macro editing screen).
- The main window of DS4WindowsWPF opens in huge size (bigger than my fhd resolution of my laptop). I guess you have some monster resolution monitor. The app doesn't remember the re-sized size when it is opened the next time. 
- I cannot "check" app items in AutoProfiles screen, so "Hide Unchecked" would always remove all profile settings.
- "Show auto-profile debug messages" option doesn't do anything in WPF version. It doesn't dump out those debug messages about detected apps and wnd titles and matching profiles. Note! This option is not supposed to be saved in XML config files because it would be a bit dangerous to forget this option enabled (too much debug messages). 
- WPF version doesn't ring the "hot plug" notification sound and doesn't show "x360 Controller 1 connected" Log message when the app is launched while controller is connected. The sound and the log message is shown when a profile is opened for editing. However, controller re-mapping seems to work even when this hotplug sound and "x360 Controller 1 connected" msg is not shown at boot time. The missing log message may be a bit misleading and someone might thing that there is something wrong in a controller connection. The same thing can be seen when you press "Start / Stop" button to connect/disconnect active controllers.

**Comment by Ryochan7** [comment]
Thank you mika for the feedback.

* Not bundling the ViGEmClient libraries was a major oversight. The template .gitignore file had rules that ignored those directories and I didn't notice. I have added exclusions for the directories and added the DLL files into the repo.
* Rumble test, 360 Steering Wheel calibration, and controller readout assume that you will use the Edit or "New Profile" options from the Controllers tab to open the Profile editor. Rumble test and controller readout will do nothing if a device number is not passed in the code. As you found out, launching the 360 Steering Wheel calibration window that way causes the app to crash. When a device number is passed, calibration works.
* Some popup tooltips are subject to localization so that process has to be figured out first before tooltips will be added back in.
* The current behavior of the Checked status in the Auto Profiles list is slightly different. The checkbox is disabled so it cannot be clicked. An entry is Checked if it has a saved Auto Profile entry and Unchecked if one does not exist. Clicking the "Hide Unchecked" button will refresh the list showing only saved entries. I have not tested the "Show auto-profile debug messages" functionality. The only part I tested was whether checking the checkbox passed the chosen state to the AutoProfileChecker class. That setting is not persisted in the XML.
* As long as the window is not in focus, notifications should work. It is working for me like the WinForms build does. Saving of the window size and location also works for me. The setting is saved on program exit.

**Comment by mika-n** [comment]
Few more comments about "auto-profile" dialog and functionality:
- If I choose "Add Programs / Browse" and choose for example c:\windows\ folder then WPF version crashes. I don't know if this crash is related to some permission issue or number of apps in the chosen folder.
- Now there are only steam/programfolder/browser options in "Add program" button. There is no way to add a single app because the "Browse for other program" option is missing.
- The auto-profile debug functionality doesn't seem to work. The autoProfile debug property is never updated when the autoProfile debug option is checked/unchecked.
- It is a bit  non-intuitive to be able to enable the autoProfile debug option only when a certain autoProfile entry is selected because this debug option is not related to a single autoProfile entry. Also, now it is not possible to debug app names and wndTitle names without adding at least one dummy app into the autoProfile list if user is just trying to figure out what are process and wndTitle names of certain apps he/she wants to add to that list.
- The application name editbox is not editable in the autoprofile properties. Wildchar support is supposed to work with both appname and wndTitle properties ($, ^, *), but now it is not possible to add search keywords (wildchars) to app name property.

**Comment by Ryochan7** [comment]
Gotten some of those issues fixed. The Auto Profile Debug messages problem was due to the AutoProfileChecker class linking to an older placeholder class rather than the log class from DS4Control. The rest of the system worked so changing the log calls fixed it so debug messages now show up in the Log list.

The debug checkbox being disabled is due to disabling the panel that holds the checkbox and other controls in that sidebar. I will need to change the layout a bit to split that checkbox from that panel.

The Browse Directory option was a recent addition due to Microsoft not providing a suitable folder browser dialog for WPF. The general advice on SO is to use the version from Windows Forms. I ended up choosing to use Ookii Dialogs to have a native WPF dialog for browsing directories. That was a higher priority than browsing for an individual executable. Leaving out the Origin games import option was done on purpose but maybe it will have to be added back.

One last thing is that the device number assumption for the Profile editor has been changed. A new field has been added to the ViewModel to make the editor choose Slot 1 if the temp slot number of 4 is passed to the editor. That is pretty much what is done in the WinForms build although it takes the temp device value from the NumericUpDown nUDSixaxis control.

**Comment by Ryochan7** [comment]
New WPF build. Changes:

* Added Controller Readings tab to Profile editor
* Added WPF Localize Extension to later provide localization support
* Added double click event handler to main profile list
* Fixed profile name lookup for controller list when profile name is blank or when profile name does not exist
* If no explicit controller slot number is passed to Profile editor, assume the use of slot 1 for some functions (Rumble test, Controller Button reading, 360 Steering Wheel calibration)
* Fixes to allow auto profile debug message to appear in Log list
* Allow application path in Auto Profile editor to be editable
* Fixed "Turn Off DS4Windows Temporarily" option saving in Auto Profiles

https://drive.google.com/file/d/1_wKzLjKswRTskG0-P11MZbKcBZm6Q83Q/view?usp=sharing

**Comment by mika-n** [comment]
Just tested the latest version from GitHub. Few more comments about auto-profile feature:
- Debug flag works now.
- If AutoProfiles.xml file has an entry for non-existence app then DS4Win crashes at launch time. The crash seems to be because of "app icon" retrieval of auto-profile list entry fails. FileExists/tryCatch check would solve it while looking for an app icon.
- Application path is editable now but after saving it and re-opening the app (or pressing "Hide unchecked items" btn) the app path is reverted back to default value. This also makes it impossible to add more than one entry per app path because the auto-profile list doesn't allow duplicate app path entries. This can be simulated, for example, by trying to add "notepad.exe$" (=match all process names ending with notepad.exe keyword) "*readme" window title entry and another one with "notepad.exe$" and "*notme" wnd title search keywords (ie. different profiles based on which TXT file is opened in a Notepad). In real work scenario this is required with WinStore apps because those all share the same process name, but just the wnd title is different).
https://github.com/Ryochan7/DS4Windows/wiki/Profile-selection-using-auto-profile-rules

The AutoProfile list should check that if an existing entry is modified (process name or wndTitle) then it should overwrite the existing entry and use the new process name (with optional keywords) as a list key value. This way it would be possible to add the same process name again in the list with a different process name search keyword. If there are potentially conflicting process or wndTitle search keywords (ie. multiple rules would match the same process/wnd) then the first rule in the list wins the race. This is how the old version worked with these cases and it is up to the user to order those auto-rules in a specific order.

Anyway. The new WPF version is getting closer to be usable in real world scenarios. Next I will test more special action macro rules and 360SteeringWheel emulation modes.

**Comment by Ryochan7** [comment]
Didn't put the check for a matched object in the new path setter so the path is not persisted after the initial save. I never used the newer expression functionality so I really need to test that. I'll take a look into the crash problem too.

**Comment by Ryochan7** [comment]
New WPF build. I have not tested auto profile support again so the previous issues still exist. Changes:

* Use device slot assumption for Controller Readings tab in Profile editor
* Show proper lightbar color in Controller listing when switching profiles
* Localization support added for portions of the GUI
* Japanese language pack has been included
* Added checkbox for FlashWhenLate setting
* Fixed right click BT disconnect. Controller listing is now removed after disconnect
* Added some tooltips to Profile editor and main window
* Application now uses the chosen language pack from settings

https://drive.google.com/file/d/1B4Q4fbF31OgBaeZayB5yoSs3SIB-5x6F/view?usp=sharing

**Comment by Ryochan7** [comment]
New WPF build. Auto profile support has been edited. It seems like the old problems should be fixed. Multiple entries can be made per process. Expression search strings are updated with path or title changes. Added file check before trying to grab app icon.

Changes:

* Added runtime MAC generation code made by mika-n
* Make sure "Run at Startup" options panel is visible at app launch if enabled
* Reduced size of Profile editor
* Added extra spacing to many portions of the application
* Added "Browse for Other Programs" menu item in Auto Profiles tab. Individual exes can be added to list
* Various fixes for expression matching in auto profiles

https://drive.google.com/file/d/1x4ApahGfFRX0eYKLiJw2kyf258E2qbwN/view?usp=sharing

**Comment by mika-n** [comment]
The latest WPF looks good. Auto-profile feature seems to work now great and 360-steeringWheel emulation mode works perfectly. 

The next area where I did more testing was specialActions macro engine. Run on keyRelease, repeatWhileHeld, runSynchronized options seem to work. But there are couple issues in specAction screens:

- Opening an existing specialAction and when I, for example, try to change a trigger key and press "Save" (=the save key within specialAction macro frame, not the Save button in the main toolbar for a profile) then WPF complains that macro with the same name already exists and refuses to save changes to a specialAction macro. 

- Macro editor shows key presses and delays, but I cannot edit a delay value (clicking a delay line does change the line as editable but I cannot enter any new numbers to a delay value).

- Editing a recorded macro and if a line of the recorded macro is removed and I press "Cancel" button to forget changes then DS4WinWPF process crashes.

**Comment by Ryochan7** [comment]
Can you share the Actions.xml filethat you are using for testing? I have mainly been testing with new actions so I have not had any legacy files to work with. I have not gotten around to creating an Actions.xml  file in DS4Windows stable and trying it in the WPF version.

Editing time delays should work as they did last time I had tested it. I will double check the macro recorder.

With the last few commits that have been added to the repository, the WPF version is pretty much complete. Exploratory testing and testing the update process would be the last big tasks before a real transition can be made. I will get a new WPF build out shortly once I properly play test the recent changes. The problems that you have mentioned will likely still be present though.

**Comment by Ryochan7** [comment]
Okay. I can confirm the lack of time delay editing. The TextBox gets hidden when it is given focus. Also I never got back to replacing that TextBox with an IntegerUpDown control.

**Comment by Ryochan7** [comment]
New WPF build. Changes:

* Added ScrollViewer to Settings tab. Content can be scrolled now
* Automatically scroll down Log list as items are added
* Reduced size of BindingWindow form
* Added 4th and 5th mouse buttons to binding window
* Changed macro wait period and rumble editing
* Fixed saving of macros

https://drive.google.com/file/d/1Jq0jMmvj4jHUw2sq4nq9rCpdw1ZfTJtl/view?usp=sharing

**Comment by Ryochan7** [comment]
Looking into the Special Action problem now. There is supposed to be a flag to be able to distinguish between creating a new Special Action and editing an existing one; it does exist in the view model. The form validation code does not take it into account though. The validation code finds the previous version of the Special Action and sets the error flag for that field. It looks like this should be a simple fix.

**Comment by Ryochan7** [comment]
New WPF build. Changes:

* Make sure to run Close in main thread after launching updater
* Don't perform existing name check for Special Action while in edit mode
* Make sure to carry over active flag when editing a Special Action

https://drive.google.com/file/d/1tKK6ZxZko-inNQGC_srcxEDJJ-8Vx57a/view?usp=sharing

**Comment by Ryochan7** [comment]
Updated WPF build. Changes:

* Properly enforce Special Action name check in edit mode
* Tweaked size of Controller Readings section
* Added spacing to controls in Axis Config tab of the Profile editor
* Took out MinWidth property setting from custom curve TextBox controls

https://drive.google.com/file/d/1Nu2gJhGx9ZDQ1gnQP1qU2LwgPqjVvTyj/view?usp=sharing

**Comment by mika-n** [comment]
(hmm.... I thought I already commented this but looks like it is gone or I simply failed to press the "Comment" button). 

Now specialAction editing and saving works (new vs edit). Modifying a delay in a recorded macro works and the app no longer crash when a delay line is removed from a macro.

.The latest change slight adjusted the width of a custom curve output textbox field (narrow but at the same time "..." button is wider). The new custom curve textBox is not wide enough to show the last few digits of "0.00, 0.00, 0.00, 0.00" curve definition string. Maybe the "..." button should be a bit smaller and the textBox few pixels wider?

**Comment by Ryochan7** [comment]
Updated WPF beta build. Changes:

* Make sure to run explicit bindings if edit template controls are still active on macro save
* Added initial logging support using NLog
* Check appdata folder structure on program startup
* Added hook so an exception that leads to a program crash will be logged
* Added SuppressUnmanagedCodeSecurity attr to App class
* Reduced width of custom curve editor launch buttons

https://drive.google.com/file/d/1VQE_ukZhIo-009qr1BF2IEo5x7Q5mcLo/view?usp=sharing

**Comment by Ryochan7** [comment]
Updated WPF build. Changes:

* Now handle blanking a profile at the Global class level
* Fixed HidGuardHelper.exe execution. Forgot to include the UtilLibrary.dll file before
* Updated HidGuardHelper.exe built with Visual Studio 2019

https://drive.google.com/file/d/1G-pfY2xCmUTtvHcqaTYxNjpVqkmS6N9L/view?usp=sharing

**Comment by Ryochan7** [comment]
Updated WPF build. Changes:

* Added Nacon Revolution Pro v.3 support. Change provided by mika-n
* Moved Axis Config to first tab in Profile Editor
* Use extra alpha flag for controller listing color box
* Make sure New Profile made from controller list shows up in profile list
* Switch active profile on currently active profile delete. Switch to first profile on list
* Changed version number grabbing for portions of app
* Updated version number to 1.9.0
* Added extra log message for when ViGEmBus is not detected

https://drive.google.com/file/d/1Cn1m1ZbtC-PfS1B3nexBza_90cNIASnj/view?usp=sharing

**Comment by Ryochan7** [comment]
Updated WPF build. Changes:

* Check for toggle status in Press Key Special Action. Only show base filename in Load Program SA
* Fixed early shutdown of app
* Changed aspects of Run as Task routine
* Added extra Run At Startup setting checks which will be helpful for replacing old Run at Startup resources
* Fixed command line minimize option

https://drive.google.com/file/d/19tQwR3p6HS1roTXGGWRO665oDUij-cDe/view?usp=sharing

**Comment by Ryochan7** [comment]
At this point, I am planning on releasing DS4Windows 2.0 on Christmas Day. That will give me a little more time for testing and possibly implementing new functionality. Special Action migration was finally tested about two days ago and it seems to work perfectly fine.

**Comment by Ryochan7** [comment]
Updated WPF build. Putting an update out now due to a problem with the Profile editor not closing after saving an existing profile. The event used to perform closing actions was moved in build 20191128 and all cases were not covered.

Changes:

* Updated Task Scheduler to version 2.8.17
* Updated Extended WPF Toolkit to version 3.7.0
* Use MainWindow Closed event. Moved some code to event handler
* Added controller check on main window closing
* Allow direct tray menu app exit
* Fixed closing Profile Editor on existing profile save

https://drive.google.com/file/d/1A0644N-3TqQGFGJCjsaEvHJb_agP0Hm8/view?usp=sharing

**Comment by Ryochan7** [comment]
Updated WPF build. This update is more meant for people to test the added output device change  delay before it gets added to DS4Windows stable. There is now a 100 ms delay after plugging and unplugging output devices. A minor action queue is being utilized in the process.

Changes:

* Unify event hooking for tray icon
* Update tray icon text on device unplug
* Unify output device plugging and unplugging
* Added 100 ms delay to output device plugging and unplugging

https://drive.google.com/file/d/128XDikjRcYEFbwgfqzqKBJfS0m9Q92Zl/view?usp=sharing

**Comment by Ryochan7** [comment]
The WPF build has been partially migrated so now the executable will be DS4Windows.exe again. Also, an initial overwrite test has been done. An upgrade from DS4Windows 1.7.24 to version 1.9 has been successful. A newer WPF beta build will probably be released shortly.

I will hold off on migrating the code to this repo for a few more days. At least one more Windows Forms build of DS4Windows will be released before the update to version 2.0 is done. The plan is to make a backup branch with the final Windows Forms build code before replacing the code in the jay branch with the DS4WindowsWPF code.

**Comment by Ryochan7** [comment]
Updated WPF build. Changes:

* Don't show disconnect confirm window when launching updater
* Renamed assembly. Final executable is now DS4Windows.exe
* Changed synchronization method for log messages
* Set Increment property for smoothing weight controls

https://drive.google.com/file/d/1y1QhftReBbJD5cmw3qqnJz6UD1rw01BG/view?usp=sharing

**Comment by Ryochan7** [comment]
Updated WPF build. Changes:

* Migrated assembly info from main DS4Windows
* Fix for failing to connect to WMI service
* Changed crash message in log file

https://drive.google.com/file/d/1c0B0TDKSOyRSjseIJdPx133c7h7otYnk/view?usp=sharing

**Comment by Ryochan7** [comment]
The WPF code has finally been imported into the jay branch. The old Windows Forms code has been placed in its own branch for archival purposes. It will probably be useful to refer back to the old code every once in a while.

https://github.com/Ryochan7/DS4Windows/tree/winforms

**Comment by Ryochan7** [comment]
Looks like the updater won't do what I want. Just tried using it to copy the WPF files and I found a long standing problem. It can only copy files one directory deep. That means translation files never got updated and people that installed DS4Windows from before version 1.7.13 never had access to the curve editor. Making a couple of changes to copy along subdirectories allows the updater to update an installation to DS4Windows 1.9.1.

This is going to make the whole upgrade process much more complicated. A new WinForms build will have to be released with a new updater. Anyone who doesn't update in a week is likely going to run into problems.

**Comment by Ryochan7** [comment]
Found another updater problem. Copying over the new updater in DS4Windows failed due to an invalid location file check. That error was my fault. Another new WinForms build (1.7.28) has been released.

**Comment by Ryochan7** [comment]
Updated WPF beta build. At this point, no more changes should be needed and this build should be identical to DS4Windows 2.0 except for adding the update hooks back in and a changed version number. This should be the final beta build unless something significantly wrong is found with this version.

Changes:

* Added extra labels for Gyro and Accel readings in Controller Readings control
* Set bounds for Mouse Joystick anti-dead zones. Increased width of gyro readings in control
* Fixed Idle Disconnect editing in Profile Editor
* Nacon Revolution Infinite support added. Change made by **mika-n**
* Bundled updated task.bat file
* Changed SpecificVersion flag to False for XAMLMarkupExtensions
* Changed version number to 1.9.2

https://drive.google.com/file/d/1zgTJ7lmpfCzIHi7IgwJ_2AZ0kXOrJ2Um/view?usp=sharing

**Comment by mika-n** [comment]
There is a small bug in WPF version while editing button re-maps of a profile using dualshock4 mode. The image of ds4 gamepad and all hotspots are slightly misaligned. Hotspots work but one must know where the hotspot is based on "misaligment offset". The following picture explains the issue.

![DS4Win_RemapKeyHotSpotAligmentBug](https://user-images.githubusercontent.com/35538525/71313821-e36b6b80-2446-11ea-87d1-e8a3ae2275dd.png)

**Comment by Ryochan7** [comment]
Got Windows 10 back to the point where I could get VS set up. I must have missed changing the locations for the DS4 canvas when I edited that window last.

**Comment by Ryochan7** [comment]
Version 2.0.0 is now published. I have posted a notice about the update in another issue that I will link here. If you already have version 1.7.28 then you can disregard the issue and just update. If not then you might have to download the latest version of the DS4Updater.exe and run it manually in order to update successfully to DS4Windows 2.0.0.

https://github.com/Ryochan7/DS4Windows/issues/945

This task is now complete so this issue can be closed.
