### ISSUE TITLE
It keeps asking to select an action

### ISSUE THREAD

**Issue by billyand** [Ryochan7/DS4Windows#825]
This is for version 1.7.17. Whenever i hit a button on my controller, it asks me to select an action for that button. Im trying to change some stuff with the R2 and L2 button on the axis config tab but it keeps asking me select an action for it instead. Is that supposed to happen?

**Comment by mika-n** [comment]
Yes. When a profile is opened in edit state then btn press brings up a mapping screen for the btn. You can disable this automation by unticking ”use controller” checkbox in Other tab page

**Comment by billyand** [comment]
thanks
