### ISSUE TITLE
Controller Drift/Spastic movement fortnite

### ISSUE THREAD

**Issue by Arrif4** [Ryochan7/DS4Windows#826]
So I used a bluetooth adapter with ds4 controller with ds4windows and it worked fone however i connected my ds4 controller to my ps4 so had to reset and it didnt connect to my pc and i stupidly deleted the bluetooth drivers and its all messed up. So i unplugged it and disabled all bluetooth. I'm now playing via usb and when i play fortnite it's so bad it does random things unrespinsive and drifts so much i cant even explain. Idk what the issue is but i need help. I have hide ds4 on in settings and as xbox 360 controller in profiles. I have dinput unticked. Also in devices i only have 1 controller so thats not the problem that there's 2 controller inputs

**Comment by mika-n** [comment]
Some USB cables are known to be problematic with DS4 gamepad. The USB cable must have both charging and ALL data lines connected. Some usb cables supplied with mobile phones don't always have all these data lines connected. And what do you see in "Logs" tab page of DS4Windows app? It should show a warning if exclusive mode fails to work.

**Comment by Arrif4** [comment]
I'm pretty sure i fixed it although ther are some small stutters and random flicks. However the wired has much more latency than bluetooth however i can't do bluetooth anymore as i deleted the bluetooth drivers on device manager:(

**Comment by mika-n** [comment]
Yes. There are many reports that DS4 gamepad is a bit more responsive over BT than USB connection (assuming PC is up to the BT task and the BT receiver is fully compatible). Some users of DS4Windows app have reported similar results. 
https://www.reddit.com/r/RocketLeague/comments/8wvf9u/controller_input_lag_comparison_more_info_in_the/

Is this difference practically significant is an another story.

**Comment by Arrif4** [comment]
Is it possible for me to get my Bluetooth drivers back in device manager? I did a restore and everything an nothing helped

**Comment by greggameplayer** [comment]
must be because of the software since with bluetooth i get a bit of stick drift especially on the right stick
