### ISSUE TITLE
Lag spikes with 2 controllers connected

### ISSUE THREAD

**Issue by fefo-dev** [Ryochan7/DS4Windows#827]
Didn't saw this issue clearly outlined but I had this problem since Jays DS4Windows.

Connection stability decreases significantly with two controllers paired. If I set it to flash when over 16ms there's a flash about every 2s, but over 10ms both become a strobe. Single controller over BT is as stable as it can be.

In games it doesn't look as bad (sub 1f latency still) but there have been times where one controller simply stops sending inputs for a fraction of a second and then wakes up.

Changing the polling rate from 4 to 1ms doesn't show any improvement.

Searching about this issue I only found that it might be a build problem within DS4. Is it true?

**Comment by Zaazu** [comment]
I have the same problem, but with 3+controllers.
Don't think it's anything to do with the software, just think the BT card is getting overwhelmed, maybe not enough bandwidth. Try another adapter if you have one.

**Comment by Ryochan7** [comment]
That is likely the adapter's problem. I encountered this before with my old BT 2.1 adapter with 2 controllers. I had to change the BT poll rate to get a stable connection. My current  BT 4.0 adapter can handle 2 controllers just fine.
