### ISSUE TITLE
Add jack audio out and external compatibility via bluetooth

### ISSUE THREAD

**Issue by greggameplayer** [Ryochan7/DS4Windows#828]
Can you add this compatibility please it, will be awesome if you can

**Comment by Dynexyst** [comment]
I think audio works on some bluetooth adapters including of course, sony's official one. I'd really like to see this work on "normal" bluetooth adapters too though.

**Comment by greggameplayer** [comment]
@Dynexyst sony official adapter cost so much compared to "normal" bluetooth adapters and is it normal that my stick drift sometimes especially the right one ?

**Comment by haywirephoenix** [comment]
#1268
