### ISSUE TITLE
Feature Request: Right click on touchpad (in profile edit) to Invert X and/or Y axis.

### ISSUE THREAD

**Issue by vvilkommen** [Ryochan7/DS4Windows#83]
The ability to right click on a thumbstick and invert an axis has really been a game changer for me. There are more than a few game developers that apparently think people are only ever keen to invert y and not x. Now I can play those games, too!

But, I often use touchpad and R-thumb in the same game for camera control in different situations (sometimes using one over the other just "feels" better, if you can relate). While it is great to be able to invert x, for example, on the right thumbstick, going back to normal (non-inverted) camera control when using the touchpad is jarring and confusing. 

Request: I would like to be able to right click on the touchpad and invert axis, similar to the right click on thumbstick menu. I wouldn't need all of those functions, e.g., face button emulation, but I really would like to be able to invert x axis on touchpad too instead of having to rely on game developers to add an axis inversion setting for mouse camera control (if they won't for thumbstick, they certainly won't for mouse!)

**Comment by Ryochan7** [comment]
It probably would not take much work to add the option to invert either axis. The option would probably be presented under the current touchpad "Use as Mouse" section though.

**Comment by vvilkommen** [comment]
Bacon and eggsellent news! I can't wait

**Comment by Ryochan7** [comment]
A touchpad axis inverting option is now available in version 1.4.85. You can invert a single axis for mouse controls or both axes if you would want to do that.

**Comment by vvilkommen** [comment]
Thanks! This is awesome!

However, would it be possible to add a qualifier button too? Like "do not invert when button whatever is held" for games where you really would not want the mouse cursor movement inverted (so one would hold the qualifier button down then) and leave the inversion in place when, in the same game, the touchpad is being used for camera?
