### ISSUE TITLE
Lactency spikes getting really bad

### ISSUE THREAD

**Issue by cristianmars22** [Ryochan7/DS4Windows#830]
Hello I'm posting here because Google is not helping , I'm having really bad lactency spikes with the latest version i been using the same controller with the same Bluetooth dongle in the same Pc at 1 meter max distance and when I connect the joysticks everything seems fine , then i open a game start flashing once every minute and as I keep playing it gets worse until that the input lag is so bas that I cannot play anymore the inputs get stuck with a delay of 5 seconds and worse .

So I've tried a couple of things , high performance mode on Windows , don't allow the Pc to turn off the device , uninstalled ds4 Windows , vigembus and Bluetooth drivers and still persist I even reinstalled windows keeping the program and data but still a fresh install I even buyed a new dongle.

Thanks in advance . Good day.

**Comment by mika-n** [comment]
What do you see in Logs tab page of DS4Win app?

Do you get the same lag with earlier versions of DS4Win? You can have multiple versions of DS4Win installed in different folders. All recent versions work with the same profile and config files (ie. no changes in config file format).

**Comment by cristianmars22** [comment]
Let me get home and try older versiona I don't know why I didn't thought of that

**Comment by cristianmars22** [comment]
so im gonna present the info you asked in the best way posible so : 

1.- I use an older vercion all the way back to 1.5.20 , still present.
2.- Log page shows up lactency is now over 10 ms and lactensy is now under 10 ms back and forth 
3.- i tried to uninstall all bluetooth things again and vigen bus driver restarted and re installed again and keeps happening
4.- while we are at it i can tell you that when i switch the color of the ligth on a profile configuration it crashes ds4 windows with an error of the track bar.
5.- the courious thing is that if i dont open a game it doesn´t increase lactency

**Comment by cristianmars22** [comment]
> What do you see in Logs tab page of DS4Win app?
> 
> Do you get the same lag with earlier versions of DS4Win? You can have multiple versions of DS4Win installed in different folders. All recent versions work with the same profile and config files (ie. no changes in config file format).

so im gonna present the info you asked in the best way posible so :

1.- I use an older vercion all the way back to 1.5.20 , still present.
2.- Log page shows up lactency is now over 10 ms and lactensy is now under 10 ms back and forth
3.- i tried to uninstall all bluetooth things again and vigen bus driver restarted and re installed again and keeps happening
4.- while we are at it i can tell you that when i switch the color of the ligth on a profile configuration it crashes ds4 windows with an error of the track bar.
5.- the courious thing is that if i dont open a game it doesn´t increase lactency

**Comment by cristianmars22** [comment]
Okey.... so i figured  it out turns out that you should not have the ge force overlay turn on it makes conflict with the controller for some reason.

**Comment by mika-n** [comment]
Hmm... Interesting. Don't understand why and how GeForce overlay causes this kind of issue. However, it is known that GeForce opens a connection to gamepad devices because it may conflict with an exclusive mode in DS4Win. Maybe GeForce overlay somehow actively uses the gamepad device and causes extra burden to BT communication.

**Comment by cristianmars22** [comment]
I do have problems when I connect 2 controllers tho , but it's different it never gets to bad so I'm thinking that the Bluetooth bandwidth is not enough :/
