### ISSUE TITLE
[Feature Request] Lightbar toggle OFF

### ISSUE THREAD

**Issue by Darthagnon** [Ryochan7/DS4Windows#831]
I just (finally!) got a DS4, and was having some fun playing around with the settings in DS4 Windows, only to notice that there was no obvious "Lightbar OFF" switch - would it be possible to implement this? (NB I haven't experimented much, maybe it's possible to switch it off by sliding all sliders to 0, but imo it would be a bit easier/cleaner if there was an OFF checkbox). Pretty please? Thank you for an awesome tool!

**Comment by cristianmars22** [comment]
just put the color to black .

**Comment by Ryochan7** [comment]
Setting the color to black is all that can be done AFAIK. Although, I should look at this again and make sure that is the case. The controller report does require a flag to activate lightbar support.

**Comment by Darthagnon** [comment]
Or maybe a semi-redundant checkbox that sets all RGB values to 0, labelled "Lightbar Off"? Just saves dragging 6x sliders. Out of curiousity, why are there 6 RGB sliders? Aren't 3 all that's necessary? or are there multiple LEDs?

**Comment by cristianmars22** [comment]
You don't need to move sliders use the presets of colors and put it to black is literally 2 clicks

**Comment by Darthagnon** [comment]
T

> You don't need to move sliders use the presets of colors and put it to black is literally 2 clicks

I always overthink things lol. That makes sense and is easy to do! Thank you!
