### ISSUE TITLE
Inputs being duplicated while in-game

### ISSUE THREAD

**Issue by Thenubster** [Ryochan7/DS4Windows#832]
Hi all,

Noticed this issue starting tonight. Like the title says, the inputs are being duplicated and it's causing some issues. While playing Tetris Effect, pieces are being spun multiple times as well as being moved over one block farther than I had anticipated. Because this seems to be an issue with the analog stick, the d-pad, and the face buttons I figure it is likely an issue with the software.

I've also noticed that the usual method of stopping the NVIDIA overlay via services is not consistently connecting exclusively, where it used to be a reliable method. As of tonight, I've repeatedly gotten the exclusivity error before it just somehow works (though this is when the duplcated inputs start to happen).

I've restarted my computer, reinstalled the drivers from this version of DS4Windows, stopped NVIDIA services, and have enabled the wireless device via the control panel. I've tried on all 4 front-facing USB ports on my computer, as well; 2 USB3 and 2 USB2. Any further advice on how to get it working again? My Tetris game is taking a pretty hard nosedive because of this.

**Comment by Ryusennin** [comment]
Duplicated inputs usually mean the game sees both the physical and virtual controllers.

DS4Windows needs to have exclusivity over the physical controller. Have you tried the "Hide DS4 Controller" in the Settings tab? If that doesn't work, you'll have to uncheck that option and install HidGuardian for better exclusivity mode.

https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues
https://github.com/Ryochan7/DS4Windows/wiki/DS4Windows-and-HIDGuardian-Install-and-Setup-Guide

**Comment by Thenubster** [comment]
@Ryusennin  I do have the hide DS4 Controller option checked. I'll install this software and edit the post with my results.
