### ISSUE TITLE
Problem when assigning controls to the games.

### ISSUE THREAD

**Issue by AlienX97** [Ryochan7/DS4Windows#833]
I noticed that in some games like Trackmania United Forever game sees my gamepad as 2 controllers and im unable to change the settings in game options, i also got troubles when im assigning controls to old game like NFS MW 2005, where everytime i change the setting it see X-rotate always pressed so im unable to set up the steering too. In NFS ProStreet whatever i'd do, when i press right trigger game pause menu is opening. I installed this version with hope that all these problems from the Jay2Kings version will be resolved but i have been disappointed.

**Comment by Ryusennin** [comment]
Check issue #832.

**Comment by mika-n** [comment]
And before posting issue reports then please read the Troubleshooting and documentation page for tips. Please provide basic details about your environment and app versions and the content of Logs tab page in DS4Windows application:
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting

Exclusive mode explanation and an alternative solution using HidGuardian driver if the DS4Win built-in "Hide Controller" option doesn't work in your environment:
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues
