### ISSUE TITLE
No nacon revolution pro controller support

### ISSUE THREAD

**Issue by UnholyScribe** [Ryochan7/DS4Windows#834]
Article say that the support was added a while back but it is not working at all.

**Comment by mika-n** [comment]
Not very detailed problem description. Version of DS4Win app? Win version? Content of Logs tabpage in DS4win app? USB or Bluetooth connection? Does it work over USB, but not over BT? How does the controller look like in Windows OS device list?

Please take a look at this page for general troubleshooting tips.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting

Another tip to diagnose the issue. Download and run "DS4Windows_RazerUltimateBTDebug2.zip" debug version of DS4Win app (place the EXE in the zip file into the same folder where you have your normal DS4Win installation). What do you see in Logs tab page? The post also explains how to check the VID/PID (vendor-id/product-id) hardware identifier of your controller in DeviceManager.
https://github.com/Ryochan7/DS4Windows/issues/689#issuecomment-493413784
https://github.com/Ryochan7/DS4Windows/issues/803

**Comment by mika-n** [comment]
@UnholyScribe  See the following post and try to run the debug version of DS4Windows.exe. Download the ZIP file linked in the post and replace existing DS4windows.exe file with the debug version (take a backup copy of the original EXE file).
https://github.com/Ryochan7/DS4Windows/issues/839#issuecomment-536330527
