### ISSUE TITLE
Suddenly not working to bloodstain ritual of the night

### ISSUE THREAD

**Issue by Hentaidaiski69** [Ryochan7/DS4Windows#835]
I using my using my ds4 playing Bloodstain ritual of the night to my pc working just fine using hide ds4 and other day I use again my ds4 and now the ds4 stop working for this game and the only thing working is home button and tracking pad even i use hide ds4 but the other game like doa 6 and final fantasy is working just fine even I using default settings.

Any help?

PS. I uninstall my steam, epic games and I tried to uninstall and reinstall the ds4windows is still not working to this game.

**Comment by mika-n** [comment]
Please post more details. Version of Winos and DS4Win app? Do you use a profile with x360 or dualshock4 output controller type? Have tired to use default profile settings? What do you see in Logs tab page of DS4Win app?
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting

More info about exlusive mode and tips how to get it working (or use alternative solution with HidGuardian tool).
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

**Comment by Hentaidaiski69** [comment]
> 
> 
> Please post more details. Version of Winos and DS4Win app? Do you use a profile with x360 or dualshock4 output controller type? Have tired to use default profile settings? What do you see in Logs tab page of DS4Win app?
> https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting
> 
> More info about exlusive mode and tips how to get it working (or use alternative solution with HidGuardian tool).
> https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

Hi thanks for the reply im using version 1903 windows 10 and I'm using profile of x360 and I'm already using default settings but is still the same and I uninstall all my steam uplay epic games and still the same and  the log and is :
![image](https://user-images.githubusercontent.com/55672093/65473374-22227180-deaa-11e9-89dd-1c8d2208f6f6.png)

**Comment by mika-n** [comment]
The logfile shown in your screenshot doesn't indicate that you are using exclusive mode (=HideDS4Controller option) in DS4Win. If you don't use exclusive mode of DS4Win app or an alternative HidGuardian tool (hidg is not part of DS4Win because it is a separate driver) then double input in a game is one very common side effect.

If you use Steam to play games then you may have to rename the DS4Windows.exe executable file because recent Steam client versions actively ignores DS4 gamepad  if certain processes are running in the background.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#steam-doesnt-see-the-virtual-output-controller-if-a-profile-uses-the-dualshock4-output-type-steam-sees-the-ds4-controller-only-if-ds4windows-uses-xbox360-output-controller-type

**Comment by Hentaidaiski69** [comment]
> 
> 
> The logfile shown in your screenshot doesn't indicate that you are using exclusive mode (=HideDS4Controller option) in DS4Win. If you don't use exclusive mode of DS4Win app or an alternative HidGuardian tool (hidg is not part of DS4Win because it is a separate driver) then double input in a game is one very common side effect.
> 
> If you use Steam to play games then you may have to rename the DS4Windows.exe executable file because recent Steam client versions actively ignores DS4 gamepad if certain processes are running in the background.
> https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#steam-doesnt-see-the-virtual-output-controller-if-a-profile-uses-the-dualshock4-output-type-steam-sees-the-ds4-controller-only-if-ds4windows-uses-xbox360-output-controller-type

Hello is still the same same issue im using exclusive mode

![image](https://user-images.githubusercontent.com/55672093/65537550-ffd73500-df37-11e9-9d49-8639ed51ae8d.png)

**Comment by Hentaidaiski69** [comment]
Hello it's works now but I'm using old version of ds4windows when using new update of ds4 the issue is still persist.

**Comment by mika-n** [comment]
Hmmm..... Very strange. What old version exactly you are now using? Although, I don't see how the new version could break the functionality of PS4 gamepad in such a way that it doesn't work with some games, but works with others.

Are you using different profiles per game? Maybe this is a profile issue? Have you tried to delete all DS4Win config and profile files and to start from scratch with the new version?
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#nothing-works-and-ds4windows-app-and-vigem-driver-connection-silently-doesnt-do-anything

**Comment by Hentaidaiski69** [comment]
> Hmmm..... Very strange. What old version exactly you are now using? Although, I don't see how the new version could break the functionality of PS4 gamepad in such a way that it doesn't work with some games, but works with others.
> 
> Are you using different profiles per game? Maybe this is a profile issue? Have you tried to delete all DS4Win config and profile files and to start from scratch with the new version?
> https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#nothing-works-and-ds4windows-app-and-vigem-driver-connection-silently-doesnt-do-anything

Hello thanks for the reply. Im using latest jay2kings ds4windows version its work like charm and its works all of my games but its have slightly bugs and tolerable like the battery is not accurate and yes Im using different profiles and I tried all to delete all the profiles the issue is still persist on newer version.

**Comment by Hentaidaiski69** [comment]
Oh it works now using newer version. Thank you Mika you saved my day.
