### ISSUE TITLE
When I save it

### ISSUE THREAD

**Issue by Khahory** [Ryochan7/DS4Windows#837]
![Anotación 2019-09-24 010741](https://user-images.githubusercontent.com/46386012/65482671-ccc57080-de67-11e9-9da7-a406862a534a.png)
![Anotación 2019-09-24 010941](https://user-images.githubusercontent.com/46386012/65482750-0a29fe00-de68-11e9-93da-6a451ce3d5b8.png)

**Comment by Khahory** [comment]
This appears when I try to save any profile

**Comment by mika-n** [comment]
If you edit and save a profile WITHOUT connecting a gamepad to PC then does it work in that case?

This issue has been reported already, but why it happens on some systems but no on other systems is a bit mystery. 
https://github.com/Ryochan7/DS4Windows/issues/823

**Comment by Khahory** [comment]
Ok, ty
