### ISSUE TITLE
Problem with Xinput

### ISSUE THREAD

**Issue by AlienX97** [Ryochan7/DS4Windows#838]
It would be nice if there would be an option for emulating the DInput mode, i got problems with some games like WarThunder or Il2 Sturmovik 1996 where i can't assign the ailerons to the triggers, its because it can't assign it to the two separate axes, but for single axis. Triggers LT/RT are visible in Xinput as two separate axes, would be nice if there would be possibility to recognize them as a single axis, its the only way to assign a function to them in many games.

**Comment by mika-n** [comment]
Is BetterDS3 only for PS3 gamepad? This DS4Win app is for PS4 gamepads and natively PS3 and PS4 gamepads are a bit different. However, the trick I explained fools games to see L2 and R2 trigger keys through a single axis. I thought this was your intention?

Or you can use DS4Win application with a default profile and it uses xbox360 output controller mode. XInput uses a single axis with analog trigger keys by default. DS4Win app does support DInput mode also ("Use DInput only" or by using "dualshock4" virtual output controller type).

Feel free to test the trick I explained. That's how you will find out if it works. Or maybe I just misunderstood what you were trying to achieve.

**Comment by Ryochan7** [comment]
This seems like a difference between the MotioninJoy driver and the ViGEmBus driver. With all the output modes available with ViGEmBus, the output triggers would be seen as two separate axes. Games that do not natively support XInput would end up using the fallback DirectInput interface where both triggers would be mapped to one axis though.

There is no way to output an arbitrary DirectInput controller in ViGEmBus. The only DirectInput-only output option available is the DualShock 4 output mode. Despite seeming like a redundant option in DS4Windows (DS4 input to DS4 output), that output mode has been useful on a few occasions. The Use DInput only option in a profile just removes the virtual controller so the native DS4 DirectInput interface can be used when connected via USB; that option won't work when connected via BT.

**Comment by AlienX97** [comment]
So there will be no possibility to at least connect the two trigger axes?, in War Thunder are recognized 8 axes of xinput, i mean that there would be also 9th axis with both L2/R2 axes connected into one, is that possible?

**Comment by AlienX97** [comment]
Oh sorry i noticed in WarThunder i can set up as ailerons both LT/RT axes, i dont know how i manged to do that, i appreciate your help thanks.

**Comment by AlienX97** [comment]
Ok i managed to configure the triggers correctly Though i dont know what i did, both axes are recognised correctly, thank you for all help.
