### ISSUE TITLE
All vibration (rumble) recieved on controller #1 when 2 controllers are connected

### ISSUE THREAD

**Issue by asheraryam** [Ryochan7/DS4Windows#841]
DS4Windows verison: 1.7.17

Controller details: controller 1 is ver2 on bluetooth, controller 2 is ver1 on usb.

Issue:

While playing a coop game with rumble, the 1st controller was the one receiving the vibration for both controller 1 & 2.

The 2nd controller did not receive any rumble.

**Comment by mika-n** [comment]
Here two controllers and a rumble works just fine. Each controller receives their own rumble effects. Maybe this is an application specific issue? What is the app/game having this kind of issue? 

Are you using the latest ViGem device driver? Please note that when DS4Windows updates itself then it doesn't update ViGem driver. Only if the VigEm driver is missing then DS4Windows asks a permission to install it.

Head to the following web page and dowload ViGEmBus_Setup_1.16.115.exe package from there and install it just in case.
https://github.com/ViGEm/ViGEmBus/releases

**Comment by asheraryam** [comment]
Thank you I will update the ViGem device driver and test other games to make sure if this is an application specific issue and then I will get back to comment.
