### ISSUE TITLE
Gyro settings tab is visually obstructed

### ISSUE THREAD

**Issue by ejoflo** [Ryochan7/DS4Windows#842]
Navigate to:
Controllers > Edit > Controls > Gyro

Change Output Mode to: 
Mouse Joystick

The user interface gets cut off after Eval Cond: and you can no longer view the rest of the settings/parameters.

Screenshot below:
![Clipboard01](https://user-images.githubusercontent.com/51680874/65996581-61653b00-e433-11e9-8461-c1402b57246c.jpg)

**Comment by Ryochan7** [comment]
Looks like the FlowLayout container being used is not working as intended. Hopefully increasing the width of the container will be enough to fix that problem.

**Comment by Ryochan7** [comment]
I need to get around to making a new release with the change. Been too busy with the test WPF version.
