### ISSUE TITLE
Wireless Controller Not Showing Up

### ISSUE THREAD

**Issue by chr1s99** [Ryochan7/DS4Windows#845]
My DS4 Wireless Controller is connected on win10 but when i load up ds4Windows it doesnt show up, i have the ViGEmBus driver installed and the C++ Redistributable 2017 installed also.

**Comment by mika-n** [comment]
Not very detailed problem description. Please see this documentation page (and other tips in the Troubleshooting wiki page):
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

Please go through this page and provide the basic information about your setup:
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting

**Comment by Ryochan7** [comment]
Does it work in Windows? Please check the Game Controller settings section of Devices and Printers portion of the Control Panel. Make sure that it can read the controller. If it cannot then it will not work in DS4Windows.

**Comment by chr1s99** [comment]
Update, updated my windows and waited a day or so and it’s now working, don’t know why that would fix it but there you go
