### ISSUE TITLE
CSR support

### ISSUE THREAD

**Issue by Rameron** [Ryochan7/DS4Windows#846]
Hello!

Is planning the support of CSR Bluetooth adapters? Or there are some technical restrictions?

Thanks.

**Comment by nikita36078** [comment]
It works fine with a CSR8510 dongle, Windows 10. Make sure you're using default Windows drivers, not the CD ones.

**Comment by Rameron** [comment]
> It works fine with a CSR8510 dongle, Windows 10. Make sure you're using default Windows drivers, not the CD ones.

It works, but I have 3 devices without the drivers in device manager. Anyway, this is solution.

**Comment by Ryochan7** [comment]
CSR adapters should work fine as long as you are using the default drivers and the MS BT stack. My main BT adapter is a CSR adapter.
