### ISSUE TITLE
is the Hori fighting commander ps4/ps3/pc supported?

### ISSUE THREAD

**Issue by antervud** [Ryochan7/DS4Windows#847]
it's only usb wired, no bluetooth

**Comment by mika-n** [comment]
Some Hori controller models work, but others don't. What is the hardware VendorID/ProductID (VID/PID) identifiers of your controller mode? This can be seen in DeviceManager/<gamepad device entry under HID devices>/Properties/HardwareID screen.

Or you could run a special debug version of DS4Windows.exe executable and it should list the VID/PID in Logs tab page.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

Similar issue with another non-official Sony controller.
https://github.com/Ryochan7/DS4Windows/issues/803

**Comment by antervud** [comment]
i'm waiting for delivery, should be here in few days

**Comment by antervud** [comment]
HID\VID_0F0D&PID_0084&REV_0100&Col01
HID\VID_0F0D&PID_0084&Col01
HID\VID_0F0D&UP:0001_U:0005
HID_DEVICE_SYSTEM_GAME
HID_DEVICE_UP:0001_U:0005
HID_DEVICE

here's what i got, the pad is connected in ps4 mode,  does not show up in normal ds4 nor in the debug version

**Comment by mika-n** [comment]
Try to run "DeviceDetectDebug9" version linked in the following page and please provide the logfile here.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

**Comment by antervud** [comment]
19/10/2019 19:40:03: DS4Windows version 1.7.17
19/10/2019 19:40:04: LinkedProfiles.xml can't be found.
19/10/2019 19:40:04: Starting...
19/10/2019 19:40:04: Connection to ViGEmBus 1.16.112.0 established
19/10/2019 19:40:04: Searching for controllers...
19/10/2019 19:40:04: Using Exclusive Mode
19/10/2019 19:40:04: DEBUG: EnumerateDS4. HID#1 Path=\\?\hid#vid_051d&pid_0002#7&29f257ed&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=APC UPS  VID=0x051D  PID=0x0002  Usage=0x4  Version=0x106
19/10/2019 19:40:04: DEBUG: EnumerateDS4. HID#2 Path=\\?\hid#vid_046d&pid_c53f&mi_00#8&1b2da78a&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd  Description=Tastiera HID  VID=0x0000  PID=0x0000  Usage=0x0  Version=0x0
19/10/2019 19:40:04: DEBUG: EnumerateDS4. HID#3 Path=\\?\hid#vid_046d&pid_c53f&mi_02&col01#8&f19f60d&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=Dispositivo compatibile HID definito da fornitore  VID=0x046D  PID=0xC53F  Usage=0x1  Version=0x4400
19/10/2019 19:40:04: DEBUG: EnumerateDS4. HID#4 Path=\\?\hid#vid_0c76&pid_161e&mi_02#8&2957cf17&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=Dispositivo controllo consumi compatibile HID  VID=0x0C76  PID=0x161E  Usage=0x1  Version=0x100
19/10/2019 19:40:04: DEBUG: EnumerateDS4. HID#5 Path=\\?\hid#vid_046d&pid_c53f&mi_02&col02#8&f19f60d&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=Dispositivo compatibile HID definito da fornitore  VID=0x046D  PID=0xC53F  Usage=0x2  Version=0x4400
19/10/2019 19:40:04: DEBUG: EnumerateDS4. HID#6 Path=\\?\hid#vid_046d&pid_c232#2&1a87f3a8&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd  Description=Tastiera HID  VID=0x0000  PID=0x0000  Usage=0x0  Version=0x0
19/10/2019 19:40:04: DEBUG: EnumerateDS4. HID#7 Path=\\?\hid#vid_046d&pid_c231#2&2fdf093d&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=Mouse compatibile HID  VID=0x0000  PID=0x0000  Usage=0x0  Version=0x0
19/10/2019 19:40:04: DEBUG: EnumerateDS4. HID#8 Path=\\?\hid#vid_046d&pid_c53f&mi_02&col03#8&f19f60d&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=Dispositivo compatibile HID definito da fornitore  VID=0x046D  PID=0xC53F  Usage=0x4  Version=0x4400
19/10/2019 19:40:04: DEBUG: EnumerateDS4. HID#9 Path=\\?\hid#vid_046d&pid_c53f&mi_01&col01#8&32f133cf&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=Mouse compatibile HID  VID=0x0000  PID=0x0000  Usage=0x0  Version=0x0
19/10/2019 19:40:04: DEBUG: EnumerateDS4. HID#10 Path=\\?\hid#vid_046d&pid_c53f&mi_01&col02#8&32f133cf&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=Dispositivo controllo consumi compatibile HID  VID=0x046D  PID=0xC53F  Usage=0x1  Version=0x4400
19/10/2019 19:40:04: DEBUG: EnumerateDS4. HID#11 Path=\\?\hid#vid_046d&pid_c53f&mi_01&col03#8&32f133cf&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=Controller di sistema compatibile HID  VID=0x046D  PID=0xC53F  Usage=0x80  Version=0x4400
19/10/2019 19:40:04: DEBUG: EnumerateDS4. HID#12 Path=\\?\hid#vid_046d&pid_c53f&mi_01&col04#8&32f133cf&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=Dispositivo compatibile HID definito da fornitore  VID=0x046D  PID=0xC53F  Usage=0x88  Version=0x4400
19/10/2019 19:40:04: DEBUG: EnumerateDS4. HID#13 Path=\\?\hid#vid_0f0d&pid_0084&col01#7&1e35070&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=Controller gioco compatibile HID  VID=0x0F0D  PID=0x0084  Usage=0x5  Version=0x100
19/10/2019 19:40:04: DEBUG: EnumerateDS4. HID#13 detected as possible DS4 compatible gamepad device
19/10/2019 19:40:04: DEBUG: EnumerateDS4. HID#14 Path=\\?\hid#vid_0f0d&pid_0084&col02#7&1e35070&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=Dispositivo compatibile HID definito da fornitore  VID=0x0F0D  PID=0x0084  Usage=0x40  Version=0x100
19/10/2019 19:40:04: DEBUG: IsRealDS4. IsRealDS4=True  hDevicePath=\\?\hid#vid_0f0d&pid_0084&col01#7&1e35070&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  deviceInstanceID=hid\vid_0f0d&pid_0084&col01\7&1e35070&0&0000  Device_UINumber=
19/10/2019 19:40:04: DEBUG: findControllers. Found 1 possible device
19/10/2019 19:40:04: DEBUG: findControllers. Idx=0 Potential DS4 gamepad. Description=Controller gioco compatibile HID  Path=\\?\hid#vid_0f0d&pid_0084&col01#7&1e35070&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
19/10/2019 19:40:04: DEBUG: findControllers. idx=0 Opening device VID=0x0F0D  PID=0x0084  isExclusiveMode=True
19/10/2019 19:40:04: DEBUG: findControllers. idx=0 Error opening device. Requested exclusive access, but it failed to open. Trying again using elevated priviledges and in shared mode
19/10/2019 19:40:05: DEBUG: findControllers. idx=0 IsOpen=True
19/10/2019 19:40:05: DEBUG: readSerial. Trying to read serial# from \\?\hid#vid_0f0d&pid_0084&col01#7&1e35070&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
19/10/2019 19:40:05: DEBUG: readSerial. Reading serial# from InputReport buffer Len=64
19/10/2019 19:40:05: DEBUG: readSerial. ERROR. Failed to read serial# as HID FeatureData. Using a dummy MAC code
19/10/2019 19:40:05: DEBUG: findControllers. idx=0 IsValidSerial=True  Serial=00:00:00:00:00:10
19/10/2019 19:40:05: DEBUG: findControllers. idx=0 Using device \\?\hid#vid_0f0d&pid_0084&col01#7&1e35070&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  metainfo.name=Hori Fighting Commander
19/10/2019 19:40:05: DEBUG: findControllers. idx=0 OK. DS4Win uses the device as input source
19/10/2019 19:40:05: Found Controller: 00:00:00:00:00:10 (USB) (Hori Fighting Commander)
19/10/2019 19:40:05: Warning: Could not open DS4 00:00:00:00:00:10 exclusively. You must quit other applications like UWP apps (Netflix), Steam, Uplay, NVIDIA IN-GAME before activating the 'Hide DS4 Controller' option. For more info check https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues
19/10/2019 19:40:05: Plugging in X360 Controller #1
19/10/2019 19:40:05: X360 Controller #1 connected
19/10/2019 19:40:05: Controller 1 is using Profile “Default"
19/10/2019 19:40:07: DEBUG: EnumerateDS4. HID#1 Path=\\?\hid#vid_051d&pid_0002#7&29f257ed&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=APC UPS  VID=0x051D  PID=0x0002  Usage=0x4  Version=0x106
19/10/2019 19:40:07: DEBUG: EnumerateDS4. HID#2 Path=\\?\hid#vid_046d&pid_c53f&mi_00#8&1b2da78a&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd  Description=Tastiera HID  VID=0x0000  PID=0x0000  Usage=0x0  Version=0x0
19/10/2019 19:40:07: DEBUG: EnumerateDS4. HID#3 Path=\\?\hid#vid_046d&pid_c53f&mi_02&col01#8&f19f60d&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=Dispositivo compatibile HID definito da fornitore  VID=0x046D  PID=0xC53F  Usage=0x1  Version=0x4400
19/10/2019 19:40:07: DEBUG: EnumerateDS4. HID#4 Path=\\?\hid#vid_0c76&pid_161e&mi_02#8&2957cf17&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=Dispositivo controllo consumi compatibile HID  VID=0x0C76  PID=0x161E  Usage=0x1  Version=0x100
19/10/2019 19:40:07: DEBUG: EnumerateDS4. HID#5 Path=\\?\hid#vid_046d&pid_c53f&mi_02&col02#8&f19f60d&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=Dispositivo compatibile HID definito da fornitore  VID=0x046D  PID=0xC53F  Usage=0x2  Version=0x4400
19/10/2019 19:40:07: DEBUG: EnumerateDS4. HID#6 Path=\\?\hid#vid_046d&pid_c232#2&1a87f3a8&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd  Description=Tastiera HID  VID=0x0000  PID=0x0000  Usage=0x0  Version=0x0
19/10/2019 19:40:07: DEBUG: EnumerateDS4. HID#7 Path=\\?\hid#vid_046d&pid_c231#2&2fdf093d&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=Mouse compatibile HID  VID=0x0000  PID=0x0000  Usage=0x0  Version=0x0
19/10/2019 19:40:07: DEBUG: EnumerateDS4. HID#8 Path=\\?\hid#vid_046d&pid_c53f&mi_02&col03#8&f19f60d&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=Dispositivo compatibile HID definito da fornitore  VID=0x046D  PID=0xC53F  Usage=0x4  Version=0x4400
19/10/2019 19:40:07: DEBUG: EnumerateDS4. HID#9 Path=\\?\hid#vid_046d&pid_c53f&mi_01&col01#8&32f133cf&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=Mouse compatibile HID  VID=0x0000  PID=0x0000  Usage=0x0  Version=0x0
19/10/2019 19:40:07: DEBUG: EnumerateDS4. HID#10 Path=\\?\hid#vid_046d&pid_c53f&mi_01&col02#8&32f133cf&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=Dispositivo controllo consumi compatibile HID  VID=0x046D  PID=0xC53F  Usage=0x1  Version=0x4400
19/10/2019 19:40:07: DEBUG: EnumerateDS4. HID#11 Path=\\?\hid#vid_045e&pid_028e&ig_00#3&1efb2488&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=Controller gioco compatibile HID  VID=0x045E  PID=0x028E  Usage=0x5  Version=0x0
19/10/2019 19:40:07: DEBUG: EnumerateDS4. HID#12 Path=\\?\hid#vid_046d&pid_c53f&mi_01&col03#8&32f133cf&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=Controller di sistema compatibile HID  VID=0x046D  PID=0xC53F  Usage=0x80  Version=0x4400
19/10/2019 19:40:07: DEBUG: EnumerateDS4. HID#13 Path=\\?\hid#vid_046d&pid_c53f&mi_01&col04#8&32f133cf&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=Dispositivo compatibile HID definito da fornitore  VID=0x046D  PID=0xC53F  Usage=0x88  Version=0x4400
19/10/2019 19:40:07: DEBUG: EnumerateDS4. HID#14 Path=\\?\hid#vid_0f0d&pid_0084&col01#7&1e35070&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=Controller gioco compatibile HID  VID=0x0F0D  PID=0x0084  Usage=0x5  Version=0x100
19/10/2019 19:40:07: DEBUG: EnumerateDS4. HID#14 detected as possible DS4 compatible gamepad device
19/10/2019 19:40:07: DEBUG: EnumerateDS4. HID#15 Path=\\?\hid#vid_0f0d&pid_0084&col02#7&1e35070&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=Dispositivo compatibile HID definito da fornitore  VID=0x0F0D  PID=0x0084  Usage=0x40  Version=0x100
19/10/2019 19:40:07: DEBUG: IsRealDS4. IsRealDS4=True  hDevicePath=\\?\hid#vid_0f0d&pid_0084&col01#7&1e35070&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  deviceInstanceID=hid\vid_0f0d&pid_0084&col01\7&1e35070&0&0000  Device_UINumber=
19/10/2019 19:40:07: DEBUG: findControllers. Found 1 possible device
19/10/2019 19:40:07: DEBUG: findControllers. Idx=0 Potential DS4 gamepad. Description=Controller gioco compatibile HID  Path=\\?\hid#vid_0f0d&pid_0084&col01#7&1e35070&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}

**Comment by antervud** [comment]
[export.txt](https://github.com/Ryochan7/DS4Windows/files/3747004/export.txt)

**Comment by mika-n** [comment]
The debug version detects the Hori Fighting Commander, but does it actually work in DS4Windows? Can you re-map buttons? 
The gamepad has a special switch to alter how DPad keys work (dpad, left stick, right stick). Does that functionality work?
If you open Joy.cpl controlPanel applet then do you see any activity in the virtual x360 gamepad controller device?

**Comment by antervud** [comment]
works in the debug version, does not work in the latest normal version, switch are hardware so they work without a special driver

is fine on joy.cpl, it is strangely named Controller (Sega Controller)

**Comment by mika-n** [comment]
Hmmm... The virtual output driver of DS4Windows should be "Controller (XBOX 360 for Windows)" controller in JOY:CPL controlPanel applet. I don't understand why and how it would be shown as "Controller (Sega Controller)". 

Are you sure that this SegaController isn't the original physical controller? IF you don't use exclusive mode (or it fails to activate) or don't use HidGuardian then you should see two gamepad controlelrs in JOY:CPL applet. The physical original controller and a virtual x360 output controller created by DS4Windows app and ViGem driver.

The logfile you provide does have a warning message about exclusive mode (it failed to activate):

`19/10/2019 19:40:05: Warning: Could not open DS4 00:00:00:00:00:10 exclusively. You must quit other applications like UWP apps (Netflix), Steam, Uplay, NVIDIA IN-GAME before activating the 'Hide DS4 Controller' option. For more info check https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues
`

See the following page for more tips about exlusive mode (built-in in DS4Windows app) and alternative solution of HidGuardian device driver.
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

**Comment by antervud** [comment]
i had steam on probably, as of now

![ds4bebug](https://user-images.githubusercontent.com/7039987/67159590-c7fcbb00-f346-11e9-9743-ef19dcf2edc1.jpg)
![joy cpl](https://user-images.githubusercontent.com/7039987/67159593-d054f600-f346-11e9-8472-6e6bf7ec9f3f.jpg)
[export2.txt](https://github.com/Ryochan7/DS4Windows/files/3747852/export2.txt)

seems fine now, i will try it in game then report

**Comment by antervud** [comment]
now that i remember, i have a sega megadrive controller clone with xinput, thats probably the first xinput device i had installed on my pc, dunno if that's related

**Comment by mika-n** [comment]
Okey. Probably that SegaMegadriveController device driver has hijacked the normal xbox 360 controller device, so your PC shows a different name. If things work with this clone driver then all is good.

About the Steam client and DS4Windows.exe process name there is a potential problem (=bad feature in Steam client) if you want to use the DS4Windows re-mapped device in Steam games. See the following post about how Steam actively ignores DS4 gamepad if certain other processes are running at the same time. The solution is to re-name DS4Windows.exe executable to some other name.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#steam-doesnt-see-the-virtual-output-controller-if-a-profile-uses-the-dualshock4-output-type-steam-sees-the-ds4-controller-only-if-ds4windows-uses-xbox360-output-controller-type

Anyway. If you are happy with the HoriFightingCommander support in the debug version then I will push those changes to wait for some upcoming official release. Until then you should use the debug version.

**Comment by antervud** [comment]
i tried to play tekken 7 for 3 hours online with exclusive mode, steam sat to ignore my controller device

all went fine, no weird things happened, no input drops, seems to work
