### ISSUE TITLE
Posible Solution to latency spikes 

### ISSUE THREAD

**Issue by cristianmars22** [Ryochan7/DS4Windows#849]
So I don't know where to post this so here we go , if you're like me after connecting your ds4 playing a couple of minutes you star to get the spikes and it gets worst as the times goes to the point where it's not even playable any more I might have something that could solve that .

So I tried countless things , 3 Bluetooth dongles , formating and installing Windows 2 times , every single option in windows power plan , drivers new and old , usb power option , exclusive mode , configuration of preference of the gamepad ,  Bluetooth services , everything that comes up with Google and eventually I tried the most silly thing I just disable the touchpad as a mouse .

Solution: so to make things short go to your profile in ds4 windows under touchpad settings tick the option to use it as controls and don't assing anything save and leave it at that. I played arround an hour without a single spike and perfect latency so give it a go ! . Why it works ? I dont know it just does for me .

**Comment by mika-n** [comment]
"gamepad as a mouse"? Do you mean "touchpad as a mouse" or "gyro as a mouse"?

**Comment by cristianmars22** [comment]
I'm so sorry English is not my first language I meant touchpad. I'm gonna edit it to not confuse people.

**Comment by mika-n** [comment]
Okey. Jep. By default a new profile does use touchpad as a mouse control. 

But why it would cause BT lag is a bit strange because the physical gamepad sends the same HID report to a PC with button/axis/gyro/touchpad information regardless of this option in a DS4Windows profile. And DS4Windows app reads those incoming HID reports in the same input rate regardless of this option (or at least tries to read in the same rate).

The only difference is that if "Touchpad/Use as Mouse" is not used (ie. it is set as "Use for controls") then DS4Windows won't generate mouse movement and click events based on how finger moves around in a touchpad. This logic is the same for both USB and BT connected gamepads.

If this option causes some lag in BT communication then there may be some bug in DS4Windows and/or in WinOS how it handles these "programmatically generated" mouse movement events. Flooding a message queue in WinOS, maybe?

Generic "Settings" option (ie. common for all profiles) has also an option "Swipe Touchpad to change profiles" option. You may wanna disable this option if touchpad events are somehow culprit to this BT lag and you don't use touchpad to change profiles anyway. If this option is set then you may accidentally cause unnecessary profile changes when a finger accidentally swipes left to right in a touchpad.

**Comment by cristianmars22** [comment]
I'm not at home right know but based on what you're saying I'm gonna do a little more of testing at home ,I do in fact use the swipe to change profiles option no problems just disabling the touchpad worked wonders for me . First I thought that  maybe windows didn't like having 2 inputs for the same thing but if that where the case a lot more of people would've having the same problem , what I want to test now is that I have my mouse a Logitech g403 set to a polling rate of 1000hz ( 1ms ) maybe that is conflicting with the touch pad? I was thinking the differences of polling rates or just to much ?

Also if you want me to do some testing and report I have no problem !

**Comment by mika-n** [comment]
@cristianmars22  How is the bluetooth lag now when you have test it few more days without enabling "Use touchpad for mouse" option? 

Profile settings have "Enable touchpad toggle" option in "Other" tab page. Do you have it enabled? 
If you use "Use touchpad for mouse" and you have "Enable touchpad toggle" enabled then do you get BT lag if you toggle off the touchpad mouse functionality (ie. press "PS" and click touchpad at the same time. This key combination enables/disables touchpad mouse functionality).

**Comment by cristianmars22** [comment]
so i been doing some testing , things goes like this.

The problem i think i just got lucky and that time didnt have lactency , so tried cheking for electricity problems and nothing seems wrong , i disabled the allow the computer to turn off this device on the usb that is connected , re installed vigem bus from the git hub no throug ds4windows , mover the dongle to the back of the case i read some where that front usb ports use less power (even tho is the same pc and case and i neve had a problem with this ports) , and changed the driver from generic bluetooth radio to dongle the one that comes with windows to se if it makes a diference , i tried to unplug a wifi extender that i have and didnt seem to make a diference , also i tried lowering the polling rate of my mouse to see if it makes a diference and nothing. I dont know what else to try its amazing the problems that this is giving me i use this program for 3 years now and never had a single problem even with my old bluetooth 2.0 dongle it started one day and it never fixed.

**Comment by mika-n** [comment]
BT with other than Sony's official BT dongle for PC is sometimes a pain. Random lags or even disconnects. It really depends on the BT dongle how compatible it is with DS4.

But, few things you could try
- Do you have NVidia GPu and NVidia GeForce Experience Overlay installed and enabled? Try disabling NVidia game overlay feature. Some users have complained that it has caused some weird lag (NVidia Overlay tries to communicate the gamepad and this way overfloods the BT channel?)

- Do you have HidGuardian installed or do you use built-in exclusive mode (="Hide DS4 Controller" option)? Try with and without exclusive mode if it makes a difference (well, some games do require exclusive mode or HidGuardian, so this is not an option with those games).
- If you use "Hide ds4 Controller" exclusive mode then try without it, but install a HidGuardian tool.  This way you can hide the original physical controller from all other apps but DS4Windows and other apps cannot interfere with the DS4 gamepad.

https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues
https://github.com/Ryochan7/DS4Windows/wiki/DS4Windows-and-HIDGuardian-Install-and-Setup-Guide#hidguardian-test-installer

**Comment by cristianmars22** [comment]
I suppose I give up it evens disconects my controller after a while I don't know what else to try or do

**Comment by mika-n** [comment]
Have you tried "HidGuardian" device driver to hide the original physical controller from all other apps? If exclusive-mode in DS4Windows fails then there is danger that some other apps does something fancy with the gamepad. HidGuardian is the best way to hide the original controller if exclusive mode (=HideDS4Controller option in DS4Win app) doesn't work.

https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues
https://github.com/Ryochan7/DS4Windows/wiki/DS4Windows-and-HIDGuardian-Install-and-Setup-Guide#hidguardian-test-installer


If you have a non standard DS4 gamepad controller then you may have to tweak "AffectedDevices" sysreg config entry of HidGuardian tool. Google "HidGuardian AffectedDevices" for more info what that registry setting does and what should go there (VID and PID hardware IDs of the controller).
https://github.com/Ryochan7/DS4Windows/issues/720

**Comment by cristianmars22** [comment]
yes i tried the installer and i think i got it working because i can not see the dualshock4 on the devices list just the xbox controller i still have latency i think im gonna start trying older versions one by one

**Comment by Ryochan7** [comment]
That is an odd problem. One odd possible reason for that issue would be that some Exception is being thrown around in the background only when the Trackball routine is run. Exceptions can really bog down the .NET Runtime as I have encountered before. That is especially true with how often the input loop runs.

Unfortunately, Trackball mode works just fine in all my profiles. The only way to diagnose this problem further would be for you to download the DS4Windows source code and run a Debug build of the program in Visual Studio.
