### ISSUE TITLE
Wireless connection not working

### ISSUE THREAD

**Issue by RaideX101** [Ryochan7/DS4Windows#857]
I've been having problems connecting my genuine DS4 rev2's wireless connection. It used to work but after not using the controller for some time it won't connect automatically via pressing the PS button nor does it show up in the BT pairing menu in Windows 10.

What I usually do is to 'remove' the device from the bluetooth menu. That way I can re-pair it and that does the trick usually.

What concerns me is that there seems to be a ghost device with no controller plugged in that shows up in the device section.

![image](https://user-images.githubusercontent.com/6232467/67135818-3abe4700-f21e-11e9-9a50-7a7787eb38be.png)

When I try to remove that device it errors out.

![image](https://user-images.githubusercontent.com/6232467/67135837-7bb65b80-f21e-11e9-9694-9a3f34394ce5.png)

When I try to manually delete it in device manager I can remove it but it appears again after scanning for hardware changes.

I've tried all these things with DS4Windows closed and even with the driver uninstalled thinking that it may stop it from removing the device with no luck.

Wired connection works without problems (though not in exclusive mode if that makes a difference). I've tried unplugging and replugging my BT dongle (type BSN23996).

Not sure what's going on as I've had very little problems for a while now.

**Comment by venkateshmoganti** [comment]
Same here

**Comment by joeldbirch** [comment]
I just found your issue while attempting to fix this issue (not for the first time). I think I found the answer and I hope it works for you.

From the page "[Fix Bluetooth problems in Windows 10](https://support.microsoft.com/en-gb/help/14169/windows-10-fix-bluetooth-problems)"...

> 
> **Run the Bluetooth troubleshooter**
> Select the Start  button, then select Settings  > Update & Security  > Troubleshoot . Under Find and fix other problems, select Bluetooth, and then select Run the troubleshooter and follow the instructions.

I didn't see "Find and fix other problems", but I did see "Additional troubleshooters", which then lead me to the page where "Find and fix other problems" (and also Bluetooth) was.

When I ran the Bluetooth troubleshooter, it turned on Bluetooth (even though it was already on) and the Bluetooth icon appeared in my toolbar, which I hadn't noticed was missing. I was then able to re-pair the controller again and it showed up in both DS4Windows and the Windows Bluetooth menu.

Hope this helps!

**Comment by venkateshmoganti** [comment]
I am having the same issue. But this did not fix it.  
I installed the Ds4 for windows as instructed and showed in the video. My controller is connected to the Pc using cable and works fine. The controller is shown in the DS4 windows also. I tested it in GTA V. Everything works fine. But the color of the light bar is flashing yellow and not solid blue.
I turned on Bluetooth in my pc and ds4 controller. The game controller shows in the Bluetooth menu and when I click on it, it will process and gets connected and it displays connected on the pc. But still, the Bluetooth light bar flashes on my ps4 controller.

**Comment by RaideX101** [comment]
> I turned on Bluetooth in my pc and ds4 controller. The game controller shows in the Bluetooth menu and when I click on it, it will process and gets connected and it displays connected on the pc. But still, the Bluetooth light bar flashes on my ps4 controller.

Unfortunately this is not the same issue that I'm facing. I can connect my controller just fine via cable, yes. But when I try to pair my controller (share + PS button) I can't seem to find it. This goes for my bluetooth dongle as well as my internal one from the motherboard.

A flashing yellow light bar would indicate that the controller pairs at least, which it does not for me.

I tried multiple things from the internet (launching troubleshooter, updating dongle driver, forcing a driver uninstall) but nothing works.

**Comment by RaideX101** [comment]
I finally fixed my issue. 

What I ended up doing is uninstalling every single Bluetooth including the dongle and also the 'hidden devices' that aren't normally visible in the device manager. 

After that I restarted and was finally able to remove the controller under HID Devices -> HID Bluetooth Device.

Restarted again and was able to re-pair my controller.
