### ISSUE TITLE
"Could not connect to ViGEmBus"

### ISSUE THREAD

**Issue by vico93** [Ryochan7/DS4Windows#859]
Hi!

After using my three dualshock 4 (via bluetooth 4.0) with DS4W yesterday without problems, today after booting my system i tried to open DS4W and now it not only always open the driver install window but it also have an entry on the log saying: "Could not connect to ViGEmBus. Please check the status of the System device in Device Manager and if Visual C++ 2017 Redistributable is installed.", and i any connection cant be made.

I tried to search for any devices named "vigem" on device manager but cant find anything. Plus i dont think any Windows update was installed from yesterday to now.

I'm using Windows 10 1903 x64

**Comment by mika-n** [comment]
Vigem driver is "Virtual gamepad driver" in DeviceManager.
![DS4Win_ViGemDriverDevManager](https://user-images.githubusercontent.com/35538525/67163549-0d39e080-f379-11e9-9a52-3a9fceb6f0f2.png)

Try installing everything related to ViGem driver and download the latest version of Vigem and re-install it (ViGEmBus_Setup_1.16.115.exe):
https://github.com/ViGEm/ViGEmBus/releases

**Comment by vico93** [comment]
Uninstalling and installing the latest version worked for me. Thanks!
