### ISSUE TITLE
>=1.6.3 crashes out

### ISSUE THREAD

**Issue by tomose** [Ryochan7/DS4Windows#860]
Similar to https://github.com/Ryochan7/DS4Windows/issues/543 as far as errors in event viewer go.

Except WMI is functional on my system and connects fine. WMI Version 17763.1 reported.

Any ideas what else could be causing the instant crashes on load?

Windows 10 LTSC x64

**Comment by mika-n** [comment]
Try to disable automatic update checker option in DS4Windows config file and download the latest version manually.
- Navigate to "%APPDATA%\DS4Windows" folder and modify Profiles.xml file. Set CheckWhen xml option to value 0.
 - Download the latest release from https://github.com/Ryochan7/DS4Windows/releases

- Try launching DS4Windows.exe using "Run as administrator" option while you don't have any gamepad controllers connected.

**Comment by Ryochan7** [comment]
Not sure what could be causing the problem. If the app will allow it, maybe I should just attempt to add some try block again to catch the error. No support for suspend and resume functionality would be possible though. With the previous issue, it ended up being a system configuration problem though.

Even the old Jays2Kings releases relied on WMI although it was for driver detection and not for detecting power management events.

**Comment by Ryochan7** [comment]
This type of issue should finally be addressed in the code. Less aggressive exception handling is done than what was done with the Jays2Kings build.
