### ISSUE TITLE
1.7.18 gui problems

### ISSUE THREAD

**Issue by Hardcor3UK** [Ryochan7/DS4Windows#861]
Just updated to 1.7.18 and i have some UI problems.

When the DS4Windows window is open it has no title bar or controls (min, max, close).

![image](https://user-images.githubusercontent.com/11295972/67192038-b2d96800-f3ea-11e9-8e37-8c9c638d8e98.png)

When i start it minimised to tray i have a blank white box on the top left of my screen (the size of the main DS4Windows form).

![image](https://user-images.githubusercontent.com/11295972/67192059-c1278400-f3ea-11e9-872c-883b251c07ac.png)

As far as i can tell functionality all works fine, just UI problems.

**Comment by Turtvaiz** [comment]
I have the exact same problem on Windows 10 18362.418 after using the updater.

**Comment by Hardcor3UK** [comment]
I have just manually re-extracted the update files into my DS4Windows folder and overwrote all the files, works fine now.

Seems to be some sort of problem caused by the updater i guess.

**Comment by Turtvaiz** [comment]
Deleting the program's files and reinstalling from the Github release did not work for me, though.

**Comment by Ryusennin** [comment]
Same issues in Win7.

The app window is blank when started minimized (the GUI reappears if clicking Open in the systray icon). And the window title bar is out of screen.

**Comment by Hardcor3UK** [comment]
After making a change on my "auto profile" settings, i seem to be getting this again.

**Comment by mika-n** [comment]
yes, there is a bug in "Start minimized" option. At this point untick this option. The side effect is that you will see the DS4Win main window when the app is started and you have to press "Minimize" window button to hide the app to tool tray when you don't want to tweak settings of DS4Win.

**Comment by Hardcor3UK** [comment]
Yes can confirm, just came back to post that, disabling & enabling that is the cause. Very strange that when i changed my auto profiles this option somehow got changed also.

**Comment by danielshv** [comment]
![Sin título](https://user-images.githubusercontent.com/56830652/67207047-08544b80-f3d0-11e9-8b89-54e14c135c66.png)


How do I make this section give me the check and not the cross?

**Comment by Hardcor3UK** [comment]
"Hide DS4 Controller" option

**Comment by mika-n** [comment]
> How do I make this section give me the check and not the cross?

The "X" icon is just an indication if the exclusive access has succeeded because often people don't look at Logs tab page (there is a warning message if DS4Win failed to acquire an exclusive access to the physical controller). The GUI in the screenshot is not a place where you check/uncheck that option. The exclusive access is determined by "Hide DS4 Controller" option in general "Settings" of DS4Win app and it is the same option for all profiles (ie. not a profile specific).
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

**Comment by JokeDeity** [comment]
Same here, updated and the GUI is broken now.

**Comment by Drynwynn** [comment]
Just adding another user confirmation that deselecting 'start minimized' and restarting ds4windows solved this issue for me.

**Comment by Hardcor3UK** [comment]
temp fix is already posted, untick **start minimized**

**Comment by Blackbird88** [comment]
Why was this even changed? It always worked fine for me.

**Comment by danielshv** [comment]
> > How do I make this section give me the check and not the cross?
> 
> The "X" icon is just an indication if the exclusive access has succeeded because often people don't look at Logs tab page (there is a warning message if DS4Win failed to acquire an exclusive access to the physical controller). The GUI in the screenshot is not a place where you check/uncheck that option. The exclusive access is determined by "Hide DS4 Controller" option in general "Settings" of DS4Win app and it is the same option for all profiles (ie. not a profile specific).
> https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

![Sin título](https://user-images.githubusercontent.com/56830652/67252745-8ac12780-f431-11e9-8384-7df27b7c94b4.png)


I already solved it thanks for your comment I was very helpful. it turns out he had the suppression mode on nvidia activated.

**Comment by Tenshigami** [comment]
I not only had to turn off "Start Minimized" but also had to turn off "Run at Startup" for this gui issue to go away. Not ideal but I'll make do for now.

**Comment by nandocova** [comment]
Also experiencing this issue. Both "start minimized" and "run at startup" had to be turned off for the window to be displayed correctly.

**Comment by Ryochan7** [comment]
I am trying those option and it is working fine for me so far. I did not test those options in combination with Run At Startup though. I will give it a try now and see if the window renders wrong for me.

The reason for the change was that Minimize to Taskbar was not working at startup if Start Minimize was used. The window would still minimize to the system tray.

**Comment by Ryochan7** [comment]
Tried both Run at Startup modes and the minimize options worked fine. However, I just disabled Start Minimize and now I am experiencing the blank window problem on my end. I will look into it.

**Comment by Ryochan7** [comment]
The window is clickthough too. Interesting.

**Comment by Ryochan7** [comment]
The issue would cause problems with any option that has DS4Windows start minimized. That includes Start Minimized as well as the two Run At Startup modes. The problem would not appear if the Minimize To Taskbar option is enabled at the time. I got a fix working in all those situations and hopefully this will be the last time this type of problem will happen. If nothing else, this tweak makes the code simpler.

**Comment by Ryochan7** [comment]
Version 1.7.19 should fix this problem.

https://github.com/Ryochan7/DS4Windows/releases/download/v1.7.19/DS4Windows_1.7.19_x64.zip

**Comment by Ryusennin** [comment]
Looks good so far at startup on Win7, will shake it up later this afternoon.

**Comment by Hardcor3UK** [comment]
Works fine here, even on windows startup.
