### ISSUE TITLE
Updater not working as of 1.7.17

### ISSUE THREAD

**Issue by transam617** [Ryochan7/DS4Windows#862]
Since release of 1.7.17, I have had an issue where the updater prompt to install a new version, results in it downloading a 0K archive and obviously not updating.

I can download the new material from various sources, but I wonder if ublock origin or windows is blocking the contents of the download.

Feel free to have me test this as I haven't found another person with quite this issue.

**Comment by mika-n** [comment]
Try updating the latest version of DS4Windows and ViGem driver manually:
https://github.com/Ryochan7/DS4Windows/releases
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#link-list

There has been some random weird problems in update logic. The latest version of DS4Windows has some tweaks relating the auto updater and ViGem driver installation. Sometimes it has been a permission issue or some firewall/virusscanner blocking network downloads from DS4Windows app (or DS4Updater.exe app).

**Comment by Ryochan7** [comment]
I have tested updating from version 1.7.17 and version 1.7.18 to 1.7.19 and both updates worked fine for me. It has been a while since I looked at the updater source code. I cannot remember if there are any checks for a failed download or if an error message appears upon failing.

**Comment by mika-n** [comment]
There has been so many random problems (permission issues? blocking virus scanners? etc) with updater that I would not mind to change this logic as "notify only about new version and WhatsNew and instruct people to navigate to Releases page to download the new package" type of logic.  This would make the update logic from the app side a lot simpler and less complex.
