### ISSUE TITLE
[Feature Request] Add the ability to bind multiple wheel axis on gyro

### ISSUE THREAD

**Issue by greggameplayer** [Ryochan7/DS4Windows#863]
It would be cool to add the ability to bind multiple wheel axis on gyro since when we use touchpad as a mouse, controls on gyro isn't accurate enough for motion controls in emulators for example

**Comment by mika-n** [comment]
I have to admit I didn't quite understand what you meant.

**Comment by greggameplayer** [comment]
@mika-n i ask  it's possible to implement the ability to bind multiple wheel axis on our ds4 sixaxis gyro since wheel axis isn't just like a button (pressed or not pressed) there are values in between which means that for example in dolphin ( wii emulator ) it detect the movement smoothly not just forward/backward/left/right but also all the positions in between of these

**Comment by greggameplayer** [comment]
@mika-n it would be just like a mouse but it's useful in case you already use your mouse for the touchpad for example

**Comment by Ryochan7** [comment]
The wording is a bit confusing but I think I get what you mean. Analog axis controls can already be bound to the gyro in a few ways. There are the standard Tilt Controls, 360 Steering Wheel mode, Mouse Joystick mode, and the UDP Server.

The main limitation with almost all the modes is that you are still limited to the axes available on an Xbox 360 controller. You would most likely just be making some form of duplicate mapping. Although, the 360 Steering Wheel mode gives options to map the gyro to arbitrary axes besides what is available on an Xbox 360 controller if you are using the vJoy driver. The UDP server option is the most open but it requires an application to directly support that protocol. It is mainly used with Cemu.

**Comment by greggameplayer** [comment]
@Ryochan7 Can you just explain how to use mouse joystick mode ? since i haven't understand how to correctly setup it to make it detected by dolphin
