### ISSUE TITLE
Latency spikes with bluetooth

### ISSUE THREAD

**Issue by cooler166** [Ryochan7/DS4Windows#865]
Whenever I try using DS4Windows over bluetooth, there would be latency spikes in the 80 range all the time. This is a DS4Window only problem because when I use the controller regularly without DS4Windows open, the latency is just fine. I also have the Poll rate set to max.

**Comment by SkyEmie** [comment]
Hi,
I also have this at random times : 

![Screenshot_3](https://user-images.githubusercontent.com/29162548/67399562-b87eab80-f5ac-11e9-8a6b-64d93ad8bf21.png)

This appears with the default configuration (pool rate at 4ms) or with mine (pool rate at 8ms). Am I the only one? It's problematic when the controller doesn't respond for about ten seconds in the middle of the game. And if he can't reconnect, he turns off, it's a little bit problematic :/

**Comment by mika-n** [comment]
These BT lag issues are nasty. No clear reason why it works in some PCs but not in others. Please see the following wiki doc page for couple of potential reasons.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#gamepad-connection-over-bluetooth-bt

Try running the controller in exclusive mode to make sure that no other apps are using the controller and causing confusion.
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

Does the controller work while using USB connection? If USB causes random disconnects also then it is more likely a gamepad issue.
