### ISSUE TITLE
Ongoing "minimize" issue

### ISSUE THREAD

**Issue by aburke20** [Ryochan7/DS4Windows#872]
So, for the longest of time I've had the annoying issue where despite everything working just fine when I boot up (i.e. the program runs at startup, and minimizes, AND hides itself in that small taskbar box) whenever I double click on the icon from within the install folder OR the taskbar box, the program then never "minimizes" properly (as in: doesn't show the window being open on the desktop, but is still prominently showing as a big icon on the taskbar itself).

I was able to ignore this as I never really summoned the window, and the program ran just fine hidden the way it was.

Well, since the last one or two updates the program now still launches on boot, but doesn't minimize to the small box, and so will always be in the above-mentioned "stuck on taskbar if opened" mode.

Hope that makes sense.

Any ideas ? This is the only program that does this; no clue why.

**Comment by Ryusennin** [comment]
In the Settings tab, maybe you checked the option "Minimize to Taskbar"?

**Comment by aburke20** [comment]
> 
> 
> In the Settings tab, maybe you checked the option "Minimize to Taskbar"?

-_-

Jesus; Yep, that did the trick.

I just never thought it could be any of the options I hadn't touched or changed in years. Plus, like I said, until a few days ago it worked just fine ... so long as I didn't "fiddle" with it.

Thanks man !
