### ISSUE TITLE
Profiles Maxzone dont save

### ISSUE THREAD

**Issue by incneet** [Ryochan7/DS4Windows#873]
https://youtu.be/I6RcId21BUk

**Comment by Ryochan7** [comment]
Confirmed that this only affects the LS Maxzone setting. All other maxzone settings save fine. The hook for ValueChanged was likely missed while switching to the tabbed interface. Visual Studio removed the old event hooks for many controls so they had to be restored manually.

**Comment by Ryochan7** [comment]
Saving of that actually worked but loading the setting was failing. LS Anti-Deadzone was hooked to the wrong event so that setting would edit the LS Maxzone instead. I have a couple of tests I want to do before packing a new release.
