### ISSUE TITLE
When i restart pc exclusively mode working but after a while its not working again

### ISSUE THREAD

**Issue by egz12** [Ryochan7/DS4Windows#877]
Hi,

A week ago i thought my pc is broken. When i playing fifa (with ds4v2+bt and only im playing) it was like instant freezing for a second and it was happening more then very once.  I formatted my pc (full patched last build of windows 10), tried 2 different bt adapter, did everything but always it was happening on fifa. Then i plugged out both bt adapters and start to using with cable and i found the actual problem. I'm not using with bt anymore and using with cable but when i open pc or after restart its connecting with exclusive mode but after a while when i want to play its never opening in exclv mode. Is there any solution about this? Cause i tired to restart my pc again and again.

PS: I gave the first details about blueooth cause a feedback maybe its can be ds4windows problem.

Thanks.

**Comment by mika-n** [comment]
Probably some app hijacks a connection to the physical gamepad, so exclusive mode doesn't work after that (DS4Windows must be the first app to use the gamepad). Alternative solution is to use HidGuardian device driver.

https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues
https://github.com/Ryochan7/DS4Windows/wiki/DS4Windows-and-HIDGuardian-Install-and-Setup-Guide#hidguardian-test-installer
https://github.com/Ryochan7/DS4Windows/issues/608
