### ISSUE TITLE
Need permission to distribute this software as a Chocolatey Package

### ISSUE THREAD

**Issue by jtcmedia** [Ryochan7/DS4Windows#88]
I am a package maintainer for chocolatey.org. Chocolatey is an 'apt-get' or package manager for windows. I would like to distribute your zip as a package. Since there is no license associated with this software, I need your permission to do so. Alternatively, I can create a package which links to the zip that you release here on GitHub. It's up to you.  Jason

**Comment by Ryochan7** [comment]
I had previously used Chocolatey but I did not install it on my most recent Windows installation. If you would like to maintain a Chocolatey package for DS4Windows then that is fine.

**Comment by jtcmedia** [comment]
Chocolatey package is here: https://chocolatey.org/packages/ds4windows Thanks!
