### ISSUE TITLE
Execute program on connection/disconnection

### ISSUE THREAD

**Issue by vrokolos** [Ryochan7/DS4Windows#885]
I see that there's a command to be run on profile start. I want to change to 4k res and back when turning gamepad on and off

**Comment by mika-n** [comment]
This is not directly available as an event handler, but maybe you can work out a semi-working solution by using auto-profile rules or cmdline options to start and stop DS4Win app.

If you are interested to use 4k reso only with certain apps then link a profile to an appilcation and use that profile to run a process.
https://github.com/Ryochan7/DS4Windows/wiki/Profile-selection-using-auto-profile-rules

Or if you stop/start the whole app by using cmdline tool then you can do what ever you want before and after DS4Win app.
https://github.com/Ryochan7/DS4Windows/wiki/Command-line-options

**Comment by Ryochan7** [comment]
That is really the main feature that interested me in tracking InputMapper 1.7 development progress. With IM 1.7, app detection can be done and commands can be assigned to exposed events. Commands will be executed when IM detects a new application; focus gained and focus lost events are available per application association. Switching profiles is one of the types of commands that can be assigned.
