### ISSUE TITLE
Emulate Xbox One Controller Drivers instead of Xbox 360 Drivers?

### ISSUE THREAD

**Issue by rechiiram-ily** [Ryochan7/DS4Windows#886]
I'm having issues with utilizing X360 drivers on Windows 7, plus could affect by using a PS4 controller and an XB1 controller (as I use XB1 drivers), it could cause a crash on the 360 drivers if I plug in the XB1 controller. So if you can make DS4Windows utilize the Windows 7/8 Xbox One controller drivers, that would be fantastic, as the Xbox 360 drivers can cause issues to play split-screen games with a PS4 controller and an XB1 controller, because of course, driver crashes.

**Comment by Ryochan7** [comment]
ViGEm does provide support for emulating an Xbox One controller but I had found no use for using that functionality as of yet. It shouldn't be hard to add a different output target to DS4Windows to allow Xbox One controller emulation.

**Comment by rechiiram-ily** [comment]
If you can do it, please do! It'd be great for a PS4 controller and a XB1 controller at once in a PC (for IRL friends or brother matches) by utilizing the Xbox One drivers as a way to not have crashes with the X360 drivers! :)

**Comment by Ryusennin** [comment]
I have both X360 and XOne drivers installed on Win7 (from Microsoft site) and I used to have an XOne controller for a short time, borrowed from a friend. My OS never crashed when connecting it while DS4W was active.

**Comment by rechiiram-ily** [comment]
> I have both X360 and XOne drivers installed on Win7 (from Microsoft site) and I used to have an XOne controller for a short time, borrowed from a friend. My OS never crashed when connecting it while DS4W was active. Though I can't remember if DS4W had already switched from SCP to ViGEm.

To be fair, the X360 drivers would be on the background till I connect the XB1 controller... And there was no mention of an OS crash. The only crash that happened IIRC was an assertion error.

**Comment by Ryochan7** [comment]
This will be next on the docket. I already had some code to better unify virtual device creation from recent experiments. That should be an easier problem to solve than some other related problems.

**Comment by Ryochan7** [comment]
Maybe this will be a never mind. Got the output device plugin and unplug routines unified only to find out the ViGEm.NET library that DS4Windows uses does not support creating an Xbox One controller.

**Comment by Ryochan7** [comment]
Unfortunately it is not doable now. Although ViGEmBus has experimental support for emulating an Xbox One controller, that functionality is not exposed in the latest version of the .NET library that DS4Windows uses; it is not doable using the C library either. Going to close this issue for now.
