### ISSUE TITLE
Latency w/Skyrim Menus - Left Stick

### ISSUE THREAD

**Issue by Heartbreaker714** [Ryochan7/DS4Windows#888]
When playing Skyrim and I open the menue, it can take up to 30 secs for my controller to allow me to select menu options (Mapp, magic, intems, etc). 
When i use v 1.4 of DS4Windows, it seems to work fine.

**Comment by mika-n** [comment]
Is this "left stick lag" a problem only in Skyrim? Does the stick response OK in other apps?
Maybe this is a deadzone issue and the game is just confused if a DS4Win profile doesn't have deadzone (zero LS deadzone value)?

See "Deadzone" explanation in Settings documentation page:
https://github.com/Ryochan7/DS4Windows/wiki/Settings

**Comment by Ryochan7** [comment]
Haven't launched Skyrim in a long time; my favorite Elder Scrolls game is Oblivion so that gets tested more often. I would assume that it should work fine but you never know with Bethesda games.

Based on a previous issue, you might want to try disabling Trackball support (under Touchpad) in the profile you are using. It is a default option so it is very likely enabled. There is at least one confirmed report of someone having lag problems in DS4Windows when the option is enabled. I have not been able to look into it but I assume that it is probably due to some NullReferenceException constantly being thrown in the background on that person's install. Trackball mode works perfectly fine for me in all my profiles.

**Comment by Heartbreaker714** [comment]
Sorry i wanted to try the things out before answering. I I corrected the deadzone and the anti-dead zone according to the settings in the link provided by mika-a (thank you, btw). Also, trackball was never enabled.
That said, the controller does respond better, however, the latency is still there. It's almost like if I select something on the menu too fast, it locks up/doesn't respond for about 3-5 secs. This despite repeatedly trying to select an option. Eventually it works but still...

**Comment by mika-n** [comment]
Are there any "lag" warning messages in Logs tabpage of DS4Windows?
Do you have the same issue both in USB and BT connectivity? 
Have you tried to use a new default profile just to make sure that there are no weird things in the existing custom profile?

**Comment by Heartbreaker714** [comment]
Ok so I checked and trackball support has always been disabled. Also have tried playing with multiple profiles and still. 
Not sure if Lag is the right way to describe it. It's just when I open a menu, it's completely unresponsive to the left controller stick for X amount of time (generally about 5-10 secs). Then it responses. This happens when I open the magic/maps/inventory windows, or the main on for selecting quests, save/load games, mod configs, etc.
Again using the version 1.4 works fine so I've been using that while playing... Any idea what the difference could be??

**Comment by Heartbreaker714** [comment]
> Are there any "lag" warning messages in Logs tabpage of DS4Windows?
> Do you have the same issue both in USB and BT connectivity?
> Have you tried to use a new default profile just to make sure that there are no weird things in the existing custom profile?

I use the USB actually. And havent seen any errors listed in the log...
NOTE: One thing I noticed, and not sure if this makes a difference, but when I open the map, the cursor is constantly drifting left.

**Comment by mika-n** [comment]
Drifting is usually a sign on undefined deadzone or too small deadzone (compared to how the stick physically behaves in hardware level). Or if you dont use "Hide DS4 Controller" (=exclusive mode) or HidGuardian tool to hide the physical controller (ie. game sees input from a virtual controller created by DS4Windows and from the physical original controller).
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

**Comment by Darthagnon** [comment]
I've got my left stick drifting left in AC Origins - It used to work fine, then I installed HID Guardian, then I uninstalled HID Guardian. Is there any solution?

**Comment by mika-n** [comment]
Check the following post. Steam client may hijack a controller and unintentionally re-map keys. Try to disable gamepad controller settings in Steam settings.
https://github.com/Ryochan7/DS4Windows/issues/874#issuecomment-560170723
