### ISSUE TITLE
Please support the Nacon Revol Pro v.3

### ISSUE THREAD

**Issue by Manuel70** [Ryochan7/DS4Windows#890]
I've tried to modify the knownDevices in DS4Devices class but without results

**Comment by Ryochan7** [comment]
Since it looks like adding support involves more than just adding the info to the array, support would be up to you. I don't have access to that hardware so you will have to figure it out and send a pull request.

**Comment by mika-n** [comment]
Try to run the DeviceDetect debug version to generate a more detailed log file.

https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

**Comment by Manuel70** [comment]
Sorry for the delay, i was out of home and with no controller.
PID is 0x0D13
To ver. 1.7.22 is sufficient to add 
new VidPidInfo(NACON_VID, 0x0D13, "Nacon Revol Pro v.3")
Works !
I got a warning "failed to read serial#" but the dummy  MAC addres generation succeded.

**Comment by mika-n** [comment]
Created a change request with Nacon Revolution v3 support. 

The new "dummy MAC address generation" logic was created especially for these non-standard DS4 gamepads to workaround few problems caused by a zero MAC address.

Did you run the DeviceDetect debug version? Were there any other warning or error messages than a warning about missing MAC address of the gamepad?

**Comment by Manuel70** [comment]
Yes i ran the DeviceDetect debug version.
Running the modified program i got only a warning "failed to read serial#" and no errors.
I debugged the code and the "dummy MAC address generation" logic worked correctly.
Thank you very much !

**Comment by Manuel70** [comment]
A little notice:
The DeviceDetect debug version returns 2 log rows for my device, the first one is the main entry for the controller then there is a HID-compliant vendor-defined one log entry. 
I'm Italian: all the description are translated into Italian language.
(now i don't have the device with me so i don't remember the exact translation)
in DS4Devices.cs i've noticed a
for (int i = 0; i < devCount; i++)
if (hDevice.Description == "HID-compliant vendor-defined device")
    continue; // ignore the Nacon Revolution Pro programming interface
i debugged this code and noticed that devCount is always 1 (the main entry)
so even if the description does not match the "HID-compliant vendor-defined device" is not parsed (as expected)

**Comment by mika-n** [comment]
This code may be some left over to ignore certain problematic HID handles, BUT nowadays DS4Windows uses only HID devices with usage=0x05 flag so all those non-gamepad device handles are ignored if the usage flag is not value of "5". What is the usage flag value in the "Hid-compliant vendor defined" HID entry in your scenario? If it is something else than 0x05 then all is OK.

**Comment by Manuel70** [comment]
I thank you and confirm.
Gamepad has usage flag = 5
the "Hid-compliant vendor defined" device has Usage flag value = 0x40

**Comment by Ryochan7** [comment]
Info has been included
