### ISSUE TITLE
Analog Sticks are glitchy

### ISSUE THREAD

**Issue by pull3rb0y** [Ryochan7/DS4Windows#891]
i tested it on two different dualshock 4 v2 controllers... same result..

both sticks are glitching and wobbling even when i dont touch the controller..... it worked two days ago though....

![image](https://user-images.githubusercontent.com/17047687/68894430-97caf100-0727-11ea-8879-3b79e7340afd.png)

**Comment by mika-n** [comment]
Try to set a deadzone to ls and rs axies. Usually it is needed because sticks are not completely stable in hardware level and it may get worse over time when springs wear out and dust gets in.

**Comment by Ryochan7** [comment]
Nothing changed with input report reading with the recent release. There is a slight chance for jitter on the low end depending on the stick at the time. You usually need some small amount of dead zone set for the sticks to compensate for the sticks not going back to absolute center. Also, setting an anti-deadzone for the stiks while using no deadzone is generally a good idea.

**Comment by pull3rb0y** [comment]
The "anti-deadzone" was the problem. whatever why it was set to 0.25 on both sticks... changing back to 0 fixed it for me!

Thank ya all!
