### ISSUE TITLE
Profile for normal DS4 Input?

### ISSUE THREAD

**Issue by CDAdkins** [Ryochan7/DS4Windows#892]
I can't seem to find a way to set up a profile that just uses normal DS4 input. Red Dead 2 on PC has native DS4 support so I'd like to use it. However I also use DS4Windows to navigate through my OS. Is there any way to have DS4Windows running while using native DS4 input?

**Comment by mika-n** [comment]
"Use DInput Only" option sets a profile in a state where the original DS4 gamepad is used directly without any virtual re-mapped gamepad rules.
https://github.com/Ryochan7/DS4Windows/wiki/Settings#use-dinput-only

Or you could use "one click" desktop shortcut to run a command line to stop/start DS4Windows on the fly.
https://github.com/Ryochan7/DS4Windows/wiki/Command-line-options

Or you could try to setup an auto-profile rule list to disable and select a specific profile automatically based on currently running foreground application.
https://github.com/Ryochan7/DS4Windows/wiki/Profile-selection-using-auto-profile-rules

**Comment by CDAdkins** [comment]
Ah I missed that option. It's too bad dinput mode doesn't work wireless. Thank you so much for your help!
