### ISSUE TITLE
Feature request: Option to tie auto-profile switching just to whether the process is running or not

### ISSUE THREAD

**Issue by cascardian** [Ryochan7/DS4Windows#898]
Right now, auto-profiles activate based on the whether a process is in the foreground or not. To make certain configurations easier, I suggest adding the above as another option to auto-profiles (not just replacing foreground activation, of course; it can be useful). A simple use case: Start an emulator with a specific profile and revert to the default upon closure of it, but maintain the profile while the process is running, regardless of what other program is in the foreground. This is useful for people who play with background input enabled and wish to easily minimise profile switching.

This can also be achieved by setting up empty profiles for other programs while still having the emulator open (explorer, browser, video player, office program, task manager, debugger etc.). It can be a bit tiresome to set all this up. On Windows 10, just bringing up the start menu counts as a new active foreground window, for which a separate empty profile has to be created.

Thank you for keeping this wonderful program alive.

**Comment by mika-n** [comment]
You could define "do not change a profile" rule by using a wildchar search key. For example if the process name is "^c:" then it would match to all processes beginning with C: path reference. If you set this kind of a rule with "(none)" profile selections then DS4Windows won't revert back to default profile when "unknown" process is in foreground (ie. it leaves the existing profile as an active profile). This way you don't have to list each and every process in auto-rule list.

If you set this "match all - don't change a profile" rule as the last rule in auto-profile list and more specific rules (fex emulator process rule) before this "match all" rule then you can control process specific rules for those apps where you need a certain profile.

https://github.com/Ryochan7/DS4Windows/wiki/Profile-selection-using-auto-profile-rules#setting-do-not-change-profile-rule

There is only one minor issue. You cannot change the order of rules in auto-profile GUI. If you create new rules in correct order then that's fine but if you need to change the order afterwards then you have to edit auto-profile.xml configuration file in Notepad and set the order of rules there.

Anyway. The auto-profile logic uses "the first matching rule sets the profile" priority.

Another way to do something like this is a command line interface of DS4Windows. You could have a BAT/CMD script to launch the emulator app and this script would load a specific profile just before the script launches the emulator app.
https://github.com/Ryochan7/DS4Windows/wiki/Command-line-options

**Comment by cascardian** [comment]
Thank you. I did not realise that the path-matching logic would be this powerful. That makes setting up indeed significantly easier, which satisfies my initial motivation for creating this issue. However, if you would still like to keep this issue open for its own merits, feel free to do so.

Perhaps what you wrote here could also be adapted to the wiki page on auto-profiles. It does not, e.g., make it entirely clear that no specific process needs to be named for the path-matching to work. An additional example like you mentioned would probably help users, as well as a mention of the ordering priority of the matching logic.

**Comment by mika-n** [comment]
Done. Updated the wiki doc page to make it more clear that order of rules may be important and how it is possible to set "catch all" rule.
https://github.com/Ryochan7/DS4Windows/wiki/Profile-selection-using-auto-profile-rules

I think that "checking all running processes" change won't make it into DS4Windows anytime soon. It would create an additional burden if DS4Windows would constantly iterate through ALL running processes (ie. not just the process of an active foreground window) to check the status. Or DS4Windows should somehow acquire a handle of launched process and then doing a background thread with WaitForMultipleObject to wait for completion of a thread handle. Sounds like something which might slightly affect the overall performance.

**Comment by mika-n** [comment]
The current version of DS4Windows app "revert back to default profile" option in AutoProfile screen and capability to move up/down autoprofile rules in the rule list.
