### ISSUE TITLE
When connecting via bluetooth controller shows as Input

### ISSUE THREAD

**Issue by richmond94** [Ryochan7/DS4Windows#899]
Every time I try to connect my controller with Bluetooth it comes up with input and does not connect. Controller works via usb, any help would be appreciated!

**Comment by mika-n** [comment]
Download the DS4Windows_DeviceDetectDebug.zip file and run the debug version to generate more detailed log messages (Logs tab page in DS4Windows app). 
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

**Comment by Ryochan7** [comment]
Is the BT controller detected by Windows at all?

**Comment by richmond94** [comment]
Managed to fix it! Turns out it was just a hardware issue, disconnecting my pc from mains sorted it
