### ISSUE TITLE
[Feature] Assign Mouse X to Gyro Tilt X

### ISSUE THREAD

**Issue by Kaltern** [Ryochan7/DS4Windows#90]
I notice that the mouse movement is only linked to lateral movements of the X gyro axis.  I would like to be able to reassign this to the X Gyro Tilt axis instead, as in certain games (Elite Dangerous!), it would be advantageous to use as a headlook option - right now it's possible, but very unwieldy to have to 'point' the controller in the direction you want to look - tilting would be far more natural.

**Comment by Ryochan7** [comment]
This feature is now available in version 1.4.85. Even though Steam offers the option for the Steam Controller and DS4, I had never seen a good use case for using Roll instead of Yaw for controlling Mouse X. I didn't see a need to implement that feature beforehand.
