### ISSUE TITLE
Heavy Rain PC Sixaxis movement

### ISSUE THREAD

**Issue by IceLancerSR** [Ryochan7/DS4Windows#902]
Hey there i just attempted to play me some Heavy Rain and i got stuck at beginning where u need to brush ur teeth by moving gamepad left/right. But its not registered by the game. Neither wired nor wireless

Game only registers V1 dualshock , so i turned that on. Tested gyro and sixaxis both works fine.

Am i missing something?
Win10x64
V2 dualshock

P.S i didt test xbox, game has dualshock icons if dualshock v1 is used, so why not..

P.P.S
Tested xbox360.. it didnt ask for movement but required to move Right stick left right instead. So ..

![saxis](https://user-images.githubusercontent.com/4452102/69502485-1ede4d00-0f10-11ea-8bae-016e838937fb.png)

**Comment by IceLancerSR** [comment]
OK problem solved.
Turned off ds4windows. 
Connected gamepad to usb and ran it with windows drivers. Everything works. Including Sixaxis

**Comment by Ryochan7** [comment]
ViGEmBus does not support emulating the DS4 gyro so that is not possible in DS4Windows. You have to use the controller without DS4Windows as you have seen. That game can put the DS4 in PS4 mode so the gyro data is accessible from a real DS4 in game.
