### ISSUE TITLE
Want to use my DS4 on PS4 now, but I cant.

### ISSUE THREAD

**Issue by beanbot25** [Ryochan7/DS4Windows#903]
I tried to remove it from bluetooth and reseting it with the back button but nothing works. Is there some way I can have the controller forget my computer all together.

**Comment by Ryochan7** [comment]
You have to manually remove the BT controller device from within Windows. Even after disconnecting the DS4 from BT, Windows will still list the paired controller but it will not be flagged as present. After that, there should be no problem syncing the controller to a PS4 or another PC with the PS+Share combo.

**Comment by second2050** [comment]
> I tried to remove it from bluetooth and reseting it with the back button but nothing works. Is there some way I can have the controller forget my computer all together.

connect your ds4 via usb to your ps4 it should pair with your ps4 this way

**Comment by 123console31** [comment]
> You have to manually remove the BT controller device from within Windows. Even after disconnecting the DS4 from BT, Windows will still list the paired controller but it will not be flagged as present. After that, there should be no problem syncing the controller to a PS4 or another PC with the PS+Share combo.

How? ı cant startb my ps4 system about a 3 weeks now ı cant figure out how to resolve this problem

**Comment by 123console31** [comment]
> > You have to manually remove the BT controller device from within Windows. Even after disconnecting the DS4 from BT, Windows will still list the paired controller but it will not be flagged as present. After that, there should be no problem syncing the controller to a PS4 or another PC with the PS+Share combo.
> 
> How? ı cant startb my ps4 system about a 3 weeks now ı cant figure out how to resolve this problem

I did it somehow

**Comment by Ryochan7** [comment]
Sony broke ViGEmBus compatibility with PS Remote Play a while ago. There is no way to have an emulated DS4 controller created with ViGEmBus be usable in Remote Play; I believe reWASD fixed a similar issue with their driver a while ago. Maybe HidHide device hiding was disabled so the PS Remote Play app was reading the physical DS4 after all?

If nothing else, just use the real DS4 controller handle and do not worry about any type of remapping.

**Comment by Masamune3210** [comment]
I didn't think this issue was talking about RP, it sounded to me as if they couldn't figure out how to pair their controller to the console, unless I missed something?
