### ISSUE TITLE
[Notice] Please download latest version of DS4Updater.exe to update to DS4Windows 2.0.0

### ISSUE THREAD

**Issue by Ryochan7** [Ryochan7/DS4Windows#904]
Due to an error in the update checker routine introduced in version 1.7.21, DS4Windows cannot automatically update to version 1.7.23. In order to update DS4Windows to version 1.7.23, you will have to manually run the DS4Updater.exe executable from Windows Explorer. The update check error has been fixed in DS4Windows version 1.7.23 so hopefully this type of problem will not happen again.

### Update (2019/12/26)

Since a higher priority issue has come about, this issue has been unpinned; I will wait to close the issue. Anyone affected by this issue will encounter the new problem and have to resolve it to fix this initial problem. The short version of the solution is to download the latest DS4Updater.exe program and run it in your DS4Windows installation folder. That should be enough to update DS4Windows to version 2.0.0.

x64:
https://github.com/Ryochan7/DS4Updater/releases/download/v1.4.0/DS4Updater.exe

x86:
https://github.com/Ryochan7/DS4Updater/releases/download/v1.4.0/DS4Updater_x86.exe

**Comment by julianxhokaxhiu** [comment]
Thanks! Was going to report this, but I'm very happy you already found the issue and fixed it. Cheers!

**Comment by Plut0nio** [comment]
I figured this out myself when updating to 1.7.22. Good to see that it's fixed now. Thanks!

**Comment by Ryochan7** [comment]
Since a higher priority issue has come about, this issue has been unpinned; I will wait to close the issue. Anyone affected by this issue will encounter the new problem and have to resolve it to fix this initial problem. The short version of the solution is to download the latest DS4Updater.exe program and run it in your DS4Windows installation folder. That should be enough to update DS4Windows to version 2.0.0.

x64:
https://github.com/Ryochan7/DS4Updater/releases/download/v1.4.0/DS4Updater.exe

x86:
https://github.com/Ryochan7/DS4Updater/releases/download/v1.4.0/DS4Updater_x86.exe
