### ISSUE TITLE
Issue with current update.

### ISSUE THREAD

**Issue by frapeil** [Ryochan7/DS4Windows#906]
https://i.imgur.com/QYacxYv.png

As of now, games are currently picking up top emulated Xbox controller where there is alot of jitter an the joysticks, whereas the second controller is working fine.

**Comment by Ryochan7** [comment]
The second controller doesn't look fine. This looks like you removed the LS and RS dead zones in the profile but left the default anti-dead zones in place. That would be the reason the reading for the Xbox 360 controller sticks is much higher than the DS4 controller.
