### ISSUE TITLE
Problem with controller connected via Bluetooth

### ISSUE THREAD

**Issue by Herku77** [Ryochan7/DS4Windows#907]
I'm have tried using my ps4 controller via Bluetooth but it doesn't work .
It doesn't show up in overlap controllers ,but in log everything is done
-Starting
-Connetion to ViGEMBUS 1.16.112.0 estabilished
-Searching for controllers
-using Exclusive mode
-Found Controller :....
-Plugging in X360 Controller #1
-X360 Controller #1 connected
-Controller 1 is using profile "Default"

**Comment by mika-n** [comment]
Is it an official Sony DS4 gamepad? Does it work over USB in PC? What do you see in JOY.CPL ControlPanel applet when the gamepad is connected over BT? Do you see any gamepad activity in ControllerReadings tab page (while a profile is opened for editing)? Have you tried a new default profile in case you have something wrong in a profile settings?

If you cannot get it to work then download the debug version of DS4Windows and post the detailed logfile here (Logs tabpage content of DS4Windows app) for further analysing.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

**Comment by mika-n** [comment]
See and continue discussions in #910 thread because that thread lists a bit more details about similar case.
