### ISSUE TITLE
Knock-off sony controller won't show up.

### ISSUE THREAD

**Issue by subjob** [Ryochan7/DS4Windows#908]
i'm trying to use my non-sony dualshock 4 controller to play fifa but it just won't show up no matter what i do.

the log says (in debug mode): 
2019-11-28 18:06:15: DS4Windows version 1.7.23
2019-11-28 18:06:15: LinkedProfiles.xml can't be found.
2019-11-28 18:06:15: Starting...
2019-11-28 18:06:15: Connection to ViGEmBus 1.16.112.0 established
2019-11-28 18:06:15: Searching for controllers...
2019-11-28 18:06:15: Using Shared Mode
2019-11-28 18:06:15: DEBUG: EnumerateDS4. HID#1 Path=\\?\hid#vid_258a&pid_0001&mi_00#7&5910826&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd  Description=HID Keyboard Device  VID=0x0000  PID=0x0000  Usage=0x0  Version=0x0
2019-11-28 18:06:15: DEBUG: EnumerateDS4. HID#2 Path=\\?\hid#vid_7545&pid_1122#7&eaaf92c&1&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-kompatibel spelenhet  VID=0x7545  PID=0x1122  Usage=0x4  Version=0x100
2019-11-28 18:06:15: DEBUG: EnumerateDS4. HID#3 Path=\\?\hid#vid_046d&pid_c051#6&34d2e821&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-kompatibel mus  VID=0x0000  PID=0x0000  Usage=0x0  Version=0x0
2019-11-28 18:06:15: DEBUG: EnumerateDS4. HID#4 Path=\\?\hid#vid_258a&pid_0001&mi_01&col01#7&296845e8&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-kompatibel systemstyrenhet  VID=0x258A  PID=0x0001  Usage=0x80  Version=0x100
2019-11-28 18:06:15: DEBUG: EnumerateDS4. HID#5 Path=\\?\hid#vid_258a&pid_0001&mi_01&col02#7&296845e8&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-kompatibel konsumentkontrollenhet  VID=0x258A  PID=0x0001  Usage=0x1  Version=0x100
2019-11-28 18:06:15: DEBUG: EnumerateDS4. HID#6 Path=\\?\hid#vid_258a&pid_0001&mi_01&col03#7&296845e8&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-kompatibel leverant�rsdefinierad enhet  VID=0x258A  PID=0x0001  Usage=0x1  Version=0x100
2019-11-28 18:06:15: DEBUG: findControllers. Found 0 possible devices

is it just not added or am i doing something wrong? i'm using the latest windows update and i've installed all the drivers

**Comment by Ryochan7** [comment]
It looks like Windows does not see an HID gamepad. This looks like the closest thing but it is not exposed as a game controller.

```
2019-11-28 18:06:15: DEBUG: EnumerateDS4. HID#5 Path=\?\hid#vid_258a&pid_0001&mi_01&col02#7&296845e8&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030} Description=HID-kompatibel konsumentkontrollenhet VID=0x258A PID=0x0001 Usage=0x1 Version=0x100
```

Also, are you trying connect via USB or BT?

**Comment by subjob** [comment]
It's via usb, in device manager it says "HID-kompatibel spelenhet" which translates to "HID-compatible gamingunit"
i found this in the properties log
Device HID\VID_7545&PID_1122\7&eaaf92c&1&0000 was not migrated due to partial or ambiguous match.

Last Device Instance Id: USB\VID_046D&PID_C051\6&4cc88e&0&1
Class Guid: {745a17a0-74d3-11d0-b6fe-00a0c90f57da}
Location Path: 
Migration Rank: 0xF000FFFFFFFFF120
Present: false
Status: 0xC0000719

**Comment by Ryochan7** [comment]
Okay. It looks like the HID usage page is wrong. 0x04 usage page is supposedly reserved for Joystick devices but every DS4 compatible device discovered so far has had a usage page of 0x05 (Gamepad). A new debug build wii probably be needed with an additional usage page check to see if the device is compatible. Is the device at least seen as a generic DirectInput controller in Windows? Please check with html5gamepad or the Game Controller settings window in the Windows Control Panel.

@mika-n

**Comment by mika-n** [comment]
`HID#2 Path=\?\hid#vid_7545&pid_1122#7&eaaf92c&1&0000#{4d1e55b2-f16f-11cf-88cb-001111000030} Description=HID-kompatibel spelenhet VID=0x7545 PID=0x1122 Usage=0x4 Version=0x100`

Hmmm.... Usually xbox and ds4 gamepads have Usage=0x5 flag. I believe Usage flag 4 is "sports controller" identifier. Do you have a link to any online store for the gamepad? Is it really standard DS4 compatible gamepad or some special kind of gamepad/controller/joystick?

Does it work at all in Windows? 
Is it listed as xinput or dinput controller in games (or in Steam client)? 
What do you see in JOY.CPL ControlPanel applet (you can run that command to open the controlPanel applet)?

Anyway. I will create a small tweak into a debug version to allow user to override the usage flag checker value (ie. now it is always Usage=0x5 but I will add a custom optional debug option to make it possible to match with Usage=0x4 cases also).

**Comment by subjob** [comment]
@Ryochan7 yeah it shows up on https://html5gamepad.com/ so i guess it is. 

@mika-n 
i've tried to play fifa and the controller didn't seem to work at all.
In joy.cpl it says "PC Gamepad - OK"

https://www.teknikproffset.se/Hemelektronik/Spel/Sony-Playstation-4/Tillbehoer/Handkontroll-till-Playstation-4-Svart.htm this is the one i bought

**Comment by mika-n** [comment]
Please download new version of the DeviceDetectDebug app.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

The debug version has DS4WindowsDebug.exe.config configuration file and now there is a new Debug_CustomHIDUsageFlag option you can set to value "4". The debug version then tries to accept HID devices with Usage=4 flag value. You may need to tweak other debug options if the gamepad is not fully DS4 compatible, but you have to experiment with those values. 

```
<appSettings>	
  <!-- Debug_xx = Debug options to enable/disable/tweak certain features of DS4Windows app -->
  <!--   false = Disabled, true = Enabled. The default value in this file is the normal DS4Windows behaviour -->
  <add key="Debug_GyroCalibration"             value="true" />
  <add key="Debug_SendRumbleLightbarData"      value="true" />
  <add key="Debug_ReadTouchpadData"            value="true" />
  <add key="Debug_ReadGyroData"                value="true" />    
  <add key="Debug_ReadBatteryData"             value="true" />  

  <!-- 0 = Don't set custom number of HID buffers (use Win defaults). >0 Num of incoming HID buffers (default in DS4Windows app is 2 -->
  <add key="Debug_HidDSetNumInputBuffers"      value="2" />    

  <!-- 0 = Autodetect gamepad connection type, 1 = Force USB type, 2 = Force Bluetooth type -->
  <add key="Debug_ForceConnectionType"         value="0" />

  <!-- -1 = Use only default Usage=5 HID devices, 0..n = custom Usage flag value. For example Usage=4 is a joystick or sports controller type of HID device -->
  <add key="Debug_CustomHIDUsageFlag"          value="-1" />

  <!-- Debug text file output of BT/USB inputData. See %APPDATA%\DS4Windows path and inputreportdata_bt/usb.txt file -->
  <add key="Debug_PrintoutInputDataBuffer"     value="false" />
</appSettings>

```

**Comment by subjob** [comment]
Thank you so much! i got it to work i think, i'm gonna go on fifa and try it out

**Comment by mika-n** [comment]
Jätte bra. Please provide the Logs tabpage content as exported text file for further analysing. It helps to design how to make this support into an official release. Those custom debug options are not yet available in the official version. 

Test touchpad (map it as mouse in DS4Windows profile), rumble (test btn in DS4Windows or through a game), lightbar and gyro (map it as mouse in DS4Windows).

**Comment by subjob** [comment]
i tried it out and it seems to be connected but the buttons are all over the place. the controller works in fifa but still unplayable due to the buttons being mapped wrong. noticed it on this page https://gamepadviewer.com/

**Comment by subjob** [comment]
also the touchpad isn't working on this controller, don't know why it's there tbh.. so the log is just full of
"index out of bounds: touchpad"

**Comment by mika-n** [comment]
See #608  
DS4Windows definitely works with FIFA but you have to hide the original controller in order to avoid "double input problem" (ie. FIFA takes gamepad input both from the original physical controller and from the virtual output controller and this causes the game go woooooow).

**Comment by mika-n** [comment]
>also the touchpad isn't working on this controller, don't know why it's there tbh.. so the log is just full of
"index out of bounds: touchpad"

Please provide the logfile as an attachment (you can add small text files directly in github issues). Some 3rd party gamepads have only "click a touchpad" support but not a true touchpad. Is the touchpad working with PS4 console? If not then it is probably just a "click touchpad".

**Comment by subjob** [comment]
[log.txt](https://github.com/Ryochan7/DS4Windows/files/3903000/log.txt)
 oh okay, make sense. here is the log, managed to get rid of the errors by stopping and starting.

**Comment by subjob** [comment]
Square=1
Cross=2
Circle=3
Triangle=4

**Comment by mika-n** [comment]
Hmmm... Based on the logfile the gamepad doesn't seem to send standard directInput DS4 data packets to PC. Maybe it acts like xinput controller in PC? It would explain why buttons don't work.

DS4Windows app assumes that the HID/USB data packet contains the gamepad data in DS4 format. There are few differences in native xbox and ds4 data packets. If you set "Debug_PrintoutInputBuffer=TRUE" then you may be able to figure out which button is where through a debug file in "%APPDATA%\ds4windows" folder. Anyway. Then someone should add support to that custom raw data packet in DS4Windows, DS4Windows was not originally meant to support xinput/xbox gamepads (ie. some DS4 gamepads acts like xbox controller in PC but as D4 gamepads with PS4).

I suppose gyro, lightbar and rumble doesn't work either? Some 3rd party gamepads don't have gyro.

**Comment by subjob** [comment]
Nah gyro, lightbar and rumble doesn't work. I just realised that it's not a dualshock 4 but a DOUBLE shock 4... can't find any drivers for it. I tried to re-map it but i don't know what to do really,

**Comment by mika-n** [comment]
"Doubleshock 4" controller. Marketing bots are sometimes funny :-)    

The online store mentions that touchpad doesn't work, but rumble would work, but if the gamepad acts like xbox controller in PC then DS4Windows cannot drive rumble motors. The gamepad should be in in true DS4 state to do those special DS4 tricks. Rumble probably works in PS4.

If buttons are mapped wrong by default then you can use DS4Windows profile editor to re-map any button to act like any DS4 button. And if you set "Controller=dualshock4" option then the output virtual controller is seen by games as DS4 gamepad.

**Comment by subjob** [comment]
it's pure genius marketing! ;-P
Yeah, i guess it's not actually calibrated for pc, but i got it to work thru XOutput.
Thanks for your help, i'd be stuck with out it. <3

**Comment by mika-n** [comment]
Virtual output controller option "xbox360 vs Dualshock" in a DS4Win profile doesn't change how data from the physical source gamepad is read. It is what it is and sends what it sends to PC. 

But the Controller profile option is used to expose the output virtual controller either as xbox360 or dualshock4 gamepad for games (physical gamepad -> DS4Win app reads physical input -> DS4Win app creates a virtual output controller object -> DS4Win writes out gamepad activity to virtual controller and does profile specific re-map rules).
https://github.com/Ryochan7/DS4Windows/wiki/Settings

**Comment by subjob** [comment]
Just ordered a proper sony ps4 controller, fuck that chinese shit perkele.
