### ISSUE TITLE
Tilt like Steam Big Picture on Bluetooth

### ISSUE THREAD

**Issue by FadyMWill** [Ryochan7/DS4Windows#909]
![download](https://user-images.githubusercontent.com/58315299/69837692-b0272980-1258-11ea-98f7-b1e3adbe90aa.jpg)
How can i tilt or remap tilt to act like Steam Big Picture or normal PlayStation tilt in games that use DS4 as native using Bluetooth ?

like this image https://imgur.com/k1qRjjS
I've been playing Heavy rain for the last couple of days and i cant use the DS4 tilt I've to use it in Xbox mode to be able to complete certain tasks.
Please help.

**Comment by mika-n** [comment]
Unfortunately the dualshock4 virtual output controller of VigEm driver doesn't support DS4 gyro and touchpad "touch regions" in the current version (touchpad has only click-touchpad support).

DS4Windows app does support full functionality of touchpad and gyro, but it can be used only as a re-map source for other keys/triggers/axis/steeringWheelEmulation/mouse. VigEm developers are working on to add gyro and touchpad support in the virtual driver level at some point (when, no one knows) and then DS4Windows app can use that feature also.

**Comment by Ryochan7** [comment]
OP is mistaken. Steam Big Picture does not offer exposing gyro motions outside of the mapper. It can only map gyro input to virtual output controls like DS4Windows already does.

Also, that functionality would not be possible right now as ViGEmBus does not support relaying gyro or touchpad data to a virtual DS4 controller.
