### ISSUE TITLE
Automatic profiles not activating

### ISSUE THREAD

**Issue by Lombra** [Ryochan7/DS4Windows#91]
I'm having some issues getting auto profiles working. I set them up for Ghost Recon Wildlands and Duck Game, but neither seems to activate. I checked task manager while the games were running to get the right executables. Is the log supposed to say anything about profiles switching? It doesn't say anything when I launch these games.

I'm using 1.4.84.

I also have some questions regarding auto profiles. How does the triggering work? Is it actually when you launch and terminate an executable, meaning you might run into unexpected behavior if you launch another game before terminating the first one? Or is it only active while the game is in focus or something?

Finally, what I'm looking to do is disable the emulation for certain games that natively support the DS4. Is adding an executable auto profile and setting it to use no profile a supported feature, and if so, does it do the same as "temporarily disabling DS4Windows"? In a previous version the GUI seemed to let you set it up like that, but the executable would mysteriously disappear from the list when you checked later. Does temporarily disabling DS4Windows do the same as "Use DInput only"?

**Comment by Ryochan7** [comment]
I think I have tested auto profiles once and it worked the one time I tried it. It was within the last month but I cannot remember which version was being used. I have just tried it with version 1.4.85 and it works for me.

The auto profile support works based on the application currently in focus. Switching active applications will switch auto profile associations depending on the configuration you have made. The log should reflect the profile being used or if DS4Windows has been stopped. The main tab will not show the currently active profile for the controller though.

The "Use DInput only" option for profiles just disconnects the virtual Xbox 360 controller associated with the DS4Windows slot. It is useful primarily when using keyboard and mouse controls exclusively but it can be useful when exclusive mode is not being used for the DS4. The "Turn off DS4Windows Temporarily" option for auto profiles essentially behaves like clicking the stop button at the bottom of the window and disconnects all DS4 HID device connections and virtual Xbox 360 controllers. That way, you should be able to play a game that has native DS4 support and have it use the real controller as opposed to the virtual Xbox 360 controller. There is currently no way to temporarily disconnect one DS4 HID device connection.

**Comment by Lombra** [comment]
Alright, thanks.

I managed to figure out Duck Game. Seems like it's path sensitive. I use a symbolic link to get a shorter path to my Steam games, but the tool needs to real path.

Can not get Wildlands to work, however. Do you know of any reason the profile would not activate, assuming I've gotten the right executable?

![bild](https://user-images.githubusercontent.com/8340020/28239205-b8db2e02-6966-11e7-9d14-74cd75c0ab8d.png)

**Comment by Ryochan7** [comment]
Auto profiles do work based on the real executable path so symbolic links would not work. There is no way to get that information from the process so there is no way to make that situation work. I am not sure why Wildlands would not work. The only thing that might affect it would be if GRW.exe acts as a launcher and launches a different executable file for the game. Based on your task manager screenshot, that is probably not the case.

**Comment by Lombra** [comment]
Yeah, there are a couple of other executables in the folder, such as RunGRW or something, but I don't see them in task manager once the game is running.

Welp, I guess this issue is solved as far as I'm concerned. Auto profiles has worked for everything else so far.

I have opted to use a whitelist approach instead, where I disable XInput on the default profile, and then enable it for the games that need it, which is only a few non Steam games.
