### ISSUE TITLE
DS4 not working in games from xbox gamepass 

### ISSUE THREAD

**Issue by jojonathan-95** [Ryochan7/DS4Windows#911]
I'm currently using the last version of DS4windows(1.7.23) and the games from xgp dont detect my ds4 while other games from gog/steam detect normally. I tried using bluetooth, plug usb, hide/unhide.

**Comment by Ryochan7** [comment]
Does XGP require using an Xbox One gamepad? If that is the case then it will not work right now.

**Comment by jojonathan-95** [comment]
Don't know if XGP require using an Xbox One gamepad and didn't find that information. A think maybe it depends on the game because Forza horizon 4 detected my ds4 and other games like Darksiders 3, Vampyr, Bloodstained didn't detect.

**Comment by Ryochan7** [comment]
I have tested XGP and played Halo Reach. It works fine for me while using DS4Windows.

**Comment by jojonathan-95** [comment]
I dont know why some games on xgp were not detecting my ds4, but I formatted my pc and now everything is working.

**Comment by Ryochan7** [comment]
That stinks that you ended up reformatting. At least it is working for you now though.

XGP does not seem like a bad service so far. If nothing else, being able to rent Halo Reach for $1 is well worth it. I can just think of it as a modern take on the Sega Channel model.
