### ISSUE TITLE
Auto Profile Doesn't work with Borderlands 3?

### ISSUE THREAD

**Issue by JoelLindsey** [Ryochan7/DS4Windows#913]
There anyway to force it to switch? im trying to get ps4 ui icons ingame.

**Comment by Ryochan7** [comment]
If no match can be made then DS4Windows will use the original selected profile. There are a couple of workarounds via Special Actions or touchpad swipe to switch profiles as needed. There is no real direct way, that I know of, to force a switch.

One nice idea would be to implement some form of overlay window with a profile switcher. I really miss that feature from SC Controller and I believe Kozec got similar functionality working in recent Windows alpha builds. Not sure if it works in fullscreen apps though.

**Comment by mika-n** [comment]
If you enable the Debug autoprofile events -option then what do you see in Logs tab page when you open BL3 process?

**Comment by Ryochan7** [comment]
A quick aside, the SC Controller OSD works better than most but not in every case that I would want. It works in Daggerfall; even the virtual keyboard works in-game. It fails to work in Might and Magic 8 though. Bringing up the OSD causes the game to minimize and then the game renders incorrectly until restarted.
