### ISSUE TITLE
[TODO] Rewrite HidGuardian Test Installer

### ISSUE THREAD

**Issue by Ryochan7** [Ryochan7/DS4Windows#914]
The uninstall process of the old HidGuardian test installer no longer works with Windows 10 update 1909; I know it was working before. Just attempted to run the uninstaller and the app crashed near the end. The driver and device were removed from the system so I thought I was okay to reboot. Now my keyboard and mouse won't work so it is likely a problem with the UpperFilters registry key. I hope that I will be able to fix my problem without having to reinstall Windows.

I lost the old test installer source code when I reformatted last time so the issue cannot be fixed. A new installer will have to be written. I have removed the link for the old installer since I consider it unsafe now.

**Comment by Ryochan7** [comment]
I was correct about the problem. The UpperFilters registry value was still set. Had to boot into Recovery Mode from a flash drive, open regedit in a command prompt, load the proper Hive and blank that value. I can now login again.

Relevant article although the Hive path is different in this case.

https://www.winhelponline.com/blog/edit-registry-offline-windows-re/

Relevant path in this case:
```
<drive of main Windows install>:\Windows\System32\config\SYSTEM
```

**Comment by Ryochan7** [comment]
One definite change to make is to update the UpperFilters registry value first in the uninstaller rather than waiting until the end of the process. That way, at least there should be no reason to lose KB+M support if something goes wrong.

**Comment by Ryusennin** [comment]
Strange, because I've just been using the installer to successfully remove/reinstall HidGuardian with the latest Win10 2004 build.

**Comment by joseashb** [comment]
Just got the same issue, while I was forced to do a system restore.

Thanks in Advance mate

**Comment by joseashb** [comment]
> Strange, because I've just been using the installer to successfully remove/reinstall HidGuardian with the latest Win10 2004 build.

Does HidGuardian works onn your side mate?

**Comment by Ryusennin** [comment]
Yes, after I uninstall then immediately reinstalled HidGuardian through the test installer. I did this several times since build 1909 (I've subscribed to the Slow Ring). The app never crashed.

**Comment by joseashb** [comment]
> Yes, after I uninstalled then immediately reinstalled HidGuardian through the test installer. I did this several times since build 1909 (I've subscribed to the Slow Ring). The app never crashed.

Thanks alot mate, can confirm that Hidguardian works fine, and for removal, the manual way from the official guide works :)

**Comment by Ryochan7** [comment]
A newer installer has been made.

HidGuardianInstaller_20191218.zip
https://drive.google.com/file/d/1PNL3uv_4KektN00S9fm61djypSQ-3HED/view?usp=sharing

**Comment by Ryochan7** [comment]
I guess it is a good thing I got this uploaded recently. I just had to reinstall Windows 10 and I could have lost my work again. Since I did not link the code repository in this issue, I will make a link here.

Code:
https://github.com/Ryochan7/HidGuardianInstaller
