### ISSUE TITLE
Infinite Available Update

### ISSUE THREAD

**Issue by Leomelati** [Ryochan7/DS4Windows#915]
Every time that I initialize my DS4Windows the following message appears:
"Download Version 1.7.23 now?" and a "Yes" or "No" buttons.
I always click in the "Yes" but nothing happens and, in the next time that I open my DS4Windows, the message shows again.

**Comment by Ryochan7** [comment]
The process has not worked due to a bug introduced in version 1.7.21. Please run DS4Updater.exe manually to download the fixed version. There is a pinned issue regarding this problem.

https://github.com/Ryochan7/DS4Windows/issues/904

**Comment by Leomelati** [comment]
Thank you so much!
I will close this Issue
