### ISSUE TITLE
Windows game overlay opens when controller disconnects

### ISSUE THREAD

**Issue by AnessZurba** [Ryochan7/DS4Windows#916]
Hi,
I'm facing this weird issue (I think it's a bug)
When I disconnect the controller using PS + options, the hotkey for PS which opens the game overlay gets triggered (the controller disconnects just fine).
is there a way to fix this?

**Comment by Ryusennin** [comment]
Win 7 or Win 10?

Win 7, sounds like the Xbox 360 Accessories app is active. You should disable the program xboxstat.exe which is launched at Windows startup.

Win 10, I don't know, maybe the Game Mode is taking over the PS ("Guide") button.

**Comment by Ryochan7** [comment]
That is a problem with the PS button being used while mapped to Guide. Some applications can detect the Guide button press and will have special behavior when it is pressed. Steam would be the main example with the app gaining focus and the overlay appearing if playing a game in BPM. NVIDIA In-Game would use the Guide button to bring up some menu; my GPU is too old to even use In-Game so I don't know what comes up.

You have to either change the Special Action triggers or have PS Unbound in the loaded profile.

**Comment by AnessZurba** [comment]
@Ryochan7 since the PS+Option shortcut is set by default AFAIK in DS4Windows, I was thinking about maybe a delay in the trigger to enable shortcuts
So the PS click would be delayed a bit so I can press the combination

**Comment by Ryochan7** [comment]
Adding a delay to the special action has been brought up before but I never got around to implementing anything.

**Comment by Ryochan7** [comment]
Just thinking about this again. Adding a delay to the special action would not have an affect on this problem. The Guide button would still be activated immediately in the mapping routine even if both PS+Options were pressed at the exact same time; likely one trigger button would be pressed before the other though.

Adding a delay to the Special Action would only help when using the Sony Wireless Adapter. The Sony Wireless Adapter presents itself to Windows as a DS4 whether a controller is currently synced to it or not. When the Disconnect BT Special Action is activated, the last input packet sent from the adapter will still be used so PS will be seen as held down. That same type of problem would happen if you just held PS until the controller disconnected. A delay on the Special Action would be set up to wait for the trigger release before actually disconnecting the controller so PS will not be seen as held down.

**Comment by AnessZurba** [comment]
Actually, thinking about it I suggest adding the ability to run multiple actions in one "Special action".
That way, I can set the PS+Options to disconnect the controller then send PS click
That would hide the overlay that just appeared

This should be fairly simple to implement I suppose

**Comment by Ryochan7** [comment]
For that functionality, it would not be necessary. You can set a Shift Modifier on PS to be mapped to Unbound while Options is currently pressed. That should be a fairly easy way around the problem and still have PS bound to Guide by default. That should be enough to take care of the biggest problem. A delay would still be useful for the Sony Wireless Adapter problem as that depends on the behavior of the input controller.
