### ISSUE TITLE
ds4windows only works once per boot

### ISSUE THREAD

**Issue by powerpuffboysz** [Ryochan7/DS4Windows#918]
lately i've been having an issue where ds4windows will only work once per windows boot. my controller is a genuine v2 connected via bluetooth and should it dissconnect either by itself via timeout or through the stop/start switch in the lower corner no game will recognize it or a game may recognize it for like 2 button presses before not working altogether. and if it does manage to connect the log reads as 10ms latency and games will show controller prompts as if it sees the controller however nothing actually happens when i press buttons. ds4windows log tab insists everything is working fine and i'm about ready to pull my hair out. using windows 10 1909 update with fresh 1.7.23 download with hidgardian installed. was working fine up until today.

**Comment by Ryochan7** [comment]
I know I have encountered a problem with ViGEmBus once where the virtual Xbox 360 controller errored out so it was not usable. Have you checked the Windows Device Manager when this happens? I need to get a new DS4Windows  release out with some of the most recent changes that have been made.

**Comment by powerpuffboysz** [comment]
against the advice on the main page, enabling xbox control configuration seems to have fixed my issue

**Comment by RileyXX** [comment]
I just started having this issue again with the latest update (Windows 10). Just updated manually to 1.7.23 from 1.7.21. I used to have this problem a long time ago (atleast 6 months ago) but I haven't had this issue for a while maybe I've just been lucky idk. I've tried reinstalling ds4 windows, deleting my paired devices and reconnecting my ps4 controller etc. Everything I tried didn't work. Only thing that ever worked was restarting my computer. 

To replicate this issue try connecting ds4 normally once everything connected and working turn off the bluetooth from windows. Then close ds4 windows then reopen it and reconnect your controller. No controller will appear in ds4 windows even though it's connected via bluetooth. Only error I can see is LinkedProfiles.xml is not found.

**Comment by powerpuffboysz** [comment]
so after testing on various emulators the problem seems to be that when first launched the controller is assigned port 1. on subsequent connects/disconnects it plugs the virtual controller into port 2 then 3 and so on

**Comment by Ryochan7** [comment]
Thank you for looking into this. This type of issue has been discussed before but I cannot remember the issue number. Something happens in ViGEmBus to switch the used XInput port sometimes despite how devices are connected. One example is transitioning from XInput Port 1 to XInput Port 3 with XInput Port 2 not being used. I have only been able to produce that problem once during testing.

DS4Windows does not handle anything regarding the XInput port number that is used and just relies on what is given by ViGEmBus. Some extra precautions have been added to DS4Windows to try to work around possibly performing actions too quickly for the driver but those changes have not been released as of yet; one major tweak is only in the WPF build right now.

**Comment by powerpuffboysz** [comment]
after further testing only games running from steam were actually affected and ONLY if they were ran from the steam client gui (if i went to a game's install folder a ran a it from the executable, provided drm or whatever didn't demand steam be open anyway, it worked fine). i was running the betas and switched back to standard client updates and any and all issues seem to be fix. i would like to leave this open just in case it does crop up again and this is mere coincidence

**Comment by powerpuffboysz** [comment]
all good
