### ISSUE TITLE
Could not connect to ViGEmBus, again arghhh

### ISSUE THREAD

**Issue by MUXMAN** [Ryochan7/DS4Windows#921]
today I wake up with this problem, I´ve reading a lot of post , I´m trying a lot of solutions but nothing works. 
I reinstalled vigembus drivers a lot of time, from ds4windows, manually, unistalling all microsoft c++ packages now only have 2017.... I used diferent versions of ds4windows but the same problem again 
Could not connect to ViGEmBus
in device manager the driver is ok, my gamepad is connected ok but cond't connect to vigembus

I'm running windows 10 

Someone can hel me?

**Comment by Ryochan7** [comment]
The gamepad being connected does not matter initially. There could be a few sources for the problem. Which version of DS4Windows are you running (version and arch)? If updating from a previous version, did you make sure to overwrite the DLL files in the installation or just the executable? The ViGEm.NET client DLL has been updated a couple of times so using an outdated DLL will probably fail.

Newer error messages in DS4Windows should help distinguish between ViGEmBus not being detected at all and the ViGEm.NET client failing to work. That will be in the next release of DS4Windows which should be pushed out sometime today.

**Comment by MUXMAN** [comment]
Thanks in advance I'm using the latest version 1.7.23 x64 now , a fresh copy. The version when starts to fail was 1.7.22.
I delteted de ds4windows folder and reinstalled the drivers again . even delete the dll driver files from system 32 and system32/drivers

it is possible that a microsoft c++ 2010 installation caused the problem? iIt's the only difference from yesterday to today

**Comment by MUXMAN** [comment]
i just installed newest version , same problem
11/12/2019 20:03:41: DS4Windows version 1.7.24
11/12/2019 20:03:41: LinkedProfiles.xml can't be found.
11/12/2019 20:03:42: Could not connect to ViGEmBus. Please check the status of the System device in Device Manager and if Visual C++ 2017 Redistributable is installed.

**Comment by Ryochan7** [comment]
At least that clears up one problem. DS4Windows can actually detect the ViGEmBus device since the new error message did not show up. However, the client library still fails to work.

You can have multiple Visual C++ Redistributable packages installed alongside each other so I would not think it would cause an issue. Did you make sure to install the x64 version of the Visual C++ 2017 Redistributable? A lot of other apps would probably depend on the x86 32 bit version instead. You need to have the x64 version installed to work with the normal DS4Windows. I guess you could try to use the x86 build of DS4Windows and see if it works there.

**Comment by MUXMAN** [comment]
I have the x64 version of visual C++ 2017 
I´ve used the x86 version of DS4Windows and still the same problem

**Comment by MUXMAN** [comment]
Now its worked, i don't know what was the solution
First I unnistalled spc bus driver that i have installed
an another thing is execute ds4windows as admin

:)

**Comment by MUXMAN** [comment]
Only works if i run as admin, the problem is that doens autoexecute as admin when windows starst, i dont know the reason

**Comment by Ryochan7** [comment]
That is odd. DS4Windows works fine for me as a normal user. I normally run DS4Windows as admin but I just checked again to confirm that normal user mode works fine for me.

Also, the Run At Startup as a Program option does not work when you set the executable to always launch as the Administrator. That is technically a security feature of Windows. The only way to launch DS4Windows with admin privileges at startup is to use the Run as Task option instead.

**Comment by MUXMAN** [comment]
Yes is odd, for me it worked fine until yesterday, but suddenly only works if a run as administrator.
at least it works, I was already starting to go crazy finding a solution

Thank you very much for yout help
