### ISSUE TITLE
latest update breaks DS4windows

### ISSUE THREAD

**Issue by Careless** [Ryochan7/DS4Windows#924]
I just updated to the latest version, 2 days ago it was working fine. Now I get this error all the time:

`You must quit other applications like UWP apps (Netflix), Steam, Uplay, NVIDIA IN-GAME before activating the 'Hide DS4 Controller' option. For more info check https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues`

I have followed the exclusive mode tips, and dwm.exe keeps taking hold of any new physical device ID that is connected.

Dark Soul 3 requires Hide DS4 Controller, so I can't bypass this setting in order to operate the game. How can I fix this once and for all, because killing dwm.exe process just restarts explorer but it retakes posession of the phyiscal address of my controller again, multiple restarts of the computer and stop/start the DS4 program does not change anything.

**Comment by Careless** [comment]
It seems running it as a Task is the issue.
I am running it as a Program now, and seems to be working without issue so far.

**Comment by Ryochan7** [comment]
This is just system configuration issues coming into affect. No recent change in DS4Windows directly changed the behavior of Exclusive Mode functionality.

**Comment by Careless** [comment]
So do you advise as running it as a "Program" or as a "Task" in Win10?
I'm not sure if you are saying that it is a Win 10 or on my particular installation, because prior to the latest Win10 update, it worked as a "Task". After the latest update, it would act as outlined in the first post.

**Comment by Ryochan7** [comment]
I would think the Task option would be better. Although, I never liked the workaround that I implemented for the Run as Task option. A workaround was needed due to some performance concerns that existed at the time. The version of Run as Task implemented in 2.0 is more sane. DS4Windows 2.0 will automatically change the Task option to use the new routine the first time it is run.

**Comment by Careless** [comment]
yeah I figured Task was the preferred method as well, but it kept being supplanted by dwm.exe. Program works for now, but it will be interesting to see if 2.0 rectifies this issue.

thanks for your continued work.
