### ISSUE TITLE
How to make DS4win recognize the Hori wireless controller...

### ISSUE THREAD

**Issue by luojunyuan** [Ryochan7/DS4Windows#926]
there is the debug version DS4windows' log...
``` shell
2019/12/14 20:45:45: DS4Windows version 1.7.24
2019/12/14 20:45:45: LinkedProfiles.xml can't be found.
2019/12/14 20:45:45: 启动中...
2019/12/14 20:45:45: Connection to ViGEmBus 1.16.112.0 established
2019/12/14 20:45:45: 搜索手柄
2019/12/14 20:45:45: 使用共享模式 share mode
2019/12/14 20:45:45: DEBUG: EnumerateDS4. HID#1 Path=\\?\hid#vid_056a&pid_0300&col01#6&2fbf2fdb&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-Compliant Mouse  VID=0x0000  PID=0x0000  Usage=0x0  Version=0x0
2019/12/14 20:45:45: DEBUG: EnumerateDS4. HID#2 Path=\\?\hid#vid_248a&pid_8367&mi_01#7&a159a03&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd  Description=HID Keyboard Device  VID=0x0000  PID=0x0000  Usage=0x0  Version=0x0
2019/12/14 20:45:45: DEBUG: EnumerateDS4. HID#3 Path=\\?\hid#vid_056a&pid_0300&col02#6&2fbf2fdb&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=���� HID ��׼�Ĺ�Ӧ�̶����豸  VID=0x056A  PID=0x0300  Usage=0xA  Version=0x100
2019/12/14 20:45:45: DEBUG: EnumerateDS4. HID#4 Path=\\?\hid#vid_056a&pid_0300&col03#6&2fbf2fdb&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=���� HID ��׼����д��  VID=0x0000  PID=0x0000  Usage=0x0  Version=0x0
2019/12/14 20:45:45: DEBUG: EnumerateDS4. HID#5 Path=\\?\hid#vid_056a&pid_0300&col04#6&2fbf2fdb&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=���� HID ��׼�����ֻ���  VID=0x056A  PID=0x0300  Usage=0x1  Version=0x100
2019/12/14 20:45:45: DEBUG: EnumerateDS4. HID#6 Path=\\?\hid#vid_248a&pid_8367&mi_00&col01#7&1d45b641&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant mouse  VID=0x0000  PID=0x0000  Usage=0x0  Version=0x0
2019/12/14 20:45:45: DEBUG: EnumerateDS4. HID#7 Path=\\?\hid#vid_248a&pid_8367&mi_00&col02#7&1d45b641&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=���� HID ��׼���û������豸  VID=0x248A  PID=0x8367  Usage=0x1  Version=0x100
2019/12/14 20:45:45: DEBUG: EnumerateDS4. HID#8 Path=\\?\hid#vid_248a&pid_8367&mi_00&col03#7&1d45b641&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=���� HID ��׼��ϵͳ������  VID=0x248A  PID=0x8367  Usage=0x80  Version=0x100
2019/12/14 20:45:45: DEBUG: EnumerateDS4. HID#9 Path=\\?\hid#vid_248a&pid_8367&mi_00&col04#7&1d45b641&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant device  VID=0x248A  PID=0x8367  Usage=0x0  Version=0x100
-------------------> DEBUG: EnumerateDS4. HID#10 Path=\\?\hid#vid_0f0d&pid_0124&ig_00#7&21d8e05a&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant game controller  VID=0x0F0D  PID=0x0124  Usage=0x5  Version=0x0
-------------------> DEBUG: EnumerateDS4. HID#10 detected as DS4 compatible gamepad device
2019/12/14 20:45:45: DEBUG: EnumerateDS4. HID#11 Path=\\?\hid#vid_08bb&pid_2902&mi_03#7&4e8685c&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=���� HID ��׼���û������豸  VID=0x08BB  PID=0x2902  Usage=0x1  Version=0x100
2019/12/14 20:45:45: DEBUG: IsRealDS4. IsRealDS4=True  hDevicePath=\\?\hid#vid_0f0d&pid_0124&ig_00#7&21d8e05a&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  deviceInstanceID=hid\vid_0f0d&pid_0124&ig_00\7&21d8e05a&0&0000  Device_UINumber=
2019/12/14 20:45:45: DEBUG: findControllers. Found 1 possible device
2019/12/14 20:45:45: DEBUG: findControllers. Idx=0 Potential DS4 gamepad. Description=HID-compliant game controller  Path=\\?\hid#vid_0f0d&pid_0124&ig_00#7&21d8e05a&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
2019/12/14 20:45:45: DEBUG: findControllers. idx=0 Opening device VID=0x0F0D  PID=0x0124  isExclusiveMode=False
2019/12/14 20:45:45: DEBUG: findControllers. idx=0 IsOpen=True
2019/12/14 20:45:45: DEBUG: readSerial. Trying to read serial# from VendorID=0x0F0D, ProductID=0x0124, Version=0, DevicePath=\\?\hid#vid_0f0d&pid_0124&ig_00#7&21d8e05a&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030} InputReportLen=15
2019/12/14 20:45:45: DEBUG: readSerial. ERROR. HidD_GetSerialNumberString. Serial#=
2019/12/14 20:45:45: DEBUG: readSerial. Generating dummy MAC address based on HID device path \\?\hid#vid_0f0d&pid_0124&ig_00#7&21d8e05a&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
2019/12/14 20:45:45: DEBUG: readSerial. From now on you should always connect the gamepad into the same USB port or BT pairing host to keep the same device path.
2019/12/14 20:45:45: DEBUG: readSerial. Generated dummy MAC serial#=21:D8:E0:5A:00:00
2019/12/14 20:45:45: DEBUG: findControllers. idx=0 IsValidSerial=True  Serial=21:D8:E0:5A:00:00
2019/12/14 20:45:45: DEBUG: findControllers. idx=0 Using device \\?\hid#vid_0f0d&pid_0124&ig_00#7&21d8e05a&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  metainfo.name=Hori Wireless Lite USB
2019/12/14 20:45:45: DEBUG: DS4Device. Hori Wireless Lite USB conType=USB  MAC=21:D8:E0:5A:00:00
2019/12/14 20:45:45: DEBUG: DS4Device. Raw InputReportLen=15  OutputReportLen=0
2019/12/14 20:45:45: DEBUG: DS4Device. Current debug options: debug_HidDSetNumInputBuffers=2  debug_GyroCalibration=False  debug_SendRumbleLightbarData=True  debug_ReadTouchpadData=True  debug_ReadGyroData=False  debug_ReadBatteryData=True  debug_PrintoutInputDataBuffer=False
2019/12/14 20:45:45: DEBUG: DS4Device. Warning. Unexpected OutputReportByteLength 0. Using default output bufferLen 78
2019/12/14 20:45:45: DEBUG: RefreshCalibration. debug_GyroCalibration is FALSE. Skipping gyro calibration.
2019/12/14 20:45:45: DEBUG: DS4Device. Hori Wireless Lite USB conType=USB InputReportBufLen=64 OutputReportBufLen=78 synced=True runCalib=True IsFileStreamOpen=True
2019/12/14 20:45:45: DEBUG: WriteOutputReportViaInterrupt. fileStream.Write. DEBUG_LogCount=1
2019/12/14 20:45:45: DEBUG: WriteOutputReportViaInterrupt. ERROR. Exception while writing to stream. DEBUG_ErrorCount=1 函数不正确。(function goes wrong?)

2019/12/14 20:45:45: DEBUG: sendOutputReport. ERROR. writeOutput failed. Force quiting output thread. LastErrorCode=1
2019/12/14 20:45:45: DEBUG: findControllers. ERROR. idx=0 \\?\hid#vid_0f0d&pid_0124&ig_00#7&21d8e05a&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030} is in ExitOutputThread state. Failed to read inputData from the controller
```
in the debug config. I set the connect type value with "1"(force usb) and trun off the `key="Debug_GyroCalibration"` and `key="Debug_ReadGyroData"`. the controller has no gyro.

I try to add the pid 0124 to the list. but when I build it. log back this to me
![批注 2019-12-14 204130](https://user-images.githubusercontent.com/28323948/70849062-915d9f80-1eb4-11ea-907e-dd4d02dd4922.png)

what can I do next

**Comment by mika-n** [comment]
In #867 issue the support was already tried, but the gamepad doesn't seem to be fully DS4 compatible in PC.

The debug log you provided had couple messages which causes DS4Windows to ignore the gamepad. It seems that DS4Windows app cannot write anything to the gamepad (lightbar or rumble data), so after trying it few times DS4Windows gave up and disconnected the gamepad.

But, you could try using the following debug options in DS4WindowsDebug.exe.config debug options:
```
  <add key="Debug_GyroCalibration"             value="false" />
  <add key="Debug_SendRumbleLightbarData"      value="false" />
  <add key="Debug_ReadTouchpadData"            value="false" />
  <add key="Debug_ReadGyroData"                value="false" />    
  <add key="Debug_ReadBatteryData"             value="false" />  
```

In practice above shown options means that the gamepad would be treated as xinput type of controller without support for special DS4 features (gyro/lightbar/touchpad/rumble). These tweaks are not available in the normal vanilla DS4Windows release because DS4Windows app was never meant to be used with xinput type of controllers, but those debug options make it possible to test run such a controller.

Unfortunately some DS4 gamepads work as xinput only controllers in PC.

```
2019/12/14 20:45:45: DEBUG: WriteOutputReportViaInterrupt. ERROR. Exception while writing to stream. DEBUG_ErrorCount=1 函数不正确。(function goes wrong?)
2019/12/14 20:45:45: DEBUG: sendOutputReport. ERROR. writeOutput failed. Force quiting output thread. LastErrorCode=1
```

The warning message about failing serial/MAC address is not fatal. These recent versions of DS4Windows makes an alternative way to generate a runtime MAC address if the hardware MAC address is not available (at least by using DS4 gamepad compatible logic to read it).

**Comment by luojunyuan** [comment]
> In #867 issue the support was already tried, but the gamepad doesn't seem to be fully DS4 compatible in PC.
> 
> The debug log you provided had couple messages which causes DS4Windows to ignore the gamepad. It seems that DS4Windows app cannot write anything to the gamepad (lightbar or rumble data), so after trying it few times DS4Windows gave up and disconnected the gamepad.
> 
> But, you could try using the following debug options in DS4WindowsDebug.exe.config debug options:
> 
> ```
>   <add key="Debug_GyroCalibration"             value="false" />
>   <add key="Debug_SendRumbleLightbarData"      value="false" />
>   <add key="Debug_ReadTouchpadData"            value="false" />
>   <add key="Debug_ReadGyroData"                value="false" />    
>   <add key="Debug_ReadBatteryData"             value="false" />  
> ```
> 
> In practice above shown options means that the gamepad would be treated as xinput type of controller without support for special DS4 features (gyro/lightbar/touchpad/rumble). These tweaks are not available in the normal vanilla DS4Windows release because DS4Windows app was never meant to be used with xinput type of controllers, but those debug options make it possible to test run such a controller.
> 
> Unfortunately some DS4 gamepads work as xinput only controllers in PC.
> 
> ```
> 2019/12/14 20:45:45: DEBUG: WriteOutputReportViaInterrupt. ERROR. Exception while writing to stream. DEBUG_ErrorCount=1 函数不正确。(function goes wrong?)
> 2019/12/14 20:45:45: DEBUG: sendOutputReport. ERROR. writeOutput failed. Force quiting output thread. LastErrorCode=1
> ```
> 
> The warning message about failing serial/MAC address is not fatal. These recent versions of DS4Windows makes an alternative way to generate a runtime MAC address if the hardware MAC address is not available (at least by using DS4 gamepad compatible logic to read it).

OMG, turn off those options it appears in the list. but still seems no use😂. 
![批注 2019-12-16 000851](https://user-images.githubusercontent.com/28323948/70865768-3b642700-1f9c-11ea-81b9-6eda6abe61c5.png)
I definitely know it means. So it's not a kind of ds4 device...in fact the 🎮 couldn't connect to ps4 with cable. Only work with the bluetooth on PS4. maybe that's the reason...
Really Thanks for your help. I must 🤲 up this turn...
