### ISSUE TITLE
Feature Request: Hold arbitrary button down to temporarily disable touchpad inversion e.g., for quick use as standard mouse.

### ISSUE THREAD

**Issue by vvilkommen** [Ryochan7/DS4Windows#93]
I really appreciate your adding in the touchpad inversion feature; it was really, REALLY helped.

But! Would it be possible to add a qualifier button for it, too? Like "do not invert when button whatever is held (e.g., psx button -- please let me psx button for this)" for games where you really would not want the mouse cursor movement inverted (so one would hold the qualifier button down then) and leave the inversion in place when, in the same game, the touchpad is being used to control the camera (i.e., the in-game mouse cursor is not visible/being currently used)?

To be clear, I think, unlike for gyro for example which has a button to temporarily enable gyro motion, touchpad inversion should probably have a user definable button that temporarily -disables- touchpad inversion.

**Comment by Ryochan7** [comment]
It should be possible to add that functionality with only a little bit of work.

**Comment by vvilkommen** [comment]
You are officially my favorite mad scientist.

**Comment by Ryochan7** [comment]
This feature is in version 1.4.88.
