### ISSUE TITLE
Update broke DS4Windows

### ISSUE THREAD

**Issue by Madatek** [Ryochan7/DS4Windows#930]
It just won't recognize the pad

**Comment by mika-n** [comment]
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting
Please be a bit more specific. Review the Troubleshooting web page for more info about what details to provide at minimum.

What do you see in Logs tab page in DS4Windows? 
Do you have genuine Sony DS4 gamepad or some compatible model?
The same result both using USB and BT connection?
Can you see the gamepad in JOY.CPL (run that command) Windows controlPanel applet when DS4Windows is not running?


Try running the DeviceDetect debug version to diagnose gamepad connection issues. Please provide the content of the Logs tab page here (you can export the Logs content to text file in DS4Windows).
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

**Comment by Madatek** [comment]
Hello! Thanks for replying. Appearently, Windows decided to disable the Wireless Controller. Had to go to the Hardware settings and reenable it. I have no idea why, I found it by chance. I guess my computer is sentient and is trying to stop me from using it correctly.

So, problem solved, I guess. Thanks everyone for checking and sorry for any disturb.

Roberto.
