### ISSUE TITLE
[issue] Dualshoch 4 mode

### ISSUE THREAD

**Issue by tamodolo** [Ryochan7/DS4Windows#933]
DS4Win is a very good X360 controler converter but when you want to use DS4 with games that support it natively you're in hot water. Dualshock mode uses vigem to emulate the Dinput buttons and don't support anything else.

Because the exclusive mode not being fully solved, hidguardian is a necessary evil. And because of that only ds4win see DS4 and none other program. Because of that it's actualy impossible to use DS4 mode without messing with hidguardian (this causes me a lot of trouble).

My sugestion: instead of using vigem as bridge for this, just passthrough ds4 to the system. Don't know if it's possible.

**Comment by tamodolo** [comment]
Maybe a good workaround should be adding back the blacklist/whitelist hidguardian entries even if it's necessary to reboot.

**Comment by Ryochan7** [comment]
Manipulating the whitelist can be done without rebooting. Changes won't take affect until you unplug and then replug the DS4 into your PC. That behavior limits automated workarounds.

As it is, you could stop DS4Windows temporarily or via an auto profile entry so controller emulation is not done. If using HidGuardian at the time, you would have to modify the AffectedDevices list manually and then hotplug the DS4 so it can be seen by the system.
