### ISSUE TITLE
[Feature Request] BthPS3 released - add Dualshock 3 support?

### ISSUE THREAD

**Issue by Darthagnon** [Ryochan7/DS4Windows#934]
Nefarius has released his BthPS3 Dualshock 3 (DS3) driver, Shibari, and Fireshock. Would it be possible to add some sort of DS3 recognition or support to DS4Windows? Maybe set it up to start/stop a hidden Shibari instance, or add DS3 listing to the controller list?

**Comment by Ryochan7** [comment]
I haven't paid attention to FireShock new in a while. Doesn't it set up the controller as a DirectInput device?

Anyway, there is no planned support for any devices beyond DS4 controllers. There are many parts of the program that use values based on DS4 attributes so it would  be highly impractical to try to add support for other devices. A more flexible mapper would be required but I have not worked on one in some time.

**Comment by Darthagnon** [comment]
As far as I understand, Shibari communicates with Fireshock and represents the DS3 as a virtual Xbox 360 remote and a virtual DS4.

Fair enough, though. It should work as-is. Thank you for all your hard work on DS4Windows!

**Comment by Ryochan7** [comment]
I have mentioned before that I personally do not like the DS3. The DS4 was a much needed upgrade IMO. For my use case, I would like to have an alternative mapper that was compatible with the Switch Pro controller and the Steam Controller. I do not currently own a Switch Pro controller but I want to buy one at some point.

At least for the Steam Controller, the official Steam mapper does not do what I want. If it weren't for the open source SC Controller program, the Steam Controller would be a paperweight. I don't like Steam's DS4 support so I doubt that I would be happy with its Switch Pro controller compatibility.

**Comment by Ryochan7** [comment]
> **THE EULA STATES IT'S OPEN SOURCE, YET THE SOURCES ARE PRIVATE, WHAT THE...?**

> Yep. For now they'll stay that way. Forking a driver properly is an art almost nobody understands so until I've refined and documented the sources to my level of quality they will stay disclosed. If you have a problem with that, please uninstall my craft, thank you!

What bizarro world are we living in? If that's the reason, don't make a public release. Double checked it and the repo still seems to be private. May Saint IGNUcius show him the errors of his ways.

![saint_ignucius](https://user-images.githubusercontent.com/581968/73123305-3fe50d80-3f54-11ea-8da8-20a6c1f4e599.jpeg)
