### ISSUE TITLE
Please add option to disable low battery warning

### ISSUE THREAD

**Issue by tirafesi** [Ryochan7/DS4Windows#936]
Currently the lowest we can set the battery warning is at 0%.

However, DS4Windows often detects my controller having 0% battery when it does not.

Please add an option to disable the warning completely, as having the controller light pulsing / flashing while playing is very distracting.

**Comment by Ryusennin** [comment]
Have you tried changing the warning colour to black (RGB 0/0/0)?

**Comment by tirafesi** [comment]
Sure that would work, but then the color would be different from when regularly playing.

The warning simply isn't useful for me, since the battery is nowhere close to 0% when the program says it is.

IMO, the way to solve this would be to:

* add an option to disable the feature completely in the same menu where we choose between pulse or flash; or
* allow the user to set the warning threshold to `-1%` (i.e. it never triggers); or
* treat the warning threshold as `0% = disabled`

**Comment by Ryusennin** [comment]
Another possible workaround: use the same colour for default state and for warning (either flash or pulse). Disclaimer: I didn't try this since I rarely use Bluetooth.

**Comment by tirafesi** [comment]
That's what I'm doing at the moment. But that's the whole point of my post, even if it's the same color, the flashing / pulsing is still distracting.

**Comment by Ryochan7** [comment]
I ended up going with option 2 of having a negative number being counted as disabled. `-10%` is used as the minimum in the GUI to not interfere with the increment value used in the control. Version 2.0.11 should be released in a few days.
