### ISSUE TITLE
DS4 mode and vibrating?

### ISSUE THREAD

**Issue by maximpalych** [Ryochan7/DS4Windows#938]
Hello! I use DS4Windows in Dualshock mode and there is no vibration in RDR2. Although in Xbox360 mode it is. Is it possible to fix this somehow?

https://i.imgur.com/iXUGSQE.png

**Comment by mika-n** [comment]
Try testing the vibration of DS4 virtual output controller in https://html5gamepad.com/ web test app. At least here vibration works in both x360 and dualshock4 controller modes.

Maybe this is a game specific issue and it doesn't know how to use vibration (rumble) motors with dinput gamepads? If the game supports natively DS4 gamepad then try connecting the gamepad using USB cable and test the game without running DS4Windows app. Maybe rumble motors don't work even when it uses the "native" physical gamepad directly? If rumble doesn't work then the game doesn't know how to use rumble over dinput interface.

**Comment by Ryusennin** [comment]
The Rockstar launcher has no support for native DS4 (DInput) mode.

**Comment by Ryochan7** [comment]
RDR2 has some support for the DS4 based on the PCGamingWiki. I am betting that it is just through DirectInput rather than true native support. Very few DirectInput compatible games support DInput force feedback which would mean no rumble for the DS4. Rocket League is like that as well

The HTML5Gamepad web app does support DInput force feedback so you can use it to check if DS4Windows receives force feedback events from the virtual DS4 device.

**Comment by maximpalych** [comment]
I have two gamepad in HTML5Gamepad. Vibration works on one of them, but not on the second. Maybe the game uses the one on which there is no vibration? Is it possible to somehow turn off the "controller without vibration"?

https://i.imgur.com/1ZWzNbP.gifv

**Comment by mika-n** [comment]
@maximpalych See Wiki doc page about hiding the original physical gamepad controller HID device from games.   
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

**Comment by maximpalych** [comment]
Okay. I do not know what I did specifically :D, but in HTML5Gamepad there was only one gamepad. The vibration test works, but there is still no vibration in the game.

https://i.imgur.com/bvvVZ5j.png
