### ISSUE TITLE
Windows 10 borked. Need to reinstall. Down for at least one day

### ISSUE THREAD

**Issue by Ryochan7** [Ryochan7/DS4Windows#939]
Just a heads up. For some reason, Windows 10 borked my main NTFS partition to the point where it looks like I will have to reinstall. I deleted an old test folder and then Explorer got crash happy. I rebooted and now I cannot even get to the login screen. Recovery Options won't work either. Even Xubuntu cannot access some parts of the partition when mounted. At least I will be able to back up some of my recent projects and I believe my crypto wallets are backed up already.

RedSeaFS > NTFS

**Comment by Ryusennin** [comment]
The amount of hard crashes I had in Win10 because of a crappy Asmedia driver... I'm surprised I can still use it. Good luck with the reinstall.

**Comment by Ryochan7** [comment]
I am mostly back up and running now. I at least have the system to the point where I can get back to working on DS4Windows. I still don't know how the file system got so screwed up. CHKDSK showed a bunch of errors with the file system.

**Comment by Ryochan7** [comment]
Worse case scenario mostly confirmed. I am fairly sure that my computer's hard drive is screwed. I knew that my current drive had bad sectors near the end of the drive, based on the results from smartctl, so I had just set up no partition in that space (last ~10% of drive). Now, Smart tests fail at about 10% with 46 found bad sectors. I currently have enough funds so I guess I better buy a new hard drive. This will very likely put the 2.0 update on hold for a few extra days.

**Comment by Ryochan7** [comment]
Back up and running again temporarily. I have now pretty much pre-allocated ~30% of my hard drive to try to avoid the bad sectors that were found. The last test I did with the badblocks command only completed 25% in 12 hours but it did not find anything past around the 10% block mark. I hope that I will be somewhat safe for the time being until I get a replacement hard drive.

**Comment by Ryochan7** [comment]
Been safe with my current partition setup so far. I need to get a Windows 8.1 partition set up for testing since Windows 7 support will no longer be a thing. I hope that I left enough free hard drive space for testing.

**Comment by Ryochan7** [comment]
Great. It happened again.

**Comment by mika-n** [comment]
Once failing HDD, always failing HDD. Lesson learned. SSD doesn't make backups irrelevant, but the speed difference to HDD is like night and day. These days I use only SSD drives especially because I use only laptops and SSD is virtually immune to clumsy handling of a laptop.

**Comment by Ryusennin** [comment]
That's tough, but indeed bound to happen. My old 2 TB gaming drive started to crap out when I realized every single new file that was written on it was blank. Thankfully read operations were still functional and I could urgently make a mirror on a new 4 TB HDD.

For system partitions, SSDs have become really affordable. In January 2019 I grabbed a 700 GB Kingspec drive for my PS3 on Alibaba for 60 euros (shipping included). New year sales are just around the corner, I'm sure you can get a good deal from them.

**Comment by Ryochan7** [comment]
Finally ordered a hard drive last night. It is just a WD Blue 2 TB HDD which will be a basic upgrade from my current WD Blue 1 TB drive. My current drive has gotten to the point where it won't spin up sometimes and the motherboard sometimes doesn't detect it on boot. The new drive was purchased through tip money otherwise I would not have had the money to afford to get a replacement. Thank you guys and gals for helping me out.

**Comment by Ryochan7** [comment]
New hard drive should arrive tomorrow. I will probably be down most of Saturday reinstalling Windows and all the programs that I use.

**Comment by Tiberiusmoon** [comment]
@Ryochan7 Is it worth supporting Win8.1 tho?
https://www.w3schools.com/browsers/browsers_os.asp

**Comment by Ryochan7** [comment]
I didn't think that Win8.1 was that bad when I used it. Original Windows 8 was horrible for desktop PC usage though. The only couple of advantages of Win8.1 compared to Win7 for DS4Windows usage would be having access to a better BT stack by default and fewer problems with the ViGEm installer. Win7 SP 1 was considered the minimum target for DS4Windows 2.0 and earlier but the ViGEm installer that is used requires some very recent Windows 7 hotfixes in order to install ViGEmBus successfully.

I would assume that most people being forced to upgrade will move to Windows 10 but some testing should still be done on Windows 8.1. Hopefully It will be a long time before I potentially introduce any change that does not work on Windows 7.

**Comment by Tiberiusmoon** [comment]
I wonder how long it would take for a win 8.1 user to report a intentional DS4 windows Win 8.1 bug. 🤔

**Comment by Ryochan7** [comment]
Back in working order.

**Comment by Ryochan7** [comment]
I have the worst of luck. Random power supply issues popped up that caused a lot of system crashes even with a fresh install of Windows. Took a long time to isolate the problem. DS4Windows version 2.0.6 will probably just be released as is once I get VS and other tools reinstalled again.
