### ISSUE TITLE
DS4Windows About/Hotkeys window - wrong build shown, credit tab out-of-date

### ISSUE THREAD

**Issue by TristanYoung** [Ryochan7/DS4Windows#94]
Clicking on Hotkeys/About in the main program window opens the About window.

The build is noted as being the "Jays2Kings Build'.  Ryochan7 has done enough improvements that this build really should be called the "Ryochan7 build".  Or maybe "Ryochan7's Incredibly Wonderful and Frequently Updated Build".   The credits tab needs updating as well to reflect the current state of this project.

I'd like to take this time to thank Ryochan7 for all the fantastic work he's done on this project.  The updates have been fantastic, making this software better and better.  I haven't been able to find a way to send Ryochan7 a PM through github (is there one?).  Keep up the great work.

**Comment by Ryochan7** [comment]
Thanks for the comment. My tweaking of DS4Windows started as a way to give back after having used DS4Windows as a reference for getting a custom program working with the SCP Virtual Bus. That program has been a nice testing ground for checking code tweaks outside of .NET to make sure that performance has improved for the general configuration as opposed to a lucky code compile. Having Jays2Kings still listed in that string hasn't been a big deal but it probably should be changed to clear up any confusion.

https://bitbucket.org/Ryochan7/xinput_scpcontrol_test

**Comment by TristanYoung** [comment]
You're welcome.

There's nothing wrong with crediting Jays2Kings in there too.  It would be the respectful thing to do.

**Comment by Ryochan7** [comment]
Jays2Kings was already being credited in the About window in the Credits tab. All I ended up doing was pointing the source code link to point to this git repository rather than the Jays2Kings repository. The link for Jays2Kings still points to http://ds4windows.com/ but that should probably be changed to point to Jays2Kings' GitHub profile page at some point.
