### ISSUE TITLE
[Notice] Version 2.0.0. We'll Do It Live

### ISSUE THREAD

**Issue by Ryochan7** [Ryochan7/DS4Windows#945]
Despite the previous potential problems found with the old DS4Updater version, I have published the WPF build as version 2.0.0. If you are currently running DS4Windows 1.7.28, you should be safe to update to version 2.0.0. If you are running an earlier version of DS4Windows, you have two forms of recourse. You can manually update to version 1.7.28 and then update from that version to 2.0.0. One other route is to manually download the current DS4Updater.exe and run it in the DS4Windows installation directory.

x64:
https://github.com/Ryochan7/DS4Updater/releases/download/v1.4.0/DS4Updater.exe

x86:
https://github.com/Ryochan7/DS4Updater/releases/download/v1.4.0/DS4Updater_x86.exe

I have been wanting to get this build out for a long time. I personally find it to be a big improvement over DS4Windows 1.7.28 and the WPF build has been my main mapper for at least the past month.

For end users, the WPF version is more snappy in many regards including the mapping routine. Proper file logging is now done. NLog is used for logging support and hooks have been added to catch application crashes. The output message and stack trace will be added to the log file before the application is terminated.

On the development end, the WPF system is pretty nice overall. Layouts are being used heavily in the GUI so window scaling should be far less of a problem than with the old WinForms build; I have tested it a bit myself and scaling works out pretty well in the new GUI. Utilizing data binding and the MVVM pattern should make application development easier in the future and hopefully less susceptible to random slowdown issues than the previous code base. Hopefully I can try to implement some features that I have hesitated trying to work on due to performance worries. I also like the way that I structured some of the new classes compared to the old code base. In the WinForms build, there was a lot of business logic that was buried in the GUI classes when it was not needed. 

Christmas Day is almost over in my time zone so I better hit the submit button. Hopefully everyone had a good Christmas and I wish all of you a happy New Year.

**Comment by Nucleoprotein** [comment]
Merry Christmas 🎄 

Thanks for update but now some options are not working as expected or are not saved/loaded like : 

- white tray icon, after restart its colour one
- lightbar color selection is odd, it display now very dark colors
- in auto profiles add start menu programs does nothing

I think I go back to 1.7 for now.

**Comment by mika-n** [comment]
>in auto profiles add start menu programs does nothing  

Here it works and adds StartMenu programs just fine. Maybe this is a permission issue, because there are some small changes in how these features have been implemented. Did it work in V1.7.x version in your setup? 

You can have both V2.x and V1.7.x DS4Windows on the same PC as long those files are "installed" into a different program folder. Both versions can still share the same profile and configuration files.

**Comment by Ashuraman666** [comment]
I just now updated to 2.0.0(x64 i believe) and everytime i press the right mouse button to disconnect the controller, the entire app crashes. It does this every time i disconnect wireless controller

**Comment by Ryochan7** [comment]
The tray icon changes after selecting the option while the application is running. However, the white icon is not restored when starting the program again. That should be a minor fix in the view model to check for that setting.

I have kind of noticed the darker color usage while working on the WPF version. Especially with the new color picker using the Extended WPF Toolkit, there is a fairly large dark region compared to the old color picker. However, other portions of the app show darker colors as well. Maybe it is just something with the way WPF handles color brushes. It is a minor detail that I can get used to if it cannot be changed.

The auto profile "Add Start Menu Programs" menu option works for me just fine. Do the controls go back to a normal state or does that portion of the window stay disabled?

**Comment by Ryochan7** [comment]
Pretty sure that is just the way WPF handles color brushes. Even the color picker that Visual Studio uses in its Properties Editor behaves like that.

**Comment by Ryusennin** [comment]
Just played a couple of hours with ETS2 and La Mulana 1/2, all went a-ok with DS4W 2.0 (Win7, USB). No additional lag, no strange behaviour. A job well done!

I only noticed that when double-clicking a profile to edit it, the window size gets automatically reset to roughly a quarter of my 1080p screen.

**Comment by Nucleoprotein** [comment]
Tested add start menu programs again, it works, but it need little more time to proces than 1.7.
