### ISSUE TITLE
2.0 Controller Options Vertical Scrollbar 

### ISSUE THREAD

**Issue by shinra358** [Ryochan7/DS4Windows#948]
2.0 version scrollbar is snappy instead of smooth.

**Comment by Ryochan7** [comment]
I can kind of see what you mean when using the Axis Config tab. I don't know if there is a way to change the scroll speed used for the scrollbar but I am fine with the current behavior. I will look into it.

**Comment by shinra358** [comment]
Yeah the scrollbars work fine everywhere else instead of when editing the controller profiles seems like.

**Comment by shinra358** [comment]
Thanks
