### ISSUE TITLE
2.0 Auto TimeOut Lightbar Dimming Issue

### ISSUE THREAD

**Issue by shinra358** [Ryochan7/DS4Windows#950]
When the DS4 lightbar dims as the controller is about to time out, the light completely turns off maybe 30 seconds before the controller does. The light is supposed to turn off exactly when the controller does.

**Comment by Ryochan7** [comment]
I'll look into this but nothing changed with the lightbar routine in the 2.0 update. It should be behaving like it does with version 1.7.28.

**Comment by shinra358** [comment]
no need. I tested this again with the updated vigem driver and it works fine now.
