### ISSUE TITLE
[ENHANCEMENT] Gui Dark Mode

### ISSUE THREAD

**Issue by shinra358** [Ryochan7/DS4Windows#951]
I would like to ask for the ability to have a dark mode for the ds4windows gui. It would use the colors of the ps buttons for the letters depending on if the words are the title, category, sub-category, etc. Textboxes would be dark grey and the main areas would be black. Scrollbar sliding space would be normal grey. Theme would also extend to the taskbar menu as well. Just throwing the idea out there.

**Comment by Ryochan7** [comment]
That should technically be possible using WPF. It would be a matter of creating a custom style in a resource file and using that resource in the various XAML files.

**Comment by Ryochan7** [comment]
Finally looking into this. WPF does not make the task that easy despite being easier than it would be using WinForms. Some of the pre-made packages that I have found are too invasive when it comes to control styling and usually don't look as good as the current theme. Material Design is probably one of the better ones I have come across but the style does not look that good for a Desktop application.

**Comment by Ryochan7** [comment]
I tried. This is about as good as it is going to get.

https://github.com/Ryochan7/DS4Windows/tree/darktheme_experiment

![ds4win_dark_theme_preview](https://user-images.githubusercontent.com/581968/101244040-b2249380-36c9-11eb-9647-c92265e22ded.png)

**Comment by shinra358** [comment]
Cool. The thin lines that are white and the white scroll bar path, can we
get some purple action in place of said white? Or a user profile for the
color scheme so we can make our own? If not, still looks cool. 😇
