### ISSUE TITLE
2.0 app crash when disconnecting manually

### ISSUE THREAD

**Issue by Ashuraman666** [Ryochan7/DS4Windows#953]
Every time i right click to disconnect the wireless controller the entire app crashes and i have to start it again, this happens everytime i disconnect manually by right clicking, something that's never happened to me on previous versions

**Comment by Ryochan7** [comment]
Can you post the ds4windows_log.txt file? Can't do much without it. Manual disconnecting works fine for me when using BT and the Sony Wireless Adapter.

**Comment by Ashuraman666** [comment]
> Can you post the ds4windows_log.txt file? Can't do much without it. Manual disconnecting works fine for me when using BT and the Sony Wireless Adapter.

Just the ds4windows_log.txt? Or the ds4windows_log_a bunch of numbers.txt?

**Comment by Ryochan7** [comment]
Those are the archived log files. NLog is configured to keep the last 7 log files before any old log file is removed. ds4windows_log.txt is the most recent log file. Can you find which archive file has the crash log and post that log file?

**Comment by Ashuraman666** [comment]
> Those are the archived log files. NLog is configured to keep the last 7 log files before any old log file is removed. ds4windows_log.txt is the most recent log file. Can you find which archive file has the crash log and post that log file?

[ds4windows_log_20191226.6.txt](https://github.com/Ryochan7/DS4Windows/files/4003212/ds4windows_log_20191226.6.txt)
This is the one i believe

**Comment by Ryochan7** [comment]
This issue was fixed in 2.0.1.
