### ISSUE TITLE
Reconnect problem

### ISSUE THREAD

**Issue by xDarkOne** [Ryochan7/DS4Windows#956]
I have a problem. 
I added DS4 as a device in bluetooth, it works.
Then I manually turn off DS4 and turn on it. Bar lights white and DS4 not reconnect. I think that the problem is with my Bluetooth Dongle, but can I fix it by myself? Or I need another dongle?

**Comment by Ryochan7** [comment]
Are you running Windows 7 by any chance? That is the only operating system where I have encountered that problem myself. Unfortunately, I do not know of a way around the problem expect for using a newer version of Windows. Maybe you can try to install the Toshiba BT stack and see if you have better luck with it compared to the bundled Microsoft BT stack.

**Comment by xDarkOne** [comment]
Windows 10, I will try to buy another dongle and will check this problem.
