### ISSUE TITLE
Keyboard key not working after mapping it to controller

### ISSUE THREAD

**Issue by hamiltino** [Ryochan7/DS4Windows#957]
Mapped the k key to controller and installed HID Guardian(Helps put controller into exclusive mode). After the k key does not work on keyboard. Uninstalled HID Guardian but the problem still exists. Reinstalled keyboard drivers, removed the USB connection and reinserted USB but still same problem.

**Comment by hamiltino** [comment]
Changed Language layout of keyboard and restarted. the k key worked for on sign in but stopped working after 5 seconds.

**Comment by mika-n** [comment]
Do you mean that just the "K" key doesn't work, but other keyboard keys work just fine? Or the whole keyboard is now broken?

Don't see theoretical cases how just one keyboard key would stop working even with HIDGuardian tool, but in theory it is possible to end up having non-functioning keyboard if HIdGuardian uninstallation fails (link of HID classfilter driver linking corrupted). See "driver uninstallation / classfilter manual removal" link in the following web page:
https://forums.vigem.org/topic/271/hidguardian-v1-driver-installation

**Comment by Ryochan7** [comment]
Pretty sure that whatever problem you are having has nothing to do with DS4Windows. It is probably not related to HidGuardian either as that would be an all or nothing scenario. If the keyboard works at all then HidGuardian is not interfering.

**Comment by Ryochan7** [comment]
Do you have DS4Windows set to launch at startup? mika-n has a point regarding if you mapped a virtual K press to the analog stick. You would need a dead zone set on LS and/or RS if mapping KB+M controls to the analog sticks. The DS4 analog sticks do not return to absolute center a lot of the time so you need to have some form of dead zone set so actions are not unintentionally executed.

**Comment by hamiltino** [comment]
Thanks for the help! Yes you are right. I assigned a controller input to the k key and then assigned the k key with push to talk on my NVIDIA in game overlay. I just reset the Nvidia shortcut button and it works now.
Offtopic
Does DS4Windows + HIDGuardian work with PS4 Controller wired or is it only for bluetooth?

Anyway thanks so much!
