### ISSUE TITLE
Low Battery Light Issue

### ISSUE THREAD

**Issue by shinra358** [Ryochan7/DS4Windows#960]
When multiple controllers are on, and one has power and the other is on 0%, the 0% ds4 will take the light color of the first controller's light instead of maintaining it's own given color.

**Comment by shinra358** [comment]
Do I just change the empty color to solve this? I thought black = default color (full color setting) but it might just be taking the default color of the first controller instead of it's own default color (just a theory).

**Comment by Ryochan7** [comment]
Black will mean no color so the controller will not adjust when using the "Color by Battery %" option; it is the same way with the old WinForms build. The full color will be maintained at all times. The Empty color should default to pure red though (R = 255, G = 0, B = 0). Will look into that.

**Comment by Ryochan7** [comment]
Just found an old bug with the Jays2Kings 1.4.52 build. A bad copy paste made it so Red was never reset when creating a profile; a line is there for it but it just resets Blue before the real step is hit. It looks like the default for the Empty color is supposed to be black.

Just checked its version of ScpUtil.cs as well. It does look like the default is actually supposed to be black (or more actually no color change). Need to think about this.

**Comment by Ryochan7** [comment]
In case anyone is curious, here is the where the problem is located.

https://github.com/Jays2Kings/DS4Windows/blob/jay/DS4Windows/DS4Forms/Options.cs#L373
