### ISSUE TITLE
2.0 Duplicate Profile editing + issue ive noticed

### ISSUE THREAD

**Issue by Tiberiusmoon** [Ryochan7/DS4Windows#961]
when expanding the window it shows more UI's, this keeps replicating each time you edit a profile with the newest one being the last profile you chose to edit.
https://i.imgur.com/hkhp51p.jpg

For some reason the software has problems switching profiles

**Comment by Ryochan7** [comment]
Pretty sure you never clicked Save or Cancel. There is no check in the button routines that open the Profile Editor for an already open editor. The assumption is that you will click Save or Cancel in the Profile Editor before attempting to create or open a different profile.

Looks like that check might be needed after all.

**Comment by Ryochan7** [comment]
Wow. Testing the old functionality allowed me to finally find a bug that I knew I encountered once. Running the Profile Editor like that in the old build loads the chosen profile in the same editor. However, the Profile Editor will still be visible even after saving a profile. Even worse, DS4Windows will crash while closing. I don't know how other people have not encountered a crash in that situation.

This is definitely a case of me using DS4Windows differently than other people. As it is, I think that I will just block attempts to reopen the Profile Editor.

**Comment by Tiberiusmoon** [comment]
https://pics.me.me/programmer-user-when-people-use-your-program-40684872.png
