### ISSUE TITLE
2.0 blurred texts

### ISSUE THREAD

**Issue by tordenflesk** [Ryochan7/DS4Windows#963]
a bunch of texts are blurred:
https://i.imgur.com/CMABOuP.png
https://i.imgur.com/5xatbdD.png
https://i.imgur.com/ctGhZCF.png
https://i.imgur.com/sY90gs0.png
https://i.imgur.com/9FaYW4d.png
https://i.imgur.com/ibNNP5M.png
https://i.imgur.com/wjDeiP5.png
https://i.imgur.com/HucmxSv.png
https://i.imgur.com/FmfdI4B.png

Resizzing a column header slightly seems to move the texts just "in to focus" again, so I'm guessing this is an issue with the texts being  positioned on half-pixels.

**Comment by Ryochan7** [comment]
This issue should be mostly resolved with the last two updates (now at 2.0.10).

**Comment by tordenflesk** [comment]
Doesn't appear to have made any difference:

![1](https://user-images.githubusercontent.com/2136727/74580890-fe6edd80-4fa8-11ea-82b4-6935ba6e8d1e.gif)

**Comment by Ryusennin** [comment]
What OS is that? Are you using Wine?

**Comment by tordenflesk** [comment]
Windows 7 x64

**Comment by Ryusennin** [comment]
Not sure which style you're using then. I have Win7 Ultimate and I don't experience these bugs.

**Comment by tordenflesk** [comment]
It's just "windows classic" with BBLeanSkin (part of BBZero). I doubt it's relevant to the issue.

The issue (seems to me) that there's something messing with the positioning of the letters, placing them on "half"-pixels. Since I'm using a pixel-font it blurs the font.
