### ISSUE TITLE
What is the intended function of auto profiles?

### ISSUE THREAD

**Issue by Tiberiusmoon** [Ryochan7/DS4Windows#964]
I wish to check its running as intended for 2.0.

**Comment by mika-n** [comment]
Do you mean that you have set some autoprofile rules, but you are not sure it works the same way it used to work in V1.7.x? Or do you mean how to use it and what it is suppose to do?

See the following doc page.
https://github.com/Ryochan7/DS4Windows/wiki/Profile-selection-using-auto-profile-rules

**Comment by Tiberiusmoon** [comment]
The latter

**Comment by Tiberiusmoon** [comment]
@mika-n just another question.
What does this do? https://i.imgur.com/Y1w5YgL.jpg

**Comment by Ryochan7** [comment]
By default, profile associations are done by controller slot. Using the Link Profile option allows a profile to be linked to a controller's serial address instead. That way, the same profile will be loaded for that specific hardware no matter which input controller slot is being used in DS4Windows.

I don't really use that feature myself. It was originally written by someone else with some changes made by myself. Getting the feature to work in the WPF build was the first time I had messed with it in a long time.
