### ISSUE TITLE
Bluetooth connection is disabled when plugging to usb

### ISSUE THREAD

**Issue by zenorabi** [Ryochan7/DS4Windows#966]
When I plug the usb cable to recharge my controller, DS4 switch to usb mode instead of staying in BT. I did not enable the quick charge option.

**Comment by mika-n** [comment]
Try using some mobile phone USB cable to charge the gamepad from PC. I have several mobile phone usb cables which don't activate the DS4 gamepad over usb, but the cable can charge the gamepad. I guess many of those cables are not fully connected and compatible with DS4 gamepad. Anyway, this is an easy way to keep the gamepad in BT while charging from PC.

Other option is to charge the gamepad from a wall plug and not from PC.

**Comment by LividJava** [comment]
Yeah go ahead and try a power only cable. if you've recently updated make sure that quick charge is indeed disabled. If you happen to have steam running, try enabling exclusive mode.

**Comment by Ryochan7** [comment]
You might want to double check whether the Quick Charge option is enabled. Also, have you checked the log to make sure DS4Windows disconnects the controller? Maybe something else is at play. Plugging in a USB cable to a BT connected controller works as expected on my end whether the Quick Charge is enabled or not.

**Comment by zenorabi** [comment]
It seems that the problem is caused by my controller. I've tested with a friend's DS4 on my pc and it stays in BT when I plug the usb.
