### ISSUE TITLE
Feature Suggestion: Named controllers column in controllers tab

### ISSUE THREAD

**Issue by Tiberiusmoon** [Ryochan7/DS4Windows#972]
We currently have ID's to seperate one controller from another.
My suggestion is to have a name section, the name sourced can be found from the device itself using the same location as the logs do when connecting a controller: https://i.imgur.com/CscdL1Y.jpg

This can improve the user friendliness of the software by having a name rather than a number to identify different controllers.

**Comment by mika-n** [comment]
Name? You mean the gamepad vendor and product type name? It would be possible to show this name in GUI but then again it is not unique name if there are more than one similar gamepads, so don't see how that name would make a big difference. Sure if all gamepads are different brands then it would make sense (Logs tab page shows gamepad model names based on the gamepad hardware VID/PID identifiers).

**Comment by mika-n** [comment]
The current version of DS4Windows lists the name (brand name, not unique if two identical gamepads are connected) of the detected gamepad in Controllers screen.
