### ISSUE TITLE
Driver Won't Install

### ISSUE THREAD

**Issue by SaltyNutella** [Ryochan7/DS4Windows#974]
![Capture](https://user-images.githubusercontent.com/45467864/71538255-8875c080-28ed-11ea-9415-66298f378754.PNG)

I've included a picture for reference. When I click install driver, the window just disappears and the driver doesn't seem to be installed. Next time I start ds4 it prompts me again. It says "if the window reappears I may need to restart"so I did and I tried restarting after every install but it still won't work.

**Comment by Ryochan7** [comment]
That issue has been fixed in the code. Had a couple of errands to run so I have not gotten a new release out yet. The problem is that an HttpClient instance was attempted to be used before it was created which led to the crash.

**Comment by SaltyNutella** [comment]
Okay, thanks for letting me know!

**Comment by Ryochan7** [comment]
Got version 2.0.1 published. ViGEm driver installation has been tested and is confirmed to work.

**Comment by SaltyNutella** [comment]
Confirmed, it is working now. Nice!
