### ISSUE TITLE
Version 2.0.1 will not open

### ISSUE THREAD

**Issue by AirysDark** [Ryochan7/DS4Windows#975]
i tried everything so i wont back to 2.0

**Comment by Tiberiusmoon** [comment]
Have you tried opening in admin mode?

**Comment by mika-n** [comment]
Anything in "%APPDATA%\ds4windows\Logs" logfiles? There should be a detailed error message if the app crashes.

**Comment by rcostanza** [comment]
I had the same issue, after updating from 1.7.x to 2.0.1 through the updater it wouldn't open. No log was being generated at that folder. Event viewer had an `IO.FileNotFoundException`, but no other details.

I ended up "reinstalling", downloading a release and extracting the zip file over the previous directory, and now it works. Just a guess, but maybe it was missing the `BezierCurveEditor` directory and contents, that didn't exist before 2.0.

**Comment by mika-n** [comment]
Missing "BezierCurveEditor" folder and web files there should not cause DS4Windows app crashes. Files in that folder are used only when axis uses "Custom" curve option and "..." button is pressed in a profile editor to open a custom curve editor (web app in BezierCurveEditor folder).

There has been few bugs and problems in the automagical updater logic. Could be that there are still some corner cases causing problems in auto updater. For example if it fails to drop in all required DLL libraries then DS4Windows app won't open. "Solution/Workaround" is to download the latest zip release from this web site and updating the app "manually" (ie. extracting the downloaded ZIP file).
https://github.com/Ryochan7/DS4Windows/releases

**Comment by AirysDark** [comment]
yea i download the zip. and it worked. as someone said the auto updater most of not work.

but its working now. keep up the good work man. i only found this project 2 weeks ago. i had been using the other died one for a long time. when i was googling a problem with it. and found you were hard at work on this project.
