### ISSUE TITLE
(v2.0.1) Gyro trigger going back to “Always On”

### ISSUE THREAD

**Issue by nr1995** [Ryochan7/DS4Windows#976]
When you change the trigger button beside the word “Triggers”,
then save,
then go back in and edit again,
it's back to “Always On” like it was originally.
Clicking on it to change it again shows a tick beside what you selected from the drop-down menu,
but when the drop-down menu is gone it looks like “Always On”.
Don't know how the app is reading it,
but it's confusing at best and annoying at worst.
![demo](https://i.imgur.com/N4LZDlC.gif)

**Comment by Ryochan7** [comment]
The Gyro Mouse Joystick version works fine but not the Gyro Mouse one. That should show which mode has been used more recently. It should be a quick fix in that case.

**Comment by Ryochan7** [comment]
Bad copy pasta. The display string for Mouse Joystick was actually being updated in the routine. Changed the routine to update the correct property and it works now.
