### ISSUE TITLE
Auto Profiles Not Working

### ISSUE THREAD

**Issue by Chrisnetika** [Ryochan7/DS4Windows#977]
Version: 2.0.1 (latest at this time)

Issue: Auto profiles is not working as intended before

Last version it was working: 1.7.23 (didn't try it in 1.7.28 due to doing proper upgrade path to 2.0 as instructed)

What is expected behavior: I have couple applications setup  as well as profiles and I expect when I switch to an application I setup to use a certain profile I expect that profile to kick in.
ie; I have chrome setup to use a profile where I can use my gamepad as a mouse mainly for the scrolling because my mouse is borked atm 
I also have a profile set for one of the games I play that has all my touchpad mappings that I need.I expect when I play my game DS4 switching to my other profile I setup for it so those mappings work for me.In my other display I have chrome so i switch back and forth and DS4 dynamically switches to the set profiles I set in seamless fashion and that all worked great before.

Additional details: So atm when I have chrome as the active window it does not switch to the profile I want automatically as before.I have even redid my mappings for the profile it was suppose to switch to.Oddly if i manually set the profile the mappings work everywhere but chrome! 
As a temporary fix I had to uncheck chrome in auto-profile and now mappings work for chrome as before.. caveat is I need to manually set the profile whenever I wanna use chrome :(

**Comment by Chrisnetika** [comment]
For me this function is essential so I am going to roll back to last working version 1.7.23 or 1.7.28

**Comment by Chrisnetika** [comment]
actually it doing it on all versions, this is weird now zzz
but some reason it's chrome that giving the issue, my profiles will not work with chroe at all if chrome is set in auto profiles

**Comment by Chrisnetika** [comment]
weird.. now it works properly, I had to make another rule for another browser to test it and saw that it worked so made another rule for chrome again and seems to work.. odd

**Comment by Ryochan7** [comment]
I had tested importing an Auto Profiles.xml file from before version 1.7.23 to one of the betas; I wouldn't know which version exactly without looking at some comment dates. The file loaded fine and all the old rules worked as intended.

The Auto Profiles system is not something that I really use. I don't have a use for it and it used to be a guaranteed way to add slowdown to the application. The new way of handling auto profiles works better on my machine and a lot of testing was done with the auto profile system running at all times with three Dogecoin wallet rules set up. The system is no longer reliant on updating any controls so all process can be done in a background thread.

**Comment by mika-n** [comment]
Tested the latest V2.0.1 and the auto-profile feature seems to be working OK even with Chrome process. Maybe there was some hidden whitespace or other special char at the end of process name and window title search keywords and that's why auto-profiler never found "Chrome" match?

**Comment by Chrisnetika** [comment]
I got it to work somehow by removing chrome from the list then putting in a diff application (comodo icedragon) then set the profile I want on it like I done for chrome and it worked no problem.I then recreated the chrome rule on next line, set it up like before with the profile I want and it seemed  to do the trick.It just very odd that it did not wanna work in that particular rule.
