### ISSUE TITLE
VigemBus Driver is not installing

### ISSUE THREAD

**Issue by rodpim8** [Ryochan7/DS4Windows#982]
I downloaded the DS4Windows and when i open it, asks to instal the VigemBus Driver, however, it doesn't download.
Actually, it stays at "Downloading 0,00%" and never changes.
Please, help me

**Comment by Lili-SXC** [comment]
Me too

**Comment by WhiteyDude** [comment]
I grabbed the latest release from [here](https://github.com/ViGEm/ViGEmBus/releases), installed and restarted DS4Windows, seems to be working fine. Note the latest is a pre-release at this time of writing, so you might be better getting one version back (1.16.115)

**Comment by mika-n** [comment]
The VigEm 1.16.116 has the same signed driver, but the installer app itself is supposed to be tweaked to solve those weird ViGem installation failures. So, I would say it is pretty safe to try this latest installer if the 1.16.115 version fails to install the Vigem driver. However, if 1.16.115 is already installed then there is no need to download and install this 1.16.116 VigEm package because the driver has still the same version.

**Comment by Tiberiusmoon** [comment]
Me too, but i already have it installed

**Comment by pransh15** [comment]
If any of you have the 1.16.115 or higher downloaded, can you pass it on here?
The download speed is 4kB/s and it just fails to download.

**Comment by Ryochan7** [comment]
The file was moved. The old release entry is gone. My Windows install got corrupt again so I didn't even get to commit the fix; compy screwed up while running the VS debugger. I have to order a new hard drive tomorrow.

Current URL
https://github.com/ViGEm/ViGEmBus/releases/download/setup-v1.16.115/ViGEmBus_Setup_1.16.115.exe

**Comment by mika-n** [comment]
Anyone having trouble installing a fresh copy of ViGem driver via DS4Windows app then the following DS4Windows wiki troubelshooting page has a link list to various required libraries (.NET Framework/VC++/Vigem). 
https://github.com/Ryochan7/DS4Windows/wiki/DS4Windows-and-HIDGuardian-Install-and-Setup-Guide#hidguardian-test-installer

**Comment by Ryochan7** [comment]
Version 2.0.2 uses the updated installer URL. 1.16.115 is still being used as 1.16.116 is a pre-release so I am a bit leery about linking to it now. Once it gets flagged as a mainline release then I would test the installer myself and link to it in DS4Windows.
