### ISSUE TITLE
Connected via BT but not working

### ISSUE THREAD

**Issue by rtran17** [Ryochan7/DS4Windows#984]
I've downloaded the drivers and managed to get my controller connected and it shows under the controller tab and the light is blue. The touchpad works as a mouse but when I try to play The Witcher 3 none of the button or stick inputs work, just the touchpad. Any suggestions?

**Comment by Tiberiusmoon** [comment]
Does the game support xbox 360 controllers? if not then you have to create a profile based on keyboard inputs.

Or have you tried enabling or disabling this setting? https://i.imgur.com/SaEdyZb.jpg

**Comment by Rabb1tof** [comment]
@Tiberiusmoon this can fix work on BT? My controller is connected, but not working in games.

**Comment by mika-n** [comment]
Some people are using DS4Win with Witcher3, so it should work. Have you enabled an exclusive mode (HideDs4Controleller option in Settings)? Maybe the game is now detecting both the original ds4 gamepad and the virtual output gamepad created by DS4Win app and the game is confused of double inputs? 

Are things working with other games?

See Wiki Troubleshooting pages for more info.

**Comment by rtran17** [comment]
I tried exclusive mode, no luck. I also tried the controller on skyrim, no luck. For more context, I run skyrim through steam and I run the witcher without a launcher. Originally downloaded from GOG galaxy if that matters.

**Comment by powerpuffboysz** [comment]
i think steam may be actively blocking ds4windows. i have issues if i run a game through it but if steam is closed (and i mean by ending it through task manager) emulators and games i launch directly from the executable work fine

**Comment by Ryochan7** [comment]
I have played some of The Witcher 3 launched through GOG Galaxy and it has worked for me just fine. I know the game only works with a real DS4 when connected via USB. The game will not detect a BT DS4 controller.

Does DS4Windows have exclusive access to the DS4? Especially if you are attempting DS4 emulation, you will probably want to make sure only the virtual DS4 is exposed to the game.

**Comment by mika-n** [comment]
If you use "Controller=dualshock4" profile option then Steam client may actively ignore DS4 gamepads if Steam detects certain background processes. DS4Windows.exe process name is jut one of those examples. See the following Troubleshooting tip for more into and workaround to this stupid Steam feature.

https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#steam-doesnt-see-the-virtual-output-controller-if-a-profile-uses-the-dualshock4-output-type-steam-sees-the-ds4-controller-only-if-ds4windows-uses-xbox360-output-controller-type

**Comment by Rabb1tof** [comment]
> 
> 
> If you use "Controller=dualshock4" profile option then Steam client may actively ignore DS4 gamepads if Steam detects certain background processes. DS4Windows.exe process name is jut one of those examples. See the following Troubleshooting tip for more into and workaround to this stupid Steam feature.
> 
> https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#steam-doesnt-see-the-virtual-output-controller-if-a-profile-uses-the-dualshock4-output-type-steam-sees-the-ds4-controller-only-if-ds4windows-uses-xbox360-output-controller-type

But trouble not only with Steam.

**Comment by mika-n** [comment]
@Rabb1tof   The original poster was rtan17 and his/her issue is probably because of exclusive mode or exclusive (=hideDS4Controller option) failed to work. The following web page tells more details.
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

@Rabb1tof  Please tell more about your exact case. Post a new topic if your issue is not about Witcher3 (which definitely requires either use of HideDS4Controller option or additional HidGuardian tool). See Troubleshooting page for general tips and what information to provide in problem descriptions.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting
