### ISSUE TITLE
Auto profile- Add Steam games: Not working

### ISSUE THREAD

**Issue by Tiberiusmoon** [Ryochan7/DS4Windows#985]
When i try to add steam games it wont load a game list.
I have tried to do this while running steam but it has not effect.
Clicking "add steam games" a second time cause the app to load start menu programs.

May i suggest and alternative location to read games that covers multiple publishers instead of just steam?
Using Geforce Experience files you can get directory information across multiple publishers.
This location shows what game files are detected Plus assets: C:\Users\*users*\AppData\Local\NVIDIA\NvBackend\VisualOPSData
In this file: C:\Users\*users*\AppData\Local\NVIDIA\NvBackend\journelBS.main.xml
You can find install directories of games detected by Geforce Experience written like this:
   <DetectedFile Type="4">D:\SteamLibrary\steamapps\common\Warframe\Warframe.x64.exe;D:\SteamLibrary\steamapps\common\Warframe\installscript.vdf</DetectedFile>

I know how to rummage through files but im no coder so i wonder if this is a better option.
If not, adding steam games in the auto profiler does not work for me. xD 
2.0.1 btw

**Comment by Ryochan7** [comment]
The loader assumes that your Steam app library will be on the C: drive. Games will be ignored if they are installed on a secondary partition. You would have to specify a custom directory using the "Use custom Steam Folder" option in the Settings tab. There are likely better ways to do this but that is the way it works now.

**Comment by Tiberiusmoon** [comment]
Ahh okay, thanks!
