### ISSUE TITLE
Can't assign actions when using touchpad as controls

### ISSUE THREAD

**Issue by Kamikazzi** [Ryochan7/DS4Windows#986]
I've been trying to get volume buttons assigned to my touchpad swipes, but unlike when i click to assign on gyro and the action window shows up, nothing comes up when i click to assign on touchpad swipes. I've restarted the program a few times and nothing changed. Can you tell me if there's something wrong with my instance or is this a bug? Following video for details. Thank you for your attention.

Video: https://streamable.com/qydmg

**Comment by Ryusennin** [comment]
It's probably a bug. It works in the last 1.7.x versions (I made a profile that way for The Witcher 3 to assign the Map key to the swipe up/down functions, like on PS4).

**Comment by Ryochan7** [comment]
I will have to look into that. Maybe it was just missed. Almost ended up forgetting to hook the Gyro Controls buttons until right before 2.0 was released.

**Comment by Ryochan7** [comment]
That was the case. I just forgot to add the hooks. The controls could have been selected by double click the Swipe Control items in the ListBox to the right.

**Comment by Kamikazzi** [comment]
I see. Thank you
