### ISSUE TITLE
Updater broke program

### ISSUE THREAD

**Issue by Keirathi** [Ryochan7/DS4Windows#991]
Opened DS4Windows a few minutes ago and it prompted me to download an update.  Once the update finished, the program just doesn't open at all.  Nothing in task manager or anything.

I backed up my profiles and downloaded a fresh version and everything seems fine again, so not exactly sure what happened and not a huge deal, but something with the update definitely went wonky for me.  Just throwing a heads up

**Comment by Ryochan7** [comment]
There is a notice about this problem. Essentially, the only safe update path was from version 1.7.28 to 2.0.x. A couple of long standing issues, that had a minor effect on previous updates, were found during the final migration to DS4Windows 2.0. Those issues pretty much made a clean update impossible. There was only about a one week delay between when the updater fix was released and when DS4Windows 2.0 was originally released.

https://github.com/Ryochan7/DS4Windows/issues/946

**Comment by Keirathi** [comment]
Ahhh okay, I didn't see that notice.  Thanks for the prompt reply!
