### ISSUE TITLE
Version 2.0.3 won't open

### ISSUE THREAD

**Issue by guillaumelamirand** [Ryochan7/DS4Windows#993]
Hi,

I updated my version with last one 2.0.3 (automaticaly done by DS4Updater.exe) but the new version won't open (even as admin), see log bellow :

```
2020-01-01 12:05:04.8562|INFO|DS4Windows version 2.0.3
2020-01-01 12:05:04.8562|INFO|Logger created
2020-01-01 12:05:04.8562|INFO|No config found. Creating default config
2020-01-01 12:05:04.8951|INFO|Default config created
2020-01-01 12:05:05.3957|ERROR|App Crashed with message Une erreur interne s’est produite. (Exception from HRESULT: 0x8007054F)
2020-01-01 12:05:05.3957|ERROR|System.Runtime.InteropServices.COMException (0x8007054F): Une erreur interne s’est produite. (Exception from HRESULT: 0x8007054F)
   at Microsoft.Win32.TaskScheduler.V2Interop.ITaskFolder.GetTasks(Int32 flags)
   at Microsoft.Win32.TaskScheduler.TaskFolder.GetTasks(Regex filter)
   at Microsoft.Win32.TaskScheduler.TaskService.FindTaskInFolder(TaskFolder fld, Regex taskName, List`1& results, Boolean recurse)
   at Microsoft.Win32.TaskScheduler.TaskService.FindAllTasks(Regex name, Boolean searchAllFolders)
   at Microsoft.Win32.TaskScheduler.TaskService.FindTask(String name, Boolean searchAllFolders)
   at DS4WinWPF.StartupMethods.HasTaskEntry()
   at DS4WinWPF.DS4Forms.ViewModels.SettingsViewModel..ctor()
   at DS4WinWPF.DS4Forms.MainWindow..ctor(ArgumentParser parser)
   at DS4WinWPF.App.Application_Startup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by Ryusennin** [comment]
I didn't try this version yet on Win10, but it works fine on Win7 (manual update).

**Comment by mika-n** [comment]
Here V2.0.3 works in Win10. Based on the log messages this was the first time you have run DS4Windows because the app created new fresh copies of configuration files (%APPDATA%\DS4Windows folder). 

Did the same crash happen the second time you run the app and do you see any config files in %APPDATA%\DS4Windows folder? If you don't see any config files in appdata folder or in programFolder (depends on which option you chose the first time you run ds4windows) then maybe there is a permission issue and the app fails to created config files in your PC? Try launching DS4Windows.exe in FileExplorer using "run as administrator" option.

**Comment by Ryusennin** [comment]
I keep forgetting that Microsoft discourages manual installations in the Program Files folder of Win10. Despite being admin of my machine and changing the access permissions, I couldn't install DS4Windows in that folder, so I ended up creating a "Program Files (Users)" directory specifically for that purpose. Works a treat.

**Comment by guillaumelamirand** [comment]
> Here V2.0.3 works in Win10. Based on the log messages this was the first time you have run DS4Windows because the app created new fresh copies of configuration files (%APPDATA%\DS4Windows folder).
> 
> Did the same crash happen the second time you run the app and do you see any config files in %APPDATA%\DS4Windows folder? If you don't see any config files in appdata folder or in programFolder (depends on which option you chose the first time you run ds4windows) then maybe there is a permission issue and the app fails to created config files in your PC? Try launching DS4Windows.exe in FileExplorer using "run as administrator" option.
> 
> Are you using a user profile with "normal user" permissions or "local computer administrator" permissions?

As said it was an automatic update that bring me to 2.0.3, I was using previous version without issues. I have tried a fresh install without success that why the log make you think it's my first launch. I can see file in %APPDATA%\DS4Windows actually it is where I found the log file. Also qs mentionned I did try in admin without success either.

My user is a local administrator.

> I keep forgetting that Microsoft discourages manual installations in the Program Files folder of Win10. Despite being admin of my machine and changing the access permissions, I couldn't install DS4Windows in that folder, so I ended up creating a "Program Files (Users)" directory specifically for that purpose. Works a treat.

I launch DSWindows from my home directory where I downloaded it, I tried to copy it somewhere else without any changes.

Thanks for your time.

**Comment by mika-n** [comment]
Hmm... The error comes from .NET internal class TaskService while DS4Windows app asks it to search for existing instance of "RunDS4Windows" TaskScheduler scheduled job.

Have you enabled "Run at startup" option in DS4Windows options? Do you have "DS4Windows.lnk" file in Startup folder (%PROGRAMMDATA%\Microsoft\Windows\Start Menu)? Try removing that link and remove "RunDS4Windows" taskSchdeduler job if you have it. And then run DS4Windows.exe manually (ie. not via TaskScheduler or StartMenu link).

**Comment by Ryochan7** [comment]
Is the Task Scheduler Windows service running? Unlike the 1.7.x releases, there is a check for the existence of the RunDS4Windows Task when DS4Windows is launched as a normal user. Checking for the existence of the task works fine for me as a normal user. Running as admin is required to edit the task and DS4Windows already takes that into account.

The COMException would make me think that the TaskScheduler library cannot access the service.

**Comment by guillaumelamirand** [comment]
When a run task scheduler I got a internal error, I guess the problem is there.

**Comment by guythnick** [comment]
I had the same issue after updating from 1.7.X.  I deleted the program folder and replaced the files with a fresh 2.03 release.  After this, the program ran as normal. 

I could be that just deleting the .config file would work, but I didn't try that.

**Comment by Dwedit** [comment]
I am having an issue getting 2.0.3 working.  When I launch it under the MSVC debugger, I see this error message: "'Could not load file or assembly 'System.Net.Http, Version=4.2.0.0", and I don't have that version, even after installing the newest .NET runtime from Microsoft.

**Comment by nmearl** [comment]
This latest version also does not launch for me either on Windows 10. I have to downgrade to the last 1.x release to get it working.

**Comment by Corrodias** [comment]
It wouldn't run for me on 10 after an automatic update to 2.0.3 from 1.7.x, due to this:

>  System.IO.FileNotFoundException
>    at DS4WinWPF.App.<CreateControlService>b__23_0()
>    at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
>    at System.Threading.ThreadHelper.ThreadStart()

A manual installation fixed it, but I kept the old installation. Looking at the difference between the two folders, the difference is that the automatically-updated one has no "libs" folder. Those are pretty important.

**Comment by guillaumelamirand** [comment]
> Is the Task Scheduler Windows service running? Unlike the 1.7.x releases, there is a check for the existence of the RunDS4Windows task when DS4Windows is launched as a normal user. Checking for the existence of the task works fine for me as a normal user. Running as admin is required to edit the task and DS4Windows already takes that into account.
> 
> The COMException would make me think that the TaskScheduler library cannot access the service.

I do a lot of clean up in my registry and folder related to TashSchedulers, and the service is running correctly now. This fix also the issue with DS4Windows. 

I am closing this issue because all other comment are not related to my original error.

Thanks for helping.
