### ISSUE TITLE
Shift functionality not intuitive

### ISSUE THREAD

**Issue by nr1995** [Ryochan7/DS4Windows#996]
This isn't a bug,
but just highlights a change that I think is sorely needed:
The UI for using the Shift Modifier function is very unintuitive.
I think it badly needs some clearer design language,
both for explaining itself when you're using it,
and for describing what you've done when you're finished.

**Comment by mika-n** [comment]
True. The GUI does show some legacy ballast here and there. The old V1.7.x version was a bit difficult to maintain in WinForms GUI side, so no one wanted to do there any major changes. Nowadays Ryochan7 did a massive job to re-build the GUI as WPF GUI, so nowadays it is a bit easier to modify layout without featuring to mess up everything (layout and performance). If you have any good ideas how to improve the re-map/keyboard/shiftmodifier layout then feel free to throw ideas.

Minimum thing someone should do would be to explain the re-map GUI in Settings wiki page (shift modifier is just one of the bolts and nuts there). Maybe someday.....
https://github.com/Ryochan7/DS4Windows/wiki
https://github.com/Ryochan7/DS4Windows/wiki/Settings
