### ISSUE TITLE
DS4 Doesn't connect controllers unless I select a profile for edit options

### ISSUE THREAD

**Issue by RailgunOrphen** [Ryochan7/DS4Windows#997]
Hi, every time I open DS4, the controllers that I connected on mi PC (via Bluetooth) are not being recognized by DS4 unless I click 'Edit' on the controller tab, but the moment I click on 'Save', the controller that was being configured gets disconnected, this doesn't happen if I click on 'close' at the upper right corner or if I click straight forward the controller tab. Also, sometimes, all my controllers are being assigned as input#1

**Comment by mika-n** [comment]
Hmmm.... Never seen this kind of behaviour.  Please go through the Trobleshooting doc page for more info about how to report more details (app version? Logs tab page content and log file? which gamepad?)
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting

And maybe even running a special debug version to generate even more detailed Logs tab page content.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

**Comment by RailgunOrphen** [comment]
Hi, Happy new year.

I followed the troubleshooting, but I keep getting this problem, I'll attach the log registry and the Profiles I have configured. I'm using DS4Windows 2.0.3, also, all of my controllers are Model CUH-ZCT2. Thanks for replying, Have a nice day.
[Log File.txt](https://github.com/Ryochan7/DS4Windows/files/4021510/Log.File.txt)
[Profiles Exports.zip](https://github.com/Ryochan7/DS4Windows/files/4021511/Profiles.Exports.zip)

**Comment by mika-n** [comment]
closed as "too weird issue and cannot replicate the issue to debug in more details".
